HoHDocs: scripts/Behaviors/Actors/Actor.as File Reference
Actor.as File Reference
Classes
class Actor
Functions
ActorCollection GetActorList (uint team)
uint GetActorListId (uint team)
vec2 FetchOffsetPos (UnitPtr unit, string offset)
Variables
Actor m_team
array< Actor@> m_arr
array< ActorCollection@> g_actors
int g_totalEnemies
int g_totalEnemiesTotal
int g_killedEnemies
int g_killedEnemiesTotal
uint g_team_none = HashString("")
uint g_team_player = HashString("player")
uint g_team_civilian = HashString("civilian")
Function Documentation
FetchOffsetPos()
vec2 FetchOffsetPos (UnitPtr unit, string offset)
Definition at line 132 of file Actor.as.
References unit, and xy().
Referenced by CompositeActorSkill::CalcAimDir(), CompositeActorSkill::HandleCastpoint(), CompositeActorSkill::NetUseSkill(), CompositeActorBurstSkill::Update(), WhirlNovaSkill::Update(), EnemyMeleeStrike::Update(), SpewSkill::Update(), and CompositeActorSkill::Update().
 {
     vec2 pos = xy(unit.GetPosition());
     if (offset != "")
         pos += unit.FetchLocator(offset);
     return pos;
 }
GetActorList()
ActorCollection GetActorList (uint team)
Definition at line 110 of file Actor.as.
References g_actors.
Referenced by Actor::SetTeam(), and TriggerOnDeath().
 {
     for (uint i = 0; i < g_actors.length(); i++)
     {
         auto coll = g_actors[i];
         if (coll.m_team == team)
             return coll;
     }
     return null;
 }
GetActorListId()
uint GetActorListId (uint team)
Definition at line 121 of file Actor.as.
References g_actors.
Referenced by CompositeActorBehavior().
 {
     for (uint i = 0; i < g_actors.length(); i++)
     {
         auto coll = g_actors[i];
         if (coll.m_team == team)
             return i + 1;
     }
     return 0;
 }
Variable Documentation
g_actors
array<ActorCollection@> g_actors
Definition at line 141 of file Actor.as.
Referenced by GetActorList(), GetActorListId(), and Actor::SetTeam().
g_killedEnemies
int g_killedEnemies
Definition at line 144 of file Actor.as.
Referenced by Destroyed().
g_killedEnemiesTotal
int g_killedEnemiesTotal
Definition at line 145 of file Actor.as.
g_team_civilian
uint g_team_civilian = HashString("civilian")
Definition at line 149 of file Actor.as.
g_team_none
uint g_team_none = HashString("")
Definition at line 147 of file Actor.as.
Referenced by ApplyAreaFilter(), and ApplyDamageFilter().
g_team_player
uint g_team_player = HashString("player")
Definition at line 148 of file Actor.as.
Referenced by ApplyAreaFilter(), ApplyDamageFilter(), KillAllCFunc(), ListEnemiesCFunc(), NetDamage(), TargetValue(), and SurvivalWaveProgress::Update().
g_totalEnemies
int g_totalEnemies
Definition at line 142 of file Actor.as.
Referenced by Actor::SetTeam().
g_totalEnemiesTotal
int g_totalEnemiesTotal
Definition at line 143 of file Actor.as.
m_arr
array<Actor@> m_arr
Definition at line 107 of file Actor.as.
m_team
Actor m_team