HoHDocs: scripts/Behaviors/Actors/ActorBuff.as File Reference
ActorBuff.as File Reference
Classes
class ActorColor
class ActorBuff
Functions
class ActorColor LoadColor (SValue &params, string prefix="")
ActorBuffDef LoadActorBuff (string path)
ActorBuffDef LoadActorBuff (uint pathHash)
Variables
vec4 m_dark
vec4 m_mid
vec4 m_bright
ActorBuff g_actorBuffDefs
Function Documentation
LoadActorBuff() [1/2]
ActorBuffDef LoadActorBuff (string path)
Definition at line 251 of file ActorBuff.as.
Referenced by ApplyBuff::ApplyBuff(), Modifiers::Aura::Aura(), Modifiers::Buff::Buff(), Skills::BuffAoe::BuffAoe(), CompositeActorAuraSkill::CompositeActorAuraSkill(), WorldScript::DamageUnits::Initialize(), DangerArea::Initialize(), PlayerHandler::ModifierTriggerEffect(), opCmp(), PlayerBase::PlayerBase(), PlayerBase::RefreshModifiers(), Skills::TempBuffAoe::TempBuffAoe(), UnitHandler::UnitBuffed(), and Modifiers::WarlockCleaverModifier::WarlockCleaverModifier().
 {
     if (path == "")
         return null;
     return LoadActorBuff(HashString(path));
 }
LoadActorBuff() [2/2]
ActorBuffDef LoadActorBuff (uint pathHash)
Definition at line 259 of file ActorBuff.as.
References ActorBuffDef(), buff, g_actorBuffDefs, and m_pathHash.
 {
     for (uint i = 0; i < g_actorBuffDefs.length(); i++)
         if (g_actorBuffDefs[i].m_pathHash == pathHash)
             return g_actorBuffDefs[i];
     SValue@ buff = Resources::GetSValue(pathHash);
     if (buff is null)
         return null;
     auto ret = ActorBuffDef(pathHash, buff);
     g_actorBuffDefs.insertLast(@ret);
     return ret;
 }
LoadColor()
class ActorColor LoadColor (SValue & params, string prefix = "")
Definition at line 9 of file ActorBuff.as.
References ActorColor::m_bright, ActorColor::m_dark, and ActorColor::m_mid.
Referenced by ActorBuffDef().
 {
     SValue@ colorData = params.GetDictionaryEntry(prefix + "colors");
     if (colorData is null)
         return null;
     ActorColor color;
     color.m_dark = vec4(0, 0, 0, 1);
     color.m_bright = vec4(1, 1, 1, 1);
     if (colorData.GetType() == SValueType::Array)
     {
         auto cArr = colorData.GetArray();
         color.m_dark = cArr[0].GetVector4();
         color.m_mid = cArr[1].GetVector4();
         color.m_bright = cArr[2].GetVector4();
     }
     else if (colorData.GetType() == SValueType::Vector4)
         color.m_mid = colorData.GetVector4();
     return color;
 }
Variable Documentation
g_actorBuffDefs
ActorBuff g_actorBuffDefs
Referenced by LoadActorBuff().
m_bright
vec4 m_bright
Definition at line 104 of file ActorBuff.as.
m_dark
vec4 m_dark
Definition at line 102 of file ActorBuff.as.
m_mid
vec4 m_mid
Definition at line 103 of file ActorBuff.as.