HoHDocs: scripts/GameModes/BaseGameMode.as File Reference
BaseGameMode.as File Reference
Classes
class BaseGameMode
Functions
void SetTileEffectsCvar (bool v)
void ListFlagsCFunc ()
void GiveAllDyesCFunc ()
void CvarExtraPlayers (int val)
void SetUIScaleCVar (float val)
float GetUIScale ()
void CvarDebugHandicap (bool value)
void CvarSmoothUI (bool value)
void CvarDebugWidgets (bool value)
void CvarInspectWidget (bool value)
void CvarPlayerNamesChanged (bool value)
void CvarHardwareCursor (bool value)
Variables
array< WorldScript::PrepareCamera@> g_prepareCameras
int g_prepareCameraIndex = -1
int g_doubleClickTime = -1
Function Documentation
CvarDebugHandicap()
void CvarDebugHandicap (bool value)
Definition at line 110 of file BaseGameMode.as.
References g_gameMode.
Referenced by BaseGameMode::BaseGameMode().
 {
     auto gm = cast<Campaign>(g_gameMode);
     if (gm !is null)
     {
         if (gm.m_hud !is null)
             gm.m_hud.m_wDebugHandicap.m_visible = value;
     }
 }
CvarDebugWidgets()
void CvarDebugWidgets (bool value)
Definition at line 125 of file BaseGameMode.as.
References g_debugWidgets.
Referenced by BaseGameMode::BaseGameMode().
 {
     g_debugWidgets = value;
 }
CvarExtraPlayers()
void CvarExtraPlayers (int val)
Definition at line 76 of file BaseGameMode.as.
References g_gameMode.
Referenced by BaseGameMode::BaseGameMode().
 {
     auto gm = cast<BaseGameMode>(g_gameMode);
     if (gm !is null)
         gm.RefreshMultiplayerScaling();
 }
CvarHardwareCursor()
void CvarHardwareCursor (bool value)
Definition at line 158 of file BaseGameMode.as.
References g_gameMode, Platform::HideCursor(), and Platform::ShowCursor().
Referenced by BaseGameMode::BaseGameMode().
 {
     auto gm = cast<BaseGameMode>(g_gameMode);
     if (gm.m_widgetRoots.length() == 0)
         return;
     if (value)
         Platform::ShowCursor();
     else
         Platform::HideCursor();
 }
CvarInspectWidget()
void CvarInspectWidget (bool value)
Definition at line 130 of file BaseGameMode.as.
References g_inspectWidget.
Referenced by BaseGameMode::BaseGameMode().
 {
     g_inspectWidget = value;
 }
CvarPlayerNamesChanged()
void CvarPlayerNamesChanged (bool value)
Definition at line 135 of file BaseGameMode.as.
References g_gameMode, and g_players.
Referenced by BaseGameMode::BaseGameMode().
 {
     for (uint i = 0; i < g_players.length(); i++)
     {
         auto husk = cast<PlayerHusk>(g_players[i].actor);
         if (husk !is null)
             @husk.m_textName = null;
     }
     auto gm = cast<Campaign>(g_gameMode);
     if (gm !is null && gm.m_hud !is null && gm.m_hud.m_waypoints !is null)
     {
         for (uint i = 0; i < gm.m_hud.m_waypoints.m_waypoints.length(); i++)
         {
             auto wp = cast<PlayerWaypoint>(gm.m_hud.m_waypoints.m_waypoints[i]);
             if (wp is null)
                 continue;
             wp.MakeNameText();
         }
     }
 }
CvarSmoothUI()
void CvarSmoothUI (bool value)
Definition at line 120 of file BaseGameMode.as.
References g_smoothOriginWidgets.
Referenced by BaseGameMode::BaseGameMode().
 {
     g_smoothOriginWidgets = value;
 }
GetUIScale()
float GetUIScale ()
Definition at line 91 of file BaseGameMode.as.
Referenced by Menu::DoLayout(), Menu::Draw(), MainMenu::RenderFrame(), BaseGameMode::RenderFrame(), Campaign::RenderWidgets(), and BaseGameMode::ResizeWindow().
 {
     float ret = GetVarFloat("ui_scale");
     if (ret < 0.05f)
         ret = 0.05f;
     if (ret > 100.0f)
         ret = 100.0f;
     return ret;
 }
GiveAllDyesCFunc()
void GiveAllDyesCFunc ()
Definition at line 47 of file BaseGameMode.as.
References Materials::g_dyes, g_gameMode, Materials::GetCategoryName(), TownRecord::GiveDye(), and TownRecord::OwnsDye().
Referenced by BaseGameMode::BaseGameMode().
 {
     TownRecord@ town = null;
     auto gmMenu = cast<MainMenu>(g_gameMode);
     auto gmCampaign = cast<Campaign>(g_gameMode);
     if (gmMenu !is null)
         @town = gmMenu.m_town;
     else if (gmCampaign !is null)
         @town = gmCampaign.m_townLocal;
     if (town is null)
     {
         PrintError("There is no town.");
         return;
     }
     for (uint i = 0; i < Materials::g_dyes.length(); i++)
     {
         auto dye = Materials::g_dyes[i];
         if (!town.OwnsDye(dye))
         {
             town.GiveDye(dye);
             print("Gave dye \"" + Resources::GetString(dye.m_name) + "\" in category \"" + Materials::GetCategoryName(dye.m_category));
         }
     }
 }
ListFlagsCFunc()
void ListFlagsCFunc ()
Definition at line 6 of file BaseGameMode.as.
References g_flags, HostTown, Level, Run, Town, and TownAll.
Referenced by BaseGameMode::BaseGameMode().
 {
     string level = ":";
     string run = ":";
     string town = ":";
     string host = ":";
     auto flagKeys = g_flags.m_flags.getKeys();
     for (uint i = 0; i < flagKeys.length(); i++)
     {
         int64 state;
         g_flags.m_flags.get(flagKeys[i], state);
         switch(FlagState(state))
         {
         case FlagState::Level:
             level = level + "  " + flagKeys[i];
             break;
         case FlagState::Run:
             run = run + "  " + flagKeys[i];
             break;
         case FlagState::Town:
             town = town + "  " + flagKeys[i];
             break;
         case FlagState::TownAll:
         case FlagState::HostTown:
             host = host + "  " + flagKeys[i];
             break;
         }
     }
     print("Level:");
     print(level);
     print("Run:");
     print(run);
     print("Town:");
     print(town);
     print("Host:");
     print(host);
 }
SetTileEffectsCvar()
void SetTileEffectsCvar (bool v)
Definition at line 1 of file BaseGameMode.as.
References CVars::UseTileEffects.
Referenced by BaseGameMode::BaseGameMode().
 {
     CVars::UseTileEffects = v;
 }
SetUIScaleCVar()
void SetUIScaleCVar (float val)
Definition at line 83 of file BaseGameMode.as.
References g_gameMode.
Referenced by BaseGameMode::BaseGameMode().
 {
     auto res = GetVarIvec2("v_resolution");
     auto gm = cast<BaseGameMode>(g_gameMode);
     if (gm !is null)
         gm.ResizeWindow(res.x, res.y, GetVarFloat("g_scale"));
 }
Variable Documentation
g_doubleClickTime
int g_doubleClickTime = -1
Definition at line 108 of file BaseGameMode.as.
Referenced by BaseGameMode::BaseGameMode(), and BaseGameMode::UpdateWidgets().
g_prepareCameraIndex
int g_prepareCameraIndex = -1
Definition at line 106 of file BaseGameMode.as.
Referenced by BaseGameMode::GetCameraPos().
g_prepareCameras
array<WorldScript::PrepareCamera@> g_prepareCameras
Definition at line 105 of file BaseGameMode.as.
Referenced by BaseGameMode::GetCameraPos(), and WorldScript::PrepareCamera::Initialize().