HoHDocs: scripts/Behaviors/Actions/SpawnUnit.as File Reference
SpawnUnit.as File Reference
Classes
class SpawnUnitEntry
Functions
SpawnUnit (UnitPtr unit, SValue &params)
bool NeedNetParams ()
void SetWeaponInformation (uint weapon)
bool DoAction (SValueBuilder@ builder, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity)
UnitPtr DoSpawnUnits (Actor@ owner, vec2 pos, vec2 dir, float intensity)
UnitPtr DoSpawnUnit (vec2 pos, vec2 dir, Actor@ owner, float intensity)
bool NetDoAction (SValue@ param, Actor@ owner, vec2 pos, vec2 dir)
bool Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
bool CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
void Update (int dt, int cooldown)
Variables
class SpawnUnitEntry IAction
class SpawnUnitEntry IEffect
class SpawnUnitEntry m_unitEntries
int m_spawnDist
bool m_safeSpawning
vec2 m_offset
bool m_rotateOffset
Function Documentation
Apply()
bool Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
Definition at line 130 of file SpawnUnit.as.
References DoSpawnUnits().
Referenced by ApplyEffects().
     {
         if (!husk)
             DoSpawnUnits(owner, pos, dir, intensity);
         return true;
     }
CanApply()
bool CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
Definition at line 137 of file SpawnUnit.as.
     {
         return true;
     }
DoAction()
bool DoAction (SValueBuilder@ builder, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity)
Definition at line 42 of file SpawnUnit.as.
References DoSpawnUnits().
     {
         DoSpawnUnits(owner, pos, dir, intensity);
         return true;
     }
DoSpawnUnit()
UnitPtr DoSpawnUnit (vec2 pos, vec2 dir, Actor@ owner, float intensity)
Definition at line 99 of file SpawnUnit.as.
References addrot(), SpawnUnitEntry::m_chance, m_offset, m_rotateOffset, m_unitEntries, SpawnUnitBase::SpawnUnit(), unit, SpawnUnitBase::UnitType, and UnitType.
Referenced by DoSpawnUnits().
     {
         if (m_rotateOffset)
             pos += addrot(m_offset, atan(dir.y, dir.x)) * length(m_offset);
         else
             pos += m_offset;
         auto prevUnitType = UnitType;
         int n = randi(1000);
         for (uint i = 0; i < m_unitEntries.length(); i++)
         {
             auto entry = m_unitEntries[i];
             n -= entry.m_chance;
             if (n < 0)
             {
                 @UnitType = entry.m_prod;
                 break;
             }
         }
         UnitPtr unit = SpawnUnit(pos, owner, intensity);
         @UnitType = prevUnitType;
         return unit;
     }
DoSpawnUnits()
UnitPtr DoSpawnUnits (Actor@ owner, vec2 pos, vec2 dir, float intensity)
Definition at line 48 of file SpawnUnit.as.
References SpawnUnitBase::CalcJitter(), distsq(), DoSpawnUnit(), g_scene, m_safeSpawning, m_spawnDist, and Actor::m_unit.
Referenced by Apply(), and DoAction().
     {
         auto origPos = pos;
         pos += CalcJitter();
         dir *= m_spawnDist;
         if (!m_safeSpawning)
             return DoSpawnUnit(pos + dir, dir, owner, intensity);
         else
         {
             if (m_spawnDist == 0)
             {
                 bool canSpawn = true;
                 if (distsq(origPos, pos) > 1.0f && g_scene.RaycastQuick(origPos, pos, ~0, RaycastType::Any))
                     canSpawn = false;
                 if (canSpawn)
                 {
                     auto res = g_scene.QueryRect(pos, 1, 1, ~0, RaycastType::Any);
                     for (uint i = 0; i < res.length; i++)
                     {
                         if (owner.m_unit != res[i])
{
                             canSpawn = false;
                             break;
                         }
                     }
                 }
                 if (canSpawn)
                     return DoSpawnUnit(pos, dir, owner, intensity);
             }
             else
             {
                 if (!g_scene.RaycastQuick(origPos, pos + dir, ~0, RaycastType::Any))
                     return DoSpawnUnit(pos + dir, dir, owner, intensity);
                 else if (!g_scene.RaycastQuick(origPos, vec2(pos.x, pos.y - m_spawnDist), ~0, RaycastType::Any))
                     return DoSpawnUnit(vec2(pos.x, pos.y - m_spawnDist), dir, owner, intensity);
                 else if (!g_scene.RaycastQuick(origPos, vec2(pos.x, pos.y + m_spawnDist), ~0, RaycastType::Any))
                     return DoSpawnUnit(vec2(pos.x, pos.y + m_spawnDist), dir, owner, intensity);
                 else if (!g_scene.RaycastQuick(origPos, vec2(pos.x - m_spawnDist, pos.y), ~0, RaycastType::Any))
                     return DoSpawnUnit(vec2(pos.x - m_spawnDist, pos.y), dir, owner, intensity);
                 else if (!g_scene.RaycastQuick(origPos, vec2(pos.x + m_spawnDist, pos.y), ~0, RaycastType::Any))
                     return DoSpawnUnit(vec2(pos.x + m_spawnDist, pos.y), dir, owner, intensity);
             }
         }
         return UnitPtr();
     }
NeedNetParams()
bool NeedNetParams ()
Definition at line 39 of file SpawnUnit.as.
 { return false; }
NetDoAction()
bool NetDoAction (SValue@ param, Actor@ owner, vec2 pos, vec2 dir)
Definition at line 125 of file SpawnUnit.as.
     {
         return true;
     }
SetWeaponInformation()
void SetWeaponInformation (uint weapon)
Definition at line 40 of file SpawnUnit.as.
 {}
SpawnUnit()
SpawnUnit (UnitPtr unit, SValue & params)
Definition at line 16 of file SpawnUnit.as.
References SpawnUnitBase::Initialize(), m_offset, m_rotateOffset, m_safeSpawning, m_spawnDist, m_unitEntries, and unit.
     {
         m_safeSpawning = GetParamBool(unit, params, "safe-spawn", false);
         m_spawnDist = GetParamInt(unit, params, "spawn-dist", false);
         m_offset = GetParamVec2(unit, params, "offset", false);
         if (m_offset.x != 0 || m_offset.y != 0)
             m_rotateOffset = GetParamBool(unit, params, "rotate-offset", false);
         array<SValue@>@ arr = GetParamArray(unit, params, "units", false);
         if (arr !is null)
         {
             for (uint i = 0; i < arr.length(); i += 2)
             {
                 auto entry = SpawnUnitEntry();
                 entry.m_chance = arr[i].GetInteger();
                 @entry.m_prod = Resources::GetUnitProducer(arr[i+1].GetString());
                 m_unitEntries.insertLast(entry);
             }
         }
         Initialize(unit, params);
     }
Update()
void Update (int dt, int cooldown)
Definition at line 142 of file SpawnUnit.as.
     {
     }
Variable Documentation
IAction
class SpawnUnitEntry IAction
Referenced by LoadAction().
IEffect
class SpawnUnitEntry IEffect
Referenced by LoadAction(), and LoadEffects().
m_offset
vec2 m_offset
Definition at line 13 of file SpawnUnit.as.
Referenced by DoSpawnUnit(), GetOffset(), SpawnUnit(), and BossBarWidget::UpdateAppearance().
m_rotateOffset
bool m_rotateOffset
Definition at line 14 of file SpawnUnit.as.
Referenced by DoSpawnUnit(), and SpawnUnit().
m_safeSpawning
bool m_safeSpawning
Definition at line 12 of file SpawnUnit.as.
Referenced by DoSpawnUnits(), and SpawnUnit().
m_spawnDist
int m_spawnDist
Definition at line 11 of file SpawnUnit.as.
Referenced by DoSpawnUnits(), and SpawnUnit().
m_unitEntries
class SpawnUnitEntry m_unitEntries
Referenced by DoSpawnUnit(), and SpawnUnit().