HoHDocs: scripts/GUI/HUD/BuffWidget.as File Reference
BuffWidget.as File Reference
Classes
class BuffWidget
Functions
int GetBuffIconDuration ()
int GetBuffIconMaxDuration ()
int GetBuffIconCount ()
BuffWidget Widget LoadBuffWidget (WidgetLoadingContext &ctx)
BuffWidget ()
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void AddedToParent () override
void Update (int dt) override
void DoDraw (SpriteBatch &sb, vec2 pos) override
Variables
IBuffWidgetInfo m_buff
TextWidget m_wStackText
Function Documentation
AddedToParent()
void LoadBuffWidget::AddedToParent () override
Definition at line 31 of file BuffWidget.as.
     {
BuffWidget()
LoadBuffWidget::BuffWidget ()
Definition at line 11 of file BuffWidget.as.
Referenced by LoadBuffWidget().
     {
Clone()
Widget LoadBuffWidget::Clone () override
Definition at line 16 of file BuffWidget.as.
     {
         super();
     }
     Widget@ Clone() override
     {
DoDraw()
void LoadBuffWidget::DoDraw (SpriteBatch & sb, vec2 pos) override
Definition at line 64 of file BuffWidget.as.
     {
         if (m_buff is null)
             return;
         auto icon = m_buff.GetBuffIcon();
         if (icon is null)
             return;
         sb.EnableColorize(vec4(0, 0, 0, 1), vec4(0.125, 0.125, 0.125, 1), vec4(0.25, 0.25, 0.25, 1));
         icon.Draw(sb, pos, g_menuTime, vec4(0.5, 0.5, 0.5, 1));
         sb.DisableColorize();
GetBuffIconCount()
int GetBuffIconCount () override
Definition at line 168 of file CooldownStackMeleeSwing.as.
References Skills::m_count, and Skills::m_destroyed.
         {
             if (m_destroyed)
                 return 0;
             if (m_count == 0)
                 return -1;
             return m_count;
         }
GetBuffIconDuration()
int GetBuffIconDuration () override
Definition at line 151 of file CooldownStackMeleeSwing.as.
References Skills::m_destroyed, Skills::m_timer, and Skills::m_timerC.
         {
             if (m_destroyed)
                 return 0;
             int ret = m_timer - m_timerC;
             if (ret <= 0)
                 return m_timer;
             return ret;
         }
GetBuffIconMaxDuration()
int GetBuffIconMaxDuration () override
Definition at line 163 of file CooldownStackMeleeSwing.as.
References Skills::m_timer.
         {
             return m_timer;
         }
Load()
void LoadBuffWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 23 of file BuffWidget.as.
     {
         Widget::Load(ctx);
LoadBuffWidget()
BuffWidget Widget LoadBuffWidget (WidgetLoadingContext & ctx)
Definition at line 86 of file BuffWidget.as.
References BuffWidget(), and BuffWidget::Load().
Referenced by BaseGameMode::BaseGameMode().
 {
     BuffWidget@ w = BuffWidget();
     w.Load(ctx);
     return w;
 }
Update()
void LoadBuffWidget::Update (int dt) override
Definition at line 36 of file BuffWidget.as.
References Widget::GetWidgetById(), and BuffWidget::m_wStackText.
     {
         @m_wStackText = cast<TextWidget>(GetWidgetById("stack-count"));
     }
     void Update(int dt) override
     {
         Widget::Update(dt);
         if (m_buff is null)
             return;
         if (m_buff.GetBuffIconDuration() <= 0)
         {
             RemoveFromParent();
             return;
         }
         int count = m_buff.GetBuffIconCount();
         if (count == 0)
         {
             RemoveFromParent();
             return;
         }
         else if (count != -1 && m_wStackText !is null)
         {
             m_wStackText.m_visible = true;
             m_wStackText.SetText("" + count);
Variable Documentation
m_buff
IBuffWidgetInfo m_buff
Definition at line 7 of file BuffWidget.as.
Referenced by DangerArea::ApplyDamage(), and DangerArea::Initialize().
m_wStackText
TextWidget m_wStackText
Definition at line 9 of file BuffWidget.as.