HoHDocs: scripts/GUI/Town/CardGame.as File Reference
CardGame.as File Reference
Classes
class CardGameSound
Functions
CardGame (SValue &sval)
void Initialize (bool loaded) override
string GetCardName (ivec2 card)
void DisableLimitButtons ()
void SetLimitButtons ()
void AnimateCardsOut ()
void HideStatus ()
void SetStatus (bool win)
void SetBattleStatus (ivec2 cardPlayer, ivec2 cardHouse)
void SetGoldStatus (int fromGold, int toGold)
vec4 GetCardFrame (ivec2 card)
ivec2 PullRandomCard ()
bool IsValidCardCombination (ivec2 house, ivec2 player)
void UnsetCard (string id)
void SetCard (string id, ivec2 card)
void LoseCash ()
void WinCash ()
void Play ()
void AddSound (SoundEvent@ snd, int delay)
bool ShouldFreezeControls () override
bool ShouldDisplayCursor () override
bool ShouldSaveExistance () override
void Update (int dt) override
void Stop () override
void OnFunc (Widget@ sender, string name) override
Variables
class CardGameSound m_wStatus
TextWidget m_wStatusBattle
Widget m_wSubStatus
TextWidget m_wGoldFrom
TextWidget m_wGoldTo
TextWidget m_wBarrel
ScalableSpriteButtonWidget m_wFlipButton
CheckBoxGroupWidget m_wLimits
Widget m_wLimit100
ScalableSpriteButtonWidget m_wLimit1m
Widget m_wDarkness
Widget m_wDarknessMove
SpriteWidget m_wDarknessMoveSprite
Sprite m_spriteDarknessSquare
Sprite m_spriteDarkness
TextWidget m_wDiff
SoundEvent m_sndLose
SoundEvent m_sndWin
SoundEvent m_sndFlip
SoundEvent m_sndSuspense
pint m_goldLimit = 100
ivec2 m_cardPlayer
ivec2 m_cardHouse
bool m_waitWin
int m_waitTime
bool m_cardsPlaced
int m_animateOutWaitTime
array< CardGameSound@> m_sounds
Function Documentation
AddSound()
void AddSound (SoundEvent@ snd, int delay)
Definition at line 437 of file CardGame.as.
References m_sounds.
Referenced by SetCard().
     {
         m_sounds.insertLast(CardGameSound(snd, delay));
     }
AnimateCardsOut()
void AnimateCardsOut ()
Definition at line 154 of file CardGame.as.
References HideStatus(), m_animateOutWaitTime, m_cardsPlaced, m_wDiff, and UnsetCard().
Referenced by Play().
     {
         HideStatus();
         m_wDiff.m_visible = false;
         UnsetCard("card-house");
         UnsetCard("card-player");
         m_cardsPlaced = false;
         m_animateOutWaitTime = 750;
     }
CardGame()
CardGame (SValue & sval)
Definition at line 56 of file CardGame.as.
     {
         super();
     }
DisableLimitButtons()
void DisableLimitButtons ()
Definition at line 110 of file CardGame.as.
References m_wLimits.
Referenced by Play().
     {
         for (uint i = 0; i < m_wLimits.m_children.length(); i++)
         {
             auto w = cast<ScalableSpriteButtonWidget>(m_wLimits.m_children[i]);
             w.m_enabled = false;
         }
     }
GetCardFrame()
vec4 GetCardFrame (ivec2 card)
Definition at line 207 of file CardGame.as.
Referenced by SetCard().
     {
         vec4 ret;
         ret.z = 45;
         ret.w = 68;
         ret.x = card.y * ret.z;
         ret.y = card.x * ret.w;
         return ret;
     }
GetCardName()
string GetCardName (ivec2 card)
Definition at line 102 of file CardGame.as.
Referenced by SetBattleStatus().
     {
         if (card.y == 10)
             return Resources::GetString(".gambling.card.wildcard");
         else
             return Resources::GetString(".gambling.card." + (card.x + 1) + "." + (card.y + 1));
     }
HideStatus()
void HideStatus ()
Definition at line 167 of file CardGame.as.
References Widget::m_visible, m_wBarrel, m_wStatus, m_wStatusBattle, and m_wSubStatus.
Referenced by AnimateCardsOut(), and Play().
     {
         m_wStatus.m_visible = false;
         m_wStatusBattle.m_visible = false;
         m_wSubStatus.m_visible = false;
         m_wBarrel.m_visible = false;
     }
Initialize()
void Initialize (bool loaded) override
Definition at line 61 of file CardGame.as.
References GetFaceSprite(), GetLocalPlayerRecord(), Widget::m_children, m_def, m_sndFlip, m_sndLose, m_sndSuspense, m_sndWin, m_spriteDarkness, m_spriteDarknessSquare, m_wBarrel, m_wDarkness, m_wDarknessMove, m_wDarknessMoveSprite, m_wDiff, m_wFlipButton, m_wGoldFrom, m_wGoldTo, m_widget, m_wLimit100, m_wLimit1m, m_wLimits, m_wStatus, m_wStatusBattle, m_wSubStatus, and SetLimitButtons().
     {
         @m_wStatus = cast<TextWidget>(m_widget.GetWidgetById("status"));
         @m_wStatusBattle = cast<TextWidget>(m_widget.GetWidgetById("status-battle"));
         @m_wSubStatus = m_widget.GetWidgetById("substatus");
         @m_wGoldFrom = cast<TextWidget>(m_widget.GetWidgetById("your-x"));
         @m_wGoldTo = cast<TextWidget>(m_widget.GetWidgetById("became-y"));
         @m_wBarrel = cast<TextWidget>(m_widget.GetWidgetById("barrel-win"));
         @m_wFlipButton = cast<ScalableSpriteButtonWidget>(m_widget.GetWidgetById("flip"));
         @m_wLimits = cast<CheckBoxGroupWidget>(m_widget.GetWidgetById("limits"));
         @m_wLimit100 = m_wLimits.GetWidgetById("bet-100");
         @m_wLimit1m = cast<ScalableSpriteButtonWidget>(m_wLimits.GetWidgetById("bet-1m"));
         @m_wDarkness = m_widget.GetWidgetById("darkness");
         @m_wDarknessMove = m_widget.GetWidgetById("darkness-move");
         @m_wDarknessMoveSprite = cast<SpriteWidget>(m_wDarknessMove.m_children[0]);
         @m_spriteDarknessSquare = m_def.GetSprite("darkness-square");
         @m_spriteDarkness = m_def.GetSprite("darkness");
         @m_wDiff = cast<TextWidget>(m_widget.GetWidgetById("diff"));
         @m_sndLose = Resources::GetSoundEvent("event:/ui/game-lose");
         @m_sndWin = Resources::GetSoundEvent("event:/ui/game-win");
         @m_sndFlip = Resources::GetSoundEvent("event:/ui/game-cardflip");
         @m_sndSuspense = Resources::GetSoundEvent("event:/ui/game-suspense");
         auto wPortrait = cast<SpriteWidget>(m_widget.GetWidgetById("portrait"));
         if (wPortrait !is null)
         {
             auto record = GetLocalPlayerRecord();
             wPortrait.SetSprite(GetFaceSprite(record.charClass, record.face));
             wPortrait.m_multiColors = record.GetMulticolors();
         }
         SetLimitButtons();
     }
IsValidCardCombination()
bool IsValidCardCombination (ivec2 house, ivec2 player)
Definition at line 237 of file CardGame.as.
Referenced by Play().
     {
         // Don't pull the same card
         if (house.x == player.x && house.y == player.y)
             return false;
         // Only pull 1 joker card
         if (house.y == 10 && player.y == 10)
             return false;
         return true;
     }
LoseCash()
void LoseCash ()
Definition at line 345 of file CardGame.as.
References Stats::Add(), g_gameMode, GetLocalPlayerRecord(), and m_goldLimit.
Referenced by Update().
     {
         auto gm = cast<Campaign>(g_gameMode);
         gm.m_townLocal.m_gold -= m_goldLimit;
         Stats::Add("gambling-gold-lost", m_goldLimit, GetLocalPlayerRecord());
     }
OnFunc()
void OnFunc (Widget@ sender, string name) override
Definition at line 506 of file CardGame.as.
References g_gameMode, m_goldLimit, name, Play(), and ScriptWidgetHost::Stop().
     {
         if (name == "close")
             Stop();
         else if (name == "set-limit")
         {
             auto group = cast<CheckBoxGroupWidget>(sender);
             int goldLimit = parseInt(group.GetChecked().GetValue());
             auto gm = cast<Campaign>(g_gameMode);
             if (goldLimit > gm.m_townLocal.m_gold)
             {
                 PrintError("Not enough gold!");
                 return;
             }
             m_goldLimit = goldLimit;
         }
         else if (name == "play")
             Play();
     }
Play()
void Play ()
Definition at line 374 of file CardGame.as.
References Widget::Animate(), AnimateCardsOut(), DisableLimitButtons(), HideStatus(), IsValidCardCombination(), m_cardHouse, m_cardPlayer, m_cardsPlaced, ScalableSpriteButtonWidget::m_enabled, m_goldLimit, m_sndFlip, m_sndSuspense, m_spriteDarknessSquare, m_waitTime, m_waitWin, m_wDarkness, m_wDarknessMoveSprite, m_wDiff, m_wFlipButton, PlaySound2D(), PullRandomCard(), SetCard(), TextWidget::SetColor(), SpriteWidget::SetSprite(), and TextWidget::SetText().
Referenced by OnFunc(), and Update().
     {
         m_wFlipButton.m_enabled = false;
         HideStatus();
         DisableLimitButtons();
         if (m_cardsPlaced)
         {
             AnimateCardsOut();
             return;
         }
         m_cardsPlaced = true;
         do
         {
             m_cardHouse = PullRandomCard();
             m_cardPlayer = PullRandomCard();
         } while (!IsValidCardCombination(m_cardHouse, m_cardPlayer));
         m_waitWin = (m_cardPlayer.y > m_cardHouse.y);
         if (m_goldLimit >= 1000000)
             m_waitTime = 5000;
         else
             m_waitTime = 750;
         SetCard("card-house", m_cardHouse);
         SetCard("card-player", m_cardPlayer);
         if (m_goldLimit >= 1000000)
         {
             m_wDarkness.Animate(WidgetBoolAnimation("visible", true, 500));
             m_wDarkness.Animate(WidgetBoolAnimation("visible", false, m_waitTime));
             m_wDarknessMoveSprite.SetSprite(m_spriteDarknessSquare);
             PlaySound2D(m_sndSuspense);
         }
         else
             PlaySound2D(m_sndFlip);
         if (m_cardHouse.y == 10 || m_cardPlayer.y == 10)
             m_wDiff.SetText("*");
         else
         {
             int diff = m_cardPlayer.y - m_cardHouse.y;
             if (diff == 0)
                 m_wDiff.SetText("-");
             else if (diff > 0)
                 m_wDiff.SetText("+" + diff);
             else
                 m_wDiff.SetText("" + diff);
         }
         if (m_waitWin)
             m_wDiff.SetColor(tocolor(vec4(0, 1, 0, 1)));
         else
             m_wDiff.SetColor(tocolor(vec4(1, 0, 0, 1)));
         m_wDiff.m_visible = false;
         m_wDiff.Animate(WidgetBoolAnimation("visible", true, m_waitTime));
     }
PullRandomCard()
ivec2 PullRandomCard ()
Definition at line 219 of file CardGame.as.
References CardGame100, CardGame1000, CardGame10000, CardGame100000, CardGame1000000, CardGame500, CardGame5000, Int(), and m_goldLimit.
Referenced by Play().
     {
         RandomContext randomContext = RandomContext::CardGame100;
         switch (int(m_goldLimit)) {
             case 100: randomContext = RandomContext::CardGame100; break;
             case 500: randomContext = RandomContext::CardGame500; break;
             case 1000: randomContext = RandomContext::CardGame1000; break;
             case 5000: randomContext = RandomContext::CardGame5000; break;
             case 10000: randomContext = RandomContext::CardGame10000; break;
             case 100000: randomContext = RandomContext::CardGame100000; break;
             case 1000000: randomContext = RandomContext::CardGame1000000; break;
         }
         int cardRow = RandomBank::Int(randomContext, 4);
         int cardNum = RandomBank::Int(randomContext, 11);
         return ivec2(cardRow, cardNum);
     }
SetBattleStatus()
void SetBattleStatus (ivec2 cardPlayer, ivec2 cardHouse)
Definition at line 190 of file CardGame.as.
References GetCardName(), m_wStatusBattle, and TextWidget::SetText().
Referenced by Update().
     {
         string namePlayer = GetCardName(cardPlayer);
         string nameHouse = GetCardName(cardHouse);
         m_wStatusBattle.SetText(Resources::GetString(".town.cardgame.battlestatus", { { "player", namePlayer }, { "house", nameHouse } }));
         m_wStatusBattle.m_visible = true;
     }
SetCard()
void SetCard (string id, ivec2 card)
Definition at line 269 of file CardGame.as.
References AddSound(), Widget::Animate(), GetCardFrame(), lerp(), m_goldLimit, m_sndFlip, m_spriteDarkness, m_spriteDarknessSquare, m_wDarknessMove, m_wDarknessMoveSprite, m_widget, ScriptSprite(), WidgetSpriteAnimation(), and WidgetVec2BezierAnimation().
Referenced by Play().
     {
         auto wCard = cast<SpriteWidget>(m_widget.GetWidgetById(id));
         if (wCard is null)
         {
             PrintError("Invalid widget ID: " + id);
             return;
         }
         if (card.y == 10)
             wCard.SetSprite("card-joker");
         else
         {
             auto texture = Resources::GetTexture2D("gui/cards.png");
             auto frame = GetCardFrame(card);
             wCard.SetSprite(ScriptSprite(texture, frame));
         }
         int animTime = 650;
         int animDelay = 0;
         if (id != "card-player")
             animDelay = 100;
         bool moveSpotlight = false;
         if (m_goldLimit >= 1000000)
         {
             moveSpotlight = true;
             if (id == "card-player")
                 animDelay = 4000;
             else
                 animDelay = 2000;
             AddSound(m_sndFlip, animDelay);
         }
         wCard.Animate(WidgetBoolAnimation("visible", true, animTime + animDelay));
         auto wDeck = m_widget.GetWidgetById(id + "-deck");
         auto wCardAnimator = m_widget.GetWidgetById(id + "-animator");
         auto wCardAnimatorShadow = m_widget.GetWidgetById(id + "-animator-shadow");
         if (animDelay > 0)
         {
             wCardAnimator.Animate(WidgetBoolAnimation("visible", true, animDelay));
             wCardAnimatorShadow.Animate(WidgetBoolAnimation("visible", true, animDelay));
         }
         else
         {
             wCardAnimator.m_visible = true;
             wCardAnimatorShadow.m_visible = true;
         }
         vec2 startPos = wDeck.m_offset;
         vec2 endPos = wCard.m_offset;
         vec2 bezierPos = lerp(startPos, endPos, 0.5f) + vec2(0, -50);
         wCardAnimator.Animate(WidgetVec2BezierAnimation("offset", startPos, bezierPos, endPos, animTime, animDelay));
         wCardAnimator.Animate(WidgetBoolAnimation("visible", false, animTime + animDelay));
         vec2 shadowBezierPos = lerp(startPos, endPos, 0.5f) + vec2(20, -55);
         wCardAnimatorShadow.Animate(WidgetVec2BezierAnimation("offset", startPos, shadowBezierPos, endPos, animTime, animDelay));
         wCardAnimatorShadow.Animate(WidgetBoolAnimation("visible", false, animTime + animDelay));
         if (moveSpotlight)
         {
             vec2 spotlightOffset = vec2(-64 + 22, -64 + 33);
             m_wDarknessMove.Animate(WidgetVec2BezierAnimation("offset", startPos + spotlightOffset, bezierPos + spotlightOffset, endPos + spotlightOffset, animTime, animDelay));
             m_wDarknessMoveSprite.Animate(WidgetSpriteAnimation("sprite", m_spriteDarkness, animDelay));
             m_wDarknessMoveSprite.Animate(WidgetSpriteAnimation("sprite", m_spriteDarknessSquare, animDelay + animTime + 500));
         }
     }
SetGoldStatus()
void SetGoldStatus (int fromGold, int toGold)
Definition at line 199 of file CardGame.as.
References formatThousands(), Widget::m_visible, m_wGoldFrom, m_wGoldTo, m_wSubStatus, and TextWidget::SetText().
Referenced by Update().
     {
         m_wGoldFrom.SetText(Resources::GetString(".town.cardgame.goldfrom", { { "num", formatThousands(fromGold) } }));
         m_wGoldTo.SetText(Resources::GetString(".town.cardgame.goldto", { { "num", formatThousands(toGold) } }));
         m_wSubStatus.m_visible = true;
     }
SetLimitButtons()
void SetLimitButtons ()
Definition at line 119 of file CardGame.as.
References g_gameMode, m_goldLimit, Widget::m_visible, m_wLimit100, m_wLimit1m, m_wLimits, min, CheckBoxGroupWidget::SetChecked(), and AGameMode::ShowDialog().
Referenced by Initialize(), and Update().
     {
         auto gm = cast<Campaign>(g_gameMode);
         int leastValue = 0;
         for (uint i = 0; i < m_wLimits.m_children.length(); i++)
         {
             auto w = cast<ScalableSpriteButtonWidget>(m_wLimits.m_children[i]);
             int value = parseInt(w.m_value);
             w.m_enabled = (gm.m_townLocal.m_gold >= value);
             if (w.m_enabled)
                 leastValue = value;
         }
         if (leastValue == 0)
             g_gameMode.ShowDialog("close", Resources::GetString(".town.cardgame.outofmoney." + (randi(5) + 1)), Resources::GetString(".menu.ok"), this);
         else
         {
             m_goldLimit = min(m_goldLimit, leastValue);
             m_wLimits.SetChecked("" + m_goldLimit);
         }
         if (gm.m_townLocal.m_gold >= 1000000)
         {
             m_wLimit100.m_visible = false;
             m_wLimit1m.m_visible = true;
         }
         else
         {
             m_wLimit100.m_visible = true;
             m_wLimit1m.m_visible = false;
         }
     }
SetStatus()
void SetStatus (bool win)
Definition at line 175 of file CardGame.as.
References m_wStatus.
Referenced by Update().
     {
         if (win)
         {
             m_wStatus.SetText(Resources::GetString(".town.cardgame.header.win"));
             m_wStatus.SetColor(tocolor(vec4(0, 1, 0, 1)));
         }
         else
         {
             m_wStatus.SetText(Resources::GetString(".town.cardgame.header.lose"));
             m_wStatus.SetColor(tocolor(vec4(1, 0, 0, 1)));
         }
         m_wStatus.m_visible = true;
     }
ShouldDisplayCursor()
bool ShouldDisplayCursor () override
Definition at line 443 of file CardGame.as.
 { return true; }
ShouldFreezeControls()
bool ShouldFreezeControls () override
Definition at line 442 of file CardGame.as.
 { return true; }
ShouldSaveExistance()
bool ShouldSaveExistance () override
Definition at line 444 of file CardGame.as.
 { return false; }
Stop()
void Stop () override
Definition at line 498 of file CardGame.as.
References m_waitTime, and ScriptWidgetHost::Stop().
     {
         if (m_waitTime > 0)
             return;
         ScriptWidgetHost::Stop();
     }
UnsetCard()
void UnsetCard (string id)
Definition at line 250 of file CardGame.as.
References m_widget.
Referenced by AnimateCardsOut().
     {
         auto wPlacedCard = m_widget.GetWidgetById(id);
         wPlacedCard.m_visible = false;
         auto wDeck = m_widget.GetWidgetById(id + "-deck");
         auto wCardAnimator = m_widget.GetWidgetById(id + "-animator-behind");
         wCardAnimator.m_visible = true;
         vec2 startPos = wPlacedCard.m_offset;
         vec2 endPos = wDeck.m_offset;
         endPos.y = startPos.y;
         wCardAnimator.Animate(WidgetVec2Animation("offset", startPos, endPos, 500));
         wCardAnimator.Animate(WidgetBoolAnimation("visible", false, 500));
     }
Update()
void Update (int dt) override
Definition at line 446 of file CardGame.as.
References LoseCash(), m_animateOutWaitTime, m_cardHouse, m_cardPlayer, ScalableSpriteButtonWidget::m_enabled, m_goldLimit, m_sndLose, m_sndWin, m_sounds, m_waitTime, m_waitWin, m_wFlipButton, Play(), PlaySound2D(), SetBattleStatus(), SetGoldStatus(), SetLimitButtons(), SetStatus(), and WinCash().
     {
         for (int i = int(m_sounds.length()) - 1; i >= 0; i--)
         {
             auto snd = m_sounds[i];
             snd.m_delay -= dt;
             if (snd.m_delay <= 0)
             {
                 PlaySound2D(snd.m_snd);
                 m_sounds.removeAt(i);
             }
         }
         if (m_waitTime > 0)
         {
             m_waitTime -= dt;
             if (m_waitTime <= 0)
             {
                 SetStatus(m_waitWin);
                 SetBattleStatus(m_cardPlayer, m_cardHouse);
                 if (m_waitWin)
                 {
                     PlaySound2D(m_sndWin);
                     SetGoldStatus(m_goldLimit, m_goldLimit * 2);
                     WinCash();
                 }
                 else
                 {
                     PlaySound2D(m_sndLose);
                     SetGoldStatus(m_goldLimit, 0);
                     LoseCash();
                 }
                 m_wFlipButton.m_enabled = true;
                 SetLimitButtons();
                 m_waitWin = false;
             }
         }
         if (m_animateOutWaitTime > 0)
         {
             m_animateOutWaitTime -= dt;
             if (m_animateOutWaitTime <= 0)
                 Play();
         }
         ScriptWidgetHost::Update(dt);
     }
WinCash()
void WinCash ()
Definition at line 353 of file CardGame.as.
References Stats::Add(), g_gameMode, GetItemQualityColorString(), GetLocalPlayer(), GetLocalPlayerRecord(), GetTavernDrink(), GiveTavernBarrelImpl(), m_goldLimit, m_wBarrel, quality, and TextWidget::SetText().
Referenced by Update().
     {
         auto gm = cast<Campaign>(g_gameMode);
         gm.m_townLocal.m_gold += m_goldLimit;
         Stats::Add("gambling-gold-won", m_goldLimit, GetLocalPlayerRecord());
         if (m_goldLimit >= 1000000)
         {
             ActorItemQuality quality = ActorItemQuality(randi(3) + 1);
             auto randomDrink = GetTavernDrink(quality);
             if (randomDrink !is null)
                 GiveTavernBarrelImpl(randomDrink, GetLocalPlayer(), true);
             m_wBarrel.m_visible = true;
             m_wBarrel.SetText(Resources::GetString(".town.cardgame.barrel", {
                 { "drink", "\\c" + GetItemQualityColorString(randomDrink.quality) + Resources::GetString(randomDrink.name) + "\\d" }
             }), false);
         }
     }
Variable Documentation
m_animateOutWaitTime
int m_animateOutWaitTime
Definition at line 52 of file CardGame.as.
Referenced by AnimateCardsOut(), and Update().
m_cardHouse
ivec2 m_cardHouse
Definition at line 46 of file CardGame.as.
Referenced by Play(), and Update().
m_cardPlayer
ivec2 m_cardPlayer
Definition at line 45 of file CardGame.as.
Referenced by Play(), and Update().
m_cardsPlaced
bool m_cardsPlaced
Definition at line 51 of file CardGame.as.
Referenced by AnimateCardsOut(), and Play().
m_goldLimit
pint m_goldLimit = 100
Definition at line 43 of file CardGame.as.
Referenced by LoseCash(), OnFunc(), Play(), PullRandomCard(), SetCard(), SetLimitButtons(), Update(), and WinCash().
m_sndFlip
SoundEvent m_sndFlip
Definition at line 40 of file CardGame.as.
Referenced by Initialize(), Play(), and SetCard().
m_sndLose
SoundEvent m_sndLose
Definition at line 38 of file CardGame.as.
Referenced by Initialize(), and Update().
m_sndSuspense
SoundEvent m_sndSuspense
Definition at line 41 of file CardGame.as.
Referenced by Initialize(), and Play().
m_sndWin
SoundEvent m_sndWin
Definition at line 39 of file CardGame.as.
Referenced by Initialize(), and Update().
m_sounds
array<CardGameSound@> m_sounds
Definition at line 54 of file CardGame.as.
Referenced by AddSound(), and Update().
m_spriteDarkness
Sprite m_spriteDarkness
Definition at line 34 of file CardGame.as.
Referenced by Initialize(), and SetCard().
m_spriteDarknessSquare
Sprite m_spriteDarknessSquare
Definition at line 33 of file CardGame.as.
Referenced by Initialize(), Play(), and SetCard().
m_waitTime
int m_waitTime
Definition at line 49 of file CardGame.as.
Referenced by Play(), Stop(), and Update().
m_waitWin
bool m_waitWin
Definition at line 48 of file CardGame.as.
Referenced by Play(), and Update().
m_wBarrel
TextWidget m_wBarrel
Definition at line 21 of file CardGame.as.
Referenced by HideStatus(), Initialize(), and WinCash().
m_wDarkness
Widget m_wDarkness
Definition at line 29 of file CardGame.as.
Referenced by Initialize(), and Play().
m_wDarknessMove
Widget m_wDarknessMove
Definition at line 30 of file CardGame.as.
Referenced by Initialize(), and SetCard().
m_wDarknessMoveSprite
SpriteWidget m_wDarknessMoveSprite
Definition at line 31 of file CardGame.as.
Referenced by Initialize(), Play(), and SetCard().
m_wDiff
TextWidget m_wDiff
Definition at line 36 of file CardGame.as.
Referenced by AnimateCardsOut(), Initialize(), and Play().
m_wFlipButton
ScalableSpriteButtonWidget m_wFlipButton
Definition at line 23 of file CardGame.as.
Referenced by Initialize(), Play(), and Update().
m_wGoldFrom
TextWidget m_wGoldFrom
Definition at line 19 of file CardGame.as.
Referenced by Initialize(), and SetGoldStatus().
m_wGoldTo
TextWidget m_wGoldTo
Definition at line 20 of file CardGame.as.
Referenced by Initialize(), and SetGoldStatus().
m_wLimit100
Widget m_wLimit100
Definition at line 26 of file CardGame.as.
Referenced by Initialize(), and SetLimitButtons().
m_wLimit1m
ScalableSpriteButtonWidget m_wLimit1m
Definition at line 27 of file CardGame.as.
Referenced by Initialize(), and SetLimitButtons().
m_wLimits
CheckBoxGroupWidget m_wLimits
Definition at line 25 of file CardGame.as.
Referenced by DisableLimitButtons(), Initialize(), and SetLimitButtons().
m_wStatus
class CardGameSound m_wStatus
Referenced by HideStatus(), Initialize(), and SetStatus().
m_wStatusBattle
TextWidget m_wStatusBattle
Definition at line 17 of file CardGame.as.
Referenced by HideStatus(), Initialize(), and SetBattleStatus().
m_wSubStatus
Widget m_wSubStatus
Definition at line 18 of file CardGame.as.
Referenced by HideStatus(), Initialize(), and SetGoldStatus().