HoHDocs: scripts/GUI/CheckBox.as File Reference
CheckBox.as File Reference
Classes
class CheckBoxWidget
Functions
CheckBoxWidget ICheckableWidget, Widget LoadCheckboxWidget (WidgetLoadingContext &ctx)
CheckBoxWidget ()
string GetValue ()
bool IsChecked ()
void SetCheckable ()
void SetChecked (bool b)
void SetGroupWidget (CheckBoxGroupWidget@ group)
bool IsEnabled ()
Widget Clone () override
void Reset ()
void Cancel ()
void Save ()
bool IsChanged ()
void Load (WidgetLoadingContext &ctx) override
void SetText (string str)
void SetColor (vec4 color)
bool OnClick (vec2 mousePos) override
bool OnDoubleClick (vec2 mousePos) override
void OnMouseEnter (vec2 mousePos, bool forced) override
void DoDraw (SpriteBatch &sb, vec2 pos) override
Variables
CheckBoxGroupWidget m_checkBoxGroup
SpriteRect m_spriteRect
Sprite m_spriteUnchecked
Sprite m_spriteHover
Sprite m_spriteChecked
Sprite m_spriteDisabled
bool m_enabled
bool m_disabledTooltip
BitmapFont m_font
BitmapString m_text
string m_str = ""
vec4 m_color = vec4(1, 1, 1, 1)
string m_value
string m_func
string m_cvar
bool m_cvarOrig
bool m_checked
SoundEvent m_pressSound
SoundEvent m_selectSound
int m_contentWidth
int m_contentHeight
Function Documentation
Cancel()
void LoadCheckboxWidget::Cancel ()
Definition at line 341 of file CheckBox.as.
CheckBoxWidget()
LoadCheckboxWidget::CheckBoxWidget ()
Definition at line 312 of file CheckBox.as.
Referenced by LoadCheckboxWidget().
Clone()
Widget LoadCheckboxWidget::Clone () override
Definition at line 324 of file CheckBox.as.
DoDraw()
void LoadCheckboxWidget::DoDraw (SpriteBatch & sb, vec2 pos) override
Definition at line 487 of file CheckBox.as.
GetValue()
string LoadCheckboxWidget::GetValue ()
Definition at line 317 of file CheckBox.as.
IsChanged()
bool LoadCheckboxWidget::IsChanged ()
Definition at line 356 of file CheckBox.as.
IsChecked()
bool LoadCheckboxWidget::IsChecked ()
Definition at line 318 of file CheckBox.as.
Referenced by FountainShopMenuContent::AnyEffectSelected().
IsEnabled()
bool LoadCheckboxWidget::IsEnabled ()
Definition at line 322 of file CheckBox.as.
Load()
void LoadCheckboxWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 361 of file CheckBox.as.
LoadCheckboxWidget()
CheckBoxWidget ICheckableWidget, Widget LoadCheckboxWidget (WidgetLoadingContext & ctx)
Definition at line 260 of file CheckBox.as.
References CheckBoxWidget(), and CheckBoxWidget::Load().
Referenced by BaseGameMode::BaseGameMode().
 {
     CheckBoxWidget@ w = CheckBoxWidget();
     w.Load(ctx);
     return w;
 }
OnClick()
bool LoadCheckboxWidget::OnClick (vec2 mousePos) override
Definition at line 447 of file CheckBox.as.
OnDoubleClick()
bool LoadCheckboxWidget::OnDoubleClick (vec2 mousePos) override
Definition at line 465 of file CheckBox.as.
OnMouseEnter()
void LoadCheckboxWidget::OnMouseEnter (vec2 mousePos, bool forced) override
Definition at line 478 of file CheckBox.as.
Reset()
void LoadCheckboxWidget::Reset ()
Definition at line 331 of file CheckBox.as.
Save()
void LoadCheckboxWidget::Save ()
Definition at line 350 of file CheckBox.as.
SetCheckable()
void LoadCheckboxWidget::SetCheckable ()
Definition at line 319 of file CheckBox.as.
SetChecked()
void LoadCheckboxWidget::SetChecked (bool b)
Definition at line 320 of file CheckBox.as.
SetColor()
void LoadCheckboxWidget::SetColor (vec4 color)
Definition at line 440 of file CheckBox.as.
SetGroupWidget()
void LoadCheckboxWidget::SetGroupWidget (CheckBoxGroupWidget@ group)
Definition at line 321 of file CheckBox.as.
SetText()
void LoadCheckboxWidget::SetText (string str)
Definition at line 423 of file CheckBox.as.
Variable Documentation
m_checkBoxGroup
CheckBoxGroupWidget m_checkBoxGroup
Definition at line 282 of file CheckBox.as.
m_checked
bool m_checked
Definition at line 304 of file CheckBox.as.
m_color
vec4 m_color = vec4(1, 1, 1, 1)
Definition at line 297 of file CheckBox.as.
m_contentHeight
int m_contentHeight
Definition at line 310 of file CheckBox.as.
m_contentWidth
int m_contentWidth
Definition at line 309 of file CheckBox.as.
m_cvar
string m_cvar
Definition at line 301 of file CheckBox.as.
m_cvarOrig
bool m_cvarOrig
Definition at line 302 of file CheckBox.as.
m_disabledTooltip
bool m_disabledTooltip
Definition at line 291 of file CheckBox.as.
m_enabled
bool m_enabled
Definition at line 290 of file CheckBox.as.
m_font
BitmapFont m_font
Definition at line 293 of file CheckBox.as.
m_func
string m_func
Definition at line 300 of file CheckBox.as.
m_pressSound
SoundEvent m_pressSound
Definition at line 306 of file CheckBox.as.
m_selectSound
SoundEvent m_selectSound
Definition at line 307 of file CheckBox.as.
m_spriteChecked
Sprite m_spriteChecked
Definition at line 287 of file CheckBox.as.
m_spriteDisabled
Sprite m_spriteDisabled
Definition at line 288 of file CheckBox.as.
m_spriteHover
Sprite m_spriteHover
Definition at line 286 of file CheckBox.as.
m_spriteRect
SpriteRect m_spriteRect
Definition at line 284 of file CheckBox.as.
m_spriteUnchecked
Sprite m_spriteUnchecked
Definition at line 285 of file CheckBox.as.
m_str
string m_str = ""
Definition at line 296 of file CheckBox.as.
m_text
BitmapString m_text
Definition at line 294 of file CheckBox.as.
m_value
string m_value
Definition at line 299 of file CheckBox.as.
Referenced by Stats::Accomplishment::GetDescription(), and Stats::Accomplishment::IsValueGood().