HoHDocs: scripts/GUI/ClipWidget.as File Reference
ClipWidget.as File Reference
Classes
class ClipWidget
Functions
ClipWidget Widget LoadClipWidget (WidgetLoadingContext &ctx)
ClipWidget ()
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void Draw (SpriteBatch &sb, bool debugDraw=false) override
void DrawChildren (SpriteBatch &sb, bool debugDraw=false) override
Variables
bool m_clipping = true
vec4 m_clipPadding
Function Documentation
ClipWidget()
LoadClipWidget::ClipWidget ()
Definition at line 299 of file ClipWidget.as.
Referenced by LoadClipWidget().
Clone()
Widget LoadClipWidget::Clone () override
Definition at line 304 of file ClipWidget.as.
Draw()
void LoadClipWidget::Draw (SpriteBatch & sb, bool debugDraw = false) override
Definition at line 321 of file ClipWidget.as.
DrawChildren()
void LoadClipWidget::DrawChildren (SpriteBatch & sb, bool debugDraw = false) override
Definition at line 339 of file ClipWidget.as.
Load()
void LoadClipWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 311 of file ClipWidget.as.
LoadClipWidget()
ClipWidget Widget LoadClipWidget (WidgetLoadingContext & ctx)
Definition at line 68 of file ClipWidget.as.
References ClipWidget(), and ClipWidget::Load().
Referenced by BaseGameMode::BaseGameMode().
 {
     ClipWidget@ w = ClipWidget();
     w.Load(ctx);
     return w;
 }
Variable Documentation
m_clipPadding
vec4 m_clipPadding
Definition at line 297 of file ClipWidget.as.
m_clipping
bool m_clipping = true
Definition at line 296 of file ClipWidget.as.