HoHDocs: scripts/GUI/ColorButtonWidget.as File Reference
ColorButtonWidget.as File Reference
Classes
class ColorButtonWidget
Functions
ColorButtonWidget SpriteButtonWidget LoadColorButtonWidget (WidgetLoadingContext &ctx)
ColorButtonWidget ()
Widget Clone () override
Sprite GetCurrentSprite () override
void Load (WidgetLoadingContext &ctx) override
void DoDraw (SpriteBatch &sb, vec2 pos) override
Variables
array< vec4 > m_shades
bool m_selected
Function Documentation
Clone()
Widget LoadColorButtonWidget::Clone () override
Definition at line 348 of file ColorButtonWidget.as.
ColorButtonWidget()
LoadColorButtonWidget::ColorButtonWidget ()
Definition at line 343 of file ColorButtonWidget.as.
Referenced by LoadColorButtonWidget().
DoDraw()
void LoadColorButtonWidget::DoDraw (SpriteBatch & sb, vec2 pos) override
Definition at line 368 of file ColorButtonWidget.as.
GetCurrentSprite()
Sprite LoadColorButtonWidget::GetCurrentSprite () override
Definition at line 355 of file ColorButtonWidget.as.
Load()
void LoadColorButtonWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 363 of file ColorButtonWidget.as.
LoadColorButtonWidget()
ColorButtonWidget SpriteButtonWidget LoadColorButtonWidget (WidgetLoadingContext & ctx)
Definition at line 46 of file ColorButtonWidget.as.
References ColorButtonWidget(), and ColorButtonWidget::Load().
Referenced by BaseGameMode::BaseGameMode().
 {
     ColorButtonWidget@ w = ColorButtonWidget();
     w.Load(ctx);
     return w;
 }
Variable Documentation
m_selected
bool m_selected
Definition at line 341 of file ColorButtonWidget.as.
m_shades
array<vec4> m_shades
Definition at line 340 of file ColorButtonWidget.as.