HoHDocs: scripts/GUI/LevelEnd/CounterWidget.as File Reference
CounterWidget.as File Reference
Enumerations
enum CounterFormat { Normal = 2, Time, TimeFractions }
Functions
CounterWidget (BitmapFont@ font)
void Load (WidgetLoadingContext &ctx) override
void Update (int dt) override
void UpdateText ()
void SetCounter (float start, float end)
void SetCount (float count, bool instant=false)
ref LoadCounterWidget (WidgetLoadingContext &ctx)
Variables
enum CounterFormat m_currentCount
float m_currentFinish
int m_countInterval
int m_countIntervalC
float m_step
string m_strBefore
string m_strAfter
CounterFormat m_format
Enumeration Type Documentation
CounterFormat
enum CounterFormat
Enumerator
Normal
Time
TimeFractions
Definition at line 1 of file CounterWidget.as.
 {
     Normal,
     Time,
     TimeFractions
 }
Function Documentation
CounterWidget()
CounterWidget (BitmapFont@ font)
Definition at line 23 of file CounterWidget.as.
References m_font.
Referenced by LoadCounterWidget().
     {
         super();
         @m_font = font;
     }
Load()
void Load (WidgetLoadingContext & ctx) override
Definition at line 29 of file CounterWidget.as.
References Widget::Load(), m_countInterval, m_countIntervalC, m_currentCount, m_currentFinish, m_format, m_step, m_strAfter, m_strBefore, Time, TimeFractions, and UpdateText().
     {
         m_currentCount = ctx.GetFloat("count", false);
         m_currentFinish = ctx.GetFloat("finish", false);
         m_countInterval = ctx.GetInteger("interval", false, 1);
         m_step = ctx.GetFloat("step", false, 1);
         m_strBefore = Resources::GetString(ctx.GetString("before", false));
         m_strAfter = Resources::GetString(ctx.GetString("after", false));
         string format = ctx.GetString("format", false, "normal");
              if (format == "time") m_format = CounterFormat::Time;
         else if (format == "timefractions") m_format = CounterFormat::TimeFractions;
         if (m_currentCount != m_currentFinish)
             m_countIntervalC = m_countInterval;
         TextWidget::Load(ctx);
         UpdateText();
     }
LoadCounterWidget()
ref LoadCounterWidget (WidgetLoadingContext & ctx)
Definition at line 117 of file CounterWidget.as.
References CounterWidget().
 {
     BitmapFont@ font = Resources::GetBitmapFont(ctx.GetString("font"));
     CounterWidget@ w = CounterWidget(font);
     w.Load(ctx);
     return w;
 }
SetCount()
void SetCount (float count, bool instant = false)
Definition at line 106 of file CounterWidget.as.
References m_countInterval, m_countIntervalC, m_currentCount, m_currentFinish, and UpdateText().
     {
         m_currentFinish = count;
         if (instant)
             m_currentCount = count;
         else
             m_countIntervalC = m_countInterval;
         UpdateText();
     }
SetCounter()
void SetCounter (float start, float end)
Definition at line 98 of file CounterWidget.as.
References m_countInterval, m_countIntervalC, m_currentCount, m_currentFinish, and UpdateText().
Referenced by Stats::UpdateCounter().
     {
         m_currentCount = start;
         m_currentFinish = end;
         m_countIntervalC = m_countInterval;
         UpdateText();
     }
Update()
void Update (int dt) override
Definition at line 52 of file CounterWidget.as.
References m_countInterval, m_countIntervalC, m_currentCount, m_currentFinish, m_step, Widget::Update(), and UpdateText().
     {
         if (m_countIntervalC > 0)
         {
             m_countIntervalC -= dt;
             if (m_countIntervalC <= 0)
             {
                 if (m_currentCount < m_currentFinish)
                 {
                     m_currentCount += m_step;
                     if (m_currentCount >= m_currentFinish)
                         m_currentCount = m_currentFinish;
                     else
                         m_countIntervalC = m_countInterval;
                 }
                 else if (m_currentCount > m_currentFinish)
                 {
                     m_currentCount -= m_step;
                     if (m_currentCount <= m_currentFinish)
                         m_currentCount = m_currentFinish;
                     else
                         m_countIntervalC = m_countInterval;
                 }
                 UpdateText();
             }
         }
         TextWidget::Update(dt);
     }
UpdateText()
void UpdateText ()
Definition at line 82 of file CounterWidget.as.
References formatTime(), m_currentCount, m_format, m_strAfter, m_strBefore, Normal, TextWidget::SetText(), Time, and TimeFractions.
Referenced by Load(), SetCount(), SetCounter(), and Update().
     {
         string str;
         if (m_format == CounterFormat::Normal)
         {
             str = "" + m_currentCount;
         }
         else if (m_format == CounterFormat::Time || m_format == CounterFormat::TimeFractions)
         {
             str = formatTime(m_currentCount, m_format == CounterFormat::TimeFractions);
         }
         SetText(m_strBefore + str + m_strAfter);
     }
Variable Documentation
m_countInterval
int m_countInterval
Definition at line 13 of file CounterWidget.as.
Referenced by Load(), SetCount(), SetCounter(), and Update().
m_countIntervalC
int m_countIntervalC
Definition at line 14 of file CounterWidget.as.
Referenced by Load(), SetCount(), SetCounter(), and Update().
m_currentCount
enum CounterFormat m_currentCount
Referenced by Load(), SetCount(), SetCounter(), Update(), and UpdateText().
m_currentFinish
float m_currentFinish
Definition at line 11 of file CounterWidget.as.
Referenced by Load(), SetCount(), SetCounter(), and Update().
m_format
CounterFormat m_format
Definition at line 21 of file CounterWidget.as.
Referenced by Load(), and UpdateText().
m_step
float m_step
Definition at line 16 of file CounterWidget.as.
Referenced by Load(), and Update().
m_strAfter
string m_strAfter
Definition at line 19 of file CounterWidget.as.
Referenced by Load(), and UpdateText().
m_strBefore
string m_strBefore
Definition at line 18 of file CounterWidget.as.
Referenced by Load(), and UpdateText().