HoHDocs: scripts/WorldScript/DangerArea.as File Reference
DangerArea.as File Reference
Classes
class DangerArea
Enumerations
enum DamageFilter
Functions
enum DamageFilter ApplyDamageFilter (UnitPtr unit, DamageFilter filter)
Variables
NeutralActor = 1
PlayerActor = 2
EnemyActor = 4
Other = 64
Enumeration Type Documentation
DamageFilter
enum DamageFilter
Definition at line 1 of file DangerArea.as.
 {
     NeutralActor        = 1,
     PlayerActor         = 2,
     EnemyActor          = 4,
     Other               = 64
 }
Function Documentation
ApplyDamageFilter()
enum DamageFilter ApplyDamageFilter (UnitPtr unit, DamageFilter filter)
Definition at line 12 of file DangerArea.as.
References EnemyActor, g_team_none, g_team_player, NeutralActor, Other, PlayerActor, Actor::Team, type, and unit.
Referenced by DangerAreaBehavior::Collide(), DangerAreaBehavior::EndCollision(), DangerArea::OnEnter(), and DangerArea::OnExit().
     {
         if (!unit.IsValid())
             return false;
         ref@ behavior = unit.GetScriptBehavior();
         if (behavior is null)
             return false;
         if (cast<IDamageTaker>(behavior) is null)
             return false;
         AreaFilter type = AreaFilter::Other;
         Actor@ actor = cast<Actor>(behavior);
         if (actor !is null)
         {
             if (actor.Team == g_team_none)
                 type = AreaFilter::NeutralActor;
             else if (actor.Team == g_team_player)
                 type = AreaFilter::PlayerActor;
             else
                 type = AreaFilter::EnemyActor;
         }
         return type & filter != 0;
     }
Variable Documentation
EnemyActor
@ EnemyActor = 4
Definition at line 73 of file DangerArea.as.
Referenced by ApplyDamageFilter().
NeutralActor
@ NeutralActor = 1
Definition at line 71 of file DangerArea.as.
Referenced by ApplyDamageFilter().
Other
@ Other = 64
Definition at line 74 of file DangerArea.as.
Referenced by ApplyDamageFilter().
PlayerActor
@ PlayerActor = 2
Definition at line 72 of file DangerArea.as.
Referenced by ApplyDamageFilter().