HoHDocs: scripts/FlagBank.as File Reference
FlagBank.as File Reference
Enumerations
enum FlagState {
Off = 0, Level, Run, Town,
TownAll, HostTown
}
Functions
void Set (const string &in flag, FlagState state)
void Delete (const string &in flag)
bool IsSet (const string &in flag)
FlagState Get (const string &in flag)
Variables
enum FlagState m_flags
Enumeration Type Documentation
FlagState
enum FlagState
Enumerator
Off
Level
Run
Town
TownAll
HostTown
Definition at line 1 of file FlagBank.as.
 {
     Off = 0,
     Level,
     Run,
 //  Character,
     Town,
     TownAll,
     HostTown
 }
Function Documentation
Delete()
void Delete (const string &in flag)
Definition at line 28 of file FlagBank.as.
References m_flags.
Referenced by Set().
     {
         m_flags.delete(flag);
     }
Get()
FlagState Get (const string &in flag)
Definition at line 38 of file FlagBank.as.
References m_flags, and Off.
Referenced by PlayerMenu::Show(), GuildHallMenu::Show(), Campaign::Start(), and Campaign::UpdateFrame().
     {
         int64 state;
         if (!m_flags.get(flag, state))
             return FlagState::Off;
         return FlagState(state);
     }
IsSet()
bool IsSet (const string &in flag)
Definition at line 33 of file FlagBank.as.
References m_flags.
     {
         return m_flags.exists(flag);
     }
Set()
void Set (const string &in flag, FlagState state)
Definition at line 17 of file FlagBank.as.
References Delete(), m_flags, and Off.
     {
         if (state == FlagState::Off)
         {
             Delete(flag);
             return;
         }
         m_flags.set(flag, state);
     }
Variable Documentation
m_flags
enum FlagState m_flags
Referenced by Delete(), Get(), IsSet(), and Set().