HoHDocs: scripts/FloatingText.as File Reference
FloatingText.as File Reference
Enumerations
enum FloatingTextType {
PlayerHurt, PlayerHurtMagical, PlayerHealed, PlayerArmor,
PlayerAmmo, EnemyHurt, EnemyHurtLocal, EnemyHurtHusk,
EnemyHealed, EnemyImmortal, Pickup
}
Functions
FloatingText (FloatingTextType type, string color, string text, vec3 pos)
void Update (int dt)
void Draw (int idt, SpriteBatch &sb)
void InitializeFloatingText ()
string GetConsoleColor (string name)
void UpdateFloatingTextColorsCFuncS (string val)
void UpdateFloatingTextColorsCFuncB (bool val)
FloatingText AddFloatingText (FloatingTextType type, string text, vec3 pos)
FloatingText AddFloatingNumber (FloatingTextType type, int num, vec3 pos)
Variables
array< FloatingText@> g_floatingTexts
dictionary _cachedText
bool _loadingColors
enum FloatingTextType m_text
FloatingTextType m_type
string m_consoleColor
string m_floatingText
int m_num
vec3 m_pos
int m_ttl
int m_timeLived
bool m_alive
Enumeration Type Documentation
FloatingTextType
enum FloatingTextType
Enumerator
PlayerHurt
PlayerHurtMagical
PlayerHealed
PlayerArmor
PlayerAmmo
EnemyHurt
EnemyHurtLocal
EnemyHurtHusk
EnemyHealed
EnemyImmortal
Pickup
Definition at line 5 of file FloatingText.as.
 {
     PlayerHurt,
     PlayerHurtMagical,
     PlayerHealed,
     PlayerArmor,
     PlayerAmmo,
     EnemyHurt,
     EnemyHurtLocal,
     EnemyHurtHusk,
     EnemyHealed,
     EnemyImmortal,
     Pickup
 }
Function Documentation
AddFloatingNumber()
FloatingText AddFloatingNumber (FloatingTextType type, int num, vec3 pos)
Definition at line 216 of file FloatingText.as.
References AddFloatingText(), FloatingText(), num, and type.
Referenced by Actor::AddFloatingGive(), and Actor::AddFloatingHurt().
 {
     FloatingText@ fTxt = AddFloatingText(type, "" + num, pos);
     if (fTxt !is null)
         fTxt.m_num = num;
     return fTxt;
 }
AddFloatingText()
FloatingText AddFloatingText (FloatingTextType type, string text, vec3 pos)
Definition at line 158 of file FloatingText.as.
References EnemyHealed, EnemyHurt, EnemyHurtHusk, EnemyHurtLocal, EnemyImmortal, FloatingText(), Tweak::FloatingTextColor_EnemyHeal, Tweak::FloatingTextColor_EnemyHurt, Tweak::FloatingTextColor_EnemyHurtHusk, Tweak::FloatingTextColor_EnemyHurtLocal, Tweak::FloatingTextColor_EnemyImmortal, Tweak::FloatingTextColor_Pickup, Tweak::FloatingTextColor_PlayerAmmo, Tweak::FloatingTextColor_PlayerArmor, Tweak::FloatingTextColor_PlayerHeal, Tweak::FloatingTextColor_PlayerHurt, Tweak::FloatingTextColor_PlayerHurtMagical, g_floatingTexts, g_gameMode, AGameMode::m_wndHeight, AGameMode::m_wndScale, AGameMode::m_wndWidth, Pickup, PlayerAmmo, PlayerArmor, PlayerHealed, PlayerHurt, PlayerHurtMagical, text, ToScreenspace(), and type.
Referenced by Actor::AddFloatingHurt(), Actor::AddFloatingImmortal(), AddFloatingNumber(), GiveKey::Apply(), ShowFloatingText::Apply(), WorldScript::UnlinkSouls::ClientExecute(), WorldScript::ShowFloatingText::ClientExecute(), WorldScript::PotionRefill::ClientExecute(), EndCollision(), GiveForgeBlueprintImpl(), GiveItemImpl(), Player::Heal(), PlayerHusk::NetDamage(), PlayerHusk::NetDecimate(), PlayerBase::NetHeal(), PlayerCorpse::NetRevive(), WorldScript::StoreOre::OnFunc(), Player::OnLevelUp(), Player::SpendCost(), Player::Update(), Door::Use(), Use(), Chest::Use(), WorldScript::Well::Use(), and Player::WarnCooldown().
 {
 %if MOD_NO_HUD
     return null;
 %else
     vec2 p = ToScreenspace(pos) / g_gameMode.m_wndScale;
     if (p.x < 0 || p.x > g_gameMode.m_wndWidth || p.y < 0 || p.y > g_gameMode.m_wndHeight)
         return null;
     string color;
     switch(type)
     {
     case FloatingTextType::PlayerHurt:
         color = Tweak::FloatingTextColor_PlayerHurt;
         break;
     case FloatingTextType::PlayerHurtMagical:
         color = Tweak::FloatingTextColor_PlayerHurtMagical;
         break;
     case FloatingTextType::EnemyHurt:
         color = Tweak::FloatingTextColor_EnemyHurt;
         break;
     case FloatingTextType::EnemyHurtLocal:
         color = Tweak::FloatingTextColor_EnemyHurtLocal;
         break;
     case FloatingTextType::EnemyHurtHusk:
         color = Tweak::FloatingTextColor_EnemyHurtHusk;
         break;
     case FloatingTextType::PlayerHealed:
         color = Tweak::FloatingTextColor_PlayerHeal;
         break;
     case FloatingTextType::EnemyHealed:
         color = Tweak::FloatingTextColor_EnemyHeal;
         break;
     case FloatingTextType::EnemyImmortal:
         color = Tweak::FloatingTextColor_EnemyImmortal;
         break;
     case FloatingTextType::PlayerArmor:
         color = Tweak::FloatingTextColor_PlayerArmor;
         break;
     case FloatingTextType::PlayerAmmo:
         color = Tweak::FloatingTextColor_PlayerAmmo;
         break;
     case FloatingTextType::Pickup:
         color = Tweak::FloatingTextColor_Pickup;
         break;
     }
     if (color == "")
         return null;
     FloatingText@ fTxt = FloatingText(type, color, text, pos);
     g_floatingTexts.insertLast(fTxt);
     return fTxt;
 %endif
 }
Draw()
void Draw (int idt, SpriteBatch & sb)
Definition at line 75 of file FloatingText.as.
References FloatingTextSpeed, g_gameMode, m_pos, m_text, AGameMode::m_wndScale, and ToScreenspace().
Referenced by NotificationManager::Draw(), UserWindow::Draw(), Menu::InGameChat::Draw(), DialogWindow::Draw(), HUDCoop::Draw(), HUD::Draw(), BaseGameMode::DrawFloatingTexts(), BaseGameMode::DrawOverheadBossBars(), and BaseGameMode::RenderWidgets().
     {
         vec3 pos = m_pos;
         pos.y -= idt * FloatingTextSpeed;
         vec2 p = ToScreenspace(pos);
         p.x -= m_text.GetWidth();
         sb.DrawString(p / g_gameMode.m_wndScale, m_text);
     }
FloatingText()
FloatingText (FloatingTextType type, string color, string text, vec3 pos)
Definition at line 34 of file FloatingText.as.
References _cachedText, Center, Tweak::FloatingTextTime, g_floatTextFont, g_floatTextFontBig, m_alive, m_consoleColor, m_floatingText, m_pos, m_text, m_ttl, m_type, Pickup, text, and type.
Referenced by AddFloatingNumber(), and AddFloatingText().
     {
         if (type == FloatingTextType::Pickup)
             @m_text = g_floatTextFontBig.BuildText(color + text, -1, TextAlignment::Center);
         else
         {
             string txt = color + text;
             bool short = (text.length() <= 4);
             if (short)
                 _cachedText.get(txt, @m_text);
             if (m_text is null)
             {
                 @m_text = g_floatTextFont.BuildText(txt, -1, TextAlignment::Center);
                 if (short)
                     _cachedText.set(txt, @m_text);
             }
         }
         m_type = type;
         m_consoleColor = color;
         m_floatingText = text;
         m_pos = pos;
         m_pos.x += randi(8) - 4;
         m_pos.y += randi(8) - 4;
         m_ttl = Tweak::FloatingTextTime;
         m_alive = true;
     }
GetConsoleColor()
string GetConsoleColor (string name)
Definition at line 107 of file FloatingText.as.
References name.
Referenced by UpdateFloatingTextColorsCFuncB().
 {
     string c = GetVarString(name);
     if (c == "")
         return "";
     return "\\c" + c;
 }
InitializeFloatingText()
void InitializeFloatingText ()
Definition at line 87 of file FloatingText.as.
References _loadingColors, Tweak::FloatingTextColor_EnemyHeal, Tweak::FloatingTextColor_EnemyHurt, Tweak::FloatingTextColor_EnemyHurtHusk, Tweak::FloatingTextColor_EnemyHurtLocal, Tweak::FloatingTextColor_EnemyImmortal, Tweak::FloatingTextColor_Pickup, Tweak::FloatingTextColor_PlayerAmmo, Tweak::FloatingTextColor_PlayerAmmoMax, Tweak::FloatingTextColor_PlayerArmor, Tweak::FloatingTextColor_PlayerHeal, Tweak::FloatingTextColor_PlayerHurt, Tweak::FloatingTextColor_PlayerHurtMagical, UpdateFloatingTextColorsCFuncB(), and UpdateFloatingTextColorsCFuncS().
Referenced by BaseGameMode::BaseGameMode().
 {
     _loadingColors = true;
     AddVar("ui_txt", true, UpdateFloatingTextColorsCFuncB);
     AddVar("ui_txt_plr_hurt", Tweak::FloatingTextColor_PlayerHurt, UpdateFloatingTextColorsCFuncS);
     AddVar("ui_txt_plr_hurt_magic", Tweak::FloatingTextColor_PlayerHurtMagical, UpdateFloatingTextColorsCFuncS);
     AddVar("ui_txt_enemy_hurt", Tweak::FloatingTextColor_EnemyHurt, UpdateFloatingTextColorsCFuncS);
     AddVar("ui_txt_enemy_hurt_local", Tweak::FloatingTextColor_EnemyHurtLocal, UpdateFloatingTextColorsCFuncS);
     AddVar("ui_txt_enemy_hurt_husk", Tweak::FloatingTextColor_EnemyHurtHusk, UpdateFloatingTextColorsCFuncS);
     AddVar("ui_txt_plr_heal", Tweak::FloatingTextColor_PlayerHeal, UpdateFloatingTextColorsCFuncS);
     AddVar("ui_txt_enemy_heal", Tweak::FloatingTextColor_EnemyHeal, UpdateFloatingTextColorsCFuncS);
     AddVar("ui_txt_enemy_immortal", Tweak::FloatingTextColor_EnemyImmortal, UpdateFloatingTextColorsCFuncS);
     AddVar("ui_txt_plr_armor", Tweak::FloatingTextColor_PlayerArmor, UpdateFloatingTextColorsCFuncS);
     AddVar("ui_txt_plr_ammo", Tweak::FloatingTextColor_PlayerAmmo, UpdateFloatingTextColorsCFuncS);
     AddVar("ui_txt_plr_ammo_max", Tweak::FloatingTextColor_PlayerAmmoMax, UpdateFloatingTextColorsCFuncS);
     AddVar("ui_txt_pickup", Tweak::FloatingTextColor_Pickup, UpdateFloatingTextColorsCFuncS);
     _loadingColors = false;
     UpdateFloatingTextColorsCFuncB(false);
 }
Update()
void Update (int dt)
Definition at line 65 of file FloatingText.as.
References FloatingTextSpeed, m_alive, m_pos, m_timeLived, and m_ttl.
     {
         m_ttl -= dt;
         m_timeLived += dt;
         m_pos.y -= dt * FloatingTextSpeed;
         if (m_ttl <= 0)
             m_alive = false;
     }
UpdateFloatingTextColorsCFuncB()
void UpdateFloatingTextColorsCFuncB (bool val)
Definition at line 121 of file FloatingText.as.
References _loadingColors, Tweak::FloatingTextColor_EnemyHeal, Tweak::FloatingTextColor_EnemyHurt, Tweak::FloatingTextColor_EnemyHurtHusk, Tweak::FloatingTextColor_EnemyHurtLocal, Tweak::FloatingTextColor_EnemyImmortal, Tweak::FloatingTextColor_Pickup, Tweak::FloatingTextColor_PlayerAmmo, Tweak::FloatingTextColor_PlayerAmmoMax, Tweak::FloatingTextColor_PlayerArmor, Tweak::FloatingTextColor_PlayerHeal, Tweak::FloatingTextColor_PlayerHurt, Tweak::FloatingTextColor_PlayerHurtMagical, and GetConsoleColor().
Referenced by InitializeFloatingText(), and UpdateFloatingTextColorsCFuncS().
 {
     if (_loadingColors)
         return;
     if (GetVarBool("ui_txt"))
     {
         Tweak::FloatingTextColor_PlayerHurt = GetConsoleColor("ui_txt_plr_hurt");
         Tweak::FloatingTextColor_PlayerHurtMagical = GetConsoleColor("ui_txt_plr_hurt_magic");
         Tweak::FloatingTextColor_EnemyHurt = GetConsoleColor("ui_txt_enemy_hurt");
         Tweak::FloatingTextColor_EnemyHurtLocal = GetConsoleColor("ui_txt_enemy_hurt_local");
         Tweak::FloatingTextColor_EnemyHurtHusk = GetConsoleColor("ui_txt_enemy_hurt_husk");
         Tweak::FloatingTextColor_PlayerHeal = GetConsoleColor("ui_txt_plr_heal");
         Tweak::FloatingTextColor_EnemyHeal = GetConsoleColor("ui_txt_enemy_heal");
         Tweak::FloatingTextColor_EnemyImmortal = GetConsoleColor("ui_txt_enemy_immortal");
         Tweak::FloatingTextColor_PlayerArmor = GetConsoleColor("ui_txt_plr_armor");
         Tweak::FloatingTextColor_PlayerAmmo = GetConsoleColor("ui_txt_plr_ammo");
         Tweak::FloatingTextColor_PlayerAmmoMax = GetConsoleColor("ui_txt_plr_ammo_max");
         Tweak::FloatingTextColor_Pickup = GetConsoleColor("ui_txt_pickup");
     }
     else
     {
         Tweak::FloatingTextColor_PlayerHurt = "";
         Tweak::FloatingTextColor_PlayerHurtMagical = "";
         Tweak::FloatingTextColor_EnemyHurt = "";
         Tweak::FloatingTextColor_EnemyHurtLocal = "";
         Tweak::FloatingTextColor_EnemyHurtHusk = "";
         Tweak::FloatingTextColor_PlayerHeal = "";
         Tweak::FloatingTextColor_EnemyHeal = "";
         Tweak::FloatingTextColor_EnemyImmortal = "";
         Tweak::FloatingTextColor_PlayerArmor = "";
         Tweak::FloatingTextColor_PlayerAmmo = "";
         Tweak::FloatingTextColor_PlayerAmmoMax = "";
         Tweak::FloatingTextColor_Pickup = "";
     }
 }
UpdateFloatingTextColorsCFuncS()
void UpdateFloatingTextColorsCFuncS (string val)
Definition at line 116 of file FloatingText.as.
References UpdateFloatingTextColorsCFuncB().
Referenced by InitializeFloatingText().
 {
     UpdateFloatingTextColorsCFuncB(false);
 }
Variable Documentation
_cachedText
dictionary _cachedText
Definition at line 2 of file FloatingText.as.
Referenced by FloatingText().
_loadingColors
bool _loadingColors
Definition at line 3 of file FloatingText.as.
Referenced by InitializeFloatingText(), and UpdateFloatingTextColorsCFuncB().
g_floatingTexts
array<FloatingText@> g_floatingTexts
Definition at line 1 of file FloatingText.as.
Referenced by AddFloatingText(), BaseGameMode::DrawFloatingTexts(), and BaseGameMode::UpdateFrame().
m_alive
bool m_alive
Definition at line 32 of file FloatingText.as.
Referenced by FloatingText(), Update(), and BaseGameMode::UpdateFrame().
m_consoleColor
string m_consoleColor
Definition at line 25 of file FloatingText.as.
Referenced by FloatingText().
m_floatingText
string m_floatingText
Definition at line 26 of file FloatingText.as.
Referenced by FloatingText().
m_num
int m_num
Definition at line 27 of file FloatingText.as.
m_pos
vec3 m_pos
Definition at line 28 of file FloatingText.as.
Referenced by Draw(), FloatingText(), and Update().
m_text
enum FloatingTextType m_text
Referenced by Draw(), and FloatingText().
m_timeLived
int m_timeLived
Definition at line 31 of file FloatingText.as.
Referenced by Update().
m_ttl
int m_ttl
Definition at line 30 of file FloatingText.as.
Referenced by FloatingText(), and Update().
m_type
FloatingTextType m_type
Definition at line 23 of file FloatingText.as.
Referenced by FloatingText(), and TownRecord::GetBestiary().