HoHDocs: scripts/GUI/Menus/GameChat.as File Reference
GameChat.as File Reference
Classes
class GameChatWidget
Functions
GameChatWidget RectWidget LoadGameChatWidget (WidgetLoadingContext &ctx)
GameChatWidget ()
void Load (WidgetLoadingContext &ctx) override
void Initialize ()
void Update (int dt) override
void AddChat (string str, vec4 color=vec4(1, 1, 1, 1))
void PlayerChat (uint8 peer, string message)
void PlayerSystem (uint8 peer, string message)
Variables
ScrollableWidget m_wList
Widget m_wTemplate
TextInputWidget m_wInput
int m_visibleCounter
Function Documentation
AddChat()
void LoadGameChatWidget::AddChat (string str, vec4 color = vec4(1, 1, 1, 1))
Definition at line 137 of file GameChat.as.
GameChatWidget()
LoadGameChatWidget::GameChatWidget ()
Definition at line 112 of file GameChat.as.
Referenced by LoadGameChatWidget().
Initialize()
void LoadGameChatWidget::Initialize ()
Definition at line 122 of file GameChat.as.
Load()
void LoadGameChatWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 117 of file GameChat.as.
LoadGameChatWidget()
GameChatWidget RectWidget LoadGameChatWidget (WidgetLoadingContext & ctx)
Definition at line 80 of file GameChat.as.
References GameChatWidget(), and GameChatWidget::Load().
Referenced by MainMenu::MainMenu().
 {
     GameChatWidget@ w = GameChatWidget();
     w.Load(ctx);
     return w;
 }
PlayerChat()
void LoadGameChatWidget::PlayerChat (uint8 peer, string message)
Definition at line 163 of file GameChat.as.
PlayerSystem()
void LoadGameChatWidget::PlayerSystem (uint8 peer, string message)
Definition at line 174 of file GameChat.as.
Update()
void LoadGameChatWidget::Update (int dt) override
Definition at line 129 of file GameChat.as.
Variable Documentation
m_visibleCounter
int m_visibleCounter
Definition at line 110 of file GameChat.as.
m_wInput
TextInputWidget m_wInput
Definition at line 108 of file GameChat.as.
m_wList
ScrollableWidget m_wList
Definition at line 106 of file GameChat.as.
m_wTemplate
Widget m_wTemplate
Definition at line 107 of file GameChat.as.