HoHDocs: scripts/GameModes/GenerateDungeon.as File Reference
GenerateDungeon.as File Reference
Classes
class PrefabToSpawn
Functions
ivec3 CalcLevel (int levelNum)
string GetLevelName (bool short=false, int levelCount=-1)
void SetLevelFlags (int levelCount)
void GenerateDungeon (RandomLevel@ gameMode, int levelCount, int shortcut, int numPlrs)
ivec2 Rectangularize (int w, int h, float amount)
class PrefabToSpawn MakeDungeonGenerator (int levelCount, int numPlrs)
PrefabToSpawn (Prefab@ pfb, vec3 pos)
Variables
pint g_ngp = 0
array< PrefabToSpawn@> g_prefabsToSpawn
Prefab m_pfb
vec3 m_pos
Function Documentation
CalcLevel()
ivec3 CalcLevel (int levelNum)
Definition at line 3 of file GenerateDungeon.as.
References g_gameMode.
Referenced by Apply(), ColorForSplit(), DungeonLevelRichPresence(), GenerateDungeon(), GetLevelName(), GiveItemImpl(), NameForSplit(), NetGiveGoldImpl(), RichPresenceGetActName(), SetLevelFlags(), RandomLootManager::SpawnLoot(), BossLevel::Start(), ShortcutLevel::Start(), and Campaign::Start().
 {
     auto gm = cast<BaseGameMode>(g_gameMode);
     if (gm is null)
         return ivec3();
     auto level = gm.m_rotation.GetLevel(levelNum);
     if (level is null)
         return ivec3();
     return ivec3(level.m_act, level.m_level, levelNum);
 }
GenerateDungeon()
void GenerateDungeon (RandomLevel@ gameMode, int levelCount, int shortcut, int numPlrs)
Definition at line 75 of file GenerateDungeon.as.
References CalcLevel(), g_gameMode, g_scene, RandomLevel::m_enemyPlacer, MakeDungeonGenerator(), and SetLevelFlags().
Referenced by RandomLevel::Generate().
 {
     DungeonGenerator@ dgn = MakeDungeonGenerator(levelCount, numPlrs);
     print("LevelCount: " + levelCount);
     auto gm = cast<BaseGameMode>(g_gameMode);
     auto level = gm.m_rotation.GetLevel(levelCount);
     SetLevelFlags(levelCount);
     if (dgn !is null)
     {
         if (gameMode !is null)
             @gameMode.m_enemyPlacer = dgn.m_enemyPlacer;
         if (level.m_level == 0 && shortcut > level.m_act)
             dgn.m_placeActShortcut = true;
         dgn.MakeBrush();
         dgn.m_brush.m_lvl = CalcLevel(levelCount);
         dgn.m_numPlrs = numPlrs;
         dgn.Generate(g_scene);
     }
 }
GetLevelName()
string GetLevelName (bool short = false, int levelCount = -1)
Definition at line 16 of file GenerateDungeon.as.
References CalcLevel(), and g_gameMode.
Referenced by PlayerMenuMapTab::OnShow(), and Campaign::RenderWidgets().
 {
     if (levelCount == -1)
     {
         auto gm = cast<Campaign>(g_gameMode);
         if (cast<Town>(gm) !is null)
             return Resources::GetString(".world.town");
         levelCount = gm.m_levelCount;
     }
     ivec3 level = CalcLevel(levelCount);
     string info = "";
     if (short)
         info += Resources::GetString(".world.acts." + level.x) + "\n";
     else
     {
         if (level.x == 0)
             info += Resources::GetString(".world.mines");
         else
             info += Resources::GetString(".world.tower");
         info += ", ";
         info += Resources::GetString(".world.acts." + level.x);
         info += " - ";
     }
     dictionary params = { { "num", level.y + 1 } };
     info += Resources::GetString(".world.floor", params);
     return info;
 }
MakeDungeonGenerator()
class PrefabToSpawn MakeDungeonGenerator (int levelCount, int numPlrs)
Definition at line 123 of file GenerateDungeon.as.
References EnemyPlacement::AddEnemyGroup(), AddExtra(), Archives, Armory, Bats, Chambers, MinesGenerator::Density, EnemySetting(), Eyes, g_flags, g_gameMode, g_ngp, Ghosts, Fountain::HasEffect(), ArmoryGenerator::Height, MinesGenerator::Height, IceTrolls, Level, Liches, EnemyPlacement::m_maxMinibosses, Maggots, ArmoryGenerator::MaxCliffNum, MinesGenerator::MaxCliffNum, MinesGenerator::NumDeadEndsFill, ArmoryGenerator::Prefabs, MinesGenerator::Prefabs, Prison, PyramidFancy, PyramidSlum, Rectangularize(), MinesGenerator::RoomChance, ArmoryGenerator::RoomSize, MinesGenerator::RoomSize, SkeletonArchers1, SkeletonArchers2, Skeletons1, Skeletons2, Ticks, MinesGenerator::Width, ArmoryGenerator::Width, and Wisps.
Referenced by GenerateDungeon(), and StaticLevel::Start().
 {
     DungeonGenerator@ dgn;
     EnemyPlacement enemyPlacer;
     auto gm = cast<BaseGameMode>(g_gameMode);
     auto level = gm.m_rotation.GetLevel(levelCount);
     float enemyAmountMul = 1.0f;
     float levelSizeMul = 1.0f;
     if (Fountain::HasEffect("bigger_levels"))
     {
         levelSizeMul *= 1.15f;
         enemyAmountMul *= 1.33f;
     }
     if (g_ngp > 0)
     {
         levelSizeMul *= 1.15f;
         enemyAmountMul *= 1.33f;
     }
     bool forceMiniboss = Fountain::HasEffect("minibosses_everywhere");
     if (level.m_theme == "mines")
     {
         MinesGenerator mines;
         auto brush = GraniteMineBrush();
         brush.m_grassChanceAdjustment = -3 * level.m_level;
         @mines.m_brush = brush;
         if (level.m_level == 0)
             g_flags.Set("no_flowers", FlagState::Level);
         mines.Width = int(level.m_width * levelSizeMul);
         mines.Height = int(level.m_height * levelSizeMul);
         mines.Density = 1;
         mines.RoomChance = 0.1;
         mines.RoomSize = 12;
         mines.NumDeadEndsFill = 5;
         mines.MaxCliffNum = 0;
         mines.Prefabs = true;
         enemyPlacer.AddEnemyGroup(EnemySetting(Enemies::Bats, 1, true, level.m_level >= 2));
         enemyPlacer.AddEnemyGroup(EnemySetting(Enemies::Ticks, 3, true, level.m_level >= 1, forceMiniboss || level.m_level >= 2).AddExtra("actors/tick_1_small_exploding.unit", 2));
         enemyPlacer.AddEnemyGroup(EnemySetting(Enemies::Maggots, (level.m_level == 0) ? 1 : 2, true, level.m_level >= 1, false));
         enemyPlacer.m_maxMinibosses = 2 + g_ngp * 2 + numPlrs;
         mines.MinEnemyGroups = int(enemyAmountMul * (8 + level.m_level * 5 + numPlrs * 2));
         @dgn = mines;
     }
     else if (level.m_theme == "prison")
     {
         PrisonGenerator prison;
         prison.Tileset = DungeonTileset::Prison;
         prison.Width = int(level.m_width * levelSizeMul);
         prison.Height = int(level.m_height * levelSizeMul);
         prison.Density = 2.5;
         prison.RoomChance = 0.2;
         prison.RoomSize = 12;
         prison.NumDeadEndsFill = 20;
         prison.MaxCliffNum = 5;
         prison.Prefabs = true;
         if (level.m_level < 1)
             enemyPlacer.AddEnemyGroup(EnemySetting(Enemies::Ticks, 3, true, true));
         if (level.m_level < 2)
             enemyPlacer.AddEnemyGroup(EnemySetting(Enemies::Bats, 3, true, true));
         enemyPlacer.AddEnemyGroup(EnemySetting(Enemies::Maggots, 3, true, true, forceMiniboss || level.m_level >= 2));
         enemyPlacer.AddEnemyGroup(EnemySetting(Enemies::SkeletonArchers1, 2, true, level.m_level >= 1, false));
         enemyPlacer.AddEnemyGroup(EnemySetting(Enemies::Skeletons1, 3, true, level.m_level >= 1, false).AddExtra("actors/bannerman_bloodlust.unit", (level.m_level >= 1) ? 1 : 0, 0.75f));
         enemyPlacer.m_maxMinibosses = 3 + g_ngp * 2 + numPlrs;
         prison.MinEnemyGroups = int(enemyAmountMul * (20 + level.m_level * 3 + numPlrs * 2));
         @dgn = prison;
     }
     else if (level.m_theme == "armory")
     {
         ArmoryGenerator armory;
         armory.Tileset = DungeonTileset::Armory;
         armory.Width = int(level.m_width * levelSizeMul);
         armory.Height = int(level.m_height * levelSizeMul);
         auto sz = Rectangularize(armory.Width, armory.Height, 0.25);
         armory.Width = sz.x;
         armory.Height = sz.y;
         armory.RoomSize = 17 + numPlrs;
         armory.MaxCliffNum = 2;
         armory.Prefabs = true;
         if (level.m_level < 1)
             enemyPlacer.AddEnemyGroup(EnemySetting(Enemies::SkeletonArchers1, 1, true, true, false));
         if (level.m_level < 2)
             enemyPlacer.AddEnemyGroup(EnemySetting(Enemies::Skeletons1, 1, true, true, false).AddExtra("actors/bannerman_bloodlust.unit", 1, 0.5f));
         auto skelGroup = EnemySetting(Enemies::Skeletons1, 1, true, true, forceMiniboss || level.m_level >= 2)
             .AddExtra("actors/bannerman_bloodlust.unit", 1, 0.2f)
             .AddExtra("actors/bannerman_protection.unit", 1, 0.2f)
             .AddExtra("actors/skeleton_1_spear.unit", 4, 1.5f);
         if (level.m_level >= 1)
             skelGroup.AddExtra("actors/lich_summ_1.unit", 1, 0.1f);
         enemyPlacer.AddEnemyGroup(skelGroup);
         enemyPlacer.AddEnemyGroup(EnemySetting(Enemies::SkeletonArchers1, 1, true, true, false).AddExtra("actors/lich_1.unit", 2));
         enemyPlacer.m_maxMinibosses = 4 + g_ngp * 2 + numPlrs * 2;
         armory.MinEnemyGroups = int(enemyAmountMul * (24 + numPlrs * 5 + level.m_level * 5));
         @dgn = armory;
     }
     else if (level.m_theme == "archives")
     {
         ArchivesGenerator archives;
         archives.Tileset = DungeonTileset::Archives;
         archives.Width = int(level.m_width * levelSizeMul);
         archives.Height = int(level.m_height * levelSizeMul);
         auto sz = Rectangularize(archives.Width, archives.Height, 0.25);
         archives.Width = sz.x;
         archives.Height = sz.y;
         archives.Padding = 30;
         archives.PathWidth = 5;
         archives.Prefabs = true;
         enemyPlacer.AddEnemyGroup(EnemySetting(Enemies::Ghosts, 1, true, true, false));
         enemyPlacer.AddEnemyGroup(EnemySetting(Enemies::Eyes, 5, true, true, forceMiniboss || level.m_level >= 1)
             .AddExtra("actors/lich_1.unit", 2, 0.8f));
         enemyPlacer.AddEnemyGroup(EnemySetting(Enemies::Wisps, 5, true, level.m_level >= 1, false)
             .AddExtra("actors/lich_1.unit", 2, 0.8f));
         enemyPlacer.m_maxMinibosses = 0; //4 + level.m_level * (3 + g_ngp * 2) + numPlrs;
         archives.MinEnemyGroups = int(enemyAmountMul * (32 + level.m_level * 4 + numPlrs * 4));
         @dgn = archives;
     }
     else if (level.m_theme == "chambers")
     {
         ChambersGenerator chambers;
         chambers.Tileset = DungeonTileset::Chambers;
         chambers.Width = int(level.m_width * levelSizeMul);
         chambers.Height = int(level.m_height * levelSizeMul);
         chambers.Padding = 43;
         chambers.Splits = 8 + level.m_level;
         chambers.Prefabs = true;
         enemyPlacer.AddEnemyGroup(EnemySetting(Enemies::SkeletonArchers2, 2, true, level.m_level >= 1, false));
         enemyPlacer.AddEnemyGroup(EnemySetting(Enemies::Skeletons2, 4, true, true, forceMiniboss || level.m_level >= 2)
             ); //.AddExtra("actors/bannerman_healing.unit", 1, 0.1f));
         enemyPlacer.AddEnemyGroup(EnemySetting(Enemies::Liches, 1, true, true, forceMiniboss || level.m_level >= 2));
         enemyPlacer.m_maxMinibosses = 6 + level.m_level * (4 + g_ngp * 2) + numPlrs;
         chambers.MinEnemyGroups = int(enemyAmountMul * (32 + level.m_level * 4 + numPlrs * 4));
         @dgn = chambers;
     }
     else if (level.m_theme == "battlements")
     {
         @dgn = DungeonGenerator();
         enemyPlacer.AddEnemyGroup(EnemySetting(Enemies::IceTrolls, 1, true, true, forceMiniboss || level.m_level >= 1)
         .AddExtra("actors/ice_troll_shaman.unit", 1, 0.8f));
         enemyPlacer.m_maxMinibosses = 6 + level.m_level * (4 + g_ngp * 2) + numPlrs;
     }
     else if (level.m_theme == "pyramid_slum")
     {
         PyramidGenerator pyramid;
         pyramid.Tileset = DungeonTileset::PyramidSlum;
         pyramid.Width = int(level.m_width * levelSizeMul);
         pyramid.Height = int(level.m_height * levelSizeMul);
         pyramid.Density = 4.5;
         pyramid.RoomChance = 0.35;
         pyramid.RoomSize = 8;
         pyramid.NumDeadEndsFill = 20;
         pyramid.MaxCliffNum = 10;
         pyramid.Prefabs = true;
         if (level.m_level < 1)
             enemyPlacer.AddEnemyGroup(EnemySetting(Enemies::Ticks, 3, true, true));
         if (level.m_level < 2)
             enemyPlacer.AddEnemyGroup(EnemySetting(Enemies::Bats, 3, true, true));
         enemyPlacer.AddEnemyGroup(EnemySetting(Enemies::Maggots, 3, true, true, forceMiniboss || level.m_level >= 2));
         enemyPlacer.AddEnemyGroup(EnemySetting(Enemies::SkeletonArchers1, 2, true, level.m_level >= 1, false));
         enemyPlacer.AddEnemyGroup(EnemySetting(Enemies::Skeletons1, 3, true, level.m_level >= 1, false).AddExtra("actors/bannerman_bloodlust.unit", (level.m_level >= 1) ? 1 : 0, 0.75f));
         enemyPlacer.m_maxMinibosses = 3 + g_ngp * 2 + numPlrs;
         pyramid.MinEnemyGroups = int(enemyAmountMul * (20 + level.m_level * 3 + numPlrs * 2));
         @dgn = pyramid;
     }
     else if (level.m_theme == "pyramid_fancy")
     {
         PyramidGenerator pyramid;
         pyramid.Tileset = DungeonTileset::PyramidFancy;
         pyramid.Width = int(level.m_width * levelSizeMul);
         pyramid.Height = int(level.m_height * levelSizeMul);
         pyramid.Density = 3.0;
         pyramid.RoomChance = 0.25;
         pyramid.RoomSize = 12;
         pyramid.NumDeadEndsFill = 20;
         pyramid.MaxCliffNum = 10;
         pyramid.Prefabs = true;
         if (level.m_level < 1)
             enemyPlacer.AddEnemyGroup(EnemySetting(Enemies::Ticks, 3, true, true));
         if (level.m_level < 2)
             enemyPlacer.AddEnemyGroup(EnemySetting(Enemies::Bats, 3, true, true));
         enemyPlacer.AddEnemyGroup(EnemySetting(Enemies::Maggots, 3, true, true, forceMiniboss || level.m_level >= 2));
         enemyPlacer.AddEnemyGroup(EnemySetting(Enemies::SkeletonArchers1, 2, true, level.m_level >= 1, false));
         enemyPlacer.AddEnemyGroup(EnemySetting(Enemies::Skeletons1, 3, true, level.m_level >= 1, false).AddExtra("actors/bannerman_bloodlust.unit", (level.m_level >= 1) ? 1 : 0, 0.75f));
         enemyPlacer.m_maxMinibosses = 3 + g_ngp * 2 + numPlrs;
         pyramid.MinEnemyGroups = int(enemyAmountMul * (20 + level.m_level * 3 + numPlrs * 2));
         @dgn = pyramid;
     }
     if (dgn !is null)
         @dgn.m_enemyPlacer = enemyPlacer;
     return dgn;
 }
PrefabToSpawn()
MakeDungeonGenerator::PrefabToSpawn (Prefab@ pfb, vec3 pos)
Definition at line 113 of file GenerateDungeon.as.
Referenced by Generate(), and SpawnPointsOfInterest().
     {
         @m_pfb = pfb;
Rectangularize()
ivec2 Rectangularize (int w, int h, float amount)
Definition at line 101 of file GenerateDungeon.as.
Referenced by MakeDungeonGenerator().
 {
     int tot = w * h;
     w += int((randf() - randf()) * w * amount);
     h = tot / w;
     return ivec2(w, h);
 }
SetLevelFlags()
void SetLevelFlags (int levelCount)
Definition at line 53 of file GenerateDungeon.as.
References CalcLevel(), Fountain::CurrentEffects, effect, g_flags, Fountain::GetEffect(), and Level.
Referenced by GenerateDungeon(), StaticLevel::Start(), BossLevel::Start(), ShortcutLevel::Start(), and TestLevel::Start().
 {
     for (uint i = 0; i < Fountain::CurrentEffects.length(); i++)
     {
         auto effect = Fountain::GetEffect(Fountain::CurrentEffects[i]);
         if (effect is null)
         {
             PrintError("Couldn't find effect for ID " + Fountain::CurrentEffects[i]);
             continue;
         }
         if (effect.m_flag != "")
             g_flags.Set(effect.m_flag, FlagState::Level);
     }
     ivec3 lvl = CalcLevel(levelCount);
     g_flags.Set("act_" + lvl.x, FlagState::Level);
     g_flags.Set("lvl_" + lvl.y, FlagState::Level);
     g_flags.Set("lvlcount_" + lvl.z, FlagState::Level);
 }
Variable Documentation
g_ngp
pint g_ngp = 0
Definition at line 1 of file GenerateDungeon.as.
Referenced by Player::Damage(), DungeonLevelRichPresence(), RandomLevel::Generate(), GetArmor(), Upgrades::DungeonShop::GetCostScale(), Titles::GetMaxClassTitleIndex(), GetMaxHp(), GiveOreImpl(), EndOfGame::Initialize(), TavernBarrel::Initialize(), CondNGPLess::IsAllowed(), CondNGPLessEqual::IsAllowed(), CondNGPNotEqual::IsAllowed(), Player::KilledActor(), MakeDungeonGenerator(), DungeonSettingsMenu::OnFunc(), DungeonSettingsMenu::OnNgpChanged(), PlayerMenuMapTab::OnShow(), PyramidGenerator::PlacePrefabs(), PrisonGenerator::PlacePrefabs(), MinesGenerator::PlacePrefabs(), RandomLootManager::RandomItemQuality(), Campaign::Save(), TownRecord::Save(), BaseGameMode::Save(), WorldScript::CheckNewGamePlus::ServerExecute(), GameModeHandler::SetNgp(), RandomLootManager::SpawnLoot(), ShortcutLevel::Start(), BossLevel::Start(), Campaign::Start(), DungeonSettingsMenu::Update(), MeleeMovement::Update(), RandomLootManager::Update(), Town::UpdateFrame(), PlayerMenuCharacterTab::UpdateFromRecord(), and DungeonSettingsMenu::UpdateNgp().
g_prefabsToSpawn
array<PrefabToSpawn@> g_prefabsToSpawn
Definition at line 109 of file GenerateDungeon.as.
Referenced by Generate(), SpawnPointsOfInterest(), and RandomLevel::Start().
m_pfb
Prefab m_pfb
Definition at line 110 of file GenerateDungeon.as.
Referenced by RandomLevel::Start().
m_pos
vec3 m_pos
Definition at line 111 of file GenerateDungeon.as.