HoHDocs: scripts/Behaviors/Effects/GiveOre.as File Reference
GiveOre.as File Reference
Classes
class GiveOre
Functions
GiveOre IEffect GiveOreImpl (int amount, Player@ player, bool showFloatingText=true)
GiveOre (UnitPtr unit, SValue &params)
void SetWeaponInformation (uint weapon)
bool Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
bool CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
void NetGiveOreImpl (int amount, PlayerBase@ player)
Variables
int m_amount
bool m_pickup
Function Documentation
Apply()
bool GiveOreImpl::Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
Definition at line 59 of file GiveOre.as.
References Stats::Add(), CalcLevel(), g_gameMode, and PlayerBase::m_record.
 {
     Stats::Add("ore-found", amount, player.m_record);
     Stats::Add("avg-ore-found", amount, player.m_record);
     auto gm = cast<Campaign>(g_gameMode);
     if (gm !is null)
     {
         ivec3 level = CalcLevel(gm.m_levelCount);
         Stats::Add("avg-ore-found-act-" + (level.x + 1), amount, player.m_record);
     }
     player.m_record.runOre += amount;
 }
CanApply()
bool GiveOreImpl::CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
Definition at line 75 of file GiveOre.as.
Referenced by CanApplyEffects().
GiveOre()
GiveOreImpl::GiveOre (UnitPtr unit, SValue & params)
Definition at line 51 of file GiveOre.as.
 {
GiveOreImpl()
GiveOre IEffect GiveOreImpl (int amount, Player@ player, bool showFloatingText = true)
Definition at line 36 of file GiveOre.as.
References g_ngp, NetGiveOreImpl(), and roll_round().
Referenced by GiveOre::Apply().
 {
     if (player is null)
         return;
     amount = roll_round(amount * (player.m_record.GetModifiers().OreGainScale(player) + 0.2f * g_ngp));
     NetGiveOreImpl(amount, player);
     string strOreValue = "";
     if (amount == 1)
         strOreValue = Resources::GetString(".item.ore");
     else
     {
         dictionary params = { { "num", amount } };
         strOreValue = Resources::GetString(".item.ore.plural", params);
     }
     if (showFloatingText)
         AddFloatingText(FloatingTextType::Pickup, strOreValue, player.m_unit.GetPosition());
 }
NetGiveOreImpl()
void NetGiveOreImpl (int amount, PlayerBase@ player)
Definition at line 58 of file GiveOre.as.
Referenced by GiveOreImpl(), and PlayerHandler::PlayerGiveOre().
 {
     Stats::Add("ore-found", amount, player.m_record);
     Stats::Add("avg-ore-found", amount, player.m_record);
     auto gm = cast<Campaign>(g_gameMode);
     if (gm !is null)
     {
         ivec3 level = CalcLevel(gm.m_levelCount);
         Stats::Add("avg-ore-found-act-" + (level.x + 1), amount, player.m_record);
     }
     player.m_record.runOre += amount;
 }
SetWeaponInformation()
void GiveOreImpl::SetWeaponInformation (uint weapon)
Definition at line 57 of file GiveOre.as.
References m_effects, m_missEffects, m_weaponInfo, and PropagateWeaponInformation().
Referenced by PropagateWeaponInformation().
 {
Variable Documentation
m_amount
int m_amount
Definition at line 48 of file GiveOre.as.
m_pickup
bool m_pickup
Definition at line 49 of file GiveOre.as.