HoHDocs: scripts/GUI/GroupRectWidget.as File Reference
GroupRectWidget.as File Reference
Classes
class GroupRectWidget
Functions
GroupRectWidget RectWidget LoadGroupRectWidget (WidgetLoadingContext &ctx)
GroupRectWidget ()
Widget Clone () override
void LoadWidthHeight (WidgetLoadingContext &ctx, bool required=true) override
void Load (WidgetLoadingContext &ctx) override
void DoLayout (vec2 origin, vec2 parentSz) override
Variables
bool m_dynamicWidth
bool m_dynamicHeight
bool m_innerSz
Function Documentation
Clone()
Widget LoadGroupRectWidget::Clone () override
Definition at line 320 of file GroupRectWidget.as.
DoLayout()
void LoadGroupRectWidget::DoLayout (vec2 origin, vec2 parentSz) override
Definition at line 358 of file GroupRectWidget.as.
GroupRectWidget()
LoadGroupRectWidget::GroupRectWidget ()
Definition at line 315 of file GroupRectWidget.as.
Referenced by LoadGroupRectWidget().
Load()
void LoadGroupRectWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 332 of file GroupRectWidget.as.
LoadGroupRectWidget()
GroupRectWidget RectWidget LoadGroupRectWidget (WidgetLoadingContext & ctx)
Definition at line 111 of file GroupRectWidget.as.
References GroupRectWidget(), and GroupRectWidget::Load().
Referenced by BaseGameMode::BaseGameMode().
 {
     GroupRectWidget@ w = GroupRectWidget();
     w.Load(ctx);
     return w;
 }
LoadWidthHeight()
void LoadGroupRectWidget::LoadWidthHeight (WidgetLoadingContext & ctx, bool required = true) override
Definition at line 327 of file GroupRectWidget.as.
Variable Documentation
m_dynamicHeight
bool m_dynamicHeight
Definition at line 312 of file GroupRectWidget.as.
m_dynamicWidth
bool m_dynamicWidth
Definition at line 311 of file GroupRectWidget.as.
m_innerSz
bool m_innerSz
Definition at line 313 of file GroupRectWidget.as.