HoHDocs: scripts/GUI/HUD/HUDSpeedrun.as File Reference
HUDSpeedrun.as File Reference
Classes
class SpeedrunSplit
Functions
HUDSpeedrun (GUIBuilder@ b)
void Initialize ()
string FormattedTime (uint64 time)
vec4 ColorForSplit (SpeedrunSplit@ split)
string NameForSplit (SpeedrunSplit@ split)
void AddCurrentSplit ()
void ReloadSplits ()
void Save (SValueBuilder &builder)
void Load (SValue@ sval)
void End ()
void Update (int dt) override
void Draw (SpriteBatch &sb, int idt) override
Variables
class SpeedrunSplit m_initialized
bool m_finished
uint64 m_totalTime
array< SpeedrunSplit@> m_splits
Widget m_wContainer
TextWidget m_wTotalTime
Widget m_wSplits
Widget m_wSplitTemplate
TextWidget m_wCurrentTime
SpeedrunSplit m_currentSplit
Function Documentation
AddCurrentSplit()
void AddCurrentSplit ()
Definition at line 94 of file HUDSpeedrun.as.
References g_gameMode, and m_splits.
Referenced by Initialize(), and Load().
     {
         auto newSplit = SpeedrunSplit();
         newSplit.m_time = 0;
         newSplit.m_levelCount = cast<Campaign>(g_gameMode).m_levelCount;
         newSplit.m_shortcut = (cast<ShortcutLevel>(g_gameMode) !is null);
         m_splits.insertLast(newSplit);
     }
ColorForSplit()
vec4 ColorForSplit (SpeedrunSplit@ split)
Definition at line 51 of file HUDSpeedrun.as.
References CalcLevel(), SpeedrunSplit::m_levelCount, and SpeedrunSplit::m_shortcut.
Referenced by ReloadSplits().
     {
         float alpha = 0.25f;
         if (split.m_shortcut)
             return vec4(0.2f, 0.2f, 0.2f, alpha);
         ivec3 level = CalcLevel(split.m_levelCount);
         switch (level.x)
         {
             case 0: return vec4(0.5f, 0.5f, 0.5f, alpha); // mines
             case 1: return vec4(0.2f, 0.2f, 0.7f, alpha); // prison
             case 2: return vec4(0.7f, 0.2f, 0.2f, alpha); // armory
             case 3: return vec4(0.2f, 0.7f, 0.2f, alpha); // archives
             case 4: return vec4(0.7f, 0.7f, 0.2f, alpha); // chambers
             case 5: return vec4(0.9f, 0.0f, 0.0f, alpha); // top
         }
         return vec4(0.0f, 0.0f, 0.0f, alpha);
     }
Draw()
void Draw (SpriteBatch & sb, int idt) override
Definition at line 223 of file HUDSpeedrun.as.
References FormattedTime(), g_gameMode, IsPaused(), m_currentSplit, m_finished, AGameMode::m_gameTime, m_splits, SpeedrunSplit::m_time, m_wCurrentTime, m_wTotalTime, and TextWidget::SetText().
     {
         if (IsPaused())
             idt = 0;
         if (!m_finished && m_wCurrentTime !is null && m_currentSplit !is null)
         {
             m_currentSplit.m_time = g_gameMode.m_gameTime + idt;
             m_wCurrentTime.SetText(FormattedTime(m_currentSplit.m_time));
         }
         if (m_wTotalTime !is null)
         {
             uint64 totalTime = 0;
             for (uint i = 0; i < m_splits.length(); i++)
                 totalTime += m_splits[i].m_time;
             m_wTotalTime.SetText(FormattedTime(totalTime));
         }
         IWidgetHoster::Draw(sb, idt);
     }
End()
void End ()
Definition at line 175 of file HUDSpeedrun.as.
References FormattedTime(), m_finished, m_splits, and NameForSplit().
     {
         m_finished = true;
         uint64 totalTime = 0;
         for (uint i = 0; i < m_splits.length(); i++)
             totalTime += m_splits[i].m_time;
         print("-----------------------");
         print("Speedrun results:");
         print("  Total time: " + FormattedTime(totalTime));
         print("  Splits:");
         for (uint i = 0; i < m_splits.length(); i++)
         {
             auto split = m_splits[i];
             print("    " + NameForSplit(split) + ": " + FormattedTime(split.m_time));
         }
     }
FormattedTime()
string FormattedTime (uint64 time)
Definition at line 46 of file HUDSpeedrun.as.
References formatTime().
Referenced by Draw(), End(), and ReloadSplits().
     {
         return formatTime(time / 1000.0f, true);
     }
HUDSpeedrun()
HUDSpeedrun (GUIBuilder@ b)
Definition at line 25 of file HUDSpeedrun.as.
References LoadWidget().
Referenced by Campaign::Campaign().
     {
         LoadWidget(b, "gui/speedrun.gui");
     }
Initialize()
void Initialize ()
Definition at line 30 of file HUDSpeedrun.as.
References AddCurrentSplit(), m_splits, m_wContainer, m_widget, m_wSplits, m_wSplitTemplate, m_wTotalTime, and ReloadSplits().
Referenced by Load(), and Update().
     {
         @m_wContainer = m_widget.GetWidgetById("container");
         @m_wTotalTime = cast<TextWidget>(m_widget.GetWidgetById("total-time"));
         @m_wSplits = m_widget.GetWidgetById("splits");
         @m_wSplitTemplate = m_widget.GetWidgetById("split-template");
         if (m_splits.length() == 0)
         {
             AddCurrentSplit();
             ReloadSplits();
         }
     }
Load()
void Load (SValue@ sval)
Definition at line 150 of file HUDSpeedrun.as.
References AddCurrentSplit(), Initialize(), m_initialized, m_splits, m_totalTime, and ReloadSplits().
     {
         if (!m_initialized)
             Initialize();
         m_totalTime = parseUInt(GetParamString(UnitPtr(), sval, "total-time"));
         m_splits.removeRange(0, m_splits.length());
         auto arrSplits = GetParamArray(UnitPtr(), sval, "splits");
         for (uint i = 0; i < arrSplits.length(); i++)
         {
             auto svSplit = arrSplits[i];
             auto newSplit = SpeedrunSplit();
             newSplit.m_time = parseUInt(GetParamString(UnitPtr(), svSplit, "time"));
             newSplit.m_levelCount = GetParamInt(UnitPtr(), svSplit, "level");
             newSplit.m_shortcut = GetParamBool(UnitPtr(), svSplit, "shortcut");
             m_splits.insertLast(newSplit);
         }
         AddCurrentSplit();
         ReloadSplits();
     }
NameForSplit()
string NameForSplit (SpeedrunSplit@ split)
Definition at line 71 of file HUDSpeedrun.as.
References CalcLevel(), SpeedrunSplit::m_levelCount, and SpeedrunSplit::m_shortcut.
Referenced by End(), and ReloadSplits().
     {
         if (split.m_shortcut)
             return "Shortcut";
         ivec3 level = CalcLevel(split.m_levelCount);
         string act = "???";
         switch (level.x)
         {
             case 0: act = "Mines"; break;
             case 1: act = "Prison"; break;
             case 2: act = "Armory"; break;
             case 3: act = "Archives"; break;
             case 4: act = "Chambers"; break;
             case 5: act = "Top"; break;
         }
         if (level.y == 3)
             return act + " Boss";
         else
             return act + " " + (level.y + 1);
     }
ReloadSplits()
void ReloadSplits ()
Definition at line 103 of file HUDSpeedrun.as.
References Widget::AddChild(), Widget::ClearChildren(), Widget::Clone(), ColorForSplit(), FormattedTime(), m_currentSplit, m_splits, m_wCurrentTime, m_wSplits, m_wSplitTemplate, and NameForSplit().
Referenced by Initialize(), and Load().
     {
         @m_wCurrentTime = null;
         m_wSplits.ClearChildren();
         for (uint i = 0; i < m_splits.length(); i++)
         {
             auto split = m_splits[i];
             auto wNewSplit = cast<RectWidget>(m_wSplitTemplate.Clone());
             wNewSplit.SetID("");
             wNewSplit.m_visible = true;
             wNewSplit.m_color = tocolor(ColorForSplit(split));
             auto wName = cast<TextWidget>(wNewSplit.GetWidgetById("name"));
             if (wName !is null)
                 wName.SetText(NameForSplit(split));
             auto wTime = cast<TextWidget>(wNewSplit.GetWidgetById("time"));
             if (wTime !is null)
             {
                 wTime.SetText(FormattedTime(split.m_time));
                 @m_wCurrentTime = wTime;
             }
             m_wSplits.AddChild(wNewSplit, 0);
             @m_currentSplit = split;
         }
     }
Save()
void Save (SValueBuilder & builder)
Definition at line 134 of file HUDSpeedrun.as.
References m_splits, and m_totalTime.
     {
         builder.PushString("total-time", "" + m_totalTime);
         builder.PushArray("splits");
         for (uint i = 0; i < m_splits.length(); i++)
         {
             auto split = m_splits[i];
             builder.PushDictionary();
             builder.PushString("time", "" + split.m_time);
             builder.PushInteger("level", split.m_levelCount);
             builder.PushBoolean("shortcut", split.m_shortcut);
             builder.PopDictionary();
         }
         builder.PopArray();
     }
Update()
void Update (int dt) override
Definition at line 194 of file HUDSpeedrun.as.
References DoLayout(), Initialize(), Widget::m_height, m_initialized, Widget::m_visible, m_wContainer, and m_wSplits.
     {
         if (!m_initialized)
         {
             m_initialized = true;
             Initialize();
         }
         int runType = GetVarInt("ui_speedrun");
         if (runType == 1)
         {
             bool updateLayout = (m_wSplits.m_visible == true);
             m_wContainer.m_height = 14;
             m_wSplits.m_visible = false;
             if (updateLayout)
                 DoLayout();
         }
         else
         {
             bool updateLayout = (m_wSplits.m_visible == false);
             m_wContainer.m_height = 214;
             m_wSplits.m_visible = true;
             if (updateLayout)
                 DoLayout();
         }
         IWidgetHoster::Update(dt);
     }
Variable Documentation
m_currentSplit
SpeedrunSplit m_currentSplit
Definition at line 23 of file HUDSpeedrun.as.
Referenced by Draw(), and ReloadSplits().
m_finished
bool m_finished
Definition at line 11 of file HUDSpeedrun.as.
Referenced by Draw(), End(), Stats::GetNumRewarded(), and Stats::Accomplishment::OnUpdated().
m_initialized
class SpeedrunSplit m_initialized
Referenced by Load(), and Update().
m_splits
array<SpeedrunSplit@> m_splits
Definition at line 14 of file HUDSpeedrun.as.
Referenced by AddCurrentSplit(), Draw(), End(), Initialize(), Load(), ReloadSplits(), and Save().
m_totalTime
uint64 m_totalTime
Definition at line 13 of file HUDSpeedrun.as.
Referenced by Load(), and Save().
m_wContainer
Widget m_wContainer
Definition at line 16 of file HUDSpeedrun.as.
Referenced by Initialize(), and Update().
m_wCurrentTime
TextWidget m_wCurrentTime
Definition at line 22 of file HUDSpeedrun.as.
Referenced by Draw(), and ReloadSplits().
m_wSplits
Widget m_wSplits
Definition at line 19 of file HUDSpeedrun.as.
Referenced by Initialize(), ReloadSplits(), and Update().
m_wSplitTemplate
Widget m_wSplitTemplate
Definition at line 20 of file HUDSpeedrun.as.
Referenced by Initialize(), and ReloadSplits().
m_wTotalTime
TextWidget m_wTotalTime
Definition at line 17 of file HUDSpeedrun.as.
Referenced by Draw(), and Initialize().