HoHDocs: scripts/Behaviors/Actions/HwSpawnUnit.as File Reference
HwSpawnUnit.as File Reference
Classes
class HwSpawnUnitEntry
Functions
HwSpawnUnit (UnitPtr unit, SValue &params)
bool NeedNetParams ()
void SetWeaponInformation (uint weapon)
bool DoAction (SValueBuilder@ builder, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity)
int GetProducer ()
void DoSpawnUnit (SValueBuilder@ builder, vec2 pos)
bool NetDoAction (SValue@ param, Actor@ owner, vec2 pos, vec2 dir)
void Update (int dt, int cooldown)
Variables
class HwSpawnUnitEntry m_entries
int m_spawnDist
bool m_safeSpawning
bool m_aggro
Function Documentation
DoAction()
bool DoAction (SValueBuilder@ builder, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity)
Definition at line 36 of file HwSpawnUnit.as.
References DoSpawnUnit(), g_scene, m_safeSpawning, m_spawnDist, and Actor::m_unit.
     {
         dir *= m_spawnDist;
         if (!m_safeSpawning)
             DoSpawnUnit(builder, pos + dir);
         else
         {
             if (m_spawnDist == 0)
             {
                 bool canSpawn = true;
                 auto res = g_scene.QueryRect(pos, 1, 1, ~0, RaycastType::Shot);
                 for (uint i = 0; i < res.length; i++)
                 {
                     if (owner.m_unit != res[i])
                     {
                         canSpawn = false;
                         break;
                     }
                 }
                 if (canSpawn)
                     DoSpawnUnit(builder, pos);
                 else
                     builder.PushNull();
             }
             else
             {
                 if (!g_scene.RaycastQuick(pos, pos + dir, ~0, RaycastType::Shot))
                     DoSpawnUnit(builder, pos + dir);
                 else if (!g_scene.RaycastQuick(pos, vec2(pos.x, pos.y - m_spawnDist), ~0, RaycastType::Shot))
                     DoSpawnUnit(builder, vec2(pos.x, pos.y - m_spawnDist));
                 else if (!g_scene.RaycastQuick(pos, vec2(pos.x, pos.y + m_spawnDist), ~0, RaycastType::Shot))
                     DoSpawnUnit(builder, vec2(pos.x, pos.y + m_spawnDist));
                 else if (!g_scene.RaycastQuick(pos, vec2(pos.x - m_spawnDist, pos.y), ~0, RaycastType::Shot))
                     DoSpawnUnit(builder, vec2(pos.x - m_spawnDist, pos.y));
                 else if (!g_scene.RaycastQuick(pos, vec2(pos.x + m_spawnDist, pos.y), ~0, RaycastType::Shot))
                     DoSpawnUnit(builder, vec2(pos.x + m_spawnDist, pos.y));
                 else
                     builder.PushNull();
             }
         }
         return true;
     }
DoSpawnUnit()
void DoSpawnUnit (SValueBuilder@ builder, vec2 pos)
Definition at line 95 of file HwSpawnUnit.as.
References g_scene, GetProducer(), IsNetsyncedExistance(), m_aggro, m_entries, HwSpawnUnitEntry::m_prod, unit, and xyz().
Referenced by DoAction().
     {
         int iProd = GetProducer();
         if (iProd < 0)
             return; // ???
         auto prod = m_entries[iProd].m_prod;
         UnitPtr unit = prod.Produce(g_scene, xyz(pos));
         bool needNetSync = !IsNetsyncedExistance(prod.GetNetSyncMode());
         if (m_aggro)
         {
             auto enemyBehavior = cast<CompositeActorBehavior>(unit.GetScriptBehavior());
             if (enemyBehavior !is null)
                 enemyBehavior.Configure(true, false, false);
         }
         if (needNetSync)
         {
             builder.PushArray();
             builder.PushInteger(iProd);
             builder.PushVector2(pos);
             builder.PushInteger(unit.GetId());
             builder.PopArray();
         }
         else
             builder.PushNull();
     }
GetProducer()
int GetProducer ()
Definition at line 82 of file HwSpawnUnit.as.
References HwSpawnUnitEntry::m_chance, and m_entries.
Referenced by DoSpawnUnit().
     {
         int n = randi(1000);
         for (uint i = 0; i < m_entries.length(); i++)
         {
             auto entry = m_entries[i];
             n -= entry.m_chance;
             if (n < 0)
                 return i;
         }
         return -1;
     }
HwSpawnUnit()
HwSpawnUnit (UnitPtr unit, SValue & params)
Definition at line 14 of file HwSpawnUnit.as.
References m_aggro, m_entries, m_safeSpawning, m_spawnDist, and unit.
     {
         array<SValue@>@ arr = GetParamArray(unit, params, "units", false);
         if (arr !is null)
         {
             for (uint i = 0; i < arr.length(); i += 2)
             {
                 auto entry = HwSpawnUnitEntry();
                 entry.m_chance = arr[i].GetInteger();
                 @entry.m_prod = Resources::GetUnitProducer(arr[i+1].GetString());
                 m_entries.insertLast(entry);
             }
         }
         m_safeSpawning = GetParamBool(unit, params, "safe-spawn", false);
         m_spawnDist = GetParamInt(unit, params, "spawn-dist", false);
         m_aggro = GetParamBool(unit, params, "aggro", false, false);
     }
NeedNetParams()
bool NeedNetParams ()
Definition at line 33 of file HwSpawnUnit.as.
 { return true; }
NetDoAction()
bool NetDoAction (SValue@ param, Actor@ owner, vec2 pos, vec2 dir)
Definition at line 125 of file HwSpawnUnit.as.
References g_scene, m_entries, HwSpawnUnitEntry::m_prod, and xyz().
     {
         if (param.GetType() == SValueType::Array)
         {
             array<SValue@>@ p = param.GetArray();
             if (p is null)
                 return false; // This means GetProducer() returned < 0 on the server
             int iProd = p[0].GetInteger();
             if (iProd < 0 || iProd >= int(m_entries.length()))
                 return false;
             m_entries[iProd].m_prod.Produce(g_scene, xyz(p[1].GetVector2()), p[2].GetInteger());
         }
         return true;
     }
SetWeaponInformation()
void SetWeaponInformation (uint weapon)
Definition at line 34 of file HwSpawnUnit.as.
 {}
Update()
void Update (int dt, int cooldown)
Definition at line 145 of file HwSpawnUnit.as.
     {
     }
Variable Documentation
m_aggro
bool m_aggro
Definition at line 12 of file HwSpawnUnit.as.
Referenced by DoSpawnUnit(), and HwSpawnUnit().
m_entries
class HwSpawnUnitEntry m_entries
Referenced by DoSpawnUnit(), GetProducer(), HwSpawnUnit(), and NetDoAction().
m_safeSpawning
bool m_safeSpawning
Definition at line 11 of file HwSpawnUnit.as.
Referenced by DoAction(), and HwSpawnUnit().
m_spawnDist
int m_spawnDist
Definition at line 10 of file HwSpawnUnit.as.
Referenced by DoAction(), and HwSpawnUnit().