HoHDocs: scripts/Behaviors/IDamageTaker.as File Reference
IDamageTaker.as File Reference
Classes
class DamageInfo
class DecimateInfo
class ADamageTaker
Enumerations
enum DamageType {
TRAP = 1, PIERCING = 2, BLUNT = 4, EXPLOSION = 8,
BIO = 16, FIRE = 32, ENERGY = 64, FROST = 128
}
Functions
CleaveInfo LoadCleave (SValue &dat, string prefix="")
class DamageInfo GetParamDamageType (UnitPtr owner, SValue@ params, string name, bool required=true, uint8 def=uint8(DamageType::PIERCING))
DamageInfo ()
DamageInfo (uint8 dmgType, Actor@ attacker, int16 dmg, bool melee, bool canKill, uint weapon)
DamageInfo (Actor@ attacker, int32 physDmg, int magicDmg, bool melee, bool canKill, uint weapon)
class DecimateInfo Decimate (DecimateInfo dec, vec2 pos, vec2 dir)
DecimateInfo (Actor@ attacker, float hpCurr, float hpMax, float manaCurr, float manaMax, uint weapon)
void NetDecimate (int hp, int mana)
int Damage (DamageInfo dmg, vec2 pos, vec2 dir)
void NetDamage (DamageInfo dmg, vec2 pos, vec2 dir)
bool Impenetrable ()
bool ShootThrough (vec2 pos, vec2 dir)
bool IsDead ()
bool Ricochets ()
Variables
enum DamageType Range
float PhysicalDamageMul
int32 PhysicalDamageAdd
float MagicalDamageMul
int32 MagicalDamageAdd
UnitScene Effect
uint8 DamageType
int32 Damage
Actor Attacker
int32 PhysicalDamage
int32 MagicalDamage
int32 DamageDealt
bool Melee
bool CanKill
uint Weapon
int Crit
vec2 ArmorMul
float LifestealMul
bool TrueStrike
CleaveInfo Cleave
float HealthCurr
float HealthMax
float ManaCurr
float ManaMax
Enumeration Type Documentation
DamageType
enum DamageType
Enumerator
TRAP
PIERCING
BLUNT
EXPLOSION
BIO
FIRE
ENERGY
FROST
Definition at line 1 of file IDamageTaker.as.
 {
     //HEAL      =   0,
     TRAP        =   1,
     PIERCING    =   2,
     BLUNT       =   4,
     EXPLOSION   =   8,
     BIO         =  16,
     FIRE        =  32,
     ENERGY      =  64,
     FROST       = 128,
 }
Function Documentation
Damage()
int Damage (DamageInfo dmg, vec2 pos, vec2 dir) override
Definition at line 472 of file CompositeActorBehavior.as.
References Actor::AddFloatingHurt(), Actor::AddFloatingImmortal(), ApplyArmorParts(), DamageInfo::ArmorMul, DamageInfo::Attacker, DamageInfo::CanKill, DamageInfo::Cleave, ActorBuffList::Cleave(), DamageInfo::Damage, damage_round(), DamageInfo::DamageDealt, DamageInfo(), ActorBuffList::DamageTakenMul(), g_scene, GetArmor(), GetMaxHp(), Actor::IsImmortal(), m_buffs, m_dmgColor, m_evadeChance, m_evadeFx, m_hitFx, m_hp, m_immortalSound, m_skills, m_unit, DamageInfo::MagicalDamage, max, min, Actor::NetDamage(), Actor::NetHeal(), UnitHandler::NetSendUnitDamaged(), OnDamaged, OnDeath(), DamageInfo::PhysicalDamage, PlayEffect(), PlaySound3D(), DamageInfo::TrueStrike, and xy().
     {
         if (m_hp <= 0)
             return 0;
         if (dmg.Cleave is null)
             @dmg.Cleave = m_buffs.Cleave();
         auto localPlayer = cast<Player>(dmg.Attacker);
         if (localPlayer !is null)
             dmg = localPlayer.DamageActor(this, dmg);
         if (!dmg.TrueStrike)
         {
             bool evaded = false;
             if (dmg.PhysicalDamage > 0 && randf() <= m_evadeChance.x)
             {
                 dmg.PhysicalDamage = 0;
                 evaded = true;
             }
             if (dmg.MagicalDamage > 0 && randf() <= m_evadeChance.y)
             {
                 dmg.MagicalDamage = 0;
                 evaded = true;
             }
             if (evaded)
                 PlayEffect(m_evadeFx, m_unit.GetPosition());
             if (dmg.PhysicalDamage == 0 && dmg.MagicalDamage == 0)
                 return 0;
         }
         vec2 dmgAmntParts = ApplyArmorParts(dmg, GetArmor() * dmg.ArmorMul, m_buffs.DamageTakenMul());
         int dmgAmnt = max(0, damage_round(dmgAmntParts.x + dmgAmntParts.y));
         if (!dmg.CanKill && floor(m_hp * float(GetMaxHp())) - dmgAmnt <= 0)
             dmgAmnt = 0;
         if (dmgAmnt > 0)
         {
             DamageInfo di = dmg;
             di.Damage = dmgAmnt;
             di.PhysicalDamage = damage_round(dmgAmntParts.x);
             di.MagicalDamage = damage_round(dmgAmntParts.y);
             if (!IsImmortal())
             {
                 float maxHp = float(GetMaxHp());
                 di.DamageDealt = int(min(m_hp, float(di.Damage) / maxHp) * maxHp);
                 if (localPlayer !is null)
                     localPlayer.DamagedActor(this, di);
                 NetDamage(di, pos, dir);
                 //m_movement.OnDamaged(dmg);
                 PlayEffect(m_hitFx, pos);
                 for (uint i = 0; i < m_skills.length(); i++)
                     m_skills[i].OnDamaged();
                 //AddFloatingHurt(dmgAmnt);
                 UnitHandler::NetSendUnitDamaged(m_unit, dmgAmnt, pos, dir, di.Attacker);
                 if (dmg.Cleave !is null && dmg.Cleave.Range > 0)
                 {
                     int pd = damage_round(di.PhysicalDamage * dmg.Cleave.PhysicalDamageMul) + dmg.Cleave.PhysicalDamageAdd;
                     int md = damage_round(di.MagicalDamage * dmg.Cleave.MagicalDamageMul) + dmg.Cleave.MagicalDamageAdd;
                     auto cleaveDmg = DamageInfo(null, pd, md, false, true, 0);
                     @cleaveDmg.Cleave = CleaveInfo();
                     auto results = g_scene.QueryCircle(pos, dmg.Cleave.Range, ~0, RaycastType::Shot, true);
                     for (uint i = 0; i < results.length(); i++)
                     {
                         auto dmgTaker = cast<IDamageTaker>(results[i].GetScriptBehavior());
                         if (dmgTaker !is null && dmgTaker !is dmg.Attacker && dmgTaker !is this)
{
                             auto dpos = xy(results[i].GetPosition());
                             dmgTaker.Damage(cleaveDmg, dpos, normalize(dpos - pos));
                             PlayEffect(dmg.Cleave.Effect, dpos);
                         }
                     }
                 }
             }
             else
             {
                 AddFloatingImmortal(0);
                 PlaySound3D(m_immortalSound, m_unit.GetPosition());
             }
             m_dmgColor = 1.0;
             if (m_hp <= 0)
                 OnDeath(di, dir);
         }
         else if (dmgAmnt < 0)
         {
             if (m_hp < 1.0)
             {
                 NetHeal(-dmgAmnt);
                 (Network::Message("UnitHealed") << m_unit << -dmgAmnt).SendToAll();
             }
         }
         else
             AddFloatingHurt(0);
         return dmgAmnt;
     }
DamageInfo() [1/3]
GetParamDamageType::DamageInfo ()
Definition at line 43 of file IDamageTaker.as.
Referenced by Damage(), Modifiers::Thorns::DamageTaken(), DoDamageUnits(), GiveHealthCFunc(), CannonBall::HitUnit(), Player::Kill(), Kill(), NetKill(), ChargeMovement::OnCollide(), WorldScript::RandomBuff::OnFunc(), Player::SoulLinkKill(), and PriestGroundCircle::Trigger().
 {
     uint8 DamageType;
     int32 Damage;
DamageInfo() [2/3]
GetParamDamageType::DamageInfo (uint8 dmgType, Actor@ attacker, int16 dmg, bool melee, bool canKill, uint weapon)
Definition at line 54 of file IDamageTaker.as.
     {
DamageInfo() [3/3]
GetParamDamageType::DamageInfo (Actor@ attacker, int32 physDmg, int magicDmg, bool melee, bool canKill, uint weapon)
Definition at line 68 of file IDamageTaker.as.
     {
         DamageType = dmgType;
         @Attacker = attacker;
         PhysicalDamage = dmg;
         Melee = melee;
Decimate()
class DecimateInfo Decimate (DecimateInfo dec, vec2 pos, vec2 dir) override
Definition at line 456 of file CompositeActorBehavior.as.
References Actor::AddFloatingHurt(), clamp(), EnemyHurtLocal, GetMaxHp(), DecimateInfo::HealthCurr, DecimateInfo::HealthMax, m_hp, and m_unit.
     {
         int maxHp = GetMaxHp();
         int preHp = int(m_hp * maxHp);
         float new = clamp((m_hp - dec.HealthMax) * (1.0f - dec.HealthCurr), 0.0f, 1.0f);
         m_hp = new;
         assert(m_hp, new);
         int dmgAmnt = preHp - int(m_hp * maxHp);
         AddFloatingHurt(dmgAmnt, 0, FloatingTextType::EnemyHurtLocal);
         (Network::Message("UnitDecimated") << m_unit << dmgAmnt << 0).SendToAll();
         return dmgAmnt;
     }
DecimateInfo()
Decimate::DecimateInfo (Actor@ attacker, float hpCurr, float hpMax, float manaCurr, float manaMax, uint weapon)
Definition at line 35 of file IDamageTaker.as.
Referenced by Decimate::Apply().
 {
GetParamDamageType()
class DamageInfo GetParamDamageType (UnitPtr owner, SValue@ params, string name, bool required = true, uint8 def = uint8(DamageType::PIERCING))
Definition at line 108 of file IDamageTaker.as.
References BIO, BLUNT, ENERGY, EXPLOSION, FIRE, FROST, name, PIERCING, and TRAP.
Referenced by ActorBuffDef(), and HitscanSpread().
 {
     string dt = GetParamString(owner, params, name, required, "");
     if (dt == "")
         return def;
     uint8 ret = 0;
     auto dts = dt.split(" ");
     for (uint i = 0; i < dts.length(); i++)
     {
         if (dts[i] == "heal")
             return 0;
         else if (dts[i] == "trap")
             ret |= uint8(DamageType::TRAP);
         else if (dts[i] == "pierce")
             ret |= uint8(DamageType::PIERCING);
         else if (dts[i] == "piercing")
             ret |= uint8(DamageType::PIERCING);
         else if (dts[i] == "blunt")
             ret |= uint8(DamageType::BLUNT);
         else if (dts[i] == "explosion")
             ret |= uint8(DamageType::EXPLOSION);
         else if (dts[i] == "bio")
             ret |= uint8(DamageType::BIO);
         else if (dts[i] == "fire")
             ret |= uint8(DamageType::FIRE);
         else if (dts[i] == "energy")
             ret |= uint8(DamageType::ENERGY);
         else if (dts[i] == "frost")
             ret |= uint8(DamageType::FROST);
         else
             print("Damage type not found: " + dts[i]);
     }
     return ret;
 }
Impenetrable()
bool Impenetrable () override
Definition at line 416 of file CompositeActorBehavior.as.
References m_impenetrable.
 { return m_impenetrable; }
IsDead()
bool IsDead () override
Definition at line 703 of file CompositeActorBehavior.as.
References m_dead, and m_hp.
Referenced by BaseGameMode::AttemptRespawn(), CondPlayersGreater(), BossEye::FindWispTargets(), BaseGameMode::GetPlayersAlive(), WorldScript::AllPlayersAreaTrigger::IsEveryoneInside(), WorldScript::CheckPlayerCount::ServerExecute(), BaseGameMode::SpectateNextPlayer(), and Miniboss::Update().
 { return m_hp <= 0 || m_dead; }
LoadCleave()
CleaveInfo LoadCleave (SValue & dat, string prefix = "")
Definition at line 26 of file IDamageTaker.as.
Referenced by ActorBuffDef(), and Damage::Damage().
 {
     SValue@ params = GetParamDictionary(UnitPtr(), dat, prefix + "cleave", false);
     if (params is null)
         return null;
     CleaveInfo cleave;
     cleave.Range = GetParamInt(UnitPtr(), params, "range");
     cleave.PhysicalDamageAdd = GetParamInt(UnitPtr(), params, "physical", false, 0);
     cleave.PhysicalDamageMul = GetParamFloat(UnitPtr(), params, "physical-mul", false, 0);
     cleave.MagicalDamageAdd = GetParamInt(UnitPtr(), params, "magical", false, 0);
     cleave.MagicalDamageMul = GetParamFloat(UnitPtr(), params, "magical-mul", false, 0);
     string fx = GetParamString(UnitPtr(), params, "fx", false);
     if (fx != "")
         @cleave.Effect = Resources::GetEffect(fx);
     return cleave;
 }
NetDamage()
void NetDamage (DamageInfo dmg, vec2 pos, vec2 dir) override
Definition at line 592 of file CompositeActorBehavior.as.
References Actor::AddFloatingHurt(), DamageInfo::Attacker, DamageInfo::Crit, DamageInfo::Damage, EnemyHurtHusk, EnemyHurtLocal, g_team_player, GetLocalPlayer(), GetMaxHp(), Actor::IsDead(), m_gore, m_hp, m_hurtSound, m_movement, m_target, m_unit, PlaySound3D(), SetTarget(), and Actor::Team.
Referenced by Miniboss::NetDamage().
     {
         //if (m_hp <= 0)
         //  return;
         if (Network::IsServer())
         {
             if (dmg.Attacker !is null && !dmg.Attacker.IsDead())
                 if (m_target is null || (dmg.Attacker.Team == g_team_player && m_target.Team != g_team_player))
                     SetTarget(dmg.Attacker);
         }
         m_hp = float(m_hp) - float(dmg.Damage) / float(GetMaxHp());
         m_movement.OnDamaged(dmg);
         if (dmg.Attacker !is null && dmg.Attacker is GetLocalPlayer())
             AddFloatingHurt(dmg.Damage, dmg.Crit, FloatingTextType::EnemyHurtLocal);
         else
             AddFloatingHurt(dmg.Damage, dmg.Crit, FloatingTextType::EnemyHurtHusk);
         //if (m_hp <= 0)
         //  OnDeath(dmg, dir);
         if (m_hp > 0)
         {
             PlaySound3D(m_hurtSound, m_unit.GetPosition());
             if (m_gore !is null)
                 m_gore.OnHit(float(dmg.Damage) / float(GetMaxHp()), pos, atan(dir.y, dir.x));
         }
     }
NetDecimate()
void NetDecimate (int hp, int mana) override
Definition at line 450 of file CompositeActorBehavior.as.
References Actor::AddFloatingHurt(), EnemyHurtHusk, GetMaxHp(), and m_hp.
     {
         m_hp = float(m_hp) - float(hp) / float(GetMaxHp());
         AddFloatingHurt(hp, 0, FloatingTextType::EnemyHurtHusk);
     }
Ricochets()
bool Ricochets ()
ShootThrough()
bool ShootThrough (vec2 pos, vec2 dir)
Variable Documentation
ArmorMul
vec2 ArmorMul
Definition at line 38 of file IDamageTaker.as.
Attacker
Actor Attacker
Definition at line 30 of file IDamageTaker.as.
CanKill
bool CanKill
Definition at line 35 of file IDamageTaker.as.
Referenced by DangerArea::Initialize().
Cleave
CleaveInfo Cleave
Definition at line 41 of file IDamageTaker.as.
Crit
int Crit
Definition at line 37 of file IDamageTaker.as.
Damage
int32 Damage
Definition at line 28 of file IDamageTaker.as.
Referenced by TransferDamageActor::Damage(), and DangerArea::Initialize().
DamageDealt
int32 DamageDealt
Definition at line 33 of file IDamageTaker.as.
DamageType
uint8 DamageType
Definition at line 27 of file IDamageTaker.as.
Effect
UnitScene Effect
Definition at line 23 of file IDamageTaker.as.
Referenced by Fountain::AddWishFile().
HealthCurr
float HealthCurr
Definition at line 30 of file IDamageTaker.as.
HealthMax
float HealthMax
Definition at line 31 of file IDamageTaker.as.
LifestealMul
float LifestealMul
Definition at line 39 of file IDamageTaker.as.
MagicalDamage
int32 MagicalDamage
Definition at line 32 of file IDamageTaker.as.
MagicalDamageAdd
int32 MagicalDamageAdd
Definition at line 21 of file IDamageTaker.as.
MagicalDamageMul
float MagicalDamageMul
Definition at line 20 of file IDamageTaker.as.
ManaCurr
float ManaCurr
Definition at line 32 of file IDamageTaker.as.
ManaMax
float ManaMax
Definition at line 33 of file IDamageTaker.as.
Melee
bool Melee
Definition at line 34 of file IDamageTaker.as.
PhysicalDamage
int32 PhysicalDamage
Definition at line 31 of file IDamageTaker.as.
PhysicalDamageAdd
int32 PhysicalDamageAdd
Definition at line 19 of file IDamageTaker.as.
PhysicalDamageMul
float PhysicalDamageMul
Definition at line 18 of file IDamageTaker.as.
Range
enum DamageType Range
TrueStrike
bool TrueStrike
Definition at line 40 of file IDamageTaker.as.
Weapon
uint Weapon
Definition at line 36 of file IDamageTaker.as.