HoHDocs: scripts/Behaviors/Items/Item.as File Reference
Item.as File Reference
Classes
class Item
Functions
Item IUsable GiveItemImpl (ActorItem@ item, PlayerBase@ player, bool showFloatingText)
Item (UnitPtr unit, SValue &params)
void Initialize (ActorItem@ item)
SValue Save ()
void PostLoad (SValue@ data)
void Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther)
void EndCollision (UnitPtr unit, Fixture@ fxSelf, Fixture@ fxOther)
UnitPtr GetUseUnit ()
bool CanUse (PlayerBase@ player)
void Use (PlayerBase@ player)
void NetUse (PlayerHusk@ player)
UsableIcon GetIcon (Player@ player)
int UsePriority (IUsable@ other)
Variables
UnitPtr m_unit
ActorItem m_item
Function Documentation
CanUse()
bool GiveItemImpl::CanUse (PlayerBase@ player)
Definition at line 330 of file Item.as.
Collide()
void GiveItemImpl::Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther)
Definition at line 305 of file Item.as.
EndCollision()
void GiveItemImpl::EndCollision (UnitPtr unit, Fixture@ fxSelf, Fixture@ fxOther)
Definition at line 315 of file Item.as.
GetIcon()
UsableIcon GiveItemImpl::GetIcon (Player@ player)
Definition at line 345 of file Item.as.
GetUseUnit()
UnitPtr GiveItemImpl::GetUseUnit ()
Definition at line 325 of file Item.as.
GiveItemImpl()
Item IUsable GiveItemImpl (ActorItem@ item, PlayerBase@ player, bool showFloatingText)
Definition at line 125 of file Item.as.
References Stats::Add(), AddFloatingText(), PlayerBase::AddItem(), CalcLevel(), Common, Epic, g_gameMode, GetItemQualityName(), Legendary, PlayerBase::m_record, Pickup, PlaySound3D(), Rare, and Uncommon.
Referenced by PlayerHandler::PlayerGiveItem(), and Item::Use().
 {
     player.AddItem(item);
     Stats::Add("items-picked", 1, player.m_record);
     Stats::Add("items-picked-" + GetItemQualityName(item.quality), 1, player.m_record);
     Stats::Add("avg-items-picked", 1, player.m_record);
     auto gm = cast<Campaign>(g_gameMode);
     if (gm !is null)
     {
         ivec3 level = CalcLevel(gm.m_levelCount);
         Stats::Add("avg-items-picked-act-" + (level.x + 1), 1, player.m_record);
     }
     if (showFloatingText)
     {
         AddFloatingText(FloatingTextType::Pickup, Resources::GetString(item.name), player.m_unit.GetPosition() + vec3(0, -5, 0));
         vec3 pos = player.m_unit.GetPosition();
         if (item.quality == ActorItemQuality::Common)
             PlaySound3D(Resources::GetSoundEvent("event:/item/item_common"), pos);
         else if (item.quality == ActorItemQuality::Uncommon)
             PlaySound3D(Resources::GetSoundEvent("event:/item/item_uncommon"), pos);
         else if (item.quality == ActorItemQuality::Rare)
             PlaySound3D(Resources::GetSoundEvent("event:/item/item_rare"), pos);
         else if (item.quality == ActorItemQuality::Epic)
             PlaySound3D(Resources::GetSoundEvent("event:/item/item_epic"), pos);
         else if (item.quality == ActorItemQuality::Legendary)
             PlaySound3D(Resources::GetSoundEvent("event:/item/item_legendary"), pos);
     }
 }
Initialize()
void GiveItemImpl::Initialize (ActorItem@ item)
Definition at line 245 of file Item.as.
Item()
GiveItemImpl::Item (UnitPtr unit, SValue & params)
Definition at line 234 of file Item.as.
Referenced by ActorItems::AddItemFile(), and PlayerHandler::ModifierTriggerEffect().
NetUse()
void GiveItemImpl::NetUse (PlayerHusk@ player)
Definition at line 341 of file Item.as.
PostLoad()
void GiveItemImpl::PostLoad (SValue@ data)
Definition at line 290 of file Item.as.
Save()
SValue GiveItemImpl::Save ()
Definition at line 280 of file Item.as.
Use()
void GiveItemImpl::Use (PlayerBase@ player)
Definition at line 335 of file Item.as.
UsePriority()
int GiveItemImpl::UsePriority (IUsable@ other)
Definition at line 350 of file Item.as.
Variable Documentation
m_item
ActorItem m_item
Definition at line 232 of file Item.as.
m_unit
UnitPtr m_unit
Definition at line 231 of file Item.as.