HoHDocs: scripts/Behaviors/Actors/Player/PlayerRecord.as File Reference
PlayerRecord.as File Reference
Classes
class ClassStats
class OwnedItemSet
Functions
ScriptSprite GetFaceSprite (string charClass, int face)
Variables
bool g_downscaling = false
class ClassStats m_id
pint m_level
Upgrades::UpgradeStep m_step
class OwnedItemSet Paladin = 1
class OwnedItemSet Ranger = 2
class OwnedItemSet Sorcerer = 4
class OwnedItemSet Warlock = 8
class OwnedItemSet Thief = 16
class OwnedItemSet Priest = 32
Function Documentation
GetFaceSprite()
ScriptSprite GetFaceSprite (string charClass, int face)
Definition at line 3 of file PlayerRecord.as.
References ScriptSprite().
Referenced by GuildHallStatsTab::AddCharacterToList(), Initialize(), Menu::CharacterSelectionMenu::ReloadList(), MultiplePlayersTab::UpdateNow(), and CoopPlayerWidget::UpdatePortrait().
 {
     SValue@ svalClass = Resources::GetSValue("players/" + charClass + "/char.sval");
     if (svalClass is null)
     {
         PrintError("Couldn't get SValue file for class \"" + charClass + "\"");
         return null;
     }
     else
     {
         int faceY = GetParamInt(UnitPtr(), svalClass, "face-y");
         return ScriptSprite(Resources::GetTexture2D("gui/icons_faces.tif"), vec4(face * 24, faceY, 24, 24));
     }
 }
Variable Documentation
g_downscaling
bool g_downscaling = false
Definition at line 1 of file PlayerRecord.as.
Referenced by RandomLevel::Generate(), Titles::GetMaxClassTitleIndex(), DungeonSettingsMenu::OnFunc(), Campaign::Save(), GameModeHandler::SetDownscaling(), Campaign::Start(), and DungeonSettingsMenu::Update().
m_id
class ClassStats m_id
m_level
pint m_level
Definition at line 38 of file PlayerRecord.as.
m_step
Upgrades::UpgradeStep m_step
Definition at line 40 of file PlayerRecord.as.
Paladin
class OwnedItemSet Paladin = 1
Priest
class OwnedItemSet Priest = 32
Ranger
class OwnedItemSet Ranger = 2
Sorcerer
class OwnedItemSet Sorcerer = 4
Thief
class OwnedItemSet Thief = 16
Warlock
class OwnedItemSet Warlock = 8