HoHDocs: scripts/GameModes/RandomLevel.as File Reference
RandomLevel.as File Reference
Classes
class RandomLevel
Functions
RandomLevel Campaign DungeonLevelRichPresence (Campaign@ gm)
RandomLevel (Scene@ scene)
void Generate (SValue@ save)
void Start (uint8 peer, SValue@ save, StartMode sMode) override
void PostStart () override
Variables
EnemyPlacement m_enemyPlacer
Function Documentation
DungeonLevelRichPresence()
RandomLevel Campaign DungeonLevelRichPresence (Campaign@ gm)
Definition at line 93 of file RandomLevel.as.
References DiscordPresence::AddDetails(), CalcLevel(), DiscordPresence::Clear(), ServicePresence::Clear(), g_ngp, GetLocalPlayerRecord(), ServicePresence::Param(), RichPresenceGetActName(), ServicePresence::Set(), DiscordPresence::SetDetails(), DiscordPresence::SetLargeImageKey(), DiscordPresence::SetLargeImageText(), DiscordPresence::SetStartTimestamp(), and DiscordPresence::SetState().
Referenced by StaticLevel::Start(), and RandomLevel::Start().
 {
     auto record = GetLocalPlayerRecord();
     auto levelInfo = CalcLevel(gm.m_levelCount);
     DiscordPresence::Clear();
     DiscordPresence::SetState("In dungeon");
     DiscordPresence::SetDetails("Act " + (levelInfo.x + 1) + " floor " + (levelInfo.y + 1));
     if (g_ngp > 0)
         DiscordPresence::AddDetails(", NG+" + g_ngp);
     DiscordPresence::SetStartTimestamp(time() - record.statisticsSession.GetStatInt("time-played"));
     DiscordPresence::SetLargeImageKey("act_" + levelInfo.x);
     DiscordPresence::SetLargeImageText(RichPresenceGetActName(gm.m_levelCount));
     ServicePresence::Clear();
     if (g_ngp == 0)
         ServicePresence::Set("#Status_InDungeon");
     else
     {
         ServicePresence::Set("#Status_InDungeon_NGP");
         ServicePresence::Param("ngp", "" + g_ngp);
     }
     ServicePresence::Param("level", "" + record.level);
     ServicePresence::Param("act", "" + (levelInfo.x + 1));
     ServicePresence::Param("floor", "" + (levelInfo.y + 1));
 }
Generate()
void DungeonLevelRichPresence::Generate (SValue@ save)
Definition at line 551 of file RandomLevel.as.
PostStart()
void DungeonLevelRichPresence::PostStart () override
Definition at line 613 of file RandomLevel.as.
RandomLevel()
DungeonLevelRichPresence::RandomLevel (Scene@ scene)
Definition at line 546 of file RandomLevel.as.
Start()
void DungeonLevelRichPresence::Start (uint8 peer, SValue@ save, StartMode sMode) override
Definition at line 592 of file RandomLevel.as.
Variable Documentation
m_enemyPlacer
EnemyPlacement m_enemyPlacer
Definition at line 544 of file RandomLevel.as.