HoHDocs: scripts/GUI/Widgets/ScalableSpriteIconButtonWidget.as File Reference
ScalableSpriteIconButtonWidget.as File Reference
Classes
class ScalableSpriteIconButtonWidget
Functions
ScalableSpriteIconButtonWidget ScalableSpriteButtonWidget LoadScalableSpriteIconButtonWidget (WidgetLoadingContext &ctx)
ScalableSpriteIconButtonWidget ()
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void DoDraw (SpriteBatch &sb, vec2 pos) override
Variables
Sprite m_icon
int m_iconSpacing
bool m_iconAfterText
bool m_iconVisible
Function Documentation
Clone()
Widget LoadScalableSpriteIconButtonWidget::Clone () override
Definition at line 215 of file ScalableSpriteIconButtonWidget.as.
DoDraw()
void LoadScalableSpriteIconButtonWidget::DoDraw (SpriteBatch & sb, vec2 pos) override
Definition at line 235 of file ScalableSpriteIconButtonWidget.as.
Load()
void LoadScalableSpriteIconButtonWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 222 of file ScalableSpriteIconButtonWidget.as.
LoadScalableSpriteIconButtonWidget()
ScalableSpriteIconButtonWidget ScalableSpriteButtonWidget LoadScalableSpriteIconButtonWidget (WidgetLoadingContext & ctx)
Definition at line 61 of file ScalableSpriteIconButtonWidget.as.
References ScalableSpriteIconButtonWidget::Load(), and ScalableSpriteIconButtonWidget().
Referenced by BaseGameMode::BaseGameMode().
 {
     ScalableSpriteIconButtonWidget@ w = ScalableSpriteIconButtonWidget();
     w.Load(ctx);
     return w;
 }
ScalableSpriteIconButtonWidget()
LoadScalableSpriteIconButtonWidget::ScalableSpriteIconButtonWidget ()
Definition at line 210 of file ScalableSpriteIconButtonWidget.as.
Referenced by LoadScalableSpriteIconButtonWidget().
Variable Documentation
m_icon
Sprite m_icon
Definition at line 204 of file ScalableSpriteIconButtonWidget.as.
m_iconAfterText
bool m_iconAfterText
Definition at line 207 of file ScalableSpriteIconButtonWidget.as.
m_iconSpacing
int m_iconSpacing
Definition at line 205 of file ScalableSpriteIconButtonWidget.as.
m_iconVisible
bool m_iconVisible
Definition at line 208 of file ScalableSpriteIconButtonWidget.as.