HoHDocs: scripts/ScriptSprite.as File Reference
ScriptSprite.as File Reference
Classes
class ScriptSpriteFrame
Functions
ScriptSprite (array< SValue@>@ params)
ScriptSprite (Texture2D@ texture, vec4 frame)
ScriptSprite (TempTexture2D@ textureTemp, vec4 frame)
int GetWidth ()
int GetHeight ()
vec2 GetSize ()
vec4 GetFrame (int time)
void Draw (SpriteBatch &sb, vec2 pos, int time, vec4 color=vec4(1, 1, 1, 1))
void Draw (SpriteBatch &sb, vec2 pos, vec2 src, int time, vec4 color=vec4(1, 1, 1, 1))
void Draw (SpriteBatch &sb, vec4 dest, int time, vec4 color=vec4(1, 1, 1, 1))
void DrawWrapped (SpriteBatch &sb, vec2 pos, vec2 size, int time, vec4 color=vec4(1, 1, 1, 1))
void DrawWrapped (SpriteBatch &sb, vec4 dest, int time, vec4 color=vec4(1, 1, 1, 1))
void DrawRadial (SpriteBatch &sb, vec2 pos, float r, int time, vec4 color=vec4(1, 1, 1, 1))
Variables
class ScriptSpriteFrame m_texture
TempTexture2D m_textureTemp
array< ScriptSpriteFrame@> m_frames
int m_length
vec2 m_srcOffset
Function Documentation
Draw() [1/3]
void Draw (SpriteBatch & sb, vec2 pos, int time, vec4 color = vec4(1, 1, 1, 1))
Definition at line 84 of file ScriptSprite.as.
References GetFrame(), and m_texture.
     {
         vec4 frame = GetFrame(time);
         vec4 p = vec4(pos.x, pos.y, frame.z, frame.w);
         sb.DrawSprite(m_texture, p, frame, color);
     }
Draw() [2/3]
void Draw (SpriteBatch & sb, vec2 pos, vec2 src, int time, vec4 color = vec4(1, 1, 1, 1))
Definition at line 92 of file ScriptSprite.as.
References GetFrame(), and m_texture.
     {
         vec4 frame = GetFrame(time);
         vec4 p = vec4(pos.x, pos.y, src.x, src.y);
         sb.DrawSprite(m_texture, p, vec4(frame.x, frame.y, src.x, src.y), color);
     }
Draw() [3/3]
void Draw (SpriteBatch & sb, vec4 dest, int time, vec4 color = vec4(1, 1, 1, 1))
Definition at line 100 of file ScriptSprite.as.
References GetFrame(), and m_texture.
     {
         vec4 frame = GetFrame(time);
         sb.DrawSprite(m_texture, dest, frame, color);
     }
DrawRadial()
void DrawRadial (SpriteBatch & sb, vec2 pos, float r, int time, vec4 color = vec4(1, 1, 1, 1))
Definition at line 117 of file ScriptSprite.as.
References GetFrame(), and m_texture.
     {
         vec4 frame = GetFrame(time);
         vec4 p = vec4(pos.x, pos.y, frame.z, frame.w);
         sb.DrawSpriteRadial(m_texture, p, frame, r, color);
     }
DrawWrapped() [1/2]
void DrawWrapped (SpriteBatch & sb, vec2 pos, vec2 size, int time, vec4 color = vec4(1, 1, 1, 1))
Definition at line 106 of file ScriptSprite.as.
References GetFrame(), and m_texture.
Referenced by DrawWrapped().
     {
         vec4 frame = GetFrame(time);
         sb.DrawSpriteWrapped(m_texture, frame, pos, size, color);
     }
DrawWrapped() [2/2]
void DrawWrapped (SpriteBatch & sb, vec4 dest, int time, vec4 color = vec4(1, 1, 1, 1))
Definition at line 112 of file ScriptSprite.as.
References DrawWrapped().
     {
         DrawWrapped(sb, vec2(dest.x, dest.y), vec2(dest.z, dest.w), time, color);
     }
GetFrame()
vec4 GetFrame (int time)
Definition at line 63 of file ScriptSprite.as.
References m_frames, m_length, and m_srcOffset.
Referenced by Draw(), DrawRadial(), and DrawWrapped().
     {
         vec4 ret = m_frames[0].frame;
         time %= m_length;
         for (uint i = 0; i < m_frames.length(); i++)
         {
             time -= m_frames[i].time;
             if (time <= 0)
             {
                 ret = m_frames[i].frame;
                 break;
             }
         }
         ret.x += m_srcOffset.x;
         ret.y += m_srcOffset.y;
         return ret;
     }
GetHeight()
int GetHeight ()
Definition at line 53 of file ScriptSprite.as.
References m_frames.
Referenced by GetSize().
     {
         return int(m_frames[0].frame.w);
     }
GetSize()
vec2 GetSize ()
Definition at line 58 of file ScriptSprite.as.
References GetHeight(), and GetWidth().
     {
         return vec2(GetWidth(), GetHeight());
     }
GetWidth()
int GetWidth ()
Definition at line 48 of file ScriptSprite.as.
References m_frames.
Referenced by DoDraw(), and GetSize().
     {
         return int(m_frames[0].frame.z);
     }
ScriptSprite() [1/3]
ScriptSprite (array< SValue@>@ params)
Definition at line 21 of file ScriptSprite.as.
References m_frames, m_length, and m_texture.
Referenced by ActorBuffDef(), ActorItems::AddItemFile(), Upgrades::ChapelShop::ChapelShop(), Menu::CharacterCreationMenu::ClassChanged(), Skills::CooldownStackMeleeSwing(), DrawAll(), Modifiers::FlameShield::FlameShield(), GetFaceSprite(), ForgeBlueprint::Initialize(), Item::Initialize(), CharacterCustomizationBase::Initialize(), Load(), LoadScriptSprite(), PlayerBase::LoadSkill(), opCmp(), SetCard(), Menu::SplitscreenPlayer::SetSkin(), Menu::SetStartScenario(), SpeechBubble::SetStyle(), Skills::StackSkill::StackSkill(), Tooltip(), Upgrades::Upgrade::Upgrade(), and Upgrades::UpgradeStep::UpgradeStep().
     {
         @m_texture = Resources::GetTexture2D(params[0].GetString());
         m_length = 0;
         for (uint i = 1; i < params.length(); i += 2)
         {
             int time = params[i].GetInteger();
             m_frames.insertLast(ScriptSpriteFrame(time, params[i + 1].GetVector4()));
             m_length += time;
         }
     }
ScriptSprite() [2/3]
ScriptSprite (Texture2D@ texture, vec4 frame)
Definition at line 33 of file ScriptSprite.as.
References m_frames, m_length, and m_texture.
     {
         @m_texture = texture;
         m_frames.insertLast(ScriptSpriteFrame(100, frame));
         m_length = 100;
     }
ScriptSprite() [3/3]
ScriptSprite (TempTexture2D@ textureTemp, vec4 frame)
Definition at line 40 of file ScriptSprite.as.
References m_frames, m_length, m_texture, and m_textureTemp.
     {
         @m_textureTemp = textureTemp;
         @m_texture = textureTemp.GetTexture();
         m_frames.insertLast(ScriptSpriteFrame(100, frame));
         m_length = 100;
     }
Variable Documentation
m_frames
array<ScriptSpriteFrame@> m_frames
Definition at line 17 of file ScriptSprite.as.
Referenced by GetFrame(), GetHeight(), GetWidth(), and ScriptSprite().
m_length
int m_length
Definition at line 18 of file ScriptSprite.as.
Referenced by GetFrame(), and ScriptSprite().
m_srcOffset
vec2 m_srcOffset
Definition at line 19 of file ScriptSprite.as.
Referenced by GetFrame().
m_texture
class ScriptSpriteFrame m_texture
Referenced by Draw(), DrawRadial(), DrawWrapped(), and ScriptSprite().
m_textureTemp
TempTexture2D m_textureTemp
Definition at line 16 of file ScriptSprite.as.
Referenced by ScriptSprite().