HoHDocs: scripts/SpawnPrefabBase.as File Reference
SpawnPrefabBase.as File Reference
Classes
class SpawnPrefabBase
class SpawnPrefabBaseTask
Functions
class SpawnPrefabBase DoSpawnPrefabBase (int delay, uint prodHash, vec2 pos, string scene, int layer, int cfgEnemy, int ownerId, float intensity)
void Initialize (UnitPtr unit, SValue@ params)
vec2 CalcJitter ()
void SpawnPrefab (vec2 pos)
Variables
Prefab Prefab
float JitterX
float JitterY
int Delay
Function Documentation
CalcJitter()
vec2 DoSpawnPrefabBase::CalcJitter ()
Definition at line 32 of file SpawnPrefabBase.as.
     {
         if (Prefab is null)
DoSpawnPrefabBase()
class SpawnPrefabBase DoSpawnPrefabBase (int delay, uint prodHash, vec2 pos, string scene, int layer, int cfgEnemy, int ownerId, float intensity)
Definition at line 56 of file SpawnPrefabBase.as.
References g_scene, GetPrefab(), QueuedTasks::Queue(), and xyz().
     {
         auto prefab = Resources::GetPrefab(prodHash);
         if (prefab is null)
             return;
         if (delay > 0)
             QueuedTasks::Queue(delay, SpawnPrefabBaseTask(prefab, pos));
         else
             prefab.Fabricate(g_scene, xyz(pos));
     }
Initialize()
void DoSpawnPrefabBase::Initialize (UnitPtr unit, SValue@ params)
Definition at line 20 of file SpawnPrefabBase.as.
     {
         return vec2((randf() * 2.0 - 1.0) * JitterX, (randf() * 2.0 - 1.0) * JitterY);
SpawnPrefab()
void DoSpawnPrefabBase::SpawnPrefab (vec2 pos)
Definition at line 37 of file SpawnPrefabBase.as.
References SpawnPrefabBase::Delay, and SpawnPrefabBase::Prefab.
         {
             (Network::Message("DoSpawnPrefabBase") << Delay << Prefab.GetResourceHash() << pos).SendToHost();
             return;
         }
         if (Delay > 0)
         {
             QueuedTasks::Queue(Delay, SpawnPrefabBaseTask(Prefab, pos));
             return;
         }
         Prefab.Fabricate(g_scene, xyz(pos));
     }
 }
 namespace SpawnPrefabBaseHandler
 {
Variable Documentation
Delay
int Delay
Definition at line 16 of file SpawnPrefabBase.as.
JitterX
float JitterX
Definition at line 11 of file SpawnPrefabBase.as.
JitterY
float JitterY
Definition at line 13 of file SpawnPrefabBase.as.
Prefab
Prefab Prefab
Definition at line 8 of file SpawnPrefabBase.as.