HoHDocs: scripts/GUI/HUD/SpriteBarWidget.as File Reference
SpriteBarWidget.as File Reference
Classes
class SpriteBarWidget
Functions
SpriteBarWidget Widget LoadSpriteBarWidget (WidgetLoadingContext &ctx)
SpriteBarWidget ()
void SetValue (float v)
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void Update (int dt) override
void DoDraw (SpriteBatch &sb, vec2 pos) override
Variables
Sprite m_sprite
Sprite m_spriteHi
Sprite m_spriteExtra
vec4 m_color
float m_value
float m_valueExtra
float m_valuePrev
int m_timePrev
Function Documentation
Clone()
Widget LoadSpriteBarWidget::Clone () override
Definition at line 107 of file SpriteBarWidget.as.
 {
DoDraw()
void LoadSpriteBarWidget::DoDraw (SpriteBatch & sb, vec2 pos) override
Definition at line 144 of file SpriteBarWidget.as.
Load()
void LoadSpriteBarWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 114 of file SpriteBarWidget.as.
 {
     auto w = SpriteBarWidget();
     w.Load(ctx);
     return w;
 }
LoadSpriteBarWidget()
SpriteBarWidget Widget LoadSpriteBarWidget (WidgetLoadingContext & ctx)
Definition at line 127 of file SpriteBarWidget.as.
References SpriteBarWidget().
Referenced by BaseGameMode::BaseGameMode().
 {
     auto w = SpriteBarWidget();
     w.Load(ctx);
     return w;
 }
SetValue()
void LoadSpriteBarWidget::SetValue (float v)
Definition at line 93 of file SpriteBarWidget.as.
         {
SpriteBarWidget()
LoadSpriteBarWidget::SpriteBarWidget ()
Definition at line 84 of file SpriteBarWidget.as.
Referenced by LoadSpriteBarWidget().
         {
Update()
void LoadSpriteBarWidget::Update (int dt) override
Definition at line 136 of file SpriteBarWidget.as.
Variable Documentation
m_color
vec4 m_color
Definition at line 77 of file SpriteBarWidget.as.
m_sprite
Sprite m_sprite
Definition at line 73 of file SpriteBarWidget.as.
m_spriteExtra
Sprite m_spriteExtra
Definition at line 75 of file SpriteBarWidget.as.
m_spriteHi
Sprite m_spriteHi
Definition at line 74 of file SpriteBarWidget.as.
m_timePrev
int m_timePrev
Definition at line 82 of file SpriteBarWidget.as.
m_value
float m_value
Definition at line 78 of file SpriteBarWidget.as.
m_valueExtra
float m_valueExtra
Definition at line 79 of file SpriteBarWidget.as.
m_valuePrev
float m_valuePrev
Definition at line 81 of file SpriteBarWidget.as.