HoHDocs: scripts/WorldScript/StoreOre.as File Reference
StoreOre.as File Reference
Classes
class WorldScript::StoreOre
Namespaces
WorldScript
Functions
double __CalcTaxRate (int money, double midpoint)
int ApplyTaxRate (int townMoney, int runMoney, float midpointMul=1.0f)
Function Documentation
__CalcTaxRate()
double __CalcTaxRate (int money, double midpoint)
Definition at line 149 of file StoreOre.as.
Referenced by ApplyTaxRate().
 {
     return pow(money / midpoint + 1, -1);
 }
ApplyTaxRate()
int ApplyTaxRate (int townMoney, int runMoney, float midpointMul = 1.0f)
Definition at line 154 of file StoreOre.as.
References __CalcTaxRate(), g_allModifiers, Fountain::HasEffect(), and min.
Referenced by Campaign::DepositRun(), WorldScript::StoreOre::OnFunc(), PlayerMenuCharacterTab::UpdateFromRecord(), and WorldScript::StoreOre::Use().
 {
     double midpoint = g_allModifiers.TaxMidpoint() * midpointMul;
     if (Fountain::HasEffect("keep_all_gold"))
         midpoint *= 4;
     int64 money = 0;
     while (runMoney > 0)
     {
         money += int64(min(250, runMoney) * 1000 * __CalcTaxRate(townMoney + int(money / 1000), midpoint));
         runMoney -= 250;
     }
     return int(money / 1000);
 }