HoHDocs: scripts/SwitchHelper.as File Reference
SwitchHelper.as File Reference
Functions
float sr_randf (int i)
int sr_randi (int i, int max)
Variables
% if MOD_SPEEDRUN array< float > g_random_seq
Function Documentation
sr_randf()
else float sr_randf (int i)
Definition at line 46 of file SwitchHelper.as.
References g_random_seq.
Referenced by WorldScript::DestroyUnitChance::ServerExecute(), and WorldScript::RandomChance::ServerExecute().
 {
     return g_random_seq[i % g_random_seq.length()];
 }
sr_randi()
int sr_randi (int i, int max)
Definition at line 51 of file SwitchHelper.as.
References g_random_seq, and max.
Referenced by WorldScript::DestroyUnitCount::ServerExecute(), and WorldScript::RandomCount::ServerExecute().
 {
     return int(g_random_seq[i % g_random_seq.length()] * max);
 }
Variable Documentation
g_random_seq
% if MOD_SPEEDRUN array<float> g_random_seq
Definition at line 3 of file SwitchHelper.as.
Referenced by sr_randf(), and sr_randi().