HoHDocs: scripts/GUI/HUD/TopNumberIconWidget.as File Reference
TopNumberIconWidget.as File Reference
Classes
class TopNumberIconWidget
Functions
TopNumberIconWidget Widget LoadTopNumberIconWidget (WidgetLoadingContext &ctx)
TopNumberIconWidget ()
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void SetSprite (string sprite)
void SetSprite (Sprite@ sprite)
void SetNumber (int number, bool force=false)
void DoDraw (SpriteBatch &sb, vec2 pos) override
void Save (SValueBuilder &builder)
Variables
GUIDef m_def
vec4 m_color
vec4 m_colorText
Sprite m_sprite
int m_number
BitmapFont m_font
BitmapString m_text
string m_topID
Function Documentation
Clone()
Widget LoadTopNumberIconWidget::Clone () override
Definition at line 163 of file TopNumberIconWidget.as.
DoDraw()
void LoadTopNumberIconWidget::DoDraw (SpriteBatch & sb, vec2 pos) override
Definition at line 206 of file TopNumberIconWidget.as.
Load()
void LoadTopNumberIconWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 170 of file TopNumberIconWidget.as.
LoadTopNumberIconWidget()
TopNumberIconWidget Widget LoadTopNumberIconWidget (WidgetLoadingContext & ctx)
Definition at line 92 of file TopNumberIconWidget.as.
References TopNumberIconWidget::Load(), and TopNumberIconWidget().
Referenced by BaseGameMode::BaseGameMode().
 {
     TopNumberIconWidget@ w = TopNumberIconWidget();
     w.Load(ctx);
     return w;
 }
Save()
void LoadTopNumberIconWidget::Save (SValueBuilder & builder)
Definition at line 225 of file TopNumberIconWidget.as.
SetNumber()
void LoadTopNumberIconWidget::SetNumber (int number, bool force = false)
Definition at line 196 of file TopNumberIconWidget.as.
SetSprite() [1/2]
void LoadTopNumberIconWidget::SetSprite (string sprite)
Definition at line 186 of file TopNumberIconWidget.as.
SetSprite() [2/2]
void LoadTopNumberIconWidget::SetSprite (Sprite@ sprite)
Definition at line 191 of file TopNumberIconWidget.as.
TopNumberIconWidget()
LoadTopNumberIconWidget::TopNumberIconWidget ()
Definition at line 158 of file TopNumberIconWidget.as.
Referenced by LoadTopNumberIconWidget().
Variable Documentation
m_color
vec4 m_color
Definition at line 147 of file TopNumberIconWidget.as.
m_colorText
vec4 m_colorText
Definition at line 148 of file TopNumberIconWidget.as.
m_def
GUIDef m_def
Definition at line 145 of file TopNumberIconWidget.as.
m_font
BitmapFont m_font
Definition at line 153 of file TopNumberIconWidget.as.
m_number
int m_number
Definition at line 151 of file TopNumberIconWidget.as.
m_sprite
Sprite m_sprite
Definition at line 150 of file TopNumberIconWidget.as.
m_text
BitmapString m_text
Definition at line 154 of file TopNumberIconWidget.as.
m_topID
string m_topID
Definition at line 156 of file TopNumberIconWidget.as.