HoHDocs: scripts/GUI/WidgetAnimations.as File Reference
WidgetAnimations.as File Reference
Classes
class WidgetAnimation
class WidgetVec2Animation
class WidgetBoolAnimation
Functions
WidgetVec4Animation (string key, vec4 start, vec4 end, int maxTime, int delay=0)
void Apply (float scalar) override
WidgetVec2BezierAnimation (string key, vec2 start, vec2 bezier, vec2 end, int maxTime, int delay=0)
WidgetSpriteAnimation (string key, Sprite@ setTo, int delay=0)
Variables
class WidgetAnimation m_start
vec4 m_end
vec2 m_bezier
WidgetBoolAnimation m_set
Function Documentation
Apply()
void Apply (float scalar) override
Definition at line 87 of file WidgetAnimations.as.
References lerp(), m_end, m_start, and m_widget.
     {
         vec4 lerped = lerp(m_start, m_end, scalar);
         m_widget.AnimateSet(m_key, lerped);
     }
WidgetSpriteAnimation()
WidgetSpriteAnimation (string key, Sprite@ setTo, int delay = 0)
Definition at line 156 of file WidgetAnimations.as.
References m_set.
Referenced by SetCard().
     {
         super(key, 1, delay);
         @m_set = setTo;
     }
WidgetVec2BezierAnimation()
WidgetVec2BezierAnimation (string key, vec2 start, vec2 bezier, vec2 end, int maxTime, int delay = 0)
Definition at line 119 of file WidgetAnimations.as.
References m_bezier, m_end, and m_start.
Referenced by LootBoxItemAnimator::AnimateUp(), LootBox::Play(), and SetCard().
     {
         super(key, maxTime, delay);
         m_start = start;
         m_bezier = bezier;
         m_end = end;
     }
WidgetVec4Animation()
WidgetVec4Animation (string key, vec4 start, vec4 end, int maxTime, int delay = 0)
Definition at line 80 of file WidgetAnimations.as.
References m_end, and m_start.
Referenced by HUD::Announce(), WorldScript::StopAnnounceText::ClientExecute(), GameOver::DoShow(), and Menu::IntroMenu::ShowLogo().
     {
         super(key, maxTime, delay);
         m_start = start;
         m_end = end;
     }
Variable Documentation
m_bezier
vec2 m_bezier
Definition at line 116 of file WidgetAnimations.as.
Referenced by WidgetVec2BezierAnimation().
m_end
vec2 m_end
Definition at line 78 of file WidgetAnimations.as.
Referenced by Apply(), WidgetVec2BezierAnimation(), and WidgetVec4Animation().
m_set
WidgetBoolAnimation m_set
Referenced by WidgetSpriteAnimation().
m_start
WidgetVec2Animation m_start
Referenced by Apply(), WidgetVec2BezierAnimation(), and WidgetVec4Animation().