HoHDocs: scripts/Behaviors/Actions/HitscanSpread.as File Reference
HitscanSpread.as File Reference
Classes
class HitscanSpreadDamage
Functions
HitscanSpread (UnitPtr unit, SValue &params)
void SetWeaponInformation (uint weapon)
bool NeedNetParams ()
bool DoAction (SValueBuilder@ builder, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity)
bool NetDoAction (SValue@ param, Actor@ owner, vec2 pos, vec2 dir)
void DoDamageUnits (Actor@ owner, bool husk)
void Update (int dt, int cooldown)
vec2 ShootSpreadHitscan (Actor@ owner, vec2 from, vec2 to, float intensity, bool husk, int ricochet=0, float ricochetMul=1.0f)
Variables
class HitscanSpreadDamage m_effects
array< IEffect@> m_missEffects
float m_teamDmg
int m_rays
int m_dmg
uint8 m_dmgType
int m_rangeMin
int m_rangeMax
float m_spread
float m_spreadMin
float m_spreadMax
int m_spreadTime
int m_spreadTimeC
int m_spreadCooldown
float m_spreadMul = 1.0f
float m_rangeMul = 1.0f
string m_shootFx
string m_hitFx
bool m_playMissFx
bool m_penetrating
int m_ricochet
int m_ricochetExtra
float m_ricochetDamageExtra
float m_origLength = -1.0f
array< HitscanSpreadDamage@> m_hitUnits
uint m_weaponInfo
Function Documentation
DoAction()
bool DoAction (SValueBuilder@ builder, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity)
Definition at line 102 of file HitscanSpread.as.
References DoDamageUnits(), lerp(), m_rangeMax, m_rangeMin, m_rangeMul, m_rays, m_ricochet, m_ricochetDamageExtra, m_ricochetExtra, m_spread, m_spreadCooldown, m_spreadMax, m_spreadMin, m_spreadMul, m_spreadTime, m_spreadTimeC, min, and ShootSpreadHitscan().
     {
         if (m_spreadTime > 0)
         {
             m_spread = lerp(m_spreadMin, m_spreadMax, min(1.0, m_spreadTimeC / float(m_spreadTime)));
             m_spreadTimeC = min(m_spreadTime, m_spreadTimeC + m_spreadCooldown);
         }
         dir = normalize(dir);
         int ricochet = m_ricochet + m_ricochetExtra;
         builder.PushArray();
         builder.PushFloat(intensity);
         builder.PushInteger(ricochet);
         builder.PushFloat(m_ricochetDamageExtra);
         for (int i = 0; i < m_rays; i++)
         {
             vec2 shootPos = dir;
             if (m_spread > 0)
             {
                 float ang = atan(shootPos.y, shootPos.x) + (randf() - 0.5) * (m_spread * m_spreadMul);
                 shootPos = vec2(cos(ang), sin(ang));
             }
             if (m_rangeMin < m_rangeMax)
                 shootPos *= (m_rangeMin + randi(m_rangeMax - m_rangeMin)) * m_rangeMul;
             else
                 shootPos *= m_rangeMin * m_rangeMul;
             shootPos += pos;
             ShootSpreadHitscan(owner, pos, shootPos, intensity, false, ricochet, m_ricochetDamageExtra);
             builder.PushVector2(shootPos);
         }
         DoDamageUnits(owner, false);
         builder.PopArray();
         return true;
     }
DoDamageUnits()
void DoDamageUnits (Actor@ owner, bool husk)
Definition at line 164 of file HitscanSpread.as.
References damage_round(), DamageInfo(), FilterHuskDamage(), Actor::GetDamageMulTarget(), m_dmg, m_dmgType, m_hitUnits, m_weaponInfo, and unit.
Referenced by DoAction(), and NetDoAction().
     {
         for (uint i = 0; i < m_hitUnits.length(); i++)
         {
             m_hitUnits[i].unit.TriggerCallbacks(UnitEventType::Damaged);
             auto dmgTaker = cast<IDamageTaker>(m_hitUnits[i].unit.GetScriptBehavior());
             if (dmgTaker is null)
                 continue;
             if (!FilterHuskDamage(owner, m_hitUnits[i].unit, husk))
                 continue;
             float mul = owner.GetDamageMulTarget(false, m_hitUnits[i].unit) * m_hitUnits[i].intensity;
 %if MOD_ROGUELIKE
             mul *= randf() * 0.5 + 0.75;
 %endif
             int dmg = damage_round(m_dmg * mul * m_hitUnits[i].numHits);
             if (dmg > 0)
                 dmgTaker.Damage(DamageInfo(m_dmgType, owner, dmg, false, true, m_weaponInfo), m_hitUnits[i].pos, m_hitUnits[i].dir);
         }
         m_hitUnits.removeRange(0, m_hitUnits.length());
     }
HitscanSpread()
HitscanSpread (UnitPtr unit, SValue & params)
Definition at line 51 of file HitscanSpread.as.
References GetParamDamageType(), LoadEffects(), m_dmg, m_dmgType, m_effects, m_hitFx, m_missEffects, m_penetrating, m_playMissFx, m_rangeMax, m_rangeMin, m_rays, m_ricochet, m_shootFx, m_spread, m_spreadCooldown, m_spreadMax, m_spreadMin, m_spreadTime, m_teamDmg, and unit.
     {
         @m_effects = LoadEffects(unit, params);
         @m_missEffects = LoadEffects(unit, params, "miss-");
         m_teamDmg = GetParamFloat(unit, params, "team-dmg", false, 0);
         m_rays = GetParamInt(unit, params, "rays", true, 1);
         m_penetrating = GetParamBool(unit, params, "penetrating", false, false);
         m_dmg = GetParamInt(unit, params, "dmg");
         m_dmgType = GetParamDamageType(unit, params, "dmg-type", true);
         SValue@ spread = GetParamDictionary(unit, params, "spread", false);
         if (spread !is null)
         {
             m_spreadMin = GetParamInt(unit, spread, "min") * PI / 180.0;
             m_spreadMax = GetParamInt(unit, spread, "max") * PI / 180.0;
             m_spreadTime = GetParamInt(unit, spread, "time");
             m_spreadCooldown = GetParamInt(unit, params, "cooldown", false, 100);
         }
         else
             m_spread = GetParamInt(unit, params, "spread", false) * PI / 180.0;
         SValue@ range = GetParamDictionary(unit, params, "range", false);
         if (range !is null)
         {
             m_rangeMin = GetParamInt(unit, range, "min");
             m_rangeMax = GetParamInt(unit, range, "max");
         }
         else
         {
             m_rangeMin = GetParamInt(unit, params, "range");
             m_rangeMax = -1;
         }
         m_ricochet = GetParamInt(unit, params, "ricochet", false);
         m_shootFx = GetParamString(unit, params, "shoot-fx", false);
         m_hitFx = GetParamString(unit, params, "hit-fx", false);
         //m_missFx = GetParamString(unit, params, "miss-fx", false);
         m_playMissFx = GetParamBool(unit, params, "miss-fx", false);
     }
NeedNetParams()
bool NeedNetParams ()
Definition at line 100 of file HitscanSpread.as.
 { return true; }
NetDoAction()
bool NetDoAction (SValue@ param, Actor@ owner, vec2 pos, vec2 dir)
Definition at line 146 of file HitscanSpread.as.
References DoDamageUnits(), and ShootSpreadHitscan().
     {
         auto rays = param.GetArray();
         float intensity = rays[0].GetFloat();
         int ricochet = rays[1].GetInteger();
         float ricochetMul = rays[2].GetFloat();
         for (uint i = 3; i < rays.length(); i++)
         {
             auto shootPos = rays[i].GetVector2();
             ShootSpreadHitscan(owner, pos, shootPos, intensity, true, ricochet, ricochetMul);
         }
         DoDamageUnits(owner, true);
         return true;
     }
SetWeaponInformation()
void SetWeaponInformation (uint weapon)
Definition at line 93 of file HitscanSpread.as.
     {
         PropagateWeaponInformation(m_effects, weapon);
         PropagateWeaponInformation(m_missEffects, weapon);
         m_weaponInfo = weapon;
     }
ShootSpreadHitscan()
vec2 ShootSpreadHitscan (Actor@ owner, vec2 from, vec2 to, float intensity, bool husk, int ricochet = 0, float ricochetMul = 1.0f)
Definition at line 197 of file HitscanSpread.as.
References ApplyEffects(), HitscanSpreadDamage::dir, effect, g_scene, GetPlayerPing(), HitscanSpreadDamage::intensity, m_effects, m_hitFx, m_hitUnits, m_missEffects, m_origLength, m_penetrating, m_playMissFx, m_shootFx, m_teamDmg, min, HitscanSpreadDamage::numHits, PlayEffect(), HitscanSpreadDamage::pos, HitscanSpreadDamage::unit, and unit.
Referenced by DoAction(), and NetDoAction().
     {
         if (m_origLength < 0)
             m_origLength = dist(from, to);
         vec2 dir = normalize(to - from);
         vec2 endPoint = to;
         bool hit = false;
         UnitPtr lastUnit = UnitPtr();
         array<RaycastResult>@ results;
         auto plrHusk = cast<PlayerHusk>(owner);
         if (plrHusk !is null && plrHusk.m_record !is null)
             @results = g_scene.LagCompensation(Lobby::GetPlayerPing(plrHusk.m_record.peer)).Raycast(from, to, ~0, RaycastType::Shot);
         else
             @results = g_scene.Raycast(from, to, ~0, RaycastType::Shot);
         for (uint j = 0; j < results.length(); j++)
         {
             RaycastResult res = results[j];
             UnitPtr res_unit = res.FetchUnit(g_scene);
             if (!res_unit.IsValid())
                 continue;
             if (res_unit == lastUnit)
                 continue;
             lastUnit = res_unit;
             auto dt = cast<IDamageTaker>(res_unit.GetScriptBehavior());
             if (dt !is null && dt.ShootThrough(res.point, dir))
                 continue;
             if (ricochet > 0 && (dt is null || dt.Ricochets()))
             {
                 vec2 rDir = res.normal * -2 * dot(dir, res.normal) + dir;
                 float rDist = (dist(from, to) - dist(from, res.point));
                 rDist = min(m_origLength, rDist * 1.5f);
                 ShootSpreadHitscan(owner, res.point, res.point + rDir * rDist, intensity * ricochetMul, husk, ricochet - 1, ricochetMul);
             }
             if (m_effects is null || ApplyEffects(m_effects, owner, res_unit, res.point, dir, intensity, husk, 0, m_teamDmg))
             {
                 bool toAdd = true;
                 for (uint i = 0; i < m_hitUnits.length(); i++)
                 {
                     if (m_hitUnits[i].unit == res_unit)
                     {
                         m_hitUnits[i].numHits++;
                         toAdd = false;
                         break;
                     }
                 }
                 if (toAdd)
                 {
                     HitscanSpreadDamage hsd;
                     hsd.unit = res_unit;
                     hsd.numHits = 1;
                     hsd.pos = res.point;
                     hsd.dir = dir;
                     hsd.intensity = intensity;
                     m_hitUnits.insertLast(hsd);
                 }
                 dictionary ePs = { { 'angle', atan(dir.y, dir.x) } };
                 PlayEffect(m_hitFx, res.point, ePs);
                 hit = true;
                 if (!m_penetrating)
                 {
                     endPoint = res.point;
                     break;
                 }
             }
             if (dt is null or dt.Impenetrable())
             {
                 endPoint = res.point;
                 break;
             }
         }
         if (!hit)
         {
     %if !GFX_VFX_LOW
             if (m_playMissFx)
             {
                 array<Tileset@>@ tilesets = g_scene.FetchTilesets(to);
                 for (int j = tilesets.length() - 1; j >= 0; j--)
                 {
                     SValue@ data = tilesets[j].GetData();
                     if (data !is null)
                     {
                         SValue@ effect = data.GetDictionaryEntry("hit-effect");
                         if (effect !is null && effect.GetType() == SValueType::String)
{
                             PlayEffect(effect.GetString(), to);
                             break;
                         }
                     }
                 }
             }
     %endif
             if (m_missEffects !is null)
                 ApplyEffects(m_missEffects, owner, UnitPtr(), to, dir, intensity, husk, 0, m_teamDmg);
         }
         if (m_shootFx != "")
         {
             vec2 ep = endPoint - from;
             dictionary ePs = { { 'angle', atan(ep.y, ep.x) }, { 'length', length(ep) } };
             PlayEffect(m_shootFx, from, ePs);
         }
         return endPoint;
     }
Update()
void Update (int dt, int cooldown)
Definition at line 191 of file HitscanSpread.as.
References m_spreadTimeC.
Referenced by Menu::GraphicsMenu::Update(), HUDSpectate::Update(), PassiveMovement::Update(), Menu::CreditsMenu::Update(), NotificationManager::Update(), Menu::InGameNotifier::Update(), BossLich::Update(), CompositeJammableActorBehavior::Update(), CirclingMovement::Update(), Miniboss::Update(), CompositeActorPeriodicTriggeredSkill::Update(), UserWindow::Update(), TripMine::Update(), DungeonSettingsMenu::Update(), RangedMovement::Update(), Menu::EditSlotMenu::Update(), BossVampire::Update(), Menu::FrontMenu::Update(), Projectile::Update(), Menu::InGameChat::Update(), BossLichMovement::Update(), BossEye::Update(), LootBox::Update(), DialogWindow::Update(), CannonBall::Update(), RayProjectile::Update(), MeleeMovement::Update(), HUD::Update(), BossVampireMovement::Update(), GameOver::Update(), MainMenu::UpdateFrame(), UpdateGibs(), BaseGameMode::UpdateMouse(), and BaseGameMode::UpdateWidgets().
     {
         if (cooldown <= 0)
             m_spreadTimeC = 0;
     }
Variable Documentation
m_dmg
int m_dmg
Definition at line 18 of file HitscanSpread.as.
Referenced by DangerArea::ApplyDamage(), DoDamageUnits(), HitscanSpread(), and DangerArea::Initialize().
m_dmgType
uint8 m_dmgType
Definition at line 19 of file HitscanSpread.as.
Referenced by DoDamageUnits(), and HitscanSpread().
m_effects
class HitscanSpreadDamage m_effects
Referenced by HitscanSpread(), SetWeaponInformation(), and ShootSpreadHitscan().
m_hitFx
string m_hitFx
Definition at line 35 of file HitscanSpread.as.
Referenced by HitscanSpread(), and ShootSpreadHitscan().
m_hitUnits
array<HitscanSpreadDamage@> m_hitUnits
Definition at line 46 of file HitscanSpread.as.
Referenced by DoDamageUnits(), and ShootSpreadHitscan().
m_missEffects
array<IEffect@> m_missEffects
Definition at line 13 of file HitscanSpread.as.
Referenced by HitscanSpread(), SetWeaponInformation(), and ShootSpreadHitscan().
m_origLength
float m_origLength = -1.0f
Definition at line 44 of file HitscanSpread.as.
Referenced by ShootSpreadHitscan().
m_penetrating
bool m_penetrating
Definition at line 38 of file HitscanSpread.as.
Referenced by HitscanSpread(), and ShootSpreadHitscan().
m_playMissFx
bool m_playMissFx
Definition at line 36 of file HitscanSpread.as.
Referenced by HitscanSpread(), and ShootSpreadHitscan().
m_rangeMax
int m_rangeMax
Definition at line 22 of file HitscanSpread.as.
Referenced by DoAction(), and HitscanSpread().
m_rangeMin
int m_rangeMin
Definition at line 21 of file HitscanSpread.as.
Referenced by DoAction(), and HitscanSpread().
m_rangeMul
float m_rangeMul = 1.0f
Definition at line 32 of file HitscanSpread.as.
Referenced by DoAction().
m_rays
int m_rays
Definition at line 16 of file HitscanSpread.as.
Referenced by DoAction(), and HitscanSpread().
m_ricochet
int m_ricochet
Definition at line 40 of file HitscanSpread.as.
Referenced by DoAction(), and HitscanSpread().
m_ricochetDamageExtra
float m_ricochetDamageExtra
Definition at line 42 of file HitscanSpread.as.
Referenced by DoAction().
m_ricochetExtra
int m_ricochetExtra
Definition at line 41 of file HitscanSpread.as.
Referenced by DoAction().
m_shootFx
string m_shootFx
Definition at line 34 of file HitscanSpread.as.
Referenced by HitscanSpread(), and ShootSpreadHitscan().
m_spread
float m_spread
Definition at line 24 of file HitscanSpread.as.
Referenced by DoAction(), and HitscanSpread().
m_spreadCooldown
int m_spreadCooldown
Definition at line 29 of file HitscanSpread.as.
Referenced by DoAction(), and HitscanSpread().
m_spreadMax
float m_spreadMax
Definition at line 26 of file HitscanSpread.as.
Referenced by DoAction(), and HitscanSpread().
m_spreadMin
float m_spreadMin
Definition at line 25 of file HitscanSpread.as.
Referenced by DoAction(), and HitscanSpread().
m_spreadMul
float m_spreadMul = 1.0f
Definition at line 31 of file HitscanSpread.as.
Referenced by DoAction().
m_spreadTime
int m_spreadTime
Definition at line 27 of file HitscanSpread.as.
Referenced by DoAction(), and HitscanSpread().
m_spreadTimeC
int m_spreadTimeC
Definition at line 28 of file HitscanSpread.as.
Referenced by DoAction(), and Update().
m_teamDmg
float m_teamDmg
Definition at line 15 of file HitscanSpread.as.
Referenced by HitscanSpread(), and ShootSpreadHitscan().
m_weaponInfo
uint m_weaponInfo
Definition at line 47 of file HitscanSpread.as.
Referenced by DoDamageUnits(), and SetWeaponInformation().