HoHDocs: scripts/Behaviors/Actions/IAction.as File Reference
IAction.as File Reference
Classes
class ActionEffectWrapper
Functions
bool NeedNetParams ()
bool DoAction (SValueBuilder@ builder, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity)
bool NetDoAction (SValue@ param, Actor@ owner, vec2 pos, vec2 dir)
void SetWeaponInformation (uint weapon)
ActionEffectWrapper IAction NetDoActions (array< IAction@>@ actions, SValue@ param, Actor@ owner, vec2 pos, vec2 dir)
ActionEffectWrapper (IEffect@ effect)
void Update (int dt, int cooldown)
SValue DoActions (array< IAction@>@ actions, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity=1.0)
IAction LoadAction (UnitPtr owner, SValue &params)
array< IAction@> LoadActions (UnitPtr owner, SValue &params, string prefix="")
float FilterAction (Actor@ a, Actor@ owner, float selfDmg, float teamDmg, float enemyDmg, float huskDmg=0, uint teamOverride=1)
void PropagateWeaponInformation (array< IAction@>@ actions, uint weapon)
Variables
IEffect m_effect
Function Documentation
ActionEffectWrapper()
NetDoActions::ActionEffectWrapper (IEffect@ effect)
Definition at line 8 of file IAction.as.
Referenced by LoadAction().
                           : IAction
DoAction()
bool DoAction (SValueBuilder@ builder, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity)
Definition at line 15 of file IAction.as.
Referenced by DoActions().
                                       {}
     bool NeedNetParams() { return true; }
     bool DoAction(SValueBuilder@ builder, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity)
     {
         UnitPtr t;
         if (target !is null)
             t = g_scene.GetUnit(target.m_unit.GetId());
DoActions()
SValue DoActions (array< IAction@>@ actions, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity = 1.0)
Definition at line 60 of file IAction.as.
References DoAction(), and NeedNetParams().
Referenced by CastTrigger(), Skills::Shatter::Do(), Skills::ShootRay::DoActivate(), BombBehavior::DoExplode(), CompositeActorSkill::HandleCastpoint(), CompositeActorBurstSkill::Update(), and CompositeActorSkill::Update().
 {
     if (actions is null)
         return null;
     bool netParams = false;
     for (uint i = 0; i < actions.length(); i++)
     {
         if (actions[i].NeedNetParams())
         {
             netParams = true;
             break;
         }
     }
     SValueBuilder@ builder;
     if (netParams)
     {
         @builder = SValueBuilder();
         builder.PushArray();
     }
     for (uint i = 0; i < actions.length(); i++)
         actions[i].DoAction(builder, owner, target, pos, dir, intensity);
     if (netParams)
         return builder.Build();
     return null;
 }
FilterAction()
float FilterAction (Actor@ a, Actor@ owner, float selfDmg, float teamDmg, float enemyDmg, float huskDmg = 0, uint teamOverride = 1)
Definition at line 137 of file IAction.as.
References AGameMode::FilterAction(), g_gameMode, and Actor::IsHusk().
Referenced by ApplyEffects(), CanApplyEffects(), Skills::DropEffect::DoExplosion(), SorcererOrbProjectile::HitUnit(), SorcererProjectile::HitUnit(), RangerProjectile::HitUnit(), RayProjectile::HitUnit(), CannonBall::HitUnit(), and WerebullChargeHitSkill::OnCollide().
 {
     if (a is null)
         return 1;
     if (owner is null)
     {
         if (teamOverride != 1)
             return g_gameMode.FilterAction(a, owner, selfDmg, teamDmg, enemyDmg, teamOverride);
         return 1;
     }
     if (owner is a)
         return selfDmg;
     if (a.IsHusk() && owner.IsHusk())
     {
         if (huskDmg == 0)
             return 0;
         return g_gameMode.FilterAction(a, owner, selfDmg, teamDmg, enemyDmg, teamOverride) * huskDmg;
     }
     return g_gameMode.FilterAction(a, owner, selfDmg, teamDmg, enemyDmg, teamOverride);
 }
LoadAction()
IAction LoadAction (UnitPtr owner, SValue & params)
Definition at line 92 of file IAction.as.
References ActionEffectWrapper(), effect, IAction, and IEffect.
Referenced by LoadActions().
 {
     auto cName = GetParamString(owner, params, "class");
     auto c = InstantiateClass(cName, owner, params);
     IAction@ action = cast<IAction>(c);
     if (action !is null)
         return action;
     IEffect@ effect = cast<IEffect>(c);
     if (effect !is null)
         return ActionEffectWrapper(effect);
     PrintError(cName + " is not an IAction or an IEffect!");
     return null;
 }
LoadActions()
array<IAction@> LoadActions (UnitPtr owner, SValue & params, string prefix = "")
Definition at line 109 of file IAction.as.
References LoadAction().
Referenced by BombBehavior::BombBehavior(), CompositeActorSkill::CompositeActorSkill(), CompositeActorTriggeredSkill(), Skills::Shatter::Shatter(), and Skills::ShootRay::ShootRay().
 {
     array<IAction@> actions;
     array<SValue@>@ effectArr = GetParamArray(owner, params, prefix + "actions", false);
     if (effectArr !is null)
     {
         for (uint i = 0; i < effectArr.length(); i++)
         {
             auto action = LoadAction(owner, effectArr[i]);
             if (action !is null)
                 actions.insertLast(action);
         }
     }
     else
     {
         SValue@ dat = GetParamDictionary(owner, params, prefix + "action", false);
         if (dat !is null)
         {
             auto action = LoadAction(owner, dat);
             if (action !is null)
                 actions.insertLast(action);
         }
     }
     return actions;
 }
NeedNetParams()
bool NeedNetParams ()
Definition at line 13 of file IAction.as.
Referenced by DoActions(), and NetDoActions().
 {}
NetDoAction()
bool NetDoAction (SValue@ param, Actor@ owner, vec2 pos, vec2 dir)
Definition at line 25 of file IAction.as.
Referenced by NetDoActions().
{
NetDoActions()
ActionEffectWrapper IAction NetDoActions (array< IAction@>@ actions, SValue@ param, Actor@ owner, vec2 pos, vec2 dir)
Definition at line 40 of file IAction.as.
References NeedNetParams(), and NetDoAction().
Referenced by Skills::Shatter::NetDo(), Skills::ShootRay::NetDoActivate(), BombBehavior::NetDoExplode(), CompositeActorSkill::NetUseSkill(), and NetUseSkill().
 {
     if (actions is null)
         return;
     uint p = 0;
     array<SValue@>@ params = null;
     if (param !is null && param.GetType() == SValueType::Array)
         @params = param.GetArray();
     for (uint i = 0; i < actions.length(); i++)
     {
         if (actions[i].NeedNetParams())
             actions[i].NetDoAction(params[p++], owner, pos, dir);
         else
             actions[i].NetDoAction(null, owner, pos, dir);
     }
 }
PropagateWeaponInformation()
void PropagateWeaponInformation (array< IAction@>@ actions, uint weapon)
Definition at line 165 of file IAction.as.
References SetWeaponInformation().
Referenced by Skills::Whirlwind::Initialize(), Skills::ShootRay::Initialize(), Skills::Juggernaut::Initialize(), Skills::DropEffect::Initialize(), Projectile::Initialize(), Skills::Charge::Initialize(), Skills::Explode::Initialize(), Skills::SpewProjectiles::Initialize(), RayProjectile::Initialize(), Skills::MeleeSwing::Initialize(), CannonBall::Initialize(), Skills::Initialize(), Skills::StaggeredSpawnUnits::LocalSpawnUnit(), Skills::SpawnUnit::LocalSpawnUnit(), ActorBuff::OnDeath(), SetWeaponInformation(), ShootBolt::SetWeaponInformation(), EffectFilter::SetWeaponInformation(), Explode::SetWeaponInformation(), MeleeHit::SetWeaponInformation(), MeleeSwing::SetWeaponInformation(), Hitscan::SetWeaponInformation(), Skills::ScorchedEarth::Trigger(), and ActorBuff::Update().
 {
     if (actions is null)
         return;
     for (uint i = 0; i < actions.length(); i++)
         actions[i].SetWeaponInformation(weapon);
 }
SetWeaponInformation()
void SetWeaponInformation (uint weapon)
Definition at line 29 of file IAction.as.
References g_scene, and ActionEffectWrapper::m_effect.
Referenced by PropagateWeaponInformation().
{
         return m_effect.Apply(owner, g_scene.GetUnit(param.GetInteger()), pos, dir, 1.0f, true);
     }
Update()
void NetDoActions::Update (int dt, int cooldown)
Definition at line 12 of file IAction.as.
 {
Variable Documentation
m_effect
IEffect m_effect
Definition at line 33 of file IAction.as.