HoHDocs: scripts/Behaviors/Actors/Enemies/CompositeActorBehavior.as File Reference
CompositeActorBehavior.as File Reference
Classes
class CompositeActorBehaviorEvading
class CompositeActorBehaviorNoNGPScale
Functions
CompositeActorBehaviorColorized (UnitPtr unit, SValue &params)
void Update (int dt) override
CompositeActorBehavior (UnitPtr unit, SValue &params)
float GetWindScale () override
void Configure (bool aggro, bool noLoot, bool noExperience)
int GetMaxHp ()
float GetHealth () override
int IconHeight () override
bool IsTargetable () override
vec4 GetOverlayColor ()
SValue Save ()
void Load (SValue@ data)
void PostLoad (SValue@ data)
void SetImmortal (bool immortal) override
bool IsImmortal (bool ignoreBuffs=false) override
bool ApplyBuff (ActorBuff@ buff) override
bool HasBuff (uint buff) override
bool Impenetrable () override
void Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther)
void Kill (Actor@ killer, uint weapon) override
void QueuedPathfind (array< vec2 >@ path)
vec2 GetArmor ()
void NetDecimate (int hp, int mana) override
int Decimate (DecimateInfo dec, vec2 pos, vec2 dir) override
int Damage (DamageInfo dmg, vec2 pos, vec2 dir) override
int Heal (int amount) override
void NetDamage (DamageInfo dmg, vec2 pos, vec2 dir) override
void NetHeal (int amt) override
void Destroyed ()
void OnDeath (DamageInfo di, vec2 dir)
void TriggerOnDeath (DamageInfo di, vec2 dir, bool local=true)
void NetKill (Actor@ attacker, uint16 dmg, vec2 dir, uint weapon) override
bool IsDead () override
vec2 GetDirection ()
vec2 GetCastDirection ()
void NetUseSkill (int skillId, int stage, vec2 pos, SValue@ param) override
int TargetValue (vec2 pos, Actor@ target, uint aggroRange)
void SpreadTarget (Actor@ target, int spreadTargetCount) override
void NetSetTarget (Actor@ target) override
void SetTarget (Actor@ newTarget, int spreadTargetCount=4)
void QueuedFetchActors (array< UnitPtr >@ possibleTargets)
int SetUnitScene (string scene, bool resetTime)
Variables
CompositeActorBehaviorEvading m_colorSpeed
vec3 m_colorA
vec3 m_colorB
CompositeActorBehaviorNoNGPScale m_hp
int m_maxHp
float m_mpScaleFact
uint m_maxRange
int m_aggroRange
bool m_impenetrable
int m_expReward
bool m_targetable
bool m_immortal
bool m_canHeal
bool m_dead
vec2 m_evadeChance
string m_evadeFx
array< ICompositeActorSkill@> m_skills
ActorMovement m_movement
SoundEvent m_aggroSound
SoundEvent m_hurtSound
SoundEvent m_immortalSound
SoundEvent m_deathSound
Actor m_target
bool m_targeting
bool m_mustSeeTarget
int m_targetSearchCd
LootDef m_lootDef
GoreSpawner m_gore
vec2 m_armor
string m_enemyType
ActorBuffList m_buffs
bool m_noBuffs
float m_debuffScale
EffectParams m_effectParams
bool m_holdAngleOnCast
float m_dmgColor
string m_hitFx
bool m_frozen
int m_unitHeight
array< uint > m_buffsImmune
uint64 m_buffsImmuneTags
% if MOD_ACHIEVEMENT_CHECKS int m_achieveGroup
% endif bool m_hasBossBar
string m_hasBossBarName
float m_windScale
Function Documentation
ApplyBuff()
bool ApplyBuff (ActorBuff@ buff) override
Definition at line 364 of file CompositeActorBehavior.as.
References ActorBuffList::Add(), Stats::Add(), buff, m_buffs, m_buffsImmune, m_buffsImmuneTags, m_debuffScale, m_noBuffs, and m_unit.
Referenced by Modifiers::AuraCone::Update(), and CompositeActorAuraSkill::Update().
     {
         if (m_unit.IsDestroyed())
             return false;
         if (m_noBuffs)
             return false;
         if ((buff.m_def.m_tags & m_buffsImmuneTags) != 0)
             return false;
         if (buff.m_def.m_disarm && buff.m_def.m_mulSpeed == 0)
         {
             auto player = cast<PlayerBase>(buff.m_owner);
             if (player !is null)
                 Stats::Add("stun-count", 1, player.m_record);
         }
         if (buff.m_def.m_debuff)
         {
             buff.m_duration = int(buff.m_duration * m_debuffScale);
             if (buff.m_duration <= 0)
                 return false;
         }
         /*
         if (BlockBuff(buff, m_armorDef, m_armorAmnt >= 0 ? m_armorAmnt : 999))
             return false;
         */
         uint pathHash = buff.m_def.m_pathHash;
         for (uint i = 0; i < m_buffsImmune.length(); i++)
         {
             if (pathHash == m_buffsImmune[i])
                 return false;
         }
         m_buffs.Add(buff);
         return true;
     }
Collide()
void Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther)
Definition at line 418 of file CompositeActorBehavior.as.
References m_movement, m_skills, OnCollide, and unit.
     {
         if (!fxOther.IsSensor())
         {
             for (uint i = 0; i < m_skills.length(); i++)
                 m_skills[i].OnCollide(unit, normal);
             m_movement.OnCollide(unit, pos, normal, fxSelf, fxOther);
         }
         //m_unit.GetPhysicsBody().SetStatic(true);
     }
CompositeActorBehavior()
CompositeActorBehavior (UnitPtr unit, SValue & params)
Definition at line 102 of file CompositeActorBehavior.as.
References Tweak::EnemyInfitniteAggro, Float(), GetActorListId(), GetBuffTags(), ActorBuffList::Initialize(), LoadGore(), LoadLootDef(), m_achieveGroup, m_aggroRange, m_aggroSound, m_armor, m_buffs, m_buffsImmune, m_buffsImmuneTags, m_canHeal, m_dead, m_deathSound, m_debuffScale, m_effectParams, m_enemyType, m_evadeChance, m_evadeFx, m_expReward, m_gore, m_hitFx, m_holdAngleOnCast, m_hp, m_hurtSound, m_impenetrable, m_lootDef, m_maxHp, m_maxRange, m_movement, m_mpScaleFact, m_mustSeeTarget, m_noBuffs, m_skills, m_targetable, m_targeting, m_targetSearchCd, m_unit, m_unitHeight, m_windScale, max, Actor::SetTeam(), and unit.
     {
         SetTeam(GetParamString(unit, params, "team", false, "enemy"), GetParamBool(unit, params, "counts-as-kill", false, true));
         super(unit);
         m_maxHp = GetParamInt(unit, params, "hp");
         m_hp = 1.0;
         m_floatingHurt = GetParamBool(unit, params, "floating-hurt", false, true);
         m_impenetrable = GetParamBool(unit, params, "impenetrable", false, false);
         m_expReward = GetParamInt(unit, params, "experience-reward", false, 0);
         m_unitHeight = GetParamInt(unit, params, "unit-height", false, 16);
         m_aggroRange = GetParamInt(unit, params, "aggro-range", false, 200);
         m_maxRange = uint(max(m_aggroRange, GetParamInt(unit, params, "max-range", false, 300)));
         m_canHeal = GetParamBool(unit, params, "can-heal", false, true);
         @m_aggroSound = Resources::GetSoundEvent(GetParamString(unit, params, "aggro-snd", false));
         @m_hurtSound = Resources::GetSoundEvent(GetParamString(unit, params, "hurt-snd", false));
         @m_deathSound = Resources::GetSoundEvent(GetParamString(unit, params, "death-snd", false));
         //@m_immortalSound = Resources::GetSoundEvent("event:/enemies/immortal");
         @m_lootDef = LoadLootDef(GetParamString(unit, params, "loot", false));
         @m_gore = LoadGore(GetParamString(unit, params, "gore", false));
         int armor = GetParamInt(unit, params, "armor", false, 0);
         int resistance = GetParamInt(unit, params, "resistance", false, 0);
         m_armor = vec2(armor, resistance);
         m_enemyType = GetParamString(unit, params, "type", false);
         m_evadeChance = vec2(
             GetParamFloat(unit, params, "evade-physical", false, 0),
             GetParamFloat(unit, params, "evade-magical", false, 0));
         m_evadeFx = GetParamString(unit, params, "evade-fx", false);
         m_mpScaleFact = GetParamFloat(unit, params, "mp-scale-fact", false, 0);
         m_targetable = GetParamBool(unit, params, "targetable", false, true);
         m_targeting = GetParamBool(unit, params, "targeting", false, true);
         if (m_targeting)
             m_mustSeeTarget = GetParamBool(unit, params, "must-see-target", false, true);
         m_targetSearchCd = 0;
         m_hitFx = GetParamString(unit, params, "hit-fx", false);
         m_crosshairColors = GetParamBool(unit, params, "crosshair-colors", false, true);
         m_debuffScale = GetParamFloat(unit, params, "debuff-scale", false, 1.0f);
         m_noBuffs = GetParamBool(unit, params, "no-buffs", false, false);
         array<SValue@>@ immuneArr = GetParamArray(unit, params, "buffs-immune", false);
         if (immuneArr !is null)
         {
             for (uint i = 0; i < immuneArr.length(); i++)
                 m_buffsImmune.insertLast(HashString(immuneArr[i].GetString()));
         }
         m_buffsImmuneTags = GetBuffTags(params, "buffs-immune-");
 %if MOD_ACHIEVEMENT_CHECKS
         m_achieveGroup = GetParamInt(unit, params, "achieve-group", false, 0);
 %endif
         {
             SValue@ movement = GetParamDictionary(unit, params, "movement", true);
             string c = GetParamString(unit, movement, "class");
             @m_movement = cast<ActorMovement>(InstantiateClass(c, unit, movement));
         }
         array<SValue@>@ skillArr = GetParamArray(unit, params, "skills");
         for (uint i = 0; i < skillArr.length(); i++)
         {
             string c = GetParamString(unit, skillArr[i], "class");
             ICompositeActorSkill@ skill = cast<ICompositeActorSkill>(InstantiateClass(c, unit, skillArr[i]));
             skill.Initialize(m_unit, this, i);
             m_skills.insertLast(skill);
         }
         m_movement.Initialize(m_unit, this);
         SValue@ dat = GetParamDictionary(unit, params, "effect-params", false);
         if (dat !is null && dat.GetType() == SValueType::Dictionary)
         {
             @m_effectParams = m_unit.CreateEffectParams();
             auto epKeys = dat.GetDictionary().getKeys();
             for (uint i = 0; i < epKeys.length(); i++)
             {
                 auto d = dat.GetDictionaryEntry(epKeys[i]);
                 if (d !is null && d.GetType() == SValueType::Float && m_effectParams !is null)
                     m_effectParams.Set(epKeys[i], d.GetFloat());
             }
             m_holdAngleOnCast = GetParamBool(unit, params, "hold-angle-on-cast", false, false);
         }
         m_windScale = GetParamFloat(unit, params, "wind-scale", false, 1.0f);
         m_unit.SetCollisionTeam(uint16(GetActorListId(Team)));
         if (!Tweak::EnemyInfitniteAggro)
             m_unit.SetUpdateDistanceLimit(int(m_maxRange));
         m_dead = false;
         m_buffs.Initialize(this);
     }
CompositeActorBehaviorColorized()
CompositeActorBehaviorColorized (UnitPtr unit, SValue & params)
Definition at line 8 of file CompositeActorBehavior.as.
References m_colorA, m_colorB, m_colorSpeed, and unit.
     {
         super(unit, params);
         m_colorSpeed = GetParamFloat(unit, params, "colorize-speed", false, 1);
         array<SValue@>@ colorArr = GetParamArray(unit, params, "colorize", true);
         if (colorArr !is null)
         {
             m_colorA = colorArr[0].GetVector3();
             m_colorB = colorArr[1].GetVector3();
         }
     }
Configure()
void Configure (bool aggro, bool noLoot, bool noExperience)
Definition at line 224 of file CompositeActorBehavior.as.
References m_aggroRange, m_expReward, m_lootDef, m_maxRange, m_movement, m_mustSeeTarget, and m_unit.
     {
         if (aggro)
         {
             m_mustSeeTarget = false;
             m_aggroRange = 5000;
             m_maxRange = 5000;
             m_unit.SetUpdateDistanceLimit(int(m_maxRange));
             m_movement.MakeAggro();
         }
         if (noLoot)
             @m_lootDef = null;
         if (noExperience)
             m_expReward = 0;
     }
Damage()
int Damage (DamageInfo dmg, vec2 pos, vec2 dir) override
Definition at line 472 of file CompositeActorBehavior.as.
     {
         if (m_hp <= 0)
             return 0;
         if (dmg.Cleave is null)
             @dmg.Cleave = m_buffs.Cleave();
         auto localPlayer = cast<Player>(dmg.Attacker);
         if (localPlayer !is null)
             dmg = localPlayer.DamageActor(this, dmg);
         if (!dmg.TrueStrike)
         {
             bool evaded = false;
             if (dmg.PhysicalDamage > 0 && randf() <= m_evadeChance.x)
             {
                 dmg.PhysicalDamage = 0;
                 evaded = true;
             }
             if (dmg.MagicalDamage > 0 && randf() <= m_evadeChance.y)
             {
                 dmg.MagicalDamage = 0;
                 evaded = true;
             }
             if (evaded)
                 PlayEffect(m_evadeFx, m_unit.GetPosition());
             if (dmg.PhysicalDamage == 0 && dmg.MagicalDamage == 0)
                 return 0;
         }
         vec2 dmgAmntParts = ApplyArmorParts(dmg, GetArmor() * dmg.ArmorMul, m_buffs.DamageTakenMul());
         int dmgAmnt = max(0, damage_round(dmgAmntParts.x + dmgAmntParts.y));
         if (!dmg.CanKill && floor(m_hp * float(GetMaxHp())) - dmgAmnt <= 0)
             dmgAmnt = 0;
         if (dmgAmnt > 0)
         {
             DamageInfo di = dmg;
             di.Damage = dmgAmnt;
             di.PhysicalDamage = damage_round(dmgAmntParts.x);
             di.MagicalDamage = damage_round(dmgAmntParts.y);
             if (!IsImmortal())
             {
                 float maxHp = float(GetMaxHp());
                 di.DamageDealt = int(min(m_hp, float(di.Damage) / maxHp) * maxHp);
                 if (localPlayer !is null)
                     localPlayer.DamagedActor(this, di);
                 NetDamage(di, pos, dir);
                 //m_movement.OnDamaged(dmg);
                 PlayEffect(m_hitFx, pos);
                 for (uint i = 0; i < m_skills.length(); i++)
                     m_skills[i].OnDamaged();
                 //AddFloatingHurt(dmgAmnt);
                 UnitHandler::NetSendUnitDamaged(m_unit, dmgAmnt, pos, dir, di.Attacker);
                 if (dmg.Cleave !is null && dmg.Cleave.Range > 0)
                 {
                     int pd = damage_round(di.PhysicalDamage * dmg.Cleave.PhysicalDamageMul) + dmg.Cleave.PhysicalDamageAdd;
                     int md = damage_round(di.MagicalDamage * dmg.Cleave.MagicalDamageMul) + dmg.Cleave.MagicalDamageAdd;
                     auto cleaveDmg = DamageInfo(null, pd, md, false, true, 0);
                     @cleaveDmg.Cleave = CleaveInfo();
                     auto results = g_scene.QueryCircle(pos, dmg.Cleave.Range, ~0, RaycastType::Shot, true);
                     for (uint i = 0; i < results.length(); i++)
                     {
                         auto dmgTaker = cast<IDamageTaker>(results[i].GetScriptBehavior());
                         if (dmgTaker !is null && dmgTaker !is dmg.Attacker && dmgTaker !is this)
{
                             auto dpos = xy(results[i].GetPosition());
                             dmgTaker.Damage(cleaveDmg, dpos, normalize(dpos - pos));
                             PlayEffect(dmg.Cleave.Effect, dpos);
                         }
                     }
                 }
             }
             else
             {
                 AddFloatingImmortal(0);
                 PlaySound3D(m_immortalSound, m_unit.GetPosition());
             }
             m_dmgColor = 1.0;
             if (m_hp <= 0)
                 OnDeath(di, dir);
         }
         else if (dmgAmnt < 0)
         {
             if (m_hp < 1.0)
             {
                 NetHeal(-dmgAmnt);
                 (Network::Message("UnitHealed") << m_unit << -dmgAmnt).SendToAll();
             }
         }
         else
             AddFloatingHurt(0);
         return dmgAmnt;
     }
Decimate()
int Decimate (DecimateInfo dec, vec2 pos, vec2 dir) override
Definition at line 456 of file CompositeActorBehavior.as.
     {
         int maxHp = GetMaxHp();
         int preHp = int(m_hp * maxHp);
         float new = clamp((m_hp - dec.HealthMax) * (1.0f - dec.HealthCurr), 0.0f, 1.0f);
         m_hp = new;
         assert(m_hp, new);
         int dmgAmnt = preHp - int(m_hp * maxHp);
         AddFloatingHurt(dmgAmnt, 0, FloatingTextType::EnemyHurtLocal);
         (Network::Message("UnitDecimated") << m_unit << dmgAmnt << 0).SendToAll();
         return dmgAmnt;
     }
Destroyed()
void Destroyed ()
Definition at line 633 of file CompositeActorBehavior.as.
Referenced by Destroyed(), and WorldScript::UnitDestroyedTrigger::OnChanged().
     {
         if (m_countsAsKill)
             g_killedEnemies++;
         m_buffs.Clear();
         for (uint i = 0; i < m_skills.length(); i++)
             m_skills[i].Destroyed();
     }
GetArmor()
vec2 GetArmor ()
Definition at line 444 of file CompositeActorBehavior.as.
References ActorBuffList::ArmorMul(), g_ngp, m_armor, and m_buffs.
Referenced by Damage().
     {
         //return m_buffs.ArmorMul() * (m_armor + vec2(g_ngp * 5)) * (1.0f + float(g_ngp) * 0.5f);
         return m_buffs.ArmorMul() * (m_armor + vec2(g_ngp * 5)) * pow(float(g_ngp + 1), 0.33f);
     }
GetCastDirection()
vec2 GetCastDirection ()
Definition at line 710 of file CompositeActorBehavior.as.
References GetDirection().
     {
         return GetDirection();
     }
GetDirection()
vec2 GetDirection ()
Definition at line 705 of file CompositeActorBehavior.as.
References m_movement.
Referenced by BossLich::GetCastDirection(), BossVampire::GetCastDirection(), and GetCastDirection().
     {
         return vec2(cos(m_movement.m_dir), sin(m_movement.m_dir));
     }
GetHealth()
float GetHealth () override
Definition at line 249 of file CompositeActorBehavior.as.
References m_hp.
     {
         return m_hp;
     }
GetMaxHp()
int GetMaxHp ()
Definition at line 244 of file CompositeActorBehavior.as.
References g_mpEnemyHealthScale, g_ngp, m_maxHp, and m_mpScaleFact.
Referenced by Damage(), Decimate(), NetDamage(), NetDecimate(), NetHeal(), and TriggerOnDeath().
     {
         return int((m_maxHp + g_ngp * 15) * (1.0f + g_mpEnemyHealthScale * m_mpScaleFact) * (1.0f + float(g_ngp) * 2.75f));
     }
GetOverlayColor()
vec4 GetOverlayColor ()
Definition at line 257 of file CompositeActorBehavior.as.
References Actor::IsImmortal(), and m_dmgColor.
     {
         if (m_dmgColor <= 0)
             return vec4(1, 1, 1, 0);
         if (!IsImmortal())
             return vec4(1, 0, 0, 0.5 * m_dmgColor);
         return vec4(160.0/255.0, 0, 1, 0.5 * m_dmgColor);
     }
GetWindScale()
float GetWindScale () override
Definition at line 222 of file CompositeActorBehavior.as.
References m_windScale.
 { return m_windScale; }
HasBuff()
bool HasBuff (uint buff) override
Definition at line 405 of file CompositeActorBehavior.as.
References buff, ActorBuffList::m_buffs, and m_buffs.
     {
         for (uint i = 0; i < m_buffs.m_buffs.length(); i++)
         {
             auto b = m_buffs.m_buffs[i];
             if (b.m_def.m_pathHash == buff)
                 return true;
         }
         return false;
     }
Heal()
int Heal (int amount) override
Definition at line 582 of file CompositeActorBehavior.as.
References m_canHeal, m_unit, and Actor::NetHeal().
     {
         if (!m_canHeal)
             return 0;
         NetHeal(amount);
         (Network::Message("UnitHealed") << m_unit << amount).SendToAll();
         return amount;
     }
IconHeight()
int IconHeight () override
Definition at line 254 of file CompositeActorBehavior.as.
References m_unitHeight.
 { return -m_unitHeight - 2; }
Impenetrable()
bool Impenetrable () override
Definition at line 416 of file CompositeActorBehavior.as.
References m_impenetrable.
 { return m_impenetrable; }
IsDead()
bool IsDead () override
Definition at line 703 of file CompositeActorBehavior.as.
Referenced by BaseGameMode::AttemptRespawn(), CondPlayersGreater(), BossEye::FindWispTargets(), BaseGameMode::GetPlayersAlive(), WorldScript::AllPlayersAreaTrigger::IsEveryoneInside(), WorldScript::CheckPlayerCount::ServerExecute(), BaseGameMode::SpectateNextPlayer(), and Miniboss::Update().
 { return m_hp <= 0 || m_dead; }
IsImmortal()
bool IsImmortal (bool ignoreBuffs = false) override
Definition at line 359 of file CompositeActorBehavior.as.
References m_immortal.
     {
         return m_immortal;
     }
IsTargetable()
bool IsTargetable () override
Definition at line 255 of file CompositeActorBehavior.as.
References m_targetable.
Referenced by BossEye::IsTargetable(), BossLich::IsTargetable(), and BossVampire::IsTargetable().
 { return m_targetable; }
Kill()
void Kill (Actor@ killer, uint weapon) override
Definition at line 430 of file CompositeActorBehavior.as.
References DamageInfo(), Actor::Kill(), m_hp, and OnDeath().
     {
         m_hp = 0;
         Actor::Kill(killer, weapon);
         OnDeath(DamageInfo(0, killer, 1, false, true, weapon), vec2());
     }
Load()
void Load (SValue@ data)
Definition at line 307 of file CompositeActorBehavior.as.
Referenced by BossVampire::Load(), BossEye::Load(), and PostLoad().
     {
         auto hp = data.GetDictionaryEntry("hp");
         if (hp !is null && hp.GetType() == SValueType::Float)
             m_hp = hp.GetFloat();
         auto immortal = data.GetDictionaryEntry("immortal");
         if (immortal !is null && immortal.GetType() == SValueType::Boolean)
             m_immortal = immortal.GetBoolean();
         auto frozen = data.GetDictionaryEntry("frozen");
         if (frozen !is null && frozen.GetType() == SValueType::Boolean)
             m_frozen = frozen.GetBoolean();
         if (m_movement !is null)
         {
             auto movement = data.GetDictionaryEntry("movement");
             if (movement !is null)
                 m_movement.Load(movement);
         }
     }
NetDamage()
void NetDamage (DamageInfo dmg, vec2 pos, vec2 dir) override
Definition at line 592 of file CompositeActorBehavior.as.
Referenced by Miniboss::NetDamage().
     {
         //if (m_hp <= 0)
         //  return;
         if (Network::IsServer())
         {
             if (dmg.Attacker !is null && !dmg.Attacker.IsDead())
                 if (m_target is null || (dmg.Attacker.Team == g_team_player && m_target.Team != g_team_player))
                     SetTarget(dmg.Attacker);
         }
         m_hp = float(m_hp) - float(dmg.Damage) / float(GetMaxHp());
         m_movement.OnDamaged(dmg);
         if (dmg.Attacker !is null && dmg.Attacker is GetLocalPlayer())
             AddFloatingHurt(dmg.Damage, dmg.Crit, FloatingTextType::EnemyHurtLocal);
         else
             AddFloatingHurt(dmg.Damage, dmg.Crit, FloatingTextType::EnemyHurtHusk);
         //if (m_hp <= 0)
         //  OnDeath(dmg, dir);
         if (m_hp > 0)
         {
             PlaySound3D(m_hurtSound, m_unit.GetPosition());
             if (m_gore !is null)
                 m_gore.OnHit(float(dmg.Damage) / float(GetMaxHp()), pos, atan(dir.y, dir.x));
         }
     }
NetDecimate()
void NetDecimate (int hp, int mana) override
Definition at line 450 of file CompositeActorBehavior.as.
     {
         m_hp = float(m_hp) - float(hp) / float(GetMaxHp());
         AddFloatingHurt(hp, 0, FloatingTextType::EnemyHurtHusk);
     }
NetHeal()
void NetHeal (int amt) override
Definition at line 626 of file CompositeActorBehavior.as.
References Actor::AddFloatingGive(), GetMaxHp(), m_hp, and min.
     {
         m_hp = min(1.0, m_hp + float(amt) / float(GetMaxHp()));
         //AddFloatingText(FloatingTextType::EnemyHealed, "" + amt, m_unit.GetPosition());
         AddFloatingGive(amt);
     }
NetKill()
void NetKill (Actor@ attacker, uint16 dmg, vec2 dir, uint weapon) override
Definition at line 696 of file CompositeActorBehavior.as.
References DamageInfo(), and TriggerOnDeath().
     {
         TriggerOnDeath(DamageInfo(0, attacker, dmg, false, true, weapon), dir, false);
     }
NetSetTarget()
void NetSetTarget (Actor@ target) override
Definition at line 773 of file CompositeActorBehavior.as.
References MusicManager::AddTension(), GetLocalPlayer(), m_aggroSound, m_expReward, m_target, m_unit, and PlaySound3D().
     {
         if (target !is null && target is GetLocalPlayer())
             MusicManager::AddTension((target !is m_target ? 2.5 : 0.1) * m_expReward / 10.f);
         @m_target = target;
         PlaySound3D(m_aggroSound, m_unit);
     }
NetUseSkill()
void NetUseSkill (int skillId, int stage, vec2 pos, SValue@ param) override
Definition at line 716 of file CompositeActorBehavior.as.
References m_skills, m_unit, and Actor::NetUseSkill().
     {
         if (m_unit.IsDestroyed())
             return;
         m_unit.SetPosition(pos.x, pos.y, m_unit.GetPosition().z, true);
         if (skillId >= 0 && uint(skillId) < m_skills.length())
             m_skills[skillId].NetUseSkill(stage, param);
         else
             PrintError("Failed to use netsynced skill " + skillId + " for unit " +  m_unit.GetDebugName());
     }
OnDeath()
void OnDeath (DamageInfo di, vec2 dir)
Definition at line 644 of file CompositeActorBehavior.as.
References m_unit, and TriggerOnDeath().
Referenced by Damage(), Kill(), and TriggerOnDeath().
     {
         if (m_unit.IsDestroyed())
             return;
         TriggerOnDeath(di, dir);
     }
PostLoad()
void PostLoad (SValue@ data)
Definition at line 329 of file CompositeActorBehavior.as.
References GetHUD(), Load(), m_hasBossBar, m_hasBossBarName, m_movement, m_skills, and min.
Referenced by BossVampire::PostLoad(), and BossEye::PostLoad().
     {
         auto bossbar = data.GetDictionaryEntry("bossbar");
         if (bossbar !is null)
         {
             m_hasBossBar = true;
             m_hasBossBarName = GetParamString(UnitPtr(), data, "bossbar-name", false);
             auto hud = GetHUD();
             hud.AddBossBar(this, m_hasBossBarName);
         }
         auto skills = data.GetDictionaryEntry("skills");
         if (skills !is null && skills.GetType() == SValueType::Array)
         {
             auto arrSkills = skills.GetArray();
             for (int i = 0; i < min(m_skills.length(), arrSkills.length()); i++)
                 m_skills[i].Load(arrSkills[i]);
         }
         if (m_movement !is null)
         {
             auto movement = data.GetDictionaryEntry("movement");
             if (movement !is null)
                 m_movement.PostLoad(movement);
         }
     }
QueuedFetchActors()
void QueuedFetchActors (array< UnitPtr >@ possibleTargets)
Definition at line 818 of file CompositeActorBehavior.as.
References Actor::IsDead(), Actor::IsTargetable(), m_aggroRange, m_targetSearchCd, m_unit, SetTarget(), TargetValue(), and xy().
     {
         m_targetSearchCd = 500 + randi(500);
         Actor@ newTarget = null;
         vec2 pos = xy(m_unit.GetPosition());
         uint aggroRange = uint(m_aggroRange);
         uint bestVal = 999999;
         for (uint i = 0; i < possibleTargets.length(); i++)
         {
             Actor@ a = cast<Actor>(possibleTargets[i].GetScriptBehavior());
             if (!a.IsDead() && a.IsTargetable())
             {
                 int val = TargetValue(pos, a, aggroRange);
                 if (val >= 0 && uint(val) < bestVal)
                 {
                     bestVal = val;
                     @newTarget = a;
                 }
             }
         }
         SetTarget(newTarget);
     }
QueuedPathfind()
void QueuedPathfind (array< vec2 >@ path)
Definition at line 437 of file CompositeActorBehavior.as.
References m_movement, and SetTarget().
     {
         m_movement.QueuedPathfind(path);
         if (path.length() == 0)
             SetTarget(null);
     }
Save()
SValue Save ()
Definition at line 268 of file CompositeActorBehavior.as.
References m_frozen, m_hasBossBar, m_hasBossBarName, m_hp, m_immortal, m_movement, and m_skills.
Referenced by BossVampire::Save(), and BossEye::Save().
     {
         SValueBuilder sval;
         sval.PushDictionary();
         if (m_hasBossBar)
         {
             sval.PushBoolean("bossbar", true);
             sval.PushString("bossbar-name", m_hasBossBarName);
         }
         if (m_hp != 1.0)
             sval.PushFloat("hp", m_hp);
         if (m_immortal)
             sval.PushBoolean("immortal", m_immortal);
         if (m_frozen)
             sval.PushBoolean("frozen", m_frozen);
         sval.PushArray("skills");
         for (uint i = 0; i < m_skills.length(); i++)
         {
             sval.PushDictionary();
             m_skills[i].Save(sval);
             sval.PopDictionary();
         }
         sval.PopArray();
         if (m_movement !is null)
         {
             auto svMovement = m_movement.Save();
             if (svMovement !is null)
                 sval.PushSimple("movement", svMovement);
         }
         return sval.Build();
     }
SetImmortal()
void SetImmortal (bool immortal) override
Definition at line 358 of file CompositeActorBehavior.as.
References m_immortal.
Referenced by WorldScript::ToggleImmortality::ServerExecute().
 { m_immortal = immortal; }
SetTarget()
void SetTarget (Actor@ newTarget, int spreadTargetCount = 4)
Definition at line 782 of file CompositeActorBehavior.as.
References MusicManager::AddTension(), g_scene, GetLocalPlayer(), m_aggroSound, m_expReward, m_target, Actor::m_unit, m_unit, PlaySound3D(), Actor::SpreadTarget(), and xy().
Referenced by NetDamage(), QueuedFetchActors(), QueuedPathfind(), and SpreadTarget().
     {
         if (!Network::IsServer())
             return;
         if (m_unit.IsDestroyed())
             return;
         if (newTarget !is null && newTarget is GetLocalPlayer())
             MusicManager::AddTension((newTarget !is m_target ? 2.5 : 0.1) * m_expReward / 10.f);
         if (newTarget !is m_target)
         {
             @m_target = newTarget;
             PlaySound3D(m_aggroSound, m_unit);
             if (m_target is null)
                 (Network::Message("UnitTarget") << m_unit << UnitPtr()).SendToAll();
             else
             {
                 (Network::Message("UnitTarget") << m_unit << m_target.m_unit).SendToAll();
                 if (spreadTargetCount > 0)
                 {
                     auto friends = g_scene.FetchActorsWithTeam(Team, xy(m_unit.GetPosition()), 50);
                     for (uint i = 0; i < friends.length(); i++)
                     {
                         cast<Actor>(friends[i].GetScriptBehavior()).SpreadTarget(m_target, spreadTargetCount--);
                         if (spreadTargetCount < 0)
                             break;
                     }
                 }
             }
         }
     }
SetUnitScene()
int SetUnitScene (string scene, bool resetTime)
Definition at line 845 of file CompositeActorBehavior.as.
References m_unit.
Referenced by WorldScript::SetUnitScene::ClientExecute(), WorldScript::StoreOre::OnFunc(), WorldScript::RandomBuff::OnFunc(), WorldScript::SetUnitScene::ServerExecute(), and WorldScript::Well::Use().
     {
         m_unit.SetUnitScene(scene, resetTime);
         return m_unit.GetCurrentUnitScene().Length();
     }
SpreadTarget()
void SpreadTarget (Actor@ target, int spreadTargetCount) override
Definition at line 767 of file CompositeActorBehavior.as.
References Actor::IsDead(), m_target, m_targeting, and SetTarget().
     {
         if (m_targeting && m_target is null && !IsDead())
             SetTarget(target, spreadTargetCount);
     }
TargetValue()
int TargetValue (vec2 pos, Actor@ target, uint aggroRange)
Definition at line 731 of file CompositeActorBehavior.as.
References Tweak::EnemiesCanSeeThroughWalls, Tweak::EnemyInfitniteAggro, g_scene, g_team_player, m_maxRange, m_mustSeeTarget, m_target, Actor::m_unit, Actor::Team, and xy().
Referenced by QueuedFetchActors().
     {
         float weight = 1.0f;
         uint d = uint(dist(pos, xy(target.m_unit.GetPosition())));
         if (target is m_target)
         {
             if (!Tweak::EnemyInfitniteAggro && d > uint(m_maxRange))
                 return -1;
             /*
             if (target.Team == g_team_player)
                 weight *= 0.25f;
             */
             weight *= 0.7f;
         }
         else
         {
             if (!Tweak::EnemyInfitniteAggro && d > aggroRange)
                 return -1;
             if (target.Team == g_team_player)
                 weight *= 0.75f;
             if (m_mustSeeTarget && !Tweak::EnemiesCanSeeThroughWalls)
             {
                 RaycastResult res = g_scene.RaycastClosest(pos, xy(target.m_unit.GetPosition()), ~0, RaycastType::Aim);
                 UnitPtr res_unit = res.FetchUnit(g_scene);
                 if (res_unit.IsValid() && res_unit != target.m_unit)
                     return -1;
             }
         }
         return int(d * weight);
     }
TriggerOnDeath()
void TriggerOnDeath (DamageInfo di, vec2 dir, bool local = true)
Definition at line 652 of file CompositeActorBehavior.as.
References DamageInfo::Attacker, DamageInfo::Damage, GetActorList(), GetMaxHp(), Fountain::HasEffect(), Actor::IsDead(), Actor::KilledActor(), m_buffs, m_dead, m_deathSound, m_gore, m_hp, m_lootDef, m_skills, Actor::m_unit, m_unit, ActorBuffList::OnDeath(), OnDeath(), PlaySound3D(), DamageInfo::Weapon, and xy().
Referenced by NetKill(), and OnDeath().
     {
         if (m_unit.IsDestroyed() || m_dead)
             return;
         m_dead = true;
         m_hp = 0;
         PlaySound3D(m_deathSound, m_unit.GetPosition());
         m_buffs.OnDeath(this);
         if (m_gore !is null)
             m_gore.OnDeath(di.Damage / float(GetMaxHp()), xy(m_unit.GetPosition()), atan(dir.y, dir.x));
         if (local)
         {
             auto attacker = di.Attacker is null || di.Attacker.IsDead() ? UnitPtr() : di.Attacker.m_unit;
             (Network::Message("UnitKilled") << m_unit << attacker << di.Damage << dir << di.Weapon).SendToAll();
         }
         if (di.Attacker !is null)
             di.Attacker.KilledActor(this, di);
         if (Network::IsServer())
         {
             if (m_lootDef !is null && !Fountain::HasEffect("no_dropped_loot"))
                 m_lootDef.Spawn(xy(m_unit.GetPosition()));
             for (uint i = 0; i < m_skills.length(); i++)
                 m_skills[i].OnDeath();
             m_unit.Destroy();
         }
         auto coll = GetActorList(Team);
         if (coll !is null)
         {
             int idx = coll.m_arr.findByRef(this);
             if (idx >= 0)
                 coll.m_arr.removeAt(idx);
         }
     }
Update()
void Update (int dt) override
Definition at line 23 of file CompositeActorBehavior.as.
References g_scene, lerp(), m_colorA, m_colorB, m_colorSpeed, m_unit, and xyzw().
     {
         CompositeActorBehavior::Update(dt);
         float xt = (sin(g_scene.GetTime() / 1000.0 * m_colorSpeed) + 1.0) / 2.0;
         auto color = lerp(m_colorA, m_colorB, xt);
         m_unit.SetMultiColor(0, xyzw(color * 0.1, 1), xyzw(color * 0.5, 1), xyzw(color * 2, 1));
     }
Variable Documentation
m_achieveGroup
% if MOD_ACHIEVEMENT_CHECKS int m_achieveGroup
Definition at line 92 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehavior().
m_aggroRange
int m_aggroRange
Definition at line 46 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehavior(), Configure(), and QueuedFetchActors().
m_aggroSound
SoundEvent m_aggroSound
Definition at line 60 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehavior(), NetSetTarget(), and SetTarget().
m_armor
vec2 m_armor
Definition at line 72 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehavior(), CompositeActorBehaviorNoNGPScale::GetArmor(), and GetArmor().
m_buffs
ActorBuffList m_buffs
Definition at line 75 of file CompositeActorBehavior.as.
Referenced by ApplyBuff(), CompositeActorBehavior(), Damage(), Destroyed(), CompositeActorBehaviorNoNGPScale::GetArmor(), GetArmor(), HasBuff(), TriggerOnDeath(), and CompositeJammableActorBehavior::Update().
m_buffsImmune
array<uint> m_buffsImmune
Definition at line 88 of file CompositeActorBehavior.as.
Referenced by ApplyBuff(), and CompositeActorBehavior().
m_buffsImmuneTags
uint64 m_buffsImmuneTags
Definition at line 89 of file CompositeActorBehavior.as.
Referenced by ApplyBuff(), and CompositeActorBehavior().
m_canHeal
bool m_canHeal
Definition at line 51 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehavior(), and Heal().
m_colorA
vec3 m_colorA
Definition at line 5 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehaviorColorized(), and Update().
m_colorB
vec3 m_colorB
Definition at line 6 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehaviorColorized(), and Update().
m_colorSpeed
CompositeActorBehaviorEvading m_colorSpeed
Referenced by CompositeActorBehaviorColorized(), and Update().
m_dead
bool m_dead
Definition at line 52 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehavior(), IsDead(), and TriggerOnDeath().
m_deathSound
SoundEvent m_deathSound
Definition at line 63 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehavior(), and TriggerOnDeath().
m_debuffScale
float m_debuffScale
Definition at line 77 of file CompositeActorBehavior.as.
Referenced by ApplyBuff(), and CompositeActorBehavior().
m_dmgColor
float m_dmgColor
Definition at line 80 of file CompositeActorBehavior.as.
Referenced by Damage(), GetOverlayColor(), and CompositeJammableActorBehavior::Update().
m_effectParams
EffectParams m_effectParams
Definition at line 78 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehavior().
m_enemyType
string m_enemyType
Definition at line 73 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehavior().
m_evadeChance
vec2 m_evadeChance
Definition at line 54 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehavior(), and Damage().
m_evadeFx
string m_evadeFx
Definition at line 55 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehavior(), and Damage().
m_expReward
int m_expReward
Definition at line 48 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehavior(), Configure(), NetSetTarget(), and SetTarget().
m_frozen
bool m_frozen
Definition at line 84 of file CompositeActorBehavior.as.
Referenced by BossVampire::BossVampire(), BossEye::Freeze(), BossEye::IsTargetable(), Load(), Save(), BossEye::Suspend(), and BossEye::Unsuspend().
m_gore
GoreSpawner m_gore
Definition at line 71 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehavior(), NetDamage(), and TriggerOnDeath().
m_hasBossBar
% endif bool m_hasBossBar
Definition at line 95 of file CompositeActorBehavior.as.
Referenced by PostLoad(), and Save().
m_hasBossBarName
string m_hasBossBarName
Definition at line 96 of file CompositeActorBehavior.as.
Referenced by PostLoad(), and Save().
m_hitFx
string m_hitFx
Definition at line 82 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehavior(), and Damage().
m_holdAngleOnCast
bool m_holdAngleOnCast
Definition at line 79 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehavior().
m_hp
CompositeActorBehaviorNoNGPScale m_hp
Referenced by CompositeActorBehavior(), Damage(), Decimate(), GetHealth(), IsDead(), Kill(), Load(), NetDamage(), NetDecimate(), NetHeal(), Save(), and TriggerOnDeath().
m_hurtSound
SoundEvent m_hurtSound
Definition at line 61 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehavior(), and NetDamage().
m_immortal
bool m_immortal
Definition at line 50 of file CompositeActorBehavior.as.
Referenced by IsImmortal(), Load(), Save(), and SetImmortal().
m_immortalSound
SoundEvent m_immortalSound
Definition at line 62 of file CompositeActorBehavior.as.
Referenced by Damage().
m_impenetrable
bool m_impenetrable
Definition at line 47 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehavior(), and Impenetrable().
m_lootDef
LootDef m_lootDef
Definition at line 70 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehavior(), Configure(), and TriggerOnDeath().
m_maxHp
int m_maxHp
Definition at line 43 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehavior(), CompositeActorBehaviorNoNGPScale::GetMaxHp(), and GetMaxHp().
m_maxRange
uint m_maxRange
Definition at line 45 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehavior(), Configure(), and TargetValue().
m_movement
ActorMovement m_movement
Definition at line 58 of file CompositeActorBehavior.as.
Referenced by Collide(), CompositeActorBehavior(), Configure(), BossEye::Freeze(), GetDirection(), CompositeJammableActorBehavior::Jam(), Load(), NetDamage(), BossVampire::OnNodeArrived(), PostLoad(), QueuedPathfind(), and Save().
m_mpScaleFact
float m_mpScaleFact
Definition at line 44 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehavior(), CompositeActorBehaviorNoNGPScale::GetMaxHp(), and GetMaxHp().
m_mustSeeTarget
bool m_mustSeeTarget
Definition at line 67 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehavior(), Configure(), and TargetValue().
m_noBuffs
bool m_noBuffs
Definition at line 76 of file CompositeActorBehavior.as.
Referenced by ApplyBuff(), and CompositeActorBehavior().
m_skills
array<ICompositeActorSkill@> m_skills
Definition at line 57 of file CompositeActorBehavior.as.
Referenced by Skills::ArrowFlurry::ArrowFlurry(), Collide(), CompositeActorBehavior(), Damage(), Destroyed(), RangerProjectile::Initialize(), Skills::Juggernaut::Juggernaut(), NetUseSkill(), PostLoad(), Save(), Skills::Shatter::Shatter(), TriggerOnDeath(), and BossLich::Update().
m_target
Actor m_target
Definition at line 65 of file CompositeActorBehavior.as.
Referenced by BossEye::FindWispTargets(), NetDamage(), NetSetTarget(), SetTarget(), SpreadTarget(), TargetValue(), BossLich::Update(), and BossVampire::Update().
m_targetable
bool m_targetable
Definition at line 49 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehavior(), and IsTargetable().
m_targeting
bool m_targeting
Definition at line 66 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehavior(), and SpreadTarget().
m_targetSearchCd
int m_targetSearchCd
Definition at line 68 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehavior(), QueuedFetchActors(), BossLich::Update(), and BossVampire::Update().
m_unitHeight
int m_unitHeight
Definition at line 86 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehavior(), IconHeight(), and Miniboss::NetDamage().
m_windScale
float m_windScale
Definition at line 98 of file CompositeActorBehavior.as.
Referenced by CompositeActorBehavior(), and GetWindScale().