HoHDocs: scripts/Behaviors/Actors/Enemies/Skills/SkillConditional.as File Reference
SkillConditional.as File Reference
Classes
class SkillConditionalHealth
class CondHealthLess
class CondHealthLessEqual
class CondPlayersGreater
class CondPlayersGreaterEqual
class CondPlayersEqual
class SkillConditionalNGP
class CondNGPLess
class CondNGPLessEqual
class CondNGPNotEqual
Functions
SkillConditionalHealth ISkillConditional CondHealthGreater (float limit)
SkillConditionalHealth (float limit)
bool IsAllowed (CompositeActorBehavior@ owner)
CondHealthLess SkillConditionalHealth CondHealthGreaterEqual (float limit)
CondHealthLess (float limit)
SkillConditionalPlayers (int limit, bool includeDead)
int GetCount ()
CondPlayersGreater SkillConditionalPlayers CondPlayersLess (int limit, bool includeDead)
CondPlayersGreater (int limit, bool includeDead)
CondPlayersGreaterEqual SkillConditionalPlayers CondPlayersLessEqual (int limit, bool includeDead)
CondPlayersGreaterEqual (int limit, bool includeDead)
CondPlayersEqual SkillConditionalPlayers CondPlayersNotEqual (int limit, bool includeDead)
CondPlayersEqual (int limit, bool includeDead)
SkillConditionalNGP ISkillConditional CondNGPGreater (int limit)
SkillConditionalNGP (int limit)
CondNGPLess SkillConditionalNGP CondNGPGreaterEqual (int limit)
CondNGPLess (int limit)
CondNGPLessEqual SkillConditionalNGP CondNGPEqual (int limit)
CondNGPLessEqual (int limit)
CondFlag (string flag, bool exists)
array< ISkillConditional@> LoadSkillConditionals (UnitPtr owner, SValue &params)
bool CheckConditionals (array< ISkillConditional@>@ conditionals, CompositeActorBehavior@ behavior)
Variables
float m_limit
bool m_includeDead
CondNGPNotEqual m_flag
bool m_exists
Function Documentation
CheckConditionals()
bool CheckConditionals (array< ISkillConditional@>@ conditionals, CompositeActorBehavior@ behavior)
Definition at line 259 of file SkillConditional.as.
References IsAllowed().
Referenced by WerebullChargeHitSkill::IsAvailable(), IsAvailable(), NovaSkill::IsAvailable(), EnemyMeleeStrike::IsAvailable(), BlinkSkill::IsAvailable(), WhirlwindSkill::IsAvailable(), JumpStrike::IsAvailable(), SpewSkill::IsAvailable(), CompositeActorSkill::IsAvailable(), CompositeActorAuraSkill::Update(), and WhirlNovaSkill::Update().
 {
     if (conditionals !is null)
     {
         for (uint i = 0; i < conditionals.length(); i++)
             if (!conditionals[i].IsAllowed(behavior))
                 return false;
     }
     return true;
 }
CondFlag()
CondFlag (string flag, bool exists)
Definition at line 153 of file SkillConditional.as.
References m_exists, and m_flag.
Referenced by LoadSkillConditionals().
     {
         m_flag = flag;
         m_exists = exists;
     }
CondHealthGreater()
SkillConditionalHealth ISkillConditional CondHealthGreater (float limit) pure virtual
Definition at line 15 of file SkillConditional.as.
Referenced by LoadSkillConditionals().
 { super(limit); }
CondHealthGreaterEqual()
CondHealthLess SkillConditionalHealth CondHealthGreaterEqual (float limit)
Definition at line 27 of file SkillConditional.as.
Referenced by LoadSkillConditionals().
 { super(limit); }
CondHealthLess()
CondHealthGreaterEqual::CondHealthLess (float limit)
Definition at line 17 of file SkillConditional.as.
Referenced by LoadSkillConditionals().
 : SkillConditionalHealth
CondNGPEqual()
CondNGPLessEqual SkillConditionalNGP CondNGPEqual (int limit)
Definition at line 137 of file SkillConditional.as.
Referenced by LoadSkillConditionals().
 { super(limit); }
CondNGPGreater()
SkillConditionalNGP ISkillConditional CondNGPGreater (int limit) pure virtual
Definition at line 113 of file SkillConditional.as.
Referenced by LoadSkillConditionals().
 { super(limit); }
CondNGPGreaterEqual()
CondNGPLess SkillConditionalNGP CondNGPGreaterEqual (int limit)
Definition at line 125 of file SkillConditional.as.
Referenced by LoadSkillConditionals().
 { super(limit); }
CondNGPLess()
CondNGPGreaterEqual::CondNGPLess (int limit)
Definition at line 115 of file SkillConditional.as.
Referenced by LoadSkillConditionals().
 : SkillConditionalNGP
CondNGPLessEqual()
CondNGPEqual::CondNGPLessEqual (int limit)
Definition at line 127 of file SkillConditional.as.
Referenced by LoadSkillConditionals().
 : SkillConditionalNGP
CondPlayersEqual()
CondPlayersNotEqual::CondPlayersEqual (int limit, bool includeDead)
Definition at line 88 of file SkillConditional.as.
Referenced by LoadSkillConditionals().
 : SkillConditionalPlayers
CondPlayersGreater()
CondPlayersLess::CondPlayersGreater (int limit, bool includeDead)
Definition at line 46 of file SkillConditional.as.
References g_players, IsDead(), m_includeDead, max, and num.
Referenced by LoadSkillConditionals().
 {
CondPlayersGreaterEqual()
CondPlayersLessEqual::CondPlayersGreaterEqual (int limit, bool includeDead)
Definition at line 76 of file SkillConditional.as.
Referenced by LoadSkillConditionals().
 : SkillConditionalPlayers
CondPlayersLess()
CondPlayersGreater SkillConditionalPlayers CondPlayersLess (int limit, bool includeDead)
Definition at line 74 of file SkillConditional.as.
Referenced by LoadSkillConditionals().
 { super(limit, includeDead); }
CondPlayersLessEqual()
CondPlayersGreaterEqual SkillConditionalPlayers CondPlayersLessEqual (int limit, bool includeDead)
Definition at line 86 of file SkillConditional.as.
Referenced by LoadSkillConditionals().
 { super(limit, includeDead); }
CondPlayersNotEqual()
CondPlayersEqual SkillConditionalPlayers CondPlayersNotEqual (int limit, bool includeDead)
Definition at line 98 of file SkillConditional.as.
Referenced by LoadSkillConditionals().
 { super(limit, includeDead); }
GetCount()
int GetCount ()
Definition at line 45 of file SkillConditional.as.
Referenced by CondPlayersGreater::IsAllowed(), CondPlayersGreaterEqual::IsAllowed(), and CondPlayersEqual::IsAllowed().
     {
         int num = 0;
         for (uint i = 0; i < g_players.length(); i++)
         {
             if (g_players[i].peer == 255)
                 continue;
             if (!m_includeDead && g_players[i].IsDead())
                 continue;
             num++;
         }
         if (m_includeDead)
             num += max(0, GetVarInt("g_extra_players"));
         return num;
     }
IsAllowed()
bool IsAllowed (CompositeActorBehavior@ owner) override
Definition at line 4 of file SkillConditional.as.
Referenced by CheckConditionals().
 : ISkillConditional
LoadSkillConditionals()
array<ISkillConditional@> LoadSkillConditionals (UnitPtr owner, SValue & params)
Definition at line 166 of file SkillConditional.as.
References CondFlag(), CondHealthGreater(), CondHealthGreaterEqual(), CondHealthLess(), CondNGPEqual(), CondNGPGreater(), CondNGPGreaterEqual(), CondNGPLess(), CondNGPLessEqual(), CondPlayersEqual(), CondPlayersGreater(), CondPlayersGreaterEqual(), CondPlayersLess(), CondPlayersLessEqual(), and CondPlayersNotEqual().
Referenced by BlinkSkill::BlinkSkill(), CompositeActorAuraSkill::CompositeActorAuraSkill(), CompositeActorSkill::CompositeActorSkill(), CompositeActorTriggeredSkill(), EnemyMeleeStrike::EnemyMeleeStrike(), JumpStrike::JumpStrike(), NovaSkill::NovaSkill(), SpewSkill::SpewSkill(), WerebullChargeHitSkill::WerebullChargeHitSkill(), WhirlNovaSkill::WhirlNovaSkill(), and WhirlwindSkill::WhirlwindSkill().
 {
     auto condArr = GetParamArray(owner, params, "conditional", false);
     if (condArr is null)
         return null;
     array<ISkillConditional@> conditionals;
     for (uint i = 0; i < condArr.length(); i++)
     {
         auto start = condArr[i].GetString();
         if (start == "hp")
         {
             string cond = condArr[++i].GetString();
             float limit = condArr[++i].GetFloat();
             if (cond == "gt" || cond == ">")
                 conditionals.insertLast(CondHealthGreater(limit));
             else if (cond == "lt" || cond == "<")
                 conditionals.insertLast(CondHealthLess(limit));
             else if (cond == "ge" || cond == ">=")
                 conditionals.insertLast(CondHealthGreaterEqual(limit));
             else if (cond == "le" || cond == "<=")
                 conditionals.insertLast(CondHealthLessEqual(limit));
         }
         else if (start == "players")
         {
             string cond = condArr[++i].GetString();
             int limit = condArr[++i].GetInteger();
             if (cond == "gt" || cond == ">")
                 conditionals.insertLast(CondPlayersGreater(limit, true));
             else if (cond == "lt" || cond == "<")
                 conditionals.insertLast(CondPlayersLess(limit, true));
             else if (cond == "ge" || cond == ">=")
                 conditionals.insertLast(CondPlayersGreaterEqual(limit, true));
             else if (cond == "le" || cond == "<=")
                 conditionals.insertLast(CondPlayersLessEqual(limit, true));
             else if (cond == "eq" || cond == "==")
                 conditionals.insertLast(CondPlayersEqual(limit, true));
             else if (cond == "ne" || cond == "!=")
                 conditionals.insertLast(CondPlayersNotEqual(limit, true));
         }
         else if (start == "alive players")
         {
             string cond = condArr[++i].GetString();
             int limit = condArr[++i].GetInteger();
             if (cond == "gt" || cond == ">")
                 conditionals.insertLast(CondPlayersGreater(limit, false));
             else if (cond == "lt" || cond == "<")
                 conditionals.insertLast(CondPlayersLess(limit, false));
             else if (cond == "ge" || cond == ">=")
                 conditionals.insertLast(CondPlayersGreaterEqual(limit, false));
             else if (cond == "le" || cond == "<=")
                 conditionals.insertLast(CondPlayersLessEqual(limit, false));
             else if (cond == "eq" || cond == "==")
                 conditionals.insertLast(CondPlayersEqual(limit, false));
             else if (cond == "ne" || cond == "!=")
                 conditionals.insertLast(CondPlayersNotEqual(limit, false));
         }
         else if (start == "ngp")
         {
             string cond = condArr[++i].GetString();
             int limit = condArr[++i].GetInteger();
             if (cond == "gt" || cond == ">")
                 conditionals.insertLast(CondNGPGreater(limit));
             else if (cond == "lt" || cond == "<")
                 conditionals.insertLast(CondNGPLess(limit));
             else if (cond == "ge" || cond == ">=")
                 conditionals.insertLast(CondNGPGreaterEqual(limit));
             else if (cond == "le" || cond == "<=")
                 conditionals.insertLast(CondNGPLessEqual(limit));
             else if (cond == "eq" || cond == "==")
                 conditionals.insertLast(CondNGPEqual(limit));
             else if (cond == "ne" || cond == "!=")
                 conditionals.insertLast(CondNGPNotEqual(limit));
         }
         else if (start == "flag")
         {
             string cond = condArr[++i].GetString();
             string flag = condArr[++i].GetString();
             if (cond == "is")
                 conditionals.insertLast(CondFlag(flag, true));
             else if (cond == "isnt")
                 conditionals.insertLast(CondFlag(flag, false));
         }
     }
     return conditionals;
 }
SkillConditionalHealth()
CondHealthGreater::SkillConditionalHealth (float limit)
Definition at line 3 of file SkillConditional.as.
 : ISkillConditional
SkillConditionalNGP()
CondNGPGreater::SkillConditionalNGP (int limit)
Definition at line 102 of file SkillConditional.as.
 : ISkillConditional
SkillConditionalPlayers()
SkillConditionalPlayers (int limit, bool includeDead)
Definition at line 42 of file SkillConditional.as.
References m_includeDead, and m_limit.
 { m_limit = limit; m_includeDead = includeDead; }
Variable Documentation
m_exists
bool m_exists
Definition at line 151 of file SkillConditional.as.
Referenced by CondFlag().
m_flag
CondNGPNotEqual m_flag
Referenced by CondFlag().
m_includeDead
bool m_includeDead
Definition at line 40 of file SkillConditional.as.
Referenced by CondPlayersGreater(), and SkillConditionalPlayers().
m_limit
int m_limit
Definition at line 2 of file SkillConditional.as.
Referenced by CondPlayersGreater::IsAllowed(), CondPlayersGreaterEqual::IsAllowed(), CondPlayersEqual::IsAllowed(), and SkillConditionalPlayers().