HoHDocs: scripts/Behaviors/Actors/Enemies/Skills/CompositeActorSkill.as File Reference
CompositeActorSkill.as File Reference
Classes
class CompositeActorSkill
Functions
void Update (int dt, bool isCasting)
bool IsCasting ()
void OnDamaged ()
void OnDeath ()
void Destroyed ()
void OnCollide (UnitPtr unit, vec2 normal)
void NetUseSkill (int stage, SValue@ param)
void Save (SValueBuilder &builder)
void Load (SValue@ sval)
Function Documentation
Destroyed()
void Destroyed ()
Definition at line 633 of file CompositeActorBehavior.as.
References ActorBuffList::Clear(), Destroyed(), g_killedEnemies, m_buffs, and m_skills.
Referenced by Destroyed(), and WorldScript::UnitDestroyedTrigger::OnChanged().
     {
         if (m_countsAsKill)
             g_killedEnemies++;
         m_buffs.Clear();
         for (uint i = 0; i < m_skills.length(); i++)
             m_skills[i].Destroyed();
     }
IsCasting()
bool IsCasting ()
Definition at line 189 of file CompositeActorTriggeredSkill.as.
References m_animTimeC.
Referenced by BossLich::Update().
     {
         return m_animTimeC > 0;
     }
Load()
void Load (SValue@ sval)
Definition at line 307 of file CompositeActorBehavior.as.
References AddCurrentSplit(), All, Borders, Float(), Horizontal, Initialize(), m_background, m_frozen, m_height, m_hp, m_immortal, m_initialized, m_mode, m_movement, m_splits, m_totalTime, m_variations, m_width, ReloadSplits(), ScriptSprite(), and Vertical.
Referenced by BossVampire::Load(), BossEye::Load(), PostLoad(), SpriteRect(), and BaseGameMode::Start().
     {
         auto hp = data.GetDictionaryEntry("hp");
         if (hp !is null && hp.GetType() == SValueType::Float)
             m_hp = hp.GetFloat();
         auto immortal = data.GetDictionaryEntry("immortal");
         if (immortal !is null && immortal.GetType() == SValueType::Boolean)
             m_immortal = immortal.GetBoolean();
         auto frozen = data.GetDictionaryEntry("frozen");
         if (frozen !is null && frozen.GetType() == SValueType::Boolean)
             m_frozen = frozen.GetBoolean();
         if (m_movement !is null)
         {
             auto movement = data.GetDictionaryEntry("movement");
             if (movement !is null)
                 m_movement.Load(movement);
         }
     }
NetUseSkill()
void NetUseSkill (int stage, SValue@ param)
Definition at line 194 of file CompositeActorTriggeredSkill.as.
References ApplyEffects(), m_actions, m_behavior, m_castTarget, m_charges, m_effects, m_unit, NetDoActions(), NetTrigger(), and xy().
     {
         if (stage == 0)
             NetTrigger();
         else if (stage == 1)
         {
             vec2 dir = m_behavior.GetCastDirection();
             vec2 pos = xy(m_unit.GetPosition());
             NetDoActions(m_actions, param, m_behavior, pos, dir);
             if (m_castTarget.IsValid())
             {
                 auto b = cast<Actor>(m_castTarget.GetScriptBehavior());
                 if (b !is null and !b.IsTargetable())
                     return;
                 ApplyEffects(m_effects, m_behavior, m_castTarget, pos, dir, m_behavior.m_buffs.DamageMul(), !Network::IsServer());
             }
             if (m_charges > 0)
                 m_charges--;
         }
     }
OnCollide()
void OnCollide (UnitPtr unit, vec2 normal)
Definition at line 157 of file CompositeActorTriggeredSkill.as.
References IsAvailable(), m_targetSelf, m_trigger, m_unit, OnCollide, Trigger(), and unit.
     {
         if (m_trigger != SkillTrigger::OnCollide)
             return;
         if (!IsAvailable())
             return;
         UnitPtr target;
         if (m_targetSelf)
             target = m_unit;
         else
             target = unit;
         Trigger(target);
     }
OnDamaged()
void OnDamaged ()
Definition at line 124 of file CompositeActorTriggeredSkill.as.
References IsAvailable(), m_targetSelf, m_trigger, m_unit, OnDamaged, and Trigger().
     {
         if (m_trigger != SkillTrigger::OnDamaged)
             return;
         if (!IsAvailable())
             return;
         UnitPtr target;
         if (m_targetSelf)
             target = m_unit;
         Trigger(target);
     }
OnDeath()
void OnDeath ()
Definition at line 139 of file CompositeActorTriggeredSkill.as.
References IsAvailable(), m_targetSelf, m_trigger, m_unit, OnDeath, and Trigger().
     {
         if (m_trigger != SkillTrigger::OnDeath)
             return;
         if (!Network::IsServer())
             return;
         if (!IsAvailable())
             return;
         UnitPtr target;
         if (m_targetSelf)
             target = m_unit;
         Trigger(target);
     }
Save()
void Save (SValueBuilder & builder)
Definition at line 84 of file CompositeActorTriggeredSkill.as.
References Stats::Average, Stats::m_name, m_splits, m_totalTime, Stats::m_type, Stats::m_valueCount, Stats::m_valueInt, and Stats::Number.
Referenced by BaseGameMode::Save().
     {
     }
Update()
void Update (int dt, bool isCasting) override
Definition at line 77 of file FleeMovement.as.
References CastTrigger(), MeleeMovement::ClientUpdate(), distsq(), GetFleeRaycastSlots(), m_actions, m_animTimeC, m_behavior, m_castPointC, m_cooldownC, FleeTestResult::m_distToPlayerSq, m_dotScale, m_enabled, m_hasTargetPoint, m_hasTargetTime, Skills::m_orbs, FleeTestResult::m_pos, m_reaction, m_reactionC, m_reactionRandom, m_scatterAngle, m_spawned, MeleeMovement::m_speed, m_stopDistance, m_targetPoint, m_testCount, Skills::m_tmNow, m_unit, OnSpawn, rayCanSee(), rayCanSeeWithoutUnit(), MeleeMovement::SetWalkingAnimation(), TestDirection(), Update(), and xy().
Referenced by Update().
     {
         if (!m_enabled)
             return;
         ActorMovement::Update(dt, isCasting);
         if (!Network::IsServer())
         {
             ClientUpdate(dt, isCasting, m_unit.GetMoveDir());
             return;
         }
         float speed = m_speed;
         if (m_stagger > 0)
         {
             m_stagger -= dt;
             speed *= 0.5;
         }
         speed *= m_behavior.m_buffs.MoveSpeedMul();
         if (isCasting)
             return;
         if (m_behavior.m_target is null)
         {
             m_unit.GetPhysicsBody().SetLinearVelocity(0, 0);
             m_unit.SetUnitScene(m_idleAnim.GetSceneName(m_dir), false);
             return;
         }
         vec2 posMe = xy(m_unit.GetPosition());
         vec2 posPlayer = xy(m_behavior.m_target.m_unit.GetPosition());
         vec2 dir = normalize(posMe - posPlayer);
         uint raySlotsMask = GetFleeRaycastSlots();
         if (!m_hasTargetPoint)
         {
             //TODO: This keeps casting rays every frame if we're stuck in a corner with nowhere to go
             m_hasTargetTime = 0;
             vec2 hiddenPos = vec2();
             bool hidden = false;
             vec2 furthestPos = vec2();
             float furthest = 0;
             float radStep = 2.0 / float(m_testCount);
             for (int i = 0; i < m_testCount; i++)
             {
                 float scatter = randf() * m_scatterAngle;
                 float rad = scatter + PI * (i * radStep);
                 vec2 testDir = vec2(cos(rad), sin(rad));
                 if (dot(dir, testDir) < m_dotScale)
                     continue;
                 FleeTestResult@ res = TestDirection(rad);
                 if (res.m_distToPlayerSq > furthest)
                 {
                     furthest = res.m_distToPlayerSq;
                     furthestPos = res.m_pos;
                 }
                 if (!hidden && !rayCanSeeWithoutUnit(res.m_pos, m_behavior.m_target.m_unit, m_unit, raySlotsMask))
                 {
                     hidden = true;
                     hiddenPos = res.m_pos;
                 }
             }
             if (hidden)
             {
                 m_targetPoint = hiddenPos;
                 m_hasTargetPoint = true;
             }
             else
             {
                 m_targetPoint = furthestPos;
                 m_hasTargetPoint = true;
             }
             m_reactionC = m_reaction + randi(m_reactionRandom);
         }
         if (m_hasTargetPoint)
         {
             if (m_reactionC > 0)
             {
                 m_reactionC -= dt;
                 if (m_reactionC > 0)
                     return;
             }
             m_hasTargetTime += dt;
             //TODO: Limit time that can be spent running away?
             auto body = m_unit.GetPhysicsBody();
             // If after a while we're stuck
             if (m_hasTargetTime > 200 && length(body.GetLinearVelocity()) < 1)
             {
                 // We need a new target position
                 m_hasTargetPoint = false;
             }
             else
             {
                 // Navigate to target position
                 vec2 pathDir = normalize(m_targetPoint - posMe) * speed;
                 if (pathDir.x != 0 || pathDir.y != 0)
                 {
                     body.SetLinearVelocity(pathDir);
                     m_dir = atan(pathDir.y, pathDir.x);
                 }
                 SetWalkingAnimation();
                 if (m_footsteps !is null)
                 {
                     m_footsteps.m_facingDirection = m_dir;
                     m_footsteps.Update(dt);
                 }
                 float distance = distsq(posMe, m_targetPoint);
                 if (distance <= m_stopDistance * m_stopDistance)
                 {
                     m_hasTargetPoint = false;
                     if (!rayCanSee(m_unit, m_behavior.m_target.m_unit, RaycastType::Any))
                         m_behavior.SetTarget(null);
                 }
             }
         }
     }