HoHDocs: scripts/Behaviors/Actors/Enemies/Skills/CompositeActorTriggeredSkill.as File Reference
CompositeActorTriggeredSkill.as File Reference
Enumerations
enum SkillTrigger {
None, OnDeath, OnDamaged, OnCollide,
OnSpawn, OnMove, OnTime
}
Functions
CompositeActorTriggeredSkill (UnitPtr unit, SValue &params)
void Initialize (UnitPtr unit, CompositeActorBehavior &behavior, int id)
void Save (SValueBuilder &builder)
void Load (SValue@ sval)
bool IsAvailable ()
void Update (int dt, bool isCasting)
void OnDamaged ()
void OnDeath ()
void OnCollide (UnitPtr unit, vec2 normal)
void OnSpawn ()
bool IsCasting ()
void NetUseSkill (int stage, SValue@ param)
void Trigger (UnitPtr target)
void NetTrigger ()
void CastTrigger ()
void Destroyed ()
Variables
enum SkillTrigger m_trigger
bool m_targetSelf
AnimString m_anim
SoundEvent m_sndStart
int m_castPoint
int m_castPointC
vec2 m_castDir
vec2 m_castPos
UnitPtr m_castTarget
UnitPtr m_unit
CompositeActorBehavior m_behavior
int m_id
array< IAction@> m_actions
array< IEffect@> m_effects
array< ISkillConditional@> m_conditionals
bool m_spawned
int m_animTimeC
int m_cooldown
int m_cooldownC
int m_charges
Enumeration Type Documentation
SkillTrigger
enum SkillTrigger
Enumerator
None
OnDeath
OnDamaged
OnCollide
OnSpawn
OnMove
OnTime
Definition at line 1 of file CompositeActorTriggeredSkill.as.
 {
     None,
     OnDeath,
     OnDamaged,
     OnCollide,
     OnSpawn,
     OnMove,
     OnTime
 }
Function Documentation
CastTrigger()
void CastTrigger ()
Definition at line 255 of file CompositeActorTriggeredSkill.as.
References ApplyEffects(), DoActions(), m_actions, m_behavior, m_castDir, m_castPos, m_castTarget, m_charges, m_effects, m_id, m_unit, and UnitHandler::NetSendUnitUseSkill().
Referenced by Trigger(), and Update().
     {
         SValue@ param = DoActions(m_actions, m_behavior, m_behavior.m_target, m_castPos, m_castDir, m_behavior.m_buffs.DamageMul());
         UnitHandler::NetSendUnitUseSkill(m_unit, m_id, 1, param);
         if (m_castTarget.IsValid())
         {
             auto b = cast<Actor>(m_castTarget.GetScriptBehavior());
             if (b !is null and !b.IsTargetable())
                 return;
             ApplyEffects(m_effects, m_behavior, m_castTarget, m_castPos, m_castDir, m_behavior.m_buffs.DamageMul(), !Network::IsServer());
         }
         if (m_charges > 0)
             m_charges--;
     }
CompositeActorTriggeredSkill()
CompositeActorTriggeredSkill (UnitPtr unit, SValue & params)
Definition at line 43 of file CompositeActorTriggeredSkill.as.
References LoadActions(), LoadEffects(), LoadSkillConditionals(), m_actions, m_anim, m_castPoint, m_charges, m_conditionals, m_cooldown, m_cooldownC, m_effects, m_sndStart, m_targetSelf, m_trigger, None, OnCollide, OnDamaged, OnDeath, OnSpawn, and unit.
     {
         m_trigger = SkillTrigger::None;
         string trigger = GetParamString(unit, params, "trigger");
         if (trigger == "OnDeath")
             m_trigger = SkillTrigger::OnDeath;
         else if (trigger == "OnDamaged")
             m_trigger = SkillTrigger::OnDamaged;
         else if (trigger == "OnCollide")
             m_trigger = SkillTrigger::OnCollide;
         else if (trigger == "OnSpawn")
             m_trigger = SkillTrigger::OnSpawn;
         @m_actions = LoadActions(unit, params);
         @m_effects = LoadEffects(unit, params);
         m_targetSelf = GetParamBool(unit, params, "targetself", false, true);
         @m_conditionals = LoadSkillConditionals(unit, params);
         string strAnim = GetParamString(unit, params, "anim", false);
         if (strAnim != "")
             @m_anim = AnimString(strAnim);
         @m_sndStart = Resources::GetSoundEvent(GetParamString(unit, params, "start-snd", false));
         m_castPoint = GetParamInt(unit, params, "castpoint", false);
         m_cooldown = GetParamInt(unit, params, "cooldown", false, 0);
         m_cooldownC = GetParamInt(unit, params, "cooldown-start", false, m_cooldown);
         m_charges = GetParamInt(unit, params, "charges", false, -1);
     }
Destroyed()
void Destroyed ()
Definition at line 273 of file CompositeActorTriggeredSkill.as.
References ActorBuffList::Clear(), Destroyed(), g_killedEnemies, m_buffs, and m_skills.
 { }
Initialize()
void Initialize (UnitPtr unit, CompositeActorBehavior & behavior, int id)
Definition at line 77 of file CompositeActorTriggeredSkill.as.
References id, m_behavior, m_id, m_unit, and unit.
Referenced by PassiveMovement::Initialize(), Modifiers::MoveFilter::Initialize(), Modifiers::EnemyTypeFilter::Initialize(), Modifiers::HealthFilter::Initialize(), Skills::PassiveSkill::Initialize(), Skills::ExtendedDomain::Initialize(), Skills::Whirlwind::Initialize(), BossLichMovement::Initialize(), Skills::ShootRay::Initialize(), Skills::Juggernaut::Initialize(), CompositeActorPeriodicTriggeredSkill::Initialize(), Skills::DropEffect::Initialize(), Projectile::Initialize(), Skills::Charge::Initialize(), Skills::Explode::Initialize(), Skills::SpewProjectiles::Initialize(), BossVampireMovement::Initialize(), RayProjectile::Initialize(), MeleeMovement::Initialize(), CannonBall::Initialize(), Skills::MeleeSwing::Initialize(), and BaseGameMode::SpawnPlayer().
     {
         m_unit = unit;
         @m_behavior = behavior;
         m_id = id;
     }
IsAvailable()
bool IsAvailable ()
Definition at line 92 of file CompositeActorTriggeredSkill.as.
References CheckConditionals(), m_behavior, m_charges, and m_conditionals.
Referenced by OnCollide(), OnDamaged(), OnDeath(), OnSpawn(), BossLichRandomSkill::Update(), and CompositeActorPeriodicTriggeredSkill::Update().
     {
         if (m_charges == 0)
             return false;
         return CheckConditionals(m_conditionals, m_behavior);
     }
IsCasting()
bool IsCasting ()
Definition at line 189 of file CompositeActorTriggeredSkill.as.
References m_animTimeC.
Referenced by BossLich::Update().
     {
         return m_animTimeC > 0;
     }
Load()
void Load (SValue@ sval)
Definition at line 88 of file CompositeActorTriggeredSkill.as.
     {
     }
NetTrigger()
void NetTrigger ()
Definition at line 245 of file CompositeActorTriggeredSkill.as.
References AnimString::GetSceneName(), m_anim, m_animTimeC, m_behavior, and m_unit.
Referenced by NetUseSkill().
     {
         if (m_anim !is null)
         {
             vec2 dir = m_behavior.GetCastDirection();
             m_unit.SetUnitScene(m_anim.GetSceneName(atan(dir.y, dir.x)), true);
             m_animTimeC = m_unit.GetCurrentUnitScene().Length();
         }
     }
NetUseSkill()
void NetUseSkill (int stage, SValue@ param)
Definition at line 194 of file CompositeActorTriggeredSkill.as.
References ApplyEffects(), m_actions, m_behavior, m_castTarget, m_charges, m_effects, m_unit, NetDoActions(), NetTrigger(), and xy().
     {
         if (stage == 0)
             NetTrigger();
         else if (stage == 1)
         {
             vec2 dir = m_behavior.GetCastDirection();
             vec2 pos = xy(m_unit.GetPosition());
             NetDoActions(m_actions, param, m_behavior, pos, dir);
             if (m_castTarget.IsValid())
             {
                 auto b = cast<Actor>(m_castTarget.GetScriptBehavior());
                 if (b !is null and !b.IsTargetable())
                     return;
                 ApplyEffects(m_effects, m_behavior, m_castTarget, pos, dir, m_behavior.m_buffs.DamageMul(), !Network::IsServer());
             }
             if (m_charges > 0)
                 m_charges--;
         }
     }
OnCollide()
void OnCollide (UnitPtr unit, vec2 normal)
Definition at line 157 of file CompositeActorTriggeredSkill.as.
References IsAvailable(), m_targetSelf, m_trigger, m_unit, OnCollide, Trigger(), and unit.
     {
         if (m_trigger != SkillTrigger::OnCollide)
             return;
         if (!IsAvailable())
             return;
         UnitPtr target;
         if (m_targetSelf)
             target = m_unit;
         else
             target = unit;
         Trigger(target);
     }
OnDamaged()
void OnDamaged ()
Definition at line 124 of file CompositeActorTriggeredSkill.as.
References IsAvailable(), m_targetSelf, m_trigger, m_unit, OnDamaged, and Trigger().
     {
         if (m_trigger != SkillTrigger::OnDamaged)
             return;
         if (!IsAvailable())
             return;
         UnitPtr target;
         if (m_targetSelf)
             target = m_unit;
         Trigger(target);
     }
OnDeath()
void OnDeath ()
Definition at line 139 of file CompositeActorTriggeredSkill.as.
References IsAvailable(), m_targetSelf, m_trigger, m_unit, OnDeath, and Trigger().
     {
         if (m_trigger != SkillTrigger::OnDeath)
             return;
         if (!Network::IsServer())
             return;
         if (!IsAvailable())
             return;
         UnitPtr target;
         if (m_targetSelf)
             target = m_unit;
         Trigger(target);
     }
OnSpawn()
void OnSpawn ()
Definition at line 174 of file CompositeActorTriggeredSkill.as.
References IsAvailable(), m_targetSelf, m_trigger, m_unit, OnSpawn, and Trigger().
     {
         if (m_trigger != SkillTrigger::OnSpawn)
             return;
         if (!IsAvailable())
             return;
         UnitPtr target;
         if (m_targetSelf)
             target = m_unit;
         Trigger(target);
     }
Save()
void Save (SValueBuilder & builder)
Definition at line 84 of file CompositeActorTriggeredSkill.as.
     {
     }
Trigger()
void Trigger (UnitPtr target)
Definition at line 218 of file CompositeActorTriggeredSkill.as.
References CastTrigger(), AnimString::GetSceneName(), m_anim, m_animTimeC, m_behavior, m_castDir, m_castPoint, m_castPointC, m_castPos, m_castTarget, m_cooldown, m_cooldownC, m_id, m_sndStart, m_unit, UnitHandler::NetSendUnitUseSkill(), PlaySound3D(), and xy().
Referenced by OnCollide(), OnDamaged(), OnDeath(), OnSpawn(), BossLichRandomSkill::Trigger(), and CompositeActorPeriodicTriggeredSkill::Update().
     {
         if (m_cooldownC > 0)
             return;
         m_cooldownC = m_cooldown;
         m_castDir = m_behavior.GetCastDirection();
         m_castPos = xy(m_unit.GetPosition());
         if (m_anim !is null)
         {
             m_unit.SetUnitScene(m_anim.GetSceneName(atan(m_castDir.y, m_castDir.x)), true);
             m_animTimeC = m_unit.GetCurrentUnitScene().Length();
         }
         if (m_sndStart !is null)
             PlaySound3D(m_sndStart, m_unit);
         UnitHandler::NetSendUnitUseSkill(m_unit, m_id, 0, null);
         m_castPointC = m_castPoint;
         m_castTarget = target;
         if (m_castPointC <= 0)
             CastTrigger();
     }
Update()
void Update (int dt, bool isCasting) override
Definition at line 100 of file CompositeActorTriggeredSkill.as.
References CastTrigger(), m_actions, m_animTimeC, m_castPointC, m_cooldownC, m_spawned, and OnSpawn.
     {
         if (m_cooldownC > 0)
             m_cooldownC -= dt;
         if (m_castPointC > 0)
         {
             m_castPointC -= dt;
             if (m_castPointC <= 0)
                 CastTrigger();
         }
         if (m_animTimeC > 0)
             m_animTimeC -= dt;
         if (!m_spawned)
         {
             m_spawned = true; // TODO: Save flag
             OnSpawn();
         }
         for (uint i = 0; i < m_actions.length(); i++)
             m_actions[i].Update(dt, 0);
     }
Variable Documentation
m_actions
array<IAction@> m_actions
Definition at line 31 of file CompositeActorTriggeredSkill.as.
Referenced by CastTrigger(), CompositeActorTriggeredSkill(), NetUseSkill(), and Update().
m_anim
AnimString m_anim
Definition at line 17 of file CompositeActorTriggeredSkill.as.
Referenced by CompositeActorTriggeredSkill(), NetTrigger(), and Trigger().
m_animTimeC
int m_animTimeC
Definition at line 37 of file CompositeActorTriggeredSkill.as.
Referenced by IsCasting(), NetTrigger(), Trigger(), and Update().
m_behavior
CompositeActorBehavior m_behavior
Definition at line 28 of file CompositeActorTriggeredSkill.as.
Referenced by CastTrigger(), Initialize(), IsAvailable(), NetTrigger(), NetUseSkill(), TestDirection(), Trigger(), Update(), BossLichRandomSkill::Update(), and CompositeActorPeriodicTriggeredSkill::Update().
m_castDir
vec2 m_castDir
Definition at line 23 of file CompositeActorTriggeredSkill.as.
Referenced by CastTrigger(), and Trigger().
m_castPoint
int m_castPoint
Definition at line 21 of file CompositeActorTriggeredSkill.as.
Referenced by CompositeActorTriggeredSkill(), and Trigger().
m_castPointC
int m_castPointC
Definition at line 22 of file CompositeActorTriggeredSkill.as.
Referenced by Trigger(), CompositeActorPeriodicTriggeredSkill::Update(), and Update().
m_castPos
vec2 m_castPos
Definition at line 24 of file CompositeActorTriggeredSkill.as.
Referenced by CastTrigger(), and Trigger().
m_castTarget
UnitPtr m_castTarget
Definition at line 25 of file CompositeActorTriggeredSkill.as.
Referenced by CastTrigger(), CompositeActorPeriodicTriggeredSkill::CompositeActorPeriodicTriggeredSkill(), NetUseSkill(), and Trigger().
m_charges
int m_charges
Definition at line 40 of file CompositeActorTriggeredSkill.as.
Referenced by CastTrigger(), CompositeActorTriggeredSkill(), IsAvailable(), and NetUseSkill().
m_conditionals
array<ISkillConditional@> m_conditionals
Definition at line 34 of file CompositeActorTriggeredSkill.as.
Referenced by CompositeActorTriggeredSkill(), and IsAvailable().
m_cooldown
int m_cooldown
Definition at line 38 of file CompositeActorTriggeredSkill.as.
Referenced by CompositeActorTriggeredSkill(), Skills::HandleBeam(), and Trigger().
m_cooldownC
int m_cooldownC
Definition at line 39 of file CompositeActorTriggeredSkill.as.
Referenced by CompositeActorTriggeredSkill(), Skills::HandleBeam(), Trigger(), and Update().
m_effects
array<IEffect@> m_effects
Definition at line 32 of file CompositeActorTriggeredSkill.as.
Referenced by CastTrigger(), CompositeActorTriggeredSkill(), and NetUseSkill().
m_id
int m_id
Definition at line 29 of file CompositeActorTriggeredSkill.as.
Referenced by CastTrigger(), CharacterColors::GetClass(), Upgrades::GetShop(), Statues::GetStatue(), TownRecord::GetStatue(), GuildHallItemiaryTab(), Initialize(), and Trigger().
m_sndStart
SoundEvent m_sndStart
Definition at line 19 of file CompositeActorTriggeredSkill.as.
Referenced by CompositeActorTriggeredSkill(), and Trigger().
m_spawned
bool m_spawned
Definition at line 36 of file CompositeActorTriggeredSkill.as.
Referenced by Update().
m_targetSelf
bool m_targetSelf
Definition at line 15 of file CompositeActorTriggeredSkill.as.
Referenced by CompositeActorTriggeredSkill(), OnCollide(), OnDamaged(), OnDeath(), and OnSpawn().
m_trigger
enum SkillTrigger m_trigger
Referenced by CompositeActorPeriodicTriggeredSkill::CompositeActorPeriodicTriggeredSkill(), CompositeActorTriggeredSkill(), OnCollide(), OnDamaged(), OnDeath(), OnSpawn(), and CompositeActorPeriodicTriggeredSkill::Update().
m_unit
UnitPtr m_unit
Definition at line 27 of file CompositeActorTriggeredSkill.as.
Referenced by BossEye::AddWisps(), ApplyBuff(), BossEye::BossEye(), CastTrigger(), CompositeActorBehavior(), CompositeActorPeriodicTriggeredSkill::CompositeActorPeriodicTriggeredSkill(), Configure(), Damage(), Decimate(), Destroy(), BossEye::Freeze(), BossLich::GetCastDirection(), BossVampire::GetCastDirection(), GetOffset(), Heal(), CompositeActorPeriodicTriggeredSkill::Initialize(), Initialize(), BossLich::IsTargetable(), BossVampire::IsTargetable(), CompositeJammableActorBehavior::Jam(), JammableBehavior::Jam(), BossEye::NetAddWisps(), NetDamage(), NetSetTarget(), NetTrigger(), NetUseSkill(), OnCollide(), OnDamaged(), OnDeath(), BossVampire::OnNodeArrived(), OnSpawn(), QueuedFetchActors(), TripMine::SetIdleAnimation(), SetTarget(), SetUnitScene(), BossEye::Suspend(), TestDirection(), Trigger(), TriggerOnDeath(), TripMine::TripMine(), CompositeJammableActorBehavior::Unjam(), JammableBehavior::Unjam(), BossEye::Unsuspend(), BossLichRandomSkill::Update(), BossLich::Update(), Update(), CompositeJammableActorBehavior::Update(), CompositeActorPeriodicTriggeredSkill::Update(), TripMine::Update(), BossVampire::Update(), and BossEye::Update().