HoHDocs: scripts/Behaviors/Armor.as File Reference
Armor.as File Reference
Classes
class ArmorDef
Functions
float CalcArmor (float armor)
vec2 ApplyArmorParts (DamageInfo dmg, vec2 armor, float damageMul)
int ApplyArmor (DamageInfo dmg, vec2 armor, float damageMul)
class ArmorDef BlockBuff (ActorBuff@ buff, ArmorDef@ armor, int armorAmnt)
ArmorDef (uint pathHash, SValue &params)
int damage_round (float f)
int armor_round (float f)
int ApplyArmor (ArmorDef@ armor, DamageInfo dmg, int armorIn, int &out armorOut, float damageMul=1.0f, vec3 pos=vec3())
ArmorDef LoadArmorDef (string path)
ArmorDef LoadArmorDef (uint pathHash)
Variables
uint m_pathHash
SoundEvent m_sound
float m_mulTrap
float m_mulPierce
float m_mulBlunt
float m_mulExplosion
float m_mulBio
float m_mulFire
float m_mulEnergy
float m_mulFrost
array< ArmorDef@> g_armorDefs
Function Documentation
ApplyArmor() [1/2]
int ApplyArmor (DamageInfo dmg, vec2 armor, float damageMul)
Definition at line 15 of file Armor.as.
Referenced by Player::Damage().
 {
     if (dmg.DamageType == 0)
         return -dmg.PhysicalDamage;
     vec2 ret = ApplyArmorParts(dmg, armor, damageMul);
     return max(0, damage_round(ret.x + ret.y));
 }
ApplyArmor() [2/2]
int ApplyArmor (ArmorDef@ armor, DamageInfo dmg, int armorIn, int &out armorOut, float damageMul = 1.0f, vec3 pos = vec3())
Definition at line 119 of file Armor.as.
References armor_round(), BIO, BLUNT, DamageInfo::Damage, DamageInfo::DamageType, ENERGY, EXPLOSION, FIRE, FROST, ArmorDef::m_mulBio, ArmorDef::m_mulBlunt, ArmorDef::m_mulEnergy, ArmorDef::m_mulExplosion, ArmorDef::m_mulFire, ArmorDef::m_mulFrost, ArmorDef::m_mulPierce, ArmorDef::m_mulTrap, ArmorDef::m_sound, PIERCING, PlaySound3D(), and TRAP.
 {
     armorOut = armorIn;
     if (dmg.DamageType == 0)
         return -dmg.Damage;
     float incDmg = dmg.Damage * damageMul;
     if (armorIn <= 0)
         return armor_round(incDmg);
     float dmgMul = 0;
     if (armor !is null)
     {
         int dmgTypeNum = 0;
         if (dmg.DamageType & uint8(DamageType::TRAP) != 0)      { dmgTypeNum++; dmgMul += armor.m_mulTrap; }
         if (dmg.DamageType & uint8(DamageType::PIERCING) != 0)  { dmgTypeNum++; dmgMul += armor.m_mulPierce; }
         if (dmg.DamageType & uint8(DamageType::BLUNT) != 0)     { dmgTypeNum++; dmgMul += armor.m_mulBlunt; }
         if (dmg.DamageType & uint8(DamageType::EXPLOSION) != 0) { dmgTypeNum++; dmgMul += armor.m_mulExplosion; }
         if (dmg.DamageType & uint8(DamageType::BIO) != 0)       { dmgTypeNum++; dmgMul += armor.m_mulBio; }
         if (dmg.DamageType & uint8(DamageType::FIRE) != 0)      { dmgTypeNum++; dmgMul += armor.m_mulFire; }
         if (dmg.DamageType & uint8(DamageType::ENERGY) != 0)    { dmgTypeNum++; dmgMul += armor.m_mulEnergy; }
         if (dmg.DamageType & uint8(DamageType::FROST) != 0)     { dmgTypeNum++; dmgMul += armor.m_mulFrost; }
         dmgMul /= dmgTypeNum;
         if (armor.m_sound !is null)
             PlaySound3D(armor.m_sound, pos, { { "dmg-mul", dmgMul } });
     }
     else
         dmgMul = 1.0;
     float res = incDmg * dmgMul;
     float diff = abs(incDmg - res);
     if (diff == 0)
         return armor_round(incDmg);
     int finalDmg = int(lerp(incDmg, res, min(1.0f, armorIn / diff)) + 0.5f);
     armorOut = max(0, armorIn - (max(0, int(incDmg) - finalDmg)));
     return finalDmg;
 }
ApplyArmorParts()
vec2 ApplyArmorParts (DamageInfo dmg, vec2 armor, float damageMul)
Definition at line 7 of file Armor.as.
References CalcArmor(), DamageInfo::MagicalDamage, and DamageInfo::PhysicalDamage.
Referenced by Damage().
 {
     float physDmg = CalcArmor(armor.x) * damageMul * dmg.PhysicalDamage;
     float magicDmg = CalcArmor(armor.y) * damageMul * dmg.MagicalDamage;
     return vec2(physDmg, magicDmg);
 }
armor_round()
int armor_round (float f)
Definition at line 105 of file Armor.as.
Referenced by ApplyArmor().
 {
     int i = int(f + 0.5f);
     if (i == 0)
     {
         if (f > 0)
             return 1;
         if (f < 0)
             return -1;
     }
     return i;
 }
ArmorDef()
BlockBuff::ArmorDef (uint pathHash, SValue & params)
Definition at line 29 of file Armor.as.
Referenced by LoadArmorDef().
     {
         m_pathHash = pathHash;
BlockBuff()
class ArmorDef BlockBuff (ActorBuff@ buff, ArmorDef@ armor, int armorAmnt)
Definition at line 58 of file Armor.as.
References BIO, BLUNT, buff, ENERGY, EXPLOSION, FIRE, FROST, ArmorDef::m_mulBio, ArmorDef::m_mulBlunt, ArmorDef::m_mulEnergy, ArmorDef::m_mulExplosion, ArmorDef::m_mulFire, ArmorDef::m_mulFrost, ArmorDef::m_mulPierce, ArmorDef::m_mulTrap, PIERCING, and TRAP.
Referenced by Player::ApplyBuff().
 {
     if (armorAmnt <= 0)
         return false;
     auto dmgType = buff.m_def.m_buffDmgType;
     if (dmgType == 0)
         return false;
     if (armor !is null)
     {
         float dmgMul = 0;
         if (dmgType & uint8(DamageType::TRAP) != 0)         { dmgMul += armor.m_mulTrap; }
         if (dmgType & uint8(DamageType::PIERCING) != 0)     { dmgMul += armor.m_mulPierce; }
         if (dmgType & uint8(DamageType::BLUNT) != 0)        { dmgMul += armor.m_mulBlunt; }
         if (dmgType & uint8(DamageType::EXPLOSION) != 0)    { dmgMul += armor.m_mulExplosion; }
         if (dmgType & uint8(DamageType::BIO) != 0)          { dmgMul += armor.m_mulBio; }
         if (dmgType & uint8(DamageType::FIRE) != 0)         { dmgMul += armor.m_mulFire; }
         if (dmgType & uint8(DamageType::ENERGY) != 0)       { dmgMul += armor.m_mulEnergy; }
         if (dmgType & uint8(DamageType::FROST) != 0)        { dmgMul += armor.m_mulFrost; }
         if (dmgMul <= 0)
             return true;
     }
     return false;
 }
CalcArmor()
float CalcArmor (float armor)
Definition at line 1 of file Armor.as.
References max.
Referenced by ApplyArmorParts(), and PlayerMenuCharacterTab::UpdateFromRecord().
 {
     float a = armor * 0.02;
     return 1.0f - a / (1.0f + max(0.0f, a));
 }
damage_round()
int damage_round (float f)
Definition at line 86 of file Armor.as.
Referenced by Damage(), Player::DamageActor(), Modifiers::Thorns::DamageTaken(), DoDamageUnits(), and CannonBall::HitUnit().
 {
     if (f == 0)
         return 0;
     int i;
     if (f < 0)
         i = int(f - 0.5f);
     else
         i = int(f + 0.5f);
     if (f > 0.01 && f < 1)
         i = 1;
     else if (f < 0.01 && f > -1)
         i = -1;
     return i;
 }
LoadArmorDef() [1/2]
ArmorDef LoadArmorDef (string path)
Definition at line 167 of file Armor.as.
Referenced by GiveArmor::GiveArmor(), BaseGameMode::LoadPlayer(), and PlayerHandler::PlayerSyncArmor().
 {
     if (path == "")
         return null;
     return LoadArmorDef(HashString(path));
 }
LoadArmorDef() [2/2]
ArmorDef LoadArmorDef (uint pathHash)
Definition at line 175 of file Armor.as.
References ArmorDef(), g_armorDefs, and m_pathHash.
 {
     for (uint i = 0; i < g_armorDefs.length(); i++)
         if (g_armorDefs[i].m_pathHash == pathHash)
             return g_armorDefs[i];
     SValue@ armor = Resources::GetSValue(pathHash);
     if (armor is null)
         return null;
     auto ret = ArmorDef(pathHash, armor);
     g_armorDefs.insertLast(@ret);
     return ret;
 }
Variable Documentation
g_armorDefs
array<ArmorDef@> g_armorDefs
Definition at line 165 of file Armor.as.
Referenced by LoadArmorDef().
m_mulBio
float m_mulBio
Definition at line 24 of file Armor.as.
m_mulBlunt
float m_mulBlunt
Definition at line 22 of file Armor.as.
m_mulEnergy
float m_mulEnergy
Definition at line 26 of file Armor.as.
m_mulExplosion
float m_mulExplosion
Definition at line 23 of file Armor.as.
m_mulFire
float m_mulFire
Definition at line 25 of file Armor.as.
m_mulFrost
float m_mulFrost
Definition at line 27 of file Armor.as.
m_mulPierce
float m_mulPierce
Definition at line 21 of file Armor.as.
m_mulTrap
float m_mulTrap
Definition at line 20 of file Armor.as.
m_pathHash
uint m_pathHash
Definition at line 16 of file Armor.as.
Referenced by LoadArmorDef().
m_sound
SoundEvent m_sound
Definition at line 18 of file Armor.as.