HoHDocs: scripts/Behaviors/Actors/TavernDrink.as File Reference
TavernDrink.as File Reference
Classes
class TavernDrink
Functions
class TavernDrink GetTavernDrink (ActorItemQuality quality)
int opCmp (const TavernDrink &other)
TavernDrink GetTavernDrink (uint idHash)
void AddDrinkFile (SValue@ sval)
Variables
string id
uint idHash
string name
string desc
ScriptSprite icon
ActorItemQuality quality
int cost
bool unlocked
ActorBuffDef buff
array< Modifiers::Modifier@> modifiers
int localCount
array< TavernDrink@> g_tavernDrinks
Function Documentation
AddDrinkFile()
void AddDrinkFile (SValue@ sval)
Definition at line 68 of file TavernDrink.as.
 {
     auto drinksData = sval.GetDictionary();
     array<string>@ drinksKeys = drinksData.getKeys();
     for (uint i = 0; i < drinksKeys.length(); i++)
     {
         auto drinkData = cast<SValue>(drinksData[drinksKeys[i]]);
         auto iconArray = GetParamArray(UnitPtr(), drinkData, "icon", false);
         TavernDrink@ tDrink = TavernDrink();
         tDrink.id = drinksKeys[i];
         tDrink.idHash = HashString(drinksKeys[i]);
         tDrink.name = GetParamString(UnitPtr(), drinkData, "name", false, "unknown");
         tDrink.desc = GetParamString(UnitPtr(), drinkData, "desc", false, "unknown");
         @tDrink.icon = ScriptSprite(iconArray);
         tDrink.quality = ParseActorItemQuality(GetParamString(UnitPtr(), drinkData, "quality", false, "common"));
         tDrink.cost = GetParamInt(UnitPtr(), drinkData, "cost", false, 0);
         tDrink.unlocked = GetParamBool(UnitPtr(), drinkData, "unlocked", false, false);
         @tDrink.buff = LoadActorBuff(GetParamString(UnitPtr(), drinkData, "buff", false));
         tDrink.modifiers = Modifiers::LoadModifiers(UnitPtr(), drinkData, "", Modifiers::SyncVerb::Drink, tDrink.idHash);
         tDrink.localCount = -1;
         g_tavernDrinks.insertLast(tDrink);
     }
     g_tavernDrinks.sortDesc();
 }
GetTavernDrink() [1/2]
TavernDrink GetTavernDrink (uint idHash)
Definition at line 57 of file TavernDrink.as.
 {
     for (uint i = 0; i < g_tavernDrinks.length(); i++)
     {
         if (g_tavernDrinks[i].idHash == idHash)
             return g_tavernDrinks[i];
     }
     return null;
 }
GetTavernDrink() [2/2]
class TavernDrink GetTavernDrink (ActorItemQuality quality)
Definition at line 34 of file TavernDrink.as.
References g_tavernDrinks, and quality.
Referenced by GiveDrinkCFunc(), GiveDrinksCFunc(), TavernBarrel::Initialize(), TavernBarrel::Load(), TownRecord::Load(), Campaign::LoadPlayer(), PlayerHandler::ModifierTriggerEffect(), DrinksMenuContent::OnFunc(), PlayerBase::RefreshModifiers(), and WinCash().
 {
     int start = -1;
     int end = -1;
     for (uint i = 0; i < g_tavernDrinks.length(); i++)
     {
         if (g_tavernDrinks[i].quality == quality && start < 0)
             start = i;
         if (g_tavernDrinks[i].quality != quality && start >= 0 && end < 0)
             end = i;
     }
     if (end < 0)
         end = g_tavernDrinks.length();
     if (end < 0 || start < 0)
         return null;
     return g_tavernDrinks[randi(end - start) + start];
 }
opCmp()
int GetTavernDrink::opCmp (const TavernDrink & other)
Definition at line 73 of file TavernDrink.as.
References TavernDrink::buff, TavernDrink::cost, TavernDrink::desc, Modifiers::Drink, g_tavernDrinks, TavernDrink::icon, TavernDrink::id, TavernDrink::idHash, LoadActorBuff(), Modifiers::LoadModifiers(), TavernDrink::localCount, TavernDrink::modifiers, TavernDrink::name, ParseActorItemQuality(), TavernDrink::quality, ScriptSprite(), and TavernDrink::unlocked.
     {
         auto drinkData = cast<SValue>(drinksData[drinksKeys[i]]);
         auto iconArray = GetParamArray(UnitPtr(), drinkData, "icon", false);
         TavernDrink@ tDrink = TavernDrink();
         tDrink.id = drinksKeys[i];
         tDrink.idHash = HashString(drinksKeys[i]);
         tDrink.name = GetParamString(UnitPtr(), drinkData, "name", false, "unknown");
         tDrink.desc = GetParamString(UnitPtr(), drinkData, "desc", false, "unknown");
         @tDrink.icon = ScriptSprite(iconArray);
         tDrink.quality = ParseActorItemQuality(GetParamString(UnitPtr(), drinkData, "quality", false, "common"));
         tDrink.cost = GetParamInt(UnitPtr(), drinkData, "cost", false, 0);
         tDrink.unlocked = GetParamBool(UnitPtr(), drinkData, "unlocked", false, false);
Variable Documentation
buff
ActorBuffDef buff
Definition at line 68 of file TavernDrink.as.
Referenced by ActorBuffList::Add(), PlayerBase::ApplyBuff(), ApplyBuff(), Player::ApplyBuff(), BlockBuff(), PlayerBase::HasBuff(), HasBuff(), ActorBuffList::HasTags(), LoadActorBuff(), Campaign::LoadPlayer(), WorldScript::RandomPossibleBuff::RandomPossibleBuff(), PlayerBase::RefreshModifiers(), PlayerBase::RefreshModifiersBuffs(), HUD::ShowBuffIcon(), and ActorBuffList::UpdateVisual().
cost
int cost
Definition at line 65 of file TavernDrink.as.
desc
string desc
Definition at line 62 of file TavernDrink.as.
g_tavernDrinks
array<TavernDrink@> g_tavernDrinks
Definition at line 101 of file TavernDrink.as.
Referenced by GetTavernDrink(), opCmp(), DrinksMenuContent::ReloadList(), ReloadList(), TownRecord::Save(), and Town::Start().
icon
ScriptSprite icon
Definition at line 63 of file TavernDrink.as.
id
string id
Definition at line 59 of file TavernDrink.as.
idHash
uint idHash
Definition at line 60 of file TavernDrink.as.
localCount
int localCount
Definition at line 71 of file TavernDrink.as.
Referenced by TavernBarrel::Initialize(), TownRecord::Save(), and Town::Start().
modifiers
array<Modifiers::Modifier@> modifiers
Definition at line 69 of file TavernDrink.as.
name
string name
Definition at line 61 of file TavernDrink.as.
quality
ActorItemQuality quality
Definition at line 64 of file TavernDrink.as.
Referenced by GetTavernDrink().
unlocked
bool unlocked
Definition at line 66 of file TavernDrink.as.