HoHDocs: scripts/Behaviors/AttachedUnit.as File Reference
AttachedUnit.as File Reference
Classes
class AttachedUnit
Functions
AttachedActorUnit (UnitPtr unit, SValue &params)
void Destroy () override
vec2 GetOffset () override
Variables
AttachedUnit m_actor
int m_sizeX
Function Documentation
AttachedActorUnit()
AttachedActorUnit (UnitPtr unit, SValue & params)
Definition at line 149 of file AttachedUnit.as.
References unit.
     {
         super(unit, params);
     }
Destroy()
void Destroy () override
Definition at line 156 of file AttachedUnit.as.
References m_actor, and m_unit.
Referenced by WorldScript::DestroyUnitChance::ClientExecute(), WorldScript::DestroyUnitCount::ClientExecute(), Skills::Explode::DoExplosion(), WorldScript::DestroyUnits::ServerExecute(), and WorldScript::DestroyScripts::ServerExecute().
     {
         if (m_actor !is null)
         {
             int i = m_actor.m_attachedUnits.find(m_unit);
             if (i != -1)
                 m_actor.m_attachedUnits.removeAt(i);
         }
         m_unit.Destroy();
     }
GetOffset()
vec2 GetOffset () override
Definition at line 168 of file AttachedUnit.as.
References m_actor, AttachedUnit::m_offset, m_offset, m_sizeX, and m_unit.
     {
         if (m_actor is null)
             return m_offset;
         int i = m_actor.m_attachedUnits.find(m_unit);
         int ct = m_actor.m_attachedUnits.length();
         return m_offset + vec2(-((ct - 1) * m_sizeX / 2.0) + (i * m_sizeX), m_actor.IconHeight());
     }
Variable Documentation
m_actor
AttachedUnit m_actor
Referenced by Destroy(), and GetOffset().
m_sizeX
int m_sizeX
Definition at line 147 of file AttachedUnit.as.
Referenced by GetOffset().