HoHDocs: scripts/Behaviors/Effects/GiveGold.as File Reference
GiveGold.as File Reference
Classes
class GiveGold
Functions
GiveGold IEffect GiveGoldImpl (int amount, Player@ player)
GiveGold (UnitPtr unit, SValue &params)
void SetWeaponInformation (uint weapon)
bool Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
bool CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
void NetGiveGoldImpl (int amount, PlayerBase@ player)
Variables
int m_amount
bool m_pickup
Function Documentation
Apply()
bool GiveGoldImpl::Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
Definition at line 46 of file GiveGold.as.
 {
     Stats::Add("gold-found", amount, player.m_record);
     Stats::Add("avg-gold-found", amount, player.m_record);
     auto gm = cast<Campaign>(g_gameMode);
     if (gm !is null)
     {
         ivec3 level = CalcLevel(gm.m_levelCount);
         Stats::Add("avg-gold-found-act-" + (level.x + 1), amount, player.m_record);
     }
CanApply()
bool GiveGoldImpl::CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
Definition at line 59 of file GiveGold.as.
GiveGold()
GiveGoldImpl::GiveGold (UnitPtr unit, SValue & params)
Definition at line 38 of file GiveGold.as.
 {
GiveGoldImpl()
GiveGold IEffect GiveGoldImpl (int amount, Player@ player)
Definition at line 33 of file GiveGold.as.
Referenced by GiveGold::Apply().
 {
     if (player is null)
         return;
     float goldGain = player.m_record.GetModifiers().GoldGainScale(player);
     goldGain += player.m_record.GetModifiers().GoldGainScaleAdd(player);
     amount = roll_round(amount * (goldGain + 0.2f * g_ngp));
     (Network::Message("PlayerGiveGold") << amount).SendToAll();
     NetGiveGoldImpl(amount, player);
 }
NetGiveGoldImpl()
void NetGiveGoldImpl (int amount, PlayerBase@ player)
Definition at line 47 of file GiveGold.as.
References Stats::Add(), CalcLevel(), g_gameMode, and PlayerBase::m_record.
Referenced by PlayerHandler::PlayerGiveGold().
 {
     Stats::Add("gold-found", amount, player.m_record);
     Stats::Add("avg-gold-found", amount, player.m_record);
     auto gm = cast<Campaign>(g_gameMode);
     if (gm !is null)
     {
         ivec3 level = CalcLevel(gm.m_levelCount);
         Stats::Add("avg-gold-found-act-" + (level.x + 1), amount, player.m_record);
     }
     player.m_record.runGold += amount;
 }
SetWeaponInformation()
void GiveGoldImpl::SetWeaponInformation (uint weapon)
Definition at line 44 of file GiveGold.as.
 {
Variable Documentation
m_amount
int m_amount
Definition at line 35 of file GiveGold.as.
m_pickup
bool m_pickup
Definition at line 36 of file GiveGold.as.