HoHDocs: scripts/Behaviors/Effects/IEffect.as File Reference
IEffect.as File Reference
Functions
bool CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity)
void SetWeaponInformation (uint weapon)
bool FilterHuskDamage (Actor@ owner, UnitPtr target, bool husk)
array< IEffect@> LoadEffects (UnitPtr owner, SValue &params, string prefix="")
bool ApplyEffects (array< IEffect@>@ effects, Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
bool ApplyEffects (array< IEffect@>@ effects, Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk, float selfDmg, float teamDmg, float enemyDmg=1.0)
bool CanApplyEffects (array< IEffect@>@ effects, Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity)
bool CanApplyEffects (array< IEffect@>@ effects, Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, float selfDmg, float teamDmg)
void PropagateWeaponInformation (array< IEffect@>@ effects, uint weapon)
Function Documentation
ApplyEffects() [1/2]
bool ApplyEffects (array< IEffect@>@ effects, Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
Definition at line 58 of file IEffect.as.
References Apply().
Referenced by ShootBolt::Apply(), EffectFilter::Apply(), DangerAreaBehavior::ApplyDamage(), JumpStrike::CancelSkill(), CastTrigger(), TossProjectile::Collide(), Projectile::Collide(), BossEyeWisp::Collide(), DelayedBreakable::DamageEffects(), Breakable::DamageEffects(), CannonBall::Destroyed(), Skills::DoActivate(), Explode::DoExplosion(), Skills::DropEffect::DoExplosion(), Skills::Explode::DoExplosion(), MeleeHit::DoHit(), Skills::Whirlwind::DoUpdate(), Skills::MeleeSwing::DoUpdate(), Skills::HandleHitUnit(), SorcererOrbProjectile::HitUnit(), SorcererProjectile::HitUnit(), RangerProjectile::HitUnit(), RayProjectile::HitUnit(), Skills::Charge::HitUnit(), Skills::HitUnit(), Skills::SpewProjectiles::Hold(), Modifiers::TriggerEffect::NetTrigger(), NetUseSkill(), Skills::Juggernaut::OnCollide(), WerebullChargeHitSkill::OnCollide(), JumpStrike::OnCollide(), ActorBuff::OnDeath(), Pickup::Picked(), ShootHitscan(), ShootSpreadHitscan(), Modifiers::TriggerEffect::Trigger(), Skills::RiposteTrigger::TriggerEffects(), SafetyAreaBehavior::Update(), TowerFlowerSpike::Update(), Skills::CelestialOrb::Update(), Projectile::Update(), MeleeSwing::Update(), EnemyMeleeStrike::Update(), WhirlwindSkill::Update(), ActorBuff::Update(), and PlayerBase::Update().
 {
     bool any = false;
     for (uint i = 0; i < effects.length(); i++)
     {
         if (effects[i].Apply(owner, target, pos, dir, intensity, husk))
             any = true;
     }
     return any;
 }
ApplyEffects() [2/2]
bool ApplyEffects (array< IEffect@>@ effects, Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk, float selfDmg, float teamDmg, float enemyDmg = 1.0)
Definition at line 70 of file IEffect.as.
References Apply(), and FilterAction().
 {
     Actor@ a = cast<Actor>(target.GetScriptBehavior());
     float f = FilterAction(a, owner, selfDmg, teamDmg, enemyDmg, 1.0);
     bool any = false;
     for (uint i = 0; i < effects.length(); i++)
     {
         if (f <= 0)
             continue;
         if (effects[i].Apply(owner, target, pos, dir, f * intensity, husk))
             any = true;
     }
     return any;
 }
CanApply()
bool CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
Definition at line 137 of file SpawnUnit.as.
Referenced by CanApplyEffects().
     {
         return true;
     }
CanApplyEffects() [1/2]
bool CanApplyEffects (array< IEffect@>@ effects, Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity)
Definition at line 88 of file IEffect.as.
References CanApply().
Referenced by Pickup::Collide().
 {
     for (uint i = 0; i < effects.length(); i++)
     {
         if (effects[i].CanApply(owner, target, pos, dir, intensity))
             return true;
     }
     return false;
 }
CanApplyEffects() [2/2]
bool CanApplyEffects (array< IEffect@>@ effects, Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, float selfDmg, float teamDmg)
Definition at line 98 of file IEffect.as.
References CanApply(), and FilterAction().
 {
     Actor@ a = cast<Actor>(target.GetScriptBehavior());
     float f = FilterAction(a, owner, selfDmg, teamDmg, 1.0);
     for (uint i = 0; i < effects.length(); i++)
     {
         if (f <= 0)
             continue;
         if (effects[i].CanApply(owner, target, pos, dir, f * intensity))
             return true;
     }
     return false;
 }
FilterHuskDamage()
bool FilterHuskDamage (Actor@ owner, UnitPtr target, bool husk)
Definition at line 8 of file IEffect.as.
References Actor::IsHusk().
Referenced by ApplyBuff::Apply(), Decimate::Apply(), WorldScript::DamageUnits::ApplyDamage(), DangerArea::ApplyDamage(), Damage(), and DoDamageUnits().
 {
     bool tHusk = (owner !is null) ? owner.IsHusk() : !Network::IsServer();
     //if (husk != tHusk)
     //  PrintError("Damage husk and Owner husk does not match!");
     auto player = cast<PlayerBase>(target.GetScriptBehavior());
     if (player !is null)
         return !player.IsHusk(); // && !husk;
     return !tHusk;
 }
LoadEffects()
array<IEffect@> LoadEffects (UnitPtr owner, SValue & params, string prefix = "")
Definition at line 22 of file IEffect.as.
References effect, and IEffect.
Referenced by ActorBuffDef(), BoltShooter::BoltShooter(), BossEyeWisp::BossEyeWisp(), Breakable::Breakable(), CannonBall::CannonBall(), Skills::CelestialOrbs(), Skills::Charge::Charge(), Modifiers::Combo::Combo(), CompositeActorTriggeredSkill(), DangerAreaBehavior::DangerAreaBehavior(), DelayedBreakable::DelayedBreakable(), Skills::DropEffect::DropEffect(), EffectFilter::EffectFilter(), EnemyMeleeStrike::EnemyMeleeStrike(), Explode::Explode(), Skills::Explode::Explode(), Skills::GrappleHook(), Hitscan::Hitscan(), HitscanSpread(), Skills::Juggernaut::Juggernaut(), JumpStrike::JumpStrike(), MeleeHit::MeleeHit(), MeleeSwing::MeleeSwing(), Skills::MeleeSwing::MeleeSwing(), Pickup::Pickup(), Projectile::Projectile(), RayProjectile::RayProjectile(), Skills::Riposte(), SafetyAreaBehavior::SafetyAreaBehavior(), Skills::ShootBeam(), ShootBolt::ShootBolt(), Skills::SpewProjectiles::SpewProjectiles(), TowerFlowerSpike::TowerFlowerSpike(), Modifiers::TriggerEffect::TriggerEffect(), WerebullChargeHitSkill::WerebullChargeHitSkill(), Skills::Whirlwind::Whirlwind(), and WhirlwindSkill::WhirlwindSkill().
 {
     array<IEffect@> effects;
     array<SValue@>@ effectArr = GetParamArray(owner, params, prefix + "effects", false);
     if (effectArr !is null)
     {
         for (uint i = 0; i < effectArr.length(); i++)
         {
             string c = GetParamString(owner, effectArr[i], "class");
             IEffect@ effect = cast<IEffect>(InstantiateClass(c, owner, effectArr[i]));
             if (effect is null)
                 PrintError(c + " is not an IEffect!");
             else
                 effects.insertLast(effect);
         }
     }
     else
     {
         SValue@ dat = GetParamDictionary(owner, params, prefix + "effect", false);
         if (dat !is null)
         {
             string c = GetParamString(owner, dat, "class");
             IEffect@ effect = cast<IEffect>(InstantiateClass(c, owner, dat));
             if (effect is null)
                 PrintError(c + " is not an IEffect!");
             else
                 effects.insertLast(effect);
         }
     }
     return effects;
 }
PropagateWeaponInformation()
void PropagateWeaponInformation (array< IEffect@>@ effects, uint weapon)
Definition at line 115 of file IEffect.as.
References SetWeaponInformation().
 {
     if (effects is null)
         return;
     for (uint i = 0; i < effects.length(); i++)
         effects[i].SetWeaponInformation(weapon);
 }
SetWeaponInformation()
void SetWeaponInformation (uint weapon)
Definition at line 93 of file HitscanSpread.as.
References g_scene, ActionEffectWrapper::m_effect, m_effects, m_missEffects, m_weaponInfo, and PropagateWeaponInformation().
Referenced by PropagateWeaponInformation().
     {
         PropagateWeaponInformation(m_effects, weapon);
         PropagateWeaponInformation(m_missEffects, weapon);
         m_weaponInfo = weapon;
     }