HoHDocs: scripts/Behaviors/Effects/GiveKey.as File Reference
GiveKey.as File Reference
Classes
class GiveKey
Functions
GiveKey IEffect NetGiveKeyImpl (int lock, int amount, PlayerBase@ player)
GiveKey (UnitPtr unit, SValue &params)
void SetWeaponInformation (uint weapon)
bool Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
bool CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
Variables
int m_lock
int m_amount
Function Documentation
Apply()
bool NetGiveKeyImpl::Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
Definition at line 71 of file GiveKey.as.
CanApply()
bool NetGiveKeyImpl::CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
Definition at line 99 of file GiveKey.as.
GiveKey()
NetGiveKeyImpl::GiveKey (UnitPtr unit, SValue & params)
Definition at line 63 of file GiveKey.as.
NetGiveKeyImpl()
GiveKey IEffect NetGiveKeyImpl (int lock, int amount, PlayerBase@ player)
Definition at line 48 of file GiveKey.as.
References Stats::Add(), and PlayerBase::m_record.
Referenced by GiveKey::Apply(), and PlayerHandler::PlayerGiveKey().
 {
     player.m_record.keys[lock] += amount;
     Stats::Add("key-found-" + lock, amount, player.m_record);
 }
SetWeaponInformation()
void NetGiveKeyImpl::SetWeaponInformation (uint weapon)
Definition at line 69 of file GiveKey.as.
Variable Documentation
m_amount
int m_amount
Definition at line 61 of file GiveKey.as.
m_lock
int m_lock
Definition at line 60 of file GiveKey.as.