HoHDocs: scripts/Behaviors/Items/ForgeBlueprint.as File Reference
ForgeBlueprint.as File Reference
Classes
class ForgeBlueprint
Functions
ForgeBlueprint IUsable GiveForgeBlueprintImpl (ActorItem@ item, PlayerBase@ player, bool showFloatingText)
ForgeBlueprint (UnitPtr unit, SValue &params)
void Initialize (ActorItem@ item)
SValue Save ()
void Load (SValue@ data)
void Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther)
void EndCollision (UnitPtr unit, Fixture@ fxSelf, Fixture@ fxOther)
UnitPtr GetUseUnit ()
bool CanUse (PlayerBase@ player)
void Use (PlayerBase@ player)
void NetUse (PlayerHusk@ player)
UsableIcon GetIcon (Player@ player)
int UsePriority (IUsable@ other)
Variables
UnitPtr m_unit
ActorItem m_item
Function Documentation
CanUse()
bool GiveForgeBlueprintImpl::CanUse (PlayerBase@ player)
Definition at line 210 of file ForgeBlueprint.as.
Collide()
void GiveForgeBlueprintImpl::Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther)
Definition at line 185 of file ForgeBlueprint.as.
EndCollision()
void GiveForgeBlueprintImpl::EndCollision (UnitPtr unit, Fixture@ fxSelf, Fixture@ fxOther)
Definition at line 195 of file ForgeBlueprint.as.
ForgeBlueprint()
GiveForgeBlueprintImpl::ForgeBlueprint (UnitPtr unit, SValue & params)
Definition at line 132 of file ForgeBlueprint.as.
                                                      :/item/item_legendary"), pos);
     }
 }
GetIcon()
UsableIcon GiveForgeBlueprintImpl::GetIcon (Player@ player)
Definition at line 225 of file ForgeBlueprint.as.
GetUseUnit()
UnitPtr GiveForgeBlueprintImpl::GetUseUnit ()
Definition at line 205 of file ForgeBlueprint.as.
GiveForgeBlueprintImpl()
ForgeBlueprint IUsable GiveForgeBlueprintImpl (ActorItem@ item, PlayerBase@ player, bool showFloatingText)
Definition at line 108 of file ForgeBlueprint.as.
References Stats::Add(), AddFloatingText(), Common, g_gameMode, PlayerBase::m_record, Pickup, PlaySound3D(), and Uncommon.
Referenced by GiveBlueprintCFunc(), and ForgeBlueprint::Use().
 {
     if (cast<Player>(player) is null)
         return;
     auto gm = cast<Campaign>(g_gameMode);
     if (cast<Player>(player) !is null)
         gm.m_townLocal.m_forgeBlueprints.insertLast(item.idHash);
     Stats::Add("blueprints-found", 1, player.m_record);
     if (showFloatingText)
     {
         AddFloatingText(FloatingTextType::Pickup, Resources::GetString(item.name), player.m_unit.GetPosition() + vec3(0, -5, 0));
         vec3 pos = player.m_unit.GetPosition();
         if (item.quality == ActorItemQuality::Common)
             PlaySound3D(Resources::GetSoundEvent("event:/item/item_common"), pos);
         else if (item.quality == ActorItemQuality::Uncommon)
             PlaySound3D(Resources::GetSoundEvent("event:/item/item_uncommon"), pos);
         else if (item.quality == ActorItemQuality::Rare)
             PlaySound3D(Resources::GetSoundEvent("event:/item/item_rare"), pos);
         else if (item.quality == ActorItemQuality::Epic)
             PlaySound3D(Resources::GetSoundEvent("event:/item/item_epic"), pos);
         else if (item.quality == ActorItemQuality::Legendary)
             PlaySound3D(Resources::GetSoundEvent("event:/item/item_legendary"), pos);
     }
 }
Initialize()
void GiveForgeBlueprintImpl::Initialize (ActorItem@ item)
Definition at line 137 of file ForgeBlueprint.as.
Load()
void GiveForgeBlueprintImpl::Load (SValue@ data)
Definition at line 180 of file ForgeBlueprint.as.
NetUse()
void GiveForgeBlueprintImpl::NetUse (PlayerHusk@ player)
Definition at line 221 of file ForgeBlueprint.as.
Save()
SValue GiveForgeBlueprintImpl::Save ()
Definition at line 170 of file ForgeBlueprint.as.
Use()
void GiveForgeBlueprintImpl::Use (PlayerBase@ player)
Definition at line 215 of file ForgeBlueprint.as.
UsePriority()
int GiveForgeBlueprintImpl::UsePriority (IUsable@ other)
Definition at line 230 of file ForgeBlueprint.as.
Variable Documentation
m_item
ActorItem m_item
Definition at line 130 of file ForgeBlueprint.as.
m_unit
UnitPtr m_unit
Definition at line 128 of file ForgeBlueprint.as.