HoHDocs: scripts/Behaviors/Loot.as File Reference
Loot.as File Reference
Classes
class LootUnit
Namespaces
LootDef
Functions
LootDef (string path, SValue &params)
void Spawn (vec2 pos)
void LootDef::NetSpawnLoot (SValue@ param)
LootDef LoadLootDef (string path)
Variables
class LootUnit m_path
vec2 m_offset
vec2 m_spread
array< array< LootUnit >@> m_loot
array< LootDef@> g_lootDefs
Function Documentation
LoadLootDef()
LootDef LoadLootDef (string path)
Definition at line 150 of file Loot.as.
References g_lootDefs, LootDef(), m_path, and name.
Referenced by Breakable::Breakable(), Chest::Chest(), and CompositeActorBehavior().
 {
     if (path == "")
         return null;
     for (uint i = 0; i < g_lootDefs.length(); i++)
         if (g_lootDefs[i].m_path == path)
             return g_lootDefs[i];
     int i = path.findFirst(":");
     if (i == -1)
         return null;
     string file = path.substr(0, i);
     string name = path.substr(i + 1);
     SValue@ loot = Resources::GetSValue(file);
     if (loot is null)
         return null;
     auto lDef = loot.GetDictionaryEntry(name);
     if (lDef is null)
         return null;
     auto ret = LootDef(path, lDef);
     g_lootDefs.insertLast(@ret);
     return ret;
 }
LootDef()
LootDef (string path, SValue & params)
Definition at line 37 of file Loot.as.
References chance, m_loot, m_offset, m_path, m_spread, and unit.
Referenced by LoadLootDef().
     {
         m_path = path;
         if (params.GetType() != SValueType::Array)
             return;
         auto arr = params.GetArray();
         m_offset = arr[0].GetVector2();
         m_spread = arr[1].GetVector2();
         for (uint i = 2; i < arr.length(); i++)
         {
             auto loot = arr[i].GetArray();
             array<LootUnit>@ lootUnits = array<LootUnit>();
             for (uint j = 0; j < loot.length(); j += 2)
             {
                 int chance = loot[j].GetInteger();
                 auto unit = Resources::GetUnitProducer(loot[j+1].GetString());
                 if (unit !is null)
                     lootUnits.insertLast(LootUnit(chance, unit));
             }
             lootUnits.sortDesc();
             m_loot.insertLast(@lootUnits);
         }
     }
Spawn()
void Spawn (vec2 pos)
Definition at line 69 of file Loot.as.
References g_scene, IsNetsyncedExistance(), m_loot, m_offset, m_spread, and unit.
     {
         if (!Network::IsServer())
             return;
         pos += m_offset;
         array<Tileset@>@ tilesets = g_scene.FetchTilesets(pos);
         for (uint i = 0; i < tilesets.length(); i++)
         {
             SValue@ tsd = tilesets[i].GetData();
             if (tsd is null)
                 continue;
             SValue@ svNoLoot = tsd.GetDictionaryEntry("no-loot");
             if (svNoLoot is null or svNoLoot.GetType() != SValueType::Boolean)
                 continue;
             if (svNoLoot.GetBoolean())
                 return;
         }
         SValueBuilder sval;
         sval.PushArray();
         for (uint i = 0; i < m_loot.length(); i++)
         {
             int n = randi(1000);
             auto lList = m_loot[i];
             for (uint j = 0; j < lList.length(); j++)
             {
                 n -= lList[j].chance;
                 if (n < 0)
                 {
                     auto p = pos;
                     p.x += (randf() * 2 - 1) * m_spread.x;
                     p.y += (randf() * 2 - 1) * m_spread.y;
                     auto u = lList[j].unit.Produce(g_scene, vec3(p.x, p.y, 0));
                     if (!IsNetsyncedExistance(lList[j].unit.GetNetSyncMode()))
                     {
                         sval.PushInteger(lList[j].unit.GetResourceHash());
                         sval.PushVector2(p);
                     }
                     break;
                 }
             }
         }
         auto val = sval.Build();
         (Network::Message("SpawnLoot") << val).SendToAll();
     }
Variable Documentation
g_lootDefs
array<LootDef@> g_lootDefs
Definition at line 148 of file Loot.as.
Referenced by LoadLootDef().
m_loot
array<array<LootUnit>@> m_loot
Definition at line 33 of file Loot.as.
Referenced by LootDef(), and Spawn().
m_offset
vec2 m_offset
Definition at line 30 of file Loot.as.
Referenced by LootDef(), and Spawn().
m_path
class LootUnit m_path
Referenced by LoadLootDef(), and LootDef().
m_spread
vec2 m_spread
Definition at line 31 of file Loot.as.
Referenced by LootDef(), and Spawn().