HoHDocs: scripts/Behaviors/Items/TavernBarrel.as File Reference
TavernBarrel.as File Reference
Classes
class TavernBarrel
Functions
TavernBarrel IUsable GiveTavernBarrelImpl (TavernDrink@ drink, PlayerBase@ player, bool showFloatingText)
TavernBarrel (UnitPtr unit, SValue &params)
void SetQualityScene ()
void Initialize (ActorItemQuality quality)
void Initialize (TavernDrink@ drink)
SValue Save ()
void Load (SValue@ data)
void Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther)
void EndCollision (UnitPtr unit, Fixture@ fxSelf, Fixture@ fxOther)
UnitPtr GetUseUnit ()
bool CanUse (PlayerBase@ player)
void Use (PlayerBase@ player)
void NetUse (PlayerHusk@ player)
UsableIcon GetIcon (Player@ player)
int UsePriority (IUsable@ other)
Variables
UnitPtr m_unit
TavernDrink m_drink
Function Documentation
CanUse()
bool GiveTavernBarrelImpl::CanUse (PlayerBase@ player)
Definition at line 185 of file TavernBarrel.as.
                                                      :/item/item_legendary"), pos);
     }
 }
Collide()
void GiveTavernBarrelImpl::Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther)
Definition at line 160 of file TavernBarrel.as.
     {
         ivec3 level = CalcLevel(gm.m_levelCount);
         Stats::Add("avg-items-picked-act-" + (level.x + 1), 1, player.m_record);
EndCollision()
void GiveTavernBarrelImpl::EndCollision (UnitPtr unit, Fixture@ fxSelf, Fixture@ fxOther)
Definition at line 170 of file TavernBarrel.as.
References AddFloatingText(), Common, TavernDrink::name, Pickup, PlaySound3D(), TavernDrink::quality, and Uncommon.
     {
         AddFloatingText(FloatingTextType::Pickup, Resources::GetString(drink.name), player.m_unit.GetPosition() + vec3(0, -5, 0));
         vec3 pos = player.m_unit.GetPosition();
         if (drink.quality == ActorItemQuality::Common)
             PlaySound3D(Resources::GetSoundEvent("event:/item/item_common"), pos);
GetIcon()
UsableIcon GiveTavernBarrelImpl::GetIcon (Player@ player)
Definition at line 200 of file TavernBarrel.as.
GetUseUnit()
UnitPtr GiveTavernBarrelImpl::GetUseUnit ()
Definition at line 180 of file TavernBarrel.as.
                                                      :/item/item_uncommon"), pos);
         else if (drink.quality == ActorItemQuality::Rare)
             PlaySound3D(Resources::GetSoundEvent("event:/item/item_rare"), pos);
         else if (drink.quality == ActorItemQuality::Epic)
GiveTavernBarrelImpl()
TavernBarrel IUsable GiveTavernBarrelImpl (TavernDrink@ drink, PlayerBase@ player, bool showFloatingText)
Definition at line 130 of file TavernBarrel.as.
Referenced by GiveDrinksCFunc(), TavernBarrel::Use(), and WinCash().
 {
     if (player.IsHusk())
         return;
     if (drink is null)
         return;
     int mul = 1;
     auto gm = cast<Campaign>(g_gameMode);
     if (gm !is null)
         mul += gm.m_townLocal.GetBuilding("tavern").m_level;
     if (drink.localCount < 0)
         drink.localCount = 0;
     if (drink.quality == ActorItemQuality::Common)
         drink.localCount = min(mul * 8, drink.localCount + 6 + (g_ngp/2));
     else if (drink.quality == ActorItemQuality::Uncommon)
         drink.localCount = min(mul * 6, drink.localCount + 5 + (g_ngp/3));
     else if (drink.quality == ActorItemQuality::Rare)
         drink.localCount = min(mul * 4, drink.localCount + 4 + (g_ngp/4));
     else if (drink.quality == ActorItemQuality::Epic)
         drink.localCount = min(mul * 1, drink.localCount + 1);
     else if (drink.quality == ActorItemQuality::Legendary)
         drink.localCount = min(mul * 1, drink.localCount + 1);
     Stats::Add("drinks-found", 1, player.m_record);
     /*
     Stats::Add("items-picked", 1, player.m_record);
     Stats::Add("items-picked-" + GetItemQualityName(item.quality), 1, player.m_record);
     Stats::Add("avg-items-picked", 1, player.m_record);
     auto gm = cast<Campaign>(g_gameMode);
     if (gm !is null)
     {
         ivec3 level = CalcLevel(gm.m_levelCount);
         Stats::Add("avg-items-picked-act-" + (level.x + 1), 1, player.m_record);
     }
     */
     if (showFloatingText)
     {
         AddFloatingText(FloatingTextType::Pickup, Resources::GetString(drink.name), player.m_unit.GetPosition() + vec3(0, -5, 0));
         vec3 pos = player.m_unit.GetPosition();
         if (drink.quality == ActorItemQuality::Common)
             PlaySound3D(Resources::GetSoundEvent("event:/item/item_common"), pos);
         else if (drink.quality == ActorItemQuality::Uncommon)
             PlaySound3D(Resources::GetSoundEvent("event:/item/item_uncommon"), pos);
         else if (drink.quality == ActorItemQuality::Rare)
             PlaySound3D(Resources::GetSoundEvent("event:/item/item_rare"), pos);
         else if (drink.quality == ActorItemQuality::Epic)
             PlaySound3D(Resources::GetSoundEvent("event:/item/item_epic"), pos);
         else if (drink.quality == ActorItemQuality::Legendary)
             PlaySound3D(Resources::GetSoundEvent("event:/item/item_legendary"), pos);
     }
 }
Initialize() [1/2]
void GiveTavernBarrelImpl::Initialize (ActorItemQuality quality)
Definition at line 104 of file TavernBarrel.as.
     {
         return true;
     }
     void Use(PlayerBase@ player)
     {
         m_unit.Destroy();
         GiveTavernBarrelImpl(m_drink, player, true);
     }
     void NetUse(PlayerHusk@ player)
     {
     }
Initialize() [2/2]
void GiveTavernBarrelImpl::Initialize (TavernDrink@ drink)
Definition at line 123 of file TavernBarrel.as.
References Generic.
     {
         return UsableIcon::Generic;
     }
     int UsePriority(IUsable@ other) { return 0; }
 }
 void GiveTavernBarrelImpl(TavernDrink@ drink, PlayerBase@ player, bool showFloatingText)
 {
     if (player.IsHusk())
         return;
Load()
void GiveTavernBarrelImpl::Load (SValue@ data)
Definition at line 145 of file TavernBarrel.as.
     {
NetUse()
void GiveTavernBarrelImpl::NetUse (PlayerHusk@ player)
Definition at line 196 of file TavernBarrel.as.
Save()
SValue GiveTavernBarrelImpl::Save ()
Definition at line 135 of file TavernBarrel.as.
SetQualityScene()
void GiveTavernBarrelImpl::SetQualityScene ()
Definition at line 90 of file TavernBarrel.as.
     {
         Player@ player = cast<Player>(unit.GetScriptBehavior());
         if (player is null)
             return;
         if (fxSelf.IsSensor())
             player.RemoveUsable(this);
     }
     UnitPtr GetUseUnit()
TavernBarrel()
GiveTavernBarrelImpl::TavernBarrel (UnitPtr unit, SValue & params)
Definition at line 85 of file TavernBarrel.as.
     {
Use()
void GiveTavernBarrelImpl::Use (PlayerBase@ player)
Definition at line 190 of file TavernBarrel.as.
References AddFloatingText(), Common, and Pickup.
UsePriority()
int GiveTavernBarrelImpl::UsePriority (IUsable@ other)
Definition at line 205 of file TavernBarrel.as.
Variable Documentation
m_drink
TavernDrink m_drink
Definition at line 83 of file TavernBarrel.as.
m_unit
UnitPtr m_unit
Definition at line 81 of file TavernBarrel.as.