HoHDocs: scripts/DungeonRotation.as File Reference
DungeonRotation.as File Reference
Classes
class DungeonRotationLevel
Functions
DungeonRotation (string fnm)
DungeonRotationLevel GetLevel (int index)
int GetNextActIndex (int index)
Variables
class DungeonRotationLevel m_levels
string m_filename
Function Documentation
DungeonRotation()
DungeonRotation (string fnm)
Definition at line 34 of file DungeonRotation.as.
References GetCurrentLevelFilename(), m_filename, and m_levels.
Referenced by BaseGameMode::LoadDungeonRotation(), OnFunc(), and WorldScript::StartDungeon::ServerExecute().
     {
         m_filename = fnm;
         SValue@ sv = Resources::GetSValue(fnm);
         if (sv is null)
             return;
         string currentLevel = GetCurrentLevelFilename();
         auto arr = sv.GetArray();
         for (uint i = 0; i < arr.length(); i++)
         {
             auto level = DungeonRotationLevel(arr[i]);
             m_levels.insertLast(level);
         }
     }
GetLevel()
DungeonRotationLevel GetLevel (int index)
Definition at line 51 of file DungeonRotation.as.
References m_levels.
Referenced by GetNextActIndex().
     {
         if (index < 0 || index >= int(m_levels.length()))
             return null;
         return m_levels[index];
     }
GetNextActIndex()
int GetNextActIndex (int index)
Gets the index of the level that starts the next Act from m_levels.
Definition at line 61 of file DungeonRotation.as.
References GetLevel(), DungeonRotationLevel::m_act, and m_levels.
     {
         auto level = GetLevel(index);
         if (level is null)
             return -1;
         for (uint i = index; i < m_levels.length(); i++)
         {
             if (m_levels[i].m_act != level.m_act)
                 return i;
         }
         return -1;
     }
Variable Documentation
m_filename
string m_filename
Definition at line 32 of file DungeonRotation.as.
Referenced by DungeonRotation().
m_levels
class DungeonRotationLevel m_levels
Referenced by DungeonRotation(), GetLevel(), and GetNextActIndex().