HoHDocs: scripts/Data.as File Reference
Data.as File Reference
Namespaces
CVars
Functions
string GetPlayerColor (int peer)
Variables
bool CVars::UseTileEffects = true
Function Documentation
GetPlayerColor()
string GetPlayerColor (int peer)
Definition at line 1 of file Data.as.
References Tweak::PlayerColors.
Referenced by BaseGameMode::ColorForPlayer(), WorldScript::LevelStart::DebugDraw(), Menu::SplitscreenPlayer::DisplayName(), PlayerWaypoint::GetColor(), PlayerCorpse::Initialize(), PlayerBase::Initialize(), PlayerCorpse::NetRevive(), PlayerBase::OnDeath(), GameChatWidget::PlayerChat(), GameChatWidget::PlayerSystem(), ScoreDialog::Set(), CoopPlayerWidget::SetPeer(), PingBehavior::Update(), CoopPlayerWidget::Update(), MultiplePlayersTab::UpdateNow(), and Menu::LobbyPlayersMenu::UpdatePlayer().
 {
     if (peer < 0 || peer >= int(Tweak::PlayerColors.length()))
         return "ffffff";
     return Tweak::PlayerColors[peer];
 }