HoHDocs: scripts/GameModes/MainMenu.as File Reference
MainMenu.as File Reference
Classes
class MainMenu
Functions
MainMenu BaseGameMode HexNibble (uint8 n)
MainMenu (Scene@ scene)
void InstantiateMice ()
Menu::ServerlistMenu GetServerlistMenu ()
void ShowMessage (MenuMessage message)
void LoadMenu ()
void Start (uint8 peer, SValue@ save, StartMode sMode) override
void SpawnPlayers () override
bool ShouldDisplayCursor () override
void SetMenuState (MenuState state)
bool MenuBack () override
void UpdateFrame (int ms, GameInput &gameInput, MenuInput &menuInput) override
vec2 GetCameraPos (int idt) override
void PreRenderFrame (int idt) override
void RenderFrame (int idt, SpriteBatch &sb) override
void DrawPlayerColorPicking (SpriteBatch &sb)
void RenderFrameLoading (int idt, SpriteBatch &sb)
void ChatMessage (uint8 peer, string msg)
void LobbyDataUpdate ()
void LobbyMemberDataUpdate (uint8 peer)
void HandleChatMessage (string message)
void LobbyCreated (bool loadingSave)
void JoiningLobby ()
void LobbyInviteAccepted (uint64 id)
void LobbyEntered ()
void LobbyFailedJoin (bool host)
void AddPlayer (uint8 peer) override
void RemovePlayer (uint8 peer, bool kicked) override
void SystemMessage (string name, SValue@ data)
void PlayGame (int numPlrs)
void OnBindingInput (ControllerType type, int key)
void LobbyList (array< uint64 >@ lobbies)
string HexByte (float a)
string HexColor (vec3 color)
void MakeDyeColorsCFunc ()
Variables
array< WorldScript::MenuAnchorPoint@> g_menuAnchors
MenuControlInputWidget m_expectingInput
MenuProvider m_mainMenu
MenuProvider m_ingameMenu
Menu::InGameChat m_ingameChat
Menu::InGameNotifier m_ingameNotifier
GameChatWidget m_wChat
MenuProvider m_gameMenu
MenuState m_state
SoundInstance m_musicInstance
bool m_testLevel
bool m_hostPrivate
string m_hostName
pint m_hostMaxPlayers
pint m_hostMaxLevel
pint m_hostMinLevel
pint m_hostNgp
bool m_hostDownscaling
uint64 m_inviteAcceptID
int m_inviteAcceptMaxLevel
int m_inviteAcceptMinLevel
int m_frameCount
bool m_lostConnection
int m_joinFailed = -1
TownRecord m_town
Menu::JoiningLobbyMenu m_joiningMenu
Function Documentation
AddPlayer()
void HexNibble::AddPlayer (uint8 peer) override
Definition at line 501 of file MainMenu.as.
     {
ChatMessage()
void HexNibble::ChatMessage (uint8 peer, string msg)
Definition at line 368 of file MainMenu.as.
     {
         if (Lobby::IsPlayerLocal(peer))
             return;
DrawPlayerColorPicking()
void HexNibble::DrawPlayerColorPicking (SpriteBatch & sb)
Definition at line 298 of file MainMenu.as.
     {
 %if WIP_BUILD
         auto dbg = GetVarString("dbg_dye");
         if (dbg == "")
             return;
         vec3 a = GetVarVec3("dbg_dye_color1");
         vec3 b = GetVarVec3("dbg_dye_color2");
         vec3 c = GetVarVec3("dbg_dye_color3");
         for (uint i = 0; i < 8; i++)
             sb.SetMultiColor(i, tocolor(xyzw(a, 1)), tocolor(xyzw(b, 1)), tocolor(xyzw(c, 1)));
         auto unit = Resources::GetUnitProducer("players/" + dbg + ".unit");
         sb.DrawUnitScene(vec2(100, 100), vec2(50, 50), unit.GetUnitScene("idle-3"), 0);
GetCameraPos()
vec2 HexNibble::GetCameraPos (int idt) override
Definition at line 253 of file MainMenu.as.
     {
GetServerlistMenu()
Menu::ServerlistMenu HexNibble::GetServerlistMenu ()
Definition at line 90 of file MainMenu.as.
     {
         for (uint i = 0; i < m_gameMenu.m_menus.length(); i++)
         {
             auto menu = cast<Menu::ServerlistMenu>(m_gameMenu.m_menus[i]);
             if (menu !is null)
HandleChatMessage()
void HexNibble::HandleChatMessage (string message)
Definition at line 390 of file MainMenu.as.
Referenced by GameChatWidget::PlayerChat().
     {
         //NOTE: See note above in LobbyDataUpdate.
     }
     void HandleChatMessage(string message)
     {
         /*
         if (message.length() >= 1 && message.length() <= 2)
         {
             int num = parseInt(message);
             if (num < 1 || num > 42)
                 return;
             if (!GetVarBool("ui_chat_dialog"))
                 return;
HexByte()
string HexByte (float a)
Definition at line 580 of file MainMenu.as.
References HexNibble().
Referenced by HexColor().
 {
     uint8 b = uint8(a * 255);
     return HexNibble(b / 16) + HexNibble(b % 16);
 }
HexColor()
string HexColor (vec3 color)
Definition at line 585 of file MainMenu.as.
References HexByte().
Referenced by MakeDyeColorsCFunc().
 {
     return HexByte(color.r) + HexByte(color.g) + HexByte(color.b);
 }
HexNibble()
MainMenu BaseGameMode HexNibble (uint8 n)
Definition at line 558 of file MainMenu.as.
Referenced by HexByte().
 {
     switch (n)
     {
     case 0: return "0";
     case 1: return "1";
     case 2: return "2";
     case 3: return "3";
     case 4: return "4";
     case 5: return "5";
     case 6: return "6";
     case 7: return "7";
     case 8: return "8";
     case 9: return "9";
     case 10: return "a";
     case 11: return "b";
     case 12: return "c";
     case 13: return "d";
     case 14: return "e";
     }
     return "f";
 }
InstantiateMice()
void HexNibble::InstantiateMice ()
Definition at line 79 of file MainMenu.as.
     {
         m_mice.removeRange(0, m_mice.length());
         int numInputs = Platform::GetInputCount();
         for (int i = 0; i < numInputs; i++) {
             GameInput@ gi = Platform::GetGameInput(i);
JoiningLobby()
void HexNibble::JoiningLobby ()
Definition at line 438 of file MainMenu.as.
     {
LoadMenu()
void HexNibble::LoadMenu ()
Definition at line 109 of file MainMenu.as.
     {
         @m_gameMenu = m_mainMenu;
         if (GetVarBool("g_debug_menu"))
             m_mainMenu.Initialize(m_guiBuilder, Menu::TestMenu(m_mainMenu), "gui/test.gui", "gui/main_menu/backdrop.gui");
         else
         {
             if (GetVarBool("g_intro_logos") && !GetVarBool("g_intro_logos_shown"))
                 m_mainMenu.Initialize(m_guiBuilder, Menu::IntroMenu(m_mainMenu), "gui/main_menu/intro.gui", "gui/main_menu/backdrop.gui");
             else
                 m_mainMenu.Initialize(m_guiBuilder, Menu::FrontMenu(m_mainMenu), "gui/main_menu/main.gui", "gui/main_menu/backdrop.gui");
         }
         @m_gameMenu = m_ingameMenu;
         m_ingameMenu.Initialize(m_guiBuilder, Menu::FrontMenu(m_ingameMenu), "gui/ingame_menu/main.gui", "gui/ingame_menu/backdrop.gui");
         @m_ingameChat = Menu::InGameChat();
LobbyCreated()
void HexNibble::LobbyCreated (bool loadingSave)
Definition at line 407 of file MainMenu.as.
     {
         print("LobbyCreated()");
         Lobby::SetPrivate(m_hostPrivate);
         Lobby::SetLobbyData("name", m_hostName);
         Lobby::SetPlayerLimit(m_hostMaxPlayers);
         Lobby::SetLobbyData("max-level", int(m_hostMaxLevel));
         Lobby::SetLobbyData("min-level", int(m_hostMinLevel));
         Lobby::SetLobbyData("downscaling", m_hostDownscaling ? "true" : "false");
         auto enabledMods = HwrSaves::GetEnabledMods();
         Lobby::SetLobbyData("mods-count", enabledMods.length());
         string modsInfo = "";
         for (uint i = 0; i < enabledMods.length(); i++)
             modsInfo += enabledMods[i].Name + "\n";
         if (modsInfo.length() > 512) // GOG lobbies have a 4095 byte limit but let's not go crazy here
             modsInfo = modsInfo.substr(0, 510) + "...";
         Lobby::SetLobbyData("mods", strTrim(modsInfo));
         GlobalCache::Set("start_host_ngp", "" + m_hostNgp);
         GlobalCache::Set("start_host_downscaling", m_hostDownscaling ? "true" : "false");
         if (m_testLevel)
             Lobby::SetLevel("levels/test/test_multi.lvl");
         else
LobbyDataUpdate()
void HexNibble::LobbyDataUpdate ()
Definition at line 377 of file MainMenu.as.
     {
         //NOTE: Steam seems to trigger a data update for the lobby right after it triggers
LobbyEntered()
void HexNibble::LobbyEntered ()
Definition at line 484 of file MainMenu.as.
     {
LobbyFailedJoin()
void HexNibble::LobbyFailedJoin (bool host)
Definition at line 488 of file MainMenu.as.
     {
     }
     void LobbyFailedJoin(bool host)
     {
         m_joinFailed = host ? 1 : 0;
         if (m_joiningMenu !is null)
         {
             m_joiningMenu.Close();
             @m_joiningMenu = null;
LobbyInviteAccepted()
void HexNibble::LobbyInviteAccepted (uint64 id)
Definition at line 444 of file MainMenu.as.
     {
         print("Invite accepted to join \"" + Lobby::GetLobbyData(id, "name") + "\"");
         if (!Platform::Service.IsMultiplayerAvailable())
         {
             print("Can't join because multiplayer is not available");
             //TODO: Give different error if using unpacked mods
             ShowDialog("", Resources::GetString(".menu.notifier.joinfailed.join"), Resources::GetString(".menu.ok"), null);
             return;
         }
         uint modsHash = parseUInt(Lobby::GetLobbyData(id, "mods-hash"));
         if (modsHash != Resources::GetModHash())
         {
             int modsCount = parseInt(Lobby::GetLobbyData(id, "mods-count"));
             string mods = Lobby::GetLobbyData(id, "mods");
             print("Can't join because mod hash mismatch (expected " + modsCount + " mods)");
             ShowDialog("", Resources::GetString(".menu.notifier.joinfailed.mods", {
                 { "num", modsCount },
                 { "mods", mods }
             }), Resources::GetString(".menu.ok"), null);
             return;
         }
         m_inviteAcceptID = id;
         m_inviteAcceptMaxLevel = parseInt(Lobby::GetLobbyData(id, "max-level"));
         m_inviteAcceptMinLevel = parseInt(Lobby::GetLobbyData(id, "min-level"));
         auto menu = cast<Menu::HwrMenu>(m_gameMenu.m_menus[0]);
         if (menu is null)
         {
             PrintError("First menu is not HwrMenu!");
             return;
LobbyList()
void HexNibble::LobbyList (array< uint64 >@ lobbies)
Definition at line 543 of file MainMenu.as.
     {
LobbyMemberDataUpdate()
void HexNibble::LobbyMemberDataUpdate (uint8 peer)
Definition at line 385 of file MainMenu.as.
     {
MainMenu()
HexNibble::MainMenu (Scene@ scene)
Definition at line 37 of file MainMenu.as.
Referenced by MainMenu::SetMenuState(), and MainMenu::UpdateFrame().
     {
         super(scene);
 %if WIP_BUILD
         AddVar("dbg_dye", "");
         AddVar("dbg_dye_color1", vec3(0,0,0));
         AddVar("dbg_dye_color2", vec3(0.5,0.5,0.5));
         AddVar("dbg_dye_color3", vec3(1,1,1));
         AddFunction("dbg_dye_mkcolor", MakeDyeColorsCFunc);
 %endif
         if (!VarExists("g_intro_logos"))
             AddVar("g_intro_logos", true);
         if (!VarExists("g_intro_logos_shown"))
             AddVar("g_intro_logos_shown", false);
         if (!VarExists("g_debug_menu"))
             AddVar("g_debug_menu", false);
         if (!VarExists("g_multi_test"))
             AddVar("g_multi_test", false, null, cvar_flags::Cheat);
         @m_mainMenu = MenuProvider();
         @m_ingameMenu = MenuProvider();
         @m_ingameNotifier = Menu::InGameNotifier();
         m_ingameNotifier.Initialize(m_guiBuilder, "gui/ingame_menu/notifier.gui");
         m_guiBuilder.AddWidgetProducer("menu_control_input", LoadMenuControlInput);
         m_guiBuilder.AddWidgetProducer("game_chat", LoadGameChatWidget);
         m_guiBuilder.AddWidgetProducer("menu_lobby_player", LoadMenuLobbyPlayer);
         m_guiBuilder.AddWidgetProducer("menu_serverlist_item", LoadMenuServerListItemWidget);
         LoadMenu();
         if (Platform::GetSessionCount() == 0)
         {
             auto cb = GetControlBindings();
             GetControlBindings().AssignControls(1);
MakeDyeColorsCFunc()
void MakeDyeColorsCFunc ()
Definition at line 589 of file MainMenu.as.
References HexColor().
Referenced by MainMenu::MainMenu().
 {
     print("<array name=\"shades\"><string>#" + HexColor(GetVarVec3("dbg_dye_color1")) +
           "</string><string>#" + HexColor(GetVarVec3("dbg_dye_color2")) +
           "</string><string>#" + HexColor(GetVarVec3("dbg_dye_color3")) +
           "</string></array>");
 }
MenuBack()
bool HexNibble::MenuBack () override
Definition at line 196 of file MainMenu.as.
     {
         if (m_state == MenuState::Hidden)
             return false;
         if (!BaseGameMode::MenuBack())
         {
             if (m_gameMenu is m_ingameMenu)
                 return m_gameMenu.GoBack();
             else
                 m_gameMenu.GoBack();
OnBindingInput()
void HexNibble::OnBindingInput (ControllerType type, int key)
Definition at line 537 of file MainMenu.as.
     {
PlayGame()
void HexNibble::PlayGame (int numPlrs)
Definition at line 531 of file MainMenu.as.
Referenced by Menu::HwrMenu::FinishContext(), and Menu::SingleplayerMenu::OnFunc().
                                                                         : "false");
     }
     void PlayGame(int numPlrs)
PreRenderFrame()
void HexNibble::PreRenderFrame (int idt) override
Definition at line 260 of file MainMenu.as.
     {
RemovePlayer()
void HexNibble::RemovePlayer (uint8 peer, bool kicked) override
Definition at line 507 of file MainMenu.as.
     {
         if (m_wChat !is null)
         {
             if (kicked)
                 m_wChat.PlayerSystem(peer, ".menu.lobby.chat.iskicked");
RenderFrame()
void HexNibble::RenderFrame (int idt, SpriteBatch & sb) override
Definition at line 264 of file MainMenu.as.
     {
     }
     void RenderFrame(int idt, SpriteBatch& sb) override
     {
         sb.PushTransformation(mat::scale(mat4(), GetUIScale()));
         int w = g_gameMode.m_wndWidth;
         int h = g_gameMode.m_wndHeight;
         if (m_state == MenuState::Hidden)
         {
             m_ingameChat.Draw(sb, idt);
             m_ingameNotifier.Draw(sb, idt);
             if (m_dialogWindow !is null && m_dialogWindow.m_visible)
             {
                 m_dialogWindow.Draw(sb, idt);
                 DrawMouse(idt, sb);
             }
             sb.PopTransformation();
             return;
         }
         m_gameMenu.Render(idt, sb);
         RenderWidgets(null, idt, sb);
         if (m_gameMenu.GetCurrentMenu().ShouldDisplayCursor())
             DrawMouse(idt, sb);
RenderFrameLoading()
void HexNibble::RenderFrameLoading (int idt, SpriteBatch & sb)
Definition at line 319 of file MainMenu.as.
     {
         BitmapFont@ loadFont = Resources::GetBitmapFont("gui/fonts/code2003_20_bold.fnt");
         if (loadFont is null)
             return;
         auto loadText = loadFont.BuildText(Resources::GetString(".menu.loading"), -1, TextAlignment::Center);
         sb.Begin(m_wndWidth, m_wndHeight, m_wndScale);
         sb.DrawSprite(null, vec4(-5, -5, m_wndWidth + 10, m_wndHeight + 10), vec4(), vec4(0, 0, 0, 1));
         sb.DrawString(vec2((m_wndWidth - loadText.GetWidth()) / 2, (m_wndHeight - loadText.GetHeight()) / 2), loadText);
         auto loadStates = Lobby::GetPlayerLoadStates();
         if (loadStates !is null)
         {
             BitmapFont@ plrFont = Resources::GetBitmapFont("gui/fonts/arial11.fnt");
             if (plrFont is null)
                 return;
             for (uint i = 0; i < loadStates.length(); i++)
             {
                 auto name = Lobby::GetPlayerName(loadStates[i].Peer);
                 string text;
                 switch(loadStates[i].Progress)
                 {
                 case 0:
                     text = "\\c000000...\\d " + name;
                     break;
                 case 1:
                     text = ".\\c000000..\\d " + name;
                     break;
                 case 2:
                     text = "..\\c000000.\\d " + name;
                     break;
                 case 3:
                     text = "... " + name;
                     break;
                 }
                 auto plrText = plrFont.BuildText(text, -1, TextAlignment::Left);
                 sb.DrawString(vec2(4, 2 + i * plrText.GetHeight()), plrText);
             }
SetMenuState()
void HexNibble::SetMenuState (MenuState state)
Definition at line 149 of file MainMenu.as.
References Hidden, AGameMode::m_dialogWindow, and MainMenu::m_state.
     {
         return (m_state != MenuState::Hidden) || (m_dialogWindow !is null);
     }
     void SetMenuState(MenuState state)
     {
         m_ingameChat.StopInput();
         g_gameMode.ClearWidgetRoot();
         m_state = state;
         if (m_state == MenuState::InGameMenu)
             @m_gameMenu = m_ingameMenu;
         else if (m_state == MenuState::MainMenu)
         {
             @m_gameMenu = m_mainMenu;
             DiscordPresence::Clear();
             DiscordPresence::SetState("In main menu");
             ServicePresence::Clear();
             ServicePresence::Set("#Status_InMainMenu");
         }
         else if (m_state == MenuState::Hidden)
         {
             if (m_musicInstance !is null && m_musicInstance.IsPlaying())
                 m_musicInstance.Stop();
             return;
         }
         g_gameMode.AddWidgetRoot(m_gameMenu.GetCurrentMenu());
         m_gameMenu.GetCurrentMenu().SetActive();
         if (m_state == MenuState::MainMenu)
         {
             if (m_musicInstance is null)
             {
                 auto music = Resources::GetSoundEvent("event:/music/menu");
                 if (music !is null)
                 {
                     @m_musicInstance = music.PlayTracked();
                     m_musicInstance.SetLooped(true);
                     m_musicInstance.SetPaused(false);
                 }
             }
ShouldDisplayCursor()
bool HexNibble::ShouldDisplayCursor () override
Definition at line 144 of file MainMenu.as.
     {
     }
ShowMessage()
void HexNibble::ShowMessage (MenuMessage message)
Definition at line 101 of file MainMenu.as.
     {
         if (message == MenuMessage::Saved)
SpawnPlayers()
void HexNibble::SpawnPlayers () override
Definition at line 140 of file MainMenu.as.
     {
Start()
void HexNibble::Start (uint8 peer, SValue@ save, StartMode sMode) override
Definition at line 132 of file MainMenu.as.
     {
         @m_town = TownRecord();
SystemMessage()
void HexNibble::SystemMessage (string name, SValue@ data)
Definition at line 518 of file MainMenu.as.
     {
         if (name == "AddChat")
         {
             if (m_wChat !is null)
                 m_wChat.AddChat(data.GetString());
         }
         else if (name == "SetNGP" && Network::IsServer())
UpdateFrame()
void HexNibble::UpdateFrame (int ms, GameInput & gameInput, MenuInput & menuInput) override
Definition at line 212 of file MainMenu.as.
     {
         BaseGameMode::UpdateFrame(ms, gameInput, menuInput);
         Platform::Service.InMenus(true);
         if (m_state == MenuState::Hidden)
         {
             m_ingameNotifier.Update(ms);
             m_ingameChat.Update(ms, menuInput);
             return;
         }
 %PROFILE_START GameMenu Update
         m_gameMenu.Update(ms, gameInput, menuInput);
 %PROFILE_STOP
         if (m_lostConnection)
         {
             m_lostConnection = false;
             ShowDialog("connectionlost", Resources::GetString(".menu.notifier.lostconnection"), Resources::GetString(".menu.ok"), m_gameMenu.GetCurrentMenu());
         }
         if (m_joinFailed != -1)
         {
             string prompt = "join";
             if (m_joinFailed == 1)
                 prompt = "host";
             ShowDialog("joinfailed", Resources::GetString(".menu.notifier.joinfailed." + prompt), Resources::GetString(".menu.ok"), m_gameMenu.GetCurrentMenu());
             m_joinFailed = -1;
         }
         m_frameCount++;
         if (m_state == MenuState::MainMenu)
         {
Variable Documentation
g_menuAnchors
array<WorldScript::MenuAnchorPoint@> g_menuAnchors
Definition at line 1 of file MainMenu.as.
Referenced by Menu::SingleplayerMenu::GetAnchorPoint(), WorldScript::MenuAnchorPoint::Initialize(), and Menu::GraphicsMenu::Update().
m_expectingInput
MenuControlInputWidget m_expectingInput
Definition at line 2 of file MainMenu.as.
m_frameCount
int m_frameCount
Definition at line 29 of file MainMenu.as.
m_gameMenu
MenuProvider m_gameMenu
Definition at line 11 of file MainMenu.as.
m_hostDownscaling
bool m_hostDownscaling
Definition at line 23 of file MainMenu.as.
Referenced by Menu::HostMenu::OnFunc().
m_hostMaxLevel
pint m_hostMaxLevel
Definition at line 20 of file MainMenu.as.
m_hostMaxPlayers
pint m_hostMaxPlayers
Definition at line 19 of file MainMenu.as.
m_hostMinLevel
pint m_hostMinLevel
Definition at line 21 of file MainMenu.as.
m_hostName
string m_hostName
Definition at line 18 of file MainMenu.as.
m_hostNgp
pint m_hostNgp
Definition at line 22 of file MainMenu.as.
m_hostPrivate
bool m_hostPrivate
Definition at line 17 of file MainMenu.as.
Referenced by Menu::HostMenu::Initialize(), and Menu::HostMenu::OnFunc().
m_ingameChat
Menu::InGameChat m_ingameChat
Definition at line 6 of file MainMenu.as.
m_ingameMenu
MenuProvider m_ingameMenu
Definition at line 5 of file MainMenu.as.
m_ingameNotifier
Menu::InGameNotifier m_ingameNotifier
Definition at line 7 of file MainMenu.as.
m_inviteAcceptID
uint64 m_inviteAcceptID
Definition at line 25 of file MainMenu.as.
m_inviteAcceptMaxLevel
int m_inviteAcceptMaxLevel
Definition at line 26 of file MainMenu.as.
m_inviteAcceptMinLevel
int m_inviteAcceptMinLevel
Definition at line 27 of file MainMenu.as.
m_joinFailed
int m_joinFailed = -1
Definition at line 31 of file MainMenu.as.
m_joiningMenu
Menu::JoiningLobbyMenu m_joiningMenu
Definition at line 35 of file MainMenu.as.
m_lostConnection
bool m_lostConnection
Definition at line 30 of file MainMenu.as.
m_mainMenu
MenuProvider m_mainMenu
Definition at line 4 of file MainMenu.as.
m_musicInstance
SoundInstance m_musicInstance
Definition at line 14 of file MainMenu.as.
m_state
MenuState m_state
Definition at line 12 of file MainMenu.as.
Referenced by ScalableSpriteButtonWidget::IsEnabled().
m_testLevel
bool m_testLevel
Definition at line 16 of file MainMenu.as.
Referenced by Menu::FrontMenu::OnFunc().
m_town
TownRecord m_town
Definition at line 33 of file MainMenu.as.
m_wChat
GameChatWidget m_wChat
Definition at line 9 of file MainMenu.as.