HoHDocs: scripts/GUI/GroupWidget.as File Reference
GroupWidget.as File Reference
Classes
class GroupWidget
Functions
GroupWidget Widget LoadGroupWidget (WidgetLoadingContext &ctx)
GroupWidget ()
void Load (WidgetLoadingContext &ctx) override
Widget Clone () override
void DoLayout (vec2 origin, vec2 parentSz) override
Variables
bool m_dynamicWidth
bool m_dynamicHeight
bool m_innerSz
bool m_doubleLayout
Function Documentation
Clone()
Widget LoadGroupWidget::Clone () override
Definition at line 398 of file GroupWidget.as.
DoLayout()
void LoadGroupWidget::DoLayout (vec2 origin, vec2 parentSz) override
Definition at line 405 of file GroupWidget.as.
GroupWidget()
LoadGroupWidget::GroupWidget ()
Definition at line 365 of file GroupWidget.as.
Referenced by LoadGroupWidget().
Load()
void LoadGroupWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 370 of file GroupWidget.as.
LoadGroupWidget()
GroupWidget Widget LoadGroupWidget (WidgetLoadingContext & ctx)
Definition at line 96 of file GroupWidget.as.
References GroupWidget(), and GroupWidget::Load().
Referenced by BaseGameMode::BaseGameMode().
 {
     GroupWidget@ w = GroupWidget();
     w.Load(ctx);
     return w;
 }
Variable Documentation
m_doubleLayout
bool m_doubleLayout
Definition at line 363 of file GroupWidget.as.
m_dynamicHeight
bool m_dynamicHeight
Definition at line 360 of file GroupWidget.as.
m_dynamicWidth
bool m_dynamicWidth
Definition at line 359 of file GroupWidget.as.
m_innerSz
bool m_innerSz
Definition at line 361 of file GroupWidget.as.