HoHDocs: scripts/GUI/DotbarWidget.as File Reference
DotbarWidget.as File Reference
Classes
class DotbarWidget
Functions
DotbarWidget Widget LoadDotbarWidget (WidgetLoadingContext &ctx)
DotbarWidget ()
void Load (WidgetLoadingContext &ctx) override
void DoDraw (SpriteBatch &sb, vec2 pos) override
Variables
int m_max
int m_value
vec4 m_color
vec4 m_colorSet
vec4 m_colorUnset
int m_borderOffset
Function Documentation
DoDraw()
void LoadDotbarWidget::DoDraw (SpriteBatch & sb, vec2 pos) override
Definition at line 201 of file DotbarWidget.as.
DotbarWidget()
LoadDotbarWidget::DotbarWidget ()
Definition at line 183 of file DotbarWidget.as.
Referenced by LoadDotbarWidget().
Load()
void LoadDotbarWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 188 of file DotbarWidget.as.
LoadDotbarWidget()
DotbarWidget Widget LoadDotbarWidget (WidgetLoadingContext & ctx)
Definition at line 59 of file DotbarWidget.as.
References DotbarWidget(), and DotbarWidget::Load().
Referenced by BaseGameMode::BaseGameMode().
 {
     DotbarWidget@ w = DotbarWidget();
     w.Load(ctx);
     return w;
 }
Variable Documentation
m_borderOffset
int m_borderOffset
Definition at line 181 of file DotbarWidget.as.
m_color
vec4 m_color
Definition at line 177 of file DotbarWidget.as.
m_colorSet
vec4 m_colorSet
Definition at line 178 of file DotbarWidget.as.
m_colorUnset
vec4 m_colorUnset
Definition at line 179 of file DotbarWidget.as.
m_max
int m_max
Definition at line 174 of file DotbarWidget.as.
m_value
int m_value
Definition at line 175 of file DotbarWidget.as.