HoHDocs: scripts/Generators/ChambersGenerator.as File Reference
ChambersGenerator.as File Reference
Classes
class ChambersRoom
Functions
bool close (int a, int b)
int getx (int ax1, int ax2, int bx1, int bx2)
ivec4 FindDoorway (ChambersRoom@ a, ChambersRoom@ b)
bool IsValidPos (array< ivec4 > &doorways, int x, int y, int w, int h)
ivec2 GetRandomPos (int roomx, int roomy, int roomw, int roomh, array< ivec4 > &doorways, int w, int h)
void PlacePrefab (array< ivec4 > &doorways, ivec2 pos, int w, int h, PointOfInterestType prefab)
void FillRoom (int x, int y, int w, int h, array< ivec4 > &doorways, PointOfInterestType type)
void MakeRoom (array< ChambersRoom@> &rooms, uint i)
void SplitRoom (array< ivec4 > &rooms, uint idx)
void Generate (Scene@ scene) override
bool FillDeadEnd (PatternMatcher@ matcher, DungeonBrush@ brush, array< array< Pattern >>@ pattern, ivec2 offset, int w, int h)
void FillDeadEnds (PatternMatcher@ matcher, DungeonBrush@ brush, int numFill)
Variables
class ChambersRoom default
int Height
int Splits
bool Prefabs
int Padding
ivec2 m_topRoom
ivec2 m_botRoom
Function Documentation
close()
bool close (int a, int b)
Definition at line 46 of file ChambersGenerator.as.
References abs().
Referenced by FindDoorway(), and MinesGenerator::Generate().
     {
         return abs(a - b) < 3;
     }
FillDeadEnd()
bool FillDeadEnd (PatternMatcher@ matcher, DungeonBrush@ brush, array< array< Pattern >>@ pattern, ivec2 offset, int w, int h)
Definition at line 478 of file ChambersGenerator.as.
References Wall.
Referenced by FillDeadEnds().
     {
         auto ends = matcher.FindAllPatterns(brush, pattern);
         for (uint i = 0; i < ends.length(); i++)
         {
             int xs = ends[i].x + offset.x;
             int ys = ends[i].y + offset.y;
             for (int x = 0; x < w; x++)
                 for (int y = 0; y < h; y++)
                     brush.SetCell(xs + x, ys + y, Cell::Wall);
         }
         return ends.length() > 0;
     }
FillDeadEnds()
void FillDeadEnds (PatternMatcher@ matcher, DungeonBrush@ brush, int numFill)
Definition at line 495 of file ChambersGenerator.as.
References FillDeadEnd(), Floor, and Wall.
     {
         auto w = Pattern::Wall;
         auto f = Pattern::Floor;
         array<array<Pattern>> ptrnA = {
             {w, w},
             {w, f},
             {w, f},
             {w, f},
             {w, f},
             {w, w}
         };
         array<array<Pattern>> ptrnB = {
             {w, w},
             {f, w},
             {f, w},
             {f, w},
             {f, w},
             {w, w}
         };
         for (int i = 0; i < numFill; i++)
         {
             bool filled = false;
             filled = FillDeadEnd(matcher, brush, ptrnA, ivec2(1, 1), 1, 4) || filled;
             filled = FillDeadEnd(matcher, brush, ptrnB, ivec2(0, 1), 1, 4) || filled;
             if (!filled)
                 break;
         }
     }
FillRoom()
void FillRoom (int x, int y, int w, int h, array< ivec4 > & doorways, PointOfInterestType type)
Definition at line 147 of file ChambersGenerator.as.
References GetRandomPos(), PlacePrefab(), Prefab13x13Block, Prefab21x21Block, Prefab3x3Block, Prefab9x9Block, and Prefabs.
Referenced by MakeRoom().
     {
         if (!Prefabs)
             return;
         for (int i = 0; i < 5; i++)
         {
             ivec2 pfbPos;
             pfbPos = GetRandomPos(x, y, w, h, doorways, 25, 27);
             if (pfbPos.x >= 0)
             {
                 PlacePrefab(doorways, pfbPos + ivec2(2, 3), 21, 21, Prefab21x21Block);
                 continue;
             }
             pfbPos = GetRandomPos(x, y, w, h, doorways, 17, 22);
             if (pfbPos.x >= 0)
             {
                 PlacePrefab(doorways, pfbPos + ivec2(2, 3), 13, 13, Prefab13x13Block);
                 continue;
             }
             pfbPos = GetRandomPos(x, y, w, h, doorways, 13, 15);
             if (pfbPos.x >= 0)
             {
                 PlacePrefab(doorways, pfbPos + ivec2(2, 3), 9, 9, Prefab9x9Block);
                 continue;
             }
             pfbPos = GetRandomPos(x, y, w, h, doorways, 7, 9);
             if (pfbPos.x >= 0)
             {
                 PlacePrefab(doorways, pfbPos + ivec2(2, 3), 3, 3, Prefab3x3Block);
                 continue;
             }
         }
     }
FindDoorway()
ivec4 FindDoorway (ChambersRoom@ a, ChambersRoom@ b)
Definition at line 61 of file ChambersGenerator.as.
References close(), getx(), ChambersRoom::w, ChambersRoom::x, ChambersRoom::y, and ChambersRoom::z.
Referenced by MakeRoom().
     {
         int w = 1;
         if (close(a.y, b.y + b.w))
         {
             int x = getx(a.x, a.x+a.z, b.x, b.x+b.z);
             if (x < 0)
                 return ivec4(-1);
             return ivec4(x - w, a.y - w, x + w, a.y + w);
         }
         else if (close(b.y, a.y + a.w))
         {
             int x = getx(a.x, a.x+a.z, b.x, b.x+b.z);
             if (x < 0)
                 return ivec4(-1);
             return ivec4(x - w, b.y - w, x + w, b.y + w);
         }
         else if (close(a.x, b.x + b.z))
         {
             int y = getx(a.y, a.y+a.w, b.y, b.y+b.w);
             if (y < 0)
                 return ivec4(-1);
             return ivec4(a.x - w, y - w, a.x + w, y + w);
         }
         else if (close(b.x, a.x + a.z))
         {
             int y = getx(a.y, a.y+a.w, b.y, b.y+b.w);
             if (y < 0)
                 return ivec4(-1);
             return ivec4(b.x - w, y - w, b.x + w, y + w);
         }
         return ivec4(-1);
     }
Generate()
void Generate (Scene@ scene) override
Definition at line 289 of file ChambersGenerator.as.
References Entry, Exit, Floor, g_prefabsToSpawn, g_spawnPos, GetPrefab(), Height, m_botRoom, m_brush, m_numPlrs, m_startPos, m_topRoom, MakeBrush(), MakeRoom(), Padding, PlaceCrateBreakables(), PlaceEnemies(), PlacePrefab(), PlotLine(), PlotPoint(), PlotRect(), Prefab10x10North2, Prefab10x10South2, Prefab13x13East, Prefab13x13North, Prefab13x13West, Prefab14x14North2, Prefab14x14South2, Prefab5x5BlockNorth, Prefab5x5BlockSouth, Prefab5x5North, Prefab5x6BlockEast, Prefab5x6BlockWest, Prefab6x12Path, Prefab6x4Path, Prefab6x8Path, Prefab8x4Path, PrefabPlacement(), Prefabs, PrefabToSpawn(), Reserved, SplitRoom(), Splits, and Wall.
     {
         while (true)
         {
             print("Generating level...");
             int w = Width / 16;
             int h = Height / 16;
             MakeBrush();
             m_brush.Initialize(w, h, vec2(-Width / 2, -Height / 2));
             int spacing = 300 / 16;
             int padding = Padding;
             array<ivec4> rooms = { ivec4(padding, padding + spacing, w - padding * 2, h - padding * 2 - spacing * 2) };
             m_topRoom = ivec2(0, 100000);
             m_botRoom = ivec2(0, -100000);
             SplitRoom(rooms, 0);
             SplitRoom(rooms, 1);
             SplitRoom(rooms, 0);
             for (int i = 0; i < Splits - 3; i++)
                 SplitRoom(rooms, randi(rooms.length()));
             for (uint i = 0; i < rooms.length(); i++)
             {
                 auto room = rooms[i];
                 if (room.x == padding)
                 {
                     int d = randi(padding/3 -1);
                     room.x -= d;
                     room.z += d;
                 }
                 if (room.y == padding)
                 {
                     int d = randi(padding/3 -1);
                     room.y -= d;
                     room.w += d;
                 }
                 if (room.x + room.z == w - padding)
                     room.z += randi(padding/3 -1);
                 if (room.y + room.w == h - padding)
                     room.w += randi(padding/3 -1);
                 rooms[i] = room;
             }
             rooms.removeAt(rooms.length() -1);
             rooms.removeAt(0);
             array<ChambersRoom@> roomCs;
             for (uint i = 0; i < rooms.length(); i++)
                 roomCs.insertLast(ChambersRoom(rooms[i]));
             for (int i = roomCs.length() - 1; i >= 0; i--)
                 MakeRoom(roomCs, i);
             bool failed = false;
             roomCs[0].FloodFill();
             for (uint i = 0; i < roomCs.length(); i++)
             {
                 if (!roomCs[i].isReachable)
                 {
                     failed = true;
                     break;
                 }
             }
             if (failed)
                 continue;
             int corridorLen = 34;
             int sideCorridorLen = 40;
             PlotLine(ivec2(m_topRoom.x + 3, m_topRoom.y), ivec2(m_topRoom.x + 3, m_topRoom.y - corridorLen), 10, Cell::Floor);
             PlotLine(ivec2(m_botRoom.x + 3, m_botRoom.y), ivec2(m_botRoom.x + 3, m_botRoom.y + corridorLen), 10, Cell::Floor);
             ivec2 topMid(m_topRoom.x, m_topRoom.y - corridorLen / 2);
             ivec2 botMid(m_botRoom.x, m_botRoom.y + corridorLen / 2);
             int sideX = topMid.x + sideCorridorLen * (topMid.x < (w / 2) ? 1 : -1);
             PlotLine(topMid, ivec2(sideX, topMid.y), 6, Cell::Floor);
             PlotLine(ivec2(sideX, m_topRoom.y - corridorLen), ivec2(sideX, topMid.y + 10), 6, Cell::Floor);
             sideX = botMid.x + sideCorridorLen * (botMid.x < (w / 2) ? 1 : -1);
             PlotLine(botMid, ivec2(sideX, botMid.y), 6, Cell::Floor);
             PlotLine(ivec2(sideX, m_botRoom.y + corridorLen), ivec2(sideX, botMid.y - 13), 6, Cell::Floor);
             //PlotRect(ivec2(m_topRoom.x - 12, m_topRoom.y - corridorLen - 24), ivec2(m_topRoom.x + 12, m_topRoom.y - corridorLen), Cell::Floor);
             PlotRect(ivec2(m_botRoom.x - 32, m_botRoom.y + corridorLen), ivec2(m_botRoom.x + 4, m_botRoom.y + corridorLen + 13), Cell::Reserved, true);
             //PlotPoint(ivec2(sideX, m_botRoom.y + corridorLen), ivec2(sideX, botMid.y - 13), 6, Cell::Wall);
             PlotPoint(m_botRoom.x + 4, m_botRoom.y + corridorLen, Cell::Wall);
             PlotPoint(m_botRoom.x - 3, m_botRoom.y + corridorLen, Cell::Wall);
 //          PlotPoint(x, y, cellType);
 //          m_brush.SetConsumed(x, y);
             ivec2 startPos = ivec2(m_botRoom.x - 32, m_botRoom.y + corridorLen -1);
             ivec2 exitPos = ivec2(m_topRoom.x, m_topRoom.y - corridorLen - 10 - 3);
             array<ivec4> doorways;
             PlacePrefab(doorways, startPos, 7, 7, PointOfInterestType::Entry);
             PlacePrefab(doorways, exitPos - ivec2(11, 11), 24, 24, PointOfInterestType::Exit);
             for (int y = 0; y < 26; y++)
                 for (int x = 0; x < 26; x++)
                     m_brush.SetConsumed(exitPos.x - 12 + x, exitPos.y - 12 + y);
             startPos += ivec2(2, 1);
             m_startPos = vec2(float(startPos.x), float(startPos.y));
             g_spawnPos = vec2(16 * startPos.x + m_brush.m_posOffset.x + 16, 16 * startPos.y + m_brush.m_posOffset.y + 24);
             //MakeCliffs(MaxCliffNum, 400);
             if (Prefabs)
             {
                 PatternMatcher ptrnMtch;
                 PrefabPlacement placer(m_brush, ptrnMtch);
                 placer.PlacePrefab(PointOfInterestType::Prefab6x12Path, 2);
                 placer.PlacePrefab(PointOfInterestType::Prefab6x8Path, 2);
                 placer.PlacePrefab(PointOfInterestType::Prefab8x4Path, 2);
                 placer.PlacePrefab(PointOfInterestType::Prefab6x4Path, 2);
                 placer.PlacePrefab(PointOfInterestType::Prefab14x14North2, 3);
                 placer.PlacePrefab(PointOfInterestType::Prefab14x14South2, 3);
                 placer.PlacePrefab(PointOfInterestType::Prefab13x13East, 3);
                 placer.PlacePrefab(PointOfInterestType::Prefab13x13West, 3);
                 placer.PlacePrefab(PointOfInterestType::Prefab10x10North2, 5);
                 placer.PlacePrefab(PointOfInterestType::Prefab10x10South2, 5);
                 placer.PlacePrefab(PointOfInterestType::Prefab5x5North, 5);
                 placer.PlacePrefab(PointOfInterestType::Prefab13x13North, 5);
                 // 10x10 blocks now
                 placer.PlacePrefab(PointOfInterestType::Prefab5x5BlockNorth, 5);
                 placer.PlacePrefab(PointOfInterestType::Prefab5x5BlockSouth, 5);
                 placer.PlacePrefab(PointOfInterestType::Prefab5x6BlockEast, 5);
                 placer.PlacePrefab(PointOfInterestType::Prefab5x6BlockWest, 5);
             }
             PlaceCrateBreakables(w, h);
             m_brush.GenerateNothingness();
             PlaceEnemies(scene, ivec2(int(m_startPos.x), int(m_startPos.y)));
             break;
         }
         m_brush.Build(scene);
         int numBatSpawners = 3 + m_numPlrs;
         int dist = int(sqrt(Width * Width + Height * Height) / 2.0f * 0.9f);
         auto batSpawner = Resources::GetPrefab("prefabs/chambers/bat_spawner.pfb");
         for (int i = 0; i < numBatSpawners; i++)
         {
             float ang = (i + 0.5f) * (PI * 2 / numBatSpawners);
             vec3 pos(m_brush.m_posOffset.x + Width / 2 + cos(ang) * dist, m_brush.m_posOffset.y + Height / 2 + sin(ang) * dist, 0);
             g_prefabsToSpawn.insertLast(PrefabToSpawn(batSpawner, pos));
             //batSpawner.Fabricate(scene, pos);
         }
     }
GetRandomPos()
ivec2 GetRandomPos (int roomx, int roomy, int roomw, int roomh, array< ivec4 > & doorways, int w, int h)
Definition at line 109 of file ChambersGenerator.as.
References IsValidPos().
Referenced by FillRoom().
     {
         if (roomw <= w || roomh <= h)
             return ivec2(-1, -1);
         for (int i = 0; i < 10; i++)
         {
             int x = randi(roomw - 2 - w) + roomx + 1;
             int y = randi(roomh - 2 - h) + roomy + 1;
             if (IsValidPos(doorways, x, y, w, h))
                 return ivec2(x, y);
         }
         return ivec2(-1, -1);
     }
getx()
int getx (int ax1, int ax2, int bx1, int bx2)
Definition at line 51 of file ChambersGenerator.as.
References max, and min.
Referenced by FindDoorway().
     {
         int x = (max(ax1, bx1) + min(ax2, bx2)) / 2;
         if (x <= ax1 || x <= bx1 || x >= ax2 || x >= bx2)
             return -1;
         return x;
     }
IsValidPos()
bool IsValidPos (array< ivec4 > & doorways, int x, int y, int w, int h)
Definition at line 97 of file ChambersGenerator.as.
Referenced by GetRandomPos().
     {
         for (uint i = 0; i < doorways.length(); i++)
         {
             auto dw = doorways[i];
             if (!(dw.x > (x + w) || dw.z < x || dw.y > (y + h) || dw.w < y))
                 return false;
         }
         return true;
     }
MakeRoom()
void MakeRoom (array< ChambersRoom@> & rooms, uint i)
Definition at line 189 of file ChambersGenerator.as.
References FillRoom(), FindDoorway(), Floor, m_botRoom, m_topRoom, None, PlotRect(), and type.
Referenced by Generate().
     {
         auto room = rooms[i];
         PlotRect(ivec2(room.x +1, room.y +1), ivec2(room.x + room.z -1, room.y + room.w -1), Cell::Floor);
         array<ivec4> doorways;
         bool openAll = false;
         auto type = PointOfInterestType::None;
         if (i > 0)
         {
             auto prev = rooms[i -1];
             auto doorway = FindDoorway(room, prev);
             if (doorway.x >= 0)
             {
                 room.connections.insertLast(prev);
                 doorways.insertLast(doorway);
                 PlotRect(ivec2(doorway.x, doorway.y), ivec2(doorway.z, doorway.w), Cell::Floor);
             }
             else
                 openAll = true;
         }
         //else
         //  type = PointOfInterestType::Entry;
         if (i < rooms.length() - 1)
         {
             auto next = rooms[i +1];
             auto doorway = FindDoorway(room, next);
             if (doorway.x >= 0)
             {
                 room.connections.insertLast(next);
                 doorways.insertLast(doorway);
                 PlotRect(ivec2(doorway.x, doorway.y), ivec2(doorway.z, doorway.w), Cell::Floor);
             }
             else
                 openAll = true;
         }
         //else
         //  type = PointOfInterestType::Exit;
         if (openAll)
         {
             for (uint j = 0; j < rooms.length(); j++)
             {
                 if (i == j)
                     continue;
                 auto doorway = FindDoorway(room, rooms[j]);
                 if (doorway.x >= 0)
                 {
                     room.connections.insertLast(rooms[j]);
                     doorways.insertLast(doorway);
                     PlotRect(ivec2(doorway.x, doorway.y), ivec2(doorway.z, doorway.w), Cell::Floor);
                 }
             }
         }
         if (room.y < m_topRoom.y)
             m_topRoom = ivec2(room.x + room.z / 2, room.y);
         if ((room.y + room.w) > m_botRoom.y)
             m_botRoom = ivec2(room.x + room.z / 2, room.y + room.w);
         FillRoom(room.x, room.y, room.z, room.w, doorways, type);
     }
PlacePrefab()
void PlacePrefab (array< ivec4 > & doorways, ivec2 pos, int w, int h, PointOfInterestType prefab)
Definition at line 126 of file ChambersGenerator.as.
References m_brush, None, and Reserved.
Referenced by FillRoom(), and Generate().
     {
         if (pos.x <= 0)
             return;
         doorways.insertLast(ivec4(pos.x -2, pos.y -2, pos.x + w +4, pos.y + h +4));
         for (int y = 0; y < h; y++)
         for (int x = 0; x < w; x++)
         {
             m_brush.SetCell(pos.x + x, pos.y + y, Cell::Reserved);
             m_brush.SetConsumed(pos.x + x, pos.y + y);
         }
         if (prefab == PointOfInterestType::None)
             return;
         m_brush.AddPointOfInterest(prefab, pos.x, pos.y);
     }
SplitRoom()
void SplitRoom (array< ivec4 > & rooms, uint idx)
Definition at line 258 of file ChambersGenerator.as.
Referenced by Generate().
     {
         if (idx >= rooms.length())
             return;
         auto room = rooms[idx];
         ivec4 a, b;
         if ((room.z > room.w) || (randi(100) <= 22))
         {
             if (room.z <= 9 * 2)
                 return;
             a = ivec4(room.x, room.y, room.z / 2 - randi(1) - 1, room.w);
             b = ivec4(room.x + room.z / 2, room.y, (room.z +1) / 2, room.w);
         }
         else
         {
             if (room.w <= 9 * 2)
                 return;
             a = ivec4(room.x, room.y, room.z, room.w / 2 - randi(1) - 1);
             b = ivec4(room.x, room.y + room.w / 2, room.z, (room.w +1) / 2);
         }
         rooms.removeAt(idx);
         rooms.insertAt(idx, b);
         rooms.insertAt(idx, a);
     }
Variable Documentation
default
class ChambersRoom default
Initial value:
=3000]
    int Width
Height
int Height
Definition at line 34 of file ChambersGenerator.as.
Referenced by Generate().
m_botRoom
ivec2 m_botRoom
Definition at line 187 of file ChambersGenerator.as.
Referenced by Generate(), and MakeRoom().
m_topRoom
ivec2 m_topRoom
Definition at line 186 of file ChambersGenerator.as.
Referenced by Generate(), and MakeRoom().
Padding
int Padding
Definition at line 43 of file ChambersGenerator.as.
Referenced by Generate().
Prefabs
bool Prefabs
Definition at line 40 of file ChambersGenerator.as.
Referenced by FillRoom(), and Generate().
Splits
int Splits
Definition at line 37 of file ChambersGenerator.as.
Referenced by Generate().