HoHDocs: scripts/GUI/FlagWidget.as File Reference
FlagWidget.as File Reference
Classes
class FlagWidget
Functions
FlagWidget Widget LoadFlagWidget (WidgetLoadingContext &ctx)
FlagWidget ()
void Load (WidgetLoadingContext &ctx) override
void Update (int dt) override
void AnimateSet (string key, bool b) override
Variables
string m_flag
bool m_invert
bool m_resetSprite
bool m_flagSet
bool m_slide
int m_slideTime
vec2 m_slideVisible
vec2 m_slideHidden
bool m_slideHiding
Function Documentation
AnimateSet()
void LoadFlagWidget::AnimateSet (string key, bool b) override
Definition at line 168 of file FlagWidget.as.
FlagWidget()
LoadFlagWidget::FlagWidget ()
Definition at line 105 of file FlagWidget.as.
Referenced by LoadFlagWidget().
Load()
void LoadFlagWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 110 of file FlagWidget.as.
LoadFlagWidget()
FlagWidget Widget LoadFlagWidget (WidgetLoadingContext & ctx)
Definition at line 87 of file FlagWidget.as.
References FlagWidget(), and FlagWidget::Load().
Referenced by BaseGameMode::BaseGameMode().
 {
     FlagWidget@ w = FlagWidget();
     w.Load(ctx);
     return w;
 }
Update()
void LoadFlagWidget::Update (int dt) override
Definition at line 130 of file FlagWidget.as.
Variable Documentation
m_flag
string m_flag
Definition at line 93 of file FlagWidget.as.
m_flagSet
bool m_flagSet
Definition at line 97 of file FlagWidget.as.
m_invert
bool m_invert
Definition at line 94 of file FlagWidget.as.
m_resetSprite
bool m_resetSprite
Definition at line 95 of file FlagWidget.as.
m_slide
bool m_slide
Definition at line 99 of file FlagWidget.as.
m_slideHidden
vec2 m_slideHidden
Definition at line 102 of file FlagWidget.as.
m_slideHiding
bool m_slideHiding
Definition at line 103 of file FlagWidget.as.
m_slideTime
int m_slideTime
Definition at line 100 of file FlagWidget.as.
m_slideVisible
vec2 m_slideVisible
Definition at line 101 of file FlagWidget.as.