HoHDocs: scripts/GUI/CheckBoxGroup.as File Reference
CheckBoxGroup.as File Reference
Classes
class CheckBoxGroupWidget
Functions
bool IsChecked ()
void SetCheckable ()
void SetChecked (bool b)
void SetGroupWidget (CheckBoxGroupWidget@ group)
bool IsEnabled ()
CheckBoxGroupWidget ScrollableWidget LoadCheckBoxGroupWidget (WidgetLoadingContext &ctx)
CheckBoxGroupWidget ()
Widget Clone () override
void Reset ()
void Cancel ()
void Save ()
bool IsChanged ()
array< ICheckableWidget@> FindCheckables (Widget@ w)
void ClearChildren () override
void AddChild (ref widget, int insertAt=-1) override
void Toggled (ICheckableWidget@ check)
void SetCheckedRandom (int subtract=0)
void SetChecked (int index)
void SetChecked (string value)
ICheckableWidget GetChecked ()
void Update (int dt) override
void Load (WidgetLoadingContext &ctx) override
void DoLayout (vec2 origin, vec2 parentSz) override
bool OnDoubleClick (vec2 mousePos) override
Variables
array< ICheckableWidget@> m_checkboxes
string m_func
string m_funcDouble
string m_cvar
bool m_cvarInit
cvar_type m_cvarType
string m_cvarOrigString
bool m_cvarOrigBool
int m_cvarOrigInt
float m_cvarOrigFloat
bool m_dynamicSize
Function Documentation
AddChild()
void LoadCheckBoxGroupWidget::AddChild (ref widget, int insertAt = -1) override
Definition at line 148 of file CheckBoxGroup.as.
     {
         ScrollableWidget::AddChild(widget, insertAt);
         array<ICheckableWidget@> checkables = FindCheckables(cast<Widget>(widget));
         for (uint i = 0; i < checkables.length(); i++)
         {
             auto checkable = checkables[i];
             checkable.SetCheckable();
Cancel()
void LoadCheckBoxGroupWidget::Cancel ()
Definition at line 67 of file CheckBoxGroup.as.
     {
         if (m_cvarType == cvar_type::String)
         {
             SetVar(m_cvar, m_cvarOrigString);
             SetChecked(m_cvarOrigString);
         }
         else if (m_cvarType == cvar_type::Bool)
         {
             SetVar(m_cvar, m_cvarOrigBool);
             if (m_cvarOrigBool)
                 SetChecked("true");
             else
                 SetChecked("false");
         }
         else if (m_cvarType == cvar_type::Int)
         {
             SetVar(m_cvar, m_cvarOrigInt);
             SetChecked("" + m_cvarOrigInt);
         }
         else if (m_cvarType == cvar_type::Float)
         {
CheckBoxGroupWidget()
LoadCheckBoxGroupWidget::CheckBoxGroupWidget ()
Definition at line 24 of file CheckBoxGroup.as.
Referenced by LoadCheckBoxGroupWidget().
     {
ClearChildren()
void LoadCheckBoxGroupWidget::ClearChildren () override
Definition at line 141 of file CheckBoxGroup.as.
     {
Clone()
Widget LoadCheckBoxGroupWidget::Clone () override
Definition at line 29 of file CheckBoxGroup.as.
     {
         super();
     }
     Widget@ Clone() override
     {
DoLayout()
void LoadCheckBoxGroupWidget::DoLayout (vec2 origin, vec2 parentSz) override
Definition at line 284 of file CheckBoxGroup.as.
Referenced by ShopMenu::DoLayout(), GameOver::DoShow(), GuildHallStatsTab::RefreshList(), BaseGameMode::ResizeWindow(), DialogWindow::SetButtonNo(), DialogWindow::SetButtonYes(), DialogWindow::SetInput(), DialogWindow::SetQuestion(), UserWindow::Show(), HUDCoop::Update(), Update(), and DungeonSettingsMenu::UpdateNgp().
     {
         if (m_dynamicSize)
         {
             m_width = int(parentSz.x);
             m_height = int(parentSz.y);
FindCheckables()
array<ICheckableWidget@> LoadCheckBoxGroupWidget::FindCheckables (Widget@ w)
Definition at line 120 of file CheckBoxGroup.as.
     {
         array<ICheckableWidget@> ret;
         ICheckableWidget@ cb = cast<ICheckableWidget>(w);
         if (cb !is null)
             ret.insertLast(cb);
         for (uint i = 0; i < w.m_children.length(); i++)
         {
             array<ICheckableWidget@> arr = FindCheckables(w.m_children[i]);
             if (arr.length() > 0)
             {
                 for (uint j = 0; j < arr.length(); j++)
                     ret.insertLast(arr[j]);
             }
GetChecked()
ICheckableWidget LoadCheckBoxGroupWidget::GetChecked ()
Definition at line 218 of file CheckBoxGroup.as.
     {
         for (uint i = 0; i < m_checkboxes.length(); i++)
         {
             if (m_checkboxes[i].IsChecked())
IsChanged()
bool LoadCheckBoxGroupWidget::IsChanged ()
Definition at line 107 of file CheckBoxGroup.as.
     {
         if (m_cvarType == cvar_type::String)
             return GetVarString(m_cvar) != m_cvarOrigString;
         else if (m_cvarType == cvar_type::Bool)
             return GetVarBool(m_cvar) != m_cvarOrigBool;
         else if (m_cvarType == cvar_type::Int)
             return GetVarInt(m_cvar) != m_cvarOrigInt;
IsChecked()
bool IsChecked ()
Definition at line 318 of file CheckBox.as.
Referenced by FountainShopMenuContent::AnyEffectSelected(), and CheckBoxGroupWidget::GetChecked().
IsEnabled()
bool IsEnabled ()
Definition at line 322 of file CheckBox.as.
Referenced by CheckBoxGroupWidget::SetCheckedRandom().
Load()
void LoadCheckBoxGroupWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 267 of file CheckBoxGroup.as.
                                                : " + int(m_cvarType));
         }
     }
     void Load(WidgetLoadingContext &ctx) override
     {
         m_func = ctx.GetString("func", false);
         m_funcDouble = ctx.GetString("func-double", false);
         m_cvar = ctx.GetString("cvar", false);
         m_autoScroll = false;
         m_clipping = false;
         ScrollableWidget::Load(ctx);
LoadCheckBoxGroupWidget()
CheckBoxGroupWidget ScrollableWidget LoadCheckBoxGroupWidget (WidgetLoadingContext & ctx)
Definition at line 308 of file CheckBoxGroup.as.
References CheckBoxGroupWidget(), and CheckBoxGroupWidget::Load().
Referenced by BaseGameMode::BaseGameMode().
 {
     CheckBoxGroupWidget@ w = CheckBoxGroupWidget();
     w.Load(ctx);
     return w;
 }
OnDoubleClick()
bool LoadCheckBoxGroupWidget::OnDoubleClick (vec2 mousePos) override
Definition at line 295 of file CheckBoxGroup.as.
     {
         if (m_funcDouble != "")
Reset()
void LoadCheckBoxGroupWidget::Reset ()
Definition at line 36 of file CheckBoxGroup.as.
     {
         if (m_cvarType == cvar_type::String)
         {
             string def = GetVarStringDefault(m_cvar);
             SetVar(m_cvar, def);
             SetChecked(def);
         }
         else if (m_cvarType == cvar_type::Bool)
         {
             bool def = GetVarBoolDefault(m_cvar);
             SetVar(m_cvar, def);
             if (def)
                 SetChecked("true");
             else
                 SetChecked("false");
         }
         else if (m_cvarType == cvar_type::Int)
         {
             int def = GetVarIntDefault(m_cvar);
             SetVar(m_cvar, def);
             SetChecked("" + def);
         }
         else if (m_cvarType == cvar_type::Float)
         {
             float def = GetVarFloatDefault(m_cvar);
Save()
void LoadCheckBoxGroupWidget::Save ()
Definition at line 94 of file CheckBoxGroup.as.
     {
         if (m_cvarType == cvar_type::String)
             m_cvarOrigString = GetVarString(m_cvar);
         else if (m_cvarType == cvar_type::Bool)
             m_cvarOrigBool = GetVarBool(m_cvar);
         else if (m_cvarType == cvar_type::Int)
             m_cvarOrigInt = GetVarInt(m_cvar);
SetCheckable()
void SetCheckable ()
Definition at line 319 of file CheckBox.as.
SetChecked() [1/3]
void SetChecked (bool b)
Definition at line 320 of file CheckBox.as.
SetChecked() [2/3]
void LoadCheckBoxGroupWidget::SetChecked (int index)
Definition at line 206 of file CheckBoxGroup.as.
     {
SetChecked() [3/3]
void LoadCheckBoxGroupWidget::SetChecked (string value)
Definition at line 212 of file CheckBoxGroup.as.
     {
SetCheckedRandom()
void LoadCheckBoxGroupWidget::SetCheckedRandom (int subtract = 0)
Definition at line 179 of file CheckBoxGroup.as.
     {
         int numEnabled = 0;
         for (int i = 0; i < int(m_checkboxes.length()) - subtract; i++)
         {
             if (m_checkboxes[i].IsEnabled())
                 numEnabled++;
         }
         int randomIndex = randi(numEnabled);
         int index = 0;
         for (uint i = 0; i < m_checkboxes.length(); i++)
         {
             if (!m_checkboxes[i].IsEnabled())
                 continue;
             if (index == randomIndex)
             {
                 SetChecked(i);
                 break;
             }
SetGroupWidget()
void SetGroupWidget (CheckBoxGroupWidget@ group)
Definition at line 321 of file CheckBox.as.
Toggled()
void LoadCheckBoxGroupWidget::Toggled (ICheckableWidget@ check)
Definition at line 162 of file CheckBoxGroup.as.
     {
         for (uint i = 0; i < m_checkboxes.length(); i++)
         {
             if (m_checkboxes[i] is check)
             {
                 check.SetChecked(true);
                 continue;
             }
             m_checkboxes[i].SetChecked(false);
         }
Update()
void LoadCheckBoxGroupWidget::Update (int dt) override
Definition at line 228 of file CheckBoxGroup.as.
     {
         ScrollableWidget::Update(dt);
         if (!m_cvarInit && m_cvar != "")
         {
             m_cvarInit = true;
             SetID(m_cvar);
             m_cvarType = GetVarType(m_cvar);
             if (m_cvarType == cvar_type::String)
             {
                 m_cvarOrigString = GetVarString(m_cvar);
                 SetChecked(m_cvarOrigString);
             }
             else if (m_cvarType == cvar_type::Bool)
             {
                 m_cvarOrigBool = GetVarBool(m_cvar);
                 if (m_cvarOrigBool)
                     SetChecked("true");
                 else
                     SetChecked("false");
             }
             else if (m_cvarType == cvar_type::Int)
             {
                 m_cvarOrigInt = GetVarInt(m_cvar);
                 SetChecked("" + m_cvarOrigInt);
             }
             else if (m_cvarType == cvar_type::Float)
             {
                 m_cvarOrigFloat = GetVarFloat(m_cvar);
                 SetChecked("" + m_cvarOrigFloat);
             }
Variable Documentation
m_checkboxes
array<ICheckableWidget@> m_checkboxes
Definition at line 9 of file CheckBoxGroup.as.
m_cvar
string m_cvar
Definition at line 13 of file CheckBoxGroup.as.
m_cvarInit
bool m_cvarInit
Definition at line 14 of file CheckBoxGroup.as.
m_cvarOrigBool
bool m_cvarOrigBool
Definition at line 18 of file CheckBoxGroup.as.
m_cvarOrigFloat
float m_cvarOrigFloat
Definition at line 20 of file CheckBoxGroup.as.
m_cvarOrigInt
int m_cvarOrigInt
Definition at line 19 of file CheckBoxGroup.as.
m_cvarOrigString
string m_cvarOrigString
Definition at line 17 of file CheckBoxGroup.as.
m_cvarType
cvar_type m_cvarType
Definition at line 16 of file CheckBoxGroup.as.
m_dynamicSize
bool m_dynamicSize
Definition at line 22 of file CheckBoxGroup.as.
m_func
string m_func
Definition at line 11 of file CheckBoxGroup.as.
m_funcDouble
string m_funcDouble
Definition at line 12 of file CheckBoxGroup.as.