HoHDocs: scripts/GUI/DetailsWidget.as File Reference
DetailsWidget.as File Reference
Classes
class DetailsWidget
Functions
DetailsWidget Widget LoadDetailsWidget (WidgetLoadingContext &ctx)
DetailsWidget ()
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void UpdateSize ()
void ToggleDetails ()
void AddedToParent () override
void DoDraw (SpriteBatch &sb, vec2 pos) override
bool OnMouseDown (vec2 mousePos) override
bool OnMouseUp (vec2 mousePos) override
bool OnClick (vec2 mousePos) override
Variables
SpriteRect m_spriteRect
Sprite m_spriteArrowDown
Sprite m_spriteArrowUp
Widget m_wHeader
Widget m_wDetails
bool m_pressedDown
string m_func
Function Documentation
AddedToParent()
void LoadDetailsWidget::AddedToParent () override
Definition at line 476 of file DetailsWidget.as.
Clone()
Widget LoadDetailsWidget::Clone () override
Definition at line 401 of file DetailsWidget.as.
DetailsWidget()
LoadDetailsWidget::DetailsWidget ()
Definition at line 396 of file DetailsWidget.as.
Referenced by LoadDetailsWidget().
DoDraw()
void LoadDetailsWidget::DoDraw (SpriteBatch & sb, vec2 pos) override
Definition at line 500 of file DetailsWidget.as.
Load()
void LoadDetailsWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 408 of file DetailsWidget.as.
LoadDetailsWidget()
DetailsWidget Widget LoadDetailsWidget (WidgetLoadingContext & ctx)
Definition at line 169 of file DetailsWidget.as.
References DetailsWidget(), and DetailsWidget::Load().
Referenced by BaseGameMode::BaseGameMode().
 {
     DetailsWidget@ w = DetailsWidget();
     w.Load(ctx);
     return w;
 }
OnClick()
bool LoadDetailsWidget::OnClick (vec2 mousePos) override
Definition at line 543 of file DetailsWidget.as.
OnMouseDown()
bool LoadDetailsWidget::OnMouseDown (vec2 mousePos) override
Definition at line 531 of file DetailsWidget.as.
OnMouseUp()
bool LoadDetailsWidget::OnMouseUp (vec2 mousePos) override
Definition at line 537 of file DetailsWidget.as.
ToggleDetails()
void LoadDetailsWidget::ToggleDetails ()
Definition at line 466 of file DetailsWidget.as.
UpdateSize()
void LoadDetailsWidget::UpdateSize ()
Definition at line 436 of file DetailsWidget.as.
Variable Documentation
m_func
string m_func
Definition at line 394 of file DetailsWidget.as.
m_pressedDown
bool m_pressedDown
Definition at line 392 of file DetailsWidget.as.
m_spriteArrowDown
Sprite m_spriteArrowDown
Definition at line 386 of file DetailsWidget.as.
m_spriteArrowUp
Sprite m_spriteArrowUp
Definition at line 387 of file DetailsWidget.as.
m_spriteRect
SpriteRect m_spriteRect
Definition at line 384 of file DetailsWidget.as.
m_wDetails
Widget m_wDetails
Definition at line 390 of file DetailsWidget.as.
m_wHeader
Widget m_wHeader
Definition at line 389 of file DetailsWidget.as.