HoHDocs: scripts/GUI/ButtonWidget.as File Reference
ButtonWidget.as File Reference
Classes
class ButtonWidget
Functions
ButtonWidget RectWidget LoadButtonWidget (WidgetLoadingContext &ctx)
ButtonWidget ()
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void SetText (string str)
void SetText (string str, vec4 color)
void SetText (string str, vec4 color, TextAlignment align)
void SetEnabled (bool enabled)
void SetColor (vec4 color)
bool OnClick (vec2 mousePos) override
void OnMouseEnter (vec2 mousePos, bool forced) override
void OnMouseLeave (vec2 mousePos) override
void DoDraw (SpriteBatch &sb, vec2 pos) override
void ShowTooltip () override
Variables
string m_func
string m_funcHover
BitmapFont m_font
vec4 m_textColor
vec4 m_textColorHover
vec4 m_textColorDisabled
bool m_textWrapping
string m_text
TextAlignment m_alignment = TextAlignment::Center
string m_textCurrent
bool m_enabled
vec2 m_textOffset
BitmapString m_renderText
Sprite m_sprite
SoundEvent m_pressSound
SoundEvent m_hoverSound
Function Documentation
ButtonWidget()
LoadButtonWidget::ButtonWidget ()
Definition at line 107 of file ButtonWidget.as.
References Widget::m_hovering, ButtonWidget::m_textColor, ButtonWidget::m_textColorHover, and ButtonWidget::SetColor().
Referenced by LoadButtonWidget().
         {
             if (m_hovering)
                 SetColor(m_textColorHover);
             else
Clone()
Widget LoadButtonWidget::Clone () override
Definition at line 112 of file ButtonWidget.as.
     {
DoDraw()
void LoadButtonWidget::DoDraw (SpriteBatch & sb, vec2 pos) override
Definition at line 239 of file ButtonWidget.as.
Load()
void LoadButtonWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 119 of file ButtonWidget.as.
     {
         if (!m_enabled)
             return false;
         m_host.OnFunc(this, m_func);
         PlaySound2D(m_pressSound);
         return true;
     }
     void OnMouseEnter(vec2 mousePos, bool forced) override
     {
         if (m_enabled)
         {
             PlaySound2D(m_hoverSound);
             SetColor(m_textColorHover);
             if (m_funcHover != "")
                 m_host.OnFunc(this, m_func);
         }
         RectWidget::OnMouseEnter(mousePos, forced);
     }
     void OnMouseLeave(vec2 mousePos) override
     {
         if (m_enabled)
             SetColor(m_textColor);
         else
             SetColor(m_textColorDisabled);
         RectWidget::OnMouseLeave(mousePos);
     }
     void DoDraw(SpriteBatch& sb, vec2 pos) override
     {
LoadButtonWidget()
ButtonWidget RectWidget LoadButtonWidget (WidgetLoadingContext & ctx)
Definition at line 206 of file ButtonWidget.as.
References ButtonWidget(), and ButtonWidget::Load().
Referenced by BaseGameMode::BaseGameMode().
 {
     ButtonWidget@ w = ButtonWidget();
     w.Load(ctx);
     return w;
 }
OnClick()
bool LoadButtonWidget::OnClick (vec2 mousePos) override
Definition at line 205 of file ButtonWidget.as.
 {
     ButtonWidget@ w = ButtonWidget();
     w.Load(ctx);
     return w;
 }
OnMouseEnter()
void LoadButtonWidget::OnMouseEnter (vec2 mousePos, bool forced) override
Definition at line 215 of file ButtonWidget.as.
OnMouseLeave()
void LoadButtonWidget::OnMouseLeave (vec2 mousePos) override
Definition at line 229 of file ButtonWidget.as.
SetColor()
void LoadButtonWidget::SetColor (vec4 color)
Definition at line 199 of file ButtonWidget.as.
References ButtonWidget::m_enabled, Widget::m_tooltipEnabled, and Widget::ShowTooltip().
     {
         m_tooltipEnabled = m_enabled;
         RectWidget::ShowTooltip();
     }
SetEnabled()
void LoadButtonWidget::SetEnabled (bool enabled)
Definition at line 185 of file ButtonWidget.as.
Referenced by Menu::MultiplayerMenu::Update().
         {
             float wSprite = m_sprite.GetWidth();
             float hSprite = m_sprite.GetHeight();
             sb.DrawSprite(vec2(
                 pos.x + m_width / 2 - wSprite / 2,
                 pos.y + m_height / 2 - hSprite / 2
             ), m_sprite, g_menuTime);
         }
     }
SetText() [1/3]
void LoadButtonWidget::SetText (string str)
Definition at line 160 of file ButtonWidget.as.
References ButtonWidget::m_renderText.
         {
             int wText = int(m_renderText.GetWidth());
SetText() [2/3]
void LoadButtonWidget::SetText (string str, vec4 color)
Definition at line 165 of file ButtonWidget.as.
References Widget::m_height, and ButtonWidget::m_textOffset.
             {
                 sb.DrawString(vec2(
                     int(pos.x + m_textOffset.x),
SetText() [3/3]
void LoadButtonWidget::SetText (string str, vec4 color, TextAlignment align)
Definition at line 170 of file ButtonWidget.as.
             {
                 sb.DrawString(vec2(
                     int(pos.x + m_textOffset.x + m_width / 2 - wText / 2),
                     int(pos.y + m_textOffset.y + m_height / 2 - hText / 2)
                 ), m_renderText);
             }
             else if (m_alignment == TextAlignment::Right)
             {
                 sb.DrawString(vec2(
                     int(pos.x + m_textOffset.x + m_width - wText),
                     int(pos.y + m_textOffset.y + m_height / 2 - hText / 2)
ShowTooltip()
void LoadButtonWidget::ShowTooltip () override
Definition at line 281 of file ButtonWidget.as.
Variable Documentation
m_alignment
TextAlignment m_alignment = TextAlignment::Center
Definition at line 94 of file ButtonWidget.as.
m_enabled
bool m_enabled
Definition at line 96 of file ButtonWidget.as.
Referenced by Update().
m_font
BitmapFont m_font
Definition at line 88 of file ButtonWidget.as.
Referenced by CounterWidget().
m_func
string m_func
Definition at line 85 of file ButtonWidget.as.
m_funcHover
string m_funcHover
Definition at line 86 of file ButtonWidget.as.
m_hoverSound
SoundEvent m_hoverSound
Definition at line 105 of file ButtonWidget.as.
m_pressSound
SoundEvent m_pressSound
Definition at line 104 of file ButtonWidget.as.
m_renderText
BitmapString m_renderText
Definition at line 100 of file ButtonWidget.as.
m_sprite
Sprite m_sprite
Definition at line 102 of file ButtonWidget.as.
m_text
string m_text
Definition at line 93 of file ButtonWidget.as.
m_textColor
vec4 m_textColor
Definition at line 89 of file ButtonWidget.as.
m_textColorDisabled
vec4 m_textColorDisabled
Definition at line 91 of file ButtonWidget.as.
m_textColorHover
vec4 m_textColorHover
Definition at line 90 of file ButtonWidget.as.
m_textCurrent
string m_textCurrent
Definition at line 95 of file ButtonWidget.as.
m_textOffset
vec2 m_textOffset
Definition at line 98 of file ButtonWidget.as.
m_textWrapping
bool m_textWrapping
Definition at line 92 of file ButtonWidget.as.