HoHDocs: scripts/GUI/HUD/WaypointMarkers.as File Reference
WaypointMarkers.as File Reference
Classes
class WaypointMarkersWidget
Functions
WaypointMarkersWidget Widget LoadWaypointMarkersWidget (WidgetLoadingContext &ctx)
WaypointMarkersWidget ()
void Load (WidgetLoadingContext &ctx) override
void AddWaypoint (Waypoint@ wp)
void Update (int dt) override
void DoDraw (SpriteBatch &sb, vec2 pos) override
Variables
array< Waypoint@> m_waypoints
Function Documentation
AddWaypoint()
void LoadWaypointMarkersWidget::AddWaypoint (Waypoint@ wp)
Definition at line 240 of file WaypointMarkers.as.
DoDraw()
void LoadWaypointMarkersWidget::DoDraw (SpriteBatch & sb, vec2 pos) override
Definition at line 257 of file WaypointMarkers.as.
Load()
void LoadWaypointMarkersWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 233 of file WaypointMarkers.as.
LoadWaypointMarkersWidget()
WaypointMarkersWidget Widget LoadWaypointMarkersWidget (WidgetLoadingContext & ctx)
Definition at line 61 of file WaypointMarkers.as.
References WaypointMarkersWidget::Load(), and WaypointMarkersWidget().
Referenced by HUD::HUD().
 {
     WaypointMarkersWidget@ w = WaypointMarkersWidget();
     w.Load(ctx);
     return w;
 }
Update()
void LoadWaypointMarkersWidget::Update (int dt) override
Definition at line 245 of file WaypointMarkers.as.
WaypointMarkersWidget()
LoadWaypointMarkersWidget::WaypointMarkersWidget ()
Definition at line 228 of file WaypointMarkers.as.
Referenced by LoadWaypointMarkersWidget().
Variable Documentation
m_waypoints
array<Waypoint@> m_waypoints
Definition at line 226 of file WaypointMarkers.as.