HoHDocs: scripts/GUI/HUD/BossBar.as File Reference
BossBar.as File Reference
Classes
class BossBarWidget
Functions
BossBarWidget BarWidget LoadBossBarWidget (WidgetLoadingContext &ctx)
BossBarWidget ()
Widget Clone () override
void Remove () override
void Load (WidgetLoadingContext &ctx) override
Sprite GetBarSprite (float factor) override
void Update (int dt) override
void SetText (string str)
void DoDraw (SpriteBatch &sb, vec2 pos) override
void UpdateAppearance ()
Variables
Actor m_actor
float m_checkpoint = -1
BitmapFont m_font
BitmapString m_text
Sprite m_spriteBarInvuln
Sprite m_spriteBarCheckpoint
vec2 m_textOffset
Function Documentation
BossBarWidget()
LoadBossBarWidget::BossBarWidget ()
Definition at line 158 of file BossBar.as.
Referenced by LoadBossBarWidget().
Clone()
Widget LoadBossBarWidget::Clone () override
Definition at line 163 of file BossBar.as.
DoDraw()
void LoadBossBarWidget::DoDraw (SpriteBatch & sb, vec2 pos) override
Definition at line 223 of file BossBar.as.
Referenced by BossBarWidget::DoDraw().
GetBarSprite()
Sprite LoadBossBarWidget::GetBarSprite (float factor) override
Definition at line 197 of file BossBar.as.
Referenced by BossBarWidget::GetBarSprite().
Load()
void LoadBossBarWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 185 of file BossBar.as.
Referenced by BossBarWidget::Load().
LoadBossBarWidget()
BossBarWidget BarWidget LoadBossBarWidget (WidgetLoadingContext & ctx)
Definition at line 128 of file BossBar.as.
References BossBarWidget(), and BossBarWidget::Load().
Referenced by HUD::HUD().
 {
     BossBarWidget@ w = BossBarWidget();
     w.Load(ctx);
     return w;
 }
Remove()
void LoadBossBarWidget::Remove () override
Definition at line 170 of file BossBar.as.
Referenced by BossBarWidget::Remove().
SetText()
void LoadBossBarWidget::SetText (string str)
Definition at line 212 of file BossBar.as.
Update()
void LoadBossBarWidget::Update (int dt) override
Definition at line 206 of file BossBar.as.
Referenced by BossBarWidget::Update().
UpdateAppearance()
void LoadBossBarWidget::UpdateAppearance ()
Definition at line 236 of file BossBar.as.
Variable Documentation
m_actor
Actor m_actor
Definition at line 146 of file BossBar.as.
m_checkpoint
float m_checkpoint = -1
Definition at line 148 of file BossBar.as.
m_font
BitmapFont m_font
Definition at line 150 of file BossBar.as.
m_spriteBarCheckpoint
Sprite m_spriteBarCheckpoint
Definition at line 154 of file BossBar.as.
m_spriteBarInvuln
Sprite m_spriteBarInvuln
Definition at line 153 of file BossBar.as.
m_text
BitmapString m_text
Definition at line 151 of file BossBar.as.
m_textOffset
vec2 m_textOffset
Definition at line 156 of file BossBar.as.