HoHDocs: scripts/GUI/MenuControlInput.as File Reference
MenuControlInput.as File Reference
Classes
class MenuControlInputWidget
Functions
MenuControlInputWidget ButtonWidget LoadMenuControlInput (WidgetLoadingContext &ctx)
MenuControlInputWidget ()
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
bool OnClick (vec2 mousePos) override
void Clear ()
array< ControlMapBinding@> GetBindings ()
void ExpectedInput (ControllerType type, int key)
void UpdateText ()
Variables
ControlMap m_map
bool m_waitingForInput
bool m_axisAction
ControlBindingSetAxis m_axisSet
Function Documentation
Clear()
void Clear ()
Definition at line 174 of file MenuControlInput.as.
Clone()
Widget LoadMenuControlInput::Clone () override
Definition at line 129 of file MenuControlInput.as.
ExpectedInput()
void LoadMenuControlInput::ExpectedInput (ControllerType type, int key)
Definition at line 200 of file MenuControlInput.as.
GetBindings()
array<ControlMapBinding@> LoadMenuControlInput::GetBindings ()
Definition at line 181 of file MenuControlInput.as.
Load()
void LoadMenuControlInput::Load (WidgetLoadingContext & ctx) override
Definition at line 136 of file MenuControlInput.as.
 {
     MenuControlInputWidget@ w = MenuControlInputWidget();
     w.Load(ctx);
     return w;
 }
LoadMenuControlInput()
MenuControlInputWidget ButtonWidget LoadMenuControlInput (WidgetLoadingContext & ctx)
Definition at line 141 of file MenuControlInput.as.
References MenuControlInputWidget::Load(), and MenuControlInputWidget().
Referenced by MainMenu::MainMenu().
 {
     MenuControlInputWidget@ w = MenuControlInputWidget();
     w.Load(ctx);
     return w;
 }
MenuControlInputWidget()
LoadMenuControlInput::MenuControlInputWidget ()
Definition at line 124 of file MenuControlInput.as.
Referenced by LoadMenuControlInput().
         {
             if (text != "")
OnClick()
bool LoadMenuControlInput::OnClick (vec2 mousePos) override
Definition at line 150 of file MenuControlInput.as.
UpdateText()
void LoadMenuControlInput::UpdateText ()
Definition at line 233 of file MenuControlInput.as.
Variable Documentation
m_axisAction
bool m_axisAction
Definition at line 121 of file MenuControlInput.as.
m_axisSet
ControlBindingSetAxis m_axisSet
Definition at line 122 of file MenuControlInput.as.
m_map
ControlMap m_map
Definition at line 118 of file MenuControlInput.as.
Referenced by Menu::GetKbmPlayer().
m_waitingForInput
bool m_waitingForInput
Definition at line 119 of file MenuControlInput.as.