HoHDocs: scripts/GUI/GuildHall/Itemiary.as File Reference
Itemiary.as File Reference
Classes
class SortableItemiaryEntry
Functions
GuildHallItemiaryTab ()
void OnShow () override
void ReloadList ()
void AddItem (ItemiaryEntry@ entry)
void AddItemNothing ()
void AddDrink (TavernDrink@ drink)
Variables
class SortableItemiaryEntry m_wListItems
Widget m_wListDrinks
Widget m_wTemplateItem
Widget m_wTemplateItemNothing
Widget m_wTemplateDrink
Function Documentation
AddDrink()
void AddDrink (TavernDrink@ drink)
Definition at line 144 of file Itemiary.as.
References Widget::AddChild(), Widget::Clone(), TavernDrink::desc, GetItemQualityColorString(), TavernDrink::icon, m_wListDrinks, m_wTemplateDrink, TavernDrink::name, TavernDrink::quality, and Widget::SetID().
Referenced by ReloadList().
     {
         auto wNewDrink = m_wTemplateDrink.Clone();
         wNewDrink.SetID("");
         wNewDrink.m_visible = true;
         auto wIcon = cast<SpriteWidget>(wNewDrink.GetWidgetById("icon"));
         if (wIcon !is null)
             wIcon.SetSprite(drink.icon);
         wNewDrink.m_tooltipTitle = "\\c" + GetItemQualityColorString(drink.quality) + utf8string(Resources::GetString(drink.name)).toUpper().plain();
         wNewDrink.m_tooltipText = Resources::GetString(drink.desc);
         m_wListDrinks.AddChild(wNewDrink);
     }
AddItem()
void AddItem (ItemiaryEntry@ entry)
Definition at line 88 of file Itemiary.as.
References Widget::Clone(), Common, formatThousands(), GetItemQualityColor(), GetItemQualityColorString(), GetItemSetColorString(), GetLocalPlayerRecord(), ColorHSV::m_saturation, ColorHSV::m_value, m_wListItems, m_wTemplateItem, Widget::SetID(), and ColorHSV::ToColorRGBA().
Referenced by ReloadList().
     {
         ActorItem@ item = entry.m_item;
         auto wNewItem = m_wTemplateItem.Clone();
         wNewItem.SetID("");
         wNewItem.m_visible = true;
         auto wIcon = cast<SpriteWidget>(wNewItem.GetWidgetById("icon"));
         if (wIcon !is null)
             wIcon.SetSprite(item.icon);
         vec4 qualityColor = GetItemQualityColor(item.quality);
         auto wNameContainer = cast<RectWidget>(wNewItem.GetWidgetById("name-container"));
         if (wNameContainer !is null)
         {
             if (item.quality != ActorItemQuality::Common)
             {
                 ColorHSV hsv(qualityColor);
                 hsv.m_saturation *= 0.5f;
                 hsv.m_value *= 0.35f;
                 wNameContainer.m_color = tocolor(hsv.ToColorRGBA());
             }
             auto wName = cast<TextWidget>(wNameContainer.GetWidgetById("name"));
             if (wName !is null)
             {
                 wName.SetText(Resources::GetString(item.name));
                 if (item.quality != ActorItemQuality::Common)
                     wName.SetColor(qualityColor);
                 wName.m_tooltipTitle = "\\c" + GetItemQualityColorString(item.quality) + utf8string(Resources::GetString(item.name)).toUpper().plain();
                 wName.m_tooltipText = Resources::GetString(item.desc);
                 if (item.set !is null)
                 {
                     wName.m_tooltipText += "\n\n";
                     wName.m_tooltipText += GetItemSetColorString(GetLocalPlayerRecord(), item);
                 }
                 wName.m_tooltipText += "\n\n" + Resources::GetString(".itemiary.itemcount") + ": " + formatThousands(entry.m_count);
             }
         }
         m_wListItems.AddChild(wNewItem);
     }
AddItemNothing()
void AddItemNothing ()
Definition at line 136 of file Itemiary.as.
References Widget::Clone(), m_wListItems, m_wTemplateItemNothing, and Widget::SetID().
Referenced by ReloadList().
     {
         auto wNewNothing = m_wTemplateItemNothing.Clone();
         wNewNothing.SetID("");
         wNewNothing.m_visible = true;
         m_wListItems.AddChild(wNewNothing);
     }
GuildHallItemiaryTab()
GuildHallItemiaryTab ()
Definition at line 33 of file Itemiary.as.
References m_id.
Referenced by GuildHallMenu::GuildHallMenu().
     {
         m_id = "itemiary";
     }
OnShow()
void OnShow () override
Definition at line 38 of file Itemiary.as.
References m_widget, m_wListDrinks, m_wListItems, m_wTemplateDrink, m_wTemplateItem, m_wTemplateItemNothing, and ReloadList().
     {
         @m_wListItems = m_widget.GetWidgetById("list-items");
         @m_wListDrinks = m_widget.GetWidgetById("list-drinks");
         @m_wTemplateItem = m_widget.GetWidgetById("template-item");
         @m_wTemplateItemNothing = m_widget.GetWidgetById("template-item-nothing");
         @m_wTemplateDrink = m_widget.GetWidgetById("template-drink");
         ReloadList();
     }
ReloadList()
void ReloadList ()
Definition at line 51 of file Itemiary.as.
References AddDrink(), AddItem(), AddItemNothing(), Widget::ClearChildren(), MenuTab::DoLayout(), g_gameMode, g_tavernDrinks, Widget::m_height, m_wListDrinks, m_wListItems, and m_wTemplateDrink.
Referenced by OnShow().
     {
         auto gm = cast<Campaign>(g_gameMode);
         auto town = gm.m_townLocal;
         array<SortableItemiaryEntry@> items;
         for (uint i = 0; i < town.m_itemiary.length(); i++)
             items.insertLast(SortableItemiaryEntry(town.m_itemiary[i]));
         items.sortDesc();
         m_wListItems.ClearChildren();
         m_wListItems.m_height = int(ceil(items.length() / 2.0f)) * 22;
         for (uint i = 0; i < items.length(); i++)
             AddItem(items[i].m_entry);
         if (town.m_itemiary.length() % 2 == 1)
             AddItemNothing();
         m_wListDrinks.ClearChildren();
         int numDrinks = 0;
         for (uint i = 0; i < g_tavernDrinks.length(); i++)
         {
             auto drink = g_tavernDrinks[i];
             if (drink.localCount == -1)
                 continue;
             AddDrink(drink);
             numDrinks++;
         }
         m_wListDrinks.m_height = 5 + int(ceil(numDrinks / 11.0f)) * (m_wTemplateDrink.m_height + 2) + 5;
         DoLayout();
     }
Variable Documentation
m_wListDrinks
Widget m_wListDrinks
Definition at line 26 of file Itemiary.as.
Referenced by AddDrink(), OnShow(), and ReloadList().
m_wListItems
class SortableItemiaryEntry m_wListItems
Referenced by AddItem(), AddItemNothing(), OnShow(), and ReloadList().
m_wTemplateDrink
Widget m_wTemplateDrink
Definition at line 31 of file Itemiary.as.
Referenced by AddDrink(), OnShow(), and ReloadList().
m_wTemplateItem
Widget m_wTemplateItem
Definition at line 28 of file Itemiary.as.
Referenced by AddItem(), and OnShow().
m_wTemplateItemNothing
Widget m_wTemplateItemNothing
Definition at line 29 of file Itemiary.as.
Referenced by AddItemNothing(), and OnShow().