HoHDocs: scripts/GUI/HUD/HUDCoop.as File Reference
HUDCoop.as File Reference
Classes
class CoopPlayerWidget
class HUDCoop
Functions
CoopPlayerWidget RectWidget LoadCoopPlayerWidget (WidgetLoadingContext &ctx)
CoopPlayerWidget ()
void Load (WidgetLoadingContext &ctx) override
void SetPeer (PlayerRecord@ record)
void UpdatePortrait ()
void Update (int dt) override
Widget Clone () override
Variables
HUDCoop m_hudCoop
PlayerRecord m_record
SpriteWidget m_wPortrait
BarWidget m_wHealth
Widget m_wIconDead
SpriteWidget m_wIconSoulLink
SpriteWidget m_wTriangle
int m_lastSoulLink = -1
Function Documentation
Clone()
Widget LoadCoopPlayerWidget::Clone () override
Definition at line 772 of file HUDCoop.as.
CoopPlayerWidget()
LoadCoopPlayerWidget::CoopPlayerWidget ()
Definition at line 701 of file HUDCoop.as.
Referenced by LoadCoopPlayerWidget().
Load()
void LoadCoopPlayerWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 706 of file HUDCoop.as.
LoadCoopPlayerWidget()
CoopPlayerWidget RectWidget LoadCoopPlayerWidget (WidgetLoadingContext & ctx)
Definition at line 94 of file HUDCoop.as.
References CoopPlayerWidget(), and CoopPlayerWidget::Load().
Referenced by HUDCoop::HUDCoop().
 {
     CoopPlayerWidget@ w = CoopPlayerWidget();
     w.Load(ctx);
     return w;
 }
SetPeer()
void LoadCoopPlayerWidget::SetPeer (PlayerRecord@ record)
Definition at line 711 of file HUDCoop.as.
Update()
void LoadCoopPlayerWidget::Update (int dt) override
Definition at line 734 of file HUDCoop.as.
Referenced by HUDCoop::Update().
UpdatePortrait()
void LoadCoopPlayerWidget::UpdatePortrait ()
Definition at line 728 of file HUDCoop.as.
Variable Documentation
m_hudCoop
HUDCoop m_hudCoop
Definition at line 689 of file HUDCoop.as.
m_lastSoulLink
int m_lastSoulLink = -1
Definition at line 699 of file HUDCoop.as.
m_record
PlayerRecord m_record
Definition at line 691 of file HUDCoop.as.
Referenced by HUDCoop::Update().
m_wHealth
BarWidget m_wHealth
Definition at line 694 of file HUDCoop.as.
m_wIconDead
Widget m_wIconDead
Definition at line 695 of file HUDCoop.as.
m_wIconSoulLink
SpriteWidget m_wIconSoulLink
Definition at line 696 of file HUDCoop.as.
m_wPortrait
SpriteWidget m_wPortrait
Definition at line 693 of file HUDCoop.as.
m_wTriangle
SpriteWidget m_wTriangle
Definition at line 697 of file HUDCoop.as.