HoHDocs: scripts/GUI/RectWidget.as File Reference
RectWidget.as File Reference
Classes
class RectWidget
Functions
RectWidget Widget LoadRectWidget (WidgetLoadingContext &ctx)
RectWidget ()
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void DoDraw (SpriteBatch &sb, vec2 pos) override
void AnimateSet (string key, vec4 v) override
Variables
vec4 m_color
vec4 m_borderColor
int m_borderWidth
BorderType m_borderType
vec4 m_shadowColor
int m_shadowSize
SpriteRect m_spriteRect
Function Documentation
AnimateSet()
void LoadRectWidget::AnimateSet (string key, vec4 v) override
Definition at line 69 of file RectWidget.as.
References Widget::AnimateSet(), RectWidget::m_borderColor, and RectWidget::m_color.
     {
         if (key == "color")
             m_color = v;
         else if (key == "border")
             m_borderColor = v;
         Widget::AnimateSet(key, v);
     }
 }
Clone()
Widget LoadRectWidget::Clone () override
Definition at line 20 of file RectWidget.as.
References Widget::CloneInto(), and RectWidget::RectWidget().
     {
         RectWidget@ w = RectWidget();
         CloneInto(w);
         return w;
     }
DoDraw()
void LoadRectWidget::DoDraw (SpriteBatch & sb, vec2 pos) override
Definition at line 49 of file RectWidget.as.
References Widget::DoDraw(), Widget::DrawBorder(), RectWidget::m_borderColor, RectWidget::m_borderType, RectWidget::m_borderWidth, RectWidget::m_color, Widget::m_height, RectWidget::m_shadowColor, RectWidget::m_shadowSize, RectWidget::m_spriteRect, and Widget::m_width.
     {
         Widget::DoDraw(sb, pos);
         vec4 p = vec4(pos.x, pos.y, m_width, m_height);
         sb.DrawSprite(null, p, p, m_color);
         if (m_shadowSize > 0 && m_shadowColor.a > 0)
         {
             vec4 sp;
             sp = vec4(pos.x, pos.y, m_width, m_shadowSize); sb.DrawSprite(null, sp, sp, m_shadowColor);
             sp = vec4(pos.x, pos.y + m_shadowSize, m_shadowSize, m_height - m_shadowSize); sb.DrawSprite(null, sp, sp, m_shadowColor);
         }
         DrawBorder(sb, pos, vec2(m_width, m_height), m_borderWidth, m_borderColor, m_borderType);
         if (m_spriteRect !is null)
             m_spriteRect.Draw(sb, pos, m_width, m_height);
     }
Load()
void LoadRectWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 27 of file RectWidget.as.
References Widget::Load(), Widget::LoadWidthHeight(), RectWidget::m_borderColor, RectWidget::m_borderType, RectWidget::m_borderWidth, RectWidget::m_color, RectWidget::m_shadowColor, RectWidget::m_shadowSize, RectWidget::m_spriteRect, Middle, and SpriteRect().
     {
         LoadWidthHeight(ctx);
         m_color = ctx.GetColorRGBA("color", false, vec4(0, 0, 0, 0));
         m_borderColor = ctx.GetColorRGBA("border", false, vec4(0, 0, 0, 0));
         m_borderWidth = ctx.GetInteger("borderwidth", false, 1);
         string borderType = ctx.GetString("bordertype", false, "inner");
              if (borderType == "middle") m_borderType = BorderType::Middle;
         else if (borderType == "outer") m_borderType = BorderType::Outer;
         m_shadowColor = ctx.GetColorRGBA("shadow", false, vec4(0, 0, 0, 0.5f));
         m_shadowSize = ctx.GetInteger("shadowsize", false, 0);
         string spriteset = ctx.GetString("spriteset", false, "");
         if (spriteset != "")
             @m_spriteRect = SpriteRect(spriteset);
         Widget::Load(ctx);
     }
LoadRectWidget()
RectWidget Widget LoadRectWidget (WidgetLoadingContext & ctx)
Definition at line 78 of file RectWidget.as.
References RectWidget::Load(), and RectWidget().
Referenced by BaseGameMode::BaseGameMode().
 {
     RectWidget@ w = RectWidget();
     w.Load(ctx);
     return w;
 }
RectWidget()
LoadRectWidget::RectWidget ()
Definition at line 15 of file RectWidget.as.
Referenced by LoadRectWidget().
     {
         super();
     }
Variable Documentation
m_borderColor
vec4 m_borderColor
Definition at line 6 of file RectWidget.as.
m_borderType
BorderType m_borderType
Definition at line 8 of file RectWidget.as.
m_borderWidth
int m_borderWidth
Definition at line 7 of file RectWidget.as.
m_color
vec4 m_color
Definition at line 4 of file RectWidget.as.
m_shadowColor
vec4 m_shadowColor
Definition at line 10 of file RectWidget.as.
m_shadowSize
int m_shadowSize
Definition at line 11 of file RectWidget.as.
m_spriteRect
SpriteRect m_spriteRect
Definition at line 13 of file RectWidget.as.