HoHDocs: scripts/GUI/ScalableSpriteButtonWidget.as File Reference
ScalableSpriteButtonWidget.as File Reference
Classes
class ScalableSpriteButtonWidget
Functions
ScalableSpriteButtonWidget ICheckableWidget, Widget LoadScalableSpriteButtonWidget (WidgetLoadingContext &ctx)
ScalableSpriteButtonWidget ()
string GetValue ()
bool IsChecked ()
void SetCheckable ()
void SetChecked (bool b)
void SetGroupWidget (CheckBoxGroupWidget@ group)
Widget Clone () override
bool IsEnabled ()
void Load (WidgetLoadingContext &ctx) override
void SetText (string str)
void DoLayout (vec2 origin, vec2 parentSz) override
vec4 GetTextColor ()
array< Sprite@> GetSprites ()
void DoDraw (SpriteBatch &sb, vec2 pos) override
bool OnClick (vec2 mousePos) override
void OnMouseEnter (vec2 mousePos, bool forced) override
bool OnMouseDown (vec2 mousePos) override
bool OnMouseUp (vec2 mousePos) override
void OnMouseLeave (vec2 mousePos) override
void SetHovering (bool hovering, vec2 mousePos, bool force=false) override
void ShowTooltip () override
Variables
CheckBoxGroupWidget m_checkBoxGroup
array< Sprite@> m_sprite
array< Sprite@> m_spriteHover
array< Sprite@> m_spriteDown
array< Sprite@> m_spriteDisabled
string m_func
string m_funcHover
string m_funcLeave
SoundEvent m_pressSound
SoundEvent m_selectSound
bool m_buttonDown
vec4 m_colorText
vec4 m_colorTextOriginal
vec4 m_colorDisableText
vec4 m_colorHoverText
vec4 m_colorDownText
bool m_enabled
bool m_disabledInGame
bool m_dynamicWidth
BitmapFont m_font
BitmapString m_text
string m_value
bool m_checkable
bool m_checked
vec2 m_textOffset
Function Documentation
Clone()
Widget LoadScalableSpriteButtonWidget::Clone () override
Definition at line 116 of file ScalableSpriteButtonWidget.as.
References ScalableSpriteButtonWidget::m_dynamicWidth, and Widget::m_width.
         {
             m_dynamicWidth = true;
             m_width = 20;
         }
         m_height = m_sprite[0].GetHeight();
DoDraw()
void LoadScalableSpriteButtonWidget::DoDraw (SpriteBatch & sb, vec2 pos) override
Definition at line 234 of file ScalableSpriteButtonWidget.as.
                                              { m_buttonDown = true; return true; }
     bool OnMouseUp(vec2 mousePos) override { m_buttonDown = false; return true; }
     void OnMouseLeave(vec2 mousePos) override
     {
         Widget::OnMouseLeave(mousePos);
         if (!IsEnabled())
             return;
         m_buttonDown = false;
         if (m_funcLeave != "")
             m_host.OnFunc(this, m_funcLeave);
     }
     void SetHovering(bool hovering, vec2 mousePos, bool force = false) override
     {
         //HACK: We need to force current input focus to null here in order to avoid bad UX in text input dialog
         if (hovering)
             @g_gameMode.m_widgetInputFocus = null;
         Widget::SetHovering(hovering, mousePos, force);
     }
     void ShowTooltip() override
     {
         m_tooltipEnabled = m_enabled;
         Widget::ShowTooltip();
     }
 }
DoLayout()
void LoadScalableSpriteButtonWidget::DoLayout (vec2 origin, vec2 parentSz) override
Definition at line 200 of file ScalableSpriteButtonWidget.as.
     {
GetSprites()
array<Sprite@> LoadScalableSpriteButtonWidget::GetSprites ()
Definition at line 219 of file ScalableSpriteButtonWidget.as.
     {
         Widget::OnMouseEnter(mousePos, forced);
GetTextColor()
vec4 LoadScalableSpriteButtonWidget::GetTextColor ()
Definition at line 208 of file ScalableSpriteButtonWidget.as.
     {
         if (!IsEnabled())
             return false;
         if (!m_buttonDown)
             return true;
         if (m_checkable)
GetValue()
string LoadScalableSpriteButtonWidget::GetValue ()
Definition at line 110 of file ScalableSpriteButtonWidget.as.
 {
IsChecked()
bool LoadScalableSpriteButtonWidget::IsChecked ()
Definition at line 111 of file ScalableSpriteButtonWidget.as.
Referenced by CheckBoxGroupWidget::GetChecked().
 {
IsEnabled()
bool LoadScalableSpriteButtonWidget::IsEnabled ()
Definition at line 123 of file ScalableSpriteButtonWidget.as.
Referenced by CheckBoxGroupWidget::SetCheckedRandom().
     {
         if (str == "")
             @m_text = null;
Load()
void LoadScalableSpriteButtonWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 130 of file ScalableSpriteButtonWidget.as.
     {
         if (m_dynamicWidth && m_text !is null)
             m_width = m_text.GetWidth() + int(m_padding.x) * 2;
         Widget::DoLayout(origin, parentSz);
     }
     vec4 GetTextColor()
     {
         if (!IsEnabled())
             return m_colorDisableText;
         else if (m_buttonDown || (m_checked && m_checked))
             return m_colorDownText;
         else if (m_hovering)
             return m_colorHoverText;
         return m_colorText;
     }
     array<Sprite@> GetSprites()
     {
         if (!IsEnabled())
             return m_spriteDisabled;
         else
         {
             if (m_buttonDown || (m_checkable && m_checked))
                 return m_spriteDown;
             else if (m_hovering)
                 return m_spriteHover;
             else
                 return m_sprite;
         }
     }
     void DoDraw(SpriteBatch& sb, vec2 pos) override
     {
         array<Sprite@> sprites = GetSprites();
         if (sprites.length() == 0)
             return;
         Sprite@ left = sprites[0];
         Sprite@ mid = sprites[1];
         Sprite@ right = sprites[2];
         vec2 posLeft = pos;
         vec2 posRight = pos + vec2(m_width - right.GetWidth(), 0);
         vec4 rectMid = vec4(
             pos.x + left.GetWidth(),
             pos.y,
             m_width - left.GetWidth() - right.GetWidth(),
             m_height
         );
         sb.DrawSprite(posLeft, left, g_menuTime);
         sb.DrawSprite(mid.GetTexture2D(), rectMid, mid.GetFrame(g_menuTime));
         sb.DrawSprite(posRight, right, g_menuTime);
         if (m_text !is null)
LoadScalableSpriteButtonWidget()
ScalableSpriteButtonWidget ICheckableWidget, Widget LoadScalableSpriteButtonWidget (WidgetLoadingContext & ctx)
Definition at line 275 of file ScalableSpriteButtonWidget.as.
Referenced by BaseGameMode::BaseGameMode().
 {
     ScalableSpriteButtonWidget@ w = ScalableSpriteButtonWidget();
     w.Load(ctx);
     return w;
 }
OnClick()
bool LoadScalableSpriteButtonWidget::OnClick (vec2 mousePos) override
Definition at line 276 of file ScalableSpriteButtonWidget.as.
References ScalableSpriteButtonWidget::Load(), and ScalableSpriteButtonWidget().
 {
     ScalableSpriteButtonWidget@ w = ScalableSpriteButtonWidget();
     w.Load(ctx);
     return w;
 }
OnMouseDown()
bool LoadScalableSpriteButtonWidget::OnMouseDown (vec2 mousePos) override
Definition at line 310 of file ScalableSpriteButtonWidget.as.
OnMouseEnter()
void LoadScalableSpriteButtonWidget::OnMouseEnter (vec2 mousePos, bool forced) override
Definition at line 297 of file ScalableSpriteButtonWidget.as.
OnMouseLeave()
void LoadScalableSpriteButtonWidget::OnMouseLeave (vec2 mousePos) override
Definition at line 313 of file ScalableSpriteButtonWidget.as.
OnMouseUp()
bool LoadScalableSpriteButtonWidget::OnMouseUp (vec2 mousePos) override
Definition at line 311 of file ScalableSpriteButtonWidget.as.
ScalableSpriteButtonWidget()
LoadScalableSpriteButtonWidget::ScalableSpriteButtonWidget ()
Definition at line 105 of file ScalableSpriteButtonWidget.as.
Referenced by OnClick().
         {
SetCheckable()
void LoadScalableSpriteButtonWidget::SetCheckable ()
Definition at line 112 of file ScalableSpriteButtonWidget.as.
 {
SetChecked()
void LoadScalableSpriteButtonWidget::SetChecked (bool b)
Definition at line 113 of file ScalableSpriteButtonWidget.as.
 {
SetGroupWidget()
void LoadScalableSpriteButtonWidget::SetGroupWidget (CheckBoxGroupWidget@ group)
Definition at line 114 of file ScalableSpriteButtonWidget.as.
 {
SetHovering()
void LoadScalableSpriteButtonWidget::SetHovering (bool hovering, vec2 mousePos, bool force = false) override
Definition at line 326 of file ScalableSpriteButtonWidget.as.
SetText()
void LoadScalableSpriteButtonWidget::SetText (string str)
Definition at line 192 of file ScalableSpriteButtonWidget.as.
     {
ShowTooltip()
void LoadScalableSpriteButtonWidget::ShowTooltip () override
Definition at line 335 of file ScalableSpriteButtonWidget.as.
Variable Documentation
m_buttonDown
bool m_buttonDown
Definition at line 84 of file ScalableSpriteButtonWidget.as.
m_checkable
bool m_checkable
Definition at line 100 of file ScalableSpriteButtonWidget.as.
m_checkBoxGroup
CheckBoxGroupWidget m_checkBoxGroup
Definition at line 70 of file ScalableSpriteButtonWidget.as.
m_checked
bool m_checked
Definition at line 101 of file ScalableSpriteButtonWidget.as.
m_colorDisableText
vec4 m_colorDisableText
Definition at line 88 of file ScalableSpriteButtonWidget.as.
m_colorDownText
vec4 m_colorDownText
Definition at line 90 of file ScalableSpriteButtonWidget.as.
m_colorHoverText
vec4 m_colorHoverText
Definition at line 89 of file ScalableSpriteButtonWidget.as.
m_colorText
vec4 m_colorText
Definition at line 86 of file ScalableSpriteButtonWidget.as.
m_colorTextOriginal
vec4 m_colorTextOriginal
Definition at line 87 of file ScalableSpriteButtonWidget.as.
m_disabledInGame
bool m_disabledInGame
Definition at line 93 of file ScalableSpriteButtonWidget.as.
m_dynamicWidth
bool m_dynamicWidth
Definition at line 94 of file ScalableSpriteButtonWidget.as.
m_enabled
bool m_enabled
Definition at line 92 of file ScalableSpriteButtonWidget.as.
m_font
BitmapFont m_font
Definition at line 96 of file ScalableSpriteButtonWidget.as.
m_func
string m_func
Definition at line 77 of file ScalableSpriteButtonWidget.as.
m_funcHover
string m_funcHover
Definition at line 78 of file ScalableSpriteButtonWidget.as.
m_funcLeave
string m_funcLeave
Definition at line 79 of file ScalableSpriteButtonWidget.as.
m_pressSound
SoundEvent m_pressSound
Definition at line 81 of file ScalableSpriteButtonWidget.as.
m_selectSound
SoundEvent m_selectSound
Definition at line 82 of file ScalableSpriteButtonWidget.as.
m_sprite
array<Sprite@> m_sprite
Definition at line 72 of file ScalableSpriteButtonWidget.as.
m_spriteDisabled
array<Sprite@> m_spriteDisabled
Definition at line 75 of file ScalableSpriteButtonWidget.as.
m_spriteDown
array<Sprite@> m_spriteDown
Definition at line 74 of file ScalableSpriteButtonWidget.as.
m_spriteHover
array<Sprite@> m_spriteHover
Definition at line 73 of file ScalableSpriteButtonWidget.as.
m_text
BitmapString m_text
Definition at line 97 of file ScalableSpriteButtonWidget.as.
m_textOffset
vec2 m_textOffset
Definition at line 103 of file ScalableSpriteButtonWidget.as.
m_value
string m_value
Definition at line 99 of file ScalableSpriteButtonWidget.as.