HoHDocs: scripts/GUI/Menus/Widgets/MenuServerListItem.as File Reference
MenuServerListItem.as File Reference
Classes
class MenuServerListItem
Functions
MenuServerListItem ScalableSpriteButtonWidget LoadMenuServerListItemWidget (WidgetLoadingContext &ctx)
MenuServerListItem ()
int opCmp (const Widget@ w) override
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void Set (Menu::ServerlistMenu@ owner, string name, int players, int playersMax, int lobbyPing)
bool PassesFilter (string str) override
void DoDraw (SpriteBatch &sb, vec2 pos) override
Variables
Menu::ServerlistMenu m_owner
string m_serverName
int m_serverPlayers
int m_serverPlayersMax
BitmapString m_textPlayers
Function Documentation
Clone()
Widget LoadMenuServerListItemWidget::Clone () override
Definition at line 86 of file MenuServerListItem.as.
     {
         ScalableSpriteButtonWidget::DoDraw(sb, pos);
DoDraw()
void LoadMenuServerListItemWidget::DoDraw (SpriteBatch & sb, vec2 pos) override
Definition at line 133 of file MenuServerListItem.as.
Load()
void LoadMenuServerListItemWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 93 of file MenuServerListItem.as.
References ScalableSpriteButtonWidget::GetTextColor(), Widget::m_height, MenuServerListItem::m_textPlayers, and Widget::m_width.
         {
             m_textPlayers.SetColor(GetTextColor());
             sb.DrawString(pos + vec2(
                 m_width - m_textPlayers.GetWidth() - 10 /* - 24 */,
                 m_height / 2.0f - m_textPlayers.GetHeight() / 2.0f
LoadMenuServerListItemWidget()
MenuServerListItem ScalableSpriteButtonWidget LoadMenuServerListItemWidget (WidgetLoadingContext & ctx)
Definition at line 113 of file MenuServerListItem.as.
References MenuServerListItem::Load(), and MenuServerListItem().
Referenced by MainMenu::MainMenu().
 {
     MenuServerListItem@ w = MenuServerListItem();
     w.Load(ctx);
     return w;
 }
MenuServerListItem()
LoadMenuServerListItemWidget::MenuServerListItem ()
Definition at line 56 of file MenuServerListItem.as.
References MenuServerListItem::m_owner, MenuServerListItem::m_serverName, and name.
Referenced by LoadMenuServerListItemWidget().
     {
         @m_owner = owner;
opCmp()
int LoadMenuServerListItemWidget::opCmp (const Widget@ w) override
Definition at line 61 of file MenuServerListItem.as.
     {
         if (m_serverName.toLower().findFirst(str) != -1)
PassesFilter()
bool LoadMenuServerListItemWidget::PassesFilter (string str) override
Definition at line 126 of file MenuServerListItem.as.
Set()
void LoadMenuServerListItemWidget::Set (Menu::ServerlistMenu@ owner, string name, int players, int playersMax, int lobbyPing)
Definition at line 100 of file MenuServerListItem.as.
 {
     MenuServerListItem@ w = MenuServerListItem();
     w.Load(ctx);
     return w;
 }
Variable Documentation
m_owner
Menu::ServerlistMenu m_owner
Definition at line 47 of file MenuServerListItem.as.
m_serverName
string m_serverName
Definition at line 49 of file MenuServerListItem.as.
m_serverPlayers
int m_serverPlayers
Definition at line 50 of file MenuServerListItem.as.
m_serverPlayersMax
int m_serverPlayersMax
Definition at line 51 of file MenuServerListItem.as.
m_textPlayers
BitmapString m_textPlayers
Definition at line 53 of file MenuServerListItem.as.