HoHDocs: scripts/GUI/ScrollableRectWidget.as File Reference
ScrollableRectWidget.as File Reference
Classes
class ScrollableRectWidget
Functions
ScrollableRectWidget ScrollableWidget LoadScrollableRectWidget (WidgetLoadingContext &ctx)
ScrollableRectWidget ()
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void DoDraw (SpriteBatch &sb, vec2 pos) override
void AnimateSet (string key, vec4 v) override
Variables
vec4 m_color
vec4 m_borderColor
int m_borderWidth
BorderType m_borderType
vec4 m_shadowColor
int m_shadowSize
SpriteRect m_spriteRect
Function Documentation
AnimateSet()
void LoadScrollableRectWidget::AnimateSet (string key, vec4 v) override
Definition at line 89 of file ScrollableRectWidget.as.
Clone()
Widget LoadScrollableRectWidget::Clone () override
Definition at line 40 of file ScrollableRectWidget.as.
     {
DoDraw()
void LoadScrollableRectWidget::DoDraw (SpriteBatch & sb, vec2 pos) override
Definition at line 69 of file ScrollableRectWidget.as.
References Widget::AnimateSet(), ScrollableRectWidget::m_borderColor, and ScrollableRectWidget::m_color.
     {
         if (key == "color")
             m_color = v;
         else if (key == "border")
             m_borderColor = v;
         ScrollableWidget::AnimateSet(key, v);
     }
 }
 ref@ LoadScrollableRectWidget(WidgetLoadingContext &ctx)
 {
     ScrollableRectWidget@ w = ScrollableRectWidget();
     w.Load(ctx);
     return w;
 }
Load()
void LoadScrollableRectWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 47 of file ScrollableRectWidget.as.
     {
         ScrollableWidget::DoDraw(sb, pos);
         vec4 p = vec4(pos.x, pos.y, m_width, m_height);
         sb.DrawSprite(null, p, p, m_color);
         if (m_shadowSize > 0 && m_shadowColor.a > 0)
         {
             vec4 sp;
             sp = vec4(pos.x, pos.y, m_width, m_shadowSize); sb.DrawSprite(null, sp, sp, m_shadowColor);
             sp = vec4(pos.x, pos.y + m_shadowSize, m_shadowSize, m_height - m_shadowSize); sb.DrawSprite(null, sp, sp, m_shadowColor);
         }
         DrawBorder(sb, pos, vec2(m_width, m_height), m_borderWidth, m_borderColor, m_borderType);
         if (m_spriteRect !is null)
             m_spriteRect.Draw(sb, pos, m_width, m_height);
     }
LoadScrollableRectWidget()
ScrollableRectWidget ScrollableWidget LoadScrollableRectWidget (WidgetLoadingContext & ctx)
Definition at line 78 of file ScrollableRectWidget.as.
References ScrollableRectWidget::Load(), and ScrollableRectWidget().
Referenced by BaseGameMode::BaseGameMode().
 {
     ScrollableRectWidget@ w = ScrollableRectWidget();
     w.Load(ctx);
     return w;
 }
ScrollableRectWidget()
LoadScrollableRectWidget::ScrollableRectWidget ()
Definition at line 35 of file ScrollableRectWidget.as.
Referenced by LoadScrollableRectWidget().
Variable Documentation
m_borderColor
vec4 m_borderColor
Definition at line 26 of file ScrollableRectWidget.as.
m_borderType
BorderType m_borderType
Definition at line 28 of file ScrollableRectWidget.as.
m_borderWidth
int m_borderWidth
Definition at line 27 of file ScrollableRectWidget.as.
m_color
vec4 m_color
Definition at line 24 of file ScrollableRectWidget.as.
m_shadowColor
vec4 m_shadowColor
Definition at line 30 of file ScrollableRectWidget.as.
m_shadowSize
int m_shadowSize
Definition at line 31 of file ScrollableRectWidget.as.
m_spriteRect
SpriteRect m_spriteRect
Definition at line 33 of file ScrollableRectWidget.as.