HoHDocs: scripts/GUI/TransformWidget.as File Reference
TransformWidget.as File Reference
Classes
class TransformWidget
Functions
TransformWidget Widget LoadTransformWidget (WidgetLoadingContext &ctx)
TransformWidget ()
void Load (WidgetLoadingContext &ctx) override
void DoLayout (vec2 origin, vec2 parentSz) override
void Draw (SpriteBatch &sb, bool debugDraw) override
Variables
bool m_dynamicSz
mat4 m_transform
bool m_nativeScale
float m_scale = 1.0f
Function Documentation
DoLayout()
void LoadTransformWidget::DoLayout (vec2 origin, vec2 parentSz) override
Definition at line 73 of file TransformWidget.as.
         {
             tform *= g_gameMode.m_wndInvScaleTransform;
             tform *= mat::scale(mat4(), m_scale);
         }
         tform = mat::translate(tform, vec3(-px, -py, 0));
         sb.PushTransformation(tform);
         Widget::Draw(sb, debugDraw);
Draw()
void LoadTransformWidget::Draw (SpriteBatch & sb, bool debugDraw) override
Definition at line 90 of file TransformWidget.as.
 {
     TransformWidget@ w = TransformWidget();
     w.Load(ctx);
     return w;
 }
Load()
void LoadTransformWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 35 of file TransformWidget.as.
         {
             m_nativeScale = true;
             m_scale = parseFloat(strScale);
         }
         Widget::Load(ctx);
     }
     void DoLayout(vec2 origin, vec2 parentSz) override
     {
         if (m_dynamicSz)
         {
             m_width = int(parentSz.x);
             m_height = int(parentSz.y);
             if (m_nativeScale)
             {
                 m_width = int(m_width * g_gameMode.m_wndScale / m_scale);
                 m_height = int(m_height * g_gameMode.m_wndScale / m_scale);
             }
         }
         Widget::DoLayout(origin, parentSz);
     }
     void Draw(SpriteBatch& sb, bool debugDraw) override
     {
         float px = m_origin.x;
LoadTransformWidget()
TransformWidget Widget LoadTransformWidget (WidgetLoadingContext & ctx)
Definition at line 94 of file TransformWidget.as.
References TransformWidget::Load(), and TransformWidget().
Referenced by BaseGameMode::BaseGameMode().
 {
     TransformWidget@ w = TransformWidget();
     w.Load(ctx);
     return w;
 }
TransformWidget()
LoadTransformWidget::TransformWidget ()
Definition at line 30 of file TransformWidget.as.
Referenced by LoadTransformWidget().
         {
Variable Documentation
m_dynamicSz
bool m_dynamicSz
Definition at line 24 of file TransformWidget.as.
m_nativeScale
bool m_nativeScale
Definition at line 27 of file TransformWidget.as.
m_scale
float m_scale = 1.0f
Definition at line 28 of file TransformWidget.as.
m_transform
mat4 m_transform
Definition at line 25 of file TransformWidget.as.