HoHDocs: scripts/GUI/UnitWidget.as File Reference
UnitWidget.as File Reference
Classes
class UnitWidgetScene
Functions
UnitWidget ()
Widget Clone () override
void ClearUnits ()
void AddUnit (UnitWidgetScene@ uws)
UnitWidgetScene AddUnit (UnitScene@ scene)
void Load (WidgetLoadingContext &ctx) override
UnitWidgetScene AddUnit (string prodName, string scene)
void DoDraw (SpriteBatch &sb, vec2 pos) override
ref LoadUnitWidget (WidgetLoadingContext &ctx)
Variables
class UnitWidgetScene m_scenes
int m_timeOffset
array< array< vec4 > > m_multiColors
Function Documentation
AddUnit() [1/3]
void AddUnit (UnitWidgetScene@ uws)
Definition at line 31 of file UnitWidget.as.
References m_scenes.
Referenced by Load().
     {
         m_scenes.insertLast(uws);
     }
AddUnit() [2/3]
UnitWidgetScene AddUnit (UnitScene@ scene)
Definition at line 36 of file UnitWidget.as.
References UnitWidgetScene::m_scene, and m_scenes.
     {
         UnitWidgetScene@ uws = UnitWidgetScene();
         @uws.m_scene = scene;
         m_scenes.insertLast(uws);
         return uws;
     }
AddUnit() [3/3]
UnitWidgetScene AddUnit (string prodName, string scene)
Definition at line 55 of file UnitWidget.as.
References UnitWidgetScene::m_scene, and m_scenes.
     {
         if (prodName == "")
             return null;
         UnitProducer@ prod = Resources::GetUnitProducer(prodName);
         if (prod is null)
         {
             PrintError("Unit producer is null for \"" + prodName + "\"");
             return null;
         }
         UnitWidgetScene@ uws = UnitWidgetScene();
         @uws.m_scene = prod.GetUnitScene(scene);
         if (uws.m_scene is null)
         {
             PrintError("Scene is null for \"" + prodName + "\": \"" + scene + "\"");
             return null;
         }
         m_scenes.insertLast(uws);
         return uws;
     }
ClearUnits()
void ClearUnits ()
Definition at line 26 of file UnitWidget.as.
References m_scenes.
     {
         m_scenes.removeRange(0, m_scenes.length());
     }
Clone()
Widget Clone () override
Definition at line 19 of file UnitWidget.as.
References Widget::CloneInto(), and UnitWidget().
     {
         UnitWidget@ w = UnitWidget();
         CloneInto(w);
         return w;
     }
DoDraw()
void DoDraw (SpriteBatch & sb, vec2 pos) override
Definition at line 80 of file UnitWidget.as.
References g_menuTime, m_height, m_multiColors, UnitWidgetScene::m_offset, UnitWidgetScene::m_scene, m_scenes, m_timeOffset, and Skills::m_width.
     {
         for (uint i = 0; i < m_multiColors.length(); i++)
         {
             array<vec4> colors = m_multiColors[i];
             sb.SetMultiColor(i, colors[0], colors[1], colors[2]);
         }
         for (uint i = 0; i < m_scenes.length(); i++)
         {
             UnitWidgetScene@ uws = m_scenes[i];
             vec2 size = vec2(m_width, m_height);
             sb.DrawUnitScene(pos + size / 2 + uws.m_offset, size, uws.m_scene, g_menuTime - m_timeOffset);
         }
         if (m_multiColors.length() > 0)
             sb.DisableMultiColor();
     }
Load()
void Load (WidgetLoadingContext & ctx) override
Definition at line 44 of file UnitWidget.as.
References AddUnit(), g_menuTime, Widget::Load(), Widget::LoadWidthHeight(), and m_timeOffset.
     {
         AddUnit(ctx.GetString("unit", false), ctx.GetString("scene", false));
         m_timeOffset = g_menuTime;
         LoadWidthHeight(ctx);
         Widget::Load(ctx);
     }
LoadUnitWidget()
ref LoadUnitWidget (WidgetLoadingContext & ctx)
Definition at line 101 of file UnitWidget.as.
References UnitWidget().
Referenced by BaseGameMode::BaseGameMode().
 {
     UnitWidget@ w = UnitWidget();
     w.Load(ctx);
     return w;
 }
UnitWidget()
UnitWidget ()
Definition at line 14 of file UnitWidget.as.
Referenced by Clone(), and LoadUnitWidget().
     {
         super();
     }
Variable Documentation
m_multiColors
array<array<vec4> > m_multiColors
Definition at line 12 of file UnitWidget.as.
Referenced by DoDraw().
m_scenes
class UnitWidgetScene m_scenes
Referenced by AddUnit(), ClearUnits(), and DoDraw().
m_timeOffset
int m_timeOffset
Definition at line 10 of file UnitWidget.as.
Referenced by DoDraw(), and Load().