HoHDocs: scripts/GUI/SpriteWidget.as File Reference
SpriteWidget.as File Reference
Classes
class SpriteWidget
Functions
SpriteWidget Widget LoadSpriteWidget (WidgetLoadingContext &ctx)
SpriteWidget ()
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void SetSprite (string spriteName, bool resetTime=false)
void SetSprite (Sprite@ sprite, bool resetTime=false)
void SetSprite (ScriptSprite@ sprite, bool resetTime=false)
void SetTexture (Texture2D@ texture)
void DoDraw (SpriteBatch &sb, vec2 pos) override
void AnimateSet (string key, vec4 v) override
void AnimateSet (string key, Sprite@ s) override
Variables
Sprite m_spriteOrig
Sprite m_sprite
string m_spriteSrc
Texture2D m_spriteTexture
ScriptSprite m_ssprite
bool m_colorize
array< vec4 > m_colorizeColors = { vec4(0, 0, 0, 1), vec4(0.125, 0.125, 0.125, 1), vec4(0.25, 0.25, 0.25, 1) }
array< array< vec4 > > m_multiColors
vec4 m_color
GUIDef m_def
int m_timeOffset
bool m_autoSize
Function Documentation
AnimateSet() [1/2]
void LoadSpriteWidget::AnimateSet (string key, vec4 v) override
Definition at line 354 of file SpriteWidget.as.
AnimateSet() [2/2]
void LoadSpriteWidget::AnimateSet (string key, Sprite@ s) override
Definition at line 362 of file SpriteWidget.as.
Clone()
Widget LoadSpriteWidget::Clone () override
Definition at line 224 of file SpriteWidget.as.
DoDraw()
void LoadSpriteWidget::DoDraw (SpriteBatch & sb, vec2 pos) override
Definition at line 310 of file SpriteWidget.as.
Load()
void LoadSpriteWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 231 of file SpriteWidget.as.
LoadSpriteWidget()
SpriteWidget Widget LoadSpriteWidget (WidgetLoadingContext & ctx)
Definition at line 184 of file SpriteWidget.as.
References SpriteWidget::Load(), and SpriteWidget().
Referenced by BaseGameMode::BaseGameMode().
 {
     SpriteWidget@ w = SpriteWidget();
     w.Load(ctx);
     return w;
 }
SetSprite() [1/3]
void LoadSpriteWidget::SetSprite (string spriteName, bool resetTime = false)
Definition at line 251 of file SpriteWidget.as.
SetSprite() [2/3]
void LoadSpriteWidget::SetSprite (Sprite@ sprite, bool resetTime = false)
Definition at line 257 of file SpriteWidget.as.
SetSprite() [3/3]
void LoadSpriteWidget::SetSprite (ScriptSprite@ sprite, bool resetTime = false)
Definition at line 282 of file SpriteWidget.as.
SetTexture()
void LoadSpriteWidget::SetTexture (Texture2D@ texture)
Definition at line 305 of file SpriteWidget.as.
SpriteWidget()
LoadSpriteWidget::SpriteWidget ()
Definition at line 214 of file SpriteWidget.as.
Referenced by LoadSpriteWidget().
Variable Documentation
m_autoSize
bool m_autoSize
Definition at line 212 of file SpriteWidget.as.
m_color
vec4 m_color
Definition at line 206 of file SpriteWidget.as.
m_colorize
bool m_colorize
Definition at line 201 of file SpriteWidget.as.
m_colorizeColors
array<vec4> m_colorizeColors = { vec4(0, 0, 0, 1), vec4(0.125, 0.125, 0.125, 1), vec4(0.25, 0.25, 0.25, 1) }
Definition at line 202 of file SpriteWidget.as.
m_def
GUIDef m_def
Definition at line 208 of file SpriteWidget.as.
m_multiColors
array<array<vec4> > m_multiColors
Definition at line 204 of file SpriteWidget.as.
m_sprite
Sprite m_sprite
Definition at line 196 of file SpriteWidget.as.
m_spriteOrig
Sprite m_spriteOrig
Definition at line 195 of file SpriteWidget.as.
m_spriteSrc
string m_spriteSrc
Definition at line 197 of file SpriteWidget.as.
m_spriteTexture
Texture2D m_spriteTexture
Definition at line 198 of file SpriteWidget.as.
m_ssprite
ScriptSprite m_ssprite
Definition at line 199 of file SpriteWidget.as.
m_timeOffset
int m_timeOffset
Definition at line 210 of file SpriteWidget.as.