HoHDocs: scripts/GUI/Widgets/InventoryItemWidget.as File Reference
InventoryItemWidget.as File Reference
Classes
class InventoryItemWidget
Functions
InventoryItemWidget Widget LoadInventoryItemWidget (WidgetLoadingContext &ctx)
InventoryItemWidget ()
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void Set (PlayerRecord@ record, ActorItem@ item)
void DoDraw (SpriteBatch &sb, vec2 pos) override
Variables
PlayerRecord m_record
ActorItem m_item
Sprite m_spriteDot
Sprite m_spritePlus
vec4 m_colorItem
vec4 m_colorSet
bool m_hasBonus
bool m_isAttuned
Function Documentation
Clone()
Widget LoadInventoryItemWidget::Clone () override
Definition at line 135 of file InventoryItemWidget.as.
DoDraw()
void LoadInventoryItemWidget::DoDraw (SpriteBatch & sb, vec2 pos) override
Definition at line 181 of file InventoryItemWidget.as.
InventoryItemWidget()
LoadInventoryItemWidget::InventoryItemWidget ()
Definition at line 130 of file InventoryItemWidget.as.
Referenced by LoadInventoryItemWidget().
Load()
void LoadInventoryItemWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 142 of file InventoryItemWidget.as.
LoadInventoryItemWidget()
InventoryItemWidget Widget LoadInventoryItemWidget (WidgetLoadingContext & ctx)
Definition at line 92 of file InventoryItemWidget.as.
References InventoryItemWidget(), and InventoryItemWidget::Load().
Referenced by Campaign::Campaign().
 {
     InventoryItemWidget@ w = InventoryItemWidget();
     w.Load(ctx);
     return w;
 }
Set()
void LoadInventoryItemWidget::Set (PlayerRecord@ record, ActorItem@ item)
Definition at line 155 of file InventoryItemWidget.as.
Variable Documentation
m_colorItem
vec4 m_colorItem
Definition at line 124 of file InventoryItemWidget.as.
m_colorSet
vec4 m_colorSet
Definition at line 125 of file InventoryItemWidget.as.
m_hasBonus
bool m_hasBonus
Definition at line 127 of file InventoryItemWidget.as.
m_isAttuned
bool m_isAttuned
Definition at line 128 of file InventoryItemWidget.as.
m_item
ActorItem m_item
Definition at line 119 of file InventoryItemWidget.as.
m_record
PlayerRecord m_record
Definition at line 118 of file InventoryItemWidget.as.
m_spriteDot
Sprite m_spriteDot
Definition at line 121 of file InventoryItemWidget.as.
m_spritePlus
Sprite m_spritePlus
Definition at line 122 of file InventoryItemWidget.as.