HoHDocs: scripts/GUI/Widgets/FavorButtonWidget.as File Reference
FavorButtonWidget.as File Reference
Classes
class FavorButtonWidget
Functions
FavorButtonWidget ScalableSpriteButtonWidget LoadFavorButtonWidget (WidgetLoadingContext &ctx)
FavorButtonWidget ()
int opCmp (const Widget@ w) override
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void Set (Fountain::Effect@ effect, int shopLevel)
vec4 GetTextColor () override
array< Sprite@> GetSprites () override
void DoDraw (SpriteBatch &sb, vec2 pos) override
Variables
Fountain::Effect m_effect
BitmapString m_textPrice
bool m_lockedIn
array< Sprite@> m_spriteLockedIn
Sprite m_spriteFavorGood
Sprite m_spriteFavorBad
Function Documentation
Clone()
Widget LoadFavorButtonWidget::Clone () override
Definition at line 35 of file FavorButtonWidget.as.
     {
         m_textOffset = vec2(36, -1);
DoDraw()
void LoadFavorButtonWidget::DoDraw (SpriteBatch & sb, vec2 pos) override
Definition at line 117 of file FavorButtonWidget.as.
 {
     FavorButtonWidget@ w = FavorButtonWidget();
FavorButtonWidget()
LoadFavorButtonWidget::FavorButtonWidget ()
Definition at line 18 of file FavorButtonWidget.as.
References FavorButtonWidget::m_effect, and Fountain::Effect::m_favor.
Referenced by LoadFavorButtonWidget().
     {
         auto other = cast<FavorButtonWidget>(w);
GetSprites()
array<Sprite@> LoadFavorButtonWidget::GetSprites () override
Definition at line 109 of file FavorButtonWidget.as.
     {
         ScalableSpriteButtonWidget::DoDraw(sb, pos);
GetTextColor()
vec4 LoadFavorButtonWidget::GetTextColor () override
Definition at line 101 of file FavorButtonWidget.as.
     {
         if (m_lockedIn)
             return m_spriteLockedIn;
Load()
void LoadFavorButtonWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 42 of file FavorButtonWidget.as.
     {
         @m_effect = effect;
LoadFavorButtonWidget()
FavorButtonWidget ScalableSpriteButtonWidget LoadFavorButtonWidget (WidgetLoadingContext & ctx)
Definition at line 124 of file FavorButtonWidget.as.
References FavorButtonWidget(), and FavorButtonWidget::Load().
Referenced by Campaign::Campaign().
 {
     FavorButtonWidget@ w = FavorButtonWidget();
     w.Load(ctx);
     return w;
 }
opCmp()
int LoadFavorButtonWidget::opCmp (const Widget@ w) override
Definition at line 23 of file FavorButtonWidget.as.
     {
         FavorButtonWidget@ w = FavorButtonWidget();
         CloneInto(w);
Set()
void LoadFavorButtonWidget::Set (Fountain::Effect@ effect, int shopLevel)
Definition at line 63 of file FavorButtonWidget.as.
References effect, ScalableSpriteButtonWidget::m_font, and FavorButtonWidget::m_textPrice.
         {
             @m_textPrice = m_font.BuildText("+" + effect.m_favor);
             m_textPrice.SetColor(vec4(0, 1, 0, 1));
         }
         else
         {
             @m_textPrice = m_font.BuildText("" + effect.m_favor);
             m_textPrice.SetColor(vec4(1, 0, 0, 1));
         }
         m_enabled = (Network::IsServer() && Fountain::CurrentEffects.length() == 0 && shopLevel >= effect.m_level);
         m_lockedIn = Fountain::HasEffect(effect.m_idHash);
         string name = Resources::GetString(".fountain.effect." + effect.m_id + ".name");
         string desc = Resources::GetString(".fountain.effect." + effect.m_id + ".description");
         m_tooltipTitle = name;
         m_tooltipText = desc;
         if (shopLevel < effect.m_level)
             m_tooltipText += "\n\n" + Resources::GetString(".fountain.requiredlevel", { { "level", effect.m_level } });
         if (effect.m_favor > 0)
             AddTooltipSub(m_spriteFavorGood, "+" + effect.m_favor);
         else
             AddTooltipSub(m_spriteFavorBad, "" + effect.m_favor);
         SetText(name);
     }
     vec4 GetTextColor() override
     {
         if (m_lockedIn)
             return vec4(1, 1, 1, 1);
Variable Documentation
m_effect
Fountain::Effect m_effect
Definition at line 8 of file FavorButtonWidget.as.
m_lockedIn
bool m_lockedIn
Definition at line 12 of file FavorButtonWidget.as.
m_spriteFavorBad
Sprite m_spriteFavorBad
Definition at line 16 of file FavorButtonWidget.as.
m_spriteFavorGood
Sprite m_spriteFavorGood
Definition at line 15 of file FavorButtonWidget.as.
m_spriteLockedIn
array<Sprite@> m_spriteLockedIn
Definition at line 13 of file FavorButtonWidget.as.
m_textPrice
BitmapString m_textPrice
Definition at line 10 of file FavorButtonWidget.as.