HoHDocs: scripts/GUI/Widgets/UpgradeShopButtonWidget.as File Reference
UpgradeShopButtonWidget.as File Reference
Classes
class UpgradeShopButtonWidget
Functions
UpgradeShopButtonWidget ShopButtonWidget LoadUpgradeShopButtonWidget (WidgetLoadingContext &ctx)
UpgradeShopButtonWidget ()
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void Set (ShopMenuContent@ menuContent, Upgrades::Upgrade@ upgrade)
void Set (ShopMenuContent@ menuContent, Upgrades::Upgrade@ upgrade, Upgrades::UpgradeStep@ step)
void DrawIcon (SpriteBatch &sb, vec2 pos, vec4 color) override
Variables
ScriptSprite m_scriptSpriteIcon
Upgrades::Upgrade m_upgrade
Upgrades::UpgradeStep m_upgradeStep
Function Documentation
Clone()
Widget LoadUpgradeShopButtonWidget::Clone () override
Definition at line 360 of file UpgradeShopButtonWidget.as.
DrawIcon()
void LoadUpgradeShopButtonWidget::DrawIcon (SpriteBatch & sb, vec2 pos, vec4 color) override
Definition at line 434 of file UpgradeShopButtonWidget.as.
Load()
void LoadUpgradeShopButtonWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 367 of file UpgradeShopButtonWidget.as.
LoadUpgradeShopButtonWidget()
UpgradeShopButtonWidget ShopButtonWidget LoadUpgradeShopButtonWidget (WidgetLoadingContext & ctx)
Definition at line 107 of file UpgradeShopButtonWidget.as.
References UpgradeShopButtonWidget::Load(), and UpgradeShopButtonWidget().
Referenced by Campaign::Campaign().
 {
     UpgradeShopButtonWidget@ w = UpgradeShopButtonWidget();
     w.Load(ctx);
     return w;
 }
Set() [1/2]
void LoadUpgradeShopButtonWidget::Set (ShopMenuContent@ menuContent, Upgrades::Upgrade@ upgrade)
Definition at line 372 of file UpgradeShopButtonWidget.as.
Set() [2/2]
void LoadUpgradeShopButtonWidget::Set (ShopMenuContent@ menuContent, Upgrades::Upgrade@ upgrade, Upgrades::UpgradeStep@ step)
Definition at line 384 of file UpgradeShopButtonWidget.as.
UpgradeShopButtonWidget()
LoadUpgradeShopButtonWidget::UpgradeShopButtonWidget ()
Definition at line 355 of file UpgradeShopButtonWidget.as.
Referenced by LoadUpgradeShopButtonWidget().
Variable Documentation
m_scriptSpriteIcon
ScriptSprite m_scriptSpriteIcon
Definition at line 350 of file UpgradeShopButtonWidget.as.
m_upgrade
Upgrades::Upgrade m_upgrade
Definition at line 352 of file UpgradeShopButtonWidget.as.
m_upgradeStep
Upgrades::UpgradeStep m_upgradeStep
Definition at line 353 of file UpgradeShopButtonWidget.as.