HoHDocs: scripts/GUI/SpriteButtonWidget.as File Reference
SpriteButtonWidget.as File Reference
Classes
class SpriteButtonWidget
Functions
SpriteButtonWidget Widget LoadSpriteButtonWidget (WidgetLoadingContext &ctx)
SpriteButtonWidget ()
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void SetSpriteset (string spriteSet)
Sprite GetCurrentSprite ()
void DoDraw (SpriteBatch &sb, vec2 pos) override
bool OnClick (vec2 mousePos) override
void ShowTooltip () override
void OnMouseEnter (vec2 mousePos, bool forced) override
bool OnMouseDown (vec2 mousePos) override
bool OnMouseUp (vec2 mousePos) override
void OnMouseLeave (vec2 mousePos) override
Variables
GUIDef m_def
Sprite m_sprite
Sprite m_spriteHover
Sprite m_spriteDown
Sprite m_spriteDisabled
string m_func
string m_funcHover
string m_funcLeave
SoundEvent m_pressSound
SoundEvent m_selectSound
bool m_buttonDown
TextWidget m_wText
vec4 m_colorHoverText
bool m_enabled
Function Documentation
Clone()
Widget LoadSpriteButtonWidget::Clone () override
Definition at line 65 of file SpriteButtonWidget.as.
References Widget::m_height, SpriteButtonWidget::m_sprite, and Widget::m_width.
         {
             m_width = m_sprite.GetWidth();
             m_height = m_sprite.GetHeight();
DoDraw()
void LoadSpriteButtonWidget::DoDraw (SpriteBatch & sb, vec2 pos) override
Definition at line 136 of file SpriteButtonWidget.as.
                                              { m_buttonDown = true; return true; }
GetCurrentSprite()
Sprite LoadSpriteButtonWidget::GetCurrentSprite ()
Definition at line 120 of file SpriteButtonWidget.as.
     {
         Widget::OnMouseEnter(mousePos, forced);
         if (!m_enabled)
             return;
         PlaySound2D(m_selectSound);
         if (m_colorHoverText.w > 0)
         {
Load()
void LoadSpriteButtonWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 72 of file SpriteButtonWidget.as.
     {
         @m_sprite = m_def.GetSprite(spriteSet);
         @m_spriteHover = m_def.GetSprite(spriteSet + "-hover");
         @m_spriteDown = m_def.GetSprite(spriteSet + "-down");
         @m_spriteDisabled = m_def.GetSprite(spriteSet + "-disabled");
     }
     Sprite@ GetCurrentSprite()
     {
         if (!m_enabled && m_spriteDisabled !is null)
             return m_spriteDisabled;
         if (!m_hovering || !m_enabled)
             return m_sprite;
         else
         {
             if (!m_buttonDown)
                 return m_spriteHover;
             else
                 return m_spriteDown;
         }
     }
     void DoDraw(SpriteBatch& sb, vec2 pos) override
     {
         sb.DrawSprite(pos, GetCurrentSprite(), g_menuTime);
     }
     bool OnClick(vec2 mousePos) override
     {
         if (!m_enabled)
             return false;
         if (!m_buttonDown)
LoadSpriteButtonWidget()
SpriteButtonWidget Widget LoadSpriteButtonWidget (WidgetLoadingContext & ctx)
Definition at line 164 of file SpriteButtonWidget.as.
References SpriteButtonWidget::Load(), and SpriteButtonWidget().
Referenced by BaseGameMode::BaseGameMode().
 {
     SpriteButtonWidget@ w = SpriteButtonWidget();
     w.Load(ctx);
     return w;
 }
OnClick()
bool LoadSpriteButtonWidget::OnClick (vec2 mousePos) override
Definition at line 141 of file SpriteButtonWidget.as.
                                              { m_buttonDown = true; return true; }
     bool OnMouseUp(vec2 mousePos) override { m_buttonDown = false; return true; }
     void OnMouseLeave(vec2 mousePos) override
     {
         Widget::OnMouseLeave(mousePos);
         if (!m_enabled)
             return;
OnMouseDown()
bool LoadSpriteButtonWidget::OnMouseDown (vec2 mousePos) override
Definition at line 180 of file SpriteButtonWidget.as.
OnMouseEnter()
void LoadSpriteButtonWidget::OnMouseEnter (vec2 mousePos, bool forced) override
Definition at line 160 of file SpriteButtonWidget.as.
 {
     SpriteButtonWidget@ w = SpriteButtonWidget();
     w.Load(ctx);
     return w;
 }
OnMouseLeave()
void LoadSpriteButtonWidget::OnMouseLeave (vec2 mousePos) override
Definition at line 183 of file SpriteButtonWidget.as.
OnMouseUp()
bool LoadSpriteButtonWidget::OnMouseUp (vec2 mousePos) override
Definition at line 181 of file SpriteButtonWidget.as.
SetSpriteset()
void LoadSpriteButtonWidget::SetSpriteset (string spriteSet)
Definition at line 112 of file SpriteButtonWidget.as.
     {
ShowTooltip()
void LoadSpriteButtonWidget::ShowTooltip () override
Definition at line 154 of file SpriteButtonWidget.as.
 {
SpriteButtonWidget()
LoadSpriteButtonWidget::SpriteButtonWidget ()
Definition at line 60 of file SpriteButtonWidget.as.
Referenced by LoadSpriteButtonWidget().
                                                      :/ui/button_click");
         @m_selectSound = Resources::GetSoundEvent("event:/ui/button_hover");
         m_colorHoverText = ctx.GetColorRGBA("hovertext", false, vec4());
Variable Documentation
m_buttonDown
bool m_buttonDown
Definition at line 53 of file SpriteButtonWidget.as.
m_colorHoverText
vec4 m_colorHoverText
Definition at line 56 of file SpriteButtonWidget.as.
m_def
GUIDef m_def
Definition at line 39 of file SpriteButtonWidget.as.
m_enabled
bool m_enabled
Definition at line 58 of file SpriteButtonWidget.as.
m_func
string m_func
Definition at line 46 of file SpriteButtonWidget.as.
m_funcHover
string m_funcHover
Definition at line 47 of file SpriteButtonWidget.as.
m_funcLeave
string m_funcLeave
Definition at line 48 of file SpriteButtonWidget.as.
m_pressSound
SoundEvent m_pressSound
Definition at line 50 of file SpriteButtonWidget.as.
m_selectSound
SoundEvent m_selectSound
Definition at line 51 of file SpriteButtonWidget.as.
m_sprite
Sprite m_sprite
Definition at line 41 of file SpriteButtonWidget.as.
m_spriteDisabled
Sprite m_spriteDisabled
Definition at line 44 of file SpriteButtonWidget.as.
m_spriteDown
Sprite m_spriteDown
Definition at line 43 of file SpriteButtonWidget.as.
m_spriteHover
Sprite m_spriteHover
Definition at line 42 of file SpriteButtonWidget.as.
m_wText
TextWidget m_wText
Definition at line 55 of file SpriteButtonWidget.as.