HoHDocs: scripts/GUI/TextWidget.as File Reference
TextWidget.as File Reference
Classes
class TextWidget
Functions
TextWidget Widget LoadTextWidget (WidgetLoadingContext &ctx)
TextWidget ()
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void SetFont (string fnm)
void SetText (string str, int width, TextAlignment align=TextAlignment::Left, vec4 color=vec4(1, 1, 1, 1), bool force=false)
void SetText (string str, bool setColor=true, bool force=false)
void SetColor (vec4 color)
void DoDraw (SpriteBatch &sb, vec2 pos) override
void AnimateSet (string key, vec4 v) override
ref LoadSysTextWidget (WidgetLoadingContext &ctx)
void ModTextWidget (Widget@ w, string text)
Variables
BitmapFont m_font
string m_fontName
BitmapString m_text
string m_str = ""
bool m_upper = false
int m_textWidth = -1
TextAlignment m_alignment = TextAlignment::Left
vec4 m_color = vec4(1, 1, 1, 1)
vec4 m_colorOriginal
Function Documentation
AnimateSet()
void LoadTextWidget::AnimateSet (string key, vec4 v) override
Definition at line 716 of file TextWidget.as.
Clone()
Widget LoadTextWidget::Clone () override
Definition at line 603 of file TextWidget.as.
DoDraw()
void LoadTextWidget::DoDraw (SpriteBatch & sb, vec2 pos) override
Definition at line 708 of file TextWidget.as.
Load()
void LoadTextWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 610 of file TextWidget.as.
LoadSysTextWidget()
ref LoadSysTextWidget (WidgetLoadingContext & ctx)
Definition at line 150 of file TextWidget.as.
References TextWidget::Load(), TextWidget::m_font, and TextWidget().
Referenced by BaseGameMode::BaseGameMode().
 {
     TextWidget@ w = TextWidget();
     @w.m_font = Resources::GetBitmapFont("system/system_small.fnt");
     w.Load(ctx);
     return w;
 }
LoadTextWidget()
TextWidget Widget LoadTextWidget (WidgetLoadingContext & ctx)
Definition at line 143 of file TextWidget.as.
References TextWidget::Load(), and TextWidget().
Referenced by BaseGameMode::BaseGameMode().
 {
     TextWidget@ w = TextWidget();
     w.Load(ctx);
     return w;
 }
ModTextWidget()
void ModTextWidget (Widget@ w, string text)
Definition at line 158 of file TextWidget.as.
References text.
 {
     auto tw = cast<TextWidget>(w);
     if (tw !is null)
         tw.SetText(text);
 }
SetColor()
void LoadTextWidget::SetColor (vec4 color)
Definition at line 701 of file TextWidget.as.
SetFont()
void LoadTextWidget::SetFont (string fnm)
Definition at line 640 of file TextWidget.as.
SetText() [1/2]
void LoadTextWidget::SetText (string str, int width, TextAlignment align = TextAlignment::Left, vec4 color = vec4(1, 1, 1, 1), bool force = false)
Definition at line 652 of file TextWidget.as.
SetText() [2/2]
void LoadTextWidget::SetText (string str, bool setColor = true, bool force = false)
Definition at line 676 of file TextWidget.as.
TextWidget()
LoadTextWidget::TextWidget ()
Definition at line 595 of file TextWidget.as.
Referenced by LoadSysTextWidget(), and LoadTextWidget().
Variable Documentation
m_alignment
TextAlignment m_alignment = TextAlignment::Left
Definition at line 591 of file TextWidget.as.
m_color
vec4 m_color = vec4(1, 1, 1, 1)
Definition at line 592 of file TextWidget.as.
m_colorOriginal
vec4 m_colorOriginal
Definition at line 593 of file TextWidget.as.
m_font
BitmapFont m_font
Definition at line 584 of file TextWidget.as.
m_fontName
string m_fontName
Definition at line 585 of file TextWidget.as.
m_str
string m_str = ""
Definition at line 588 of file TextWidget.as.
m_text
BitmapString m_text
Definition at line 586 of file TextWidget.as.
m_textWidth
int m_textWidth = -1
Definition at line 590 of file TextWidget.as.
m_upper
bool m_upper = false
Definition at line 589 of file TextWidget.as.