HoHDocs: scripts/GUI/Widgets/ShopButtonWidget.as File Reference
ShopButtonWidget.as File Reference
Classes
class ShopButtonWidget
Functions
ShopButtonWidget ScalableSpriteButtonWidget LoadShopButtonWidget (WidgetLoadingContext &ctx)
ShopButtonWidget ()
void Load (WidgetLoadingContext &ctx) override
Widget Clone () override
int OwnedGold ()
int OwnedOre ()
void SetPriceGold (int amount)
void SetPriceOre (int amount)
void SetPriceSkillPoints (int amount)
void SetPrice (int amount)
void DrawIcon (SpriteBatch &sb, vec2 pos, vec4 color)
void UpdateEnabled ()
void DoDraw (SpriteBatch &sb, vec2 pos) override
Variables
Sprite m_spriteIconFrame
Sprite m_spriteIcon
Sprite m_itemDot
Sprite m_itemPlus
Sprite m_spriteGold
Sprite m_spriteOre
Sprite m_spriteSkillPoints
Sprite m_spriteCurrency
BitmapFont m_fontPrice
BitmapString m_textPrice
bool m_canAfford
bool m_shopRestricted
Function Documentation
Clone()
Widget LoadShopButtonWidget::Clone () override
Definition at line 281 of file ShopButtonWidget.as.
DoDraw()
void LoadShopButtonWidget::DoDraw (SpriteBatch & sb, vec2 pos) override
Definition at line 349 of file ShopButtonWidget.as.
DrawIcon()
void LoadShopButtonWidget::DrawIcon (SpriteBatch & sb, vec2 pos, vec4 color)
Definition at line 337 of file ShopButtonWidget.as.
Load()
void LoadShopButtonWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 258 of file ShopButtonWidget.as.
LoadShopButtonWidget()
ShopButtonWidget ScalableSpriteButtonWidget LoadShopButtonWidget (WidgetLoadingContext & ctx)
Definition at line 190 of file ShopButtonWidget.as.
References ShopButtonWidget::Load(), and ShopButtonWidget().
Referenced by Campaign::Campaign().
 {
     ShopButtonWidget@ w = ShopButtonWidget();
     w.Load(ctx);
     return w;
 }
OwnedGold()
int LoadShopButtonWidget::OwnedGold ()
Definition at line 288 of file ShopButtonWidget.as.
OwnedOre()
int LoadShopButtonWidget::OwnedOre ()
Definition at line 298 of file ShopButtonWidget.as.
SetPrice()
void LoadShopButtonWidget::SetPrice (int amount)
Definition at line 329 of file ShopButtonWidget.as.
SetPriceGold()
void LoadShopButtonWidget::SetPriceGold (int amount)
Definition at line 308 of file ShopButtonWidget.as.
SetPriceOre()
void LoadShopButtonWidget::SetPriceOre (int amount)
Definition at line 315 of file ShopButtonWidget.as.
SetPriceSkillPoints()
void LoadShopButtonWidget::SetPriceSkillPoints (int amount)
Definition at line 322 of file ShopButtonWidget.as.
ShopButtonWidget()
LoadShopButtonWidget::ShopButtonWidget ()
Definition at line 253 of file ShopButtonWidget.as.
Referenced by LoadShopButtonWidget().
UpdateEnabled()
void LoadShopButtonWidget::UpdateEnabled ()
Definition at line 344 of file ShopButtonWidget.as.
Variable Documentation
m_canAfford
bool m_canAfford
Definition at line 250 of file ShopButtonWidget.as.
m_fontPrice
BitmapFont m_fontPrice
Definition at line 247 of file ShopButtonWidget.as.
m_itemDot
Sprite m_itemDot
Definition at line 238 of file ShopButtonWidget.as.
m_itemPlus
Sprite m_itemPlus
Definition at line 239 of file ShopButtonWidget.as.
m_shopRestricted
bool m_shopRestricted
Definition at line 251 of file ShopButtonWidget.as.
m_spriteCurrency
Sprite m_spriteCurrency
Definition at line 245 of file ShopButtonWidget.as.
m_spriteGold
Sprite m_spriteGold
Definition at line 241 of file ShopButtonWidget.as.
m_spriteIcon
Sprite m_spriteIcon
Definition at line 237 of file ShopButtonWidget.as.
m_spriteIconFrame
Sprite m_spriteIconFrame
Definition at line 236 of file ShopButtonWidget.as.
m_spriteOre
Sprite m_spriteOre
Definition at line 242 of file ShopButtonWidget.as.
m_spriteSkillPoints
Sprite m_spriteSkillPoints
Definition at line 243 of file ShopButtonWidget.as.
m_textPrice
BitmapString m_textPrice
Definition at line 248 of file ShopButtonWidget.as.