HoHDocs: scripts/GUI/TextInputWidget.as File Reference
TextInputWidget.as File Reference
Classes
class TextInputWidget
Functions
TextInputWidget Widget LoadTextInputWidget (WidgetLoadingContext &ctx)
void Load (WidgetLoadingContext &ctx) override
void ClearText ()
bool UpdateInput (GameInput &input) override
void SetText (string str)
void UpdateText ()
vec2 GetTextOffset ()
void UpdateCursorPos ()
void DoDraw (SpriteBatch &sb, vec2 pos) override
Variables
BitmapFont m_font
BitmapString m_bitmapText
utf8string m_text
int m_cursorPos = 0
float m_drawOffset = 0
vec2 m_textOffset
int m_textLimit
vec2 m_caretPos
int m_caretHeight
string m_func
string m_funcEdit
string m_funcCancel
TextAlignment m_alignment = TextAlignment::Left
vec4 m_color
Function Documentation
ClearText()
void LoadTextInputWidget::ClearText ()
Definition at line 417 of file TextInputWidget.as.
DoDraw()
void LoadTextInputWidget::DoDraw (SpriteBatch & sb, vec2 pos) override
Definition at line 583 of file TextInputWidget.as.
GetTextOffset()
vec2 LoadTextInputWidget::GetTextOffset ()
Definition at line 546 of file TextInputWidget.as.
Load()
void LoadTextInputWidget::Load (WidgetLoadingContext & ctx) override
Definition at line 384 of file TextInputWidget.as.
LoadTextInputWidget()
TextInputWidget Widget LoadTextInputWidget (WidgetLoadingContext & ctx)
Definition at line 252 of file TextInputWidget.as.
References TextInputWidget::Load().
Referenced by BaseGameMode::BaseGameMode().
 {
     TextInputWidget@ w = TextInputWidget();
     w.Load(ctx);
     return w;
 }
SetText()
void LoadTextInputWidget::SetText (string str)
Definition at line 525 of file TextInputWidget.as.
UpdateCursorPos()
void LoadTextInputWidget::UpdateCursorPos ()
Definition at line 561 of file TextInputWidget.as.
UpdateInput()
bool LoadTextInputWidget::UpdateInput (GameInput & input) override
Definition at line 426 of file TextInputWidget.as.
Referenced by Menu::CreditsMenu::UpdateInput().
UpdateText()
void LoadTextInputWidget::UpdateText ()
Definition at line 534 of file TextInputWidget.as.
Variable Documentation
m_alignment
TextAlignment m_alignment = TextAlignment::Left
Definition at line 380 of file TextInputWidget.as.
m_bitmapText
BitmapString m_bitmapText
Definition at line 364 of file TextInputWidget.as.
m_caretHeight
int m_caretHeight
Definition at line 374 of file TextInputWidget.as.
m_caretPos
vec2 m_caretPos
Definition at line 373 of file TextInputWidget.as.
m_color
vec4 m_color
Definition at line 382 of file TextInputWidget.as.
m_cursorPos
int m_cursorPos = 0
Definition at line 367 of file TextInputWidget.as.
m_drawOffset
float m_drawOffset = 0
Definition at line 368 of file TextInputWidget.as.
m_font
BitmapFont m_font
Definition at line 363 of file TextInputWidget.as.
m_func
string m_func
Definition at line 376 of file TextInputWidget.as.
m_funcCancel
string m_funcCancel
Definition at line 378 of file TextInputWidget.as.
m_funcEdit
string m_funcEdit
Definition at line 377 of file TextInputWidget.as.
m_text
utf8string m_text
Definition at line 366 of file TextInputWidget.as.
m_textLimit
int m_textLimit
Definition at line 371 of file TextInputWidget.as.
m_textOffset
vec2 m_textOffset
Definition at line 370 of file TextInputWidget.as.