HoHDocs: scripts/main.as File Reference
main.as File Reference
Classes
class AttachedSound
Functions
void dbgArgs (vec2 spawnPos)
int NumConnectedPlayers ()
void AddGib (Gib gib)
void UpdateGibs (int ms)
GoreSpawner LoadGore (string path)
UnitPtr PlayEffect (string effect, UnitPtr unit)
UnitPtr PlayEffect (UnitScene@ effect, UnitPtr unit)
UnitPtr PlayEffect (string effect, vec2 pos)
UnitPtr PlayEffect (UnitScene@ effect, vec2 pos)
UnitPtr PlayEffect (string effect, vec3 pos)
UnitPtr PlayEffect (UnitScene@ effect, vec3 pos)
UnitPtr PlayEffect (string effect, vec2 pos, dictionary params)
UnitPtr PlayEffect (UnitScene@ effect, vec2 pos, dictionary params)
UnitPtr PlayEffect (string effect, vec2 pos, EffectParams@ params)
UnitPtr PlayEffect (UnitScene@ effect, vec2 pos, EffectParams@ params)
void PlaySound3D (SoundEvent@ snd, UnitPtr unit)
void PlaySound3D (SoundEvent@ snd, vec3 pos)
void PlaySound3D (SoundEvent@ snd, UnitPtr unit, dictionary params)
void PlaySound3D (SoundEvent@ snd, vec3 pos, dictionary params)
void PlaySound2D (SoundEvent@ snd)
GameInput GetInput ()
MenuInput GetMenuInput ()
vec2 GetGameModeMousePosition ()
Kind of an ugly function.. can we get rid of this?
HUD GetHUD ()
Player GetLocalPlayer ()
PlayerRecord GetLocalPlayerRecord ()
PlayerRecord GetPlayerRecordByPeer (uint8 peer)
void SetGamepadRumble (float strength, int length)
EffectParams LoadEffectParams (UnitPtr unit, SValue &params)
Variables
Scene g_scene
AGameMode g_gameMode
uint g_menuTime
UnitProducer g_effectUnit
BitmapFont g_floatTextFont
BitmapFont g_floatTextFontBig
float FloatingTextSpeed = 0.05
const string g_strGamepadA = "A"
const string g_strGamepadB = "B"
const string g_strGamepadX = "X"
const string g_strGamepadY = "Y"
const string g_strGamepadBack = "BACK"
const string g_strGamepadGuide = "GUIDE"
const string g_strGamepadStart = "START"
const string g_strGamepadLeftStick = "L3"
const string g_strGamepadRightStick = "R3"
const string g_strGamepadLeftTrigger = "LT"
const string g_strGamepadRightTrigger = "RT"
const string g_strGamepadLeftShoulder = "LB"
const string g_strGamepadRightShoulder = "RB"
const string g_strGamepadDpadUp = "UP"
const string g_strGamepadDpadDown = "DOWN"
const string g_strGamepadDpadLeft = "LEFT"
const string g_strGamepadDpadRight = "RIGHT"
float g_mpEnemyHealthScale
float g_mpExpScale
class AttachedSound effect
UnitPtr unit
array< IPreRenderable@> m_preRenderables
array< AttachedSound > m_attachedSounds
array< AttachedEffect > m_attachedEffects
array< WorldScript::LevelStart@> m_levelStarts
FlagBank g_flags
bool g_useSpawnPos
vec2 g_spawnPos
string g_startId
array< PlayerRecord@> g_players
array< Gib > m_gibs
int m_gibsSpawned
GoreSpawner m_safeGore
array< GoreSpawner@> m_goreSpawners
Function Documentation
AddGib()
void AddGib (Gib gib)
Definition at line 91 of file main.as.
References m_gibs, and m_gibsSpawned.
Referenced by ResolveGibs().
 {
     m_gibsSpawned++;
     m_gibs.insertLast(gib);
 }
dbgArgs()
void dbgArgs (vec2 spawnPos)
Definition at line 66 of file main.as.
References g_spawnPos, and g_useSpawnPos.
 {
     g_spawnPos = spawnPos;
     g_useSpawnPos = true;
 }
GetGameModeMousePosition()
vec2 GetGameModeMousePosition ()
Kind of an ugly function.. can we get rid of this?
Definition at line 360 of file main.as.
References g_gameMode, and BaseGameMode::GetMousePos().
Referenced by ScrollbarWidget::OnMouseDown(), OnMouseDown(), ScrollbarWidget::Update(), and Update().
 {
     BaseGameMode@ gm = cast<BaseGameMode>(g_gameMode);
     if (gm !is null)
         return gm.GetMousePos();
     return vec2();
 }
GetHUD()
HUD GetHUD ()
Definition at line 369 of file main.as.
References g_gameMode, and AGameMode::GetHUD().
Referenced by WorldScript::Door::Announce(), GiveLives::Apply(), WorldScript::HideAllSpeechBubbles::ClientExecute(), WorldScript::StopAnnounceText::ClientExecute(), WorldScript::WaypointAdd::ClientExecute(), WorldScript::AnnounceText::ClientExecute(), Modifiers::FlameShield::DamageTakenMul(), GameModeHandler::ExtraLives(), PlayerHusk::Initialize(), Player::OnDeath(), Player::OnLevelUp(), PlayerWaypoint::PlayerWaypoint(), PostLoad(), Skills::StackSkill::RefreshCount(), Skills::RefreshCount(), ScriptWaypoint::ScriptWaypoint(), WorldScript::ClearTopNumbers::ServerExecute(), WorldScript::HideTopNumber::ServerExecute(), WorldScript::SetTopNumber::ServerExecute(), WorldScript::BossBarCheckpoint::ServerExecute(), WorldScript::CreateBossBar::ServerExecute(), WorldScript::CountdownText::ServerExecute(), Player::Update(), and ActorBuffList::UpdateVisual().
 {
     return g_gameMode.GetHUD();
 }
GetInput()
GameInput GetInput ()
Definition at line 349 of file main.as.
References g_gameMode, and AGameMode::m_currInput.
Referenced by PlayerBase::RefreshScene(), SetGamepadRumble(), ShopMenu::Update(), and Player::Update().
 {
     return g_gameMode.m_currInput;
 }
GetLocalPlayer()
Player GetLocalPlayer ()
Definition at line 377 of file main.as.
References g_players.
Referenced by GiveGold::Apply(), GiveOre::Apply(), Attune(), FountainShopMenuContent::Buy(), ShopMenuContent::BuyItem(), ClearItemsCfunc(), Craft(), WaypointMarkersWidget::DoDraw(), HUD::DrawHoverItem(), Upgrades::RecordUpgradeStep::DrawShopIcon(), HUD::DrawUseIcon(), GiveArmorCFunc(), GiveBlueprintCFunc(), GiveComboCfunc(), GiveDrinkCFunc(), GiveDrinksCFunc(), GiveExperienceCFunc(), GiveHealthCFunc(), GiveItemCFunc(), GiveItemsCFunc(), GiveKeyCFunc(), GiveManaCFunc(), PlayerHandler::HealPlayer(), KillCFunc(), NetDamage(), NetSetTarget(), Door::NetUse(), PlayerHusk::OnDeath(), WorldScript::SoundEnvironmentArea::OnEnter(), WorldScript::SoundEnvironmentArea::OnExit(), WorldScript::StoreOre::OnFunc(), WorldScript::RandomBuff::OnFunc(), DrinksMenuContent::OnFunc(), OnFunc(), ChapelShopMenuContent::OnFunc(), SkillsShopMenuContent::OnFunc(), PlayerMenuMapTab::OnShow(), PlayerHandler::PlayerDamage(), PlayerHandler::PlayerShareExperience(), SkillsShopMenuContent::ReloadList(), TownhallMenuContent::ReloadList(), BaseGameMode::RenderFrame(), SetCharNgpCFunc(), SetNoClipCVar(), SetTarget(), PriestGroundCircle::Update(), Campaign::UpdateFrame(), and WinCash().
 {
     for (uint i = 0; i < g_players.length(); i++)
     {
         if (g_players[i].peer == 255)
             continue;
         if (g_players[i].local)
             return cast<Player>(g_players[i].actor);
     }
     return null;
 }
GetLocalPlayerRecord()
PlayerRecord GetLocalPlayerRecord ()
Definition at line 391 of file main.as.
References g_players.
Referenced by TownhallMenuContent::AddButton(), DungeonStoreMenuContent::AddItem(), AddItem(), DungeonStoreMenuContent::BuyItem(), ShopMenuContent::BuyItem(), TownhallMenuContent::BuyItem(), ChapelShopMenuContent::BuyItem(), CharacterCustomizationNPC::CharacterCustomizationNPC(), WorldScript::SetBossKilled::ClientExecute(), DebugHandler::DebugCompareKills(), FountainShopMenuContent::Deposit(), GameOver::DoShow(), IngameMouse::Draw(), HUD::DrawPlayerBars(), Upgrades::ItemUpgradeStep::DrawShopIcon(), DungeonLevelRichPresence(), BaseGameMode::GetCameraPos(), CharacterCustomizationBase::GetDyeChangeCost(), SkillsShopMenuContent::GetManaCost(), CharacterCustomizationBase::GetNameChangeCost(), CharacterCustomizationBase::GetPortraitChangeCost(), SkillsShopMenuContent::GetRespecCost(), GetRespecSkillPoints(), SkillsShopMenuContent::GetRespecSkillPoints(), Upgrades::ItemUpgradeStep::GetTooltipDescription(), BaseGameMode::GetVignette(), EndOfGame::Initialize(), CharacterCustomizationNPC::Initialize(), Initialize(), LootBox::Initialize(), Upgrades::ItemUpgradeStep::IsRestricted(), LevelupCFunc(), LoseCash(), CharacterCustomizationNPC::OnFunc(), EndOfBeta::OnFunc(), GeneralStoreMenuContent::OnFunc(), OnFunc(), ChapelShopMenuContent::OnFunc(), Campaign::OnRunEnd(), ShopButtonWidget::OwnedGold(), ShopButtonWidget::OwnedOre(), Upgrades::BuildingUpgradeStep::PayForUpgrade(), Upgrades::ItemUpgradeStep::PayScale(), PlayerHandler::PlayerDamaged(), PlayerHandler::PlayerDied(), RandomLevel::PostStart(), Campaign::PostStart(), Titles::ClassTitles::RefreshModifiers(), BaseGameMode::RefreshMultiplayerScaling(), DrinksMenuContent::ReloadList(), GeneralStoreMenuContent::ReloadList(), DungeonStoreMenuContent::ReloadList(), UpgradeShopMenuContent::ReloadList(), ReloadList(), ChapelShopMenuContent::ReloadList(), BaseGameMode::RenderFrame(), ReviveCFunc(), BaseGameMode::Save(), Campaign::SaveLocalTown(), WorldScript::SecretFound::ServerExecute(), UpgradeShopButtonWidget::Set(), ShopButtonWidget::SetPriceSkillPoints(), ChapelShopMenuContent::ShouldEnableButton(), PlayerMenuMapTab::ShouldShowFog(), StaticLevel::Start(), BossLevel::Start(), TestLevel::Start(), ShortcutLevel::Start(), Town::Start(), RandomLevel::Start(), Campaign::Start(), IngameMouse::Update(), DiscordPresence::Update(), Tutorial::Update(), LootBox::Update(), HUDCoop::Update(), HUD::Update(), CharacterCustomizationBase::UpdateCost(), Campaign::UpdateFrame(), IngameMouse::UpdateMouseColor(), Campaign::UpdateWidgets(), PlayerCorpse::Use(), and WinCash().
 {
     for (uint i = 0; i < g_players.length(); i++)
     {
         if (g_players[i].peer == 255)
             continue;
         if (g_players[i].local)
             return g_players[i];
     }
     return null;
 }
GetMenuInput()
MenuInput GetMenuInput ()
Definition at line 354 of file main.as.
References g_gameMode, and AGameMode::m_currInputMenu.
Referenced by PlayerMenuMapTab::Update(), Menu::IntroMenu::Update(), ScrollbarWidget::Update(), Update(), and Menu::CreditsMenu::UpdateInput().
 {
     return g_gameMode.m_currInputMenu;
 }
GetPlayerRecordByPeer()
PlayerRecord GetPlayerRecordByPeer (uint8 peer)
Definition at line 405 of file main.as.
References g_players.
Referenced by ScoreDialog::Set(), and Town::Start().
 {
     for (uint i = 0; i < g_players.length(); i++)
     {
         if (g_players[i].peer == 255)
             continue;
         if (g_players[i].peer == peer)
             return g_players[i];
     }
     return null;
 }
LoadEffectParams()
EffectParams LoadEffectParams (UnitPtr unit, SValue & params)
Definition at line 427 of file main.as.
References Float(), and unit.
Referenced by BombBehavior::BombBehavior(), BossEyeWisp::BossEyeWisp(), DangerAreaBehavior::DangerAreaBehavior(), DoodadEffect::DoodadEffect(), and DropSpawnBehavior::Initialize().
 {
     SValue@ dat = GetParamDictionary(unit, params, "effect-params", false);
     if (dat !is null && dat.GetType() == SValueType::Dictionary)
     {
         EffectParams@ effectParams = unit.CreateEffectParams();
         auto epKeys = dat.GetDictionary().getKeys();
         for (uint i = 0; i < epKeys.length(); i++)
         {
             auto d = dat.GetDictionaryEntry(epKeys[i]);
             if (d !is null && d.GetType() == SValueType::Float && effectParams !is null)
                 effectParams.Set(epKeys[i], d.GetFloat());
         }
         return effectParams;
     }
     return null;
 }
LoadGore()
GoreSpawner LoadGore (string path)
Definition at line 119 of file main.as.
References GoreSpawner(), m_goreSpawners, and m_path.
Referenced by BaseGameMode::BaseGameMode(), BombBehavior::BombBehavior(), Breakable::Breakable(), CompositeActorBehavior(), DelayedBreakable::DelayedBreakable(), EffectBehavior::Initialize(), WorldScript::SpawnGore::ServerExecute(), and SimpleBreakable::SimpleBreakable().
 {
     for (uint i = 0; i < m_goreSpawners.length(); i++)
         if (m_goreSpawners[i].m_path == path)
             return m_goreSpawners[i];
     SValue@ gore = Resources::GetSValue(path);
     if (gore is null)
         return null;
     GoreSpawner @ret = GoreSpawner(path, gore);
     m_goreSpawners.insertLast(@ret);
     return ret;
 }
NumConnectedPlayers()
int NumConnectedPlayers ()
Definition at line 75 of file main.as.
References g_players.
Referenced by MultiplePlayersTab::OnFunc(), and MultiplePlayersTab::OnShow().
 {
     int ret = 0;
     for (uint i = 0; i < g_players.length(); i++)
     {
         if (g_players[i].peer != 255)
             ret++;
     }
     return ret;
 }
PlayEffect() [1/10]
UnitPtr PlayEffect (string effect, UnitPtr unit)
Definition at line 142 of file main.as.
References effect, Fountain::GetEffect(), and unit.
Referenced by KillSameType::Apply(), Skills::CelestialOrb::BeamStart(), Player::BlockProjectile(), BlinkSkill::CastBlink(), Damage(), Player::Damage(), Player::DamagedActor(), SimpleBreakable::DamageEffects(), Breakable::DamageEffects(), Modifiers::FlameShield::DamageTakenMul(), SpawnEffect::Do(), SpawnTilesetEffect::Do(), Skills::ShootRay::DoActivate(), BossVampireMovement::DoCasting(), LifestealDamage::DoDamage(), Explode::DoExplosion(), Skills::DropEffect::DoExplosion(), MeleeHit::DoHit(), Skills::MeleeSwing::DoUpdate(), Skills::Charge::DoUpdate(), Skills::DoUpdate(), BossVampireMovement::DoWalkPaths(), DrawLightningBoltSegment(), Skills::HandleBeam(), Skills::MakeChain(), Skills::StackSkill::NetAddStack(), Skills::NetAddStack(), Skills::ShootRay::NetDoActivate(), PlayerCorpse::NetRevive(), Skills::StackSkill::NetTakeStack(), Skills::NetTakeStack(), Modifiers::TriggerEffect::NetTrigger(), TowerFlowerSkill::NetUseSkill(), BlinkSkill::NetUseSkill(), PlayerHusk::OnLevelUp(), Player::OnLevelUp(), Skills::Charge::PlayHitEffect(), WorldScript::SpawnUnitWithEffect::ProduceUnitEffects(), ResolveEffect(), WorldScript::PlayAttachedEffect::ServerExecute(), WorldScript::SpawnEffect::ServerExecute(), ShootHitscan(), ShootSpreadHitscan(), WorldScript::RefreshSpawnPickup::SpawnEffects(), WorldScript::SurvivalEnemySpawn::SpawnEffects(), WorldScript::SurvivalEnemyDropSpawn::SpawnEffects(), Skills::ChargeUnit::StartChargeEffect(), Skills::ChargeUnit::StartFullChargeEffect(), ActorFootsteps::StepEffect(), Modifiers::TriggerEffect::Trigger(), LurkerProjectile::Update(), EffectSpawner::Update(), Modifiers::FlameShield::Update(), MeleeSwing::Update(), Skills::StackSkill::Update(), and ActorBuff::Update().
 {
     UnitScene@ fx = Resources::GetEffect(effect);
     if (fx is null)
         return UnitPtr();
     return PlayEffect(fx, unit);
 }
PlayEffect() [2/10]
UnitPtr PlayEffect (UnitScene@ effect, UnitPtr unit)
Definition at line 151 of file main.as.
References effect, g_effectUnit, g_scene, m_attachedEffects, and unit.
 {
     if (effect is null)
         return UnitPtr();
     UnitPtr fxUnit = g_effectUnit.Produce(g_scene, unit.GetPosition());
     auto eb = cast<EffectBehavior>(fxUnit.GetScriptBehavior());
     eb.Initialize(effect);
     AttachedEffect aFx;
     @(aFx.effect) = eb;
     aFx.unit = unit;
     m_attachedEffects.insertLast(aFx);
     return fxUnit;
 }
PlayEffect() [3/10]
UnitPtr PlayEffect (string effect, vec2 pos)
Definition at line 168 of file main.as.
References effect, g_effectUnit, g_scene, and Fountain::GetEffect().
 {
     UnitScene@ fx = Resources::GetEffect(effect);
     if (fx is null)
         return UnitPtr();
     UnitPtr fxUnit = g_effectUnit.Produce(g_scene, vec3(pos.x, pos.y, 0));
     auto ret = cast<EffectBehavior>(fxUnit.GetScriptBehavior());
     ret.Initialize(fx);
     return fxUnit;
 }
PlayEffect() [4/10]
UnitPtr PlayEffect (UnitScene@ effect, vec2 pos)
Definition at line 180 of file main.as.
References effect, g_effectUnit, and g_scene.
 {
     if (effect is null)
         return UnitPtr();
     UnitPtr fxUnit = g_effectUnit.Produce(g_scene, vec3(pos.x, pos.y, 0));
     auto ret = cast<EffectBehavior>(fxUnit.GetScriptBehavior());
     ret.Initialize(effect);
     return fxUnit;
 }
PlayEffect() [5/10]
UnitPtr PlayEffect (string effect, vec3 pos)
Definition at line 191 of file main.as.
References effect, g_effectUnit, g_scene, and Fountain::GetEffect().
 {
     UnitScene@ fx = Resources::GetEffect(effect);
     if (fx is null)
         return UnitPtr();
     UnitPtr fxUnit = g_effectUnit.Produce(g_scene, pos);
     auto ret = cast<EffectBehavior>(fxUnit.GetScriptBehavior());
     ret.Initialize(fx);
     return fxUnit;
 }
PlayEffect() [6/10]
UnitPtr PlayEffect (UnitScene@ effect, vec3 pos)
Definition at line 203 of file main.as.
References effect, g_effectUnit, and g_scene.
 {
     if (effect is null)
         return UnitPtr();
     UnitPtr fxUnit = g_effectUnit.Produce(g_scene, pos);
     auto ret = cast<EffectBehavior>(fxUnit.GetScriptBehavior());
     ret.Initialize(effect);
     return fxUnit;
 }
PlayEffect() [7/10]
UnitPtr PlayEffect (string effect, vec2 pos, dictionary params)
Definition at line 214 of file main.as.
References effect, g_effectUnit, g_scene, and Fountain::GetEffect().
 {
     UnitScene@ fx = Resources::GetEffect(effect);
     if (fx is null)
         return UnitPtr();
     UnitPtr fxUnit = g_effectUnit.Produce(g_scene, vec3(pos.x, pos.y, 0));
     auto ret = cast<EffectBehavior>(fxUnit.GetScriptBehavior());
     ret.Initialize(fx, params);
     return fxUnit;
 }
PlayEffect() [8/10]
UnitPtr PlayEffect (UnitScene@ effect, vec2 pos, dictionary params)
Definition at line 226 of file main.as.
References effect, g_effectUnit, and g_scene.
 {
     if (effect is null)
         return UnitPtr();
     UnitPtr fxUnit = g_effectUnit.Produce(g_scene, vec3(pos.x, pos.y, 0));
     auto ret = cast<EffectBehavior>(fxUnit.GetScriptBehavior());
     ret.Initialize(effect, params);
     return fxUnit;
 }
PlayEffect() [9/10]
UnitPtr PlayEffect (string effect, vec2 pos, EffectParams@ params)
Definition at line 237 of file main.as.
References effect, g_effectUnit, g_scene, and Fountain::GetEffect().
 {
     UnitScene@ fx = Resources::GetEffect(effect);
     if (fx is null)
         return UnitPtr();
     UnitPtr fxUnit = g_effectUnit.Produce(g_scene, vec3(pos.x, pos.y, 0));
     auto ret = cast<EffectBehavior>(fxUnit.GetScriptBehavior());
     ret.Initialize(fx, params);
     return fxUnit;
 }
PlayEffect() [10/10]
UnitPtr PlayEffect (UnitScene@ effect, vec2 pos, EffectParams@ params)
Definition at line 249 of file main.as.
References effect, g_effectUnit, and g_scene.
 {
     if (effect is null)
         return UnitPtr();
     UnitPtr fxUnit = g_effectUnit.Produce(g_scene, vec3(pos.x, pos.y, 0));
     auto ret = cast<EffectBehavior>(fxUnit.GetScriptBehavior());
     ret.Initialize(effect, params);
     return fxUnit;
 }
PlaySound2D()
void PlaySound2D (SoundEvent@ snd)
Definition at line 337 of file main.as.
Referenced by WorldScript::Door::Announce(), FountainShopMenuContent::Buy(), ShopMenuContent::BuyItem(), WorldScript::AnnounceText::ClientExecute(), WorldScript::CountdownText::Done(), PlayerHusk::NetDamage(), MenuControlInputWidget::OnClick(), ButtonWidget::OnClick(), CheckBoxWidget::OnClick(), CheckBoxWidget::OnDoubleClick(), OnFunc(), SpriteButtonWidget::OnMouseEnter(), ButtonWidget::OnMouseEnter(), CheckBoxWidget::OnMouseEnter(), Play(), WorldScript::CountdownText::ServerExecute(), WorldScript::CountdownText::Update(), Notification::Update(), and Update().
 {
     if (snd is null)
         return;
     snd.Play();
 }
PlaySound3D() [1/4]
void PlaySound3D (SoundEvent@ snd, UnitPtr unit)
Definition at line 262 of file main.as.
References m_attachedSounds, AttachedSound::sound, AttachedSound::unit, and unit.
Referenced by MagicTile::ActivateNow(), ApplyArmor(), Player::BlockProjectile(), BlinkSkill::CastBlink(), Projectile::Collide(), Damage(), Player::Damage(), DelayedBreakable::DamageEffects(), SimpleBreakable::DamageEffects(), Breakable::DamageEffects(), TossProjectile::Destroyed(), Skills::ShootRay::DoActivate(), Skills::DoActivate(), BombBehavior::DoExplode(), MeleeHit::DoHit(), Skills::MeleeSwing::DoUpdate(), EndCollision(), NovaSkill::FireProjectiles(), GiveForgeBlueprintImpl(), GiveItemImpl(), CompositeActorSkill::HandleCastpoint(), SorcererOrbProjectile::HitUnit(), SorcererProjectile::HitUnit(), RangerProjectile::HitUnit(), RayProjectile::HitUnit(), CannonBall::HitUnit(), EffectBehavior::Initialize(), Projectile::Initialize(), RayProjectile::Initialize(), CompositeJammableActorBehavior::Jam(), JammableBehavior::Jam(), NetDamage(), Skills::ShootRay::NetDoActivate(), Skills::NetDoActivate(), BombBehavior::NetDoExplode(), NetSetTarget(), TowerFlowerSkill::NetUseSkill(), CompositeActorSkill::NetUseSkill(), WhirlNovaSkill::NetUseSkill(), BlinkSkill::NetUseSkill(), PlayerBase::OnDeath(), PlayerHusk::OnLevelUp(), Player::OnLevelUp(), SpeechBubble::OnShown(), BombBehavior::OnSpawn(), WorldScript::Door::OpenDoor(), Pickup::Picked(), Pickup::PickedLocalFeedback(), Skills::Charge::PlayHitEffect(), WorldScript::SpawnUnitWithEffect::ProduceUnitEffects(), SetTarget(), WorldScript::RefreshSpawnPickup::SpawnEffects(), WorldScript::SurvivalEnemySpawn::SpawnEffects(), WorldScript::SurvivalEnemyDropSpawn::SpawnEffects(), Player::SpendCost(), ActorFootsteps::StepSound(), SpewSkill::StopLoopingSound(), Trigger(), TriggerOnDeath(), CompositeJammableActorBehavior::Unjam(), JammableBehavior::Unjam(), CompositeActorBurstSkill::Update(), TripMine::Update(), BossVampire::Update(), MeleeSwing::Update(), WhirlNovaSkill::Update(), EnemyMeleeStrike::Update(), JumpStrike::Update(), SpewSkill::Update(), CompositeActorSkill::Update(), PlayerBase::Update(), Player::Update(), Door::Use(), and Chest::Use().
 {
     if (snd is null)
         return;
     SoundInstance@ si = snd.PlayTracked(unit.GetPosition());
     si.SetPaused(false);
     int l = si.GetLength();
     if (l > -1 && l <= 350)
         return;
     AttachedSound aSnd;
     @(aSnd.sound) = si;
     aSnd.unit = unit;
     m_attachedSounds.insertLast(aSnd);
 }
PlaySound3D() [2/4]
void PlaySound3D (SoundEvent@ snd, vec3 pos)
Definition at line 281 of file main.as.
 {
     if (snd is null)
         return;
     snd.Play(pos);
 }
PlaySound3D() [3/4]
void PlaySound3D (SoundEvent@ snd, UnitPtr unit, dictionary params)
Definition at line 290 of file main.as.
References m_attachedSounds, AttachedSound::sound, AttachedSound::unit, and unit.
 {
     if (snd is null)
         return;
     SoundInstance@ si = snd.PlayTracked(unit.GetPosition());
     auto keys = params.getKeys();
     for (uint i = 0; i < keys.length(); i++)
     {
         float val;
         params.get(keys[i], val);
         si.SetParameter(keys[i], val);
     }
     si.SetPaused(false);
     int l = si.GetLength();
     if (l > -1 && l <= 350)
         return;
     AttachedSound aSnd;
     @(aSnd.sound) = si;
     aSnd.unit = unit;
     m_attachedSounds.insertLast(aSnd);
 }
PlaySound3D() [4/4]
void PlaySound3D (SoundEvent@ snd, vec3 pos, dictionary params)
Definition at line 318 of file main.as.
 {
     if (snd is null)
         return;
     SoundInstance@ si = snd.PlayTracked(pos);
     auto keys = params.getKeys();
     for (uint i = 0; i < keys.length(); i++)
     {
         float val;
         params.get(keys[i], val);
         si.SetParameter(keys[i], val);
     }
     si.SetPaused(false);
 }
SetGamepadRumble()
void SetGamepadRumble (float strength, int length)
Definition at line 418 of file main.as.
References GetInput(), and RumbleGamepad().
Referenced by ScreenShake::Update().
 {
     auto input = GetInput();
     if (input is null || !input.UsingGamepad)
         return;
     RumbleGamepad(strength, length);
 }
UpdateGibs()
void UpdateGibs (int ms)
Definition at line 97 of file main.as.
References m_gibs, m_gibsSpawned, and Update().
Referenced by BaseGameMode::UpdateFrame().
 {
 %PROFILE_START Gibs
     m_gibsSpawned = 0;
     for (uint i = 0; i < m_gibs.length();)
     {
         if (m_gibs[i].Update(ms))
         {
             m_gibs[i].unit.SetPositionZ(0);
             m_gibs.removeAt(i);
         }
         else
             i++;
     }
 %PROFILE_STOP
 }
Variable Documentation
effect
class AttachedSound effect
Referenced by PlayEffect().
FloatingTextSpeed
float FloatingTextSpeed = 0.05
Definition at line 14 of file main.as.
Referenced by Draw(), and Update().
g_effectUnit
UnitProducer g_effectUnit
Definition at line 10 of file main.as.
Referenced by ActorBuff::Attach(), BaseGameMode::BaseGameMode(), PingBehavior::PingBehavior(), and PlayEffect().
g_flags
FlagBank g_flags
Definition at line 57 of file main.as.
Referenced by TownhallMenuContent::AddButton(), Town::CheckForAchievements(), SetFlag::Do(), GameOver::FindPossibleSentences(), RandomLevel::Generate(), MinesGenerator::Generate(), Player::KilledActor(), ListFlagsCFunc(), TownRecord::Load(), MakeDungeonGenerator(), BossVampire::OnNodeArrived(), BossVampireMovement::OnNodeArrived(), Campaign::OnRunEnd(), WorldScript::Door::OpenDoor(), TownRecord::Save(), BaseGameMode::Save(), WorldScript::SetFlag::ServerExecute(), WorldScript::PrefabPicker::ServerExecute(), WorldScript::CheckFlag::ServerExecute(), UpgradeShopButtonWidget::Set(), SetFlagCFunc(), SetLevelFlags(), BossVampireMovement::SetTargetNode(), RandomLootManager::SpawnForgeBlueprint(), Town::Start(), Campaign::Start(), BaseGameMode::Start(), GameModeHandler::SyncFlag(), ActorItems::TakeRandomItem(), FlagWidget::Update(), HUD::Update(), and Player::Update().
g_floatTextFont
BitmapFont g_floatTextFont
Definition at line 11 of file main.as.
Referenced by BaseGameMode::BaseGameMode(), and FloatingText().
g_floatTextFontBig
BitmapFont g_floatTextFontBig
Definition at line 12 of file main.as.
Referenced by BaseGameMode::BaseGameMode(), and FloatingText().
g_gameMode
AGameMode g_gameMode
Definition at line 6 of file main.as.
Referenced by Stats::Add(), Stats::AddAvg(), GuildHallAccomplishmentsTab::AddBoss(), TownhallMenuContent::AddButton(), AddCurrentSplit(), AddFloatingText(), GuildHallStatsTab::AddGuildToList(), Player::AddItem(), MenuTabSystem::AddTab(), PlayerMenuMapTab::AfterUpdate(), GiveLives::Apply(), Apply(), Upgrades::OreTraderUpgradeStep::ApplyNow(), PlayerHandler::AttemptRespawn(), BaseGameMode::BaseGameMode(), Menu::InGameChat::BeginInput(), FountainShopMenuContent::Buy(), Upgrades::BuildingUpgradeStep::BuyNow(), CalcLevel(), Upgrades::UpgradeStep::CanAfford(), FountainShopMenuContent::CanAfford(), GiveLives::CanApply(), WorldScript::SetBossKilled::ClientExecute(), WorldScript::AddNotification::ClientExecute(), WorldScript::AddScreenShake::ClientExecute(), WorldScript::SurvivalWave::ClientExecute(), UserWindow::Close(), Menu::GameLanguagesMenu::Close(), Menu::Menu::Close(), StatueSelectMenu::Close(), DialogWindow::Close(), Menu::Close(), Menu::SlotsMenu::Close(), UserWindow::CloseTooltip(), CvarDebugHandicap(), CvarExtraPlayers(), CvarHardwareCursor(), CvarPlayerNamesChanged(), Modifiers::Block::DamageBlock(), Widget::DebugDraw(), FountainShopMenuContent::Deposit(), GameModeHandler::DepositFountain(), Menu::SplitscreenPlayer::DisplayName(), ScreenShaker::DoAction(), WaypointMarkersWidget::DoDraw(), TextInputWidget::DoDraw(), TransformWidget::DoLayout(), DoLayout(), Menu::DoLayout(), GameOver::DoShow(), OverheadBossBar::Draw(), WidgetInspector::Draw(), MenuMouse::Draw(), IngameMouse::Draw(), Draw(), SpeechBubble::Draw(), PlayerMenuMapTab::Draw(), MouseBase::Draw(), HUD::DrawHoverItem(), BaseGameMode::DrawMouse(), HUD::DrawPlayerBar(), HUD::DrawPlayerBars(), MouseBase::DrawTooltip(), HUD::DrawUseIcon(), GameModeHandler::ExtraLives(), FilterAction(), Menu::HwrMenu::FinishContext(), DialogWindow::FocusInput(), GameModeHandler::GameOver(), GenerateDungeon(), PlayerWaypoint::GetColor(), MenuMouse::GetCursor(), MouseBase::GetCursor(), Crowd::TimeAction::GetDelta(), GameModeHandler::GetFountainMenu(), GetGameModeMousePosition(), GetHUD(), GetInput(), Upgrades::DungeonShop::GetItemCategory(), GetLevelName(), GetMenuInput(), Upgrades::BuildingUpgrade::GetNextStep(), TownRecord::GetNextTitle(), Statues::GetPlacedLevel(), Waypoint::GetScreenPosition(), ScriptWaypoint::GetScreenPosition(), TownRecord::GetTitle(), CharacterCustomizationBase::GetTown(), GiveAllDyesCFunc(), GiveForgeBlueprintImpl(), GiveGoldCFunc(), GiveItemImpl(), GiveOreCFunc(), WorldScript::ShowSpeechBubble::HideAll(), WorldScript::ShowSpeechBubble::HideBubble(), StatisticsInterface::Initialize(), EndOfBeta::Initialize(), EndOfGame::Initialize(), Menu::InGameChat::Initialize(), SurvivalEnemySpawnPoint::Initialize(), Menu::HostMenu::Initialize(), Menu::CharacterCreationMenu::IsBuildingLevel(), ScalableSpriteButtonWidget::IsEnabled(), Upgrades::BuildingUpgradeStep::IsOwned(), Player::KilledActor(), LoseCash(), MakeDungeonGenerator(), PlayerWaypoint::MakeNameText(), Stats::Max(), Miniboss::NetDamage(), FountainShopMenuContent::NetDeposit(), ScreenShaker::NetDoAction(), NetGiveGoldImpl(), PlayerCorpse::NetRevive(), RandomLootManager::NetSpawnDrinkBarrel(), RandomLootManager::NetSpawnDyeBucket(), RandomLootManager::NetSpawnItemBlueprint(), MenuControlInputWidget::OnClick(), ShopMenuContent::OnClose(), PlayerMenuCharacterTab::OnCreated(), PlayerBase::OnDeath(), Player::OnDeath(), HWRGameOver::OnFunc(), CharacterCustomizationNPC::OnFunc(), Menu::SingleplayerMenu::OnFunc(), Menu::ControlsMenu::OnFunc(), EndOfGame::OnFunc(), DungeonSettingsMenu::OnFunc(), Menu::OnFunc(), WorldScript::StoreOre::OnFunc(), GeneralStoreMenuContent::OnFunc(), WorldScript::RandomBuff::OnFunc(), StatueSelectMenu::OnFunc(), Menu::HostMenu::OnFunc(), Menu::ControlMapMenu::OnFunc(), Menu::FrontMenu::OnFunc(), StatuesShopMenuContent::OnFunc(), Menu::InGameChat::OnFunc(), DrinksMenuContent::OnFunc(), Menu::SubOptionsMenu::OnFunc(), Menu::CharacterSelectionMenu::OnFunc(), Menu::LobbyPlayersMenu::OnFunc(), OnFunc(), Menu::SlotsMenu::OnFunc(), ChapelShopMenuContent::OnFunc(), GameOver::OnFunc(), SkillsShopMenuContent::OnFunc(), Stats::Accomplishment::OnLoadFinished(), ScrollbarWidget::OnMouseDown(), OnMouseDown(), Widget::OnMouseLeave(), TownRecord::OnNewTitle(), Player::OnNewTitle(), PlayerMenuCharacterTab::OnShow(), GuildHallBeastiaryTab::OnShow(), Stats::Accomplishment::OnUpdated(), Menu::Menu::OpenMenu(), ShopButtonWidget::OwnedGold(), ShopButtonWidget::OwnedOre(), Crowd::Pause(), Upgrades::BuildingUpgradeStep::PayForUpgrade(), Upgrades::UpgradeStep::PayForUpgrade(), LootBox::Play(), GameChatWidget::PlayerChat(), PlayerHandler::PlayerDied(), PlayerHandler::PlayerPing(), StatuesShopMenuContent::RefreshBuyList(), Skills::StackSkill::RefreshCount(), Skills::RefreshCount(), GuildHallAccomplishmentsTab::RefreshList(), StatuesShopMenuContent::RefreshPlacementList(), PlayerBase::RefreshScene(), DrinksMenuContent::ReloadList(), GeneralStoreMenuContent::ReloadList(), ReloadList(), SkillsShopMenuContent::ReloadList(), MenuProvider::Render(), MainMenu::RenderFrame(), ResolveGibs(), WorldScript::SecretFound::ServerExecute(), WorldScript::StartDungeon::ServerExecute(), WorldScript::LevelExitNextAct::ServerExecute(), WorldScript::LevelExitNext::ServerExecute(), WorldScript::SpawnEnemyGroup::ServerExecute(), WorldScript::ExploreMinimap::ServerExecute(), WorldScript::LogText::ServerExecute(), WorldScript::BossBarCheckpoint::ServerExecute(), WorldScript::CreateBossBar::ServerExecute(), WorldScript::CheckCrowdValue::ServerExecute(), WorldScript::TownBuildingLevel::ServerExecute(), WorldScript::CheckNewGamePlus::ServerExecute(), WorldScript::SurvivalEnemySpawn::ServerExecute(), WorldScript::SurvivalEnemyDropSpawn::ServerExecute(), Upgrades::ItemUpgrade::Set(), ScoreDialog::Set(), Menu::Menu::SetActive(), SetCharNgpCFunc(), ScalableSpriteButtonWidget::SetHovering(), Widget::SetHovering(), SetLimitButtons(), MainMenu::SetMenuState(), SetUIScaleCVar(), MenuMouse::ShouldRenderName(), Waypoint::ShouldShow(), PlayerWaypoint::ShouldShow(), UserWindow::Show(), StatueSelectMenu::Show(), ShopMenu::Show(), WorldScript::ShowSpeechBubble::ShowBubble(), HUD::ShowBuffIcon(), Menu::ShowLoadFailedDialog(), Widget::ShowTooltip(), RandomLootManager::SpawnLoot(), PlayerHandler::SpawnPlayer(), PlayerHandler::SpawnPlayerCorpse(), WorldScript::OpenInterface::Start(), Campaign::Start(), HUD::Start(), WorldScript::OpenInterface::Stop(), Menu::InGameChat::StopInput(), Crowd::TimeReset(), Crowd::Trigger(), Modifiers::TriggerEffect::TriggerEffects(), Widget::Unfocus(), DiscordPresence::Update(), WidgetInspector::Update(), HUDSurvival::Update(), Menu::GraphicsMenu::Update(), HUDSpectate::Update(), Miniboss::Update(), MouseBase::Update(), PlayerMenuCharacterTab::Update(), PlayerMenuMapTab::Update(), MenuTabSystem::Update(), Menu::Update(), Menu::InGameChat::Update(), ScrollbarWidget::Update(), HUD::Update(), Update(), Player::Update(), PlayerBase::UpdateColors(), CharacterCustomizationBase::UpdateCost(), Campaign::UpdateFrame(), PlayerMenuCharacterTab::UpdateFromRecord(), TextInputWidget::UpdateInput(), LootBox::UpdateInterface(), FountainShopMenuContent::UpdateInterface(), IngameMouse::UpdateMouseColor(), DungeonSettingsMenu::UpdateNgp(), Menu::HostMenu::UpdateNgp(), Upgrades::BuildingUpgradeStep::UpgradeBulding(), WorldScript::StoreOre::Use(), WorldScript::RandomBuff::Use(), and WinCash().
g_menuTime
uint g_menuTime
Definition at line 7 of file main.as.
Referenced by ScalableSpriteIconButtonWidget::DoDraw(), TopNumberIconWidget::DoDraw(), InventoryItemWidget::DoDraw(), BuffWidget::DoDraw(), ScrollableWidget::DoDraw(), DoDraw(), SpriteButtonWidget::DoDraw(), ShopButtonWidget::DoDraw(), SpriteWidget::DoDraw(), DetailsWidget::DoDraw(), ScalableSpriteButtonWidget::DoDraw(), CheckBoxWidget::DoDraw(), Waypoint::Draw(), SpeechBubble::Draw(), PlayerWaypoint::Draw(), Draw(), DrawAll(), DrawHorizontal(), UpgradeShopButtonWidget::DrawIcon(), ShopButtonWidget::DrawIcon(), Upgrades::RecordUpgradeStep::DrawShopIcon(), Upgrades::ItemUpgradeStep::DrawShopIcon(), HUD::DrawUseIcon(), DrawVertical(), Load(), SpriteWidget::SetSprite(), FlagWidget::Update(), and BaseGameMode::UpdateWidgets().
g_mpEnemyHealthScale
float g_mpEnemyHealthScale
Definition at line 34 of file main.as.
Referenced by CompositeActorBehaviorNoNGPScale::GetMaxHp(), GetMaxHp(), BaseGameMode::RefreshMultiplayerScaling(), and Breakable::TransformDmg().
g_mpExpScale
float g_mpExpScale
Definition at line 35 of file main.as.
Referenced by Player::KilledActor(), Player::NetShareExperience(), and BaseGameMode::RefreshMultiplayerScaling().
g_players
array<PlayerRecord@> g_players
Definition at line 73 of file main.as.
Referenced by BaseGameMode::ActivatePlayerRecord(), BaseGameMode::AddPlayer(), BaseGameMode::AttemptRespawn(), ScoreDialog::BuildData(), Campaign::CheckGameOver(), WorldScript::UnlinkSouls::ClientExecute(), MagicTile::ClosestPlayer(), CondPlayersGreater(), CvarPlayerNamesChanged(), BossEye::FindWispTargets(), BaseGameMode::GetCameraPos(), Crowd::HealthAction::GetDelta(), GetLocalPlayer(), GetLocalPlayerRecord(), PlayerHandler::GetPlayer(), PlayerHandler::GetPlayerIndex(), PlayerHandler::GetPlayerRecord(), GetPlayerRecordByPeer(), BaseGameMode::GetPlayersAlive(), BaseGameMode::GetVignette(), WorldScript::AllPlayersAreaTrigger::IsEveryoneInside(), PlayerCorpse::NetRevive(), NumConnectedPlayers(), PlayerHandler::PlayerDamage(), BaseGameMode::RefreshMultiplayerScaling(), BaseGameMode::RenderFrame(), Town::Save(), BaseGameMode::Save(), WorldScript::GiveExperience::ServerExecute(), WorldScript::CheckPlayerCount::ServerExecute(), WorldScript::SurvivalEnemySpawn::ServerExecute(), WorldScript::SurvivalEnemyDropSpawn::ServerExecute(), HUDCoop::ShouldShow(), HUD::ShowBuffIcon(), BaseGameMode::SpawnPlayer(), BaseGameMode::SpawnPlayerCorpse(), BaseGameMode::SpawnPlayers(), BaseGameMode::SpectateNextPlayer(), BaseGameMode::SpectateUpdateHUD(), BossLevel::Start(), PlayerHandler::TakeFreeLife(), HUDSpectate::Update(), SafetyAreaBehavior::Update(), BoltShooter::Update(), DangerAreaBehavior::Update(), HUDCoop::Update(), HUD::Update(), Campaign::UpdateFrame(), BaseGameMode::UpdateFrame(), MultiplePlayersTab::UpdateFromLocal(), MultiplePlayersTab::UpdateNow(), and Campaign::UpdateWidgets().
g_scene
Scene g_scene
Testing Still Testing WTF
Definition at line 5 of file main.as.
Referenced by ActorBuffIcon::ActorBuffIcon(), BossEye::AddWisps(), PlayerMenuMapTab::AfterUpdate(), ShootRandomEnemy::Apply(), KillSameType::Apply(), ShootProjectile::Apply(), ActorBuff::Attach(), BaseGameMode::BaseGameMode(), NovaSkill::CanSee(), WhirlwindSkill::CanSee(), BlinkSkill::CanSee(), JumpStrike::CanSee(), SpewSkill::CanSee(), CompositeActorSkill::CanSee(), WorldScript::UseTrigger::CanUse(), BlinkSkill::CastBlink(), Campaign::CheckGameOver(), WorldScript::PotionRefill::ClientExecute(), WorldScript::DestroyUnitChance::ClientExecute(), WorldScript::DestroyUnitCount::ClientExecute(), WorldScript::SurvivalEnemySpawn::ClientExecute(), WorldScript::SurvivalEnemyDropSpawn::ClientExecute(), Player::Collide(), Damage(), DelayedBreakable::DamageEffects(), Breakable::DamageEffects(), SpawnTilesetEffect::Do(), ActionEffectWrapper::DoAction(), RaiseMagicTiles::DoAction(), DoAction(), MeleeHit::DoAction(), ShootProjectile::DoAction(), Skills::ShootRay::DoActivate(), Skills::DoActivate(), Skills::DoBeamRay(), Explode::DoExplosion(), Skills::DropEffect::DoExplosion(), Skills::Explode::DoExplosion(), MeleeHit::DoHit(), Nova::DoNova(), Skills::ShootProjectile::DoShoot(), Skills::ChargeUnit::DoShoot(), WorldScript::SpawnItem::DoSpawn(), DoSpawnPrefabBase(), SpawnPrefab::DoSpawnPrefabs(), DoSpawnUnit(), SpawnUnitBaseHandler::DoSpawnUnitBase(), DoSpawnUnits(), Skills::SpawnUnit::DoSpawnUnits(), WorldScript::ProjectileSpewer::DoSpewProjectile(), Skills::TempBuffAoe::DoUpdate(), Skills::Whirlnova::DoUpdate(), Skills::BuffAoe::DoUpdate(), Skills::MeleeSwing::DoUpdate(), Skills::Charge::DoUpdate(), Skills::DoUpdate(), BossLichMovement::DoWalkPaths(), SpawnPrefabBaseTask::Execute(), SurvivalWaveProgress::ExecuteFeed(), TargetMovement::FindTarget(), NovaSkill::FireProjectiles(), PathFollower::FollowPathPathfind(), GenerateDungeon(), UnitHandler::GetActor(), BossLich::GetCastDirection(), BossVampire::GetCastDirection(), Explode::GetFxName(), WorldScript::Teleport::GetPosition(), WorldScript::StoreOre::GetUseUnit(), WorldScript::RandomBuff::GetUseUnit(), WorldScript::UseTrigger::GetUseUnit(), WorldScript::Well::GetUseUnit(), WorldScript::Door::GetUseUnit(), BaseGameMode::GetVignette(), SorcererProjectile::HitUnit(), CannonBall::HitUnit(), WorldScript::ProjectileSpewer::Initialize(), RayProjectile::Initialize(), CannonBall::Initialize(), RangedMovement::IsStandPosValid(), KillAllCFunc(), ListEnemiesCFunc(), Skills::StaggeredSpawnUnits::LocalSpawnUnit(), Skills::SpawnUnit::LocalSpawnUnit(), RangerProjectile::Multiply(), BossEye::NetAddWisps(), Nova::NetDoAction(), RaiseMagicTiles::NetDoAction(), ShootProjectile::NetDoAction(), NetDoAction(), Skills::ShootProjectile::NetDoActivate(), Skills::SpewProjectiles::NetHold(), RandomLootManager::NetSpawnDrinkBarrel(), RandomLootManager::NetSpawnDyeBucket(), RandomLootManager::NetSpawnItemBlueprint(), LootDef::NetSpawnLoot(), BossScatterBurstSkill::NetUseSkill(), TowerFlowerSkill::NetUseSkill(), BossScatterBurstSkill::NewBurstShot(), Skills::Juggernaut::OnCollide(), PlayerBase::OnDeath(), WorldScript::DropPod::OnDropped(), WorldScript::Teleport::OnEnabledChanged(), AreaTrigger::OnEnabledChanged(), WorldScript::Teleport::OnEnter(), WorldScript::AllPlayersAreaTrigger::OnEnter(), AreaTrigger::OnEnter(), WorldScript::AllPlayersAreaTrigger::OnExit(), AreaTrigger::OnExit(), BossVampireMovement::OnNodeArrived(), PingBehavior::PingBehavior(), PlayEffect(), PlayerHandler::PlayerPing(), TransferDamageActor::PostLoad(), DropSpawnBehavior::PostLoad(), BombBehavior::PostLoad(), DangerAreaBehavior::PostLoad(), BossVampireMovement::PostLoad(), AttachedUnit::PostLoad(), BoltShooter::PostLoad(), BossEyeWisp::PostLoad(), PostLoad(), WorldScript::Wind::PostUpdate(), Campaign::PreRenderFrame(), HwShootProjectile::ProduceProjectile(), WorldScript::ProjectileShooter::ProduceProjectile(), ShootProjectile::ProduceProjectile(), Skills::ShootProjectile::ProduceProjectile(), Skills::SpewProjectiles::ProduceProjectile(), WorldScript::AttachNewUnit::ProduceUnit(), WorldScript::RefreshSpawnPickup::ProduceUnit(), WorldScript::SurvivalEnemySpawn::ProduceUnit(), WorldScript::SpawnDropUnit::ProduceUnit(), WorldScript::DropPod::ProduceUnit(), WorldScript::SurvivalEnemyDropSpawn::ProduceUnit(), WorldScript::SpawnUnitWithEffect::ProduceUnit(), WorldScript::SpawnUnitWithEffect::ProduceUnitEffects(), QueuedTasks::Queue(), rayCanSee(), rayCanSeeWithoutUnit(), rayClosestWithoutUnit(), rayQuickWithoutUnit(), BaseGameMode::RenderFrame(), ResolveDecal(), ResolveGibs(), DropSpawnBehavior::Save(), BossVampireMovement::Save(), RangedMovement::SeesTarget(), WorldScript::SetEnvironment::ServerExecute(), WorldScript::SpawnEnemyGroup::ServerExecute(), WorldScript::ExploreMinimap::ServerExecute(), WorldScript::ClearDelayedTriggers::ServerExecute(), WorldScript::SetCollider::ServerExecute(), WorldScript::DestroyScripts::ServerExecute(), WorldScript::PrefabPicker::ServerExecute(), WorldScript::RandomPicker::ServerExecute(), WorldScript::CheckMods::ServerExecute(), WorldScript::CheckTimeOfDay::ServerExecute(), WorldScript::IsWIPBuild::ServerExecute(), WorldScript::RandomChance::ServerExecute(), WorldScript::Counter::ServerExecute(), WorldScript::CheckSwitch::ServerExecute(), WorldScript::CheckFlag::ServerExecute(), WorldScript::SpawnEffect::ServerExecute(), WorldScript::CheckCrowdValue::ServerExecute(), WorldScript::CheckNewGamePlus::ServerExecute(), WorldScript::CheckSpawnDistance::ServerExecute(), WorldScript::CheckPlayerCount::ServerExecute(), WorldScript::CheckUnitSlot::ServerExecute(), WorldScript::CheckUnitActorTeam::ServerExecute(), WorldScript::TownBuildingLevel::ServerExecute(), WorldScript::SurvivalEnemySpawn::ServerExecute(), WorldScript::SurvivalEnemyDropSpawn::ServerExecute(), SetTarget(), BossLichMovement::SetTargetNode(), BossVampireMovement::SetTargetNode(), SetWeaponInformation(), ShootHitscan(), SorcererOrbProjectile::ShootProj(), ShootSpreadHitscan(), Spawn(), Town::SpawnBuildings(), Skills::DropEffect::SpawnDropEffect(), BaseGameMode::SpawnPlayer(), BaseGameMode::SpawnPlayerCorpse(), Town::SpawnStatues(), Skills::DropUnit::SpawnUnit(), UnitHandler::SpawnUnit(), SpawnUnitBaseImpl(), RandomLevel::Start(), Campaign::Start(), ActorFootsteps::StepEffect(), TargetValue(), TestDirection(), Skills::ScorchedEarth::Trigger(), PriestGroundCircle::Trigger(), WorldScript::TriggerGlobalEvent(), WorldScript::UnitEventTrigger::UnitCustomEvent(), WorldScript::UnitDamagedTrigger::UnitDamaged(), WorldScript::ActorHealthTrigger::UnitDamaged(), WorldScript::UnitDestroyedTrigger::UnitDestroyed(), WorldScript::UnitPickedUpTrigger::UnitPicked(), SorcererProjectile::Update(), Modifiers::AuraCone::Update(), Modifiers::Aura::Update(), BossLichRandomSkill::Update(), Update(), LurkerProjectile::Update(), SurvivalWaveProgress::Update(), SafetyAreaBehavior::Update(), WorldScript::TimerTrigger::Update(), TowerFlowerSpike::Update(), Tree::Update(), CompositeActorAuraSkill::Update(), TripMine::Update(), GargoyleSpawner::Update(), RangedMovement::Update(), QueuedTasks::Update(), Skills::CelestialOrb::Update(), BossVampire::Update(), DropSpawnBehavior::Update(), MagicTile::Update(), WorldScript::DropPod::Update(), MeleeSwing::Update(), WhirlNovaSkill::Update(), EnemyMeleeStrike::Update(), FixedPathFollower::Update(), ChargeMovement::Update(), SpewSkill::Update(), Gib::Update(), CannonBall::Update(), RayProjectile::Update(), Pickup::Update(), Breakable::Update(), PlayerBase::Update(), Player::Update(), Campaign::UpdateFrame(), BaseGameMode::UpdateFrame(), IngameMouse::UpdateMouseColor(), Campaign::UpdateWidgets(), WorldScript::UseTrigger::Use(), and WorldScript::Door::Use().
g_spawnPos
vec2 g_spawnPos
Definition at line 60 of file main.as.
Referenced by dbgArgs(), CaveGenerator::Generate(), ArmoryGenerator::Generate(), Generate(), MinesGenerator::Generate(), BaseGameMode::GetPlayerSpawnPosition(), BaseGameMode::Save(), WorldScript::CheckSpawnDistance::ServerExecute(), BaseGameMode::SpawnPlayers(), BaseGameMode::Start(), and Campaign::UpdateFrame().
g_startId
string g_startId
Definition at line 61 of file main.as.
Referenced by OnFunc(), BaseGameMode::Save(), WorldScript::LevelExitNext::ServerExecute(), and WorldScript::LevelExitNextAct::ServerExecute().
g_strGamepadA
const string g_strGamepadA = "A"
Definition at line 16 of file main.as.
g_strGamepadB
const string g_strGamepadB = "B"
Definition at line 17 of file main.as.
g_strGamepadBack
const string g_strGamepadBack = "BACK"
Definition at line 20 of file main.as.
g_strGamepadDpadDown
const string g_strGamepadDpadDown = "DOWN"
Definition at line 30 of file main.as.
g_strGamepadDpadLeft
const string g_strGamepadDpadLeft = "LEFT"
Definition at line 31 of file main.as.
g_strGamepadDpadRight
const string g_strGamepadDpadRight = "RIGHT"
Definition at line 32 of file main.as.
g_strGamepadDpadUp
const string g_strGamepadDpadUp = "UP"
Definition at line 29 of file main.as.
g_strGamepadGuide
const string g_strGamepadGuide = "GUIDE"
Definition at line 21 of file main.as.
g_strGamepadLeftShoulder
const string g_strGamepadLeftShoulder = "LB"
Definition at line 27 of file main.as.
g_strGamepadLeftStick
const string g_strGamepadLeftStick = "L3"
Definition at line 23 of file main.as.
g_strGamepadLeftTrigger
const string g_strGamepadLeftTrigger = "LT"
Definition at line 25 of file main.as.
g_strGamepadRightShoulder
const string g_strGamepadRightShoulder = "RB"
Definition at line 28 of file main.as.
g_strGamepadRightStick
const string g_strGamepadRightStick = "R3"
Definition at line 24 of file main.as.
g_strGamepadRightTrigger
const string g_strGamepadRightTrigger = "RT"
Definition at line 26 of file main.as.
g_strGamepadStart
const string g_strGamepadStart = "START"
Definition at line 22 of file main.as.
g_strGamepadX
const string g_strGamepadX = "X"
Definition at line 18 of file main.as.
g_strGamepadY
const string g_strGamepadY = "Y"
Definition at line 19 of file main.as.
g_useSpawnPos
bool g_useSpawnPos
Definition at line 59 of file main.as.
Referenced by dbgArgs(), and BaseGameMode::Start().
m_attachedEffects
array<AttachedEffect> m_attachedEffects
Definition at line 54 of file main.as.
Referenced by ActorBuff::Attach(), PlayEffect(), and BaseGameMode::PreRenderFrame().
m_attachedSounds
array<AttachedSound> m_attachedSounds
Definition at line 53 of file main.as.
Referenced by PlaySound3D(), and BaseGameMode::UpdateFrame().
m_gibs
array<Gib> m_gibs
Definition at line 87 of file main.as.
Referenced by AddGib(), ResolveGibs(), and UpdateGibs().
m_gibsSpawned
int m_gibsSpawned
Definition at line 88 of file main.as.
Referenced by AddGib(), ResolveGibs(), and UpdateGibs().
m_goreSpawners
array<GoreSpawner@> m_goreSpawners
Definition at line 117 of file main.as.
Referenced by LoadGore().
m_levelStarts
array<WorldScript::LevelStart@> m_levelStarts
Definition at line 55 of file main.as.
Referenced by BaseGameMode::GetCameraPos(), WorldScript::TeamLevelStart::Initialize(), WorldScript::LevelStart::Initialize(), and BaseGameMode::Start().
m_preRenderables
array<IPreRenderable@> m_preRenderables
Definition at line 52 of file main.as.
Referenced by BossEyeWisp::BossEyeWisp(), Skills::HandleBeam(), AttachedUnit::Initialize(), PlayerHusk::Initialize(), Player::Initialize(), AttachedUnit::PostLoad(), and BaseGameMode::PreRenderFrame().
m_safeGore
GoreSpawner m_safeGore
Definition at line 116 of file main.as.
Referenced by BaseGameMode::BaseGameMode(), OnDeath(), and OnHit().
unit
UnitPtr unit
Definition at line 47 of file main.as.
Referenced by LoadEffectParams(), PlayEffect(), and PlaySound3D().