HoHDocs: scripts/SpawnUnitBase.as File Reference
SpawnUnitBase.as File Reference
Classes
class SpawnUnitBase
class SpawnUnitBaseTask
Namespaces
SpawnUnitBaseHandler
Functions
class SpawnUnitBase SpawnUnitBaseImpl (UnitProducer@ UnitType, vec2 pos, string scene, int layer, int cfgEnemy, UnitPtr owner, float intensity)
void Initialize (UnitPtr unit, SValue@ params)
vec2 CalcJitter ()
UnitPtr SpawnUnit (vec2 pos, Actor@ owner, float intensity=1.0)
int SpawnUnitBaseHandler::PackEnemyCfg (bool AggroEnemy, bool NoLootEnemy, bool NoExperienceEnemy)
void SpawnUnitBaseHandler::ConfigureEnemy (CompositeActorBehavior@ enemy, int cfgEnemy)
void SpawnUnitBaseHandler::NetSpawnUnitBaseImpl (uint prodHash, int unitId, vec2 pos, string scene, int layer, int cfgEnemy, UnitPtr owner, float intensity)
void SpawnUnitBaseHandler::DoSpawnUnitBase (int delay, uint prodHash, vec2 pos, string scene, int layer, int cfgEnemy, int ownerId, float intensity)
void SpawnUnitBaseHandler::SpawnedOwnedUnitEnemy (uint prodHash, int unitId, vec2 pos, string scene, int layer, int cfgEnemy, UnitPtr owner, float intensity)
void SpawnUnitBaseHandler::SpawnedOwnedUnit (uint prodHash, int unitId, vec2 pos, string scene, int layer, UnitPtr owner, float intensity)
void SpawnUnitBaseHandler::SpawnedUnitEnemy (uint prodHash, int unitId, vec2 pos, string scene, int layer, int cfgEnemy)
void SpawnUnitBaseHandler::SpawnedUnit (uint prodHash, int unitId, vec2 pos, string scene, int layer)
void SpawnUnitBaseHandler::SpawnedUnitSimple (uint prodHash, int unitId, vec2 pos)
Variables
UnitProducer UnitType
string SceneName
int Layer
float JitterX
float JitterY
int Delay
bool AggroEnemy
bool NoLootEnemy
bool NoExperienceEnemy
Function Documentation
CalcJitter()
vec2 SpawnUnitBaseImpl::CalcJitter ()
Definition at line 128 of file SpawnUnitBase.as.
References UnitType.
     {
         UnitProducer@ UnitType = Resources::GetUnitProducer(prodHash);
         if (UnitType is null)
             return;
Initialize()
void SpawnUnitBaseImpl::Initialize (UnitPtr unit, SValue@ params)
Definition at line 111 of file SpawnUnitBase.as.
 {
     int PackEnemyCfg(bool AggroEnemy, bool NoLootEnemy, bool NoExperienceEnemy)
     {
         return (AggroEnemy ? 1 : 0) | (NoLootEnemy ? 2 : 0) | (NoExperienceEnemy ? 4 : 0);
     }
     void ConfigureEnemy(CompositeActorBehavior@ enemy, int cfgEnemy)
     {
         enemy.Configure((cfgEnemy & 1) != 0, (cfgEnemy & 2) != 0, (cfgEnemy & 4) != 0);
     }
SpawnUnit()
UnitPtr SpawnUnitBaseImpl::SpawnUnit (vec2 pos, Actor@ owner, float intensity = 1.0)
Definition at line 133 of file SpawnUnitBase.as.
     {
SpawnUnitBaseImpl()
class SpawnUnitBase SpawnUnitBaseImpl (UnitProducer@ UnitType, vec2 pos, string scene, int layer, int cfgEnemy, UnitPtr owner, float intensity)
Definition at line 74 of file SpawnUnitBase.as.
References SpawnUnitBaseHandler::ConfigureEnemy(), g_scene, UnitType, and xyz().
Referenced by SpawnUnitBaseHandler::DoSpawnUnitBase(), SpawnUnitBaseTask::Execute(), and SpawnUnitBase::SpawnUnit().
 {
     UnitPtr u;
     if (UnitType is null)
         return u;
     u = UnitType.Produce(g_scene, xyz(pos));
     auto enemyBehavior = cast<CompositeActorBehavior>(u.GetScriptBehavior());
     if (enemyBehavior !is null)
         SpawnUnitBaseHandler::ConfigureEnemy(enemyBehavior, cfgEnemy);
     else
         cfgEnemy = 0;
     if (scene != "")
         u.SetUnitScene(scene, true);
     if (layer != 0)
         u.SetLayer(layer);
     auto ownedUnit = cast<IOwnedUnit>(u.GetScriptBehavior());
     if (owner.IsValid() && ownedUnit !is null)
     {
         ownedUnit.Initialize(cast<Actor>(owner.GetScriptBehavior()), intensity, false);
         if (cfgEnemy != 0)
             (Network::Message("SpawnedOwnedUnitEnemy") << UnitType.GetResourceHash() << u.GetId() << pos << scene << layer << cfgEnemy << owner << intensity).SendToAll();
         else
             (Network::Message("SpawnedOwnedUnit") << UnitType.GetResourceHash() << u.GetId() << pos << scene << layer << owner << intensity).SendToAll();
         return u;
     }
     if (cfgEnemy != 0)
         (Network::Message("SpawnedUnitEnemy") << UnitType.GetResourceHash() << u.GetId() << pos << scene << layer << cfgEnemy).SendToAll();
     else if (scene != "" || layer != 0)
         (Network::Message("SpawnedUnit") << UnitType.GetResourceHash() << u.GetId() << pos << scene << layer).SendToAll();
     else
         (Network::Message("SpawnedUnitSimple") << UnitType.GetResourceHash() << u.GetId() << pos).SendToAll();
     return u;
 }
Variable Documentation
AggroEnemy
bool AggroEnemy
Definition at line 103 of file SpawnUnitBase.as.
Referenced by SpawnUnitBaseHandler::PackEnemyCfg().
Delay
int Delay
Definition at line 99 of file SpawnUnitBase.as.
JitterX
float JitterX
Definition at line 94 of file SpawnUnitBase.as.
JitterY
float JitterY
Definition at line 96 of file SpawnUnitBase.as.
Layer
int Layer
Definition at line 91 of file SpawnUnitBase.as.
NoExperienceEnemy
bool NoExperienceEnemy
Definition at line 107 of file SpawnUnitBase.as.
Referenced by SpawnUnitBaseHandler::PackEnemyCfg().
NoLootEnemy
bool NoLootEnemy
Definition at line 105 of file SpawnUnitBase.as.
Referenced by SpawnUnitBaseHandler::PackEnemyCfg().
SceneName
string SceneName
Definition at line 88 of file SpawnUnitBase.as.
UnitType
UnitProducer UnitType
Definition at line 85 of file SpawnUnitBase.as.
Referenced by CalcJitter(), DoSpawnUnit(), SpawnUnitBaseImpl(), and SpawnUnitBaseTask::SpawnUnitBaseTask().