HoHDocs: scripts/Utils/RandomBank.as File Reference
RandomBank.as File Reference
Enumerations
enum RandomContext
Functions
enum RandomContext g_randomSequences (int(RandomContext::NumContexts))
int Int (RandomContext ctx, int max)
float Float (RandomContext ctx)
uint GetSeed (RandomContext ctx)
void SetSeed (RandomContext ctx, uint seed)
Variables
CardGame100
CardGame500
CardGame1000
CardGame5000
CardGame10000
CardGame100000
CardGame1000000
Fountain
NumContexts
Enumeration Type Documentation
RandomContext
enum RandomContext
Definition at line 1 of file RandomBank.as.
 {
     CardGame100,
     CardGame500,
     CardGame1000,
     CardGame5000,
     CardGame10000,
     CardGame100000,
     CardGame1000000,
     Fountain,
     NumContexts,
 }
Function Documentation
Float()
float Float (RandomContext ctx)
Definition at line 21 of file RandomBank.as.
References g_randomSequences().
Referenced by CheckBoxGroupWidget::Cancel(), CompositeActorBehavior(), CheckBoxGroupWidget::IsChanged(), Load(), DangerAreaBehavior::Load(), LoadDecalSets(), LoadEffectParams(), LoadEffectSets(), LoadGibSets(), Menu::SubOptionsMenu::OnFunc(), MeleeMovement::PostLoad(), CheckBoxGroupWidget::Reset(), CheckBoxGroupWidget::Save(), CheckBoxGroupWidget::Update(), and Player::Update().
 { return g_randomSequences[int(ctx)].GetFloat(); }
g_randomSequences()
enum RandomContext g_randomSequences (int(RandomContext::NumContexts))
Referenced by Float(), GetSeed(), Int(), and SetSeed().
GetSeed()
uint GetSeed (RandomContext ctx)
Definition at line 22 of file RandomBank.as.
References g_randomSequences().
Referenced by TownRecord::Save().
 { return g_randomSequences[int(ctx)].GetSeed(); }
Int()
int Int (RandomContext ctx, int max)
Definition at line 20 of file RandomBank.as.
References g_randomSequences(), and max.
Referenced by CheckBoxGroupWidget::Cancel(), CheckBoxGroupWidget::IsChanged(), Menu::SubOptionsMenu::OnFunc(), Player::Player(), PullRandomCard(), CheckBoxGroupWidget::Reset(), CheckBoxGroupWidget::Save(), and CheckBoxGroupWidget::Update().
 { return g_randomSequences[int(ctx)].GetInt(max); }
SetSeed()
void SetSeed (RandomContext ctx, uint seed)
Definition at line 23 of file RandomBank.as.
References g_randomSequences().
Referenced by TownRecord::Load().
 { g_randomSequences[int(ctx)].SetSeed(seed); }
Variable Documentation
CardGame100
CardGame100
Definition at line 12 of file RandomBank.as.
Referenced by PullRandomCard().
CardGame1000
CardGame1000
Definition at line 12 of file RandomBank.as.
Referenced by PullRandomCard().
CardGame10000
CardGame10000
Definition at line 12 of file RandomBank.as.
Referenced by PullRandomCard().
CardGame100000
CardGame100000
Definition at line 12 of file RandomBank.as.
Referenced by PullRandomCard().
CardGame1000000
CardGame1000000
Definition at line 12 of file RandomBank.as.
Referenced by PullRandomCard().
CardGame500
CardGame500
Definition at line 12 of file RandomBank.as.
Referenced by PullRandomCard().
CardGame5000
CardGame5000
Definition at line 12 of file RandomBank.as.
Referenced by PullRandomCard().
Fountain
Fountain
Definition at line 12 of file RandomBank.as.
NumContexts
NumContexts
Definition at line 12 of file RandomBank.as.
Referenced by TownRecord::Load(), and TownRecord::Save().