HoHDocs: scripts/Utils/MarkovName.as File Reference
MarkovName.as File Reference
Classes
class MarkovPair
Functions
MarkovName (array< string >@ input, int lookback=2)
MarkovPair GetPair (string char, bool allowNew=false)
string GenerateName (uint lenMin=4, uint lenMax=12)
Variables
class MarkovPair m_chain
int m_lookback
Function Documentation
GenerateName()
string GenerateName (uint lenMin = 4, uint lenMax = 12)
Definition at line 65 of file MarkovName.as.
References GetPair(), m_lookback, and MarkovPair::m_next.
     {
         uint bigAttempts = 0;
         string vowels = "aoeiu";
         while (bigAttempts < 5)
         {
             bool hasVowel = false;
             uint smallAttempts = 0;
             string ret;
             string cur = " "; // used to mark both first and last character
             while ((cur != " " || ret.length() < lenMin) && ret.length() < lenMax && smallAttempts < 5)
             {
                 MarkovPair@ pair;
                 if (ret.length() >= 2)
                 {
                     for (int i = m_lookback; i >= 2; i--)
                     {
                         if (ret.length() < uint(i))
                             continue;
                         string part = ret.substr(ret.length() - i, i);
                         @pair = GetPair(part);
                         if (pair !is null)
                             break;
                     }
                 }
                 if (pair is null)
                     @pair = GetPair(cur);
                 if (pair is null)
                     break;
                 cur = pair.m_next.substr(randi(pair.m_next.length()), 1);
                 if (vowels.findFirst(cur) != -1)
                     hasVowel = true;
                 if (cur == " " || (ret.length() >= 2 && ret.substr(ret.length() - 2, 1) == cur))
                 {
                     cur = ret.substr(ret.length() - 1, 1);
                     if (ret.length() < lenMin)
                     {
                         smallAttempts++;
                         continue;
                     }
                     break;
                 }
                 ret += cur;
             }
             if (ret.length() < lenMin || !hasVowel)
             {
                 bigAttempts++;
                 continue;
             }
             return ret.substr(0, 1).toUpper() + ret.substr(1);
         }
         return "Bob"; // This will hopefully never happen
     }
GetPair()
MarkovPair GetPair (string char, bool allowNew = false)
Definition at line 46 of file MarkovName.as.
References m_chain.
Referenced by GenerateName(), and MarkovName().
     {
         for (uint i = 0; i < m_chain.length(); i++)
         {
             if (m_chain[i].m_char == char)
                 return m_chain[i];
         }
         if (allowNew)
         {
             auto newPair = MarkovPair();
             newPair.m_char = char;
             m_chain.insertLast(newPair);
             return newPair;
         }
         return null;
     }
MarkovName()
MarkovName (array< string >@ input, int lookback = 2)
Definition at line 19 of file MarkovName.as.
References GetPair(), m_lookback, MarkovPair::m_next, and name.
Referenced by CharacterCustomizationBase::Initialize().
     {
         m_lookback = lookback;
         for (uint i = 0; i < input.length(); i++)
         {
             string name = input[i];
             // name = "alice"
             for (uint j = 0; j < name.length() - 1; j++)
             {
                 GetPair(name.substr(j, 1), true).m_next += name.substr(j + 1, 1);
                 // "li" -> "c"
                 for (int k = 2; k <= m_lookback; k++)
                 {
                     if (int(j) < k - 1)
                         continue;
                     GetPair(name.substr(j - (k - 1), k), true).m_next += name.substr(j + 1, 1);
                 }
             }
             // +1 for "e" as last character
             for (int j = 1; j <= m_lookback; j++)
                 GetPair(name.substr(name.length() - j, j), true).m_next += " ";
             // +1 for "a" as first character
             GetPair(" ", true).m_next += name.substr(0, 1);
         }
     }
Variable Documentation
m_chain
class MarkovPair m_chain
Referenced by GetPair().
m_lookback
int m_lookback
Definition at line 17 of file MarkovName.as.
Referenced by GenerateName(), and MarkovName().