HoHDocs: scripts/Utils/Functions.as File Reference
Functions.as File Reference
Enumerations
enum EasingFunction {
Linear, Quad, QuadIn, QuadOut,
Cubic, CubicIn, CubicOut, Sine,
Elastic
}
Functions
float lerp (const float v0, const float v1, float t)
int lerp (const int v0, const int v1, float t)
vec2 lerp (const vec2 v0, const vec2 v1, float t)
vec3 lerp (const vec3 v0, const vec3 v1, float t)
vec4 lerp (const vec4 v0, const vec4 v1, float t)
float ilerp (const float v0, const float v1, const float v)
float ilerp (const int v0, const int v1, const int v)
float clamp (const float val, const float minVal, const float maxVal)
int clamp (const int val, const int minVal, const int maxVal)
float min (const float v0, const float v1)
int min (const int v0, const int v1)
float max (const float v0, const float v1)
int max (const int v0, const int v1)
float abs (const float v)
int abs (const int v)
int64 abs (const int64 v)
int sign (const int v)
int sign (const float v)
vec2 xy (vec3 v)
vec2 xy (vec4 v)
vec3 xyz (vec4 v)
vec3 xyz (vec2 v)
vec3 xyz (vec2 v, float z)
vec4 xyzw (vec3 v, float w)
float randfn ()
float rottowards (float source, float target, float amount)
float capangle (float angle)
float angdiff (float a, float b)
vec2 addrot (vec2 v, float rad)
int distsq (Actor@ a, Actor@ b)
int distsq (UnitPtr a, UnitPtr b)
int distsq (Actor@ a, UnitPtr b)
int distsq (UnitPtr a, Actor@ b)
int distsq (UnitPtr a, vec2 b)
int distsq (Actor@ a, vec2 b)
int distsq (vec2 b, UnitPtr a)
int distsq (vec2 b, Actor@ a)
string formatTime (double tm, bool fractions=false, bool forceMinutes=false, bool forceHours=false, bool letters=false, bool short=false)
float ease (float x, EasingFunction func)
float easeQuad (float x)
float easeQuadIn (float x)
float easeQuadOut (float x)
float easeCubic (float x)
float easeCubicIn (float x)
float easeCubicOut (float x)
float easeSine (float x)
float easeElastic (float x)
string strTrim (string str)
int strCountWords (string str)
array< string > strCommandLineParse (string str, bool bUseLiterals=true)
string formatThousands (int64 number)
string toRoman (int num)
string formatMeters (int units)
string formatMeters (int64 units)
bool rayQuickFromUnit (UnitPtr unit, vec2 toPos, uint slots, RaycastType type)
bool rayQuickWithoutUnit (vec2 fromPos, vec2 toPos, uint slots, RaycastType type, UnitPtr unit)
RaycastResult rayClosestFromUnit (UnitPtr unit, vec2 toPos, uint slots, RaycastType type)
RaycastResult rayClosestWithoutUnit (vec2 fromPos, vec2 toPos, uint slots, RaycastType type, UnitPtr unit)
bool rayCanSee (UnitPtr a, UnitPtr b, RaycastType type=RaycastType::Aim)
bool rayCanSee (vec2 p, UnitPtr b, RaycastType type=RaycastType::Aim)
bool rayCanSeeWithoutUnit (vec2 p, UnitPtr b, UnitPtr unitIgnore, uint slots=~0, RaycastType type=RaycastType::Aim)
bool IsNetsyncedExistance (NetSyncMode mode)
string GetNamePart (string resname)
int roll_round (float f)
vec2 intercept (vec2 srcPos, vec2 dstPos, vec2 dstVel, float vel)
vec2 quad (float a, float b, float c)
string GetCurrentDifficultyName ()
bool AnyPressed (GameInput@ gi, MenuInput@ mi)
string UcFirst (string str)
string RichPresenceGetActName (int levelCount)
Enumeration Type Documentation
EasingFunction
enum EasingFunction
Enumerator
Linear
Quad
QuadIn
QuadOut
Cubic
CubicIn
CubicOut
Sine
Elastic
Definition at line 297 of file Functions.as.
 {
     Linear,
     Quad,
     QuadIn,
     QuadOut,
     Cubic,
     CubicIn,
     CubicOut,
     Sine,
     Elastic
 };
Function Documentation
abs() [1/3]
float abs (const float v)
Definition at line 66 of file Functions.as.
Referenced by angdiff(), MeleeMovement::CalcDirSpeed(), close(), CaveGenerator::FindWall(), formatThousands(), Skills::HandleBeam(), ArmoryGenerator::MakeRoomLine(), ChargeMovement::OnCollide(), PlotLine(), Modifiers::BlockProjectile::ProjectileBlock(), quad(), roll_round(), rottowards(), EnemyMeleeStrike::Update(), Player::Update(), and ScrollableWidget::UpdateInput().
 {
     return v > 0 ? v : -v;
 }
abs() [2/3]
int abs (const int v)
Definition at line 71 of file Functions.as.
 {
     return v > 0 ? v : -v;
 }
abs() [3/3]
int64 abs (const int64 v)
Definition at line 76 of file Functions.as.
 {
     return v > 0 ? v : -v;
 }
addrot()
vec2 addrot (vec2 v, float rad)
Definition at line 164 of file Functions.as.
Referenced by CompositeActorSkill::CalcAimDir(), SpawnPrefab::DoSpawnPrefab(), DoSpawnUnit(), WhirlwindSkill::Update(), JumpStrike::Update(), and SpewSkill::Update().
 {
     float ang = atan(v.y, v.x);
     return vec2(cos(ang + rad), sin(ang + rad));
 }
angdiff()
float angdiff (float a, float b)
Definition at line 155 of file Functions.as.
References abs().
Referenced by MeleeMovement::CalcDirSpeed().
 {
     if (abs(b - a) < PI)
         return b - a;
     if (b > a)
         return b - a - TwoPI;
     return b - a + TwoPI;
 }
AnyPressed()
bool AnyPressed (GameInput@ gi, MenuInput@ mi)
Definition at line 695 of file Functions.as.
References MenuInput::ChatAll, MenuInput::Down, MenuInput::Forward, MenuInput::Left, ButtonState::Pressed, MenuInput::Right, and MenuInput::Up.
 {
     if (gi.Attack1.Pressed) return true;
     if (gi.Attack2.Pressed) return true;
     if (gi.Attack3.Pressed) return true;
     if (gi.Attack4.Pressed) return true;
     if (gi.Use.Pressed) return true;
     if (gi.Potion.Pressed) return true;
     if (gi.PlayerMenu.Pressed) return true;
     if (gi.Ping.Pressed) return true;
     if (mi.Up.Pressed) return true;
     if (mi.Down.Pressed) return true;
     if (mi.Left.Pressed) return true;
     if (mi.Right.Pressed) return true;
     if (mi.Forward.Pressed) return true;
     if (mi.ChatAll.Pressed) return true;
     return false;
 }
capangle()
float capangle (float angle)
Definition at line 146 of file Functions.as.
Referenced by rottowards().
 {
     angle = angle % TwoPI;
     if (angle < 0)
         angle += TwoPI;
     return angle;
 }
clamp() [1/2]
float clamp (const float val, const float minVal, const float maxVal)
Definition at line 36 of file Functions.as.
Referenced by Actor::AddFloatingHurt(), MeleeMovement::CalcDirSpeed(), Modifiers::SealOfMana::DamageMul(), Modifiers::SealOfMartyr::DamageMul(), Decimate(), Player::Decimate(), BaseGameMode::DisplayPlayerHealth(), DoLighting(), HUD::DrawPlayerBar(), CaveGenerator::Generate(), ArmoryGenerator::Generate(), Skills::ActiveSkill::GetCooldownProgess(), Player::GiveMana(), WorldScript::Wind::PostUpdate(), SpriteBarWidget::SetValue(), Player::TakeMana(), MenuTabSystem::Update(), HUD::Update(), and Player::Update().
 {
     return (val < minVal) ? minVal : ((val > maxVal) ? maxVal : val);
 }
clamp() [2/2]
int clamp (const int val, const int minVal, const int maxVal)
Definition at line 41 of file Functions.as.
 {
     return (val < minVal) ? minVal : ((val > maxVal) ? maxVal : val);
 }
distsq() [1/8]
int distsq (Actor@ a, Actor@ b)
Definition at line 170 of file Functions.as.
References Actor::m_unit.
Referenced by MagicTile::ClosestPlayer(), Skills::DoBeamRay(), SpawnPrefab::DoSpawnPrefabs(), DoSpawnUnits(), Skills::DoUpdate(), FixedPathFollower::FindFirstNode(), PathFollower::FollowPathPathfind(), BossLich::GetCastDirection(), BossVampire::GetCastDirection(), SorcererProjectile::HitUnit(), MeleeMovement::IdleUpdate(), NovaSkill::IsAvailable(), EnemyMeleeStrike::IsAvailable(), BlinkSkill::IsAvailable(), WhirlwindSkill::IsAvailable(), JumpStrike::IsAvailable(), SpewSkill::IsAvailable(), CompositeActorSkill::IsAvailable(), RangedMovement::IsStandPosValid(), RemoveNearby(), RemoveNearbySame(), Player::SendPlayerMove(), TestDirection(), Update(), MenuMouse::Update(), TripMine::Update(), RangedMovement::Update(), PowershotProjectile::Update(), Skills::CelestialOrb::Update(), Projectile::Update(), WhirlNovaSkill::Update(), FixedPathFollower::Update(), SpewSkill::Update(), PlayerHusk::Update(), and UpdateInput().
 {
     vec3 pa = a.m_unit.GetPosition();
     vec3 pb = b.m_unit.GetPosition();
     float dx = pa.x - pb.x;
     float dy = pa.y - pb.y;
     return int(dx * dx + dy * dy);
 }
distsq() [2/8]
int distsq (UnitPtr a, UnitPtr b)
Definition at line 181 of file Functions.as.
 {
     vec3 pa = a.GetPosition();
     vec3 pb = b.GetPosition();
     float dx = pa.x - pb.x;
     float dy = pa.y - pb.y;
     return int(dx * dx + dy * dy);
 }
distsq() [3/8]
int distsq (Actor@ a, UnitPtr b)
Definition at line 192 of file Functions.as.
References Actor::m_unit.
 {
     vec3 pa = a.m_unit.GetPosition();
     vec3 pb = b.GetPosition();
     float dx = pa.x - pb.x;
     float dy = pa.y - pb.y;
     return int(dx * dx + dy * dy);
 }
distsq() [4/8]
int distsq (UnitPtr a, Actor@ b)
Definition at line 203 of file Functions.as.
References Actor::m_unit.
 {
     vec3 pa = a.GetPosition();
     vec3 pb = b.m_unit.GetPosition();
     float dx = pa.x - pb.x;
     float dy = pa.y - pb.y;
     return int(dx * dx + dy * dy);
 }
distsq() [5/8]
int distsq (UnitPtr a, vec2 b)
Definition at line 214 of file Functions.as.
 {
     vec3 pa = a.GetPosition();
     float dx = pa.x - b.x;
     float dy = pa.y - b.y;
     return int(dx * dx + dy * dy);
 }
distsq() [6/8]
int distsq (Actor@ a, vec2 b)
Definition at line 224 of file Functions.as.
References Actor::m_unit.
 {
     vec3 pa = a.m_unit.GetPosition();
     float dx = pa.x - b.x;
     float dy = pa.y - b.y;
     return int(dx * dx + dy * dy);
 }
distsq() [7/8]
int distsq (vec2 b, UnitPtr a)
Definition at line 234 of file Functions.as.
 {
     vec3 pa = a.GetPosition();
     float dx = pa.x - b.x;
     float dy = pa.y - b.y;
     return int(dx * dx + dy * dy);
 }
distsq() [8/8]
int distsq (vec2 b, Actor@ a)
Definition at line 244 of file Functions.as.
References Actor::m_unit.
 {
     vec3 pa = a.m_unit.GetPosition();
     float dx = pa.x - b.x;
     float dy = pa.y - b.y;
     return int(dx * dx + dy * dy);
 }
ease()
float ease (float x, EasingFunction func)
Definition at line 310 of file Functions.as.
References Cubic, CubicIn, CubicOut, easeCubic(), easeCubicIn(), easeCubicOut(), easeElastic(), easeQuad(), easeQuadIn(), easeQuadOut(), easeSine(), Elastic, Quad, QuadIn, QuadOut, and Sine.
Referenced by WidgetAnimation::PreRender().
 {
     switch (func)
     {
         case EasingFunction::Quad: return easeQuad(x);
         case EasingFunction::QuadIn: return easeQuadIn(x);
         case EasingFunction::QuadOut: return easeQuadOut(x);
         case EasingFunction::Cubic: return easeCubic(x);
         case EasingFunction::CubicIn: return easeCubicIn(x);
         case EasingFunction::CubicOut: return easeCubicOut(x);
         case EasingFunction::Sine: return easeSine(x);
         case EasingFunction::Elastic: return easeElastic(x);
     }
     return x;
 }
easeCubic()
float easeCubic (float x)
Definition at line 342 of file Functions.as.
Referenced by ease().
 {
     if ((x /= 0.5) < 1) return 0.5 * x * x * x;
     return 0.5 * ((x -= 2) * x * x + 2);
 }
easeCubicIn()
float easeCubicIn (float x)
Definition at line 348 of file Functions.as.
Referenced by ease().
 {
     return x * x * x;
 }
easeCubicOut()
float easeCubicOut (float x)
Definition at line 353 of file Functions.as.
Referenced by ease().
 {
     return (x -= 1) * x * x + 1;
 }
easeElastic()
float easeElastic (float x)
Definition at line 363 of file Functions.as.
Referenced by ease().
 {
     float s = 0.1125;
     if (x == 0) return 0;
     if ((x /= 0.5) == 2) return 1;
     if (x < 1) return -0.5 * (pow(2, 10 * (x -= 1)) * sin((x - s) * (2 * PI) / 0.45));
     return pow(2, -10 * (x -= 1)) * sin((x - s) * (2 * PI) / 0.45) * 0.5 + 1;
 }
easeQuad()
float easeQuad (float x)
Definition at line 326 of file Functions.as.
Referenced by ease(), Notification::GetColor(), and Campaign::RenderWidgets().
 {
     if ((x /= 0.5) < 1) return 0.5 * x * x;
     return -0.5 * ((--x) * (x - 2) - 1);
 }
easeQuadIn()
float easeQuadIn (float x)
Definition at line 332 of file Functions.as.
Referenced by ease().
 {
     return x * x;
 }
easeQuadOut()
float easeQuadOut (float x)
Definition at line 337 of file Functions.as.
Referenced by ease().
 {
     return -x * (x - 2);
 }
easeSine()
float easeSine (float x)
Definition at line 358 of file Functions.as.
Referenced by ease().
 {
     return -0.5 * (cos(PI * x) - 1);
 }
formatMeters() [1/2]
string formatMeters (int units)
Definition at line 524 of file Functions.as.
References formatThousands(), and Tweak::PixelsPerMeter.
Referenced by GameOver::FindPossibleSentences(), Stats::Accomplishment::GetDescription(), and Stats::ToString().
 {
     int meters = int(units / Tweak::PixelsPerMeter);
     if (meters >= 10000)
         return round(meters / 1000.0f, 2) + " km";
     else
         return formatThousands(meters) + " m";
 }
formatMeters() [2/2]
string formatMeters (int64 units)
Definition at line 533 of file Functions.as.
References formatThousands(), and Tweak::PixelsPerMeter.
 {
     int64 meters = int64(units / Tweak::PixelsPerMeter);
     if (meters >= 10000)
         return round(meters / 1000.0f, 2) + " km";
     else
         return formatThousands(meters) + " m";
 }
formatThousands()
string formatThousands (int64 number)
Definition at line 484 of file Functions.as.
References abs().
Referenced by GuildHallBeastiaryTab::AddCategory(), GuildHallStatsTab::AddGuildToList(), AddItem(), CharacterCustomizationBase::ColorsChanged(), CharacterCustomizationBase::FaceChanged(), formatMeters(), Stats::Accomplishment::GetDescription(), FountainShopMenuContent::NetDeposit(), CharacterCustomizationNPC::OnFunc(), OnFunc(), SkillsShopMenuContent::OnFunc(), TownRecord::OnNewTitle(), Stats::Accomplishment::OnUpdated(), GuildHallAccomplishmentsTab::RefreshList(), DrinksMenuContent::ReloadList(), ReloadList(), SkillsShopMenuContent::ReloadList(), SetGoldStatus(), ShopButtonWidget::SetPrice(), CharacterCustomizationBase::ShowSelection(), Stats::ToString(), HUD::Update(), BossBarWidget::UpdateAppearance(), CharacterCustomizationBase::UpdateCost(), PlayerMenuCharacterTab::UpdateFromRecord(), and FountainShopMenuContent::UpdateInterface().
 {
     if (number < 1000 && number > -1000)
         return "" + number;
     bool negative = (number < 0);
     number = abs(number);
     string ret = "";
     int64 curr = number;
     while (curr > 0)
     {
         if (ret != "")
             ret = "\u2005" + ret;
         string str;
         if (curr >= 1000)
             str = formatInt(curr % 1000, "0", 3);
         else
             str = formatInt(curr);
         ret = str + ret;
         curr /= 1000;
     }
     if (negative)
         ret = "-" + ret;
     return ret;
 }
formatTime()
string formatTime (double tm, bool fractions = false, bool forceMinutes = false, bool forceHours = false, bool letters = false, bool short = false)
Definition at line 254 of file Functions.as.
References max().
Referenced by FormattedTime(), PlayerMenuCharacterTab::OnShow(), ScoreDialog::Set(), Stats::ToString(), PlayerMenuCharacterTab::Update(), UpdateText(), and Player::WarnCooldown().
 {
     string str = "";
     int milliseconds = int((tm % 1.0) * 1000);
     int seconds = int(tm % 60);
     int minutes = int(tm / 60) % 60;
     int hours = int(tm / 60 / 60);
     if (hours > 0 || forceHours)
     {
         str += hours;
         if (letters)
             str += Resources::GetString(".misc.timeletters.hours") + " ";
         else
             str += ":";
     }
     if (minutes > 0 || hours > 0 || forceMinutes)
     {
         str += formatInt(minutes, "0", (hours > 0 || forceHours) ? 2 : 1);
         if (letters)
             str += Resources::GetString(".misc.timeletters.minutes") + " ";
         else
             str += ":";
     }
     str += formatInt(seconds, "0", (minutes > 0 || hours > 0 || forceMinutes) ? 2 : 1);
     if (fractions)
     {
         str += ".";
         if (short)
             str += formatInt(max(1, milliseconds / 100), "0", 1);
         else
             str += formatInt(milliseconds, "0", 3);
     }
     if (letters)
         str += Resources::GetString(".misc.timeletters.seconds");
     return str;
 }
GetCurrentDifficultyName()
string GetCurrentDifficultyName ()
Definition at line 680 of file Functions.as.
 {
 %if DIFF_EASY
     return Resources::GetString(".difficulty.easy");
 %elif DIFF_NORMAL
     return Resources::GetString(".difficulty.normal");
 %elif DIFF_HARD
     return Resources::GetString(".difficulty.hard");
 %elif DIFF_SERIOUS
     return Resources::GetString(".difficulty.serious");
 %else
     return "??";
 %endif
 }
GetNamePart()
string GetNamePart (string resname)
Definition at line 620 of file Functions.as.
 {
     return resname.substr(resname.findLast(":") + 1);
 }
ilerp() [1/2]
float ilerp (const float v0, const float v1, const float v)
Definition at line 26 of file Functions.as.
Referenced by GuildHallStatsTab::AddGuildToList(), GuildHallAccomplishmentsTab::RefreshList(), and MenuTabSystem::Update().
 {
     return (v - v0) / (v1 - v0);
 }
ilerp() [2/2]
float ilerp (const int v0, const int v1, const int v)
Definition at line 31 of file Functions.as.
 {
     return (v - v0) / float(v1 - v0);
 }
intercept()
vec2 intercept (vec2 srcPos, vec2 dstPos, vec2 dstVel, float vel)
Definition at line 634 of file Functions.as.
References max(), min(), and quad().
Referenced by CompositeActorSkill::CalcAimDir(), SorcererProjectile::HitUnit(), and RangerProjectile::Multiply().
 {
     vec2 t = dstPos - srcPos;
     vec2 tv = dstVel;
     // Get quadratic equation components
     float a = tv.x*tv.x + tv.y*tv.y - vel*vel;
     float b = 2 * (tv.x * t.x + tv.y * t.y);
     float c = t.x*t.x + t.y*t.y;
     vec2 ts = quad(a, b, c);
     float res = min(ts.x, ts.y);
     if (res < 0)
         res = max(ts.x, ts.y);
     if (res > 0)
         return dstPos + dstVel * res;
     return dstPos;
 }
IsNetsyncedExistance()
bool IsNetsyncedExistance (NetSyncMode mode)
Definition at line 615 of file Functions.as.
Referenced by BombBehavior::BombBehavior(), WorldScript::DestroyUnits::ClientExecute(), DelayedBreakable::DamageEffects(), Breakable::DamageEffects(), DangerAreaBehavior::DangerAreaBehavior(), DoSpawnUnit(), Skills::DropUnit::DropUnit(), WorldScript::ProjectileSpewer::Initialize(), WorldScript::RefreshSpawnPickup::Initialize(), WorldScript::SurvivalEnemySpawn::Initialize(), WorldScript::SpawnUnitWithEffect::Initialize(), WorldScript::SurvivalEnemyDropSpawn::Initialize(), Pickup::Pickup(), WorldScript::DestroyUnitCount::ServerExecute(), WorldScript::DestroyUnitChance::ServerExecute(), SimpleBreakable::SimpleBreakable(), Spawn(), Skills::SpawnUnit::SpawnUnit(), SpawnUnitBase::SpawnUnit(), Skills::StaggeredSpawnUnits::StaggeredSpawnUnits(), and DropSpawnBehavior::Update().
 {
     return mode == NetSyncMode::Existance || mode == NetSyncMode::Position;
 }
lerp() [1/5]
float lerp (const float v0, const float v1, float t)
Definition at line 1 of file Functions.as.
Referenced by Apply(), WidgetVec2Animation::Apply(), MeleeMovement::CalcDirSpeed(), ShootProjectile::DoAction(), Hitscan::DoAction(), DoAction(), Skills::ShootProjectile::DoActivate(), DoDraw(), OverheadBossBar::Draw(), Menu::BackdropLayer::Draw(), MenuTabSystem::Draw(), Notification::GetColor(), BossEyeWisp::GetCurrentOffset(), Widget::GetOrigin(), MouseBase::GetPos(), GetValue(), BaseGameMode::GetVignette(), CannonBall::HitUnit(), TossProjectile::Initialize(), PowershotProjectile::Initialize(), CannonBall::Initialize(), Modifiers::Speed::MoveSpeedMul(), ActorBuffList::MoveSpeedMul(), Notification::PreDraw(), WidgetAnimation::PreRender(), Skills::PreRender(), Campaign::RenderWidgets(), SetCard(), ScreenShake::ShakeFactor(), Update(), MenuTabSystem::Update(), BossEyeWisp::Update(), Player::Update(), and UpdateText().
 {
     return (1.0 - t) * v0 + t * v1;
 }
lerp() [2/5]
int lerp (const int v0, const int v1, float t)
Definition at line 6 of file Functions.as.
 {
     return int((1.0 - t) * v0 + t * v1);
 }
lerp() [3/5]
vec2 lerp (const vec2 v0, const vec2 v1, float t)
Definition at line 11 of file Functions.as.
 {
     return vec2((1.0 - t) * v0.x + t * v1.x, (1.0 - t) * v0.y + t * v1.y);
 }
lerp() [4/5]
vec3 lerp (const vec3 v0, const vec3 v1, float t)
Definition at line 16 of file Functions.as.
 {
     return vec3((1.0 - t) * v0.x + t * v1.x, (1.0 - t) * v0.y + t * v1.y, (1.0 - t) * v0.z + t * v1.z);
 }
lerp() [5/5]
vec4 lerp (const vec4 v0, const vec4 v1, float t)
Definition at line 21 of file Functions.as.
 {
     return vec4((1.0 - t) * v0.x + t * v1.x, (1.0 - t) * v0.y + t * v1.y, (1.0 - t) * v0.z + t * v1.z, (1.0 - t) * v0.w + t * v1.w);
 }
max() [1/2]
float max (const float v0, const float v1)
Definition at line 56 of file Functions.as.
Referenced by formatTime(), and intercept().
 {
     return v0 > v1 ? v0 : v1;
 }
max() [2/2]
int max (const int v0, const int v1)
Definition at line 61 of file Functions.as.
 {
     return v0 > v1 ? v0 : v1;
 }
min() [1/2]
float min (const float v0, const float v1)
Definition at line 46 of file Functions.as.
Referenced by intercept(), and rottowards().
 {
     return v0 < v1 ? v0 : v1;
 }
min() [2/2]
int min (const int v0, const int v1)
Definition at line 51 of file Functions.as.
 {
     return v0 < v1 ? v0 : v1;
 }
quad()
vec2 quad (float a, float b, float c)
Definition at line 656 of file Functions.as.
References abs().
Referenced by intercept().
 {
     if (abs(a) < 0.0001)
     {
         if (abs(b) < 0.0001)
             return vec2(0, 0);
         else
             return vec2(-c / b, -c / b);
     }
     else
     {
         auto disc = b * b - 4 * a * c;
         if (disc >= 0)
         {
             disc = sqrt(disc);
             a = 2 * a;
             return vec2((-b - disc) / a, (-b + disc) / a);
         }
     }
     return vec2(0, 0);
 }
randfn()
float randfn ()
Definition at line 125 of file Functions.as.
Referenced by CompositeActorSkill::CalcAimDir(), WhirlwindSkill::Update(), JumpStrike::Update(), and SpewSkill::Update().
 {
     return randf() * 2.0 - 1.0;
 }
rayCanSee() [1/2]
bool rayCanSee (UnitPtr a, UnitPtr b, RaycastType type = RaycastType::Aim)
Definition at line 576 of file Functions.as.
References g_scene, type, and xy().
Referenced by Update(), and CirclingMovement::Update().
 {
     if (!a.IsValid() || !b.IsValid())
         return false;
     RaycastResult res = g_scene.RaycastClosest(xy(a.GetPosition()), xy(b.GetPosition()), ~0, type);
     UnitPtr res_unit = res.FetchUnit(g_scene);
     if (!res_unit.IsValid())
         return true;
     return (res_unit == b);
 }
rayCanSee() [2/2]
bool rayCanSee (vec2 p, UnitPtr b, RaycastType type = RaycastType::Aim)
Definition at line 590 of file Functions.as.
References g_scene, type, and xy().
 {
     if (!b.IsValid())
         return false;
     RaycastResult res = g_scene.RaycastClosest(p, xy(b.GetPosition()), ~0, type);
     UnitPtr res_unit = res.FetchUnit(g_scene);
     if (!res_unit.IsValid())
         return true;
     return (res_unit == b);
 }
rayCanSeeWithoutUnit()
bool rayCanSeeWithoutUnit (vec2 p, UnitPtr b, UnitPtr unitIgnore, uint slots = ~0, RaycastType type = RaycastType::Aim)
Definition at line 604 of file Functions.as.
References g_scene, rayClosestWithoutUnit(), type, and xy().
Referenced by Update().
 {
     RaycastResult res = rayClosestWithoutUnit(p, xy(b.GetPosition()), slots, type, unitIgnore);
     UnitPtr res_unit = res.FetchUnit(g_scene);
     if (!res_unit.IsValid())
         return true;
     return (res_unit == b);
 }
rayClosestFromUnit()
RaycastResult rayClosestFromUnit (UnitPtr unit, vec2 toPos, uint slots, RaycastType type)
Definition at line 559 of file Functions.as.
References rayClosestWithoutUnit(), type, unit, and xy().
Referenced by TestDirection().
 {
     return rayClosestWithoutUnit(xy(unit.GetPosition()), toPos, slots, type, unit);
 }
rayClosestWithoutUnit()
RaycastResult rayClosestWithoutUnit (vec2 fromPos, vec2 toPos, uint slots, RaycastType type, UnitPtr unit)
Definition at line 564 of file Functions.as.
References g_scene, type, and unit.
Referenced by rayCanSeeWithoutUnit(), and rayClosestFromUnit().
 {
     array<RaycastResult>@ res = g_scene.Raycast(fromPos, toPos, slots, type);
     for (uint i = 0; i < res.length(); i++)
     {
         if (res[i].FetchUnit(g_scene) != unit)
             return res[i];
     }
     RaycastResult ret;
     return ret;
 }
rayQuickFromUnit()
bool rayQuickFromUnit (UnitPtr unit, vec2 toPos, uint slots, RaycastType type)
Definition at line 542 of file Functions.as.
References rayQuickWithoutUnit(), type, unit, and xy().
Referenced by CirclingMovement::Update().
 {
     return rayQuickWithoutUnit(xy(unit.GetPosition()), toPos, slots, type, unit);
 }
rayQuickWithoutUnit()
bool rayQuickWithoutUnit (vec2 fromPos, vec2 toPos, uint slots, RaycastType type, UnitPtr unit)
Definition at line 547 of file Functions.as.
References g_scene, type, and unit.
Referenced by rayQuickFromUnit().
 {
     array<RaycastResult>@ res = g_scene.Raycast(fromPos, toPos, slots, type);
     for (uint i = 0; i < res.length(); i++)
     {
         UnitPtr hitUnit = res[i].FetchUnit(g_scene);
         if (hitUnit != unit)
             return true;
     }
     return false;
 }
RichPresenceGetActName()
string RichPresenceGetActName (int levelCount)
Definition at line 724 of file Functions.as.
References CalcLevel().
Referenced by DungeonLevelRichPresence(), ShortcutLevel::Start(), and BossLevel::Start().
 {
     ivec3 level = CalcLevel(levelCount);
     switch (level.x)
     {
         case 0: return "Mines";
         case 1: return "Prison";
         case 2: return "Armory";
         case 3: return "Archives";
         case 4: return "Chambers";
         case 5: return "Battlements";
         case 6: return "Top";
     }
     return "";
 }
roll_round()
int roll_round (float f)
Definition at line 625 of file Functions.as.
References abs().
Referenced by Player::DamagedActor(), LifestealDamage::DoDamage(), GiveOreImpl(), WorldScript::HealUnits::ServerExecute(), and RandomLootManager::Update().
 {
     int v = abs(int(f));
     if (randf() < (f - v))
         v++;
     return (f < 0) ? -v : v;
 }
rottowards()
float rottowards (float source, float target, float amount)
Definition at line 130 of file Functions.as.
References abs(), capangle(), and min().
 {
     source = capangle(source);
     target = capangle(target);
     float difference = abs(source - target);
     amount = min(amount, difference % PI);
     if (difference < PI && target > source) return source + amount;
     if (difference < PI && target < source) return source - amount;
     if (difference > PI && target > source) return source - amount;
     if (difference > PI && target < source) return source + amount;
     if (difference == PI || difference == 0) return source + amount;
     return source;
 }
sign() [1/2]
int sign (const int v)
Definition at line 81 of file Functions.as.
Referenced by ArmoryGenerator::MakeRoomLine().
 {
     if (v < 0) return -1;
     if (v > 0) return 1;
     return 0;
 }
sign() [2/2]
int sign (const float v)
Definition at line 88 of file Functions.as.
 {
     if (v < 0) return -1;
     if (v > 0) return 1;
     return 0;
 }
strCommandLineParse()
array<string> strCommandLineParse (string str, bool bUseLiterals = true)
Definition at line 418 of file Functions.as.
 {
     array<string> ret;
     string buffer = "";
     bool inStr = false;
     for (uint i = 0; i < str.length(); i++)
     {
         string c = str.substr(i, 1);
         // literals
         if (c == "\\")
         {
             if (bUseLiterals)
             {
                 if (i + 1 < str.length())
                     buffer += c;
             }
             else
                 buffer += "\\";
         }
         // strings
         else if (c == "\"")
         {
             if (inStr)
             {
                 // string ends
                 inStr = false;
                 ret.insertLast(buffer);
                 buffer = "";
                 if (i + 1 < str.length() && str.substr(i + 1, 1) == " ")
                     i++;
             }
             else
             {
                 // string starts
                 inStr = true;
             }
         }
         // words
         else if (c == " ")
         {
             if (inStr)
                 buffer += " ";
             else
             {
                 ret.insertLast(buffer);
                 buffer = "";
             }
         }
         // characters
         else
             buffer += c;
     }
     // last word
     if (buffer != "")
         ret.insertLast(buffer);
     return ret;
 }
strCountWords()
int strCountWords (string str)
Definition at line 397 of file Functions.as.
References strTrim().
 {
     int ret = 0;
     int chars = 0;
     str = strTrim(str);
     auto space = " "[0];
     for (uint i = 0; i < str.length(); i++)
     {
         if (str[i] == space)
         {
             ret++;
             chars = 0;
         }
         else
             chars++;
     }
     if (chars > 0)
         ret++;
     return ret;
 }
strTrim()
string strTrim (string str)
Definition at line 372 of file Functions.as.
Referenced by PlayerMenuCharacterTab::GetSingularTooltip(), PlayerMenuCharacterTab::GetTooltipText(), MainMenu::LobbyCreated(), Menu::InGameChat::OnFunc(), strCountWords(), and PlayerMenuCharacterTab::UpdateFromRecord().
 {
     if (str.isEmpty())
         return str;
     auto space = " "[0];
     auto newLine = "\n"[0];
     for (uint i = 0; i < str.length(); i++)
     {
         if (str[i] != space && str[i] != newLine)
         {
             str = str.substr(i);
             break;
         }
     }
     for (int i = int(str.length()) - 1; i >= 0; i--)
     {
         if (str[i] != space && str[i] != newLine)
         {
             str = str.substr(0, i + 1);
             break;
         }
     }
     return str[0] != space ? str : "";
 }
toRoman()
string toRoman (int num)
Definition at line 515 of file Functions.as.
References num.
 {
     array<string> m = { "", "M", "MM", "MMM" };
     array<string> c = { "", "C", "CC", "CCC", "CD", "D", "DC", "DCC", "DCCC", "CM" };
     array<string> x = { "", "X", "XX", "XXX", "XL", "L", "LX", "LXX", "LXXX", "XC" };
     array<string> i = { "", "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX" };
     return m[num / 1000] + c[(num % 1000) / 100] + x[(num % 100) / 10] + i[num % 10];
 }
UcFirst()
string UcFirst (string str)
Definition at line 716 of file Functions.as.
Referenced by DiscordPresence::Update().
 {
     if (str == "")
         return "";
     return str.substr(0, 1).toUpper() + str.substr(1);
 }
xy() [1/2]
vec2 xy (vec3 v)
Definition at line 95 of file Functions.as.
Referenced by BaseGameMode::AddPlayer(), ShootRandomEnemy::Apply(), ShootBolt::Apply(), ShootProjectile::Apply(), DangerAreaBehavior::ApplyDamage(), ActorBuff::Attach(), ChargeMovement::BeginCharging(), ChargeMovement::BeginLooking(), Player::BlockProjectile(), CompositeActorSkill::CalcAimDir(), WhirlwindSkill::CancelSkill(), JumpStrike::CancelSkill(), NovaSkill::CanSee(), WhirlwindSkill::CanSee(), BlinkSkill::CanSee(), JumpStrike::CanSee(), SpewSkill::CanSee(), CompositeActorSkill::CanSee(), BlinkSkill::CastBlink(), MeleeMovement::ClientUpdate(), Pickup::Collide(), TransferDamageActor::Damage(), Damage(), Player::DamagedActor(), DelayedBreakable::DamageEffects(), SimpleBreakable::DamageEffects(), Breakable::DamageEffects(), Modifiers::Thorns::DamageTaken(), Modifiers::FlameShield::DamageTakenMul(), WorldScript::BossLichRoom::DebugDraw(), CannonBall::Destroyed(), Skills::Shatter::Do(), RaiseMagicTiles::DoAction(), MeleeHit::DoAction(), ShootProjectile::DoAction(), Skills::ShootRay::DoActivate(), Skills::SpawnUnit::DoActivate(), Skills::DoActivate(), Skills::ShootProjectile::DoActivate(), BombBehavior::DoExplode(), Explode::DoExplosion(), Skills::DropEffect::DoExplosion(), Skills::Explode::DoExplosion(), Skills::ChargeUnit::DoShoot(), Skills::Explode::DoTrigger(), Skills::StaggeredSpawnUnits::DoUpdate(), Skills::Whirlwind::DoUpdate(), Skills::TempBuffAoe::DoUpdate(), Skills::Whirlnova::DoUpdate(), Skills::BuffAoe::DoUpdate(), Skills::MeleeSwing::DoUpdate(), Skills::Charge::DoUpdate(), Skills::DoUpdate(), BossLichMovement::DoWalkPaths(), BossVampireMovement::DoWalkPaths(), FetchOffsetPos(), NovaSkill::FireProjectiles(), BaseGameMode::GetCameraPos(), BossLich::GetCastDirection(), BossVampire::GetCastDirection(), CirclingMovement::GetMoveDir(), Skills::GetMoveDir(), Skills::CelestialOrb::GetOrbPosition(), Skills::CelestialOrb::GetOwnerPosition(), Skills::CelestialOrb::GetTargetPosition(), Skills::HandleBeam(), Skills::HandleHitUnit(), SorcererProjectile::HitUnit(), Skills::SpewProjectiles::Hold(), MeleeMovement::IdleUpdate(), EffectBehavior::Initialize(), CompositeActorPeriodicTriggeredSkill::Initialize(), RayProjectile::Initialize(), CannonBall::Initialize(), WorldScript::BossLichRoom::IsInside(), RangedMovement::IsStandPosValid(), MeleeMovement::MeleeMovement(), RangerProjectile::Multiply(), Skills::Shatter::NetDo(), ShootProjectile::NetDoAction(), Skills::SpawnUnit::NetDoActivate(), Skills::ShootProjectile::NetDoActivate(), BombBehavior::NetDoExplode(), Skills::SpewProjectiles::NetHold(), BossVampireMovement::NetOnNodeArrived(), PlayerCorpse::NetRevive(), UnitHandler::NetSendUnitUseSkill(), Modifiers::TriggerEffect::NetTrigger(), Skills::Explode::NetTrigger(), EnemyMeleeStrike::NetUseSkill(), TowerFlowerSkill::NetUseSkill(), CompositeActorSkill::NetUseSkill(), SpewSkill::NetUseSkill(), BlinkSkill::NetUseSkill(), NetUseSkill(), BossScatterBurstSkill::NewBurstShot(), WerebullChargeHitSkill::OnCollide(), JumpStrike::OnCollide(), ActorBuff::OnDeath(), PlayerBase::OnDeath(), Skills::DropEffect::OnDropped(), WorldScript::Teleport::OnEnabledChanged(), Skills::Shatter::OnEnemyKilled(), WorldScript::Teleport::OnEnter(), WorldScript::RandomBuff::OnFunc(), PlayerMenuMapTab::OnShow(), Pickup::Picked(), PlayerHandler::PlayerDamage(), PlayerHandler::PlayerDamaged(), PlayerHusk::PlayerHusk(), PostLoad(), WorldScript::Wind::PostUpdate(), WorldScript::SpawnUnitWithEffect::ProduceUnitEffects(), QueuedFetchActors(), rayCanSee(), rayCanSeeWithoutUnit(), rayClosestFromUnit(), rayQuickFromUnit(), BaseGameMode::RenderFrame(), BaseGameMode::SavePlayer(), RangedMovement::SeesTarget(), Player::SendPlayerMove(), WorldScript::SpawnEnemyGroup::ServerExecute(), WorldScript::ExploreMinimap::ServerExecute(), WorldScript::SpawnPrefab::ServerExecute(), WorldScript::SpawnUnit::ServerExecute(), WorldScript::SpawnUnitAsLoot::ServerExecute(), WorldScript::SpawnEffect::ServerExecute(), WorldScript::SpawnGore::ServerExecute(), WorldScript::CheckSpawnDistance::ServerExecute(), WorldScript::DamageUnits::ServerExecute(), SetTarget(), RandomLootManager::SpawnDrinkBarrel(), Skills::DropEffect::SpawnDropEffect(), RandomLootManager::SpawnDyeBucket(), WorldScript::RefreshSpawnPickup::SpawnEffects(), WorldScript::SurvivalEnemySpawn::SpawnEffects(), WorldScript::SurvivalEnemyDropSpawn::SpawnEffects(), RandomLootManager::SpawnForgeBlueprint(), BaseGameMode::SpawnPlayer(), BaseGameMode::SpawnPlayerCorpse(), BaseGameMode::Start(), ActorFootsteps::StepEffect(), TargetValue(), TestDirection(), DangerArea::TickDamage(), DangerAreaBehavior::TickDamage(), PriestGroundCircle::Trigger(), Modifiers::TriggerEffect::Trigger(), Trigger(), Skills::RiposteTrigger::TriggerEffects(), TriggerOnDeath(), Update(), Menu::GraphicsMenu::Update(), Modifiers::AuraCone::Update(), BossLichRandomSkill::Update(), Modifiers::Aura::Update(), LurkerProjectile::Update(), SafetyAreaBehavior::Update(), CirclingMovement::Update(), EffectSpawner::Update(), TowerFlowerSpike::Update(), CompositeActorBurstSkill::Update(), CompositeActorPeriodicTriggeredSkill::Update(), CompositeActorAuraSkill::Update(), TripMine::Update(), RangedMovement::Update(), TargetMovement::Update(), Skills::CelestialOrb::Update(), BlinkSkill::Update(), DropSpawnBehavior::Update(), MagicTile::Update(), Projectile::Update(), MeleeSwing::Update(), WhirlNovaSkill::Update(), EnemyMeleeStrike::Update(), FixedPathFollower::Update(), WhirlwindSkill::Update(), ChargeMovement::Update(), JumpStrike::Update(), SpewSkill::Update(), Gib::Update(), ActorBuff::Update(), CompositeActorSkill::Update(), MeleeMovement::Update(), PlayerBase::Update(), Player::Update(), Campaign::UpdateFrame(), BaseGameMode::UpdateFrame(), Widget::UpdateInput(), IngameMouse::UpdateMouseColor(), and Chest::Use().
 {
     return vec2(v.x, v.y);
 }
xy() [2/2]
vec2 xy (vec4 v)
Definition at line 100 of file Functions.as.
 {
     return vec2(v.x, v.y);
 }
xyz() [1/3]
vec3 xyz (vec4 v)
Definition at line 105 of file Functions.as.
Referenced by ShootRandomEnemy::Apply(), Skills::CelestialOrb::BeamStart(), BlinkSkill::CastBlink(), Projectile::Collide(), PlaySound::Do(), Skills::ShootRay::DoActivate(), Skills::DropUnit::DoActivate(), Skills::DoActivate(), Nova::DoNova(), Skills::ChargeUnit::DoShoot(), DoSpawnPrefabBase(), DoSpawnUnit(), Skills::Whirlnova::DoUpdate(), SpawnPrefabBaseTask::Execute(), NovaSkill::FireProjectiles(), BaseGameMode::GetCameraPos(), ActorFootsteps::GetFootPosition(), SorcererOrbProjectile::HitUnit(), SorcererProjectile::HitUnit(), RangerProjectile::HitUnit(), RayProjectile::HitUnit(), Skills::StaggeredSpawnUnits::LocalSpawnUnit(), Skills::SpawnUnit::LocalSpawnUnit(), EnemyPlacement::MakeDir(), RangerProjectile::Multiply(), NetDoAction(), Skills::ShootRay::NetDoActivate(), Skills::NetDoActivate(), RandomLootManager::NetSpawnDrinkBarrel(), RandomLootManager::NetSpawnDyeBucket(), RandomLootManager::NetSpawnItemBlueprint(), TowerFlowerSkill::NetUseSkill(), PlayerBase::OnDeath(), EnemyPlacement::PlaceGroup(), PlayerHandler::PlayerPing(), Skills::Charge::PlayHitEffect(), AttachedUnit::PreRender(), BossEyeWisp::PreRender(), BaseGameMode::PreRenderFrame(), HwShootProjectile::ProduceProjectile(), ShootProjectile::ProduceProjectile(), Skills::ShootProjectile::ProduceProjectile(), Skills::SpewProjectiles::ProduceProjectile(), WorldScript::AttachNewUnit::ProduceUnit(), ResolveDecal(), ResolveGibs(), BossEyeWisp::Set(), GraniteMineBrush::SpawnBreakablePlant(), SandCaveBrush::SpawnBreakablePlant(), Skills::DropEffect::SpawnDropEffect(), EnemyPlacement::SpawnGroup(), BaseGameMode::SpawnPlayer(), BaseGameMode::SpawnPlayerCorpse(), UnitHandler::SpawnUnit(), SpawnUnitBaseImpl(), Skills::ScorchedEarth::Trigger(), UnitHandler::UnitMovementChargeBegin(), UnitHandler::UnitMovementChargeLook(), UnitHandler::UnitTeleported(), TargetMovement::Update(), Skills::CelestialOrb::Update(), WhirlNovaSkill::Update(), SpewSkill::Update(), MeleeMovement::Update(), and Campaign::UpdateFrame().
 {
     return vec3(v.x, v.y, v.z);
 }
xyz() [2/3]
vec3 xyz (vec2 v)
Definition at line 110 of file Functions.as.
 {
     return vec3(v.x, v.y, 0);
 }
xyz() [3/3]
vec3 xyz (vec2 v, float z)
Definition at line 115 of file Functions.as.
 {
     return vec3(v.x, v.y, z);
 }
xyzw()
vec4 xyzw (vec3 v, float w)
Definition at line 120 of file Functions.as.
Referenced by MainMenu::DrawPlayerColorPicking(), and Update().
 {
     return vec4(v.x, v.y, v.z, w);
 }