HoHDocs: scripts/WorldScript/AreaTrigger.as File Reference
AreaTrigger.as File Reference
Classes
class AreaTrigger
Enumerations
enum AreaFilter
Functions
enum AreaFilter ApplyAreaFilter (UnitPtr unit, AreaFilter filter)
Variables
enum AreaFilter OnEnter = 1
NeutralActor = 1
PlayerActor = 2
EnemyActor = 4
PlayerProjectile = 8
EnemyProjectile = 16
TrapProjectile = 32
Other = 64
Enumeration Type Documentation
AreaFilter
enum AreaFilter
Definition at line 1 of file AreaTrigger.as.
 {
     NeutralActor        = 1,
     PlayerActor         = 2,
     EnemyActor          = 4,
     PlayerProjectile    = 8,
     EnemyProjectile     = 16,
     TrapProjectile      = 32,
     Other               = 64
 }
Function Documentation
ApplyAreaFilter()
enum AreaFilter ApplyAreaFilter (UnitPtr unit, AreaFilter filter)
Definition at line 20 of file AreaTrigger.as.
References EnemyActor, EnemyProjectile, g_team_none, g_team_player, NeutralActor, Other, PlayerActor, PlayerProjectile, Actor::Team, TrapProjectile, type, and unit.
Referenced by WorldScript::Teleport::OnEnabledChanged(), AreaTrigger::OnEnabledChanged(), WorldScript::Teleport::OnEnter(), AreaTrigger::OnEnter(), and AreaTrigger::OnExit().
     {
         if (!unit.IsValid())
             return false;
         ref@ behavior = unit.GetScriptBehavior();
         if (behavior is null)
             return false;
         AreaFilter type = AreaFilter::Other;
         Actor@ actor = cast<Actor>(behavior);
         if (actor !is null)
         {
             if (actor.Team == g_team_none)
                 type = AreaFilter::NeutralActor;
             else if (actor.Team == g_team_player)
                 type = AreaFilter::PlayerActor;
             else
                 type = AreaFilter::EnemyActor;
         }
         else
         {
             IProjectile@ proj = cast<IProjectile>(behavior);
             if (proj !is null)
             {
                 if (proj.Team == g_team_none)
                     type = AreaFilter::TrapProjectile;
                 else if (proj.Team == g_team_player)
                     type = AreaFilter::PlayerProjectile;
                 else
                     type = AreaFilter::EnemyProjectile;
             }
         }
         return type & filter != 0;
     }
Variable Documentation
EnemyActor
EnemyActor = 4
Definition at line 81 of file AreaTrigger.as.
Referenced by ApplyAreaFilter().
EnemyProjectile
EnemyProjectile = 16
Definition at line 83 of file AreaTrigger.as.
Referenced by ApplyAreaFilter().
NeutralActor
NeutralActor = 1
Definition at line 79 of file AreaTrigger.as.
Referenced by ApplyAreaFilter().
OnEnter
enum AreaFilter OnEnter = 1
Referenced by AreaTrigger::OnEnabledChanged(), and AreaTrigger::OnEnter().
Other
Other = 64
Definition at line 85 of file AreaTrigger.as.
Referenced by ApplyAreaFilter().
PlayerActor
PlayerActor = 2
Definition at line 80 of file AreaTrigger.as.
Referenced by ApplyAreaFilter().
PlayerProjectile
PlayerProjectile = 8
Definition at line 82 of file AreaTrigger.as.
Referenced by ApplyAreaFilter().
TrapProjectile
TrapProjectile = 32
Definition at line 84 of file AreaTrigger.as.
Referenced by ApplyAreaFilter().