HoHDocs: system/engine.as File Reference
engine.as File Reference
Classes
class GameSaveInfo
class ScenarioInfo
class ButtonState
class MenuInput
class ControlMap
class PlatformCursor
class PlayerLoadState
class Discord::Status
Namespaces
HwrSaves
Platform
Saves
Discord
Enumerations
enum GameDifficulty
enum ScenarioModificationVisual
enum TextInputControlEventType {
Home, End, Left, Right,
LeftWord, RightWord, Backspace, Delete,
Tab, Submit, Cancel, Copy,
Paste, Cut, Up, Down
}
enum GemState
Functions
% if EDITOR_GAME EDITOR vec2 ToScreenspace (vec3 pos)
vec3 ToWorldspace (vec2 pos)
void EnableMod (uint32 id)
void DisableMod (uint32 id)
void Write ()
bool HwrSaves::IsSaving ()
void HwrSaves::CreateCharacter (SValue@ char)
array< SValue@> HwrSaves::GetCharacters ()
void HwrSaves::PickCharacter (int index)
void HwrSaves::DeleteCharacter (int index)
void HwrSaves::SaveTownAndCharacter (SValue@ town, SValue@ character, bool saveLevel)
SValue HwrSaves::LoadHostTown ()
void HwrSaves::DeleteTown (int slot)
void HwrSaves::CopyTown (int slot, int newSlot, bool withChars=true)
SValue HwrSaves::LoadLocalTown ()
SValue HwrSaves::LoadCharacter (int peer=-1)
array< SaveSlot@> HwrSaves::GetSaveSlots ()
SaveSlot HwrSaves::CreateSlot (int num)
array< ResourceMod@> HwrSaves::GetEnabledMods ()
void RenderScene (int idt, vec2 pos, vec4 vignette)
void StartGame (int numPlrs, string level)
void ChangeLevel (string level)
void QuitGame ()
void ResumeGame ()
void StopScenario ()
string GetCurrentLevelFilename ()
string GetCurrentLevelName ()
int GetRestartCount ()
void SetRestartCount (int count)
void SendSystemMessage (const string &in name, SValue@ data)
void RestartMenu ()
uint64 GetUniquePeerId (uint8 peer)
void RumbleGamepad (float strength, int length)
void RumbleGamepadStop ()
void PlayAsMusic (int channel, SoundEvent@ event)
void PauseGame (bool paused, bool localOnly)
bool IsPaused ()
uint64 CurrPlaytimeLevel ()
uint64 CurrPlaytimeTotal ()
enum GameDifficulty GetName ()
string GetLevel ()
enum ScenarioModificationVisual GetVisual ()
string GetID ()
string GetTooltip ()
string GetLockedBy ()
bool GetDefaultOn ()
string GetRadioGroup ()
bool GetMultiplayer ()
class ScenarioInfo get_ID ()
TempTexture2D LoadLogos ()
string GetTag ()
string GetDescription ()
bool Multiplayer ()
bool Official ()
bool Packaged ()
bool Workshop ()
array< ScenarioStartLevel@> GetStartLevels ()
array< ScenarioModification@> GetModifications ()
int MinPlayers ()
int MaxPlayers ()
string get_Name ()
string get_Author ()
string get_Description ()
SValue get_Data ()
bool get_Packaged ()
uint64 get_WorkshopID ()
array< ControlMap@> GetControlMaps ()
ControlMap GetCurrentMap ()
int GetTextInputCount ()
TextInputControlEvent GetTextInput (int)
class ControlMap Save ()
bool get_SteamController ()
uint64 get_Handle ()
array< ControlMapBinding@> GetBindings ()
array< ControlMapBinding@> GetStaging ()
void Clear ()
void Remove (ControlMapBinding@ bind)
void Add (ControllerType type, int key, const string &in action)
void ClearStaging ()
void RemoveStaging (ControlMapBinding@ bind)
void AddStaging (ControllerType type, int key, const string &in action)
void AddStagingAxis (ControllerType type, int key, const string &in action, ControlBindingSetAxis setAxis)
void BeginStaging ()
void CommitStaging ()
void Defaults ()
ControlMap GetMap (const string &in id)
array< ControlMap@> GetMaps ()
bool IsExpectingTextInput ()
void ExpectTextInput ()
void StopExpectTextInput ()
void ExpectInput ()
void AssignControls (int numSessions)
void UnassignAll ()
void Assign (int player, ControlMap@ map)
array< string > GetAvailableActions ()
ControlBindings GetControlBindings ()
void Platform::HideCursor ()
void Platform::ShowCursor ()
vec2 Platform::GetMousePosition ()
int Platform::GetInputCount ()
GameInput Platform::GetGameInput (int index)
MenuInput Platform::GetMenuInput (int index)
int Platform::GetSessionCount ()
array< ivec2 > Platform::GetResolutions ()
array< LanguageInfo > Platform::GetLanguages ()
void Platform::OpenUrl (const string &in url)
ButtonState Platform::GetKeyState (int button)
array< ScenarioInfo@> Platform::GetAllScenarios ()
ScenarioInfo Platform::GetScenario (const string &in id)
ScenarioInfo Platform::GetScenario (uint32 id)
array< ResourceMod@> Platform::GetAllResourceMods ()
ResourceMod Platform::GetResourceMod (const string &in id)
ResourceMod Platform::GetResourceMod (uint32 id)
class PlayerLoadState GetLobbyId ()
bool CanOpenProfile (uint8 peer)
void OpenProfile (uint8 peer)
bool IsInLobby ()
void CreateLobby ()
void JoinLobby (uint64 id)
void LeaveLobby ()
void SendChatMessage (string msg)
string GetPlayerName (uint8 peer)
string GetPlayerSkin (uint8 peer)
int GetPlayerPing (uint8 peer)
int GetHostPing (uint8 peer)
bool IsPlayerHost (uint8 peer)
bool IsPlayerLocal (uint8 peer)
int GetLocalPeer ()
void SetPrivate (bool priv)
void SetJoinable (bool joinable)
void KickPlayer (uint8 peer)
void SetLevel (string level)
void StartGame ()
void ListLobbies ()
void SetLobbyData (const string &in key, const string &in value)
string GetLobbyData (uint64 id, const string &in key)
string GetLobbyData (const string &in key)
void SetLobbyMemberData (const string &in key, const string &in value)
string GetLobbyMemberData (uint8 peer, const string &in key)
uint8 GetLobbyMemberDownloadProgress (uint8 peer)
int GetLobbyPing (uint64 id)
int GetLobbyPlayerCount ()
int GetLobbyPlayerCount (uint64 id)
int GetLobbyPlayerCountMax ()
int GetLobbyPlayerCountMax (uint64 id)
GameDifficulty GetDifficulty ()
array< string > GetModifiers ()
void SetPlayerLimit (int max)
void SetGemState (GemState state)
array< PlayerLoadState > GetPlayerLoadStates ()
array< string > Saves::GetSaves ()
GameSaveInfo Saves::ReadInfo (string filename)
bool Saves::Load (string filename)
void Saves::Rename (string filename, string newname)
void Saves::Delete (string filename)
enum GemState OPT_FindAllPatterns (ref pattern, ref grid, ref gridConsumed)
class Discord::Status Discord::IsReady ()
bool opEquals (const Status &in other)
void opAssign (const Status &in copy)
void Discord::SetStatus (const Status &in)
Variables
class GameSaveInfo Slot
SValue Town
bool Modded
array< uint32 > EnabledMods
Easy = 1
Normal = 2
Hard = 4
Serious = 8
None
Separator
Header
class ButtonState Attack1
ButtonState Attack2
ButtonState Attack3
ButtonState Attack4
ButtonState Use
ButtonState Potion
ButtonState PlayerMenu
ButtonState GuildMenu
ButtonState MapOverlay
ButtonState Ping
vec2 MoveDir
vec2 AimDir
vec2 MousePos
int MouseWheelDelta
bool Assigned
bool UsingGamepad
bool UsingMouseLook
class MenuInput StartGame
class MenuInput Continue
class MenuInput LoadGame
class MenuInput MainMenu
class MenuInput InGameMenu
class MenuInput Saved
class MenuInput Keyboard
class MenuInput Mouse
class MenuInput MouseWheel
class MenuInput Gamepad
class MenuInput GamepadAxis
class MenuInput GamepadVector
class MenuInput Joystick
class MenuInput JoystickAxis
class MenuInput JoystickVector
class MenuInput Low
class MenuInput ID
string Action
ControlBindingSetAxis SetAxis
int Index
bool UseMouseLook
bool SteamController
string Name
uint8 Peer
uint8 Progress
enum TextInputControlEventType text
TextInputControlEventType evt
bool select
Inactive = 0
Active = 1
Perfect = 10
Moo = 100
string State
string Details
int64 StartTimestamp
int64 EndTimestamp
string LargeImageKey
string LargeImageText
string SmallImageKey
string SmallImageText
string PartyId
int PartySize
int PartyMax
string MatchSecret
string JoinSecret
string SpectateSecret
Enumeration Type Documentation
GameDifficulty
enum GameDifficulty
Definition at line 74 of file engine.as.
 {
     Easy    = 1,
     Normal  = 2,
     Hard    = 4,
     Serious = 8
 }
GemState
enum GemState
Definition at line 416 of file engine.as.
 {
     Inactive = 0,
     Active   = 1,
     Perfect  = 10,
     Moo      = 100
 }
ScenarioModificationVisual
enum ScenarioModificationVisual
Definition at line 88 of file engine.as.
 {
     None,
     Separator,
     Header,
 }
TextInputControlEventType
enum TextInputControlEventType
Enumerator
Home
End
Left
Right
LeftWord
RightWord
Backspace
Delete
Tab
Submit
Cancel
Copy
Paste
Cut
Up
Down
Definition at line 388 of file engine.as.
 {
     Home,
     End,
     Left,
     Right,
     LeftWord,
     RightWord,
     Backspace,
     Delete,
     Tab,
     Submit,
     Cancel,
     Copy,
     Paste,
     Cut,
     Up,
     Down,
     None
 }
Function Documentation
Add()
void Save::Add (ControllerType type, int key, const string &in action)
Definition at line 258 of file engine.as.
 { return null; }
AddStaging()
void Save::AddStaging (ControllerType type, int key, const string &in action)
Definition at line 262 of file engine.as.
 { }
AddStagingAxis()
void Save::AddStagingAxis (ControllerType type, int key, const string &in action, ControlBindingSetAxis setAxis)
Definition at line 263 of file engine.as.
 { }
Assign()
void Assign (int player, ControlMap@ map)
Definition at line 288 of file engine.as.
 { }
AssignControls()
void AssignControls (int numSessions)
Definition at line 286 of file engine.as.
 { }
BeginStaging()
void Save::BeginStaging ()
Definition at line 265 of file engine.as.
 { }
CanOpenProfile()
bool CanOpenProfile (uint8 peer)
Definition at line 341 of file engine.as.
Referenced by Menu::LobbyPlayersMenu::UpdatePlayer().
 { return false; }
ChangeLevel()
void ChangeLevel (string level)
Definition at line 55 of file engine.as.
Referenced by ShopMenu::Close(), HWRGameOver::OnFunc(), EndOfBeta::OnFunc(), EndOfGame::OnFunc(), OnFunc(), Upgrades::BuildingUpgradeStep::PayForUpgrade(), WorldScript::LevelExitNextAct::ServerExecute(), WorldScript::StartDungeon::ServerExecute(), and WorldScript::LevelExitNext::ServerExecute().
 {}
Clear()
void Save::Clear ()
Definition at line 256 of file engine.as.
 { return null; }
ClearStaging()
void Save::ClearStaging ()
Definition at line 260 of file engine.as.
 { }
CommitStaging()
void Save::CommitStaging ()
Definition at line 266 of file engine.as.
 { }
CreateLobby()
void CreateLobby ()
Definition at line 344 of file engine.as.
Referenced by Menu::HostMenu::OnFunc(), and Menu::FrontMenu::OnFunc().
 { }
CurrPlaytimeLevel()
uint64 CurrPlaytimeLevel ()
Definition at line 71 of file engine.as.
Referenced by ScoreDialog::Set().
 { return 0; }
CurrPlaytimeTotal()
uint64 CurrPlaytimeTotal ()
Definition at line 72 of file engine.as.
Referenced by ScoreDialog::Set().
 { return 0; }
Defaults()
void Save::Defaults ()
Definition at line 268 of file engine.as.
 { }
DisableMod()
void DisableMod (uint32 id)
Definition at line 29 of file engine.as.
 {}
EnableMod()
void EnableMod (uint32 id)
Definition at line 28 of file engine.as.
 {}
ExpectInput()
void ExpectInput ()
Definition at line 284 of file engine.as.
 { }
ExpectTextInput()
void ExpectTextInput ()
Definition at line 282 of file engine.as.
 { }
get_Author()
string get_Author ()
Definition at line 128 of file engine.as.
 { return ""; }
get_Data()
SValue get_Data ()
Definition at line 131 of file engine.as.
 { return null; }
get_Description()
string get_Description ()
Definition at line 129 of file engine.as.
 { return ""; }
get_Handle()
uint64 Save::get_Handle ()
Definition at line 251 of file engine.as.
 { return false; }
get_ID()
class ScenarioInfo get_ID ()
Definition at line 126 of file engine.as.
 { return ""; }
get_Name()
string get_Name ()
Definition at line 127 of file engine.as.
 { return ""; }
get_Packaged()
bool get_Packaged ()
Definition at line 133 of file engine.as.
 { return false; }
get_SteamController()
bool Save::get_SteamController ()
Definition at line 250 of file engine.as.
 { return false; }
get_WorkshopID()
uint64 get_WorkshopID ()
Definition at line 134 of file engine.as.
 { return 0; }
GetAvailableActions()
array<string> GetAvailableActions ()
Definition at line 290 of file engine.as.
 { return null; }
GetBindings()
array<ControlMapBinding@> Save::GetBindings ()
Definition at line 253 of file engine.as.
 { return false; }
GetControlBindings()
ControlBindings GetControlBindings ()
Definition at line 293 of file engine.as.
Referenced by Menu::InGameChat::BeginInput(), Menu::Close(), Menu::ControlsMenu::Initialize(), Menu::ControlMapMenu::Initialize(), MainMenu::MainMenu(), MenuControlInputWidget::OnClick(), Menu::ControlMapMenu::OnFunc(), Menu::SplitscreenSelectionMenu(), Menu::InGameChat::StopInput(), Tutorial::Update(), and Menu::InGameChat::Update().
 { return null; }
GetControlMaps()
array<ControlMap@> GetControlMaps ()
Definition at line 170 of file engine.as.
 { return null; }
GetCurrentLevelFilename()
string GetCurrentLevelFilename ()
Definition at line 59 of file engine.as.
Referenced by ShopMenu::Close(), DungeonRotation(), MapRotation::MapRotation(), and Upgrades::BuildingUpgradeStep::PayForUpgrade().
 { return ""; }
GetCurrentLevelName()
string GetCurrentLevelName ()
Definition at line 60 of file engine.as.
 { return ""; }
GetCurrentMap()
ControlMap GetCurrentMap ()
Definition at line 171 of file engine.as.
 { return null; }
GetDefaultOn()
bool GetDefaultOn ()
Definition at line 102 of file engine.as.
Referenced by Menu::SetStartScenario().
 { return false; }
GetDescription()
string get_ID::GetDescription ()
Definition at line 109 of file engine.as.
 { return null; }
GetDifficulty()
GameDifficulty GetDifficulty ()
Definition at line 372 of file engine.as.
References Normal.
 { return GameDifficulty::Normal; }
GetHostPing()
int GetHostPing (uint8 peer)
Definition at line 351 of file engine.as.
 { return -1; }
GetID()
string GetID ()
Definition at line 98 of file engine.as.
 { return ""; }
GetLevel()
string GetLevel ()
Definition at line 85 of file engine.as.
 { return ""; }
GetLobbyData() [1/2]
string GetLobbyData (uint64 id, const string &in key)
Definition at line 362 of file engine.as.
Referenced by MainMenu::LobbyInviteAccepted(), Menu::OnLobbyList(), DiscordPresence::Update(), and ServicePresence::Update().
 { return ""; }
GetLobbyData() [2/2]
string GetLobbyData (const string &in key)
Definition at line 363 of file engine.as.
 { return ""; }
GetLobbyId()
class PlayerLoadState GetLobbyId ()
Definition at line 340 of file engine.as.
Referenced by DiscordPresence::Update().
 { return 0; }
GetLobbyMemberData()
string GetLobbyMemberData (uint8 peer, const string &in key)
Definition at line 365 of file engine.as.
 { return ""; }
GetLobbyMemberDownloadProgress()
uint8 GetLobbyMemberDownloadProgress (uint8 peer)
Definition at line 366 of file engine.as.
 { return 0; }
GetLobbyPing()
int GetLobbyPing (uint64 id)
Definition at line 367 of file engine.as.
Referenced by Menu::OnLobbyList().
 { return -1; }
GetLobbyPlayerCount() [1/2]
int GetLobbyPlayerCount ()
Definition at line 368 of file engine.as.
Referenced by Menu::OnLobbyList(), DiscordPresence::Update(), ServicePresence::Update(), Menu::LobbyPlayersMenu::Update(), and Menu::LobbyPlayersMenu::UpdatePlayerList().
 { return 0; }
GetLobbyPlayerCount() [2/2]
int GetLobbyPlayerCount (uint64 id)
Definition at line 369 of file engine.as.
 { return 0; }
GetLobbyPlayerCountMax() [1/2]
int GetLobbyPlayerCountMax ()
Definition at line 370 of file engine.as.
Referenced by Menu::OnLobbyList(), and DiscordPresence::Update().
 { return 0; }
GetLobbyPlayerCountMax() [2/2]
int GetLobbyPlayerCountMax (uint64 id)
Definition at line 371 of file engine.as.
 { return 0; }
GetLocalPeer()
int GetLocalPeer ()
Definition at line 354 of file engine.as.
Referenced by Menu::LobbyPlayersMenu::GetPeerPing(), Menu::InGameChat::OnFunc(), and Menu::LobbyPlayersMenu::UpdatePlayer().
 { return -1; }
GetLockedBy()
string GetLockedBy ()
Definition at line 101 of file engine.as.
 { return ""; }
GetMap()
ControlMap GetMap (const string &in id)
Definition at line 279 of file engine.as.
 { return null; }
GetMaps()
array<ControlMap@> GetMaps ()
Definition at line 280 of file engine.as.
 { return null; }
GetModifications()
array<ScenarioModification@> get_ID::GetModifications ()
Definition at line 115 of file engine.as.
 { return false; }
GetModifiers()
array<string> GetModifiers ()
Definition at line 373 of file engine.as.
 { return null; }
GetMultiplayer()
bool GetMultiplayer ()
Definition at line 104 of file engine.as.
 { return false; }
GetName()
string GetName ()
Definition at line 84 of file engine.as.
Referenced by Stats::Accomplishment::OnUpdated().
 { return ""; }
GetPlayerLoadStates()
array<PlayerLoadState> GetPlayerLoadStates ()
Definition at line 376 of file engine.as.
Referenced by MainMenu::RenderFrameLoading().
 { return null; }
GetPlayerName()
string GetPlayerName (uint8 peer)
Definition at line 348 of file engine.as.
Referenced by Menu::HostMenu::Initialize(), Menu::LobbyPlayersMenu::OnFunc(), GameChatWidget::PlayerChat(), GameChatWidget::PlayerSystem(), MainMenu::RenderFrameLoading(), MultiplePlayersTab::UpdateNow(), and Menu::LobbyPlayersMenu::UpdatePlayer().
 { return ""; }
GetPlayerPing()
int GetPlayerPing (uint8 peer)
Definition at line 350 of file engine.as.
Referenced by Menu::LobbyPlayersMenu::GetPeerPing(), ShootHitscan(), and ShootSpreadHitscan().
 { return -1; }
GetPlayerSkin()
string GetPlayerSkin (uint8 peer)
Definition at line 349 of file engine.as.
 { return ""; }
GetRadioGroup()
string GetRadioGroup ()
Definition at line 103 of file engine.as.
 { return ""; }
GetRestartCount()
int GetRestartCount ()
Definition at line 61 of file engine.as.
Referenced by ScoreDialog::Set().
 { return 0; }
GetStaging()
array<ControlMapBinding@> Save::GetStaging ()
Definition at line 254 of file engine.as.
 { return false; }
GetStartLevels()
array<ScenarioStartLevel@> get_ID::GetStartLevels ()
Definition at line 114 of file engine.as.
 { return false; }
GetTag()
string get_ID::GetTag ()
Definition at line 107 of file engine.as.
 {
GetTextInput()
TextInputControlEvent GetTextInput (int)
Definition at line 173 of file engine.as.
 { return null; }
GetTextInputCount()
int GetTextInputCount ()
Definition at line 172 of file engine.as.
 { return 0; }
GetTooltip()
string GetTooltip ()
Definition at line 100 of file engine.as.
 { return ""; }
GetUniquePeerId()
uint64 GetUniquePeerId (uint8 peer)
Definition at line 65 of file engine.as.
Referenced by BaseGameMode::ActivatePlayerRecord().
 { return 0; }
GetVisual()
enum ScenarioModificationVisual GetVisual ()
Definition at line 97 of file engine.as.
References None.
 { return ScenarioModificationVisual::None; }
IsExpectingTextInput()
bool IsExpectingTextInput ()
Definition at line 281 of file engine.as.
 { return false; }
IsInLobby()
bool IsInLobby ()
Definition at line 343 of file engine.as.
Referenced by Menu::InGameChat::Initialize(), Menu::FrontMenu::Initialize(), DungeonSettingsMenu::OnFunc(), DungeonSettingsMenu::OnNgpChanged(), HUDCoop::ShouldShow(), Campaign::Start(), DiscordPresence::Update(), ServicePresence::Update(), Menu::LobbyPlayersMenu::UpdatePlayerList(), and Campaign::UpdateWidgets().
 { return false; }
IsPaused()
bool IsPaused ()
Definition at line 70 of file engine.as.
Referenced by Draw(), BaseGameMode::DrawFloatingTexts(), AttachedUnit::PreRender(), BossEyeWisp::PreRender(), and BaseGameMode::ShouldDisplayCursor().
 { return false; }
IsPlayerHost()
bool IsPlayerHost (uint8 peer)
Definition at line 352 of file engine.as.
Referenced by Menu::LobbyPlayersMenu::GetPeerPing(), and Menu::LobbyPlayersMenu::UpdatePlayer().
 { return false; }
IsPlayerLocal()
bool IsPlayerLocal (uint8 peer)
Definition at line 353 of file engine.as.
Referenced by BaseGameMode::ActivatePlayerRecord(), BaseGameMode::AddPlayer(), MainMenu::ChatMessage(), and BaseGameMode::GetPlayerSave().
 { return false; }
JoinLobby()
void JoinLobby (uint64 id)
Definition at line 345 of file engine.as.
Referenced by Menu::HwrMenu::FinishContext(), and Menu::OnFunc().
 { }
KickPlayer()
void KickPlayer (uint8 peer)
Definition at line 357 of file engine.as.
Referenced by Menu::LobbyPlayersMenu::OnFunc().
 { }
LeaveLobby()
void LeaveLobby ()
Definition at line 346 of file engine.as.
 { }
ListLobbies()
void ListLobbies ()
Definition at line 360 of file engine.as.
Referenced by Menu::Initialize(), Menu::OnFunc(), and Menu::Show().
 { }
LoadLogos()
TempTexture2D get_ID::LoadLogos ()
Definition at line 105 of file engine.as.
 {
MaxPlayers()
int get_ID::MaxPlayers ()
Definition at line 117 of file engine.as.
 { return false; }
MinPlayers()
int get_ID::MinPlayers ()
Definition at line 116 of file engine.as.
 { return false; }
Multiplayer()
bool get_ID::Multiplayer ()
Definition at line 110 of file engine.as.
 { return ""; }
Official()
bool get_ID::Official ()
Definition at line 111 of file engine.as.
 { return ""; }
opAssign()
void IsReady::opAssign (const Status &in copy)
Definition at line 436 of file engine.as.
 { return true; }
OpenProfile()
void OpenProfile (uint8 peer)
Definition at line 342 of file engine.as.
Referenced by Menu::LobbyPlayersMenu::OnFunc().
 { }
opEquals()
bool IsReady::opEquals (const Status &in other)
Definition at line 435 of file engine.as.
 { return true; }
OPT_FindAllPatterns()
enum GemState OPT_FindAllPatterns (ref pattern, ref grid, ref gridConsumed)
Definition at line 426 of file engine.as.
Referenced by FindAllPatterns().
 { return null; }
Packaged()
bool get_ID::Packaged ()
Definition at line 112 of file engine.as.
Referenced by Menu::FrontMenu::Initialize().
 { return ""; }
PauseGame()
void PauseGame (bool paused, bool localOnly)
Definition at line 69 of file engine.as.
Referenced by PlayerMenu::Close(), GuildHallMenu::Close(), ShopMenu::Close(), HWRGameOver::OnFunc(), GameOver::OnFunc(), PlayerMenu::Show(), GuildHallMenu::Show(), ShopMenu::Show(), and Campaign::UpdateWidgets().
 {}
PlayAsMusic()
void PlayAsMusic (int channel, SoundEvent@ event)
Definition at line 68 of file engine.as.
Referenced by WorldScript::PlayMusic::ServerExecute().
 {}
QuitGame()
void QuitGame ()
Definition at line 56 of file engine.as.
Referenced by Menu::FrontMenu::OnFunc().
 {}
Remove()
void Save::Remove (ControlMapBinding@ bind)
Definition at line 257 of file engine.as.
 { return null; }
RemoveStaging()
void Save::RemoveStaging (ControlMapBinding@ bind)
Definition at line 261 of file engine.as.
 { }
RenderScene()
void RenderScene (int idt, vec2 pos, vec4 vignette)
Definition at line 53 of file engine.as.
 {}
RestartMenu()
void RestartMenu ()
Definition at line 64 of file engine.as.
Referenced by Menu::SlotsMenu::Close().
 {}
ResumeGame()
void ResumeGame ()
Definition at line 57 of file engine.as.
Referenced by Menu::FrontMenu::OnFunc().
 {}
RumbleGamepad()
void RumbleGamepad (float strength, int length)
Definition at line 66 of file engine.as.
Referenced by SetGamepadRumble().
 {}
RumbleGamepadStop()
void RumbleGamepadStop ()
Definition at line 67 of file engine.as.
Referenced by ScreenShake::Stop().
 {}
Save()
class ControlMap Save ()
Definition at line 277 of file engine.as.
 { }
SendChatMessage()
void SendChatMessage (string msg)
Definition at line 347 of file engine.as.
Referenced by Menu::InGameChat::OnFunc().
 { }
SendSystemMessage()
void SendSystemMessage (const string &in name, SValue@ data)
Definition at line 63 of file engine.as.
Referenced by WorldScript::UnlinkSouls::ClientExecute(), PlayerCorpse::NetRevive(), PlayerBase::OnDeath(), DungeonSettingsMenu::OnFunc(), DungeonSettingsMenu::OnNgpChanged(), and Campaign::Start().
 {}
SetGemState()
void SetGemState (GemState state)
Definition at line 375 of file engine.as.
 { }
SetJoinable()
void SetJoinable (bool joinable)
Definition at line 356 of file engine.as.
Referenced by OnFunc(), WorldScript::LevelExitNext::ServerExecute(), WorldScript::LevelExitNextAct::ServerExecute(), WorldScript::StartDungeon::ServerExecute(), TestLevel::Start(), and Town::Start().
 { }
SetLevel()
void SetLevel (string level)
Definition at line 358 of file engine.as.
Referenced by MainMenu::LobbyCreated().
 { }
SetLobbyData()
void SetLobbyData (const string &in key, const string &in value)
Definition at line 361 of file engine.as.
Referenced by MainMenu::LobbyCreated(), and MainMenu::SystemMessage().
 { }
SetLobbyMemberData()
void SetLobbyMemberData (const string &in key, const string &in value)
Definition at line 364 of file engine.as.
 { }
SetPlayerLimit()
void SetPlayerLimit (int max)
Definition at line 374 of file engine.as.
Referenced by MainMenu::LobbyCreated().
 { }
SetPrivate()
void SetPrivate (bool priv)
Definition at line 355 of file engine.as.
Referenced by MainMenu::LobbyCreated().
 { }
SetRestartCount()
void SetRestartCount (int count)
Definition at line 62 of file engine.as.
 {}
StartGame() [1/2]
void StartGame (int numPlrs, string level)
Definition at line 54 of file engine.as.
 {}
StartGame() [2/2]
void StartGame ()
Definition at line 359 of file engine.as.
 { }
StopExpectTextInput()
void StopExpectTextInput ()
Definition at line 283 of file engine.as.
 { }
StopScenario()
void StopScenario ()
Definition at line 58 of file engine.as.
Referenced by HWRGameOver::OnFunc(), Menu::Menu::OnFunc(), Menu::FrontMenu::OnFunc(), and GameOver::OnFunc().
 {}
ToScreenspace()
% if EDITOR_GAME EDITOR vec2 ToScreenspace (vec3 pos)
Definition at line 3 of file engine.as.
Referenced by AddFloatingText(), WaypointMarkersWidget::DoDraw(), OverheadBossBar::Draw(), Draw(), SpeechBubble::Draw(), and BaseGameMode::RenderFrame().
 { return vec2(pos.x, pos.y); }
ToWorldspace()
vec3 ToWorldspace (vec2 pos)
Definition at line 4 of file engine.as.
Referenced by BaseGameMode::RenderFrame(), Campaign::UpdateFrame(), and IngameMouse::UpdateMouseColor().
 { return vec3(pos.x, pos.y, 0); }
UnassignAll()
void UnassignAll ()
Definition at line 287 of file engine.as.
 { }
Workshop()
bool get_ID::Workshop ()
Definition at line 113 of file engine.as.
 { return ""; }
Write()
void Write ()
Definition at line 30 of file engine.as.
 {}
Variable Documentation
Action
string Action
Definition at line 241 of file engine.as.
Referenced by Tutorial::GetMappedKey().
Active
Active = 1
Definition at line 415 of file engine.as.
AimDir
vec2 AimDir
Definition at line 162 of file engine.as.
Assigned
bool Assigned
Definition at line 166 of file engine.as.
Attack1
class ButtonState Attack1
Attack2
ButtonState Attack2
Definition at line 148 of file engine.as.
Attack3
ButtonState Attack3
Definition at line 149 of file engine.as.
Attack4
ButtonState Attack4
Definition at line 150 of file engine.as.
Continue
class MenuInput Continue
Referenced by BossLevel::Start(), and BaseGameMode::Start().
Details
string Details
Definition at line 421 of file engine.as.
Easy
Easy = 1
Definition at line 73 of file engine.as.
Referenced by Menu::GetDifficultyName(), Menu::ToDifficulty(), and Menu::SplitscreenOptionsMenu::UpdateDifficultyTexts().
EnabledMods
array<uint32> EnabledMods
Definition at line 26 of file engine.as.
EndTimestamp
int64 EndTimestamp
Definition at line 423 of file engine.as.
evt
TextInputControlEventType evt
Definition at line 412 of file engine.as.
Referenced by Update(), and TextInputWidget::UpdateInput().
Gamepad
bool Gamepad
Definition at line 246 of file engine.as.
GamepadAxis
class MenuInput GamepadAxis
GamepadVector
class MenuInput GamepadVector
GuildMenu
ButtonState GuildMenu
Definition at line 156 of file engine.as.
Hard
Hard = 4
Definition at line 75 of file engine.as.
Referenced by Menu::GetDifficultyName(), Menu::ToDifficulty(), and Menu::SplitscreenOptionsMenu::UpdateDifficultyTexts().
Header
Header
Definition at line 86 of file engine.as.
ID
class PlatformCursor ID
Definition at line 243 of file engine.as.
Inactive
Inactive = 0
Definition at line 414 of file engine.as.
Index
int Index
Definition at line 244 of file engine.as.
InGameMenu
class MenuInput InGameMenu
Referenced by ScalableSpriteButtonWidget::IsEnabled(), and MainMenu::SetMenuState().
JoinSecret
string JoinSecret
Definition at line 432 of file engine.as.
Joystick
bool Joystick
Definition at line 247 of file engine.as.
JoystickAxis
class MenuInput JoystickAxis
JoystickVector
class MenuInput JoystickVector
Keyboard
class MenuInput Keyboard
Referenced by MenuControlInputWidget::ExpectedInput().
LargeImageKey
string LargeImageKey
Definition at line 424 of file engine.as.
LargeImageText
string LargeImageText
Definition at line 425 of file engine.as.
LoadGame
class MenuInput LoadGame
Referenced by BaseGameMode::GetPlayerSpawnPosition(), RandomLevel::PostStart(), Campaign::PostStart(), RandomLevel::Start(), and Campaign::Start().
Low
class MenuInput Low
Referenced by Menu::ControlMapMenu::Initialize().
MainMenu
class MenuInput MainMenu
MapOverlay
ButtonState MapOverlay
Definition at line 158 of file engine.as.
MatchSecret
string MatchSecret
Definition at line 431 of file engine.as.
Modded
bool Modded
Definition at line 25 of file engine.as.
Moo
Moo = 100
Definition at line 417 of file engine.as.
Mouse
class MenuInput Mouse
Referenced by MenuControlInputWidget::ExpectedInput().
MousePos
vec2 MousePos
Definition at line 163 of file engine.as.
MouseWheel
class MenuInput MouseWheel
Referenced by MenuControlInputWidget::ExpectedInput().
MouseWheelDelta
int MouseWheelDelta
Definition at line 164 of file engine.as.
MoveDir
vec2 MoveDir
Definition at line 161 of file engine.as.
Name
string Name
Definition at line 300 of file engine.as.
Referenced by MainMenu::LobbyCreated(), Menu::OnFunc(), and MenuServerListItem::opCmp().
None
@ None
Definition at line 86 of file engine.as.
Referenced by GetVisual().
Normal
@ Normal = 2
Definition at line 74 of file engine.as.
Referenced by GetDifficulty().
PartyId
string PartyId
Definition at line 428 of file engine.as.
PartyMax
int PartyMax
Definition at line 430 of file engine.as.
PartySize
int PartySize
Definition at line 429 of file engine.as.
Peer
uint8 Peer
Definition at line 301 of file engine.as.
Referenced by MainMenu::RenderFrameLoading().
Perfect
Perfect = 10
Definition at line 416 of file engine.as.
Ping
ButtonState Ping
Definition at line 159 of file engine.as.
PlayerMenu
ButtonState PlayerMenu
Definition at line 155 of file engine.as.
Referenced by Campaign::Campaign().
Potion
ButtonState Potion
Definition at line 153 of file engine.as.
Progress
uint8 Progress
Definition at line 302 of file engine.as.
Referenced by MainMenu::RenderFrameLoading().
Saved
class MenuInput Saved
Referenced by MainMenu::ShowMessage().
select
bool select
Definition at line 413 of file engine.as.
Separator
Separator
Definition at line 86 of file engine.as.
Serious
Serious = 8
Definition at line 76 of file engine.as.
Referenced by Menu::GetDifficultyName(), Menu::ToDifficulty(), and Menu::SplitscreenOptionsMenu::UpdateDifficultyTexts().
SetAxis
ControlBindingSetAxis SetAxis
Definition at line 242 of file engine.as.
Slot
class GameSaveInfo Slot
Referenced by Menu::SlotsMenu::GetSlotInfo(), Menu::SlotsMenu::OnFunc(), and Menu::SlotsMenu::RefreshSlots().
SmallImageKey
string SmallImageKey
Definition at line 426 of file engine.as.
SmallImageText
string SmallImageText
Definition at line 427 of file engine.as.
SpectateSecret
string SpectateSecret
Definition at line 433 of file engine.as.
StartGame
class MenuInput StartGame
Referenced by BaseGameMode::Start().
StartTimestamp
int64 StartTimestamp
Definition at line 422 of file engine.as.
State
string State
Definition at line 420 of file engine.as.
SteamController
bool SteamController
Definition at line 248 of file engine.as.
text
enum TextInputControlEventType text
Referenced by NotificationManager::Add(), AddButton(), AddFloatingText(), AddHeader(), GuildHallAccomplishmentsTab::AddHeader(), GameOver::AddSentence(), PlayerMenuCharacterTab::AddTextWidget(), Widget::AddTooltipSub(), Tutorial::AssignHUD(), WorldScript::Variable::DebugDraw(), WidgetInspector::Draw(), FloatingText(), TextWidget::Load(), Load(), ModTextWidget(), Notification::Notification(), Menu::InGameChat::OnFunc(), BaseGameMode::RenderFrame(), MainMenu::RenderFrameLoading(), BaseGameMode::RenderWidgets(), DiscordPresence::SetLargeImageText(), SpeechBubble::SetText(), SetText(), PlayerMenuCharacterTab::SetTextWidget(), PlayerMenuCharacterTab::SetTooltipWidget(), and WorldScript::ShowSpeechBubble::ShowBubble().
Town
SValue Town
Definition at line 24 of file engine.as.
Use
ButtonState Use
Definition at line 152 of file engine.as.
UseMouseLook
bool UseMouseLook
Definition at line 245 of file engine.as.
UsingGamepad
bool UsingGamepad
Definition at line 167 of file engine.as.
Referenced by PlayerBase::RefreshScene().
UsingMouseLook
bool UsingMouseLook
Definition at line 168 of file engine.as.