HoHDocs: Crowd Namespace Reference
Crowd Namespace Reference
Classes
class FloatValueAction
class HealthAction
class TimeAction
class TriggerAction
class ValueAction
Functions
void LoadActions (string filename)
CrowdAction GetAction (const string &in id, bool stat=false)
CrowdAction GetAction (uint id, bool stat=false)
void Trigger (const string &in id, int delta=1, bool stat=false)
void Pause (bool paused)
void TimeReset ()
float ClearDelta ()
IntValueAction (SValue &params)
Variables
array< CrowdAction@> g_actions
Crowd::ValueAction m_thresholdNegative
int m_thresholdPositive
Function Documentation
ClearDelta()
float Crowd::ClearDelta ()
Definition at line 76 of file Crowd.as.
References g_actions.
Referenced by Survival::UpdateFrame().
     {
         bool debugCrowd = GetVarBool("g_debug_crowd");
         if (debugCrowd)
             print("Calculating crowd delta:");
         float ret = 0.0f;
         for (uint i = 0; i < g_actions.length(); i++)
         {
             auto action = g_actions[i];
             float delta = action.GetDelta();
             ret += delta;
             action.Clear();
             if (debugCrowd)
                 print("  " + delta + "   " + action.m_id);
         }
         return ret;
     }
GetAction() [1/2]
CrowdAction Crowd::GetAction (const string &in id, bool stat = false)
Definition at line 19 of file Crowd.as.
Referenced by Trigger().
     {
         return GetAction(HashString(id), stat);
     }
GetAction() [2/2]
CrowdAction Crowd::GetAction (uint id, bool stat = false)
Definition at line 24 of file Crowd.as.
References g_actions.
     {
         for (uint i = 0; i < g_actions.length(); i++)
         {
             auto action = g_actions[i];
             if (action.m_stat == stat && action.m_idHash == id)
                 return action;
         }
         return null;
     }
IntValueAction()
Crowd::IntValueAction (SValue & params)
Definition at line 24 of file ValueAction.as.
References m_thresholdNegative, and m_thresholdPositive.
         {
             super(params);
             m_thresholdNegative = GetParamInt(UnitPtr(), params, "threshold-negative", false, 0);
             m_thresholdPositive = GetParamInt(UnitPtr(), params, "threshold-positive", false, 1);
         }
LoadActions()
void Crowd::LoadActions (string filename)
Definition at line 5 of file Crowd.as.
References g_actions.
Referenced by Survival::Survival().
     {
         auto sval = Resources::GetSValue(filename);
         auto arr = sval.GetArray();
         for (uint i = 0; i < arr.length(); i++)
         {
             auto svAction = arr[i];
             string className = GetParamString(UnitPtr(), svAction, "class");
             auto newAction = cast<CrowdAction>(InstantiateClass(className, svAction));
             if (newAction !is null)
                 g_actions.insertLast(newAction);
         }
     }
Pause()
void Crowd::Pause (bool paused)
Definition at line 54 of file Crowd.as.
References g_gameMode.
Referenced by WorldScript::CrowdPause::ServerExecute().
     {
         auto gm = cast<Survival>(g_gameMode);
         if (gm is null)
             return;
         if (gm.m_crowdPaused == paused)
             return;
         gm.m_crowdPaused = paused;
         gm.m_crowdTimeC = gm.m_crowdTime;
     }
TimeReset()
void Crowd::TimeReset ()
Definition at line 67 of file Crowd.as.
References g_gameMode.
Referenced by WorldScript::CrowdTimeReset::ServerExecute().
     {
         auto gm = cast<Survival>(g_gameMode);
         if (gm is null)
             return;
         gm.m_crowdTimeElapsed = 0;
     }
Trigger()
void Crowd::Trigger (const string &in id, int delta = 1, bool stat = false)
Definition at line 35 of file Crowd.as.
References g_gameMode, and GetAction().
Referenced by Stats::Add(), and WorldScript::CrowdTrigger::ServerExecute().
     {
         //TODO: This is currently called for both server & clients - only allow this to pass as server?
         auto gm = cast<Survival>(g_gameMode);
         if (gm is null)
             return;
         auto action = cast<TriggerAction>(GetAction(id, stat));
         if (action is null)
         {
             if (!stat)
                 PrintError("Couldn't find Crowd TriggerAction '" + id + "'!");
             return;
         }
         action.Trigger(delta);
     }
Variable Documentation
g_actions
array<CrowdAction@> Crowd::g_actions
Definition at line 3 of file Crowd.as.
Referenced by ClearDelta(), GetAction(), and LoadActions().
m_thresholdNegative
Crowd::ValueAction Crowd::m_thresholdNegative
Referenced by Crowd::TriggerAction::GetDelta(), and IntValueAction().
m_thresholdPositive
int Crowd::m_thresholdPositive
Definition at line 22 of file ValueAction.as.
Referenced by Crowd::TriggerAction::GetDelta(), and IntValueAction().