HoHDocs: Menu Namespace Reference
Menu Namespace Reference
Classes
class BackdropLayer
class CharacterCreationMenu
class CharacterCustomizationMenu
class CharacterSelectionMenu
class ControlMapMenu
class ControlsMenu
class CreditsMenu
class EditSlotMenu
class FrontMenu
class GameLanguagesMenu
class GameOptionsMenu
class GraphicsMenu
class HostMenu
class HwrMenu
class InGameChat
class InGameNotifier
class IntroMenu
class JoiningLobbyMenu
class LobbyPlayersMenu
class Menu
class MultiplayerMenu
class OptionsMenu
class ResolutionsMenu
class SimpleMenu
class SingleplayerMenu
class SlotsMenu
class SoundMenu
class SplitscreenMenu
class SplitscreenOptionsMenu
class SplitscreenPlayer
class SubOptionsMenu
class TestMenu
Enumerations
enum ServerlistSortColumn { None, Name, Players }
Functions
Backdrop (GUIBuilder@ b, string fnm)
void SmoothWidgets (Widget@ widget)
void Update (int dt) override
void DoLayout () override
void Draw (SpriteBatch &sb, int idt) override
ServerlistMenu (MenuProvider@ provider)
void Initialize (GUIDef@ def) override
void Show () override
void OnFunc (Widget@ sender, string name) override
void OnLobbyList (array< uint64 >@ lobbies)
SplitscreenSelectionMenu (MenuProvider@ provider)
bool Close () override
SplitscreenPlayer GetKbmPlayer ()
SplitscreenPlayer GetInput (int index)
bool HasJoined (int index)
void RemoveInput (int index)
void JoinInput (int index)
void SkinInput (int index, int dir)
bool GoBack () override
void SetStartScenario (ScenarioInfo@ scenario)
void SetStartLevel (ScenarioStartLevel@ level)
void SetCurrentDifficulty ()
string GetDifficultyName (GameDifficulty diff)
GameDifficulty ToDifficulty (int diff)
void ShowLoadFailedDialog ()
Variables
class Menu::BackdropLayer m_clipping
Rect m_clippingRect
array< BackdropLayer@> m_layers
enum Menu::ServerlistSortColumn m_wFilter
MenuServerListItem m_listTemplate
FilteredListWidget m_list
ServerlistSortColumn m_sortColumn = ServerlistSortColumn::Players
int m_sortDir = 1
Sprite m_spriteButton
Sprite m_spriteButtonHover
Sprite m_spriteButtonDown
int m_charLevel
class Menu::SplitscreenPlayer m_players
array< string > m_skins
Widget m_wPlayerTemplate
Widget m_wPlayerList
Sprite m_spriteLogosDefault
ScenarioInfo m_startScenario
string m_startLevel
array< string > m_startMods
GameDifficulty m_startDifficulty = GameDifficulty::Normal
string m_saveGame
Enumeration Type Documentation
ServerlistSortColumn
enum Menu::ServerlistSortColumn
Enumerator
None
Name
Players
Definition at line 3 of file ServerlistMenu.as.
     {
         None,
         Name,
         Players,
     }
Function Documentation
Backdrop()
Menu::Backdrop (GUIBuilder@ b, string fnm)
Definition at line 42 of file MenuBackdrop.as.
References LoadWidget(), m_layers, m_widget, and SmoothWidgets().
Referenced by MenuProvider::Initialize(), and Menu::GraphicsMenu::Update().
         {
             LoadWidget(b, fnm);
             auto wContainer = m_widget.GetWidgetById("container");
             if (wContainer !is null)
             {
                 SmoothWidgets(wContainer);
                 for (uint i = 0; i < wContainer.m_children.length(); i++)
                     m_layers.insertLast(BackdropLayer(wContainer.m_children[i]));
                 auto sval = Resources::GetSValue("gui/main_menu/backdrop_parallax.sval");
                 if (sval !is null && sval.GetType() == SValueType::Array)
                 {
                     auto arr = sval.GetArray();
                     for (uint i = 0; i < m_layers.length(); i++)
                     {
                         if (i >= arr.length())
{
                             PrintError("backdrop_parallax.sval doesn't have enough weights!");
                             break;
                         }
                         m_layers[i].m_weight = arr[i].GetVector2();
                     }
                 }
             }
         }
Close()
bool Menu::Close () override
Definition at line 169 of file SplitscreenSelectionMenu.as.
References Menu::Menu::Close(), g_gameMode, and GetControlBindings().
Referenced by Menu::Menu::GoBack(), GoBack(), and Menu::Menu::OnFunc().
         {
             if (Menu::Close())
             {
                 auto gm = cast<BaseGameMode>(g_gameMode);
                 @gm.m_mice[0].m_hackSecondGame = null;
                 @gm.m_mice[0].m_hackSecondMenu = null;
                 GetControlBindings().AssignControls(1);
                 return true;
             }
             return false;
         }
DoLayout()
void Menu::DoLayout () override
Definition at line 105 of file MenuBackdrop.as.
References g_gameMode, GetUIScale(), m_hasLayout, m_widget, AGameMode::m_wndHeight, and AGameMode::m_wndWidth.
Referenced by Menu::SubOptionsMenu::Initialize(), Menu::SlotsMenu::RefreshSlots(), and Menu::HostMenu::UpdateNgp().
         {
 %PROFILE_START DoLayout
             m_widget.DoLayout(vec2(), vec2(g_gameMode.m_wndWidth, g_gameMode.m_wndHeight) * GetUIScale());
             m_hasLayout = true;
 %PROFILE_STOP
         }
Draw()
void Menu::Draw (SpriteBatch & sb, int idt) override
Definition at line 113 of file MenuBackdrop.as.
References GetUIScale(), Rect::GetVec4(), m_clipping, m_clippingRect, and m_layers.
         {
             sb.PushTransformation(mat::scale(mat4(), 1.0f / GetUIScale()));
             if (m_clipping)
                 sb.PushClipping(m_clippingRect.GetVec4(), true);
             for (uint i = 0; i < m_layers.length(); i++)
                 m_layers[i].Draw(idt);
             IWidgetHoster::Draw(sb, idt);
             if (m_clipping)
                 sb.PopClipping();
             sb.PopTransformation();
         }
GetDifficultyName()
string Menu::GetDifficultyName (GameDifficulty diff)
Definition at line 380 of file SplitscreenSelectionMenu.as.
References Easy, Hard, Normal, and Serious.
Referenced by SetCurrentDifficulty().
         {
             switch (diff)
             {
                 case GameDifficulty::Easy: return Resources::GetString(".difficulty.easy");
                 case GameDifficulty::Normal: return Resources::GetString(".difficulty.normal");
                 case GameDifficulty::Hard: return Resources::GetString(".difficulty.hard");
                 case GameDifficulty::Serious: return Resources::GetString(".difficulty.serious");
             }
             return Resources::GetString(".difficulty.normal");
         }
GetInput()
SplitscreenPlayer Menu::GetInput (int index)
Definition at line 193 of file SplitscreenSelectionMenu.as.
References Upgrades::m_index, and m_players.
Referenced by HasJoined(), and SkinInput().
         {
             for (uint i = 0; i < m_players.length(); i++)
             {
                 if (m_players[i].m_index == index)
                     return m_players[i];
             }
             return null;
         }
GetKbmPlayer()
SplitscreenPlayer Menu::GetKbmPlayer ()
Definition at line 183 of file SplitscreenSelectionMenu.as.
References m_map, m_players, and ControlMap::UseMouseLook.
         {
             for (uint i = 0; i < m_players.length(); i++)
             {
                 if (m_players[i].m_map.UseMouseLook)
                     return m_players[i];
             }
             return null;
         }
GoBack()
bool Menu::GoBack () override
Definition at line 270 of file SplitscreenSelectionMenu.as.
References Close(), and m_players.
         {
             if (m_players.length() == 0)
                 return Close();
             return true;
         }
HasJoined()
bool Menu::HasJoined (int index)
Definition at line 203 of file SplitscreenSelectionMenu.as.
References GetInput().
         {
             return (GetInput(index) !is null);
         }
Initialize()
void Menu::Initialize (GUIDef@ def) override
Definition at line 30 of file ServerlistMenu.as.
References ListLobbies(), HwrSaves::LoadCharacter(), m_charLevel, m_list, m_listTemplate, m_spriteButton, m_spriteButtonDown, m_spriteButtonHover, m_wFilter, m_widget, Materials::MulticolorsFromSval(), and name.
         {
             @m_wFilter = cast<TextInputWidget>(m_widget.GetWidgetById("filter"));
             @m_listTemplate = cast<MenuServerListItem>(m_widget.GetWidgetById("serverlist-template"));
             @m_list = cast<FilteredListWidget>(m_widget.GetWidgetById("serverlist"));
             @m_spriteButton = def.GetSprite("listitem");
             @m_spriteButtonHover = def.GetSprite("listitem-hover");
             @m_spriteButtonDown = def.GetSprite("listitem-down");
             Lobby::ListLobbies();
             auto svChar = HwrSaves::LoadCharacter();
             if (svChar !is null)
             {
                 m_charLevel = GetParamInt(UnitPtr(), svChar, "level", false, 1);
                 string name = GetParamString(UnitPtr(), svChar, "name");
                 string charClass = GetParamString(UnitPtr(), svChar, "class");
                 auto wCharUnit = cast<UnitWidget>(m_widget.GetWidgetById("char-unit"));
                 wCharUnit.AddUnit("players/" + charClass + ".unit", "idle-3");
                 wCharUnit.m_multiColors = Materials::MulticolorsFromSval(svChar);
                 string charClassName = Resources::GetString(".class." + charClass);
                 auto wName = cast<TextWidget>(m_widget.GetWidgetById("char-name"));
                 wName.SetText(Resources::GetString(".mainmenu.serverlist.charname", {
                     { "name", name },
                     { "lvl", m_charLevel },
                     { "class", charClassName }
                 }));
             }
         }
JoinInput()
void Menu::JoinInput (int index)
Definition at line 223 of file SplitscreenSelectionMenu.as.
References Widget::AddChild(), Widget::Clone(), Menu::SplitscreenPlayer::DisplayName(), Menu::SplitscreenPlayer::m_map, m_players, Menu::SplitscreenPlayer::m_widget, m_wPlayerList, m_wPlayerTemplate, and ControlMap::UseMouseLook.
         {
             int playerIndex = m_players.length();
             SplitscreenPlayer@ player = SplitscreenPlayer(index);
             if (player.m_map.UseMouseLook)
                 playerIndex = 0;
             RectWidget@ wPlayer = cast<RectWidget>(m_wPlayerTemplate.Clone());
             wPlayer.SetID("");
             wPlayer.m_visible = true;
             m_wPlayerList.AddChild(wPlayer, playerIndex);
             @player.m_widget = wPlayer;
             player.DisplayName(playerIndex);
             m_players.insertAt(playerIndex, player);
             for (uint i = playerIndex + 1; i < m_players.length(); i++)
                 m_players[i].DisplayName(i);
         }
OnFunc()
void Menu::OnFunc (Widget@ sender, string name) override
Definition at line 71 of file ServerlistMenu.as.
References g_gameMode, MainMenu::JoiningLobby(), JoinLobby(), ListLobbies(), m_list, m_sortColumn, m_sortDir, m_wFilter, name, Name, None, Menu::Menu::OnFunc(), Players, FilteredListWidget::SetFilter(), and FilteredListWidget::ShowAll().
Referenced by DungeonSettingsMenu::OnFunc(), DialogWindow::OnFunc(), and LootBox::OnFunc().
         {
             auto parse = name.split(" ");
             if (parse[0] == "join")
             {
                 if (parse.length() > 1)
                 {
                     MainMenu@ menu = cast<MainMenu>(g_gameMode);
                     menu.JoiningLobby();
                     Lobby::JoinLobby(parseUInt(parse[1]));
                 }
             }
             else if (parse[0] == "refresh")
             {
                 //m_list.ClearChildren();
                 Lobby::ListLobbies();
             }
             else if (parse[0] == "filterlist")
                 m_list.SetFilter(m_wFilter.m_text.plain());
             else if (parse[0] == "filterlist-clear")
             {
                 m_wFilter.ClearText();
                 m_list.ShowAll();
             }
             else if (parse[0] == "sort")
             {
                 ServerlistSortColumn setCol = ServerlistSortColumn::None;
                 if (parse[1] == "name")
                     setCol = ServerlistSortColumn::Name;
                 else if (parse[1] == "players")
                     setCol = ServerlistSortColumn::Players;
                 else
                     setCol = ServerlistSortColumn::None;
                 if (m_sortColumn == setCol)
                 {
                     if (m_sortDir == 0 || m_sortDir == -1)
                         m_sortDir = 1;
                     else if (m_sortDir == 1)
                         m_sortDir = -1;
                 }
                 else
                     m_sortDir = 1;
                 m_sortColumn = setCol;
                 m_list.m_children.sortAsc();
             }
             else
                 Menu::OnFunc(sender, name);
         }
OnLobbyList()
void Menu::OnLobbyList (array< uint64 >@ lobbies)
Definition at line 122 of file ServerlistMenu.as.
References MenuServerListItem::Clone(), GetLobbyData(), GetLobbyPing(), GetLobbyPlayerCount(), GetLobbyPlayerCountMax(), m_charLevel, m_list, m_listTemplate, and MenuServerListItem::Set().
         {
             uint localModHash = Resources::GetModHash();
             m_list.ClearChildren();
             for (uint i = 0; i < lobbies.length(); i++)
             {
                 string lobbyName = Lobby::GetLobbyData(lobbies[i], "name");
                 int lobbyPlayerCount = Lobby::GetLobbyPlayerCount(lobbies[i]);
                 int lobbyPlayerCountMax = Lobby::GetLobbyPlayerCountMax(lobbies[i]);
                 int lobbyPing = Lobby::GetLobbyPing(lobbies[i]);
                 int maxLevel = parseInt(Lobby::GetLobbyData(lobbies[i], "max-level"));
                 int minLevel = parseInt(Lobby::GetLobbyData(lobbies[i], "min-level"));
                 int ngp = parseInt(Lobby::GetLobbyData(lobbies[i], "ngp"));
                 bool downscaling = (Lobby::GetLobbyData(lobbies[i], "downscaling") == "true");
                 uint modsHash = parseUInt(Lobby::GetLobbyData(lobbies[i], "mods-hash"));
                 int modsCount = parseInt(Lobby::GetLobbyData(lobbies[i], "mods-count"));
                 string mods = Lobby::GetLobbyData(lobbies[i], "mods");
                 MenuServerListItem@ wLobbyItem = cast<MenuServerListItem>(m_listTemplate.Clone());
                 wLobbyItem.m_visible = true;
                 wLobbyItem.m_func = "join " + lobbies[i];
                 wLobbyItem.Set(this, lobbyName, lobbyPlayerCount, lobbyPlayerCountMax, lobbyPing);
                 if (lobbyPlayerCount >= lobbyPlayerCountMax)
                     wLobbyItem.m_enabled = false;
                 else if (m_charLevel < minLevel || m_charLevel > maxLevel)
                     wLobbyItem.m_enabled = false;
                 else if (modsHash != localModHash)
                     wLobbyItem.m_enabled = false;
                 if (minLevel > 1 && maxLevel < 60)
                 {
                     string strMinLevel = "" + minLevel;
                     string strMaxLevel = "" + maxLevel;
                     if (m_charLevel < minLevel)
                         strMinLevel = "\\cff0000" + minLevel;
                     if (m_charLevel > maxLevel)
                         strMaxLevel = "\\cff0000" + maxLevel;
                     wLobbyItem.m_tooltipText = Resources::GetString(".mainmenu.serverlist.level-restriction.both", {
                         { "min", strMinLevel },
                         { "max", strMaxLevel }
                     });
                 }
                 else if (minLevel > 1)
                 {
                     string strMinLevel = "" + minLevel;
                     if (m_charLevel < minLevel)
                         strMinLevel = "\\cff0000" + minLevel + "\\d";
                     wLobbyItem.m_tooltipText = Resources::GetString(".mainmenu.serverlist.level-restriction.min", {
                         { "min", strMinLevel }
                     });
                 }
                 else if (maxLevel < 60)
                 {
                     string strMaxLevel = "" + maxLevel;
                     if (m_charLevel > maxLevel)
                         strMaxLevel = "\\cff0000" + maxLevel + "\\d";
                     wLobbyItem.m_tooltipText = Resources::GetString(".mainmenu.serverlist.level-restriction.max", {
                         { "max", strMaxLevel }
                     });
                 }
                 if (ngp > 0)
                 {
                     if (wLobbyItem.m_tooltipText != "")
                         wLobbyItem.m_tooltipText += "\n\\d";
                     wLobbyItem.m_tooltipText += Resources::GetString(".mainmenu.serverlist.ngp", {
                         { "ngp", ngp }
                     });
                 }
                 if (downscaling)
                 {
                     if (wLobbyItem.m_tooltipText != "")
                         wLobbyItem.m_tooltipText += "\n\\d";
                     wLobbyItem.m_tooltipText += Resources::GetString(".mainmenu.serverlist.downscaling");
                 }
                 if (modsHash != 0 || modsCount > 0)
                 {
                     string strModCount;
                     if (modsCount == 1)
                         strModCount = Resources::GetString(".mainmenu.serverlist.mods.one");
                     else
                         strModCount = Resources::GetString(".mainmenu.serverlist.mods.plural", { { "num", modsCount } });
                     if (modsHash != localModHash)
                         strModCount = "\\cff0000" + strModCount + "\\d - " + Resources::GetString(".mainmenu.serverlist.mods.dontmatch");
                     wLobbyItem.m_tooltipText += strModCount + "\n\\c7f7f7f" + mods;
                 }
                 m_list.AddChild(wLobbyItem);
             }
             m_list.m_children.sortAsc();
         }
RemoveInput()
void Menu::RemoveInput (int index)
Definition at line 208 of file SplitscreenSelectionMenu.as.
References Upgrades::m_index, m_players, and Menu::SplitscreenPlayer::m_widget.
         {
             for (uint i = 0; i < m_players.length(); i++)
             {
                 if (m_players[i].m_index == index)
                 {
                     m_players[i].m_widget.RemoveFromParent();
                     m_players.removeAt(i);
                     for (uint j = i; j < m_players.length(); j++)
                         m_players[j].DisplayName(j);
                     break;
                 }
             }
         }
ServerlistMenu()
Menu::ServerlistMenu (MenuProvider@ provider)
Definition at line 25 of file ServerlistMenu.as.
Referenced by Menu::HwrMenu::FinishContext(), and Menu::MultiplayerMenu::OnFunc().
         {
             super(provider);
         }
SetCurrentDifficulty()
void Menu::SetCurrentDifficulty ()
Definition at line 373 of file SplitscreenSelectionMenu.as.
References GetDifficultyName(), m_startDifficulty, m_widget, and ScalableSpriteButtonWidget::SetText().
         {
             ScalableSpriteButtonWidget@ wDiff = cast<ScalableSpriteButtonWidget>(m_widget.GetWidgetById("difficulty"));
             if (wDiff !is null)
                 wDiff.SetText(utf8string(GetDifficultyName(m_startDifficulty)).toUpper().plain());
         }
SetStartLevel()
void Menu::SetStartLevel (ScenarioStartLevel@ level)
Definition at line 364 of file SplitscreenSelectionMenu.as.
References m_startLevel, m_widget, and TextWidget::SetText().
Referenced by SetStartScenario().
         {
             m_startLevel = level.GetLevel();
             TextWidget@ wLevelName = cast<TextWidget>(m_widget.GetWidgetById("scenario-level"));
             if (wLevelName !is null)
                 wLevelName.SetText(Resources::GetString(level.GetName()));
         }
SetStartScenario()
void Menu::SetStartScenario (ScenarioInfo@ scenario)
Definition at line 319 of file SplitscreenSelectionMenu.as.
References GetDefaultOn(), ScenarioInfo::GetID(), ScenarioInfo::GetName(), ScenarioInfo::GetStartLevels(), ScenarioInfo::LoadLogos(), m_spriteLogosDefault, m_startMods, m_startScenario, m_widget, Tweak::ScenarioLogoSmall, ScriptSprite(), SpriteWidget::SetSprite(), SetStartLevel(), and TextWidget::SetText().
         {
             // Clear start mods if we switch scenario
             if (m_startScenario !is scenario)
             {
                 m_startMods.removeRange(0, m_startMods.length());
                 // Set default-on switches
                 array<ScenarioModification@>@ arrMods = scenario.GetModifications();
                 for (uint i = 0; i < arrMods.length(); i++)
                 {
                     if (arrMods[i].GetDefaultOn())
                         m_startMods.insertLast(arrMods[i].GetID());
                 }
             }
             @m_startScenario = scenario;
             TextWidget@ wScenarioName = cast<TextWidget>(m_widget.GetWidgetById("scenario-name"));
             if (wScenarioName !is null)
                 wScenarioName.SetText(Resources::GetString(m_startScenario.GetName()));
             SpriteWidget@ wLogo = cast<SpriteWidget>(m_widget.GetWidgetById("logo"));
             if (wLogo !is null)
             {
                 TempTexture2D@ logoTexture = null;
                 if (m_startScenario !is null)
                     @logoTexture = m_startScenario.LoadLogos();
                 if (logoTexture !is null)
                 {
                     ScriptSprite@ logoSprite = ScriptSprite(logoTexture, Tweak::ScenarioLogoSmall);
                     wLogo.SetSprite(logoSprite);
                 }
                 else
                     wLogo.SetSprite(m_spriteLogosDefault);
             }
             auto startLevels = m_startScenario.GetStartLevels();
             if (startLevels.length() > 0)
                 SetStartLevel(startLevels[0]);
             else
                 PrintError("No start levels for scenario '" + m_startScenario.GetID() + "'");
         }
Show()
void Menu::Show () override
Definition at line 64 of file ServerlistMenu.as.
References ListLobbies(), and Menu::Menu::Show().
Referenced by Menu::Menu::Close().
         {
             Menu::Show();
             Lobby::ListLobbies();
         }
ShowLoadFailedDialog()
void Menu::ShowLoadFailedDialog ()
Definition at line 404 of file SplitscreenSelectionMenu.as.
References g_gameMode, and AGameMode::ShowDialog().
         {
             print("Failed to load savegame!");
             g_gameMode.ShowDialog(
                 "",
                 Resources::GetString(".menu.loadgame.failed"),
                 Resources::GetString(".menu.ok"),
                 this
             );
         }
SkinInput()
void Menu::SkinInput (int index, int dir)
Definition at line 245 of file SplitscreenSelectionMenu.as.
References GetInput(), m_players, Menu::SplitscreenPlayer::m_skin, m_skins, Modifiers::Set, and Menu::SplitscreenPlayer::SetSkin().
         {
             SplitscreenPlayer@ ply = GetInput(index);
             if (ply is null)
                 return;
             string newSkin = ply.m_skin;
             int skinIndex = m_skins.find(ply.m_skin);
             if (skinIndex != -1)
             {
                 skinIndex += dir;
                 if (skinIndex < 0)
                     skinIndex = m_skins.length() - 1;
                 else if (skinIndex >= int(m_skins.length()))
                     skinIndex = 0;
                 newSkin = m_skins[skinIndex];
             }
             int playerIndex = m_players.findByRef(ply);
             GlobalCache::Set("skin_" + playerIndex, newSkin);
             ply.SetSkin(newSkin);
         }
SmoothWidgets()
void Menu::SmoothWidgets (Widget@ widget)
Definition at line 70 of file MenuBackdrop.as.
References Widget::m_children, and Widget::m_pixelPerfect.
Referenced by Backdrop().
         {
             if (widget is null)
                 return;
             widget.m_pixelPerfect = false;
             for (uint i = 0; i < widget.m_children.length(); i++)
                 SmoothWidgets(widget.m_children[i]);
         }
SplitscreenSelectionMenu()
Menu::SplitscreenSelectionMenu (MenuProvider@ provider)
Definition at line 121 of file SplitscreenSelectionMenu.as.
References GetControlBindings().
Referenced by Menu::SplitscreenMenu::OnFunc().
         {
             super(provider);
             // Some high number will cause sequential automatic assignments which is what we want for this menu
             GetControlBindings().AssignControls(16);
         }
ToDifficulty()
GameDifficulty Menu::ToDifficulty (int diff)
Definition at line 392 of file SplitscreenSelectionMenu.as.
References Easy, Hard, Normal, and Serious.
         {
             switch (diff)
             {
                 case 0: return GameDifficulty::Easy;
                 case 1: return GameDifficulty::Normal;
                 case 2: return GameDifficulty::Hard;
                 case 3: return GameDifficulty::Serious;
             }
             return GameDifficulty::Normal;
         }
Update()
void Menu::Update (int dt) override
Definition at line 80 of file MenuBackdrop.as.
References g_gameMode, and m_layers.
Referenced by Menu::TestMenu::Update(), Menu::MultiplayerMenu::Update(), Menu::IntroMenu::Update(), and Menu::LobbyPlayersMenu::Update().
         {
             if (m_layers.length() > 0)
             {
                 auto gm = cast<BaseGameMode>(g_gameMode);
                 vec2 mousePos = gm.m_mice[0].GetPos(0) / gm.m_wndScale;
                 vec2 mouseOffset = mousePos - vec2(gm.m_wndWidth / 2.0f, gm.m_wndHeight / 2.0f);
                 mouseOffset.x /= gm.m_wndWidth / 2.0f;
                 mouseOffset.y /= gm.m_wndHeight / 2.0f;
                 mouseOffset *= -1.0f;
                 for (uint i = 0; i < m_layers.length(); i++)
                 {
                     auto layer = m_layers[i];
                     layer.SetOffset(vec2(
                         layer.m_weight.x * mouseOffset.x,
                         layer.m_weight.y * mouseOffset.y
                     ));
                 }
             }
             IWidgetHoster::Update(dt);
         }
Variable Documentation
m_charLevel
int Menu::m_charLevel
Definition at line 23 of file ServerlistMenu.as.
Referenced by Initialize(), and OnLobbyList().
m_clipping
class Menu::BackdropLayer Menu::m_clipping
Referenced by Draw().
m_clippingRect
Rect Menu::m_clippingRect
Definition at line 38 of file MenuBackdrop.as.
Referenced by Draw().
m_layers
array<BackdropLayer@> Menu::m_layers
Definition at line 40 of file MenuBackdrop.as.
Referenced by Backdrop(), Draw(), and Update().
m_list
FilteredListWidget Menu::m_list
Definition at line 14 of file ServerlistMenu.as.
Referenced by Initialize(), OnFunc(), and OnLobbyList().
m_listTemplate
MenuServerListItem Menu::m_listTemplate
Definition at line 13 of file ServerlistMenu.as.
Referenced by Initialize(), and OnLobbyList().
m_players
class Menu::SplitscreenPlayer Menu::m_players
Referenced by GetInput(), GetKbmPlayer(), GoBack(), JoinInput(), RemoveInput(), and SkinInput().
m_saveGame
string Menu::m_saveGame
Definition at line 119 of file SplitscreenSelectionMenu.as.
m_skins
array<string> Menu::m_skins
Initial value:
= {
            "serious_sam",
            "bogus_beret",
            "canned_cain",
            "hilarious_harry",
            "marty_mcparty",
            "minotaur_mike",
            "ninja_nobody",
            "pirate_pete",
            "rocking_ryan",
            "wild_wyatt"
        }
Definition at line 96 of file SplitscreenSelectionMenu.as.
Referenced by SkinInput().
m_sortColumn
ServerlistSortColumn Menu::m_sortColumn = ServerlistSortColumn::Players
Definition at line 16 of file ServerlistMenu.as.
Referenced by OnFunc().
m_sortDir
int Menu::m_sortDir = 1
Definition at line 17 of file ServerlistMenu.as.
Referenced by OnFunc().
m_spriteButton
Sprite Menu::m_spriteButton
Definition at line 19 of file ServerlistMenu.as.
Referenced by Initialize().
m_spriteButtonDown
Sprite Menu::m_spriteButtonDown
Definition at line 21 of file ServerlistMenu.as.
Referenced by Initialize().
m_spriteButtonHover
Sprite Menu::m_spriteButtonHover
Definition at line 20 of file ServerlistMenu.as.
Referenced by Initialize().
m_spriteLogosDefault
Sprite Menu::m_spriteLogosDefault
Definition at line 112 of file SplitscreenSelectionMenu.as.
Referenced by SetStartScenario().
m_startDifficulty
GameDifficulty Menu::m_startDifficulty = GameDifficulty::Normal
Definition at line 117 of file SplitscreenSelectionMenu.as.
Referenced by SetCurrentDifficulty().
m_startLevel
string Menu::m_startLevel
Definition at line 115 of file SplitscreenSelectionMenu.as.
Referenced by SetStartLevel().
m_startMods
array<string> Menu::m_startMods
Definition at line 116 of file SplitscreenSelectionMenu.as.
Referenced by SetStartScenario().
m_startScenario
ScenarioInfo Menu::m_startScenario
Definition at line 114 of file SplitscreenSelectionMenu.as.
Referenced by SetStartScenario().
m_wFilter
enum Menu::ServerlistSortColumn Menu::m_wFilter
Referenced by Initialize(), and OnFunc().
m_wPlayerList
Widget Menu::m_wPlayerList
Definition at line 110 of file SplitscreenSelectionMenu.as.
Referenced by JoinInput().
m_wPlayerTemplate
Widget Menu::m_wPlayerTemplate
Definition at line 109 of file SplitscreenSelectionMenu.as.
Referenced by JoinInput().