HoHDocs: HwrSaves Namespace Reference
HwrSaves Namespace Reference
Functions
bool IsSaving ()
void CreateCharacter (SValue@ char)
array< SValue@> GetCharacters ()
void PickCharacter (int index)
void DeleteCharacter (int index)
void SaveTownAndCharacter (SValue@ town, SValue@ character, bool saveLevel)
SValue LoadHostTown ()
void DeleteTown (int slot)
void CopyTown (int slot, int newSlot, bool withChars=true)
SValue LoadLocalTown ()
SValue LoadCharacter (int peer=-1)
array< SaveSlot@> GetSaveSlots ()
SaveSlot CreateSlot (int num)
array< ResourceMod@> GetEnabledMods ()
Function Documentation
CopyTown()
void HwrSaves::CopyTown (int slot, int newSlot, bool withChars = true)
Definition at line 45 of file engine.as.
Referenced by Menu::SlotsMenu::OnFunc().
 {}
CreateCharacter()
void HwrSaves::CreateCharacter (SValue@ char)
Definition at line 36 of file engine.as.
Referenced by Menu::CharacterCustomizationMenu::OnFunc().
 {}
CreateSlot()
SaveSlot HwrSaves::CreateSlot (int num)
Definition at line 49 of file engine.as.
Referenced by Menu::SlotsMenu::Initialize(), and Menu::SlotsMenu::OnFunc().
 { return null; }
DeleteCharacter()
void HwrSaves::DeleteCharacter (int index)
Definition at line 39 of file engine.as.
Referenced by Menu::CharacterSelectionMenu::OnFunc().
 {}
DeleteTown()
void HwrSaves::DeleteTown (int slot)
Definition at line 44 of file engine.as.
Referenced by Menu::SlotsMenu::OnFunc().
 {}
GetCharacters()
array<SValue@> HwrSaves::GetCharacters ()
Definition at line 37 of file engine.as.
Referenced by GuildHallStatsTab::AddClassesToList(), Town::CheckForAchievements(), Menu::HostMenu::Initialize(), TownRecord::Load(), GuildHallStatsTab::RefreshList(), Titles::ClassTitles::RefreshModifiers(), Menu::CharacterSelectionMenu::ReloadList(), and Menu::HwrMenu::ShowCharacterSelection().
 { return null; }
GetEnabledMods()
array<ResourceMod@> HwrSaves::GetEnabledMods ()
Definition at line 50 of file engine.as.
Referenced by Menu::CharacterSelectionMenu::GetModClassName(), Menu::FrontMenu::Initialize(), Initialize(), MainMenu::LobbyCreated(), and WorldScript::CheckMods::ServerExecute().
 { return null; }
GetSaveSlots()
array<SaveSlot@> HwrSaves::GetSaveSlots ()
Definition at line 48 of file engine.as.
Referenced by Menu::SlotsMenu::Initialize(), and Menu::SlotsMenu::OnFunc().
 { return null; }
IsSaving()
bool HwrSaves::IsSaving ()
Definition at line 35 of file engine.as.
Referenced by Menu::EditSlotMenu::Update().
 { return false; }
LoadCharacter()
SValue HwrSaves::LoadCharacter (int peer = -1)
Definition at line 47 of file engine.as.
Referenced by BaseGameMode::ActivatePlayerRecord(), Campaign::Campaign(), Menu::HwrMenu::FinishContext(), Menu::Initialize(), and Menu::LobbyPlayersMenu::UpdatePlayer().
 { return null; }
LoadHostTown()
SValue HwrSaves::LoadHostTown ()
Definition at line 43 of file engine.as.
Referenced by RandomLevel::Generate(), and Campaign::Start().
 { return null; }
LoadLocalTown()
SValue HwrSaves::LoadLocalTown ()
Definition at line 46 of file engine.as.
Referenced by Campaign::Start(), and MainMenu::Start().
 { return null; }
PickCharacter()
void HwrSaves::PickCharacter (int index)
Definition at line 38 of file engine.as.
Referenced by Campaign::Campaign(), Menu::CharacterCustomizationMenu::OnFunc(), Menu::FrontMenu::OnFunc(), and Menu::CharacterSelectionMenu::OnFunc().
 {}
SaveTownAndCharacter()
void HwrSaves::SaveTownAndCharacter (SValue@ town, SValue@ character, bool saveLevel)
Definition at line 42 of file engine.as.
Referenced by Campaign::SavePlayer().
 {}