HoHDocs: Materials Namespace Reference
Materials Namespace Reference
Classes
class DyeMapping
Enumerations
enum Category {
None, Skin, Hair, Cloth,
Metal, Leather, Wood
}
Functions
enum Materials::Category GetCategoryName (Category cat)
Category GetCategoryValue (string cat)
Dye (string category, SValue@ sval)
int GetDyeCount (string category)
int GetDyeCount (Category category)
Dye GetDye (string category, string id)
Dye GetDye (string category, uint id)
Dye GetDye (Category category, uint id)
Dye GetRandomDye (Category category)
DyeMapping GetDyeMapping (string charClass)
array< array< vec4 > > MulticolorsFromSval (SValue@ sval)
void LoadDyesCategory (string category, array< SValue@>@ arr)
void LoadDyes ()
Variables
array< Dye@> g_dyes
array< DyeMapping@> g_dyeMappings
class Materials::DyeMapping m_category
string m_id
uint m_idHash
string m_name
array< vec4 > m_shades
ActorItemQuality m_quality
bool m_default
Enumeration Type Documentation
Category
enum Materials::Category
Enumerator
None
Skin
Hair
Cloth
Metal
Leather
Wood
Definition at line 6 of file PlayerMaterial.as.
     {
         None,
         Skin,
         Hair,
         Cloth,
         Metal,
         Leather,
         Wood
     }
Function Documentation
Dye()
Materials::Dye (string category, SValue@ sval)
Definition at line 79 of file PlayerMaterial.as.
References GetCategoryValue(), m_category, m_default, m_id, m_idHash, m_name, m_quality, m_shades, and ParseActorItemQuality().
Referenced by GetDye(), and LoadDyesCategory().
         {
             m_category = GetCategoryValue(category);
             m_id = GetParamString(UnitPtr(), sval, "id");
             m_idHash = HashString(m_id);
             m_name = GetParamString(UnitPtr(), sval, "name", false, "???");
             auto arrShades = GetParamArray(UnitPtr(), sval, "shades");
             for (uint i = 0; i < arrShades.length(); i++)
             {
                 string strColor = arrShades[i].GetString();
                 vec4 color = ParseColorRGBA(strColor);
                 m_shades.insertLast(color);
             }
             m_quality = ParseActorItemQuality(GetParamString(UnitPtr(), sval, "quality"));
             m_default = GetParamBool(UnitPtr(), sval, "default", false);
         }
GetCategoryName()
enum Materials::Category Materials::GetCategoryName (Category cat)
Definition at line 18 of file PlayerMaterial.as.
References Cloth, Hair, Leather, Metal, Skin, and Wood.
Referenced by HUD::DrawHoverItem(), and GiveAllDyesCFunc().
     {
         switch (cat)
         {
             case Category::Skin: return Resources::GetString(".materials.skin");
             case Category::Hair: return Resources::GetString(".materials.hair");
             case Category::Cloth: return Resources::GetString(".materials.cloth");
             case Category::Metal: return Resources::GetString(".materials.metal");
             case Category::Leather: return Resources::GetString(".materials.leather");
             case Category::Wood: return Resources::GetString(".materials.wood");
         }
         return "";
     }
GetCategoryValue()
Category Materials::GetCategoryValue (string cat)
Definition at line 32 of file PlayerMaterial.as.
References Cloth, Hair, Leather, Metal, None, Skin, and Wood.
Referenced by Dye(), Materials::DyeMapping::DyeMapping(), GetDye(), and GetDyeCount().
     {
              if (cat == "skin") return Category::Skin;
         else if (cat == "hair") return Category::Hair;
         else if (cat == "cloth") return Category::Cloth;
         else if (cat == "metal") return Category::Metal;
         else if (cat == "leather") return Category::Leather;
         else if (cat == "wood") return Category::Wood;
         return Category::None;
     }
GetDye() [1/3]
Dye Materials::GetDye (string category, string id)
Definition at line 117 of file PlayerMaterial.as.
References GetCategoryValue().
Referenced by GetDye(), TownRecord::Load(), Campaign::LoadPlayer(), MulticolorsFromSval(), CharacterCustomizationBase::OnFunc(), PlayerHandler::PlayerUpdateColors(), and DyeBucket::PostLoad().
     {
         return GetDye(GetCategoryValue(category), HashString(id));
     }
GetDye() [2/3]
Dye Materials::GetDye (string category, uint id)
Definition at line 122 of file PlayerMaterial.as.
References GetCategoryValue(), and GetDye().
     {
         return GetDye(GetCategoryValue(category), id);
     }
GetDye() [3/3]
Dye Materials::GetDye (Category category, uint id)
Definition at line 127 of file PlayerMaterial.as.
References Dye(), g_dyes, and GetRandomDye().
     {
         for (uint i = 0; i < g_dyes.length(); i++)
         {
             Dye@ dye = g_dyes[i];
             if (dye.m_category != category)
                 continue;
             if (dye.m_idHash == id)
                 return dye;
         }
         //TODO: This should be temporary
         PrintError("Can't find dye with category " + int(category) + " and ID " + id + ", returning random dye instead");
         return GetRandomDye(category);
     }
GetDyeCount() [1/2]
int Materials::GetDyeCount (string category)
Definition at line 101 of file PlayerMaterial.as.
References GetCategoryValue().
     {
         return GetDyeCount(GetCategoryValue(category));
     }
GetDyeCount() [2/2]
int Materials::GetDyeCount (Category category)
Definition at line 106 of file PlayerMaterial.as.
References g_dyes, and m_category.
     {
         int ret = 0;
         for (uint i = 0; i < g_dyes.length(); i++)
         {
             if (g_dyes[i].m_category == category)
                 ret++;
         }
         return ret;
     }
GetDyeMapping()
DyeMapping Materials::GetDyeMapping (string charClass)
Definition at line 165 of file PlayerMaterial.as.
References g_dyeMappings.
Referenced by CharacterCustomizationBase::ColorsChanged(), Menu::CharacterCreationMenu::Initialize(), CharacterCustomizationBase::Initialize(), Campaign::InitializePlayer(), Campaign::LoadPlayer(), MulticolorsFromSval(), and CharacterCustomizationBase::ShowSelection().
     {
         for (uint i = 0; i < g_dyeMappings.length(); i++)
         {
             auto mapping = g_dyeMappings[i];
             if (mapping.m_charClass == charClass)
                 return mapping;
         }
         return null;
     }
GetRandomDye()
Dye Materials::GetRandomDye (Category category)
Definition at line 144 of file PlayerMaterial.as.
References g_dyes, and RandomLootManager::possibleDyes.
Referenced by GetDye(), Menu::CharacterCreationMenu::Initialize(), Campaign::InitializePlayer(), Campaign::LoadPlayer(), and MulticolorsFromSval().
     {
         array<Dye@> possibleDyes;
         for (uint i = 0; i < g_dyes.length(); i++)
         {
             auto dye = g_dyes[i];
             if (dye.m_category != category)
                 continue;
             if (!dye.m_default)
                 continue;
             possibleDyes.insertLast(dye);
         }
         if (possibleDyes.length() == 0)
             return null;
         return possibleDyes[randi(possibleDyes.length())];
     }
LoadDyes()
void Materials::LoadDyes ()
Definition at line 240 of file PlayerMaterial.as.
References g_dyeMappings, and LoadDyesCategory().
Referenced by BaseGameMode::BaseGameMode().
     {
         SValue@ sval = Resources::GetSValue("tweak/playermaterials.sval");
         SValue@ svMapping = GetParamDictionary(UnitPtr(), sval, "mapping");
         dictionary dicMapping = svMapping.GetDictionary();
         auto keys = dicMapping.getKeys();
         for (uint i = 0; i < keys.length(); i++)
         {
             SValue@ svMap = null;
             dicMapping.get(keys[i], @svMap);
             DyeMapping@ newMapping = DyeMapping(keys[i], svMap.GetArray());
             g_dyeMappings.insertLast(newMapping);
         }
         LoadDyesCategory("skin", GetParamArray(UnitPtr(), sval, "skin"));
         LoadDyesCategory("hair", GetParamArray(UnitPtr(), sval, "hair"));
         LoadDyesCategory("cloth", GetParamArray(UnitPtr(), sval, "cloth"));
         LoadDyesCategory("metal", GetParamArray(UnitPtr(), sval, "metal"));
         LoadDyesCategory("leather", GetParamArray(UnitPtr(), sval, "leather"));
         LoadDyesCategory("wood", GetParamArray(UnitPtr(), sval, "wood"));
     }
LoadDyesCategory()
void Materials::LoadDyesCategory (string category, array< SValue@>@ arr)
Definition at line 230 of file PlayerMaterial.as.
References Dye(), and g_dyes.
Referenced by LoadDyes().
     {
         for (uint i = 0; i < arr.length(); i++)
         {
             SValue@ svDye = arr[i];
             Dye@ newDye = Dye(category, svDye);
             g_dyes.insertLast(newDye);
         }
     }
MulticolorsFromSval()
array<array<vec4> > Materials::MulticolorsFromSval (SValue@ sval)
Definition at line 176 of file PlayerMaterial.as.
References GetDye(), GetDyeMapping(), and GetRandomDye().
Referenced by GuildHallStatsTab::AddCharacterToList(), Menu::Initialize(), and Menu::CharacterSelectionMenu::ReloadList().
     {
         array<array<vec4>> ret;
         if (sval is null)
             return ret;
         string charClass = GetParamString(UnitPtr(), sval, "class");
         auto arrColors = GetParamArray(UnitPtr(), sval, "colors", false);
         if (arrColors !is null)
         {
             for (uint i = 0; i < arrColors.length(); i++)
             {
                 auto arrCol = arrColors[i].GetArray();
                 int category = arrCol[0].GetInteger();
                 uint id = uint(arrCol[1].GetInteger());
                 auto dye = GetDye(Category(category), id);
                 if (dye is null)
                 {
                     PrintError("Couldn't find dye with category " + category + " with ID " + id);
                     continue;
                 }
                 ret.insertLast(dye.m_shades);
             }
         }
         else
         {
             /*
             int colorSkin = GetParamInt(UnitPtr(), sval, "color-skin");
             int color1 = GetParamInt(UnitPtr(), sval, "color-1");
             int color2 = GetParamInt(UnitPtr(), sval, "color-2");
             int color3 = GetParamInt(UnitPtr(), sval, "color-3");
             ret.insertLast(colorSet.m_skin[colorSkin % colorSet.m_skin.length()]);
             ret.insertLast(colorSet.m_1[color1 % colorSet.m_1.length()]);
             ret.insertLast(colorSet.m_2[color2 % colorSet.m_2.length()]);
             ret.insertLast(colorSet.m_3[color3 % colorSet.m_3.length()]);
             */
             auto mapping = GetDyeMapping(charClass);
             if (mapping is null)
                 return ret;
             for (uint i = 0; i < mapping.m_categories.length(); i++)
             {
                 Category category = mapping.m_categories[i];
                 auto dye = GetRandomDye(category);
                 ret.insertLast(dye.m_shades);
             }
         }
         return ret;
     }
Variable Documentation
g_dyeMappings
array<DyeMapping@> Materials::g_dyeMappings
Definition at line 4 of file PlayerMaterial.as.
Referenced by GetDyeMapping(), and LoadDyes().
g_dyes
array<Dye@> Materials::g_dyes
Definition at line 3 of file PlayerMaterial.as.
Referenced by GetDye(), GetDyeCount(), TownRecord::GetOwnedDyes(), GetRandomDye(), GiveAllDyesCFunc(), LoadDyesCategory(), and RandomLootManager::NetSpawnDyeBucket().
m_category
class Materials::DyeMapping Materials::m_category
Referenced by Dye(), and GetDyeCount().
m_default
bool Materials::m_default
Definition at line 77 of file PlayerMaterial.as.
Referenced by Dye().
m_id
string Materials::m_id
Definition at line 70 of file PlayerMaterial.as.
Referenced by Dye().
m_idHash
uint Materials::m_idHash
Definition at line 71 of file PlayerMaterial.as.
Referenced by Dye(), and Fountain::GetEffect().
m_name
string Materials::m_name
Definition at line 73 of file PlayerMaterial.as.
Referenced by Dye().
m_quality
ActorItemQuality Materials::m_quality
Definition at line 76 of file PlayerMaterial.as.
Referenced by Dye().
m_shades
array<vec4> Materials::m_shades
Definition at line 75 of file PlayerMaterial.as.
Referenced by Dye().