HoHDocs: DiscordPresence Namespace Reference
DiscordPresence Namespace Reference
Functions
void Update (int ms)
void Clear ()
void SetState (string state)
void SetDetails (string details)
void AddDetails (string details)
void SetStartTimestamp (int64 timestamp)
void SetLargeImageKey (string key)
void SetLargeImageText (string text)
Variables
Discord::Status g_statusCurrent
Discord::Status g_status
int g_timeC
Function Documentation
AddDetails()
void DiscordPresence::AddDetails (string details)
Definition at line 66 of file Discord.as.
References Discord::Status::Details, and g_status.
Referenced by DungeonLevelRichPresence(), and BossLevel::Start().
     {
         g_status.Details += details;
     }
Clear()
void DiscordPresence::Clear ()
Definition at line 51 of file Discord.as.
References Discord::Status::Clear(), and g_status.
Referenced by DungeonLevelRichPresence(), MainMenu::SetMenuState(), ShortcutLevel::Start(), BossLevel::Start(), and Town::Start().
     {
         g_status.Clear();
     }
SetDetails()
void DiscordPresence::SetDetails (string details)
Definition at line 61 of file Discord.as.
References Discord::Status::Details, and g_status.
Referenced by DungeonLevelRichPresence(), BossLevel::Start(), ShortcutLevel::Start(), and Town::UpdateFrame().
     {
         g_status.Details = details;
     }
SetLargeImageKey()
void DiscordPresence::SetLargeImageKey (string key)
Definition at line 76 of file Discord.as.
References g_status, and Discord::Status::LargeImageKey.
Referenced by DungeonLevelRichPresence(), BossLevel::Start(), ShortcutLevel::Start(), and Town::Start().
     {
         g_status.LargeImageKey = key;
     }
SetLargeImageText()
void DiscordPresence::SetLargeImageText (string text)
Definition at line 81 of file Discord.as.
References g_status, Discord::Status::LargeImageText, and text.
Referenced by DungeonLevelRichPresence(), and BossLevel::Start().
     {
         g_status.LargeImageText = text;
     }
SetStartTimestamp()
void DiscordPresence::SetStartTimestamp (int64 timestamp)
Definition at line 71 of file Discord.as.
References g_status, and Discord::Status::StartTimestamp.
Referenced by DungeonLevelRichPresence(), ShortcutLevel::Start(), and BossLevel::Start().
     {
         g_status.StartTimestamp = timestamp;
     }
SetState()
void DiscordPresence::SetState (string state)
Definition at line 56 of file Discord.as.
References g_status, and Discord::Status::State.
Referenced by DungeonLevelRichPresence(), MainMenu::SetMenuState(), ShortcutLevel::Start(), BossLevel::Start(), and Town::Start().
     {
         g_status.State = state;
     }
Update()
void DiscordPresence::Update (int ms)
Definition at line 8 of file Discord.as.
References g_gameMode, g_status, g_statusCurrent, g_timeC, GetLobbyData(), GetLobbyId(), GetLobbyPlayerCount(), GetLobbyPlayerCountMax(), GetLocalPlayerRecord(), IsInLobby(), Discord::IsReady(), Discord::Status::JoinSecret, Discord::Status::LargeImageKey, Discord::Status::PartyId, Discord::Status::PartyMax, Discord::Status::PartySize, Discord::SetStatus(), Discord::Status::SmallImageKey, Discord::Status::SmallImageText, and UcFirst().
Referenced by MainMenu::UpdateFrame(), and Campaign::UpdateFrame().
     {
         if (!Discord::IsReady())
             return;
         g_timeC -= ms;
         if (g_timeC <= 0)
         {
             g_timeC = 1000;
             if (g_status.LargeImageKey == "")
                 g_status.LargeImageKey = "default";
             auto record = GetLocalPlayerRecord();
             if (record !is null)
             {
                 g_status.SmallImageKey = "class_" + record.charClass;
                 g_status.SmallImageText = record.name + " the level " + record.level + " " + UcFirst(record.charClass);
             }
             if (Lobby::IsInLobby())
             {
                 g_status.PartySize = Lobby::GetLobbyPlayerCount();
                 g_status.PartyMax = Lobby::GetLobbyPlayerCountMax();
                 g_status.PartyId = Lobby::GetLobbyData("name");
                 if (g_status.PartyId.length() == 0)
                     g_status.PartyId = "..";
                 else if (g_status.PartyId.length() == 1)
                     g_status.PartyId += ".";
                 auto gm = cast<Town>(g_gameMode);
                 if (gm !is null)
                     g_status.JoinSecret = Lobby::GetLobbyId();
             }
             if (g_statusCurrent != g_status)
             {
                 g_statusCurrent = g_status;
                 Discord::SetStatus(g_statusCurrent);
             }
         }
     }
Variable Documentation
g_status
Discord::Status DiscordPresence::g_status
Definition at line 4 of file Discord.as.
Referenced by AddDetails(), Clear(), SetDetails(), SetLargeImageKey(), SetLargeImageText(), SetStartTimestamp(), SetState(), and Update().
g_statusCurrent
Discord::Status DiscordPresence::g_statusCurrent
Definition at line 3 of file Discord.as.
Referenced by Update().
g_timeC
int DiscordPresence::g_timeC
Definition at line 6 of file Discord.as.
Referenced by Update().