HoHDocs: Stats Namespace Reference
Stats Namespace Reference
Classes
class Accomplishment
class StatList
Enumerations
enum StatType { Average }
Functions
Stat (SValue@ params)
StatDisplay GetStatDisplay (const string &in str)
int opCmp (const Stat &in other) const
string ToString (bool guildhall=false)
string ToString (int64 value, bool guildhall=false)
string ToString (int64 value, StatDisplay display)
int64 ValueInt ()
void Add (int64 value, bool checkAwards)
void AddAvg ()
void Max (int value, bool checkAwards)
int GetNumRewarded ()
void UpdateCounter ()
void Load (SValue@ svStat, bool checkAwards)
void Save (SValueBuilder &builder)
void Clear ()
void Add (const string &in name, int value, PlayerRecord@ record=null)
void AddAvg (const string &in name, PlayerRecord@ record=null)
void Max (const string &in name, int value, PlayerRecord@ record=null)
StatList LoadList (string filename)
Variables
enum Stats::StatType None
enum Stats::StatType Number
enum Stats::StatType Time
enum Stats::StatType Town
enum Stats::StatType Character
enum Stats::StatType m_name
string m_category
uint m_nameHash
bool m_town
StatType m_type
StatDisplay m_display
StatDisplay m_displayGuildhall
StatScope m_scope
bool m_hasCounter
string m_counterId
uint m_counterIdHash
array< Accomplishment@> m_accomplishments
pint64 m_valueInt
pint64 m_valueCount
string m_achievement
int64 m_achievementLimit
Enumeration Type Documentation
StatType
enum Stats::StatType
Enumerator
Average
Definition at line 3 of file Stat.as.
     {
         Number,
         Average
     }
Function Documentation
Add() [1/2]
void Stats::Add (const string &in name, int value, PlayerRecord@ record = null)
Definition at line 13 of file Stats.as.
References g_gameMode, name, and Crowd::Trigger().
     {
         if (value == 0)
             return;
         Crowd::Trigger(name, value, true);
         if (record !is null)
         {
             record.statistics.Add(name, value);
             record.statisticsSession.Add(name, value);
             if (!record.local)
                 return;
         }
         auto gm = cast<Campaign>(g_gameMode);
         if (gm !is null)
         {
             gm.m_townLocal.m_statistics.Add(name, value);
             gm.m_townLocal.CheckForNewTitle();
         }
     }
Add() [2/2]
void Stats::Add (int64 value, bool checkAwards)
Definition at line 146 of file Stat.as.
References g_isTown, m_accomplishments, m_achievement, m_achievementLimit, m_town, m_valueInt, and UpdateCounter().
Referenced by PlayerBase::AddDrink(), PlayerBase::AddItem(), Heal::Apply(), Apply(), ApplyBuff(), PlayerBase::AttuneItem(), FountainShopMenuContent::Buy(), TownhallMenuContent::BuyItem(), ChapelShopMenuContent::BuyItem(), WorldScript::PotionRefill::ClientExecute(), Craft(), Player::Damage(), Player::DamageActor(), Player::DamagedActor(), Player::Decimate(), FountainShopMenuContent::Deposit(), Campaign::DepositRun(), GiveForgeBlueprintImpl(), GiveItemImpl(), Player::Heal(), Player::KilledActor(), LoseCash(), NetGiveGoldImpl(), NetGiveKeyImpl(), Player::OnDeath(), WorldScript::StoreOre::OnFunc(), Player::OnLevelUp(), Upgrades::ModifierUpgradeStep::PayForUpgrade(), Upgrades::BuildingUpgradeStep::PayForUpgrade(), Upgrades::ItemUpgradeStep::PayForUpgrade(), Upgrades::UpgradeStep::PayForUpgrade(), Campaign::PostStart(), WorldScript::SecretFound::ServerExecute(), Player::SpendCost(), StaticLevel::Start(), BossLevel::Start(), ShortcutLevel::Start(), TestLevel::Start(), RandomLevel::Start(), Player::Update(), Campaign::UpdateFrame(), Chest::Use(), WorldScript::Well::Use(), and WinCash().
         {
             if (g_isTown && !m_town)
                 return;
             m_valueInt += value;
             if (checkAwards)
             {
                 for (uint i = 0; i < m_accomplishments.length(); i++)
                     m_accomplishments[i].OnUpdated();
                 if (m_achievementLimit > 0 && m_valueInt >= m_achievementLimit)
                 {
                     Platform::Service.UnlockAchievement(m_achievement);
                     m_achievementLimit = 0;
                 }
             }
             UpdateCounter();
         }
AddAvg() [1/2]
void Stats::AddAvg (const string &in name, PlayerRecord@ record = null)
Definition at line 37 of file Stats.as.
References g_gameMode, and name.
     {
         if (record !is null)
         {
             record.statistics.AddAvg(name);
             record.statisticsSession.AddAvg(name);
             if (!record.local)
                 return;
         }
         auto gm = cast<Campaign>(g_gameMode);
         if (gm !is null)
         {
             gm.m_townLocal.m_statistics.AddAvg(name);
             gm.m_townLocal.CheckForNewTitle();
         }
     }
AddAvg() [2/2]
void Stats::AddAvg ()
Definition at line 168 of file Stat.as.
References Average, g_isTown, m_name, m_town, m_type, m_valueCount, and UpdateCounter().
Referenced by Campaign::PostStart(), and Campaign::Start().
         {
             if (g_isTown && !m_town)
                 return;
             if (m_type != StatType::Average)
             {
                 PrintError("Tried adding average count to non-average stat \"" + m_name + "\"!");
                 return;
             }
             m_valueCount++;
             UpdateCounter();
         }
Clear()
void Stats::Clear ()
Definition at line 289 of file Stat.as.
References m_valueCount, m_valueInt, and UpdateCounter().
         {
             m_valueInt = 0;
             m_valueCount = 0;
             UpdateCounter();
         }
GetNumRewarded()
int Stats::GetNumRewarded ()
Definition at line 207 of file Stat.as.
References m_accomplishments, and m_finished.
         {
             int ret = 0;
             for (uint i = 0; i < m_accomplishments.length(); i++)
             {
                 if (m_accomplishments[i].m_finished)
                     ret++;
             }
             return ret;
         }
GetStatDisplay()
StatDisplay Stats::GetStatDisplay (const string &in str)
Definition at line 86 of file Stat.as.
References None, Number, and Time.
Referenced by Stat().
         {
             if (str == "none") return StatDisplay::None;
             else if (str == "number") return StatDisplay::Number;
             else if (str == "time") return StatDisplay::Time;
             else if (str == "distance") return StatDisplay::Distance;
             else PrintError("Unknown stat display type \"" + str + "\"");
             return StatDisplay::None;
         }
Load()
void Stats::Load (SValue@ svStat, bool checkAwards)
Definition at line 226 of file Stat.as.
References Average, m_accomplishments, m_achievement, m_achievementLimit, m_type, m_valueCount, m_valueInt, Number, and UpdateCounter().
         {
             if (m_type == StatType::Number)
             {
                 if (svStat.GetType() == SValueType::Integer)
                 {
                     m_valueInt = int64(svStat.GetInteger());
                     if (m_valueInt < 0)
                         m_valueInt += uint(-1);
                 }
                 else
                     m_valueInt = svStat.GetLong();
             }
             else if (m_type == StatType::Average && svStat.GetType() == SValueType::Array)
             {
                 auto arr = svStat.GetArray();
                 if (arr[0].GetType() == SValueType::Integer)
                 {
                     m_valueInt = int64(arr[0].GetInteger());
                     m_valueCount = int64(arr[1].GetInteger());
                 }
                 else
                 {
                     m_valueInt = arr[0].GetLong();
                     m_valueCount = arr[1].GetLong();
                 }
             }
             for (uint i = 0; i < m_accomplishments.length(); i++)
             {
                 auto reward = m_accomplishments[i];
                 if (reward.IsValueGood(m_valueInt))
                 {
                     reward.m_finished = true;
                     reward.OnLoadFinished();
                 }
             }
             if (checkAwards)
             {
                 if (m_achievementLimit > 0 && m_valueInt >= m_achievementLimit)
                 {
                     Platform::Service.UnlockAchievement(m_achievement);
                     m_achievementLimit = 0;
                 }
             }
             UpdateCounter();
         }
LoadList()
StatList Stats::LoadList (string filename)
Definition at line 75 of file Stats.as.
References Stats::StatList::AddStat(), Stats::StatList::SortStats(), and Stat().
Referenced by GuildHallStatsTab::AddCharacterToList(), and TownRecord::TownRecord().
     {
         SValue@ sval = Resources::GetSValue(filename);
         if (sval is null)
         {
             PrintError("Couldn't find statistics list file \"" + filename + "\"");
             return null;
         }
         StatList@ ret = StatList();
         array<SValue@>@ arr = sval.GetArray();
         for (uint i = 0; i < arr.length(); i++)
             ret.AddStat(Stat(arr[i]));
         ret.SortStats();
         return ret;
     }
Max() [1/2]
void Stats::Max (const string &in name, int value, PlayerRecord@ record = null)
Definition at line 56 of file Stats.as.
References g_gameMode, and name.
     {
         if (record !is null)
         {
             record.statistics.Max(name, value);
             record.statisticsSession.Max(name, value);
             if (!record.local)
                 return;
         }
         auto gm = cast<Campaign>(g_gameMode);
         if (gm !is null)
         {
             gm.m_townLocal.m_statistics.Max(name, value);
             gm.m_townLocal.CheckForNewTitle();
         }
     }
Max() [2/2]
void Stats::Max (int value, bool checkAwards)
Definition at line 183 of file Stat.as.
References g_isTown, m_accomplishments, m_achievement, m_achievementLimit, m_town, m_valueInt, and UpdateCounter().
Referenced by WorldScript::SetBossKilled::ClientExecute(), Player::Damage(), Player::DamagedActor(), PlayerHusk::KilledActor(), and Player::KilledActor().
         {
             if (g_isTown && !m_town)
                 return;
             if (value <= m_valueInt)
                 return;
             m_valueInt = value;
             if (checkAwards)
             {
                 for (uint i = 0; i < m_accomplishments.length(); i++)
                     m_accomplishments[i].OnUpdated();
                 if (m_achievementLimit > 0 && m_valueInt >= m_achievementLimit)
                 {
                     Platform::Service.UnlockAchievement(m_achievement);
                     m_achievementLimit = 0;
                 }
             }
             UpdateCounter();
         }
opCmp()
int Stats::opCmp (const Stat &in other) const
Definition at line 96 of file Stat.as.
References m_category.
         {
             return m_category.opCmp(other.m_category);
         }
Save()
void Stats::Save (SValueBuilder & builder)
Definition at line 276 of file Stat.as.
References Average, m_name, m_type, m_valueCount, m_valueInt, and Number.
         {
             if (m_type == StatType::Number)
                 builder.PushLong(m_name, m_valueInt);
             else if (m_type == StatType::Average)
             {
                 builder.PushArray(m_name);
                 builder.PushLong(m_valueInt);
                 builder.PushLong(m_valueCount);
                 builder.PopArray();
             }
         }
Stat()
Stats::Stat (SValue@ params)
Definition at line 49 of file Stat.as.
References Average, Character, GetStatDisplay(), m_accomplishments, m_achievement, m_achievementLimit, m_category, m_display, m_displayGuildhall, m_hasCounter, m_name, m_nameHash, m_scope, m_town, m_type, Number, and Town.
Referenced by Stats::StatList::Load(), LoadList(), and GuildHallAccomplishmentsTab::RefreshList().
         {
             m_name = GetParamString(UnitPtr(), params, "name");
             m_category = GetParamString(UnitPtr(), params, "category", false, "");
             m_nameHash = HashString(m_name);
             m_town = GetParamBool(UnitPtr(), params, "town", false);
             string statTypeString = GetParamString(UnitPtr(), params, "type", false, "number");
                  if (statTypeString == "number") m_type = StatType::Number;
             else if (statTypeString == "average") m_type = StatType::Average;
             else PrintError("Unknown stat type \"" + statTypeString + "\"");
             string statDisplayString = GetParamString(UnitPtr(), params, "display", false, "number");
             m_display = GetStatDisplay(statDisplayString);
             string statDisplayGuildhallString = GetParamString(UnitPtr(), params, "display-guildhall", false, statDisplayString);
             m_displayGuildhall = GetStatDisplay(statDisplayGuildhallString);
             string statScopeString = GetParamString(UnitPtr(), params, "scope", false, "global");
                  if (statScopeString == "town") m_scope = StatScope::Town;
             else if (statScopeString == "character") m_scope = StatScope::Character;
             else if (statScopeString == "global") m_scope = StatScope::Global;
             m_hasCounter = GetParamBool(UnitPtr(), params, "has-counter", false, true);
             auto arrAccomplishments =  GetParamArray(UnitPtr(), params, "rewards", false);
             if (arrAccomplishments !is null)
             {
                 for (uint i = 0; i < arrAccomplishments.length(); i++)
                     m_accomplishments.insertLast(Accomplishment(this, arrAccomplishments[i], i + 1));
             }
             m_achievement = GetParamString(UnitPtr(), params, "achievement", false);
             m_achievementLimit = GetParamInt(UnitPtr(), params, "achievement-limit", false, 0);
         }
ToString() [1/3]
string Stats::ToString (bool guildhall = false)
Definition at line 101 of file Stat.as.
References m_valueInt.
Referenced by ToString().
         {
             return ToString(m_valueInt, guildhall);
         }
ToString() [2/3]
string Stats::ToString (int64 value, bool guildhall = false)
Definition at line 106 of file Stat.as.
References m_display, m_displayGuildhall, and ToString().
         {
             if (guildhall)
                 return ToString(value, m_displayGuildhall);
             else
                 return ToString(value, m_display);
         }
ToString() [3/3]
string Stats::ToString (int64 value, StatDisplay display)
Definition at line 114 of file Stat.as.
References Average, formatMeters(), formatThousands(), formatTime(), m_type, m_valueCount, m_valueInt, None, Number, and Time.
         {
             if (display == StatDisplay::None)
                 return "";
             if (m_type == StatType::Average)
             {
                 value /= m_valueCount;
                 // Special case: If avg result is < 100 and it's a regular number,
                 // we can show the average as a float
                 if (value < 100 && display == StatDisplay::Number)
                     return "" + roundl(double(m_valueInt) / double(m_valueCount), 2);
             }
             if (display == StatDisplay::Distance)
                 return formatMeters(value);
             switch (display)
             {
                 case StatDisplay::Number: return "" + formatThousands(value);
                 case StatDisplay::Time: return formatTime(value, false, true);
             }
             return "" + value;
         }
UpdateCounter()
void Stats::UpdateCounter ()
Definition at line 218 of file Stat.as.
References m_counterIdHash, m_valueInt, and SetCounter().
Referenced by Add(), AddAvg(), Clear(), Load(), and Max().
         {
             if (m_counterIdHash == 0)
                 return;
             SetCounter(m_counterIdHash, m_valueInt);
         }
ValueInt()
int64 Stats::ValueInt ()
Definition at line 141 of file Stat.as.
References m_valueInt.
         {
             return m_valueInt;
         }
Variable Documentation
Character
enum Stats::StatType Stats::Character
Referenced by Stat().
m_accomplishments
array<Accomplishment@> Stats::m_accomplishments
Definition at line 40 of file Stat.as.
Referenced by Add(), GetNumRewarded(), Load(), Max(), and Stat().
m_achievement
string Stats::m_achievement
Definition at line 45 of file Stat.as.
Referenced by Add(), Load(), Max(), and Stat().
m_achievementLimit
int64 Stats::m_achievementLimit
Definition at line 46 of file Stat.as.
Referenced by Add(), Load(), Max(), and Stat().
m_category
string Stats::m_category
Definition at line 27 of file Stat.as.
Referenced by opCmp(), and Stat().
m_counterId
string Stats::m_counterId
Definition at line 37 of file Stat.as.
m_counterIdHash
uint Stats::m_counterIdHash
Definition at line 38 of file Stat.as.
Referenced by UpdateCounter().
m_display
StatDisplay Stats::m_display
Definition at line 32 of file Stat.as.
Referenced by Stat(), and ToString().
m_displayGuildhall
StatDisplay Stats::m_displayGuildhall
Definition at line 33 of file Stat.as.
Referenced by Stat(), and ToString().
m_hasCounter
bool Stats::m_hasCounter
Definition at line 36 of file Stat.as.
Referenced by Stat().
m_name
enum Stats::StatType Stats::m_name
Referenced by AddAvg(), Save(), and Stat().
m_nameHash
uint Stats::m_nameHash
Definition at line 28 of file Stat.as.
Referenced by Stats::StatList::GetStat(), and Stat().
m_scope
StatScope Stats::m_scope
Definition at line 34 of file Stat.as.
Referenced by Stat().
m_town
bool Stats::m_town
Definition at line 30 of file Stat.as.
Referenced by Add(), AddAvg(), Max(), and Stat().
m_type
StatType Stats::m_type
Definition at line 31 of file Stat.as.
Referenced by AddAvg(), Load(), Save(), Stat(), and ToString().
m_valueCount
pint64 Stats::m_valueCount
Definition at line 43 of file Stat.as.
Referenced by AddAvg(), Clear(), Load(), Save(), and ToString().
m_valueInt
pint64 Stats::m_valueInt
Definition at line 42 of file Stat.as.
Referenced by Add(), Clear(), Load(), Max(), Save(), ToString(), UpdateCounter(), and ValueInt().
None
enum Stats::StatType Stats::None
Referenced by GetStatDisplay(), and ToString().
Number
Stats::Number
Definition at line 5 of file Stat.as.
Referenced by GetStatDisplay(), Load(), Save(), Stat(), and ToString().
Time
enum Stats::StatType Stats::Time
Town
enum Stats::StatType Stats::Town
Referenced by Stat().