HoHDocs: MusicManager Namespace Reference
MusicManager Namespace Reference
Functions
void Initialize ()
void Update (int ms)
void Save (SValueBuilder &builder)
void Load (SValue@ save)
void Play (SoundEvent@ music)
void AddTension (float tension)
Function Documentation
AddTension()
void MusicManager::AddTension (float tension)
Definition at line 36 of file MusicManager.as.
Referenced by NetSetTarget(), and SetTarget().
     {
     }
Initialize()
void MusicManager::Initialize ()
Definition at line 3 of file MusicManager.as.
Referenced by BaseGameMode::BaseGameMode().
     {
     }
Load()
void MusicManager::Load (SValue@ save)
Definition at line 19 of file MusicManager.as.
Referenced by BaseGameMode::Start().
     {
 /*
         auto musicData = save.GetDictionaryEntry("curr-music");
         if (musicData !is null && musicData.GetType() == SValueType::String)
         {
             auto music = Resources::GetSoundEvent(musicData.GetString());
             if (music !is null)
                 Play(music);
         }
 */
     }
Play()
void MusicManager::Play (SoundEvent@ music)
Definition at line 32 of file MusicManager.as.
     {
     }
Save()
void MusicManager::Save (SValueBuilder & builder)
Definition at line 11 of file MusicManager.as.
Referenced by BaseGameMode::Save().
     {
 /*
         if (g_currMusic !is null)
             builder.PushString("curr-music", g_currMusic.GetName());
 */
     }
Update()
void MusicManager::Update (int ms)
Definition at line 7 of file MusicManager.as.
Referenced by BaseGameMode::UpdateFrame().
     {
     }