HoHDocs: Tutorial Namespace Reference
Tutorial Namespace Reference
Functions
void Initialize ()
void AssignHUD (TextWidget@ text)
void RegisterAction (string action)
void Update (int dt)
string MakeTutorialString (string id, array< ControlMapBinding@>@ bindings, string action, string name)
string GetMappedKey (array< ControlMapBinding@>@ bindings, string action)
Variables
TextWidget m_wTutorial
Function Documentation
AssignHUD()
void Tutorial::AssignHUD (TextWidget@ text)
Definition at line 17 of file Tutorial.as.
References m_wTutorial, and text.
Referenced by HUD::HUD().
     {
         @m_wTutorial = text;
         m_wTutorial.m_visible = true;
     }
GetMappedKey()
string Tutorial::GetMappedKey (array< ControlMapBinding@>@ bindings, string action)
Definition at line 88 of file Tutorial.as.
References Action.
Referenced by MakeTutorialString().
     {
         for (uint i = 0; i < bindings.length(); i++)
         {
             if (bindings[i].Action == action)
             {
                 string keyID = bindings[i].ID.toUpper();
                 keyID = keyID.replace("_", " ");
                 return keyID;
             }
         }
         return Resources::GetString("  ");
     }
Initialize()
void Tutorial::Initialize ()
Definition at line 6 of file Tutorial.as.
Referenced by BaseGameMode::BaseGameMode().
     {
         AddVar("ui_show_tutorial_attack1", 4);
         AddVar("ui_show_tutorial_attack2", 3);
         AddVar("ui_show_tutorial_map_overlay", 1);
         AddVar("ui_show_tutorial_player_menu", 1);
         AddVar("ui_show_tutorial_guild_menu", 1);
         AddVar("ui_show_tutorial_use", 2);
         AddVar("ui_show_tutorial_potion", 0); // 1
     }
MakeTutorialString()
string Tutorial::MakeTutorialString (string id, array< ControlMapBinding@>@ bindings, string action, string name)
Definition at line 69 of file Tutorial.as.
References GetMappedKey(), and name.
Referenced by Update().
     {
         int n = GetVarInt("ui_show_tutorial_" + id);
         if (n <= 0)
             return "";
         string post;
         if (n == 1)
             post = "\n";
         else if (n == 2)
             post = ".\n";
         else if (n == 3)
             post = "..\n";
         else
             post = "...\n";
         return "[" + GetMappedKey(bindings, action) + "] " + utf8string(Resources::GetString(name)).toUpper().plain() + post;
     }
RegisterAction()
void Tutorial::RegisterAction (string action)
Definition at line 23 of file Tutorial.as.
References m_wTutorial.
Referenced by Skills::ActiveSkill::Activate(), Player::Update(), Campaign::UpdateFrame(), and Campaign::UpdateWidgets().
     {
         if (!m_wTutorial.m_visible)
             return;
         int val = GetVarInt("ui_show_tutorial_" + action);
         if (val <= 0)
             return;
         SetVar("ui_show_tutorial_" + action, --val);
         Config::SaveVar("ui_show_tutorial_" + action, "" + val);
     }
Update()
void Tutorial::Update (int dt)
Definition at line 36 of file Tutorial.as.
References GetControlBindings(), GetLocalPlayerRecord(), m_wTutorial, MakeTutorialString(), and TextWidget::SetText().
Referenced by HUD::Update().
     {
         if (!m_wTutorial.m_visible)
             return;
         string tutText = "";
         auto map = GetControlBindings().GetMap("kbm");
         if (map !is null)
         {
             int n = 0;
             auto record = GetLocalPlayerRecord();
             auto bindings = map.GetBindings();
             auto player = cast<PlayerBase>(record.actor);
             if (player !is null && player.m_skills !is null && player.m_skills.length() > 1)
             {
                 tutText += MakeTutorialString("attack1", bindings, "Attack1", player.m_skills[0].m_name);
                 tutText += MakeTutorialString("attack2", bindings, "Attack2", player.m_skills[1].m_name);
             }
             tutText += MakeTutorialString("map_overlay", bindings, "MapOverlay", ".menu.controls.mapoverlay");
             tutText += MakeTutorialString("player_menu", bindings, "PlayerMenu", ".menu.controls.playermenu");
             tutText += MakeTutorialString("guild_menu", bindings, "GuildMenu", ".menu.controls.guildmenu");
             tutText += MakeTutorialString("use", bindings, "Use", ".menu.controls.use");
             tutText += MakeTutorialString("potion", bindings, "Potion", ".menu.controls.potion");
             if (tutText.length() <= 0)
                 m_wTutorial.m_visible = false;
             else
                 m_wTutorial.SetText(tutText);
         }
     }
Variable Documentation
m_wTutorial
TextWidget Tutorial::m_wTutorial
Definition at line 3 of file Tutorial.as.
Referenced by AssignHUD(), RegisterAction(), and Update().