HoHDocs: Upgrades Namespace Reference
Upgrades Namespace Reference
Classes
class BuildingUpgrade
class BuildingUpgradeStep
class ChapelShop
class DungeonShop
class ItemShop
class ItemUpgrade
class ItemUpgradeStep
class KeyUpgrade
class KeyUpgradeStep
class ModifierUpgrade
class ModifierUpgradeStep
class OreTraderUpgrade
class OreTraderUpgradeStep
class RecordUpgrade
class RecordUpgradeStep
class Shop
class SingleStepUpgrade
class Upgrade
class UpgradeShop
class UpgradeStep
Functions
ShopIterator (Shop@ shop, int level, PlayerRecord@ record)
bool AtEnd ()
Upgrade Current ()
void Next ()
Shop GetShop (string id)
Upgrade GetShopUpgrade (string id, PlayerRecord@ record)
void LoadShop (string id)
void LoadShops ()
ItemShopIterator (Shop@ shop, int level, PlayerRecord@ record)
UpgradeShopIterator (Shop@ shop, int level, PlayerRecord@ record)
Variables
class Upgrades::Shop m_shop
int m_level
PlayerRecord m_record
array< Shop@> g_shops
Upgrades::ItemShop m_index = -1
Function Documentation
AtEnd()
bool Upgrades::AtEnd () override
Definition at line 50 of file Shop.as.
 { return true; }
Current()
Upgrade Upgrades::Current () override
Definition at line 51 of file Shop.as.
 { return null; }
GetShop()
Shop Upgrades::GetShop (string id)
Definition at line 57 of file Shop.as.
References g_shops, and m_id.
Referenced by ChapelShopMenuContent::ChapelShopMenuContent(), SkillsShopMenuContent::SkillsShopMenuContent(), TownhallMenuContent::TownhallMenuContent(), and UpgradeShopMenuContent::UpgradeShopMenuContent().
     {
         for (uint i = 0; i < g_shops.length(); i++)
         {
             if (g_shops[i].m_id == id)
                 return g_shops[i];
         }
         return null;
     }
GetShopUpgrade()
Upgrade Upgrades::GetShopUpgrade (string id, PlayerRecord@ record)
Definition at line 67 of file Shop.as.
References g_shops.
Referenced by Campaign::LoadPlayer(), and PlayerHandler::PlayerGiveUpgrade().
     {
         for (uint i = 0; i < g_shops.length(); i++)
         {
             auto upgrade = g_shops[i].FindUpgrade(id, record);
             if (upgrade !is null)
                 return upgrade;
         }
         return null;
     }
ItemShopIterator()
Upgrades::ItemShopIterator (Shop@ shop, int level, PlayerRecord@ record)
Definition at line 179 of file ItemShop.as.
References m_index, and Next().
Referenced by Upgrades::ItemShop::Iterate().
         {
             super(shop, level, record);
             m_index = -1;
             Next();
         }
LoadShop()
void Upgrades::LoadShop (string id)
Definition at line 78 of file Shop.as.
References g_shops.
Referenced by LoadShops().
     {
         auto svShop = Resources::GetSValue("tweak/shops/" + id + ".sval");
         string className = GetParamString(UnitPtr(), svShop, "class");
         auto newShop = cast<Shop>(InstantiateClass(className, svShop));
         if (newShop is null)
         {
             PrintError("Failed to create shop class \"" + className + "\" for shop id \"" + id + "\"");
             return;
         }
         g_shops.insertLast(newShop);
     }
LoadShops()
void Upgrades::LoadShops ()
Definition at line 93 of file Shop.as.
References LoadShop().
Referenced by Campaign::Campaign().
     {
         LoadShop("townhall");
         LoadShop("blacksmith");
         LoadShop("apothecary");
         LoadShop("trainer");
         LoadShop("generalstore");
         LoadShop("dungeonstore");
         LoadShop("chapel");
         LoadShop("magicshop");
         LoadShop("oretrader");
     }
Next()
void Upgrades::Next () override
Definition at line 52 of file Shop.as.
Referenced by ItemShopIterator(), and UpgradeShopIterator().
 { }
ShopIterator()
Upgrades::ShopIterator (Shop@ shop, int level, PlayerRecord@ record)
Definition at line 43 of file Shop.as.
References m_level, m_record, and m_shop.
Referenced by Upgrades::Shop::Iterate().
         {
             @m_shop = shop;
             m_level = level;
             @m_record = record;
         }
UpgradeShopIterator()
Upgrades::UpgradeShopIterator (Shop@ shop, int level, PlayerRecord@ record)
Definition at line 41 of file UpgradeShop.as.
References Next().
Referenced by Upgrades::UpgradeShop::Iterate().
         {
             super(shop, level, record);
             Next();
         }
Variable Documentation
g_shops
array<Shop@> Upgrades::g_shops
Definition at line 55 of file Shop.as.
Referenced by GetShop(), GetShopUpgrade(), and LoadShop().
m_index
Upgrades::UpgradeShop Upgrades::m_index = -1
Referenced by Menu::GetInput(), ItemShopIterator(), and Menu::RemoveInput().
m_level
int Upgrades::m_level
Definition at line 40 of file Shop.as.
Referenced by Upgrades::Upgrade::GetNextLevel(), Upgrades::Upgrade::GetStep(), and ShopIterator().
m_record
PlayerRecord Upgrades::m_record
Definition at line 41 of file Shop.as.
Referenced by ShopIterator().
m_shop
class Upgrades::Shop Upgrades::m_shop
Referenced by ShopIterator().