HoHDocs: QueuedTasks Namespace Reference
QueuedTasks Namespace Reference
Classes
class QueuedTask
Functions
void Initialize ()
void Queue (int delay, QueuedTask@ task)
void Update (int ms)
void Save (SValueBuilder &builder)
void Load (SValue@ save)
Variables
abstract class QueuedTasks::QueuedTask g_queuedTasks
Function Documentation
Initialize()
void QueuedTasks::Initialize ()
Definition at line 15 of file QueuedTasks.as.
Referenced by BaseGameMode::BaseGameMode().
     {
     }
Load()
void QueuedTasks::Load (SValue@ save)
Definition at line 87 of file QueuedTasks.as.
Referenced by BaseGameMode::Start().
     {
 /*
         auto tasksData = save.GetDictionaryEntry("queued-tasks");
         if (tasksData !is null && tasksData.GetType() == SValueType::Array)
         {
         }
 */
     }
Queue()
void QueuedTasks::Queue (int delay, QueuedTask@ task)
Definition at line 19 of file QueuedTasks.as.
References QueuedTasks::QueuedTask::Execute(), g_queuedTasks, g_scene, QueuedTasks::QueuedTask::m_queued, and QueuedTasks::QueuedTask::m_time.
Referenced by DoSpawnPrefabBase(), SpawnUnitBaseHandler::DoSpawnUnitBase(), and SpawnUnitBase::SpawnUnit().
     {
         if (task is null)
             return;
         if (delay <= 0)
         {
             task.Execute();
             return;
         }
         if (task.m_queued)
         {
             PrintError("A task cannot be queued twice");
             return;
         }
         else
             task.m_queued = true;
         task.m_time = delay + g_scene.GetTime();
         uint time = task.m_time;
         for (uint i = 0; i < g_queuedTasks.length(); i++)
         {
             if (g_queuedTasks[i].m_time > time)
             {
                 g_queuedTasks.insertAt(i, task);
                 return;
             }
         }
         g_queuedTasks.insertLast(task);
     }
Save()
void QueuedTasks::Save (SValueBuilder & builder)
Definition at line 69 of file QueuedTasks.as.
Referenced by BaseGameMode::Save().
     {
         /*
         if (g_queuedTasks.length() <= 0)
             return;
         builder.PushArray("queued-tasks");
         for (uint i = 0; i < g_queuedTasks.length(); i++)
         {
             g_queuedTasks.Save(builder);
         }
         builder.PopArray();
         */
     }
Update()
void QueuedTasks::Update (int ms)
Definition at line 53 of file QueuedTasks.as.
References QueuedTasks::QueuedTask::Execute(), g_queuedTasks, and g_scene.
Referenced by BaseGameMode::UpdateFrame().
     {
         uint time = g_scene.GetTime();
         uint sit = 0;
         for (; sit < g_queuedTasks.length(); sit++)
         {
             if (g_queuedTasks[sit].m_time <= time)
                 g_queuedTasks[sit].Execute();
             else
                 break;
         }
         if (sit > 0)
             g_queuedTasks.removeRange(0, sit);
     }
Variable Documentation
g_queuedTasks
abstract class QueuedTasks::QueuedTask QueuedTasks::g_queuedTasks
Referenced by Queue(), and Update().