HoHDocs: ServicePresence Namespace Reference
ServicePresence Namespace Reference
Classes
class StatusKey
Functions
int opCmp (const Status &in status) const
void Update (int ms)
void Clear ()
void Set (string key)
void Param (string key, string value)
Variables
class ServicePresence::StatusKey m_display
array< StatusKey > m_keys
string m_groupId
int m_groupSize
Status g_statusCurrent
Status g_status
int g_timeC
Function Documentation
Clear()
void ServicePresence::Clear ()
Definition at line 83 of file Service.as.
References g_status.
Referenced by DungeonLevelRichPresence(), MainMenu::SetMenuState(), ShortcutLevel::Start(), and Town::Start().
     {
         g_status = Status();
     }
opCmp()
int ServicePresence::opCmp (const Status &in status) const
Definition at line 38 of file Service.as.
References m_display, m_groupId, m_groupSize, and m_keys.
         {
             if (m_display != status.m_display) return 1;
             if (m_keys != status.m_keys) return 1;
             if (m_groupId != status.m_groupId) return 1;
             if (m_groupSize != status.m_groupSize) return 1;
             return 0;
         }
Param()
void ServicePresence::Param (string key, string value)
Definition at line 93 of file Service.as.
References g_status.
Referenced by DungeonLevelRichPresence(), and ShortcutLevel::Start().
     {
         g_status.m_keys.insertLast(StatusKey(key, value));
     }
Set()
void ServicePresence::Set (string key)
Definition at line 88 of file Service.as.
References g_status.
Referenced by DungeonLevelRichPresence(), MainMenu::SetMenuState(), ShortcutLevel::Start(), and Town::Start().
     {
         g_status.m_display = key;
     }
Update()
void ServicePresence::Update (int ms)
Definition at line 53 of file Service.as.
References g_status, g_statusCurrent, g_timeC, GetLobbyData(), GetLobbyPlayerCount(), and IsInLobby().
Referenced by Campaign::UpdateFrame().
     {
         g_timeC -= ms;
         if (g_timeC <= 0)
         {
             g_timeC = 1000;
             if (Lobby::IsInLobby())
             {
                 g_status.m_groupId = Lobby::GetLobbyData("name");
                 g_status.m_groupSize = Lobby::GetLobbyPlayerCount();
             }
             if (g_statusCurrent != g_status)
             {
                 g_statusCurrent = g_status;
                 Platform::Service.ClearRichPresence();
                 Platform::Service.SetRichPresence(g_statusCurrent.m_display);
                 for (uint i = 0; i < g_statusCurrent.m_keys.length(); i++)
                 {
                     auto key = g_statusCurrent.m_keys[i];
                     Platform::Service.SetRichPresenceKey(key.m_key, key.m_value);
                 }
                 Platform::Service.SetRichPresenceGroup(g_statusCurrent.m_groupId);
                 Platform::Service.SetRichPresenceGroupSize(g_statusCurrent.m_groupSize);
             }
         }
     }
Variable Documentation
g_status
Status ServicePresence::g_status
Definition at line 49 of file Service.as.
Referenced by Clear(), Param(), Set(), and Update().
g_statusCurrent
Status ServicePresence::g_statusCurrent
Definition at line 48 of file Service.as.
Referenced by Update().
g_timeC
int ServicePresence::g_timeC
Definition at line 51 of file Service.as.
Referenced by Update().
m_display
class ServicePresence::StatusKey ServicePresence::m_display
Referenced by opCmp().
m_groupId
string ServicePresence::m_groupId
Definition at line 35 of file Service.as.
Referenced by opCmp().
m_groupSize
int ServicePresence::m_groupSize
Definition at line 36 of file Service.as.
Referenced by opCmp().
m_keys
array<StatusKey> ServicePresence::m_keys
Definition at line 33 of file Service.as.
Referenced by opCmp().