HoHDocs: Actor Class Reference
Actor Class Reference
Private Member Functions
Actor (UnitPtr unit)
float GetWindScale ()
void AddFloatingHurt (int num, int crit=0, FloatingTextType type=FloatingTextType::EnemyHurt)
void AddFloatingImmortal (int num, FloatingTextType type=FloatingTextType::EnemyImmortal)
void AddFloatingGive (int num, FloatingTextType type=FloatingTextType::EnemyHealed)
void SetTeam (string str, bool countsAsKill=true)
void SetTeam (uint tm, bool countsAsKill=true)
float GetHealth ()
float GetDamageMulTarget (bool melee, UnitPtr target)
void Kill (Actor@ killer, uint weapon)
int Damage (DamageInfo dmg, vec2 pos, vec2 dir) override
int Decimate (DecimateInfo dec, vec2 pos, vec2 dir) override
void NetDecimate (int hp, int mana) override
int Heal (int amount)
bool IsDead () override
bool Impenetrable () override
bool ApplyBuff (ActorBuff@ buff)
bool HasBuff (uint buff)
void KilledActor (Actor@ killed, DamageInfo di)
void NetDamage (DamageInfo dmg, vec2 pos, vec2 dir) override
void NetKill (Actor@ attacker, uint16 dmg, vec2 dir, uint weapon)
void NetHeal (int amt)
void NetSetTarget (Actor@ target)
void NetUseSkill (int skillId, int stage, vec2 pos, SValue@ param)
void SpreadTarget (Actor@ target, int spreadTargetCount)
bool IsTargetable ()
void SetImmortal (bool immortal)
bool IsImmortal (bool ignoreBuffs=false)
bool IsHusk ()
bool Ricochets () override
bool ShootThrough (vec2 pos, vec2 dir) override
bool BlockProjectile (IProjectile@ proj)
void WarnCooldown (Skills::Skill@ skill, int ms)
bool SpendCost (int mana, int stamina, int health)
int SetUnitScene (AnimString@ anim, bool resetScene)
int IconHeight ()
Private Attributes
uint Team
UnitPtr m_unit
bool m_countsAsKill
bool m_crosshairColors
bool m_floatingHurt = true
array< UnitPtr > m_attachedUnits
Detailed Description
Gets the
Definition at line 1 of file Actor.as.
Constructor & Destructor Documentation
Actor()
Actor::Actor (UnitPtr unit) inline private
Definition at line 13 of file Actor.as.
References m_unit, and unit.
     {
         m_unit = unit;
     }
Member Function Documentation
AddFloatingGive()
void Actor::AddFloatingGive (int num, FloatingTextType type = FloatingTextType::EnemyHealed) inline private
Definition at line 40 of file Actor.as.
References AddFloatingNumber(), m_unit, num, and type.
Referenced by Player::GiveMana(), NetHeal(), and Player::TakeMana().
     {
         AddFloatingNumber(type, num, m_unit.GetPosition());
     }
AddFloatingHurt()
void Actor::AddFloatingHurt (int num, int crit = 0, FloatingTextType type = FloatingTextType::EnemyHurt) inline private
Definition at line 20 of file Actor.as.
References AddFloatingNumber(), AddFloatingText(), clamp(), EnemyImmortal, m_floatingHurt, m_unit, num, and type.
Referenced by Damage(), Player::Damage(), Decimate(), Player::Decimate(), NetDamage(), NetDecimate(), and Player::NetDecimate().
     {
         if (!m_floatingHurt)
             return;
         if (crit <= 0)
             AddFloatingNumber(type, num, m_unit.GetPosition());
         else
         {
             string dmgText = Resources::GetString(".misc.dmg.crit" + clamp(crit, 0, 5), { { "dmg", num } });
             AddFloatingText(FloatingTextType::EnemyImmortal, dmgText, m_unit.GetPosition());
         }
     }
AddFloatingImmortal()
void Actor::AddFloatingImmortal (int num, FloatingTextType type = FloatingTextType::EnemyImmortal) inline private
Definition at line 34 of file Actor.as.
References AddFloatingText(), m_unit, and type.
Referenced by Damage().
     {
         AddFloatingText(type, Resources::GetString(".misc.dmg.immortal"), m_unit.GetPosition());
         //AddFloatingNumber(type, num, m_unit.GetPosition());
     }
ApplyBuff()
bool Actor::ApplyBuff (ActorBuff@ buff) inline private
Definition at line 79 of file Actor.as.
Referenced by ApplyBuff::Apply(), WorldScript::DamageUnits::ApplyDamage(), DangerArea::ApplyDamage(), Modifiers::WarlockCleaverModifier::TriggerEffects(), and UnitHandler::UnitBuffed().
 { return false; }
BlockProjectile()
bool Actor::BlockProjectile (IProjectile@ proj) inline private
Definition at line 96 of file Actor.as.
 { return false; }
Damage()
int Actor::Damage (DamageInfo dmg, vec2 pos, vec2 dir) inline override private
Definition at line 73 of file Actor.as.
Referenced by Modifiers::Thorns::DamageTaken().
 { return 0; }
Decimate()
int Actor::Decimate (DecimateInfo dec, vec2 pos, vec2 dir) inline override private
Definition at line 74 of file Actor.as.
 { return 0; }
GetDamageMulTarget()
float Actor::GetDamageMulTarget (bool melee, UnitPtr target) inline private
Definition at line 70 of file Actor.as.
Referenced by Damage(), and DoDamageUnits().
 { return 1; }
GetHealth()
float Actor::GetHealth () inline private
Definition at line 68 of file Actor.as.
Referenced by Heal::CanApply(), OverheadBossBar::Draw(), Skills::Shatter::OnEnemyKilled(), and BossBarWidget::UpdateAppearance().
 { return 1; }
GetWindScale()
float Actor::GetWindScale () inline private
Definition at line 18 of file Actor.as.
 { return 1.0f; }
HasBuff()
bool Actor::HasBuff (uint buff) inline private
Definition at line 80 of file Actor.as.
 { return false; }
Heal()
int Actor::Heal (int amount) inline private
Definition at line 76 of file Actor.as.
Referenced by Heal::Apply(), and LifestealDamage::DoDamage().
 { return 0; }
IconHeight()
int Actor::IconHeight () inline private
Definition at line 101 of file Actor.as.
 { return -20; }
Impenetrable()
bool Actor::Impenetrable () inline override private
Definition at line 78 of file Actor.as.
Referenced by ChargeMovement::OnCollide(), and ChargeMovement::Update().
 { return false; }
IsDead()
bool Actor::IsDead () inline override private
Definition at line 77 of file Actor.as.
Referenced by Player::Damage(), Modifiers::Thorns::DamageTaken(), OverheadBossBar::Draw(), SorcererProjectile::HitUnit(), NetDamage(), BossScatterBurstSkill::NewBurstShot(), Skills::Shatter::OnEnemyKilled(), QueuedFetchActors(), PlayerBase::RefreshScene(), ScriptWaypoint::ShouldStay(), SpreadTarget(), TriggerOnDeath(), and BossBarWidget::UpdateAppearance().
 { return false; }
IsHusk()
bool Actor::IsHusk () inline private
Definition at line 93 of file Actor.as.
Referenced by PlayerBase::ApplyBuff(), FilterAction(), FilterHuskDamage(), PlayerBase::RefreshModifiers(), and PriestGroundCircle::Update().
 { return !Network::IsServer(); }
IsImmortal()
bool Actor::IsImmortal (bool ignoreBuffs = false) inline private
Definition at line 92 of file Actor.as.
Referenced by Damage(), BossBarWidget::GetBarSprite(), and GetOverlayColor().
 { return false; }
IsTargetable()
bool Actor::IsTargetable () inline private
Definition at line 90 of file Actor.as.
Referenced by SorcererProjectile::HitUnit(), KillAllCFunc(), BossScatterBurstSkill::NewBurstShot(), QueuedFetchActors(), Modifiers::TriggerEffect::TriggerEffects(), SurvivalWaveProgress::Update(), and Skills::CelestialOrb::Update().
 { return true; }
Kill()
void Actor::Kill (Actor@ killer, uint weapon) inline private
Definition at line 72 of file Actor.as.
Referenced by Suicide::Apply(), Suicide::DoAction(), PlayerHusk::Kill(), Kill(), KillAllCFunc(), Suicide::NetDoAction(), and Skills::Shatter::OnEnemyKilled().
 {}
KilledActor()
void Actor::KilledActor (Actor@ killed, DamageInfo di) inline private
Definition at line 81 of file Actor.as.
Referenced by PlayerHusk::KilledActor(), Player::KilledActor(), and TriggerOnDeath().
 {}
NetDamage()
void Actor::NetDamage (DamageInfo dmg, vec2 pos, vec2 dir) inline override private
Definition at line 83 of file Actor.as.
Referenced by Damage().
 {}
NetDecimate()
void Actor::NetDecimate (int hp, int mana) inline override private
Definition at line 75 of file Actor.as.
 {}
NetHeal()
void Actor::NetHeal (int amt) inline private
Definition at line 85 of file Actor.as.
Referenced by Damage(), Heal(), and UnitHandler::UnitHealed().
 {}
NetKill()
void Actor::NetKill (Actor@ attacker, uint16 dmg, vec2 dir, uint weapon) inline private
Definition at line 84 of file Actor.as.
Referenced by UnitHandler::UnitKilled().
 {}
NetSetTarget()
void Actor::NetSetTarget (Actor@ target) inline private
Definition at line 86 of file Actor.as.
Referenced by UnitHandler::UnitTarget().
 {}
NetUseSkill()
void Actor::NetUseSkill (int skillId, int stage, vec2 pos, SValue@ param) inline private
Definition at line 87 of file Actor.as.
Referenced by NetUseSkill(), and UnitHandler::UnitUseSSkillParam().
 {}
Ricochets()
bool Actor::Ricochets () inline override private
Definition at line 94 of file Actor.as.
 { return false; }
SetImmortal()
void Actor::SetImmortal (bool immortal) inline private
Definition at line 91 of file Actor.as.
 {}
SetTeam() [1/2]
void Actor::SetTeam (string str, bool countsAsKill = true) inline private
Definition at line 45 of file Actor.as.
Referenced by CompositeActorBehavior(), and PlayerBase::PlayerBase().
     {
         SetTeam(HashString(str), countsAsKill);
     }
SetTeam() [2/2]
void Actor::SetTeam (uint tm, bool countsAsKill = true) inline private
Definition at line 50 of file Actor.as.
References g_actors, g_totalEnemies, GetActorList(), m_countsAsKill, and Team.
     {
         Team = tm;
         m_countsAsKill = countsAsKill;
         ActorCollection@ coll = GetActorList(Team);
         if (coll is null)
         {
             @coll = ActorCollection();
             coll.m_team = Team;
             g_actors.insertLast(coll);
         }
         coll.m_arr.insertLast(this);
         if (m_countsAsKill)
             g_totalEnemies++;
     }
SetUnitScene()
int Actor::SetUnitScene (AnimString@ anim, bool resetScene) inline private
Definition at line 100 of file Actor.as.
 { return 0; }
ShootThrough()
bool Actor::ShootThrough (vec2 pos, vec2 dir) inline override private
Definition at line 95 of file Actor.as.
 { return false; }
SpendCost()
bool Actor::SpendCost (int mana, int stamina, int health) inline private
Definition at line 99 of file Actor.as.
 { return true; }
SpreadTarget()
void Actor::SpreadTarget (Actor@ target, int spreadTargetCount) inline private
Definition at line 89 of file Actor.as.
Referenced by SetTarget().
 {}
WarnCooldown()
void Actor::WarnCooldown (Skills::Skill@ skill, int ms) inline private
Definition at line 98 of file Actor.as.
 {}
Member Data Documentation
m_attachedUnits
array<UnitPtr> Actor::m_attachedUnits private
Definition at line 11 of file Actor.as.
Referenced by ActorBuffIcon::ActorBuffIcon().
m_countsAsKill
bool Actor::m_countsAsKill private
Definition at line 6 of file Actor.as.
Referenced by SetTeam().
m_crosshairColors
bool Actor::m_crosshairColors private
Definition at line 8 of file Actor.as.
Referenced by PlayerHusk::PlayerHusk().
m_floatingHurt
bool Actor::m_floatingHurt = true private
Definition at line 9 of file Actor.as.
Referenced by AddFloatingHurt().
m_unit
UnitPtr Actor::m_unit private
Definition at line 4 of file Actor.as.
Referenced by Actor(), ActorBuffIcon::ActorBuffIcon(), ActorBuffList::Add(), AddFloatingGive(), AddFloatingHurt(), AddFloatingImmortal(), ShootBolt::Apply(), ShootProjectile::Apply(), PlayerBase::ApplyBuff(), ActorBuff::Attach(), Player::BlockProjectile(), BombBehavior::BombBehavior(), Player::BroadcastNetDamage(), MagicTile::ClosestPlayer(), Player::Damage(), Player::DamagedActor(), Modifiers::Thorns::DamageTaken(), Modifiers::PlayerBarrier::DamageTakenMul(), Modifiers::FlameShield::DamageTakenMul(), Player::Decimate(), distsq(), Skills::Shatter::Do(), ScreenShaker::DoAction(), ActionEffectWrapper::DoAction(), MeleeHit::DoAction(), DoAction(), Nova::DoAction(), ShootProjectile::DoAction(), LifestealDamage::DoDamage(), BombBehavior::DoExplode(), Skills::Explode::DoExplosion(), MeleeHit::DoHit(), Skills::ShootProjectile::DoShoot(), GameOver::DoShow(), SpawnPrefab::DoSpawnPrefabs(), DoSpawnUnits(), Skills::SpawnUnit::DoSpawnUnits(), OverheadBossBar::Draw(), GargoyleSpawner::GargoyleSpawner(), Player::Heal(), SorcererProjectile::HitUnit(), PlayerHusk::Initialize(), TossProjectile::Initialize(), RayProjectile::Initialize(), CannonBall::Initialize(), Player::IsDead(), Player::KilledActor(), PlayerBase::LoadSkill(), PlayerBase::LoadSkills(), PlayerBase::LoadStats(), Skills::StaggeredSpawnUnits::LocalSpawnUnit(), Skills::SpawnUnit::LocalSpawnUnit(), PlayerHusk::NetDamage(), PlayerHusk::NetDecimate(), Skills::Shatter::NetDo(), ScreenShaker::NetDoAction(), ShootProjectile::NetDoAction(), BombBehavior::NetDoExplode(), PlayerBase::NetHeal(), BossScatterBurstSkill::NewBurstShot(), ActorBuff::OnDeath(), PlayerBase::OnDeath(), Player::OnDeath(), Skills::Shatter::OnEnemyKilled(), PlayerHusk::OnLevelUp(), Player::OnLevelUp(), BombBehavior::OnSpawn(), PlayerBase::PlayerBase(), PlayerHusk::PlayerHusk(), PlayerHusk::PreRender(), Player::PreRender(), PlayerBase::RefreshScene(), BombBehavior::Save(), DangerAreaBehavior::Save(), BoltShooter::Save(), Player::SendPlayerMove(), PlayerBase::SetBodyAnim(), PlayerBase::SetColor(), SetTarget(), SpawnUnitBase::SpawnUnit(), Player::SpendCost(), TargetValue(), Skills::RiposteTrigger::TriggerEffects(), Modifiers::TriggerEffect::TriggerEffects(), TriggerOnDeath(), UnitHandler::UnitMovementChargeBegin(), UnitHandler::UnitMovementChargeLook(), GargoyleSpawner::Update(), MagicTile::Update(), MeleeSwing::Update(), BossEyeWisp::Update(), PlayerHusk::Update(), ActorBuff::Update(), PlayerBase::Update(), Player::Update(), BossBarWidget::UpdateAppearance(), Campaign::UpdateFrame(), ActorBuffList::UpdateVisual(), and Player::WarnCooldown().
Team
uint Actor::Team private
Definition at line 3 of file Actor.as.
Referenced by ShootRandomEnemy::Apply(), ApplyAreaFilter(), ApplyDamageFilter(), BombBehavior::BombBehavior(), BaseGameMode::FilterAction(), SorcererProjectile::HitUnit(), Projectile::Initialize(), RayProjectile::Initialize(), CannonBall::Initialize(), RangerProjectile::Multiply(), NetDamage(), TowerFlowerSkill::NetUseSkill(), SetTeam(), TargetValue(), PriestGroundCircle::Trigger(), and TowerFlowerSpike::Update().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Actor.as