HoHDocs: ActorBuffList Class Reference
ActorBuffList Class Reference
Private Member Functions
void Initialize (Actor@ actor)
ActorBuffIcon AddIcon (UnitProducer@ prod)
ActorBuffIcon GetIcon (UnitProducer@ prod)
void Add (ActorBuff@ buff)
void OnDeath (Actor@ actor)
void Clear ()
void UpdateVisual ()
void Update (int dt)
bool HasTags (uint64 tags)
vec2 ArmorMul ()
float MoveSpeedMul ()
float MoveSpeedMul (float slowScale)
float MoveSpeedDashMul ()
float DamageMul ()
float DamageTakenMul ()
float ExperienceMul ()
float WindScaleMul ()
float ReceiveCritChance ()
float MinSpeed ()
bool FreeMana ()
bool Disarm ()
bool Confuse ()
bool AntiConfuse ()
bool Drifting ()
bool InfDodge ()
bool Darkness ()
bool Shatterable ()
CleaveInfo Cleave ()
Private Attributes
array< ActorBuff@> m_buffs
Actor m_actor
ActorColor m_color
array< ActorBuffIcon@> m_icons
Detailed Description
Definition at line 1 of file ActorBuffList.as.
Member Function Documentation
Add()
void ActorBuffList::Add (ActorBuff@ buff) inline private
Definition at line 38 of file ActorBuffList.as.
References buff, m_actor, m_buffs, m_def, Actor::m_unit, and UpdateVisual().
Referenced by PlayerBase::ApplyBuff(), ApplyBuff(), and PlayerBase::RefreshModifiers().
     {
         if (m_actor is null)
             return;
         if (!buff.m_husk)
         {
             auto owner = (buff.m_owner !is null) ? buff.m_owner.m_unit : UnitPtr();
             (Network::Message("UnitBuffed") << m_actor.m_unit << owner << buff.m_def.m_pathHash << buff.m_intensity << buff.m_weaponInfo << buff.m_duration).SendToAll();
         }
         for (uint i = 0; i < m_buffs.length(); i++)
         {
             if (m_buffs[i].m_def is buff.m_def)
             {
                 m_buffs[i].Refresh(buff);
                 UpdateVisual();
                 return;
             }
         }
         m_buffs.insertLast(buff);
         buff.Attach(m_actor, this);
         auto player = cast<PlayerBase>(m_actor);
         if (player !is null)
             player.RefreshModifiersBuffs();
         UpdateVisual();
     }
AddIcon()
ActorBuffIcon ActorBuffList::AddIcon (UnitProducer@ prod) inline private
Definition at line 13 of file ActorBuffList.as.
References GetIcon(), icon, m_actor, and m_icons.
Referenced by ActorBuff::Attach().
     {
         auto icon = GetIcon(prod);
         if (icon !is null)
         {
             icon.AddRef();
             return icon;
         }
         auto newIcon = ActorBuffIcon(prod, m_actor);
         m_icons.insertLast(newIcon);
         return newIcon;
     }
AntiConfuse()
bool ActorBuffList::AntiConfuse () inline private
Definition at line 223 of file ActorBuffList.as.
References m_buffs, and m_def.
Referenced by Player::Update().
 { for (uint i = 0; i < m_buffs.length(); i++) { if (m_buffs[i].m_def.m_antiConfuse) return true; } return false; }
ArmorMul()
vec2 ActorBuffList::ArmorMul () inline private
Definition at line 193 of file ActorBuffList.as.
References m_buffs.
Referenced by Player::Damage(), CompositeActorBehaviorNoNGPScale::GetArmor(), and GetArmor().
 { vec2 v = 1.0; for (uint i = 0; i < m_buffs.length(); i++) { v *= m_buffs[i].m_def.m_mulArmor; } return v; }
Clear()
void ActorBuffList::Clear () inline private
Definition at line 75 of file ActorBuffList.as.
References m_actor, m_buffs, and UpdateVisual().
Referenced by Destroyed(), PlayerBase::Destroyed(), and PlayerBase::OnDeath().
     {
         for (uint i = 0; i < m_buffs.length(); i++)
             m_buffs[i].Clear();
         m_buffs.removeRange(0, m_buffs.length());
         auto player = cast<PlayerBase>(m_actor);
         if (player !is null)
             player.RefreshModifiersBuffs();
         UpdateVisual();
         @m_actor = null;
     }
Cleave()
CleaveInfo ActorBuffList::Cleave () inline private
Definition at line 230 of file ActorBuffList.as.
References m_buffs, and m_def.
Referenced by Damage().
 { for (uint i = 0; i < m_buffs.length(); i++) { if (m_buffs[i].m_def.m_cleave !is null) return m_buffs[i].m_def.m_cleave; } return null; }
Confuse()
bool ActorBuffList::Confuse () inline private
Definition at line 222 of file ActorBuffList.as.
References m_buffs, and m_def.
Referenced by Player::Update().
 { for (uint i = 0; i < m_buffs.length(); i++) { if (m_buffs[i].m_def.m_confuse) return true; } return false; }
DamageMul()
float ActorBuffList::DamageMul () inline private
Definition at line 208 of file ActorBuffList.as.
References m_buffs.
Referenced by Player::DamageActor().
 { float v = 1.0; for (uint i = 0; i < m_buffs.length(); i++) { v *= m_buffs[i].m_def.m_mulDamage; } return v; }
DamageTakenMul()
float ActorBuffList::DamageTakenMul () inline private
Definition at line 209 of file ActorBuffList.as.
References m_buffs.
Referenced by Damage(), and Player::Damage().
 { float v = 1.0; for (uint i = 0; i < m_buffs.length(); i++) { v *= m_buffs[i].m_def.m_mulDamageTaken; } return v; }
Darkness()
bool ActorBuffList::Darkness () inline private
Definition at line 226 of file ActorBuffList.as.
References m_buffs, and m_def.
 { for (uint i = 0; i < m_buffs.length(); i++) { if (m_buffs[i].m_def.m_darkness) return true; } return false; }
Disarm()
bool ActorBuffList::Disarm () inline private
Definition at line 221 of file ActorBuffList.as.
References m_buffs, and m_def.
Referenced by Player::Update().
 { for (uint i = 0; i < m_buffs.length(); i++) { if (m_buffs[i].m_def.m_disarm) return true; } return false; }
Drifting()
bool ActorBuffList::Drifting () inline private
Definition at line 224 of file ActorBuffList.as.
References m_buffs, and m_def.
Referenced by Player::Update().
 { for (uint i = 0; i < m_buffs.length(); i++) { if (m_buffs[i].m_def.m_drifting) return true; } return false; }
ExperienceMul()
float ActorBuffList::ExperienceMul () inline private
Definition at line 210 of file ActorBuffList.as.
References m_buffs.
Referenced by Player::KilledActor(), and Player::NetShareExperience().
 { float v = 1.0; for (uint i = 0; i < m_buffs.length(); i++) { v *= m_buffs[i].m_def.m_mulExperience; } return v; }
FreeMana()
bool ActorBuffList::FreeMana () inline private
Definition at line 220 of file ActorBuffList.as.
References m_buffs, and m_def.
Referenced by Player::SpendCost().
 { for (uint i = 0; i < m_buffs.length(); i++) { if (m_buffs[i].m_def.m_freeMana) return true; } return false; }
GetIcon()
ActorBuffIcon ActorBuffList::GetIcon (UnitProducer@ prod) inline private
Definition at line 27 of file ActorBuffList.as.
References icon, and m_icons.
Referenced by AddIcon().
     {
         for (uint i = 0; i < m_icons.length(); i++)
         {
             auto icon = m_icons[i];
             if (icon.m_prod is prod)
                 return m_icons[i];
         }
         return null;
     }
HasTags()
bool ActorBuffList::HasTags (uint64 tags) inline private
Definition at line 181 of file ActorBuffList.as.
References buff, and m_buffs.
     {
         for (uint i = 0; i < m_buffs.length(); i++)
         {
             auto buff = m_buffs[i];
             if ((buff.m_def.m_tags & tags) != 0)
                 return true;
         }
         return false;
     }
InfDodge()
bool ActorBuffList::InfDodge () inline private
Definition at line 225 of file ActorBuffList.as.
References m_buffs, and m_def.
 { for (uint i = 0; i < m_buffs.length(); i++) { if (m_buffs[i].m_def.m_infDodge) return true; } return false; }
Initialize()
void ActorBuffList::Initialize (Actor@ actor) inline private
Definition at line 8 of file ActorBuffList.as.
References m_actor.
Referenced by CompositeActorBehavior(), and PlayerBase::PlayerBase().
     {
         @m_actor = actor;
     }
MinSpeed()
float ActorBuffList::MinSpeed () inline private
Definition at line 217 of file ActorBuffList.as.
References m_buffs, m_def, and max.
Referenced by Player::Update().
 { float v = 0.0; for (uint i = 0; i < m_buffs.length(); i++) { v = max(v, m_buffs[i].m_def.m_minSpeed); } return v; }
MoveSpeedDashMul()
float ActorBuffList::MoveSpeedDashMul () inline private
Definition at line 207 of file ActorBuffList.as.
References m_buffs.
 { float v = 1.0; for (uint i = 0; i < m_buffs.length(); i++) { v *= m_buffs[i].m_def.m_mulSpeedDash; } return v; }
MoveSpeedMul() [1/2]
float ActorBuffList::MoveSpeedMul () inline private
Definition at line 196 of file ActorBuffList.as.
References m_buffs.
Referenced by Player::Update().
 { float v = 1.0; for (uint i = 0; i < m_buffs.length(); i++) { v *= m_buffs[i].m_def.m_mulSpeed; } return v; }
MoveSpeedMul() [2/2]
float ActorBuffList::MoveSpeedMul (float slowScale) inline private
Definition at line 197 of file ActorBuffList.as.
References lerp(), m_buffs, and m_def.
{
         float v = 1.0;
         for (uint i = 0; i < m_buffs.length(); i++) {
             if (m_buffs[i].m_def.m_mulSpeed < 1.0f)
                 v *= lerp(1.0f, m_buffs[i].m_def.m_mulSpeed, slowScale);
             else
                 v *= m_buffs[i].m_def.m_mulSpeed;
         }
         return v;
     }
OnDeath()
void ActorBuffList::OnDeath (Actor@ actor) inline private
Definition at line 69 of file ActorBuffList.as.
References m_buffs.
Referenced by TriggerOnDeath().
     {
         for (uint i = 0; i < m_buffs.length(); i++)
             m_buffs[i].OnDeath(actor);
     }
ReceiveCritChance()
float ActorBuffList::ReceiveCritChance () inline private
Definition at line 214 of file ActorBuffList.as.
References m_buffs.
 { float v = 0.0; for (uint i = 0; i < m_buffs.length(); i++) { v += m_buffs[i].m_def.m_receiveCritChance; } return v; }
Shatterable()
bool ActorBuffList::Shatterable () inline private
Definition at line 227 of file ActorBuffList.as.
References m_buffs, and m_def.
 { for (uint i = 0; i < m_buffs.length(); i++) { if (m_buffs[i].m_def.m_shatterable) return true; } return false; }
Update()
void ActorBuffList::Update (int dt) inline private
Definition at line 142 of file ActorBuffList.as.
References m_actor, m_attached, m_buffs, m_icons, and UpdateVisual().
Referenced by CompositeJammableActorBehavior::Update(), and PlayerBase::Update().
     {
         if (m_actor is null)
             return;
         bool buffRemoved = false;
         for (uint i = 0; i < m_buffs.length();)
         {
             if (!m_buffs[i].Update(dt, m_actor))
             {
                 buffRemoved = true;
                 if (m_buffs.length() == 0)
                     break;
                 m_buffs[i].Clear();
                 m_buffs.removeAt(i);
             }
             else
                 i++;
         }
         if (buffRemoved)
         {
             auto player = cast<PlayerBase>(m_actor);
             if (player !is null)
                 player.RefreshModifiersBuffs();
             UpdateVisual();
         }
         for (int i = int(m_icons.length()) - 1; i >= 0; i--)
         {
             if (m_icons[i].m_attached.m_unit.IsDestroyed())
                 m_icons.removeAt(i);
         }
     }
UpdateVisual()
void ActorBuffList::UpdateVisual () inline private
Definition at line 91 of file ActorBuffList.as.
References buff, GetHUD(), m_actor, ActorColor::m_bright, m_buffs, m_color, ActorColor::m_dark, ActorColor::m_mid, and Actor::m_unit.
Referenced by Add(), Clear(), and Update().
     {
         if (m_actor is null)
             return;
         auto hud = GetHUD();
         int numColors = 0;
         vec4 darkC(0,0,0,0);
         vec4 midC(0,0,0,0);
         vec4 brightC(0,0,0,0);
         bool gotHead = false;
         for (uint i = 0; i < m_buffs.length(); i++)
         {
             auto buff = m_buffs[i];
             auto color = buff.m_def.m_color;
             if (color !is null)
             {
                 numColors++;
                 darkC += color.m_dark;
                 midC += color.m_mid;
                 brightC += color.m_bright;
             }
             @buff.m_hudIcon = hud.ShowBuffIcon(cast<PlayerBase>(m_actor), buff);
         }
         if (numColors > 0)
         {
             auto d = vec4(numColors);
             m_color.m_dark = darkC / d;
             m_color.m_mid = midC / d;
             m_color.m_bright = brightC / d;
             //print(":" + numColors + " :: " + m_color.m_mid.x + ", " + m_color.m_mid.y + ", " + m_color.m_mid.z + ", " + m_color.m_mid.w);
             //print(":  :: " + midC.x + ", " + midC.y + ", " + midC.z + ", " + midC.w);
         }
         else
         {
             m_color.m_dark = darkC;
             m_color.m_mid = midC;
             m_color.m_bright = brightC;
         }
         m_actor.m_unit.Colorize(m_color.m_dark, m_color.m_mid, m_color.m_bright);
     }
WindScaleMul()
float ActorBuffList::WindScaleMul () inline private
Definition at line 211 of file ActorBuffList.as.
References m_buffs.
Referenced by Player::GetWindScale().
 { float v = 1.0; for (uint i = 0; i < m_buffs.length(); i++) { v *= m_buffs[i].m_def.m_mulWindScale; } return v; }
Member Data Documentation
m_actor
Actor ActorBuffList::m_actor private
Definition at line 4 of file ActorBuffList.as.
Referenced by Add(), AddIcon(), Clear(), Initialize(), Update(), and UpdateVisual().
m_buffs
array<ActorBuff@> ActorBuffList::m_buffs private
Definition at line 3 of file ActorBuffList.as.
Referenced by Add(), AntiConfuse(), ArmorMul(), Clear(), Cleave(), Confuse(), DamageMul(), DamageTakenMul(), Darkness(), Disarm(), Drifting(), ExperienceMul(), FreeMana(), PlayerBase::HasBuff(), HasBuff(), HasTags(), InfDodge(), MinSpeed(), MoveSpeedDashMul(), MoveSpeedMul(), OnDeath(), ReceiveCritChance(), PlayerBase::RefreshModifiersBuffs(), Shatterable(), Update(), UpdateVisual(), and WindScaleMul().
m_color
ActorColor ActorBuffList::m_color private
Definition at line 5 of file ActorBuffList.as.
Referenced by PlayerBase::Update(), and UpdateVisual().
m_icons
array<ActorBuffIcon@> ActorBuffList::m_icons private
Definition at line 6 of file ActorBuffList.as.
Referenced by AddIcon(), GetIcon(), and Update().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/ActorBuffList.as