HoHDocs: Suicide Class Reference
Suicide Class Reference
Private Member Functions
Suicide (UnitPtr unit, SValue &params)
bool NeedNetParams ()
void SetWeaponInformation (uint weapon)
bool DoAction (SValueBuilder@ builder, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity)
bool NetDoAction (SValue@ param, Actor@ owner, vec2 pos, vec2 dir)
void Update (int dt, int cooldown)
bool Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
bool CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
Private Attributes
uint m_weaponInfo
Detailed Description
Definition at line 1 of file Suicide.as.
Constructor & Destructor Documentation
Suicide()
Suicide::Suicide (UnitPtr unit, SValue & params) inline private
Definition at line 5 of file Suicide.as.
     {
     }
Member Function Documentation
Apply()
bool Suicide::Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk) inline private
Definition at line 31 of file Suicide.as.
References Actor::Kill(), and m_weaponInfo.
     {
         owner.Kill(owner, m_weaponInfo);
         return true;
     }
CanApply()
bool Suicide::CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) inline override private
Definition at line 37 of file Suicide.as.
     {
         return true;
     }
DoAction()
bool Suicide::DoAction (SValueBuilder@ builder, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity) inline private
Definition at line 15 of file Suicide.as.
References Actor::Kill(), and m_weaponInfo.
     {
         owner.Kill(owner, m_weaponInfo);
         return true;
     }
NeedNetParams()
bool Suicide::NeedNetParams () inline private
Definition at line 9 of file Suicide.as.
 { return false; }
NetDoAction()
bool Suicide::NetDoAction (SValue@ param, Actor@ owner, vec2 pos, vec2 dir) inline private
Definition at line 21 of file Suicide.as.
References Actor::Kill(), and m_weaponInfo.
     {
         owner.Kill(owner, m_weaponInfo);
         return true;
     }
SetWeaponInformation()
void Suicide::SetWeaponInformation (uint weapon) inline private
Definition at line 10 of file Suicide.as.
References m_weaponInfo.
     {
         m_weaponInfo = weapon;
     }
Update()
void Suicide::Update (int dt, int cooldown) inline private
Definition at line 27 of file Suicide.as.
     {
     }
Member Data Documentation
m_weaponInfo
uint Suicide::m_weaponInfo private
Definition at line 3 of file Suicide.as.
Referenced by Apply(), DoAction(), NetDoAction(), and SetWeaponInformation().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actions/Suicide.as