HoHDocs: ActorItems Class Reference
ActorItems Class Reference
Private Member Functions
void Clear ()
void AddSetFile (SValue@ sval)
void AddItemFile (SValue@ sval)
ActorItem TakeRandomItem (ActorItemQuality quality, bool mustNotBeInUse=true)
ActorItem TakeItem (string id)
ActorItem GetItem (string id)
ActorItem GetItem (uint idHash)
Private Attributes
array< ActorItem@> m_allItemsList
array< ActorSet@> m_sets
Detailed Description
Definition at line 163 of file ActorItem.as.
Member Function Documentation
AddItemFile()
void ActorItems::AddItemFile (SValue@ sval) inline private
Definition at line 216 of file ActorItem.as.
References Item(), Modifiers::LoadModifiers(), m_allItemsList, ParseActorItemQuality(), and ScriptSprite().
Referenced by AddItemFile().
     {
         auto itemsData = sval.GetDictionary();
         array<string>@ itemsKeys = itemsData.getKeys();
         for (uint i = 0; i < itemsKeys.length(); i++)
         {
             auto itemData = cast<SValue>(itemsData[itemsKeys[i]]);
             auto iconArray = GetParamArray(UnitPtr(), itemData, "icon", false);
             ActorItem@ aItem = ActorItem();
             aItem.id = itemsKeys[i];
             aItem.idHash = HashString(itemsKeys[i]);
             aItem.name = GetParamString(UnitPtr(), itemData, "name", false, "unknown");
             aItem.desc = GetParamString(UnitPtr(), itemData, "desc", false, "unknown");
             @aItem.icon = ScriptSprite(iconArray);
             aItem.inUse = false;
             aItem.quality = ParseActorItemQuality(GetParamString(UnitPtr(), itemData, "quality", false, "common"));
             aItem.cost = GetParamInt(UnitPtr(), itemData, "cost", false, 0);
             aItem.requiredFlag = GetParamString(UnitPtr(), itemData, "required-flag", false);
             aItem.buyInTown = GetParamBool(UnitPtr(), itemData, "buy-in-town", false, true);
             aItem.buyInDungeon = GetParamBool(UnitPtr(), itemData, "buy-in-dungeon", false, true);
             aItem.hasBlueprints = GetParamBool(UnitPtr(), itemData, "has-blueprints", false, false);
             aItem.modifiers = Modifiers::LoadModifiers(UnitPtr(), itemData, "", Modifiers::SyncVerb::Item, aItem.idHash);
             m_allItemsList.insertLast(aItem);
         }
     }
AddSetFile()
void ActorItems::AddSetFile (SValue@ sval) inline private
Definition at line 175 of file ActorItem.as.
References GetItem(), Modifiers::LoadModifiers(), m_sets, ActorSet::name, and Modifiers::Set.
Referenced by AddSetFile().
     {
         auto setsData = sval.GetArray();
         if (setsData is null)
             return;
         for (uint i = 0; i < setsData.length(); i++)
         {
             auto setData = cast<SValue>(setsData[i]);
             ActorSet set;
             set.name = GetParamString(UnitPtr(), setData, "name", false, "unknown");
             array<SValue@>@ items = GetParamArray(UnitPtr(), setData, "items", true);
             for (uint j = 0; j < items.length(); j++)
             {
                 auto item = GetItem(items[j].GetString());
                 if (item !is null)
                     @item.set = set;
                 else
                     PrintError("Couldn't find item '" + items[j].GetString() + "' for inclusion in a set");
             }
             for (uint j = 0; j < items.length(); j++)
             {
                 auto bonusData = GetParamDictionary(UnitPtr(), setData, "" + (j + 1), false);
                 if (bonusData is null)
                     continue;
                 ActorSetBonus bonus;
                 bonus.num = j + 1;
                 bonus.desc = GetParamString(UnitPtr(), bonusData, "desc", false, "unknown");
                 bonus.modifiers = Modifiers::LoadModifiers(UnitPtr(), bonusData, "", Modifiers::SyncVerb::Set, m_sets.length());
                 set.bonuses.insertLast(bonus);
             }
             m_sets.insertLast(set);
         }
     }
Clear()
void ActorItems::Clear () inline private
Definition at line 169 of file ActorItem.as.
References m_allItemsList, and m_sets.
     {
         m_allItemsList.removeRange(0, m_allItemsList.length());
         m_sets.removeRange(0, m_sets.length());
     }
GetItem() [1/2]
ActorItem ActorItems::GetItem (string id) inline private
Definition at line 293 of file ActorItem.as.
Referenced by AddSetFile(), WorldScript::SpawnItem::DoSpawn(), GetRespecSkillPoints(), SkillsShopMenuContent::GetRespecSkillPoints(), GiveBlueprintCFunc(), ForgeBlueprint::Load(), TownRecord::Load(), Campaign::LoadPlayer(), PlayerHandler::ModifierTriggerEffect(), OnFunc(), PlayerHandler::PlayerGiveItem(), PlayerHandler::PlayerItemAttuned(), Upgrades::ItemShop::ReadItems(), ReloadList(), Upgrades::ItemShop::RerollItems(), TakeItem(), LootBox::Update(), and InventoryWidget::UpdateFromRecord().
     {
         return GetItem(HashString(id));
     }
GetItem() [2/2]
ActorItem ActorItems::GetItem (uint idHash) inline private
Definition at line 298 of file ActorItem.as.
References idHash, and m_allItemsList.
     {
         for (uint i = 0; i < m_allItemsList.length(); i++)
         {
             if (m_allItemsList[i].idHash == idHash)
                 return m_allItemsList[i];
         }
         return null;
     }
TakeItem()
ActorItem ActorItems::TakeItem (string id) inline private
Definition at line 280 of file ActorItem.as.
References GetItem().
Referenced by GiveItemCFunc(), Campaign::LoadPlayer(), and Item::PostLoad().
     {
         ActorItem@ item = GetItem(HashString(id));
         if (item is null)
         {
             PrintError("Couldn't find item with ID \"" + id + "\"");
             return null;
         }
         item.inUse = true;
         return item;
     }
TakeRandomItem()
ActorItem ActorItems::TakeRandomItem (ActorItemQuality quality, bool mustNotBeInUse = true) inline private
Definition at line 246 of file ActorItem.as.
References g_flags, m_allItemsList, and quality.
Referenced by GiveRandomItems(), Item::Item(), Upgrades::ItemUpgrade::Set(), and LootBox::Update().
     {
         array<ActorItem@> matchingItems;
         for (uint i = 0; i < m_allItemsList.length(); i++)
         {
             auto item = m_allItemsList[i];
             if ((!mustNotBeInUse || !item.inUse) && item.quality == quality)
             {
                 if (item.requiredFlag == "" || g_flags.IsSet(item.requiredFlag))
                     matchingItems.insertLast(item);
             }
         }
         if (matchingItems.length() <= 0)
         {
             for (uint i = 0; i < m_allItemsList.length(); i++)
             {
                 auto item = m_allItemsList[i];
                 if (item.quality == quality && item.requiredFlag == "")
                     matchingItems.insertLast(item);
             }
         }
         if (matchingItems.length() <= 0)
             return null;
         auto item = matchingItems[randi(matchingItems.length())];
         if (mustNotBeInUse)
             item.inUse = true;
         return item;
     }
Member Data Documentation
m_allItemsList
array<ActorItem@> ActorItems::m_allItemsList private
Definition at line 165 of file ActorItem.as.
Referenced by AddItemFile(), Clear(), GetItem(), RandomLootManager::NetSpawnItemBlueprint(), ReloadList(), Town::Start(), and TakeRandomItem().
m_sets
array<ActorSet@> ActorItems::m_sets private
Definition at line 166 of file ActorItem.as.
Referenced by AddSetFile(), Clear(), and PlayerHandler::ModifierTriggerEffect().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/ActorItem.as