HoHDocs: TargetMovement Class Reference
TargetMovement Class Reference
Private Member Functions
TargetMovement (UnitPtr unit, SValue &params)
void FindTarget ()
void Update (int dt, bool isCasting) override
Private Attributes
string m_targetName
WorldScript m_target
int m_targetFindCd
int m_newIdlePosTimer
vec3 m_targetPos
int m_idleRadius
Detailed Description
Definition at line 1 of file TargetMovement.as.
Constructor & Destructor Documentation
TargetMovement()
TargetMovement::TargetMovement (UnitPtr unit, SValue & params) inline private
Definition at line 11 of file TargetMovement.as.
References m_idleRadius, m_targetName, and unit.
     {
         super(unit, params);
         m_targetName = GetParamString(unit, params, "target");
         m_idleRadius = GetParamInt(unit, params, "idle-radius", false, 0);
         unit.SetShouldCollideWithSame(false);
     }
Member Function Documentation
FindTarget()
void TargetMovement::FindTarget () inline private
Definition at line 20 of file TargetMovement.as.
References g_scene, m_newIdlePosTimer, m_target, m_targetFindCd, m_targetName, and m_targetPos.
Referenced by Update().
     {
         if (!Network::IsServer())
             return;
         if (g_scene is null)
             return;
         if (m_targetFindCd-- > 0)
             return;
         m_targetFindCd = 100;
         auto res = g_scene.FetchAllWorldScriptsWithComment("ScriptLink", m_targetName);
         if (res.length() > 0)
         {
             int startIdx = randi(res.length());
             for (uint i = 0; i < res.length(); i++)
             {
                 auto script = res[(startIdx + i) % res.length()];
                 if (!script.IsEnabled())
                     continue;
                 @m_target = script;
                 m_targetPos = m_target.GetUnit().GetPosition();
                 m_newIdlePosTimer = 1000;
                 return;
             }
         }
     }
Update()
void TargetMovement::Update (int dt, bool isCasting) inline override private
Definition at line 52 of file TargetMovement.as.
References MeleeMovement::CalcDirSpeed(), MeleeMovement::ClientUpdate(), FindTarget(), PathFollower::FollowPath(), AnimString::GetSceneName(), ActorMovement::m_behavior, ActorMovement::m_enabled, ActorFootsteps::m_facingDirection, MeleeMovement::m_footsteps, MeleeMovement::m_idleAnim, m_idleRadius, m_newIdlePosTimer, MeleeMovement::m_pathFollower, MeleeMovement::m_speed, MeleeMovement::m_stagger, MeleeMovement::m_standDist, m_target, m_targetPos, ActorMovement::m_unit, MeleeMovement::SetWalkingAnimation(), ActorFootsteps::Update(), xy(), and xyz().
     {
         if (!m_enabled)
             return;
         if (!Network::IsServer())
         {
             ClientUpdate(dt, isCasting, m_unit.GetMoveDir());
             return;
         }
         if (m_target is null)
             FindTarget();
         float speed = m_speed;
         if (m_stagger > 0)
         {
             m_stagger -= dt;
             speed *= 0.5;
         }
         speed *= m_behavior.m_buffs.MoveSpeedMul();
         if (!isCasting)
         {
             if (m_target is null)
             {
                 m_unit.GetPhysicsBody().SetLinearVelocity(0, 0);
                 m_unit.SetUnitScene(m_idleAnim.GetSceneName(m_dir), false);
                 return;
             }
             vec3 posMe = m_unit.GetPosition();
             auto body = m_unit.GetPhysicsBody();
             float distSq = lengthsq(posMe - m_targetPos);
             if (distSq <= m_standDist * m_standDist)
             {
                 m_newIdlePosTimer -= dt;
                 if (m_newIdlePosTimer <= 0)
                 {
                     m_newIdlePosTimer = 1000 + randi(1000);
                     m_targetPos = m_target.GetUnit().GetPosition() + xyz(randdir()) * randi(m_idleRadius);
                 }
                 vec2 dir = normalize(xy(m_targetPos - posMe));
                 m_dir = atan(dir.y, dir.x);
                 body.SetLinearVelocity(0, 0);
                 m_unit.SetUnitScene(m_idleAnim.GetSceneName(m_dir), false);
                 //body.SetStatic(true);
                 return;
             }
             //body.SetStatic(false);
             vec2 dir = m_pathFollower.FollowPath(xy(posMe), xy(m_targetPos)) * speed * CalcDirSpeed();
             if (m_behavior.m_buffs.Confuse() && !m_behavior.m_buffs.AntiConfuse())
                 dir = GetConfuseDir(dir, speed);
             if (dir.x != 0 || dir.y != 0)
             {
                 body.SetLinearVelocity(dir);
                 m_dir = atan(dir.y, dir.x);
             }
             else
             {
                 body.SetLinearVelocity(0, 0);
                 m_newIdlePosTimer = 1000 + randi(1000);
                 m_targetPos = m_target.GetUnit().GetPosition() + xyz(randdir()) * randi(m_idleRadius);
             }
             SetWalkingAnimation();
             if (m_footsteps !is null)
             {
                 m_footsteps.m_facingDirection = m_dir;
                 m_footsteps.Update(dt);
             }
         }
     }
Member Data Documentation
m_idleRadius
int TargetMovement::m_idleRadius private
Definition at line 8 of file TargetMovement.as.
Referenced by TargetMovement(), and Update().
m_newIdlePosTimer
int TargetMovement::m_newIdlePosTimer private
Definition at line 6 of file TargetMovement.as.
Referenced by FindTarget(), and Update().
m_target
WorldScript TargetMovement::m_target private
Definition at line 4 of file TargetMovement.as.
Referenced by FindTarget(), and Update().
m_targetFindCd
int TargetMovement::m_targetFindCd private
Definition at line 5 of file TargetMovement.as.
Referenced by FindTarget().
m_targetName
string TargetMovement::m_targetName private
Definition at line 3 of file TargetMovement.as.
Referenced by FindTarget(), and TargetMovement().
m_targetPos
vec3 TargetMovement::m_targetPos private
Definition at line 7 of file TargetMovement.as.
Referenced by FindTarget(), and Update().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Enemies/Movements/TargetMovement.as