HoHDocs: BossLich Class Reference
BossLich Class Reference
Private Member Functions
BossLich (UnitPtr unit, SValue &params)
void Update (int dt) override
void Collide (UnitPtr unit, vec2 pos, vec2 normal)
void Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther) override
void EndCollision (UnitPtr unit)
vec2 GetCastDirection () override
bool IsTargetable () override
bool ShootThrough (vec2 pos, vec2 dir) override
Private Attributes
array< Actor@> m_actorsInside
int m_takeMana
int m_takeManaTime
int m_takeManaTimeC
array< UnitPtr > m_insideWalls
Detailed Description
Definition at line 3 of file BossLich.as.
Constructor & Destructor Documentation
BossLich()
BossLich::BossLich (UnitPtr unit, SValue & params) inline private
Definition at line 13 of file BossLich.as.
References m_takeMana, m_takeManaTime, m_takeManaTimeC, and unit.
     {
         super(unit, params);
         m_takeMana = GetParamInt(unit, params, "take-mana", false, 5);
         m_takeManaTime = GetParamInt(unit, params, "take-mana-time", false, 100);
         m_takeManaTimeC = m_takeManaTime;
     }
Member Function Documentation
Collide() [1/2]
void BossLich::Collide (UnitPtr unit, vec2 pos, vec2 normal) inline private
Definition at line 59 of file BossLich.as.
References m_actorsInside, and unit.
     {
         auto actor = cast<Actor>(unit.GetScriptBehavior());
         if (actor is null)
             return;
         m_actorsInside.insertLast(actor);
     }
Collide() [2/2]
void BossLich::Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther) inline override private
Definition at line 68 of file BossLich.as.
References Collide, m_insideWalls, and unit.
     {
         if (unit.GetScriptBehavior() is null && !fxOther.IsSensor())
             m_insideWalls.insertLast(unit);
         CompositeActorBehavior::Collide(unit, pos, normal, fxSelf, fxOther);
     }
EndCollision()
void BossLich::EndCollision (UnitPtr unit) inline private
Definition at line 76 of file BossLich.as.
References m_actorsInside, m_insideWalls, and unit.
     {
         int wallIndex = m_insideWalls.find(unit);
         if (wallIndex != -1)
             m_insideWalls.removeAt(wallIndex);
         auto actor = cast<Actor>(unit.GetScriptBehavior());
         if (actor is null)
             return;
         int index = m_actorsInside.findByRef(actor);
         if (index != -1)
             m_actorsInside.removeAt(index);
     }
GetCastDirection()
vec2 BossLich::GetCastDirection () inline override private
Definition at line 91 of file BossLich.as.
References distsq(), g_scene, GetDirection(), m_unit, and xy().
     {
         array<UnitPtr>@ results = g_scene.FetchActorsWithOtherTeam(Team, xy(m_unit.GetPosition()), 300);
         if (results.length() == 0)
             return GetDirection();
         UnitPtr closestUnit = results[0];
         float closestDistance = distsq(results[0].GetPosition(), m_unit.GetPosition());
         for (uint i = 1; i < results.length(); i++)
         {
             float distance = distsq(results[i].GetPosition(), m_unit.GetPosition());
             if (distance < closestDistance)
             {
                 closestDistance = distance;
                 closestUnit = results[i];
             }
         }
         return normalize(xy(closestUnit.GetPosition() - m_unit.GetPosition()));
     }
IsTargetable()
bool BossLich::IsTargetable () inline override private
Definition at line 113 of file BossLich.as.
References IsTargetable(), and m_unit.
Referenced by ShootThrough().
     {
         auto body = m_unit.GetPhysicsBody();
         if (body !is null && !body.IsStatic())
             return false;
         return CompositeActorBehavior::IsTargetable();
     }
ShootThrough()
bool BossLich::ShootThrough (vec2 pos, vec2 dir) inline override private
Definition at line 122 of file BossLich.as.
References IsTargetable().
     {
         return !IsTargetable();
     }
Update()
void BossLich::Update (int dt) inline override private
Definition at line 22 of file BossLich.as.
References g_lichRoom, IsCasting(), WorldScript::BossLichRoom::IsInside(), m_actorsInside, m_insideWalls, m_skills, m_takeMana, m_takeManaTime, m_takeManaTimeC, m_target, m_targetSearchCd, m_unit, and Update().
     {
         if (g_lichRoom is null)
         {
             PrintError("You forgot to place a BossLichRoom worldscript!");
             return;
         }
         if (!g_lichRoom.IsInside(m_unit.GetPosition()) || m_insideWalls.length() > 0)
             @m_target = null;
         else if (m_target is null)
             m_targetSearchCd = 0;
         CompositeActorBehavior::Update(dt);
         for (uint i = 0; i < m_skills.length(); i++)
         {
             if (m_skills[i].IsCasting())
                 return;
         }
         m_takeManaTimeC -= dt;
         if (m_takeManaTimeC <= 0)
         {
             m_takeManaTimeC = m_takeManaTime;
             for (uint i = 0; i < m_actorsInside.length(); i++)
             {
                 auto player = cast<Player>(m_actorsInside[i]);
                 if (player is null)
                     continue;
                 player.TakeMana(m_takeMana);
             }
         }
     }
Member Data Documentation
m_actorsInside
array<Actor@> BossLich::m_actorsInside private
Definition at line 5 of file BossLich.as.
Referenced by Collide(), EndCollision(), and Update().
m_insideWalls
array<UnitPtr> BossLich::m_insideWalls private
Definition at line 11 of file BossLich.as.
Referenced by Collide(), EndCollision(), and Update().
m_takeMana
int BossLich::m_takeMana private
Definition at line 7 of file BossLich.as.
Referenced by BossLich(), and Update().
m_takeManaTime
int BossLich::m_takeManaTime private
Definition at line 8 of file BossLich.as.
Referenced by BossLich(), and Update().
m_takeManaTimeC
int BossLich::m_takeManaTimeC private
Definition at line 9 of file BossLich.as.
Referenced by BossLich(), and Update().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Enemies/BossLich.as