HoHDocs: BossVampire Class Reference
BossVampire Class Reference
Private Member Functions
BossVampire (UnitPtr unit, SValue &params)
SValue Save () override
void Load (SValue@ data) override
void PostLoad (SValue@ data) override
void Update (int dt) override
void Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther) override
void EndCollision (UnitPtr unit)
void NetOnNodeArrived ()
void OnNodeArrived ()
vec2 GetCastDirection () override
bool IsTargetable () override
bool ShootThrough (vec2 pos, vec2 dir) override
Private Attributes
array< UnitPtr > m_insideWalls
int m_roaming
int m_roamingC = -1
float m_roamChance
string m_roamFlag
UnitProducer m_prodRoam
SoundEvent m_sndRoam
int m_roamSpawnTime
int m_roamSpawnTimeC
Detailed Description
Definition at line 1 of file BossVampire.as.
Constructor & Destructor Documentation
BossVampire()
BossVampire::BossVampire (UnitPtr unit, SValue & params) inline private
Definition at line 16 of file BossVampire.as.
References m_frozen, m_prodRoam, m_roamChance, m_roamFlag, m_roaming, m_roamSpawnTime, m_sndRoam, and unit.
     {
         super(unit, params);
         m_roaming = GetParamInt(unit, params, "roaming", false, 3);
         m_roamChance = GetParamFloat(unit, params, "roam-chance", false, 0.25f);
         m_roamFlag = GetParamString(unit, params, "roam-flag", false, "vampire_roaming");
         @m_prodRoam = Resources::GetUnitProducer(GetParamString(unit, params, "roam-unit", false, "doodads/generic/trap_barrel_bomb.unit"));
         @m_sndRoam = Resources::GetSoundEvent(GetParamString(unit, params, "roam-unit-snd", false));
         m_roamSpawnTime = GetParamInt(unit, params, "roam-unit-interval", false, 150);
         m_frozen = true;
     }
Member Function Documentation
Collide()
void BossVampire::Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther) inline override private
Definition at line 88 of file BossVampire.as.
References Collide, m_insideWalls, and unit.
     {
         if (unit.GetScriptBehavior() is null && !fxOther.IsSensor())
             m_insideWalls.insertLast(unit);
         CompositeActorBehavior::Collide(unit, pos, normal, fxSelf, fxOther);
     }
EndCollision()
void BossVampire::EndCollision (UnitPtr unit) inline private
Definition at line 96 of file BossVampire.as.
References m_insideWalls, and unit.
     {
         int wallIndex = m_insideWalls.find(unit);
         if (wallIndex != -1)
             m_insideWalls.removeAt(wallIndex);
     }
GetCastDirection()
vec2 BossVampire::GetCastDirection () inline override private
Definition at line 122 of file BossVampire.as.
References distsq(), g_scene, GetDirection(), m_unit, and xy().
     {
         array<UnitPtr>@ results = g_scene.FetchActorsWithOtherTeam(Team, xy(m_unit.GetPosition()), 300);
         if (results.length() == 0)
             return GetDirection();
         UnitPtr closestUnit = results[0];
         float closestDistance = distsq(results[0].GetPosition(), m_unit.GetPosition());
         for (uint i = 1; i < results.length(); i++)
         {
             float distance = distsq(results[i].GetPosition(), m_unit.GetPosition());
             if (distance < closestDistance)
             {
                 closestDistance = distance;
                 closestUnit = results[i];
             }
         }
         return normalize(xy(closestUnit.GetPosition() - m_unit.GetPosition()));
     }
IsTargetable()
bool BossVampire::IsTargetable () inline override private
Definition at line 144 of file BossVampire.as.
References IsTargetable(), and m_unit.
Referenced by ShootThrough().
     {
         auto body = m_unit.GetPhysicsBody();
         if (body !is null && !body.IsStatic())
             return false;
         return CompositeActorBehavior::IsTargetable();
     }
Load()
void BossVampire::Load (SValue@ data) inline override private
Definition at line 45 of file BossVampire.as.
References Load(), m_roamingC, and m_roamSpawnTimeC.
     {
         SValue@ svComposite = data.GetDictionaryEntry("composite");
         if (svComposite !is null)
         {
             m_roamingC = GetParamInt(UnitPtr(), data, "roaming", false, m_roamingC);
             m_roamSpawnTimeC = GetParamInt(UnitPtr(), data, "roaming-spawn-time", false, m_roamSpawnTimeC);
             CompositeActorBehavior::Load(svComposite);
         }
         else
             CompositeActorBehavior::Load(data);
     }
NetOnNodeArrived()
void BossVampire::NetOnNodeArrived () inline private
Definition at line 103 of file BossVampire.as.
References m_roamingC.
Referenced by BossVampireMovement::NetOnNodeArrived().
     {
         if (m_roamingC >= 0)
             m_roamingC--;
     }
OnNodeArrived()
void BossVampire::OnNodeArrived () inline private
Definition at line 109 of file BossVampire.as.
References g_flags, g_vampireCenterNode, m_movement, m_roamChance, m_roamFlag, m_roaming, m_roamingC, and m_unit.
Referenced by BossVampireMovement::OnNodeArrived().
     {
         auto movement = cast<BossVampireMovement>(m_movement);
         if (g_flags.IsSet(m_roamFlag) && movement.m_nodeTarget !is g_vampireCenterNode)
         {
             if (m_roamingC == -1 && randf() <= m_roamChance)
             {
                 m_roamingC = m_roaming;
                 (Network::Message("VampireBossRoaming") << m_unit).SendToAll();
             }
         }
     }
PostLoad()
void BossVampire::PostLoad (SValue@ data) inline override private
Definition at line 59 of file BossVampire.as.
References PostLoad().
     {
         SValue@ svComposite = data.GetDictionaryEntry("composite");
         if (svComposite !is null)
             CompositeActorBehavior::PostLoad(svComposite);
         else
             CompositeActorBehavior::PostLoad(data);
     }
Save()
SValue BossVampire::Save () inline override private
Definition at line 31 of file BossVampire.as.
References m_roamingC, m_roamSpawnTimeC, and Save().
     {
         SValueBuilder builder;
         builder.PushDictionary();
         builder.PushInteger("roaming", m_roamingC);
         builder.PushInteger("roaming-spawn-time", m_roamSpawnTimeC);
         builder.PushSimple("composite", CompositeActorBehavior::Save());
         builder.PopDictionary();
         return builder.Build();
     }
ShootThrough()
bool BossVampire::ShootThrough (vec2 pos, vec2 dir) inline override private
Definition at line 153 of file BossVampire.as.
References IsTargetable().
     {
         return !IsTargetable();
     }
Update()
void BossVampire::Update (int dt) inline override private
Definition at line 68 of file BossVampire.as.
References g_scene, m_prodRoam, m_roamingC, m_roamSpawnTime, m_roamSpawnTimeC, m_sndRoam, m_target, m_targetSearchCd, m_unit, PlaySound3D(), and Update().
     {
         if (m_target is null)
             m_targetSearchCd = 0;
         if (m_roamingC > 0)
         {
             m_roamSpawnTimeC -= dt;
             if (m_roamSpawnTimeC <= 0)
             {
                 m_roamSpawnTimeC = m_roamSpawnTime;
                 vec3 pos = m_unit.GetPosition();
                 m_prodRoam.Produce(g_scene, pos);
                 PlaySound3D(m_sndRoam, pos);
             }
         }
         CompositeActorBehavior::Update(dt);
     }
Member Data Documentation
m_insideWalls
array<UnitPtr> BossVampire::m_insideWalls private
Definition at line 3 of file BossVampire.as.
Referenced by Collide(), and EndCollision().
m_prodRoam
UnitProducer BossVampire::m_prodRoam private
Definition at line 11 of file BossVampire.as.
Referenced by BossVampire(), and Update().
m_roamChance
float BossVampire::m_roamChance private
Definition at line 8 of file BossVampire.as.
Referenced by BossVampire(), and OnNodeArrived().
m_roamFlag
string BossVampire::m_roamFlag private
Definition at line 9 of file BossVampire.as.
Referenced by BossVampire(), and OnNodeArrived().
m_roaming
int BossVampire::m_roaming private
Definition at line 5 of file BossVampire.as.
Referenced by BossVampire(), and OnNodeArrived().
m_roamingC
int BossVampire::m_roamingC = -1 private
Definition at line 6 of file BossVampire.as.
Referenced by BossVampireMovement::DoWalkPaths(), BossVampireMovement::FindNewNode(), Load(), NetOnNodeArrived(), OnNodeArrived(), BossVampireMovement::OnNodeArrived(), Save(), Update(), and BossVampireMovement::Update().
m_roamSpawnTime
int BossVampire::m_roamSpawnTime private
Definition at line 13 of file BossVampire.as.
Referenced by BossVampire(), and Update().
m_roamSpawnTimeC
int BossVampire::m_roamSpawnTimeC private
Definition at line 14 of file BossVampire.as.
Referenced by Load(), Save(), and Update().
m_sndRoam
SoundEvent BossVampire::m_sndRoam private
Definition at line 12 of file BossVampire.as.
Referenced by BossVampire(), and Update().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Enemies/BossVampire.as