HoHDocs: CompositeActorPeriodicTriggeredSkill Class Reference
CompositeActorPeriodicTriggeredSkill Class Reference
Private Member Functions
CompositeActorPeriodicTriggeredSkill (UnitPtr unit, SValue &params)
void Initialize (UnitPtr unit, CompositeActorBehavior &behavior, int id) override
void Update (int dt, bool isCasting) override
Private Attributes
int m_period
float m_periodC
int m_periodRandom
bool m_mustHaveTarget
vec2 m_lastPos
Detailed Description
Definition at line 1 of file CompositeActorPeriodicTriggeredSkill.as.
Constructor & Destructor Documentation
CompositeActorPeriodicTriggeredSkill()
CompositeActorPeriodicTriggeredSkill::CompositeActorPeriodicTriggeredSkill (UnitPtr unit, SValue & params) inline private
Definition at line 13 of file CompositeActorPeriodicTriggeredSkill.as.
References m_castTarget, m_mustHaveTarget, m_period, m_periodC, m_periodRandom, m_trigger, m_unit, OnMove, OnTime, and unit.
     {
         super(unit, params);
         string trigger = GetParamString(unit, params, "trigger");
         if (trigger == "OnMove")
             m_trigger = SkillTrigger::OnMove;
         else if (trigger == "OnTime")
             m_trigger = SkillTrigger::OnTime;
         m_period = GetParamInt(unit, params, "period", false, 100);
         m_periodRandom = GetParamInt(unit, params, "period-rand", false);
         m_periodC = float(m_period + m_periodRandom);
         m_mustHaveTarget = GetParamBool(unit, params, "must-have-target", false);
         m_castTarget = m_unit;
     }
Member Function Documentation
Initialize()
void CompositeActorPeriodicTriggeredSkill::Initialize (UnitPtr unit, CompositeActorBehavior & behavior, int id) inline override private
Definition at line 31 of file CompositeActorPeriodicTriggeredSkill.as.
References Initialize(), m_lastPos, m_unit, unit, and xy().
     {
         CompositeActorTriggeredSkill::Initialize(unit, behavior, id);
         m_lastPos = xy(m_unit.GetPosition());
     }
Update()
void CompositeActorPeriodicTriggeredSkill::Update (int dt, bool isCasting) inline override private
Definition at line 37 of file CompositeActorPeriodicTriggeredSkill.as.
References IsAvailable(), m_behavior, m_castPointC, m_lastPos, m_mustHaveTarget, m_period, m_periodC, m_periodRandom, m_trigger, m_unit, OnMove, OnTime, Trigger(), Update(), and xy().
Referenced by BossLichRandomSkill::Update().
     {
         CompositeActorTriggeredSkill::Update(dt, isCasting);
         if (!Network::IsServer())
             return;
         if (m_castPointC > 0 || isCasting)
             return;
         if (m_mustHaveTarget && m_behavior.m_target is null)
             return;
         if (m_trigger == SkillTrigger::OnMove)
         {
             auto pos = xy(m_unit.GetPosition());
             auto movedDt = dist(pos, m_lastPos);
             m_lastPos = pos;
             m_periodC -= movedDt;
         }
         else if (m_trigger == SkillTrigger::OnTime)
             m_periodC -= dt;
         if (m_periodC <= 0)
         {
             m_periodC += m_period + randi(m_periodRandom);
             if (!IsAvailable())
                 return;
             Trigger(m_unit);
         }
     }
Member Data Documentation
m_lastPos
vec2 CompositeActorPeriodicTriggeredSkill::m_lastPos private
Definition at line 10 of file CompositeActorPeriodicTriggeredSkill.as.
Referenced by Initialize(), and Update().
m_mustHaveTarget
bool CompositeActorPeriodicTriggeredSkill::m_mustHaveTarget private
Definition at line 8 of file CompositeActorPeriodicTriggeredSkill.as.
Referenced by CompositeActorPeriodicTriggeredSkill(), and Update().
m_period
int CompositeActorPeriodicTriggeredSkill::m_period private
Definition at line 3 of file CompositeActorPeriodicTriggeredSkill.as.
Referenced by CompositeActorPeriodicTriggeredSkill(), BossLichRandomSkill::Update(), and Update().
m_periodC
float CompositeActorPeriodicTriggeredSkill::m_periodC private
Definition at line 4 of file CompositeActorPeriodicTriggeredSkill.as.
Referenced by CompositeActorPeriodicTriggeredSkill(), BossLichRandomSkill::Update(), and Update().
m_periodRandom
int CompositeActorPeriodicTriggeredSkill::m_periodRandom private
Definition at line 6 of file CompositeActorPeriodicTriggeredSkill.as.
Referenced by CompositeActorPeriodicTriggeredSkill(), BossLichRandomSkill::Update(), and Update().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Enemies/Skills/CompositeActorPeriodicTriggeredSkill.as