HoHDocs: Modifiers::CriticalHitTrigger Class Reference
Modifiers::CriticalHitTrigger Class Reference
Private Member Functions
CriticalHitTrigger (UnitPtr unit, SValue &params)
bool HasTriggerEffects () override
bool HasCrit () override
float CritChance (bool spell) override
int Crit (PlayerBase@ player, Actor@ enemy, bool spell) override
bool RollCrit (bool spell)
Private Attributes
float m_critChance
float m_spellChance
Detailed Description
Definition at line 3 of file CriticalHitTrigger.as.
Constructor & Destructor Documentation
CriticalHitTrigger()
Modifiers::CriticalHitTrigger::CriticalHitTrigger (UnitPtr unit, SValue & params) inline private
Definition at line 8 of file CriticalHitTrigger.as.
References Modifiers::TriggerEffect::m_chance, m_critChance, m_spellChance, Modifiers::TriggerEffect::m_trigger, None, and unit.
         {
             super(unit, params);
             m_critChance = GetParamFloat(unit, params, "chance", false, 0);
             m_spellChance = GetParamFloat(unit, params, "spell-chance", false, 0);
             m_trigger = EffectTrigger::None;
             m_chance = GetParamFloat(unit, params, "trigger-chance", false, 10);
         }
Member Function Documentation
Crit()
int Modifiers::CriticalHitTrigger::Crit (PlayerBase@ player, Actor@ enemy, bool spell) inline override private
Definition at line 23 of file CriticalHitTrigger.as.
References None, RollCrit(), and Modifiers::TriggerEffect::TriggerEffects().
         {
             if (!RollCrit(spell))
                 return 0;
             TriggerEffects(player, enemy, EffectTrigger::None);
             return 1;
         }
CritChance()
float Modifiers::CriticalHitTrigger::CritChance (bool spell) inline override private
Definition at line 21 of file CriticalHitTrigger.as.
References m_critChance, and m_spellChance.
 { return spell ? m_spellChance : m_critChance; }
HasCrit()
bool Modifiers::CriticalHitTrigger::HasCrit () inline override private
Definition at line 20 of file CriticalHitTrigger.as.
 { return true; }
HasTriggerEffects()
bool Modifiers::CriticalHitTrigger::HasTriggerEffects () inline override private
Definition at line 19 of file CriticalHitTrigger.as.
 { return false; }
RollCrit()
bool Modifiers::CriticalHitTrigger::RollCrit (bool spell) inline private
Definition at line 32 of file CriticalHitTrigger.as.
References m_critChance, and m_spellChance.
Referenced by Crit().
         {
             if (spell)
                 return (randf() <= m_spellChance);
             return (randf() <= m_critChance);
         }
Member Data Documentation
m_critChance
float Modifiers::CriticalHitTrigger::m_critChance private
Definition at line 5 of file CriticalHitTrigger.as.
Referenced by CritChance(), CriticalHitTrigger(), and RollCrit().
m_spellChance
float Modifiers::CriticalHitTrigger::m_spellChance private
Definition at line 6 of file CriticalHitTrigger.as.
Referenced by CritChance(), CriticalHitTrigger(), and RollCrit().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Modifiers/CriticalHitTrigger.as