HoHDocs: Modifiers::WarlockCleaverModifier Class Reference
Modifiers::WarlockCleaverModifier Class Reference
Private Member Functions
WarlockCleaverModifier (UnitPtr unit, SValue &params)
bool HasTriggerEffects () override
void TriggerEffects (PlayerBase@ player, Actor@ enemy, EffectTrigger trigger) override
Private Attributes
ActorBuffDef m_buff
Detailed Description
Definition at line 3 of file WarlockCleaverModifier.as.
Constructor & Destructor Documentation
WarlockCleaverModifier()
Modifiers::WarlockCleaverModifier::WarlockCleaverModifier (UnitPtr unit, SValue & params) inline private
Definition at line 7 of file WarlockCleaverModifier.as.
References LoadActorBuff(), m_buff, and unit.
         {
             @m_buff = LoadActorBuff(GetParamString(unit, params, "buff"));
         }
Member Function Documentation
HasTriggerEffects()
bool Modifiers::WarlockCleaverModifier::HasTriggerEffects () inline override private
Definition at line 12 of file WarlockCleaverModifier.as.
 { return true; }
TriggerEffects()
void Modifiers::WarlockCleaverModifier::TriggerEffects (PlayerBase@ player, Actor@ enemy, EffectTrigger trigger) inline override private
Definition at line 13 of file WarlockCleaverModifier.as.
References ActorBuffDef(), Actor::ApplyBuff(), Hit, m_buff, PlayerBase::m_record, and PlayerBase::m_skills.
         {
             if (trigger != EffectTrigger::Hit)
                 return;
             auto skill = cast<Skills::MeleeSwing>(player.m_skills[0]);
             if (skill is null)
                 return;
             ActorBuffDef@ buffDef = null;
             for (uint i = 0; i < skill.m_effects.length(); i++)
             {
                 auto buffEffect = cast<ApplyBuff>(skill.m_effects[i]);
                 if (buffEffect !is null)
                 {
                     @buffDef = buffEffect.m_buff;
                     break;
                 }
             }
             if (buffDef is null)
                 return;
             auto newBuff = ActorBuff(player, m_buff, 1.0f, !player.m_record.local);
             newBuff.m_duration = buffDef.m_duration;
             enemy.ApplyBuff(newBuff);
         }
Member Data Documentation
m_buff
ActorBuffDef Modifiers::WarlockCleaverModifier::m_buff private
Definition at line 5 of file WarlockCleaverModifier.as.
Referenced by TriggerEffects(), and WarlockCleaverModifier().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Modifiers/WarlockCleaverModifier.as