HoHDocs: Modifiers::Markham Class Reference
Modifiers::Markham Class Reference
Private Member Functions
Markham (UnitPtr unit, SValue &params)
bool HasStatsAdd () override
bool HasDamagePower () override
bool HasArmorAdd () override
bool HasOreGainScale () override
bool HasGoldGainScale () override
bool HasSkillTimeMul () override
ivec2 StatsAdd (PlayerBase@ player) override
ivec2 DamagePower (PlayerBase@ player, Actor@ enemy) override
vec2 ArmorAdd (PlayerBase@ player, Actor@ enemy) override
float OreGainScale (PlayerBase@ player) override
float GoldGainScale (PlayerBase@ player) override
float SkillTimeMul (PlayerBase@ player) override
int GetNumItems (PlayerBase@ player)
ivec2 ToIVec (vec2 v)
Private Attributes
vec2 m_stats
vec2 m_power
vec2 m_armor
float m_oreScale
float m_goldScale
float m_skillMul
Detailed Description
Definition at line 3 of file Markham.as.
Constructor & Destructor Documentation
Markham()
Modifiers::Markham::Markham (UnitPtr unit, SValue & params) inline private
Definition at line 12 of file Markham.as.
References m_armor, m_goldScale, m_oreScale, m_power, m_skillMul, m_stats, and unit.
         {
             m_stats = vec2(
                 GetParamFloat(unit, params, "health", false, 0),
                 GetParamFloat(unit, params, "mana", false, 0));
             m_power = vec2(
                 GetParamFloat(unit, params, "attack-power", false, 0),
                 GetParamFloat(unit, params, "spell-power", false, 0));
             m_armor = vec2(
                 GetParamFloat(unit, params, "armor", false, 0),
                 GetParamFloat(unit, params, "resistance", false, 0)
             );
             m_oreScale = GetParamFloat(unit, params, "ore-scale", false, 0);
             m_goldScale = GetParamFloat(unit, params, "gold-scale", false, 0);
             m_skillMul = GetParamFloat(unit, params, "skill-mul", false, 0);
         }
Member Function Documentation
ArmorAdd()
vec2 Modifiers::Markham::ArmorAdd (PlayerBase@ player, Actor@ enemy) inline override private
Definition at line 42 of file Markham.as.
References GetNumItems(), and m_armor.
 { return m_armor * GetNumItems(player); }
DamagePower()
ivec2 Modifiers::Markham::DamagePower (PlayerBase@ player, Actor@ enemy) inline override private
Definition at line 41 of file Markham.as.
References GetNumItems(), m_power, and ToIVec().
 { return ToIVec(m_power * GetNumItems(player)); }
GetNumItems()
int Modifiers::Markham::GetNumItems (PlayerBase@ player) inline private
Definition at line 48 of file Markham.as.
References PlayerBase::m_record.
Referenced by ArmorAdd(), DamagePower(), GoldGainScale(), OreGainScale(), SkillTimeMul(), and StatsAdd().
 { return player.m_record.items.length(); }
GoldGainScale()
float Modifiers::Markham::GoldGainScale (PlayerBase@ player) inline override private
Definition at line 45 of file Markham.as.
References GetNumItems(), and m_goldScale.
 { return 1 + m_goldScale * GetNumItems(player); }
HasArmorAdd()
bool Modifiers::Markham::HasArmorAdd () inline override private
Definition at line 34 of file Markham.as.
 { return true; }
HasDamagePower()
bool Modifiers::Markham::HasDamagePower () inline override private
Definition at line 33 of file Markham.as.
 { return true; }
HasGoldGainScale()
bool Modifiers::Markham::HasGoldGainScale () inline override private
Definition at line 36 of file Markham.as.
 { return true; }
HasOreGainScale()
bool Modifiers::Markham::HasOreGainScale () inline override private
Definition at line 35 of file Markham.as.
 { return true; }
HasSkillTimeMul()
bool Modifiers::Markham::HasSkillTimeMul () inline override private
Definition at line 37 of file Markham.as.
 { return true; }
HasStatsAdd()
bool Modifiers::Markham::HasStatsAdd () inline override private
Definition at line 32 of file Markham.as.
 { return true; }
OreGainScale()
float Modifiers::Markham::OreGainScale (PlayerBase@ player) inline override private
Definition at line 44 of file Markham.as.
References GetNumItems(), and m_oreScale.
 { return 1 + m_oreScale * GetNumItems(player); }
SkillTimeMul()
float Modifiers::Markham::SkillTimeMul (PlayerBase@ player) inline override private
Definition at line 46 of file Markham.as.
References GetNumItems(), and m_skillMul.
 { return 1 + m_skillMul * GetNumItems(player); }
StatsAdd()
ivec2 Modifiers::Markham::StatsAdd (PlayerBase@ player) inline override private
Definition at line 40 of file Markham.as.
References GetNumItems(), m_stats, and ToIVec().
 { return ToIVec(m_stats * GetNumItems(player)); }
ToIVec()
ivec2 Modifiers::Markham::ToIVec (vec2 v) inline private
Definition at line 49 of file Markham.as.
Referenced by DamagePower(), and StatsAdd().
 { return ivec2(int(v.x), int(v.y)); }
Member Data Documentation
m_armor
vec2 Modifiers::Markham::m_armor private
Definition at line 7 of file Markham.as.
Referenced by ArmorAdd(), and Markham().
m_goldScale
float Modifiers::Markham::m_goldScale private
Definition at line 9 of file Markham.as.
Referenced by GoldGainScale(), and Markham().
m_oreScale
float Modifiers::Markham::m_oreScale private
Definition at line 8 of file Markham.as.
Referenced by Markham(), and OreGainScale().
m_power
vec2 Modifiers::Markham::m_power private
Definition at line 6 of file Markham.as.
Referenced by DamagePower(), and Markham().
m_skillMul
float Modifiers::Markham::m_skillMul private
Definition at line 10 of file Markham.as.
Referenced by Markham(), and SkillTimeMul().
m_stats
vec2 Modifiers::Markham::m_stats private
Definition at line 5 of file Markham.as.
Referenced by Markham(), and StatsAdd().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Modifiers/Markham.as