HoHDocs: Modifiers::TriggerEffect Class Reference
Modifiers::TriggerEffect Class Reference
Private Member Functions
TriggerEffect (UnitPtr unit, SValue &params)
void Initialize (SyncVerb verb, uint id, uint modId) override
void NetTrigger (PlayerBase@ player, UnitPtr target)
void Trigger (PlayerBase@ player, UnitPtr target)
bool HasTriggerEffects () override
void TriggerEffects (PlayerBase@ player, Actor@ enemy, EffectTrigger trigger) override
Private Attributes
bool m_enabled
float m_chance
array< IEffect@> m_effects
bool m_targetSelf
string m_fx
string m_selfFx
EffectTrigger m_trigger
uint m_timeout
uint64 m_timeoutLastFired
SyncVerb m_verb
uint m_verbId
uint m_modId
Detailed Description
Definition at line 3 of file TriggerEffect.as.
Constructor & Destructor Documentation
TriggerEffect()
Modifiers::TriggerEffect::TriggerEffect (UnitPtr unit, SValue & params) inline private
Definition at line 19 of file TriggerEffect.as.
References LoadEffects(), m_chance, m_effects, m_enabled, m_fx, m_selfFx, m_targetSelf, m_timeout, m_trigger, Modifiers::ParseEffectTrigger(), and unit.
         {
             m_chance = GetParamFloat(unit, params, "chance", false, 10);
             @m_effects = LoadEffects(unit, params);
             m_targetSelf = GetParamBool(unit, params, "target-self", false, false);
             m_trigger = ParseEffectTrigger(GetParamString(unit, params, "trigger", false));
             m_fx = GetParamString(unit, params, "fx", false);
             m_selfFx = GetParamString(unit, params, "self-fx", false);
             m_timeout = GetParamInt(unit, params, "timeout", false);
             m_enabled = true;
         }
Member Function Documentation
HasTriggerEffects()
bool Modifiers::TriggerEffect::HasTriggerEffects () inline override private
Definition at line 97 of file TriggerEffect.as.
 { return true; }
Initialize()
void Modifiers::TriggerEffect::Initialize (SyncVerb verb, uint id, uint modId) inline override private
Definition at line 31 of file TriggerEffect.as.
References id, m_modId, m_verb, m_verbId, and None.
         {
             m_verb = verb;
             m_verbId = id;
             m_modId = modId;
             if (m_verb == SyncVerb::None)
             {
                 PrintError("Trigger effect modifier unsyncable: No netsync verb set!");
                 DumpStack();
             }
         }
NetTrigger()
void Modifiers::TriggerEffect::NetTrigger (PlayerBase@ player, UnitPtr target) inline private
Definition at line 44 of file TriggerEffect.as.
References ApplyEffects(), PlayerBase::m_dirAngle, m_effects, m_fx, m_selfFx, PlayEffect(), and xy().
Referenced by PlayerHandler::ModifierTriggerEffect().
         {
             if (!target.IsValid())
                 return;
             if (player is null)
                 return;
             vec2 targetPos = xy(target.GetPosition());
             vec2 dir = (target != player.m_unit) ? normalize(xy(target.GetPosition() - player.m_unit.GetPosition())) : vec2(cos(player.m_dirAngle), sin(player.m_dirAngle));
             ApplyEffects(m_effects, player, target, targetPos, dir, 1.0, true);
             if (m_selfFx != "")
             {
                 dictionary ePs = { { 'angle', atan(dir.y, dir.x) } };
                 PlayEffect(m_selfFx, xy(player.m_unit.GetPosition()), ePs);
             }
             if (m_fx != "")
             {
                 dictionary ePs = { { 'angle', atan(dir.y, dir.x) } };
                 PlayEffect(m_fx, targetPos, ePs);
             }
         }
Trigger()
void Modifiers::TriggerEffect::Trigger (PlayerBase@ player, UnitPtr target) inline private
Definition at line 69 of file TriggerEffect.as.
References ApplyEffects(), PlayerBase::m_dirAngle, m_effects, m_enabled, m_fx, m_modId, m_selfFx, m_verb, m_verbId, None, PlayEffect(), and xy().
Referenced by TriggerEffects().
         {
             if (!m_enabled)
                 return;
             if (!target.IsValid())
                 return;
             vec2 targetPos = xy(target.GetPosition());
             vec2 dir = (target != player.m_unit) ? normalize(xy(target.GetPosition() - player.m_unit.GetPosition())) : vec2(cos(player.m_dirAngle), sin(player.m_dirAngle));
             if (m_verb != Modifiers::SyncVerb::None && !target.IsDestroyed())
                 (Network::Message("ModifierTriggerEffect") << int(m_verb) << m_verbId << m_modId << target).SendToAll();
             ApplyEffects(m_effects, player, target, targetPos, dir, 1.0, false);
             if (m_selfFx != "")
             {
                 dictionary ePs = { { 'angle', atan(dir.y, dir.x) } };
                 PlayEffect(m_selfFx, xy(player.m_unit.GetPosition()), ePs);
             }
             if (m_fx != "")
             {
                 dictionary ePs = { { 'angle', atan(dir.y, dir.x) } };
                 PlayEffect(m_fx, targetPos, ePs);
             }
         }
TriggerEffects()
void Modifiers::TriggerEffect::TriggerEffects (PlayerBase@ player, Actor@ enemy, EffectTrigger trigger) inline override private
Definition at line 98 of file TriggerEffect.as.
References g_gameMode, Actor::IsTargetable(), m_chance, AGameMode::m_gameTime, m_targetSelf, m_timeout, m_timeoutLastFired, m_trigger, Actor::m_unit, and Trigger().
Referenced by Modifiers::CriticalHitTrigger::Crit(), and Skills::Juggernaut::OnCollide().
         {
             if (m_trigger != trigger)
                 return;
             if (randf() > m_chance)
                 return;
             if (m_timeout > 0)
             {
                 uint64 tmNow = g_gameMode.m_gameTime;
                 if (m_timeoutLastFired > 0 && (m_timeoutLastFired + m_timeout) > tmNow)
                     return;
                 m_timeoutLastFired = tmNow;
             }
             UnitPtr target;
             if (m_targetSelf)
                 target = player.m_unit;
             else if (enemy !is null)
             {
                 target = enemy.m_unit;
                 if (!enemy.IsTargetable())
                     return;
             }
             Trigger(player, target);
         }
Member Data Documentation
m_chance
float Modifiers::TriggerEffect::m_chance private
Definition at line 6 of file TriggerEffect.as.
Referenced by Modifiers::CriticalHitTrigger::CriticalHitTrigger(), TriggerEffect(), and TriggerEffects().
m_effects
array<IEffect@> Modifiers::TriggerEffect::m_effects private
Definition at line 7 of file TriggerEffect.as.
Referenced by NetTrigger(), Trigger(), and TriggerEffect().
m_enabled
bool Modifiers::TriggerEffect::m_enabled private
Definition at line 5 of file TriggerEffect.as.
Referenced by Trigger(), and TriggerEffect().
m_fx
string Modifiers::TriggerEffect::m_fx private
Definition at line 9 of file TriggerEffect.as.
Referenced by NetTrigger(), Trigger(), and TriggerEffect().
m_modId
uint Modifiers::TriggerEffect::m_modId private
Definition at line 17 of file TriggerEffect.as.
Referenced by Initialize(), and Trigger().
m_selfFx
string Modifiers::TriggerEffect::m_selfFx private
Definition at line 10 of file TriggerEffect.as.
Referenced by NetTrigger(), Trigger(), and TriggerEffect().
m_targetSelf
bool Modifiers::TriggerEffect::m_targetSelf private
Definition at line 8 of file TriggerEffect.as.
Referenced by TriggerEffect(), and TriggerEffects().
m_timeout
uint Modifiers::TriggerEffect::m_timeout private
Definition at line 12 of file TriggerEffect.as.
Referenced by TriggerEffect(), and TriggerEffects().
m_timeoutLastFired
uint64 Modifiers::TriggerEffect::m_timeoutLastFired private
Definition at line 13 of file TriggerEffect.as.
Referenced by TriggerEffects().
m_trigger
EffectTrigger Modifiers::TriggerEffect::m_trigger private
Definition at line 11 of file TriggerEffect.as.
Referenced by Modifiers::CriticalHitTrigger::CriticalHitTrigger(), TriggerEffect(), and TriggerEffects().
m_verb
SyncVerb Modifiers::TriggerEffect::m_verb private
Definition at line 15 of file TriggerEffect.as.
Referenced by Initialize(), and Trigger().
m_verbId
uint Modifiers::TriggerEffect::m_verbId private
Definition at line 16 of file TriggerEffect.as.
Referenced by Initialize(), and Trigger().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Modifiers/TriggerEffect.as