HoHDocs: PlayerBase Class Reference
PlayerBase Class Reference
Private Member Functions
PlayerBase ()
PlayerBase (UnitPtr unit, SValue &params)
vec2 GetComboBars ()
void LoadStats (SValue@ charFile)
void AddItem (ActorItem@ item)
void AddDrink (TavernDrink@ drink)
void AttuneItem (ActorItem@ item)
void RefreshSkills ()
void RefreshModifiers ()
void RefreshModifiersBuffs ()
void LoadSkills (SValue@ charFile)
Skills::Skill LoadSkill (string path, int skillId)
int IconHeight () override
bool IsTargetable () override
vec4 GetOverlayColor ()
void SetAngle (float angle)
void Initialize (PlayerRecord@ record)
void Refresh ()
void SetColor (int c, array< vec4 > color)
void UpdateColors ()
void InitSkin ()
bool ApplyBuff (ActorBuff@ buff) override
bool HasBuff (uint buff) override
int SetUnitScene (AnimString@ anim, bool resetScene) override
void SetCharging (bool charging)
int RefreshScene ()
void SetBodyAnim (string scene, bool resetTime)
void Destroyed ()
float GetHealth () override
void OnDeath (DamageInfo di, vec2 dir)
SValue Save ()
void OnComboBegin ()
void OnComboEnd ()
void Update (int dt)
void UpdateFootsteps (int dt, bool dashing, bool force=false)
void NetHeal (int amt) override
Private Attributes
AnimString m_idleAnim
AnimString m_walkAnim
AnimString m_dashAnim
vec2 m_dashDir
int m_dashTime
UnitProducer m_body
UnitScene m_aimLaser
CustomUnitScene m_unitScene
UnitScene m_markerFx
GoreSpawner m_gore
SoundEvent m_hurtSound
SoundEvent m_deathSound
string m_bodySceneName
int m_bodySceneTimeOffset
PlayerRecord m_record
EffectParams m_effectParams
vec4 m_dmgColor
ActorFootsteps m_footsteps
ActorFootsteps m_footstepsDash
ActorBuffList m_buffs
bool m_playerBobbing
bool m_charging
bool m_comboActive
ActorBuffDef m_comboBuff
int m_comboTime
int m_comboCount
int m_comboEffectsTime
array< Skills::Skill@> m_skills
float m_dirAngle
Detailed Description
Definition at line 1 of file PlayerBase.as.
Constructor & Destructor Documentation
PlayerBase() [1/2]
PlayerBase::PlayerBase () inline private
Definition at line 43 of file PlayerBase.as.
 { super(UnitPtr()); }
PlayerBase() [2/2]
PlayerBase::PlayerBase (UnitPtr unit, SValue & params) inline private
Definition at line 44 of file PlayerBase.as.
References Fountain::GetEffect(), ActorBuffList::Initialize(), LoadActorBuff(), m_buffs, m_charging, m_comboBuff, m_dashAnim, m_deathSound, m_dmgColor, m_effectParams, m_footsteps, m_footstepsDash, m_hurtSound, m_idleAnim, m_markerFx, m_playerBobbing, Actor::m_unit, m_unitScene, m_walkAnim, Tweak::PlayerCameraHeight, Actor::SetTeam(), and unit.
     {
         SetTeam("player", false);
         super(unit);
         @m_idleAnim = AnimString(GetParamString(unit, params, "anim-idle"));
         @m_walkAnim = AnimString(GetParamString(unit, params, "anim-walk"));
         @m_dashAnim = AnimString(GetParamString(unit, params, "anim-dash"));
         @m_unitScene = CustomUnitScene();
         @m_hurtSound = Resources::GetSoundEvent("event:/player/hurt");
         @m_deathSound = Resources::GetSoundEvent("event:/player/death");
         @m_markerFx = Resources::GetEffect("actors/players/marker.effect");
         @m_effectParams = m_unit.CreateEffectParams();
         m_effectParams.Set("height", Tweak::PlayerCameraHeight);
         m_effectParams.Set("frenzy", 1.0f);
         m_dmgColor = vec4(0, 0, 0, 0);
 %if !GFX_VFX_LOW
         auto svFootsteps = GetParamDictionary(unit, params, "footsteps", false);
         if (svFootsteps !is null)
             @m_footsteps = ActorFootsteps(unit, svFootsteps);
 %endif
         auto svFootstepsDash = GetParamDictionary(unit, params, "footsteps-dash", false);
         if (svFootstepsDash !is null)
             @m_footstepsDash = ActorFootsteps(unit, svFootstepsDash);
         m_buffs.Initialize(this);
         m_playerBobbing = GetParamBool(unit, params, "bobbing", false, true);
         m_charging = false;
         @m_comboBuff = LoadActorBuff("players/buffs.sval:combo");
     }
Member Function Documentation
AddDrink()
void PlayerBase::AddDrink (TavernDrink@ drink) inline private
Definition at line 142 of file PlayerBase.as.
References Stats::Add(), TavernDrink::id, m_record, and RefreshModifiers().
     {
         m_record.tavernDrinks.insertLast(drink.id);
         RefreshModifiers();
         Stats::Add("drinks-consumed", 1, m_record);
     }
AddItem()
void PlayerBase::AddItem (ActorItem@ item) inline private
Definition at line 116 of file PlayerBase.as.
References Stats::Add(), OwnedItemSet::GetNumBonusesActive(), m_record, and RefreshModifiers().
Referenced by Player::AddItem(), and GiveItemImpl().
     {
         int numActiveBonusesBefore = 0;
         if (item.set !is null)
         {
             OwnedItemSet@ ownedItemSet = m_record.GetOwnedItemSet(item.set);
             if (ownedItemSet !is null)
                 numActiveBonusesBefore = ownedItemSet.GetNumBonusesActive();
         }
         m_record.items.insertLast(item.id);
         RefreshModifiers();
         if (item.set !is null)
         {
             OwnedItemSet@ ownedItemSet = m_record.GetOwnedItemSet(item.set);
             int numActiveBonusesAfter = ownedItemSet.GetNumBonusesActive();
             if (numActiveBonusesAfter > numActiveBonusesBefore && numActiveBonusesAfter == int(item.set.bonuses.length()))
             {
                 print("New completed set: \"" + Resources::GetString(item.set.name) + "\"");
                 Stats::Add("sets-completed", 1, m_record);
             }
         }
     }
ApplyBuff()
bool PlayerBase::ApplyBuff (ActorBuff@ buff) inline override private
Definition at line 320 of file PlayerBase.as.
References ActorBuffList::Add(), buff, Actor::IsHusk(), m_buffs, m_record, Actor::m_unit, and modifiers.
Referenced by Modifiers::Buff::Update(), and Update().
     {
         if (m_unit.IsDestroyed())
             return false;
         if (IsHusk() && !buff.m_husk)
             return false;
         auto modifiers = m_record.GetModifiers();
         if ((buff.m_def.m_tags & modifiers.ImmuneBuffs(this)) != 0)
             return false;
         if (buff.m_def.m_debuff)
         {
             buff.m_duration = int(buff.m_duration * (buff.m_def.m_debuff ? modifiers.DebuffScale(this) : modifiers.BuffScale(this)));
             if (buff.m_duration <= 0)
                 return false;
         }
         m_buffs.Add(buff);
         return true;
     }
AttuneItem()
void PlayerBase::AttuneItem (ActorItem@ item) inline private
Definition at line 150 of file PlayerBase.as.
References Stats::Add(), m_record, and RefreshModifiers().
Referenced by Player::AttuneItem().
     {
         m_record.itemForgeAttuned.insertLast(item.idHash);
         RefreshModifiers();
         Stats::Add("items-attuned", 1, m_record);
     }
Destroyed()
void PlayerBase::Destroyed () inline private
Definition at line 423 of file PlayerBase.as.
References ActorBuffList::Clear(), m_buffs, m_record, m_skills, and Skills::OnDestroy().
     {
         for (uint i = 0; i < m_skills.length(); i++)
             m_skills[i].OnDestroy();
         m_buffs.Clear();
         @m_record.actor = null;
     }
GetComboBars()
vec2 PlayerBase::GetComboBars () inline private
Definition at line 86 of file PlayerBase.as.
References m_comboCount, m_comboTime, and m_record.
Referenced by PlayerHusk::KilledActor(), Player::KilledActor(), and Update().
     {
         auto props = ivec3(10, 1000, 2000) + m_record.GetModifiers().ComboProps(this);
         float amnt = m_comboCount / float(props.x);
         if (amnt >= 1.0f)
             return vec2(amnt, m_comboTime / float(props.z));
         return vec2(amnt, m_comboTime / float(props.y));
     }
GetHealth()
float PlayerBase::GetHealth () inline override private
Definition at line 432 of file PlayerBase.as.
References m_record.
     {
         return m_record.hp;
     }
GetOverlayColor()
vec4 PlayerBase::GetOverlayColor () inline private
Definition at line 248 of file PlayerBase.as.
References m_dmgColor.
     {
         return m_dmgColor;
     }
HasBuff()
bool PlayerBase::HasBuff (uint buff) inline override private
Definition at line 344 of file PlayerBase.as.
References buff, ActorBuffList::m_buffs, and m_buffs.
     {
         for (uint i = 0; i < m_buffs.m_buffs.length(); i++)
         {
             auto b = m_buffs.m_buffs[i];
             if (b.m_def.m_pathHash == buff)
                 return true;
         }
         return false;
     }
IconHeight()
int PlayerBase::IconHeight () inline override private
Definition at line 245 of file PlayerBase.as.
 { return -24; }
Initialize()
void PlayerBase::Initialize (PlayerRecord@ record) inline private
Definition at line 266 of file PlayerBase.as.
References GetPlayerColor(), InitSkin(), LoadSkills(), LoadStats(), m_effectParams, m_record, and RefreshModifiers().
Referenced by PlayerHusk::Initialize(), Player::Initialize(), and Refresh().
     {
         @m_record = record;
         auto charData = Resources::GetSValue("players/" + m_record.charClass + "/char.sval");
         LoadSkills(charData);
         LoadStats(charData);
         auto color = ParseColorRGBA("#" + GetPlayerColor(m_record.peer) + "ff");
         m_effectParams.Set("color_r", color.r);
         m_effectParams.Set("color_g", color.g);
         m_effectParams.Set("color_b", color.b);
         InitSkin();
         RefreshModifiers();
     }
InitSkin()
void PlayerBase::InitSkin () inline private
Definition at line 312 of file PlayerBase.as.
References Fountain::GetEffect(), m_aimLaser, m_body, m_record, and UpdateColors().
Referenced by Initialize().
     {
         @m_body = Resources::GetUnitProducer("players/" + m_record.charClass + ".unit");
         @m_aimLaser = Resources::GetEffect("actors/players/aim_laser.effect");
         UpdateColors();
     }
IsTargetable()
bool PlayerBase::IsTargetable () inline override private
Definition at line 246 of file PlayerBase.as.
 { return true; }
LoadSkill()
Skills::Skill PlayerBase::LoadSkill (string path, int skillId) inline private
Definition at line 218 of file PlayerBase.as.
References m_record, Actor::m_unit, min, ScriptSprite(), and Skills::Skill().
Referenced by LoadSkills().
     {
         auto skillData = Resources::GetSValue(path);
         auto iconArray = GetParamArray(m_unit, skillData, "icon", false);
         string skillName = GetParamString(m_unit, skillData, "name", false);
         Skills::Skill@ skill;
         int skillLevel = m_record.levelSkills[skillId];
         auto skillsArr = GetParamArray(m_unit, skillData, "skills", true);
         @skillData = skillsArr[min(skillsArr.length() - 1, skillLevel)];
         if (skillData is null || skillData.GetType() == SValueType::Null || skillData.GetType() == SValueType::Integer)
             @skill = Skills::NullSkill(m_unit);
         else
         {
             string c = GetParamString(m_unit, skillData, "class");
             @skill = cast<Skills::Skill>(InstantiateClass(c, m_unit, skillData));
         }
         skill.Initialize(this, ScriptSprite(iconArray), skillId);
         skill.m_name = skillName;
         return skill;
     }
LoadSkills()
void PlayerBase::LoadSkills (SValue@ charFile) inline private
Definition at line 207 of file PlayerBase.as.
References LoadSkill(), m_skills, Actor::m_unit, and Skills::OnDestroy().
Referenced by Initialize(), and RefreshSkills().
     {
         for (uint i = 0; i < m_skills.length(); i++)
             m_skills[i].OnDestroy();
         m_skills.removeRange(0, m_skills.length());
         array<SValue@>@ skillsArr = GetParamArray(m_unit, charFile, "skills", true);
         for (uint i = 0; i < skillsArr.length(); i++)
             m_skills.insertLast(LoadSkill(skillsArr[i].GetString(), i));
     }
LoadStats()
void PlayerBase::LoadStats (SValue@ charFile) inline private
Definition at line 97 of file PlayerBase.as.
References m_record, and Actor::m_unit.
Referenced by Initialize().
     {
         auto statsData = charFile;
         m_record.classStats.base_health = GetParamFloat(m_unit, statsData, "base-health", false, 100);
         m_record.classStats.level_health = GetParamFloat(m_unit, statsData, "level-health", false, 0);
         m_record.classStats.base_health_regen = GetParamFloat(m_unit, statsData, "base-health-regen", false, 0);
         m_record.classStats.level_health_regen = GetParamFloat(m_unit, statsData, "level-health-regen", false, 0.05);
         m_record.classStats.base_mana = GetParamFloat(m_unit, statsData, "base-mana", false, 100);
         m_record.classStats.level_mana = GetParamFloat(m_unit, statsData, "level-mana", false, 0);
         m_record.classStats.base_mana_regen = GetParamFloat(m_unit, statsData, "base-mana-regen", false, 0.3);
         m_record.classStats.level_mana_regen = GetParamFloat(m_unit, statsData, "level-mana-regen", false, 0.15);
         m_record.classStats.base_armor = GetParamFloat(m_unit, statsData, "base-armor", false, 0);
         m_record.classStats.level_armor = GetParamFloat(m_unit, statsData, "level-armor", false, 0);
         m_record.classStats.base_resistance = GetParamFloat(m_unit, statsData, "base-resistance", false, 0);
         m_record.classStats.level_resistance = GetParamFloat(m_unit, statsData, "level-resistance", false, 0);
     }
NetHeal()
void PlayerBase::NetHeal (int amt) inline override private
Definition at line 593 of file PlayerBase.as.
References AddFloatingText(), m_dmgColor, m_record, Actor::m_unit, min, and PlayerHealed.
Referenced by PlayerHusk::Heal(), and Player::Update().
     {
         AddFloatingText(FloatingTextType::PlayerHealed, "" + amt, m_unit.GetPosition());
         m_dmgColor = vec4(0, 1, 0, 1);
         m_record.hp = min(1.0f, m_record.hp + (float(amt) / float(m_record.MaxHealth() + m_record.GetModifiers().StatsAdd(this).x)));
     }
OnComboBegin()
void PlayerBase::OnComboBegin () inline private
Definition at line 502 of file PlayerBase.as.
References m_comboEffectsTime.
Referenced by Update().
     {
         m_comboEffectsTime = 0;
     }
OnComboEnd()
void PlayerBase::OnComboEnd () inline private
Definition at line 507 of file PlayerBase.as.
Referenced by Update().
     {
     }
OnDeath()
void PlayerBase::OnDeath (DamageInfo di, vec2 dir) inline private
Definition at line 437 of file PlayerBase.as.
References DamageInfo::Attacker, ActorBuffList::Clear(), g_gameMode, g_scene, GetPlayerColor(), m_buffs, m_deathSound, m_gore, m_record, Actor::m_unit, PlaySound3D(), SendSystemMessage(), unit, xy(), and xyz().
Referenced by PlayerHusk::OnDeath(), and Player::OnDeath().
     {
         if (m_record.IsDead())
             return;
         auto gm = cast<BaseGameMode>(g_gameMode);
         auto otherPlayer = cast<PlayerHusk>(di.Attacker);
         if (otherPlayer !is null)
         {
             // If soul link kill
             SValueBuilder builder;
             builder.PushString(Resources::GetString(".menu.lobby.chat.soullinkdeath", {
                 { "name", "\\c" + GetPlayerColor(m_record.peer) + gm.GetPlayerDisplayName(m_record) + "\\d" },
                 { "killer", "\\c" + GetPlayerColor(otherPlayer.m_record.peer) + gm.GetPlayerDisplayName(otherPlayer.m_record) + "\\d" }
             }));
             SendSystemMessage("AddChat", builder.Build());
         }
         else if (di.Attacker !is null)
         {
             // If monster kill
             auto unit = di.Attacker.m_unit;
             auto@ unitProd = unit.GetUnitProducer();
             auto params = unitProd.GetBehaviorParams();
             string unitName = GetParamString(unit, params, "beastiary-name", false);
             SValueBuilder builder;
             builder.PushString(Resources::GetString(".menu.lobby.chat.death", {
                 { "name", "\\c" + GetPlayerColor(m_record.peer) + gm.GetPlayerDisplayName(m_record) + "\\d" },
                 { "killer", Resources::GetString(unitName) }
             }));
             SendSystemMessage("AddChat", builder.Build());
         }
         else
         {
             // If suicide
             SValueBuilder builder;
             builder.PushString(Resources::GetString(".menu.lobby.chat.suicide", {
                 { "name", "\\c" + GetPlayerColor(m_record.peer) + gm.GetPlayerDisplayName(m_record) + "\\d" }
             }));
             SendSystemMessage("AddChat", builder.Build());
         }
         m_buffs.Clear();
         m_record.deadTime = g_scene.GetTime();
         PlaySound3D(m_deathSound, m_unit.GetPosition());
         if (m_gore !is null)
             m_gore.OnDeath(1.0f, xy(m_unit.GetPosition()), atan(dir.y, dir.x));
         auto corpse = Resources::GetUnitProducer("players/player_corpse.unit").Produce(g_scene, xyz(xy(m_unit.GetPosition()), 0));
         @m_record.corpse = cast<PlayerCorpse>(corpse.GetScriptBehavior());
         m_record.corpse.Initialize(m_record);
         m_unit.Destroy();
         m_unit = UnitPtr();
     }
Refresh()
void PlayerBase::Refresh () inline private
Definition at line 285 of file PlayerBase.as.
References Initialize(), and m_record.
     {
         Initialize(m_record);
     }
RefreshModifiers()
void PlayerBase::RefreshModifiers () inline private
Definition at line 166 of file PlayerBase.as.
References ActorBuffList::Add(), buff, GetTavernDrink(), Actor::IsHusk(), LoadActorBuff(), m_buffs, and m_record.
Referenced by AddDrink(), AddItem(), AttuneItem(), Initialize(), Player::RefreshModifiers(), and RefreshSkills().
     {
         m_record.RefreshModifiers();
         for (uint j = 0; j < m_record.tavernDrinks.length(); j++)
         {
             auto drink = GetTavernDrink(HashString(m_record.tavernDrinks[j]));
             if (drink.buff is null)
                 continue;
             auto buff = ActorBuff(this, drink.buff, 1.0f, IsHusk());
             buff.m_duration = 1000000000;
             m_buffs.Add(buff);
         }
         for (uint j = 0; j < m_record.temporaryBuffs.length(); j += 2)
         {
             auto buffDef = LoadActorBuff(m_record.temporaryBuffs[j]);
             if (buffDef is null)
                 continue;
             auto buff = ActorBuff(this, buffDef, 1.0f, IsHusk());
             buff.m_duration = m_record.temporaryBuffs[j + 1];
             m_buffs.Add(buff);
         }
     }
RefreshModifiersBuffs()
void PlayerBase::RefreshModifiersBuffs () inline private
Definition at line 193 of file PlayerBase.as.
References buff, ActorBuffList::m_buffs, m_buffs, and m_record.
     {
         m_record.RefreshModifiersBuffs();
         for (uint i = 0; i < m_buffs.m_buffs.length(); i++)
         {
             auto buff = m_buffs.m_buffs[i];
             auto buffDef = buff.m_def;
             for (uint j = 0; j < buffDef.m_modifiers.length(); j++)
                 m_record.modifiersBuffs.Add(buffDef.m_modifiers[j]);
         }
     }
RefreshScene()
int PlayerBase::RefreshScene () inline private
Definition at line 374 of file PlayerBase.as.
References g_gameMode, GetInput(), Actor::IsDead(), m_aimLaser, m_body, m_bodySceneName, m_bodySceneTimeOffset, m_charging, m_markerFx, m_record, m_skills, Actor::m_unit, m_unitScene, BaseGameMode::RefreshPlayerScene(), and UsingGamepad.
Referenced by SetBodyAnim(), and SetCharging().
     {
         if (IsDead())
             return 0; //TODO: Corpse scene?
         int time = 0;
         m_unitScene.Clear();
         m_unitScene.AddScene(m_unit.GetUnitScene((m_charging ? "shared-charge" : "shared")), m_bodySceneTimeOffset, vec2(), 0, 0);
         m_unitScene.AddScene(m_body.GetUnitScene(m_bodySceneName), m_bodySceneTimeOffset, vec2(), 0, 0);
         for (uint i = 0; i < m_skills.length(); i++)
             m_skills[i].RefreshScene(m_unitScene);
         if (m_record.local)
         {
             if (GetVarBool("g_local_player_marker"))
                 m_unitScene.AddScene(m_markerFx, 0, vec2(), 0, 0);
             int laserSight = GetVarInt("g_laser_sight");
             if ((laserSight == -1 && GetInput().UsingGamepad) || laserSight == 1)
                 m_unitScene.AddScene(m_aimLaser, 0, vec2(), 0, 0);
         }
         else
         {
             if (GetVarBool("g_player_markers"))
                 m_unitScene.AddScene(m_markerFx, 0, vec2(), 0, 0);
         }
         BaseGameMode@ gm = cast<BaseGameMode>(g_gameMode);
         if (gm !is null)
             gm.RefreshPlayerScene(this, m_unitScene);
         Hooks::Call("PlayerRefreshScene", @this);
         m_unit.SetUnitScene(m_unitScene, false);
         return time;
     }
RefreshSkills()
void PlayerBase::RefreshSkills () inline private
Definition at line 158 of file PlayerBase.as.
References LoadSkills(), m_record, and RefreshModifiers().
     {
         auto charData = Resources::GetSValue("players/" + m_record.charClass + "/char.sval");
         LoadSkills(charData);
         RefreshModifiers();
     }
Save()
SValue PlayerBase::Save () inline private
Definition at line 497 of file PlayerBase.as.
     {
         return null;
     }
SetAngle()
void PlayerBase::SetAngle (float angle) inline private
Definition at line 255 of file PlayerBase.as.
References m_dirAngle, m_effectParams, ActorFootsteps::m_facingDirection, m_footsteps, and m_footstepsDash.
Referenced by PlayerHusk::Update(), and Player::Update().
     {
         m_effectParams.Set("angle", angle);
         m_dirAngle = angle;
         if (m_footsteps !is null)
             m_footsteps.m_facingDirection = angle;
         if (m_footstepsDash !is null)
             m_footstepsDash.m_facingDirection = angle;
     }
SetBodyAnim()
void PlayerBase::SetBodyAnim (string scene, bool resetTime) inline private
Definition at line 413 of file PlayerBase.as.
References m_bodySceneName, m_bodySceneTimeOffset, Actor::m_unit, and RefreshScene().
Referenced by SetUnitScene(), PlayerHusk::Update(), and Player::Update().
     {
         m_bodySceneName = scene;
         if (resetTime)
             m_bodySceneTimeOffset = -m_unit.GetUnitSceneTime();
         RefreshScene();
     }
SetCharging()
void PlayerBase::SetCharging (bool charging) inline private
Definition at line 368 of file PlayerBase.as.
References m_charging, and RefreshScene().
     {
         m_charging = charging;
         RefreshScene();
     }
SetColor()
void PlayerBase::SetColor (int c, array< vec4 > color) inline private
Definition at line 290 of file PlayerBase.as.
References Actor::m_unit.
Referenced by UpdateColors().
     {
         m_unit.SetMultiColor(c, color[0], color[1], color[2]);
     }
SetUnitScene()
int PlayerBase::SetUnitScene (AnimString@ anim, bool resetScene) inline override private
Definition at line 355 of file PlayerBase.as.
References anim, AnimString::GetSceneName(), m_body, m_dirAngle, and SetBodyAnim().
     {
         auto sceneName = anim.GetSceneName(m_dirAngle);
         SetBodyAnim(sceneName, resetScene);
         auto scene = m_body.GetUnitScene(sceneName);
         if (scene is null)
         {
             PrintError("Couldn't find scene '" + sceneName + "'");
             return 0;
         }
         return scene.Length();
     }
Update()
void PlayerBase::Update (int dt) inline private
Definition at line 511 of file PlayerBase.as.
References ApplyBuff(), ApplyEffects(), g_scene, GetComboBars(), ActorColor::m_bright, m_buffs, ActorBuffList::m_color, m_comboActive, m_comboBuff, m_comboCount, m_comboEffectsTime, m_comboTime, ActorColor::m_dark, m_dirAngle, m_dmgColor, ActorColor::m_mid, m_record, Actor::m_unit, OnComboBegin(), OnComboEnd(), PlaySound3D(), ActorBuffList::Update(), and xy().
Referenced by PlayerHusk::Update(), and Player::Update().
     {
         m_buffs.Update(dt);
         if (m_dmgColor.a > 0)
             m_dmgColor.a -= dt / 100.0;
         for (uint j = 0; j < m_record.temporaryBuffs.length(); j += 2)
         {
             if (m_record.temporaryBuffs[j + 1] > uint(dt))
                 m_record.temporaryBuffs[j + 1] -= uint(dt);
             else
                 m_record.temporaryBuffs[j + 1] = 0;
         }
         if (m_comboTime > 0)
         {
             m_comboTime -= dt;
             if (m_comboTime <= 0)
             {
                 m_comboCount = 0;
                 if (m_comboActive)
                     PlaySound3D(Resources::GetSoundEvent("event:/player/combo/deactivate"), m_unit.GetPosition());
                 else
                     PlaySound3D(Resources::GetSoundEvent("event:/player/combo/failed"), m_unit.GetPosition());
             }
         }
         else
             m_comboCount = 0;
         bool comboPrev = m_comboActive;
         m_comboActive = false;
         if (GetComboBars().x >= 1.0f)
         {
             this.ApplyBuff(ActorBuff(this, m_comboBuff, 1.0f, false, 0));
             float t = g_scene.GetTime() / 250.0;
             float st = 0.25;
             m_unit.Colorize(vec4(0.5,0,0.5, st), vec4(1,0,1, st), vec4(1,0.75,1,1));
             m_comboEffectsTime -= dt;
             if (m_comboEffectsTime <= 0)
             {
                 m_comboEffectsTime += 1000;
                 vec2 aimDir = vec2(cos(m_dirAngle), sin(m_dirAngle));
                 auto effects = m_record.GetModifiers().ComboEffects(this);
                 if (effects.length() > 0)
                     ApplyEffects(effects, this, UnitPtr(), xy(m_unit.GetPosition()), aimDir, 1.0, false);
             }
             m_comboActive = true;
         }
         else
             m_unit.Colorize(m_buffs.m_color.m_dark, m_buffs.m_color.m_mid, m_buffs.m_color.m_bright);
         if (comboPrev != m_comboActive)
         {
             if (m_comboActive)
                 OnComboBegin();
             else
                 OnComboEnd();
         }
     }
UpdateColors()
void PlayerBase::UpdateColors () inline private
Definition at line 295 of file PlayerBase.as.
References g_gameMode, m_record, and SetColor().
Referenced by InitSkin(), and PlayerHusk::UpdateColors().
     {
         for (uint i = 0; i < m_record.colors.length(); i++)
         {
             auto dye = m_record.colors[i];
             SetColor(i, dye.m_shades);
         }
         auto gm = cast<Campaign>(g_gameMode);
         if (gm !is null)
         {
             auto wPlayer = gm.m_hudCoop.GetPlayer(m_record.peer);
             if (wPlayer !is null)
                 wPlayer.UpdatePortrait();
         }
     }
UpdateFootsteps()
void PlayerBase::UpdateFootsteps (int dt, bool dashing, bool force = false) inline private
Definition at line 579 of file PlayerBase.as.
References force, m_footsteps, m_footstepsDash, and ActorFootsteps::Update().
Referenced by PlayerHusk::Update(), and Player::Update().
     {
         if (!dashing)
         {
             if (m_footsteps !is null)
                 m_footsteps.Update(dt, force);
         }
         else
         {
             if (m_footstepsDash !is null)
                 m_footstepsDash.Update(dt, force);
         }
     }
Member Data Documentation
m_aimLaser
UnitScene PlayerBase::m_aimLaser private
Definition at line 11 of file PlayerBase.as.
Referenced by InitSkin(), and RefreshScene().
m_body
UnitProducer PlayerBase::m_body private
Definition at line 10 of file PlayerBase.as.
Referenced by InitSkin(), RefreshScene(), and SetUnitScene().
m_bodySceneName
string PlayerBase::m_bodySceneName private
Definition at line 19 of file PlayerBase.as.
Referenced by RefreshScene(), and SetBodyAnim().
m_bodySceneTimeOffset
int PlayerBase::m_bodySceneTimeOffset private
Definition at line 20 of file PlayerBase.as.
Referenced by RefreshScene(), and SetBodyAnim().
m_buffs
ActorBuffList PlayerBase::m_buffs private
Definition at line 30 of file PlayerBase.as.
Referenced by ApplyBuff(), Player::Damage(), Player::DamageActor(), Destroyed(), Player::GetWindScale(), HasBuff(), Player::KilledActor(), Player::NetShareExperience(), OnDeath(), PlayerBase(), RefreshModifiers(), RefreshModifiersBuffs(), Player::SpendCost(), Update(), Player::Update(), and PlayerMenuCharacterTab::UpdateFromRecord().
m_charging
bool PlayerBase::m_charging private
Definition at line 33 of file PlayerBase.as.
Referenced by PlayerBase(), RefreshScene(), and SetCharging().
m_comboActive
bool PlayerBase::m_comboActive private
Definition at line 35 of file PlayerBase.as.
Referenced by Modifiers::Combo::Filter(), PlayerHusk::KilledActor(), Update(), and Player::Update().
m_comboBuff
ActorBuffDef PlayerBase::m_comboBuff private
Definition at line 36 of file PlayerBase.as.
Referenced by PlayerBase(), and Update().
m_comboCount
int PlayerBase::m_comboCount private
Definition at line 38 of file PlayerBase.as.
Referenced by GetComboBars(), PlayerHusk::KilledActor(), Player::KilledActor(), Player::OnComboBegin(), and Update().
m_comboEffectsTime
int PlayerBase::m_comboEffectsTime private
Definition at line 39 of file PlayerBase.as.
Referenced by OnComboBegin(), and Update().
m_comboTime
int PlayerBase::m_comboTime private
Definition at line 37 of file PlayerBase.as.
Referenced by GetComboBars(), PlayerHusk::KilledActor(), Player::KilledActor(), Player::OnComboBegin(), and Update().
m_dashAnim
AnimString PlayerBase::m_dashAnim private
Definition at line 5 of file PlayerBase.as.
Referenced by PlayerBase(), and PlayerHusk::Update().
m_dashDir
vec2 PlayerBase::m_dashDir private
Definition at line 7 of file PlayerBase.as.
Referenced by PlayerHusk::Dash(), and PlayerHusk::Update().
m_dashTime
int PlayerBase::m_dashTime private
Definition at line 8 of file PlayerBase.as.
Referenced by PlayerHusk::Dash(), and PlayerHusk::Update().
m_deathSound
SoundEvent PlayerBase::m_deathSound private
Definition at line 17 of file PlayerBase.as.
Referenced by OnDeath(), and PlayerBase().
m_dirAngle
float PlayerBase::m_dirAngle private
Definition at line 254 of file PlayerBase.as.
Referenced by Modifiers::TriggerEffect::NetTrigger(), Modifiers::BlockProjectile::ProjectileBlock(), SetAngle(), SetUnitScene(), Modifiers::TriggerEffect::Trigger(), Modifiers::AuraCone::Update(), Update(), and Player::Update().
m_dmgColor
vec4 PlayerBase::m_dmgColor private
Definition at line 25 of file PlayerBase.as.
Referenced by Player::Damage(), GetOverlayColor(), NetHeal(), PlayerBase(), and Update().
m_effectParams
EffectParams PlayerBase::m_effectParams private
Definition at line 24 of file PlayerBase.as.
Referenced by Initialize(), PlayerBase(), SetAngle(), and Player::Update().
m_footsteps
ActorFootsteps PlayerBase::m_footsteps private
Definition at line 27 of file PlayerBase.as.
Referenced by PlayerBase(), SetAngle(), and UpdateFootsteps().
m_footstepsDash
ActorFootsteps PlayerBase::m_footstepsDash private
Definition at line 28 of file PlayerBase.as.
Referenced by PlayerBase(), SetAngle(), and UpdateFootsteps().
m_gore
GoreSpawner PlayerBase::m_gore private
Definition at line 14 of file PlayerBase.as.
Referenced by Player::Damage(), PlayerHusk::NetDamage(), and OnDeath().
m_hurtSound
SoundEvent PlayerBase::m_hurtSound private
Definition at line 16 of file PlayerBase.as.
Referenced by Player::Damage(), and PlayerBase().
m_idleAnim
AnimString PlayerBase::m_idleAnim private
Definition at line 3 of file PlayerBase.as.
Referenced by PlayerBase(), PlayerHusk::Update(), and Player::Update().
m_markerFx
UnitScene PlayerBase::m_markerFx private
Definition at line 13 of file PlayerBase.as.
Referenced by PlayerBase(), and RefreshScene().
m_playerBobbing
bool PlayerBase::m_playerBobbing private
Definition at line 32 of file PlayerBase.as.
Referenced by PlayerBase(), PlayerHusk::Update(), and Player::Update().
m_record
PlayerRecord PlayerBase::m_record private
Definition at line 22 of file PlayerBase.as.
Referenced by AddDrink(), AddItem(), Apply(), ApplyBuff(), Player::ApplyBuff(), AttuneItem(), Player::BroadcastNetDamage(), Chest::CanUse(), WorldScript::StoreOre::CanUse(), WorldScript::RandomBuff::CanUse(), WorldScript::UseTrigger::CanUse(), WorldScript::Well::CanUse(), Player::Damage(), Player::DamageActor(), Player::DamagedActor(), Modifiers::SealOfMartyr::DamageMul(), Modifiers::SealOfMana::DamageMul(), Skills::GoldFeverMod::DamageMul(), Skills::ManaShieldMod::DamageTakenMul(), Player::Decimate(), Destroyed(), Modifiers::HealthFilter::Filter(), GetComboBars(), GetHealth(), Modifiers::Markham::GetNumItems(), GiveForgeBlueprintImpl(), GiveItemImpl(), Player::GiveMana(), Player::Heal(), PlayerHusk::Initialize(), Initialize(), InitSkin(), PlayerHusk::IsDead(), Player::IsDead(), PlayerHusk::KilledActor(), Player::KilledActor(), LoadSkill(), LoadStats(), PlayerHusk::NetDamage(), Player::NetDecimate(), NetGiveGoldImpl(), NetGiveKeyImpl(), NetHeal(), Player::NetShareExperience(), PlayerHusk::OnDeath(), OnDeath(), Player::OnDeath(), WorldScript::AllPlayersAreaTrigger::OnEnter(), WorldScript::AllPlayersAreaTrigger::OnExit(), Player::OnLevelUp(), Player::OnNewTitle(), Refresh(), RefreshModifiers(), RefreshModifiersBuffs(), RefreshScene(), RefreshSkills(), HUD::ShowBuffIcon(), Player::SpendCost(), Modifiers::StatsBase::StatsAdd(), Modifiers::RandomBuff::StatsAdd(), Player::TakeMana(), Modifiers::WarlockCleaverModifier::TriggerEffects(), Skills::RiposteTrigger::TriggerEffects(), Update(), Player::Update(), UpdateColors(), PlayerMenuCharacterTab::UpdateFromRecord(), Door::Use(), Chest::Use(), WorldScript::Well::Use(), WorldScript::StoreOre::Use(), and WorldScript::RandomBuff::Use().
m_skills
array<Skills::Skill@> PlayerBase::m_skills private
Definition at line 41 of file PlayerBase.as.
Referenced by Player::CheckSkillBlocked(), Player::CheckUseSkill(), Player::Collide(), Skills::PlannedAttackModifier::Crit(), Destroyed(), LoadSkills(), RefreshScene(), Modifiers::WarlockCleaverModifier::TriggerEffects(), Skills::RiposteTrigger::TriggerEffects(), PlayerHusk::Update(), Player::Update(), and PlayerMenuCharacterTab::UpdateFromRecord().
m_unitScene
CustomUnitScene PlayerBase::m_unitScene private
Definition at line 12 of file PlayerBase.as.
Referenced by PlayerBase(), and RefreshScene().
m_walkAnim
AnimString PlayerBase::m_walkAnim private
Definition at line 4 of file PlayerBase.as.
Referenced by PlayerBase(), PlayerHusk::Update(), and Player::Update().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Player/PlayerBase.as