HoHDocs: Skills::CelestialOrb Class Reference
Skills::CelestialOrb Class Reference
Private Member Functions
CelestialOrb (int index, CelestialOrbs@ skill)
vec2 GetOwnerPosition ()
vec2 GetOrbPosition ()
vec2 GetTargetPosition ()
float GetOrbBeamDirection ()
float GetOrbBeamLength ()
void RefreshScene (CustomUnitScene@ scene)
void Update (int dt)
void BeamStart ()
void BeamStop ()
Private Attributes
int m_index
CelestialOrbs m_skill
int m_intervalC
vec2 m_offset
vec2 m_overrideTarget
bool m_overrideTargetSet
UnitPtr m_target
UnitPtr m_beam
SoundInstance m_sndI
Detailed Description
Definition at line 3 of file CelestialOrb.as.
Constructor & Destructor Documentation
CelestialOrb()
Skills::CelestialOrb::CelestialOrb (int index, CelestialOrbs@ skill) inline private
Definition at line 20 of file CelestialOrb.as.
References m_index, m_intervalC, and m_skill.
         {
             m_index = index;
             @m_skill = skill;
             m_intervalC = m_skill.m_effectInterval;
         }
Member Function Documentation
BeamStart()
void Skills::CelestialOrb::BeamStart () inline private
Definition at line 176 of file CelestialOrb.as.
References GetOrbBeamDirection(), GetOrbBeamLength(), GetOrbPosition(), m_beam, m_skill, m_sndI, PlayEffect(), and xyz().
Referenced by Update().
         {
             vec2 orbPos = GetOrbPosition();
             dictionary ePs = {
                 { 'angle', GetOrbBeamDirection() },
                 { 'length', GetOrbBeamLength() }
             };
             m_beam = PlayEffect(m_skill.m_orbBeamFx, orbPos, ePs);
             @m_sndI = m_skill.m_snd.PlayTracked(xyz(orbPos));
             auto behavior = cast<EffectBehavior>(m_beam.GetScriptBehavior());
             behavior.m_looping = true;
         }
BeamStop()
void Skills::CelestialOrb::BeamStop () inline private
Definition at line 192 of file CelestialOrb.as.
References m_beam, and m_sndI.
Referenced by Update().
         {
             if (m_beam.IsValid())
                 m_beam.Destroy();
             m_beam = UnitPtr();
             if (m_sndI !is null)
                 m_sndI.Stop();
             @m_sndI = null;
         }
GetOrbBeamDirection()
float Skills::CelestialOrb::GetOrbBeamDirection () inline private
Definition at line 45 of file CelestialOrb.as.
References GetOrbPosition(), and GetTargetPosition().
Referenced by BeamStart(), and Update().
         {
             vec2 orbPos = GetOrbPosition();
             vec2 actorPos = GetTargetPosition();
             vec2 dir = normalize(actorPos - orbPos);
             return atan(dir.y, dir.x);
         }
GetOrbBeamLength()
float Skills::CelestialOrb::GetOrbBeamLength () inline private
Definition at line 53 of file CelestialOrb.as.
References GetOrbPosition(), and GetTargetPosition().
Referenced by BeamStart(), and Update().
         {
             vec2 orbPos = GetOrbPosition();
             vec2 actorPos = GetTargetPosition();
             return dist(orbPos, actorPos);
         }
GetOrbPosition()
vec2 Skills::CelestialOrb::GetOrbPosition () inline private
Definition at line 33 of file CelestialOrb.as.
References m_offset, m_skill, and xy().
Referenced by BeamStart(), GetOrbBeamDirection(), GetOrbBeamLength(), and Update().
         {
             return xy(m_skill.m_owner.m_unit.GetPosition()) + m_offset;
         }
GetOwnerPosition()
vec2 Skills::CelestialOrb::GetOwnerPosition () inline private
Definition at line 28 of file CelestialOrb.as.
References m_skill, and xy().
Referenced by Update().
         {
             return xy(m_skill.m_owner.m_unit.GetPosition());
         }
GetTargetPosition()
vec2 Skills::CelestialOrb::GetTargetPosition () inline private
Definition at line 38 of file CelestialOrb.as.
References m_overrideTarget, m_overrideTargetSet, m_target, and xy().
Referenced by GetOrbBeamDirection(), GetOrbBeamLength(), and Update().
         {
             if (m_overrideTargetSet)
                 return m_overrideTarget;
             return xy(m_target.GetPosition());
         }
RefreshScene()
void Skills::CelestialOrb::RefreshScene (CustomUnitScene@ scene) inline private
Definition at line 60 of file CelestialOrb.as.
References m_offset, and m_skill.
         {
             int layerOffset = 0;
             if (m_offset.y < 0)
                 layerOffset = -1;
             scene.AddScene(m_skill.m_orbFx, 0, m_offset, layerOffset, 0);
         }
Update()
void Skills::CelestialOrb::Update (int dt) inline private
Definition at line 68 of file CelestialOrb.as.
References ApplyEffects(), BeamStart(), BeamStop(), distsq(), g_scene, GetOrbBeamDirection(), GetOrbBeamLength(), GetOrbPosition(), GetOwnerPosition(), GetTargetPosition(), Actor::IsTargetable(), m_beam, m_index, m_intervalC, m_offset, m_overrideTarget, m_overrideTargetSet, m_skill, m_sndI, m_target, max, xy(), and xyz().
         {
             UnitPtr newTarget;
             // Check if we should override the target
             auto owner = cast<PlayerBase>(m_skill.m_owner);
             if (owner !is null)
             {
                 auto skillBeam = cast<Skills::ShootBeam>(owner.m_skills[1]);
                 if (skillBeam !is null)
                 {
                     m_overrideTargetSet = skillBeam.m_isUnitHit;
                     if (m_overrideTargetSet)
                     {
                         m_overrideTarget = skillBeam.m_unitHitPos;
                         newTarget = skillBeam.m_unitHit;
                     }
                 }
             }
             // Find offset of orb from player
             float angle = (m_index / float(m_skill.m_numOrbs)) * PI * 2;
             angle += m_skill.m_tmNow / 1000.0f;
             vec2 dir = vec2(cos(angle), sin(angle));
             float distance;
             vec2 ownerPos = GetOwnerPosition();
             auto rayRes = g_scene.Raycast(ownerPos, ownerPos + dir * m_skill.m_orbDistance, ~0, RaycastType::Shot);
             if (rayRes.length() > 0)
                 distance = max(0.0f, dist(ownerPos, rayRes[0].point) - 4.0f);
             else
                 distance = m_skill.m_orbDistance;
             m_offset = dir * distance;
             vec2 orbPos = GetOrbPosition();
             if (!m_overrideTargetSet)
             {
                 // Find closest unit
                 float closestDistance = (m_skill.m_orbRange * m_skill.m_orbRange) + 1.0f;
                 array<UnitPtr>@ results = g_scene.FetchActorsWithOtherTeam(m_skill.m_owner.Team, orbPos, m_skill.m_orbRange);
                 for (uint i = 0; i < results.length(); i++)
                 {
                     Actor@ actor = cast<Actor>(results[i].GetScriptBehavior());
                     if (!actor.IsTargetable())
                         continue;
                     bool canSee = true;
                     auto canSeeRes = g_scene.Raycast(orbPos, xy(results[i].GetPosition()), ~0, RaycastType::Shot);
                     for (uint j = 0; j < canSeeRes.length(); j++)
                     {
                         UnitPtr canSeeUnit = canSeeRes[j].FetchUnit(g_scene);
                         if (canSeeUnit == results[i])
                             break;
                         auto canSeeActor = cast<Actor>(canSeeUnit.GetScriptBehavior());
                         if (canSeeActor is m_skill.m_owner)
                             continue;
                         canSee = false;
                         break;
                     }
                     if (!canSee)
                         continue;
                     vec2 actorPos = xy(results[i].GetPosition());
                     float d = distsq(orbPos, actorPos);
                     if (d < closestDistance)
                     {
                         newTarget = results[i];
                         closestDistance = d;
                     }
                 }
             }
             // Start, stop, or update beam
             UnitPtr prevTarget = m_target;
             m_target = newTarget;
             if (!prevTarget.IsValid() && newTarget.IsValid())
                 BeamStart();
             else if (prevTarget.IsValid() && !newTarget.IsValid())
                 BeamStop();
             else if (m_beam.IsValid())
             {
                 m_sndI.SetPosition(xyz(orbPos));
                 m_beam.SetPosition(xyz(orbPos));
                 auto beamBehavior = cast<EffectBehavior>(m_beam.GetScriptBehavior());
                 if (beamBehavior !is null)
                 {
                     beamBehavior.SetParam("angle", GetOrbBeamDirection());
                     beamBehavior.SetParam("length", GetOrbBeamLength());
                 }
             }
             // Maybe apply effects
             m_intervalC -= dt;
             if (m_intervalC <= 0)
             {
                 m_intervalC += m_skill.m_effectInterval;
                 vec2 targetPos = GetTargetPosition();
                 vec2 targetDir = normalize(targetPos - orbPos);
                 ApplyEffects(m_skill.m_effects, m_skill.m_owner, m_target, targetPos, targetDir, 1.0f, m_skill.m_owner.IsHusk());
             }
         }
Member Data Documentation
m_beam
UnitPtr Skills::CelestialOrb::m_beam private
Definition at line 16 of file CelestialOrb.as.
Referenced by BeamStart(), BeamStop(), and Update().
m_index
int Skills::CelestialOrb::m_index private
Definition at line 5 of file CelestialOrb.as.
Referenced by CelestialOrb(), and Update().
m_intervalC
int Skills::CelestialOrb::m_intervalC private
Definition at line 8 of file CelestialOrb.as.
Referenced by CelestialOrb(), and Update().
m_offset
vec2 Skills::CelestialOrb::m_offset private
Definition at line 10 of file CelestialOrb.as.
Referenced by GetOrbPosition(), RefreshScene(), and Update().
m_overrideTarget
vec2 Skills::CelestialOrb::m_overrideTarget private
Definition at line 12 of file CelestialOrb.as.
Referenced by GetTargetPosition(), and Update().
m_overrideTargetSet
bool Skills::CelestialOrb::m_overrideTargetSet private
Definition at line 13 of file CelestialOrb.as.
Referenced by GetTargetPosition(), and Update().
m_skill
CelestialOrbs Skills::CelestialOrb::m_skill private
Definition at line 6 of file CelestialOrb.as.
Referenced by BeamStart(), CelestialOrb(), GetOrbPosition(), GetOwnerPosition(), RefreshScene(), and Update().
m_sndI
SoundInstance Skills::CelestialOrb::m_sndI private
Definition at line 18 of file CelestialOrb.as.
Referenced by BeamStart(), BeamStop(), and Update().
m_target
UnitPtr Skills::CelestialOrb::m_target private
Definition at line 15 of file CelestialOrb.as.
Referenced by GetTargetPosition(), and Update().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Skills/CelestialOrb.as