HoHDocs: OwnedItemSet Class Reference
OwnedItemSet Class Reference
Private Member Functions
OwnedItemSet (ActorSet@ itemSet)
bool IsBonusActive (ActorSetBonus@ bonus)
bool IsAnyBonusActive ()
int GetNumBonusesActive ()
ActorSetBonus GetBestBonus ()
Private Attributes
ActorSet m_set
int m_count
Detailed Description
Definition at line 43 of file PlayerRecord.as.
Constructor & Destructor Documentation
OwnedItemSet()
OwnedItemSet::OwnedItemSet (ActorSet@ itemSet) inline private
Definition at line 48 of file PlayerRecord.as.
References m_set.
     {
         @m_set = itemSet;
     }
Member Function Documentation
GetBestBonus()
ActorSetBonus OwnedItemSet::GetBestBonus () inline private
Definition at line 79 of file PlayerRecord.as.
References ActorSet::bonuses, IsBonusActive(), and m_set.
     {
         ActorSetBonus@ ret = null;
         for (uint i = 0; i < m_set.bonuses.length(); i++)
         {
             auto bonus = m_set.bonuses[i];
             if (IsBonusActive(bonus))
                 @ret = bonus;
             else
                 break;
         }
         return ret;
     }
GetNumBonusesActive()
int OwnedItemSet::GetNumBonusesActive () inline private
Definition at line 68 of file PlayerRecord.as.
References ActorSet::bonuses, IsBonusActive(), and m_set.
Referenced by PlayerBase::AddItem().
     {
         int ret = 0;
         for (uint i = 0; i < m_set.bonuses.length(); i++)
         {
             if (IsBonusActive(m_set.bonuses[i]))
                 ret++;
         }
         return ret;
     }
IsAnyBonusActive()
bool OwnedItemSet::IsAnyBonusActive () inline private
Definition at line 58 of file PlayerRecord.as.
References ActorSet::bonuses, IsBonusActive(), and m_set.
     {
         for (uint i = 0; i < m_set.bonuses.length(); i++)
         {
             if (IsBonusActive(m_set.bonuses[i]))
                 return true;
         }
         return false;
     }
IsBonusActive()
bool OwnedItemSet::IsBonusActive (ActorSetBonus@ bonus) inline private
Definition at line 53 of file PlayerRecord.as.
References m_count.
Referenced by GetBestBonus(), GetItemSetColorString(), GetNumBonusesActive(), and IsAnyBonusActive().
     {
         return (m_count >= bonus.num);
     }
Member Data Documentation
m_count
int OwnedItemSet::m_count private
Definition at line 46 of file PlayerRecord.as.
Referenced by GetItemSetColorString(), and IsBonusActive().
m_set
ActorSet OwnedItemSet::m_set private
Definition at line 45 of file PlayerRecord.as.
Referenced by GetBestBonus(), GetNumBonusesActive(), IsAnyBonusActive(), and OwnedItemSet().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Player/PlayerRecord.as