HoHDocs: PlayerHusk Class Reference
PlayerHusk Class Reference
Private Member Functions
PlayerHusk (UnitPtr unit, SValue &params)
void Initialize (PlayerRecord@ record) override
bool IsHusk () override
bool IsDead () override
void UpdateColors () override
int Heal (int amount) override
void NetDamage (DamageInfo dmg, vec2 pos, vec2 dir) override
void NetDecimate (int hp, int mana) override
void OnDeath (DamageInfo di, vec2 dir) override
void KilledActor (Actor@ killed, DamageInfo di) override
void Kill (DamageInfo di)
void MovePlayer (vec2 pos, vec2 dir)
void Dash (int dur, vec2 dir)
void OnLevelUp ()
void Update (int dt) override
bool PreRender (int idt)
Private Attributes
SoundEvent m_dmHit
vec2 m_dir
vec2 m_posTarget
BitmapString m_textName
Detailed Description
Definition at line 1 of file PlayerHusk.as.
Constructor & Destructor Documentation
PlayerHusk()
PlayerHusk::PlayerHusk (UnitPtr unit, SValue & params) inline private
Definition at line 11 of file PlayerHusk.as.
References Actor::m_crosshairColors, m_dmHit, m_posTarget, Actor::m_unit, unit, and xy().
     {
         super(unit, params);
         m_unit.SetShouldCollide(false);
         m_posTarget = xy(m_unit.GetPosition());
         @m_dmHit = Resources::GetSoundEvent("event:/player/dm-hit");
         m_crosshairColors = true;
     }
Member Function Documentation
Dash()
void PlayerHusk::Dash (int dur, vec2 dir) inline private
Definition at line 128 of file PlayerHusk.as.
References PlayerBase::m_dashDir, and PlayerBase::m_dashTime.
Referenced by PlayerHandler::PlayerDash().
     {
         m_dashTime = dur;
         m_dashDir = dir;
     }
Heal()
int PlayerHusk::Heal (int amount) inline override private
Definition at line 47 of file PlayerHusk.as.
References PlayerBase::NetHeal().
     {
         NetHeal(amount);
         return amount;
     }
Initialize()
void PlayerHusk::Initialize (PlayerRecord@ record) inline override private
Definition at line 23 of file PlayerHusk.as.
References GetHUD(), PlayerBase::Initialize(), m_preRenderables, PlayerBase::m_record, and Actor::m_unit.
     {
         PlayerBase::Initialize(record);
         m_preRenderables.insertLast(this);
         if (m_record.corpse is null)
         {
             auto hud = GetHUD();
             if (hud !is null && hud.m_waypoints !is null)
                 hud.m_waypoints.AddWaypoint(PlayerWaypoint(m_unit, record));
         }
     }
IsDead()
bool PlayerHusk::IsDead () inline override private
Definition at line 38 of file PlayerHusk.as.
References PlayerBase::m_record.
 { return m_record.IsDead(); }
IsHusk()
bool PlayerHusk::IsHusk () inline override private
Definition at line 37 of file PlayerHusk.as.
 { return true; }
Kill()
void PlayerHusk::Kill (DamageInfo di) inline private
Definition at line 116 of file PlayerHusk.as.
References DamageInfo::Attacker, Actor::Kill(), m_dir, and OnDeath().
     {
         OnDeath(di, m_dir);
         Actor::Kill(di.Attacker, 0);
     }
KilledActor()
void PlayerHusk::KilledActor (Actor@ killed, DamageInfo di) inline override private
Definition at line 87 of file PlayerHusk.as.
References PlayerBase::GetComboBars(), Actor::KilledActor(), PlayerBase::m_comboActive, PlayerBase::m_comboCount, PlayerBase::m_comboTime, PlayerBase::m_record, and Stats::Max().
     {
         PlayerBase::KilledActor(killed, di);
         if (m_comboActive)
         {
             m_comboCount++;
             Stats::Max("best-combo", m_comboCount, m_record);
             vec2 combo = GetComboBars();
             if (combo.x >= 1.0f)
                 m_comboTime = 2000;
             else
                 m_comboTime = 1000;
         }
         if (cast<CompositeActorBehavior>(killed) is null)
             return;
         /*
         if (killed.m_countsAsKill)
         {
             m_record.kills++;
             m_record.killsTotal++;
         }
         */
     }
MovePlayer()
void PlayerHusk::MovePlayer (vec2 pos, vec2 dir) inline private
Definition at line 122 of file PlayerHusk.as.
References m_dir, and m_posTarget.
Referenced by PlayerHandler::PlayerMove().
     {
         m_posTarget = pos;
         m_dir = dir;
     }
NetDamage()
void PlayerHusk::NetDamage (DamageInfo dmg, vec2 pos, vec2 dir) inline override private
Definition at line 53 of file PlayerHusk.as.
References AddFloatingText(), DamageInfo::Attacker, DamageInfo::Damage, EnemyHurt, m_dmHit, PlayerBase::m_gore, PlayerBase::m_record, Actor::m_unit, and PlaySound2D().
Referenced by PlayerHandler::PlayerDamaged().
     {
         if (cast<Player>(dmg.Attacker) !is null)
             PlaySound2D(m_dmHit);
         AddFloatingText(FloatingTextType::EnemyHurt, "" + dmg.Damage, m_unit.GetPosition());
         //m_record.hp -= float(dmg.Damage) / float(m_record.MaxHealth());
         if (m_gore !is null)
             m_gore.OnHit(float(dmg.Damage) / float(m_record.MaxHealth()), pos, atan(dir.y, dir.x));
     }
NetDecimate()
void PlayerHusk::NetDecimate (int hp, int mana) inline override private
Definition at line 65 of file PlayerHusk.as.
References AddFloatingText(), EnemyHurt, and Actor::m_unit.
     {
         AddFloatingText(FloatingTextType::EnemyHurt, "" + hp, m_unit.GetPosition());
     }
OnDeath()
void PlayerHusk::OnDeath (DamageInfo di, vec2 dir) inline override private
Definition at line 70 of file PlayerHusk.as.
References DamageInfo::Attacker, GetLocalPlayer(), PlayerBase::m_record, PlayerBase::OnDeath(), and DamageInfo::Weapon.
Referenced by Kill().
     {
         PlayerBase::OnDeath(di, dir);
         m_record.deaths++;
         m_record.deathsTotal++;
         m_record.hp = -1;
 %if MOD_SHARED_HP
         Player@ ply = GetLocalPlayer();
         if (ply is null)
             return;
         ply.Kill(di.Attacker, di.Weapon);
 %endif
     }
OnLevelUp()
void PlayerHusk::OnLevelUp () inline private
Definition at line 134 of file PlayerHusk.as.
References Actor::m_unit, PlayEffect(), and PlaySound3D().
Referenced by PlayerHandler::PlayerLevelUp().
     {
         PlaySound3D(Resources::GetSoundEvent("event:/player/levelup-others"), m_unit);
         PlayEffect("effects/generic/player_levelup.effect", m_unit);
     }
PreRender()
bool PlayerHusk::PreRender (int idt) inline private
Definition at line 172 of file PlayerHusk.as.
References Actor::m_unit.
     {
         if (m_unit.IsDestroyed())
             return true;
         return false;
     }
Update()
void PlayerHusk::Update (int dt) inline override private
Definition at line 140 of file PlayerHusk.as.
References distsq(), PlayerBase::m_dashAnim, PlayerBase::m_dashDir, PlayerBase::m_dashTime, m_dir, PlayerBase::m_idleAnim, PlayerBase::m_playerBobbing, m_posTarget, PlayerBase::m_skills, Actor::m_unit, PlayerBase::m_walkAnim, PlayerBase::SetAngle(), PlayerBase::SetBodyAnim(), PlayerBase::Update(), and PlayerBase::UpdateFootsteps().
     {
         PhysicsBody@ bdy = m_unit.GetPhysicsBody();
         float facing;
         if (m_dashTime > 0)
         {
             m_dashTime -= dt;
             facing = atan(m_dashDir.y, m_dashDir.x);
         }
         else
             facing = atan(m_dir.y, m_dir.x);
         SetAngle(facing);
         bool walking = (distsq(m_unit, m_posTarget) > 1);
         bool dashing = m_dashTime > 0;
         string scene = (dashing ? m_dashAnim : (walking ? m_walkAnim : m_idleAnim)).GetSceneName(facing);
         SetBodyAnim(scene, false);
         UpdateFootsteps(dt, dashing, walking);
         for (uint i = 0; i < m_skills.length(); i++)
             m_skills[i].Update(dt, walking);
         //m_unit.SetPositionZ(walking ? ((m_unit.GetUnitSceneTime() / 125) % 2) : 0);
         if (m_playerBobbing)
             m_unit.SetPosition(m_posTarget.x, m_posTarget.y, walking ? ((m_unit.GetUnitSceneTime() / 125) % 2) : 0, true);
         PlayerBase::Update(dt);
     }
UpdateColors()
void PlayerHusk::UpdateColors () inline override private
Definition at line 40 of file PlayerHusk.as.
References m_textName, and PlayerBase::UpdateColors().
     {
         PlayerBase::UpdateColors();
         @m_textName = null;
     }
Member Data Documentation
m_dir
vec2 PlayerHusk::m_dir private
Definition at line 5 of file PlayerHusk.as.
Referenced by Kill(), MovePlayer(), PlayerHandler::PlayerDamaged(), and Update().
m_dmHit
SoundEvent PlayerHusk::m_dmHit private
Definition at line 3 of file PlayerHusk.as.
Referenced by NetDamage(), and PlayerHusk().
m_posTarget
vec2 PlayerHusk::m_posTarget private
Definition at line 6 of file PlayerHusk.as.
Referenced by MovePlayer(), PlayerHusk(), and Update().
m_textName
BitmapString PlayerHusk::m_textName private
Definition at line 8 of file PlayerHusk.as.
Referenced by BaseGameMode::DisplayPlayerName(), and UpdateColors().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Player/PlayerHusk.as