HoHDocs: Skills::Charge Class Reference
Skills::Charge Class Reference
Private Member Functions
Charge (UnitPtr unit, SValue &params)
void Initialize (Actor@ owner, ScriptSprite@ icon, uint id) override
TargetingMode GetTargetingMode (int &out size) override
void DoActivate (SValueBuilder@ builder, vec2 target) override
void CancelCharge ()
void NetDoActivate (SValue@ param, vec2 target) override
void OnCollide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxOther) override
vec2 GetMoveDir () override
void PlayHitEffect (vec2 pos)
bool HitUnit (UnitPtr unit, vec2 pos, bool sensor=false)
bool TryHit (UnitPtr unit)
void DoUpdate (int dt) override
Private Attributes
array< IEffect@> m_effects
int m_speed
int m_duration
int m_durationC
vec2 m_dir
int m_dustC
string m_dustFx
bool m_husk
array< UnitPtr > m_hitUnits
string m_hitFx
SoundEvent m_hitSnd
bool m_hitSensors
Detailed Description
Definition at line 3 of file Charge.as.
Constructor & Destructor Documentation
Charge()
Skills::Charge::Charge (UnitPtr unit, SValue & params) inline private
Definition at line 22 of file Charge.as.
References LoadEffects(), m_duration, m_durationC, m_dustFx, m_effects, m_hitFx, m_hitSensors, m_hitSnd, m_speed, and unit.
         {
             super(unit, params);
             @m_effects = LoadEffects(unit, params);
             m_speed = GetParamInt(unit, params, "speed", false, 3);
             m_duration = GetParamInt(unit, params, "duration", false, 1000);
             m_durationC = 0;
             m_dustFx = GetParamString(unit, params, "dust-fx", false);
             m_hitFx = GetParamString(unit, params, "hit-fx", false);
             @m_hitSnd = Resources::GetSoundEvent(GetParamString(unit, params, "hit-snd", false));
             m_hitSensors = GetParamBool(unit, params, "hit-sensors", false);
         }
Member Function Documentation
CancelCharge()
void Skills::Charge::CancelCharge () inline private
Definition at line 63 of file Charge.as.
References m_durationC, and Skills::m_owner.
Referenced by DoUpdate().
         {
             m_durationC = 0;
             cast<PlayerBase>(m_owner).SetCharging(false);
         }
DoActivate()
void Skills::Charge::DoActivate (SValueBuilder@ builder, vec2 target) inline override private
Definition at line 54 of file Charge.as.
References m_dir, m_duration, m_durationC, m_hitUnits, Skills::m_owner, and Skills::ActiveSkill::PlaySkillEffect().
         {
             m_durationC = m_duration;
             m_dir = normalize(target);
             m_hitUnits.removeRange(0, m_hitUnits.length());
             cast<PlayerBase>(m_owner).SetCharging(true);
             PlaySkillEffect(m_dir);
         }
DoUpdate()
void Skills::Charge::DoUpdate (int dt) inline override private
Definition at line 151 of file Charge.as.
References CancelCharge(), g_scene, HitUnit(), Skills::ActiveSkill::m_animation, m_dir, m_durationC, m_dustC, m_dustFx, Skills::m_owner, m_speed, PlayEffect(), and xy().
         {
             if (m_durationC > 0)
             {
                 m_durationC -= dt;
                 m_owner.SetUnitScene(m_animation, false);
                 m_dustC -= dt;
                 if (m_dustC <= 0)
                 {
                     m_dustC += randi(66) + 33;
                     PlayEffect(m_dustFx, xy(m_owner.m_unit.GetPosition()));
                 }
                 vec2 from = xy(m_owner.m_unit.GetPosition()) ;//+ m_dir * 3;
                 vec2 to = from + m_dir * m_speed * dt / 33.0;
                 array<RaycastResult>@ results = g_scene.RaycastWide(4, 3, from, to + m_dir * 3, ~0, RaycastType::Any);
                 for (uint i = 0; i < results.length(); i++)
                 {
                     RaycastResult res = results[i];
                     //if (res.fixture.IsSensor())
                     //  continue;
                     HitUnit(res.FetchUnit(g_scene), res.point, res.fixture.IsSensor());
                 }
 //              m_owner.m_unit.SetPosition(to.x, to.y, 0, true);
                 if (m_durationC <= 0)
                     CancelCharge();
             }
         }
GetMoveDir()
vec2 Skills::Charge::GetMoveDir () inline override private
Definition at line 94 of file Charge.as.
References m_dir, m_durationC, and m_speed.
         {
             return (m_durationC > 0) ? (m_dir * m_speed) : vec2();
         }
GetTargetingMode()
TargetingMode Skills::Charge::GetTargetingMode (int &out size) inline override private
Definition at line 48 of file Charge.as.
References Skills::Direction.
         {
             size = 0;
             return TargetingMode::Direction;
         }
HitUnit()
bool Skills::Charge::HitUnit (UnitPtr unit, vec2 pos, bool sensor = false) inline private
Definition at line 105 of file Charge.as.
References ApplyEffects(), m_dir, m_effects, m_husk, Skills::m_owner, PlayHitEffect(), TryHit(), and unit.
Referenced by DoUpdate(), and OnCollide().
         {
             if (!unit.IsValid())
                 return true;
             ref@ b = unit.GetScriptBehavior();
             IProjectile@ p = cast<IProjectile>(b);
             if (p !is null)
                 return true;
             auto dt = cast<IDamageTaker>(b);
             if (dt !is null)
             {
                 if (dt.ShootThrough(pos, m_dir))
                     return true;
                 if (TryHit(unit))
                 {
                     ApplyEffects(m_effects, m_owner, unit, pos, m_dir, 1.0, m_husk, 0.0f, 0.0f, 1.0f);
                     PlayHitEffect(pos);
                     return !dt.Impenetrable();
                 }
                 return true;
             }
             if (TryHit(unit))
             {
                 ApplyEffects(m_effects, m_owner, unit, pos, m_dir, 1.0f, m_husk, 0.0f, 0.0f, 1.0f);
                 PlayHitEffect(pos);
                 return sensor;
             }
             return sensor;
         }
Initialize()
void Skills::Charge::Initialize (Actor@ owner, ScriptSprite@ icon, uint id) inline override private
Definition at line 40 of file Charge.as.
References icon, Initialize(), m_effects, m_husk, and PropagateWeaponInformation().
         {
             ActiveSkill::Initialize(owner, icon, id);
             PropagateWeaponInformation(m_effects, id + 1);
             m_husk = cast<Player>(owner) is null;
         }
NetDoActivate()
void Skills::Charge::NetDoActivate (SValue@ param, vec2 target) inline override private
Definition at line 69 of file Charge.as.
References m_dir, m_duration, m_durationC, Skills::m_owner, and Skills::ActiveSkill::PlaySkillEffect().
         {
             cast<PlayerBase>(m_owner).SetCharging(true);
             PlaySkillEffect(target);
             m_durationC = m_duration;
             m_dir = normalize(target);
         }
OnCollide()
void Skills::Charge::OnCollide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxOther) inline override private
Definition at line 78 of file Charge.as.
References HitUnit(), m_durationC, m_hitSensors, and unit.
         {
             if (m_durationC <= 0)
                 return;
             bool isSensor = fxOther.IsSensor();
             if (isSensor && !m_hitSensors)
                 return;
             HitUnit(unit, pos, isSensor);
             /*
             else if (dot(normal, m_dir) > 0.75)
                 CancelCharge();
             */
         }
PlayHitEffect()
void Skills::Charge::PlayHitEffect (vec2 pos) inline private
Definition at line 99 of file Charge.as.
References m_hitFx, m_hitSnd, PlayEffect(), PlaySound3D(), and xyz().
Referenced by HitUnit().
         {
             PlayEffect(m_hitFx, pos);
             PlaySound3D(m_hitSnd, xyz(pos));
         }
TryHit()
bool Skills::Charge::TryHit (UnitPtr unit) inline private
Definition at line 141 of file Charge.as.
References m_hitUnits, and unit.
Referenced by HitUnit().
         {
             for (uint j = 0; j < m_hitUnits.length(); j++)
                 if (m_hitUnits[j] == unit)
                     return false;
             m_hitUnits.insertLast(unit);
             return true;
         }
Member Data Documentation
m_dir
vec2 Skills::Charge::m_dir private
Definition at line 10 of file Charge.as.
Referenced by DoActivate(), DoUpdate(), GetMoveDir(), HitUnit(), and NetDoActivate().
m_duration
int Skills::Charge::m_duration private
Definition at line 8 of file Charge.as.
Referenced by Charge(), DoActivate(), and NetDoActivate().
m_durationC
int Skills::Charge::m_durationC private
Definition at line 9 of file Charge.as.
Referenced by CancelCharge(), Charge(), DoActivate(), DoUpdate(), GetMoveDir(), NetDoActivate(), and OnCollide().
m_dustC
int Skills::Charge::m_dustC private
Definition at line 11 of file Charge.as.
Referenced by DoUpdate().
m_dustFx
string Skills::Charge::m_dustFx private
Definition at line 12 of file Charge.as.
Referenced by Charge(), and DoUpdate().
m_effects
array<IEffect@> Skills::Charge::m_effects private
Definition at line 5 of file Charge.as.
Referenced by Charge(), HitUnit(), and Initialize().
m_hitFx
string Skills::Charge::m_hitFx private
Definition at line 16 of file Charge.as.
Referenced by Charge(), and PlayHitEffect().
m_hitSensors
bool Skills::Charge::m_hitSensors private
Definition at line 19 of file Charge.as.
Referenced by Charge(), and OnCollide().
m_hitSnd
SoundEvent Skills::Charge::m_hitSnd private
Definition at line 17 of file Charge.as.
Referenced by Charge(), and PlayHitEffect().
m_hitUnits
array<UnitPtr> Skills::Charge::m_hitUnits private
Definition at line 14 of file Charge.as.
Referenced by DoActivate(), and TryHit().
m_husk
bool Skills::Charge::m_husk private
Definition at line 13 of file Charge.as.
Referenced by HitUnit(), and Initialize().
m_speed
int Skills::Charge::m_speed private
Definition at line 7 of file Charge.as.
Referenced by Charge(), DoUpdate(), and GetMoveDir().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Skills/Charge.as