HoHDocs: Skills::ShootRay Class Reference
Skills::ShootRay Class Reference
Private Member Functions
ShootRay (UnitPtr unit, SValue &params)
void Initialize (Actor@ owner, ScriptSprite@ icon, uint id) override
bool NeedNetParams () override
void DoActivate (SValueBuilder@ builder, vec2 target) override
void NetDoActivate (SValue@ param, vec2 target) override
Private Attributes
float m_distance
SoundEvent m_hitSnd
string m_hitFx
array< IAction@> m_actions
Detailed Description
Definition at line 3 of file ShootRay.as.
Constructor & Destructor Documentation
ShootRay()
Skills::ShootRay::ShootRay (UnitPtr unit, SValue & params) inline private
Definition at line 12 of file ShootRay.as.
References LoadActions(), m_actions, m_distance, m_hitFx, m_hitSnd, and unit.
         {
             super(unit, params);
             m_distance = GetParamFloat(unit, params, "dist", false, 50);
             @m_hitSnd = Resources::GetSoundEvent(GetParamString(unit, params, "hit-snd", false));
             m_hitFx = GetParamString(unit, params, "hit-fx", false);
             @m_actions = LoadActions(unit, params);
         }
Member Function Documentation
DoActivate()
void Skills::ShootRay::DoActivate (SValueBuilder@ builder, vec2 target) inline override private
Definition at line 32 of file ShootRay.as.
References DoActions(), g_scene, m_actions, m_distance, m_hitFx, m_hitSnd, Skills::m_owner, PlayEffect(), PlaySound3D(), unit, xy(), and xyz().
         {
             builder.PushArray();
             vec2 pos = xy(m_owner.m_unit.GetPosition());
             vec2 posHit = pos + target * m_distance;
             auto ray = g_scene.Raycast(pos, posHit, ~0, RaycastType::Shot);
             for (uint i = 0; i < ray.length(); i++)
             {
                 UnitPtr unit = ray[i].FetchUnit(g_scene);
                 if (!unit.IsValid())
                     continue;
                 if (cast<PlayerBase>(unit.GetScriptBehavior()) is null)
                 {
                     posHit = ray[i].point;
                     break;
                 }
             }
             builder.PushVector2(pos);
             builder.PushVector2(posHit);
             PlaySound3D(m_hitSnd, xyz(posHit));
             dictionary ePs = { { 'angle', atan(target.y, target.x) } };
             PlayEffect(m_hitFx, posHit, ePs);
             SValue@ params = DoActions(m_actions, m_owner, null, posHit, target);
             builder.PushSimple(params);
             builder.PopArray();
         }
Initialize()
void Skills::ShootRay::Initialize (Actor@ owner, ScriptSprite@ icon, uint id) inline override private
Definition at line 24 of file ShootRay.as.
References icon, Initialize(), m_actions, and PropagateWeaponInformation().
         {
             ActiveSkill::Initialize(owner, icon, id);
             PropagateWeaponInformation(m_actions, id + 1);
         }
NeedNetParams()
bool Skills::ShootRay::NeedNetParams () inline override private
Definition at line 30 of file ShootRay.as.
 { return true; }
NetDoActivate()
void Skills::ShootRay::NetDoActivate (SValue@ param, vec2 target) inline override private
Definition at line 67 of file ShootRay.as.
References m_actions, m_hitFx, m_hitSnd, Skills::m_owner, NetDoActions(), PlayEffect(), PlaySound3D(), and xyz().
         {
             array<SValue@>@ pm = param.GetArray();
             vec2 pos = pm[0].GetVector2();
             vec2 posHit = pm[1].GetVector2();
             PlaySound3D(m_hitSnd, xyz(posHit));
             dictionary ePs = { { 'angle', atan(target.y, target.x) } };
             PlayEffect(m_hitFx, posHit, ePs);
             NetDoActions(m_actions, pm[2], m_owner, posHit, target);
         }
Member Data Documentation
m_actions
array<IAction@> Skills::ShootRay::m_actions private
Definition at line 10 of file ShootRay.as.
Referenced by DoActivate(), Initialize(), NetDoActivate(), and ShootRay().
m_distance
float Skills::ShootRay::m_distance private
Definition at line 5 of file ShootRay.as.
Referenced by DoActivate(), and ShootRay().
m_hitFx
string Skills::ShootRay::m_hitFx private
Definition at line 8 of file ShootRay.as.
Referenced by DoActivate(), NetDoActivate(), and ShootRay().
m_hitSnd
SoundEvent Skills::ShootRay::m_hitSnd private
Definition at line 7 of file ShootRay.as.
Referenced by DoActivate(), NetDoActivate(), and ShootRay().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Skills/ShootRay.as