HoHDocs: Skills::StaggeredSpawnUnits Class Reference
Skills::StaggeredSpawnUnits Class Reference
Private Member Functions
StaggeredSpawnUnits (UnitPtr unit, SValue &params)
TargetingMode GetTargetingMode (int &out size) override
void DoActivate (SValueBuilder@ builder, vec2 target) override
void NetDoActivate (SValue@ param, vec2 target) override
void StartSpawning (bool husk)
float GetMoveSpeedMul () override
void DoUpdate (int dt) override
UnitPtr LocalSpawnUnit (vec2 pos, Actor@ owner, float intensity, bool husk, int id=0)
Private Attributes
UnitProducer m_unitProd
array< vec2 > m_positions
int m_duration
int m_durationC
bool m_spawningHusk
bool m_needNetSync
Detailed Description
Definition at line 3 of file StaggeredSpawnUnits.as.
Constructor & Destructor Documentation
StaggeredSpawnUnits()
Skills::StaggeredSpawnUnits::StaggeredSpawnUnits (UnitPtr unit, SValue & params) inline private
Definition at line 14 of file StaggeredSpawnUnits.as.
References IsNetsyncedExistance(), m_duration, m_needNetSync, m_positions, m_unitProd, and unit.
         {
             super(unit, params);
             m_duration = GetParamInt(unit, params, "duration");
             @m_unitProd = Resources::GetUnitProducer(GetParamString(unit, params, "unit", false));
             array<SValue@>@ arr = GetParamArray(unit, params, "positions", false);
             for (int i = arr.length() -1; i >= 0; i--)
                 m_positions.insertLast(arr[i].GetVector2());
             m_needNetSync = !IsNetsyncedExistance(m_unitProd.GetNetSyncMode());
         }
Member Function Documentation
DoActivate()
void Skills::StaggeredSpawnUnits::DoActivate (SValueBuilder@ builder, vec2 target) inline override private
Definition at line 34 of file StaggeredSpawnUnits.as.
References StartSpawning().
         {
             StartSpawning(false);
         }
DoUpdate()
void Skills::StaggeredSpawnUnits::DoUpdate (int dt) inline override private
Definition at line 57 of file StaggeredSpawnUnits.as.
References LocalSpawnUnit(), m_duration, m_durationC, m_needNetSync, Skills::m_owner, m_positions, m_spawningHusk, min, and xy().
         {
             if (m_durationC <= 0)
                 return;
             int i1 = min(int(m_durationC * m_positions.length()) / m_duration, int(m_positions.length()) -1);
             m_durationC -= dt;
             int i2 = min(int(m_durationC * m_positions.length()) / m_duration, int(m_positions.length()) -1);
             if (i1 != i2 || m_durationC <= 0)
             {
                 vec2 pos = xy(m_owner.m_unit.GetPosition()) + m_positions[m_durationC <= 0 ? 0 : i1];
                 if (m_needNetSync || Network::IsServer())
                     LocalSpawnUnit(pos, m_owner, 1.0f, m_spawningHusk);
             }
         }
GetMoveSpeedMul()
float Skills::StaggeredSpawnUnits::GetMoveSpeedMul () inline override private
Definition at line 55 of file StaggeredSpawnUnits.as.
References m_durationC, and Skills::ActiveSkill::m_speedMul.
 { return m_durationC <= 0 ? 1.0 : m_speedMul; }
GetTargetingMode()
TargetingMode Skills::StaggeredSpawnUnits::GetTargetingMode (int &out size) inline override private
Definition at line 28 of file StaggeredSpawnUnits.as.
References Skills::Direction.
         {
             size = 0;
             return TargetingMode::Direction;
         }
LocalSpawnUnit()
UnitPtr Skills::StaggeredSpawnUnits::LocalSpawnUnit (vec2 pos, Actor@ owner, float intensity, bool husk, int id = 0) inline private
Definition at line 74 of file StaggeredSpawnUnits.as.
References g_scene, m_needNetSync, Skills::m_skillId, Actor::m_unit, m_unitProd, PropagateWeaponInformation(), unit, and xyz().
Referenced by DoUpdate().
         {
             auto unit = m_unitProd.Produce(g_scene, xyz(pos), id);
             if (owner !is null)
             {
                 auto ownedUnit = cast<IOwnedUnit>(unit.GetScriptBehavior());
                 if (ownedUnit !is null)
                 {
                     ownedUnit.Initialize(owner, intensity, husk);
                     if (!m_needNetSync && Network::IsServer())
                         (Network::Message("SetOwnedUnit") << unit << owner.m_unit << intensity).SendToAll();
                     // TODO: Remove
                     auto bomb = cast<BombBehavior>(ownedUnit);
                     PropagateWeaponInformation(bomb.m_actions, m_skillId + 1);
                 }
             }
             return unit;
         }
NetDoActivate()
void Skills::StaggeredSpawnUnits::NetDoActivate (SValue@ param, vec2 target) inline override private
Definition at line 39 of file StaggeredSpawnUnits.as.
References StartSpawning().
         {
             StartSpawning(true);
         }
StartSpawning()
void Skills::StaggeredSpawnUnits::StartSpawning (bool husk) inline private
Definition at line 44 of file StaggeredSpawnUnits.as.
References Skills::ActiveSkill::m_animCountdown, Skills::ActiveSkill::m_castpoint, m_duration, m_durationC, m_spawningHusk, and Skills::ActiveSkill::PlaySkillEffect().
Referenced by DoActivate(), and NetDoActivate().
         {
             if (m_durationC > 0)
                 return;
             m_spawningHusk = husk;
             m_durationC = m_duration;
             m_animCountdown = m_duration - m_castpoint;
             PlaySkillEffect(vec2(1,0));
         }
Member Data Documentation
m_duration
int Skills::StaggeredSpawnUnits::m_duration private
Definition at line 8 of file StaggeredSpawnUnits.as.
Referenced by DoUpdate(), StaggeredSpawnUnits(), and StartSpawning().
m_durationC
int Skills::StaggeredSpawnUnits::m_durationC private
Definition at line 9 of file StaggeredSpawnUnits.as.
Referenced by DoUpdate(), GetMoveSpeedMul(), and StartSpawning().
m_needNetSync
bool Skills::StaggeredSpawnUnits::m_needNetSync private
Definition at line 12 of file StaggeredSpawnUnits.as.
Referenced by DoUpdate(), LocalSpawnUnit(), and StaggeredSpawnUnits().
m_positions
array<vec2> Skills::StaggeredSpawnUnits::m_positions private
Definition at line 6 of file StaggeredSpawnUnits.as.
Referenced by DoUpdate(), and StaggeredSpawnUnits().
m_spawningHusk
bool Skills::StaggeredSpawnUnits::m_spawningHusk private
Definition at line 11 of file StaggeredSpawnUnits.as.
Referenced by DoUpdate(), and StartSpawning().
m_unitProd
UnitProducer Skills::StaggeredSpawnUnits::m_unitProd private
Definition at line 5 of file StaggeredSpawnUnits.as.
Referenced by LocalSpawnUnit(), and StaggeredSpawnUnits().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Skills/StaggeredSpawnUnits.as