HoHDocs: Skills::StackSkill Class Reference
Skills::StackSkill Class Reference
Private Member Functions
StackSkill (UnitPtr unit, SValue &params)
void OnDestroy () override
void AddStack (int num=1)
void NetAddStack (int num)
bool TakeStack (int num=1)
void NetTakeStack (int num)
void RefreshCount ()
void Update (int dt, bool walking) override
ScriptSprite GetBuffIcon ()
int GetBuffIconDuration ()
int GetBuffIconMaxDuration ()
int GetBuffIconCount ()
Private Attributes
int m_timerC
int m_timer
int m_maxCount
int m_count
bool m_loseAll
UnitScene m_fxAddStack
UnitScene m_fxTakeStack
UnitScene m_fxLoseStack
ScriptSprite m_hud
bool m_destroyed
Detailed Description
Definition at line 11 of file StackSkill.as.
Constructor & Destructor Documentation
StackSkill()
Skills::StackSkill::StackSkill (UnitPtr unit, SValue & params) inline private
Definition at line 29 of file StackSkill.as.
References Fountain::GetEffect(), m_fxAddStack, m_fxLoseStack, m_fxTakeStack, m_hud, m_loseAll, m_maxCount, m_timer, ScriptSprite(), and unit.
         {
             super(unit);
             m_timer = GetParamInt(unit, params, "duration", false, -1);
             m_maxCount = GetParamInt(unit, params, "max-stacks");
             m_loseAll = GetParamBool(unit, params, "lose-all", false);
             @m_fxAddStack = Resources::GetEffect(GetParamString(unit, params, "fx-add-stack", false));
             @m_fxTakeStack = Resources::GetEffect(GetParamString(unit, params, "fx-take-stack", false));
             @m_fxLoseStack = Resources::GetEffect(GetParamString(unit, params, "fx-lose-stack", false));
             auto arrIcon = GetParamArray(unit, params, "hud", false);
             if (arrIcon !is null)
                 @m_hud = ScriptSprite(arrIcon);
         }
Member Function Documentation
AddStack()
void Skills::StackSkill::AddStack (int num = 1) inline private
Definition at line 52 of file StackSkill.as.
References Skills::m_owner, Skills::m_skillId, NetAddStack(), and num.
         {
             NetAddStack(num);
             if (cast<Player>(m_owner) !is null)
                 (Network::Message("PlayerStackSkillAdd") << m_skillId << num).SendToAll();
         }
GetBuffIcon()
ScriptSprite Skills::StackSkill::GetBuffIcon () inline private
Definition at line 135 of file StackSkill.as.
References m_hud.
         {
             return m_hud;
         }
GetBuffIconCount()
int Skills::StackSkill::GetBuffIconCount () inline private
Definition at line 159 of file StackSkill.as.
References m_count, and m_destroyed.
         {
             if (m_destroyed)
                 return 0;
             return m_count;
         }
GetBuffIconDuration()
int Skills::StackSkill::GetBuffIconDuration () inline private
Definition at line 140 of file StackSkill.as.
References m_count, m_destroyed, m_timer, and m_timerC.
         {
             if (m_destroyed)
                 return 0;
             if (m_timer != -1)
                 return m_timerC;
             else
                 return m_count;
         }
GetBuffIconMaxDuration()
int Skills::StackSkill::GetBuffIconMaxDuration () inline private
Definition at line 151 of file StackSkill.as.
References m_maxCount, and m_timer.
         {
             if (m_timer != -1)
                 return m_timer;
             else
                 return m_maxCount;
         }
NetAddStack()
void Skills::StackSkill::NetAddStack (int num) inline private
Definition at line 60 of file StackSkill.as.
References m_count, m_fxAddStack, m_maxCount, Skills::m_owner, m_timer, m_timerC, min, num, PlayEffect(), and RefreshCount().
Referenced by AddStack().
         {
             int countBefore = m_count;
             m_timerC = m_timer;
             m_count = min(m_maxCount, m_count + num);
             RefreshCount();
             if (m_count > countBefore)
                 PlayEffect(m_fxAddStack, m_owner.m_unit);
         }
NetTakeStack()
void Skills::StackSkill::NetTakeStack (int num) inline private
Definition at line 86 of file StackSkill.as.
References m_count, m_fxTakeStack, Skills::m_owner, PlayEffect(), and RefreshCount().
Referenced by TakeStack().
         {
             m_count--;
             RefreshCount();
             PlayEffect(m_fxTakeStack, m_owner.m_unit);
         }
OnDestroy()
void Skills::StackSkill::OnDestroy () inline override private
Definition at line 47 of file StackSkill.as.
References m_destroyed.
         {
             m_destroyed = true;
         }
RefreshCount()
void Skills::StackSkill::RefreshCount () inline private
Definition at line 94 of file StackSkill.as.
References g_gameMode, GetHUD(), and Skills::m_owner.
Referenced by NetAddStack(), NetTakeStack(), and Update().
         {
             BaseGameMode@ gm = cast<BaseGameMode>(g_gameMode);
             auto player = cast<PlayerBase>(m_owner);
             if (gm is null || player is null)
                 return;
             auto hud = GetHUD();
             if (hud !is null)
                 hud.ShowBuffIcon(player, this);
         }
TakeStack()
bool Skills::StackSkill::TakeStack (int num = 1) inline private
Definition at line 73 of file StackSkill.as.
References m_count, Skills::m_owner, Skills::m_skillId, NetTakeStack(), and num.
         {
             if (num > m_count)
                 return false;
             NetTakeStack(num);
             if (cast<Player>(m_owner) !is null)
                 (Network::Message("PlayerStackSkillTake") << m_skillId << num).SendToAll();
             return true;
         }
Update()
void Skills::StackSkill::Update (int dt, bool walking) inline override private
Definition at line 106 of file StackSkill.as.
References m_count, m_fxLoseStack, m_loseAll, Skills::m_owner, m_timer, m_timerC, PlayEffect(), and RefreshCount().
         {
             if (m_timer == -1)
                 return;
             if (m_count <= 0)
             {
                 m_count = 0;
                 return;
             }
             m_timerC -= dt;
             if (m_timerC > 0)
                 return;
             if (m_loseAll)
                 m_count = 0;
             else
                 m_count--;
             if (m_count == 0)
                 m_timerC = 0;
             else
                 m_timerC += m_timer;
             RefreshCount();
             PlayEffect(m_fxLoseStack, m_owner.m_unit);
         }
Member Data Documentation
m_count
int Skills::StackSkill::m_count private
Definition at line 17 of file StackSkill.as.
Referenced by GetBuffIconCount(), GetBuffIconDuration(), NetAddStack(), NetTakeStack(), TakeStack(), and Update().
m_destroyed
bool Skills::StackSkill::m_destroyed private
Definition at line 27 of file StackSkill.as.
Referenced by GetBuffIconCount(), GetBuffIconDuration(), and OnDestroy().
m_fxAddStack
UnitScene Skills::StackSkill::m_fxAddStack private
Definition at line 21 of file StackSkill.as.
Referenced by NetAddStack(), and StackSkill().
m_fxLoseStack
UnitScene Skills::StackSkill::m_fxLoseStack private
Definition at line 23 of file StackSkill.as.
Referenced by StackSkill(), and Update().
m_fxTakeStack
UnitScene Skills::StackSkill::m_fxTakeStack private
Definition at line 22 of file StackSkill.as.
Referenced by NetTakeStack(), and StackSkill().
m_hud
ScriptSprite Skills::StackSkill::m_hud private
Definition at line 25 of file StackSkill.as.
Referenced by GetBuffIcon(), and StackSkill().
m_loseAll
bool Skills::StackSkill::m_loseAll private
Definition at line 19 of file StackSkill.as.
Referenced by StackSkill(), and Update().
m_maxCount
int Skills::StackSkill::m_maxCount private
Definition at line 16 of file StackSkill.as.
Referenced by GetBuffIconMaxDuration(), NetAddStack(), and StackSkill().
m_timer
int Skills::StackSkill::m_timer private
Definition at line 14 of file StackSkill.as.
Referenced by GetBuffIconDuration(), GetBuffIconMaxDuration(), NetAddStack(), StackSkill(), and Update().
m_timerC
int Skills::StackSkill::m_timerC private
Definition at line 13 of file StackSkill.as.
Referenced by GetBuffIconDuration(), NetAddStack(), and Update().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Skills/StackSkill.as