HoHDocs: Skills::Shatter Class Reference
Skills::Shatter Class Reference
Private Member Functions
Shatter (UnitPtr unit, SValue &params)
void OnEnemyKilled (PlayerBase@ player, Actor@ enemy)
void Do (PlayerBase@ player, Actor@ enemy)
void NetDo (Actor@ enemy, SValue@ params)
Private Attributes
float m_chance
Modifiers::EffectTrigger m_effectTrigger
float m_requiredHp
Skills::ShootProjectileFan m_skill
array< IAction@> m_actions
bool m_triggering
Detailed Description
Definition at line 3 of file Shatter.as.
Constructor & Destructor Documentation
Shatter()
Skills::Shatter::Shatter (UnitPtr unit, SValue & params) inline private
Definition at line 14 of file Shatter.as.
References LoadActions(), m_actions, m_chance, m_effectTrigger, Skills::m_owner, m_requiredHp, m_skill, m_skills, Modifiers::ParseEffectTrigger(), and unit.
         {
             super(unit);
             m_chance = GetParamFloat(unit, params, "chance", false, 0.5);
             m_effectTrigger = Modifiers::ParseEffectTrigger(GetParamString(unit, params, "trigger", false, "kill"));
             m_requiredHp = GetParamFloat(unit, params, "required-hp", false, 1.0f);
             int skillIndex = GetParamInt(unit, params, "skill-index", false, -1);
             if (skillIndex != -1)
                 @m_skill = cast<Skills::ShootProjectileFan>(cast<PlayerBase>(m_owner).m_skills[skillIndex]);
             @m_actions = LoadActions(unit, params);
         }
Member Function Documentation
Do()
void Skills::Shatter::Do (PlayerBase@ player, Actor@ enemy) inline private
Definition at line 65 of file Shatter.as.
References DoActions(), m_actions, Actor::m_unit, and xy().
Referenced by OnEnemyKilled().
         {
             if (m_actions is null)
                 return;
             SValue@ params = DoActions(m_actions, player, null, xy(enemy.m_unit.GetPosition()), vec2());
             (Network::Message("PlayerShatterActivate") << enemy.m_unit << params).SendToAll();
         }
NetDo()
void Skills::Shatter::NetDo (Actor@ enemy, SValue@ params) inline private
Definition at line 74 of file Shatter.as.
References m_actions, Skills::m_owner, Actor::m_unit, NetDoActions(), and xy().
         {
             if (enemy is null)
             {
                 PrintError("Enemy behavior is null or not an actor!");
                 return;
             }
             if (m_actions is null)
                 return;
             NetDoActions(m_actions, params, m_owner, xy(enemy.m_unit.GetPosition()), vec2());
         }
OnEnemyKilled()
void Skills::Shatter::OnEnemyKilled (PlayerBase@ player, Actor@ enemy) inline private
Definition at line 29 of file Shatter.as.
References Do(), Actor::GetHealth(), Actor::IsDead(), Actor::Kill(), Kill, m_chance, m_effectTrigger, Skills::m_owner, m_requiredHp, m_skill, m_triggering, Actor::m_unit, and xy().
         {
             if (m_triggering)
                 return;
             if (m_effectTrigger != Modifiers::EffectTrigger::Kill)
                 return; // What then??
             if (enemy.GetHealth() > m_requiredHp)
                 return;
             if (randf() > m_chance)
                 return;
             // Avoid going too far into the level
             auto pos = xy(enemy.m_unit.GetPosition());
             if (dist(xy(player.m_unit.GetPosition()), pos) > 250)
                 return;
             m_triggering = true;
             if (m_skill !is null)
             {
                 SValueBuilder builder;
                 m_skill.DoShoot(builder, pos, vec2(1, 0));
                 (Network::Message("PlayerActiveSkillDoActivate") << m_skill.m_skillId << vec2() << builder.Build()).SendToAll();
             }
             else
                 Do(cast<PlayerBase>(m_owner), enemy);
             if (!enemy.IsDead())
                 enemy.Kill(cast<PlayerBase>(m_owner), 0);
             m_triggering = false;
         }
Member Data Documentation
m_actions
array<IAction@> Skills::Shatter::m_actions private
Definition at line 10 of file Shatter.as.
Referenced by Do(), NetDo(), and Shatter().
m_chance
float Skills::Shatter::m_chance private
Definition at line 5 of file Shatter.as.
Referenced by OnEnemyKilled(), and Shatter().
m_effectTrigger
Modifiers::EffectTrigger Skills::Shatter::m_effectTrigger private
Definition at line 6 of file Shatter.as.
Referenced by OnEnemyKilled(), and Shatter().
m_requiredHp
float Skills::Shatter::m_requiredHp private
Definition at line 7 of file Shatter.as.
Referenced by OnEnemyKilled(), and Shatter().
m_skill
Skills::ShootProjectileFan Skills::Shatter::m_skill private
Definition at line 9 of file Shatter.as.
Referenced by OnEnemyKilled(), and Shatter().
m_triggering
bool Skills::Shatter::m_triggering private
Definition at line 12 of file Shatter.as.
Referenced by OnEnemyKilled().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Skills/Shatter.as