HoHDocs: AnimString Class Reference
AnimString Class Reference
Private Member Functions
AnimString (string str)
string GetSceneName (float dir)
Private Attributes
string m_anim
int m_numDirs
bool m_flipped
bool m_capped
float m_capStart
float m_capSpan
Detailed Description
Definition at line 1 of file AnimString.as.
Constructor & Destructor Documentation
AnimString()
AnimString::AnimString (string str) inline private
Definition at line 10 of file AnimString.as.
References m_anim, m_capped, m_capSpan, m_capStart, and m_numDirs.
     {
         auto strs = str.split(" ");
         if (strs.length() >= 2)
         {
             m_anim = strs[0] + "-";
             m_numDirs = int(parseInt(strs[1]));
         }
         else
         {
             m_anim = str;
             m_numDirs = -1;
         }
         if (strs.length() >= 4)
         {
             m_capStart = parseInt(strs[2]) * PI / 180.0f;
             m_capSpan = parseInt(strs[3]) * PI / 180.0f - m_capStart;
             m_capped = true;
         }
         else
         {
             m_capStart = 0;
             m_capSpan = 2 * PI;
             m_capped = false;
         }
     }
Member Function Documentation
GetSceneName()
string AnimString::GetSceneName (float dir) inline private
Definition at line 39 of file AnimString.as.
References m_anim, m_capped, m_capSpan, m_capStart, and m_numDirs.
Referenced by BossLichMovement::DoWalkPaths(), BossVampireMovement::DoWalkPaths(), MeleeMovement::IdleUpdate(), PassiveMovement::Initialize(), BossLichMovement::Initialize(), BossVampireMovement::Initialize(), MeleeMovement::Initialize(), CompositeJammableActorBehavior::Jam(), BossVampireMovement::NetOnNodeArrived(), NetTrigger(), EnemyMeleeStrike::NetUseSkill(), WhirlwindSkill::NetUseSkill(), TowerFlowerSkill::NetUseSkill(), WhirlNovaSkill::NetUseSkill(), NovaSkill::NetUseSkill(), NovaSkill::NovaSkill(), ResolveDecal(), ResolveGibs(), TossProjectile::SetDirection(), Projectile::SetDirection(), RayProjectile::SetDirection(), CannonBall::SetDirection(), FixedPathFollower::SetFinished(), TripMine::SetIdleAnimation(), FixedPathFollower::SetPaused(), PlayerBase::SetUnitScene(), ChargeMovement::SetWalkingAnimation(), MeleeMovement::SetWalkingAnimation(), Trigger(), TripMine::TripMine(), PassiveMovement::Update(), LurkerProjectile::Update(), CirclingMovement::Update(), TripMine::Update(), TargetMovement::Update(), RangedMovement::Update(), TowerFlowerSkill::Update(), BlinkSkill::Update(), FixedPathFollower::Update(), ChargeMovement::Update(), JumpStrike::Update(), SpewSkill::Update(), Gib::Update(), MeleeMovement::Update(), and Player::Update().
     {
         if (m_numDirs == -1)
             return m_anim;
         if (!m_capped)
             return m_anim + int((dir / (2 * PI) * m_numDirs - 0.5) + 1 + m_numDirs) % m_numDirs;
         dir -= m_capStart;
         if (dir < 0)
             dir = 0 - dir;
         if (dir > m_capSpan)
             dir = m_capSpan + (m_capSpan - dir);
         return m_anim + int((dir / (m_capSpan) * m_numDirs) + m_numDirs) % m_numDirs;
     }
Member Data Documentation
m_anim
string AnimString::m_anim private
Definition at line 3 of file AnimString.as.
Referenced by AnimString(), GetSceneName(), and TripMine::Update().
m_capped
bool AnimString::m_capped private
Definition at line 6 of file AnimString.as.
Referenced by AnimString(), and GetSceneName().
m_capSpan
float AnimString::m_capSpan private
Definition at line 8 of file AnimString.as.
Referenced by AnimString(), and GetSceneName().
m_capStart
float AnimString::m_capStart private
Definition at line 7 of file AnimString.as.
Referenced by AnimString(), and GetSceneName().
m_flipped
bool AnimString::m_flipped private
Definition at line 5 of file AnimString.as.
m_numDirs
int AnimString::m_numDirs private
Definition at line 4 of file AnimString.as.
Referenced by AnimString(), and GetSceneName().
The documentation for this class was generated from the following file:
scripts/Behaviors/AnimString.as