HoHDocs: GiveKey Class Reference
GiveKey Class Reference
Private Member Functions
GiveKey (UnitPtr unit, SValue &params)
void SetWeaponInformation (uint weapon)
bool Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
bool CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
Private Attributes
int m_lock
int m_amount
Detailed Description
Definition at line 1 of file GiveKey.as.
Constructor & Destructor Documentation
GiveKey()
GiveKey::GiveKey (UnitPtr unit, SValue & params) inline private
Definition at line 6 of file GiveKey.as.
References m_amount, m_lock, and unit.
     {
         m_lock = GetParamInt(unit, params, "lock");
         m_amount = GetParamInt(unit, params, "amount", false, 1);
     }
Member Function Documentation
Apply()
bool GiveKey::Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk) inline private
Definition at line 14 of file GiveKey.as.
References AddFloatingText(), CanApply(), m_amount, m_lock, NetGiveKeyImpl(), and Pickup.
     {
         if (!CanApply(owner, target, pos, dir, intensity))
             return false;
         auto player = cast<Player>(target.GetScriptBehavior());
         if (player !is null)
         {
             int amount = int(m_amount * player.m_record.GetModifiers().KeyGainScale(player));
             NetGiveKeyImpl(m_lock, amount, player);
             string strKeyValue = "";
             if (amount == 1)
                 strKeyValue = Resources::GetString(".item.key");
             else
             {
                 dictionary params = { { "num", amount } };
                 strKeyValue = Resources::GetString(".item.key.plural", params);
             }
             AddFloatingText(FloatingTextType::Pickup, strKeyValue, player.m_unit.GetPosition());
             (Network::Message("PlayerGiveKey") << m_lock << amount).SendToAll();
         }
         return true;
     }
CanApply()
bool GiveKey::CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) inline override private
Definition at line 42 of file GiveKey.as.
Referenced by Apply().
     {
         return true;
     }
SetWeaponInformation()
void GiveKey::SetWeaponInformation (uint weapon) inline private
Definition at line 12 of file GiveKey.as.
 {}
Member Data Documentation
m_amount
int GiveKey::m_amount private
Definition at line 4 of file GiveKey.as.
Referenced by Apply(), and GiveKey().
m_lock
int GiveKey::m_lock private
Definition at line 3 of file GiveKey.as.
Referenced by Apply(), and GiveKey().
The documentation for this class was generated from the following file:
scripts/Behaviors/Effects/GiveKey.as