HoHDocs: GiveGold Class Reference
GiveGold Class Reference
Private Member Functions
GiveGold (UnitPtr unit, SValue &params)
void SetWeaponInformation (uint weapon)
bool Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
bool CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
Private Attributes
int m_amount
bool m_pickup
Detailed Description
Definition at line 1 of file GiveGold.as.
Constructor & Destructor Documentation
GiveGold()
GiveGold::GiveGold (UnitPtr unit, SValue & params) inline private
Definition at line 6 of file GiveGold.as.
References m_amount, m_pickup, and unit.
     {
         m_amount = GetParamInt(unit, params, "amount");
         m_pickup = GetParamBool(unit, params, "pickup", false, false);
     }
Member Function Documentation
Apply()
bool GiveGold::Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk) inline private
Definition at line 14 of file GiveGold.as.
References CanApply(), GetLocalPlayer(), GiveGoldImpl(), m_amount, and m_pickup.
     {
         if (!CanApply(owner, target, pos, dir, intensity))
             return false;
         if (m_pickup)
             GiveGoldImpl(m_amount, GetLocalPlayer());
         else
             GiveGoldImpl(m_amount, cast<Player>(target.GetScriptBehavior()));
         return true;
     }
CanApply()
bool GiveGold::CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) inline override private
Definition at line 27 of file GiveGold.as.
Referenced by Apply().
     {
         return true;
     }
SetWeaponInformation()
void GiveGold::SetWeaponInformation (uint weapon) inline private
Definition at line 12 of file GiveGold.as.
 {}
Member Data Documentation
m_amount
int GiveGold::m_amount private
Definition at line 3 of file GiveGold.as.
Referenced by Apply(), and GiveGold().
m_pickup
bool GiveGold::m_pickup private
Definition at line 4 of file GiveGold.as.
Referenced by Apply(), and GiveGold().
The documentation for this class was generated from the following file:
scripts/Behaviors/Effects/GiveGold.as