HoHDocs: Heal Class Reference
Heal Class Reference
Private Member Functions
Heal (UnitPtr unit, SValue &params)
void SetWeaponInformation (uint weapon)
int GetAmount (float intensity, Actor@ actor)
bool Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
bool CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
Private Attributes
int m_heal
bool m_pickup
uint m_weaponInfo
Detailed Description
Definition at line 1 of file Heal.as.
Constructor & Destructor Documentation
Heal()
Heal::Heal (UnitPtr unit, SValue & params) inline private
Definition at line 7 of file Heal.as.
References m_heal, m_pickup, and unit.
     {
         m_heal = GetParamInt(unit, params, "heal");
         m_pickup = GetParamBool(unit, params, "pickup", false, false);
     }
Member Function Documentation
Apply()
bool Heal::Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk) inline private
Definition at line 40 of file Heal.as.
References Stats::Add(), CanApply(), GetAmount(), Actor::Heal(), and m_pickup.
     {
         if (!CanApply(owner, target, pos, dir, intensity))
             return false;
         Actor@ actor = cast<Actor>(target.GetScriptBehavior());
         int amount = GetAmount(intensity, actor);
         if (m_pickup)
         {
             auto player = cast<PlayerBase>(actor);
             if (player !is null)
                 Stats::Add("amount-healed-pickups", amount, player.m_record);
         }
         actor.Heal(amount);
         return true;
     }
CanApply()
bool Heal::CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) inline override private
Definition at line 59 of file Heal.as.
References GetAmount(), and Actor::GetHealth().
Referenced by Apply().
     {
         if (!target.IsValid())
             return false;
         Actor@ actor = cast<Actor>(target.GetScriptBehavior());
         if (actor is null)
             return false;
         if (actor.GetHealth() >= 1.0)
             return false;
         if (GetAmount(intensity, actor) <= 0)
             return false;
         return true;
     }
GetAmount()
int Heal::GetAmount (float intensity, Actor@ actor) inline private
Definition at line 18 of file Heal.as.
References Fountain::HasEffect(), m_heal, and m_pickup.
Referenced by Apply(), and CanApply().
     {
         float ret = float(m_heal);
         ret *= intensity;
         if (m_pickup)
         {
             auto player = cast<Player>(actor);
             if (player !is null)
                 ret *= player.m_record.GetModifiers().HealthGainScale(player);
             if (Fountain::HasEffect("amazing_pickups"))
                 ret *= 5;
             if (Fountain::HasEffect("bad_pickups"))
                 ret *= 0.5f;
         }
         return int(ret);
     }
SetWeaponInformation()
void Heal::SetWeaponInformation (uint weapon) inline private
Definition at line 13 of file Heal.as.
References m_weaponInfo.
     {
         m_weaponInfo = weapon;
     }
Member Data Documentation
m_heal
int Heal::m_heal private
Definition at line 3 of file Heal.as.
Referenced by GetAmount(), and Heal().
m_pickup
bool Heal::m_pickup private
Definition at line 4 of file Heal.as.
Referenced by Apply(), GetAmount(), and Heal().
m_weaponInfo
uint Heal::m_weaponInfo private
Definition at line 5 of file Heal.as.
Referenced by SetWeaponInformation().
The documentation for this class was generated from the following file:
scripts/Behaviors/Effects/Heal.as