HoHDocs: GiveLives Class Reference
GiveLives Class Reference
Private Member Functions
GiveLives (UnitPtr unit, SValue &params)
void SetWeaponInformation (uint weapon)
bool Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
bool CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
Private Attributes
int m_lives
Detailed Description
Definition at line 1 of file GiveLives.as.
Constructor & Destructor Documentation
GiveLives()
GiveLives::GiveLives (UnitPtr unit, SValue & params) inline private
Definition at line 5 of file GiveLives.as.
References m_lives, and unit.
     {
         m_lives = GetParamInt(unit, params, "lives", false, 1);
     }
Member Function Documentation
Apply()
bool GiveLives::Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk) inline private
Definition at line 12 of file GiveLives.as.
References CanApply(), g_gameMode, GetHUD(), m_lives, and HUD::SetExtraLife().
     {
         if (!CanApply(owner, target, pos, dir, intensity))
             return false;
         auto gm = cast<BaseGameMode>(g_gameMode);
         gm.m_extraLives += m_lives;
         (Network::Message("ExtraLives") << gm.m_extraLives).SendToAll();
         GetHUD().SetExtraLife();
         return true;
     }
CanApply()
bool GiveLives::CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) inline override private
Definition at line 26 of file GiveLives.as.
References g_gameMode.
Referenced by Apply().
     {
         if (!target.IsValid())
             return false;
         if (cast<BaseGameMode>(g_gameMode) is null)
             return false;
         if (cast<Player>(target.GetScriptBehavior()) is null)
             return false;
         return true;
     }
SetWeaponInformation()
void GiveLives::SetWeaponInformation (uint weapon) inline private
Definition at line 10 of file GiveLives.as.
 {}
Member Data Documentation
m_lives
int GiveLives::m_lives private
Definition at line 3 of file GiveLives.as.
Referenced by Apply(), and GiveLives().
The documentation for this class was generated from the following file:
scripts/Behaviors/Effects/GiveLives.as