HoHDocs: SetFlag Class Reference
SetFlag Class Reference
Private Member Functions
SetFlag (UnitPtr unit, SValue &params)
void SetWeaponInformation (uint weapon)
bool NeedNetParams ()
bool DoAction (SValueBuilder@ builder, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity)
bool NetDoAction (SValue@ param, Actor@ owner, vec2 pos, vec2 dir)
bool Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
bool CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
void Do ()
void Update (int dt, int cooldown)
Private Attributes
string m_flag
bool m_value
bool m_persistent
Detailed Description
Definition at line 1 of file SetFlag.as.
Constructor & Destructor Documentation
SetFlag()
SetFlag::SetFlag (UnitPtr unit, SValue & params) inline private
Definition at line 7 of file SetFlag.as.
References m_flag, m_persistent, m_value, and unit.
     {
         m_flag = GetParamString(unit, params, "flag");
         m_value = GetParamBool(unit, params, "value");
         m_persistent = GetParamBool(unit, params, "persistent", false);
     }
Member Function Documentation
Apply()
bool SetFlag::Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk) inline private
Definition at line 29 of file SetFlag.as.
References CanApply(), Do(), m_flag, m_persistent, and m_value.
     {
         if (!CanApply(owner, target, pos, dir, intensity))
             return false;
         Do();
         (Network::Message("SyncFlag") << m_flag << m_value << m_persistent).SendToAll();
         return true;
     }
CanApply()
bool SetFlag::CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) inline override private
Definition at line 40 of file SetFlag.as.
Referenced by Apply().
     {
         if (cast<Player>(target.GetScriptBehavior()) is null)
             return false;
         return true;
     }
Do()
void SetFlag::Do () inline private
Definition at line 48 of file SetFlag.as.
References g_flags, Level, m_flag, m_persistent, m_value, and Run.
Referenced by Apply(), DoAction(), and NetDoAction().
     {
         if (!m_value)
             g_flags.Delete(m_flag);
         else
             g_flags.Set(m_flag, m_persistent ? FlagState::Run : FlagState::Level);
     }
DoAction()
bool SetFlag::DoAction (SValueBuilder@ builder, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity) inline private
Definition at line 17 of file SetFlag.as.
References Do().
     {
         Do();
         return true;
     }
NeedNetParams()
bool SetFlag::NeedNetParams () inline private
Definition at line 15 of file SetFlag.as.
 { return false; }
NetDoAction()
bool SetFlag::NetDoAction (SValue@ param, Actor@ owner, vec2 pos, vec2 dir) inline private
Definition at line 23 of file SetFlag.as.
References Do().
     {
         Do();
         return true;
     }
SetWeaponInformation()
void SetFlag::SetWeaponInformation (uint weapon) inline private
Definition at line 14 of file SetFlag.as.
 {}
Update()
void SetFlag::Update (int dt, int cooldown) inline private
Definition at line 57 of file SetFlag.as.
     {
     }
Member Data Documentation
m_flag
string SetFlag::m_flag private
Definition at line 3 of file SetFlag.as.
Referenced by Apply(), Do(), and SetFlag().
m_persistent
bool SetFlag::m_persistent private
Definition at line 5 of file SetFlag.as.
Referenced by Apply(), Do(), and SetFlag().
m_value
bool SetFlag::m_value private
Definition at line 4 of file SetFlag.as.
Referenced by Apply(), Do(), and SetFlag().
The documentation for this class was generated from the following file:
scripts/Behaviors/Effects/SetFlag.as