HoHDocs: SpawnTilesetEffect Class Reference
SpawnTilesetEffect Class Reference
Private Member Functions
SpawnTilesetEffect (UnitPtr unit, SValue &params)
bool NeedNetParams ()
void SetWeaponInformation (uint weapon)
bool DoAction (SValueBuilder@ builder, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity)
bool NetDoAction (SValue@ param, Actor@ owner, vec2 pos, vec2 dir)
bool Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
bool CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
void Do (vec2 pos)
void Update (int dt, int cooldown)
Private Attributes
string m_effectName
UnitScene m_effectFallback
Detailed Description
Definition at line 1 of file SpawnTilesetEffect.as.
Constructor & Destructor Documentation
SpawnTilesetEffect()
SpawnTilesetEffect::SpawnTilesetEffect (UnitPtr unit, SValue & params) inline private
Definition at line 6 of file SpawnTilesetEffect.as.
References Fountain::GetEffect(), m_effectFallback, m_effectName, and unit.
     {
         m_effectName = GetParamString(unit, params, "name");
         @m_effectFallback = Resources::GetEffect(GetParamString(unit, params, "fallback"));
     }
Member Function Documentation
Apply()
bool SpawnTilesetEffect::Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk) inline private
Definition at line 27 of file SpawnTilesetEffect.as.
References Do().
     {
         Do(pos);
         return true;
     }
CanApply()
bool SpawnTilesetEffect::CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) inline override private
Definition at line 33 of file SpawnTilesetEffect.as.
     {
         return true;
     }
Do()
void SpawnTilesetEffect::Do (vec2 pos) inline private
Definition at line 38 of file SpawnTilesetEffect.as.
References effect, g_scene, Fountain::GetEffect(), m_effectFallback, m_effectName, and PlayEffect().
Referenced by Apply(), DoAction(), and NetDoAction().
     {
         array<Tileset@>@ tilesets = g_scene.FetchTilesets(pos);
         for (int i = tilesets.length() - 1; i >= 0; i--)
         {
             auto tsd = tilesets[i].GetData();
             if (tsd is null)
                 continue;
             SValue@ svEffect = tsd.GetDictionaryEntry(m_effectName);
             if (svEffect is null || svEffect.GetType() != SValueType::String)
                 continue;
             auto effect = Resources::GetEffect(svEffect.GetString());
             if (effect is null)
                 break;
             PlayEffect(effect, pos);
             return;
         }
         PlayEffect(m_effectFallback, pos);
     }
DoAction()
bool SpawnTilesetEffect::DoAction (SValueBuilder@ builder, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity) inline private
Definition at line 15 of file SpawnTilesetEffect.as.
References Do().
     {
         Do(pos);
         return true;
     }
NeedNetParams()
bool SpawnTilesetEffect::NeedNetParams () inline private
Definition at line 12 of file SpawnTilesetEffect.as.
 { return false; }
NetDoAction()
bool SpawnTilesetEffect::NetDoAction (SValue@ param, Actor@ owner, vec2 pos, vec2 dir) inline private
Definition at line 21 of file SpawnTilesetEffect.as.
References Do().
     {
         Do(pos);
         return true;
     }
SetWeaponInformation()
void SpawnTilesetEffect::SetWeaponInformation (uint weapon) inline private
Definition at line 13 of file SpawnTilesetEffect.as.
 {}
Update()
void SpawnTilesetEffect::Update (int dt, int cooldown) inline private
Definition at line 61 of file SpawnTilesetEffect.as.
     {
     }
Member Data Documentation
m_effectFallback
UnitScene SpawnTilesetEffect::m_effectFallback private
Definition at line 4 of file SpawnTilesetEffect.as.
Referenced by Do(), and SpawnTilesetEffect().
m_effectName
string SpawnTilesetEffect::m_effectName private
Definition at line 3 of file SpawnTilesetEffect.as.
Referenced by Do(), and SpawnTilesetEffect().
The documentation for this class was generated from the following file:
scripts/Behaviors/Effects/SpawnTilesetEffect.as