HoHDocs: Door Class Reference
Door Class Reference
Private Member Functions
Door (UnitPtr unit, SValue &params)
void Use (PlayerBase@ player) override
void NetUse (PlayerHusk@ player) override
Detailed Description
Definition at line 1 of file Door.as.
Constructor & Destructor Documentation
Door()
Door::Door (UnitPtr unit, SValue & params) inline private
Definition at line 3 of file Door.as.
References unit.
     {
         super(unit, params);
     }
Member Function Documentation
NetUse()
void Door::NetUse (PlayerHusk@ player) inline override private
Definition at line 33 of file Door.as.
References GetLocalPlayer(), and Chest::NetUse().
     {
         Chest::NetUse(player);
         auto localPlayer = GetLocalPlayer();
         if (localPlayer !is null && localPlayer.FindUsable(this) != -1)
             localPlayer.RemoveUsable(this);
     }
Use()
void Door::Use (PlayerBase@ player) inline override private
Definition at line 8 of file Door.as.
References AddFloatingText(), Chest::m_lock, Chest::m_openSnd, PlayerBase::m_record, Chest::m_unit, Pickup, and PlaySound3D().
     {
         if (m_unit.IsDestroyed() || !m_unit.IsValid())
             return;
         if (m_lock >= 0)
         {
             if (player.m_record.keys[m_lock] <= 0 && cast<PlayerHusk>(player) is null)
             {
                 AddFloatingText(FloatingTextType::Pickup, Resources::GetString(".hud.nokey"), player.m_unit.GetPosition());
                 print("No key!");
                 return;
             }
             player.m_record.keys[m_lock]--;
         }
         auto plr = cast<Player>(player);
         if (plr !is null)
             plr.RemoveUsable(this);
         m_unit.SetUnitScene("open", true);
         PlaySound3D(m_openSnd, m_unit.GetPosition());
     }
The documentation for this class was generated from the following file:
scripts/Behaviors/Items/Door.as