HoHDocs: TavernBarrel Class Reference
TavernBarrel Class Reference
Private Member Functions
TavernBarrel (UnitPtr unit, SValue &params)
void SetQualityScene ()
void Initialize (ActorItemQuality quality)
void Initialize (TavernDrink@ drink)
SValue Save ()
void Load (SValue@ data)
void Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther)
void EndCollision (UnitPtr unit, Fixture@ fxSelf, Fixture@ fxOther)
UnitPtr GetUseUnit ()
bool CanUse (PlayerBase@ player)
void Use (PlayerBase@ player)
void NetUse (PlayerHusk@ player)
UsableIcon GetIcon (Player@ player)
int UsePriority (IUsable@ other)
Private Attributes
UnitPtr m_unit
TavernDrink m_drink
Detailed Description
Definition at line 1 of file TavernBarrel.as.
Constructor & Destructor Documentation
TavernBarrel()
TavernBarrel::TavernBarrel (UnitPtr unit, SValue & params) inline private
Definition at line 7 of file TavernBarrel.as.
References m_unit, and unit.
     {
         m_unit = unit;
     }
Member Function Documentation
CanUse()
bool TavernBarrel::CanUse (PlayerBase@ player) inline private
Definition at line 107 of file TavernBarrel.as.
     {
         return true;
     }
Collide()
void TavernBarrel::Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther) inline private
Definition at line 82 of file TavernBarrel.as.
     {
         Player@ player = cast<Player>(unit.GetScriptBehavior());
         if (player is null)
             return;
         if (fxSelf.IsSensor())
             player.AddUsable(this);
     }
EndCollision()
void TavernBarrel::EndCollision (UnitPtr unit, Fixture@ fxSelf, Fixture@ fxOther) inline private
Definition at line 92 of file TavernBarrel.as.
References Player::RemoveUsable(), and unit.
     {
         Player@ player = cast<Player>(unit.GetScriptBehavior());
         if (player is null)
             return;
         if (fxSelf.IsSensor())
             player.RemoveUsable(this);
     }
GetIcon()
UsableIcon TavernBarrel::GetIcon (Player@ player) inline private
Definition at line 122 of file TavernBarrel.as.
     {
         return UsableIcon::Generic;
     }
GetUseUnit()
UnitPtr TavernBarrel::GetUseUnit () inline private
Definition at line 102 of file TavernBarrel.as.
     {
         return m_unit;
     }
Initialize() [1/2]
void TavernBarrel::Initialize (ActorItemQuality quality) inline private
Definition at line 26 of file TavernBarrel.as.
References g_ngp, GetTavernDrink(), TavernDrink::localCount, localCount, and quality.
Referenced by Load().
     {
         array<TavernDrink@> drinks;
         for (int i = 0; i < (3 + g_ngp); i++)
             drinks.insertLast(GetTavernDrink(quality));
         TavernDrink@ bestDrink = null;
         for (uint i = 0; i < drinks.length(); i++)
         {
             if (bestDrink is null || drinks[i].localCount < bestDrink.localCount)
                 @bestDrink = drinks[i];
         }
         if (bestDrink !is null)
             Initialize(bestDrink);
         else
             Initialize(GetTavernDrink(quality));
     }
Initialize() [2/2]
void TavernBarrel::Initialize (TavernDrink@ drink) inline private
Definition at line 45 of file TavernBarrel.as.
References m_drink, m_unit, and SetQualityScene().
     {
         @m_drink = drink;
         if (m_drink is null)
         {
             PrintError("Barrel was initialized with a null drink!");
             m_unit.Destroy();
             return;
         }
         SetQualityScene();
     }
Load()
void TavernBarrel::Load (SValue@ data) inline private
Definition at line 67 of file TavernBarrel.as.
References GetTavernDrink(), Initialize(), and m_unit.
     {
         uint drinkId = uint(data.GetInteger());
         TavernDrink@ drink = GetTavernDrink(drinkId);
         if (drink is null)
         {
             PrintError("Couldn't find drink with ID " + drinkId);
             m_unit.Destroy();
             return;
         }
         Initialize(drink);
     }
NetUse()
void TavernBarrel::NetUse (PlayerHusk@ player) inline private
Definition at line 118 of file TavernBarrel.as.
     {
     }
Save()
SValue TavernBarrel::Save () inline private
Definition at line 57 of file TavernBarrel.as.
References TavernDrink::idHash, and m_drink.
     {
         if (m_drink is null)
             return null;
         SValueBuilder sval;
         sval.PushInteger(m_drink.idHash);
         return sval.Build();
     }
SetQualityScene()
void TavernBarrel::SetQualityScene () inline private
Definition at line 12 of file TavernBarrel.as.
References Common, Epic, Legendary, m_drink, m_unit, TavernDrink::quality, Rare, and Uncommon.
Referenced by Initialize().
     {
         if (m_drink.quality == ActorItemQuality::Common)
             m_unit.SetUnitScene("common", false);
         else if (m_drink.quality == ActorItemQuality::Uncommon)
             m_unit.SetUnitScene("uncommon", false);
         else if (m_drink.quality == ActorItemQuality::Rare)
             m_unit.SetUnitScene("rare", false);
         else if (m_drink.quality == ActorItemQuality::Epic)
             m_unit.SetUnitScene("epic", false);
         else if (m_drink.quality == ActorItemQuality::Legendary)
             m_unit.SetUnitScene("legendary", false);
     }
Use()
void TavernBarrel::Use (PlayerBase@ player) inline private
Definition at line 112 of file TavernBarrel.as.
References GiveTavernBarrelImpl(), m_drink, and m_unit.
     {
         m_unit.Destroy();
         GiveTavernBarrelImpl(m_drink, player, true);
     }
UsePriority()
int TavernBarrel::UsePriority (IUsable@ other) inline private
Definition at line 127 of file TavernBarrel.as.
 { return 0; }
Member Data Documentation
m_drink
TavernDrink TavernBarrel::m_drink private
Definition at line 5 of file TavernBarrel.as.
Referenced by Initialize(), Save(), SetQualityScene(), and Use().
m_unit
UnitPtr TavernBarrel::m_unit private
Definition at line 3 of file TavernBarrel.as.
Referenced by Initialize(), Load(), SetQualityScene(), TavernBarrel(), and Use().
The documentation for this class was generated from the following file:
scripts/Behaviors/Items/TavernBarrel.as