HoHDocs: ForgeBlueprint Class Reference
ForgeBlueprint Class Reference
Private Member Functions
ForgeBlueprint (UnitPtr unit, SValue &params)
void Initialize (ActorItem@ item)
SValue Save ()
void Load (SValue@ data)
void Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther)
void EndCollision (UnitPtr unit, Fixture@ fxSelf, Fixture@ fxOther)
UnitPtr GetUseUnit ()
bool CanUse (PlayerBase@ player)
void Use (PlayerBase@ player)
void NetUse (PlayerHusk@ player)
UsableIcon GetIcon (Player@ player)
int UsePriority (IUsable@ other)
Private Attributes
UnitPtr m_unit
ActorItem m_item
Detailed Description
Definition at line 1 of file ForgeBlueprint.as.
Constructor & Destructor Documentation
ForgeBlueprint()
ForgeBlueprint::ForgeBlueprint (UnitPtr unit, SValue & params) inline private
Definition at line 7 of file ForgeBlueprint.as.
References m_unit, and unit.
     {
         m_unit = unit;
     }
Member Function Documentation
CanUse()
bool ForgeBlueprint::CanUse (PlayerBase@ player) inline private
Definition at line 85 of file ForgeBlueprint.as.
     {
         return true;
     }
Collide()
void ForgeBlueprint::Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther) inline private
Definition at line 60 of file ForgeBlueprint.as.
References Player::AddUsable(), and unit.
     {
         Player@ player = cast<Player>(unit.GetScriptBehavior());
         if (player is null)
             return;
         if (fxSelf.IsSensor())
             player.AddUsable(this);
     }
EndCollision()
void ForgeBlueprint::EndCollision (UnitPtr unit, Fixture@ fxSelf, Fixture@ fxOther) inline private
Definition at line 70 of file ForgeBlueprint.as.
References Player::RemoveUsable(), and unit.
     {
         Player@ player = cast<Player>(unit.GetScriptBehavior());
         if (player is null)
             return;
         if (fxSelf.IsSensor())
             player.RemoveUsable(this);
     }
GetIcon()
UsableIcon ForgeBlueprint::GetIcon (Player@ player) inline private
Definition at line 100 of file ForgeBlueprint.as.
References Generic.
     {
         return UsableIcon::Generic;
     }
GetUseUnit()
UnitPtr ForgeBlueprint::GetUseUnit () inline private
Definition at line 80 of file ForgeBlueprint.as.
References m_unit.
     {
         return m_unit;
     }
Initialize()
void ForgeBlueprint::Initialize (ActorItem@ item) inline private
Definition at line 12 of file ForgeBlueprint.as.
References Common, Epic, Legendary, m_item, m_unit, Rare, ScriptSprite(), and Uncommon.
Referenced by Load().
     {
         if (item is null)
             return;
         @m_item = item;
         UnitScene@ scrollScene;
         if (item.quality == ActorItemQuality::Common)
             @scrollScene = m_unit.GetUnitScene("common");
         else if (item.quality == ActorItemQuality::Uncommon)
             @scrollScene = m_unit.GetUnitScene("uncommon");
         else if (item.quality == ActorItemQuality::Rare)
             @scrollScene = m_unit.GetUnitScene("rare");
         else if (item.quality == ActorItemQuality::Epic)
             @scrollScene = m_unit.GetUnitScene("epic");
         else if (item.quality == ActorItemQuality::Legendary)
             @scrollScene = m_unit.GetUnitScene("legendary");
         ScriptSprite@ sprite = m_item.icon;
         array<vec4> frames;
         for (uint i = 0; i < sprite.m_frames.length(); i++)
             frames.insertLast(sprite.m_frames[i].frame);
         CustomUnitScene unitScene;
         unitScene.AddScene(scrollScene, 0, vec2(), 0, 0);
         unitScene.AddSprite(CustomUnitSprite(vec2(6, 6), sprite.m_texture, Resources::GetMaterial("system/default.mats:proj-prop"), frames, { 100 }, true, 0), 0, vec2(0, -1), 0, 0);
         m_unit.SetUnitScene(unitScene, false);
     }
Load()
void ForgeBlueprint::Load (SValue@ data) inline private
Definition at line 55 of file ForgeBlueprint.as.
References g_items, ActorItems::GetItem(), and Initialize().
     {
         Initialize(g_items.GetItem(uint(data.GetInteger())));
     }
NetUse()
void ForgeBlueprint::NetUse (PlayerHusk@ player) inline private
Definition at line 96 of file ForgeBlueprint.as.
     {
     }
Save()
SValue ForgeBlueprint::Save () inline private
Definition at line 45 of file ForgeBlueprint.as.
References m_item.
     {
         if (m_item is null)
             return null;
         SValueBuilder sval;
         sval.PushInteger(m_item.idHash);
         return sval.Build();
     }
Use()
void ForgeBlueprint::Use (PlayerBase@ player) inline private
Definition at line 90 of file ForgeBlueprint.as.
References GiveForgeBlueprintImpl(), m_item, and m_unit.
     {
         m_unit.Destroy();
         GiveForgeBlueprintImpl(m_item, player, true);
     }
UsePriority()
int ForgeBlueprint::UsePriority (IUsable@ other) inline private
Definition at line 105 of file ForgeBlueprint.as.
 { return 0; }
Member Data Documentation
m_item
ActorItem ForgeBlueprint::m_item private
Definition at line 5 of file ForgeBlueprint.as.
Referenced by Initialize(), Save(), and Use().
m_unit
UnitPtr ForgeBlueprint::m_unit private
Definition at line 3 of file ForgeBlueprint.as.
Referenced by ForgeBlueprint(), GetUseUnit(), Initialize(), and Use().
The documentation for this class was generated from the following file:
scripts/Behaviors/Items/ForgeBlueprint.as