HoHDocs: Pickup Class Reference
Pickup Class Reference
Private Member Functions
Pickup (UnitPtr unit, SValue &params)
SValue Save ()
void PostLoad (SValue@ data)
void Hide ()
void Show ()
bool Picked (UnitPtr unit, bool force=false)
bool NetPicked (UnitPtr unit)
void PickedLocalFeedback ()
void Collide (UnitPtr unit, vec2 pos, vec2 normal)
void CallbackPicked (UnitPtr picker)
void Update (int dt)
void Destroy ()
Private Attributes
UnitPtr m_unit
bool m_bounce
bool m_plrOnly
SoundEvent m_sound
bool m_global
bool m_secure
bool m_shouldDestroy
% if MOD_ACHIEVEMENT_CHECKS int m_achievementGroup
% endif % if MOD_PICKUP_RESPAWN int m_respawnTime
int m_toRespawn
% endif array< IEffect@> m_effects
bool m_visible
array< WorldScript::UnitPickedUpTrigger@> m_callbacks
Detailed Description
Definition at line 1 of file Pickup.as.
Constructor & Destructor Documentation
Pickup()
Pickup::Pickup (UnitPtr unit, SValue & params) inline private
Definition at line 28 of file Pickup.as.
References g_totalPickups, g_totalPickupsTotal, Fountain::HasEffect(), Hide(), IsNetsyncedExistance(), LoadEffects(), m_achievementGroup, m_bounce, m_effects, m_global, m_plrOnly, m_respawnTime, m_secure, m_shouldDestroy, m_sound, m_unit, m_visible, and unit.
     {
         m_unit = unit;
         @m_effects = LoadEffects(unit, params);
         m_bounce = GetParamBool(unit, params, "bounce", false, true);
         @m_sound = Resources::GetSoundEvent(GetParamString(unit, params, "sound", false));
         m_plrOnly = GetParamBool(unit, params, "player-only", false, true);
         m_global = GetParamBool(unit, params, "global", false, false);
         m_secure = GetParamBool(unit, params, "secure", false, false);
 %if MOD_ACHIEVEMENT_CHECKS
         m_achievementGroup = GetParamInt(unit, params, "achievement-group", false, -1);
 %endif
         if (m_secure)
             m_global = true;
         m_shouldDestroy = !IsNetsyncedExistance(m_unit.GetUnitProducer().GetNetSyncMode()) || (m_global && Network::IsServer());
 %if MOD_PICKUP_RESPAWN
         m_respawnTime = GetParamInt(unit, params, "respawn-time", false, -1);
 %else
         m_unit.SetUpdateDistanceLimit(300);
 %endif
         g_totalPickups++;
         g_totalPickupsTotal++;
         m_visible = true;
         bool isOre = GetParamBool(unit, params, "is-ore", false, false);
         if (isOre && Fountain::HasEffect("no_ore"))
             Hide();
     }
Member Function Documentation
CallbackPicked()
void Pickup::CallbackPicked (UnitPtr picker) inline private
Definition at line 217 of file Pickup.as.
References m_callbacks, m_unit, and UnitHandler::UnitPicked().
Referenced by Collide().
     {
         for (uint i = 0; i < m_callbacks.length(); i++)
             m_callbacks[i].UnitPicked(m_unit, picker);
     }
Collide()
void Pickup::Collide (UnitPtr unit, vec2 pos, vec2 normal) inline private
Definition at line 171 of file Pickup.as.
References CallbackPicked(), CanApplyEffects(), Player::IsDead(), m_callbacks, m_effects, m_global, m_plrOnly, m_secure, m_unit, m_visible, None, Picked(), PickedLocalFeedback(), unit, and xy().
     {
         if (!m_visible)
             return;
         ref@ b = unit.GetScriptBehavior();
         Player@ a = cast<Player>(b);
         if ((a is null && m_plrOnly) || (a !is null && a.m_record.IsDead()))
             return;
         bool picked = false;
         if (!m_secure || Network::IsServer())
         {
             if (Picked(unit))
             {
                 PickedLocalFeedback();
                 picked = true;
                 if (m_global)
                     (Network::Message("UnitPicked") << m_unit << unit).SendToAll();
                 if (a !is null)
                     (Network::Message("PlayerPickups") << a.m_record.pickups << a.m_record.pickupsTotal).SendToAll();
             }
         }
         else if (CanApplyEffects(m_effects, null, unit, xy(m_unit.GetPosition()), vec2(0, 0), 1.0))
         {
             PickedLocalFeedback();
             picked = true;
             (Network::Message("UnitPickSecure") << m_unit << unit).SendToHost();
         }
         if (picked && m_callbacks.length() > 0)
         {
             if (m_unit.GetUnitProducer().GetNetSyncMode() != NetSyncMode::None)
             {
                 if (!Network::IsServer())
                     (Network::Message("UnitPickCallback") << m_unit << unit).SendToHost();
                 else
                     CallbackPicked(unit);
             }
         }
     }
Destroy()
void Pickup::Destroy () inline private
Definition at line 256 of file Pickup.as.
References m_shouldDestroy, and m_unit.
Referenced by Update().
     {
         if (m_shouldDestroy)
             m_unit.Destroy();
     }
Hide()
void Pickup::Hide () inline private
Definition at line 96 of file Pickup.as.
References m_respawnTime, m_toRespawn, m_unit, and m_visible.
Referenced by Picked(), PickedLocalFeedback(), Pickup(), and PostLoad().
     {
         if (!m_visible)
             return;
         m_visible = false;
         m_unit.SetHidden(true);
         m_unit.SetShouldCollide(false);
 %if MOD_PICKUP_RESPAWN
         m_toRespawn = m_respawnTime;
 %endif
     }
NetPicked()
bool Pickup::NetPicked (UnitPtr unit) inline private
Definition at line 154 of file Pickup.as.
References m_visible, Picked(), PickedLocalFeedback(), and unit.
     {
         if (!m_visible && Network::IsServer())
             return false;
         Picked(unit, true);
         PickedLocalFeedback();
         return true;
     }
Picked()
bool Pickup::Picked (UnitPtr unit, bool force = false) inline private
Definition at line 121 of file Pickup.as.
References ApplyEffects(), force, Hide(), m_effects, m_global, m_sound, m_unit, m_visible, PlaySound3D(), unit, and xy().
Referenced by Collide(), and NetPicked().
     {
         if (!m_visible && !force)
             return false;
         if (ApplyEffects(m_effects, null, unit, xy(m_unit.GetPosition()), vec2(0, 0), 1.0, false))
         {
             if (m_global)
             {
                 if (cast<PlayerBase>(unit.GetScriptBehavior()) !is null)
                     Hide();
             }
             else
             {
                 if (cast<Player>(unit.GetScriptBehavior()) !is null)
                     Hide();
             }
             Player@ plr = cast<Player>(unit.GetScriptBehavior());
             if (plr !is null)
             {
                 plr.m_record.pickups++;
                 plr.m_record.pickupsTotal++;
             }
             else
                 PlaySound3D(m_sound, m_unit.GetPosition());
             return true;
         }
         return false;
     }
PickedLocalFeedback()
void Pickup::PickedLocalFeedback () inline private
Definition at line 165 of file Pickup.as.
References Hide(), m_sound, m_unit, and PlaySound3D().
Referenced by Collide(), and NetPicked().
     {
         PlaySound3D(m_sound, m_unit.GetPosition());
         Hide();
     }
PostLoad()
void Pickup::PostLoad (SValue@ data) inline private
Definition at line 78 of file Pickup.as.
References Hide(), and m_toRespawn.
     {
         auto visible = data.GetDictionaryEntry("visible");
         if (visible !is null && visible.GetType() == SValueType::Boolean)
         {
             if (!visible.GetBoolean())
             {
                 Hide();
 %if MOD_PICKUP_RESPAWN
                 auto toRespawn = data.GetDictionaryEntry("to-respawn");
                 if (toRespawn !is null && toRespawn.GetType() == SValueType::Integer)
                     m_toRespawn = toRespawn.GetInteger();
 %endif
             }
         }
     }
Save()
SValue Pickup::Save () inline private
Definition at line 63 of file Pickup.as.
References m_toRespawn, and m_visible.
     {
         SValueBuilder sval;
         sval.PushDictionary();
         sval.PushBoolean("visible", m_visible);
 %if MOD_PICKUP_RESPAWN
         if (!m_visible)
             sval.PushInteger("to-respawn", m_toRespawn);
 %endif
         return sval.Build();
     }
Show()
void Pickup::Show () inline private
Definition at line 111 of file Pickup.as.
References m_unit, and m_visible.
Referenced by Update().
     {
         if (m_visible)
             return;
         m_visible = true;
         m_unit.SetHidden(false);
         m_unit.SetShouldCollide(true);
     }
Update()
void Pickup::Update (int dt) inline private
Definition at line 224 of file Pickup.as.
References Destroy(), g_scene, m_bounce, m_toRespawn, m_unit, m_visible, and Show().
     {
         if (!m_visible)
         {
 %if MOD_PICKUP_RESPAWN
             if (m_toRespawn > 0)
             {
                 m_toRespawn -= dt;
                 if (m_toRespawn <= 0)
                     Show();
             }
             else
                 Destroy();
             return;
 %else
             Destroy();
             return;
 %endif
         }
         if (m_bounce)
         {
             const int tPeriod = 1000;
             uint time = g_scene.GetTime() % tPeriod;
             float h = (sin(time * PI * 2 / tPeriod) + 1.0) * 1.5;
             m_unit.SetPositionZ(h, true);
         }
     }
Member Data Documentation
m_achievementGroup
% if MOD_ACHIEVEMENT_CHECKS int Pickup::m_achievementGroup private
Definition at line 12 of file Pickup.as.
Referenced by Pickup().
m_bounce
bool Pickup::m_bounce private
Definition at line 4 of file Pickup.as.
Referenced by Pickup(), and Update().
m_callbacks
array<WorldScript::UnitPickedUpTrigger@> Pickup::m_callbacks private
Definition at line 24 of file Pickup.as.
Referenced by CallbackPicked(), and Collide().
m_effects
% endif array<IEffect@> Pickup::m_effects private
Definition at line 20 of file Pickup.as.
Referenced by Collide(), Picked(), and Pickup().
m_global
bool Pickup::m_global private
Definition at line 7 of file Pickup.as.
Referenced by Collide(), Picked(), and Pickup().
m_plrOnly
bool Pickup::m_plrOnly private
Definition at line 5 of file Pickup.as.
Referenced by Collide(), and Pickup().
m_respawnTime
% endif % if MOD_PICKUP_RESPAWN int Pickup::m_respawnTime private
Definition at line 16 of file Pickup.as.
Referenced by Hide(), and Pickup().
m_secure
bool Pickup::m_secure private
Definition at line 8 of file Pickup.as.
Referenced by Collide(), and Pickup().
m_shouldDestroy
bool Pickup::m_shouldDestroy private
Definition at line 9 of file Pickup.as.
Referenced by Destroy(), and Pickup().
m_sound
SoundEvent Pickup::m_sound private
Definition at line 6 of file Pickup.as.
Referenced by Picked(), PickedLocalFeedback(), and Pickup().
m_toRespawn
int Pickup::m_toRespawn private
Definition at line 17 of file Pickup.as.
Referenced by Hide(), PostLoad(), Save(), and Update().
m_unit
UnitPtr Pickup::m_unit private
Definition at line 3 of file Pickup.as.
Referenced by WorldScript::RefreshSpawnPickup::AlreadyExists(), CallbackPicked(), Collide(), Destroy(), Hide(), Picked(), PickedLocalFeedback(), Pickup(), Show(), and Update().
m_visible
bool Pickup::m_visible private
Definition at line 22 of file Pickup.as.
Referenced by WorldScript::RefreshSpawnPickup::AlreadyExists(), Collide(), Hide(), NetPicked(), Picked(), Pickup(), Save(), Show(), and Update().
The documentation for this class was generated from the following file:
scripts/Behaviors/Items/Pickup.as