HoHDocs: RangerProjectile Class Reference
RangerProjectile Class Reference
Private Member Functions
RangerProjectile (UnitPtr unit, SValue &params)
void Initialize (Actor@ owner, vec2 dir, float intensity, bool husk, Actor@ target, uint weapon) override
bool Multiply (vec2 pos)
bool HitUnit (UnitPtr unit, vec2 pos, vec2 normal, float selfDmg, bool bounce, bool collide=true) override
void Update (int dt) override
Private Attributes
uint m_weaponInfo
float m_twinChance
bool m_hasUpdated
Detailed Description
Definition at line 1 of file RangerProjectile.as.
Constructor & Destructor Documentation
RangerProjectile()
RangerProjectile::RangerProjectile (UnitPtr unit, SValue & params) inline private
Definition at line 7 of file RangerProjectile.as.
References m_hasUpdated, and unit.
     {
         super(unit, params);
         m_hasUpdated = false;
     }
Member Function Documentation
HitUnit()
bool RangerProjectile::HitUnit (UnitPtr unit, vec2 pos, vec2 normal, float selfDmg, bool bounce, bool collide = true) inline override private
Definition at line 71 of file RangerProjectile.as.
References ApplyEffects(), FilterAction(), RayProjectile::m_bounces, RayProjectile::m_bounceSpeedMul, RayProjectile::m_dir, RayProjectile::m_effects, ProjectileBase::m_husk, ProjectileBase::m_intensity, Skills::m_lastCollision, RayProjectile::m_owner, RayProjectile::m_penetration, RayProjectile::m_pos, RayProjectile::m_selfDmg, RayProjectile::m_soundBounce, ProjectileBase::m_soundHit, ProjectileBase::m_speed, RayProjectile::m_teamDmg, m_twinChance, ProjectileBase::m_unit, Multiply(), PlaySound3D(), RayProjectile::SetDirection(), unit, and xyz().
     {
         if (!unit.IsValid())
             return true;
         ref@ b = unit.GetScriptBehavior();
         /*
         IProjectile@ p = cast<IProjectile>(b);
         if (p !is null)
             return true;
         */
         auto dt = cast<IDamageTaker>(b);
         if (dt !is null)
         {
             if (dt.ShootThrough(pos, m_dir))
                 return false;
 //          m_lastCollision = unit;
             if (!dt.Impenetrable())
                 bounce = false;
             if (dt is m_owner && selfDmg > 0)
             {
                 if (m_lastCollision != unit)
                 {
                     m_lastCollision = unit;
                     ApplyEffects(m_effects, m_owner, unit, pos, m_dir, m_intensity * selfDmg, m_husk);
                     m_intensity *= 0.75;
                     if (--m_penetration <= 0)
                     {
                         PlaySound3D(m_soundHit, xyz(pos));
                         m_unit.Destroy();
                     }
                 }
                 return true;
             }
             else if (!(FilterAction(cast<Actor>(b), m_owner, m_selfDmg, m_teamDmg, 1, 1) > 0))
                 return true;
             else if (--m_penetration <= 0)
             {
                 PlaySound3D(m_soundHit, xyz(pos));
                 m_unit.Destroy();
             }
         }
         if (m_lastCollision != unit)
         {
             m_lastCollision = unit;
             ApplyEffects(m_effects, m_owner, unit, pos, m_dir, m_intensity, m_husk);
             m_intensity *= 0.66f;
             if (dt !is null && randf() < m_twinChance && m_intensity > 0.01f)
                 Multiply(pos);
         }
         if (bounce)
         {
             if (m_bounces <= 0)
                 m_unit.Destroy();
             else
             {
                 m_lastCollision = unit;
                 m_bounces--;
                 m_speed *= m_bounceSpeedMul;
                 SetDirection(normal * -2 * dot(m_dir, normal) + m_dir);
                 m_pos = pos;
                 PlaySound3D(m_soundBounce, xyz(pos));
             }
         }
         return false;
     }
Initialize()
void RangerProjectile::Initialize (Actor@ owner, vec2 dir, float intensity, bool husk, Actor@ target, uint weapon) inline override private
Definition at line 13 of file RangerProjectile.as.
References RayProjectile::Initialize(), m_skills, m_twinChance, and m_weaponInfo.
     {
         RayProjectile::Initialize(owner, dir, intensity, husk, target, weapon);
         m_weaponInfo = weapon;
         auto twinnedArrow = cast<Skills::TwinnedArrow>(cast<PlayerBase>(owner).m_skills[6]);
         if (twinnedArrow !is null)
             m_twinChance = twinnedArrow.m_chance;
         else
             m_twinChance = 0;
     }
Multiply()
bool RangerProjectile::Multiply (vec2 pos) inline private
Definition at line 25 of file RangerProjectile.as.
References g_scene, intercept(), RayProjectile::m_dir, m_hasUpdated, ProjectileBase::m_husk, ProjectileBase::m_intensity, RayProjectile::m_owner, RayProjectile::m_penetration, ProjectileBase::m_speed, RayProjectile::m_ttl, ProjectileBase::m_unit, m_weaponInfo, Actor::Team, xy(), and xyz().
Referenced by HitUnit().
     {
         if (!m_hasUpdated)
             return false;
         int ttl = m_ttl + 10;
         int range = int(ttl * m_speed / 33.0f * 1.05f);
         array<UnitPtr>@ enemies = g_scene.FetchActorsWithOtherTeam(m_owner.Team, pos, range);
         for (int i = 0; i < int(enemies.length()); i++)
         {
             if (dot(pos - xy(enemies[i].GetPosition()), m_dir) > 0)
             {
                 enemies.removeAt(i--);
                 continue;
             }
             auto actor = cast<Actor>(enemies[i].GetScriptBehavior());
             if (actor is null || !actor.IsTargetable())
             {
                 enemies.removeAt(i--);
                 continue;
             }
         }
         if (enemies.length() <= 0)
             return false;
         auto proj = m_unit.GetUnitProducer().Produce(g_scene, xyz(pos));
         if (!proj.IsValid())
             return false;
         auto p = cast<RangerProjectile>(proj.GetScriptBehavior());
         if (p is null)
             return false;
         auto target = enemies[randi(enemies.length())];
         auto tpos = intercept(pos, xy(target.GetPosition()), target.GetMoveDir(), m_speed);
         vec2 shootDir = normalize(tpos - pos);
         p.Initialize(m_owner, shootDir, m_intensity, m_husk, cast<Actor>(target.GetScriptBehavior()), m_weaponInfo);
         p.m_ttl = ttl;
         p.m_penetration = m_penetration;
         return true;
     }
Update()
void RangerProjectile::Update (int dt) inline override private
Definition at line 151 of file RangerProjectile.as.
References m_hasUpdated, and RayProjectile::Update().
     {
         RayProjectile::Update(dt);
         //m_intensity = max(0.05, m_intensity - (m_speed * dt / 33.0f) / 250.0f);
         m_hasUpdated = true;
     }
Member Data Documentation
m_hasUpdated
bool RangerProjectile::m_hasUpdated private
Definition at line 5 of file RangerProjectile.as.
Referenced by Multiply(), RangerProjectile(), and Update().
m_twinChance
float RangerProjectile::m_twinChance private
Definition at line 4 of file RangerProjectile.as.
Referenced by HitUnit(), and Initialize().
m_weaponInfo
uint RangerProjectile::m_weaponInfo private
Definition at line 3 of file RangerProjectile.as.
Referenced by Initialize(), and Multiply().
The documentation for this class was generated from the following file:
scripts/Behaviors/Projectiles/RangerProjectile.as