HoHDocs: Projectile Class Reference
Projectile Class Reference
Private Member Functions
Projectile (UnitPtr unit, SValue &params)
void Initialize (Actor@ owner, vec2 dir, float intensity, bool husk, Actor@ target, uint weapon) override
vec2 GetDirection () override
void SetDirection (vec2 dir) override
void Collide (UnitPtr unit, vec2 pos, vec2 normal)
void Update (int dt) override
Private Attributes
uint m_team
uint Team
float m_liveRangeSq
vec3 m_startPos
Actor m_owner
AnimString m_anim
array< IEffect@> m_effects
vec2 m_dir
float m_selfDmg
float m_teamDmg
Detailed Description
Definition at line 1 of file Projectile.as.
Constructor & Destructor Documentation
Projectile()
Projectile::Projectile (UnitPtr unit, SValue & params) inline private
Definition at line 21 of file Projectile.as.
References LoadEffects(), m_anim, m_effects, m_liveRangeSq, m_selfDmg, m_team, m_teamDmg, m_ttl, and unit.
     {
         super(unit, params);
         m_ttl = GetParamInt(unit, params, "ttl", false, 5000);
         m_liveRangeSq = float(GetParamInt(unit, params, "range", false, -1));
         if (m_liveRangeSq > 0)
             m_liveRangeSq = m_liveRangeSq * m_liveRangeSq;
         m_selfDmg = GetParamFloat(unit, params, "self-dmg", false, 0);
         m_teamDmg = GetParamFloat(unit, params, "team-dmg", false, 0);
         @m_anim = AnimString(GetParamString(unit, params, "anim"));
         @m_effects = LoadEffects(unit, params);
         auto to = GetParamString(unit, params, "team-override", false, "ERRR");
         m_team = (to == "ERRR") ? 1 : HashString(to);
     }
Member Function Documentation
Collide()
void Projectile::Collide (UnitPtr unit, vec2 pos, vec2 normal) inline private
Definition at line 69 of file Projectile.as.
References ApplyEffects(), m_dir, m_effects, ProjectileBase::m_husk, ProjectileBase::m_intensity, m_owner, m_selfDmg, ProjectileBase::m_soundHit, m_teamDmg, ProjectileBase::m_unit, PlaySound3D(), unit, and xyz().
Referenced by TossProjectile::Collide().
     {
         if (m_unit.IsDestroyed())
             return;
         if (!ShouldCollide(unit, pos, m_dir, m_owner, m_selfDmg, m_teamDmg))
             return;
         ApplyEffects(m_effects, m_owner, unit, pos, m_dir, m_intensity, m_husk, m_selfDmg, m_teamDmg);
         PlaySound3D(m_soundHit, xyz(pos));
         m_unit.Destroy();
     }
GetDirection()
vec2 Projectile::GetDirection () inline override private
Definition at line 57 of file Projectile.as.
References m_dir.
 { return m_dir; }
Initialize()
void Projectile::Initialize (Actor@ owner, vec2 dir, float intensity, bool husk, Actor@ target, uint weapon) inline override private
Definition at line 38 of file Projectile.as.
References Initialize(), m_effects, ProjectileBase::m_husk, ProjectileBase::m_intensity, m_owner, ProjectileBase::m_soundShoot, m_startPos, m_team, ProjectileBase::m_unit, PlaySound3D(), PropagateWeaponInformation(), SetDirection(), and Actor::Team.
Referenced by TossProjectile::Initialize().
     {
         SetDirection(dir);
         m_intensity = intensity;
         m_husk = husk;
         PropagateWeaponInformation(m_effects, weapon);
         m_startPos = m_unit.GetPosition();
         PlaySound3D(m_soundShoot, m_unit.GetPosition());
         @m_owner = owner;
         if (m_owner !is null && m_team == 1)
             m_team = owner.Team;
         SetSeekTarget(target);
         ProjectileBase::Initialize(owner, dir, intensity, husk, target, weapon);
     }
SetDirection()
void Projectile::SetDirection (vec2 dir) inline override private
Definition at line 58 of file Projectile.as.
References AnimString::GetSceneName(), m_anim, m_dir, ProjectileBase::m_speed, and ProjectileBase::m_unit.
Referenced by Initialize().
     {
         m_dir = dir;
         float ang = atan(dir.y, dir.x);
         m_unit.SetUnitScene(m_anim.GetSceneName(ang), false);
         SetScriptParams(ang, m_speed);
         PhysicsBody@ bdy = m_unit.GetPhysicsBody();
         bdy.SetLinearVelocity(dir * m_speed);
     }
Update()
void Projectile::Update (int dt) inline override private
Definition at line 82 of file Projectile.as.
References ApplyEffects(), distsq(), m_dir, m_effects, ProjectileBase::m_husk, ProjectileBase::m_intensity, m_liveRangeSq, m_owner, m_selfDmg, m_startPos, m_teamDmg, m_ttl, ProjectileBase::m_unit, Update(), and xy().
Referenced by TossProjectile::Update().
     {
         m_ttl -= dt;
         bool died = (m_ttl <= 0);
         if (!died && m_liveRangeSq > 0)
             died = (distsq(m_startPos, m_unit.GetPosition()) >= m_liveRangeSq);
         if (died)
         {
             ApplyEffects(m_effects, m_owner, UnitPtr(), xy(m_unit.GetPosition()), m_dir, m_intensity, m_husk, m_selfDmg, m_teamDmg);
             m_unit.Destroy();
         }
         UpdateSeeking(m_dir, dt);
         UpdateSpeed(m_dir, dt);
         ProjectileBase::Update(dt);
     }
Member Data Documentation
m_anim
AnimString Projectile::m_anim private
Definition at line 13 of file Projectile.as.
Referenced by Projectile(), TossProjectile::SetDirection(), and SetDirection().
m_dir
vec2 Projectile::m_dir private
Definition at line 16 of file Projectile.as.
Referenced by TossProjectile::Collide(), Collide(), TossProjectile::GetDirection(), GetDirection(), TossProjectile::SetDirection(), SetDirection(), and Update().
m_effects
array<IEffect@> Projectile::m_effects private
Definition at line 14 of file Projectile.as.
Referenced by TossProjectile::Collide(), Collide(), Initialize(), Projectile(), and Update().
m_liveRangeSq
float Projectile::m_liveRangeSq private
Definition at line 8 of file Projectile.as.
Referenced by Projectile(), and Update().
m_owner
Actor Projectile::m_owner private
Definition at line 11 of file Projectile.as.
Referenced by TossProjectile::Collide(), Collide(), Initialize(), and Update().
m_selfDmg
float Projectile::m_selfDmg private
Definition at line 17 of file Projectile.as.
Referenced by TossProjectile::Collide(), Collide(), Projectile(), and Update().
m_startPos
vec3 Projectile::m_startPos private
Definition at line 9 of file Projectile.as.
Referenced by Initialize(), and Update().
m_team
uint Projectile::m_team private
Definition at line 3 of file Projectile.as.
Referenced by Initialize(), and Projectile().
m_teamDmg
float Projectile::m_teamDmg private
Definition at line 18 of file Projectile.as.
Referenced by TossProjectile::Collide(), Collide(), Projectile(), and Update().
Team
uint Projectile::Team private
Initial value:
{ get override { return m_team; } }
    int m_ttl
Definition at line 4 of file Projectile.as.
The documentation for this class was generated from the following file:
scripts/Behaviors/Projectiles/Projectile.as