HoHDocs: MagicTile Class Reference
MagicTile Class Reference
Private Member Functions
MagicTile (UnitPtr unit, SValue &params)
void Activate (Actor@ owner, Actor@ target, int delay, uint weapon)
void ActivateNow ()
Actor ClosestPlayer ()
void Update (int dt)
Private Attributes
UnitPtr m_unit
bool m_activating
int m_activatingC
int m_activatingDelayC
UnitScene m_sceneActivate
SoundEvent m_sndActivate
UnitProducer m_projectile
Actor m_owner
uint m_weaponInfo
Detailed Description
Definition at line 1 of file MagicTile.as.
Constructor & Destructor Documentation
MagicTile()
MagicTile::MagicTile (UnitPtr unit, SValue & params) inline private
Definition at line 19 of file MagicTile.as.
References m_projectile, m_sceneActivate, m_sndActivate, m_unit, and unit.
     {
         m_unit = unit;
         @m_sceneActivate = unit.GetUnitScene(GetParamString(unit, params, "activate-scene"));
         @m_sndActivate = Resources::GetSoundEvent(GetParamString(unit, params, "activate-snd", false));
         @m_projectile = Resources::GetUnitProducer(GetParamString(unit, params, "projectile"));
         m_unit.SetUpdateDistanceLimit(1);
     }
Member Function Documentation
Activate()
void MagicTile::Activate (Actor@ owner, Actor@ target, int delay, uint weapon) inline private
Definition at line 31 of file MagicTile.as.
References ActivateNow(), m_activating, m_activatingDelayC, m_owner, m_unit, and m_weaponInfo.
Referenced by RaiseMagicTiles::DoAction(), and RaiseMagicTiles::NetDoAction().
     {
         m_weaponInfo = weapon;
         m_unit.SetUpdateDistanceLimit(0);
         if (m_activating)
             return;
         m_activatingDelayC = delay;
         m_activating = true;
         if (m_activatingDelayC == 0)
             ActivateNow();
         @m_owner = owner;
     }
ActivateNow()
void MagicTile::ActivateNow () inline private
Definition at line 49 of file MagicTile.as.
References m_activatingC, m_sceneActivate, m_sndActivate, m_unit, and PlaySound3D().
Referenced by Activate(), and Update().
     {
         m_unit.SetUnitScene(m_sceneActivate, true);
         m_activatingC = m_sceneActivate.Length();
         PlaySound3D(m_sndActivate, m_unit.GetPosition());
     }
ClosestPlayer()
Actor MagicTile::ClosestPlayer () inline private
Definition at line 56 of file MagicTile.as.
References distsq(), g_players, m_unit, and Actor::m_unit.
Referenced by Update().
     {
         vec3 myPos = m_unit.GetPosition();
         Actor@ closest = null;
         float closestDistance = 0;
         for (uint i = 0; i < g_players.length(); i++)
         {
             Actor@ a = g_players[i].actor;
             if (a is null)
                 continue;
             float distance = distsq(a.m_unit.GetPosition(), myPos);
             if (closest is null || distance < closestDistance)
             {
                 closestDistance = distance;
                 @closest = a;
             }
         }
         return closest;
     }
Update()
void MagicTile::Update (int dt) inline private
Definition at line 79 of file MagicTile.as.
References ActivateNow(), ClosestPlayer(), g_scene, m_activatingC, m_activatingDelayC, m_owner, m_projectile, m_unit, Actor::m_unit, m_weaponInfo, and xy().
     {
         if (m_activatingDelayC > 0)
         {
             m_activatingDelayC -= dt;
             if (m_activatingDelayC <= 0)
                 ActivateNow();
             return;
         }
         if (m_activatingC > 0)
         {
             m_activatingC -= dt;
             if (m_activatingC <= 0)
             {
                 if (m_projectile is null)
                     return;
                 Actor@ target = ClosestPlayer();
                 vec2 shootDir;
                 if (target !is null)
                     shootDir = normalize(xy(target.m_unit.GetPosition() - m_unit.GetPosition()));
                 else
                     shootDir = randdir();
                 UnitPtr proj = m_projectile.Produce(g_scene, m_unit.GetPosition());
                 if (!proj.IsValid())
                     return;
                 IProjectile@ p = cast<IProjectile>(proj.GetScriptBehavior());
                 if (p is null)
                     return;
                 p.Initialize(m_owner, shootDir, 1.0, false, target, m_weaponInfo);
                 if (target !is null)
                 {
                     auto pp = cast<ProjectileBase>(proj.GetScriptBehavior());
                     if (pp !is null && pp.m_seeking)
                         pp.m_seekTarget = target.m_unit;
                 }
                 m_unit.Destroy();
             }
         }
     }
Member Data Documentation
m_activating
bool MagicTile::m_activating private
Definition at line 5 of file MagicTile.as.
Referenced by Activate().
m_activatingC
int MagicTile::m_activatingC private
Definition at line 6 of file MagicTile.as.
Referenced by ActivateNow(), and Update().
m_activatingDelayC
int MagicTile::m_activatingDelayC private
Definition at line 8 of file MagicTile.as.
Referenced by Activate(), and Update().
m_owner
Actor MagicTile::m_owner private
Definition at line 15 of file MagicTile.as.
Referenced by Activate(), and Update().
m_projectile
UnitProducer MagicTile::m_projectile private
Definition at line 13 of file MagicTile.as.
Referenced by MagicTile(), and Update().
m_sceneActivate
UnitScene MagicTile::m_sceneActivate private
Definition at line 10 of file MagicTile.as.
Referenced by ActivateNow(), and MagicTile().
m_sndActivate
SoundEvent MagicTile::m_sndActivate private
Definition at line 11 of file MagicTile.as.
Referenced by ActivateNow(), and MagicTile().
m_unit
UnitPtr MagicTile::m_unit private
Definition at line 3 of file MagicTile.as.
Referenced by Activate(), ActivateNow(), ClosestPlayer(), MagicTile(), and Update().
m_weaponInfo
uint MagicTile::m_weaponInfo private
Definition at line 16 of file MagicTile.as.
Referenced by Activate(), and Update().
The documentation for this class was generated from the following file:
scripts/Behaviors/MagicTile.as