HoHDocs: CannonBall Class Reference
CannonBall Class Reference
Private Member Functions
CannonBall (UnitPtr unit, SValue &params)
void Initialize (Actor@ owner, vec2 dir, float intensity, bool husk, Actor@ target, uint weapon) override
void Initialize (Actor@ owner, vec2 dir, float intensity, bool husk, Actor@ target, uint weapon, float charge)
vec2 GetDirection () override
void SetDirection (vec2 dir) override
void Destroyed () override
void Collide (UnitPtr unit, vec2 pos, vec2 normal)
bool HitUnit (UnitPtr unit, vec2 pos, vec2 normal, float selfDmg, bool verifyBounce)
void Update (int dt) override
Private Attributes
uint m_team
uint Team
int m_ttl
int m_minDamage
int m_maxDamage
float m_minSpeed
float m_maxSpeed
float m_charge
float m_bounceSpeedMul
SoundEvent m_bounceSnd
Actor m_owner
AnimString m_anim
array< IEffect@> m_effects
vec2 m_dir
vec2 m_pos
float m_selfDmg
float m_teamDmg
bool m_bounced
uint m_weaponInfo
Detailed Description
Definition at line 1 of file CannonBall.as.
Constructor & Destructor Documentation
CannonBall()
CannonBall::CannonBall (UnitPtr unit, SValue & params) inline private
Definition at line 33 of file CannonBall.as.
References LoadEffects(), m_anim, m_bounceSnd, m_bounceSpeedMul, m_effects, m_maxDamage, m_maxSpeed, m_minDamage, m_minSpeed, m_selfDmg, m_teamDmg, m_ttl, and unit.
     {
         super(unit, params);
         m_ttl = GetParamInt(unit, params, "ttl", false, 5000);
         m_minSpeed = GetParamFloat(unit, params, "min-speed");
         m_maxSpeed = GetParamFloat(unit, params, "max-speed");
         m_selfDmg = GetParamFloat(unit, params, "self-dmg", false, 0);
         m_teamDmg = GetParamFloat(unit, params, "team-dmg", false, 0);
         m_minDamage = GetParamInt(unit, params, "min-dmg");
         m_maxDamage = GetParamInt(unit, params, "max-dmg");
         @m_anim = AnimString(GetParamString(unit, params, "anim"));
         @m_effects = LoadEffects(unit, params);
         m_bounceSpeedMul = GetParamFloat(unit, params, "bounce-speed-mul", false, 1.0);
         @m_bounceSnd = Resources::GetSoundEvent(GetParamString(unit, params, "bounce-snd", false));
     }
Member Function Documentation
Collide()
void CannonBall::Collide (UnitPtr unit, vec2 pos, vec2 normal) inline private
Definition at line 104 of file CannonBall.as.
References HitUnit(), m_bounced, m_selfDmg, and unit.
     {
         if (m_bounced)
             return;
         HitUnit(unit, pos, normal, m_selfDmg, true);
     }
Destroyed()
void CannonBall::Destroyed () inline override private
Definition at line 99 of file CannonBall.as.
References ApplyEffects(), m_dir, m_effects, ProjectileBase::m_husk, m_owner, m_selfDmg, m_teamDmg, ProjectileBase::m_unit, and xy().
     {
         ApplyEffects(m_effects, m_owner, UnitPtr(), xy(m_unit.GetPosition()), m_dir, 1.0, m_husk, m_selfDmg, m_teamDmg);
     }
GetDirection()
vec2 CannonBall::GetDirection () inline override private
Definition at line 90 of file CannonBall.as.
References m_dir.
 { return m_dir; }
HitUnit()
bool CannonBall::HitUnit (UnitPtr unit, vec2 pos, vec2 normal, float selfDmg, bool verifyBounce) inline private
Definition at line 112 of file CannonBall.as.
References BLUNT, damage_round(), DamageInfo(), FilterAction(), g_scene, lerp(), m_bounced, m_bounceSnd, m_bounceSpeedMul, m_charge, m_dir, ProjectileBase::m_intensity, Skills::m_lastCollision, m_maxDamage, m_minDamage, m_owner, m_selfDmg, ProjectileBase::m_speed, m_teamDmg, ProjectileBase::m_unit, m_weaponInfo, PlaySound3D(), SetDirection(), and unit.
Referenced by Collide(), Initialize(), and Update().
     {
         bool bounce = true;
         if (!unit.IsValid() || unit == m_unit || m_lastCollision == unit)
             return false;
         ref@ b = unit.GetScriptBehavior();
         IProjectile@ p = cast<IProjectile>(b);
         if (p !is null)
             return false;
         if (FilterAction(cast<Actor>(b), m_owner, m_selfDmg, m_teamDmg, 1.0, 1.0) <= 0)
             return false;
         int dmg = damage_round(lerp(m_minDamage, m_maxDamage, m_charge) * FilterAction(cast<Actor>(b), m_owner, m_selfDmg, m_teamDmg, 1.0) * m_intensity);
         if (dmg > 0)
             unit.TriggerCallbacks(UnitEventType::Damaged);
         IDamageTaker@ dt = cast<IDamageTaker>(unit.GetScriptBehavior());
         if (dt !is null)
         {
             if (dt.Impenetrable())
             {
                 m_unit.Destroy();
                 return true;
             }
             else
             {
                 if (dmg > 0)
                     dt.Damage(DamageInfo(uint8(DamageType::BLUNT), m_owner, dmg, false, true, m_weaponInfo), pos, m_dir);
                 bounce = false;
             }
         }
         m_lastCollision = unit;
         if (bounce)
         {
             if (verifyBounce)
             {
                 array<RaycastResult>@ results = g_scene.Raycast(pos - m_dir * 4.0f, pos + m_dir * 8.0f, ~0, RaycastType::Shot);
                 for (uint i = 0; i < results.length(); i++)
                 {
                     RaycastResult res = results[i];
                     if (res.FetchUnit(g_scene) == unit)
                     {
                         normal = res.normal;
                         pos = res.point;
                         break;
                     }
                 }
             }
             m_speed *= m_bounceSpeedMul;
             SetDirection(normal * -2 * dot(m_dir, normal) + m_dir);
             PlaySound3D(m_bounceSnd, m_unit.GetPosition());
             m_bounced = true;
         }
         return true;
     }
Initialize() [1/2]
void CannonBall::Initialize (Actor@ owner, vec2 dir, float intensity, bool husk, Actor@ target, uint weapon) inline override private
Definition at line 53 of file CannonBall.as.
References Initialize().
     {
         Initialize(owner, dir, intensity, husk, target, weapon, 1.0);
         ProjectileBase::Initialize(owner, dir, intensity, husk, target, weapon);
     }
Initialize() [2/2]
void CannonBall::Initialize (Actor@ owner, vec2 dir, float intensity, bool husk, Actor@ target, uint weapon, float charge) inline private
Definition at line 59 of file CannonBall.as.
References g_scene, HitUnit(), lerp(), m_charge, m_effects, ProjectileBase::m_husk, ProjectileBase::m_intensity, Skills::m_lastCollision, m_maxSpeed, m_minSpeed, m_owner, m_pos, ProjectileBase::m_speed, m_team, Actor::m_unit, ProjectileBase::m_unit, m_weaponInfo, PropagateWeaponInformation(), SetDirection(), Actor::Team, and xy().
     {
         m_husk = husk;
         m_intensity = intensity;
         m_charge = charge;
         m_speed = lerp(m_minSpeed, m_maxSpeed, charge);
         SetDirection(dir * m_speed);
         PropagateWeaponInformation(m_effects, weapon);
         m_weaponInfo = weapon;
         @m_owner = owner;
         if (m_owner !is null)
         {
             m_team = owner.Team;
             m_lastCollision = owner.m_unit;
         }
         m_pos = xy(m_unit.GetPosition());
         vec2 nDir = vec2(-dir.x, -dir.y);
         array<UnitPtr>@ results = g_scene.QueryRect(m_pos, 1, 1, ~0, RaycastType::Aim);
         for (uint i = 0; i < results.length(); i++)
         {
             if (m_owner !is null && m_owner.m_unit == results[i])
                 continue;
             if (HitUnit(results[i], m_pos, nDir, 0, true))
                 break;
         }
     }
SetDirection()
void CannonBall::SetDirection (vec2 dir) inline override private
Definition at line 91 of file CannonBall.as.
References AnimString::GetSceneName(), m_anim, m_dir, ProjectileBase::m_speed, and ProjectileBase::m_unit.
Referenced by HitUnit(), and Initialize().
     {
         m_dir = dir;
         float ang = atan(dir.y, dir.x);
         m_unit.SetUnitScene(m_anim.GetSceneName(ang), false);
         SetScriptParams(ang, m_speed);
     }
Update()
void CannonBall::Update (int dt) inline override private
Definition at line 177 of file CannonBall.as.
References g_scene, HitUnit(), m_bounced, m_dir, m_pos, m_selfDmg, ProjectileBase::m_speed, m_ttl, ProjectileBase::m_unit, and Update().
     {
         m_bounced = false;
         UpdateSeeking(m_dir, dt);
         m_ttl -= dt;
         if (m_ttl <= 0)
             m_unit.Destroy();
         vec2 from = m_pos;
         m_pos += m_dir * m_speed * dt / 33.0;
         array<RaycastResult>@ results = g_scene.Raycast(from, m_pos, ~0, RaycastType::Shot);
         for (uint i = 0; i < results.length(); i++)
         {
             RaycastResult res = results[i];
             if (HitUnit(res.FetchUnit(g_scene), res.point, res.normal, m_selfDmg, false))
             {
                 m_unit.SetPosition(res.point.x, res.point.y, 0, true);
                 return;
             }
         }
         m_unit.SetPosition(m_pos.x, m_pos.y, 0, true);
         UpdateSpeed(m_dir, dt);
         ProjectileBase::Update(dt);
     }
Member Data Documentation
m_anim
AnimString CannonBall::m_anim private
Definition at line 20 of file CannonBall.as.
Referenced by CannonBall(), and SetDirection().
m_bounced
bool CannonBall::m_bounced private
Definition at line 29 of file CannonBall.as.
Referenced by Collide(), HitUnit(), and Update().
m_bounceSnd
SoundEvent CannonBall::m_bounceSnd private
Definition at line 16 of file CannonBall.as.
Referenced by CannonBall(), and HitUnit().
m_bounceSpeedMul
float CannonBall::m_bounceSpeedMul private
Definition at line 15 of file CannonBall.as.
Referenced by CannonBall(), and HitUnit().
m_charge
float CannonBall::m_charge private
Definition at line 13 of file CannonBall.as.
Referenced by HitUnit(), and Initialize().
m_dir
vec2 CannonBall::m_dir private
Definition at line 23 of file CannonBall.as.
Referenced by Destroyed(), GetDirection(), HitUnit(), SetDirection(), and Update().
m_effects
array<IEffect@> CannonBall::m_effects private
Definition at line 21 of file CannonBall.as.
Referenced by CannonBall(), Destroyed(), and Initialize().
m_maxDamage
int CannonBall::m_maxDamage private
Definition at line 10 of file CannonBall.as.
Referenced by CannonBall(), and HitUnit().
m_maxSpeed
float CannonBall::m_maxSpeed private
Definition at line 12 of file CannonBall.as.
Referenced by CannonBall(), and Initialize().
m_minDamage
int CannonBall::m_minDamage private
Definition at line 9 of file CannonBall.as.
Referenced by CannonBall(), and HitUnit().
m_minSpeed
float CannonBall::m_minSpeed private
Definition at line 11 of file CannonBall.as.
Referenced by CannonBall(), and Initialize().
m_owner
Actor CannonBall::m_owner private
Definition at line 18 of file CannonBall.as.
Referenced by Destroyed(), HitUnit(), and Initialize().
m_pos
vec2 CannonBall::m_pos private
Definition at line 24 of file CannonBall.as.
Referenced by Initialize(), and Update().
m_selfDmg
float CannonBall::m_selfDmg private
Definition at line 26 of file CannonBall.as.
Referenced by CannonBall(), Collide(), Destroyed(), HitUnit(), and Update().
m_team
uint CannonBall::m_team private
Definition at line 3 of file CannonBall.as.
Referenced by Initialize().
m_teamDmg
float CannonBall::m_teamDmg private
Definition at line 27 of file CannonBall.as.
Referenced by CannonBall(), Destroyed(), and HitUnit().
m_ttl
int CannonBall::m_ttl private
Definition at line 8 of file CannonBall.as.
Referenced by CannonBall(), and Update().
m_weaponInfo
uint CannonBall::m_weaponInfo private
Definition at line 30 of file CannonBall.as.
Referenced by HitUnit(), and Initialize().
Team
uint CannonBall::Team private
Initial value:
{ get override { return m_team; } }
    UnitPtr m_lastCollision
Definition at line 4 of file CannonBall.as.
The documentation for this class was generated from the following file:
scripts/Behaviors/Projectiles/CannonBall.as