HoHDocs: MainMenu Class Reference
MainMenu Class Reference
Private Member Functions
MainMenu (Scene@ scene)
void InstantiateMice ()
Menu::ServerlistMenu GetServerlistMenu ()
void ShowMessage (MenuMessage message)
void LoadMenu ()
void Start (uint8 peer, SValue@ save, StartMode sMode) override
void SpawnPlayers () override
bool ShouldDisplayCursor () override
void SetMenuState (MenuState state)
bool MenuBack () override
void UpdateFrame (int ms, GameInput &gameInput, MenuInput &menuInput) override
vec2 GetCameraPos (int idt) override
void PreRenderFrame (int idt) override
void RenderFrame (int idt, SpriteBatch &sb) override
void DrawPlayerColorPicking (SpriteBatch &sb)
void RenderFrameLoading (int idt, SpriteBatch &sb)
void ChatMessage (uint8 peer, string msg)
void LobbyDataUpdate ()
void LobbyMemberDataUpdate (uint8 peer)
void HandleChatMessage (string message)
void LobbyCreated (bool loadingSave)
void JoiningLobby ()
void LobbyInviteAccepted (uint64 id)
void LobbyEntered ()
void LobbyFailedJoin (bool host)
void AddPlayer (uint8 peer) override
void RemovePlayer (uint8 peer, bool kicked) override
void SystemMessage (string name, SValue@ data)
void PlayGame (int numPlrs)
void OnBindingInput (ControllerType type, int key)
void LobbyList (array< uint64 >@ lobbies)
Private Attributes
MenuControlInputWidget m_expectingInput
MenuProvider m_mainMenu
MenuProvider m_ingameMenu
Menu::InGameChat m_ingameChat
Menu::InGameNotifier m_ingameNotifier
GameChatWidget m_wChat
MenuProvider m_gameMenu
MenuState m_state
SoundInstance m_musicInstance
bool m_testLevel
bool m_hostPrivate
string m_hostName
pint m_hostMaxPlayers
pint m_hostMaxLevel
pint m_hostMinLevel
pint m_hostNgp
bool m_hostDownscaling
uint64 m_inviteAcceptID
int m_inviteAcceptMaxLevel
int m_inviteAcceptMinLevel
int m_frameCount
bool m_lostConnection
int m_joinFailed = -1
TownRecord m_town
Menu::JoiningLobbyMenu m_joiningMenu
Detailed Description
Definition at line 4 of file MainMenu.as.
Constructor & Destructor Documentation
MainMenu()
MainMenu::MainMenu (Scene@ scene) inline private
Definition at line 41 of file MainMenu.as.
References GetControlBindings(), Platform::GetSessionCount(), Menu::InGameNotifier::Initialize(), LoadGameChatWidget(), LoadMenu(), LoadMenuControlInput(), LoadMenuLobbyPlayer(), LoadMenuServerListItemWidget(), AGameMode::m_guiBuilder, m_ingameMenu, m_ingameNotifier, m_mainMenu, and MakeDyeColorsCFunc().
     {
         super(scene);
 %if WIP_BUILD
         AddVar("dbg_dye", "");
         AddVar("dbg_dye_color1", vec3(0,0,0));
         AddVar("dbg_dye_color2", vec3(0.5,0.5,0.5));
         AddVar("dbg_dye_color3", vec3(1,1,1));
         AddFunction("dbg_dye_mkcolor", MakeDyeColorsCFunc);
 %endif
         if (!VarExists("g_intro_logos"))
             AddVar("g_intro_logos", true);
         if (!VarExists("g_intro_logos_shown"))
             AddVar("g_intro_logos_shown", false);
         if (!VarExists("g_debug_menu"))
             AddVar("g_debug_menu", false);
         if (!VarExists("g_multi_test"))
             AddVar("g_multi_test", false, null, cvar_flags::Cheat);
         @m_mainMenu = MenuProvider();
         @m_ingameMenu = MenuProvider();
         @m_ingameNotifier = Menu::InGameNotifier();
         m_ingameNotifier.Initialize(m_guiBuilder, "gui/ingame_menu/notifier.gui");
         m_guiBuilder.AddWidgetProducer("menu_control_input", LoadMenuControlInput);
         m_guiBuilder.AddWidgetProducer("game_chat", LoadGameChatWidget);
         m_guiBuilder.AddWidgetProducer("menu_lobby_player", LoadMenuLobbyPlayer);
         m_guiBuilder.AddWidgetProducer("menu_serverlist_item", LoadMenuServerListItemWidget);
         LoadMenu();
         if (Platform::GetSessionCount() == 0)
         {
             auto cb = GetControlBindings();
             GetControlBindings().AssignControls(1);
         }
         InstantiateMice();
     }
Member Function Documentation
AddPlayer()
void MainMenu::AddPlayer (uint8 peer) inline override private
Definition at line 505 of file MainMenu.as.
     {
         if (m_wChat !is null)
             m_wChat.PlayerSystem(peer, ".menu.lobby.chat.isjoined");
     }
ChatMessage()
void MainMenu::ChatMessage (uint8 peer, string msg) inline private
Definition at line 372 of file MainMenu.as.
References IsPlayerLocal().
     {
         if (Lobby::IsPlayerLocal(peer))
             return;
         if (m_wChat !is null)
             m_wChat.PlayerChat(peer, msg);
     }
DrawPlayerColorPicking()
void MainMenu::DrawPlayerColorPicking (SpriteBatch & sb) inline private
Definition at line 302 of file MainMenu.as.
References unit, and xyzw().
Referenced by RenderFrame().
     {
 %if WIP_BUILD
         auto dbg = GetVarString("dbg_dye");
         if (dbg == "")
             return;
         vec3 a = GetVarVec3("dbg_dye_color1");
         vec3 b = GetVarVec3("dbg_dye_color2");
         vec3 c = GetVarVec3("dbg_dye_color3");
         for (uint i = 0; i < 8; i++)
             sb.SetMultiColor(i, tocolor(xyzw(a, 1)), tocolor(xyzw(b, 1)), tocolor(xyzw(c, 1)));
         auto unit = Resources::GetUnitProducer("players/" + dbg + ".unit");
         sb.DrawUnitScene(vec2(100, 100), vec2(50, 50), unit.GetUnitScene("idle-3"), 0);
         sb.DisableMultiColor();
 %endif
     }
GetCameraPos()
vec2 MainMenu::GetCameraPos (int idt) inline override private
Definition at line 257 of file MainMenu.as.
References m_frameCount.
     {
         float scalar = (m_frameCount + idt / 33.0f);
         vec2 camOffset = vec2(sin(scalar / 40.0f) * 8.0f, cos(scalar / 60.0f) * 4.0f);
         return m_camPos + camOffset;
     }
GetServerlistMenu()
Menu::ServerlistMenu MainMenu::GetServerlistMenu () inline private
Definition at line 94 of file MainMenu.as.
References m_gameMenu, and MenuProvider::m_menus.
Referenced by LobbyList().
     {
         for (uint i = 0; i < m_gameMenu.m_menus.length(); i++)
         {
             auto menu = cast<Menu::ServerlistMenu>(m_gameMenu.m_menus[i]);
             if (menu !is null)
                 return menu;
         }
         return null;
     }
HandleChatMessage()
void MainMenu::HandleChatMessage (string message) inline private
Definition at line 394 of file MainMenu.as.
     {
         /*
         if (message.length() >= 1 && message.length() <= 2)
         {
             int num = parseInt(message);
             if (num < 1 || num > 42)
                 return;
             if (!GetVarBool("ui_chat_dialog"))
                 return;
             PlaySound2D(Resources::GetSoundEvent("event:/dialog/chat/chat_" + num));
         }
         */
     }
InstantiateMice()
void MainMenu::InstantiateMice () inline private
Definition at line 83 of file MainMenu.as.
References Platform::GetGameInput(), Platform::GetInputCount(), Platform::GetMenuInput(), and BaseGameMode::m_mice.
     {
         m_mice.removeRange(0, m_mice.length());
         int numInputs = Platform::GetInputCount();
         for (int i = 0; i < numInputs; i++) {
             GameInput@ gi = Platform::GetGameInput(i);
             MenuInput@ mi = Platform::GetMenuInput(i);
             m_mice.insertLast(MenuMouse(gi, mi, numInputs > 1));
         }
     }
JoiningLobby()
void MainMenu::JoiningLobby () inline private
Definition at line 442 of file MainMenu.as.
Referenced by Menu::OnFunc().
     {
         @m_joiningMenu = Menu::JoiningLobbyMenu(m_gameMenu);
         m_gameMenu.GetCurrentMenu().OpenMenu(m_joiningMenu, "gui/main_menu/joininglobby.gui");
     }
LoadMenu()
void MainMenu::LoadMenu () inline private
Definition at line 113 of file MainMenu.as.
References MenuProvider::Initialize(), Menu::InGameChat::Initialize(), m_gameMenu, AGameMode::m_guiBuilder, m_ingameChat, m_ingameMenu, and m_mainMenu.
Referenced by MainMenu().
     {
         @m_gameMenu = m_mainMenu;
         if (GetVarBool("g_debug_menu"))
             m_mainMenu.Initialize(m_guiBuilder, Menu::TestMenu(m_mainMenu), "gui/test.gui", "gui/main_menu/backdrop.gui");
         else
         {
             if (GetVarBool("g_intro_logos") && !GetVarBool("g_intro_logos_shown"))
                 m_mainMenu.Initialize(m_guiBuilder, Menu::IntroMenu(m_mainMenu), "gui/main_menu/intro.gui", "gui/main_menu/backdrop.gui");
             else
                 m_mainMenu.Initialize(m_guiBuilder, Menu::FrontMenu(m_mainMenu), "gui/main_menu/main.gui", "gui/main_menu/backdrop.gui");
         }
         @m_gameMenu = m_ingameMenu;
         m_ingameMenu.Initialize(m_guiBuilder, Menu::FrontMenu(m_ingameMenu), "gui/ingame_menu/main.gui", "gui/ingame_menu/backdrop.gui");
         @m_ingameChat = Menu::InGameChat();
         m_ingameChat.Initialize(m_guiBuilder, "gui/ingame_menu/chat.gui");
         g_gameMode.ClearWidgetRoot();
     }
LobbyCreated()
void MainMenu::LobbyCreated (bool loadingSave) inline private
Definition at line 411 of file MainMenu.as.
References HwrSaves::GetEnabledMods(), m_hostDownscaling, m_hostMaxLevel, m_hostMaxPlayers, m_hostMinLevel, m_hostName, m_hostNgp, m_hostPrivate, m_testLevel, Name, Modifiers::Set, SetLevel(), SetLobbyData(), SetPlayerLimit(), SetPrivate(), and strTrim().
     {
         print("LobbyCreated()");
         Lobby::SetPrivate(m_hostPrivate);
         Lobby::SetLobbyData("name", m_hostName);
         Lobby::SetPlayerLimit(m_hostMaxPlayers);
         Lobby::SetLobbyData("max-level", int(m_hostMaxLevel));
         Lobby::SetLobbyData("min-level", int(m_hostMinLevel));
         Lobby::SetLobbyData("downscaling", m_hostDownscaling ? "true" : "false");
         auto enabledMods = HwrSaves::GetEnabledMods();
         Lobby::SetLobbyData("mods-count", enabledMods.length());
         string modsInfo = "";
         for (uint i = 0; i < enabledMods.length(); i++)
             modsInfo += enabledMods[i].Name + "\n";
         if (modsInfo.length() > 512) // GOG lobbies have a 4095 byte limit but let's not go crazy here
             modsInfo = modsInfo.substr(0, 510) + "...";
         Lobby::SetLobbyData("mods", strTrim(modsInfo));
         GlobalCache::Set("start_host_ngp", "" + m_hostNgp);
         GlobalCache::Set("start_host_downscaling", m_hostDownscaling ? "true" : "false");
         if (m_testLevel)
             Lobby::SetLevel("levels/test/test_multi.lvl");
         else
             Lobby::SetLevel("levels/town_outlook.lvl");
         Lobby::StartGame();
         //Lobby::SetJoinable(true);
     }
LobbyDataUpdate()
void MainMenu::LobbyDataUpdate () inline private
Definition at line 381 of file MainMenu.as.
     {
         //NOTE: Steam seems to trigger a data update for the lobby right after it triggers
         //      a data update for a lobby member. Not sure why, but this means that you should
         //      be careful when setting lobby member data in this callback, as it could result
         //      in never-ending events. (I suppose the same counts for regular lobby data too)
     }
LobbyEntered()
void MainMenu::LobbyEntered () inline private
Definition at line 488 of file MainMenu.as.
     {
     }
LobbyFailedJoin()
void MainMenu::LobbyFailedJoin (bool host) inline private
Definition at line 492 of file MainMenu.as.
References m_joinFailed, and m_joiningMenu.
     {
         m_joinFailed = host ? 1 : 0;
         if (m_joiningMenu !is null)
         {
             m_joiningMenu.Close();
             @m_joiningMenu = null;
         }
         ShowDialog("", Resources::GetString(".menu.notifier.joinfailed.join"), Resources::GetString(".menu.ok"), null);
     }
LobbyInviteAccepted()
void MainMenu::LobbyInviteAccepted (uint64 id) inline private
Definition at line 448 of file MainMenu.as.
References GetLobbyData(), id, m_gameMenu, m_inviteAcceptID, m_inviteAcceptMaxLevel, m_inviteAcceptMinLevel, MenuProvider::m_menus, and BaseGameMode::ShowDialog().
     {
         print("Invite accepted to join \"" + Lobby::GetLobbyData(id, "name") + "\"");
         if (!Platform::Service.IsMultiplayerAvailable())
         {
             print("Can't join because multiplayer is not available");
             //TODO: Give different error if using unpacked mods
             ShowDialog("", Resources::GetString(".menu.notifier.joinfailed.join"), Resources::GetString(".menu.ok"), null);
             return;
         }
         uint modsHash = parseUInt(Lobby::GetLobbyData(id, "mods-hash"));
         if (modsHash != Resources::GetModHash())
         {
             int modsCount = parseInt(Lobby::GetLobbyData(id, "mods-count"));
             string mods = Lobby::GetLobbyData(id, "mods");
             print("Can't join because mod hash mismatch (expected " + modsCount + " mods)");
             ShowDialog("", Resources::GetString(".menu.notifier.joinfailed.mods", {
                 { "num", modsCount },
                 { "mods", mods }
             }), Resources::GetString(".menu.ok"), null);
             return;
         }
         m_inviteAcceptID = id;
         m_inviteAcceptMaxLevel = parseInt(Lobby::GetLobbyData(id, "max-level"));
         m_inviteAcceptMinLevel = parseInt(Lobby::GetLobbyData(id, "min-level"));
         auto menu = cast<Menu::HwrMenu>(m_gameMenu.m_menus[0]);
         if (menu is null)
         {
             PrintError("First menu is not HwrMenu!");
             return;
         }
         menu.ShowCharacterSelection("multi-invite");
     }
LobbyList()
void MainMenu::LobbyList (array< uint64 >@ lobbies) inline private
Definition at line 547 of file MainMenu.as.
References GetServerlistMenu().
     {
         auto listMenu = GetServerlistMenu();
         if (listMenu !is null)
             listMenu.OnLobbyList(lobbies);
     }
LobbyMemberDataUpdate()
void MainMenu::LobbyMemberDataUpdate (uint8 peer) inline private
Definition at line 389 of file MainMenu.as.
     {
         //NOTE: See note above in LobbyDataUpdate.
     }
MenuBack()
bool MainMenu::MenuBack () inline override private
Definition at line 200 of file MainMenu.as.
References MenuProvider::GoBack(), Hidden, m_gameMenu, m_ingameMenu, m_state, and BaseGameMode::MenuBack().
     {
         if (m_state == MenuState::Hidden)
             return false;
         if (!BaseGameMode::MenuBack())
         {
             if (m_gameMenu is m_ingameMenu)
                 return m_gameMenu.GoBack();
             else
                 m_gameMenu.GoBack();
         }
         return true;
     }
OnBindingInput()
void MainMenu::OnBindingInput (ControllerType type, int key) inline private
Definition at line 541 of file MainMenu.as.
     {
         if (m_expectingInput !is null)
             m_expectingInput.ExpectedInput(type, key);
     }
PlayGame()
void MainMenu::PlayGame (int numPlrs) inline private
Definition at line 535 of file MainMenu.as.
     {
         // Singleplayer
         StartGame(numPlrs, "levels/town_outlook.lvl");
     }
PreRenderFrame()
void MainMenu::PreRenderFrame (int idt) inline override private
Definition at line 264 of file MainMenu.as.
     {
     }
RemovePlayer()
void MainMenu::RemovePlayer (uint8 peer, bool kicked) inline override private
Definition at line 511 of file MainMenu.as.
References m_wChat, and GameChatWidget::PlayerSystem().
     {
         if (m_wChat !is null)
         {
             if (kicked)
                 m_wChat.PlayerSystem(peer, ".menu.lobby.chat.iskicked");
             else
                 m_wChat.PlayerSystem(peer, ".menu.lobby.chat.isleft");
         }
     }
RenderFrame()
void MainMenu::RenderFrame (int idt, SpriteBatch & sb) inline override private
Definition at line 268 of file MainMenu.as.
References Menu::InGameChat::Draw(), DialogWindow::Draw(), BaseGameMode::DrawMouse(), DrawPlayerColorPicking(), g_gameMode, MenuProvider::GetCurrentMenu(), GetUIScale(), Hidden, AGameMode::m_dialogWindow, m_gameMenu, m_ingameChat, m_ingameNotifier, m_state, DialogWindow::m_visible, AGameMode::m_wndHeight, AGameMode::m_wndWidth, MenuProvider::Render(), BaseGameMode::RenderWidgets(), and Menu::Menu::ShouldDisplayCursor().
     {
         sb.PushTransformation(mat::scale(mat4(), GetUIScale()));
         int w = g_gameMode.m_wndWidth;
         int h = g_gameMode.m_wndHeight;
         if (m_state == MenuState::Hidden)
         {
             m_ingameChat.Draw(sb, idt);
             m_ingameNotifier.Draw(sb, idt);
             if (m_dialogWindow !is null && m_dialogWindow.m_visible)
             {
                 m_dialogWindow.Draw(sb, idt);
                 DrawMouse(idt, sb);
             }
             sb.PopTransformation();
             return;
         }
         m_gameMenu.Render(idt, sb);
         RenderWidgets(null, idt, sb);
         if (m_gameMenu.GetCurrentMenu().ShouldDisplayCursor())
             DrawMouse(idt, sb);
         DrawPlayerColorPicking(sb);
         sb.PopTransformation();
     }
RenderFrameLoading()
void MainMenu::RenderFrameLoading (int idt, SpriteBatch & sb) inline private
Definition at line 323 of file MainMenu.as.
References Center, GetPlayerLoadStates(), GetPlayerName(), Left, AGameMode::m_wndHeight, AGameMode::m_wndScale, AGameMode::m_wndWidth, name, Peer, Progress, and text.
     {
         BitmapFont@ loadFont = Resources::GetBitmapFont("gui/fonts/code2003_20_bold.fnt");
         if (loadFont is null)
             return;
         auto loadText = loadFont.BuildText(Resources::GetString(".menu.loading"), -1, TextAlignment::Center);
         sb.Begin(m_wndWidth, m_wndHeight, m_wndScale);
         sb.DrawSprite(null, vec4(-5, -5, m_wndWidth + 10, m_wndHeight + 10), vec4(), vec4(0, 0, 0, 1));
         sb.DrawString(vec2((m_wndWidth - loadText.GetWidth()) / 2, (m_wndHeight - loadText.GetHeight()) / 2), loadText);
         auto loadStates = Lobby::GetPlayerLoadStates();
         if (loadStates !is null)
         {
             BitmapFont@ plrFont = Resources::GetBitmapFont("gui/fonts/arial11.fnt");
             if (plrFont is null)
                 return;
             for (uint i = 0; i < loadStates.length(); i++)
             {
                 auto name = Lobby::GetPlayerName(loadStates[i].Peer);
                 string text;
                 switch(loadStates[i].Progress)
                 {
                 case 0:
                     text = "\\c000000...\\d " + name;
                     break;
                 case 1:
                     text = ".\\c000000..\\d " + name;
                     break;
                 case 2:
                     text = "..\\c000000.\\d " + name;
                     break;
                 case 3:
                     text = "... " + name;
                     break;
                 }
                 auto plrText = plrFont.BuildText(text, -1, TextAlignment::Left);
                 sb.DrawString(vec2(4, 2 + i * plrText.GetHeight()), plrText);
             }
         }
         sb.End();
     }
SetMenuState()
void MainMenu::SetMenuState (MenuState state) inline private
Definition at line 153 of file MainMenu.as.
References AGameMode::AddWidgetRoot(), DiscordPresence::Clear(), ServicePresence::Clear(), AGameMode::ClearWidgetRoot(), g_gameMode, MenuProvider::GetCurrentMenu(), Hidden, InGameMenu, m_gameMenu, m_ingameChat, m_ingameMenu, m_mainMenu, m_musicInstance, m_state, MainMenu(), ServicePresence::Set(), Menu::Menu::SetActive(), DiscordPresence::SetState(), and Menu::InGameChat::StopInput().
     {
         m_ingameChat.StopInput();
         g_gameMode.ClearWidgetRoot();
         m_state = state;
         if (m_state == MenuState::InGameMenu)
             @m_gameMenu = m_ingameMenu;
         else if (m_state == MenuState::MainMenu)
         {
             @m_gameMenu = m_mainMenu;
             DiscordPresence::Clear();
             DiscordPresence::SetState("In main menu");
             ServicePresence::Clear();
             ServicePresence::Set("#Status_InMainMenu");
         }
         else if (m_state == MenuState::Hidden)
         {
             if (m_musicInstance !is null && m_musicInstance.IsPlaying())
                 m_musicInstance.Stop();
             return;
         }
         g_gameMode.AddWidgetRoot(m_gameMenu.GetCurrentMenu());
         m_gameMenu.GetCurrentMenu().SetActive();
         if (m_state == MenuState::MainMenu)
         {
             if (m_musicInstance is null)
             {
                 auto music = Resources::GetSoundEvent("event:/music/menu");
                 if (music !is null)
                 {
                     @m_musicInstance = music.PlayTracked();
                     m_musicInstance.SetLooped(true);
                     m_musicInstance.SetPaused(false);
                 }
             }
         }
         else if (m_musicInstance !is null)
             m_musicInstance.Stop();
     }
ShouldDisplayCursor()
bool MainMenu::ShouldDisplayCursor () inline override private
Definition at line 148 of file MainMenu.as.
     {
         return (m_state != MenuState::Hidden) || (m_dialogWindow !is null);
     }
ShowMessage()
void MainMenu::ShowMessage (MenuMessage message) inline private
Definition at line 105 of file MainMenu.as.
References m_ingameNotifier, Saved, and Menu::InGameNotifier::ShowSaved().
     {
         if (message == MenuMessage::Saved)
             m_ingameNotifier.ShowSaved(2000);
         else if (message == MenuMessage::LostConnection)
             m_lostConnection = true;
     }
SpawnPlayers()
void MainMenu::SpawnPlayers () inline override private
Definition at line 144 of file MainMenu.as.
     {
     }
Start()
void MainMenu::Start (uint8 peer, SValue@ save, StartMode sMode) inline override private
Definition at line 136 of file MainMenu.as.
References TownRecord::Load(), HwrSaves::LoadLocalTown(), and m_town.
     {
         @m_town = TownRecord();
         m_town.Load(HwrSaves::LoadLocalTown());
         m_hostNgp = m_town.m_currentNgp;
     }
SystemMessage()
void MainMenu::SystemMessage (string name, SValue@ data) inline private
Definition at line 522 of file MainMenu.as.
References GameChatWidget::AddChat(), m_wChat, name, and SetLobbyData().
     {
         if (name == "AddChat")
         {
             if (m_wChat !is null)
                 m_wChat.AddChat(data.GetString());
         }
         else if (name == "SetNGP" && Network::IsServer())
             Lobby::SetLobbyData("ngp", data.GetInteger());
         else if (name == "SetDownscaling" && Network::IsServer())
             Lobby::SetLobbyData("downscaling", data.GetBoolean() ? "true" : "false");
     }
UpdateFrame()
void MainMenu::UpdateFrame (int ms, GameInput & gameInput, MenuInput & menuInput) inline override private
Definition at line 216 of file MainMenu.as.
References MenuProvider::GetCurrentMenu(), Hidden, m_frameCount, m_gameMenu, m_ingameChat, m_ingameNotifier, m_joinFailed, m_lostConnection, m_state, MainMenu(), BaseGameMode::ShowDialog(), DiscordPresence::Update(), Menu::InGameNotifier::Update(), MenuProvider::Update(), Menu::InGameChat::Update(), Update(), and BaseGameMode::UpdateFrame().
     {
         BaseGameMode::UpdateFrame(ms, gameInput, menuInput);
         Platform::Service.InMenus(true);
         if (m_state == MenuState::Hidden)
         {
             m_ingameNotifier.Update(ms);
             m_ingameChat.Update(ms, menuInput);
             return;
         }
 %PROFILE_START GameMenu Update
         m_gameMenu.Update(ms, gameInput, menuInput);
 %PROFILE_STOP
         if (m_lostConnection)
         {
             m_lostConnection = false;
             ShowDialog("connectionlost", Resources::GetString(".menu.notifier.lostconnection"), Resources::GetString(".menu.ok"), m_gameMenu.GetCurrentMenu());
         }
         if (m_joinFailed != -1)
         {
             string prompt = "join";
             if (m_joinFailed == 1)
                 prompt = "host";
             ShowDialog("joinfailed", Resources::GetString(".menu.notifier.joinfailed." + prompt), Resources::GetString(".menu.ok"), m_gameMenu.GetCurrentMenu());
             m_joinFailed = -1;
         }
         m_frameCount++;
         if (m_state == MenuState::MainMenu)
         {
             DiscordPresence::Update(ms);
             ServicePresence::Update(ms);
         }
     }
Member Data Documentation
m_expectingInput
MenuControlInputWidget MainMenu::m_expectingInput private
Definition at line 6 of file MainMenu.as.
m_frameCount
int MainMenu::m_frameCount private
Definition at line 33 of file MainMenu.as.
Referenced by GetCameraPos(), and UpdateFrame().
m_gameMenu
MenuProvider MainMenu::m_gameMenu private
Definition at line 15 of file MainMenu.as.
Referenced by GetServerlistMenu(), LoadMenu(), LobbyInviteAccepted(), MenuBack(), RenderFrame(), SetMenuState(), and UpdateFrame().
m_hostDownscaling
bool MainMenu::m_hostDownscaling private
Definition at line 27 of file MainMenu.as.
Referenced by LobbyCreated().
m_hostMaxLevel
pint MainMenu::m_hostMaxLevel private
Definition at line 24 of file MainMenu.as.
Referenced by LobbyCreated().
m_hostMaxPlayers
pint MainMenu::m_hostMaxPlayers private
Definition at line 23 of file MainMenu.as.
Referenced by LobbyCreated().
m_hostMinLevel
pint MainMenu::m_hostMinLevel private
Definition at line 25 of file MainMenu.as.
Referenced by LobbyCreated().
m_hostName
string MainMenu::m_hostName private
Definition at line 22 of file MainMenu.as.
Referenced by LobbyCreated().
m_hostNgp
pint MainMenu::m_hostNgp private
Definition at line 26 of file MainMenu.as.
Referenced by LobbyCreated().
m_hostPrivate
bool MainMenu::m_hostPrivate private
Definition at line 21 of file MainMenu.as.
Referenced by LobbyCreated().
m_ingameChat
Menu::InGameChat MainMenu::m_ingameChat private
Definition at line 10 of file MainMenu.as.
Referenced by LoadMenu(), RenderFrame(), SetMenuState(), and UpdateFrame().
m_ingameMenu
MenuProvider MainMenu::m_ingameMenu private
Definition at line 9 of file MainMenu.as.
Referenced by LoadMenu(), MainMenu(), MenuBack(), and SetMenuState().
m_ingameNotifier
Menu::InGameNotifier MainMenu::m_ingameNotifier private
Definition at line 11 of file MainMenu.as.
Referenced by MainMenu(), RenderFrame(), ShowMessage(), and UpdateFrame().
m_inviteAcceptID
uint64 MainMenu::m_inviteAcceptID private
Definition at line 29 of file MainMenu.as.
Referenced by LobbyInviteAccepted().
m_inviteAcceptMaxLevel
int MainMenu::m_inviteAcceptMaxLevel private
Definition at line 30 of file MainMenu.as.
Referenced by LobbyInviteAccepted().
m_inviteAcceptMinLevel
int MainMenu::m_inviteAcceptMinLevel private
Definition at line 31 of file MainMenu.as.
Referenced by LobbyInviteAccepted().
m_joinFailed
int MainMenu::m_joinFailed = -1 private
Definition at line 35 of file MainMenu.as.
Referenced by LobbyFailedJoin(), and UpdateFrame().
m_joiningMenu
Menu::JoiningLobbyMenu MainMenu::m_joiningMenu private
Definition at line 39 of file MainMenu.as.
Referenced by LobbyFailedJoin().
m_lostConnection
bool MainMenu::m_lostConnection private
Definition at line 34 of file MainMenu.as.
Referenced by UpdateFrame().
m_mainMenu
MenuProvider MainMenu::m_mainMenu private
Definition at line 8 of file MainMenu.as.
Referenced by LoadMenu(), MainMenu(), and SetMenuState().
m_musicInstance
SoundInstance MainMenu::m_musicInstance private
Definition at line 18 of file MainMenu.as.
Referenced by SetMenuState().
m_state
MenuState MainMenu::m_state private
Definition at line 16 of file MainMenu.as.
Referenced by MenuBack(), RenderFrame(), SetMenuState(), SetMenuState(), and UpdateFrame().
m_testLevel
bool MainMenu::m_testLevel private
Definition at line 20 of file MainMenu.as.
Referenced by LobbyCreated().
m_town
TownRecord MainMenu::m_town private
Definition at line 37 of file MainMenu.as.
Referenced by Start().
m_wChat
GameChatWidget MainMenu::m_wChat private
Definition at line 13 of file MainMenu.as.
Referenced by RemovePlayer(), and SystemMessage().
The documentation for this class was generated from the following file:
scripts/GameModes/MainMenu.as