HoHDocs: HWRGameOver Class Reference
HWRGameOver Class Reference
Private Member Functions
HWRGameOver (GUIBuilder@ b)
void OnFunc (Widget@ sender, string name) override
Detailed Description
Definition at line 1 of file HWRGameOver.as.
Constructor & Destructor Documentation
HWRGameOver()
HWRGameOver::HWRGameOver (GUIBuilder@ b) inline private
Definition at line 3 of file HWRGameOver.as.
     {
         super(b);
     }
Member Function Documentation
OnFunc()
void HWRGameOver::OnFunc (Widget@ sender, string name) inline override private
Definition at line 8 of file HWRGameOver.as.
References ChangeLevel(), g_gameMode, name, GameOver::OnFunc(), PauseGame(), AGameMode::ReplaceTopWidgetRoot(), and StopScenario().
     {
         if (name == "restart" && Network::IsServer())
         {
             ChangeLevel("levels/town_outlook.lvl");
         }
         else if (name == "exit")
         {
             PauseGame(false, false);
             StopScenario();
             return;
         }
         else if (name == "scoreclose")
             g_gameMode.ReplaceTopWidgetRoot(this);
         else
             GameOver::OnFunc(sender, name);
     }
The documentation for this class was generated from the following file:
scripts/GameModes/HWRGameOver.as