HoHDocs: Survival Class Reference
Survival Class Reference
Private Member Functions
Survival (Scene@ scene)
void Start (uint8 peer, SValue@ save, StartMode sMode) override
void UpdateFrame (int ms, GameInput &gameInput, MenuInput &menuInput) override
void RenderWidgets (PlayerRecord@ player, int idt, SpriteBatch &sb) override
void SetWave (WorldScript::SurvivalWave@ wave)
Private Attributes
HUDSurvival m_hudSurvival
array< SurvivalEnemySpawnPoint@> m_enemySpawns
int m_waveBest
int m_waveCount
SurvivalWaveProgress m_currWave
pfloat m_crowdValue = 50.0f
int m_crowdTime = 10000
int m_crowdTimeC
bool m_crowdPaused
uint64 m_crowdTimeElapsed
Detailed Description
Definition at line 2 of file Survival.as.
Constructor & Destructor Documentation
Survival()
Survival::Survival (Scene@ scene) inline private
Definition at line 22 of file Survival.as.
References Crowd::LoadActions(), m_crowdPaused, m_crowdTime, m_crowdTimeC, AGameMode::m_guiBuilder, and m_hudSurvival.
     {
         super(scene);
         AddVar("g_debug_crowd", false, null, cvar_flags::Cheat);
         Crowd::LoadActions("tweak/crowd.sval");
         m_crowdTimeC = m_crowdTime;
         m_crowdPaused = false;
         @m_hudSurvival = HUDSurvival(m_guiBuilder);
     }
Member Function Documentation
RenderWidgets()
void Survival::RenderWidgets (PlayerRecord@ player, int idt, SpriteBatch & sb) inline override private
Definition at line 100 of file Survival.as.
References m_hudSurvival, and Campaign::RenderWidgets().
     {
         Campaign::RenderWidgets(player, idt, sb);
         m_hudSurvival.Draw(sb, idt);
     }
SetWave()
void Survival::SetWave (WorldScript::SurvivalWave@ wave) inline private
Definition at line 107 of file Survival.as.
References m_currWave, m_waveBest, and m_waveCount.
Referenced by WorldScript::SurvivalWave::ClientExecute().
     {
         m_waveCount++;
         if (m_waveCount > m_waveBest)
             m_waveBest = m_waveCount;
         @m_currWave = SurvivalWaveProgress(wave);
     }
Start()
void Survival::Start (uint8 peer, SValue@ save, StartMode sMode) inline override private
Definition at line 36 of file Survival.as.
References Campaign::PostStart(), and Campaign::Start().
     {
         Campaign::Start(peer, save, sMode);
         Campaign::PostStart();
     }
UpdateFrame()
void Survival::UpdateFrame (int ms, GameInput & gameInput, MenuInput & menuInput) inline override private
Definition at line 42 of file Survival.as.
References Crowd::ClearDelta(), m_crowdPaused, m_crowdTime, m_crowdTimeC, m_crowdTimeElapsed, m_crowdValue, m_currWave, m_hudSurvival, max, min, WorldScript::TriggerGlobalEvent(), HUDSurvival::Update(), SurvivalWaveProgress::Update(), and Campaign::UpdateFrame().
     {
         Campaign::UpdateFrame(ms, gameInput, menuInput);
         bool debugCrowd = GetVarBool("g_debug_crowd");
         m_hudSurvival.Update(ms);
         if (m_currWave !is null)
             m_currWave.Update(ms);
         if (!m_crowdPaused)
         {
             m_crowdTimeElapsed += ms;
             m_crowdTimeC -= ms;
             if (m_crowdTimeC <= 0)
             {
                 m_crowdTimeC = m_crowdTime;
                 float delta = Crowd::ClearDelta();
                 if (debugCrowd)
                 {
                     if (delta < 0.0f)
                         print("D:");
                     else if (delta > 0.0f)
                         print(":D");
                     else
                         print(":|");
                 }
                 float valueBefore = m_crowdValue;
                 m_crowdValue = min(100.0f, max(0.0f, m_crowdValue + delta));
                 int showValue = int(round(m_crowdValue));
                 if (m_crowdValue != valueBefore)
                 {
                     if (showValue == 0)
                     {
                         if (debugCrowd)
                             print("boooooo");
                     }
                     else if (showValue == 100)
                     {
                         if (debugCrowd)
                             print("yeeeeee");
                     }
                 }
                 if (debugCrowd)
                     print("Crowd update: " + m_crowdValue + " (added " + delta + ")");
                 WorldScript::TriggerGlobalEvent("crowd_update");
             }
         }
     }
Member Data Documentation
m_crowdPaused
bool Survival::m_crowdPaused private
Definition at line 18 of file Survival.as.
Referenced by Survival(), and UpdateFrame().
m_crowdTime
int Survival::m_crowdTime = 10000 private
Definition at line 15 of file Survival.as.
Referenced by Survival(), and UpdateFrame().
m_crowdTimeC
int Survival::m_crowdTimeC private
Definition at line 16 of file Survival.as.
Referenced by Survival(), and UpdateFrame().
m_crowdTimeElapsed
uint64 Survival::m_crowdTimeElapsed private
Definition at line 20 of file Survival.as.
Referenced by UpdateFrame().
m_crowdValue
pfloat Survival::m_crowdValue = 50.0f private
Definition at line 13 of file Survival.as.
Referenced by UpdateFrame().
m_currWave
SurvivalWaveProgress Survival::m_currWave private
Definition at line 11 of file Survival.as.
Referenced by SetWave(), and UpdateFrame().
m_enemySpawns
array<SurvivalEnemySpawnPoint@> Survival::m_enemySpawns private
Definition at line 6 of file Survival.as.
m_hudSurvival
HUDSurvival Survival::m_hudSurvival private
Definition at line 4 of file Survival.as.
Referenced by RenderWidgets(), Survival(), and UpdateFrame().
m_waveBest
int Survival::m_waveBest private
Definition at line 8 of file Survival.as.
Referenced by SetWave().
m_waveCount
int Survival::m_waveCount private
Definition at line 9 of file Survival.as.
Referenced by SetWave().
The documentation for this class was generated from the following file:
scripts/GameModes/Survival.as