HoHDocs: BossLevel Class Reference
BossLevel Class Reference
Private Member Functions
BossLevel (Scene@ scene)
void Generate (SValue@ save)
void Start (uint8 peer, SValue@ save, StartMode sMode) override
Detailed Description
Definition at line 2 of file BossLevel.as.
Constructor & Destructor Documentation
BossLevel()
BossLevel::BossLevel (Scene@ scene) inline private
Definition at line 4 of file BossLevel.as.
     {
         super(scene);
     }
Member Function Documentation
Generate()
void BossLevel::Generate (SValue@ save) inline private
Definition at line 10 of file BossLevel.as.
 {}
Start()
void BossLevel::Start (uint8 peer, SValue@ save, StartMode sMode) inline override private
Definition at line 12 of file BossLevel.as.
References Stats::Add(), DiscordPresence::AddDetails(), CalcLevel(), DiscordPresence::Clear(), Continue, g_ngp, g_players, GetLocalPlayerRecord(), BaseGameMode::m_levelCount, Campaign::PostStart(), RichPresenceGetActName(), DiscordPresence::SetDetails(), DiscordPresence::SetLargeImageKey(), DiscordPresence::SetLargeImageText(), SetLevelFlags(), DiscordPresence::SetStartTimestamp(), DiscordPresence::SetState(), and Campaign::Start().
     {
         Campaign::Start(peer, save, sMode);
         SetLevelFlags(m_levelCount);
         Campaign::PostStart();
         Stats::Add("floors-visited", 1, GetLocalPlayerRecord());
         if (sMode == StartMode::Continue)
         {
             for (uint i = 0; i < g_players.length(); i++)
             {
                 if (g_players[i].peer == 255)
                     continue;
                 if (g_players[i].hp > 0)
                 {
                     g_players[i].hp = 1;
                     g_players[i].mana = 1;
                 }
             }
         }
         auto record = GetLocalPlayerRecord();
         auto levelInfo = CalcLevel(m_levelCount);
         DiscordPresence::Clear();
         DiscordPresence::SetState("In boss battle");
         DiscordPresence::SetDetails("Act " + (levelInfo.x + 1) + " floor " + (levelInfo.y + 1));
         if (g_ngp > 0)
             DiscordPresence::AddDetails(", NG+" + g_ngp);
         DiscordPresence::SetStartTimestamp(time() - record.statisticsSession.GetStatInt("time-played"));
         DiscordPresence::SetLargeImageKey("boss_" + levelInfo.x);
         DiscordPresence::SetLargeImageText(RichPresenceGetActName(m_levelCount));
         Platform::Service.ClearRichPresence();
         if (g_ngp == 0)
             Platform::Service.SetRichPresence("#Status_InBossBattle");
         else
         {
             Platform::Service.SetRichPresence("#Status_InBossBattle_NGP");
             Platform::Service.SetRichPresenceKey("ngp", "" + g_ngp);
         }
         Platform::Service.SetRichPresenceKey("level", "" + record.level);
         Platform::Service.SetRichPresenceKey("act", "" + (levelInfo.x + 1));
     }
The documentation for this class was generated from the following file:
scripts/GameModes/BossLevel.as