HoHDocs: TestLevel Class Reference
TestLevel Class Reference
Private Member Functions
TestLevel (Scene@ scene)
void Generate (SValue@ save)
void Start (uint8 peer, SValue@ save, StartMode sMode) override
Detailed Description
Definition at line 2 of file TestLevel.as.
Constructor & Destructor Documentation
TestLevel()
TestLevel::TestLevel (Scene@ scene) inline private
Definition at line 4 of file TestLevel.as.
     {
         super(scene);
     }
Member Function Documentation
Generate()
void TestLevel::Generate (SValue@ save) inline private
Definition at line 10 of file TestLevel.as.
 {}
Start()
void TestLevel::Start (uint8 peer, SValue@ save, StartMode sMode) inline override private
Definition at line 12 of file TestLevel.as.
References Stats::Add(), GetLocalPlayerRecord(), BaseGameMode::m_levelCount, Campaign::PostStart(), SetJoinable(), SetLevelFlags(), and Campaign::Start().
     {
         Campaign::Start(peer, save, sMode);
         SetLevelFlags(m_levelCount);
         Campaign::PostStart();
         Stats::Add("floors-visited", 1, GetLocalPlayerRecord());
         Lobby::SetJoinable(true);
     }
The documentation for this class was generated from the following file:
scripts/GameModes/TestLevel.as