HoHDocs: DialogWindow Class Reference
DialogWindow Class Reference
Private Member Functions
DialogWindow (GUIBuilder@ b)
bool BlocksLower () override
void SetID (string id)
void SetQuestion (string question)
void SetButtonYes (string yes)
void SetButtonNo (string no)
void SetInput (string defaultText)
void FocusInput ()
void SetReturnHost (IWidgetHoster@ returnHost)
void Update (int dt) override
void Draw (SpriteBatch &sb, int idt) override
void Close ()
void OnFunc (Widget@ sender, string name) override
Private Attributes
bool m_visible
string m_id
IWidgetHoster m_returnHost
string m_result
bool m_question
bool m_input
Detailed Description
Definition at line 1 of file Dialog.as.
Constructor & Destructor Documentation
DialogWindow()
DialogWindow::DialogWindow (GUIBuilder@ b) inline private
Definition at line 11 of file Dialog.as.
References LoadWidget(), and m_visible.
     {
         LoadWidget(b, "gui/dialogwindow.gui");
         m_visible = false;
     }
Member Function Documentation
BlocksLower()
bool DialogWindow::BlocksLower () inline override private
Definition at line 18 of file Dialog.as.
     {
         return true;
     }
Close()
void DialogWindow::Close () inline private
Definition at line 150 of file Dialog.as.
References g_gameMode, m_id, m_input, m_question, m_result, m_returnHost, m_visible, m_widget, and AGameMode::RemoveWidgetRoot().
Referenced by BaseGameMode::MenuBack(), and OnFunc().
     {
         m_visible = false;
         g_gameMode.RemoveWidgetRoot(this);
         if (m_returnHost is null)
             return;
         if (m_input)
         {
             if (m_result == "yes")
             {
                 auto wInput = cast<TextInputWidget>(m_widget.GetWidgetById("input"));
                 m_returnHost.OnFunc(wInput, m_id);
             }
         }
         else if (m_question)
             m_returnHost.OnFunc(null, m_id + " " + m_result);
         else
             m_returnHost.OnFunc(null, m_id);
     }
Draw()
void DialogWindow::Draw (SpriteBatch & sb, int idt) inline override private
Definition at line 144 of file Dialog.as.
References Draw(), and m_visible.
Referenced by MenuProvider::Render(), MainMenu::RenderFrame(), and BaseGameMode::RenderWidgets().
     {
         if (m_visible)
             IWidgetHoster::Draw(sb, idt);
     }
FocusInput()
void DialogWindow::FocusInput () inline private
Definition at line 120 of file Dialog.as.
References g_gameMode, and m_widget.
Referenced by BaseGameMode::ShowInputDialog().
     {
         auto wInput = cast<TextInputWidget>(m_widget.GetWidgetById("input"));
         if (wInput is null)
             return;
         auto gm = cast<BaseGameMode>(g_gameMode);
         if (gm !is null)
             @gm.m_widgetInputFocus = wInput;
     }
OnFunc()
void DialogWindow::OnFunc (Widget@ sender, string name) inline override private
Definition at line 173 of file Dialog.as.
References Close(), m_result, name, and Menu::OnFunc().
     {
         m_result = name;
         Close();
         IWidgetHoster::OnFunc(sender, name);
     }
SetButtonNo()
void DialogWindow::SetButtonNo (string no) inline private
Definition at line 73 of file Dialog.as.
References DoLayout(), m_input, and m_widget.
Referenced by BaseGameMode::ShowDialog().
     {
         m_input = false;
         auto wNo = cast<ScalableSpriteButtonWidget>(m_widget.GetWidgetById("no"));
         if (wNo is null)
             return;
         wNo.m_visible = true;
         wNo.SetText(no);
         DoLayout();
     }
SetButtonYes()
void DialogWindow::SetButtonYes (string yes) inline private
Definition at line 44 of file Dialog.as.
References DoLayout(), m_input, m_question, and m_widget.
Referenced by BaseGameMode::ShowDialog().
     {
         m_input = false;
         auto wInput = cast<TextInputWidget>(m_widget.GetWidgetById("input"));
         if (wInput !is null)
             wInput.m_parent.m_visible = false;
         auto wYes = cast<ScalableSpriteButtonWidget>(m_widget.GetWidgetById("yes"));
         if (wYes !is null)
         {
             auto wNo = cast<ScalableSpriteButtonWidget>(m_widget.GetWidgetById("no"));
             if (yes == "")
             {
                 wYes.m_visible = false;
                 m_question = false;
             }
             else
             {
                 m_question = true;
                 wYes.m_visible = true;
                 wYes.SetText(yes);
             }
             DoLayout();
         }
     }
SetID()
void DialogWindow::SetID (string id) inline private
Definition at line 23 of file Dialog.as.
References id, m_id, and m_result.
Referenced by BaseGameMode::ShowDialog(), and BaseGameMode::ShowInputDialog().
     {
         m_id = id;
         m_result = "cancel";
     }
SetInput()
void DialogWindow::SetInput (string defaultText) inline private
Definition at line 87 of file Dialog.as.
References DoLayout(), m_input, m_question, and m_widget.
Referenced by BaseGameMode::ShowInputDialog().
     {
         m_question = false;
         m_input = true;
         auto wYes = cast<ScalableSpriteButtonWidget>(m_widget.GetWidgetById("yes"));
         if (wYes !is null)
         {
             wYes.m_visible = true;
             wYes.SetText(Resources::GetString(".menu.accept"));
         }
         auto wNo = cast<ScalableSpriteButtonWidget>(m_widget.GetWidgetById("no"));
         if (wNo !is null)
         {
             wNo.m_visible = true;
             wNo.SetText(Resources::GetString(".menu.cancel"));
         }
         auto wInput = cast<TextInputWidget>(m_widget.GetWidgetById("input"));
         if (wInput !is null)
         {
             wInput.m_parent.m_visible = true;
             wInput.m_text = defaultText;
             wInput.UpdateText();
             wInput.m_cursorPos = defaultText.length();
             wInput.UpdateCursorPos();
             wInput.m_drawOffset = 0;
         }
         DoLayout();
     }
SetQuestion()
void DialogWindow::SetQuestion (string question) inline private
Definition at line 29 of file Dialog.as.
References DoLayout(), m_input, and m_widget.
Referenced by BaseGameMode::ShowDialog(), and BaseGameMode::ShowInputDialog().
     {
         auto wQuestion = cast<TextWidget>(m_widget.GetWidgetById("question"));
         if (wQuestion !is null)
         {
             if (m_input)
                 wQuestion.m_anchor.y = 0.3;
             else
                 wQuestion.m_anchor.y = 0.5;
             wQuestion.SetText(question);
         }
         DoLayout();
     }
SetReturnHost()
void DialogWindow::SetReturnHost (IWidgetHoster@ returnHost) inline private
Definition at line 131 of file Dialog.as.
References m_returnHost.
Referenced by BaseGameMode::ShowDialog(), and BaseGameMode::ShowInputDialog().
     {
         @m_returnHost = returnHost;
     }
Update()
void DialogWindow::Update (int dt) inline override private
Definition at line 136 of file Dialog.as.
References m_visible, and Update().
Referenced by BaseGameMode::UpdateWidgets().
     {
         if (!m_visible)
             return;
         IWidgetHoster::Update(dt);
     }
Member Data Documentation
m_id
string DialogWindow::m_id private
Definition at line 5 of file Dialog.as.
Referenced by Close(), and SetID().
m_input
bool DialogWindow::m_input private
Definition at line 9 of file Dialog.as.
Referenced by Close(), SetButtonNo(), SetButtonYes(), SetInput(), and SetQuestion().
m_question
bool DialogWindow::m_question private
Definition at line 8 of file Dialog.as.
Referenced by Close(), SetButtonYes(), and SetInput().
m_result
string DialogWindow::m_result private
Definition at line 7 of file Dialog.as.
Referenced by Close(), OnFunc(), and SetID().
m_returnHost
IWidgetHoster DialogWindow::m_returnHost private
Definition at line 6 of file Dialog.as.
Referenced by Close(), and SetReturnHost().
m_visible
bool DialogWindow::m_visible private
Definition at line 3 of file Dialog.as.
Referenced by Close(), DialogWindow(), Draw(), BaseGameMode::MenuBack(), MainMenu::RenderFrame(), BaseGameMode::ShouldDisplayCursor(), BaseGameMode::ShouldFreezeControls(), BaseGameMode::ShowDialog(), BaseGameMode::ShowInputDialog(), and Update().
The documentation for this class was generated from the following file:
scripts/GUI/Dialog.as