HoHDocs: ClipWidget Class Reference
ClipWidget Class Reference
Private Member Functions
ClipWidget ()
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void Draw (SpriteBatch &sb, bool debugDraw=false) override
void DrawChildren (SpriteBatch &sb, bool debugDraw=false) override
Private Attributes
bool m_clipping = true
vec4 m_clipPadding
Detailed Description
Definition at line 1 of file ClipWidget.as.
Constructor & Destructor Documentation
ClipWidget()
ClipWidget::ClipWidget () inline private
Definition at line 6 of file ClipWidget.as.
Referenced by Clone().
     {
         super();
     }
Member Function Documentation
Clone()
Widget ClipWidget::Clone () inline override private
Definition at line 11 of file ClipWidget.as.
References ClipWidget(), and Widget::CloneInto().
     {
         ClipWidget@ w = ClipWidget();
         CloneInto(w);
         return w;
     }
Draw()
void ClipWidget::Draw (SpriteBatch & sb, bool debugDraw = false) inline override private
Definition at line 28 of file ClipWidget.as.
References Widget::Draw(), Widget::GetOrigin(), m_clipping, Widget::m_height, and Widget::m_width.
     {
         if (m_clipping)
         {
             vec2 origin = GetOrigin();
             sb.PushClipping(vec4(
                 origin.x, origin.y,
                 m_width, m_height
             ));
         }
         Widget::Draw(sb, debugDraw);
         if (m_clipping)
             sb.PopClipping();
     }
DrawChildren()
void ClipWidget::DrawChildren (SpriteBatch & sb, bool debugDraw = false) inline override private
Definition at line 46 of file ClipWidget.as.
References Widget::DrawChildren(), Widget::GetOrigin(), Widget::m_children, m_clipPadding, m_clipping, Widget::m_height, and Widget::m_width.
     {
         bool useDoubleClipping = (m_clipping && lengthsq(m_clipPadding) > 0 && m_children.length() > 0);
         if (useDoubleClipping)
         {
             vec2 origin = GetOrigin();
             sb.PushClipping(vec4(
                 origin.x + m_clipPadding.x,
                 origin.y + m_clipPadding.y,
                 m_width - m_clipPadding.x - m_clipPadding.z,
                 m_height - m_clipPadding.y - m_clipPadding.w
             ));
         }
         Widget::DrawChildren(sb, debugDraw);
         if (useDoubleClipping)
             sb.PopClipping();
     }
Load()
void ClipWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 18 of file ClipWidget.as.
References Widget::Load(), Widget::LoadWidthHeight(), m_clipPadding, and m_clipping.
Referenced by LoadClipWidget().
     {
         m_clipping = ctx.GetBoolean("clipping", false, m_clipping);
         m_clipPadding = ctx.GetVector4("clippadding", false);
         LoadWidthHeight(ctx, false);
         Widget::Load(ctx);
     }
Member Data Documentation
m_clipPadding
vec4 ClipWidget::m_clipPadding private
Definition at line 4 of file ClipWidget.as.
Referenced by DrawChildren(), and Load().
m_clipping
bool ClipWidget::m_clipping = true private
Definition at line 3 of file ClipWidget.as.
Referenced by Draw(), DrawChildren(), FilteredListWidget::Load(), Load(), and CheckBoxGroupWidget::Load().
The documentation for this class was generated from the following file:
scripts/GUI/ClipWidget.as