HoHDocs: ColorCheckBoxWidget Class Reference
ColorCheckBoxWidget Class Reference
Private Member Functions
ColorCheckBoxWidget ()
void Load (WidgetLoadingContext &ctx) override
void DoDraw (SpriteBatch &sb, vec2 pos) override
Private Attributes
vec4 m_fillColor
Detailed Description
Definition at line 1 of file ColorCheckBox.as.
Constructor & Destructor Documentation
ColorCheckBoxWidget()
ColorCheckBoxWidget::ColorCheckBoxWidget () inline private
Definition at line 5 of file ColorCheckBox.as.
     {
         super();
     }
Member Function Documentation
DoDraw()
void ColorCheckBoxWidget::DoDraw (SpriteBatch & sb, vec2 pos) inline override private
Definition at line 17 of file ColorCheckBox.as.
References CheckBoxWidget::DoDraw(), m_fillColor, Widget::m_height, and Widget::m_width.
     {
         sb.FillRectangle(vec4(
             pos.x, pos.y,
             m_width, m_height
         ), m_fillColor);
         CheckBoxWidget::DoDraw(sb, pos);
     }
Load()
void ColorCheckBoxWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 10 of file ColorCheckBox.as.
References Widget::Load(), and m_fillColor.
Referenced by LoadColorCheckboxWidget().
     {
         CheckBoxWidget::Load(ctx);
         m_fillColor = ctx.GetColorRGBA("fill-color", false, vec4(0, 0, 0, 1));
     }
Member Data Documentation
m_fillColor
vec4 ColorCheckBoxWidget::m_fillColor private
Definition at line 3 of file ColorCheckBox.as.
Referenced by DoDraw(), and Load().
The documentation for this class was generated from the following file:
scripts/GUI/ColorCheckBox.as