HoHDocs: PyramidFancyBrush Class Reference
PyramidFancyBrush Class Reference
Private Member Functions
PyramidFancyBrush ()
bool SpawnTorchDeco (Scene@ scene, vec3 pos, int x, int y) override
void SpawnBreakable (Scene@ scene, vec3 pos)
void SpawnHorizontalWallDeco (Scene@ scene, vec3 pos, int x, int y) override
void SpawnHorizontalWall2Deco (Scene@ scene, vec3 pos, int x, int y) override
void SpawnCornerSEWallDeco (Scene@ scene, vec3 pos, int x, int y) override
void SpawnCornerSWWallDeco (Scene@ scene, vec3 pos, int x, int y) override
bool CanUseBreakables (int x, int y)
bool IsFloorOrBreakables (int x, int y)
void Build (Scene@ scene) override
Private Attributes
UnitProducer m_torch
array< UnitProducer@> m_deco_wall
array< UnitProducer@> m_deco_wall_small
array< UnitProducer@> m_breakables
array< UnitPtr > m_spawnedDeco
array< UnitPtr > m_spawnedTorches
Detailed Description
Definition at line 1 of file PyramidFancyBrush.as.
Constructor & Destructor Documentation
PyramidFancyBrush()
PyramidFancyBrush::PyramidFancyBrush () inline private
Definition at line 13 of file PyramidFancyBrush.as.
References LoadPrefabs(), m_breakables, m_deco_wall, m_deco_wall_small, and m_torch.
     {
         super();
         @m_torch = Resources::GetUnitProducer("doodads/generic/lamp_torch.unit");
         m_deco_wall.insertLast(Resources::GetUnitProducer("doodads/walls/pyramid_fancy/_deco_h_crack_1.unit"));
         m_deco_wall.insertLast(Resources::GetUnitProducer("doodads/walls/pyramid_fancy/_deco_h_crack_2.unit"));
         m_deco_wall.insertLast(Resources::GetUnitProducer("doodads/walls/pyramid_fancy/_deco_h_crack_3.unit"));
         m_deco_wall.insertLast(Resources::GetUnitProducer("doodads/walls/pyramid_fancy/_deco_h_crack_4.unit"));
         m_deco_wall.insertLast(Resources::GetUnitProducer("doodads/walls/pyramid_fancy/_deco_h_pillar_large.unit"));
         m_deco_wall.insertLast(Resources::GetUnitProducer("doodads/walls/pyramid_fancy/_deco_h_pillar_medium.unit"));
         m_deco_wall_small.insertLast(Resources::GetUnitProducer("doodads/walls/pyramid_fancy/_deco_h_pillar_small.unit"));
         m_breakables.insertLast(Resources::GetUnitProducer("doodads/generic/container_barrel_b.unit"));
         m_breakables.insertLast(Resources::GetUnitProducer("doodads/generic/container_crate_b.unit"));
         m_breakables.insertLast(Resources::GetUnitProducer("doodads/generic/container_vase.unit"));
         LoadPrefabs("pyramid_fancy");
     }
Member Function Documentation
Build()
void PyramidFancyBrush::Build (Scene@ scene) inline override private
Definition at line 99 of file PyramidFancyBrush.as.
References Breakables, Bridge, CanUseBreakables(), Cliff, DoLighting(), FillCellCliff(), FillCellMaggotEnemies(), FillCellNothing(), FillCellWall(), Floor, GetCell(), IsCliff(), IsFloorOrBreakables(), IsWallOrBreakable(), LoadBaseBrushTiles(), m_grid, m_gridConsumed, m_height, m_posOffset, m_spawnedDeco, m_spawnedTorches, Skills::m_width, MaggotEnemies, MakeSpread(), max, Nothing, PlacePaddingColor(), RemoveNearby(), RemoveNearbySame(), Reserved, SpawnBreakable(), SpawnPointsOfInterest(), and Wall.
     {
         auto bt = LoadBaseBrushTiles("pyramid_fancy");
         auto arch = Resources::GetUnitProducer("doodads/walls/pyramid_fancy/_deco_ceiling_support.unit");
         auto reserved = Resources::GetUnitProducer("doodads/special/color_archives_16.unit");
         SpawnPointsOfInterest(scene);
         auto t_default = Resources::GetTileset("tilesets/pyramid_slum_default.tileset");
         auto t_dirt = Resources::GetTileset("tilesets/pyramid_fancy_default.tileset");
         auto t_default_grass = Resources::GetTileset("tilesets/pyramid_fancy_symbols.tileset");
         scene.PaintTileset(t_default, m_posOffset + vec2(m_width * 8, m_height * 8), uint(max(m_width * 16, m_height * 16) * 1.5));
         for (int y = 0; y < m_height; y++)
         {
             for (int x = 0; x < m_width; x++)
             {
                 vec2 pos(16 * x + m_posOffset.x, 16 * y + m_posOffset.y);
                 auto cell = m_grid[x][y];
                 if(cell == Cell::Enemies || cell == Cell::MaggotEnemies)
                 {
                     if (randi(100) < 50)
                         scene.PaintTileset(t_dirt, pos, 24 + randi(32));
                 }
                 else if(cell == Cell::Reserved)
                 {
                     if (randi(100) < 15)
                         scene.PaintTileset(t_default_grass, pos, 16);
                     else if (randi(100) < 10)
                         scene.PaintTileset(t_dirt, pos, 24 + randi(32));
                 }
                 else if(cell == Cell::Floor || cell == Cell::Breakables)
                 {
                     if (randi(100) < 15)
                         scene.PaintTileset(t_dirt, pos, 24 + randi(24));
                     if (IsCliff(x -1, y) || IsCliff(x +1, y) || IsCliff(x, y -1) || IsCliff(x, y +1))
                         continue;
                     int wl = 0;
                     if (CanUseBreakables(x - 1, y - 1)) wl++;
                     if (CanUseBreakables(x, y - 1)) wl++;
                     if (CanUseBreakables(x + 1, y - 1)) wl++;
                     if (CanUseBreakables(x - 1, y)) wl++;
                     if (CanUseBreakables(x + 1, y)) wl++;
                     if (CanUseBreakables(x - 1, y + 1)) wl++;
                     if (CanUseBreakables(x, y + 1)) wl++;
                     if (CanUseBreakables(x + 1, y + 1)) wl++;
                     if (CanUseBreakables(x + 2, y)) wl++;
                     if (CanUseBreakables(x - 2, y)) wl++;
                     if (CanUseBreakables(x, y + 2)) wl++;
                     if (CanUseBreakables(x, y - 2)) wl++;
                     if (randi(100) < (10 + wl * 10))
                         scene.PaintTileset(t_default_grass, pos, 16);
                 }
             }
         }
         DoLighting(scene, "pyramid_fancy", 100);
         for (int y = 0; y < m_height; y++)
         {
             for (int x = 0; x < m_width; x++)
             {
                 if (m_gridConsumed[x][y])
                     continue;
                 auto cell = m_grid[x][y];
                 if(cell == Cell::Nothing)
                     FillCellNothing(scene, bt, x, y);
                 else if(cell == Cell::Wall)
                     FillCellWall(scene, bt, x, y);
                 else if(cell == Cell::Cliff)
                     FillCellCliff(scene, bt, x, y);
                 else if (cell == Cell::MaggotEnemies)
                     FillCellMaggotEnemies(scene, bt, x, y);
                 else if (cell == Cell::Floor)
                 {
                     if (randi(100) < 33 && GetCell(x - 1, y) == Cell::Wall && GetCell(x + 2, y) == Cell::Wall &&
                         IsFloorOrBreakables(x + 1, y) && IsFloorOrBreakables(x, y + 1) && IsFloorOrBreakables(x + 1, y + 1))
                         m_spawnedDeco.insertLast(arch.Produce(scene, vec3(16 * x + m_posOffset.x + 16, 16 * y + m_posOffset.y, 0)));
                     m_gridConsumed[x][y] = true;
                 }
                 else if(cell == Cell::Breakables)
                 {
                     bool q1, q2, q3, q4;
                     q1 = q2 = q3 = q4 = false;
                     if (IsWallOrBreakable(x, y -1))
                         q1 = q2 = true;
                     if (IsWallOrBreakable(x, y +1))
                         q3 = q4 = true;
                     if (IsWallOrBreakable(x -1, y))
                         q1 = q3 = true;
                     if (IsWallOrBreakable(x +1, y))
                         q2 = q4 = true;
                     m_gridConsumed[x][y] = true;
                     vec3 midPos = vec3(16 * x + m_posOffset.x + 8, 16 * y + m_posOffset.y + 8, 0);
                     if (!q1 && !q2 && !q3 && !q4)
                         SpawnBreakable(scene, midPos + MakeSpread(4, 4));
                     if (randi(100) < 50)
                     {
                         if (q1 != q2 || (randi(100) < 90 && q1))
                             SpawnBreakable(scene, midPos + vec3(-3, -4, 0) + MakeSpread(2, 0));
                         else if (q1)
{
                             SpawnBreakable(scene, midPos + vec3(-4, -4, 0));
                             SpawnBreakable(scene, midPos + vec3(4, -4, 0));
                         }
                         if (q3 != q4 || (randi(100) < 90 && q3))
                             SpawnBreakable(scene, midPos + vec3(3, 4, 0) + MakeSpread(2, 0));
                         else if (q3)
{
                             SpawnBreakable(scene, midPos + vec3(-4, 4, 0));
                             SpawnBreakable(scene, midPos + vec3(4, 4, 0));
                         }
                     }
                     else
                     {
                         if (q1 != q3 || (randi(100) < 90 && q1))
                             SpawnBreakable(scene, midPos + vec3(-4, -3, 0) + MakeSpread(0, 2));
                         else if (q1)
{
                             SpawnBreakable(scene, midPos + vec3(-4, -4, 0));
                             SpawnBreakable(scene, midPos + vec3(-4, 4, 0));
                         }
                         if (q2 != q4 || (randi(100) < 90 && q3))
                             SpawnBreakable(scene, midPos + vec3(4, 3, 0) + MakeSpread(0, 2));
                         else if (q2)
{
                             SpawnBreakable(scene, midPos + vec3(4, -4, 0));
                             SpawnBreakable(scene, midPos + vec3(4, 4, 0));
                         }
                     }
                 }
                 else if (cell == Cell::Bridge)
                 {
                     /*
                     vec3 pos = vec3(16 * x + m_posOffset.x, 16 * y + m_posOffset.y, 0);
                     reserved.Produce(scene, pos);
                     */
                     m_gridConsumed[x][y] = true;
                 }
                 else if (cell == Cell::Reserved)
                 {
                     vec3 pos = vec3(16 * x + m_posOffset.x, 16 * y + m_posOffset.y, 0);
                     reserved.Produce(scene, pos);
                     m_gridConsumed[x][y] = true;
                 }
             }
         }
         PlacePaddingColor(scene, bt);
         RemoveNearbySame(m_spawnedDeco, 50);
         m_spawnedDeco = array<UnitPtr>();
         RemoveNearby(m_spawnedTorches, 125);
         m_spawnedTorches = array<UnitPtr>();
     }
CanUseBreakables()
bool PyramidFancyBrush::CanUseBreakables (int x, int y) inline private
Definition at line 86 of file PyramidFancyBrush.as.
References Breakables, m_grid, m_gridConsumed, m_height, and Skills::m_width.
Referenced by Build().
     {
         if (x < 0 || y < 0 || x >= m_width || y >= m_height)
             return false;
         return !m_gridConsumed[x][y] && m_grid[x][y] == Cell::Breakables;
     }
IsFloorOrBreakables()
bool PyramidFancyBrush::IsFloorOrBreakables (int x, int y) inline private
Definition at line 93 of file PyramidFancyBrush.as.
References Breakables, Floor, and GetCell().
Referenced by Build().
     {
         auto cell = GetCell(x, y);
         return cell == Cell::Breakables || cell == Cell::Floor;
     }
SpawnBreakable()
void PyramidFancyBrush::SpawnBreakable (Scene@ scene, vec3 pos) inline private
Definition at line 47 of file PyramidFancyBrush.as.
References m_breakables.
Referenced by Build().
     {
         m_breakables[randi(m_breakables.length())].Produce(scene, pos);
     }
SpawnCornerSEWallDeco()
void PyramidFancyBrush::SpawnCornerSEWallDeco (Scene@ scene, vec3 pos, int x, int y) inline override private
Definition at line 76 of file PyramidFancyBrush.as.
References SpawnTorchDeco().
     {
         SpawnTorchDeco(scene, pos + vec3(8, 0, 0), x, y);
     }
SpawnCornerSWWallDeco()
void PyramidFancyBrush::SpawnCornerSWWallDeco (Scene@ scene, vec3 pos, int x, int y) inline override private
Definition at line 81 of file PyramidFancyBrush.as.
References SpawnTorchDeco().
     {
         SpawnTorchDeco(scene, pos + vec3(8, 0, 0), x, y);
     }
SpawnHorizontalWall2Deco()
void PyramidFancyBrush::SpawnHorizontalWall2Deco (Scene@ scene, vec3 pos, int x, int y) inline override private
Definition at line 64 of file PyramidFancyBrush.as.
References IsOpen(), m_deco_wall, m_spawnedDeco, and SpawnTorchDeco().
     {
         if (!IsOpen(x, y + 1))
             return;
         if (randi(100) < 50 && SpawnTorchDeco(scene, pos + vec3(16, 0, 0), x, y))
             return;
         //if (randi(100) < 75)
             m_spawnedDeco.insertLast(m_deco_wall[randi(m_deco_wall.length())].Produce(scene, pos + vec3(16, 16, 0)));
     }
SpawnHorizontalWallDeco()
void PyramidFancyBrush::SpawnHorizontalWallDeco (Scene@ scene, vec3 pos, int x, int y) inline override private
Definition at line 52 of file PyramidFancyBrush.as.
References IsOpen(), m_deco_wall_small, m_spawnedDeco, and SpawnTorchDeco().
     {
         if (!IsOpen(x, y + 1))
             return;
         if (SpawnTorchDeco(scene, pos + vec3(8, 0, 0), x, y))
             return;
         //if (randi(100) < 75)
             m_spawnedDeco.insertLast(m_deco_wall_small[randi(m_deco_wall_small.length())].Produce(scene, pos + vec3(8, 16, 0)));
     }
SpawnTorchDeco()
bool PyramidFancyBrush::SpawnTorchDeco (Scene@ scene, vec3 pos, int x, int y) inline override private
Definition at line 35 of file PyramidFancyBrush.as.
References IsOpen(), m_spawnedTorches, and m_torch.
Referenced by SpawnCornerSEWallDeco(), SpawnCornerSWWallDeco(), SpawnHorizontalWall2Deco(), and SpawnHorizontalWallDeco().
     {
         if (!IsOpen(x, y + 1))
             return false;
         if (randi(100) < 66)
             return false;
         m_spawnedTorches.insertLast(m_torch.Produce(scene, pos + vec3(0, 16, 0)));
         return true;
     }
Member Data Documentation
m_breakables
array<UnitProducer@> PyramidFancyBrush::m_breakables private
Definition at line 7 of file PyramidFancyBrush.as.
Referenced by PyramidFancyBrush(), and SpawnBreakable().
m_deco_wall
array<UnitProducer@> PyramidFancyBrush::m_deco_wall private
Definition at line 4 of file PyramidFancyBrush.as.
Referenced by PyramidFancyBrush(), and SpawnHorizontalWall2Deco().
m_deco_wall_small
array<UnitProducer@> PyramidFancyBrush::m_deco_wall_small private
Definition at line 5 of file PyramidFancyBrush.as.
Referenced by PyramidFancyBrush(), and SpawnHorizontalWallDeco().
m_spawnedDeco
array<UnitPtr> PyramidFancyBrush::m_spawnedDeco private
Definition at line 9 of file PyramidFancyBrush.as.
Referenced by Build(), SpawnHorizontalWall2Deco(), and SpawnHorizontalWallDeco().
m_spawnedTorches
array<UnitPtr> PyramidFancyBrush::m_spawnedTorches private
Definition at line 10 of file PyramidFancyBrush.as.
Referenced by Build(), and SpawnTorchDeco().
m_torch
UnitProducer PyramidFancyBrush::m_torch private
Definition at line 3 of file PyramidFancyBrush.as.
Referenced by PyramidFancyBrush(), and SpawnTorchDeco().
The documentation for this class was generated from the following file:
scripts/Generators/PyramidFancyBrush.as