HoHDocs: PyramidGenerator Class Reference
PyramidGenerator Class Reference
Private Member Functions
void FinalizeRoom (ivec2 tl, ivec2 br) override
void PlaceBreakables () override
float MakeInitialState (array< ivec2 >@ junctions, array< ivec2 >@ rooms) override
bool PlacePrefabs (PrefabPlacement@ placer) override
Detailed Description
Definition at line 2 of file PyramidGenerator.as.
Member Function Documentation
FinalizeRoom()
void PyramidGenerator::FinalizeRoom (ivec2 tl, ivec2 br) inline override private
Definition at line 4 of file PyramidGenerator.as.
     {
     }
MakeInitialState()
float PyramidGenerator::MakeInitialState (array< ivec2 >@ junctions, array< ivec2 >@ rooms) inline override private
Definition at line 16 of file PyramidGenerator.as.
References MinesGenerator::Height, MinesGenerator::TryMakeRoom(), and MinesGenerator::Width.
     {
         int w = Width / 16;
         int h = Height / 16;
         TryMakeRoom(junctions, ivec2(w / 2, h / 2), 14, 16);
         rooms.insertLast(ivec2(w / 2, h / 2));
         return 1.f;
     }
PlaceBreakables()
void PyramidGenerator::PlaceBreakables () inline override private
Definition at line 8 of file PyramidGenerator.as.
References MinesGenerator::Height, PlaceCrateBreakables(), and MinesGenerator::Width.
     {
         int w = Width / 16;
         int h = Height / 16;
         PlaceCrateBreakables(w, h);
     }
PlacePrefabs()
bool PyramidGenerator::PlacePrefabs (PrefabPlacement@ placer) inline override private
Definition at line 27 of file PyramidGenerator.as.
References MinesGenerator::FillDeadEnds(), g_ngp, m_brush, MinesGenerator::NumDeadEndsFill, Prefab10x10North2, Prefab10x10South2, Prefab13x13Block, Prefab13x13North, Prefab2x3Junction, Prefab2x6Path, Prefab3x3Block, Prefab3x3Cliff, Prefab3x3North, Prefab5x5Block, Prefab5x5BlockNorth, Prefab5x5BlockSouth, Prefab5x5East, Prefab5x5North, Prefab5x5West, Prefab5x6BlockEast, Prefab5x6BlockWest, Prefab6x3Path, Prefab6x6North2, Prefab6x6South2, Prefab7x7Block, Prefab9x3Cliff, Prefab9x9Block, Prefab9x9East, Prefab9x9North, and Prefab9x9West.
     {
         array<PointOfInterestType> specials = {
             PointOfInterestType::Prefab13x13North,
             PointOfInterestType::Prefab9x9North,
             PointOfInterestType::Prefab5x5North,
             PointOfInterestType::Prefab3x3North
             //PointOfInterestType::Prefab9x9South,
             //PointOfInterestType::Prefab5x5South
         };
         placer.PlacePrefabs(specials, 2);
         array<PointOfInterestType> rooms = {
             PointOfInterestType::Prefab10x10North2,
             PointOfInterestType::Prefab10x10South2,
             PointOfInterestType::Prefab6x6North2,
             PointOfInterestType::Prefab6x6South2,
             PointOfInterestType::Prefab9x9East,
             PointOfInterestType::Prefab5x5East,
             PointOfInterestType::Prefab9x9West,
             PointOfInterestType::Prefab5x5West
         };
         placer.PlacePrefabs(rooms, 11, 3);
         placer.PlacePrefab(PointOfInterestType::Prefab13x13Block, 1);
         placer.PlacePrefab(PointOfInterestType::Prefab9x9Block, 1);
         bool valid = false;
         valid = (placer.PlacePrefab(PointOfInterestType::Prefab7x7Block, 2 + g_ngp) > 0) || valid;
         valid = (placer.PlacePrefab(PointOfInterestType::Prefab5x5Block, 3 + g_ngp) > 0) || valid;
         valid = (placer.PlacePrefab(PointOfInterestType::Prefab3x3Block, 4 + g_ngp) > 0) || valid;
         if (!m_brush.HasPointOfInterest(PointOfInterestType::Prefab7x7Block) &&
             !m_brush.HasPointOfInterest(PointOfInterestType::Prefab5x5Block) &&
             !m_brush.HasPointOfInterest(PointOfInterestType::Prefab3x3Block))
             valid = true;
         if (!valid)
             return false;
         FillDeadEnds(placer.m_ptrnMtch, m_brush, NumDeadEndsFill);
         placer.PlacePrefab(PointOfInterestType::Prefab2x6Path, 3 + g_ngp);
         placer.PlacePrefab(PointOfInterestType::Prefab6x3Path, 3 + g_ngp);
         placer.PlacePrefab(PointOfInterestType::Prefab2x3Junction, 3 + g_ngp);
         array<PointOfInterestType> wallBlocks = {
             PointOfInterestType::Prefab5x5BlockNorth,
             PointOfInterestType::Prefab5x5BlockSouth,
             PointOfInterestType::Prefab5x6BlockEast,
             PointOfInterestType::Prefab5x6BlockWest
         };
         placer.PlacePrefabs(wallBlocks, 6 + g_ngp * 2, 2 + g_ngp);
         if (randi(2) == 0)
             placer.PlacePrefab(PointOfInterestType::Prefab9x3Cliff, 1);
         else
             placer.PlacePrefab(PointOfInterestType::Prefab3x9Cliff, 1);
         placer.PlacePrefab(PointOfInterestType::Prefab3x3Cliff, 3);
         return true;
     }
The documentation for this class was generated from the following file:
scripts/Generators/PyramidGenerator.as