HoHDocs: EnemyPlacement Class Reference
EnemyPlacement Class Reference
Private Member Functions
EnemyPlacement ()
EnemyPlacement (Enemies enemies, bool spawners, bool elites, bool minibosses)
void AddEnemyGroup (EnemySetting setting)
void Initialize (ivec2 dungeonEntrance)
void RemovePoint (DungeonBrush@ brush, Cell cellType, array< ivec2 >@ group, int x, int y)
vec3 MakeSpread (int x, int y)
vec3 MakeDir (int r)
void SpawnGroup (Scene@ scene, vec3 pos, int radius, EnemyGroupSetting@ groupSetting)
void SpawnGroup (Scene@ scene, DungeonBrush@ brush, array< ivec2 >@ group, EnemyGroupSetting@ groupSetting)
void Place (Scene@ scene, DungeonBrush@ brush, array< array< ivec2 >@> groups)
void PlaceGroup (Scene@ scene, vec2 pos, int radius)
Private Attributes
array< EnemySetting@> m_enemyTypes
ivec2 m_dungeonEntrance
int m_maxMinibosses
bool m_fewerSpawners
Detailed Description
Definition at line 375 of file EnemyPlacement.as.
Constructor & Destructor Documentation
EnemyPlacement() [1/2]
EnemyPlacement::EnemyPlacement () inline private
Definition at line 382 of file EnemyPlacement.as.
 {}
EnemyPlacement() [2/2]
EnemyPlacement::EnemyPlacement (Enemies enemies, bool spawners, bool elites, bool minibosses) inline private
Definition at line 384 of file EnemyPlacement.as.
References Fountain::HasEffect(), m_fewerSpawners, and m_maxMinibosses.
     {
         m_maxMinibosses = 3;
         m_fewerSpawners = Fountain::HasEffect("fewer_spawners");
     }
Member Function Documentation
AddEnemyGroup()
void EnemyPlacement::AddEnemyGroup (EnemySetting setting) inline private
Definition at line 390 of file EnemyPlacement.as.
References m_enemyTypes.
Referenced by MakeDungeonGenerator().
     {
         m_enemyTypes.insertLast(setting);
     }
Initialize()
void EnemyPlacement::Initialize (ivec2 dungeonEntrance) inline private
Definition at line 396 of file EnemyPlacement.as.
References m_dungeonEntrance, and m_enemyTypes.
Referenced by PlaceEnemies().
     {
         m_dungeonEntrance = dungeonEntrance;
         m_enemyTypes.sortDesc();
     }
MakeDir()
vec3 EnemyPlacement::MakeDir (int r) inline private
Definition at line 422 of file EnemyPlacement.as.
References xyz().
Referenced by SpawnGroup().
     {
         return xyz(randdir()) * r;
     }
MakeSpread()
vec3 EnemyPlacement::MakeSpread (int x, int y) inline private
Definition at line 416 of file EnemyPlacement.as.
Referenced by SpawnGroup().
     {
         //return vec3(0, 0, 0);
         return vec3(randi(x) - x/2, randi(y) - y/2, 0);
     }
Place()
void EnemyPlacement::Place (Scene@ scene, DungeonBrush@ brush, array< array< ivec2 >@> groups) inline private
Definition at line 569 of file EnemyPlacement.as.
References m_enemyTypes, m_ratio, MakeGroup(), and SpawnGroup().
Referenced by PlaceEnemies().
     {
         int totChance = 0;
         for (uint i = 0; i < m_enemyTypes.length(); i++)
             totChance += m_enemyTypes[i].m_ratio;
         for (uint i = 0; i < groups.length(); i++)
         {
             int n = randi(totChance);
             for (uint j = 0; j < m_enemyTypes.length(); j++)
             {
                 n -= m_enemyTypes[j].m_ratio;
                 if (n < 0)
                 {
                     SpawnGroup(scene, brush, groups[i], m_enemyTypes[j].MakeGroup());
                     break;
                 }
             }
         }
     }
PlaceGroup()
void EnemyPlacement::PlaceGroup (Scene@ scene, vec2 pos, int radius) inline private
Definition at line 591 of file EnemyPlacement.as.
References m_enemyTypes, m_ratio, MakeGroup(), SpawnGroup(), and xyz().
Referenced by WorldScript::SpawnEnemyGroup::ServerExecute().
     {
         int totChance = 0;
         for (uint i = 0; i < m_enemyTypes.length(); i++)
             totChance += m_enemyTypes[i].m_ratio;
         int n = randi(totChance);
         for (uint j = 0; j < m_enemyTypes.length(); j++)
         {
             n -= m_enemyTypes[j].m_ratio;
             if (n < 0)
             {
                 SpawnGroup(scene, xyz(pos), radius, m_enemyTypes[j].MakeGroup());
                 return;
             }
         }
     }
RemovePoint()
void EnemyPlacement::RemovePoint (DungeonBrush@ brush, Cell cellType, array< ivec2 >@ group, int x, int y) inline private
Definition at line 402 of file EnemyPlacement.as.
Referenced by SpawnGroup().
     {
         brush.SetCell(x, y, cellType);
         for (uint i = 0; i < group.length(); i++)
         {
             if (group[i].x == x && group[i].y == y)
             {
                 group.removeAt(i);
                 return;
             }
         }
     }
SpawnGroup() [1/2]
void EnemyPlacement::SpawnGroup (Scene@ scene, vec3 pos, int radius, EnemyGroupSetting@ groupSetting) inline private
Definition at line 427 of file EnemyPlacement.as.
References EnemyGroupSetting::GetEliteUnit(), EnemyGroupSetting::GetMinibossUnit(), EnemyGroupSetting::GetSpawnerUnit(), EnemyGroupSetting::GetUnit(), Fountain::HasEffect(), EnemyGroupSetting::HasEliteUnit(), EnemyGroupSetting::HasMinibossUnit(), EnemyGroupSetting::HasSpawnerUnit(), EnemyGroupSetting::m_baseEnemyCount, m_fewerSpawners, m_maxMinibosses, EnemyGroupSetting::m_numScale, MakeDir(), MakeSpread(), num, and xyz().
Referenced by Place(), and PlaceGroup().
     {
         int num = int(PI * 2 * radius / 40 * groupSetting.m_numScale);
         if (radius > 40 && groupSetting.HasSpawnerUnit() && randi(100) < 33 && (!m_fewerSpawners || randi(100) < 33))
         {
             int numEnemies = randi(groupSetting.m_baseEnemyCount) + 1;
             num -= numEnemies + 3;
             auto spwnPos = pos + vec3(16, 16, 0) + MakeSpread(6, 6);
             groupSetting.GetSpawnerUnit().Produce(scene, spwnPos);
             for (int i = 0; i < numEnemies; i++)
                 groupSetting.GetUnit().Produce(scene, spwnPos + MakeDir(15));
         }
         else if (m_maxMinibosses > 0 && radius > 30 && groupSetting.HasMinibossUnit() && randi(100) < 25)
         {
             int numEnemies = randi(groupSetting.m_baseEnemyCount - 1) + 1;
             num -= 2;
             auto spwnPos = pos + vec3(16, 16, 0) + MakeSpread(6, 6);
             groupSetting.GetMinibossUnit().Produce(scene, spwnPos);
             m_maxMinibosses--;
             for (int i = 0; i < numEnemies; i++)
                 groupSetting.GetUnit().Produce(scene, spwnPos + MakeDir(12));
         }
         int eliteChance = 10;
         if (Fountain::HasEffect("more_elites"))
             eliteChance = 50;
         for (int n = 0; n < num; n++)
         {
             auto sp = pos + xyz(randdir()) * randi(radius - 5);
             if (groupSetting.HasEliteUnit() && randi(100) < eliteChance && (num - n) >= 3)
             {
                 groupSetting.GetEliteUnit().Produce(scene, sp);
                 eliteChance -= 2;
             }
             else
                 groupSetting.GetUnit().Produce(scene, sp);
         }
     }
SpawnGroup() [2/2]
void EnemyPlacement::SpawnGroup (Scene@ scene, DungeonBrush@ brush, array< ivec2 >@ group, EnemyGroupSetting@ groupSetting) inline private
Definition at line 473 of file EnemyPlacement.as.
References Floor, EnemyGroupSetting::GetEliteUnit(), EnemyGroupSetting::GetMinibossUnit(), EnemyGroupSetting::GetSpawnerUnit(), EnemyGroupSetting::GetUnit(), Fountain::HasEffect(), EnemyGroupSetting::HasEliteUnit(), EnemyGroupSetting::HasMinibossUnit(), EnemyGroupSetting::HasSpawnerUnit(), EnemyGroupSetting::m_baseEnemyCount, EnemyGroupSetting::m_cellType, m_dungeonEntrance, m_fewerSpawners, m_maxMinibosses, EnemyGroupSetting::m_numScale, MakeDir(), MakeSpread(), max, num, RemovePoint(), and Wall.
     {
         auto cellType = groupSetting.m_cellType;
         int baseEnemyCount = groupSetting.m_baseEnemyCount;
         int num = max(6, int(group.length() / 3.0f * groupSetting.m_numScale));
         int chanceLower = 0;
         if (Fountain::HasEffect("more_enemies"))
         {
             baseEnemyCount += 1;
             num += 1;
             chanceLower = -5;
         }
         int eliteChance = 10;
         if (Fountain::HasEffect("more_elites"))
             eliteChance = 50;
         for (int n = 0; n < num && !group.isEmpty(); n++)
         {
             auto pos = group[randi(group.length())];
             auto entranceDt = pos - m_dungeonEntrance;
             if ((entranceDt.x * entranceDt.x + entranceDt.y * entranceDt.y) < (17 * 17))
                 continue;
             if (brush.GetCell(pos.x, pos.y + 1) == Cell::Wall || brush.GetCell(pos.x, pos.y + 2) == Cell::Wall)
                 continue;
             if (randi(100) < chanceLower * 2)
                 continue;
             vec3 midPos = vec3(16 * pos.x + brush.m_posOffset.x + 8, 16 * pos.y + brush.m_posOffset.y + 8, 0);
             if (groupSetting.HasSpawnerUnit() && group.length() >= 4 && randi(100) < max(1, 20 - chanceLower) && (!m_fewerSpawners || randi(100) < 33) &&
                 brush.GetCell(pos.x + 1, pos.y) == Cell::Floor &&
                 brush.GetCell(pos.x + 1, pos.y + 1) == Cell::Floor &&
                 brush.GetCell(pos.x, pos.y + 1) == Cell::Floor &&
                 brush.GetCell(pos.x + 2, pos.y + 2) == Cell::Floor &&
                 brush.GetCell(pos.x - 1, pos.y - 1) == Cell::Floor &&
                 brush.GetCell(pos.x + 0, pos.y + 3) == Cell::Floor &&
                 brush.GetCell(pos.x + 1, pos.y + 3) == Cell::Floor &&
                 brush.GetCell(pos.x + 2, pos.y + 3) == Cell::Floor &&
                 brush.GetCell(pos.x + 0, pos.y + 4) == Cell::Floor)
             {
                 chanceLower += 2;
                 RemovePoint(brush, cellType, group, pos.x, pos.y);
                 RemovePoint(brush, cellType, group, pos.x + 1, pos.y);
                 RemovePoint(brush, cellType, group, pos.x, pos.y + 1);
                 RemovePoint(brush, cellType, group, pos.x + 1, pos.y + 1);
                 auto spwnPos = midPos + vec3(16, 16, 0) + MakeSpread(6, 6);
                 groupSetting.GetSpawnerUnit().Produce(scene, spwnPos);
                 int numEnemies = randi(baseEnemyCount) + 1;
                 for (int i = 0; i < numEnemies; i++)
                     groupSetting.GetUnit().Produce(scene, spwnPos + MakeDir(15));
             }
             else if (m_maxMinibosses > 0 && groupSetting.HasMinibossUnit() && group.length() >= 6 && randi(100) < (14 - chanceLower) &&
                 brush.GetCell(pos.x + 1, pos.y) == Cell::Floor &&
                 brush.GetCell(pos.x + 1, pos.y + 1) == Cell::Floor &&
                 brush.GetCell(pos.x, pos.y + 1) == Cell::Floor)
             {
                 chanceLower += 4;
                 RemovePoint(brush, cellType, group, pos.x, pos.y);
                 RemovePoint(brush, cellType, group, pos.x + 1, pos.y);
                 RemovePoint(brush, cellType, group, pos.x, pos.y + 1);
                 RemovePoint(brush, cellType, group, pos.x + 1, pos.y + 1);
                 auto spwnPos = midPos + vec3(16, 16, 0) + MakeSpread(6, 6);
                 groupSetting.GetMinibossUnit().Produce(scene, spwnPos);
                 m_maxMinibosses--;
                 int numEnemies = randi(baseEnemyCount - 1) + 1;
                 for (int i = 0; i < numEnemies; i++)
                     groupSetting.GetUnit().Produce(scene, spwnPos + MakeDir(12));
             }
             else
             {
                 RemovePoint(brush, cellType, group, pos.x, pos.y);
                 chanceLower++;
                 int numEnemies = randi(baseEnemyCount) + 1;
                 for (int i = 0; i < numEnemies; i++)
                 {
                     if (groupSetting.HasEliteUnit() && randi(100) < eliteChance && group.length() >= 3)
                         groupSetting.GetEliteUnit().Produce(scene, midPos + MakeSpread(5, 5));
                     else
                         groupSetting.GetUnit().Produce(scene, midPos + MakeSpread(5, 5));
                 }
             }
         }
     }
Member Data Documentation
m_dungeonEntrance
ivec2 EnemyPlacement::m_dungeonEntrance private
Definition at line 378 of file EnemyPlacement.as.
Referenced by Initialize(), and SpawnGroup().
m_enemyTypes
array<EnemySetting@> EnemyPlacement::m_enemyTypes private
Definition at line 377 of file EnemyPlacement.as.
Referenced by AddEnemyGroup(), Initialize(), Place(), and PlaceGroup().
m_fewerSpawners
bool EnemyPlacement::m_fewerSpawners private
Definition at line 380 of file EnemyPlacement.as.
Referenced by EnemyPlacement(), and SpawnGroup().
m_maxMinibosses
int EnemyPlacement::m_maxMinibosses private
Definition at line 379 of file EnemyPlacement.as.
Referenced by EnemyPlacement(), MakeDungeonGenerator(), and SpawnGroup().
The documentation for this class was generated from the following file:
scripts/Generators/EnemyPlacement.as