HoHDocs: ColorButtonWidget Class Reference
ColorButtonWidget Class Reference
Private Member Functions
ColorButtonWidget ()
Widget Clone () override
Sprite GetCurrentSprite () override
void Load (WidgetLoadingContext &ctx) override
void DoDraw (SpriteBatch &sb, vec2 pos) override
Private Attributes
array< vec4 > m_shades
bool m_selected
Detailed Description
Definition at line 1 of file ColorButtonWidget.as.
Constructor & Destructor Documentation
ColorButtonWidget()
ColorButtonWidget::ColorButtonWidget () inline private
Definition at line 6 of file ColorButtonWidget.as.
Referenced by Clone().
     {
         super();
     }
Member Function Documentation
Clone()
Widget ColorButtonWidget::Clone () inline override private
Definition at line 11 of file ColorButtonWidget.as.
References Widget::CloneInto(), and ColorButtonWidget().
     {
         ColorButtonWidget@ w = ColorButtonWidget();
         CloneInto(w);
         return w;
     }
DoDraw()
void ColorButtonWidget::DoDraw (SpriteBatch & sb, vec2 pos) inline override private
Definition at line 31 of file ColorButtonWidget.as.
References SpriteButtonWidget::DoDraw(), and m_shades.
     {
         SpriteButtonWidget::DoDraw(sb, pos);
         vec4 rectShade = vec4(pos.x + 4, pos.y + 4, 25, 12);
         for (uint i = 0; i < 3; i++)
         {
             vec4 rect = rectShade;
             rect.x += 25 * i;
             sb.FillRectangle(rect, m_shades[2 - i]);
         }
     }
GetCurrentSprite()
Sprite ColorButtonWidget::GetCurrentSprite () inline override private
Definition at line 18 of file ColorButtonWidget.as.
References SpriteButtonWidget::GetCurrentSprite(), m_selected, and SpriteButtonWidget::m_spriteDown.
     {
         if (m_selected)
             return m_spriteDown;
         else
             return SpriteButtonWidget::GetCurrentSprite();
     }
Load()
void ColorButtonWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 26 of file ColorButtonWidget.as.
References Widget::Load().
Referenced by LoadColorButtonWidget().
     {
         SpriteButtonWidget::Load(ctx);
     }
Member Data Documentation
m_selected
bool ColorButtonWidget::m_selected private
Definition at line 4 of file ColorButtonWidget.as.
Referenced by GetCurrentSprite().
m_shades
array<vec4> ColorButtonWidget::m_shades private
Definition at line 3 of file ColorButtonWidget.as.
Referenced by DoDraw().
The documentation for this class was generated from the following file:
scripts/GUI/ColorButtonWidget.as