HoHDocs: TopNumberIconWidget Class Reference
TopNumberIconWidget Class Reference
Private Member Functions
TopNumberIconWidget ()
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void SetSprite (string sprite)
void SetSprite (Sprite@ sprite)
void SetNumber (int number, bool force=false)
void DoDraw (SpriteBatch &sb, vec2 pos) override
void Save (SValueBuilder &builder)
Private Attributes
GUIDef m_def
vec4 m_color
vec4 m_colorText
Sprite m_sprite
int m_number
BitmapFont m_font
BitmapString m_text
string m_topID
Detailed Description
Definition at line 1 of file TopNumberIconWidget.as.
Constructor & Destructor Documentation
TopNumberIconWidget()
TopNumberIconWidget::TopNumberIconWidget () inline private
Definition at line 16 of file TopNumberIconWidget.as.
Referenced by Clone().
     {
         super();
     }
Member Function Documentation
Clone()
Widget TopNumberIconWidget::Clone () inline override private
Definition at line 21 of file TopNumberIconWidget.as.
References Widget::CloneInto(), and TopNumberIconWidget().
     {
         TopNumberIconWidget@ w = TopNumberIconWidget();
         CloneInto(w);
         return w;
     }
DoDraw()
void TopNumberIconWidget::DoDraw (SpriteBatch & sb, vec2 pos) inline override private
Definition at line 64 of file TopNumberIconWidget.as.
References Widget::DoDraw(), g_menuTime, m_color, Widget::m_height, m_sprite, m_text, and Widget::m_width.
     {
         Widget::DoDraw(sb, pos);
         vec4 p = vec4(pos.x, pos.y, m_width, m_height);
         sb.DrawSprite(null, p, p, m_color);
         if (m_sprite !is null)
             sb.DrawSprite(pos + vec2(1, 1), m_sprite, g_menuTime);
         if (m_text !is null)
         {
             vec2 posText = pos;
             posText.x = int(posText.x) + 11 + (3 - m_text.GetWidth() / 2);
             posText.y = int(posText.y) + 2;
             sb.DrawString(posText, m_text);
         }
     }
Load()
void TopNumberIconWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 28 of file TopNumberIconWidget.as.
References Widget::Load(), m_color, m_colorText, m_def, m_font, Widget::m_height, Widget::m_width, and SetNumber().
Referenced by LoadTopNumberIconWidget().
     {
         Widget::Load(ctx);
         @m_def = ctx.GetGUIDef();
         m_color = ctx.GetColorRGBA("color", false, vec4(0, 0, 0, 1));
         m_colorText = ctx.GetColorRGBA("color-text", false, vec4(1, 1, 1, 1));
         @m_font = Resources::GetBitmapFont(ctx.GetString("font", false, "gui/fonts/font_hw8.fnt"));
         SetNumber(0, true);
         m_width = 17;
         m_height = 12;
     }
Save()
void TopNumberIconWidget::Save (SValueBuilder & builder) inline private
Definition at line 83 of file TopNumberIconWidget.as.
References m_number, and m_topID.
     {
         builder.PushDictionary();
         builder.PushString("id", m_topID);
         builder.PushInteger("num", m_number);
         builder.PopDictionary();
     }
SetNumber()
void TopNumberIconWidget::SetNumber (int number, bool force = false) inline private
Definition at line 54 of file TopNumberIconWidget.as.
References force, m_colorText, m_font, m_number, and m_text.
Referenced by Load().
     {
         if (m_font is null || (m_number == number && !force))
             return;
         m_number = number;
         @m_text = m_font.BuildText("" + number);
         m_text.SetColor(m_colorText);
     }
SetSprite() [1/2]
void TopNumberIconWidget::SetSprite (string sprite) inline private
Definition at line 44 of file TopNumberIconWidget.as.
References m_def.
     {
         SetSprite(m_def.GetSprite(sprite));
     }
SetSprite() [2/2]
void TopNumberIconWidget::SetSprite (Sprite@ sprite) inline private
Definition at line 49 of file TopNumberIconWidget.as.
References m_sprite.
     {
         @m_sprite = sprite;
     }
Member Data Documentation
m_color
vec4 TopNumberIconWidget::m_color private
Definition at line 5 of file TopNumberIconWidget.as.
Referenced by DoDraw(), and Load().
m_colorText
vec4 TopNumberIconWidget::m_colorText private
Definition at line 6 of file TopNumberIconWidget.as.
Referenced by Load(), and SetNumber().
m_def
GUIDef TopNumberIconWidget::m_def private
Definition at line 3 of file TopNumberIconWidget.as.
Referenced by Load(), and SetSprite().
m_font
BitmapFont TopNumberIconWidget::m_font private
Definition at line 11 of file TopNumberIconWidget.as.
Referenced by Load(), and SetNumber().
m_number
int TopNumberIconWidget::m_number private
Definition at line 9 of file TopNumberIconWidget.as.
Referenced by Save(), and SetNumber().
m_sprite
Sprite TopNumberIconWidget::m_sprite private
Definition at line 8 of file TopNumberIconWidget.as.
Referenced by DoDraw(), and SetSprite().
m_text
BitmapString TopNumberIconWidget::m_text private
Definition at line 12 of file TopNumberIconWidget.as.
Referenced by DoDraw(), and SetNumber().
m_topID
string TopNumberIconWidget::m_topID private
Definition at line 14 of file TopNumberIconWidget.as.
Referenced by Save().
The documentation for this class was generated from the following file:
scripts/GUI/HUD/TopNumberIconWidget.as