HoHDocs: GuildHallStatsTab Class Reference
GuildHallStatsTab Class Reference
Private Member Functions
GuildHallStatsTab ()
void OnShow () override
bool OnFunc (Widget@ sender, string name) override
void AddSeparatorToList (Widget@ wList)
void AddStatisticsToList (Stats::StatList@ stats, Widget@ wList)
void AddGuildToList (Widget@ wList)
void AddClassesClassToList (Widget@ wList, string className, array< SValue@>@ characters, vec2 anchor)
void AddClassesToList (Widget@ wList)
void AddCharacterToList (Widget@ wList, SValue@ svChar)
void RefreshList ()
Private Attributes
Widget m_wList
Widget m_wTemplateGuild
Widget m_wTemplateCharacter
Widget m_wTemplateSeparator
Widget m_wTemplateStats
Widget m_wTemplateStatsHeader
Widget m_wTemplateStatsSeparator
Widget m_wTemplateClasses
Widget m_wTemplateClassesClass
Detailed Description
Definition at line 1 of file Stats.as.
Constructor & Destructor Documentation
GuildHallStatsTab()
GuildHallStatsTab::GuildHallStatsTab () inline private
Definition at line 16 of file Stats.as.
References MenuTab::m_id.
     {
         m_id = "stats";
     }
Member Function Documentation
AddCharacterToList()
void GuildHallStatsTab::AddCharacterToList (Widget@ wList, SValue@ svChar) inline private
Definition at line 306 of file Stats.as.
References Widget::AddChild(), Widget::Clone(), GetFaceSprite(), Stats::StatList::Load(), Stats::LoadList(), Materials::MulticolorsFromSval(), and name.
     {
         auto wNewItem = cast<DetailsWidget>(m_wTemplateCharacter.Clone());
         wNewItem.SetID("");
         wNewItem.m_visible = true;
         wList.AddChild(wNewItem);
         string name = GetParamString(UnitPtr(), svChar, "name");
         int level = GetParamInt(UnitPtr(), svChar, "level");
         string charClass = GetParamString(UnitPtr(), svChar, "class");
         int face = GetParamInt(UnitPtr(), svChar, "face", false);
         int ngp = GetParamInt(UnitPtr(), svChar, "new-game-plus", false);
         SValue@ svStatistics = svChar.GetDictionaryEntry("statistics");
         array<array<vec4>> multiColors = Materials::MulticolorsFromSval(svChar);
         auto wUnit = cast<UnitWidget>(wNewItem.GetWidgetById("unit"));
         if (wUnit !is null)
         {
             wUnit.AddUnit("players/" + charClass + ".unit", "idle-3");
             wUnit.m_multiColors = multiColors;
         }
         auto wFace = cast<SpriteWidget>(wNewItem.GetWidgetById("face"));
         if (wFace !is null)
         {
             wFace.SetSprite(GetFaceSprite(charClass, face));
             wFace.m_multiColors = multiColors;
         }
         auto wLevel = cast<TextWidget>(wNewItem.GetWidgetById("level"));
         if (wLevel !is null)
         {
             wLevel.SetText("" + level);
             if (ngp == 0)
                 wLevel.m_anchor.y = 0.5;
         }
         auto wNGP = cast<TextWidget>(wNewItem.GetWidgetById("ngp"));
         if (wNGP !is null)
         {
             wNGP.m_visible = (ngp > 0);
             if (wNGP.m_visible)
                 wNGP.SetText("+" + ngp);
         }
         auto wName = cast<TextWidget>(wNewItem.GetWidgetById("name"));
         if (wName !is null)
         {
             string charClassName = Resources::GetString(".class." + charClass);
             dictionary params = { { "name", name }, { "class", charClassName } };
             wName.SetText(Resources::GetString(".mainmenu.character.select.name", params));
         }
         Stats::StatList@ stats = Stats::LoadList("tweak/stats.sval");
         if (svStatistics !is null)
             stats.Load(svStatistics);
         AddStatisticsToList(stats, wNewItem.m_wDetails);
     }
AddClassesClassToList()
void GuildHallStatsTab::AddClassesClassToList (Widget@ wList, string className, array< SValue@>@ characters, vec2 anchor) inline private
Definition at line 154 of file Stats.as.
References Widget::Clone(), g_classTitles, Titles::TitleList::GetExtraModifiers(), Titles::ClassTitles::GetList(), Titles::GetMaxClassTitleIndex(), Titles::ClassTitles::GetTitle(), Titles::Title::m_modifiers, Titles::Title::m_name, m_wTemplateClassesClass, max, modifiers, and Widget::SetID().
     {
         SValue@ bestChar = null;
         Titles::Title@ bestCharTitle = null;
         int bestCharTitleIndex = -1;
         int actualBestCharTitleIndex = -1;
         int maxTitleIndex = Titles::GetMaxClassTitleIndex();
         for (uint i = 0; i < characters.length(); i++)
         {
             auto charData = characters[i];
             string charClass = GetParamString(UnitPtr(), charData, "class");
             if (charClass != className)
                 continue;
             int titleIndex = GetParamInt(UnitPtr(), charData, "title", false);
             actualBestCharTitleIndex = max(actualBestCharTitleIndex, titleIndex);
             if (titleIndex > maxTitleIndex)
                 titleIndex = maxTitleIndex;
             if (titleIndex <= bestCharTitleIndex)
                 continue;
             auto title = g_classTitles.GetTitle(className, titleIndex);
             if (title is null)
                 continue;
             bestCharTitleIndex = titleIndex;
             @bestChar = charData;
             @bestCharTitle = title;
         }
         auto wNewClass = m_wTemplateClassesClass.Clone();
         wNewClass.SetID("");
         wNewClass.m_visible = true;
         wNewClass.m_anchor = anchor;
         if (bestCharTitle !is null)
         {
             auto wTitle = cast<TextWidget>(wNewClass.GetWidgetById("title"));
             if (wTitle !is null)
                 wTitle.SetText(bestCharTitleIndex + ". " + Resources::GetString(bestCharTitle.m_name));
             auto wBonus = wNewClass.GetWidgetById("bonus");
             auto wBonusSprite = cast<SpriteWidget>(wBonus.GetWidgetById("sprite"));
             auto wBonusValue = cast<TextWidget>(wBonus.GetWidgetById("value"));
             auto modifiers = Modifiers::ModifierList(bestCharTitle.m_modifiers.m_modifiers);
             auto titleList = g_classTitles.GetList(className);
             if (titleList !is null)
             {
                 auto extra = titleList.GetExtraModifiers(bestCharTitleIndex);
                 for (uint i = 0; i < extra.length(); i++)
                     modifiers.Add(extra[i]);
             }
             vec2 armorAdd = modifiers.ArmorAdd(null, null);
             ivec2 damagePower = modifiers.DamagePower(null, null);
             vec2 regenAdd = modifiers.RegenAdd(null);
             float goldGain = modifiers.GoldGainScale(null);
             goldGain += modifiers.GoldGainScaleAdd(null);
             if (armorAdd.x > 0)
             {
                 wBonus.m_tooltipText = Resources::GetString(".guildhall.stats.armor", { { "amount", formatFloat(armorAdd.x, "", 0, 2) } });
                 wBonusSprite.SetSprite("icon-armor");
                 wBonusValue.SetText(formatFloat(armorAdd.x, "", 0, 2));
             }
             else if (armorAdd.y > 0)
             {
                 wBonus.m_tooltipText = Resources::GetString(".guildhall.stats.resistance", { { "amount", formatFloat(armorAdd.y, "", 0, 2) } });
                 wBonusSprite.SetSprite("icon-resistance");
                 wBonusValue.SetText(formatFloat(armorAdd.y, "", 0, 2));
             }
             else if (damagePower.x > 0)
             {
                 wBonus.m_tooltipText = Resources::GetString(".guildhall.stats.attackpower", { { "amount", damagePower.x } });
                 wBonusSprite.SetSprite("icon-attack-power");
                 wBonusValue.SetText("" + damagePower.x);
             }
             else if (damagePower.y > 0)
             {
                 wBonus.m_tooltipText = Resources::GetString(".guildhall.stats.spellpower", { { "amount", damagePower.y } });
                 wBonusSprite.SetSprite("icon-spell-power");
                 wBonusValue.SetText("" + damagePower.y);
             }
             else if (regenAdd.x > 0)
             {
                 wBonus.m_tooltipText = Resources::GetString(".guildhall.stats.healthregen", { { "amount", formatFloat(regenAdd.x, "", 0, 2) } });
                 wBonusSprite.SetSprite("icon-health-regen");
                 wBonusValue.SetText(formatFloat(regenAdd.x, "", 0, 2));
             }
             else if (regenAdd.y > 0)
             {
                 wBonus.m_tooltipText = Resources::GetString(".guildhall.stats.manaregen", { { "amount", formatFloat(regenAdd.y, "", 0, 2) } });
                 wBonusSprite.SetSprite("icon-mana-regen");
                 wBonusValue.SetText(formatFloat(regenAdd.y, "", 0, 2));
             }
             else if (goldGain > 1.0f)
             {
                 wBonus.m_tooltipText = Resources::GetString(".guildhall.stats.goldgain", { { "amount", ((goldGain - 1.0f) * 100.0f) + "%" } });
                 wBonusSprite.SetSprite("icon-gold-gain");
                 wBonusValue.SetText("+" + formatFloat((goldGain - 1.0f) * 100.0f, "", 0, 1) + "%");
             }
             if (actualBestCharTitleIndex > bestCharTitleIndex)
                 wBonusValue.SetText(wBonusValue.m_str + " " + Resources::GetString(".misc.ngp", { { "ngp", int(g_ngp) } }));
         }
         if (bestChar !is null)
         {
             int face = GetParamInt(UnitPtr(), bestChar, "face");
             auto wSprite = cast<SpriteWidget>(wNewClass.GetWidgetById("sprite"));
             if (wSprite !is null)
             {
                 wSprite.SetSprite(GetFaceSprite(className, face));
                 wSprite.m_tooltipTitle = Resources::GetString(".class." + className);
                 wSprite.m_tooltipText = GetParamString(UnitPtr(), bestChar, "name");
                 wSprite.m_multiColors = Materials::MulticolorsFromSval(bestChar);
             }
         }
         wList.AddChild(wNewClass);
     }
AddClassesToList()
void GuildHallStatsTab::AddClassesToList (Widget@ wList) inline private
Definition at line 286 of file Stats.as.
References Widget::AddChild(), Widget::Clone(), HwrSaves::GetCharacters(), and Widget::SetID().
     {
         auto wNewClasses = m_wTemplateClasses.Clone();
         wNewClasses.SetID("");
         wNewClasses.m_visible = true;
         auto characters = HwrSaves::GetCharacters();
         auto wNewList = wNewClasses.GetWidgetById("list");
         AddClassesClassToList(wNewList, "paladin", characters, vec2(0.1f, 0.0f));
         AddClassesClassToList(wNewList, "ranger", characters, vec2(0.35f, 0.0f));
         AddClassesClassToList(wNewList, "sorcerer", characters, vec2(0.65f, 0.0f));
         AddClassesClassToList(wNewList, "warlock", characters, vec2(0.9f, 0.0f));
         AddClassesClassToList(wNewList, "thief", characters, vec2(0.25f, 1.0f));
         AddClassesClassToList(wNewList, "priest", characters, vec2(0.50f, 1.0f));
         AddClassesClassToList(wNewList, "wizard", characters, vec2(0.75f, 1.0f));
         wList.AddChild(wNewClasses);
     }
AddGuildToList()
void GuildHallStatsTab::AddGuildToList (Widget@ wList) inline private
Definition at line 115 of file Stats.as.
References Widget::AddChild(), AddStatisticsToList(), Widget::Clone(), formatThousands(), g_gameMode, ilerp(), and m_wTemplateGuild.
     {
         auto gm = cast<Campaign>(g_gameMode);
         auto town = gm.m_townLocal;
         auto wNewItem = cast<DetailsWidget>(m_wTemplateGuild.Clone());
         wNewItem.SetID("");
         wNewItem.m_visible = true;
         wList.AddChild(wNewItem);
         auto title = town.GetTitle();
         auto titleNext = town.GetNextTitle();
         string guildTitle = utf8string(Resources::GetString(title.m_name)).toUpper().plain();
         auto wGuildTitle = cast<TextWidget>(wNewItem.GetWidgetById("guild-title"));
         wGuildTitle.SetText(Resources::GetString(".guildhall.stats.guildtitle", { { "title", guildTitle } }));
         auto wBar = cast<BarWidget>(wNewItem.GetWidgetById("reputation-bar"));
         auto wBarText = cast<TextWidget>(wBar.GetWidgetById("text"));
         if (titleNext !is null)
         {
             int reputation = town.GetReputation();
             int goodStart = title.m_points;
             int goodEnd = titleNext.m_points;
             float scale = ilerp(goodStart, goodEnd, reputation);
             wBar.SetScale(scale);
             wBarText.SetText(formatThousands(reputation) + " / " + formatThousands(goodEnd));
         }
         else
         {
             wBar.m_spriteRectVariation = 1;
             wBarText.SetColor(vec4(0, 1, 0, 1));
         }
         AddStatisticsToList(town.m_statistics, wNewItem.m_wDetails);
     }
AddSeparatorToList()
void GuildHallStatsTab::AddSeparatorToList (Widget@ wList) inline private
Definition at line 52 of file Stats.as.
References Widget::AddChild(), Widget::Clone(), m_wTemplateSeparator, and Widget::SetID().
     {
         auto wNewItem = m_wTemplateSeparator.Clone();
         wNewItem.SetID("");
         wNewItem.m_visible = true;
         wList.AddChild(wNewItem);
     }
AddStatisticsToList()
void GuildHallStatsTab::AddStatisticsToList (Stats::StatList@ stats, Widget@ wList) inline private
Definition at line 60 of file Stats.as.
References Widget::AddChild(), Widget::Clone(), Stats::StatList::m_stats, Widget::m_visible, m_wTemplateStats, m_wTemplateStatsHeader, m_wTemplateStatsSeparator, and None.
Referenced by AddGuildToList().
     {
         string lastCategory;
         for (uint i = 0; i < stats.m_stats.length(); i++)
         {
             auto stat = stats.m_stats[i];
             if (stat.m_display == Stats::StatDisplay::None || stat.m_valueInt == 0)
                 continue;
             if (stat.m_category != lastCategory)
             {
                 if (lastCategory != "")
                 {
                     auto wNewSeparator = m_wTemplateStatsSeparator.Clone();
                     wNewSeparator.m_visible = true;
                     wNewSeparator.SetID("");
                     wList.AddChild(wNewSeparator);
                 }
                 lastCategory = stat.m_category;
                 auto wNewHeader = m_wTemplateStatsHeader.Clone();
                 wNewHeader.m_visible = true;
                 wNewHeader.SetID("");
                 auto wHeaderCategory = cast<TextWidget>(wNewHeader.GetWidgetById("category"));
                 if (wHeaderCategory !is null)
                     wHeaderCategory.SetText(utf8string(Resources::GetString(".stats.category." + stat.m_category)).toUpper().plain());
                 wList.AddChild(wNewHeader);
             }
             auto wNewItem = m_wTemplateStats.Clone();
             wNewItem.m_visible = true;
             wNewItem.SetID("");
             auto wName = cast<TextWidget>(wNewItem.GetWidgetById("name"));
             if (wName !is null)
                 wName.SetText(Resources::GetString(".stats." + stat.m_name));
             auto wValue = cast<TextWidget>(wNewItem.GetWidgetById("value"));
             if (wValue !is null)
             {
                 if (stat.m_valueInt == 0)
                     wValue.SetText("-");
                 else
                     wValue.SetText(stat.ToString());
             }
             wList.AddChild(wNewItem);
         }
     }
OnFunc()
bool GuildHallStatsTab::OnFunc (Widget@ sender, string name) inline override private
Definition at line 41 of file Stats.as.
References MenuTab::DoLayout(), and name.
     {
         if (name == "details-toggled")
         {
             // We have to do the layout twice to avoid flickering (once from within DetailsWidget and once from here)
             DoLayout();
             return true;
         }
         return false;
     }
OnShow()
void GuildHallStatsTab::OnShow () inline override private
Definition at line 21 of file Stats.as.
References Widget::GetWidgetById(), MenuTab::m_widget, m_wList, m_wTemplateCharacter, m_wTemplateClasses, m_wTemplateClassesClass, m_wTemplateGuild, m_wTemplateSeparator, m_wTemplateStats, m_wTemplateStatsHeader, m_wTemplateStatsSeparator, MenuTab::OnShow(), and RefreshList().
     {
         GuildHallMenuTab::OnShow();
         @m_wList = m_widget.GetWidgetById("list");
         @m_wTemplateGuild = m_widget.GetWidgetById("template-guild");
         @m_wTemplateCharacter = m_widget.GetWidgetById("template-character");
         @m_wTemplateSeparator = m_widget.GetWidgetById("template-separator");
         @m_wTemplateStats = m_widget.GetWidgetById("template-stats");
         @m_wTemplateStatsHeader = m_widget.GetWidgetById("template-stats-header");
         @m_wTemplateStatsSeparator = m_widget.GetWidgetById("template-stats-separator");
         @m_wTemplateClasses = m_widget.GetWidgetById("template-classes");
         @m_wTemplateClassesClass = m_widget.GetWidgetById("template-classes-class");
         RefreshList();
     }
RefreshList()
void GuildHallStatsTab::RefreshList () inline private
Definition at line 368 of file Stats.as.
References DoLayout(), HwrSaves::GetCharacters(), and m_widget.
Referenced by OnShow().
     {
         auto wList = m_widget.GetWidgetById("list");
         wList.ClearChildren();
         AddGuildToList(wList);
         AddSeparatorToList(wList);
         AddClassesToList(wList);
         auto arrCharacters = HwrSaves::GetCharacters();
         for (uint i = 0; i < arrCharacters.length(); i++)
         {
             AddSeparatorToList(wList);
             AddCharacterToList(wList, arrCharacters[i]);
         }
         DoLayout();
     }
Member Data Documentation
m_wList
Widget GuildHallStatsTab::m_wList private
Definition at line 3 of file Stats.as.
Referenced by OnShow().
m_wTemplateCharacter
Widget GuildHallStatsTab::m_wTemplateCharacter private
Definition at line 6 of file Stats.as.
Referenced by OnShow().
m_wTemplateClasses
Widget GuildHallStatsTab::m_wTemplateClasses private
Definition at line 13 of file Stats.as.
Referenced by OnShow().
m_wTemplateClassesClass
Widget GuildHallStatsTab::m_wTemplateClassesClass private
Definition at line 14 of file Stats.as.
Referenced by AddClassesClassToList(), and OnShow().
m_wTemplateGuild
Widget GuildHallStatsTab::m_wTemplateGuild private
Definition at line 5 of file Stats.as.
Referenced by AddGuildToList(), and OnShow().
m_wTemplateSeparator
Widget GuildHallStatsTab::m_wTemplateSeparator private
Definition at line 7 of file Stats.as.
Referenced by AddSeparatorToList(), and OnShow().
m_wTemplateStats
Widget GuildHallStatsTab::m_wTemplateStats private
Definition at line 9 of file Stats.as.
Referenced by AddStatisticsToList(), and OnShow().
m_wTemplateStatsHeader
Widget GuildHallStatsTab::m_wTemplateStatsHeader private
Definition at line 10 of file Stats.as.
Referenced by AddStatisticsToList(), and OnShow().
m_wTemplateStatsSeparator
Widget GuildHallStatsTab::m_wTemplateStatsSeparator private
Definition at line 11 of file Stats.as.
Referenced by AddStatisticsToList(), and OnShow().
The documentation for this class was generated from the following file:
scripts/GUI/GuildHall/Stats.as