HoHDocs: Notification Class Reference
Notification Class Reference
Private Member Functions
Notification (NotificationManager@ manager, Widget@ widget, string text)
vec4 GetColor ()
void AddSubtext (string icon, string subtext)
void Update (int dt)
void PreDraw (int idt)
Private Attributes
NotificationManager m_manager
Widget m_widget
Widget m_wTemplateSubtext
int m_delayC = 200
int m_timeC = 4500
float m_targetY = 0
float m_newY = 0
float m_prevY = 0
bool m_animated = false
vec4 m_startColor
vec4 m_endColor
Detailed Description
Definition at line 1 of file Notification.as.
Constructor & Destructor Documentation
Notification()
Notification::Notification (NotificationManager@ manager, Widget@ widget, string text) inline private
Definition at line 18 of file Notification.as.
References Widget::GetWidgetById(), m_manager, m_widget, Widget::m_width, and text.
     {
         @m_manager = manager;
         @m_widget = widget;
         auto wText = cast<TextWidget>(m_widget.GetWidgetById("text"));
         if (wText !is null)
         {
             wText.SetText(text);
             m_widget.m_width = wText.m_width + 25 * 2;
         }
     }
Member Function Documentation
AddSubtext()
void Notification::AddSubtext (string icon, string subtext) inline private
Definition at line 41 of file Notification.as.
References Widget::Clone(), Widget::GetWidgetById(), icon, Widget::m_height, m_widget, m_wTemplateSubtext, and Widget::SetID().
     {
         auto wList = m_widget.GetWidgetById("subtexts");
         if (wList.m_children.length() == 0)
             m_widget.m_height = 40;
         auto newSubtext = m_wTemplateSubtext.Clone();
         newSubtext.SetID("");
         newSubtext.m_visible = true;
         if (icon != "")
         {
             auto wIcon = cast<SpriteWidget>(newSubtext.GetWidgetById("icon"));
             if (wIcon !is null)
                 wIcon.SetSprite(icon);
         }
         auto wText = cast<TextWidget>(newSubtext.GetWidgetById("text"));
         if (wText !is null)
             wText.SetText(subtext);
         wList.AddChild(newSubtext);
     }
GetColor()
vec4 Notification::GetColor () inline private
Definition at line 31 of file Notification.as.
References easeQuad(), lerp(), m_endColor, m_startColor, and m_timeC.
Referenced by PreDraw().
     {
         int interval = 500;
         int current = (3000 - m_timeC) % (interval * 2);
         float factor = easeQuad((current % interval) / float(interval));
         if (current >= interval)
             return lerp(m_startColor, m_endColor, factor);
         return lerp(m_endColor, m_startColor, factor);
     }
PreDraw()
void Notification::PreDraw (int idt) inline private
Definition at line 94 of file Notification.as.
References Widget::DoLayout(), GetColor(), lerp(), m_animated, m_newY, Widget::m_offset, Widget::m_parent, m_prevY, and m_widget.
Referenced by NotificationManager::Draw().
     {
         m_widget.m_offset.y = lerp(m_prevY, m_newY, idt / 33.0f);
         auto wRect = cast<RectWidget>(m_widget);
         if (wRect !is null)
             wRect.m_color = tocolor(GetColor());
         if (m_animated)
         {
             auto wParent = m_widget.m_parent;
             m_widget.DoLayout(vec2(), vec2(wParent.m_width, wParent.m_height));
         }
     }
Update()
void Notification::Update (int dt) inline private
Definition at line 66 of file Notification.as.
References m_animated, m_delayC, m_newY, Widget::m_offset, m_prevY, m_targetY, m_timeC, Widget::m_visible, m_widget, and PlaySound2D().
Referenced by NotificationManager::Update().
     {
         if (m_delayC > 0)
         {
             m_delayC -= dt;
             if (m_delayC <= 0)
                 PlaySound2D(Resources::GetSoundEvent("event:/ui/announce"));
             else
                 return;
         }
         m_widget.m_visible = true;
         m_timeC -= dt;
         if (m_timeC <= 0)
             return;
         float diff = m_targetY - m_widget.m_offset.y;
         if (diff > 0.5f)
         {
             m_prevY = m_widget.m_offset.y;
             m_newY = m_widget.m_offset.y + (diff * 0.2f);
             m_animated = true;
         }
         else
             m_animated = false;
     }
Member Data Documentation
m_animated
bool Notification::m_animated = false private
Definition at line 13 of file Notification.as.
Referenced by PreDraw(), and Update().
m_delayC
int Notification::m_delayC = 200 private
Definition at line 7 of file Notification.as.
Referenced by Update().
m_endColor
vec4 Notification::m_endColor private
Definition at line 16 of file Notification.as.
Referenced by NotificationManager::Add(), and GetColor().
m_manager
NotificationManager Notification::m_manager private
Definition at line 3 of file Notification.as.
Referenced by Notification().
m_newY
float Notification::m_newY = 0 private
Definition at line 11 of file Notification.as.
Referenced by PreDraw(), and Update().
m_prevY
float Notification::m_prevY = 0 private
Definition at line 12 of file Notification.as.
Referenced by PreDraw(), and Update().
m_startColor
vec4 Notification::m_startColor private
Definition at line 15 of file Notification.as.
Referenced by NotificationManager::Add(), and GetColor().
m_targetY
float Notification::m_targetY = 0 private
Definition at line 10 of file Notification.as.
Referenced by NotificationManager::Update(), and Update().
m_timeC
int Notification::m_timeC = 4500 private
Definition at line 8 of file Notification.as.
Referenced by GetColor(), NotificationManager::Update(), and Update().
m_widget
Widget Notification::m_widget private
Definition at line 4 of file Notification.as.
Referenced by AddSubtext(), Notification(), PreDraw(), NotificationManager::Update(), and Update().
m_wTemplateSubtext
Widget Notification::m_wTemplateSubtext private
Definition at line 5 of file Notification.as.
Referenced by NotificationManager::Add(), and AddSubtext().
The documentation for this class was generated from the following file:
scripts/GUI/HUD/Notification.as