HoHDocs: WaypointMarkersWidget Class Reference
WaypointMarkersWidget Class Reference
Private Member Functions
WaypointMarkersWidget ()
void Load (WidgetLoadingContext &ctx) override
void AddWaypoint (Waypoint@ wp)
void Update (int dt) override
void DoDraw (SpriteBatch &sb, vec2 pos) override
Private Attributes
array< Waypoint@> m_waypoints
Detailed Description
Definition at line 1 of file WaypointMarkers.as.
Constructor & Destructor Documentation
WaypointMarkersWidget()
WaypointMarkersWidget::WaypointMarkersWidget () inline private
Definition at line 5 of file WaypointMarkers.as.
     {
         super();
     }
Member Function Documentation
AddWaypoint()
void WaypointMarkersWidget::AddWaypoint (Waypoint@ wp) inline private
Definition at line 17 of file WaypointMarkers.as.
References m_waypoints.
     {
         m_waypoints.insertLast(wp);
     }
DoDraw()
void WaypointMarkersWidget::DoDraw (SpriteBatch & sb, vec2 pos) inline override private
Definition at line 34 of file WaypointMarkers.as.
References Waypoint::Draw(), g_gameMode, GetLocalPlayer(), Waypoint::GetScreenPosition(), Waypoint::m_fromPos, Waypoint::m_pos, Waypoint::m_sprite, m_waypoints, AGameMode::m_wndScale, Waypoint::ShouldShow(), and ToScreenspace().
     {
         Player@ ply = GetLocalPlayer();
         if (ply is null)
             return;
         vec3 centerPosWorld = ply.m_unit.GetPosition();
         for (uint i = 0; i < m_waypoints.length(); i++)
         {
             Waypoint@ wp = m_waypoints[i];
             wp.m_fromPos = centerPosWorld;
             Sprite@ sprite = wp.m_sprite;
             if (sprite is null)
                 continue;
             vec2 wayPos = ToScreenspace(wp.m_pos) / g_gameMode.m_wndScale;
             if (!wp.ShouldShow(wayPos))
                 continue;
             wp.Draw(sb, wp.GetScreenPosition(wayPos));
         }
     }
Load()
void WaypointMarkersWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 10 of file WaypointMarkers.as.
References Widget::Load().
Referenced by LoadWaypointMarkersWidget().
     {
         auto def = ctx.GetGUIDef();
         Widget::Load(ctx);
     }
Update()
void WaypointMarkersWidget::Update (int dt) inline override private
Definition at line 22 of file WaypointMarkers.as.
References m_waypoints, and Widget::Update().
     {
         for (uint i = 0; i < m_waypoints.length(); i++)
         {
             m_waypoints[i].Update(dt);
             if (!m_waypoints[i].ShouldStay())
                 m_waypoints.removeAt(i--);
         }
         Widget::Update(dt);
     }
Member Data Documentation
m_waypoints
array<Waypoint@> WaypointMarkersWidget::m_waypoints private
Definition at line 3 of file WaypointMarkers.as.
Referenced by AddWaypoint(), DoDraw(), and Update().
The documentation for this class was generated from the following file:
scripts/GUI/HUD/WaypointMarkers.as