HoHDocs: GroupWidget Class Reference
GroupWidget Class Reference
Private Member Functions
GroupWidget ()
void Load (WidgetLoadingContext &ctx) override
Widget Clone () override
void DoLayout (vec2 origin, vec2 parentSz) override
Private Attributes
bool m_dynamicWidth
bool m_dynamicHeight
bool m_innerSz
bool m_doubleLayout
Detailed Description
Definition at line 1 of file GroupWidget.as.
Constructor & Destructor Documentation
GroupWidget()
GroupWidget::GroupWidget () inline private
Definition at line 9 of file GroupWidget.as.
Referenced by Clone().
     {
         super();
     }
Member Function Documentation
Clone()
Widget GroupWidget::Clone () inline override private
Definition at line 42 of file GroupWidget.as.
References Widget::CloneInto(), and GroupWidget().
     {
         GroupWidget@ w = GroupWidget();
         CloneInto(w);
         return w;
     }
DoLayout()
void GroupWidget::DoLayout (vec2 origin, vec2 parentSz) inline override private
Definition at line 49 of file GroupWidget.as.
References Widget::DoLayout(), Widget::m_children, m_doubleLayout, m_dynamicHeight, m_dynamicWidth, Widget::m_height, m_innerSz, Widget::m_origin, and Widget::m_width.
     {
         if (!m_innerSz && (m_dynamicWidth || m_dynamicHeight))
         {
             if (m_dynamicWidth)
                 m_width = int(parentSz.x);
             if (m_dynamicHeight)
                 m_height = int(parentSz.y);
             //CalculateOrigin(origin, parentSz);
         }
         Widget::DoLayout(origin, parentSz);
         if (m_innerSz && (m_dynamicWidth || m_dynamicHeight))
         {
             float w = 0;
             float h = 0;
             for (uint i = 0; i < m_children.length(); i++)
             {
                 auto c = m_children[i];
                 if (!c.m_visible)
                     continue;
                 vec2 o = c.m_origin - m_origin;
                 float x2 = o.x + c.m_width;
                 float y2 = o.y + c.m_height;
                 if (x2 > w)
                     w = x2;
                 if (y2 > h)
                     h = y2;
             }
             if (m_dynamicWidth)
                 m_width = int(w);
             if (m_dynamicHeight)
                 m_height = int(h);
             if (m_doubleLayout)
                 Widget::DoLayout(origin, parentSz);
         }
     }
Load()
void GroupWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 14 of file GroupWidget.as.
References Widget::Load(), m_doubleLayout, m_dynamicHeight, m_dynamicWidth, Widget::m_height, m_innerSz, and Widget::m_width.
Referenced by LoadGroupWidget().
     {
         int w = ctx.GetInteger("width", false, -1);
         int h = ctx.GetInteger("height", false, -1);
         m_innerSz = ctx.GetBoolean("inner", false, false);
         m_doubleLayout = ctx.GetBoolean("double-layout", false, true);
         if (w != -1)
         {
             m_width = w;
             m_dynamicWidth = false;
         }
         else
             m_dynamicWidth = true;
         if (h != -1)
         {
             m_height = h;
             m_dynamicHeight = false;
         }
         else
             m_dynamicHeight = true;
         Widget::Load(ctx);
     }
Member Data Documentation
m_doubleLayout
bool GroupWidget::m_doubleLayout private
Definition at line 7 of file GroupWidget.as.
Referenced by DoLayout(), and Load().
m_dynamicHeight
bool GroupWidget::m_dynamicHeight private
Definition at line 4 of file GroupWidget.as.
Referenced by DoLayout(), and Load().
m_dynamicWidth
bool GroupWidget::m_dynamicWidth private
Definition at line 3 of file GroupWidget.as.
Referenced by DoLayout(), and Load().
m_innerSz
bool GroupWidget::m_innerSz private
Definition at line 5 of file GroupWidget.as.
Referenced by DoLayout(), and Load().
The documentation for this class was generated from the following file:
scripts/GUI/GroupWidget.as