HoHDocs: CoopPlayerWidget Class Reference
CoopPlayerWidget Class Reference
Private Member Functions
CoopPlayerWidget ()
void Load (WidgetLoadingContext &ctx) override
void SetPeer (PlayerRecord@ record)
void UpdatePortrait ()
void Update (int dt) override
Widget Clone () override
Private Attributes
HUDCoop m_hudCoop
PlayerRecord m_record
SpriteWidget m_wPortrait
BarWidget m_wHealth
Widget m_wIconDead
SpriteWidget m_wIconSoulLink
SpriteWidget m_wTriangle
int m_lastSoulLink = -1
Detailed Description
Definition at line 1 of file HUDCoop.as.
Constructor & Destructor Documentation
CoopPlayerWidget()
CoopPlayerWidget::CoopPlayerWidget () inline private
Definition at line 15 of file HUDCoop.as.
Referenced by Clone().
     {
         super();
     }
Member Function Documentation
Clone()
Widget CoopPlayerWidget::Clone () inline override private
Definition at line 86 of file HUDCoop.as.
References Widget::CloneInto(), and CoopPlayerWidget().
     {
         CoopPlayerWidget@ w = CoopPlayerWidget();
         CloneInto(w);
         return w;
     }
Load()
void CoopPlayerWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 20 of file HUDCoop.as.
References Widget::Load().
Referenced by LoadCoopPlayerWidget().
     {
         RectWidget::Load(ctx);
     }
SetPeer()
void CoopPlayerWidget::SetPeer (PlayerRecord@ record) inline private
Definition at line 25 of file HUDCoop.as.
References GetPlayerColor(), Widget::GetWidgetById(), SpriteWidget::m_color, m_record, m_wHealth, m_wIconDead, m_wIconSoulLink, m_wPortrait, m_wTriangle, and UpdatePortrait().
Referenced by HUDCoop::Update().
     {
         @m_record = record;
         vec4 color = ParseColorRGBA("#" + GetPlayerColor(m_record.peer) + "ff");
         @m_wPortrait = cast<SpriteWidget>(GetWidgetById("portrait"));
         @m_wHealth = cast<BarWidget>(GetWidgetById("health"));
         @m_wIconDead = GetWidgetById("dead");
         @m_wIconSoulLink = cast<SpriteWidget>(GetWidgetById("soullink"));
         @m_wTriangle = cast<SpriteWidget>(GetWidgetById("triangle"));
         UpdatePortrait();
         m_wTriangle.m_color = color;
     }
Update()
void CoopPlayerWidget::Update (int dt) inline override private
Definition at line 48 of file HUDCoop.as.
References GetPlayerColor(), SpriteWidget::m_color, SpriteWidget::m_colorize, Widget::m_host, m_lastSoulLink, m_record, Widget::m_visible, m_wHealth, m_wIconDead, m_wIconSoulLink, m_wPortrait, and Widget::Update().
     {
         RectWidget::Update(dt);
         if (m_record is null || m_record.peer == 255)
         {
             bool haveToLayout = false;
             if (m_visible)
                 haveToLayout = true;
             m_visible = false;
             if (haveToLayout)
                 m_host.DoLayout();
             return;
         }
         else if (m_record !is null && m_record.peer != 255)
             m_visible = true;
         bool isDead = m_record.IsDead();
         m_wIconDead.m_visible = isDead;
         m_wIconSoulLink.m_visible = (!isDead && m_record.soulLinkedBy != -1);
         if (!isDead && m_lastSoulLink != m_record.soulLinkedBy)
         {
             m_lastSoulLink = m_record.soulLinkedBy;
             m_wIconSoulLink.m_color = ParseColorRGBA("#" + GetPlayerColor(m_record.soulLinkedBy) + "ff");
         }
         m_wPortrait.m_colorize = isDead;
         if (isDead)
         {
             m_wHealth.SetScale(0.0f);
             return;
         }
         if (m_wHealth !is null)
             m_wHealth.SetScale(m_record.hp);
     }
UpdatePortrait()
void CoopPlayerWidget::UpdatePortrait () inline private
Definition at line 42 of file HUDCoop.as.
References GetFaceSprite(), SpriteWidget::m_multiColors, m_record, m_wPortrait, and SpriteWidget::SetSprite().
Referenced by SetPeer().
     {
         m_wPortrait.SetSprite(GetFaceSprite(m_record.charClass, m_record.face));
         m_wPortrait.m_multiColors = m_record.GetMulticolors();
     }
Member Data Documentation
m_hudCoop
HUDCoop CoopPlayerWidget::m_hudCoop private
Definition at line 3 of file HUDCoop.as.
Referenced by HUDCoop::Update().
m_lastSoulLink
int CoopPlayerWidget::m_lastSoulLink = -1 private
Definition at line 13 of file HUDCoop.as.
Referenced by Update().
m_record
PlayerRecord CoopPlayerWidget::m_record private
Definition at line 5 of file HUDCoop.as.
Referenced by SetPeer(), Update(), and UpdatePortrait().
m_wHealth
BarWidget CoopPlayerWidget::m_wHealth private
Definition at line 8 of file HUDCoop.as.
Referenced by SetPeer(), and Update().
m_wIconDead
Widget CoopPlayerWidget::m_wIconDead private
Definition at line 9 of file HUDCoop.as.
Referenced by SetPeer(), and Update().
m_wIconSoulLink
SpriteWidget CoopPlayerWidget::m_wIconSoulLink private
Definition at line 10 of file HUDCoop.as.
Referenced by SetPeer(), and Update().
m_wPortrait
SpriteWidget CoopPlayerWidget::m_wPortrait private
Definition at line 7 of file HUDCoop.as.
Referenced by SetPeer(), Update(), and UpdatePortrait().
m_wTriangle
SpriteWidget CoopPlayerWidget::m_wTriangle private
Definition at line 11 of file HUDCoop.as.
Referenced by SetPeer().
The documentation for this class was generated from the following file:
scripts/GUI/HUD/HUDCoop.as