HoHDocs: SkillWidget Class Reference
SkillWidget Class Reference
Private Member Functions
SkillWidget ()
Widget Clone () override
void RefreshManaCost (int manaCost)
void SetSkill (Skills::Skill@ skill)
void Load (WidgetLoadingContext &ctx) override
void DoDraw (SpriteBatch &sb, vec2 pos) override
Private Attributes
GUIDef m_def
Skills::ActiveSkill m_skill
BitmapFont m_font
BitmapString m_manaCost
int m_manaCostCache
Detailed Description
Definition at line 1 of file SkillWidget.as.
Constructor & Destructor Documentation
SkillWidget()
SkillWidget::SkillWidget () inline private
Definition at line 11 of file SkillWidget.as.
References m_font, Widget::m_height, m_manaCostCache, and Widget::m_width.
     {
         super();
         m_width = 0;
         m_height = 0;
         m_manaCostCache = -1;
         @m_font = Resources::GetBitmapFont("gui/fonts/font_hw8.fnt");
     }
Member Function Documentation
Clone()
Widget SkillWidget::Clone () inline override private
Definition at line 22 of file SkillWidget.as.
     {
         auto w = SkillWidget();
         w.SetSkill(m_skill);
         return w;
     }
DoDraw()
void SkillWidget::DoDraw (SpriteBatch & sb, vec2 pos) inline override private
Definition at line 51 of file SkillWidget.as.
References m_skill.
     {
         if (m_skill is null || m_skill.m_icon is null)
             return;
         int idt = 0;
         auto frame = m_skill.m_icon.GetFrame(0);
         vec4 p = vec4(pos.x, pos.y, frame.z, frame.w);
         auto texture_cd = Resources::GetTexture2D("gui/icons_skills_cd.png");
         if (texture_cd is null)
         {
             sb.EnableColorize(vec4(0.1,0.1,0.1, 1), vec4(2,2,2, 1), vec4(4,4,4, 1));
             sb.DrawSprite(m_skill.m_icon.m_texture, p, frame, vec4(4,4,4,1));
             sb.DisableColorize();
         }
         else
             sb.DrawSprite(texture_cd, p, frame);
         sb.DrawSpriteRadial(m_skill.m_icon.m_texture, p, frame, 1.0 - m_skill.GetCooldownProgess(idt), vec4(1,1,1,1));
         auto player = GetLocalPlayer();
         if (player !is null && m_skill.m_costMana > 0)
         {
             int manaCost = int(m_skill.m_costMana * g_allModifiers.SpellCostMul(player));
             RefreshManaCost(manaCost);
             if (manaCost > player.m_record.mana * (player.m_record.MaxMana() + g_allModifiers.StatsAdd(player).y))
                 m_manaCost.SetColor(vec4(1, 0, 0, 1));
             else if (m_skill.m_cooldownC > 0)
                 m_manaCost.SetColor(vec4(0.1, 0.1, 0.1, 1));
             else
                 m_manaCost.SetColor(vec4(0.6, 0.6, 1, 1));
             sb.DrawString(pos + vec2(frame.z - m_manaCost.GetWidth(), frame.w - m_manaCost.GetHeight()), m_manaCost);
         }
     }
Load()
void SkillWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 45 of file SkillWidget.as.
References Widget::Load(), and m_def.
Referenced by LoadSkillWidget().
     {
         @m_def = ctx.GetGUIDef();
         Widget::Load(ctx);
     }
RefreshManaCost()
void SkillWidget::RefreshManaCost (int manaCost) inline private
Definition at line 29 of file SkillWidget.as.
Referenced by SetSkill().
     {
         if (m_manaCostCache == manaCost)
             return;
         m_manaCostCache = manaCost;
         @m_manaCost = m_font.BuildText("" + manaCost, -1, TextAlignment::Right);
     }
SetSkill()
void SkillWidget::SetSkill (Skills::Skill@ skill) inline private
Definition at line 38 of file SkillWidget.as.
References Skills::ActiveSkill::m_costMana, m_skill, and RefreshManaCost().
     {
         @m_skill = cast<Skills::ActiveSkill>(skill);
         if (m_skill !is null)
             RefreshManaCost(m_skill.m_costMana);
     }
Member Data Documentation
m_def
GUIDef SkillWidget::m_def private
Definition at line 3 of file SkillWidget.as.
Referenced by Load().
m_font
BitmapFont SkillWidget::m_font private
Definition at line 6 of file SkillWidget.as.
Referenced by SkillWidget().
m_manaCost
BitmapString SkillWidget::m_manaCost private
Definition at line 7 of file SkillWidget.as.
m_manaCostCache
int SkillWidget::m_manaCostCache private
Definition at line 8 of file SkillWidget.as.
Referenced by SkillWidget().
m_skill
Skills::ActiveSkill SkillWidget::m_skill private
Definition at line 5 of file SkillWidget.as.
Referenced by DoDraw(), and SetSkill().
The documentation for this class was generated from the following file:
scripts/GUI/HUD/SkillWidget.as