HoHDocs: Menu::CharacterCreationMenu Class Reference
Menu::CharacterCreationMenu Class Reference
Private Member Functions
CharacterCreationMenu (MenuProvider@ provider, string context)
void Initialize (GUIDef@ def) override
bool IsBuildingLevel (string id, int level)
bool IsClassUnlocked (string className)
void ClassChanged ()
void OnFunc (Widget@ sender, string name) override
Private Attributes
string m_context
CheckBoxGroupWidget m_wGroupClass
array< UnitWidget@> m_wPreviews
string m_charClass
Detailed Description
Definition at line 3 of file CharacterCreationMenu.as.
Constructor & Destructor Documentation
CharacterCreationMenu()
Menu::CharacterCreationMenu::CharacterCreationMenu (MenuProvider@ provider, string context) inline private
Definition at line 13 of file CharacterCreationMenu.as.
References Menu::HwrMenu::m_closeAfterContext, and m_context.
         {
             super(provider);
             m_context = context;
             m_closeAfterContext = true;
             //m_isPopup = true;
         }
Member Function Documentation
ClassChanged()
void Menu::CharacterCreationMenu::ClassChanged () inline private
Definition at line 90 of file CharacterCreationMenu.as.
References CheckBoxGroupWidget::GetChecked(), m_charClass, m_wGroupClass, m_widget, min, and ScriptSprite().
Referenced by Initialize(), and OnFunc().
         {
             m_charClass = m_wGroupClass.GetChecked().GetValue();
             SValue@ svalClass = Resources::GetSValue("players/" + m_charClass + "/char.sval");
             if (svalClass is null)
             {
                 PrintError("Couldn't get SValue file for class \"" + m_charClass + "\"");
                 return;
             }
             auto arrClassSkills = GetParamArray(UnitPtr(), svalClass, "skills");
             for (uint i = 0; i < uint(min(arrClassSkills.length(), 7)); i++)
             {
                 string skillFnm = arrClassSkills[i].GetString();
                 auto skill = Resources::GetSValue(skillFnm);
                 string skillName = GetParamString(UnitPtr(), skill, "name");
                 string skillDesc = skillName + ".create";
                 auto arrIcon = GetParamArray(UnitPtr(), skill, "icon");
                 auto spriteIcon = ScriptSprite(arrIcon);
                 auto wSkillIcon = cast<SpriteWidget>(m_widget.GetWidgetById("skill-" + i));
                 wSkillIcon.SetSprite(spriteIcon);
                 wSkillIcon.m_tooltipTitle = Resources::GetString(skillName);
                 wSkillIcon.m_tooltipText = Resources::GetString(skillDesc);
             }
         }
Initialize()
void Menu::CharacterCreationMenu::Initialize (GUIDef@ def) inline override private
Definition at line 23 of file CharacterCreationMenu.as.
References ClassChanged(), Materials::GetDyeMapping(), Materials::GetRandomDye(), IsClassUnlocked(), m_wGroupClass, m_widget, m_wPreviews, and CheckBoxGroupWidget::SetCheckedRandom().
         {
             @m_wGroupClass = cast<CheckBoxGroupWidget>(m_widget.GetWidgetById("group-class"));
             for (uint i = 0; i < m_wGroupClass.m_children.length(); i++)
             {
                 auto wCheckbox = cast<CheckBoxWidget>(m_wGroupClass.m_children[i]);
                 string className = wCheckbox.GetValue();
                 wCheckbox.m_enabled = IsClassUnlocked(className);
                 wCheckbox.m_tooltipTitle = Resources::GetString(".class." + className);
                 if (wCheckbox.m_enabled)
                     wCheckbox.m_tooltipText = Resources::GetString(".class." + className + ".desc");
                 else
                     wCheckbox.m_tooltipText = Resources::GetString(".class." + className + ".disabled.desc");
                 auto wPreview = cast<UnitWidget>(wCheckbox.GetWidgetById("preview"));
                 wPreview.ClearUnits();
                 auto uws = wPreview.AddUnit("players/" + className + ".unit", "idle-3");
                 if (uws !is null)
                     uws.m_offset = vec2(3, 3);
                 auto dyeMap = Materials::GetDyeMapping(className);
                 for (uint j = 0; j < dyeMap.m_categories.length(); j++)
                 {
                     auto category = dyeMap.m_categories[j];
                     auto dye = Materials::GetRandomDye(category);
                     wPreview.m_multiColors.insertLast(dye.m_shades);
                 }
                 m_wPreviews.insertLast(wPreview);
             }
             m_wGroupClass.SetCheckedRandom();
             ClassChanged();
         }
IsBuildingLevel()
bool Menu::CharacterCreationMenu::IsBuildingLevel (string id, int level) inline private
Definition at line 62 of file CharacterCreationMenu.as.
References g_gameMode.
Referenced by IsClassUnlocked().
         {
             auto gm = cast<MainMenu>(g_gameMode);
             auto building = gm.m_town.GetBuilding(id);
             if (building is null)
                 return false;
             return (building.m_level >= level);
         }
IsClassUnlocked()
bool Menu::CharacterCreationMenu::IsClassUnlocked (string className) inline private
Definition at line 73 of file CharacterCreationMenu.as.
References IsBuildingLevel().
Referenced by Initialize().
         {
             if (className == "thief")
                 return IsBuildingLevel("tavern", 1);
             if (className == "priest")
                 return IsBuildingLevel("chapel", 1);
             if (className == "wizard")
                 return IsBuildingLevel("magicshop", 1);
             if (className == "paladin" || className == "ranger" || className == "sorcerer" || className == "warlock")
                 return true;
             return false;
         }
OnFunc()
void Menu::CharacterCreationMenu::OnFunc (Widget@ sender, string name) inline override private
Definition at line 122 of file CharacterCreationMenu.as.
References ClassChanged(), m_context, Menu::Menu::m_provider, name, Menu::Menu::OnFunc(), and Menu::Menu::OpenMenu().
         {
             auto parse = name.split(" ");
             if (name == "class-changed")
                 ClassChanged();
             else if (name == "next")
                 OpenMenu(CharacterCustomizationMenu(m_provider, this, m_context), "gui/main_menu/character_customization.gui");
             else
                 HwrMenu::OnFunc(sender, name);
         }
Member Data Documentation
m_charClass
string Menu::CharacterCreationMenu::m_charClass private
Definition at line 11 of file CharacterCreationMenu.as.
Referenced by Menu::CharacterCustomizationMenu::CharacterCustomizationMenu(), and ClassChanged().
m_context
string Menu::CharacterCreationMenu::m_context private
Definition at line 5 of file CharacterCreationMenu.as.
Referenced by CharacterCreationMenu(), and OnFunc().
m_wGroupClass
CheckBoxGroupWidget Menu::CharacterCreationMenu::m_wGroupClass private
Definition at line 7 of file CharacterCreationMenu.as.
Referenced by ClassChanged(), and Initialize().
m_wPreviews
array<UnitWidget@> Menu::CharacterCreationMenu::m_wPreviews private
Definition at line 9 of file CharacterCreationMenu.as.
Referenced by Initialize().
The documentation for this class was generated from the following file:
scripts/GUI/Menus/CharacterCreationMenu.as