HoHDocs: Menu::IntroMenu Class Reference
Menu::IntroMenu Class Reference
Private Member Functions
IntroMenu (MenuProvider@ provider)
bool ShouldDisplayCursor () override
void Initialize (GUIDef@ def) override
void ShowLogo (uint index)
bool Close () override
void NextLogo ()
void Update (int dt) override
Private Attributes
int m_tmLogo
array< SpriteWidget@> m_logos
uint m_currentLogo
Detailed Description
Definition at line 3 of file IntroMenu.as.
Constructor & Destructor Documentation
IntroMenu()
Menu::IntroMenu::IntroMenu (MenuProvider@ provider) inline private
Definition at line 10 of file IntroMenu.as.
         {
             super(provider);
         }
Member Function Documentation
Close()
bool Menu::IntroMenu::Close () inline override private
Definition at line 50 of file IntroMenu.as.
References Menu::Menu::m_closing, Menu::Menu::m_provider, and Menu::Menu::OpenMenu().
Referenced by NextLogo().
         {
             if (m_closing)
                 return true;
             SetVar("g_intro_logos_shown", true);
             FrontMenu@ newFrontMenu = FrontMenu(m_provider);
             OpenMenu(newFrontMenu, "gui/main_menu/main.gui", 0);
             m_closing = true;
             return true;
         }
Initialize()
void Menu::IntroMenu::Initialize (GUIDef@ def) inline override private
Definition at line 17 of file IntroMenu.as.
References Widget::m_children, m_logos, m_widget, and ShowLogo().
         {
             Widget@ wMenu = m_widget.GetWidgetById("menu");
             for (uint i = 0; i < wMenu.m_children.length(); i++)
             {
                 SpriteWidget@ wSprite = cast<SpriteWidget>(wMenu.m_children[i]);
                 if (wSprite is null)
                     continue;
                 m_logos.insertLast(wSprite);
             }
             ShowLogo(0);
         }
NextLogo()
void Menu::IntroMenu::NextLogo () inline private
Definition at line 64 of file IntroMenu.as.
References Close(), m_currentLogo, m_logos, and ShowLogo().
Referenced by Update().
         {
             if (m_currentLogo < m_logos.length() - 1)
                 ShowLogo(m_currentLogo + 1);
             else
                 Close();
         }
ShouldDisplayCursor()
bool Menu::IntroMenu::ShouldDisplayCursor () inline override private
Definition at line 15 of file IntroMenu.as.
 { return false; }
ShowLogo()
void Menu::IntroMenu::ShowLogo (uint index) inline private
Definition at line 32 of file IntroMenu.as.
References Cubic, m_currentLogo, m_logos, m_tmLogo, and WidgetVec4Animation().
Referenced by Initialize(), and NextLogo().
         {
             if (index > 0)
                 m_logos[m_currentLogo].FinishAnimations();
             m_currentLogo = index;
             vec4 colVisible = vec4(1, 1, 1, 1);
             vec4 colHidden = vec4(1, 1, 1, 0);
             SpriteWidget@ wSprite = m_logos[m_currentLogo];
             wSprite.Animate(WidgetVec4Animation("color", colHidden, colVisible, 750).WithEasing(EasingFunction::Cubic));
             wSprite.Animate(WidgetVec4Animation("color", colVisible, colHidden, 750, 2000).WithEasing(EasingFunction::Cubic));
             m_tmLogo = 2750;
         }
Update()
void Menu::IntroMenu::Update (int dt) inline override private
Definition at line 72 of file IntroMenu.as.
References MenuInput::Forward, GetMenuInput(), m_tmLogo, NextLogo(), ButtonState::Pressed, and Menu::Update().
         {
             Menu::Update(dt);
             MenuInput@ input = GetMenuInput();
             if (input.Forward.Pressed)
                 NextLogo();
             if (m_tmLogo > 0)
             {
                 m_tmLogo -= dt;
                 if (m_tmLogo <= 0)
                     NextLogo();
             }
         }
Member Data Documentation
m_currentLogo
uint Menu::IntroMenu::m_currentLogo private
Definition at line 8 of file IntroMenu.as.
Referenced by NextLogo(), and ShowLogo().
m_logos
array<SpriteWidget@> Menu::IntroMenu::m_logos private
Definition at line 7 of file IntroMenu.as.
Referenced by Initialize(), NextLogo(), and ShowLogo().
m_tmLogo
int Menu::IntroMenu::m_tmLogo private
Definition at line 5 of file IntroMenu.as.
Referenced by ShowLogo(), and Update().
The documentation for this class was generated from the following file:
scripts/GUI/Menus/IntroMenu.as