HoHDocs: Menu::EditSlotMenu Class Reference
Menu::EditSlotMenu Class Reference
Private Member Functions
EditSlotMenu (MenuProvider@ provider, SaveSlot@ originSlot=null)
void Initialize (GUIDef@ def) override
bool GoBack () override
void Update (int dt) override
void OnFunc (Widget@ sender, string name) override
Private Attributes
Widget m_wSaving
Widget m_wWindow
Widget m_wModList
Widget m_wModTemplate
SaveSlot m_slot
bool m_saving
Detailed Description
Definition at line 3 of file EditSlotMenu.as.
Constructor & Destructor Documentation
EditSlotMenu()
Menu::EditSlotMenu::EditSlotMenu (MenuProvider@ provider, SaveSlot@ originSlot = null) inline private
Definition at line 15 of file EditSlotMenu.as.
References m_slot.
         {
             super(provider);
             @m_slot = originSlot;
         }
Member Function Documentation
GoBack()
bool Menu::EditSlotMenu::GoBack () inline override private
Definition at line 59 of file EditSlotMenu.as.
References Menu::Menu::GoBack(), and m_saving.
         {
             if (m_saving)
                 return true;
             return HwrMenu::GoBack();
         }
Initialize()
void Menu::EditSlotMenu::Initialize (GUIDef@ def) inline override private
Definition at line 22 of file EditSlotMenu.as.
References Widget::AddChild(), Widget::Clone(), Platform::GetAllResourceMods(), m_slot, m_widget, m_wModList, m_wModTemplate, m_wSaving, and m_wWindow.
         {
             @m_wSaving = m_widget.GetWidgetById("saving");
             @m_wWindow = m_widget.GetWidgetById("window");
             @m_wModList = m_widget.GetWidgetById("mod-list");
             @m_wModTemplate = m_widget.GetWidgetById("mod-template");
             array<uint32> enabledMods;
             if (m_slot !is null)
                 enabledMods = m_slot.EnabledMods;
             auto mods = Platform::GetAllResourceMods();
             for (uint i = 0; i < mods.length(); i++)
             {
                 auto mod = mods[i];
                 auto wNewMod = cast<ScalableSpriteButtonWidget>(m_wModTemplate.Clone());
                 wNewMod.SetID("");
                 wNewMod.m_visible = true;
                 wNewMod.SetText(mod.Name);
                 wNewMod.m_value = mod.ID;
                 if (m_slot !is null)
                     wNewMod.SetChecked(enabledMods.find(HashString(mod.ID)) != -1);
                 wNewMod.m_tooltipTitle = Resources::GetString(".mods.by", { { "author", mod.Author } });
                 wNewMod.m_tooltipText = mod.Description;
                 if (!mod.Packaged)
                     wNewMod.m_tooltipText += "\n\n" + Resources::GetString(".mods.unpacked");
                 m_wModList.AddChild(wNewMod);
             }
         }
OnFunc()
void Menu::EditSlotMenu::OnFunc (Widget@ sender, string name) inline override private
Definition at line 77 of file EditSlotMenu.as.
References Widget::m_children, m_saving, m_slot, Widget::m_visible, m_wModList, m_wSaving, m_wWindow, name, and Menu::Menu::OnFunc().
         {
             if (name == "ok")
             {
                 print("ok, setting mods in " + m_slot.Slot);
                 for (uint i = 0; i < m_wModList.m_children.length(); i++)
                 {
                     auto wCheck = cast<ICheckableWidget>(m_wModList.m_children[i]);
                     if (wCheck is null)
                         continue;
                     string modIdString = wCheck.GetValue();
                     uint modId = HashString(modIdString);
                     if (wCheck.IsChecked())
                         m_slot.EnableMod(modId);
                     else
                         m_slot.DisableMod(modId);
                 }
                 m_slot.Write();
                 m_saving = true;
                 m_wSaving.m_visible = true;
                 m_wWindow.m_visible = false;
             }
             else
                 HwrMenu::OnFunc(sender, name);
         }
Update()
void Menu::EditSlotMenu::Update (int dt) inline override private
Definition at line 66 of file EditSlotMenu.as.
References Menu::Menu::Close(), HwrSaves::IsSaving(), m_saving, and Update().
         {
             HwrMenu::Update(dt);
             if (m_saving && !HwrSaves::IsSaving())
             {
                 m_saving = false;
                 Close();
             }
         }
Member Data Documentation
m_saving
bool Menu::EditSlotMenu::m_saving private
Definition at line 13 of file EditSlotMenu.as.
Referenced by GoBack(), OnFunc(), and Update().
m_slot
SaveSlot Menu::EditSlotMenu::m_slot private
Definition at line 11 of file EditSlotMenu.as.
Referenced by EditSlotMenu(), Initialize(), and OnFunc().
m_wModList
Widget Menu::EditSlotMenu::m_wModList private
Definition at line 8 of file EditSlotMenu.as.
Referenced by Initialize(), and OnFunc().
m_wModTemplate
Widget Menu::EditSlotMenu::m_wModTemplate private
Definition at line 9 of file EditSlotMenu.as.
Referenced by Initialize().
m_wSaving
Widget Menu::EditSlotMenu::m_wSaving private
Definition at line 5 of file EditSlotMenu.as.
Referenced by Initialize(), and OnFunc().
m_wWindow
Widget Menu::EditSlotMenu::m_wWindow private
Definition at line 6 of file EditSlotMenu.as.
Referenced by Initialize(), and OnFunc().
The documentation for this class was generated from the following file:
scripts/GUI/Menus/EditSlotMenu.as