HoHDocs: GameChatWidget Class Reference
GameChatWidget Class Reference
Private Member Functions
GameChatWidget ()
void Load (WidgetLoadingContext &ctx) override
void Initialize ()
void Update (int dt) override
void AddChat (string str, vec4 color=vec4(1, 1, 1, 1))
void PlayerChat (uint8 peer, string message)
void PlayerSystem (uint8 peer, string message)
Private Attributes
ScrollableWidget m_wList
Widget m_wTemplate
TextInputWidget m_wInput
int m_visibleCounter
Detailed Description
Definition at line 1 of file GameChat.as.
Constructor & Destructor Documentation
GameChatWidget()
GameChatWidget::GameChatWidget () inline private
Definition at line 9 of file GameChat.as.
     {
         super();
     }
Member Function Documentation
AddChat()
void GameChatWidget::AddChat (string str, vec4 color = vec4(1, 1, 1, 1)) inline private
Definition at line 34 of file GameChat.as.
References ScrollableWidget::AddChild(), Widget::Clone(), m_visibleCounter, m_wList, m_wTemplate, ScrollableWidget::ScrollDown(), TextWidget::SetColor(), and TextWidget::SetText().
Referenced by PlayerChat(), PlayerSystem(), and MainMenu::SystemMessage().
     {
         if (str == "")
             return;
         if (m_wList is null || m_wTemplate is null)
         {
             PrintError("No chat list or template!");
             return;
         }
         m_visibleCounter = GetVarInt("ui_chat_fade_time");
         TextWidget@ wNewChat = cast<TextWidget>(m_wTemplate.Clone());
         wNewChat.m_visible = true;
         wNewChat.SetID("");
         m_wList.AddChild(wNewChat);
         bool customColor = (str.findFirst("\\c") != -1);
         wNewChat.SetText(str, !customColor);
         if (!customColor)
             wNewChat.SetColor(color);
         m_wList.ScrollDown();
     }
Initialize()
void GameChatWidget::Initialize () inline private
Definition at line 19 of file GameChat.as.
References Widget::GetWidgetById(), m_wInput, m_wList, and m_wTemplate.
Referenced by Menu::InGameChat::Initialize().
     {
         @m_wList = cast<ScrollableWidget>(GetWidgetById("chat-list"));
         @m_wTemplate = GetWidgetById("chat-template");
         @m_wInput = cast<TextInputWidget>(GetWidgetById("chat-input"));
     }
Load()
void GameChatWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 14 of file GameChat.as.
References Widget::Load().
Referenced by LoadGameChatWidget().
     {
         RectWidget::Load(ctx);
     }
PlayerChat()
void GameChatWidget::PlayerChat (uint8 peer, string message) inline private
Definition at line 60 of file GameChat.as.
References AddChat(), g_gameMode, GetPlayerColor(), GetPlayerName(), and HandleChatMessage().
     {
         string playerColor = GetPlayerColor(peer);
         string playerName = EscapeString(Lobby::GetPlayerName(peer));
         string playerMessage = EscapeString(message);
         AddChat("\\c" + playerColor + playerName + "\\d: " + playerMessage);
         cast<MainMenu>(g_gameMode).HandleChatMessage(message);
     }
PlayerSystem()
void GameChatWidget::PlayerSystem (uint8 peer, string message) inline private
Definition at line 71 of file GameChat.as.
References AddChat(), GetPlayerColor(), and GetPlayerName().
Referenced by MainMenu::RemovePlayer().
     {
         string playerColor = GetPlayerColor(peer);
         string playerName = EscapeString(Lobby::GetPlayerName(peer));
         AddChat(Resources::GetString(message, { { "name", "\\c" + playerColor + playerName + "\\d" } }));
     }
Update()
void GameChatWidget::Update (int dt) inline override private
Definition at line 26 of file GameChat.as.
References m_visibleCounter, max, and Widget::Update().
     {
         RectWidget::Update(dt);
         if (m_visibleCounter > 0)
             m_visibleCounter = max(0, m_visibleCounter - dt);
     }
Member Data Documentation
m_visibleCounter
int GameChatWidget::m_visibleCounter private
Definition at line 7 of file GameChat.as.
Referenced by AddChat(), and Update().
m_wInput
TextInputWidget GameChatWidget::m_wInput private
Definition at line 5 of file GameChat.as.
Referenced by Initialize().
m_wList
ScrollableWidget GameChatWidget::m_wList private
Definition at line 3 of file GameChat.as.
Referenced by AddChat(), and Initialize().
m_wTemplate
Widget GameChatWidget::m_wTemplate private
Definition at line 4 of file GameChat.as.
Referenced by AddChat(), and Initialize().
The documentation for this class was generated from the following file:
scripts/GUI/Menus/GameChat.as