HoHDocs: Menu::ControlsMenu Class Reference
Menu::ControlsMenu Class Reference
Private Member Functions
ControlsMenu (MenuProvider@ provider)
void Initialize (GUIDef@ def) override
void OnFunc (Widget@ sender, string name) override
Detailed Description
Definition at line 3 of file ControlsMenu.as.
Constructor & Destructor Documentation
ControlsMenu()
Menu::ControlsMenu::ControlsMenu (MenuProvider@ provider) inline private
Definition at line 5 of file ControlsMenu.as.
References Menu::Menu::m_isPopup.
         {
             super(provider);
             m_isPopup = true;
         }
Member Function Documentation
Initialize()
void Menu::ControlsMenu::Initialize (GUIDef@ def) inline override private
Definition at line 12 of file ControlsMenu.as.
References Widget::AddChild(), GetControlBindings(), ControlMap::ID, m_widget, and ControlMap::SteamController.
         {
             Widget@ wMaps = m_widget.GetWidgetById("maps");
             if (wMaps is null)
                 return;
             auto wTemplate = cast<ScalableSpriteButtonWidget>(m_widget.GetWidgetById("maps-template"));
             if (wTemplate is null)
                 return;
             auto cb = GetControlBindings();
             array<ControlMap@>@ arrMaps = cb.GetMaps();
             for (uint i = 0; i < arrMaps.length(); i++)
             {
                 ControlMap@ map = arrMaps[i];
                 auto wNewItem = cast<ScalableSpriteButtonWidget>(wTemplate.Clone());
                 wNewItem.m_visible = true;
                 wNewItem.SetID("");
                 wNewItem.SetText(Resources::GetString(".menu.controls.layout." + map.ID));
                 if (map.SteamController)
                     wNewItem.m_func = "map-sc " + map.Handle;
                 else
                     wNewItem.m_func = "map " + map.ID;
                 wMaps.AddChild(wNewItem);
             }
         }
OnFunc()
void Menu::ControlsMenu::OnFunc (Widget@ sender, string name) inline override private
Definition at line 41 of file ControlsMenu.as.
References g_gameMode, Menu::Menu::m_provider, name, Menu::Menu::OnFunc(), Menu::Menu::OpenMenu(), and AGameMode::ShowDialog().
         {
             array<string> parse = name.split(" ");
             if (parse[0] == "map")
                 OpenMenu(ControlMapMenu(m_provider, parse[1]), "gui/main_menu/options_controlmap.gui");
             else if (parse[0] == "map-sc")
             {
                 if (!Platform::Service.ControllerInterface(parseUInt(parse[1])))
                     g_gameMode.ShowDialog("", Resources::GetString(".menu.controls.scinputs.prompt"), Resources::GetString(".menu.ok"), this);
             }
             else
                 Menu::OnFunc(sender, name);
         }
The documentation for this class was generated from the following file:
scripts/GUI/Menus/ControlsMenu.as