HoHDocs: Menu::HwrMenu Class Reference
Menu::HwrMenu Class Reference
Private Member Functions
HwrMenu (MenuProvider@ provider)
void ShowCharacterSelection (string context)
void FinishContext (string context)
Private Attributes
bool m_closeAfterContext
Detailed Description
Definition at line 3 of file HwrMenu.as.
Constructor & Destructor Documentation
HwrMenu()
Menu::HwrMenu::HwrMenu (MenuProvider@ provider) inline private
Definition at line 7 of file HwrMenu.as.
         {
             super(provider);
         }
Member Function Documentation
FinishContext()
void Menu::HwrMenu::FinishContext (string context) inline private
Definition at line 20 of file HwrMenu.as.
References g_gameMode, JoinLobby(), HwrSaves::LoadCharacter(), m_closeAfterContext, Menu::Menu::m_provider, Menu::Menu::OpenMenu(), PlayGame(), Menu::Menu::RemoveFromProvider(), Menu::ServerlistMenu(), and AGameMode::ShowDialog().
Referenced by Menu::CharacterCustomizationMenu::OnFunc(), and Menu::CharacterSelectionMenu::OnFunc().
         {
             if (context == "")
                 cast<MainMenu>(g_gameMode).PlayGame(GetVarInt("g_start_sessions"));
             else if (context == "multi-host")
                 OpenMenu(Menu::HostMenu(m_provider), "gui/main_menu/host.gui");
             else if (context == "multi-serverlist")
                 OpenMenu(Menu::ServerlistMenu(m_provider), "gui/main_menu/serverlist.gui");
             else if (context == "multi-invite")
             {
                 auto char = HwrSaves::LoadCharacter();
                 int charLevel = GetParamInt(UnitPtr(), char, "level", false, 1);
                 auto gm = cast<MainMenu>(g_gameMode);
                 if (charLevel < gm.m_inviteAcceptMinLevel || charLevel > gm.m_inviteAcceptMaxLevel)
                 {
                     g_gameMode.ShowDialog("", Resources::GetString(".menu.notifier.joinfailed.level", {
                         { "min", gm.m_inviteAcceptMinLevel },
                         { "max", gm.m_inviteAcceptMaxLevel }
                     }), Resources::GetString(".menu.ok"), null);
                     return;
                 }
                 gm.JoiningLobby();
                 Lobby::JoinLobby(gm.m_inviteAcceptID);
             }
             if (m_closeAfterContext)
                 RemoveFromProvider();
         }
ShowCharacterSelection()
void Menu::HwrMenu::ShowCharacterSelection (string context) inline private
Definition at line 12 of file HwrMenu.as.
References HwrSaves::GetCharacters(), Menu::Menu::m_provider, and Menu::Menu::OpenMenu().
Referenced by Menu::FrontMenu::OnFunc().
         {
             if (GetVarInt("g_save_slot") == 0 && HwrSaves::GetCharacters().length() == 0)
                 OpenMenu(CharacterCreationMenu(m_provider, context), "gui/main_menu/character_creation.gui");
             else
                 OpenMenu(CharacterSelectionMenu(m_provider, context), "gui/main_menu/character_selection.gui");
         }
Member Data Documentation
m_closeAfterContext
bool Menu::HwrMenu::m_closeAfterContext private
Definition at line 5 of file HwrMenu.as.
Referenced by Menu::CharacterCreationMenu::CharacterCreationMenu(), and FinishContext().
The documentation for this class was generated from the following file:
scripts/GUI/Menus/HwrMenu.as