HoHDocs: Menu::CharacterSelectionMenu Class Reference
Menu::CharacterSelectionMenu Class Reference
Private Member Functions
CharacterSelectionMenu (MenuProvider@ provider, string context)
void Initialize (GUIDef@ def) override
void Show () override
string GetModClassName (string id)
void ReloadList ()
void OnFunc (Widget@ sender, string name) override
Private Attributes
CheckBoxGroupWidget m_wList
Widget m_wTemplate
ScalableSpriteButtonWidget m_wPlayButton
string m_context
Detailed Description
Definition at line 3 of file CharacterSelectionMenu.as.
Constructor & Destructor Documentation
CharacterSelectionMenu()
Menu::CharacterSelectionMenu::CharacterSelectionMenu (MenuProvider@ provider, string context) inline private
Definition at line 12 of file CharacterSelectionMenu.as.
References m_context.
         {
             super(provider);
             m_context = context;
         }
Member Function Documentation
GetModClassName()
string Menu::CharacterSelectionMenu::GetModClassName (string id) inline private
Definition at line 38 of file CharacterSelectionMenu.as.
References HwrSaves::GetEnabledMods(), and id.
Referenced by ReloadList().
         {
             auto enabledMods = HwrSaves::GetEnabledMods();
             for (uint i = 0; i < enabledMods.length(); i++)
             {
                 auto mod = enabledMods[i];
                 auto sval = mod.Data;
                 auto arrCustomClasses = GetParamArray(UnitPtr(), sval, "custom-character-classes", false);
                 if (arrCustomClasses !is null)
                 {
                     for (uint j = 0; j < arrCustomClasses.length(); j++)
                     {
                         auto charClass = arrCustomClasses[j];
                         if (charClass.GetType() == SValueType::Dictionary)
{
                             string classId = GetParamString(UnitPtr(), charClass, "id");
                             if (classId == id)
                                 return GetParamString(UnitPtr(), charClass, "name");
                         }
                         else if (charClass.GetType() == SValueType::String && charClass.GetString() == id)
                             return id;
                     }
                 }
             }
             return id;
         }
Initialize()
void Menu::CharacterSelectionMenu::Initialize (GUIDef@ def) inline override private
Definition at line 19 of file CharacterSelectionMenu.as.
References m_context, m_widget, m_wList, m_wPlayButton, m_wTemplate, ReloadList(), and ScalableSpriteButtonWidget::SetText().
         {
             @m_wList = cast<CheckBoxGroupWidget>(m_widget.GetWidgetById("list"));
             @m_wTemplate = m_widget.GetWidgetById("template");
             @m_wPlayButton = cast<ScalableSpriteButtonWidget>(m_widget.GetWidgetById("playbutton"));
             if (m_context != "")
                 m_wPlayButton.SetText(Resources::GetString(".mainmenu.character.select.select"));
             ReloadList();
         }
OnFunc()
void Menu::CharacterSelectionMenu::OnFunc (Widget@ sender, string name) inline override private
Definition at line 155 of file CharacterSelectionMenu.as.
References HwrSaves::DeleteCharacter(), Menu::HwrMenu::FinishContext(), g_gameMode, CheckBoxGroupWidget::GetChecked(), m_context, Menu::Menu::m_provider, m_wList, name, Menu::Menu::OnFunc(), Menu::Menu::OpenMenu(), HwrSaves::PickCharacter(), ReloadList(), and AGameMode::ShowDialog().
         {
             if (name == "new")
                 OpenMenu(CharacterCreationMenu(m_provider, m_context), "gui/main_menu/character_creation.gui");
             else if (name == "play")
             {
                 auto wChecked = m_wList.GetChecked();
                 if (wChecked is null)
                     return;
                 HwrSaves::PickCharacter(parseInt(wChecked.GetValue()));
                 FinishContext(m_context);
             }
             else if (name == "delete")
             {
                 auto wChecked = cast<Widget>(m_wList.GetChecked());
                 if (wChecked is null)
                     return;
                 auto wName = cast<TextWidget>(wChecked.GetWidgetById("name"));
                 g_gameMode.ShowDialog(
                     "delete",
                     Resources::GetString(".mainmenu.character.delete.text", { { "name", wName.m_str } }),
                     Resources::GetString(".misc.yes"),
                     Resources::GetString(".misc.no"),
                     this
                 );
             }
             else if (name == "delete yes")
             {
                 auto wChecked = m_wList.GetChecked();
                 if (wChecked is null)
                     return;
                 HwrSaves::DeleteCharacter(parseInt(wChecked.GetValue()));
                 ReloadList();
             }
             else
                 HwrMenu::OnFunc(sender, name);
         }
ReloadList()
void Menu::CharacterSelectionMenu::ReloadList () inline private
Definition at line 66 of file CharacterSelectionMenu.as.
References CheckBoxGroupWidget::AddChild(), CheckBoxGroupWidget::ClearChildren(), Widget::Clone(), HwrSaves::GetCharacters(), GetFaceSprite(), GetModClassName(), m_wList, m_wTemplate, Materials::MulticolorsFromSval(), and name.
Referenced by Initialize(), OnFunc(), and Show().
         {
             m_wList.ClearChildren();
             auto arrCharacters = HwrSaves::GetCharacters();
             for (uint i = 0; i < arrCharacters.length(); i++)
             {
                 auto svChar = arrCharacters[i];
                 string name = GetParamString(UnitPtr(), svChar, "name");
                 int level = GetParamInt(UnitPtr(), svChar, "level");
                 string charClass = GetParamString(UnitPtr(), svChar, "class");
                 int face = GetParamInt(UnitPtr(), svChar, "face", false);
                 int ngp = GetParamInt(UnitPtr(), svChar, "new-game-plus", false);
                 string charClassUnitPath = "players/" + charClass + ".unit";
                 bool charClassExists = (Resources::GetUnitProducer(charClassUnitPath) !is null);
                 auto wNewItem = cast<CheckBoxWidget>(m_wTemplate.Clone());
                 wNewItem.SetID("");
                 wNewItem.m_visible = true;
                 wNewItem.m_value = "" + i;
                 array<array<vec4>> multiColors = Materials::MulticolorsFromSval(svChar);
                 auto wUnit = cast<UnitWidget>(wNewItem.GetWidgetById("unit"));
                 if (wUnit !is null)
                 {
                     wUnit.m_visible = charClassExists;
                     if (charClassExists)
                     {
                         wUnit.AddUnit(charClassUnitPath, "idle-3");
                         wUnit.m_multiColors = multiColors;
                     }
                 }
                 if (!charClassExists)
                 {
                     auto wUnknownClass = wNewItem.GetWidgetById("unknown-class");
                     if (wUnknownClass !is null)
                         wUnknownClass.m_visible = true;
                 }
                 auto wFace = cast<SpriteWidget>(wNewItem.GetWidgetById("face"));
                 if (wFace !is null)
                 {
                     wFace.m_visible = charClassExists;
                     if (charClassExists)
                     {
                         wFace.SetSprite(GetFaceSprite(charClass, face));
                         wFace.m_multiColors = multiColors;
                     }
                 }
                 auto wLevel = cast<TextWidget>(wNewItem.GetWidgetById("level"));
                 if (wLevel !is null)
                 {
                     wLevel.SetText("" + level);
                     if (ngp == 0)
                         wLevel.m_anchor.y = 0.5;
                 }
                 auto wNGP = cast<TextWidget>(wNewItem.GetWidgetById("ngp"));
                 if (wNGP !is null)
                 {
                     wNGP.m_visible = (ngp > 0);
                     if (wNGP.m_visible)
                         wNGP.SetText("+" + ngp);
                 }
                 auto wName = cast<TextWidget>(wNewItem.GetWidgetById("name"));
                 if (wName !is null)
                 {
                     string charClassName;
                     if (charClassExists)
                         charClassName = Resources::GetString(".class." + charClass);
                     else
                         charClassName = GetModClassName(charClass);
                     dictionary params = { { "name", name }, { "class", charClassName } };
                     wName.SetText(Resources::GetString(".mainmenu.character.select.name", params));
                 }
                 m_wList.AddChild(wNewItem);
                 if (i == 0)
                     wNewItem.SetChecked(true);
             }
         }
Show()
void Menu::CharacterSelectionMenu::Show () inline override private
Definition at line 31 of file CharacterSelectionMenu.as.
References ReloadList(), and Menu::Menu::Show().
         {
             HwrMenu::Show();
             ReloadList();
         }
Member Data Documentation
m_context
string Menu::CharacterSelectionMenu::m_context private
Definition at line 10 of file CharacterSelectionMenu.as.
Referenced by CharacterSelectionMenu(), Initialize(), and OnFunc().
m_wList
CheckBoxGroupWidget Menu::CharacterSelectionMenu::m_wList private
Definition at line 5 of file CharacterSelectionMenu.as.
Referenced by Initialize(), OnFunc(), and ReloadList().
m_wPlayButton
ScalableSpriteButtonWidget Menu::CharacterSelectionMenu::m_wPlayButton private
Definition at line 8 of file CharacterSelectionMenu.as.
Referenced by Initialize().
m_wTemplate
Widget Menu::CharacterSelectionMenu::m_wTemplate private
Definition at line 6 of file CharacterSelectionMenu.as.
Referenced by Initialize(), and ReloadList().
The documentation for this class was generated from the following file:
scripts/GUI/Menus/CharacterSelectionMenu.as