HoHDocs: MouseBase Class Reference
MouseBase Class Reference
Private Member Functions
MouseBase (GameInput@ inputGame, MenuInput@ inputMenu)
MenuInput UsingSecondaryMenuInput ()
void Update (int dt)
void SetColor (vec4 color)
vec2 GetPos (int idt)
Platform::CursorInfo GetCursor ()
void Draw (int idt, SpriteBatch &sb)
void DrawTooltip (int idt, SpriteBatch &sb, Tooltip@ tooltip)
Private Attributes
GameInput m_inputGame
MenuInput m_inputMenu
GameInput m_hackSecondGame
MenuInput m_hackSecondMenu
bool m_hackUseSecondary
vec2 m_hackPosPrimaryPrev
bool m_real
vec2 m_pos
vec2 m_posPrev
int m_colorC = 0
vec3 m_color = vec3(1, 1, 1)
Detailed Description
Definition at line 1 of file MouseBase.as.
Constructor & Destructor Documentation
MouseBase()
MouseBase::MouseBase (GameInput@ inputGame, MenuInput@ inputMenu) inline private
Definition at line 19 of file MouseBase.as.
References m_inputGame, m_inputMenu, and m_real.
     {
         @m_inputGame = inputGame;
         @m_inputMenu = inputMenu;
         m_real = inputGame.UsingMouseLook;
     }
Member Function Documentation
Draw()
void MouseBase::Draw (int idt, SpriteBatch & sb) inline private
Definition at line 123 of file MouseBase.as.
References g_gameMode, GetCursor(), GetPos(), m_color, Platform::CursorInfo::m_hotX, Platform::CursorInfo::m_hotY, Platform::CursorInfo::m_texture, AGameMode::m_wndInvScaleTransform, and AGameMode::m_wndScale.
Referenced by MenuMouse::Draw(), and IngameMouse::Draw().
     {
         float scale = g_gameMode.m_wndScale;
         Platform::CursorInfo@ cursor = GetCursor();
         if (cursor is null)
             return;
         auto tex = cursor.m_texture;
         vec2 mousePos = GetPos(idt);
         vec4 mousePosScaled = vec4(
             mousePos.x - cursor.m_hotX * scale,
             mousePos.y - cursor.m_hotY * scale, 0, 0) * g_gameMode.m_wndInvScaleTransform;
         mousePosScaled.z = tex.GetWidth();
         mousePosScaled.w = tex.GetHeight();
         auto gm = cast<BaseGameMode>(g_gameMode);
         vec4 color = vec4(1, 1, 1, GetVarFloat("ui_cursor_alpha"));
         if (!gm.m_usingUICursor)
             color = vec4(m_color.x, m_color.y, m_color.z, color.w);
         sb.DrawSprite(tex, mousePosScaled, vec4(0, 0, tex.GetWidth(), tex.GetHeight()), color);
     }
DrawTooltip()
void MouseBase::DrawTooltip (int idt, SpriteBatch & sb, Tooltip@ tooltip) inline private
Definition at line 150 of file MouseBase.as.
References g_gameMode, GetPos(), and AGameMode::m_wndScale.
     {
         vec2 mousePos = GetPos(idt);
         mousePos /= g_gameMode.m_wndScale;
         tooltip.Draw(sb, mousePos);
     }
GetCursor()
Platform::CursorInfo MouseBase::GetCursor () inline private
Definition at line 118 of file MouseBase.as.
References g_gameMode, and AGameMode::m_currCursor.
Referenced by IngameMouse::Draw(), and Draw().
     {
         return g_gameMode.m_currCursor;
     }
GetPos()
vec2 MouseBase::GetPos (int idt) inline private
Definition at line 110 of file MouseBase.as.
References Platform::GetMousePosition(), lerp(), m_inputGame, m_pos, m_posPrev, and m_real.
Referenced by MenuMouse::Draw(), IngameMouse::Draw(), Draw(), DrawTooltip(), and MenuMouse::Update().
     {
         if (m_inputGame.UsingMouseLook && m_real)
             return Platform::GetMousePosition();
         else
             return lerp(m_posPrev, m_pos, idt / 33.0);
     }
SetColor()
void MouseBase::SetColor (vec4 color) inline private
Definition at line 105 of file MouseBase.as.
References m_color.
     {
         m_color = vec3(color.x, color.y, color.z);
     }
Update()
void MouseBase::Update (int dt) inline private
Definition at line 34 of file MouseBase.as.
References g_gameMode, m_hackPosPrimaryPrev, m_hackSecondGame, m_hackSecondMenu, m_hackUseSecondary, m_inputGame, m_inputMenu, m_pos, m_posPrev, m_real, AGameMode::m_wndHeight, AGameMode::m_wndScale, AGameMode::m_wndWidth, and MenuInput::MouseMove.
Referenced by IngameMouse::Update(), and MenuMouse::Update().
     {
         float width = g_gameMode.m_wndWidth;
         float height = g_gameMode.m_wndHeight;
         float scale = g_gameMode.m_wndScale;
         GameInput@ gi = m_inputGame;
         MenuInput@ mi = m_inputMenu;
         if (m_hackSecondGame !is null)
         {
             if (m_inputGame.MousePos.x != m_hackPosPrimaryPrev.x || m_inputGame.MousePos.y != m_hackPosPrimaryPrev.y)
             {
                 m_hackPosPrimaryPrev = m_inputGame.MousePos;
                 m_hackUseSecondary = false;
             }
             else if (length(m_hackSecondMenu.MouseMove) > 0)
                 m_hackUseSecondary = true;
             if (m_hackUseSecondary)
             {
                 @gi = m_hackSecondGame;
                 @mi = m_hackSecondMenu;
             }
         }
         m_posPrev = m_pos;
         if (gi.UsingGamepad)
         {
             m_real = false;
             auto map = gi.GetCurrentMap();
             vec2 move = mi.MouseMove;
             if (map !is null && map.SteamController)
             {
                 // Absolute movement (Steam controller etc.)
                 m_pos += move;
             }
             else
             {
                 // Normalized movement (Thumbsticks etc.)
                 for (int i = 0; i < 2; i++)
                     move *= length(move);
                 m_pos += move * GetVarFloat("g_mousemove_speed");
             }
             if (m_pos.x < 0)
                 m_pos.x = 0;
             else if (m_pos.x > width * scale)
                 m_pos.x = width * scale;
             if (m_pos.y < 0)
                 m_pos.y = 0;
             else if (m_pos.y > height * scale)
                 m_pos.y = height * scale;
         }
         else
         {
             if (gi.MousePos.x >= 0 && gi.MousePos.y >= 0)
             {
                 m_real = true;
                 m_pos = gi.MousePos;
             }
             else
             {
                 m_real = false;
                 m_pos = vec2(width / 2, height / 2) * scale;
             }
         }
     }
UsingSecondaryMenuInput()
MenuInput MouseBase::UsingSecondaryMenuInput () inline private
Definition at line 27 of file MouseBase.as.
References m_hackSecondMenu, and m_hackUseSecondary.
     {
         if (m_hackUseSecondary)
             return m_hackSecondMenu;
         return null;
     }
Member Data Documentation
m_color
vec3 MouseBase::m_color = vec3(1, 1, 1) private
Definition at line 17 of file MouseBase.as.
Referenced by Draw(), SetColor(), IngameMouse::Update(), and IngameMouse::UpdateMouseColor().
m_colorC
int MouseBase::m_colorC = 0 private
Definition at line 16 of file MouseBase.as.
Referenced by IngameMouse::Update().
m_hackPosPrimaryPrev
vec2 MouseBase::m_hackPosPrimaryPrev private
Definition at line 9 of file MouseBase.as.
Referenced by Update().
m_hackSecondGame
GameInput MouseBase::m_hackSecondGame private
Definition at line 6 of file MouseBase.as.
Referenced by Update().
m_hackSecondMenu
MenuInput MouseBase::m_hackSecondMenu private
Definition at line 7 of file MouseBase.as.
Referenced by Update(), and UsingSecondaryMenuInput().
m_hackUseSecondary
bool MouseBase::m_hackUseSecondary private
Definition at line 8 of file MouseBase.as.
Referenced by Update(), and UsingSecondaryMenuInput().
m_inputGame
GameInput MouseBase::m_inputGame private
Definition at line 3 of file MouseBase.as.
Referenced by GetPos(), MouseBase(), Update(), and IngameMouse::UpdateMouseColor().
m_inputMenu
MenuInput MouseBase::m_inputMenu private
Definition at line 4 of file MouseBase.as.
Referenced by MouseBase(), and Update().
m_pos
vec2 MouseBase::m_pos private
Definition at line 13 of file MouseBase.as.
Referenced by GetPos(), and Update().
m_posPrev
vec2 MouseBase::m_posPrev private
Definition at line 14 of file MouseBase.as.
Referenced by GetPos(), and Update().
m_real
bool MouseBase::m_real private
Definition at line 11 of file MouseBase.as.
Referenced by GetPos(), MouseBase(), and Update().
The documentation for this class was generated from the following file:
scripts/GUI/Input/MouseBase.as