HoHDocs: Menu::InGameNotifier Class Reference
Menu::InGameNotifier Class Reference
Private Member Functions
InGameNotifier ()
void Initialize (GUIBuilder@ b, string filename)
void Update (int dt) override
void ShowSaved (int tm)
Private Attributes
int m_showSaved
Widget m_wSaved
Detailed Description
Definition at line 3 of file InGameNotifier.as.
Constructor & Destructor Documentation
InGameNotifier()
Menu::InGameNotifier::InGameNotifier () inline private
Definition at line 9 of file InGameNotifier.as.
         {
             super();
         }
Member Function Documentation
Initialize()
void Menu::InGameNotifier::Initialize (GUIBuilder@ b, string filename) inline private
Definition at line 14 of file InGameNotifier.as.
References LoadWidget(), m_widget, and m_wSaved.
Referenced by MainMenu::MainMenu().
         {
             LoadWidget(b, filename);
             @m_wSaved = m_widget.GetWidgetById("saved");
         }
ShowSaved()
void Menu::InGameNotifier::ShowSaved (int tm) inline private
Definition at line 30 of file InGameNotifier.as.
References m_showSaved.
Referenced by MainMenu::ShowMessage().
         {
             m_showSaved = tm;
         }
Update()
void Menu::InGameNotifier::Update (int dt) inline override private
Definition at line 21 of file InGameNotifier.as.
References m_showSaved, Widget::m_visible, m_wSaved, and Update().
Referenced by MainMenu::UpdateFrame().
         {
             IWidgetHoster::Update(dt);
             if (m_showSaved > 0)
                 m_showSaved -= dt;
             m_wSaved.m_visible = (m_showSaved > 0);
         }
Member Data Documentation
m_showSaved
int Menu::InGameNotifier::m_showSaved private
Definition at line 5 of file InGameNotifier.as.
Referenced by ShowSaved(), and Update().
m_wSaved
Widget Menu::InGameNotifier::m_wSaved private
Definition at line 7 of file InGameNotifier.as.
Referenced by Initialize(), and Update().
The documentation for this class was generated from the following file:
scripts/GUI/Menus/InGameNotifier.as