HoHDocs: Menu::Menu Class Reference
Menu::Menu Class Reference
Private Member Functions
Menu (MenuProvider@ provider)
void Initialize (GUIDef@ def)
void SetActive ()
void OpenMenu (string path)
void OpenMenu (Menu::Menu@ menu, string path, int index=-1)
bool GoBack ()
bool ShouldDisplayCursor ()
bool Close ()
bool Close (int num)
bool RemoveFromProvider ()
void Show ()
void OnFunc (Widget@ sender, string name) override
Private Attributes
MenuProvider m_provider
bool m_isPopup
bool m_closing
Detailed Description
Definition at line 3 of file Menu.as.
Constructor & Destructor Documentation
Menu()
Menu::Menu::Menu (MenuProvider@ provider) inline private
Definition at line 10 of file Menu.as.
         {
             @m_provider = provider;
             m_isPopup = false;
             m_closing = false;
         }
Member Function Documentation
Close() [1/2]
bool Menu::Menu::Close () inline private
Definition at line 52 of file Menu.as.
References g_gameMode, MenuProvider::m_menus, and BaseGameMode::m_tooltip.
Referenced by Menu::GameLanguagesMenu::Close(), Menu::Close(), Menu::SlotsMenu::Close(), Menu::ControlMapMenu::OnFunc(), Menu::SubOptionsMenu::OnFunc(), Menu::EditSlotMenu::Update(), and Menu::CreditsMenu::UpdateInput().
         {
             if (m_closing)
                 return true;
             BaseGameMode@ gm = cast<BaseGameMode>(g_gameMode);
             if (gm !is null)
                 gm.m_tooltip.Hide();
             m_provider.m_menus[m_provider.m_menus.length() - 2].Show();
             m_closing = true;
             return true;
         }
Close() [2/2]
bool Menu::Menu::Close (int num) inline private
Definition at line 67 of file Menu.as.
References g_gameMode, MenuProvider::m_menus, BaseGameMode::m_tooltip, num, and Menu::Show().
         {
             if (m_closing)
                 return true;
             BaseGameMode@ gm = cast<BaseGameMode>(g_gameMode);
             if (gm !is null)
                 gm.m_tooltip.Hide();
             for (int i = m_provider.m_menus.length() - 1; i > m_provider.m_menus.length() - (num + 1); i--)
                 m_provider.m_menus[i].m_closing = true;
             m_provider.m_menus[m_provider.m_menus.length() - (num + 1)].Show();
             return true;
         }
GoBack()
bool Menu::Menu::GoBack () inline private
Definition at line 45 of file Menu.as.
References Menu::Close().
Referenced by MenuProvider::GoBack(), and Menu::EditSlotMenu::GoBack().
         {
             return Close();
         }
Initialize()
void Menu::Menu::Initialize (GUIDef@ def) inline private
Definition at line 18 of file Menu.as.
Referenced by MenuProvider::Initialize(), Menu::SubOptionsMenu::Initialize(), Menu::TestMenu::Initialize(), Menu::MultiplayerMenu::Initialize(), Menu::SplitscreenOptionsMenu::Initialize(), Menu::FrontMenu::Initialize(), Menu::HostMenu::Initialize(), Menu::SlotsMenu::Initialize(), Menu::LobbyPlayersMenu::Initialize(), and OpenMenu().
 {}
OnFunc()
void Menu::Menu::OnFunc (Widget@ sender, string name) inline override private
Definition at line 98 of file Menu.as.
References Menu::Close(), name, and StopScenario().
Referenced by Menu::OptionsMenu::OnFunc(), Menu::SplitscreenMenu::OnFunc(), Menu::CharacterCustomizationMenu::OnFunc(), Menu::SingleplayerMenu::OnFunc(), Menu::TestMenu::OnFunc(), Menu::MultiplayerMenu::OnFunc(), Menu::ControlsMenu::OnFunc(), Menu::ResolutionsMenu::OnFunc(), Menu::SplitscreenOptionsMenu::OnFunc(), Menu::GameLanguagesMenu::OnFunc(), Menu::OnFunc(), Menu::EditSlotMenu::OnFunc(), Menu::HostMenu::OnFunc(), Menu::ControlMapMenu::OnFunc(), Menu::FrontMenu::OnFunc(), Menu::CharacterCreationMenu::OnFunc(), Menu::SubOptionsMenu::OnFunc(), Menu::CharacterSelectionMenu::OnFunc(), Menu::LobbyPlayersMenu::OnFunc(), and Menu::SlotsMenu::OnFunc().
         {
             if (name == "connectionlost")
                 StopScenario();
             else if (name == "back")
                 Close();
         }
OpenMenu() [1/2]
void Menu::Menu::OpenMenu (string path) inline private
Definition at line 25 of file Menu.as.
References g_gameMode, AGameMode::m_guiBuilder, and MenuProvider::m_menus.
Referenced by Menu::IntroMenu::Close(), Menu::HwrMenu::FinishContext(), Menu::GameOptionsMenu::OnFunc(), Menu::OptionsMenu::OnFunc(), Menu::SplitscreenMenu::OnFunc(), Menu::MultiplayerMenu::OnFunc(), Menu::ControlsMenu::OnFunc(), Menu::GraphicsMenu::OnFunc(), Menu::FrontMenu::OnFunc(), Menu::CharacterCreationMenu::OnFunc(), Menu::CharacterSelectionMenu::OnFunc(), Menu::SlotsMenu::OnFunc(), and Menu::HwrMenu::ShowCharacterSelection().
         {
             Menu::SimpleMenu@ menu = Menu::SimpleMenu(m_provider);
             m_provider.m_menus.insertLast(menu);
             GUIDef@ def = menu.LoadWidget(g_gameMode.m_guiBuilder, path);
             menu.Initialize(def);
             menu.SetActive();
         }
OpenMenu() [2/2]
void Menu::Menu::OpenMenu (Menu::Menu@ menu, string path, int index = -1) inline private
Definition at line 34 of file Menu.as.
References g_gameMode, Initialize(), AGameMode::m_guiBuilder, MenuProvider::m_menus, and SetActive().
         {
             if (index == -1)
                 m_provider.m_menus.insertLast(menu);
             else
                 m_provider.m_menus.insertAt(index, menu);
             GUIDef@ def = menu.LoadWidget(g_gameMode.m_guiBuilder, path);
             menu.Initialize(def);
             menu.SetActive();
         }
RemoveFromProvider()
bool Menu::Menu::RemoveFromProvider () inline private
Definition at line 83 of file Menu.as.
References MenuProvider::m_menus.
Referenced by Menu::HwrMenu::FinishContext().
         {
             int index = m_provider.m_menus.findByRef(this);
             if (index != -1)
             {
                 m_provider.m_menus.removeAt(index);
                 return true;
             }
             return false;
         }
SetActive()
void Menu::Menu::SetActive () inline private
Definition at line 20 of file Menu.as.
References g_gameMode, and AGameMode::ReplaceTopWidgetRoot().
Referenced by MenuProvider::Initialize(), OpenMenu(), MainMenu::SetMenuState(), and MenuProvider::Update().
         {
             g_gameMode.ReplaceTopWidgetRoot(this);
         }
ShouldDisplayCursor()
bool Menu::Menu::ShouldDisplayCursor () inline private
Definition at line 50 of file Menu.as.
Referenced by MainMenu::RenderFrame().
 { return true; }
Show()
void Menu::Menu::Show () inline private
Definition at line 94 of file Menu.as.
Referenced by Menu::CharacterSelectionMenu::Show(), Menu::SlotsMenu::Show(), and Menu::Show().
         {
         }
Member Data Documentation
m_closing
bool Menu::Menu::m_closing private
Definition at line 8 of file Menu.as.
Referenced by Menu::IntroMenu::Close(), Menu::GraphicsMenu::Update(), and MenuProvider::Update().
m_isPopup
bool Menu::Menu::m_isPopup private
Definition at line 7 of file Menu.as.
Referenced by Menu::ControlMapMenu::ControlMapMenu(), Menu::ControlsMenu::ControlsMenu(), Menu::GameLanguagesMenu::GameLanguagesMenu(), Menu::GameOptionsMenu::GameOptionsMenu(), Menu::MultiplayerMenu::MultiplayerMenu(), Menu::OptionsMenu::OptionsMenu(), Menu::ResolutionsMenu::ResolutionsMenu(), Menu::SoundMenu::SoundMenu(), Menu::SplitscreenMenu::SplitscreenMenu(), and Menu::SplitscreenOptionsMenu::SplitscreenOptionsMenu().
m_provider
MenuProvider Menu::Menu::m_provider private
Definition at line 5 of file Menu.as.
Referenced by Menu::IntroMenu::Close(), Menu::HwrMenu::FinishContext(), Menu::GameOptionsMenu::OnFunc(), Menu::OptionsMenu::OnFunc(), Menu::SplitscreenMenu::OnFunc(), Menu::MultiplayerMenu::OnFunc(), Menu::ControlsMenu::OnFunc(), Menu::GraphicsMenu::OnFunc(), Menu::FrontMenu::OnFunc(), Menu::CharacterCreationMenu::OnFunc(), Menu::CharacterSelectionMenu::OnFunc(), Menu::SlotsMenu::OnFunc(), Menu::HwrMenu::ShowCharacterSelection(), and Menu::GraphicsMenu::Update().
The documentation for this class was generated from the following file:
scripts/GUI/Menus/Menu.as