HoHDocs: Menu::SplitscreenMenu Class Reference
Menu::SplitscreenMenu Class Reference
Private Member Functions
SplitscreenMenu (MenuProvider@ provider)
void OnFunc (Widget@ sender, string name) override
Detailed Description
Definition at line 3 of file SplitscreenMenu.as.
Constructor & Destructor Documentation
SplitscreenMenu()
Menu::SplitscreenMenu::SplitscreenMenu (MenuProvider@ provider) inline private
Definition at line 5 of file SplitscreenMenu.as.
References Menu::Menu::m_isPopup.
         {
             super(provider);
             m_isPopup = true;
         }
Member Function Documentation
OnFunc()
void Menu::SplitscreenMenu::OnFunc (Widget@ sender, string name) inline override private
Definition at line 12 of file SplitscreenMenu.as.
References Menu::Menu::m_provider, name, Menu::Menu::OnFunc(), Menu::Menu::OpenMenu(), and Menu::SplitscreenSelectionMenu().
         {
             if (name == "newgame")
                 OpenMenu(SplitscreenSelectionMenu(m_provider), "gui/main_menu/splitscreenselection.gui");
             else
                 Menu::OnFunc(sender, name);
         }
The documentation for this class was generated from the following file:
scripts/GUI/Menus/SplitscreenMenu.as