HoHDocs: Menu::SubOptionsMenu Class Reference
Menu::SubOptionsMenu Class Reference
Private Member Functions
SubOptionsMenu (MenuProvider@ provider)
void Initialize (GUIDef@ def) override
void CancelCvarWidgets (string listID)
void CancelCvarWidgetsInternal (Widget@ wList)
void SaveCvarWidgets (string listID)
void SaveCvarWidgetsInternal (Widget@ wList)
void ResetCvarWidgets (string listID)
void ResetCvarWidgetsInternal (Widget@ wList)
bool AnyCvarChanged (string listID)
bool AnyCvarChangedInternal (Widget@ wList)
bool GoBack () override
void OnFunc (Widget@ sender, string name) override
Private Attributes
string m_optionsListName = "options-list"
Detailed Description
Definition at line 3 of file SubOptionsMenu.as.
Constructor & Destructor Documentation
SubOptionsMenu()
Menu::SubOptionsMenu::SubOptionsMenu (MenuProvider@ provider) inline private
Definition at line 7 of file SubOptionsMenu.as.
         {
             super(provider);
         }
Member Function Documentation
AnyCvarChanged()
bool Menu::SubOptionsMenu::AnyCvarChanged (string listID) inline private
Definition at line 116 of file SubOptionsMenu.as.
References AnyCvarChangedInternal(), and m_widget.
Referenced by OnFunc().
         {
             auto wList = m_widget.GetWidgetById(listID);
             if (wList is null)
                 return false;
             return AnyCvarChangedInternal(wList);
         }
AnyCvarChangedInternal()
bool Menu::SubOptionsMenu::AnyCvarChangedInternal (Widget@ wList) inline private
Definition at line 124 of file SubOptionsMenu.as.
References Widget::m_children.
Referenced by AnyCvarChanged().
         {
             for (uint i = 0; i < wList.m_children.length(); i++)
             {
                 auto wCheckGroup = cast<CheckBoxGroupWidget>(wList.m_children[i]);
                 if (wCheckGroup !is null && wCheckGroup.IsChanged())
                     return true;
                 auto wSlider = cast<SliderWidget>(wList.m_children[i]);
                 if (wSlider !is null && wSlider.IsChanged())
                     return true;
                 auto wCheckbox = cast<CheckBoxWidget>(wList.m_children[i]);
                 if (wCheckbox !is null && wCheckbox.IsChanged())
                     return true;
                 if (AnyCvarChangedInternal(wList.m_children[i]))
                     return true;
             }
             return false;
         }
CancelCvarWidgets()
void Menu::SubOptionsMenu::CancelCvarWidgets (string listID) inline private
Definition at line 19 of file SubOptionsMenu.as.
References CancelCvarWidgetsInternal(), and m_widget.
Referenced by OnFunc().
         {
             auto wList = m_widget.GetWidgetById(listID);
             if (wList is null)
                 return;
             CancelCvarWidgetsInternal(wList);
         }
CancelCvarWidgetsInternal()
void Menu::SubOptionsMenu::CancelCvarWidgetsInternal (Widget@ wList) inline private
Definition at line 27 of file SubOptionsMenu.as.
References Widget::m_children.
Referenced by CancelCvarWidgets().
         {
             for (uint i = 0; i < wList.m_children.length(); i++)
             {
                 auto wCheckGroup = cast<CheckBoxGroupWidget>(wList.m_children[i]);
                 if (wCheckGroup !is null)
                 {
                     wCheckGroup.Cancel();
                     continue;
                 }
                 auto wSlider = cast<SliderWidget>(wList.m_children[i]);
                 if (wSlider !is null)
                 {
                     wSlider.Cancel();
                     continue;
                 }
                 CancelCvarWidgetsInternal(wList.m_children[i]);
             }
         }
GoBack()
bool Menu::SubOptionsMenu::GoBack () inline override private
Definition at line 146 of file SubOptionsMenu.as.
References OnFunc().
         {
             OnFunc(null, "back");
             return true;
         }
Initialize()
void Menu::SubOptionsMenu::Initialize (GUIDef@ def) inline override private
Definition at line 12 of file SubOptionsMenu.as.
References Menu::DoLayout(), and Menu::Menu::Initialize().
         {
             Menu::Initialize(def);
             DoLayout();
         }
OnFunc()
void Menu::SubOptionsMenu::OnFunc (Widget@ sender, string name) inline override private
Definition at line 152 of file SubOptionsMenu.as.
References AnyCvarChanged(), CancelCvarWidgets(), Menu::Menu::Close(), Float(), g_gameMode, Int(), m_optionsListName, m_widget, name, Menu::Menu::OnFunc(), ResetCvarWidgets(), SaveCvarWidgets(), and AGameMode::ShowDialog().
Referenced by GoBack(), Menu::GameOptionsMenu::OnFunc(), and Menu::GraphicsMenu::OnFunc().
         {
             if (name == "defaults")
                 g_gameMode.ShowDialog(
                     "defaults",
                     Resources::GetString(".menu.defaults_dialog"),
                     Resources::GetString(".menu.yes"),
                     Resources::GetString(".menu.no"),
                     this
                 );
             else if (name == "defaults yes")
                 ResetCvarWidgets(m_optionsListName);
             else if (name == "back")
             {
                 if (AnyCvarChanged(m_optionsListName))
                     g_gameMode.ShowDialog(
                         "cancel",
                         Resources::GetString(".menu.unsaved_dialog"),
                         Resources::GetString(".menu.yes"),
                         Resources::GetString(".menu.no"),
                         this
                     );
                 else
                     Close();
             }
             else if (name == "cancel yes")
             {
                 SaveCvarWidgets(m_optionsListName);
                 Close();
             }
             else if (name == "cancel no")
             {
                 CancelCvarWidgets(m_optionsListName);
                 Close();
             }
             else
             {
                 array<string> parse = name.split(" ");
                 if (parse[0] == "cfg-set")
                     SetVar(parse[1], parse[2]);
                 else if (parse[0] == "cfg-radio")
                 {
                     auto wGroup = cast<CheckBoxGroupWidget>(m_widget.GetWidgetById(parse[1]));
                     if (wGroup !is null)
                     {
                         ICheckableWidget@ checkable = wGroup.GetChecked();
                         if (checkable !is null)
{
                             cvar_type cvarType = GetVarType(wGroup.m_cvar);
                             if (cvarType == cvar_type::String)
                                 SetVar(wGroup.m_cvar, checkable.GetValue());
                             else if (cvarType == cvar_type::Int)
                                 SetVar(wGroup.m_cvar, parseInt(checkable.GetValue()));
                             else if (cvarType == cvar_type::Float)
                                 SetVar(wGroup.m_cvar, parseFloat(checkable.GetValue()));
                             else if (cvarType == cvar_type::Bool)
                                 SetVar(wGroup.m_cvar, checkable.GetValue() == "true");
                         }
                     }
                 }
                 else if (parse[0] == "cfg-check")
                 {
                     auto check = cast<CheckBoxWidget>(sender);
                     if (check !is null)
                     {
                         cvar_type cvarType = GetVarType(parse[1]);
                         if (cvarType == cvar_type::Bool)
                             SetVar(parse[1], check.IsChecked());
                     }
                 }
                 else if (parse[0] == "accept")
                 {
                     SaveCvarWidgets(m_optionsListName);
                     OnFunc(sender, "back");
                 }
                 else
                     Menu::OnFunc(sender, name);
             }
         }
ResetCvarWidgets()
void Menu::SubOptionsMenu::ResetCvarWidgets (string listID) inline private
Definition at line 86 of file SubOptionsMenu.as.
References m_widget, and ResetCvarWidgetsInternal().
Referenced by OnFunc().
         {
             auto wList = m_widget.GetWidgetById(listID);
             if (wList is null)
                 return;
             ResetCvarWidgetsInternal(wList);
         }
ResetCvarWidgetsInternal()
void Menu::SubOptionsMenu::ResetCvarWidgetsInternal (Widget@ wList) inline private
Definition at line 94 of file SubOptionsMenu.as.
References Widget::m_children.
Referenced by ResetCvarWidgets().
         {
             for (uint i = 0; i < wList.m_children.length(); i++)
             {
                 auto wCheckGroup = cast<CheckBoxGroupWidget>(wList.m_children[i]);
                 if (wCheckGroup !is null)
                 {
                     wCheckGroup.Reset();
                     continue;
                 }
                 auto wSlider = cast<SliderWidget>(wList.m_children[i]);
                 if (wSlider !is null)
                 {
                     wSlider.Reset();
                     continue;
                 }
                 ResetCvarWidgetsInternal(wList.m_children[i]);
             }
         }
SaveCvarWidgets()
void Menu::SubOptionsMenu::SaveCvarWidgets (string listID) inline private
Definition at line 49 of file SubOptionsMenu.as.
References m_widget, and SaveCvarWidgetsInternal().
Referenced by OnFunc().
         {
             auto wList = m_widget.GetWidgetById(listID);
             if (wList is null)
                 return;
             SaveCvarWidgetsInternal(wList);
         }
SaveCvarWidgetsInternal()
void Menu::SubOptionsMenu::SaveCvarWidgetsInternal (Widget@ wList) inline private
Definition at line 57 of file SubOptionsMenu.as.
References Widget::m_children.
Referenced by SaveCvarWidgets().
         {
             for (uint i = 0; i < wList.m_children.length(); i++)
             {
                 auto wCheckGroup = cast<CheckBoxGroupWidget>(wList.m_children[i]);
                 if (wCheckGroup !is null)
                 {
                     wCheckGroup.Save();
                     continue;
                 }
                 auto wSlider = cast<SliderWidget>(wList.m_children[i]);
                 if (wSlider !is null)
                 {
                     wSlider.Save();
                     continue;
                 }
                 auto wCheckbox = cast<CheckBoxWidget>(wList.m_children[i]);
                 if (wCheckbox !is null)
                 {
                     wCheckbox.Save();
                     continue;
                 }
                 SaveCvarWidgetsInternal(wList.m_children[i]);
             }
         }
Member Data Documentation
m_optionsListName
string Menu::SubOptionsMenu::m_optionsListName = "options-list" private
Definition at line 5 of file SubOptionsMenu.as.
Referenced by OnFunc().
The documentation for this class was generated from the following file:
scripts/GUI/Menus/SubOptionsMenu.as