HoHDocs: Menu::LobbyPlayersMenu Class Reference
Menu::LobbyPlayersMenu Class Reference
Private Member Functions
LobbyPlayersMenu (MenuProvider@ provider)
void Initialize (GUIDef@ def) override
void Show () override
int GetPeerPing (int peer)
void UpdatePlayerList ()
void UpdatePlayer (Widget@ wPlayer, int peer)
void Update (int dt) override
void OnFunc (Widget@ sender, string name) override
Private Attributes
Widget m_wPlayerWindow
Widget m_wPlayerList
Widget m_wPlayerTemplate
TextWidget m_wTitle
int m_kickPeer
int m_lastNumPlayers = 0
int m_pingC = 1000
Detailed Description
Definition at line 3 of file LobbyPlayersMenu.as.
Constructor & Destructor Documentation
LobbyPlayersMenu()
Menu::LobbyPlayersMenu::LobbyPlayersMenu (MenuProvider@ provider) inline private
Definition at line 16 of file LobbyPlayersMenu.as.
         {
             super(provider);
         }
Member Function Documentation
GetPeerPing()
int Menu::LobbyPlayersMenu::GetPeerPing (int peer) inline private
Definition at line 40 of file LobbyPlayersMenu.as.
References GetLocalPeer(), GetPlayerPing(), and IsPlayerHost().
Referenced by UpdatePlayer().
         {
             int localPeer = Lobby::GetLocalPeer();
             if (!Lobby::IsPlayerHost(localPeer))
             {
                 if (peer == localPeer)
                     return Lobby::GetPlayerPing(0);
                 else if (peer == 0)
                     return Lobby::GetPlayerPing(localPeer);
             }
             return Lobby::GetPlayerPing(peer);
         }
Initialize()
void Menu::LobbyPlayersMenu::Initialize (GUIDef@ def) inline override private
Definition at line 21 of file LobbyPlayersMenu.as.
References Menu::Menu::Initialize(), Widget::m_visible, m_widget, m_wPlayerList, m_wPlayerTemplate, m_wPlayerWindow, m_wTitle, and UpdatePlayerList().
         {
             Menu::Initialize(def);
             @m_wPlayerWindow = m_widget.GetWidgetById("player-window");
             @m_wPlayerList = m_widget.GetWidgetById("player-list");
             @m_wPlayerTemplate = m_widget.GetWidgetById("player-template");
             @m_wTitle = cast<TextWidget>(m_widget.GetWidgetById("title"));
             m_wPlayerWindow.m_visible = true;
             UpdatePlayerList();
         }
OnFunc()
void Menu::LobbyPlayersMenu::OnFunc (Widget@ sender, string name) inline override private
Definition at line 156 of file LobbyPlayersMenu.as.
References g_gameMode, GetPlayerName(), KickPlayer(), m_kickPeer, name, Menu::Menu::OnFunc(), OpenProfile(), and AGameMode::ShowDialog().
         {
             auto parse = name.split(" ");
             if (parse[0] == "profile")
                 Lobby::OpenProfile(parseInt(parse[1]));
             else if (parse[0] == "kick")
             {
                 if (parse[1] == "yes")
                     Lobby::KickPlayer(m_kickPeer);
                 else if (parse[1] != "no")
                 {
                     m_kickPeer = parseInt(parse[1]);
                     g_gameMode.ShowDialog("kick", Resources::GetString(".mainmenu.lobbyplayers.kick.prompt", {
                         { "name", Lobby::GetPlayerName(m_kickPeer) }
                     }), Resources::GetString(".menu.yes"), Resources::GetString(".menu.no"), this);
                 }
             }
             else
                 Menu::OnFunc(sender, name);
         }
Show()
void Menu::LobbyPlayersMenu::Show () inline override private
Definition at line 35 of file LobbyPlayersMenu.as.
References UpdatePlayerList().
         {
             UpdatePlayerList();
         }
Update()
void Menu::LobbyPlayersMenu::Update (int dt) inline override private
Definition at line 132 of file LobbyPlayersMenu.as.
References GetLobbyPlayerCount(), m_lastNumPlayers, m_pingC, m_widget, Menu::Update(), UpdatePlayer(), and UpdatePlayerList().
         {
             m_pingC -= dt;
             if (m_pingC <= 0)
             {
                 m_pingC += 1000;
                 int numPlayers = Lobby::GetLobbyPlayerCount();
                 if (m_lastNumPlayers != numPlayers)
                     UpdatePlayerList();
                 else
                 {
                     for (int i = 0; i < numPlayers; i++)
                     {
                         auto wPlayer = m_widget.GetWidgetById("player-" + i);
                         if (wPlayer !is null)
                             UpdatePlayer(wPlayer, i);
                     }
                 }
             }
             Menu::Update(dt);
         }
UpdatePlayer()
void Menu::LobbyPlayersMenu::UpdatePlayer (Widget@ wPlayer, int peer) inline private
Definition at line 85 of file LobbyPlayersMenu.as.
References CanOpenProfile(), GetLocalPeer(), GetPeerPing(), GetPlayerColor(), GetPlayerName(), Widget::GetWidgetById(), IsPlayerHost(), and HwrSaves::LoadCharacter().
Referenced by Update(), and UpdatePlayerList().
         {
             int localPeer = Lobby::GetLocalPeer();
             bool isLocal = (localPeer == peer);
             bool isHost = Lobby::IsPlayerHost(localPeer);
             string playerName = Lobby::GetPlayerName(peer);
             int playerPing = GetPeerPing(peer);
             auto plrSave = HwrSaves::LoadCharacter(peer);
             if (plrSave is null)
                 return;
             string charName = GetParamString(UnitPtr(), plrSave, "name", false);
             string charClass = GetParamString(UnitPtr(), plrSave, "class", false);
             int charLevel = GetParamInt(UnitPtr(), plrSave, "level", false);
             auto wName = cast<TextWidget>(wPlayer.GetWidgetById("name"));
             if (wName !is null)
             {
                 wName.SetText(
                     charName +
                     " (" + playerName + "), " +
                     Resources::GetString(".mainmenu.lobbyplayers.level", { { "level", charLevel } }) + " " +
                     Resources::GetString(".class." + charClass)
                 );
                 wName.SetColor(ParseColorRGBA("#" + GetPlayerColor(peer) + "ff"));
             }
             auto wPing = cast<TextWidget>(wPlayer.GetWidgetById("ping"));
             if (wPing !is null)
                 wPing.SetText(playerPing + " ms");
             auto wProfileButton = cast<SpriteButtonWidget>(wPlayer.GetWidgetById("profile-button"));
             if (wProfileButton !is null)
             {
                 wProfileButton.m_enabled = Lobby::CanOpenProfile(peer);
                 wProfileButton.m_func = "profile " + peer;
             }
             auto wKickButton = cast<SpriteButtonWidget>(wPlayer.GetWidgetById("kick-button"));
             if (wKickButton !is null)
             {
                 wKickButton.m_enabled = (isHost && !isLocal);
                 wKickButton.m_func = "kick " + peer;
             }
         }
UpdatePlayerList()
void Menu::LobbyPlayersMenu::UpdatePlayerList () inline private
Definition at line 53 of file LobbyPlayersMenu.as.
References Widget::AddChild(), Widget::ClearChildren(), Widget::Clone(), GetLobbyPlayerCount(), IsInLobby(), m_lastNumPlayers, m_wPlayerList, m_wPlayerTemplate, m_wTitle, Widget::SetID(), TextWidget::SetText(), and UpdatePlayer().
Referenced by Initialize(), Show(), and Update().
         {
             if (!Lobby::IsInLobby())
                 return;
             int numPlayers = Lobby::GetLobbyPlayerCount();
             m_lastNumPlayers = numPlayers;
             if (numPlayers <= 4)
                 m_wTitle.SetText(Resources::GetString(".mainmenu.lobbyplayers.title"));
             else
             {
                 m_wTitle.SetText(Resources::GetString(".mainmenu.lobbyplayers.title.multiple", {
                     { "count", numPlayers }
                 }));
             }
             m_wPlayerList.ClearChildren();
             for (int i = 0; i < numPlayers; i++)
             {
                 auto wPlayer = m_wPlayerTemplate.Clone();
                 wPlayer.SetID("player-" + i);
                 wPlayer.m_visible = true;
                 UpdatePlayer(wPlayer, i);
                 m_wPlayerList.AddChild(wPlayer);
             }
         }
Member Data Documentation
m_kickPeer
int Menu::LobbyPlayersMenu::m_kickPeer private
Definition at line 11 of file LobbyPlayersMenu.as.
Referenced by OnFunc().
m_lastNumPlayers
int Menu::LobbyPlayersMenu::m_lastNumPlayers = 0 private
Definition at line 13 of file LobbyPlayersMenu.as.
Referenced by Update(), and UpdatePlayerList().
m_pingC
int Menu::LobbyPlayersMenu::m_pingC = 1000 private
Definition at line 14 of file LobbyPlayersMenu.as.
Referenced by Update().
m_wPlayerList
Widget Menu::LobbyPlayersMenu::m_wPlayerList private
Definition at line 6 of file LobbyPlayersMenu.as.
Referenced by Initialize(), and UpdatePlayerList().
m_wPlayerTemplate
Widget Menu::LobbyPlayersMenu::m_wPlayerTemplate private
Definition at line 7 of file LobbyPlayersMenu.as.
Referenced by Initialize(), and UpdatePlayerList().
m_wPlayerWindow
Widget Menu::LobbyPlayersMenu::m_wPlayerWindow private
Definition at line 5 of file LobbyPlayersMenu.as.
Referenced by Initialize().
m_wTitle
TextWidget Menu::LobbyPlayersMenu::m_wTitle private
Definition at line 9 of file LobbyPlayersMenu.as.
Referenced by Initialize(), and UpdatePlayerList().
The documentation for this class was generated from the following file:
scripts/GUI/Menus/LobbyPlayersMenu.as