HoHDocs: Menu::SplitscreenPlayer Class Reference
Menu::SplitscreenPlayer Class Reference
Private Member Functions
SplitscreenPlayer (int index)
void DisplayName (int playerIndex)
void SetSkin (string skin)
Private Attributes
int m_index
GameInput m_inputGame
MenuInput m_inputMenu
ControlMap m_map
RectWidget m_widget
string m_skin = "serious_sam"
Detailed Description
Definition at line 3 of file SplitscreenSelectionMenu.as.
Constructor & Destructor Documentation
SplitscreenPlayer()
Menu::SplitscreenPlayer::SplitscreenPlayer (int index) inline private
Definition at line 16 of file SplitscreenSelectionMenu.as.
References Platform::GetGameInput(), Platform::GetMenuInput(), m_index, m_inputGame, m_inputMenu, and m_map.
         {
             m_index = index;
             @m_inputGame = Platform::GetGameInput(index);
             @m_inputMenu = Platform::GetMenuInput(index);
             auto maps = m_inputGame.GetControlMaps();
             if (maps.length() == 1)
                 @m_map = maps[0];
             else
                 PrintError("There are " + maps.length() + " maps assigned to index " + index);
         }
Member Function Documentation
DisplayName()
void Menu::SplitscreenPlayer::DisplayName (int playerIndex) inline private
Definition at line 30 of file SplitscreenSelectionMenu.as.
References g_gameMode, GetPlayerColor(), RectWidget::m_color, m_inputGame, m_inputMenu, m_map, m_skin, Widget::m_visible, m_widget, SetSkin(), TextWidget::SetText(), and ControlMap::UseMouseLook.
Referenced by Menu::JoinInput().
         {
             auto gm = cast<BaseGameMode>(g_gameMode);
             if (playerIndex == 0)
             {
                 if (!m_map.UseMouseLook)
                 {
                     @gm.m_mice[0].m_hackSecondGame = m_inputGame;
                     @gm.m_mice[0].m_hackSecondMenu = m_inputMenu;
                 }
                 else
                 {
                     @gm.m_mice[0].m_hackSecondGame = null;
                     @gm.m_mice[0].m_hackSecondMenu = null;
                 }
             }
             m_widget.m_color = ParseColorRGBA("#" + GetPlayerColor(playerIndex) + "7f");
             TextWidget@ wPlayerName = cast<TextWidget>(m_widget.GetWidgetById("name"));
             if (wPlayerName !is null)
             {
                 dictionary params = { { "num", playerIndex + 1 } };
                 wPlayerName.SetText(Resources::GetString(".player.num", params));
             }
             Widget@ wPrompt = m_widget.GetWidgetById("prompt");
             if (wPrompt !is null)
                 wPrompt.m_visible = !m_map.UseMouseLook;
             Widget@ wKbmButtonLeft = m_widget.GetWidgetById("kbm-skin-left");
             if (wKbmButtonLeft !is null)
                 wKbmButtonLeft.m_visible = m_map.UseMouseLook;
             Widget@ wKbmButtonRight = m_widget.GetWidgetById("kbm-skin-right");
             if (wKbmButtonRight !is null)
                 wKbmButtonRight.m_visible = m_map.UseMouseLook;
             Widget@ wGpSkinLeft = m_widget.GetWidgetById("gp-skin-left");
             if (wGpSkinLeft !is null)
                 wGpSkinLeft.m_visible = !m_map.UseMouseLook;
             Widget@ wGpSkinRight = m_widget.GetWidgetById("gp-skin-right");
             if (wGpSkinRight !is null)
                 wGpSkinRight.m_visible = !m_map.UseMouseLook;
             SetSkin(m_skin);
         }
SetSkin()
void Menu::SplitscreenPlayer::SetSkin (string skin) inline private
Definition at line 79 of file SplitscreenSelectionMenu.as.
References m_skin, m_widget, ScriptSprite(), and SpriteWidget::SetSprite().
Referenced by DisplayName(), and Menu::SkinInput().
         {
             m_skin = skin;
             SpriteWidget@ wSkin = cast<SpriteWidget>(m_widget.GetWidgetById("skin-preview"));
             if (wSkin is null)
                 return;
             Texture2D@ tex = Resources::GetTexture2D("actors/players/skins/" + skin + "/hud.png");
             wSkin.SetSprite(ScriptSprite(tex, vec4(96, 0, 32, 32)));
         }
Member Data Documentation
m_index
int Menu::SplitscreenPlayer::m_index private
Definition at line 5 of file SplitscreenSelectionMenu.as.
Referenced by SplitscreenPlayer().
m_inputGame
GameInput Menu::SplitscreenPlayer::m_inputGame private
Definition at line 7 of file SplitscreenSelectionMenu.as.
Referenced by DisplayName(), and SplitscreenPlayer().
m_inputMenu
MenuInput Menu::SplitscreenPlayer::m_inputMenu private
Definition at line 8 of file SplitscreenSelectionMenu.as.
Referenced by DisplayName(), and SplitscreenPlayer().
m_map
ControlMap Menu::SplitscreenPlayer::m_map private
Definition at line 10 of file SplitscreenSelectionMenu.as.
Referenced by DisplayName(), Menu::JoinInput(), and SplitscreenPlayer().
m_skin
string Menu::SplitscreenPlayer::m_skin = "serious_sam" private
Definition at line 14 of file SplitscreenSelectionMenu.as.
Referenced by DisplayName(), SetSkin(), and Menu::SkinInput().
m_widget
RectWidget Menu::SplitscreenPlayer::m_widget private
Definition at line 12 of file SplitscreenSelectionMenu.as.
Referenced by DisplayName(), Menu::JoinInput(), Menu::RemoveInput(), and SetSkin().
The documentation for this class was generated from the following file:
scripts/GUI/Menus/SplitscreenSelectionMenu.as