HoHDocs: PlayerMenu Class Reference
PlayerMenu Class Reference
Private Member Functions
PlayerMenu (GUIBuilder@ b)
bool BlocksLower () override
void SetTab (string id)
void Show () override
void Close () override
void Update (int dt) override
void AfterUpdate ()
void Draw (SpriteBatch &sb, int idt) override
void OnFunc (Widget@ sender, string name) override
Private Attributes
MenuTabSystem m_tabSystem
PlayerMenuMapTab m_tabMap
Detailed Description
Definition at line 1 of file PlayerMenu.as.
Constructor & Destructor Documentation
PlayerMenu()
PlayerMenu::PlayerMenu (GUIBuilder@ b) inline private
Definition at line 7 of file PlayerMenu.as.
References MenuTabSystem::AddTab(), m_tabMap, and m_tabSystem.
     {
         super(b, "gui/playermenu.gui");
         @m_tabSystem = MenuTabSystem(this);
         m_tabSystem.AddTab(@m_tabMap = PlayerMenuMapTab(), b);
         m_tabSystem.AddTab(PlayerMenuCharacterTab(), b);
         m_tabSystem.AddTab(PlayerMenuStatsTab(), b);
     }
Member Function Documentation
AfterUpdate()
void PlayerMenu::AfterUpdate () inline private
Definition at line 66 of file PlayerMenu.as.
References MenuTabSystem::AfterUpdate(), m_tabSystem, and UserWindow::m_visible.
Referenced by Campaign::PreRenderFrame().
     {
         if (m_visible)
             m_tabSystem.AfterUpdate();
     }
BlocksLower()
bool PlayerMenu::BlocksLower () inline override private
Definition at line 18 of file PlayerMenu.as.
     {
         return true;
     }
Close()
void PlayerMenu::Close () inline override private
Definition at line 46 of file PlayerMenu.as.
References UserWindow::Close(), MenuTabSystem::Close(), m_tabSystem, UserWindow::m_visible, and PauseGame().
Referenced by OnFunc().
     {
         if (!m_visible)
             return;
         m_tabSystem.Close();
         UserWindow::Close();
         PauseGame(false, true);
     }
Draw()
void PlayerMenu::Draw (SpriteBatch & sb, int idt) inline override private
Definition at line 72 of file PlayerMenu.as.
References UserWindow::Draw(), MenuTabSystem::Draw(), m_tabSystem, and UserWindow::m_visible.
     {
         if (!m_visible)
             return;
         UserWindow::Draw(sb, idt);
         m_tabSystem.Draw(sb, idt);
     }
OnFunc()
void PlayerMenu::OnFunc (Widget@ sender, string name) inline override private
Definition at line 82 of file PlayerMenu.as.
References Close(), m_tabSystem, name, MenuTabSystem::OnFunc(), and SetTab().
     {
         auto parse = name.split(" ");
         if (parse[0] == "close")
             Close();
         else if (parse[0] == "set-tab")
             SetTab(parse[1]);
         else
             m_tabSystem.OnFunc(sender, name);
     }
SetTab()
void PlayerMenu::SetTab (string id) inline private
Definition at line 23 of file PlayerMenu.as.
References m_tabSystem, Modifiers::Set, and MenuTabSystem::SetTab().
Referenced by OnFunc(), and Show().
     {
         GlobalCache::Set("playermenu-tab", id);
         m_tabSystem.SetTab(id);
     }
Show()
void PlayerMenu::Show () inline override private
Definition at line 30 of file PlayerMenu.as.
References Get(), UserWindow::m_visible, PauseGame(), SetTab(), and UserWindow::Show().
     {
         if (m_visible)
             return;
         UserWindow::Show();
         PauseGame(true, true);
         string startTab = GlobalCache::Get("playermenu-tab");
         if (startTab == "")
             startTab = "character";
         SetTab(startTab);
     }
Update()
void PlayerMenu::Update (int dt) inline override private
Definition at line 58 of file PlayerMenu.as.
References m_tabSystem, UserWindow::m_visible, UserWindow::Update(), and MenuTabSystem::Update().
     {
         if (m_visible)
             m_tabSystem.Update(dt);
         UserWindow::Update(dt);
     }
Member Data Documentation
m_tabMap
PlayerMenuMapTab PlayerMenu::m_tabMap private
Definition at line 5 of file PlayerMenu.as.
Referenced by PlayerMenu(), Campaign::RenderWidgets(), and Campaign::UpdateWidgets().
m_tabSystem
MenuTabSystem PlayerMenu::m_tabSystem private
Definition at line 3 of file PlayerMenu.as.
Referenced by AfterUpdate(), Close(), Draw(), OnFunc(), PlayerMenu(), SetTab(), and Update().
The documentation for this class was generated from the following file:
scripts/GUI/PlayerMenu.as