HoHDocs: ChapelShopMenuContent Class Reference
ChapelShopMenuContent Class Reference
Private Member Functions
ChapelShopMenuContent (ShopMenu@ shopMenu)
string GetTitle () override
void OnShow () override
void Update (int dt) override
int ShouldEnableButton (uint rowIndex, uint columnIndex)
void ReloadList () override
bool BuyItem (Upgrades::Upgrade@ upgrade, Upgrades::UpgradeStep@ step) override
string GetGuiFilename () override
void OnFunc (Widget@ sender, string name) override
Private Attributes
Widget m_wRowList
Widget m_wTemplateRow
Widget m_wTemplateItemContainer
UpgradeShopButtonWidget m_wTemplateItem
Widget m_wTemplateUnknown
Widget m_wTemplateOwned
Widget m_wTemplateLocked
Sprite m_spriteGold
Upgrades::ChapelShop m_shop
array< array< RectWidget@>@> m_itemContainers
Detailed Description
Definition at line 1 of file ChapelShopMenu.as.
Constructor & Destructor Documentation
ChapelShopMenuContent()
ChapelShopMenuContent::ChapelShopMenuContent (ShopMenu@ shopMenu) inline private
Definition at line 18 of file ChapelShopMenu.as.
References Upgrades::GetShop(), and m_shop.
     {
         super(shopMenu);
         @m_shop = cast<Upgrades::ChapelShop>(Upgrades::GetShop("chapel"));
     }
Member Function Documentation
BuyItem()
bool ChapelShopMenuContent::BuyItem (Upgrades::Upgrade@ upgrade, Upgrades::UpgradeStep@ step) inline override private
Definition at line 290 of file ChapelShopMenu.as.
References Stats::Add(), ShopMenuContent::BuyItem(), and GetLocalPlayerRecord().
     {
         if (!ShopMenuContent::BuyItem(upgrade, step))
             return false;
         Stats::Add("blessings-purchased", 1, GetLocalPlayerRecord());
         return true;
     }
GetGuiFilename()
string ChapelShopMenuContent::GetGuiFilename () inline override private
Definition at line 299 of file ChapelShopMenu.as.
     {
         return "gui/shop/chapel.gui";
     }
GetTitle()
string ChapelShopMenuContent::GetTitle () inline override private
Definition at line 25 of file ChapelShopMenu.as.
     {
         return Resources::GetString(".shop.chapel");
     }
OnFunc()
void ChapelShopMenuContent::OnFunc (Widget@ sender, string name) inline override private
Definition at line 304 of file ChapelShopMenu.as.
References g_gameMode, GetLocalPlayer(), GetLocalPlayerRecord(), Upgrades::ChapelShop::m_rows, m_shop, ShopMenuContent::m_shopMenu, name, ShopMenuContent::OnFunc(), Player::RefreshModifiers(), ReloadList(), and AGameMode::ShowDialog().
     {
         if (name == "convert")
         {
             g_gameMode.ShowDialog(
                 "convert",
                 Resources::GetString(".shop.chapel.convert.prompt"),
                 Resources::GetString(".menu.yes"),
                 Resources::GetString(".menu.no"),
                 m_shopMenu
             );
         }
         else if (name == "convert yes")
         {
             auto record = GetLocalPlayerRecord();
             for (uint i = 0; i < m_shop.m_rows.length(); i++)
             {
                 auto row = m_shop.m_rows[i];
                 for (uint x = 0; x < row.length(); x++)
                 {
                     auto upgr = row[x];
                     if (!upgr.IsOwned(record))
                         continue;
                     for (uint j = 0; j < record.upgrades.length(); j++)
                     {
                         auto ownedUpgrade = record.upgrades[j];
                         if (ownedUpgrade.m_id == upgr.m_id)
{
                             record.upgrades.removeAt(j);
                             break;
                         }
                     }
                 }
             }
             //TODO: Netsync
             GetLocalPlayer().RefreshModifiers();
             ReloadList();
         }
         else
             ShopMenuContent::OnFunc(sender, name);
     }
OnShow()
void ChapelShopMenuContent::OnShow () inline override private
Definition at line 30 of file ChapelShopMenu.as.
References Widget::GetWidgetById(), ShopMenuContent::m_def, m_spriteGold, ShopMenuContent::m_widget, m_wRowList, m_wTemplateItem, m_wTemplateItemContainer, m_wTemplateLocked, m_wTemplateOwned, m_wTemplateRow, m_wTemplateUnknown, and ReloadList().
     {
         @m_wRowList = m_widget.GetWidgetById("row-list");
         @m_wTemplateRow = m_widget.GetWidgetById("row-template");
         @m_wTemplateItemContainer = m_widget.GetWidgetById("item-container-template");
         @m_wTemplateItem = cast<UpgradeShopButtonWidget>(m_widget.GetWidgetById("item-template"));
         @m_wTemplateUnknown = m_widget.GetWidgetById("item-template-unknown");
         @m_wTemplateOwned = m_widget.GetWidgetById("item-template-owned");
         @m_wTemplateLocked = m_widget.GetWidgetById("item-template-locked");
         @m_spriteGold = m_def.GetSprite("icon-gold");
         ReloadList();
     }
ReloadList()
void ChapelShopMenuContent::ReloadList () inline override private
Definition at line 135 of file ChapelShopMenu.as.
References Widget::AddChild(), Widget::ClearChildren(), UpgradeShopButtonWidget::Clone(), Widget::Clone(), ShopMenu::DoLayout(), Upgrades::ChapelShop::GetIcon(), Upgrades::ChapelShop::GetIconIndex(), GetLocalPlayerRecord(), m_itemContainers, Upgrades::ChapelShop::m_rows, m_shop, ShopMenuContent::m_shopMenu, m_spriteGold, m_wRowList, m_wTemplateItem, m_wTemplateItemContainer, m_wTemplateLocked, m_wTemplateOwned, m_wTemplateRow, m_wTemplateUnknown, Widget::SetID(), and ShouldEnableButton().
Referenced by OnFunc(), and OnShow().
     {
         //TODO: We have to hide the tooltip here
         m_itemContainers.removeRange(0, m_itemContainers.length());
         m_wRowList.ClearChildren();
         int lastOwnedIcon = -1;
         int lastOwnedX = -1;
         auto record = GetLocalPlayerRecord();
         for (uint i = 0; i < m_shop.m_rows.length(); i++)
         {
             auto wRowContainer = m_wTemplateRow.Clone();
             wRowContainer.SetID("");
             wRowContainer.m_visible = true;
             m_wRowList.AddChild(wRowContainer);
             auto wRowItems = wRowContainer.GetWidgetById("items");
             int thisOwnedIcon = -1;
             int thisOwnedX = -1;
             Widget@ wNewItem = null;
             array<RectWidget@>@ arrContainers = array<RectWidget@>();
             m_itemContainers.insertLast(arrContainers);
             auto row = m_shop.m_rows[i];
             for (uint j = 0; j < row.length(); j++)
             {
                 auto upgrade = row[j];
                 auto step = upgrade.GetStep(1);
                 int shouldEnable = ShouldEnableButton(i, j);
                 if (shouldEnable == 0)
                 {
                     auto newItem = m_wTemplateUnknown.Clone();
                     newItem.SetID("");
                     newItem.m_visible = true;
                     newItem.m_tooltipTitle = step.GetTooltipTitle();
                     newItem.AddTooltipSub(m_spriteGold, ("" + step.m_costGold));
                     newItem.m_tooltipText = step.GetTooltipDescription();
                     @wNewItem = newItem;
                 }
                 else if (shouldEnable == -1 && !step.IsOwned(record))
                 {
                     auto newItem = m_wTemplateLocked.Clone();
                     newItem.SetID("");
                     newItem.m_visible = true;
                     newItem.m_tooltipTitle = step.GetTooltipTitle();
                     newItem.m_tooltipText = step.GetTooltipDescription();
                     auto wIcon = cast<SpriteWidget>(newItem.GetWidgetById("icon"));
                     if (wIcon !is null)
                     {
                         if (i == 0)
                             wIcon.SetSprite(m_shop.GetIcon(0, j));
                         else
{
                             int index = m_shop.GetIconIndex(lastOwnedIcon, j - lastOwnedX);
                             wIcon.SetSprite(m_shop.GetIcon(i, index));
                         }
                     }
                     @wNewItem = newItem;
                 }
                 else if (step.IsOwned(record))
                 {
                     auto newItem = m_wTemplateOwned.Clone();
                     newItem.SetID("");
                     newItem.m_visible = true;
                     newItem.m_tooltipTitle = step.GetTooltipTitle();
                     newItem.m_tooltipText = step.GetTooltipDescription();
                     auto wIcon = cast<SpriteWidget>(newItem.GetWidgetById("icon"));
                     if (wIcon !is null)
                     {
                         if (i == 0)
{
                             wIcon.SetSprite(m_shop.GetIcon(0, j));
                             thisOwnedIcon = j;
                             thisOwnedX = j;
                         }
                         else
{
                             int index = m_shop.GetIconIndex(lastOwnedIcon, j - lastOwnedX);
                             wIcon.SetSprite(m_shop.GetIcon(i, index));
                             thisOwnedIcon = index;
                             thisOwnedX = j;
                         }
                     }
                     @wNewItem = newItem;
                 }
                 else
                 {
                     auto newButton = cast<UpgradeShopButtonWidget>(m_wTemplateItem.Clone());
                     newButton.SetID("");
                     newButton.m_visible = true;
                     newButton.Set(this, upgrade, step);
                     newButton.m_enabled = (newButton.m_enabled && shouldEnable == 1);
                     newButton.m_tooltipTitle = step.GetTooltipTitle();
                     newButton.AddTooltipSub(m_spriteGold, ("" + step.m_costGold));
                     newButton.m_tooltipText = step.GetTooltipDescription();
                     if (i == 0)
                     {
                         @newButton.m_scriptSpriteIcon = m_shop.GetIcon(0, j);
                         if (step.IsOwned(record))
{
                             thisOwnedIcon = i;
                             thisOwnedX = j;
                         }
                     }
                     else
                     {
                         int index = m_shop.GetIconIndex(lastOwnedIcon, j - lastOwnedX);
                         @newButton.m_scriptSpriteIcon = m_shop.GetIcon(i, index);
                         if (step.IsOwned(record))
{
                             thisOwnedIcon = index;
                             thisOwnedX = j;
                         }
                     }
                     @wNewItem = newButton;
                 }
                 if (wNewItem !is null)
                 {
                     auto wNewContainer = cast<RectWidget>(m_wTemplateItemContainer.Clone());
                     wNewContainer.SetID("");
                     wNewContainer.m_visible = true;
                     wNewContainer.m_borderColor.w = 0.0f;
                     wNewContainer.AddChild(wNewItem);
                     wRowItems.AddChild(wNewContainer);
                     arrContainers.insertLast(wNewContainer);
                 }
             }
             lastOwnedIcon = thisOwnedIcon;
             lastOwnedX = thisOwnedX;
         }
         m_shopMenu.DoLayout();
     }
ShouldEnableButton()
int ChapelShopMenuContent::ShouldEnableButton (uint rowIndex, uint columnIndex) inline private
Definition at line 79 of file ChapelShopMenu.as.
References GetLocalPlayerRecord(), ShopMenu::m_currentShopLevel, Upgrades::ChapelShop::m_rows, m_shop, and ShopMenuContent::m_shopMenu.
Referenced by ReloadList().
     {
         auto record = GetLocalPlayerRecord();
         auto row = m_shop.m_rows[rowIndex];
         for (uint i = 0; i < row.length(); i++)
         {
             if (row[i].IsOwned(record))
             {
                 if (rowIndex == 0)
                     return -1;
                 auto rowAbove = m_shop.m_rows[rowIndex - 1];
                 for (uint j = 0; j < rowAbove.length(); j++)
                 {
                     if (!rowAbove[j].IsOwned(record))
                         continue;
                     if (columnIndex == j || columnIndex == j + 1)
                         return -1;
                     else
                         return 0;
                 }
                 return 0;
             }
         }
         if (rowIndex == 0)
             return 1;
         if (int(rowIndex) >= m_shopMenu.m_currentShopLevel)
             return 0;
         else
         {
             auto rowAbove = m_shop.m_rows[rowIndex - 1];
             if (columnIndex == row.length() - 1)
             {
                 if (rowAbove[rowAbove.length() - 1].IsOwned(record))
                     return 1;
             }
             else if (columnIndex == 0)
             {
                 if (rowAbove[0].IsOwned(record))
                     return 1;
             }
             else
             {
                 if (rowAbove[columnIndex - 1].IsOwned(record) || rowAbove[columnIndex].IsOwned(record))
                     return 1;
             }
         }
         return 0;
     }
Update()
void ChapelShopMenuContent::Update (int dt) inline override private
Definition at line 46 of file ChapelShopMenu.as.
References m_itemContainers.
     {
         int highlightRow = -1;
         int highlightCols = -1;
         for (uint i = 0; i < m_itemContainers.length(); i++)
         {
             auto row = m_itemContainers[i];
             for (uint j = 0; j < row.length(); j++)
             {
                 auto item = row[j];
                 if (highlightRow != -1)
                 {
                     if (int(i) == highlightRow && (int(j) == highlightCols || int(j) == highlightCols + 1))
                         item.m_borderColor.a = 1.0f;
                     else
                         item.m_borderColor.a = 0.0f;
                 }
                 else
                 {
                     if (item.m_hovering)
                     {
                         item.m_borderColor.a = 1.0f;
                         highlightRow = i + 1;
                         highlightCols = j;
                     }
                     else
                         item.m_borderColor.a = 0.0f;
                 }
             }
         }
     }
Member Data Documentation
m_itemContainers
array<array<RectWidget@>@> ChapelShopMenuContent::m_itemContainers private
Definition at line 16 of file ChapelShopMenu.as.
Referenced by ReloadList(), and Update().
m_shop
Upgrades::ChapelShop ChapelShopMenuContent::m_shop private
Definition at line 14 of file ChapelShopMenu.as.
Referenced by ChapelShopMenuContent(), OnFunc(), ReloadList(), and ShouldEnableButton().
m_spriteGold
Sprite ChapelShopMenuContent::m_spriteGold private
Definition at line 12 of file ChapelShopMenu.as.
Referenced by OnShow(), and ReloadList().
m_wRowList
Widget ChapelShopMenuContent::m_wRowList private
Definition at line 3 of file ChapelShopMenu.as.
Referenced by OnShow(), and ReloadList().
m_wTemplateItem
UpgradeShopButtonWidget ChapelShopMenuContent::m_wTemplateItem private
Definition at line 7 of file ChapelShopMenu.as.
Referenced by OnShow(), and ReloadList().
m_wTemplateItemContainer
Widget ChapelShopMenuContent::m_wTemplateItemContainer private
Definition at line 6 of file ChapelShopMenu.as.
Referenced by OnShow(), and ReloadList().
m_wTemplateLocked
Widget ChapelShopMenuContent::m_wTemplateLocked private
Definition at line 10 of file ChapelShopMenu.as.
Referenced by OnShow(), and ReloadList().
m_wTemplateOwned
Widget ChapelShopMenuContent::m_wTemplateOwned private
Definition at line 9 of file ChapelShopMenu.as.
Referenced by OnShow(), and ReloadList().
m_wTemplateRow
Widget ChapelShopMenuContent::m_wTemplateRow private
Definition at line 4 of file ChapelShopMenu.as.
Referenced by OnShow(), and ReloadList().
m_wTemplateUnknown
Widget ChapelShopMenuContent::m_wTemplateUnknown private
Definition at line 8 of file ChapelShopMenu.as.
Referenced by OnShow(), and ReloadList().
The documentation for this class was generated from the following file:
scripts/GUI/Shop/ChapelShopMenu.as