HoHDocs: ScriptWidgetHost Class Reference
ScriptWidgetHost Class Reference
Private Member Functions
ScriptWidgetHost ()
GUIDef LoadWidget (GUIBuilder@ b, string filename) override
void Initialize (bool loaded)
bool ShouldFreezeControls ()
bool ShouldDisplayCursor ()
bool ShouldSaveExistance ()
void Stop ()
Private Attributes
GUIDef m_def
WorldScript::OpenInterface m_script
Detailed Description
Definition at line 1 of file ScriptWidgetHost.as.
Constructor & Destructor Documentation
ScriptWidgetHost()
ScriptWidgetHost::ScriptWidgetHost () inline private
Definition at line 7 of file ScriptWidgetHost.as.
     {
         super();
     }
Member Function Documentation
Initialize()
void ScriptWidgetHost::Initialize (bool loaded) inline private
Definition at line 18 of file ScriptWidgetHost.as.
Referenced by WorldScript::OpenInterface::Start().
 { }
LoadWidget()
GUIDef ScriptWidgetHost::LoadWidget (GUIBuilder@ b, string filename) inline override private
Definition at line 12 of file ScriptWidgetHost.as.
References LoadWidget(), and m_def.
Referenced by WorldScript::OpenInterface::Start().
     {
         @m_def = IWidgetHoster::LoadWidget(b, filename);
         return m_def;
     }
ShouldDisplayCursor()
bool ScriptWidgetHost::ShouldDisplayCursor () inline private
Definition at line 20 of file ScriptWidgetHost.as.
 { return false; }
ShouldFreezeControls()
bool ScriptWidgetHost::ShouldFreezeControls () inline private
Definition at line 19 of file ScriptWidgetHost.as.
 { return false; }
ShouldSaveExistance()
bool ScriptWidgetHost::ShouldSaveExistance () inline private
Definition at line 21 of file ScriptWidgetHost.as.
Referenced by WorldScript::OpenInterface::Save().
 { return true; }
Stop()
void ScriptWidgetHost::Stop () inline private
Definition at line 23 of file ScriptWidgetHost.as.
References m_script, and WorldScript::OpenInterface::Stop().
Referenced by CharacterCustomizationNPC::OnFunc(), StatisticsInterface::OnFunc(), DungeonSettingsMenu::OnFunc(), OnFunc(), and Stop().
     {
         m_script.Stop();
     }
Member Data Documentation
m_def
GUIDef ScriptWidgetHost::m_def private
Definition at line 3 of file ScriptWidgetHost.as.
Referenced by CharacterCustomizationNPC::Initialize(), and LoadWidget().
m_script
WorldScript::OpenInterface ScriptWidgetHost::m_script private
Definition at line 5 of file ScriptWidgetHost.as.
Referenced by WorldScript::OpenInterface::Start(), and Stop().
The documentation for this class was generated from the following file:
scripts/GUI/ScriptWidgetHost.as