HoHDocs: InventoryWidget Class Reference
InventoryWidget Class Reference
Private Member Functions
InventoryWidget ()
void Load (WidgetLoadingContext &ctx) override
void UpdateFromRecord (PlayerRecord@ record)
void AddItem (PlayerRecord@ record, ActorItem@ item)
Private Attributes
InventoryItemWidget m_itemTemplate
bool m_local
Detailed Description
Definition at line 1 of file InventoryWidget.as.
Constructor & Destructor Documentation
InventoryWidget()
InventoryWidget::InventoryWidget () inline private
Definition at line 7 of file InventoryWidget.as.
     {
         super();
     }
Member Function Documentation
AddItem()
void InventoryWidget::AddItem (PlayerRecord@ record, ActorItem@ item) inline private
Definition at line 24 of file InventoryWidget.as.
References ScrollableWidget::AddChild(), InventoryItemWidget::Clone(), and m_itemTemplate.
Referenced by UpdateFromRecord().
     {
         auto wNewItem = cast<InventoryItemWidget>(m_itemTemplate.Clone());
         if (wNewItem is null)
             return;
         wNewItem.Set(record, item);
         wNewItem.SetID("");
         wNewItem.m_visible = true;
         AddChild(wNewItem);
     }
Load()
void InventoryWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 12 of file InventoryWidget.as.
References Widget::Load().
Referenced by LoadInventoryWidget().
     {
         ScrollableRectWidget::Load(ctx);
     }
UpdateFromRecord()
void InventoryWidget::UpdateFromRecord (PlayerRecord@ record) inline private
Definition at line 17 of file InventoryWidget.as.
References AddItem(), ScrollableWidget::ClearChildren(), g_items, and ActorItems::GetItem().
Referenced by LootBox::Initialize(), and PlayerMenuCharacterTab::UpdateNow().
     {
         ClearChildren();
         for (uint j = 0; j < record.items.length(); j++)
             AddItem(record, g_items.GetItem(record.items[j]));
     }
Member Data Documentation
m_itemTemplate
InventoryItemWidget InventoryWidget::m_itemTemplate private
Definition at line 3 of file InventoryWidget.as.
Referenced by AddItem(), LootBox::Initialize(), and PlayerMenuCharacterTab::OnCreated().
m_local
bool InventoryWidget::m_local private
Definition at line 5 of file InventoryWidget.as.
The documentation for this class was generated from the following file:
scripts/GUI/Widgets/InventoryWidget.as