HoHDocs: Widget Class Reference
Widget Class Reference
Private Member Functions
Widget ()
int opCmp (const Widget@ w)
void SetID (string id)
Widget Clone ()
void CloneInto (Widget@ w)
void Load ()
void LoadWidthHeight (WidgetLoadingContext &ctx, bool required=true)
void Load (WidgetLoadingContext &ctx)
void ClearTooltipSubs ()
void AddTooltipSub (Sprite@ sprite, string text)
void Update (int dt)
vec2 GetAbsolutePosition ()
vec2 GetRelativeOffset ()
bool UseSmoothOrigin ()
void CalculateOrigin (vec2 origin, vec2 parentSz)
void DoLayout (vec2 origin, vec2 parentSz)
void DrawBorder (SpriteBatch &sb, vec2 pos, vec2 size, int borderWidth=1, vec4 borderColor=vec4(1, 1, 1, 1), BorderType borderType=BorderType::Inner)
vec2 GetOrigin ()
bool ShouldDrawChild (Widget@ child)
void Draw (SpriteBatch &sb, bool debugDraw=false)
void DrawChildren (SpriteBatch &sb, bool debugDraw=false)
void DebugDraw (SpriteBatch &sb)
bool ContainsFocusable ()
void ScrollTo ()
void SetHovering (bool hovering, vec2 mousePos, bool force=false)
bool UpdateInput (GameInput &input)
bool UpdateInput (vec2 origin, vec2 parentSz, vec3 mousePos)
Rect GetRectangle (int inset=0)
vec2 GetCenter ()
array< Widget@> IntersectWidgets (Rect &rect, bool onlyCanFocus=false, Widget@ ignore=null, bool onlyInsideParent=false)
Widget ClosestInArray (array< Widget@> arr, WidgetDirection dir)
bool FocusTowards (WidgetDirection dir)
GUIDef AddResource (GUIBuilder@ b, string filename)
void AddChild (ref widget, int insertAt=-1)
void AddedToParent ()
void RemoveFromParent ()
void SetOriginFromParent (vec2 origin)
void MoveToParentInPlace (Widget@ newParent, int insertAt=-1)
bool Unfocus ()
void SetHost (IWidgetHoster@ host)
void ClearChildren ()
void Remove ()
void DoDraw (SpriteBatch &sb, vec2 pos)
void Animate (WidgetAnimation@ anim)
void FinishAnimations ()
void CancelAnimations ()
void AnimateSet (string key, vec4 v)
void AnimateSet (string key, vec2 v)
void AnimateSet (string key, float f)
void AnimateSet (string key, bool b)
void AnimateSet (string key, Sprite@ s)
void AnimateSet (string key, string str)
Widget GetWidgetById (string id)
Widget GetWidgetByIdImpl (uint idHash)
array< Widget@> GetWidgetsById (string id)
bool PassesFilter (string str)
void ShowTooltip ()
bool OnMouseDown (vec2 mousePos)
bool OnMouseUp (vec2 mousePos)
bool OnClick (vec2 mousePos)
bool OnDoubleClick (vec2 mousePos)
void OnMouseEnter (vec2 mousePos, bool forced)
void OnMouseLeave (vec2 mousePos)
Private Attributes
Widget m_parent
IWidgetHoster m_host
bool m_priorityFocus
bool m_pixelPerfect
int m_doubleClickTime
vec2 m_doubleClickPos
bool m_canDoubleClick
vec2 m_anchor
vec2 m_offset
vec2 m_padding
string m_id
uint m_idHash
string m_filter
int m_width
int m_height
float m_widthScalar = -1
float m_heightScalar = -1
WidgetFlow m_flow
bool m_flowAffected
int m_spacing
int m_spacingLine
bool m_flowFlip
bool m_flowFlipOrder
bool m_hovering
bool m_defaultFocus
bool m_canFocus
bool m_canFocusInput
string m_focusUp
string m_focusDown
string m_focusLeft
string m_focusRight
bool m_smoothOrigin
bool m_smoothOriginForced
vec2 m_origin
vec2 m_originPrev
bool m_originPrevSet
vec2 m_originOriginal
array< Widget@> m_children
array< WidgetAnimation@> m_animations
vec2 m_lastMousePos
vec2 m_childOffset
bool m_tooltipEnabled
string m_tooltipTitle
array< WidgetSubText@> m_tooltipSubtexts
string m_tooltipText
int m_tooltipAlign
private bool _m_visible
bool m_visible
Platform::CursorInfo m_cursor
Detailed Description
Definition at line 41 of file Widget.as.
Constructor & Destructor Documentation
Widget()
Widget::Widget () inline private
Definition at line 125 of file Widget.as.
References m_children.
Referenced by Clone().
     {
         @m_children = array<Widget@>();
     }
Member Function Documentation
AddChild()
void Widget::AddChild (ref widget, int insertAt = -1) inline private
Definition at line 884 of file Widget.as.
References AddedToParent(), m_children, m_host, m_parent, and SetHost().
Referenced by NotificationManager::Add(), GuildHallAccomplishmentsTab::AddBoss(), HUD::AddBossBar(), AddButton(), TownhallMenuContent::AddButton(), GuildHallBeastiaryTab::AddCategory(), GuildHallStatsTab::AddCharacterToList(), ScrollableWidget::AddChild(), GuildHallStatsTab::AddClassesToList(), AddDrink(), GuildHallStatsTab::AddGuildToList(), AddHeader(), GuildHallAccomplishmentsTab::AddHeader(), UpgradeShopMenuContent::AddItem(), Menu::ControlMapMenu::AddNewControl(), AddResource(), GameOver::AddSentence(), GuildHallStatsTab::AddSeparatorToList(), GuildHallStatsTab::AddStatisticsToList(), CloneInto(), CharacterCustomizationBase::ColorsChanged(), Menu::ControlsMenu::Initialize(), Menu::EditSlotMenu::Initialize(), HUD::InitializeKeys(), Menu::JoinInput(), MoveToParentInPlace(), Menu::TestMenu::OnFunc(), StatuesShopMenuContent::RefreshBuyList(), GuildHallAccomplishmentsTab::RefreshList(), StatuesShopMenuContent::RefreshPlacementList(), DrinksMenuContent::ReloadList(), GeneralStoreMenuContent::ReloadList(), FountainShopMenuContent::ReloadList(), ChapelShopMenuContent::ReloadList(), SkillsShopMenuContent::ReloadList(), TownhallMenuContent::ReloadList(), ReloadSplits(), ScoreDialog::Set(), HUD::SetTopNumberIcon(), StatueSelectMenu::Show(), ShopMenu::Show(), HUD::ShowBuffIcon(), HUDCoop::Update(), and Menu::LobbyPlayersMenu::UpdatePlayerList().
     {
         Widget@ w = cast<Widget>(widget);
         if (insertAt == -1 || insertAt > int(m_children.length()))
             m_children.insertLast(w);
         else
             m_children.insertAt(insertAt, w);
         @w.m_parent = this;
         if (w.m_host is null)
             SetHost(m_host);
         w.AddedToParent();
     }
AddedToParent()
void Widget::AddedToParent () inline private
Definition at line 898 of file Widget.as.
Referenced by AddChild(), and DetailsWidget::AddedToParent().
     {
     }
AddResource()
GUIDef Widget::AddResource (GUIBuilder@ b, string filename) inline private
Definition at line 865 of file Widget.as.
References AddChild(), and m_host.
Referenced by ShopMenu::Show().
     {
         GUIDef@ def = Resources::GetGUIDef(filename);
         if (def is null)
         {
             PrintError("GUI Definition is null for: '" + filename + "'");
             return null;
         }
         Widget@ w = cast<Widget>(b.BuildGUI(def, m_host));
         if (w is null)
         {
             PrintError("GUI resource build failed for: '" + filename + "'");
             return null;
         }
         else
             AddChild(w);
         return def;
     }
AddTooltipSub()
void Widget::AddTooltipSub (Sprite@ sprite, string text) inline private
Definition at line 249 of file Widget.as.
References m_tooltipSubtexts, and text.
Referenced by DrinksMenuContent::ReloadList().
     {
         auto newSubText = WidgetSubText();
         newSubText.m_text = text;
         @newSubText.m_sprite = sprite;
         m_tooltipSubtexts.insertLast(newSubText);
     }
Animate()
void Widget::Animate (WidgetAnimation@ anim) inline private
Definition at line 972 of file Widget.as.
References anim, and m_animations.
Referenced by Play(), SetCard(), and FlagWidget::Update().
     {
         @anim.m_widget = this;
         m_animations.insertLast(anim);
         if (anim.m_key == "offset" || anim.m_key == "anchor")
             anim.m_clearOriginSmooth = true;
     }
AnimateSet() [1/6]
void Widget::AnimateSet (string key, vec4 v) inline private
Definition at line 993 of file Widget.as.
Referenced by AnimateSet(), FlagWidget::AnimateSet(), TextWidget::AnimateSet(), SpriteWidget::AnimateSet(), WidgetAnimation::Apply(), WidgetVec2Animation::Apply(), WidgetBoolAnimation::Apply(), and DoDraw().
 { }
AnimateSet() [2/6]
void Widget::AnimateSet (string key, vec2 v) inline private
Definition at line 995 of file Widget.as.
References m_anchor, m_host, and m_offset.
     {
         if (key == "offset")
             m_offset = v;
         else if (key == "anchor")
             m_anchor = v;
         m_host.DoLayout();
     }
AnimateSet() [3/6]
void Widget::AnimateSet (string key, float f) inline private
Definition at line 1005 of file Widget.as.
References m_height, m_host, and m_width.
     {
         if (key == "width")
             m_width = int(f);
         else if (key == "height")
             m_height = int(f);
         m_host.DoLayout();
     }
AnimateSet() [4/6]
void Widget::AnimateSet (string key, bool b) inline private
Definition at line 1015 of file Widget.as.
References m_visible.
     {
         if (key == "visible")
             m_visible = b;
     }
AnimateSet() [5/6]
void Widget::AnimateSet (string key, Sprite@ s) inline private
Definition at line 1021 of file Widget.as.
     {
     }
AnimateSet() [6/6]
void Widget::AnimateSet (string key, string str) inline private
Definition at line 1025 of file Widget.as.
References m_host.
     {
         if (key == "func")
             m_host.OnFunc(this, str);
     }
CalculateOrigin()
void Widget::CalculateOrigin (vec2 origin, vec2 parentSz) inline private
Definition at line 300 of file Widget.as.
References m_anchor, m_height, m_offset, m_origin, m_originPrev, m_originPrevSet, m_pixelPerfect, m_width, and UseSmoothOrigin().
Referenced by DoLayout(), and Menu::BackdropLayer::Draw().
     {
         origin.x += (m_anchor.x * (parentSz.x - m_width)) + m_offset.x;
         origin.y += (m_anchor.y * (parentSz.y - m_height)) + m_offset.y;
         if (m_pixelPerfect)
         {
             origin.x = int(origin.x);
             origin.y = int(origin.y);
         }
         if (UseSmoothOrigin())
         {
             if (m_originPrevSet && !m_invalidated)
                 m_originPrev = m_origin;
             else
             {
                 m_originPrev = origin;
                 m_originPrevSet = true;
             }
         }
         m_origin = origin;
     }
CancelAnimations()
void Widget::CancelAnimations () inline private
Definition at line 988 of file Widget.as.
References m_animations.
Referenced by FinishAnimations().
     {
         m_animations.removeRange(0, m_animations.length());
     }
ClearChildren()
void Widget::ClearChildren () inline private
Definition at line 952 of file Widget.as.
References m_children.
Referenced by ScrollableWidget::ClearChildren(), HUD::ClearTopNumberIcons(), CharacterCustomizationBase::ColorsChanged(), HUD::InitializeKeys(), GuildHallBeastiaryTab::OnShow(), StatuesShopMenuContent::RefreshBuyList(), GuildHallAccomplishmentsTab::RefreshList(), StatuesShopMenuContent::RefreshPlacementList(), DrinksMenuContent::ReloadList(), ReloadList(), FountainShopMenuContent::ReloadList(), ChapelShopMenuContent::ReloadList(), SkillsShopMenuContent::ReloadList(), TownhallMenuContent::ReloadList(), ReloadSplits(), ScoreDialog::Set(), ShopMenu::Show(), PlayerMenuStatsTab::UpdateNow(), and Menu::LobbyPlayersMenu::UpdatePlayerList().
     {
         for (uint i = 0; i < m_children.length(); i++)
         {
             m_children[i].Unfocus();
             @m_children[i].m_parent = null;
         }
         m_children.removeRange(0, m_children.length());
     }
ClearTooltipSubs()
void Widget::ClearTooltipSubs () inline private
Definition at line 244 of file Widget.as.
References m_tooltipSubtexts.
     {
         m_tooltipSubtexts.removeRange(0, m_tooltipSubtexts.length());
     }
Clone()
Widget Widget::Clone () inline private
Definition at line 141 of file Widget.as.
References CloneInto(), and Widget().
Referenced by NotificationManager::Add(), GuildHallAccomplishmentsTab::AddBoss(), AddButton(), TownhallMenuContent::AddButton(), GuildHallBeastiaryTab::AddCategory(), GuildHallStatsTab::AddCharacterToList(), GameChatWidget::AddChat(), GuildHallStatsTab::AddClassesClassToList(), GuildHallStatsTab::AddClassesToList(), AddDrink(), GuildHallStatsTab::AddGuildToList(), AddHeader(), GuildHallAccomplishmentsTab::AddHeader(), AddItem(), AddItemNothing(), GameOver::AddSentence(), GuildHallStatsTab::AddSeparatorToList(), GuildHallStatsTab::AddStatisticsToList(), Notification::AddSubtext(), CharacterCustomizationBase::ColorsChanged(), Menu::EditSlotMenu::Initialize(), Menu::JoinInput(), Menu::TestMenu::OnFunc(), GuildHallAccomplishmentsTab::RefreshList(), Menu::SlotsMenu::RefreshSlots(), DrinksMenuContent::ReloadList(), GeneralStoreMenuContent::ReloadList(), FountainShopMenuContent::ReloadList(), Menu::CharacterSelectionMenu::ReloadList(), ReloadList(), ChapelShopMenuContent::ReloadList(), SkillsShopMenuContent::ReloadList(), TownhallMenuContent::ReloadList(), ReloadSplits(), ScoreDialog::Set(), HUD::SetTopNumberIcon(), HUD::ShowBuffIcon(), CharacterCustomizationBase::ShowSelection(), HUDCoop::Update(), and Menu::LobbyPlayersMenu::UpdatePlayerList().
     {
         Widget@ w = Widget();
         CloneInto(w);
         return w;
     }
CloneInto()
void Widget::CloneInto (Widget@ w) inline private
Definition at line 148 of file Widget.as.
References AddChild(), m_children, m_host, and m_parent.
Referenced by FilteredListWidget::Clone(), MenuLobbyPlayerWidget::Clone(), ColorButtonWidget::Clone(), ClipWidget::Clone(), GroupRectWidget::Clone(), UpgradeShopButtonWidget::Clone(), ScalableSpriteIconButtonWidget::Clone(), MenuControlInputWidget::Clone(), ScrollableRectWidget::Clone(), DetailsWidget::Clone(), InventoryItemWidget::Clone(), TopNumberIconWidget::Clone(), TextWidget::Clone(), SpriteButtonWidget::Clone(), FavorButtonWidget::Clone(), ButtonWidget::Clone(), SpriteWidget::Clone(), SpriteBarWidget::Clone(), GroupWidget::Clone(), MenuServerListItem::Clone(), CheckBoxWidget::Clone(), ShopButtonWidget::Clone(), ScalableSpriteButtonWidget::Clone(), Clone(), CoopPlayerWidget::Clone(), and Clone().
     {
         w = this;
         @w.m_parent = null;
         @w.m_host = null;
         @w.m_children = array<Widget@>();
         for (uint i = 0; i < m_children.length(); i++)
             w.AddChild(m_children[i].Clone());
     }
ClosestInArray()
Widget Widget::ClosestInArray (array< Widget@> arr, WidgetDirection dir) inline private
Definition at line 708 of file Widget.as.
References Down, Left, m_height, m_origin, m_width, Right, and Up.
Referenced by FocusTowards().
     {
         Widget@ candidate = null;
         for (uint i = 0; i < arr.length(); i++)
         {
             auto w = arr[i];
             bool closer = false;
             if (candidate is null)
                 closer = true;
             else
             {
                 switch (dir)
                 {
                     case WidgetDirection::Up: closer = w.m_origin.y + w.m_height > candidate.m_origin.y + candidate.m_height; break;
                     case WidgetDirection::Down: closer = w.m_origin.y < candidate.m_origin.y; break;
                     case WidgetDirection::Left: closer = w.m_origin.x + w.m_width > candidate.m_origin.x + candidate.m_width; break;
                     case WidgetDirection::Right: closer = w.m_origin.x < candidate.m_origin.x; break;
                 }
             }
             if (closer)
                 @candidate = w;
         }
         return candidate;
     }
ContainsFocusable()
bool Widget::ContainsFocusable () inline private
Definition at line 571 of file Widget.as.
References m_canFocus, and m_children.
     {
         if (m_canFocus)
             return true;
         for (uint i = 0; i < m_children.length(); i++)
         {
             if (m_children[i].ContainsFocusable())
                 return true;
         }
         return false;
     }
DebugDraw()
void Widget::DebugDraw (SpriteBatch & sb) inline private
Definition at line 533 of file Widget.as.
References Rect::bottom, g_gameMode, GetRectangle(), Rect::left, m_children, m_height, m_hovering, m_origin, AGameMode::m_widgetInputFocus, AGameMode::m_widgetUnderCursor, m_width, Rect::right, and Rect::top.
Referenced by ScrollableWidget::DebugDraw(), and Draw().
     {
         vec4 color = vec4(0, 0, 0, 0.5);
         if (g_gameMode.m_widgetUnderCursor is this)
         {
             color.r = 1;
             color.a = 1;
         }
         if (g_gameMode.m_widgetInputFocus is this)
         {
             color.g = 1;
             color.a = 1;
         }
         if (m_hovering)
         {
             color.b = 1;
             color.a = 1;
         }
         sb.PauseClipping();
         Rect@ rect = GetRectangle();
         sb.DrawLine(vec2(rect.left, rect.top), vec2(rect.right, rect.top), 1, color);
         sb.DrawLine(vec2(rect.left, rect.top), vec2(rect.left, rect.bottom), 1, color);
         sb.DrawLine(vec2(rect.right, rect.top), vec2(rect.right, rect.bottom), 1, color);
         sb.DrawLine(vec2(rect.left, rect.bottom), vec2(rect.right, rect.bottom), 1, color);
         for (uint i = 0; i < m_children.length(); i++)
         {
             auto c = m_children[i];
             vec4 col = color;
             col.w = 0.25;
             sb.DrawLine(m_origin, m_origin + (c.m_anchor * (vec2(m_width, m_height) - vec2(c.m_width, c.m_height)) + c.m_offset), 1, col);
         }
         sb.ResumeClipping();
     }
DoDraw()
void Widget::DoDraw (SpriteBatch & sb, vec2 pos) inline private
Definition at line 970 of file Widget.as.
Referenced by DoDraw(), TopNumberIconWidget::DoDraw(), and Draw().
 {}
DoLayout()
void Widget::DoLayout (vec2 origin, vec2 parentSz) inline private
Definition at line 324 of file Widget.as.
References CalculateOrigin(), Hbox, HboxWrapped, m_childOffset, m_children, m_flow, m_flowFlip, m_flowFlipOrder, m_height, m_heightScalar, m_origin, m_padding, m_spacing, m_spacingLine, m_visible, m_width, m_widthScalar, None, Vbox, and VboxWrapped.
Referenced by ScrollableWidget::DoLayout(), GroupWidget::DoLayout(), GroupRectWidget::DoLayout(), TransformWidget::DoLayout(), ScalableSpriteButtonWidget::DoLayout(), ScrollbarWidget::DoLayout(), and Notification::PreDraw().
     {
         if (!m_visible)
             return;
         if (m_widthScalar >= 0)
             m_width = int(m_widthScalar * parentSz.x);
         if (m_heightScalar >= 0)
             m_height = int(m_heightScalar * parentSz.y);
         CalculateOrigin(origin, parentSz);
         origin = m_origin;
         vec2 childOffset = m_padding + m_childOffset;
         float ox = origin.x;
         float oy = origin.y;
         Widget@ lastWidget = null;
         int numChildren = m_children.length();
         int forStart = 0;
         int forDir = 1;
         if (m_flow != WidgetFlow::None && (m_flowFlip && !m_flowFlipOrder))
         {
             forStart = numChildren - 1;
             forDir = -1;
         }
         for (int i = forStart; i >= 0 && i < numChildren; i += forDir)
         {
             auto child = m_children[i];
             vec2 newOrigin = childOffset + origin;
             if (lastWidget !is null && m_flow != WidgetFlow::None && child.m_flowAffected)
             {
                 switch (m_flow)
                 {
                     case WidgetFlow::Vbox:
                         if (m_flowFlip)
                             newOrigin.y = lastWidget.m_origin.y - child.m_height - m_spacing;
                         else
                             newOrigin.y = lastWidget.m_origin.y + lastWidget.m_height + m_spacing;
                         break;
                     case WidgetFlow::VboxWrapped:
                         if (m_flowFlip)
                             newOrigin.y = lastWidget.m_origin.y - child.m_width - m_spacing;
                         else
                             newOrigin.y = lastWidget.m_origin.y + lastWidget.m_height + m_spacing;
                         newOrigin.x = lastWidget.m_origin.x;
                         if (newOrigin.y < 0 || newOrigin.y - origin.y + child.m_height > m_height - m_padding.y)
{
                             newOrigin.y = childOffset.y + origin.y;
                             if (m_flowFlip)
                                 newOrigin.y += m_height - child.m_height - m_padding.y;
                             newOrigin.x += lastWidget.m_width + m_spacingLine;
                         }
                         break;
                     case WidgetFlow::Hbox:
                         if (m_flowFlip)
                             newOrigin.x = lastWidget.m_origin.x - child.m_width - m_spacing;
                         else
                             newOrigin.x = lastWidget.m_origin.x + lastWidget.m_width + m_spacing;
                         break;
                     case WidgetFlow::HboxWrapped:
                         if (m_flowFlip)
                             newOrigin.x = lastWidget.m_origin.x - child.m_width - m_spacing;
                         else
                             newOrigin.x = lastWidget.m_origin.x + lastWidget.m_width + m_spacing;
                         newOrigin.y = lastWidget.m_origin.y;
                         if (newOrigin.x < 0 || newOrigin.x - origin.x + child.m_width > m_width - m_padding.x)
{
                             newOrigin.x = childOffset.x + origin.x;
                             if (m_flowFlip)
                                 newOrigin.x += m_width - child.m_width - m_padding.x;
                             newOrigin.y += lastWidget.m_height + m_spacingLine;
                         }
                         break;
                 }
             }
             else if (m_flowFlip)
             {
                 switch (m_flow)
                 {
                     case WidgetFlow::Vbox:
                     case WidgetFlow::VboxWrapped:
                         newOrigin.y += m_height - child.m_height;
                         break;
                     case WidgetFlow::Hbox:
                     case WidgetFlow::HboxWrapped:
                         newOrigin.x += m_width - child.m_width;
                         break;
                 }
             }
             vec2 mySz = vec2(m_width, m_height);
             child.m_originOriginal = newOrigin - childOffset;
             //child.CalculateOrigin(newOrigin, mySz);
             if (child.m_visible)
                 child.DoLayout(newOrigin, mySz);
             if (child.m_visible && (child.m_flowAffected || m_flow == WidgetFlow::None))
                 @lastWidget = child;
         }
         m_invalidated = false;
     }
Draw()
void Widget::Draw (SpriteBatch & sb, bool debugDraw = false) inline private
Definition at line 486 of file Widget.as.
References anim, DebugDraw(), DoDraw(), DrawChildren(), g_debugWidgets, GetOrigin(), m_animations, m_host, and m_visible.
Referenced by ClipWidget::Draw().
     {
         for (uint i = 0; i < m_animations.length(); i++)
         {
             auto anim = m_animations[i];
             anim.PreRender(m_host.m_idt);
             if (anim.IsDone())
                 m_animations.removeAt(i--);
         }
         if (!m_visible || m_invalidated)
             return;
         DoDraw(sb, GetOrigin());
         if (g_debugWidgets)
             debugDraw = true;
         DrawChildren(sb, debugDraw);
         if (debugDraw)
             DebugDraw(sb);
     }
DrawBorder()
void Widget::DrawBorder (SpriteBatch & sb, vec2 pos, vec2 size, int borderWidth = 1, vec4 borderColor = vec4(1, 1, 1, 1), BorderType borderType = BorderType::Inner) inline private
Definition at line 439 of file Widget.as.
References Inner, and Middle.
Referenced by ScrollableRectWidget::DoDraw(), and DoDraw().
     {
         if (borderWidth == 0 || borderColor.w <= 0)
             return;
         vec4 rect;
         if (borderType == BorderType::Inner)
         {
             rect = vec4(pos.x, pos.y, size.x, borderWidth); sb.DrawSprite(null, rect, rect, borderColor);
             rect = vec4(pos.x, pos.y + borderWidth, borderWidth, size.y - borderWidth * 2); sb.DrawSprite(null, rect, rect, borderColor);
             rect = vec4(pos.x, pos.y + size.y - borderWidth, size.x, borderWidth); sb.DrawSprite(null, rect, rect, borderColor);
             rect = vec4(pos.x + size.x - borderWidth, pos.y + borderWidth, borderWidth, size.y - borderWidth * 2); sb.DrawSprite(null, rect, rect, borderColor);
         }
         else if (borderType == BorderType::Outer)
         {
             rect = vec4(pos.x - borderWidth, pos.y - borderWidth, size.x + borderWidth * 2, borderWidth); sb.DrawSprite(null, rect, rect, borderColor);
             rect = vec4(pos.x - borderWidth, pos.y, borderWidth, size.y); sb.DrawSprite(null, rect, rect, borderColor);
             rect = vec4(pos.x - borderWidth, pos.y + size.y, size.x + borderWidth * 2, borderWidth); sb.DrawSprite(null, rect, rect, borderColor);
             rect = vec4(pos.x + size.x, pos.y, borderWidth, size.y); sb.DrawSprite(null, rect, rect, borderColor);
         }
         else if (borderType == BorderType::Middle)
         {
             rect = vec4(pos.x - borderWidth / 2, pos.y - borderWidth / 2, size.x + borderWidth, borderWidth); sb.DrawSprite(null, rect, rect, borderColor);
             rect = vec4(pos.x - borderWidth / 2, pos.y + borderWidth / 2, borderWidth, size.y - borderWidth); sb.DrawSprite(null, rect, rect, borderColor);
             rect = vec4(pos.x - borderWidth / 2, pos.y + size.y - borderWidth / 2, size.x + borderWidth, borderWidth); sb.DrawSprite(null, rect, rect, borderColor);
             rect = vec4(pos.x + size.x - borderWidth / 2, pos.y + borderWidth / 2, borderWidth, size.y - borderWidth); sb.DrawSprite(null, rect, rect, borderColor);
         }
     }
DrawChildren()
void Widget::DrawChildren (SpriteBatch & sb, bool debugDraw = false) inline private
Definition at line 510 of file Widget.as.
References m_children, m_flow, m_flowFlip, m_height, m_width, None, and ShouldDrawChild().
Referenced by Draw(), and ClipWidget::DrawChildren().
     {
         uint numChildren = m_children.length();
         int forStart = 0;
         int forDir = 1;
         if (m_flow != WidgetFlow::None && m_flowFlip)
         {
             forStart = numChildren - 1;
             forDir = -1;
         }
         for (int i = forStart; i >= 0 && i < int(numChildren); i += forDir)
         {
             auto child = m_children[i];
             vec2 mySz = vec2(m_width, m_height);
             if (ShouldDrawChild(child))
                 child.Draw(sb, debugDraw);
         }
     }
FinishAnimations()
void Widget::FinishAnimations () inline private
Definition at line 981 of file Widget.as.
References CancelAnimations(), and m_animations.
     {
         for (uint i = 0; i < m_animations.length; i++)
             m_animations[i].Finish();
         CancelAnimations();
     }
FocusTowards()
bool Widget::FocusTowards (WidgetDirection dir) inline private
Definition at line 734 of file Widget.as.
References Rect::bottom, ClosestInArray(), Down, ScrollableWidget::FocusTowards(), FocusTowards(), GetCenter(), GetRectangle(), IntersectWidgets(), Rect::left, Left, ScrollableWidget::m_autoScroll, ScrollableWidget::m_autoScrollHeight, m_canFocus, m_focusDown, m_focusLeft, m_focusRight, m_focusUp, m_height, m_host, m_origin, m_parent, m_width, Rect::right, Right, SetHovering(), Rect::top, Up, and Vbox.
Referenced by ScrollableWidget::FocusTowards(), FocusTowards(), and BaseGameMode::UpdateWidgets().
     {
         // maybe we have hard-defined the focus widgets so check that first before anything
         string hardFocus = "";
         switch (dir)
         {
             case WidgetDirection::Up: hardFocus = m_focusUp; break;
             case WidgetDirection::Down: hardFocus = m_focusDown; break;
             case WidgetDirection::Left: hardFocus = m_focusLeft; break;
             case WidgetDirection::Right: hardFocus = m_focusRight; break;
         }
         if (hardFocus != "")
         {
             Widget@ hardFocusWidget = m_host.m_widget.GetWidgetById(hardFocus);
             if (hardFocusWidget !is null)
             {
                 hardFocusWidget.SetHovering(true, hardFocusWidget.GetCenter(), true);
                 return true;
             }
         }
         // if there's no parent we can't figure out what's around us
         if (m_parent is null)
             return false;
         // special case: if we're trying to go up/down, and our parent is a combination of vbox and autoscroll, it's probably a list, so we just follow along the list
         ScrollableWidget@ wScrollableParent = cast<ScrollableWidget>(m_parent);
         if (wScrollableParent !is null && (dir == WidgetDirection::Up || dir == WidgetDirection::Down) && wScrollableParent.m_flow == WidgetFlow::Vbox && wScrollableParent.m_autoScroll)
         {
             int index = wScrollableParent.m_children.findByRef(this);
             if (index == -1 || (dir == WidgetDirection::Up && index == 0) || (dir == WidgetDirection::Down && index == int(wScrollableParent.m_children.length()) - 1))
                 return wScrollableParent.FocusTowards(dir);
             Widget@ w = null;
             int add = (dir == WidgetDirection::Up ? -1 : 1);
             for (uint i = index + add; i >= 0 && i < wScrollableParent.m_children.length(); i += add)
             {
                 @w = wScrollableParent.m_children[i];
                 if (w.m_canFocus)
                     break;
                 @w = null;
             }
             if (w !is null)
             {
                 w.SetHovering(true, w.GetCenter(), true);
                 return true;
             }
         }
         // get the parent rectangle
         Rect@ parentRect = m_parent.GetRectangle();
         // get the rectangle that we want to test first
         Rect rect;
         switch (dir)
         {
             case WidgetDirection::Up:
                 rect.left = m_origin.x;
                 rect.right = m_origin.x + m_width;
                 rect.top = parentRect.top;
                 rect.bottom = m_origin.y;
                 break;
             case WidgetDirection::Down:
                 rect.left = m_origin.x;
                 rect.right = m_origin.x + m_width;
                 rect.top = m_origin.y + m_height;
                 rect.bottom = parentRect.bottom;
                 if (wScrollableParent !is null && wScrollableParent.m_autoScroll)
                     rect.bottom = parentRect.top + wScrollableParent.m_autoScrollHeight;
                 break;
             case WidgetDirection::Left:
                 rect.left = parentRect.left;
                 rect.right = m_origin.x;
                 rect.top = m_origin.y;
                 rect.bottom = m_origin.y + m_height;
                 break;
             case WidgetDirection::Right:
                 rect.left = m_origin.x + m_width;
                 rect.right = parentRect.right;
                 rect.top = m_origin.y;
                 rect.bottom = m_origin.y + m_height;
                 break;
         }
         { // test if we have any widgets in the immediate area
             auto widgets = m_parent.IntersectWidgets(rect, true, this);
             Widget@ closest = ClosestInArray(widgets, dir);
             if (closest !is null)
             {
                 closest.SetHovering(true, closest.GetCenter(), true);
                 return true;
             }
         }
         // if we get here, the first test did not give any results, so we expand the search area
         WidgetDirection dirSwap = dir;
         switch (dir)
         {
             case WidgetDirection::Up:
             case WidgetDirection::Down:
                 rect.left = parentRect.left;
                 rect.right = parentRect.right;
                 dirSwap = WidgetDirection::Right;
                 break;
             case WidgetDirection::Left:
             case WidgetDirection::Right:
                 rect.top = parentRect.top;
                 rect.bottom = parentRect.bottom;
                 dirSwap = WidgetDirection::Down;
                 break;
         }
         { // test if we have any widgets in the expanded area
             auto widgets = m_parent.IntersectWidgets(rect, true, this);
             Widget@ closest = ClosestInArray(widgets, dirSwap);
             if (closest !is null)
             {
                 closest.SetHovering(true, closest.GetCenter(), true);
                 return true;
             }
         }
         // pass 2 didn't find anything either, so try from the parent instead
         return m_parent.FocusTowards(dir);
     }
GetAbsolutePosition()
vec2 Widget::GetAbsolutePosition () inline private
Definition at line 269 of file Widget.as.
References m_offset, and m_parent.
     {
         vec2 ret = m_offset;
         Widget@ parent = m_parent;
         while (parent !is null)
         {
             ret += parent.m_offset;
             @parent = parent.m_parent;
         }
         return ret;
     }
GetCenter()
vec2 Widget::GetCenter () inline private
Definition at line 675 of file Widget.as.
References m_height, m_origin, and m_width.
Referenced by BaseGameMode::FocusTopRoot(), and FocusTowards().
     {
         return vec2(m_origin.x + m_width / 2, m_origin.y + m_height / 2);
     }
GetOrigin()
vec2 Widget::GetOrigin () inline private
Definition at line 468 of file Widget.as.
References lerp(), m_host, m_origin, m_originPrev, and UseSmoothOrigin().
Referenced by ClipWidget::Draw(), Draw(), ClipWidget::DrawChildren(), and ScrollableWidget::ShouldDrawChild().
     {
         vec2 origin = m_origin;
         if (UseSmoothOrigin())
         {
             if (m_originPrev.x != m_origin.x)
                 origin.x = lerp(m_originPrev.x, m_origin.x, m_host.m_idt / 33.0f);
             if (m_originPrev.y != m_origin.y)
                 origin.y = lerp(m_originPrev.y, m_origin.y, m_host.m_idt / 33.0f);
         }
         return origin;
     }
GetRectangle()
Rect Widget::GetRectangle (int inset = 0) inline private
Definition at line 667 of file Widget.as.
References m_height, m_origin, and m_width.
Referenced by DebugDraw(), WidgetInspector::Draw(), FocusTowards(), IntersectWidgets(), ScrollTo(), Menu::GraphicsMenu::Update(), and PlayerMenuMapTab::Update().
     {
         return Rect(
             m_origin.x + inset, m_origin.y + inset,
             m_origin.x + m_width - inset, m_origin.y + m_height - inset
         );
     }
GetRelativeOffset()
vec2 Widget::GetRelativeOffset () inline private
Definition at line 281 of file Widget.as.
References m_origin, and m_parent.
Referenced by LootBox::Play().
     {
         if (m_parent is null)
             return m_origin;
         else
             return m_origin - m_parent.m_origin;
     }
GetWidgetById()
Widget Widget::GetWidgetById (string id) inline private
Definition at line 1031 of file Widget.as.
References GetWidgetByIdImpl(), and m_id.
Referenced by GuildHallBeastiaryTab::AddCategory(), DetailsWidget::AddedToParent(), Menu::ControlMapMenu::AddNewControlAxis(), Notification::AddSubtext(), PlayerMenuCharacterTab::AddTextWidget(), ScrollbarWidget::DoLayout(), GameChatWidget::Initialize(), Notification::Notification(), PlayerMenuCharacterTab::OnCreated(), PlayerMenuMapTab::OnCreated(), Menu::ControlMapMenu::OnFunc(), MultiplePlayersTab::OnShow(), DrinksMenuContent::OnShow(), GuildHallAccomplishmentsTab::OnShow(), StatuesShopMenuContent::OnShow(), GuildHallStatsTab::OnShow(), DungeonStoreMenuContent::OnShow(), GeneralStoreMenuContent::OnShow(), UpgradeShopMenuContent::OnShow(), ChapelShopMenuContent::OnShow(), FountainShopMenuContent::OnShow(), SkillsShopMenuContent::OnShow(), TownhallMenuContent::OnShow(), GuildHallBeastiaryTab::OnShow(), Menu::SlotsMenu::RefreshSlots(), DrinksMenuContent::ReloadList(), GeneralStoreMenuContent::ReloadList(), SkillsShopMenuContent::ReloadList(), TownhallMenuContent::ReloadList(), ScoreDialog::Set(), CoopPlayerWidget::SetPeer(), PlayerMenuCharacterTab::SetTextWidget(), PlayerMenuCharacterTab::SetTooltipWidget(), CharacterCustomizationBase::ShowSelection(), Update(), PlayerMenuCharacterTab::UpdateFromRecord(), ActorBuff::UpdateHudIcon(), PlayerMenuStatsTab::UpdateNow(), MultiplePlayersTab::UpdateNow(), PlayerMenuCharacterTab::UpdateNow(), and Menu::LobbyPlayersMenu::UpdatePlayer().
     {
         //print("GetWidgetById(" + id + ")");
         if (m_id == id)
             return this;
         return GetWidgetByIdImpl(HashString(id));
     }
GetWidgetByIdImpl()
Widget Widget::GetWidgetByIdImpl (uint idHash) inline private
Definition at line 1041 of file Widget.as.
References idHash, m_children, and m_idHash.
Referenced by GetWidgetById().
     {
         for (uint i = 0; i < m_children.length(); i++)
         {
             if (m_children[i].m_idHash == idHash)
                 return m_children[i];
             Widget@ w = m_children[i].GetWidgetByIdImpl(idHash);
             if (w !is null)
                 return w;
         }
         return null;
     }
GetWidgetsById()
array<Widget@> Widget::GetWidgetsById (string id) inline private
Definition at line 1057 of file Widget.as.
References m_children, and m_id.
     {
         array<Widget@> ret;
         if (m_id == id)
             ret.insertLast(this);
         for (uint i = 0; i < m_children.length(); i++)
         {
             array<Widget@> ws = m_children[i].GetWidgetsById(id);
             for (uint j = 0; j < ws.length(); j++)
                 ret.insertLast(ws[j]);
         }
         return ret;
     }
IntersectWidgets()
array<Widget@> Widget::IntersectWidgets (Rect & rect, bool onlyCanFocus = false, Widget@ ignore = null, bool onlyInsideParent = false) inline private
Definition at line 680 of file Widget.as.
References Rect::Contains(), GetRectangle(), Rect::IntersectsWith(), IntersectWidgets(), m_canFocus, m_children, and m_visible.
Referenced by FocusTowards(), and IntersectWidgets().
     {
         Rect@ rectUs = GetRectangle();
         array<Widget@> ret;
         for (uint i = 0; i < m_children.length(); i++)
         {
             Widget@ w = m_children[i];
             auto more = w.IntersectWidgets(rect, onlyCanFocus, w, onlyInsideParent);
             for (uint j = 0; j < more.length(); j++)
                 ret.insertLast(more[j]);
             if (onlyCanFocus && !w.m_canFocus)
                 continue;
             if (!w.m_visible)
                 continue;
             if (ignore is w)
                 continue;
             Rect@ wr = w.GetRectangle(1);
             if (wr.IntersectsWith(rect) and (!onlyInsideParent or rectUs.Contains(wr)))
                 ret.insertLast(w);
         }
         return ret;
     }
Load() [1/2]
void Widget::Load () inline private
Definition at line 158 of file Widget.as.
References m_anchor, m_id, m_idHash, m_offset, and m_visible.
Referenced by ColorCheckBoxWidget::Load(), WaypointMarkersWidget::Load(), InventoryWidget::Load(), GameChatWidget::Load(), GroupWidget::Load(), FilteredListWidget::Load(), DotbarWidget::Load(), ScrollableWidget::Load(), ClipWidget::Load(), UpgradeShopButtonWidget::Load(), FlagWidget::Load(), CoopPlayerWidget::Load(), ScalableSpriteIconButtonWidget::Load(), MenuControlInputWidget::Load(), Load(), GroupRectWidget::Load(), TextInputWidget::Load(), ShopButtonWidget::Load(), ColorButtonWidget::Load(), DetailsWidget::Load(), InventoryItemWidget::Load(), BuffWidget::Load(), TopNumberIconWidget::Load(), TextWidget::Load(), SpriteButtonWidget::Load(), ButtonWidget::Load(), FavorButtonWidget::Load(), SpriteWidget::Load(), SpriteBarWidget::Load(), SkillWidget::Load(), ScrollbarWidget::Load(), ScalableSpriteButtonWidget::Load(), CheckBoxWidget::Load(), and CheckBoxGroupWidget::Load().
     {
         m_id = "";
         m_idHash = 0;
         m_anchor = vec2();
         m_offset = vec2();
         m_visible = true;
     }
Load() [2/2]
void Widget::Load (WidgetLoadingContext & ctx) inline private
Definition at line 187 of file Widget.as.
References g_smoothOriginWidgets, Hbox, HboxWrapped, m_anchor, m_canDoubleClick, m_canFocus, m_filter, m_flow, m_flowAffected, m_flowFlip, m_flowFlipOrder, m_focusDown, m_focusLeft, m_focusRight, m_focusUp, m_host, m_offset, m_padding, m_pixelPerfect, m_priorityFocus, m_smoothOrigin, m_smoothOriginForced, m_spacing, m_spacingLine, m_tooltipEnabled, m_tooltipSubtexts, m_tooltipText, m_tooltipTitle, m_visible, SetID(), Vbox, and VboxWrapped.
     {
         GUIDef@ def = ctx.GetGUIDef();;
         @m_host = cast<IWidgetHoster>(ctx.GetWidgetHost());
         SetID(ctx.GetString("id", false));
         m_priorityFocus = ctx.GetBoolean("priorityfocus", false, false);
         m_canDoubleClick = ctx.GetBoolean("candoubleclick", false, false);
         m_filter = ctx.GetString("filter", false).toLower();
         m_anchor = ctx.GetVector2("anchor", false);
         m_offset = ctx.GetVector2("offset", false, m_offset);
         m_padding = ctx.GetVector2("padding", false);
         m_visible = ctx.GetBoolean("visible", false, true);
         m_canFocus = ctx.GetBoolean("canfocus", false, false);
         m_focusUp = ctx.GetString("focusup", false);
         m_focusDown = ctx.GetString("focusdown", false);
         m_focusLeft = ctx.GetString("focusleft", false);
         m_focusRight = ctx.GetString("focusright", false);
         m_smoothOriginForced = ctx.HasAttribute("smooth");
         m_smoothOrigin = ctx.GetBoolean("smooth", false, g_smoothOriginWidgets);
         m_pixelPerfect = ctx.GetBoolean("pixel-perfect", false, true);
         string flow = ctx.GetString("flow", false, "none");
              if (flow == "vbox") m_flow = WidgetFlow::Vbox;
         else if (flow == "vboxwrapped") m_flow = WidgetFlow::VboxWrapped;
         else if (flow == "hbox") m_flow = WidgetFlow::Hbox;
         else if (flow == "hboxwrapped") m_flow = WidgetFlow::HboxWrapped;
         m_spacing = ctx.GetInteger("spacing", false, 0);
         m_spacingLine = ctx.GetInteger("spacing-line", false, m_spacing);
         m_flowFlip = ctx.GetBoolean("flow-flip", false);
         m_flowFlipOrder = ctx.GetBoolean("flow-flip-order", false);
         m_flowAffected = ctx.GetBoolean("flow-affected", false, true);
         m_tooltipEnabled = ctx.GetBoolean("tooltip-enabled", false, true);
         m_tooltipTitle = Resources::GetString(ctx.GetString("tooltip-title", false));
         string subText = Resources::GetString(ctx.GetString("tooltip-sub", false));
         auto subSprite = def.GetSprite(ctx.GetString("tooltip-sub-sprite", false));
         if (subText != "")
         {
             auto newSubText = WidgetSubText();
             newSubText.m_text = subText;
             @newSubText.m_sprite = subSprite;
             m_tooltipSubtexts.insertLast(newSubText);
         }
         m_tooltipText = Resources::GetString(ctx.GetString("tooltip", false));
     }
LoadWidthHeight()
void Widget::LoadWidthHeight (WidgetLoadingContext & ctx, bool required = true) inline private
Definition at line 167 of file Widget.as.
References m_height, m_heightScalar, m_width, and m_widthScalar.
Referenced by FilteredListWidget::Load(), DotbarWidget::Load(), ClipWidget::Load(), Load(), TextInputWidget::Load(), InventoryItemWidget::Load(), TextWidget::Load(), SpriteWidget::Load(), and ScrollbarWidget::Load().
     {
         string w = ctx.GetString("width", required, "");
         if (w != "")
         {
             if (w.substr(w.length() - 1, 1) == "%")
                 m_widthScalar = int(parseInt(w.substr(0, w.length() - 1))) / 100.0;
             else
                 m_width = parseInt(w);
         }
         string h = ctx.GetString("height", required, "");
         if (h != "")
         {
             if (h.substr(h.length() - 1, 1) == "%")
                 m_heightScalar = int(parseInt(h.substr(0, h.length() - 1))) / 100.0;
             else
                 m_height = parseInt(h);
         }
     }
MoveToParentInPlace()
void Widget::MoveToParentInPlace (Widget@ newParent, int insertAt = -1) inline private
Definition at line 922 of file Widget.as.
References AddChild(), m_origin, RemoveFromParent(), and SetOriginFromParent().
     {
         RemoveFromParent();
         newParent.AddChild(this, insertAt);
         SetOriginFromParent(m_origin);
     }
OnClick()
bool Widget::OnClick (vec2 mousePos) inline private
Definition at line 1107 of file Widget.as.
Referenced by MenuControlInputWidget::OnClick(), and BaseGameMode::UpdateWidgets().
 { return false; }
OnDoubleClick()
bool Widget::OnDoubleClick (vec2 mousePos) inline private
Definition at line 1108 of file Widget.as.
Referenced by BaseGameMode::UpdateWidgets().
 { return false; }
OnMouseDown()
bool Widget::OnMouseDown (vec2 mousePos) inline private
Definition at line 1105 of file Widget.as.
Referenced by BaseGameMode::UpdateWidgets().
 { return false; }
OnMouseEnter()
void Widget::OnMouseEnter (vec2 mousePos, bool forced) inline private
Definition at line 1110 of file Widget.as.
References m_tooltipText, m_tooltipTitle, and ShowTooltip().
Referenced by SpriteButtonWidget::OnMouseEnter(), ButtonWidget::OnMouseEnter(), CheckBoxWidget::OnMouseEnter(), and ScalableSpriteButtonWidget::OnMouseEnter().
     {
         if (m_tooltipText != "" || m_tooltipTitle != "")
             ShowTooltip();
     }
OnMouseLeave()
void Widget::OnMouseLeave (vec2 mousePos) inline private
Definition at line 1116 of file Widget.as.
References g_gameMode, BaseGameMode::m_tooltip, m_tooltipText, and m_tooltipTitle.
Referenced by ButtonWidget::OnMouseLeave(), SpriteButtonWidget::OnMouseLeave(), ScalableSpriteButtonWidget::OnMouseLeave(), and Unfocus().
     {
         if (m_tooltipText != "" || m_tooltipTitle != "")
         {
             BaseGameMode@ gm = cast<BaseGameMode>(g_gameMode);
             if (gm !is null)
                 gm.m_tooltip.Hide();
         }
     }
OnMouseUp()
bool Widget::OnMouseUp (vec2 mousePos) inline private
Definition at line 1106 of file Widget.as.
Referenced by BaseGameMode::UpdateWidgets().
 { return false; }
opCmp()
int Widget::opCmp (const Widget@ w) inline private
Definition at line 130 of file Widget.as.
     {
         return 0;
     }
PassesFilter()
bool Widget::PassesFilter (string str) inline private
Definition at line 1074 of file Widget.as.
References m_filter.
     {
         if (m_filter == "")
             return true;
         return (m_filter.findFirst(str) != -1);
     }
Remove()
void Widget::Remove () inline private
Definition at line 962 of file Widget.as.
References m_children, and m_parent.
     {
         if (m_parent is null)
             return;
         m_parent.m_children.removeAt(m_parent.m_children.findByRef(this));
         @m_parent = null;
     }
RemoveFromParent()
void Widget::RemoveFromParent () inline private
Definition at line 902 of file Widget.as.
References m_children, m_parent, and Unfocus().
Referenced by MoveToParentInPlace(), GeneralStoreMenuContent::ReloadList(), NotificationManager::Update(), and BuffWidget::Update().
     {
         if (m_parent is null)
             return;
         int index = m_parent.m_children.findByRef(this);
         if (index == -1)
             return;
         Unfocus();
         m_parent.m_children.removeAt(index);
         @m_parent = null;
     }
ScrollTo()
void Widget::ScrollTo () inline private
Definition at line 583 of file Widget.as.
References GetRectangle(), ScrollableWidget::m_autoScroll, ScrollableWidget::m_autoScrollValue, m_height, m_originOriginal, m_parent, ScrollTo(), and ScrollableWidget::TestAutoscrollLimit().
Referenced by ScrollTo().
     {
         if (m_parent is null)
             return;
         ScrollableWidget@ wScrollable = cast<ScrollableWidget>(m_parent);
         if (wScrollable is null || !wScrollable.m_autoScroll)
         {
             if (m_parent.m_parent !is null)
                 m_parent.ScrollTo();
             return;
         }
         // might already fit inside, no need to scroll then
         if (wScrollable.GetRectangle().Contains(GetRectangle(1)))
             return;
         int top = int(m_originOriginal.y - wScrollable.m_origin.y);
         int padding = (top - wScrollable.m_autoScrollValue > 0) ? (wScrollable.m_height - m_height) : 0;
         wScrollable.m_autoScrollValue = top - padding;
         wScrollable.TestAutoscrollLimit();
     }
SetHost()
void Widget::SetHost (IWidgetHoster@ host) inline private
Definition at line 945 of file Widget.as.
References m_children, and m_host.
Referenced by AddChild().
     {
         @m_host = host;
         for (uint i = 0; i < m_children.length(); i++)
             m_children[i].SetHost(host);
     }
SetHovering()
void Widget::SetHovering (bool hovering, vec2 mousePos, bool force = false) inline private
Definition at line 606 of file Widget.as.
References force, g_gameMode, m_canFocus, m_host, m_hovering, and AGameMode::m_widgetUnderCursor.
Referenced by BaseGameMode::FocusTopRoot(), FocusTowards(), ScalableSpriteButtonWidget::SetHovering(), and UpdateInput().
     {
         if (m_hovering != hovering || force)
         {
             m_hovering = hovering;
             if (hovering)
             {
                 if (m_canFocus)
                     @g_gameMode.m_widgetUnderCursor = this;
                 /*
                 if (force)
                     ScrollTo();
                 */
                 m_host.m_queueMouseEnter.insertLast(WidgetMouseEvt(this, mousePos, force));
             }
             else
                 m_host.m_queueMouseLeave.insertLast(WidgetMouseEvt(this, mousePos));
         }
     }
SetID()
void Widget::SetID (string id) inline private
Definition at line 135 of file Widget.as.
References id, m_id, and m_idHash.
Referenced by GuildHallAccomplishmentsTab::AddBoss(), TownhallMenuContent::AddButton(), GuildHallStatsTab::AddClassesClassToList(), GuildHallStatsTab::AddClassesToList(), AddDrink(), AddHeader(), GuildHallAccomplishmentsTab::AddHeader(), AddItem(), AddItemNothing(), GuildHallStatsTab::AddSeparatorToList(), Notification::AddSubtext(), CharacterCustomizationBase::ColorsChanged(), Load(), Menu::TestMenu::OnFunc(), GuildHallAccomplishmentsTab::RefreshList(), DrinksMenuContent::ReloadList(), GeneralStoreMenuContent::ReloadList(), FountainShopMenuContent::ReloadList(), ReloadList(), ChapelShopMenuContent::ReloadList(), SkillsShopMenuContent::ReloadList(), TownhallMenuContent::ReloadList(), ScoreDialog::Set(), CharacterCustomizationBase::ShowSelection(), HUDCoop::Update(), CheckBoxGroupWidget::Update(), and Menu::LobbyPlayersMenu::UpdatePlayerList().
     {
         m_id = id;
         m_idHash = HashString(id);
     }
SetOriginFromParent()
void Widget::SetOriginFromParent (vec2 origin) inline private
Definition at line 914 of file Widget.as.
References m_offset, m_origin, and m_parent.
Referenced by MoveToParentInPlace().
     {
         if (m_parent is null)
             m_offset = origin;
         else
             m_offset = origin - m_parent.m_origin;
     }
ShouldDrawChild()
bool Widget::ShouldDrawChild (Widget@ child) inline private
Definition at line 481 of file Widget.as.
Referenced by DrawChildren().
     {
         return true;
     }
ShowTooltip()
void Widget::ShowTooltip () inline private
Definition at line 1081 of file Widget.as.
References g_gameMode, BaseGameMode::m_tooltip, m_tooltipAlign, m_tooltipEnabled, m_tooltipSubtexts, m_tooltipText, and m_tooltipTitle.
Referenced by OnMouseEnter(), SetColor(), and ScalableSpriteButtonWidget::ShowTooltip().
     {
         BaseGameMode@ gm = cast<BaseGameMode>(g_gameMode);
         if (gm !is null)
         {
             gm.m_tooltip.Reset();
             gm.m_tooltip.SetTitle(m_tooltipTitle);
             for (uint i = 0; i < m_tooltipSubtexts.length(); i++)
             {
                 auto subText = m_tooltipSubtexts[i];
                 gm.m_tooltip.AddSub(subText.m_sprite, subText.m_text);
             }
             if (m_tooltipAlign > -1)
                 gm.m_tooltip.SetText(m_tooltipText, TextAlignment(m_tooltipAlign));
             else
                 gm.m_tooltip.SetText(m_tooltipText);
             gm.m_tooltip.SetEnabled(m_tooltipEnabled);
         }
     }
Unfocus()
bool Widget::Unfocus () inline private
Definition at line 929 of file Widget.as.
References g_gameMode, m_children, AGameMode::m_widgetUnderCursor, and OnMouseLeave().
Referenced by RemoveFromParent().
     {
         if (g_gameMode.m_widgetUnderCursor is this)
         {
             @g_gameMode.m_widgetUnderCursor = null;
             OnMouseLeave(vec2());
             return true;
         }
         for (uint i = 0; i < m_children.length(); i++)
         {
             if (m_children[i].Unfocus())
                 return true;
         }
         return false;
     }
Update()
void Widget::Update (int dt) inline private
Definition at line 257 of file Widget.as.
References m_animations, m_children, and m_doubleClickTime.
Referenced by WaypointMarkersWidget::Update(), GameChatWidget::Update(), BuffWidget::Update(), FlagWidget::Update(), CoopPlayerWidget::Update(), Update(), SpriteBarWidget::Update(), ScrollbarWidget::Update(), and CheckBoxGroupWidget::Update().
     {
         for (uint i = 0; i < m_children.length(); i++)
             m_children[i].Update(dt);
         for (uint i = 0; i < m_animations.length(); i++)
             m_animations[i].Update(dt);
         if (m_doubleClickTime > 0)
             m_doubleClickTime -= dt;
     }
UpdateInput() [1/2]
bool Widget::UpdateInput (GameInput & input) inline private
Definition at line 627 of file Widget.as.
Referenced by ScrollableWidget::UpdateInput(), UpdateInput(), and BaseGameMode::UpdateWidgets().
     {
         return false;
     }
UpdateInput() [2/2]
bool Widget::UpdateInput (vec2 origin, vec2 parentSz, vec3 mousePos) inline private
Definition at line 632 of file Widget.as.
References m_children, m_height, m_host, m_hovering, m_lastMousePos, m_origin, m_parent, m_visible, m_width, SetHovering(), UpdateInput(), and xy().
     {
         vec2 d = m_origin - origin;
         origin += d;
         mousePos.x -= d.x;
         mousePos.y -= d.y;
         m_lastMousePos = xy(mousePos);
         if (!m_visible)
         {
             SetHovering(false, xy(mousePos));
             return false;
         }
         if (m_host.m_mouseUsed)
         {
             bool mouseHoverSelf = mousePos.x >= 0 && mousePos.y >= 0 && mousePos.x < m_width && mousePos.y < m_height;
             if (m_parent !is null)// && m_parent.m_overflow == WidgetOverflow::Clip)
                 SetHovering(mouseHoverSelf && m_parent.m_hovering, xy(mousePos), m_host.m_forcingFocus);
             else
                 SetHovering(mouseHoverSelf, xy(mousePos), m_host.m_forcingFocus);
         }
         bool hoveringChildren = false;
         for (uint i = 0; i < m_children.length(); i++)
         {
             if(m_children[i].UpdateInput(origin, vec2(m_width, m_height), mousePos))
                 hoveringChildren = true;
         }
         return m_hovering;
     }
UseSmoothOrigin()
bool Widget::UseSmoothOrigin () inline private
Definition at line 289 of file Widget.as.
References m_parent, m_smoothOrigin, m_smoothOriginForced, and UseSmoothOrigin().
Referenced by CalculateOrigin(), GetOrigin(), and UseSmoothOrigin().
     {
         if (m_smoothOriginForced)
             return m_smoothOrigin;
         if (m_parent !is null)
             return m_parent.UseSmoothOrigin();
         else
             return m_smoothOrigin;
     }
Member Data Documentation
_m_visible
private bool Widget::_m_visible private
Definition at line 108 of file Widget.as.
m_anchor
vec2 Widget::m_anchor private
Definition at line 53 of file Widget.as.
Referenced by AnimateSet(), CalculateOrigin(), WidgetInspector::Draw(), and Load().
m_animations
array<WidgetAnimation@> Widget::m_animations private
Definition at line 96 of file Widget.as.
Referenced by Animate(), CancelAnimations(), Draw(), FinishAnimations(), and Update().
m_canDoubleClick
bool Widget::m_canDoubleClick private
Definition at line 51 of file Widget.as.
Referenced by Load(), and BaseGameMode::UpdateWidgets().
m_canFocus
bool Widget::m_canFocus private
Definition at line 78 of file Widget.as.
Referenced by ContainsFocusable(), WidgetInspector::Draw(), BaseGameMode::FirstFocusable(), FocusTowards(), IntersectWidgets(), MenuControlInputWidget::Load(), TextInputWidget::Load(), DetailsWidget::Load(), InventoryItemWidget::Load(), ButtonWidget::Load(), ScrollbarWidget::Load(), CheckBoxWidget::Load(), Load(), SetHovering(), and BaseGameMode::UpdateWidgets().
m_canFocusInput
bool Widget::m_canFocusInput private
Definition at line 79 of file Widget.as.
Referenced by TextInputWidget::Load(), and BaseGameMode::UpdateWidgets().
m_childOffset
vec2 Widget::m_childOffset private
Definition at line 100 of file Widget.as.
Referenced by ScrollableWidget::DoLayout(), and DoLayout().
m_children
array<Widget@> Widget::m_children private
Definition at line 94 of file Widget.as.
Referenced by HUD::AddBossBar(), AddChild(), Menu::SubOptionsMenu::AnyCvarChangedInternal(), Menu::SubOptionsMenu::CancelCvarWidgetsInternal(), ClearChildren(), UpgradeShopMenuContent::ClearList(), CloneInto(), Colorize(), ContainsFocusable(), DebugDraw(), ScrollableWidget::DoLayout(), GroupWidget::DoLayout(), GroupRectWidget::DoLayout(), DoLayout(), WidgetInspector::Draw(), ClipWidget::DrawChildren(), DrawChildren(), CheckBoxGroupWidget::FindCheckables(), BaseGameMode::FirstFocusable(), ScrollableWidget::FocusTowards(), HUD::GetBossBar(), HUDCoop::GetPlayer(), GetWidgetByIdImpl(), GetWidgetsById(), Menu::IntroMenu::Initialize(), Initialize(), IntersectWidgets(), Menu::TestMenu::OnFunc(), Menu::EditSlotMenu::OnFunc(), Menu::ControlMapMenu::OnFunc(), Menu::FrontMenu::OnFunc(), FountainShopMenuContent::ReloadList(), Remove(), RemoveFromParent(), Menu::SubOptionsMenu::ResetCvarWidgetsInternal(), Menu::SubOptionsMenu::SaveCvarWidgetsInternal(), FilteredListWidget::SetFilter(), SetHost(), FilteredListWidget::ShowAll(), HUD::ShowBuffIcon(), Menu::SmoothWidgets(), Unfocus(), WidgetInspector::Update(), FlagWidget::Update(), Menu::FrontMenu::Update(), HUD::Update(), Update(), UpdateInput(), FountainShopMenuContent::UpdateInterface(), and Widget().
m_cursor
Platform::CursorInfo Widget::m_cursor private
Definition at line 123 of file Widget.as.
Referenced by TextInputWidget::Load(), and BaseGameMode::SetCursorUI().
m_defaultFocus
bool Widget::m_defaultFocus private
Definition at line 76 of file Widget.as.
m_doubleClickPos
vec2 Widget::m_doubleClickPos private
Definition at line 50 of file Widget.as.
Referenced by BaseGameMode::UpdateWidgets().
m_doubleClickTime
int Widget::m_doubleClickTime private
Definition at line 49 of file Widget.as.
Referenced by Update(), and BaseGameMode::UpdateWidgets().
m_filter
string Widget::m_filter private
Definition at line 60 of file Widget.as.
Referenced by Load(), PassesFilter(), and TextWidget::SetText().
m_flow
WidgetFlow Widget::m_flow private
Definition at line 68 of file Widget.as.
Referenced by ScrollableWidget::AddChild(), DoLayout(), DrawChildren(), FilteredListWidget::Load(), DetailsWidget::Load(), and Load().
m_flowAffected
bool Widget::m_flowAffected private
Definition at line 69 of file Widget.as.
Referenced by Load().
m_flowFlip
bool Widget::m_flowFlip private
Definition at line 72 of file Widget.as.
Referenced by DoLayout(), DrawChildren(), and Load().
m_flowFlipOrder
bool Widget::m_flowFlipOrder private
Definition at line 73 of file Widget.as.
Referenced by DoLayout(), and Load().
m_focusDown
string Widget::m_focusDown private
Definition at line 81 of file Widget.as.
Referenced by FocusTowards(), and Load().
m_focusLeft
string Widget::m_focusLeft private
Definition at line 82 of file Widget.as.
Referenced by FocusTowards(), and Load().
m_focusRight
string Widget::m_focusRight private
Definition at line 83 of file Widget.as.
Referenced by FocusTowards(), and Load().
m_focusUp
string Widget::m_focusUp private
Definition at line 80 of file Widget.as.
Referenced by FocusTowards(), and Load().
m_height
int Widget::m_height private
Definition at line 63 of file Widget.as.
Referenced by ScrollableWidget::AddChild(), Notification::AddSubtext(), AnimateSet(), CalculateOrigin(), Clone(), ClosestInArray(), DebugDraw(), ColorCheckBoxWidget::DoDraw(), DotbarWidget::DoDraw(), ScalableSpriteIconButtonWidget::DoDraw(), ScrollableRectWidget::DoDraw(), DoDraw(), TopNumberIconWidget::DoDraw(), InventoryItemWidget::DoDraw(), ScrollableWidget::DoDraw(), ShopButtonWidget::DoDraw(), SpriteWidget::DoDraw(), DetailsWidget::DoDraw(), ScalableSpriteButtonWidget::DoDraw(), CheckBoxWidget::DoDraw(), TextInputWidget::DoDraw(), ScrollableWidget::DoLayout(), GroupWidget::DoLayout(), GroupRectWidget::DoLayout(), TransformWidget::DoLayout(), ShopMenu::DoLayout(), ScrollbarWidget::DoLayout(), CheckBoxGroupWidget::DoLayout(), DoLayout(), Menu::BackdropLayer::Draw(), ClipWidget::Draw(), WidgetInspector::Draw(), PlayerMenuMapTab::Draw(), ClipWidget::DrawChildren(), DrawChildren(), FocusTowards(), GetCenter(), PlayerMenuMapTab::GetMapHeight(), GetRectangle(), GroupWidget::Load(), FlagWidget::Load(), GroupRectWidget::Load(), TopNumberIconWidget::Load(), SpriteBarWidget::Load(), CheckBoxWidget::Load(), Load(), LoadWidthHeight(), LootBox::Play(), GuildHallAccomplishmentsTab::RefreshList(), ReloadList(), TownhallMenuContent::ReloadList(), ScrollableWidget::ScrollDown(), ScrollTo(), SpriteWidget::SetSprite(), TextWidget::SetText(), CheckBoxWidget::SetText(), SetText(), ScrollableWidget::ShouldDrawChild(), SkillWidget::SkillWidget(), ScrollableWidget::SpaceToScroll(), SpriteBarWidget::SpriteBarWidget(), SpriteWidget::SpriteWidget(), ScrollableWidget::TestAutoscrollLimit(), TextWidget::TextWidget(), Update(), UpdateInput(), and DetailsWidget::UpdateSize().
m_heightScalar
float Widget::m_heightScalar = -1 private
Definition at line 66 of file Widget.as.
Referenced by DoLayout(), and LoadWidthHeight().
m_host
IWidgetHoster Widget::m_host private
Definition at line 44 of file Widget.as.
Referenced by AddChild(), AddResource(), AnimateSet(), CloneInto(), MenuTab::DoLayout(), ScrollbarWidget::DoLayout(), Draw(), FocusTowards(), GetOrigin(), Load(), ButtonWidget::OnClick(), CheckBoxWidget::OnClick(), CheckBoxGroupWidget::OnDoubleClick(), ButtonWidget::OnMouseEnter(), ScalableSpriteButtonWidget::OnMouseLeave(), SetHost(), SetHovering(), DetailsWidget::ToggleDetails(), CoopPlayerWidget::Update(), TextInputWidget::UpdateInput(), UpdateInput(), and BaseGameMode::UpdateWidgets().
m_hovering
bool Widget::m_hovering private
Definition at line 75 of file Widget.as.
Referenced by ButtonWidget(), DebugDraw(), DetailsWidget::DoDraw(), CheckBoxWidget::DoDraw(), SpriteButtonWidget::GetCurrentSprite(), ScalableSpriteButtonWidget::GetSprites(), ScalableSpriteButtonWidget::GetTextColor(), BaseGameMode::SetCursorUI(), SetHovering(), ScrollableWidget::UpdateInput(), UpdateInput(), and BaseGameMode::UpdateWidgets().
m_id
string Widget::m_id private
Definition at line 57 of file Widget.as.
Referenced by GetWidgetById(), WidgetInspector::GetWidgetDebugName(), GetWidgetsById(), Load(), and SetID().
m_idHash
uint Widget::m_idHash private
Definition at line 58 of file Widget.as.
Referenced by GetWidgetByIdImpl(), Load(), and SetID().
m_lastMousePos
vec2 Widget::m_lastMousePos private
Definition at line 98 of file Widget.as.
Referenced by UpdateInput().
m_offset
vec2 Widget::m_offset private
Definition at line 54 of file Widget.as.
Referenced by AnimateSet(), CalculateOrigin(), GroupRectWidget::DoLayout(), ScrollbarWidget::DoLayout(), Menu::BackdropLayer::Draw(), GetAbsolutePosition(), Load(), Notification::PreDraw(), GuildHallAccomplishmentsTab::RefreshList(), SetOriginFromParent(), Notification::Update(), and HUD::Update().
m_origin
vec2 Widget::m_origin private
Definition at line 88 of file Widget.as.
Referenced by CalculateOrigin(), ClosestInArray(), ScrollableWidget::DebugDraw(), DebugDraw(), TextInputWidget::DoDraw(), ScrollableWidget::DoLayout(), GroupWidget::DoLayout(), GroupRectWidget::DoLayout(), ScrollbarWidget::DoLayout(), DoLayout(), Menu::BackdropLayer::Draw(), WidgetInspector::Draw(), TransformWidget::Draw(), PlayerMenuMapTab::Draw(), FocusTowards(), GetCenter(), GetOrigin(), GetRectangle(), GetRelativeOffset(), MoveToParentInPlace(), ScrollbarWidget::OnMouseDown(), SetOriginFromParent(), ScrollbarWidget::Update(), UpdateInput(), and BaseGameMode::UpdateWidgets().
m_originOriginal
vec2 Widget::m_originOriginal private
Definition at line 92 of file Widget.as.
Referenced by ScrollTo().
m_originPrev
vec2 Widget::m_originPrev private
Definition at line 89 of file Widget.as.
Referenced by CalculateOrigin(), ScrollbarWidget::DoLayout(), and GetOrigin().
m_originPrevSet
bool Widget::m_originPrevSet private
Definition at line 90 of file Widget.as.
Referenced by CalculateOrigin(), and WidgetAnimation::PreRender().
m_padding
vec2 Widget::m_padding private
Definition at line 55 of file Widget.as.
Referenced by GroupRectWidget::DoLayout(), ScalableSpriteButtonWidget::DoLayout(), DoLayout(), DetailsWidget::Load(), Load(), ScrollableWidget::ScrollDown(), ScrollableWidget::SpaceToScroll(), and ScrollableWidget::TestAutoscrollLimit().
m_parent
Widget Widget::m_parent private
Definition at line 43 of file Widget.as.
Referenced by AddChild(), CloneInto(), ScrollbarWidget::DoLayout(), Menu::BackdropLayer::Draw(), WidgetInspector::Draw(), FocusTowards(), GetAbsolutePosition(), GetRelativeOffset(), Menu::FrontMenu::Initialize(), Notification::PreDraw(), Remove(), RemoveFromParent(), ScrollTo(), SetOriginFromParent(), TextWidget::SetText(), UpdateInput(), BaseGameMode::UpdateWidgets(), and UseSmoothOrigin().
m_pixelPerfect
bool Widget::m_pixelPerfect private
Definition at line 47 of file Widget.as.
Referenced by CalculateOrigin(), Load(), and Menu::SmoothWidgets().
m_priorityFocus
bool Widget::m_priorityFocus private
Definition at line 46 of file Widget.as.
Referenced by Load(), and BaseGameMode::UpdateWidgets().
m_smoothOrigin
bool Widget::m_smoothOrigin private
Definition at line 85 of file Widget.as.
Referenced by Load(), and UseSmoothOrigin().
m_smoothOriginForced
bool Widget::m_smoothOriginForced private
Definition at line 86 of file Widget.as.
Referenced by Load(), and UseSmoothOrigin().
m_spacing
int Widget::m_spacing private
Definition at line 70 of file Widget.as.
Referenced by DoLayout(), Menu::FrontMenu::Initialize(), and Load().
m_spacingLine
int Widget::m_spacingLine private
Definition at line 71 of file Widget.as.
Referenced by DoLayout(), and Load().
m_tooltipAlign
int Widget::m_tooltipAlign private
Definition at line 106 of file Widget.as.
Referenced by ShowTooltip().
m_tooltipEnabled
bool Widget::m_tooltipEnabled private
Definition at line 102 of file Widget.as.
Referenced by Load(), SetColor(), ScalableSpriteButtonWidget::ShowTooltip(), and ShowTooltip().
m_tooltipSubtexts
array<WidgetSubText@> Widget::m_tooltipSubtexts private
Definition at line 104 of file Widget.as.
Referenced by AddTooltipSub(), ClearTooltipSubs(), WidgetInspector::Draw(), Load(), and ShowTooltip().
m_tooltipText
string Widget::m_tooltipText private
Definition at line 105 of file Widget.as.
Referenced by WidgetInspector::Draw(), Load(), OnMouseEnter(), OnMouseLeave(), Menu::SlotsMenu::RefreshSlots(), DrinksMenuContent::ReloadList(), UpgradeShopButtonWidget::Set(), InventoryItemWidget::Set(), and ShowTooltip().
m_tooltipTitle
string Widget::m_tooltipTitle private
Definition at line 103 of file Widget.as.
Referenced by WidgetInspector::Draw(), Load(), OnMouseEnter(), OnMouseLeave(), DrinksMenuContent::ReloadList(), UpgradeShopButtonWidget::Set(), InventoryItemWidget::Set(), and ShowTooltip().
m_visible
bool Widget::m_visible private
Initial value:
{
        get { return _m_visible; }
        set {
            if (value != _m_visible)
            {
                m_invalidated = true;
                m_originPrevSet = false;
            }
            _m_visible = value;
        }
    }
    bool m_invalidated = true
Definition at line 110 of file Widget.as.
Referenced by NotificationManager::Add(), GuildHallBeastiaryTab::AddCategory(), ScrollableWidget::AddChild(), DetailsWidget::AddedToParent(), GuildHallStatsTab::AddStatisticsToList(), MenuTabSystem::AddTab(), AnimateSet(), Menu::SplitscreenPlayer::DisplayName(), DetailsWidget::DoDraw(), ScrollableWidget::DoLayout(), DoLayout(), Draw(), HideStatus(), Menu::FrontMenu::Initialize(), Menu::LobbyPlayersMenu::Initialize(), IntersectWidgets(), MenuTab::IsVisible(), FlagWidget::Load(), Load(), Menu::EditSlotMenu::OnFunc(), PlayerMenuMapTab::OnShow(), GuildHallAccomplishmentsTab::RefreshList(), Menu::SlotsMenu::RefreshSlots(), DrinksMenuContent::ReloadList(), GeneralStoreMenuContent::ReloadList(), DungeonStoreMenuContent::ReloadList(), UpgradeShopMenuContent::ReloadList(), SkillsShopMenuContent::ReloadList(), TownhallMenuContent::ReloadList(), UpgradeShopButtonWidget::Set(), ScoreDialog::Set(), SetGoldStatus(), SetLimitButtons(), MenuTab::SetVisible(), FilteredListWidget::ShowAll(), DetailsWidget::ToggleDetails(), Menu::InGameNotifier::Update(), FlagWidget::Update(), CoopPlayerWidget::Update(), Notification::Update(), Update(), HUD::Update(), PlayerMenuCharacterTab::UpdateFromRecord(), UpdateInput(), PlayerMenuCharacterTab::UpdateNow(), DetailsWidget::UpdateSize(), and BaseGameMode::UpdateWidgets().
m_width
int Widget::m_width private
Definition at line 62 of file Widget.as.
Referenced by AnimateSet(), CalculateOrigin(), Clone(), ClosestInArray(), DebugDraw(), ColorCheckBoxWidget::DoDraw(), DotbarWidget::DoDraw(), ScalableSpriteIconButtonWidget::DoDraw(), ScrollableRectWidget::DoDraw(), DoDraw(), TopNumberIconWidget::DoDraw(), InventoryItemWidget::DoDraw(), ScrollableWidget::DoDraw(), ShopButtonWidget::DoDraw(), SpriteWidget::DoDraw(), DetailsWidget::DoDraw(), ScalableSpriteButtonWidget::DoDraw(), CheckBoxWidget::DoDraw(), TextInputWidget::DoDraw(), GroupWidget::DoLayout(), GroupRectWidget::DoLayout(), TransformWidget::DoLayout(), ScalableSpriteButtonWidget::DoLayout(), ScrollbarWidget::DoLayout(), CheckBoxGroupWidget::DoLayout(), DoLayout(), ClipWidget::Draw(), Menu::BackdropLayer::Draw(), WidgetInspector::Draw(), PlayerMenuMapTab::Draw(), ClipWidget::DrawChildren(), DrawChildren(), FocusTowards(), GetCenter(), PlayerMenuMapTab::GetMapWidth(), GetRectangle(), TextInputWidget::GetTextOffset(), Menu::FrontMenu::Initialize(), GroupWidget::Load(), FlagWidget::Load(), GroupRectWidget::Load(), TopNumberIconWidget::Load(), TextWidget::Load(), SpriteBarWidget::Load(), ScrollbarWidget::Load(), CheckBoxWidget::Load(), Load(), LoadWidthHeight(), Notification::Notification(), LootBox::Play(), SpriteWidget::SetSprite(), TextWidget::SetText(), CheckBoxWidget::SetText(), ShopMenu::Show(), SkillWidget::SkillWidget(), SpriteBarWidget::SpriteBarWidget(), SpriteWidget::SpriteWidget(), TextWidget::TextWidget(), HUD::Update(), TextInputWidget::UpdateCursorPos(), UpdateInput(), DetailsWidget::UpdateSize(), and TextInputWidget::UpdateText().
m_widthScalar
float Widget::m_widthScalar = -1 private
Definition at line 65 of file Widget.as.
Referenced by DoLayout(), LoadWidthHeight(), and TextWidget::SetText().
The documentation for this class was generated from the following file:
scripts/GUI/Widget.as