HoHDocs: SpeechBubbleManager Class Reference
SpeechBubbleManager Class Reference
Private Member Functions
SpeechBubbleManager ()
void HideAll ()
void Hide (SpeechBubble@ bubble)
SpeechBubble Show ()
void Update (int dt)
void Draw (SpriteBatch &sb, int idt)
Private Attributes
array< SpeechBubble@> m_list
Detailed Description
Definition at line 1 of file SpeechBubbleManager.as.
Constructor & Destructor Documentation
SpeechBubbleManager()
SpeechBubbleManager::SpeechBubbleManager () inline private
Definition at line 5 of file SpeechBubbleManager.as.
     {
     }
Member Function Documentation
Draw()
void SpeechBubbleManager::Draw (SpriteBatch & sb, int idt) inline private
Definition at line 38 of file SpeechBubbleManager.as.
References m_list.
Referenced by HUD::Draw().
     {
         for (uint i = 0; i < m_list.length(); i++)
             m_list[i].Draw(sb, idt);
     }
Hide()
void SpeechBubbleManager::Hide (SpeechBubble@ bubble) inline private
Definition at line 14 of file SpeechBubbleManager.as.
References m_list.
     {
         int index = m_list.findByRef(bubble);
         if (index == -1)
         {
             PrintError("Tried hiding speech bubble that is not in list!");
             return;
         }
         m_list.removeAt(index);
     }
HideAll()
void SpeechBubbleManager::HideAll () inline private
Definition at line 9 of file SpeechBubbleManager.as.
References m_list.
Referenced by WorldScript::HideAllSpeechBubbles::ClientExecute().
     {
         m_list.removeRange(0, m_list.length());
     }
Show()
SpeechBubble SpeechBubbleManager::Show () inline private
Definition at line 25 of file SpeechBubbleManager.as.
References m_list.
     {
         auto ret = SpeechBubble();
         m_list.insertLast(ret);
         return ret;
     }
Update()
void SpeechBubbleManager::Update (int dt) inline private
Definition at line 32 of file SpeechBubbleManager.as.
References m_list.
Referenced by HUD::Update().
     {
         for (uint i = 0; i < m_list.length(); i++)
             m_list[i].Update(dt);
     }
Member Data Documentation
m_list
array<SpeechBubble@> SpeechBubbleManager::m_list private
Definition at line 3 of file SpeechBubbleManager.as.
Referenced by Draw(), Hide(), HideAll(), Show(), and Update().
The documentation for this class was generated from the following file:
scripts/GUI/SpeechBubbleManager.as