HoHDocs: InventoryItemWidget Class Reference
InventoryItemWidget Class Reference
Private Member Functions
InventoryItemWidget ()
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void Set (PlayerRecord@ record, ActorItem@ item)
void DoDraw (SpriteBatch &sb, vec2 pos) override
Private Attributes
PlayerRecord m_record
ActorItem m_item
Sprite m_spriteDot
Sprite m_spritePlus
vec4 m_colorItem
vec4 m_colorSet
bool m_hasBonus
bool m_isAttuned
Detailed Description
Definition at line 1 of file InventoryItemWidget.as.
Constructor & Destructor Documentation
InventoryItemWidget()
InventoryItemWidget::InventoryItemWidget () inline private
Definition at line 15 of file InventoryItemWidget.as.
Referenced by Clone().
     {
         super();
     }
Member Function Documentation
Clone()
Widget InventoryItemWidget::Clone () inline override private
Definition at line 20 of file InventoryItemWidget.as.
References Widget::CloneInto(), and InventoryItemWidget().
Referenced by InventoryWidget::AddItem(), and LootBoxItemAnimator::AnimateUp().
     {
         InventoryItemWidget@ w = InventoryItemWidget();
         CloneInto(w);
         return w;
     }
DoDraw()
void InventoryItemWidget::DoDraw (SpriteBatch & sb, vec2 pos) inline override private
Definition at line 66 of file InventoryItemWidget.as.
References Common, g_menuTime, m_colorItem, m_colorSet, m_hasBonus, Widget::m_height, m_isAttuned, m_item, m_spriteDot, m_spritePlus, and Widget::m_width.
     {
         m_item.icon.Draw(sb, pos + vec2(2, 2), g_menuTime);
         int dotX = m_width - m_spriteDot.GetWidth() - 2;
         int dotY = m_height - m_spriteDot.GetHeight() - 2;
         if (m_item.quality != ActorItemQuality::Common)
         {
             vec2 dotPos = pos + vec2(dotX, dotY);
             sb.DrawSprite(dotPos, m_spriteDot, g_menuTime, m_colorItem);
             dotX -= m_spriteDot.GetWidth() - 1;
         }
         if (m_hasBonus)
         {
             vec2 dotPos = pos + vec2(dotX, dotY);
             sb.DrawSprite(dotPos, m_spriteDot, g_menuTime, m_colorSet);
             dotX -= m_spriteDot.GetWidth() - 1;
         }
         if (m_isAttuned)
             sb.DrawSprite(pos + vec2(2, 2), m_spritePlus, g_menuTime);
     }
Load()
void InventoryItemWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 27 of file InventoryItemWidget.as.
References Widget::Load(), Widget::LoadWidthHeight(), Widget::m_canFocus, m_spriteDot, and m_spritePlus.
Referenced by LoadInventoryItemWidget().
     {
         Widget::Load(ctx);
         LoadWidthHeight(ctx);
         auto def = ctx.GetGUIDef();
         @m_spriteDot = def.GetSprite("inventory-item-dot");
         @m_spritePlus = def.GetSprite("inventory-item-plus");
         m_canFocus = true;
     }
Set()
void InventoryItemWidget::Set (PlayerRecord@ record, ActorItem@ item) inline private
Definition at line 40 of file InventoryItemWidget.as.
References GetItemQualityColor(), GetItemQualityColorString(), GetItemSetColorString(), m_colorItem, m_colorSet, m_hasBonus, m_isAttuned, m_item, m_record, Widget::m_tooltipText, Widget::m_tooltipTitle, and SetItemColorString.
     {
         @m_record = record;
         @m_item = item;
         m_tooltipTitle = "\\c" + GetItemQualityColorString(item.quality) + utf8string(Resources::GetString(item.name)).toUpper().plain();
         m_tooltipText = Resources::GetString(item.desc);
         if (item.set !is null)
         {
             m_tooltipText += "\n\n";
             m_tooltipText += GetItemSetColorString(record, item);
             auto ownedSet = record.GetOwnedItemSet(item.set);
             if (ownedSet !is null)
                 m_hasBonus = true;
                 //m_hasBonus = (ownedSet.m_count > 1);
                 //m_hasBonus = ownedSet.IsAnyBonusActive();
         }
         m_colorItem = GetItemQualityColor(item.quality);
         m_colorSet = ParseColorRGBA("#" + SetItemColorString + "FF");
         m_isAttuned = (record.itemForgeAttuned.find(item.idHash) != -1);
     }
Member Data Documentation
m_colorItem
vec4 InventoryItemWidget::m_colorItem private
Definition at line 9 of file InventoryItemWidget.as.
Referenced by DoDraw(), and Set().
m_colorSet
vec4 InventoryItemWidget::m_colorSet private
Definition at line 10 of file InventoryItemWidget.as.
Referenced by DoDraw(), and Set().
m_hasBonus
bool InventoryItemWidget::m_hasBonus private
Definition at line 12 of file InventoryItemWidget.as.
Referenced by DoDraw(), and Set().
m_isAttuned
bool InventoryItemWidget::m_isAttuned private
Definition at line 13 of file InventoryItemWidget.as.
Referenced by DoDraw(), and Set().
m_item
ActorItem InventoryItemWidget::m_item private
Definition at line 4 of file InventoryItemWidget.as.
Referenced by DoDraw(), and Set().
m_record
PlayerRecord InventoryItemWidget::m_record private
Definition at line 3 of file InventoryItemWidget.as.
Referenced by Set().
m_spriteDot
Sprite InventoryItemWidget::m_spriteDot private
Definition at line 6 of file InventoryItemWidget.as.
Referenced by DoDraw(), and Load().
m_spritePlus
Sprite InventoryItemWidget::m_spritePlus private
Definition at line 7 of file InventoryItemWidget.as.
Referenced by DoDraw(), and Load().
The documentation for this class was generated from the following file:
scripts/GUI/Widgets/InventoryItemWidget.as