HoHDocs: SpriteWidget Class Reference
SpriteWidget Class Reference
Private Member Functions
SpriteWidget ()
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void SetSprite (string spriteName, bool resetTime=false)
void SetSprite (Sprite@ sprite, bool resetTime=false)
void SetSprite (ScriptSprite@ sprite, bool resetTime=false)
void SetTexture (Texture2D@ texture)
void DoDraw (SpriteBatch &sb, vec2 pos) override
void AnimateSet (string key, vec4 v) override
void AnimateSet (string key, Sprite@ s) override
Private Attributes
Sprite m_spriteOrig
Sprite m_sprite
string m_spriteSrc
Texture2D m_spriteTexture
ScriptSprite m_ssprite
bool m_colorize
array< vec4 > m_colorizeColors = { vec4(0, 0, 0, 1), vec4(0.125, 0.125, 0.125, 1), vec4(0.25, 0.25, 0.25, 1) }
array< array< vec4 > > m_multiColors
vec4 m_color
GUIDef m_def
int m_timeOffset
bool m_autoSize
Detailed Description
Definition at line 1 of file SpriteWidget.as.
Constructor & Destructor Documentation
SpriteWidget()
SpriteWidget::SpriteWidget () inline private
Definition at line 22 of file SpriteWidget.as.
References Widget::m_height, m_sprite, m_spriteOrig, and Widget::m_width.
Referenced by Clone().
     {
         super();
         @m_spriteOrig = null;
         @m_sprite = null;
         m_width = 0;
         m_height = 0;
     }
Member Function Documentation
AnimateSet() [1/2]
void SpriteWidget::AnimateSet (string key, vec4 v) inline override private
Definition at line 162 of file SpriteWidget.as.
References Widget::AnimateSet(), and m_color.
     {
         if (key == "color")
             m_color = v;
         else
             Widget::AnimateSet(key, v);
     }
AnimateSet() [2/2]
void SpriteWidget::AnimateSet (string key, Sprite@ s) inline override private
Definition at line 170 of file SpriteWidget.as.
References m_timeOffset, and SetSprite().
     {
         if (key == "sprite")
             SetSprite(s);
         else if (key == "spriter")
             SetSprite(s, true);
         else if (key == "sprite0")
         {
             SetSprite(s);
             m_timeOffset = 0;
         }
     }
Clone()
Widget SpriteWidget::Clone () inline override private
Definition at line 32 of file SpriteWidget.as.
References Widget::CloneInto(), and SpriteWidget().
Referenced by ShopMenu::Show().
     {
         SpriteWidget@ w = SpriteWidget();
         CloneInto(w);
         return w;
     }
DoDraw()
void SpriteWidget::DoDraw (SpriteBatch & sb, vec2 pos) inline override private
Definition at line 118 of file SpriteWidget.as.
References g_menuTime, m_color, m_colorize, m_colorizeColors, Widget::m_height, m_multiColors, m_sprite, m_spriteSrc, m_spriteTexture, m_ssprite, m_timeOffset, and Widget::m_width.
     {
         vec4 dst = vec4(pos.x, pos.y, m_width, m_height);
         Texture2D@ texture = null;
         if (m_sprite !is null)
             @texture = m_sprite.GetTexture2D();
         else if (m_ssprite !is null)
             @texture = m_ssprite.m_texture;
         else if (m_spriteTexture !is null)
             @texture = m_spriteTexture;
         else
             return;
         if (texture is null)
         {
             PrintError("There is no texture for sprite widget! (src: \"" + m_spriteSrc + "\")");
             return;
         }
         if (m_colorize)
             sb.EnableColorize(m_colorizeColors[0], m_colorizeColors[1], m_colorizeColors[2]);
         for (uint i = 0; i < m_multiColors.length(); i++)
         {
             array<vec4> colors = m_multiColors[i];
             sb.SetMultiColor(i, colors[0], colors[1], colors[2]);
         }
         if (m_sprite !is null)
         {
             vec4 src = m_sprite.GetFrame(g_menuTime - m_timeOffset);
             sb.DrawSprite(texture, dst, src, m_color);
         }
         else if (m_ssprite !is null)
             m_ssprite.Draw(sb, dst, g_menuTime - m_timeOffset, m_color);
         if (m_multiColors.length() > 0)
             sb.DisableMultiColor();
         if (m_colorize)
             sb.DisableColorize();
     }
Load()
void SpriteWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 39 of file SpriteWidget.as.
References Widget::Load(), Widget::LoadWidthHeight(), m_autoSize, m_color, m_def, m_sprite, m_spriteSrc, m_timeOffset, and SetSprite().
Referenced by LoadSpriteWidget().
     {
         @m_def = ctx.GetGUIDef();
         m_autoSize = ctx.GetBoolean("autosize", false, true);
         if (!m_autoSize)
             LoadWidthHeight(ctx);
         m_spriteSrc = ctx.GetString("src", false);
         if (m_spriteSrc != "")
             SetSprite(m_def.GetSprite(m_spriteSrc));
         if (m_sprite !is null && ctx.GetBoolean("random-start", false))
             m_timeOffset = -randi(m_sprite.GetLength());
         m_color = ctx.GetColorRGBA("color", false, vec4(1, 1, 1, 1));
         Widget::Load(ctx);
     }
SetSprite() [1/3]
void SpriteWidget::SetSprite (string spriteName, bool resetTime = false) inline private
Definition at line 59 of file SpriteWidget.as.
References m_def, and m_spriteSrc.
Referenced by AnimateSet(), CharacterCustomizationBase::FaceChanged(), Load(), Play(), Menu::SplitscreenPlayer::SetSkin(), Menu::SetStartScenario(), HUD::Start(), HUD::Update(), FountainShopMenuContent::UpdateInterface(), and CoopPlayerWidget::UpdatePortrait().
     {
         m_spriteSrc = spriteName;
         SetSprite(m_def.GetSprite(spriteName), resetTime);
     }
SetSprite() [2/3]
void SpriteWidget::SetSprite (Sprite@ sprite, bool resetTime = false) inline private
Definition at line 65 of file SpriteWidget.as.
References g_menuTime, m_autoSize, Widget::m_height, m_sprite, m_spriteOrig, m_ssprite, m_timeOffset, and Widget::m_width.
     {
         if (m_spriteOrig is null)
             @m_spriteOrig = sprite;
         @m_sprite = sprite;
         @m_ssprite = null;
         if (m_autoSize)
         {
             if (m_sprite !is null)
             {
                 m_width = m_sprite.GetWidth();
                 m_height = m_sprite.GetHeight();
             }
             else
             {
                 m_width = 0;
                 m_height = 0;
             }
         }
         if (resetTime)
             m_timeOffset = g_menuTime;
     }
SetSprite() [3/3]
void SpriteWidget::SetSprite (ScriptSprite@ sprite, bool resetTime = false) inline private
Definition at line 90 of file SpriteWidget.as.
References g_menuTime, m_autoSize, Widget::m_height, m_sprite, m_ssprite, m_timeOffset, and Widget::m_width.
     {
         @m_sprite = null;
         @m_ssprite = sprite;
         if (m_autoSize)
         {
             if (m_ssprite !is null)
             {
                 m_width = m_ssprite.GetWidth();
                 m_height = m_ssprite.GetHeight();
             }
             else
             {
                 m_width = 0;
                 m_height = 0;
             }
         }
         if (resetTime)
             m_timeOffset = g_menuTime;
     }
SetTexture()
void SpriteWidget::SetTexture (Texture2D@ texture) inline private
Definition at line 113 of file SpriteWidget.as.
References m_spriteTexture.
     {
         @m_spriteTexture = texture;
     }
Member Data Documentation
m_autoSize
bool SpriteWidget::m_autoSize private
Definition at line 20 of file SpriteWidget.as.
Referenced by Load(), and SetSprite().
m_color
vec4 SpriteWidget::m_color private
Definition at line 14 of file SpriteWidget.as.
Referenced by AnimateSet(), DoDraw(), Load(), CoopPlayerWidget::SetPeer(), and CoopPlayerWidget::Update().
m_colorize
bool SpriteWidget::m_colorize private
Definition at line 9 of file SpriteWidget.as.
Referenced by DoDraw(), and CoopPlayerWidget::Update().
m_colorizeColors
array<vec4> SpriteWidget::m_colorizeColors = { vec4(0, 0, 0, 1), vec4(0.125, 0.125, 0.125, 1), vec4(0.25, 0.25, 0.25, 1) } private
Definition at line 10 of file SpriteWidget.as.
Referenced by DoDraw().
m_def
GUIDef SpriteWidget::m_def private
Definition at line 16 of file SpriteWidget.as.
Referenced by Load(), and SetSprite().
m_multiColors
array<array<vec4> > SpriteWidget::m_multiColors private
Definition at line 12 of file SpriteWidget.as.
Referenced by DoDraw(), CharacterCustomizationBase::FaceChanged(), and CoopPlayerWidget::UpdatePortrait().
m_sprite
Sprite SpriteWidget::m_sprite private
Definition at line 4 of file SpriteWidget.as.
Referenced by DoDraw(), Load(), SetSprite(), and SpriteWidget().
m_spriteOrig
Sprite SpriteWidget::m_spriteOrig private
Definition at line 3 of file SpriteWidget.as.
Referenced by SetSprite(), and SpriteWidget().
m_spriteSrc
string SpriteWidget::m_spriteSrc private
Definition at line 5 of file SpriteWidget.as.
Referenced by DoDraw(), Load(), and SetSprite().
m_spriteTexture
Texture2D SpriteWidget::m_spriteTexture private
Definition at line 6 of file SpriteWidget.as.
Referenced by DoDraw(), and SetTexture().
m_ssprite
ScriptSprite SpriteWidget::m_ssprite private
Definition at line 7 of file SpriteWidget.as.
Referenced by DoDraw(), and SetSprite().
m_timeOffset
int SpriteWidget::m_timeOffset private
Definition at line 18 of file SpriteWidget.as.
Referenced by AnimateSet(), DoDraw(), Load(), and SetSprite().
The documentation for this class was generated from the following file:
scripts/GUI/SpriteWidget.as