HoHDocs: FavorButtonWidget Class Reference
FavorButtonWidget Class Reference
Private Member Functions
FavorButtonWidget ()
int opCmp (const Widget@ w) override
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void Set (Fountain::Effect@ effect, int shopLevel)
vec4 GetTextColor () override
array< Sprite@> GetSprites () override
void DoDraw (SpriteBatch &sb, vec2 pos) override
Private Attributes
Fountain::Effect m_effect
BitmapString m_textPrice
bool m_lockedIn
array< Sprite@> m_spriteLockedIn
Sprite m_spriteFavorGood
Sprite m_spriteFavorBad
Detailed Description
Definition at line 1 of file FavorButtonWidget.as.
Constructor & Destructor Documentation
FavorButtonWidget()
FavorButtonWidget::FavorButtonWidget () inline private
Definition at line 13 of file FavorButtonWidget.as.
Referenced by Clone().
     {
         super();
     }
Member Function Documentation
Clone()
Widget FavorButtonWidget::Clone () inline override private
Definition at line 30 of file FavorButtonWidget.as.
References Widget::CloneInto(), and FavorButtonWidget().
     {
         FavorButtonWidget@ w = FavorButtonWidget();
         CloneInto(w);
         return w;
     }
DoDraw()
void FavorButtonWidget::DoDraw (SpriteBatch & sb, vec2 pos) inline override private
Definition at line 112 of file FavorButtonWidget.as.
References ScalableSpriteButtonWidget::DoDraw().
     {
         ScalableSpriteButtonWidget::DoDraw(sb, pos);
         vec2 pricePos = vec2(
             pos.x + m_width - m_textPrice.GetWidth() - m_textOffset.x,
             pos.y + m_height / 2 - m_textPrice.GetHeight() / 2 + m_textOffset.y - 1
         );
         sb.DrawString(pricePos, m_textPrice);
     }
GetSprites()
array<Sprite@> FavorButtonWidget::GetSprites () inline override private
Definition at line 104 of file FavorButtonWidget.as.
References m_lockedIn, and m_spriteLockedIn.
     {
         if (m_lockedIn)
             return m_spriteLockedIn;
         return ScalableSpriteButtonWidget::GetSprites();
     }
GetTextColor()
vec4 FavorButtonWidget::GetTextColor () inline override private
Definition at line 96 of file FavorButtonWidget.as.
References m_lockedIn.
     {
         if (m_lockedIn)
             return vec4(1, 1, 1, 1);
         return ScalableSpriteButtonWidget::GetTextColor();
     }
Load()
void FavorButtonWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 37 of file FavorButtonWidget.as.
References Widget::Load(), and ScalableSpriteButtonWidget::m_textOffset.
Referenced by LoadFavorButtonWidget().
     {
         m_textOffset = vec2(36, -1);
         ScalableSpriteButtonWidget::Load(ctx);
         GUIDef@ def = ctx.GetGUIDef();
         string spriteSet = ctx.GetString("spriteset");
         m_spriteLockedIn.insertLast(def.GetSprite(spriteSet + "-lockedin-left"));
         m_spriteLockedIn.insertLast(def.GetSprite(spriteSet + "-lockedin-mid"));
         m_spriteLockedIn.insertLast(def.GetSprite(spriteSet + "-lockedin-right"));
         @m_spriteFavorGood = def.GetSprite("icon-favor-good");
         @m_spriteFavorBad = def.GetSprite("icon-favor-bad");
         m_checkable = true;
         @m_font = Resources::GetBitmapFont("gui/fonts/arial11.fnt");
     }
opCmp()
int FavorButtonWidget::opCmp (const Widget@ w) inline override private
Definition at line 18 of file FavorButtonWidget.as.
     {
         auto other = cast<FavorButtonWidget>(w);
         if (m_effect.m_favor > other.m_effect.m_favor)
             return 1;
         else if (m_effect.m_favor < other.m_effect.m_favor)
             return -1;
         return 0;
     }
Set()
void FavorButtonWidget::Set (Fountain::Effect@ effect, int shopLevel) inline private
Definition at line 58 of file FavorButtonWidget.as.
References effect, m_effect, and ScalableSpriteButtonWidget::m_value.
     {
         @m_effect = effect;
         m_value = effect.m_id;
         if (effect.m_favor > 0)
         {
             @m_textPrice = m_font.BuildText("+" + effect.m_favor);
             m_textPrice.SetColor(vec4(0, 1, 0, 1));
         }
         else
         {
             @m_textPrice = m_font.BuildText("" + effect.m_favor);
             m_textPrice.SetColor(vec4(1, 0, 0, 1));
         }
         m_enabled = (Network::IsServer() && Fountain::CurrentEffects.length() == 0 && shopLevel >= effect.m_level);
         m_lockedIn = Fountain::HasEffect(effect.m_idHash);
         string name = Resources::GetString(".fountain.effect." + effect.m_id + ".name");
         string desc = Resources::GetString(".fountain.effect." + effect.m_id + ".description");
         m_tooltipTitle = name;
         m_tooltipText = desc;
         if (shopLevel < effect.m_level)
             m_tooltipText += "\n\n" + Resources::GetString(".fountain.requiredlevel", { { "level", effect.m_level } });
         if (effect.m_favor > 0)
             AddTooltipSub(m_spriteFavorGood, "+" + effect.m_favor);
         else
             AddTooltipSub(m_spriteFavorBad, "" + effect.m_favor);
         SetText(name);
     }
Member Data Documentation
m_effect
Fountain::Effect FavorButtonWidget::m_effect private
Definition at line 3 of file FavorButtonWidget.as.
Referenced by FavorButtonWidget(), and Set().
m_lockedIn
bool FavorButtonWidget::m_lockedIn private
Definition at line 7 of file FavorButtonWidget.as.
Referenced by GetSprites(), and GetTextColor().
m_spriteFavorBad
Sprite FavorButtonWidget::m_spriteFavorBad private
Definition at line 11 of file FavorButtonWidget.as.
m_spriteFavorGood
Sprite FavorButtonWidget::m_spriteFavorGood private
Definition at line 10 of file FavorButtonWidget.as.
m_spriteLockedIn
array<Sprite@> FavorButtonWidget::m_spriteLockedIn private
Definition at line 8 of file FavorButtonWidget.as.
Referenced by GetSprites().
m_textPrice
BitmapString FavorButtonWidget::m_textPrice private
Definition at line 5 of file FavorButtonWidget.as.
Referenced by Set().
The documentation for this class was generated from the following file:
scripts/GUI/Widgets/FavorButtonWidget.as