HoHDocs: UpgradeShopButtonWidget Class Reference
UpgradeShopButtonWidget Class Reference
Private Member Functions
UpgradeShopButtonWidget ()
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void Set (ShopMenuContent@ menuContent, Upgrades::Upgrade@ upgrade)
void Set (ShopMenuContent@ menuContent, Upgrades::Upgrade@ upgrade, Upgrades::UpgradeStep@ step)
void DrawIcon (SpriteBatch &sb, vec2 pos, vec4 color) override
Private Attributes
ScriptSprite m_scriptSpriteIcon
Upgrades::Upgrade m_upgrade
Upgrades::UpgradeStep m_upgradeStep
Detailed Description
Definition at line 1 of file UpgradeShopButtonWidget.as.
Constructor & Destructor Documentation
UpgradeShopButtonWidget()
UpgradeShopButtonWidget::UpgradeShopButtonWidget () inline private
Definition at line 8 of file UpgradeShopButtonWidget.as.
Referenced by Clone().
     {
         super();
     }
Member Function Documentation
Clone()
Widget UpgradeShopButtonWidget::Clone () inline override private
Definition at line 13 of file UpgradeShopButtonWidget.as.
References Widget::CloneInto(), and UpgradeShopButtonWidget().
Referenced by ChapelShopMenuContent::ReloadList().
     {
         UpgradeShopButtonWidget@ w = UpgradeShopButtonWidget();
         CloneInto(w);
         return w;
     }
DrawIcon()
void UpgradeShopButtonWidget::DrawIcon (SpriteBatch & sb, vec2 pos, vec4 color) inline override private
Definition at line 87 of file UpgradeShopButtonWidget.as.
References Upgrades::UpgradeStep::DrawShopIcon(), g_menuTime, m_scriptSpriteIcon, Upgrades::Upgrade::m_sprite, Upgrades::UpgradeStep::m_sprite, ShopButtonWidget::m_spriteIcon, ShopButtonWidget::m_spriteIconFrame, m_upgrade, and m_upgradeStep.
     {
         sb.DrawSprite(pos, m_spriteIconFrame, g_menuTime, color);
         if (m_scriptSpriteIcon !is null)
             m_scriptSpriteIcon.Draw(sb, pos + vec2(1, 1), g_menuTime, color);
         else if (m_upgradeStep.m_sprite !is null)
             m_upgradeStep.m_sprite.Draw(sb, pos + vec2(1, 1), g_menuTime, color);
         else if (m_upgrade.m_sprite !is null)
             m_upgrade.m_sprite.Draw(sb, pos + vec2(1, 1), g_menuTime, color);
         else
         {
             if (m_spriteIcon !is null)
                 sb.DrawSprite(pos + vec2(1, 1), m_spriteIcon, g_menuTime, color);
             vec2 frameSize = vec2(m_spriteIconFrame.GetWidth(), m_spriteIconFrame.GetHeight());
             m_upgradeStep.DrawShopIcon(this, sb, pos + vec2(1, 1), frameSize, color);
         }
     }
Load()
void UpgradeShopButtonWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 20 of file UpgradeShopButtonWidget.as.
References Widget::Load().
Referenced by LoadUpgradeShopButtonWidget().
     {
         ShopButtonWidget::Load(ctx);
     }
Set() [1/2]
void UpgradeShopButtonWidget::Set (ShopMenuContent@ menuContent, Upgrades::Upgrade@ upgrade) inline private
Definition at line 25 of file UpgradeShopButtonWidget.as.
References GetLocalPlayerRecord(), Upgrades::Upgrade::GetNextStep(), and Widget::m_visible.
Referenced by UpgradeShopMenuContent::AddItem().
     {
         auto step = upgrade.GetNextStep(GetLocalPlayerRecord());
         if (step is null)
         {
             m_visible = false;
             return;
         }
         Set(menuContent, upgrade, step);
     }
Set() [2/2]
void UpgradeShopButtonWidget::Set (ShopMenuContent@ menuContent, Upgrades::Upgrade@ upgrade, Upgrades::UpgradeStep@ step) inline private
Definition at line 37 of file UpgradeShopButtonWidget.as.
References g_flags, Upgrades::UpgradeStep::GetButtonText(), GetLocalPlayerRecord(), Upgrades::UpgradeStep::GetTooltipDescription(), Upgrades::UpgradeStep::GetTooltipTitle(), Upgrades::UpgradeStep::IsRestricted(), Upgrades::UpgradeStep::m_costGold, Upgrades::UpgradeStep::m_costOre, Upgrades::UpgradeStep::m_costSkillPoints, ShopMenu::m_currentShopLevel, Upgrades::UpgradeStep::m_restrictFlag, Upgrades::UpgradeStep::m_restrictPlayerLevelMin, Upgrades::UpgradeStep::m_restrictShopLevelMin, ShopMenuContent::m_shopMenu, ShopButtonWidget::m_shopRestricted, Widget::m_tooltipText, Widget::m_tooltipTitle, m_upgrade, m_upgradeStep, Upgrades::UpgradeStep::PayScale(), ShopButtonWidget::SetPrice(), ShopButtonWidget::SetPriceGold(), ShopButtonWidget::SetPriceOre(), ShopButtonWidget::SetPriceSkillPoints(), ScalableSpriteButtonWidget::SetText(), and ShopButtonWidget::UpdateEnabled().
     {
         @m_upgrade = upgrade;
         @m_upgradeStep = step;
         SetText(m_upgradeStep.GetButtonText());
         m_tooltipTitle = m_upgradeStep.GetTooltipTitle();
         m_tooltipText = m_upgradeStep.GetTooltipDescription();
         auto record = GetLocalPlayerRecord();
         float priceScale = step.PayScale();
         if (m_upgradeStep.m_costGold > 0)
             SetPriceGold(int(int(m_upgradeStep.m_costGold) * priceScale));
         else if (m_upgradeStep.m_costOre > 0)
             SetPriceOre(int(int(m_upgradeStep.m_costOre) * priceScale));
         else if (m_upgradeStep.m_costSkillPoints > 0)
             SetPriceSkillPoints(int(int(m_upgradeStep.m_costSkillPoints) * priceScale));
         else
             SetPrice(0);
         //TODO: Show restriction reason somewhere
         m_shopRestricted = false;
         if (m_upgradeStep.m_restrictShopLevelMin != -1)
         {
             if (m_upgradeStep.m_restrictShopLevelMin > menuContent.m_shopMenu.m_currentShopLevel)
                 m_shopRestricted = true;
         }
         if (m_upgradeStep.m_restrictPlayerLevelMin != -1)
         {
             if (m_upgradeStep.m_restrictPlayerLevelMin > record.level)
                 m_shopRestricted = true;
         }
         if (m_upgradeStep.m_restrictFlag != "")
         {
             if (!g_flags.IsSet(m_upgradeStep.m_restrictFlag))
                 m_shopRestricted = true;
         }
         if (!m_shopRestricted)
             m_shopRestricted = m_upgradeStep.IsRestricted();
         UpdateEnabled();
     }
Member Data Documentation
m_scriptSpriteIcon
ScriptSprite UpgradeShopButtonWidget::m_scriptSpriteIcon private
Definition at line 3 of file UpgradeShopButtonWidget.as.
Referenced by DrawIcon().
m_upgrade
Upgrades::Upgrade UpgradeShopButtonWidget::m_upgrade private
Definition at line 5 of file UpgradeShopButtonWidget.as.
Referenced by DrawIcon(), and Set().
m_upgradeStep
Upgrades::UpgradeStep UpgradeShopButtonWidget::m_upgradeStep private
Definition at line 6 of file UpgradeShopButtonWidget.as.
Referenced by DrawIcon(), and Set().
The documentation for this class was generated from the following file:
scripts/GUI/Widgets/UpgradeShopButtonWidget.as