HoHDocs: TownRecord Class Reference
TownRecord Class Reference
Private Member Functions
TownRecord (bool local=false)
void FoundItem (ActorItem@ item)
void KilledEnemy (UnitProducer@ prod)
void EnemyKilledPlayer (UnitProducer@ prod)
array< BestiaryEntry@> GetBestiary (string type)
int GetReputation ()
int GetReputationPresented ()
void CheckForNewTitle ()
void OnNewTitle (Titles::Title@ title)
Titles::Title GetTitle ()
Titles::Title GetNextTitle ()
void GiveStatue (string id, int level)
TownStatue GetStatue (string id)
array< TownStatue@> GetPlacedStatues ()
int GetStatuePlacement (string id)
TownBuilding GetBuilding (string typeName)
array< Materials::Dye@> GetOwnedDyes (Materials::Category category)
bool OwnsDye (Materials::Dye@ dye)
void GiveDye (Materials::Dye@ dye)
void Save (SValueBuilder &builder, bool saveFlags)
void Load (SValue@ sv)
Private Attributes
bool m_local
dictionary m_userdata
array< TownBuilding@> m_buildings
array< TownStatue@> m_statues
array< string > m_statuePlacements
array< BestiaryEntry@> m_bestiary
array< ItemiaryEntry@> m_itemiary
Stats::StatList m_statistics
pint m_gold
pint m_ore
pint m_fountainGold
pint m_reputationPresented
pint m_currentNgp
pint m_highestNgp
array< uint > m_bossesKilled
array< string > m_townFlags
array< uint > m_forgeBlueprints
array< Materials::Dye@> m_dyes
array< uint > m_savedFountainEffects
Detailed Description
Definition at line 32 of file TownRecord.as.
Constructor & Destructor Documentation
TownRecord()
TownRecord::TownRecord (bool local = false) inline private
Definition at line 67 of file TownRecord.as.
References Stats::LoadList(), m_bossesKilled, m_buildings, m_local, and m_statistics.
     {
         m_local = local;
         m_buildings.insertLast(TownBuilding(this, "townhall", 1));
         m_buildings.insertLast(TownBuilding(this, "guildhall", 1));
         m_buildings.insertLast(TownBuilding(this, "generalstore", 1));
         m_buildings.insertLast(TownBuilding(this, "blacksmith", 0));
         m_buildings.insertLast(TownBuilding(this, "oretrader", 0));
         m_buildings.insertLast(TownBuilding(this, "apothecary", 0));
         m_buildings.insertLast(TownBuilding(this, "fountain", 0));
         m_buildings.insertLast(TownBuilding(this, "magicshop", 0));
         m_buildings.insertLast(TownBuilding(this, "chapel", 0));
         m_buildings.insertLast(TownBuilding(this, "tavern", 0));
         m_buildings.insertLast(TownBuilding(this, "treasury", 1));
         m_buildings.insertLast(TownBuilding(this, "sculptor", 0));
         m_buildings.insertLast(TownBuilding(this, "forge", 0));
         @m_statistics = Stats::LoadList("tweak/stats.sval");
         m_bossesKilled.insertLast(0);
         m_bossesKilled.insertLast(0);
         m_bossesKilled.insertLast(0);
         m_bossesKilled.insertLast(0);
         m_bossesKilled.insertLast(0);
         m_bossesKilled.insertLast(0);
     }
Member Function Documentation
CheckForNewTitle()
void TownRecord::CheckForNewTitle () inline private
Definition at line 163 of file TownRecord.as.
References GetNextTitle(), GetReputation(), GetTitle(), m_reputationPresented, and OnNewTitle().
     {
         int reputation = GetReputation();
         int reputationRun = reputation - m_reputationPresented;
         while (reputationRun > 0)
         {
             auto title = GetTitle();
             auto titleNext = GetNextTitle();
             if (titleNext is null)
                 break;
             int giveRep = titleNext.m_points - title.m_points;
             if (reputationRun < giveRep)
                 break;
             OnNewTitle(titleNext);
             m_reputationPresented += giveRep;
             reputationRun -= giveRep;
         }
         m_reputationPresented = reputation;
     }
EnemyKilledPlayer()
void TownRecord::EnemyKilledPlayer (UnitProducer@ prod) inline private
Definition at line 123 of file TownRecord.as.
References m_bestiary.
     {
         for (uint i = 0; i < m_bestiary.length(); i++)
         {
             if (m_bestiary[i].m_producer !is prod)
                 continue;
             m_bestiary[i].m_killer++;
             return;
         }
         m_bestiary.insertLast(BestiaryEntry(prod, 0, 1));
     }
FoundItem()
void TownRecord::FoundItem (ActorItem@ item) inline private
Definition at line 95 of file TownRecord.as.
References ItemiaryEntry(), m_item, and m_itemiary.
     {
         for (uint i = 0; i < m_itemiary.length(); i++)
         {
             if (m_itemiary[i].m_item !is item)
                 continue;
             m_itemiary[i].m_count++;
             return;
         }
         m_itemiary.insertLast(ItemiaryEntry(item, 1));
     }
GetBestiary()
array<BestiaryEntry@> TownRecord::GetBestiary (string type) inline private
Definition at line 137 of file TownRecord.as.
References m_bestiary, m_type, and type.
     {
         uint filter = HashString(type);
         array<BestiaryEntry@> ret;
         for (uint i = 0; i < m_bestiary.length(); i++)
         {
             if (m_bestiary[i].m_type != filter)
                 continue;
             ret.insertLast(m_bestiary[i]);
         }
         return ret;
     }
GetBuilding()
TownBuilding TownRecord::GetBuilding (string typeName) inline private
Definition at line 267 of file TownRecord.as.
References m_buildings.
Referenced by TownhallMenuContent::AddButton(), Town::CheckForAchievements(), Load(), and Town::SpawnBuildings().
     {
         for (uint i = 0; i < m_buildings.length(); i++)
         {
             if (m_buildings[i].m_typeName == typeName)
                 return m_buildings[i];
         }
         return null;
     }
GetNextTitle()
Titles::Title TownRecord::GetNextTitle () inline private
Definition at line 216 of file TownRecord.as.
References g_gameMode, and GetReputationPresented().
Referenced by CheckForNewTitle().
     {
         auto gm = cast<Campaign>(g_gameMode);
         return gm.m_titlesGuild.GetNextTitleFromPoints(GetReputationPresented());
     }
GetOwnedDyes()
array<Materials::Dye@> TownRecord::GetOwnedDyes (Materials::Category category) inline private
Definition at line 277 of file TownRecord.as.
References Materials::g_dyes, and m_dyes.
     {
         array<Materials::Dye@> ret;
         for (uint i = 0; i < Materials::g_dyes.length(); i++)
         {
             auto dye = Materials::g_dyes[i];
             if (dye.m_default && dye.m_category == category)
                 ret.insertLast(dye);
         }
         for (uint i = 0; i < m_dyes.length(); i++)
         {
             auto dye = m_dyes[i];
             if (dye.m_category == category)
                 ret.insertLast(dye);
         }
         return ret;
     }
GetPlacedStatues()
array<TownStatue@> TownRecord::GetPlacedStatues () inline private
Definition at line 245 of file TownRecord.as.
References GetStatue(), and m_statuePlacements.
Referenced by Campaign::RefreshTownModifiers().
     {
         array<TownStatue@> ret;
         for (uint i = 0; i < m_statuePlacements.length(); i++)
         {
             auto statue = GetStatue(m_statuePlacements[i]);
             if (statue !is null)
                 ret.insertLast(statue);
         }
         return ret;
     }
GetReputation()
int TownRecord::GetReputation () inline private
Definition at line 153 of file TownRecord.as.
References Stats::StatList::GetReputationPoints(), and m_statistics.
Referenced by CheckForNewTitle(), Load(), and Menu::SlotsMenu::RefreshSlots().
     {
         return m_statistics.GetReputationPoints();
     }
GetReputationPresented()
int TownRecord::GetReputationPresented () inline private
Definition at line 158 of file TownRecord.as.
References m_reputationPresented.
Referenced by GetNextTitle(), and GetTitle().
     {
         return m_reputationPresented;
     }
GetStatue()
TownStatue TownRecord::GetStatue (string id) inline private
Definition at line 235 of file TownRecord.as.
References m_id, and m_statues.
Referenced by GetPlacedStatues(), GiveStatue(), Load(), and Town::SetStatues().
     {
         for (uint i = 0; i < m_statues.length(); i++)
         {
             if (m_statues[i].m_id == id)
                 return m_statues[i];
         }
         return null;
     }
GetStatuePlacement()
int TownRecord::GetStatuePlacement (string id) inline private
Definition at line 257 of file TownRecord.as.
References m_statuePlacements.
     {
         for (uint i = 0; i < m_statuePlacements.length(); i++)
         {
             if (m_statuePlacements[i] == id)
                 return i;
         }
         return -1;
     }
GetTitle()
Titles::Title TownRecord::GetTitle () inline private
Definition at line 210 of file TownRecord.as.
References g_gameMode, and GetReputationPresented().
Referenced by CheckForNewTitle(), and Campaign::RefreshTownModifiers().
     {
         auto gm = cast<Campaign>(g_gameMode);
         return gm.m_titlesGuild.GetTitleFromPoints(GetReputationPresented());
     }
GiveDye()
void TownRecord::GiveDye (Materials::Dye@ dye) inline private
Definition at line 303 of file TownRecord.as.
References m_dyes, and OwnsDye().
Referenced by GiveAllDyesCFunc().
     {
         if (OwnsDye(dye))
         {
             PrintError("Town already owns dye with category " + int(dye.m_category) + " and ID \"" + dye.m_id + "\"");
             return;
         }
         m_dyes.insertLast(dye);
     }
GiveStatue()
void TownRecord::GiveStatue (string id, int level) inline private
Definition at line 222 of file TownRecord.as.
References GetStatue(), id, TownStatue::m_id, TownStatue::m_level, m_statues, and max.
     {
         TownStatue@ statue = GetStatue(id);
         if (statue is null)
         {
             @statue = TownStatue();
             statue.m_id = id;
             m_statues.insertLast(statue);
         }
         print("Received statue \"" + id + "\" level " + level);
         statue.m_level = max(statue.m_level, level);
     }
KilledEnemy()
void TownRecord::KilledEnemy (UnitProducer@ prod) inline private
Definition at line 109 of file TownRecord.as.
References m_bestiary.
     {
         for (uint i = 0; i < m_bestiary.length(); i++)
         {
             if (m_bestiary[i].m_producer !is prod)
                 continue;
             m_bestiary[i].m_kills++;
             return;
         }
         m_bestiary.insertLast(BestiaryEntry(prod, 1, 0));
     }
Load()
void TownRecord::Load (SValue@ sv) inline private
Definition at line 437 of file TownRecord.as.
References g_flags, g_items, GetBuilding(), HwrSaves::GetCharacters(), Materials::GetDye(), ActorItems::GetItem(), GetReputation(), GetStatue(), GetTavernDrink(), HostTown, ItemiaryEntry(), TownStatue::Load(), TownBuilding::Load(), Stats::StatList::Load(), m_bestiary, m_bossesKilled, m_currentNgp, m_dyes, m_forgeBlueprints, m_fountainGold, m_gold, m_highestNgp, TownStatue::m_id, m_itemiary, m_local, m_ore, m_reputationPresented, m_savedFountainEffects, m_statistics, m_statuePlacements, min, NumContexts, SetSeed(), and Town.
Referenced by Menu::SlotsMenu::RefreshSlots(), Campaign::Start(), and MainMenu::Start().
     {
         if (sv is null)
             return;
         m_gold = GetParamInt(UnitPtr(), sv, "gold");
         m_ore = GetParamInt(UnitPtr(), sv, "ore");
         m_fountainGold = GetParamInt(UnitPtr(), sv, "fountain-gold", false);
         m_currentNgp = GetParamInt(UnitPtr(), sv, "current-ngp", false, -1);
         m_highestNgp = GetParamInt(UnitPtr(), sv, "highest-ngp", false, -1);
         if (m_highestNgp == -1)
         {
             m_highestNgp = 0;
             auto chars = HwrSaves::GetCharacters();
             for (uint i = 0; i < chars.length(); i++)
             {
                 int ngp = GetParamInt(UnitPtr(), chars[i], "new-game-plus", false);
                 if (ngp > m_highestNgp)
                     m_highestNgp = ngp;
             }
             print("Setting initial town NGP: " + m_highestNgp);
         }
         if (m_currentNgp > m_highestNgp)
             m_currentNgp = m_highestNgp;
         if (m_currentNgp == -1)
             m_currentNgp = m_highestNgp;
         auto dictBuildings = GetParamDictionary(UnitPtr(), sv, "buildings", false);
         if (dictBuildings !is null)
         {
             auto keys = dictBuildings.GetDictionary().getKeys();
             for (uint i = 0; i < keys.length(); i++)
             {
                 TownBuilding@ building = GetBuilding(keys[i]);
                 if (building is null)
                 {
                     PrintError("Couldn't load building type \"" + keys[i] + "\"");
                     continue;
                 }
                 building.Load(dictBuildings.GetDictionaryEntry(keys[i]));
             }
         }
         auto dictStatistics = GetParamDictionary(UnitPtr(), sv, "statistics", false);
         if (dictStatistics !is null)
             m_statistics.Load(dictStatistics);
         m_reputationPresented = GetReputation();
         auto dictStatues = GetParamDictionary(UnitPtr(), sv, "statues", false);
         if (dictStatues !is null)
         {
             auto keys = dictStatues.GetDictionary().getKeys();
             for (uint i = 0; i < keys.length(); i++)
             {
                 TownStatue@ statue = GetStatue(keys[i]);
                 if (statue !is null)
                     statue.Load(dictStatues.GetDictionaryEntry(keys[i]));
             }
         }
         auto arrPlacements = GetParamArray(UnitPtr(), sv, "statue-placements", false);
         if (arrPlacements !is null)
         {
             for (uint i = 0; i < arrPlacements.length(); i++)
             {
                 TownStatue@ statue = GetStatue(arrPlacements[i].GetString());
                 if (statue !is null)
                     m_statuePlacements.insertLast(statue.m_id);
             }
         }
         auto arrBestiary = GetParamArray(UnitPtr(), sv, "bestiary", false);
         if (arrBestiary !is null)
         {
             for (uint i = 0; i < arrBestiary.length(); i += 3)
             {
                 auto prod = Resources::GetUnitProducer(arrBestiary[i].GetInteger());
                 if (prod is null)
                     continue;
                 m_bestiary.insertLast(BestiaryEntry(prod, arrBestiary[i + 1].GetInteger(), arrBestiary[i + 2].GetInteger()));
             }
         }
         auto arrItemiary = GetParamArray(UnitPtr(), sv, "itemiary", false);
         if (arrItemiary !is null)
         {
             for (uint i = 0; i < arrItemiary.length(); i += 2)
             {
                 auto item = g_items.GetItem(arrItemiary[i].GetInteger());
                 if (item is null)
                     continue;
                 m_itemiary.insertLast(ItemiaryEntry(item, arrItemiary[i + 1].GetInteger()));
             }
         }
         auto arrTDrinks = GetParamArray(UnitPtr(), sv, "tavern-drinks", false);
         if (m_local && arrTDrinks !is null)
         {
             for (uint i = 0; i < arrTDrinks.length(); i += 2)
             {
                 auto drink = GetTavernDrink(arrTDrinks[i].GetInteger());
                 if (drink is null)
                     continue;
                 drink.localCount = arrTDrinks[i + 1].GetInteger();
             }
         }
         auto arrFlags = GetParamArray(UnitPtr(), sv, "flags", false);
         if (arrFlags !is null)
         {
             /*
             for (uint i = 0; i < arrFlags.length(); i++)
                 m_townFlags.insertLast(arrFlags[i].GetString());
             */
             auto flag = m_local ? FlagState::Town : FlagState::HostTown;
             for (uint i = 0; i < arrFlags.length(); i++)
                 g_flags.Set(arrFlags[i].GetString(), flag);
         }
         auto arrRandom = GetParamArray(UnitPtr(), sv, "random", false);
         if (arrRandom !is null)
         {
             for (int i = 0; i < min(int(arrRandom.length()), int(RandomContext::NumContexts)); i++)
                 RandomBank::SetSeed(RandomContext(i), arrRandom[i].GetInteger());
         }
         auto arrBossesKilled = GetParamArray(UnitPtr(), sv, "bosses-killed", false);
         if (arrBossesKilled !is null)
         {
             for (int i = 0; i < min(m_bossesKilled.length(), arrBossesKilled.length()); i++)
                 m_bossesKilled[i] = uint(arrBossesKilled[i].GetInteger());
         }
         auto arrForgeBlueprints = GetParamArray(UnitPtr(), sv, "forge-blueprints", false);
         if (arrForgeBlueprints !is null)
         {
             for (uint i = 0; i < arrForgeBlueprints.length(); i++)
             {
                 if (arrForgeBlueprints[i].GetType() != SValueType::Integer)
                     continue;
                 auto item = g_items.GetItem(arrForgeBlueprints[i].GetInteger());
                 if (item is null || !item.hasBlueprints)
                     continue;
                 if (m_forgeBlueprints.find(item.idHash) != -1)
                     continue;
                 m_forgeBlueprints.insertLast(item.idHash);
             }
         }
         auto arrDyes = GetParamArray(UnitPtr(), sv, "dyes", false);
         if (arrDyes !is null)
         {
             for (uint i = 0; i < arrDyes.length(); i++)
             {
                 auto arrDye = arrDyes[i].GetArray();
                 Materials::Category category = Materials::Category(arrDye[0].GetInteger());
                 uint id = uint(arrDye[1].GetInteger());
                 auto dye = Materials::GetDye(category, id);
                 if (dye is null)
                 {
                     PrintError("Couldn't find dye with category " + int(category) + " and ID " + id);
                     continue;
                 }
                 if (dye.m_default)
                     continue;
                 m_dyes.insertLast(dye);
             }
         }
         auto arrFountainEffects = GetParamArray(UnitPtr(), sv, "fountain-effects", false);
         if (arrFountainEffects !is null)
         {
             for (uint i = 0; i < arrFountainEffects.length(); i++)
                 m_savedFountainEffects.insertLast(uint(arrFountainEffects[i].GetInteger()));
         }
         Hooks::Call("TownRecordLoad", @this, @sv);
     }
OnNewTitle()
void TownRecord::OnNewTitle (Titles::Title@ title) inline private
Definition at line 185 of file TownRecord.as.
References formatThousands(), g_gameMode, m_gold, Titles::Title::m_name, m_ore, Titles::Title::m_skillPoints, Titles::Title::m_unlockGold, Titles::Title::m_unlockOre, and Tweak::NotificationColors_NewTitle.
Referenced by CheckForNewTitle().
     {
         print("New guild title: \"" + title.m_name + "\"");
         m_gold += title.m_unlockGold;
         m_ore += title.m_unlockOre;
         auto gm = cast<Campaign>(g_gameMode);
         gm.RefreshTownModifiers();
         gm.SaveLocalTown();
         dictionary paramsTitle = { { "title", Resources::GetString(title.m_name) } };
         auto notif = gm.m_notifications.Add(
             Resources::GetString(".hud.newtitle.guild", paramsTitle),
             ParseColorRGBA("#" + Tweak::NotificationColors_NewTitle + "FF")
         );
         if (title.m_unlockGold > 0)
             notif.AddSubtext("icon-gold", formatThousands(title.m_unlockGold));
         if (title.m_unlockOre > 0)
             notif.AddSubtext("icon-ore", formatThousands(title.m_unlockOre));
         if (title.m_skillPoints > 0)
             notif.AddSubtext("icon-star", formatThousands(title.m_skillPoints));
     }
OwnsDye()
bool TownRecord::OwnsDye (Materials::Dye@ dye) inline private
Definition at line 298 of file TownRecord.as.
References m_dyes.
Referenced by GiveAllDyesCFunc(), and GiveDye().
     {
         return (dye.m_default || m_dyes.findByRef(dye) != -1);
     }
Save()
void TownRecord::Save (SValueBuilder & builder, bool saveFlags) inline private
Definition at line 314 of file TownRecord.as.
References Fountain::CurrentEffects, g_flags, g_ngp, g_tavernDrinks, GetSeed(), idHash, localCount, m_bestiary, m_bossesKilled, m_buildings, m_count, m_currentNgp, m_dyes, m_forgeBlueprints, m_fountainGold, m_gold, m_highestNgp, m_item, m_itemiary, m_ore, m_statistics, m_statuePlacements, m_statues, m_townFlags, max, NumContexts, Stats::StatList::Save(), and Town.
Referenced by Campaign::SaveLocalTown(), and Campaign::SavePlayer().
     {
         if (Network::IsServer())
             m_currentNgp = g_ngp;
         Hooks::Call("TownRecordSave", @this, builder);
         builder.PushInteger("gold", max(0, m_gold));
         builder.PushInteger("ore", max(0, m_ore));
         builder.PushInteger("fountain-gold", max(0, m_fountainGold));
         builder.PushInteger("current-ngp", m_currentNgp);
         builder.PushInteger("highest-ngp", m_highestNgp);
         builder.PushDictionary("buildings");
         for (uint i = 0; i < m_buildings.length(); i++)
             m_buildings[i].Save(builder);
         builder.PopDictionary();
         builder.PushDictionary("statistics");
         m_statistics.Save(builder);
         builder.PopDictionary();
         builder.PushDictionary("statues");
         for (uint i = 0; i < m_statues.length(); i++)
         {
             auto statue = m_statues[i];
             if (statue.m_sculpted)
                 statue.Save(builder);
         }
         builder.PopDictionary();
         builder.PushArray("statue-placements");
         for (uint i = 0; i < m_statuePlacements.length(); i++)
             builder.PushString(m_statuePlacements[i]);
         builder.PopArray();
         builder.PushArray("bestiary");
         for (uint i = 0; i < m_bestiary.length(); i++)
         {
             builder.PushInteger(m_bestiary[i].m_producer.GetResourceHash());
             builder.PushInteger(m_bestiary[i].m_kills);
             builder.PushInteger(m_bestiary[i].m_killer);
         }
         builder.PopArray();
         builder.PushArray("itemiary");
         for (uint i = 0; i < m_itemiary.length(); i++)
         {
             builder.PushInteger(m_itemiary[i].m_item.idHash);
             builder.PushInteger(m_itemiary[i].m_count);
         }
         builder.PopArray();
         builder.PushArray("tavern-drinks");
         for (uint i = 0; i < g_tavernDrinks.length(); i++)
         {
             if (g_tavernDrinks[i].localCount < 0)
                 continue;
             builder.PushInteger(g_tavernDrinks[i].idHash);
             builder.PushInteger(g_tavernDrinks[i].localCount);
         }
         builder.PopArray();
         builder.PushArray("flags");
         //if (saveFlags)
         {
             for (uint i = 0; i < m_townFlags.length(); i++)
                 builder.PushString(m_townFlags[i]);
             auto flagKeys = g_flags.m_flags.getKeys();
             for (uint i = 0; i < flagKeys.length(); i++)
             {
                 int64 state;
                 g_flags.m_flags.get(flagKeys[i], state);
                 FlagState flag = FlagState(state);
                 if (flag == FlagState::Town /* || flag == FlagState::TownAll || flag == FlagState::HostTown */)
                     builder.PushString(flagKeys[i]);
             }
         }
         builder.PopArray();
         builder.PushArray("random");
         for (int i = 0; i < int(RandomContext::NumContexts); i++)
             builder.PushInteger(RandomBank::GetSeed(RandomContext(i)));
         builder.PopArray();
         builder.PushArray("bosses-killed");
         for (uint i = 0; i < m_bossesKilled.length(); i++)
             builder.PushInteger(int(m_bossesKilled[i]));
         builder.PopArray();
         builder.PushArray("forge-blueprints");
         for (uint i = 0; i < m_forgeBlueprints.length(); i++)
             builder.PushInteger(m_forgeBlueprints[i]);
         builder.PopArray();
         builder.PushArray("dyes");
         for (uint i = 0; i < m_dyes.length(); i++)
         {
             auto dye = m_dyes[i];
             if (dye.m_default)
                 continue;
             builder.PushArray();
             builder.PushInteger(int(dye.m_category));
             builder.PushInteger(dye.m_idHash);
             builder.PopArray();
         }
         builder.PopArray();
         if (Network::IsServer())
         {
             builder.PushArray("fountain-effects");
             for (uint i = 0; i < Fountain::CurrentEffects.length(); i++)
                 builder.PushInteger(Fountain::CurrentEffects[i]);
             builder.PopArray();
         }
     }
Member Data Documentation
m_bestiary
array<BestiaryEntry@> TownRecord::m_bestiary private
Definition at line 43 of file TownRecord.as.
Referenced by EnemyKilledPlayer(), GetBestiary(), KilledEnemy(), Load(), and Save().
m_bossesKilled
array<uint> TownRecord::m_bossesKilled private
Definition at line 58 of file TownRecord.as.
Referenced by Town::CheckForAchievements(), Load(), Save(), and TownRecord().
m_buildings
array<TownBuilding@> TownRecord::m_buildings private
Definition at line 39 of file TownRecord.as.
Referenced by GetBuilding(), Save(), and TownRecord().
m_currentNgp
pint TownRecord::m_currentNgp private
Definition at line 55 of file TownRecord.as.
Referenced by Load(), Save(), and Campaign::Start().
m_dyes
array<Materials::Dye@> TownRecord::m_dyes private
Definition at line 63 of file TownRecord.as.
Referenced by GetOwnedDyes(), GiveDye(), Load(), OwnsDye(), and Save().
m_forgeBlueprints
array<uint> TownRecord::m_forgeBlueprints private
Definition at line 62 of file TownRecord.as.
Referenced by Load(), Save(), and Town::Start().
m_fountainGold
pint TownRecord::m_fountainGold private
Definition at line 51 of file TownRecord.as.
Referenced by Load(), and Save().
m_gold
pint TownRecord::m_gold private
Definition at line 48 of file TownRecord.as.
Referenced by Campaign::DepositRun(), Load(), OnNewTitle(), and Save().
m_highestNgp
pint TownRecord::m_highestNgp private
Definition at line 56 of file TownRecord.as.
Referenced by Load(), and Save().
m_itemiary
array<ItemiaryEntry@> TownRecord::m_itemiary private
Definition at line 44 of file TownRecord.as.
Referenced by FoundItem(), Load(), and Save().
m_local
bool TownRecord::m_local private
Definition at line 34 of file TownRecord.as.
Referenced by Load(), TownBuilding::RefreshModifiers(), and TownRecord().
m_ore
pint TownRecord::m_ore private
Definition at line 49 of file TownRecord.as.
Referenced by Campaign::DepositRun(), Load(), OnNewTitle(), and Save().
m_reputationPresented
pint TownRecord::m_reputationPresented private
Definition at line 53 of file TownRecord.as.
Referenced by CheckForNewTitle(), GetReputationPresented(), and Load().
m_savedFountainEffects
array<uint> TownRecord::m_savedFountainEffects private
Definition at line 65 of file TownRecord.as.
Referenced by Load(), and Campaign::Start().
m_statistics
Stats::StatList TownRecord::m_statistics private
Definition at line 46 of file TownRecord.as.
Referenced by GetReputation(), Load(), Save(), Campaign::Start(), and TownRecord().
m_statuePlacements
array<string> TownRecord::m_statuePlacements private
Definition at line 42 of file TownRecord.as.
Referenced by GetPlacedStatues(), GetStatuePlacement(), Load(), Save(), and Town::SetStatues().
m_statues
array<TownStatue@> TownRecord::m_statues private
Definition at line 41 of file TownRecord.as.
Referenced by GetStatue(), GiveStatue(), and Save().
m_townFlags
array<string> TownRecord::m_townFlags private
Definition at line 60 of file TownRecord.as.
Referenced by Save().
m_userdata
dictionary TownRecord::m_userdata private
Definition at line 37 of file TownRecord.as.
The documentation for this class was generated from the following file:
scripts/Town/TownRecord.as