HoHDocs: Titles::TitleList Class Reference
Titles::TitleList Class Reference
Private Member Functions
TitleList (string filename)
void ClearModifiers (Modifiers::ModifierList@ modifiers)
void EnableTitleModifiers (PlayerRecord@ record, int index)
array< Modifiers::Modifier@> GetExtraModifiers (int index)
Title GetTitle (int index)
Title GetTitleFromPoints (int points)
Title GetNextTitleFromPoints (int points)
Private Attributes
array< Title@> m_titles
array< Modifiers::Modifier@> m_incModifiers
Detailed Description
Definition at line 3 of file TitleList.as.
Constructor & Destructor Documentation
TitleList()
Titles::TitleList::TitleList (string filename) inline private
Definition at line 9 of file TitleList.as.
References Modifiers::LoadModifiers(), m_incModifiers, and m_titles.
         {
             auto sval = Resources::GetSValue(filename);
             if (sval is null)
             {
                 PrintError("Couldn't find titles list file \"" + filename + "\"");
                 return;
             }
             m_incModifiers = Modifiers::LoadModifiers(UnitPtr(), sval, "inc-");
             auto arr = GetParamArray(UnitPtr(), sval, "titles");
             for (uint i = 0; i < arr.length(); i++)
                 m_titles.insertLast(Title(arr[i]));
         }
Member Function Documentation
ClearModifiers()
void Titles::TitleList::ClearModifiers (Modifiers::ModifierList@ modifiers) inline private
Definition at line 25 of file TitleList.as.
References m_titles, and modifiers.
Referenced by Campaign::RefreshTownModifiers().
         {
             for (uint i = 0; i < m_titles.length(); i++)
                 modifiers.Remove(m_titles[i].m_modifiers);
         }
EnableTitleModifiers()
void Titles::TitleList::EnableTitleModifiers (PlayerRecord@ record, int index) inline private
Definition at line 31 of file TitleList.as.
References Titles::Title::EnableModifiers(), GetExtraModifiers(), and GetTitle().
         {
             GetTitle(index).EnableModifiers(record);
             auto extra = GetExtraModifiers(index);
             for (uint i = 0; i < extra.length(); i++)
                 record.modifiersTitles.Add(extra[i]);
         }
GetExtraModifiers()
array<Modifiers::Modifier@> Titles::TitleList::GetExtraModifiers (int index) inline private
Definition at line 40 of file TitleList.as.
References m_incModifiers, m_titles, and num.
Referenced by GuildHallStatsTab::AddClassesClassToList(), and EnableTitleModifiers().
         {
             array<Modifiers::Modifier@> ret;
             if (index < int(m_titles.length()) || m_incModifiers.length() == 0)
                 return ret;
             int num = index - int(m_titles.length()) + 1;
             for (int i = 0; i < num; i++)
             {
                 for (uint j = 0; j < m_incModifiers.length(); j++)
                     ret.insertLast(m_incModifiers[j]);
             }
             return ret;
         }
GetNextTitleFromPoints()
Title Titles::TitleList::GetNextTitleFromPoints (int points) inline private
Definition at line 73 of file TitleList.as.
References m_titles.
         {
             for (int i = m_titles.length() - 1; i >= 0; i--)
             {
                 if (points >= m_titles[i].m_points)
                 {
                     if (i == int(m_titles.length()) - 1)
                         break;
                     return m_titles[i + 1];
                 }
             }
             return null;
         }
GetTitle()
Title Titles::TitleList::GetTitle (int index) inline private
Definition at line 56 of file TitleList.as.
References m_titles.
Referenced by EnableTitleModifiers(), and Titles::ClassTitles::GetTitle().
         {
             if (index >= int(m_titles.length()))
                 return m_titles[m_titles.length() - 1];
             return m_titles[index];
         }
GetTitleFromPoints()
Title Titles::TitleList::GetTitleFromPoints (int points) inline private
Definition at line 63 of file TitleList.as.
References m_titles.
         {
             for (int i = m_titles.length() - 1; i >= 0; i--)
             {
                 if (points >= m_titles[i].m_points)
                     return m_titles[i];
             }
             return null;
         }
Member Data Documentation
m_incModifiers
array<Modifiers::Modifier@> Titles::TitleList::m_incModifiers private
Definition at line 7 of file TitleList.as.
Referenced by GetExtraModifiers(), and TitleList().
m_titles
array<Title@> Titles::TitleList::m_titles private
Definition at line 5 of file TitleList.as.
Referenced by ClearModifiers(), GetExtraModifiers(), GetNextTitleFromPoints(), GetTitle(), GetTitleFromPoints(), and TitleList().
The documentation for this class was generated from the following file:
scripts/Titles/TitleList.as