HoHDocs: SpawnPrefabBase Class Reference
SpawnPrefabBase Class Reference
Private Member Functions
void Initialize (UnitPtr unit, SValue@ params)
vec2 CalcJitter ()
void SpawnPrefab (vec2 pos)
Private Attributes
Prefab Prefab
float JitterX
float JitterY
int Delay
Detailed Description
Definition at line 1 of file SpawnPrefabBase.as.
Member Function Documentation
CalcJitter()
vec2 SpawnPrefabBase::CalcJitter () inline private
Definition at line 28 of file SpawnPrefabBase.as.
References JitterX, and JitterY.
Referenced by SpawnPrefab::DoSpawnPrefabs(), and WorldScript::SpawnPrefab::ServerExecute().
     {
         return vec2((randf() * 2.0 - 1.0) * JitterX, (randf() * 2.0 - 1.0) * JitterY);
     }
Initialize()
void SpawnPrefabBase::Initialize (UnitPtr unit, SValue@ params) inline private
Definition at line 16 of file SpawnPrefabBase.as.
Referenced by SpawnPrefab::SpawnPrefab().
     {
         if (params !is null)
         {
             @Prefab = Resources::GetPrefab(GetParamString(unit, params, "prefab"));
             Delay = GetParamInt(unit, params, "delay", false, 0);
             vec2 jitter = GetParamVec2(unit, params, "jitter", false);
             JitterX = jitter.x;
             JitterY = jitter.y;
         }
     }
SpawnPrefab()
void SpawnPrefabBase::SpawnPrefab (vec2 pos) inline private
Definition at line 33 of file SpawnPrefabBase.as.
References Prefab.
Referenced by WorldScript::SpawnPrefab::ServerExecute().
     {
         if (Prefab is null)
             return;
         if (!Network::IsServer())
         {
             (Network::Message("DoSpawnPrefabBase") << Delay << Prefab.GetResourceHash() << pos).SendToHost();
             return;
         }
         if (Delay > 0)
         {
             QueuedTasks::Queue(Delay, SpawnPrefabBaseTask(Prefab, pos));
             return;
         }
         Prefab.Fabricate(g_scene, xyz(pos));
     }
Member Data Documentation
Delay
int SpawnPrefabBase::Delay private
Definition at line 12 of file SpawnPrefabBase.as.
Referenced by SpawnPrefab().
JitterX
float SpawnPrefabBase::JitterX private
Definition at line 7 of file SpawnPrefabBase.as.
Referenced by CalcJitter().
JitterY
float SpawnPrefabBase::JitterY private
Definition at line 9 of file SpawnPrefabBase.as.
Referenced by CalcJitter().
Prefab
Prefab SpawnPrefabBase::Prefab private
Definition at line 4 of file SpawnPrefabBase.as.
Referenced by SpawnPrefab(), and SpawnPrefab().
The documentation for this class was generated from the following file:
scripts/SpawnPrefabBase.as