HoHDocs: ScalableSpriteIconButtonWidget Class Reference
ScalableSpriteIconButtonWidget Class Reference
Private Member Functions
ScalableSpriteIconButtonWidget ()
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void DoDraw (SpriteBatch &sb, vec2 pos) override
Private Attributes
Sprite m_icon
int m_iconSpacing
bool m_iconAfterText
bool m_iconVisible
Detailed Description
Definition at line 1 of file ScalableSpriteIconButtonWidget.as.
Constructor & Destructor Documentation
ScalableSpriteIconButtonWidget()
ScalableSpriteIconButtonWidget::ScalableSpriteIconButtonWidget () inline private
Definition at line 9 of file ScalableSpriteIconButtonWidget.as.
Referenced by Clone().
     {
         super();
     }
Member Function Documentation
Clone()
Widget ScalableSpriteIconButtonWidget::Clone () inline override private
Definition at line 14 of file ScalableSpriteIconButtonWidget.as.
References Widget::CloneInto(), and ScalableSpriteIconButtonWidget().
     {
         ScalableSpriteIconButtonWidget@ w = ScalableSpriteIconButtonWidget();
         CloneInto(w);
         return w;
     }
DoDraw()
void ScalableSpriteIconButtonWidget::DoDraw (SpriteBatch & sb, vec2 pos) inline override private
Definition at line 34 of file ScalableSpriteIconButtonWidget.as.
References ScalableSpriteButtonWidget::DoDraw(), g_menuTime, Widget::m_height, m_icon, m_iconAfterText, m_iconSpacing, m_iconVisible, ScalableSpriteButtonWidget::m_text, ScalableSpriteButtonWidget::m_textOffset, and Widget::m_width.
     {
         ScalableSpriteButtonWidget::DoDraw(sb, pos);
         if (m_iconVisible && m_icon !is null)
         {
             vec2 posIcon;
             if (m_iconAfterText)
             {
                 posIcon = vec2(
                     round(m_width / 2.0f + m_text.GetWidth() / 2.0f + m_iconSpacing),
                     round(m_height / 2.0f - m_icon.GetHeight() / 2.0f + m_textOffset.y)
                 );
             }
             else
             {
                 posIcon = vec2(
                     round(m_width - m_icon.GetWidth() - m_iconSpacing),
                     round(m_height / 2.0f - m_icon.GetHeight() / 2.0f + m_textOffset.y)
                 );
             }
             sb.DrawSprite(pos + posIcon, m_icon, g_menuTime);
         }
     }
Load()
void ScalableSpriteIconButtonWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 21 of file ScalableSpriteIconButtonWidget.as.
References Widget::Load(), m_icon, m_iconAfterText, m_iconSpacing, and m_iconVisible.
Referenced by LoadScalableSpriteIconButtonWidget().
     {
         ScalableSpriteButtonWidget::Load(ctx);
         auto def = ctx.GetGUIDef();
         @m_icon = def.GetSprite(ctx.GetString("icon", false));
         m_iconSpacing = ctx.GetInteger("icon-spacing", false, 2);
         m_iconAfterText = ctx.GetBoolean("icon-after-text", false, true);
         m_iconVisible = ctx.GetBoolean("icon-visible", false, true);
     }
Member Data Documentation
m_icon
Sprite ScalableSpriteIconButtonWidget::m_icon private
Definition at line 3 of file ScalableSpriteIconButtonWidget.as.
Referenced by DoDraw(), Load(), and CharacterCustomizationBase::UpdateCost().
m_iconAfterText
bool ScalableSpriteIconButtonWidget::m_iconAfterText private
Definition at line 6 of file ScalableSpriteIconButtonWidget.as.
Referenced by DoDraw(), and Load().
m_iconSpacing
int ScalableSpriteIconButtonWidget::m_iconSpacing private
Definition at line 4 of file ScalableSpriteIconButtonWidget.as.
Referenced by DoDraw(), and Load().
m_iconVisible
bool ScalableSpriteIconButtonWidget::m_iconVisible private
Definition at line 7 of file ScalableSpriteIconButtonWidget.as.
Referenced by DoDraw(), Load(), and FountainShopMenuContent::UpdateInterface().
The documentation for this class was generated from the following file:
scripts/GUI/Widgets/ScalableSpriteIconButtonWidget.as