HoHDocs: Stats::Accomplishment Class Reference
Stats::Accomplishment Class Reference
Private Member Functions
Accomplishment (Stat@ stat, SValue@ sval, int level)
string GetName ()
string GetDescription ()
bool IsValueGood (int64 value)
void OnUpdated ()
void OnLoadFinished ()
Private Attributes
Stat m_stat
int m_level
int64 m_value
int m_reputation
string m_statueID
int m_statueLevel
bool m_finished
Detailed Description
Definition at line 3 of file Accomplishment.as.
Constructor & Destructor Documentation
Accomplishment()
Stats::Accomplishment::Accomplishment (Stat@ stat, SValue@ sval, int level) inline private
Definition at line 16 of file Accomplishment.as.
References m_level, m_reputation, m_stat, m_statueID, m_statueLevel, and m_value.
         {
             @m_stat = stat;
             m_level = level;
             m_value = GetParamLong(UnitPtr(), sval, "value");
             m_reputation = GetParamInt(UnitPtr(), sval, "reputation", false);
             m_statueID = GetParamString(UnitPtr(), sval, "statue-id", false);
             m_statueLevel = GetParamInt(UnitPtr(), sval, "statue-level", false);
         }
Member Function Documentation
GetDescription()
string Stats::Accomplishment::GetDescription () inline private
Definition at line 36 of file Accomplishment.as.
References formatMeters(), formatThousands(), and m_value.
Referenced by GuildHallAccomplishmentsTab::RefreshList().
         {
             string requirement;
             if (m_stat.m_display == Stats::StatDisplay::Distance)
                 requirement = formatMeters(m_value);
             else
                 requirement = formatThousands(m_value);
             return Resources::GetString(".accomplishment." + m_stat.m_name + ".desc", {
                 { "lvl", toRoman(m_level) },
                 { "requirement", requirement }
             });
         }
GetName()
string Stats::Accomplishment::GetName () inline private
Definition at line 29 of file Accomplishment.as.
References m_stat.
Referenced by GuildHallAccomplishmentsTab::RefreshList().
         {
             return Resources::GetString(".accomplishment." + m_stat.m_name + ".name", {
                 { "lvl", toRoman(m_level) }
             });
         }
IsValueGood()
bool Stats::Accomplishment::IsValueGood (int64 value) inline private
Definition at line 51 of file Accomplishment.as.
References m_value.
         {
             return value >= m_value;
         }
OnLoadFinished()
void Stats::Accomplishment::OnLoadFinished () inline private
Definition at line 76 of file Accomplishment.as.
References g_gameMode.
         {
             // Called from:
             // * OnUpdated if the value is good
             // * Town load if the value is good
             auto gm = cast<Campaign>(g_gameMode);
             if (gm is null)
                 return;
             if (m_statueID != "")
             {
                 print("  * Statue: \"" + m_statueID + "\", level: " + m_statueLevel);
                 gm.m_town.GiveStatue(m_statueID, m_statueLevel);
             }
         }
OnUpdated()
void Stats::Accomplishment::OnUpdated () inline private
Definition at line 56 of file Accomplishment.as.
References formatThousands(), g_gameMode, GetName(), m_finished, and Tweak::NotificationColors_Accomplishment.
         {
             // If already finished, or the stat value isn't reached yet
             if (m_finished || !IsValueGood(m_stat.ValueInt()))
                 return;
             m_finished = true;
             auto gm = cast<Campaign>(g_gameMode);
             dictionary params = { { "name", GetName() } };
             auto notif = gm.m_notifications.Add(
                 Resources::GetString(".hud.accomplishment.done", params),
                 ParseColorRGBA("#" + Tweak::NotificationColors_Accomplishment + "FF")
             );
             notif.AddSubtext("icon-reputation", formatThousands(m_reputation));
             OnLoadFinished();
         }
Member Data Documentation
m_finished
bool Stats::Accomplishment::m_finished private
Definition at line 14 of file Accomplishment.as.
Referenced by GuildHallAccomplishmentsTab::RefreshList().
m_level
int Stats::Accomplishment::m_level private
Definition at line 6 of file Accomplishment.as.
Referenced by Accomplishment().
m_reputation
int Stats::Accomplishment::m_reputation private
Definition at line 9 of file Accomplishment.as.
Referenced by Accomplishment(), and GuildHallAccomplishmentsTab::RefreshList().
m_stat
Stat Stats::Accomplishment::m_stat private
Definition at line 5 of file Accomplishment.as.
Referenced by Accomplishment(), and GetName().
m_statueID
string Stats::Accomplishment::m_statueID private
Definition at line 11 of file Accomplishment.as.
Referenced by Accomplishment().
m_statueLevel
int Stats::Accomplishment::m_statueLevel private
Definition at line 12 of file Accomplishment.as.
Referenced by Accomplishment().
m_value
int64 Stats::Accomplishment::m_value private
Definition at line 8 of file Accomplishment.as.
Referenced by Accomplishment(), and GuildHallAccomplishmentsTab::RefreshList().
The documentation for this class was generated from the following file:
scripts/Stats/Accomplishment.as