HoHDocs: Upgrades::ItemUpgrade Class Reference
Upgrades::ItemUpgrade Class Reference
Private Member Functions
ItemUpgrade (SValue &sval)
void Set (ItemShop@ shop, ActorItem@ item)
void Set (ItemShop@ shop)
void SetApplied (PlayerRecord@ record)
Private Attributes
ActorItemQuality m_quality
ItemShop m_shop
ActorItem m_item
float m_costScale
Detailed Description
Definition at line 3 of file ItemUpgrade.as.
Constructor & Destructor Documentation
ItemUpgrade()
Upgrades::ItemUpgrade::ItemUpgrade (SValue & sval) inline private
Definition at line 12 of file ItemUpgrade.as.
References m_costScale.
         {
             super(sval);
             m_costScale = GetParamFloat(UnitPtr(), sval, "cost-scale", false, 1.0f);
         }
Member Function Documentation
Set() [1/2]
void Upgrades::ItemUpgrade::Set (ItemShop@ shop, ActorItem@ item) inline private
Definition at line 19 of file ItemUpgrade.as.
References Upgrades::UpgradeStep::m_costGold, m_costScale, m_item, m_quality, m_shop, and Upgrades::SingleStepUpgrade::m_step.
Referenced by Upgrades::ItemShop::ReadItems(), and Set().
         {
             m_quality = item.quality;
             @m_shop = shop;
             @m_item = item;
             SValueBuilder builder;
             builder.PushDictionary();
             builder.PushString("name", item.name);
             builder.PushString("desc", item.desc);
             @m_step = ItemUpgradeStep(item, this, builder.Build(), 1);
             m_step.m_costGold = int(ceil(int(m_step.m_costGold) * m_costScale));
         }
Set() [2/2]
void Upgrades::ItemUpgrade::Set (ItemShop@ shop) inline private
Definition at line 36 of file ItemUpgrade.as.
References g_gameMode, g_items, m_item, m_quality, Set(), and ActorItems::TakeRandomItem().
         {
             if (m_item !is null)
                 return;
             ActorItem@ item = null;
             while (true)
             {
                 //print("taking a random item..");
                 @item = g_items.TakeRandomItem(m_quality);
                 if (item is null)
                     break;
                 if (item.cost == 0)
                     continue;
                 else if (!item.buyInTown && cast<Town>(g_gameMode) !is null)
                     continue;
                 else if (!item.buyInDungeon && cast<Town>(g_gameMode) is null)
                     continue;
                 else
                     break;
             }
             if (item is null)
             {
                 PrintError("Couldn't find item for quality " + int(m_quality));
                 return;
             }
             Set(shop, item);
         }
SetApplied()
void Upgrades::ItemUpgrade::SetApplied (PlayerRecord@ record) inline private
Definition at line 70 of file ItemUpgrade.as.
References m_shop, and Upgrades::ItemShop::SetApplied().
         {
             m_shop.SetApplied(this, record);
         }
Member Data Documentation
m_costScale
float Upgrades::ItemUpgrade::m_costScale private
Definition at line 10 of file ItemUpgrade.as.
Referenced by ItemUpgrade(), and Set().
m_item
ActorItem Upgrades::ItemUpgrade::m_item private
Definition at line 8 of file ItemUpgrade.as.
Referenced by Set(), and Upgrades::ItemShop::SetApplied().
m_quality
ActorItemQuality Upgrades::ItemUpgrade::m_quality private
Definition at line 5 of file ItemUpgrade.as.
Referenced by Upgrades::ItemShop::AddNewItem(), Upgrades::ItemShop::RerollItems(), and Set().
m_shop
ItemShop Upgrades::ItemUpgrade::m_shop private
Definition at line 7 of file ItemUpgrade.as.
Referenced by Set(), and SetApplied().
The documentation for this class was generated from the following file:
scripts/Upgrades/Upgrades/ItemUpgrade.as