HoHDocs: Upgrades::UpgradeStep Class Reference
Upgrades::UpgradeStep Class Reference
Private Member Functions
UpgradeStep (Upgrade@ upgrade, SValue@ params, int level)
string GetButtonText ()
string GetTooltipTitle ()
string GetTooltipDescription ()
ScriptSprite GetSprite ()
void DrawShopIcon (ShopButtonWidget@ widget, SpriteBatch &sb, vec2 pos, vec2 size, vec4 color)
bool IsOwned (PlayerRecord@ record)
bool IsRestricted ()
bool CanAfford (PlayerRecord@ record)
float PayScale ()
void PayForUpgrade (PlayerRecord@ record)
bool BuyNow (PlayerRecord@ record)
bool ApplyNow (PlayerRecord@ record)
Private Attributes
Upgrade m_upgrade
pint m_costGold
pint m_costOre
pint m_costSkillPoints
string m_name
string m_description
ScriptSprite m_sprite
int m_level
int m_restrictShopLevelMin
int m_restrictShopLevelMax
int m_restrictPlayerLevelMin
string m_restrictFlag
Detailed Description
Definition at line 3 of file UpgradeStep.as.
Constructor & Destructor Documentation
UpgradeStep()
Upgrades::UpgradeStep::UpgradeStep (Upgrade@ upgrade, SValue@ params, int level) inline private
Definition at line 22 of file UpgradeStep.as.
References m_costGold, m_costOre, m_costSkillPoints, m_description, m_level, m_name, m_restrictFlag, m_restrictPlayerLevelMin, m_restrictShopLevelMax, m_restrictShopLevelMin, m_sprite, m_upgrade, and ScriptSprite().
         {
             @m_upgrade = upgrade;
             m_costGold = GetParamInt(UnitPtr(), params, "cost-gold", false);
             m_costOre = GetParamInt(UnitPtr(), params, "cost-ore", false);
             m_costSkillPoints = GetParamInt(UnitPtr(), params, "cost-skillpoints", false);
             m_name = GetParamString(UnitPtr(), params, "name", false);
             m_description = GetParamString(UnitPtr(), params, "desc", false);
             auto arrSprite = GetParamArray(UnitPtr(), params, "icon", false);
             if (arrSprite !is null)
                 @m_sprite = ScriptSprite(arrSprite);
             m_level = GetParamInt(UnitPtr(), params, "level", false, level);
             m_restrictShopLevelMin = GetParamInt(UnitPtr(), params, "restrict-shop-level-min", false, -1);
             m_restrictShopLevelMax = GetParamInt(UnitPtr(), params, "restrict-shop-level-max", false, -1);
             m_restrictPlayerLevelMin = GetParamInt(UnitPtr(), params, "restrict-player-level-min", false, -1);
             m_restrictFlag = GetParamString(UnitPtr(), params, "restrict-flag", false, "");
         }
Member Function Documentation
ApplyNow()
bool Upgrades::UpgradeStep::ApplyNow (PlayerRecord@ record) inline private
Definition at line 161 of file UpgradeStep.as.
Referenced by BuyNow().
         {
             return false;
         }
BuyNow()
bool Upgrades::UpgradeStep::BuyNow (PlayerRecord@ record) inline private
Definition at line 156 of file UpgradeStep.as.
References ApplyNow().
Referenced by ShopMenuContent::BuyItem().
         {
             return ApplyNow(record);
         }
CanAfford()
bool Upgrades::UpgradeStep::CanAfford (PlayerRecord@ record) inline private
Definition at line 87 of file UpgradeStep.as.
References g_gameMode, m_costGold, m_costOre, m_costSkillPoints, and PayScale().
Referenced by ShopMenuContent::BuyItem(), Upgrades::ItemUpgradeStep::PayForUpgrade(), and PayForUpgrade().
         {
             bool inTown = (cast<Town>(g_gameMode) !is null);
             int costGold = int(int(m_costGold) * PayScale());
             int costOre = int(int(m_costOre) * PayScale());
             if (inTown)
             {
                 auto gm = cast<Campaign>(g_gameMode);
                 if (gm is null)
                     return false;
                 if (costGold > 0 && costGold > gm.m_townLocal.m_gold)
                     return false;
                 if (costOre > 0 && costOre > gm.m_townLocal.m_ore)
                     return false;
             }
             else
             {
                 if (costGold > 0 && costGold > record.runGold)
                     return false;
                 if (costOre > 0 && costOre > record.runOre)
                     return false;
             }
             if (m_costSkillPoints > 0 && m_costSkillPoints > record.GetAvailableSkillpoints())
                 return false;
             return true;
         }
DrawShopIcon()
void Upgrades::UpgradeStep::DrawShopIcon (ShopButtonWidget@ widget, SpriteBatch & sb, vec2 pos, vec2 size, vec4 color) inline private
Definition at line 67 of file UpgradeStep.as.
Referenced by UpgradeShopButtonWidget::DrawIcon().
         {
         }
GetButtonText()
string Upgrades::UpgradeStep::GetButtonText () inline private
Definition at line 45 of file UpgradeStep.as.
References m_name.
Referenced by UpgradeShopButtonWidget::Set().
         {
             return Resources::GetString(m_name);
         }
GetSprite()
ScriptSprite Upgrades::UpgradeStep::GetSprite () inline private
Definition at line 60 of file UpgradeStep.as.
References Upgrades::Upgrade::m_sprite, m_sprite, and m_upgrade.
         {
             if (m_sprite is null)
                 return m_upgrade.m_sprite;
             return m_sprite;
         }
GetTooltipDescription()
string Upgrades::UpgradeStep::GetTooltipDescription () inline private
Definition at line 55 of file UpgradeStep.as.
References m_description.
Referenced by Upgrades::ItemUpgradeStep::GetTooltipDescription(), and UpgradeShopButtonWidget::Set().
         {
             return Resources::GetString(m_description);
         }
GetTooltipTitle()
string Upgrades::UpgradeStep::GetTooltipTitle () inline private
Definition at line 50 of file UpgradeStep.as.
References m_name.
Referenced by Upgrades::ItemUpgradeStep::GetTooltipTitle(), and UpgradeShopButtonWidget::Set().
         {
             return Resources::GetString(m_name);
         }
IsOwned()
bool Upgrades::UpgradeStep::IsOwned (PlayerRecord@ record) inline private
Definition at line 71 of file UpgradeStep.as.
References Upgrades::Upgrade::m_id, m_level, and m_upgrade.
         {
             for (uint i = 0; i < record.upgrades.length(); i++)
             {
                 auto ownedUpgrade = record.upgrades[i];
                 if (ownedUpgrade.m_id == m_upgrade.m_id && ownedUpgrade.m_level >= m_level)
                     return true;
             }
             return false;
         }
IsRestricted()
bool Upgrades::UpgradeStep::IsRestricted () inline private
Definition at line 82 of file UpgradeStep.as.
Referenced by Upgrades::ItemUpgradeStep::IsRestricted(), and UpgradeShopButtonWidget::Set().
         {
             return false;
         }
PayForUpgrade()
void Upgrades::UpgradeStep::PayForUpgrade (PlayerRecord@ record) inline private
Definition at line 126 of file UpgradeStep.as.
References Stats::Add(), CanAfford(), g_gameMode, m_costGold, m_costOre, m_costSkillPoints, Upgrades::Upgrade::m_id, m_level, m_upgrade, and PayScale().
Referenced by ShopMenuContent::BuyItem(), Upgrades::ModifierUpgradeStep::PayForUpgrade(), Upgrades::BuildingUpgradeStep::PayForUpgrade(), and Upgrades::ItemUpgradeStep::PayForUpgrade().
         {
             if (!CanAfford(record))
             {
                 PrintError("Tried paying for upgrade while we can not afford the upgrade. (\"" + m_upgrade.m_id + "\" level " + m_level + ")");
                 return;
             }
             bool inTown = (cast<Town>(g_gameMode) !is null);
             if (inTown)
             {
                 auto gm = cast<Campaign>(g_gameMode);
                 if (gm is null)
                     return;
                 gm.m_townLocal.m_gold -= int(int(m_costGold) * PayScale());
                 gm.m_townLocal.m_ore -= int(int(m_costOre) * PayScale());
             }
             else
             {
                 record.runGold -= int(int(m_costGold) * PayScale());
                 record.runOre -= int(int(m_costOre) * PayScale());
             }
             Stats::Add("spent-gold", m_costGold, record);
             Stats::Add("spent-ore", m_costOre, record);
             Stats::Add("spent-skillpoints", m_costSkillPoints, record);
         }
PayScale()
float Upgrades::UpgradeStep::PayScale () inline private
Definition at line 121 of file UpgradeStep.as.
Referenced by CanAfford(), PayForUpgrade(), and UpgradeShopButtonWidget::Set().
         {
             return 1.0f;
         }
Member Data Documentation
m_costGold
pint Upgrades::UpgradeStep::m_costGold private
Definition at line 7 of file UpgradeStep.as.
Referenced by CanAfford(), Upgrades::ItemUpgradeStep::ItemUpgradeStep(), PayForUpgrade(), Upgrades::ItemUpgrade::Set(), UpgradeShopButtonWidget::Set(), and UpgradeStep().
m_costOre
pint Upgrades::UpgradeStep::m_costOre private
Definition at line 8 of file UpgradeStep.as.
Referenced by ShopMenuContent::BuyItem(), CanAfford(), PayForUpgrade(), UpgradeShopButtonWidget::Set(), and UpgradeStep().
m_costSkillPoints
pint Upgrades::UpgradeStep::m_costSkillPoints private
Definition at line 9 of file UpgradeStep.as.
Referenced by ShopMenuContent::BuyItem(), CanAfford(), PayForUpgrade(), UpgradeShopButtonWidget::Set(), and UpgradeStep().
m_description
string Upgrades::UpgradeStep::m_description private
Definition at line 12 of file UpgradeStep.as.
Referenced by GetTooltipDescription(), and UpgradeStep().
m_level
int Upgrades::UpgradeStep::m_level private
Definition at line 15 of file UpgradeStep.as.
Referenced by ShopMenuContent::BuyItem(), IsOwned(), PayForUpgrade(), and UpgradeStep().
m_name
string Upgrades::UpgradeStep::m_name private
Definition at line 11 of file UpgradeStep.as.
Referenced by GetButtonText(), GetTooltipTitle(), Upgrades::BuildingUpgradeStep::UpgradeBulding(), and UpgradeStep().
m_restrictFlag
string Upgrades::UpgradeStep::m_restrictFlag private
Definition at line 20 of file UpgradeStep.as.
Referenced by UpgradeShopButtonWidget::Set(), and UpgradeStep().
m_restrictPlayerLevelMin
int Upgrades::UpgradeStep::m_restrictPlayerLevelMin private
Definition at line 19 of file UpgradeStep.as.
Referenced by UpgradeShopButtonWidget::Set(), and UpgradeStep().
m_restrictShopLevelMax
int Upgrades::UpgradeStep::m_restrictShopLevelMax private
Definition at line 18 of file UpgradeStep.as.
Referenced by UpgradeStep().
m_restrictShopLevelMin
int Upgrades::UpgradeStep::m_restrictShopLevelMin private
Definition at line 17 of file UpgradeStep.as.
Referenced by UpgradeShopButtonWidget::Set(), and UpgradeStep().
m_sprite
ScriptSprite Upgrades::UpgradeStep::m_sprite private
Definition at line 13 of file UpgradeStep.as.
Referenced by UpgradeShopButtonWidget::DrawIcon(), GetSprite(), and UpgradeStep().
m_upgrade
Upgrade Upgrades::UpgradeStep::m_upgrade private
Definition at line 5 of file UpgradeStep.as.
Referenced by Upgrades::ItemUpgradeStep::ApplyNow(), Upgrades::BuildingUpgradeStep::BuyNow(), GetSprite(), Upgrades::BuildingUpgradeStep::IsOwned(), IsOwned(), Upgrades::BuildingUpgradeStep::PayForUpgrade(), PayForUpgrade(), Upgrades::BuildingUpgradeStep::UpgradeBulding(), and UpgradeStep().
The documentation for this class was generated from the following file:
scripts/Upgrades/UpgradeStep.as