HoHDocs: Upgrades::BuildingUpgradeStep Class Reference
Upgrades::BuildingUpgradeStep Class Reference
Private Member Functions
BuildingUpgradeStep (Upgrade@ upgrade, SValue@ params, int level)
bool BuyNow (PlayerRecord@ record) override
void PayForUpgrade (PlayerRecord@ record) override
bool IsOwned (PlayerRecord@ record) override
bool UpgradeBulding ()
Private Attributes
int m_buildingLevel
Detailed Description
Definition at line 3 of file BuildingUpgradeStep.as.
Constructor & Destructor Documentation
BuildingUpgradeStep()
Upgrades::BuildingUpgradeStep::BuildingUpgradeStep (Upgrade@ upgrade, SValue@ params, int level) inline private
Definition at line 7 of file BuildingUpgradeStep.as.
References m_buildingLevel.
         {
             super(upgrade, params, level);
             m_buildingLevel = GetParamInt(UnitPtr(), params, "building-level");
         }
Member Function Documentation
BuyNow()
bool Upgrades::BuildingUpgradeStep::BuyNow (PlayerRecord@ record) inline override private
Definition at line 14 of file BuildingUpgradeStep.as.
References g_gameMode, Upgrades::Upgrade::m_id, Upgrades::UpgradeStep::m_upgrade, and UpgradeBulding().
         {
             if (!UpgradeBulding())
                 return false;
             //TODO: Is this ok for netsync?
             if (Network::IsServer())
             {
                 auto gm = cast<Town>(g_gameMode);
                 if (gm !is null)
                 {
                     if (m_upgrade.m_id != "townhall")
                     {
                         gm.m_shopMenu.m_upgradedBuilding = true;
                         gm.m_upgradedBuildingName = m_upgrade.m_id;
                     }
                 }
             }
             return true;
         }
IsOwned()
bool Upgrades::BuildingUpgradeStep::IsOwned (PlayerRecord@ record) inline override private
Definition at line 55 of file BuildingUpgradeStep.as.
References g_gameMode, m_buildingLevel, Upgrades::Upgrade::m_id, TownBuilding::m_level, and Upgrades::UpgradeStep::m_upgrade.
Referenced by TownhallMenuContent::AddButton().
         {
             auto gm = cast<Town>(g_gameMode);
             if (gm is null)
                 return false;
             TownBuilding@ building = gm.m_townLocal.GetBuilding(m_upgrade.m_id);
             if (building is null)
             {
                 PrintError("Building '" + m_upgrade.m_id + "' was not found");
                 return false;
             }
             return building.m_level >= m_buildingLevel;
         }
PayForUpgrade()
void Upgrades::BuildingUpgradeStep::PayForUpgrade (PlayerRecord@ record) inline override private
Definition at line 36 of file BuildingUpgradeStep.as.
References Stats::Add(), ChangeLevel(), g_gameMode, GetCurrentLevelFilename(), GetLocalPlayerRecord(), Upgrades::Upgrade::m_id, Upgrades::UpgradeStep::m_upgrade, and Upgrades::UpgradeStep::PayForUpgrade().
         {
             UpgradeStep::PayForUpgrade(record);
             if (m_upgrade.m_id == "townhall")
             {
                 // Need to do this here because scripts abort on ChangeLevel
                 Stats::Add("buildings-purchased", 1, GetLocalPlayerRecord());
                 // Save town
                 auto gm = cast<Campaign>(g_gameMode);
                 if (gm !is null)
                     gm.SaveLocalTown();
                 // Change level
                 ChangeLevel(GetCurrentLevelFilename());
             }
         }
UpgradeBulding()
bool Upgrades::BuildingUpgradeStep::UpgradeBulding () inline private
Definition at line 72 of file BuildingUpgradeStep.as.
References g_gameMode, m_buildingLevel, Upgrades::Upgrade::m_id, TownBuilding::m_level, Upgrades::UpgradeStep::m_name, Upgrades::UpgradeStep::m_upgrade, and TownBuilding::Upgrade().
Referenced by BuyNow().
         {
             //TODO: What do in multiplayer? Only allow host to purchase town upgrades for their own town?
             auto gm = cast<Town>(g_gameMode);
             if (gm is null)
                 return false;
             TownBuilding@ building = gm.m_townLocal.GetBuilding(m_upgrade.m_id);
             if (building is null)
             {
                 PrintError("Building '" + m_upgrade.m_id + "' was not found");
                 return false;
             }
             if (building.m_level >= m_buildingLevel)
             {
                 PrintError("Building is already level " + building.m_level + ", no need to upgrade it to level " + m_buildingLevel + "!");
                 return false;
             }
             print("Upgrading building \"" + m_name + "\" to level " + m_buildingLevel);
             building.Upgrade(m_buildingLevel);
             return true;
         }
Member Data Documentation
m_buildingLevel
int Upgrades::BuildingUpgradeStep::m_buildingLevel private
Definition at line 5 of file BuildingUpgradeStep.as.
Referenced by BuildingUpgradeStep(), IsOwned(), and UpgradeBulding().
The documentation for this class was generated from the following file:
scripts/Upgrades/Steps/BuildingUpgradeStep.as