HoHDocs: Upgrades::ItemShop Class Reference
Upgrades::ItemShop Class Reference
Private Member Functions
ItemShop (SValue &params)
int GetItemCategory ()
float GetCostScale ()
void ClearItems ()
int ItemsForLevel (int shopLevel)
void RerollItems (int shopLevel, PlayerRecord@ record)
void AddNewItem (ActorItemQuality quality, float costScale, PlayerRecord@ record)
void NewItems (SValue@ sv, PlayerRecord@ record)
void ReadItems (float costScale, PlayerRecord@ record)
void OnOpenMenu (int shopLevel, PlayerRecord@ record) override
ShopIterator Iterate (int shopLevel, PlayerRecord@ record) override
void SetApplied (ItemUpgrade@ upgrade, PlayerRecord@ record)
Private Attributes
SValue m_sval
Detailed Description
Definition at line 3 of file ItemShop.as.
Constructor & Destructor Documentation
ItemShop()
Upgrades::ItemShop::ItemShop (SValue & params) inline private
Definition at line 7 of file ItemShop.as.
References m_sval.
         {
             super(params);
             @m_sval = params;
         }
Member Function Documentation
AddNewItem()
void Upgrades::ItemShop::AddNewItem (ActorItemQuality quality, float costScale, PlayerRecord@ record) inline private
Definition at line 87 of file ItemShop.as.
References Upgrades::ItemUpgrade::m_quality, Upgrades::UpgradeShop::m_upgrades, and quality.
Referenced by Upgrades::DungeonShop::AddPlumeItem(), Upgrades::DungeonShop::NewItems(), and NewItems().
         {
             SValueBuilder builder;
             builder.PushDictionary();
             builder.PushString("id", "item-" + m_upgrades.length());
             builder.PushFloat("cost-scale", costScale);
             auto newUpgrade = ItemUpgrade(builder.Build());
             newUpgrade.m_quality = quality;
             newUpgrade.Set(this);
             m_upgrades.insertLast(newUpgrade);
             record.generalStoreItems.insertLast(newUpgrade.m_item.idHash);
         }
ClearItems()
void Upgrades::ItemShop::ClearItems () inline private
Definition at line 24 of file ItemShop.as.
References Upgrades::UpgradeShop::m_upgrades.
Referenced by OnOpenMenu(), and RerollItems().
         {
             for (int i = int(m_upgrades.length()) - 1; i >= 0; i--)
             {
                 auto upgrade = cast<ItemUpgrade>(m_upgrades[i]);
                 if (upgrade !is null)
                 {
                     upgrade.m_item.inUse = false;
                     m_upgrades.removeAt(i);
                 }
             }
         }
GetCostScale()
float Upgrades::ItemShop::GetCostScale () inline private
Definition at line 19 of file ItemShop.as.
Referenced by NewItems(), ReadItems(), and RerollItems().
         {
             return 1.0f;
         }
GetItemCategory()
int Upgrades::ItemShop::GetItemCategory () inline private
Definition at line 14 of file ItemShop.as.
Referenced by NewItems(), OnOpenMenu(), and RerollItems().
         {
             return 0;
         }
ItemsForLevel()
int Upgrades::ItemShop::ItemsForLevel (int shopLevel) inline private
Definition at line 37 of file ItemShop.as.
References m_sval.
Referenced by GeneralStoreMenuContent::ReloadList().
         {
             auto arr = GetParamArray(UnitPtr(), m_sval, "items");
             auto svalLevel = arr[shopLevel - 1];
             auto arrQualities = GetParamArray(UnitPtr(), svalLevel, "qualities");
             return int(arrQualities.length());
         }
Iterate()
ShopIterator Upgrades::ItemShop::Iterate (int shopLevel, PlayerRecord@ record) inline override private
Definition at line 158 of file ItemShop.as.
References Upgrades::ItemShopIterator().
         {
             return ItemShopIterator(this, shopLevel, record);
         }
NewItems()
void Upgrades::ItemShop::NewItems (SValue@ sv, PlayerRecord@ record) inline private
Definition at line 102 of file ItemShop.as.
References AddNewItem(), GetCostScale(), GetItemCategory(), ParseActorItemQuality(), and quality.
Referenced by Upgrades::DungeonShop::NewItems(), and OnOpenMenu().
         {
             float costScale = GetParamFloat(UnitPtr(), sv, "cost-scale", false, 1.0f);
             costScale *= GetCostScale();
             record.generalStoreItemsSaved = GetItemCategory();
             record.generalStoreItems.removeRange(0, record.generalStoreItems.length());
             auto arrQualities = GetParamArray(UnitPtr(), sv, "qualities");
             for (uint j = 0; j < arrQualities.length(); j++)
             {
                 ActorItemQuality quality = ParseActorItemQuality(arrQualities[j].GetString());
                 AddNewItem(quality, costScale, record);
             }
         }
OnOpenMenu()
void Upgrades::ItemShop::OnOpenMenu (int shopLevel, PlayerRecord@ record) inline override private
Definition at line 142 of file ItemShop.as.
References ClearItems(), GetItemCategory(), m_sval, NewItems(), and ReadItems().
Referenced by Upgrades::DungeonShop::OnOpenMenu().
         {
             ClearItems();
             auto arr = GetParamArray(UnitPtr(), m_sval, "items");
             auto svalLevel = arr[shopLevel - 1];
             if (record.generalStoreItemsSaved == GetItemCategory())
             {
                 float costScale = GetParamFloat(UnitPtr(), svalLevel, "cost-scale", false, 1.0f);
                 ReadItems(costScale, record);
             }
             else
                 NewItems(svalLevel, record);
         }
ReadItems()
void Upgrades::ItemShop::ReadItems (float costScale, PlayerRecord@ record) inline private
Definition at line 118 of file ItemShop.as.
References g_items, GetCostScale(), ActorItems::GetItem(), Upgrades::UpgradeShop::m_upgrades, and Upgrades::ItemUpgrade::Set().
Referenced by OnOpenMenu(), and Upgrades::DungeonShop::ReadItems().
         {
             costScale *= GetCostScale();
             for (uint i = 0; i < record.generalStoreItems.length(); i++)
             {
                 auto item = g_items.GetItem(record.generalStoreItems[i]);
                 if (item is null)
                 {
                     PrintError("Couldn't find item for hash!");
                     continue;
                 }
                 SValueBuilder builder;
                 builder.PushDictionary();
                 builder.PushString("id", "item-" + i);
                 builder.PushFloat("cost-scale", costScale);
                 auto newUpgrade = ItemUpgrade(builder.Build());
                 newUpgrade.Set(this, item);
                 m_upgrades.insertLast(newUpgrade);
             }
         }
RerollItems()
void Upgrades::ItemShop::RerollItems (int shopLevel, PlayerRecord@ record) inline private
Definition at line 45 of file ItemShop.as.
References ClearItems(), g_items, GetCostScale(), ActorItems::GetItem(), GetItemCategory(), Upgrades::ItemUpgrade::m_quality, m_sval, and Upgrades::UpgradeShop::m_upgrades.
         {
             array<ActorItemQuality> qualities;
             for (uint i = 0; i < record.generalStoreItems.length(); i++)
             {
                 auto item = g_items.GetItem(record.generalStoreItems[i]);
                 if (item is null)
                 {
                     PrintError("Couldn't find item for hash in reroll!");
                     continue;
                 }
                 qualities.insertLast(item.quality);
             }
             ClearItems();
             record.generalStoreItemsSaved = GetItemCategory();
             record.generalStoreItems.removeRange(0, record.generalStoreItems.length());
             auto arr = GetParamArray(UnitPtr(), m_sval, "items");
             auto svalLevel = arr[shopLevel - 1];
             float costScale = GetParamFloat(UnitPtr(), svalLevel, "cost-scale", false, 1.0f);
             costScale *= GetCostScale();
             for (uint i = 0; i < qualities.length(); i++)
             {
                 SValueBuilder builder;
                 builder.PushDictionary();
                 builder.PushString("id", "item-" + i);
                 builder.PushFloat("cost-scale", costScale);
                 auto newUpgrade = ItemUpgrade(builder.Build());
                 newUpgrade.m_quality = qualities[i];
                 newUpgrade.Set(this);
                 m_upgrades.insertLast(newUpgrade);
                 record.generalStoreItems.insertLast(newUpgrade.m_item.idHash);
             }
         }
SetApplied()
void Upgrades::ItemShop::SetApplied (ItemUpgrade@ upgrade, PlayerRecord@ record) inline private
Definition at line 163 of file ItemShop.as.
References Upgrades::ItemUpgrade::m_item, and Upgrades::UpgradeShop::m_upgrades.
Referenced by Upgrades::ItemUpgrade::SetApplied().
         {
             int indexUpgrade = m_upgrades.findByRef(upgrade);
             if (indexUpgrade != -1)
                 m_upgrades.removeAt(indexUpgrade);
             int indexStore = record.generalStoreItems.find(upgrade.m_item.idHash);
             if (indexStore != -1)
                 record.generalStoreItems.removeAt(indexStore);
         }
Member Data Documentation
m_sval
SValue Upgrades::ItemShop::m_sval private
Definition at line 5 of file ItemShop.as.
Referenced by ItemsForLevel(), ItemShop(), Upgrades::DungeonShop::OnOpenMenu(), OnOpenMenu(), and RerollItems().
The documentation for this class was generated from the following file:
scripts/Upgrades/Shops/ItemShop.as