HoHDocs: Upgrades::ModifierUpgradeStep Class Reference
Upgrades::ModifierUpgradeStep Class Reference
Private Member Functions
ModifierUpgradeStep (Upgrade@ upgrade, SValue@ params, int level)
bool BuyNow (PlayerRecord@ record) override
void PayForUpgrade (PlayerRecord@ record) override
array< Modifiers::Modifier@> GetModifiers ()
Private Attributes
array< Modifiers::Modifier@> m_modifiers
Detailed Description
Definition at line 3 of file ModifierUpgradeStep.as.
Constructor & Destructor Documentation
ModifierUpgradeStep()
Upgrades::ModifierUpgradeStep::ModifierUpgradeStep (Upgrade@ upgrade, SValue@ params, int level) inline private
Definition at line 7 of file ModifierUpgradeStep.as.
References Modifiers::LoadModifiers(), and m_modifiers.
         {
             super(upgrade, params, level);
             m_modifiers = Modifiers::LoadModifiers(UnitPtr(), params);
         }
Member Function Documentation
BuyNow()
bool Upgrades::ModifierUpgradeStep::BuyNow (PlayerRecord@ record) inline override private
Definition at line 14 of file ModifierUpgradeStep.as.
         {
             //TODO: Husk?
             if (cast<Player>(record.actor) is null)
                 return false;
             return true;
         }
GetModifiers()
array<Modifiers::Modifier@> Upgrades::ModifierUpgradeStep::GetModifiers () inline private
Definition at line 34 of file ModifierUpgradeStep.as.
References m_modifiers.
         {
             return m_modifiers;
         }
PayForUpgrade()
void Upgrades::ModifierUpgradeStep::PayForUpgrade (PlayerRecord@ record) inline override private
Definition at line 23 of file ModifierUpgradeStep.as.
References Stats::Add(), and Upgrades::UpgradeStep::PayForUpgrade().
         {
             UpgradeStep::PayForUpgrade(record);
             Stats::Add("upgrades-bought", 1, record);
             auto player = cast<Player>(record.actor);
             if (player !is null)
                 player.RefreshModifiers();
         }
Member Data Documentation
m_modifiers
array<Modifiers::Modifier@> Upgrades::ModifierUpgradeStep::m_modifiers private
Definition at line 5 of file ModifierUpgradeStep.as.
Referenced by GetModifiers(), and ModifierUpgradeStep().
The documentation for this class was generated from the following file:
scripts/Upgrades/Steps/ModifierUpgradeStep.as