HoHDocs: Upgrades::ChapelShop Class Reference
Upgrades::ChapelShop Class Reference
Private Member Functions
ChapelShop (SValue &params)
int GetIconIndex (int index, int x)
ScriptSprite GetIcon (int y, int index)
Private Attributes
array< array< ScriptSprite@> > m_icons
array< array< Upgrade@> > m_rows
Detailed Description
Definition at line 3 of file ChapelShop.as.
Constructor & Destructor Documentation
ChapelShop()
Upgrades::ChapelShop::ChapelShop (SValue & params) inline private
Definition at line 8 of file ChapelShop.as.
References m_icons, m_rows, Upgrades::UpgradeShop::m_upgrades, and ScriptSprite().
         {
             super(params);
             auto icons = GetParamArray(UnitPtr(), params, "icons");
             for (uint i = 0; i < icons.length(); i++)
             {
                 m_icons.insertLast(array<ScriptSprite@>());
                 auto row = icons[i].GetArray();
                 for (uint j = 0; j < row.length(); j++)
                 {
                     auto iconParams = row[j].GetArray();
                     auto newSprite = ScriptSprite(iconParams);
                     m_icons[i].insertLast(newSprite);
                 }
             }
             auto rows = GetParamArray(UnitPtr(), params, "rows");
             for (uint i = 0; i < rows.length(); i++)
             {
                 m_rows.insertLast(array<Upgrade@>());
                 auto row = rows[i].GetArray();
                 for (uint j = 0; j < row.length(); j++)
                 {
                     auto upgrData = cast<SValue>(row[j]);
                     string upgrClassName = GetParamString(UnitPtr(), upgrData, "class");
                     auto upgr = cast<Upgrades::Upgrade>(InstantiateClass(upgrClassName, upgrData));
                     if (upgr is null)
                     {
                         PrintError("Class \"" + upgrClassName + "\" is not of type Upgrades::Upgrade");
                         continue;
                     }
                     m_upgrades.insertLast(upgr); // so that the iterator can find it (for remembered upgrades)
                     m_rows[i].insertLast(upgr);
                 }
             }
         }
Member Function Documentation
GetIcon()
ScriptSprite Upgrades::ChapelShop::GetIcon (int y, int index) inline private
Definition at line 55 of file ChapelShop.as.
References m_icons.
Referenced by ChapelShopMenuContent::ReloadList().
         {
             if (y < 0 || y >= int(m_icons.length()))
             {
                 PrintError("Y out of range! (Max: " + m_icons.length() + ")");
                 return null;
             }
             if (index < 0 || index >= int(m_icons[y].length()))
             {
                 PrintError("Index out of range! (Max: " + m_icons[y].length() + ")");
                 return null;
             }
             return m_icons[y][index];
         }
GetIconIndex()
int Upgrades::ChapelShop::GetIconIndex (int index, int x) inline private
Definition at line 50 of file ChapelShop.as.
Referenced by ChapelShopMenuContent::ReloadList().
         {
             return index * 2 + x;
         }
Member Data Documentation
m_icons
array<array<ScriptSprite@> > Upgrades::ChapelShop::m_icons private
Definition at line 5 of file ChapelShop.as.
Referenced by ChapelShop(), and GetIcon().
m_rows
array<array<Upgrade@> > Upgrades::ChapelShop::m_rows private
Definition at line 6 of file ChapelShop.as.
Referenced by ChapelShop(), ChapelShopMenuContent::OnFunc(), ChapelShopMenuContent::ReloadList(), and ChapelShopMenuContent::ShouldEnableButton().
The documentation for this class was generated from the following file:
scripts/Upgrades/Shops/ChapelShop.as