HoHDocs: WorldScript::AttachNewUnit Class Reference
WorldScript::AttachNewUnit Class Reference
Private Member Functions
UnitPtr ProduceUnit (int id)
SValue ServerExecute ()
void ClientExecute (SValue@ val)
Private Attributes
UnitProducer UnitType
string SceneName
UnitFeed AttachTo
int OffsetX
int OffsetY
bool DestroyOnDestroy
int Layer
int Duration
Detailed Description
Definition at line 4 of file AttachNewUnit.as.
Member Function Documentation
ClientExecute()
void WorldScript::AttachNewUnit::ClientExecute (SValue@ val) inline private
Definition at line 69 of file AttachNewUnit.as.
References ProduceUnit().
         {
             if (val is null)
                 return;
             ProduceUnit(val.GetInteger());
         }
ProduceUnit()
UnitPtr WorldScript::AttachNewUnit::ProduceUnit (int id) inline private
Definition at line 31 of file AttachNewUnit.as.
References AttachTo, DestroyOnDestroy, Duration, g_scene, id, Layer, OffsetX, OffsetY, SceneName, UnitType, and xyz().
Referenced by ClientExecute(), and ServerExecute().
         {
             auto attachTo = AttachTo.FetchFirst();
             if (!attachTo.IsValid())
                 return UnitPtr();
             if (UnitType is null)
                 return UnitPtr();
             auto sceneName = SceneName;
             if (sceneName == "")
             {
                 auto sceneSet = UnitType.GetSceneSet("start");
                 if (sceneSet.length() > 0)
                     sceneName = sceneSet[0];
             }
             auto offset = vec2(OffsetX, OffsetY);
             UnitProducer@ attProd = Resources::GetUnitProducer("system/attached.unit");
             UnitPtr attUnit = attProd.Produce(g_scene, attachTo.GetPosition() + xyz(offset), id);
             auto att = cast<AttachedUnit>(attUnit.GetScriptBehavior());
             att.Initialize(UnitType, sceneName, Layer, attachTo, offset, DestroyOnDestroy, Duration);
             return attUnit;
         }
ServerExecute()
SValue WorldScript::AttachNewUnit::ServerExecute () inline private
Definition at line 58 of file AttachNewUnit.as.
References ProduceUnit().
         {
             auto u = ProduceUnit(0);
             if (!u.IsValid())
                 return null;
             SValueBuilder sval;
             sval.PushInteger(u.GetId());
             return sval.Build();
         }
Member Data Documentation
AttachTo
UnitFeed WorldScript::AttachNewUnit::AttachTo private
Definition at line 13 of file AttachNewUnit.as.
Referenced by ProduceUnit().
DestroyOnDestroy
bool WorldScript::AttachNewUnit::DestroyOnDestroy private
Definition at line 21 of file AttachNewUnit.as.
Referenced by ProduceUnit().
Duration
int WorldScript::AttachNewUnit::Duration private
Definition at line 27 of file AttachNewUnit.as.
Referenced by ProduceUnit().
Layer
int WorldScript::AttachNewUnit::Layer private
Definition at line 24 of file AttachNewUnit.as.
Referenced by ProduceUnit().
OffsetX
int WorldScript::AttachNewUnit::OffsetX private
Definition at line 16 of file AttachNewUnit.as.
Referenced by ProduceUnit().
OffsetY
int WorldScript::AttachNewUnit::OffsetY private
Definition at line 18 of file AttachNewUnit.as.
Referenced by ProduceUnit().
SceneName
string WorldScript::AttachNewUnit::SceneName private
Definition at line 10 of file AttachNewUnit.as.
Referenced by ProduceUnit().
UnitType
UnitProducer WorldScript::AttachNewUnit::UnitType private
Definition at line 7 of file AttachNewUnit.as.
Referenced by ProduceUnit().
The documentation for this class was generated from the following file:
scripts/WorldScript/AttachNewUnit.as