HoHDocs: WorldScript::ClearTopNumbers Class Reference
WorldScript::ClearTopNumbers Class Reference
Private Member Functions
SValue ServerExecute ()
void ClientExecute (SValue@ sval)
Detailed Description
Definition at line 4 of file ClearTopNumbers.as.
Member Function Documentation
ClientExecute()
void WorldScript::ClearTopNumbers::ClientExecute (SValue@ sval) inline private
Definition at line 16 of file ClearTopNumbers.as.
References ServerExecute().
         {
             ServerExecute();
         }
ServerExecute()
SValue WorldScript::ClearTopNumbers::ServerExecute () inline private
Definition at line 6 of file ClearTopNumbers.as.
References GetHUD().
Referenced by ClientExecute().
         {
             auto hud = GetHUD();
             if (hud is null)
                 return null;
             hud.ClearTopNumberIcons();
             return null;
         }
The documentation for this class was generated from the following file:
scripts/WorldScript/ClearTopNumbers.as