HoHDocs: WorldScript::BossLichRoom Class Reference
WorldScript::BossLichRoom Class Reference
Private Member Functions
void Initialize ()
bool IsInside (vec3 pos)
void DebugDraw (vec2 pos, SpriteBatch &sb)
Private Attributes
vec3 Position
int Width
int Height
Detailed Description
Definition at line 4 of file BossLichRoom.as.
Member Function Documentation
DebugDraw()
void WorldScript::BossLichRoom::DebugDraw (vec2 pos, SpriteBatch & sb) inline private
Definition at line 27 of file BossLichRoom.as.
References Height, Position, Width, and xy().
         {
             vec2 size = vec2(Width, Height);
             vec2 topLeft = xy(Position) - size / 2.0f;
             sb.DrawRectangle(vec4(topLeft.x, topLeft.y, size.x, size.y), vec4(1, 0, 0, 1));
         }
Initialize()
void WorldScript::BossLichRoom::Initialize () inline private
Definition at line 14 of file BossLichRoom.as.
References g_lichRoom.
         {
             @g_lichRoom = this;
         }
IsInside()
bool WorldScript::BossLichRoom::IsInside (vec3 pos) inline private
Definition at line 19 of file BossLichRoom.as.
References Height, Position, Width, and xy().
Referenced by BossLich::Update().
         {
             vec2 size = vec2(Width, Height);
             vec2 topLeft = xy(Position) - size / 2.0f;
             vec2 bottomRight = topLeft + size;
             return (pos.x > topLeft.x && pos.y > topLeft.y && pos.x < bottomRight.x && pos.y < bottomRight.y);
         }
Member Data Documentation
Height
int WorldScript::BossLichRoom::Height private
Definition at line 12 of file BossLichRoom.as.
Referenced by DebugDraw(), and IsInside().
Position
vec3 WorldScript::BossLichRoom::Position private
Definition at line 6 of file BossLichRoom.as.
Referenced by DebugDraw(), and IsInside().
Width
int WorldScript::BossLichRoom::Width private
Definition at line 9 of file BossLichRoom.as.
Referenced by DebugDraw(), and IsInside().
The documentation for this class was generated from the following file:
scripts/WorldScript/BossLichRoom.as