HoHDocs: WorldScript::HideTopNumber Class Reference
WorldScript::HideTopNumber Class Reference
Private Member Functions
SValue ServerExecute ()
void ClientExecute (SValue@ sval)
Private Attributes
string ID
Detailed Description
Definition at line 4 of file HideTopNumber.as.
Member Function Documentation
ClientExecute()
void WorldScript::HideTopNumber::ClientExecute (SValue@ sval) inline private
Definition at line 19 of file HideTopNumber.as.
References ServerExecute().
         {
             ServerExecute();
         }
ServerExecute()
SValue WorldScript::HideTopNumber::ServerExecute () inline private
Definition at line 9 of file HideTopNumber.as.
References GetHUD(), and ID.
Referenced by ClientExecute().
         {
             auto hud = GetHUD();
             if (hud is null)
                 return null;
             hud.HideTopNumberIcon(ID);
             return null;
         }
Member Data Documentation
ID
string WorldScript::HideTopNumber::ID private
Definition at line 7 of file HideTopNumber.as.
Referenced by ServerExecute().
The documentation for this class was generated from the following file:
scripts/WorldScript/HideTopNumber.as