HoHDocs: WorldScript::CreateBossBar Class Reference
WorldScript::CreateBossBar Class Reference
Private Member Functions
bool IsActor (UnitPtr unit)
SValue ServerExecute ()
void ClientExecute (SValue@ val)
Private Attributes
UnitFeed Actors
bool OverActor
int BarCount
int BarOffset
string Name
Detailed Description
Definition at line 4 of file CreateBossBar.as.
Member Function Documentation
ClientExecute()
void WorldScript::CreateBossBar::ClientExecute (SValue@ val) inline private
Definition at line 54 of file CreateBossBar.as.
References ServerExecute().
         {
             ServerExecute();
         }
IsActor()
bool WorldScript::CreateBossBar::IsActor (UnitPtr unit) inline private
Definition at line 21 of file CreateBossBar.as.
References unit.
         {
             return cast<Actor>(unit.GetScriptBehavior()) !is null;
         }
ServerExecute()
SValue WorldScript::CreateBossBar::ServerExecute () inline private
Definition at line 26 of file CreateBossBar.as.
References Actors, HUD::AddBossBar(), BarCount, BarOffset, g_gameMode, GetHUD(), Name, and OverActor.
Referenced by ClientExecute().
         {
             HUD@ hud = GetHUD();
             auto gm = cast<BaseGameMode>(g_gameMode);
             auto units = Actors.FetchAll();
             for (uint i = 0; i < units.length(); i++)
             {
                 Actor@ actor = cast<Actor>(units[i].GetScriptBehavior());
                 if (OverActor)
                 {
                     if (gm !is null)
                         gm.AddBossBarActor(actor, BarCount, BarOffset, Name);
                 }
                 else
                     hud.AddBossBar(actor, Name);
                 auto compositeActor = cast<CompositeActorBehavior>(actor);
                 if (compositeActor !is null)
                 {
                     compositeActor.m_hasBossBar = true;
                     compositeActor.m_hasBossBarName = Name;
                 }
             }
             return null;
         }
Member Data Documentation
Actors
UnitFeed WorldScript::CreateBossBar::Actors private
Definition at line 7 of file CreateBossBar.as.
Referenced by ServerExecute().
BarCount
int WorldScript::CreateBossBar::BarCount private
Definition at line 13 of file CreateBossBar.as.
Referenced by ServerExecute().
BarOffset
int WorldScript::CreateBossBar::BarOffset private
Definition at line 16 of file CreateBossBar.as.
Referenced by ServerExecute().
Name
string WorldScript::CreateBossBar::Name private
Definition at line 19 of file CreateBossBar.as.
Referenced by ServerExecute().
OverActor
bool WorldScript::CreateBossBar::OverActor private
Definition at line 10 of file CreateBossBar.as.
Referenced by ServerExecute().
The documentation for this class was generated from the following file:
scripts/WorldScript/CreateBossBar.as