HoHDocs: WorldScript::DestroyUnitChance Class Reference
WorldScript::DestroyUnitChance Class Reference
Private Member Functions
bool IsValid (UnitPtr unit)
SValue ServerExecute ()
void ClientExecute (SValue@ val)
Private Attributes
UnitFeed Units
float ChanceToDestroy
Detailed Description
Definition at line 4 of file DestroyUnitChance.as.
Member Function Documentation
ClientExecute()
void WorldScript::DestroyUnitChance::ClientExecute (SValue@ val) inline private
Definition at line 40 of file DestroyUnitChance.as.
References Destroy(), and g_scene.
         {
             array<SValue@>@ units = val.GetArray();
             for (uint i = 0; i < units.length(); i++)
                 g_scene.GetUnit(units[i].GetInteger()).Destroy();
         }
IsValid()
bool WorldScript::DestroyUnitChance::IsValid (UnitPtr unit) inline private
Definition at line 13 of file DestroyUnitChance.as.
References unit.
         {
             return WorldScript::GetWorldScript(unit) is null;
         }
ServerExecute()
SValue WorldScript::DestroyUnitChance::ServerExecute () inline private
Definition at line 19 of file DestroyUnitChance.as.
References ChanceToDestroy, IsNetsyncedExistance(), sr_randf(), and Units.
         {
             SValueBuilder sval;
             sval.PushArray();
             auto units = Units.FetchAll();
             for (uint i = 0; i < units.length(); i++)
             {
                 if (sr_randf(i) <= ChanceToDestroy)
                 {
                     auto prod = units[i].GetUnitProducer();
                     if (prod !is null && !IsNetsyncedExistance(prod.GetNetSyncMode()))
                         sval.PushInteger(units[i].GetId());
                     units[i].Destroy();
                 }
             }
             return sval.Build();
         }
Member Data Documentation
ChanceToDestroy
float WorldScript::DestroyUnitChance::ChanceToDestroy private
Definition at line 10 of file DestroyUnitChance.as.
Referenced by ServerExecute().
Units
UnitFeed WorldScript::DestroyUnitChance::Units private
Definition at line 7 of file DestroyUnitChance.as.
Referenced by ServerExecute().
The documentation for this class was generated from the following file:
scripts/WorldScript/DestroyUnitChance.as