HoHDocs: WorldScript::DamageUnits Class Reference
WorldScript::DamageUnits Class Reference
Private Member Functions
bool IsValid (UnitPtr unit)
void Initialize ()
bool ApplyDamage (UnitPtr unit, vec2 pos)
SValue ServerExecute ()
Private Attributes
UnitFeed Units
int Physical
int Magical
DamageType DamageType
string Buff
bool CanKill
DamageInfo m_dmg
ActorBuffDef m_buff
Detailed Description
Definition at line 4 of file DamageUnits.as.
Member Function Documentation
ApplyDamage()
bool WorldScript::DamageUnits::ApplyDamage (UnitPtr unit, vec2 pos) inline private
Definition at line 41 of file DamageUnits.as.
References Actor::ApplyBuff(), FilterHuskDamage(), m_buff, m_dmg, DamageInfo::MagicalDamage, DamageInfo::PhysicalDamage, and unit.
Referenced by ServerExecute().
         {
             if (!FilterHuskDamage(null, unit, !Network::IsServer()))
                 return false;
             auto behavior = unit.GetScriptBehavior();
             if (m_buff !is null)
             {
                 Actor@ actor = cast<Actor>(behavior);
                 if (actor !is null)
                     actor.ApplyBuff(ActorBuff(null, m_buff, 1.0, false));
             }
             if (m_dmg.PhysicalDamage > 0 || m_dmg.MagicalDamage > 0)
             {
                 unit.TriggerCallbacks(UnitEventType::Damaged);
                 IDamageTaker@ dt = cast<IDamageTaker>(behavior);
                 if (dt is null)
                     return true;
                 dt.Damage(m_dmg, pos, vec2(0, 0));
                 return dt.IsDead();
             }
             return false;
         }
Initialize()
void WorldScript::DamageUnits::Initialize () inline private
Definition at line 32 of file DamageUnits.as.
References Buff, CanKill, DamageInfo::CanKill, DamageInfo::DamageType, LoadActorBuff(), m_buff, m_dmg, Magical, DamageInfo::MagicalDamage, Physical, and DamageInfo::PhysicalDamage.
         {
             m_dmg.PhysicalDamage = Physical;
             m_dmg.MagicalDamage = Magical;
             m_dmg.DamageType = uint8(DamageType);
             m_dmg.CanKill = CanKill;
             @m_buff = LoadActorBuff(Buff);
         }
IsValid()
bool WorldScript::DamageUnits::IsValid (UnitPtr unit) inline private
Definition at line 27 of file DamageUnits.as.
References unit.
         {
             return cast<IDamageTaker>(unit.GetScriptBehavior()) !is null;
         }
ServerExecute()
SValue WorldScript::DamageUnits::ServerExecute () inline private
Definition at line 70 of file DamageUnits.as.
References ApplyDamage(), Units, and xy().
         {
             array<UnitPtr>@ units = Units.FetchAll();
             for (uint i = 0; i < units.length(); i++)
                 ApplyDamage(units[i], xy(units[i].GetPosition()));
             return null;
         }
Member Data Documentation
Buff
string WorldScript::DamageUnits::Buff private
Definition at line 19 of file DamageUnits.as.
Referenced by Initialize().
CanKill
bool WorldScript::DamageUnits::CanKill private
Definition at line 22 of file DamageUnits.as.
Referenced by Initialize().
DamageType
DamageType WorldScript::DamageUnits::DamageType private
Definition at line 16 of file DamageUnits.as.
m_buff
ActorBuffDef WorldScript::DamageUnits::m_buff private
Definition at line 25 of file DamageUnits.as.
Referenced by ApplyDamage(), and Initialize().
m_dmg
DamageInfo WorldScript::DamageUnits::m_dmg private
Definition at line 24 of file DamageUnits.as.
Referenced by ApplyDamage(), and Initialize().
Magical
int WorldScript::DamageUnits::Magical private
Definition at line 13 of file DamageUnits.as.
Referenced by Initialize().
Physical
int WorldScript::DamageUnits::Physical private
Definition at line 10 of file DamageUnits.as.
Referenced by Initialize().
Units
UnitFeed WorldScript::DamageUnits::Units private
Definition at line 7 of file DamageUnits.as.
Referenced by ServerExecute().
The documentation for this class was generated from the following file:
scripts/WorldScript/DamageUnits.as