HoHDocs: WorldScript::DestroyUnitCount Class Reference
WorldScript::DestroyUnitCount Class Reference
Private Member Functions
bool IsValid (UnitPtr unit)
SValue ServerExecute ()
void ClientExecute (SValue@ val)
Private Attributes
UnitFeed Units
uint NumToDestroy
Detailed Description
Definition at line 4 of file DestroyUnitCount.as.
Member Function Documentation
ClientExecute()
void WorldScript::DestroyUnitCount::ClientExecute (SValue@ val) inline private
Definition at line 42 of file DestroyUnitCount.as.
References Destroy(), and g_scene.
         {
             array<SValue@>@ units = val.GetArray();
             for (uint i = 0; i < units.length(); i++)
                 g_scene.GetUnit(units[i].GetInteger()).Destroy();
         }
IsValid()
bool WorldScript::DestroyUnitCount::IsValid (UnitPtr unit) inline private
Definition at line 13 of file DestroyUnitCount.as.
References unit.
         {
             return WorldScript::GetWorldScript(unit) is null;
         }
ServerExecute()
SValue WorldScript::DestroyUnitCount::ServerExecute () inline private
Definition at line 18 of file DestroyUnitCount.as.
References IsNetsyncedExistance(), num, NumToDestroy, sr_randi(), and Units.
         {
             SValueBuilder sval;
             sval.PushArray();
             auto units = Units.FetchAll();
             uint num = NumToDestroy;
             int n = 0;
             while (units.length() > 0 && num > 0)
             {
                 uint i = sr_randi(n++, units.length());
                 if (!IsNetsyncedExistance(units[i].GetUnitProducer().GetNetSyncMode()))
                     sval.PushInteger(units[i].GetId());
                 units[i].Destroy();
                 units.removeAt(i);
                 num--;
             }
             return sval.Build();
         }
Member Data Documentation
NumToDestroy
uint WorldScript::DestroyUnitCount::NumToDestroy private
Definition at line 10 of file DestroyUnitCount.as.
Referenced by ServerExecute().
Units
UnitFeed WorldScript::DestroyUnitCount::Units private
Definition at line 7 of file DestroyUnitCount.as.
Referenced by ServerExecute().
The documentation for this class was generated from the following file:
scripts/WorldScript/DestroyUnitCount.as