HoHDocs: WorldScript::OpenInterface Class Reference
WorldScript::OpenInterface Class Reference
Private Member Functions
SValue Save ()
void Load (SValue@ data)
void Start (SValue@ sval, bool loaded)
void Stop ()
SValue ServerExecute ()
void ClientExecute (SValue@ sval)
Private Attributes
ScriptWidgetHost m_interface
UnitFeed ForPlayer
string UserWindowID
string Filename
bool MakeRoot
string Class
Detailed Description
Definition at line 4 of file OpenInterface.as.
Member Function Documentation
ClientExecute()
void WorldScript::OpenInterface::ClientExecute (SValue@ sval) inline private
Definition at line 103 of file OpenInterface.as.
References ForPlayer, Start(), and unit.
Referenced by ServerExecute().
         {
             UnitPtr unit = ForPlayer.FetchFirst();
             if (unit.IsValid() && cast<Player>(unit.GetScriptBehavior()) is null)
                 return;
             Start(sval, false);
         }
Load()
void WorldScript::OpenInterface::Load (SValue@ data) inline private
Definition at line 30 of file OpenInterface.as.
References Start().
         {
             if (data is null || data.GetType() != SValueType::Boolean)
                 return;
             if (data.GetBoolean())
                 Start(null, true);
         }
Save()
SValue WorldScript::OpenInterface::Save () inline private
Definition at line 23 of file OpenInterface.as.
References m_interface, and ScriptWidgetHost::ShouldSaveExistance().
         {
             SValueBuilder builder;
             builder.PushBoolean(m_interface !is null && m_interface.ShouldSaveExistance());
             return builder.Build();
         }
ServerExecute()
SValue WorldScript::OpenInterface::ServerExecute () inline private
Definition at line 97 of file OpenInterface.as.
References ClientExecute().
         {
             ClientExecute(null);
             return null;
         }
Start()
void WorldScript::OpenInterface::Start (SValue@ sval, bool loaded) inline private
Definition at line 39 of file OpenInterface.as.
References Class, Filename, g_gameMode, ScriptWidgetHost::Initialize(), ScriptWidgetHost::LoadWidget(), AGameMode::m_guiBuilder, m_interface, ScriptWidgetHost::m_script, MakeRoot, Stop(), and UserWindowID.
Referenced by ClientExecute(), and Load().
         {
             auto gm = cast<BaseGameMode>(g_gameMode);
             if (gm is null)
             {
                 PrintError("OpenInterface only works on BaseGameMode!");
                 return;
             }
             if (UserWindowID != "")
                 gm.ShowUserWindow(UserWindowID);
             else
             {
                 if (m_interface !is null)
                     Stop();
                 if (Class == "")
                     @m_interface = ScriptWidgetHost();
                 else
                 {
                     SValueBuilder svb;
                     @m_interface = cast<ScriptWidgetHost>(InstantiateClass(Class, svb.Build()));
                 }
                 m_interface.LoadWidget(g_gameMode.m_guiBuilder, Filename);
                 @m_interface.m_script = this;
                 gm.m_widgetScriptHosts.insertLast(m_interface);
                 if (MakeRoot)
                     gm.AddWidgetRoot(m_interface);
                 m_interface.Initialize(loaded);
             }
         }
Stop()
void WorldScript::OpenInterface::Stop () inline private
Definition at line 75 of file OpenInterface.as.
References g_gameMode, m_interface, and MakeRoot.
Referenced by Start(), and ScriptWidgetHost::Stop().
         {
             if (m_interface is null)
                 return;
             auto gm = cast<BaseGameMode>(g_gameMode);
             if (gm is null)
             {
                 PrintError("OpenInterface only works on BaseGameMode!");
                 return;
             }
             int index = gm.m_widgetScriptHosts.findByRef(m_interface);
             if (index != -1)
                 gm.m_widgetScriptHosts.removeAt(index);
             if (MakeRoot)
                 gm.RemoveWidgetRoot(m_interface);
             @m_interface = null;
         }
Member Data Documentation
Class
string WorldScript::OpenInterface::Class private
Definition at line 21 of file OpenInterface.as.
Referenced by Start().
Filename
string WorldScript::OpenInterface::Filename private
Definition at line 15 of file OpenInterface.as.
Referenced by Start().
ForPlayer
UnitFeed WorldScript::OpenInterface::ForPlayer private
Definition at line 9 of file OpenInterface.as.
Referenced by ClientExecute().
m_interface
ScriptWidgetHost WorldScript::OpenInterface::m_interface private
Definition at line 6 of file OpenInterface.as.
Referenced by Save(), Start(), and Stop().
MakeRoot
bool WorldScript::OpenInterface::MakeRoot private
Definition at line 18 of file OpenInterface.as.
Referenced by Start(), and Stop().
UserWindowID
string WorldScript::OpenInterface::UserWindowID private
Definition at line 12 of file OpenInterface.as.
Referenced by Start().
The documentation for this class was generated from the following file:
scripts/WorldScript/OpenInterface.as