HoHDocs: WorldScript::PotionRefill Class Reference
WorldScript::PotionRefill Class Reference
Private Member Functions
bool IsExecutable (UnitPtr unit)
SValue ServerExecute ()
void ClientExecute (SValue@ val)
Private Attributes
UnitFeed Targets
UnitFeed OnRefilled
UnitSource RefillTaker
Detailed Description
Definition at line 4 of file PotionRefill.as.
Member Function Documentation
ClientExecute()
void WorldScript::PotionRefill::ClientExecute (SValue@ val) inline private
Definition at line 29 of file PotionRefill.as.
References Stats::Add(), AddFloatingText(), g_scene, OnRefilled, Pickup, RefillTaker, and Targets.
Referenced by ServerExecute().
         {
             bool hasSet = false;
             auto units = Targets.FetchAll();
             for (uint i = 0; i < units.length(); i++)
             {
                 auto player = cast<PlayerBase>(units[i].GetScriptBehavior());
                 if (player is null)
                     continue;
                 auto record = player.m_record;
                 if (record.potionChargesUsed == 0 && record.hp >= 1.0f && record.mana >= 1.0f)
                     continue;
                 RefillTaker.Replace(player.m_unit);
                 record.potionChargesUsed = 0;
                 record.hp = 1.0f;
                 record.mana = 1.0f;
                 AddFloatingText(FloatingTextType::Pickup, Resources::GetString(".hud.potionrefill"), player.m_unit.GetPosition());
                 hasSet = true;
                 Stats::Add("well-used", 1, record);
             }
             if (hasSet && Network::IsServer())
             {
                 auto arr = OnRefilled.FetchAll();
                 for (uint i = 0; i < arr.length(); i++)
                     WorldScript::GetWorldScript(g_scene, arr[i].GetScriptBehavior()).Execute();
             }
         }
IsExecutable()
bool WorldScript::PotionRefill::IsExecutable (UnitPtr unit) inline private
Definition at line 14 of file PotionRefill.as.
References unit.
         {
             WorldScript@ script = WorldScript::GetWorldScript(unit);
             if (script is null)
                 return false;
             return script.IsExecutable();
         }
ServerExecute()
SValue WorldScript::PotionRefill::ServerExecute () inline private
Definition at line 23 of file PotionRefill.as.
References ClientExecute().
         {
             ClientExecute(null);
             return null;
         }
Member Data Documentation
OnRefilled
UnitFeed WorldScript::PotionRefill::OnRefilled private
Definition at line 10 of file PotionRefill.as.
Referenced by ClientExecute().
RefillTaker
UnitSource WorldScript::PotionRefill::RefillTaker private
Definition at line 12 of file PotionRefill.as.
Referenced by ClientExecute().
Targets
UnitFeed WorldScript::PotionRefill::Targets private
Definition at line 7 of file PotionRefill.as.
Referenced by ClientExecute().
The documentation for this class was generated from the following file:
scripts/WorldScript/PotionRefill.as