HoHDocs: WorldScript::SpawnItem Class Reference
WorldScript::SpawnItem Class Reference
Private Member Functions
UnitPtr DoSpawn (int id=0)
SValue ServerExecute ()
void ClientExecute (SValue@ val)
Private Attributes
vec3 Position
string ItemID
bool Take
Detailed Description
Definition at line 4 of file SpawnItem.as.
Member Function Documentation
ClientExecute()
void WorldScript::SpawnItem::ClientExecute (SValue@ val) inline private
Definition at line 44 of file SpawnItem.as.
References DoSpawn().
         {
             DoSpawn(val.GetInteger());
         }
DoSpawn()
UnitPtr WorldScript::SpawnItem::DoSpawn (int id = 0) inline private
Definition at line 14 of file SpawnItem.as.
References g_items, g_scene, ActorItems::GetItem(), ItemID, Position, Take, and unit.
Referenced by ClientExecute(), and ServerExecute().
         {
             auto item = g_items.GetItem(ItemID);
             if (item is null)
             {
                 PrintError("Couldn't find item with ID \"" + ItemID + "\"!");
                 return UnitPtr();
             }
             if (Take)
                 item.inUse = true;
             auto prod = Resources::GetUnitProducer("items/item_specific.unit");
             auto unit = prod.Produce(g_scene, Position, id);
             auto b = cast<Item>(unit.GetScriptBehavior());
             b.Initialize(item);
             return unit;
         }
ServerExecute()
SValue WorldScript::SpawnItem::ServerExecute () inline private
Definition at line 35 of file SpawnItem.as.
References DoSpawn(), and unit.
         {
             UnitPtr unit = DoSpawn();
             SValueBuilder builder;
             builder.PushInteger(unit.GetId());
             return builder.Build();
         }
Member Data Documentation
ItemID
string WorldScript::SpawnItem::ItemID private
Definition at line 9 of file SpawnItem.as.
Referenced by DoSpawn().
Position
vec3 WorldScript::SpawnItem::Position private
Definition at line 6 of file SpawnItem.as.
Referenced by DoSpawn().
Take
bool WorldScript::SpawnItem::Take private
Definition at line 12 of file SpawnItem.as.
Referenced by DoSpawn().
The documentation for this class was generated from the following file:
scripts/WorldScript/SpawnItem.as