HoHDocs: WorldScript::ShowFloatingText Class Reference
WorldScript::ShowFloatingText Class Reference
Private Member Functions
SValue ServerExecute ()
void ClientExecute (SValue@ val)
Private Attributes
vec3 Position
string Text
FloatingTextType FloatingType
Detailed Description
Definition at line 4 of file ShowFloatingText.as.
Member Function Documentation
ClientExecute()
void WorldScript::ShowFloatingText::ClientExecute (SValue@ val) inline private
Definition at line 20 of file ShowFloatingText.as.
References AddFloatingText(), FloatingType, Position, and Text.
Referenced by ServerExecute().
         {
             string str = Resources::GetString(Text);
             AddFloatingText(FloatingType, str, Position);
         }
ServerExecute()
SValue WorldScript::ShowFloatingText::ServerExecute () inline private
Definition at line 14 of file ShowFloatingText.as.
References ClientExecute().
         {
             ClientExecute(null);
             return null;
         }
Member Data Documentation
FloatingType
FloatingTextType WorldScript::ShowFloatingText::FloatingType private
Definition at line 12 of file ShowFloatingText.as.
Referenced by ClientExecute().
Position
vec3 WorldScript::ShowFloatingText::Position private
Definition at line 6 of file ShowFloatingText.as.
Referenced by ClientExecute().
Text
string WorldScript::ShowFloatingText::Text private
Definition at line 9 of file ShowFloatingText.as.
Referenced by ClientExecute().
The documentation for this class was generated from the following file:
scripts/WorldScript/ShowFloatingText.as