HoHDocs: WorldScript::SetBossKilled Class Reference
WorldScript::SetBossKilled Class Reference
Private Member Functions
SValue ServerExecute ()
void ClientExecute (SValue@ val)
Private Attributes
int BossNumber
Detailed Description
Definition at line 4 of file SetBossKilled.as.
Member Function Documentation
ClientExecute()
void WorldScript::SetBossKilled::ClientExecute (SValue@ val) inline private
Definition at line 15 of file SetBossKilled.as.
References BossNumber, g_gameMode, GetLocalPlayerRecord(), and Stats::Max().
Referenced by ServerExecute().
         {
             auto localPlayer = GetLocalPlayerRecord();
             if (BossNumber == 1)
                 Platform::Service.UnlockAchievement("beat_stone_guardian");
             else if (BossNumber == 2)
                 Platform::Service.UnlockAchievement("beat_warden");
             else if (BossNumber == 3)
                 Platform::Service.UnlockAchievement("beat_three_councilors");
             else if (BossNumber == 4)
                 Platform::Service.UnlockAchievement("beat_watcher");
             else if (BossNumber == 5)
                 Platform::Service.UnlockAchievement("beat_thundersnow");
             else if (BossNumber == 6)
                 Platform::Service.UnlockAchievement("beat_vampire");
             auto gm = cast<Campaign>(g_gameMode);
             gm.m_townLocal.m_bossesKilled[BossNumber - 1] |= localPlayer.GetCharFlags();
             int numClasses = 0;
             for (int i = 0; i < 7; i++)
             {
                 if ((gm.m_townLocal.m_bossesKilled[BossNumber - 1] & (1 << i)) != 0)
                     numClasses++;
             }
             Stats::Max("boss-" + BossNumber + "-killed-class", numClasses, localPlayer);
         }
ServerExecute()
SValue WorldScript::SetBossKilled::ServerExecute () inline private
Definition at line 9 of file SetBossKilled.as.
References ClientExecute().
         {
             ClientExecute(null);
             return null;
         }
Member Data Documentation
BossNumber
int WorldScript::SetBossKilled::BossNumber private
Definition at line 7 of file SetBossKilled.as.
Referenced by ClientExecute().
The documentation for this class was generated from the following file:
scripts/WorldScript/SetBossKilled.as