HoHDocs: WorldScript::SecretFound Class Reference
WorldScript::SecretFound Class Reference
Private Member Functions
SValue ServerExecute ()
void ClientExecute (SValue@ val)
Detailed Description
Definition at line 4 of file SecretFound.as.
Member Function Documentation
ClientExecute()
void WorldScript::SecretFound::ClientExecute (SValue@ val) inline private
Definition at line 19 of file SecretFound.as.
References ServerExecute().
         {
             ServerExecute();
         }
ServerExecute()
SValue WorldScript::SecretFound::ServerExecute () inline private
Definition at line 6 of file SecretFound.as.
References Stats::Add(), g_gameMode, and GetLocalPlayerRecord().
Referenced by ClientExecute().
         {
             Stats::Add("secrets-found", 1, GetLocalPlayerRecord());
             auto campaign = cast<Campaign>(g_gameMode);
             if (campaign !is null)
             {
                 //campaign.FoundSecrets++;
                 //campaign.FoundSecretsTotal++;
             }
             return null;
         }
The documentation for this class was generated from the following file:
scripts/WorldScript/SecretFound.as