HoHDocs: WorldScript::RefreshSpawnPickup Class Reference
WorldScript::RefreshSpawnPickup Class Reference
Private Member Functions
void Initialize ()
UnitPtr ProduceUnit (int id)
void SpawnEffects ()
bool AlreadyExists ()
SValue ServerExecute ()
void ClientExecute (SValue@ val)
Private Attributes
vec3 Position
UnitProducer UnitType
UnitScene SpawnEffect
int SpawnLayer
int EffectLayer
SoundEvent SpawnSound
bool m_needNetSync
Pickup m_currPickup
Detailed Description
Definition at line 4 of file RefreshSpawnPickup.as.
Member Function Documentation
AlreadyExists()
bool WorldScript::RefreshSpawnPickup::AlreadyExists () inline private
Definition at line 58 of file RefreshSpawnPickup.as.
References m_currPickup, Pickup::m_unit, and Pickup::m_visible.
Referenced by ClientExecute(), and ServerExecute().
         {
             if (m_currPickup is null)
                 return false;
             if (!m_currPickup.m_visible || m_currPickup.m_unit.IsDestroyed() || m_currPickup.m_unit.IsHidden())
             {
                 @m_currPickup = null;
                 return false;
             }
             return true;
         }
ClientExecute()
void WorldScript::RefreshSpawnPickup::ClientExecute (SValue@ val) inline private
Definition at line 84 of file RefreshSpawnPickup.as.
References AlreadyExists(), m_needNetSync, ProduceUnit(), and SpawnEffects().
         {
             if (m_needNetSync)
             {
                 if (AlreadyExists())
                     return;
                 ProduceUnit(0);
                 SpawnEffects();
             }
             else
             {
                 if (val is null)
                     return;
                 SpawnEffects();
             }
         }
Initialize()
void WorldScript::RefreshSpawnPickup::Initialize () inline private
Definition at line 28 of file RefreshSpawnPickup.as.
References IsNetsyncedExistance(), m_needNetSync, and UnitType.
         {
             m_needNetSync = !IsNetsyncedExistance(UnitType.GetNetSyncMode());
         }
ProduceUnit()
UnitPtr WorldScript::RefreshSpawnPickup::ProduceUnit (int id) inline private
Definition at line 33 of file RefreshSpawnPickup.as.
References g_scene, m_currPickup, Position, SpawnLayer, and UnitType.
Referenced by ClientExecute(), and ServerExecute().
         {
             UnitPtr u = UnitType.Produce(g_scene, Position, id);
             if (SpawnLayer != 0)
                 u.SetLayer(SpawnLayer);
             @m_currPickup = cast<Pickup>(u.GetScriptBehavior());
             return u;
         }
ServerExecute()
SValue WorldScript::RefreshSpawnPickup::ServerExecute () inline private
Definition at line 72 of file RefreshSpawnPickup.as.
References AlreadyExists(), ProduceUnit(), and SpawnEffects().
         {
             if (AlreadyExists())
                 return null;
             SValueBuilder sval;
             auto u = ProduceUnit(0);
             sval.PushInteger(u.GetId());
             SpawnEffects();
             return sval.Build();
         }
SpawnEffects()
void WorldScript::RefreshSpawnPickup::SpawnEffects () inline private
Definition at line 43 of file RefreshSpawnPickup.as.
References EffectLayer, PlayEffect(), PlaySound3D(), Position, SpawnSound, and xy().
Referenced by ClientExecute(), and ServerExecute().
         {
             if (SpawnEffect !is null)
             {
                 UnitPtr effectUnit = PlayEffect(SpawnEffect, xy(Position));
                 if (effectUnit.IsValid())
                 {
                     if (EffectLayer != 0)
                         effectUnit.SetLayer(EffectLayer);
                 }
             }
             if (SpawnSound !is null)
                 PlaySound3D(SpawnSound, Position);
         }
Member Data Documentation
EffectLayer
int WorldScript::RefreshSpawnPickup::EffectLayer private
Definition at line 18 of file RefreshSpawnPickup.as.
Referenced by SpawnEffects().
m_currPickup
Pickup WorldScript::RefreshSpawnPickup::m_currPickup private
Definition at line 25 of file RefreshSpawnPickup.as.
Referenced by AlreadyExists(), and ProduceUnit().
m_needNetSync
bool WorldScript::RefreshSpawnPickup::m_needNetSync private
Definition at line 24 of file RefreshSpawnPickup.as.
Referenced by ClientExecute(), and Initialize().
Position
vec3 WorldScript::RefreshSpawnPickup::Position private
Definition at line 6 of file RefreshSpawnPickup.as.
Referenced by ProduceUnit(), and SpawnEffects().
SpawnEffect
UnitScene WorldScript::RefreshSpawnPickup::SpawnEffect private
Definition at line 12 of file RefreshSpawnPickup.as.
SpawnLayer
int WorldScript::RefreshSpawnPickup::SpawnLayer private
Definition at line 15 of file RefreshSpawnPickup.as.
Referenced by ProduceUnit().
SpawnSound
SoundEvent WorldScript::RefreshSpawnPickup::SpawnSound private
Definition at line 21 of file RefreshSpawnPickup.as.
Referenced by SpawnEffects().
UnitType
UnitProducer WorldScript::RefreshSpawnPickup::UnitType private
Definition at line 9 of file RefreshSpawnPickup.as.
Referenced by Initialize(), and ProduceUnit().
The documentation for this class was generated from the following file:
scripts/WorldScript/RefreshSpawnPickup.as