HoHDocs: WorldScript::SetTopNumber Class Reference
WorldScript::SetTopNumber Class Reference
Private Member Functions
SValue ServerExecute ()
void ClientExecute (SValue@ sval)
Private Attributes
string ID
int Number
Detailed Description
Definition at line 4 of file SetTopNumber.as.
Member Function Documentation
ClientExecute()
void WorldScript::SetTopNumber::ClientExecute (SValue@ sval) inline private
Definition at line 22 of file SetTopNumber.as.
References ServerExecute().
         {
             ServerExecute();
         }
ServerExecute()
SValue WorldScript::SetTopNumber::ServerExecute () inline private
Definition at line 12 of file SetTopNumber.as.
References GetHUD(), ID, and Number.
Referenced by ClientExecute().
         {
             auto hud = GetHUD();
             if (hud is null)
                 return null;
             hud.SetTopNumberIcon(ID, Number);
             return null;
         }
Member Data Documentation
ID
string WorldScript::SetTopNumber::ID private
Definition at line 7 of file SetTopNumber.as.
Referenced by ServerExecute().
Number
int WorldScript::SetTopNumber::Number private
Definition at line 10 of file SetTopNumber.as.
Referenced by ServerExecute().
The documentation for this class was generated from the following file:
scripts/WorldScript/SetTopNumber.as