HoHDocs: WorldScript::SurvivalEnemyDropSpawn Class Reference
WorldScript::SurvivalEnemyDropSpawn Class Reference
Private Member Functions
bool IsExecutable (UnitPtr unit)
void Initialize ()
UnitPtr ProduceUnit (vec3 pos, int id)
void SpawnEffects (SurvivalEnemySpawnPoint@ spawn)
SValue ServerExecute ()
void ClientExecute (SValue@ val)
void OnDropped (UnitPtr unit)
Private Attributes
UnitProducer UnitType
string DropSceneName
float Height
float InitialFallSpeed
float MaxFallSpeed
float FallSpeedMultiplier
UnitFeed DropTrigger
uint NumberToSpawnMin
uint NumberToSpawnMax
uint NumberPerPlayer
uint NumberPerPlayerMax
uint MaxToSpawn
string SpawnPointFilter
UnitSource AllSpawned
bool m_needNetSync
Detailed Description
Definition at line 4 of file SurvivalEnemyDropSpawn.as.
Member Function Documentation
ClientExecute()
void WorldScript::SurvivalEnemyDropSpawn::ClientExecute (SValue@ val) inline private
Definition at line 162 of file SurvivalEnemyDropSpawn.as.
References g_scene, ProduceUnit(), and SpawnEffects().
         {
             if (val is null)
                 return;
             array<SValue@>@ arr = val.GetArray();
             for (uint i = 0; i < arr.length(); i += 3)
             {
                 int id = arr[i].GetInteger();
                 vec3 pos = arr[i + 1].GetVector3();
                 auto spawn = cast<SurvivalEnemySpawnPoint>(g_scene.GetUnit(arr[i + 2].GetInteger()).GetScriptBehavior());
                 ProduceUnit(pos, id);
                 SpawnEffects(spawn);
             }
         }
Initialize()
void WorldScript::SurvivalEnemyDropSpawn::Initialize () inline private
Definition at line 58 of file SurvivalEnemyDropSpawn.as.
References IsNetsyncedExistance(), m_needNetSync, and UnitType.
         {
             m_needNetSync = UnitType !is null && !IsNetsyncedExistance(UnitType.GetNetSyncMode());
         }
IsExecutable()
bool WorldScript::SurvivalEnemyDropSpawn::IsExecutable (UnitPtr unit) inline private
Definition at line 49 of file SurvivalEnemyDropSpawn.as.
References unit.
         {
             WorldScript@ script = WorldScript::GetWorldScript(unit);
             if (script is null)
                 return false;
             return script.IsExecutable();
         }
OnDropped()
void WorldScript::SurvivalEnemyDropSpawn::OnDropped (UnitPtr unit) inline private
Definition at line 179 of file SurvivalEnemyDropSpawn.as.
References AllSpawned, DropTrigger, and unit.
         {
             auto enemyBehavior = cast<CompositeActorBehavior>(unit.GetScriptBehavior());
             if (enemyBehavior !is null)
                 enemyBehavior.Configure(true, false, false);
             if (!Network::IsServer())
                 return;
             if (unit.IsValid())
                 AllSpawned.Add(unit);
             auto arr = DropTrigger.FetchAll();
             for (uint i = 0; i < arr.length(); i++)
             {
                 auto script = WorldScript::GetWorldScript(arr[i]);
                 if (script !is null)
                     script.Execute();
             }
         }
ProduceUnit()
UnitPtr WorldScript::SurvivalEnemyDropSpawn::ProduceUnit (vec3 pos, int id) inline private
Definition at line 63 of file SurvivalEnemyDropSpawn.as.
References DropSceneName, FallSpeedMultiplier, g_scene, Height, InitialFallSpeed, MaxFallSpeed, and UnitType.
Referenced by ClientExecute(), and ServerExecute().
         {
             auto prod = Resources::GetUnitProducer("system/drop_spawn.unit");
             if (prod is null)
                 return UnitPtr();
             if (UnitType is null)
             {
                 auto script = WorldScript::GetWorldScript(g_scene, this);
                 PrintError("Undefined UnitType in worldscript SpawnDropUnit with unit ID " + script.GetUnit().GetId());
                 return UnitPtr();
             }
             //TODO: Use UnitType's default scene if none is given?
             auto scene = UnitType.GetUnitScene(DropSceneName);
             if (scene is null)
             {
                 PrintError("Scene '" + DropSceneName + "' is not found!");
                 return UnitPtr();
             }
             UnitPtr u = prod.Produce(g_scene, pos, id);
             u.SetUnitScene(scene, true);
             auto dropper = cast<DropSpawnBehavior>(u.GetScriptBehavior());
             dropper.Initialize(this, UnitType, InitialFallSpeed, MaxFallSpeed, FallSpeedMultiplier, Height);
             return u;
         }
ServerExecute()
SValue WorldScript::SurvivalEnemyDropSpawn::ServerExecute () inline private
Definition at line 100 of file SurvivalEnemyDropSpawn.as.
References g_gameMode, g_players, g_scene, Height, m_needNetSync, MaxToSpawn, min, num, NumberPerPlayer, NumberPerPlayerMax, NumberToSpawnMax, NumberToSpawnMin, ProduceUnit(), SpawnEffects(), and SpawnPointFilter.
         {
             auto survivalMode = cast<Survival>(g_gameMode);
             if (survivalMode is null)
                 return null;
             SValueBuilder sval;
             if (m_needNetSync)
                 sval.PushArray();
             uint num = NumberToSpawnMin + randi(NumberToSpawnMax - NumberToSpawnMin + 1);
             for (uint i = 0; i < g_players.length(); i++)
             {
                 if (g_players[i].peer == 255)
                     continue;
                 int perPlayer = NumberPerPlayer;
                 if (NumberPerPlayerMax > NumberPerPlayer)
                     perPlayer += randi(NumberPerPlayerMax - NumberPerPlayer + 1);
                 num += perPlayer;
             }
             num = min(num, MaxToSpawn);
             array<WorldScript::SurvivalEnemySpawnPoint@> spawns;
             for (uint i = 0; i < survivalMode.m_enemySpawns.length(); i++)
             {
                 auto spawn = survivalMode.m_enemySpawns[i];
                 if (spawn.Filter == SpawnPointFilter && spawn.Enabled)
                     spawns.insertLast(spawn);
             }
             for (uint i = 0; i < num; i++)
             {
                 auto spawn = spawns[randi(spawns.length())];
                 auto spawnScript = WorldScript::GetWorldScript(g_scene, spawn);
                 vec3 pos = spawn.Position;
                 pos.z = Height;
                 UnitPtr u = ProduceUnit(pos, 0);
                 SpawnEffects(spawn);
                 if (!u.IsValid())
                     continue;
                 //AllSpawned.Add(u);
                 if (m_needNetSync)
                 {
                     sval.PushInteger(u.GetId());
                     sval.PushVector3(u.GetPosition());
                     sval.PushInteger(spawnScript.GetUnit().GetId());
                 }
             }
             if (m_needNetSync)
                 return sval.Build();
             return null;
         }
SpawnEffects()
void WorldScript::SurvivalEnemyDropSpawn::SpawnEffects (SurvivalEnemySpawnPoint@ spawn) inline private
Definition at line 92 of file SurvivalEnemyDropSpawn.as.
References PlayEffect(), PlaySound3D(), SurvivalEnemySpawnPoint::Position, SurvivalEnemySpawnPoint::SpawnEffect, SurvivalEnemySpawnPoint::SpawnSound, and xy().
Referenced by ClientExecute(), and ServerExecute().
         {
             if (spawn.SpawnEffect !is null)
                 PlayEffect(spawn.SpawnEffect, xy(spawn.Position));
             if (spawn.SpawnSound !is null)
                 PlaySound3D(spawn.SpawnSound, spawn.Position);
         }
Member Data Documentation
AllSpawned
UnitSource WorldScript::SurvivalEnemyDropSpawn::AllSpawned private
Definition at line 45 of file SurvivalEnemyDropSpawn.as.
Referenced by OnDropped().
DropSceneName
string WorldScript::SurvivalEnemyDropSpawn::DropSceneName private
Definition at line 10 of file SurvivalEnemyDropSpawn.as.
Referenced by ProduceUnit().
DropTrigger
UnitFeed WorldScript::SurvivalEnemyDropSpawn::DropTrigger private
Definition at line 25 of file SurvivalEnemyDropSpawn.as.
Referenced by OnDropped().
FallSpeedMultiplier
float WorldScript::SurvivalEnemyDropSpawn::FallSpeedMultiplier private
Definition at line 22 of file SurvivalEnemyDropSpawn.as.
Referenced by ProduceUnit().
Height
float WorldScript::SurvivalEnemyDropSpawn::Height private
Definition at line 13 of file SurvivalEnemyDropSpawn.as.
Referenced by ProduceUnit(), and ServerExecute().
InitialFallSpeed
float WorldScript::SurvivalEnemyDropSpawn::InitialFallSpeed private
Definition at line 16 of file SurvivalEnemyDropSpawn.as.
Referenced by ProduceUnit().
m_needNetSync
bool WorldScript::SurvivalEnemyDropSpawn::m_needNetSync private
Definition at line 47 of file SurvivalEnemyDropSpawn.as.
Referenced by Initialize(), and ServerExecute().
MaxFallSpeed
float WorldScript::SurvivalEnemyDropSpawn::MaxFallSpeed private
Definition at line 19 of file SurvivalEnemyDropSpawn.as.
Referenced by ProduceUnit().
MaxToSpawn
uint WorldScript::SurvivalEnemyDropSpawn::MaxToSpawn private
Definition at line 40 of file SurvivalEnemyDropSpawn.as.
Referenced by ServerExecute().
NumberPerPlayer
uint WorldScript::SurvivalEnemyDropSpawn::NumberPerPlayer private
Definition at line 34 of file SurvivalEnemyDropSpawn.as.
Referenced by ServerExecute().
NumberPerPlayerMax
uint WorldScript::SurvivalEnemyDropSpawn::NumberPerPlayerMax private
Definition at line 37 of file SurvivalEnemyDropSpawn.as.
Referenced by ServerExecute().
NumberToSpawnMax
uint WorldScript::SurvivalEnemyDropSpawn::NumberToSpawnMax private
Definition at line 31 of file SurvivalEnemyDropSpawn.as.
Referenced by ServerExecute().
NumberToSpawnMin
uint WorldScript::SurvivalEnemyDropSpawn::NumberToSpawnMin private
Definition at line 28 of file SurvivalEnemyDropSpawn.as.
Referenced by ServerExecute().
SpawnPointFilter
string WorldScript::SurvivalEnemyDropSpawn::SpawnPointFilter private
Definition at line 43 of file SurvivalEnemyDropSpawn.as.
Referenced by ServerExecute().
UnitType
UnitProducer WorldScript::SurvivalEnemyDropSpawn::UnitType private
Definition at line 7 of file SurvivalEnemyDropSpawn.as.
Referenced by Initialize(), and ProduceUnit().
The documentation for this class was generated from the following file:
scripts/WorldScript/SurvivalEnemyDropSpawn.as