HoHDocs: WorldScript::StoreOre Class Reference
WorldScript::StoreOre Class Reference
Private Member Functions
void Initialize ()
Player GetPlayer (UnitPtr unit)
void OnEnter (UnitPtr unit, vec2 pos, vec2 normal)
void OnExit (UnitPtr unit)
UnitPtr GetUseUnit ()
bool CanUse (PlayerBase@ player)
void OnFunc (Widget@ sender, string name) override
void Use (PlayerBase@ player)
UsableIcon GetIcon (Player@ player)
int UsePriority (IUsable@ other)
SValue Save ()
void Load (SValue@ data)
void NetUse (PlayerHusk@ player)
void DoLayout () override
void Update (int dt) override
void Draw (SpriteBatch &sb, int idt) override
void UpdateInput (vec2 origin, vec2 parentSz, vec3 mousePos) override
Private Attributes
bool Enabled
array< CollisionArea@> Areas
UnitFeed Unit
string UseScene
bool m_used
Detailed Description
Definition at line 4 of file StoreOre.as.
Member Function Documentation
CanUse()
bool WorldScript::StoreOre::CanUse (PlayerBase@ player) inline private
Definition at line 61 of file StoreOre.as.
References Enabled, PlayerBase::m_record, and m_used.
Referenced by GetIcon().
         {
             if (!Enabled)
                 return false;
             if (m_used && player.m_record.local)
                 return false;
             return true;
         }
DoLayout()
void WorldScript::StoreOre::DoLayout () inline override private
Definition at line 141 of file StoreOre.as.
 { }
Draw()
void WorldScript::StoreOre::Draw (SpriteBatch & sb, int idt) inline override private
Definition at line 143 of file StoreOre.as.
 { }
GetIcon()
UsableIcon WorldScript::StoreOre::GetIcon (Player@ player) inline private
Definition at line 118 of file StoreOre.as.
References CanUse(), Cross, and Generic.
         {
             if (!CanUse(player))
                 return Cross;
             return Generic;
         }
GetPlayer()
Player WorldScript::StoreOre::GetPlayer (UnitPtr unit) inline private
Definition at line 29 of file StoreOre.as.
References unit.
Referenced by OnEnter(), and OnExit().
         {
             if (!unit.IsValid())
                 return null;
             ref@ behavior = unit.GetScriptBehavior();
             if (behavior is null)
                 return null;
             return cast<Player>(behavior);
         }
GetUseUnit()
UnitPtr WorldScript::StoreOre::GetUseUnit () inline private
Definition at line 56 of file StoreOre.as.
References g_scene.
         {
             return WorldScript::GetWorldScript(g_scene, this).GetUnit();
         }
Initialize()
void WorldScript::StoreOre::Initialize () inline private
Definition at line 19 of file StoreOre.as.
References Areas, and m_used.
         {
             m_used = false;
             for (uint i = 0; i < Areas.length(); i++)
             {
                 Areas[i].AddOnEnter(this, "OnEnter");
                 Areas[i].AddOnExit(this, "OnExit");
             }
         }
Load()
void WorldScript::StoreOre::Load (SValue@ data) inline private
Definition at line 135 of file StoreOre.as.
References m_used.
         {
             m_used = data.GetBoolean();
         }
NetUse()
void WorldScript::StoreOre::NetUse (PlayerHusk@ player) inline private
Definition at line 140 of file StoreOre.as.
 { }
OnEnter()
void WorldScript::StoreOre::OnEnter (UnitPtr unit, vec2 pos, vec2 normal) inline private
Definition at line 42 of file StoreOre.as.
References Player::AddUsable(), GetPlayer(), and unit.
         {
             Player@ plr = GetPlayer(unit);
             if (plr !is null)
                 plr.AddUsable(this);
         }
OnExit()
void WorldScript::StoreOre::OnExit (UnitPtr unit) inline private
Definition at line 49 of file StoreOre.as.
References GetPlayer(), Player::RemoveUsable(), and unit.
         {
             Player@ plr = GetPlayer(unit);
             if (plr !is null)
                 plr.RemoveUsable(this);
         }
OnFunc()
void WorldScript::StoreOre::OnFunc (Widget@ sender, string name) inline override private
Definition at line 72 of file StoreOre.as.
References Stats::Add(), AddFloatingText(), ApplyTaxRate(), g_gameMode, GetLocalPlayer(), m_used, name, Pickup, SetUnitScene(), Unit, and UseScene.
         {
             auto player = GetLocalPlayer();
             auto town = cast<Campaign>(g_gameMode).m_townLocal;
             if (name == "q yes")
             {
                 m_used = true;
                 if (UseScene != "")
                 {
                     auto units = Unit.FetchAll();
                     for (uint i = 0; i < units.length(); i++)
                         units[i].SetUnitScene(UseScene, true);
                 }
                 int takeOre = player.m_record.runOre;
                 player.m_record.runOre = 0;
                 town.m_ore += takeOre;
                 Stats::Add("ores-stored", takeOre, player.m_record);
                 AddFloatingText(FloatingTextType::Pickup, Resources::GetString(".misc.store.ore", { { "num", takeOre } }), player.m_unit.GetPosition());
                 int takeGold = ApplyTaxRate(town.m_gold, player.m_record.runGold);
                 player.m_record.runGold = 0;
                 town.m_gold += takeGold;
                 Stats::Add("gold-stored", takeGold, player.m_record);
                 AddFloatingText(FloatingTextType::Pickup, Resources::GetString(".misc.store.gold", { { "num", takeGold } }), player.m_unit.GetPosition());
                 Stats::Add("elevator-used", 1, player.m_record);
             }
         }
Save()
SValue WorldScript::StoreOre::Save () inline private
Definition at line 128 of file StoreOre.as.
References m_used.
         {
             SValueBuilder sval;
             sval.PushBoolean(m_used);
             return sval.Build();
         }
Update()
void WorldScript::StoreOre::Update (int dt) inline override private
Definition at line 142 of file StoreOre.as.
 { }
UpdateInput()
void WorldScript::StoreOre::UpdateInput (vec2 origin, vec2 parentSz, vec3 mousePos) inline override private
Definition at line 144 of file StoreOre.as.
 { }
Use()
void WorldScript::StoreOre::Use (PlayerBase@ player) inline private
Definition at line 106 of file StoreOre.as.
References ApplyTaxRate(), g_gameMode, PlayerBase::m_record, max, and AGameMode::ShowDialog().
         {
             int oreTake = player.m_record.runOre;
             int goldTake = ApplyTaxRate(cast<Campaign>(g_gameMode).m_townLocal.m_gold, player.m_record.runGold);
             float taxRate = (1.0f - goldTake / float(max(1, player.m_record.runGold))) * 100.0f;
             g_gameMode.ShowDialog("q",
                 Resources::GetString(".misc.elevator.question", { { "ore", oreTake }, { "gold", goldTake }, { "tax", taxRate } }),
                 Resources::GetString(".misc.yes"),
                 Resources::GetString(".misc.no"),
                 this);
         }
UsePriority()
int WorldScript::StoreOre::UsePriority (IUsable@ other) inline private
Definition at line 126 of file StoreOre.as.
 { return 0; }
Member Data Documentation
Areas
array<CollisionArea@> WorldScript::StoreOre::Areas private
Definition at line 9 of file StoreOre.as.
Referenced by Initialize().
Enabled
bool WorldScript::StoreOre::Enabled private
Definition at line 6 of file StoreOre.as.
Referenced by CanUse().
m_used
bool WorldScript::StoreOre::m_used private
Definition at line 17 of file StoreOre.as.
Referenced by CanUse(), Initialize(), Load(), OnFunc(), and Save().
Unit
UnitFeed WorldScript::StoreOre::Unit private
Definition at line 12 of file StoreOre.as.
Referenced by OnFunc().
UseScene
string WorldScript::StoreOre::UseScene private
Definition at line 14 of file StoreOre.as.
Referenced by OnFunc().
The documentation for this class was generated from the following file:
scripts/WorldScript/StoreOre.as