HoHDocs: WorldScript::SpawnUnitWithEffect Class Reference
WorldScript::SpawnUnitWithEffect Class Reference
Private Member Functions
bool IsExecutable (UnitPtr unit)
void Initialize ()
void ProduceUnitEffects (vec3 pos)
UnitPtr ProduceUnit (int id)
SValue ServerExecute ()
void ClientExecute (SValue@ val)
Private Attributes
vec3 Position
UnitProducer UnitType
string SceneName
UnitScene SpawnEffect
int SpawnLayer
UnitFeed EffectFinishTrigger
int EffectLayer
SoundEvent SpawnSound
bool AggroEnemy
UnitSource LastSpawned
UnitSource AllSpawned
bool m_needNetSync
Detailed Description
Definition at line 4 of file SpawnUnitWithEffect.as.
Member Function Documentation
ClientExecute()
void WorldScript::SpawnUnitWithEffect::ClientExecute (SValue@ val) inline private
Definition at line 115 of file SpawnUnitWithEffect.as.
References Position, ProduceUnit(), and ProduceUnitEffects().
         {
             if (val is null)
                 ProduceUnitEffects(Position);
             else
                 ProduceUnit(val.GetInteger());
         }
Initialize()
void WorldScript::SpawnUnitWithEffect::Initialize () inline private
Definition at line 48 of file SpawnUnitWithEffect.as.
References IsNetsyncedExistance(), m_needNetSync, and UnitType.
         {
             m_needNetSync = !IsNetsyncedExistance(UnitType.GetNetSyncMode());
         }
IsExecutable()
bool WorldScript::SpawnUnitWithEffect::IsExecutable (UnitPtr unit) inline private
Definition at line 39 of file SpawnUnitWithEffect.as.
References unit.
         {
             WorldScript@ script = WorldScript::GetWorldScript(unit);
             if (script is null)
                 return false;
             return script.IsExecutable();
         }
ProduceUnit()
UnitPtr WorldScript::SpawnUnitWithEffect::ProduceUnit (int id) inline private
Definition at line 78 of file SpawnUnitWithEffect.as.
References AggroEnemy, g_scene, Position, ProduceUnitEffects(), SceneName, SpawnLayer, and UnitType.
Referenced by ClientExecute(), and ServerExecute().
         {
             vec3 pos = Position;
             UnitPtr u = UnitType.Produce(g_scene, pos, id);
             if (SceneName != "")
                 u.SetUnitScene(SceneName, true);
             if (SpawnLayer != 0)
                 u.SetLayer(SpawnLayer);
             if (AggroEnemy)
             {
                 auto enemyBehavior = cast<CompositeActorBehavior>(u.GetScriptBehavior());
                 if (enemyBehavior !is null)
                     enemyBehavior.Configure(true, false, false);
             }
             ProduceUnitEffects(pos);
             return u;
         }
ProduceUnitEffects()
void WorldScript::SpawnUnitWithEffect::ProduceUnitEffects (vec3 pos) inline private
Definition at line 53 of file SpawnUnitWithEffect.as.
References EffectFinishTrigger, EffectLayer, g_scene, PlayEffect(), PlaySound3D(), SpawnSound, and xy().
Referenced by ClientExecute(), and ProduceUnit().
         {
             if (SpawnEffect !is null)
             {
                 UnitPtr effectUnit = PlayEffect(SpawnEffect, xy(pos));
                 if (effectUnit.IsValid())
                 {
                     if (EffectLayer != 0)
                         effectUnit.SetLayer(EffectLayer);
                     if (Network::IsServer())
                     {
                         auto fx = cast<EffectBehavior>(effectUnit.GetScriptBehavior());
                         auto triggerArr = EffectFinishTrigger.FetchAll();
                         for (uint i = 0; i < triggerArr.length(); i++)
{
                             auto callbackScript = WorldScript::GetWorldScript(g_scene, triggerArr[i].GetScriptBehavior());
                             fx.m_finishTriggers.insertLast(callbackScript);
                         }
                     }
                 }
             }
             if (SpawnSound !is null)
                 PlaySound3D(SpawnSound, pos);
         }
ServerExecute()
SValue WorldScript::SpawnUnitWithEffect::ServerExecute () inline private
Definition at line 100 of file SpawnUnitWithEffect.as.
References AllSpawned, LastSpawned, m_needNetSync, and ProduceUnit().
         {
             UnitPtr u = ProduceUnit(0);
             LastSpawned.Replace(u);
             AllSpawned.Add(u);
             if (!m_needNetSync)
                 return null;
             SValueBuilder sval;
             sval.PushInteger(u.GetId());
             return sval.Build();
         }
Member Data Documentation
AggroEnemy
bool WorldScript::SpawnUnitWithEffect::AggroEnemy private
Definition at line 30 of file SpawnUnitWithEffect.as.
Referenced by ProduceUnit().
AllSpawned
UnitSource WorldScript::SpawnUnitWithEffect::AllSpawned private
Definition at line 34 of file SpawnUnitWithEffect.as.
Referenced by ServerExecute().
EffectFinishTrigger
UnitFeed WorldScript::SpawnUnitWithEffect::EffectFinishTrigger private
Definition at line 21 of file SpawnUnitWithEffect.as.
Referenced by ProduceUnitEffects().
EffectLayer
int WorldScript::SpawnUnitWithEffect::EffectLayer private
Definition at line 24 of file SpawnUnitWithEffect.as.
Referenced by ProduceUnitEffects().
LastSpawned
UnitSource WorldScript::SpawnUnitWithEffect::LastSpawned private
Definition at line 33 of file SpawnUnitWithEffect.as.
Referenced by ServerExecute().
m_needNetSync
bool WorldScript::SpawnUnitWithEffect::m_needNetSync private
Definition at line 37 of file SpawnUnitWithEffect.as.
Referenced by Initialize(), and ServerExecute().
Position
vec3 WorldScript::SpawnUnitWithEffect::Position private
Definition at line 6 of file SpawnUnitWithEffect.as.
Referenced by ClientExecute(), and ProduceUnit().
SceneName
string WorldScript::SpawnUnitWithEffect::SceneName private
Definition at line 12 of file SpawnUnitWithEffect.as.
Referenced by ProduceUnit().
SpawnEffect
UnitScene WorldScript::SpawnUnitWithEffect::SpawnEffect private
Definition at line 15 of file SpawnUnitWithEffect.as.
SpawnLayer
int WorldScript::SpawnUnitWithEffect::SpawnLayer private
Definition at line 18 of file SpawnUnitWithEffect.as.
Referenced by ProduceUnit().
SpawnSound
SoundEvent WorldScript::SpawnUnitWithEffect::SpawnSound private
Definition at line 27 of file SpawnUnitWithEffect.as.
Referenced by ProduceUnitEffects().
UnitType
UnitProducer WorldScript::SpawnUnitWithEffect::UnitType private
Definition at line 9 of file SpawnUnitWithEffect.as.
Referenced by Initialize(), and ProduceUnit().
The documentation for this class was generated from the following file:
scripts/WorldScript/SpawnUnitWithEffect.as