HoHDocs: WorldScript::UnitCallbackList Class Reference
WorldScript::UnitCallbackList Class Reference
Private Member Functions
void RegisterEventCallback (UnitPtr unit, UnitEventType event, ref script, string func)
void UnregisterEventCallback (UnitPtr unit)
Private Attributes
array< UnitPtr > m_units
array< UnitEventCallbackId > m_callbacks
Detailed Description
Definition at line 3 of file UnitCallbackList.as.
Member Function Documentation
RegisterEventCallback()
void WorldScript::UnitCallbackList::RegisterEventCallback (UnitPtr unit, UnitEventType event, ref script, string func) inline private
Definition at line 8 of file UnitCallbackList.as.
References m_callbacks, m_units, and unit.
Referenced by WorldScript::UnitDestroyedTrigger::OnChanged(), WorldScript::UnitEventTrigger::OnChanged(), WorldScript::UnitDamagedTrigger::OnChanged(), and WorldScript::ActorHealthTrigger::OnChanged().
         {
             auto clbk = unit.RegisterEventCallback(event, script, func);
             m_units.insertLast(unit);
             m_callbacks.insertLast(clbk);
         }
UnregisterEventCallback()
void WorldScript::UnitCallbackList::UnregisterEventCallback (UnitPtr unit) inline private
Definition at line 15 of file UnitCallbackList.as.
References m_callbacks, m_units, and unit.
Referenced by WorldScript::UnitDestroyedTrigger::OnChanged(), WorldScript::UnitEventTrigger::OnChanged(), WorldScript::UnitDamagedTrigger::OnChanged(), and WorldScript::ActorHealthTrigger::OnChanged().
         {
             for (uint i = 0; i < m_units.length(); i++)
             {
                 if (m_units[i] != unit)
                     continue;
                 m_units[i].UnregisterEventCallback(m_callbacks[i]);
                 m_units.removeAt(i);
                 m_callbacks.removeAt(i);
                 return;
             }
         }
Member Data Documentation
m_callbacks
array<UnitEventCallbackId> WorldScript::UnitCallbackList::m_callbacks private
Definition at line 6 of file UnitCallbackList.as.
Referenced by RegisterEventCallback(), and UnregisterEventCallback().
m_units
array<UnitPtr> WorldScript::UnitCallbackList::m_units private
Definition at line 5 of file UnitCallbackList.as.
Referenced by RegisterEventCallback(), and UnregisterEventCallback().
The documentation for this class was generated from the following file:
scripts/WorldScript/UnitCallbackList.as