HoHDocs: WorldScript::StopAnnounceText Class Reference
WorldScript::StopAnnounceText Class Reference
Private Member Functions
bool IsValid (UnitPtr unit)
SValue ServerExecute ()
void ClientExecute (SValue@ val)
Private Attributes
UnitFeed AnnounceScript
int FadeTime
Detailed Description
Definition at line 4 of file StopAnnounceText.as.
Member Function Documentation
ClientExecute()
void WorldScript::StopAnnounceText::ClientExecute (SValue@ val) inline private
Definition at line 23 of file StopAnnounceText.as.
References AnnounceScript, FadeTime, GetHUD(), unit, and WidgetVec4Animation().
Referenced by ServerExecute().
         {
             auto unit = AnnounceScript.FetchFirst();
             if (!unit.IsValid())
                 return;
             auto script = cast<AnnounceText>(unit.GetScriptBehavior());
             if (script is null)
                 return;
             auto hud = GetHUD();
             if (hud is null) {
                 return;
             }
             auto w = cast<TextWidget>(hud.m_widget.GetWidgetById("announce"));
             if (!w.m_visible || hud.m_currAnnounce !is script)
                 return;
             auto col = script.Color;
             auto colTransparent = vec4(col.x, col.y, col.x, 0);
             w.CancelAnimations();
             w.Animate(WidgetVec4Animation("color", col, colTransparent, FadeTime));
             w.Animate(WidgetBoolAnimation("visible", false, FadeTime));
         }
IsValid()
bool WorldScript::StopAnnounceText::IsValid (UnitPtr unit) inline private
Definition at line 12 of file StopAnnounceText.as.
References unit.
         {
             return cast<AnnounceText>(unit.GetScriptBehavior()) !is null;
         }
ServerExecute()
SValue WorldScript::StopAnnounceText::ServerExecute () inline private
Definition at line 17 of file StopAnnounceText.as.
References ClientExecute().
         {
             ClientExecute(null);
             return null;
         }
Member Data Documentation
AnnounceScript
UnitFeed WorldScript::StopAnnounceText::AnnounceScript private
Definition at line 7 of file StopAnnounceText.as.
Referenced by ClientExecute().
FadeTime
int WorldScript::StopAnnounceText::FadeTime private
Definition at line 10 of file StopAnnounceText.as.
Referenced by ClientExecute().
The documentation for this class was generated from the following file:
scripts/WorldScript/StopAnnounceText.as