HoHDocs: WorldScript::SpawnUnit Class Reference
WorldScript::SpawnUnit Class Reference
Private Member Functions
void Initialize ()
SValue ServerExecute ()
Private Attributes
vec3 Position
UnitSource LastSpawned
UnitSource AllSpawned
Detailed Description
Definition at line 4 of file SpawnUnit.as.
Member Function Documentation
Initialize()
void WorldScript::SpawnUnit::Initialize () inline private
Definition at line 12 of file SpawnUnit.as.
         {
             Initialize(UnitPtr(), null);
         }
ServerExecute()
SValue WorldScript::SpawnUnit::ServerExecute () inline private
Definition at line 17 of file SpawnUnit.as.
References AllSpawned, SpawnUnitBase::CalcJitter(), LastSpawned, Position, SpawnUnitBase::SpawnUnit(), and xy().
         {
             UnitPtr u = SpawnUnit(xy(Position) + CalcJitter(), null, 1.0);
             if (u.IsValid())
             {
                 LastSpawned.Replace(u);
                 AllSpawned.Add(u);
             }
             return null;
         }
Member Data Documentation
AllSpawned
UnitSource WorldScript::SpawnUnit::AllSpawned private
Definition at line 9 of file SpawnUnit.as.
Referenced by ServerExecute().
LastSpawned
UnitSource WorldScript::SpawnUnit::LastSpawned private
Definition at line 8 of file SpawnUnit.as.
Referenced by ServerExecute().
Position
vec3 WorldScript::SpawnUnit::Position private
Definition at line 6 of file SpawnUnit.as.
Referenced by ServerExecute().
The documentation for this class was generated from the following file:
scripts/WorldScript/SpawnUnit.as