HoHDocs: WorldScript::SurvivalEnemySpawn Class Reference
WorldScript::SurvivalEnemySpawn Class Reference
Private Member Functions
void Initialize ()
UnitPtr ProduceUnit (vec3 pos, int id)
void SpawnEffects (SurvivalEnemySpawnPoint@ spawn)
SValue ServerExecute ()
void ClientExecute (SValue@ val)
Private Attributes
UnitProducer UnitType
uint NumberToSpawnMin
uint NumberToSpawnMax
uint NumberPerPlayer
uint NumberPerPlayerMax
uint MaxToSpawn
string SpawnPointFilter
UnitSource AllSpawned
bool m_needNetSync
Detailed Description
Definition at line 4 of file SurvivalEnemySpawn.as.
Member Function Documentation
ClientExecute()
void WorldScript::SurvivalEnemySpawn::ClientExecute (SValue@ val) inline private
Definition at line 124 of file SurvivalEnemySpawn.as.
References g_scene, ProduceUnit(), and SpawnEffects().
         {
             if (val is null)
                 return;
             array<SValue@>@ arr = val.GetArray();
             for (uint i = 0; i < arr.length(); i += 2)
             {
                 int id = arr[i].GetInteger();
                 auto spawn = cast<SurvivalEnemySpawnPoint>(g_scene.GetUnit(arr[i + 1].GetInteger()).GetScriptBehavior());
                 ProduceUnit(spawn.Position, id);
                 SpawnEffects(spawn);
             }
         }
Initialize()
void WorldScript::SurvivalEnemySpawn::Initialize () inline private
Definition at line 31 of file SurvivalEnemySpawn.as.
References IsNetsyncedExistance(), m_needNetSync, and UnitType.
         {
             m_needNetSync = UnitType !is null && !IsNetsyncedExistance(UnitType.GetNetSyncMode());
         }
ProduceUnit()
UnitPtr WorldScript::SurvivalEnemySpawn::ProduceUnit (vec3 pos, int id) inline private
Definition at line 36 of file SurvivalEnemySpawn.as.
References g_scene, and UnitType.
Referenced by ClientExecute(), and ServerExecute().
         {
             if (UnitType is null)
             {
                 auto script = WorldScript::GetWorldScript(g_scene, this);
                 PrintError("Undefined UnitType in unit ID " + script.GetUnit().GetId());
                 return UnitPtr();
             }
             pos.x += randf() / 100.0;
             pos.y += randf() / 100.0;
             UnitPtr ret = UnitType.Produce(g_scene, pos, id);
             auto actor = cast<CompositeActorBehavior>(ret.GetScriptBehavior());
             if (actor !is null)
                 actor.Configure(true, false, false);
             return ret;
         }
ServerExecute()
SValue WorldScript::SurvivalEnemySpawn::ServerExecute () inline private
Definition at line 65 of file SurvivalEnemySpawn.as.
References AllSpawned, g_gameMode, g_players, g_scene, m_needNetSync, MaxToSpawn, min, num, NumberPerPlayer, NumberPerPlayerMax, NumberToSpawnMax, NumberToSpawnMin, ProduceUnit(), SpawnEffects(), and SpawnPointFilter.
         {
             auto survivalMode = cast<Survival>(g_gameMode);
             if (survivalMode is null)
                 return null;
             SValueBuilder sval;
             if (m_needNetSync)
                 sval.PushArray();
             uint num = NumberToSpawnMin + randi(NumberToSpawnMax - NumberToSpawnMin + 1);
             for (uint i = 0; i < g_players.length(); i++)
             {
                 if (g_players[i].peer == 255)
                     continue;
                 int perPlayer = NumberPerPlayer;
                 if (NumberPerPlayerMax > NumberPerPlayer)
                     perPlayer += randi(NumberPerPlayerMax - NumberPerPlayer + 1);
                 num += perPlayer;
             }
             num = min(num, MaxToSpawn);
             array<WorldScript::SurvivalEnemySpawnPoint@> spawns;
             for (uint i = 0; i < survivalMode.m_enemySpawns.length(); i++)
             {
                 auto spawn = survivalMode.m_enemySpawns[i];
                 if (spawn.Filter == SpawnPointFilter && spawn.Enabled)
                     spawns.insertLast(spawn);
             }
             for (uint i = 0; i < num; i++)
             {
                 auto spawn = spawns[randi(spawns.length())];
                 auto spawnScript = WorldScript::GetWorldScript(g_scene, spawn);
                 vec3 pos = spawn.Position;
                 UnitPtr u = ProduceUnit(pos, 0);
                 SpawnEffects(spawn);
                 if (!u.IsValid())
                     continue;
                 AllSpawned.Add(u);
                 if (m_needNetSync)
                 {
                     sval.PushInteger(u.GetId());
                     sval.PushInteger(spawnScript.GetUnit().GetId());
                 }
             }
             if (m_needNetSync)
                 return sval.Build();
             return null;
         }
SpawnEffects()
void WorldScript::SurvivalEnemySpawn::SpawnEffects (SurvivalEnemySpawnPoint@ spawn) inline private
Definition at line 57 of file SurvivalEnemySpawn.as.
References PlayEffect(), PlaySound3D(), SurvivalEnemySpawnPoint::Position, SurvivalEnemySpawnPoint::SpawnEffect, SurvivalEnemySpawnPoint::SpawnSound, and xy().
Referenced by ClientExecute(), and ServerExecute().
         {
             if (spawn.SpawnEffect !is null)
                 PlayEffect(spawn.SpawnEffect, xy(spawn.Position));
             if (spawn.SpawnSound !is null)
                 PlaySound3D(spawn.SpawnSound, spawn.Position);
         }
Member Data Documentation
AllSpawned
UnitSource WorldScript::SurvivalEnemySpawn::AllSpawned private
Definition at line 27 of file SurvivalEnemySpawn.as.
Referenced by ServerExecute().
m_needNetSync
bool WorldScript::SurvivalEnemySpawn::m_needNetSync private
Definition at line 29 of file SurvivalEnemySpawn.as.
Referenced by Initialize(), and ServerExecute().
MaxToSpawn
uint WorldScript::SurvivalEnemySpawn::MaxToSpawn private
Definition at line 22 of file SurvivalEnemySpawn.as.
Referenced by ServerExecute().
NumberPerPlayer
uint WorldScript::SurvivalEnemySpawn::NumberPerPlayer private
Definition at line 16 of file SurvivalEnemySpawn.as.
Referenced by ServerExecute().
NumberPerPlayerMax
uint WorldScript::SurvivalEnemySpawn::NumberPerPlayerMax private
Definition at line 19 of file SurvivalEnemySpawn.as.
Referenced by ServerExecute().
NumberToSpawnMax
uint WorldScript::SurvivalEnemySpawn::NumberToSpawnMax private
Definition at line 13 of file SurvivalEnemySpawn.as.
Referenced by ServerExecute().
NumberToSpawnMin
uint WorldScript::SurvivalEnemySpawn::NumberToSpawnMin private
Definition at line 10 of file SurvivalEnemySpawn.as.
Referenced by ServerExecute().
SpawnPointFilter
string WorldScript::SurvivalEnemySpawn::SpawnPointFilter private
Definition at line 25 of file SurvivalEnemySpawn.as.
Referenced by ServerExecute().
UnitType
UnitProducer WorldScript::SurvivalEnemySpawn::UnitType private
Definition at line 7 of file SurvivalEnemySpawn.as.
Referenced by Initialize(), and ProduceUnit().
The documentation for this class was generated from the following file:
scripts/WorldScript/SurvivalEnemySpawn.as