HoHDocs: WorldScript::ToggleImmortality Class Reference
WorldScript::ToggleImmortality Class Reference
Private Member Functions
bool IsValid (UnitPtr unit)
SValue ServerExecute ()
void ClientExecute (SValue@ val)
Private Attributes
ToggleState State
UnitFeed Units
Detailed Description
Definition at line 4 of file ToggleImmortality.as.
Member Function Documentation
ClientExecute()
void WorldScript::ToggleImmortality::ClientExecute (SValue@ val) inline private
Definition at line 44 of file ToggleImmortality.as.
References ServerExecute().
         {
             ServerExecute();
         }
IsValid()
bool WorldScript::ToggleImmortality::IsValid (UnitPtr unit) inline private
Definition at line 12 of file ToggleImmortality.as.
References unit.
         {
             return cast<Actor>(unit.GetScriptBehavior()) !is null;
         }
ServerExecute()
SValue WorldScript::ToggleImmortality::ServerExecute () inline private
Definition at line 17 of file ToggleImmortality.as.
References Disable, Enable, SetImmortal(), State, Skills::Toggle, and Units.
Referenced by ClientExecute().
         {
             auto units = Units.FetchAll();
             switch(State)
             {
             case ToggleState::Enable:
                 for (uint i = 0; i < units.length(); i++)
                     cast<Actor>(units[i].GetScriptBehavior()).SetImmortal(true);
                 break;
             case ToggleState::Disable:
                 for (uint i = 0; i < units.length(); i++)
                     cast<Actor>(units[i].GetScriptBehavior()).SetImmortal(false);
                 break;
             case ToggleState::Toggle:
                 for (uint i = 0; i < units.length(); i++)
                 {
                     auto actor = cast<Actor>(units[i].GetScriptBehavior());
                     actor.SetImmortal(!actor.IsImmortal(true));
                 }
                 break;
             }
             return null;
         }
Member Data Documentation
State
ToggleState WorldScript::ToggleImmortality::State private
Definition at line 7 of file ToggleImmortality.as.
Referenced by ServerExecute().
Units
UnitFeed WorldScript::ToggleImmortality::Units private
Definition at line 10 of file ToggleImmortality.as.
Referenced by ServerExecute().
The documentation for this class was generated from the following file:
scripts/WorldScript/ToggleImmortality.as