HoHDocs: WorldScript::Variable Class Reference
WorldScript::Variable Class Reference
Private Member Functions
int GetValue ()
void SetValue (int v)
SValue Save ()
void Load (SValue@ data)
void DebugDraw (vec2 pos, SpriteBatch &sb)
Private Attributes
int Value
Detailed Description
Definition at line 4 of file Variable.as.
Member Function Documentation
DebugDraw()
void WorldScript::Variable::DebugDraw (vec2 pos, SpriteBatch & sb) inline private
Definition at line 24 of file Variable.as.
References GetValue(), and text.
         {
             auto sysFont = Resources::GetBitmapFont("system/system.fnt");
             auto text = sysFont.BuildText("" + GetValue());
             sb.DrawString(pos - vec2(text.GetWidth(), text.GetHeight() - 1) / 2, text);
         }
GetValue()
int WorldScript::Variable::GetValue () inline private
Definition at line 9 of file Variable.as.
References Value.
Referenced by DebugDraw(), Save(), and WorldScript::LogText::ServerExecute().
 { return Value; }
Load()
void WorldScript::Variable::Load (SValue@ data) inline private
Definition at line 19 of file Variable.as.
References SetValue().
         {
             SetValue(data.GetInteger());
         }
Save()
SValue WorldScript::Variable::Save () inline private
Definition at line 12 of file Variable.as.
References GetValue().
         {
             SValueBuilder sval;
             sval.PushInteger(GetValue());
             return sval.Build();
         }
SetValue()
void WorldScript::Variable::SetValue (int v) inline private
Definition at line 10 of file Variable.as.
References Value.
Referenced by Load().
 { Value = v; }
Member Data Documentation
Value
int WorldScript::Variable::Value private
Definition at line 7 of file Variable.as.
Referenced by GetValue(), WorldScript::GlobalVariable::GetValue(), and SetValue().
The documentation for this class was generated from the following file:
scripts/WorldScript/Variable.as