HoHDocs: ScenarioInfo Class Reference
ScenarioInfo Class Reference
Private Member Functions
TempTexture2D LoadLogos ()
string GetID ()
string GetTag ()
string GetName ()
string GetDescription ()
bool Multiplayer ()
bool Official ()
bool Packaged ()
bool Workshop ()
array< ScenarioStartLevel@> GetStartLevels ()
array< ScenarioModification@> GetModifications ()
int MinPlayers ()
int MaxPlayers ()
Detailed Description
Definition at line 107 of file engine.as.
Member Function Documentation
GetDescription()
string ScenarioInfo::GetDescription () inline private
Definition at line 113 of file engine.as.
 { return ""; }
GetID()
string ScenarioInfo::GetID () inline private
Definition at line 110 of file engine.as.
Referenced by Menu::SetStartScenario().
 { return ""; }
GetModifications()
array<ScenarioModification@> ScenarioInfo::GetModifications () inline private
Definition at line 119 of file engine.as.
 { return null; }
GetName()
string ScenarioInfo::GetName () inline private
Definition at line 112 of file engine.as.
Referenced by Menu::SetStartScenario().
 { return ""; }
GetStartLevels()
array<ScenarioStartLevel@> ScenarioInfo::GetStartLevels () inline private
Definition at line 118 of file engine.as.
Referenced by Menu::SetStartScenario().
 { return null; }
GetTag()
string ScenarioInfo::GetTag () inline private
Definition at line 111 of file engine.as.
 { return ""; }
LoadLogos()
TempTexture2D ScenarioInfo::LoadLogos () inline private
Definition at line 109 of file engine.as.
Referenced by Menu::SetStartScenario().
 { return null; }
MaxPlayers()
int ScenarioInfo::MaxPlayers () inline private
Definition at line 121 of file engine.as.
 { return -1; }
MinPlayers()
int ScenarioInfo::MinPlayers () inline private
Definition at line 120 of file engine.as.
 { return -1; }
Multiplayer()
bool ScenarioInfo::Multiplayer () inline private
Definition at line 114 of file engine.as.
 { return false; }
Official()
bool ScenarioInfo::Official () inline private
Definition at line 115 of file engine.as.
 { return false; }
Packaged()
bool ScenarioInfo::Packaged () inline private
Definition at line 116 of file engine.as.
 { return false; }
Workshop()
bool ScenarioInfo::Workshop () inline private
Definition at line 117 of file engine.as.
 { return false; }
The documentation for this class was generated from the following file:
system/engine.as