HoHDocs: scripts/Behaviors/Effects/Damage.as File Reference
Damage.as File Reference
Classes
class Damage
Functions
Damage IEffect BogusDamage (UnitPtr unit, SValue &params)
Damage (UnitPtr unit, SValue &params)
void SetWeaponInformation (uint weapon)
int DoDamage (IDamageTaker@ target, DamageInfo di, vec2 pos, vec2 dir)
bool Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
bool CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
Variables
int m_physicalDmg
int m_magicalDmg
bool m_canKill
bool m_melee
bool m_trueStrike
uint m_weaponInfo
vec2 m_armorMul
CleaveInfo m_cleave
Function Documentation
Apply()
bool BogusDamage::Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
Definition at line 68 of file Damage.as.
                   : Damage
 {
     BogusDamage(UnitPtr unit, SValue& params)
     {
         super(unit, params);
     }
     bool CanApply(Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
     {
         if (!Damage::CanApply(owner, target, pos, dir, intensity))
             return false;
         if (cast<Actor>(target.GetScriptBehavior()) !is null)
BogusDamage()
Damage IEffect BogusDamage (UnitPtr unit, SValue & params)
Definition at line 79 of file Damage.as.
References unit.
     {
         super(unit, params);
     }
CanApply()
bool BogusDamage::CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
Definition at line 91 of file Damage.as.
Damage()
BogusDamage::Damage (UnitPtr unit, SValue & params)
Definition at line 40 of file Damage.as.
References Damage::CanApply(), damage_round(), DamageInfo(), FilterHuskDamage(), Actor::GetDamageMulTarget(), Damage::m_armorMul, Damage::m_canKill, Damage::m_cleave, Damage::m_magicalDmg, Damage::m_melee, Damage::m_physicalDmg, Damage::m_trueStrike, and Damage::m_weaponInfo.
     {
         target.TriggerCallbacks(UnitEventType::Damaged);
         if (!CanApply(owner, target, pos, dir, intensity))
             return false;
         if (!FilterHuskDamage(owner, target, husk))
             return false;
         float dmgMul = owner is null ? 1.0f : owner.GetDamageMulTarget(m_melee, target);
         IDamageTaker@ dmgTaker = cast<IDamageTaker>(target.GetScriptBehavior());
         dmgMul *= intensity;
         auto dmgInfo = DamageInfo(owner, damage_round(float(m_physicalDmg) * dmgMul), damage_round(float(m_magicalDmg) * dmgMul), m_melee, m_canKill, m_weaponInfo);
         dmgInfo.ArmorMul = m_armorMul;
         dmgInfo.TrueStrike = m_trueStrike;
DoDamage()
int BogusDamage::DoDamage (IDamageTaker@ target, DamageInfo di, vec2 pos, vec2 dir)
Definition at line 63 of file Damage.as.
     {
         if (!target.IsValid())
             return false;
SetWeaponInformation()
void BogusDamage::SetWeaponInformation (uint weapon)
Definition at line 58 of file Damage.as.
     {
Variable Documentation
m_armorMul
vec2 m_armorMul
Definition at line 37 of file Damage.as.
m_canKill
bool m_canKill
Definition at line 33 of file Damage.as.
m_cleave
CleaveInfo m_cleave
Definition at line 38 of file Damage.as.
m_magicalDmg
int m_magicalDmg
Definition at line 32 of file Damage.as.
m_melee
bool m_melee
Definition at line 34 of file Damage.as.
m_physicalDmg
int m_physicalDmg
Definition at line 31 of file Damage.as.
m_trueStrike
bool m_trueStrike
Definition at line 35 of file Damage.as.
m_weaponInfo
uint m_weaponInfo
Definition at line 36 of file Damage.as.