HoHDocs: scripts/Behaviors/Actors/Player/Player.as File Reference
Player.as File Reference
Classes
class Player
Enumerations
enum AttackRangeType { Melee, Ranged, Unspecified }
Functions
Player PlayerBase, IPreRenderable SetNoClipCVar (bool val)
Player (UnitPtr unit, SValue &params)
float GetWindScale () override
void Initialize (PlayerRecord@ record) override
void EnableModifiers ()
void DisableModifiers ()
int FindUsable (IUsable@ usable)
void AddUsable (IUsable@ usable)
void RemoveUsable (IUsable@ usable)
IUsable GetTopUsable ()
void RefreshModifiers () override
void AddItem (ActorItem@ item) override
void AttuneItem (ActorItem@ item) override
bool IsHusk () override
float GetDamageMul (AttackRangeType rangeType)
float GetDamageMulTarget (bool melee, UnitPtr target) override
void DamagedActor (Actor@ actor, DamageInfo di)
DamageInfo DamageActor (Actor@ actor, DamageInfo di)
void NetShareExperience (int experience)
void PlayerKilled (PlayerRecord@ player)
void KilledActor (Actor@ killed, DamageInfo di) override
bool CanGiveArmor (int amt, ArmorDef@ def, bool replace)
bool GiveArmor (int amt, ArmorDef@ def, bool replace)
void Kill (Actor@ killer, uint weapon) override
bool ApplyBuff (ActorBuff@ buff) override
void GiveMana (int mana)
void TakeMana (int mana)
int Heal (int amount) override
void SoulLinkKill (PlayerHusk@ killer)
void SoulLinkDamage (int dmg)
void NetDecimate (int hp, int mana) override
int Decimate (DecimateInfo dec, vec2 pos, vec2 dir) override
int Damage (DamageInfo dmg, vec2 pos, vec2 dir) override
void NetDamage (DamageInfo dmg, vec2 pos, vec2 dir) override
void BroadcastNetDamage (DamageInfo di)
void OnDeath (DamageInfo di, vec2 dir) override
bool IsDead () override
void OnNewTitle (Titles::Title@ title)
void OnLevelUp (int levels)
void WarnCooldown (Skills::Skill@ skill, int ms) override
bool SpendCost (int mana, int stamina, int health) override
void Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther)
bool BlockProjectile (IProjectile@ proj) override
bool CheckSkillBlocked (Skills::Skill@ skill)
void CheckUseSkill (int dt, ButtonState &in btn, Skills::Skill@ skill, vec2 aimDir)
void OnComboBegin () override
void OnComboEnd () override
void Update (int dt) override
void SendPlayerMove (vec2 dir, bool force=false)
bool PreRender (int idt)
void SetGodmodeCVar (bool val)
void GiveRandomItems (Player@ ply, ActorItemQuality quality, int num)
void GiveItemsCFunc (cvar_t@ arg0, cvar_t@ arg1, cvar_t@ arg2, cvar_t@ arg3, cvar_t@ arg4)
void GiveDrinksCFunc (cvar_t@ arg0, cvar_t@ arg1, cvar_t@ arg2, cvar_t@ arg3, cvar_t@ arg4)
void GiveItemCFunc (cvar_t@ arg0)
void GiveDrinkCFunc (cvar_t@ arg0)
void ClearItemsCfunc ()
void GiveComboCfunc ()
void NextLevelCfunc ()
void GiveExperienceCFunc (cvar_t@ arg0)
void GiveHealthCFunc (cvar_t@ arg0)
void GiveManaCFunc (cvar_t@ arg0)
void GiveArmorCFunc (cvar_t@ arg0)
void GiveKeyCFunc (cvar_t@ arg0)
void LevelupCFunc (cvar_t@ arg0)
void SetCharNgpCFunc (cvar_t@ arg0)
void KillCFunc ()
void KillAllCFunc ()
void ReviveCFunc ()
void ListEnemiesCFunc ()
void ListModifiersEx (Modifiers::ModifierList@ list, int indentSize=1)
void ListModifiersCFunc ()
void GiveBlueprintCFunc (cvar_t@ arg0)
void SetFlagCFunc (cvar_t@ arg0, cvar_t@ arg1, cvar_t@ arg2)
void GiveGoldCFunc (cvar_t@ arg0)
void GiveOreCFunc (cvar_t@ arg0)
Variables
enum AttackRangeType g_cvar_god = false
array< PlayerUsable@> m_usables
vec2 m_lastDirection
vec2 m_lastSentPos
vec2 m_lastSentDir
float m_lastSentHP
float m_driftingOffset
float m_queuedHealing = 0
UnitScene m_fxBlockProjectile
SoundEvent m_sndBlockProjectile
UnitScene m_fxBlockPhysical
UnitScene m_fxBlockMagical
UnitScene m_fxLifesteal
SoundEvent m_sndNoMana
SoundEvent m_sndCooldown
SoundEvent m_sndEvade
bool m_returningDamage
bool m_insideJammable
int m_potionDelay
float m_windScale
uint m_lastCollideTime
UnitPtr m_lastCollideUnit
Enumeration Type Documentation
AttackRangeType
enum AttackRangeType
Enumerator
Melee
Ranged
Unspecified
Definition at line 1 of file Player.as.
 {
     Melee,
     Ranged,
     Unspecified
 }
Function Documentation
AddItem()
void SetNoClipCVar::AddItem (ActorItem@ item) override
Definition at line 187 of file Player.as.
     {
         PlayerBase::AddItem(item);
         (Network::Message("PlayerGiveItem") << item.id).SendToAll();
         cast<Campaign>(g_gameMode).m_townLocal.FoundItem(item);
AddUsable()
void SetNoClipCVar::AddUsable (IUsable@ usable)
Definition at line 140 of file Player.as.
     {
         int index = FindUsable(usable);
         if (index != -1)
         {
             m_usables[index].m_refCount++;
             return;
         }
ApplyBuff()
bool SetNoClipCVar::ApplyBuff (ActorBuff@ buff) override
Definition at line 388 of file Player.as.
     {
         if (BlockBuff(buff, m_record.armorDef, m_record.armor))
             return false;
AttuneItem()
void SetNoClipCVar::AttuneItem (ActorItem@ item) override
Definition at line 197 of file Player.as.
     {
         PlayerBase::AttuneItem(item);
BlockProjectile()
bool SetNoClipCVar::BlockProjectile (IProjectile@ proj) override
Definition at line 838 of file Player.as.
     {
         auto block = g_allModifiers.ProjectileBlock(this, proj);
         if (block)
         {
             auto pb = cast<ProjectileBase>(proj);
             vec3 pos;
             if (pb !is null)
                 pos = pb.m_unit.GetPosition();
             else
                 pos = m_unit.GetPosition();
             PlayEffect(m_fxBlockProjectile, xy(pos));
             PlaySound3D(m_sndBlockProjectile, pos);
             return true;
         }
BroadcastNetDamage()
void SetNoClipCVar::BroadcastNetDamage (DamageInfo di)
Definition at line 677 of file Player.as.
     {
         int damager = 0;
         if (di.Attacker !is null && di.Attacker.m_unit.IsDestroyed())
             damager = di.Attacker.m_unit.GetId();
CanGiveArmor()
bool SetNoClipCVar::CanGiveArmor (int amt, ArmorDef@ def, bool replace)
Definition at line 372 of file Player.as.
     {
CheckSkillBlocked()
bool SetNoClipCVar::CheckSkillBlocked (Skills::Skill@ skill)
Definition at line 860 of file Player.as.
     {
         int firstSkill = (skill is m_skills[0]) ? 0 : 1;
         if (skill.IsBlocking())
         {
             for (uint i = firstSkill; i < m_skills.length(); i++)
             {
                 if (m_skills[i].IgnoreForBlock())
                     continue;
                 if (skill !is m_skills[i] && m_skills[i].IsActive())
                     return true;
             }
         }
         else
         {
             for (uint i = firstSkill; i < m_skills.length(); i++)
                 if (skill !is m_skills[i] && m_skills[i].IsActive() && m_skills[i].IsBlocking())
                     return true;
         }
CheckUseSkill()
void SetNoClipCVar::CheckUseSkill (int dt, ButtonState &in btn, Skills::Skill@ skill, vec2 aimDir)
Definition at line 884 of file Player.as.
     {
         int targetSz = 0;
         auto targetMode = skill.GetTargetingMode(targetSz);
         if (CheckSkillBlocked(skill))
         {
             if (targetMode == Skills::TargetingMode::Channeling && skill.IsActive())
             {
                 skill.Release(aimDir);
                 skill.m_isActive = false;
             }
             return;
         }
         if (btn.Pressed)
         {
             if (targetMode == Skills::TargetingMode::Toggle)
             {
                 if (!skill.m_isActive && skill.Activate(aimDir))
                 {
                     g_allModifiers.TriggerEffects(this, null, Modifiers::EffectTrigger::CastSpell);
                     skill.m_isActive = true;
                 }
                 else if (skill.m_isActive)
                 {
                     skill.Deactivate();
                     skill.m_isActive = false;
                 }
             }
             else if (skill.Activate(aimDir) && skill !is m_skills[0])
                 g_allModifiers.TriggerEffects(this, null, Modifiers::EffectTrigger::CastSpell);
         }
         if (targetMode == Skills::TargetingMode::Channeling)
         {
             if (btn.Down)
             {
                 skill.Hold(dt, aimDir);
                 skill.m_isActive = true;
             }
             if (btn.Released || (!btn.Down && skill.m_isActive))
             {
                 skill.Release(aimDir);
                 skill.m_isActive = false;
ClearItemsCfunc()
void ClearItemsCfunc ()
Definition at line 1333 of file Player.as.
References GetLocalPlayer().
Referenced by Player::Player().
 {
     auto ply = GetLocalPlayer();
     if (ply is null)
         return;
     ply.m_record.items.removeRange(0, ply.m_record.items.length());
     ply.RefreshModifiers();
 }
Collide()
void SetNoClipCVar::Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther)
Definition at line 807 of file Player.as.
Referenced by Player::Collide().
     {
         for (uint i = 0; i < m_skills.length(); i++)
             m_skills[i].OnCollide(unit, pos, normal, fxOther);
         if (fxOther.IsSensor())
             return;
         auto nowT = g_scene.GetTime();
         if (m_lastCollideUnit == unit)
         {
             if ((m_lastCollideTime + 100) > nowT)
                 return;
         }
         m_lastCollideUnit = unit;
         auto actor = cast<Actor>(unit.GetScriptBehavior());
         if (actor is null)
             return;
         auto player = cast<PlayerBase>(actor);
         if (player !is null)
             return;
Damage()
int SetNoClipCVar::Damage (DamageInfo dmg, vec2 pos, vec2 dir) override
Definition at line 523 of file Player.as.
References Actor::AddFloatingHurt(), Actor::AddFloatingImmortal(), ApplyArmorParts(), DamageInfo::ArmorMul, DamageInfo::Attacker, DamageInfo::CanKill, DamageInfo::Cleave, ActorBuffList::Cleave(), DamageInfo::Damage, damage_round(), DamageInfo::DamageDealt, DamageInfo(), ActorBuffList::DamageTakenMul(), g_scene, GetArmor(), GetMaxHp(), Actor::IsImmortal(), m_buffs, m_dmgColor, m_evadeChance, m_evadeFx, m_hitFx, m_hp, m_immortalSound, m_skills, m_unit, DamageInfo::MagicalDamage, max, min, Actor::NetDamage(), Actor::NetHeal(), UnitHandler::NetSendUnitDamaged(), OnDamaged, OnDeath(), DamageInfo::PhysicalDamage, PlayEffect(), PlaySound3D(), DamageInfo::TrueStrike, and xy().
     {
         if (
 %if NON_FINAL
             g_cvar_god ||
 %endif
             m_record.IsDead())
         {
             return 0;
         }
         bool isTrapDamage = (dmg.Attacker is null);
         bool selfDmg = false;
         if (dmg.Attacker is this)
         {
             @dmg.Attacker = null;
             selfDmg = true;
         }
         int maxHp = m_record.MaxHealth();
         vec2 armor(m_record.Armor(), m_record.Resistance());
         ivec2 block;
         float dmgTakenMul = 1.0f;
         if (g_allModifiers.NonLethalDamage(this, dmg))
             dmg.CanKill = false;
         if (dmg.DamageType != 0)
         {
             if (!dmg.TrueStrike)
             {
                 if (g_allModifiers.Evasion(this, dmg.Attacker))
                 {
                     Stats::Add("evade-amount", 1, m_record);
                     g_allModifiers.TriggerEffects(this, dmg.Attacker, Modifiers::EffectTrigger::Evade);
                     m_dmgColor = vec4(0, 0, 0, 2.0);
                     PlaySound3D(m_sndEvade, m_unit);
                     return 0;
                 }
                 block += g_allModifiers.DamageBlock(this, dmg.Attacker);
                 if (block.x + block.y > 0)
                 {
                     Stats::Add("damage-blocked", block.x + block.y, m_record);
                     if (block.x > 0)
                         PlayEffect(m_fxBlockPhysical, pos);
                     else
                         PlayEffect(m_fxBlockMagical, pos);
                 }
                 if (dmg.PhysicalDamage > 0)
                     dmg.PhysicalDamage = max(0, dmg.PhysicalDamage - block.x);
                 if (dmg.MagicalDamage > 0)
                     dmg.MagicalDamage = max(0, dmg.MagicalDamage - block.y);
             }
             armor += g_allModifiers.ArmorAdd(this, dmg.Attacker);
             maxHp += g_allModifiers.StatsAdd(this).x;
             float trapMultiplier = 1.0f;
             if (isTrapDamage)
             {
                 if (Fountain::HasEffect("reduced_trap_damage"))
                     trapMultiplier *= 0.5f;
                 if (Fountain::HasEffect("more_trap_damage"))
                     trapMultiplier *= 2.0f;
             }
             float hc = 1.0f; //lerp(1.0f, 0.8f, m_record.GetHandicap());
             dmgTakenMul = hc * trapMultiplier * g_allModifiers.DamageTakenMul(this, dmg) * m_buffs.DamageTakenMul();
         }
         int dmgAmnt = ApplyArmor(dmg, m_buffs.ArmorMul() * armor * dmg.ArmorMul - Tweak::NewGamePlusNegArmor(g_ngp), dmgTakenMul);
         if (dmgAmnt > 0)
         {
             if (!dmg.CanKill && m_record.CurrentHealth() - dmgAmnt <= 0)
                 dmgAmnt = 0;
             bool evadable = dmg.Melee && dmg.Attacker !is null && !dmg.Attacker.IsDead();
             m_returningDamage = true;
             g_allModifiers.TriggerEffects(this, dmg.Attacker, Modifiers::EffectTrigger::Hurt);
             g_allModifiers.DamageTaken(this, dmg.Attacker, dmgAmnt);
             m_returningDamage = false;
             if (evadable && dmg.Attacker.IsDead())
             {
                 g_allModifiers.TriggerEffects(this, dmg.Attacker, Modifiers::EffectTrigger::Evade);
                 m_dmgColor = vec4(0, 0, 0, 2.0);
                 PlaySound3D(m_sndEvade, m_unit);
                 return 0;
             }
             float new = float(m_record.hp) - float(dmgAmnt) / float(maxHp);
             m_record.hp = new;
             assert(m_record.hp, new);
             AddFloatingHurt(dmgAmnt, dmg.Crit, dmg.MagicalDamage > dmg.PhysicalDamage ? FloatingTextType::PlayerHurtMagical : FloatingTextType::PlayerHurt);
             m_dmgColor = vec4(1, 0, 0, 1);
             int manaFromDamage = g_allModifiers.ManaFromDamage(this, dmgAmnt);
             if (manaFromDamage > 0)
                 this.GiveMana(manaFromDamage);
             Stats::Add("damage-taken", dmgAmnt, m_record);
             Stats::Max("damage-taken-max", dmgAmnt, m_record);
             //if (dmgAmnt > 5)
             //  MusicManager::AddTension(2.5);
             if (m_record.CurrentHealth() <= 0)
             {
                 //dmg.Damage = dmgAmnt;
                 //BroadcastNetDamage(dmg);
                 OnDeath(dmg, dir);
                 return dmgAmnt;
             }
             else
             {
                 if (m_gore !is null)
                     m_gore.OnHit(float(dmgAmnt) / float(maxHp), pos, atan(dir.y, dir.x));
                 dictionary params = { { "damage", float(dmgAmnt) } };
                 if (!selfDmg)
                     PlaySound3D(m_hurtSound, m_unit, params);
             }
         }
         else if (dmgAmnt < 0)
         {
             if (m_record.hp < 1.0)
                 return -Heal(-dmgAmnt);
             else
                 return 0;
         }
         else
         {
             AddFloatingHurt(0, dmg.Crit, dmg.MagicalDamage > dmg.PhysicalDamage ? FloatingTextType::PlayerHurtMagical : FloatingTextType::PlayerHurt);
         }
         dmg.Damage = dmgAmnt;
DamageActor()
DamageInfo SetNoClipCVar::DamageActor (Actor@ actor, DamageInfo di)
Definition at line 257 of file Player.as.
     {
         ivec2 dmgPowerV = g_allModifiers.DamagePower(this, actor);
         float dmgMul = m_buffs.DamageMul();
         int crit;
         int dmgPower;
         vec2 armorIg;
         ivec2 dmgAddV;
         if (di.Weapon == 1)
         {
             dmgPower = dmgPowerV.x;
             dmgMul *= g_allModifiers.DamageMul(this, actor).x;
             crit = g_allModifiers.Crit(this, actor, false);
             armorIg = g_allModifiers.ArmorIgnore(this, actor, false);
             dmgAddV = g_allModifiers.AttackDamageAdd(this, actor);
             g_allModifiers.TriggerEffects(this, actor, Modifiers::EffectTrigger::Hit);
         }
         else
         {
             dmgPower = dmgPowerV.y;
             dmgMul *= g_allModifiers.DamageMul(this, actor).y;
             crit = g_allModifiers.Crit(this, actor, true);
             armorIg = g_allModifiers.ArmorIgnore(this, actor, true);
             dmgAddV = g_allModifiers.SpellDamageAdd(this, actor);
             g_allModifiers.TriggerEffects(this, actor, Modifiers::EffectTrigger::SpellHit);
         }
         auto enemy = cast<CompositeActorBehavior>(actor);
         if (enemy !is null)
         {
             float receiveCritChance = enemy.m_buffs.ReceiveCritChance();
             if (receiveCritChance > 0.0f && randf() < receiveCritChance)
                 crit++;
         }
         if (crit > 0)
         {
             Stats::Add("crit-count", 1, m_record);
             dmgMul *= (2.0f + (g_allModifiers.CritMul(this, actor, di.Weapon != 1) - 1.0f)) * crit;
         }
         di.PhysicalDamage = damage_round(((di.PhysicalDamage + dmgAddV.x) * (50.0 + dmgPower) / 50.0) * dmgMul);
         di.MagicalDamage = damage_round(((di.MagicalDamage + dmgAddV.y) * (50.0 + dmgPower) / 50.0) * dmgMul);
         di.Crit = crit;
         di.ArmorMul *= armorIg;
         if (crit > 0)
             g_allModifiers.TriggerEffects(this, actor, Modifiers::EffectTrigger::CriticalHit);
DamagedActor()
void SetNoClipCVar::DamagedActor (Actor@ actor, DamageInfo di)
Definition at line 216 of file Player.as.
     {
         auto eb = cast<CompositeActorBehavior>(actor);
         if (!(eb !is null && eb.m_enemyType == "construct" && di.LifestealMul > 0))
         {
             float ls = di.LifestealMul * g_allModifiers.Lifesteal(this, actor, (di.Weapon != 1), di.Crit);
             ls *= g_allModifiers.AllHealthGainScale(this);
             if (ls > 0)
             {
                 ivec2 stats = g_allModifiers.StatsAdd(this);
                 float maxHealth = m_record.MaxHealth() + stats.x;
                 int stealHealth = max(0, roll_round(di.DamageDealt * ls));
                 if (m_record.hp * maxHealth + stealHealth > maxHealth)
                     stealHealth = int(maxHealth - m_record.hp * maxHealth);
                 if (stealHealth > 0)
                 {
                     m_queuedHealing += max(0, stealHealth);
                     Stats::Add("lifesteal-amount", stealHealth, m_record);
                 }
                 else if (stealHealth < 0)
                     PrintError("Lifesteal value " + stealHealth + " is invalid!");
                 PlayEffect(m_fxLifesteal, xy(m_unit.GetPosition()) + vec2(0, 1));
             }
         }
         if (di.Damage > 0)
         {
             Stats::Add("damage-dealt", di.Damage, m_record);
             Stats::Max("damage-dealt-max", di.Damage, m_record);
             if (m_returningDamage)
                 Stats::Add("damage-returned", di.Damage, m_record);
             Stats::Add("damage-dealt-physical", di.PhysicalDamage, m_record);
Decimate()
int SetNoClipCVar::Decimate (DecimateInfo dec, vec2 pos, vec2 dir) override
Definition at line 482 of file Player.as.
References Actor::AddFloatingHurt(), clamp(), EnemyHurtLocal, GetMaxHp(), DecimateInfo::HealthCurr, DecimateInfo::HealthMax, m_hp, and m_unit.
     {
         if (
 %if NON_FINAL
             g_cvar_god ||
 %endif
             m_record.IsDead())
         {
             return 0;
         }
         int maxHp = m_record.MaxHealth() + g_allModifiers.StatsAdd(this).x;
         int maxMp = m_record.MaxMana() + g_allModifiers.StatsAdd(this).y;
         int preHp = int(m_record.hp * maxHp);
         int preMp = int(m_record.mana * maxMp);
         float new = clamp((m_record.hp - dec.HealthMax) * (1.0f - dec.HealthCurr), 0.0f, 1.0f);
         m_record.hp = new;
         m_record.mana = clamp((m_record.mana - dec.ManaMax) * (1.0f - dec.ManaCurr), 0.0f, 1.0f);
         assert(m_record.hp, new);
         int dmgAmnt = preHp - int(m_record.hp * maxHp);
         int mpLoss = preMp - int(m_record.mana * maxMp);
         if (dmgAmnt < 0)
         {
             AddFloatingHurt(-dmgAmnt, 0, FloatingTextType::PlayerHealed);
             Stats::Add("amount-healed", -dmgAmnt, m_record);
         }
         else if (dmgAmnt > 0)
         {
             AddFloatingHurt(dmgAmnt, 0, FloatingTextType::PlayerHurt);
             //Stats::Add("damage-taken", dmgAmnt, m_record);
         }
DisableModifiers()
void SetNoClipCVar::DisableModifiers ()
Definition at line 125 of file Player.as.
     {
EnableModifiers()
void SetNoClipCVar::EnableModifiers ()
Definition at line 120 of file Player.as.
     {
FindUsable()
int SetNoClipCVar::FindUsable (IUsable@ usable)
Definition at line 130 of file Player.as.
     {
         for (uint i = 0; i < m_usables.length(); i++)
         {
             if (m_usables[i].m_usable is usable)
                 return i;
GetDamageMul()
float SetNoClipCVar::GetDamageMul (AttackRangeType rangeType)
Definition at line 206 of file Player.as.
                            { return false; }
     float GetDamageMul(AttackRangeType rangeType)
GetDamageMulTarget()
float SetNoClipCVar::GetDamageMulTarget (bool melee, UnitPtr target) override
Definition at line 211 of file Player.as.
     {
GetTopUsable()
IUsable SetNoClipCVar::GetTopUsable ()
Definition at line 165 of file Player.as.
     {
         for (uint i = 0; i < m_usables.length(); i++)
         {
             if (m_usables[i].m_usable.CanUse(this))
                 return m_usables[i].m_usable;
         }
         if (m_usables.length() > 0)
GetWindScale()
float SetNoClipCVar::GetWindScale () override
Definition at line 109 of file Player.as.
 { return m_windScale * m_buffs.WindScaleMul() * g_allModifiers.WindScale(this); }
GiveArmor()
bool SetNoClipCVar::GiveArmor (int amt, ArmorDef@ def, bool replace)
Definition at line 377 of file Player.as.
     {
GiveArmorCFunc()
void GiveArmorCFunc (cvar_t@ arg0)
Definition at line 1391 of file Player.as.
References GetLocalPlayer().
Referenced by Player::Player().
 {
     auto ply = GetLocalPlayer();
     if (ply is null)
         return;
     ply.GiveArmor(arg0.GetInt(), null, false);
 }
GiveBlueprintCFunc()
void GiveBlueprintCFunc (cvar_t@ arg0)
Definition at line 1503 of file Player.as.
References g_items, ActorItems::GetItem(), GetLocalPlayer(), and GiveForgeBlueprintImpl().
Referenced by Player::Player().
 {
     string id = arg0.GetString();
     auto item = g_items.GetItem(id);
     if (item is null)
         return;
     GiveForgeBlueprintImpl(item, GetLocalPlayer(), true);
 }
GiveComboCfunc()
void GiveComboCfunc ()
Definition at line 1343 of file Player.as.
References GetLocalPlayer().
Referenced by Player::Player().
 {
     auto ply = GetLocalPlayer();
     if (ply is null)
         return;
     if (ply.m_comboCount < 10)
         ply.m_comboCount = 10;
     ply.m_comboTime = 2000;
     ply.m_comboActive = true;
 }
GiveDrinkCFunc()
void GiveDrinkCFunc (cvar_t@ arg0)
Definition at line 1315 of file Player.as.
References GetLocalPlayer(), and GetTavernDrink().
Referenced by Player::Player().
 {
     auto ply = GetLocalPlayer();
     if (ply is null)
         return;
     auto drink = GetTavernDrink(HashString(arg0.GetString()));
     if (drink is null)
     {
         print("No drink '" + arg0.GetString() + "' found");
         return;
     }
     ply.AddDrink(drink);
     ply.RefreshModifiers();
 }
GiveDrinksCFunc()
void GiveDrinksCFunc (cvar_t@ arg0, cvar_t@ arg1, cvar_t@ arg2, cvar_t@ arg3, cvar_t@ arg4)
Definition at line 1276 of file Player.as.
References Common, GetLocalPlayer(), GetTavernDrink(), GiveTavernBarrelImpl(), Legendary, Rare, and Uncommon.
Referenced by Player::Player().
 {
     auto ply = GetLocalPlayer();
     if (ply is null)
         return;
     for (int i = 0; i < arg0.GetInt(); i++)
         GiveTavernBarrelImpl(GetTavernDrink(ActorItemQuality::Common), ply, false);
     for (int i = 0; i < arg1.GetInt(); i++)
         GiveTavernBarrelImpl(GetTavernDrink(ActorItemQuality::Uncommon), ply, false);
     for (int i = 0; i < arg2.GetInt(); i++)
         GiveTavernBarrelImpl(GetTavernDrink(ActorItemQuality::Rare), ply, false);
     for (int i = 0; i < arg3.GetInt(); i++)
         GiveTavernBarrelImpl(GetTavernDrink(ActorItemQuality::Rare), ply, false);
     for (int i = 0; i < arg4.GetInt(); i++)
         GiveTavernBarrelImpl(GetTavernDrink(ActorItemQuality::Legendary), ply, false);
 }
GiveExperienceCFunc()
void GiveExperienceCFunc (cvar_t@ arg0)
Definition at line 1364 of file Player.as.
References GetLocalPlayer().
Referenced by Player::Player().
 {
     auto ply = GetLocalPlayer();
     if (ply is null)
         return;
     ply.m_record.GiveExperience(arg0.GetInt());
 }
GiveGoldCFunc()
void GiveGoldCFunc (cvar_t@ arg0)
Definition at line 1528 of file Player.as.
References g_gameMode.
Referenced by Player::Player().
 {
     int amount = arg0.GetInt();
     cast<Campaign>(g_gameMode).m_townLocal.m_gold += amount;
 }
GiveHealthCFunc()
void GiveHealthCFunc (cvar_t@ arg0)
Definition at line 1373 of file Player.as.
References DamageInfo(), and GetLocalPlayer().
Referenced by Player::Player().
 {
     auto ply = GetLocalPlayer();
     if (ply is null)
         return;
     ply.Damage(DamageInfo(0, ply, arg0.GetInt(), false, false, 0), vec2(), vec2());
 }
GiveItemCFunc()
void GiveItemCFunc (cvar_t@ arg0)
Definition at line 1298 of file Player.as.
References g_items, GetLocalPlayer(), and ActorItems::TakeItem().
Referenced by Player::Player().
 {
     auto ply = GetLocalPlayer();
     if (ply is null)
         return;
     auto item = g_items.TakeItem(arg0.GetString());
     if (item is null)
     {
         print("No item '" + arg0.GetString() + "' found");
         return;
     }
     ply.AddItem(item);
     ply.RefreshModifiers();
 }
GiveItemsCFunc()
void GiveItemsCFunc (cvar_t@ arg0, cvar_t@ arg1, cvar_t@ arg2, cvar_t@ arg3, cvar_t@ arg4)
Definition at line 1261 of file Player.as.
References Common, Epic, GetLocalPlayer(), GiveRandomItems(), Legendary, Rare, and Uncommon.
Referenced by Player::Player().
 {
     auto ply = GetLocalPlayer();
     if (ply is null)
         return;
     GiveRandomItems(ply, ActorItemQuality::Common, arg0.GetInt());
     GiveRandomItems(ply, ActorItemQuality::Uncommon, arg1.GetInt());
     GiveRandomItems(ply, ActorItemQuality::Rare, arg2.GetInt());
     GiveRandomItems(ply, ActorItemQuality::Epic, arg3.GetInt());
     GiveRandomItems(ply, ActorItemQuality::Legendary, arg4.GetInt());
     ply.RefreshModifiers();
 }
GiveKeyCFunc()
void GiveKeyCFunc (cvar_t@ arg0)
Definition at line 1400 of file Player.as.
References GetLocalPlayer().
Referenced by Player::Player().
 {
     auto ply = GetLocalPlayer();
     if (ply is null)
         return;
     ply.m_record.keys[arg0.GetInt()] += 1;
 }
GiveMana()
void SetNoClipCVar::GiveMana (int mana)
Definition at line 396 of file Player.as.
     {
         ivec2 stats = g_allModifiers.StatsAdd(this);
         float manaf = mana;
         if (manaf < 0)
             manaf *= g_allModifiers.ManaDamageTakenMul(this);
         AddFloatingGive(int(manaf), FloatingTextType::PlayerAmmo);
         m_record.mana = clamp(m_record.mana + manaf / float(m_record.MaxMana() + stats.y), 0.0f, 1.0f);
GiveManaCFunc()
void GiveManaCFunc (cvar_t@ arg0)
Definition at line 1382 of file Player.as.
References GetLocalPlayer().
Referenced by Player::Player().
 {
     auto ply = GetLocalPlayer();
     if (ply is null)
         return;
     ply.GiveMana(arg0.GetInt());
 }
GiveOreCFunc()
void GiveOreCFunc (cvar_t@ arg0)
Definition at line 1534 of file Player.as.
References g_gameMode.
Referenced by Player::Player().
 {
     int amount = arg0.GetInt();
     cast<Campaign>(g_gameMode).m_townLocal.m_ore += amount;
 }
GiveRandomItems()
void GiveRandomItems (Player@ ply, ActorItemQuality quality, int num)
Definition at line 1249 of file Player.as.
References Player::AddItem(), g_items, num, quality, and ActorItems::TakeRandomItem().
Referenced by GiveItemsCFunc().
 {
     for (int i = 0; i < num; i++)
     {
         auto item = g_items.TakeRandomItem(quality);
         if (item is null)
             return;
         ply.AddItem(item);
     }
 }
Heal()
int SetNoClipCVar::Heal (int amount) override
Definition at line 421 of file Player.as.
     {
         int healAmnt = int(amount * g_allModifiers.AllHealthGainScale(this));
         m_queuedHealing += healAmnt;
         AddFloatingText(FloatingTextType::PlayerHealed, "" + amount, m_unit.GetPosition());
         (Network::Message("PlayerHealed") << healAmnt << m_record.hp).SendToAll();
Initialize()
void SetNoClipCVar::Initialize (PlayerRecord@ record) override
Definition at line 111 of file Player.as.
                                   { return m_windScale * m_buffs.WindScaleMul() * g_allModifiers.WindScale(this); }
     void Initialize(PlayerRecord@ record) override
     {
         PlayerBase::Initialize(record);
         m_preRenderables.insertLast(this);
IsDead()
bool SetNoClipCVar::IsDead () override
Definition at line 723 of file Player.as.
References m_dead, and m_hp.
 { return !m_unit.IsValid() || m_record.IsDead(); }
IsHusk()
bool SetNoClipCVar::IsHusk () override
Definition at line 204 of file Player.as.
 { return false; }
Kill()
void SetNoClipCVar::Kill (Actor@ killer, uint weapon) override
Definition at line 382 of file Player.as.
Referenced by Player::KilledActor().
     {
KillAllCFunc()
void KillAllCFunc ()
Definition at line 1445 of file Player.as.
References g_scene, g_team_player, Actor::IsTargetable(), and Actor::Kill().
Referenced by Player::Player().
 {
     auto enemies = g_scene.FetchAllActorsWithOtherTeam(g_team_player);
     for (uint i = 0; i < enemies.length(); i++)
     {
         Actor@ a = cast<Actor>(enemies[i].GetScriptBehavior());
         if (a.IsTargetable())
             a.Kill(null, 0);
     }
 }
KillCFunc()
void KillCFunc ()
Definition at line 1436 of file Player.as.
References GetLocalPlayer().
Referenced by Player::Player().
 {
     auto ply = GetLocalPlayer();
     if (ply is null)
         return;
     ply.Kill(null, 0);
 }
KilledActor()
void SetNoClipCVar::KilledActor (Actor@ killed, DamageInfo di) override
Definition at line 328 of file Player.as.
     {
     }
     void KilledActor(Actor@ killed, DamageInfo di) override
     {
         PlayerBase::KilledActor(killed, di);
         auto enemy = cast<CompositeActorBehavior>(killed);
         Stats::Add("enemies-killed", 1, m_record);
         if (enemy !is null && enemy.m_enemyType != "")
             Stats::Add(enemy.m_enemyType + "-killed", 1, m_record);
         cast<Campaign>(g_gameMode).m_townLocal.KilledEnemy(killed.m_unit.GetUnitProducer());
         g_allModifiers.TriggerEffects(this, killed, Modifiers::EffectTrigger::Kill);
         //TODO: Cache flag?
         if (g_flags.IsSet("unlock_combo"))
         {
             m_comboCount++;
             Stats::Max("best-combo", m_comboCount, m_record);
             vec2 combo = GetComboBars();
             if (combo.x >= 1.0f)
                 m_comboTime = 2000;
             else
                 m_comboTime = 1000;
         }
         if (enemy !is null && enemy.m_expReward > 0)
         {
             int xp = int(enemy.m_expReward * (1.0f + float(g_ngp) * 0.1f) + 30 * float(g_ngp));
             (Network::Message("PlayerShareExperience") << xp).SendToAll();
             float xpReward = float(xp - m_record.level * 3);
             xpReward *= m_buffs.ExperienceMul();
             xpReward *= Tweak::ExperienceScale;
             float expMul = g_allModifiers.ExpMul(this, killed) * g_mpExpScale;
             int xpr = int(xpReward * expMul);
             if (xpr > 0)
LevelupCFunc()
void LevelupCFunc (cvar_t@ arg0)
Definition at line 1409 of file Player.as.
References GetLocalPlayerRecord().
Referenced by Player::Player().
 {
     auto record = GetLocalPlayerRecord();
     int levels = arg0.GetInt();
     for (int i = 0; i < levels; i++)
     {
         int level = record.level;
         int xp = record.LevelExperience(level) - record.LevelExperience(level - 1);
         record.GiveExperience(xp);
     }
 }
ListEnemiesCFunc()
void ListEnemiesCFunc ()
Definition at line 1466 of file Player.as.
References g_scene, and g_team_player.
Referenced by Player::Player().
 {
     auto enemies = g_scene.FetchAllActorsWithOtherTeam(g_team_player);
     for (uint i = 0; i < enemies.length(); i++)
     {
         print(enemies[i].GetDebugName());
     }
 }
ListModifiersCFunc()
void ListModifiersCFunc ()
Definition at line 1497 of file Player.as.
References g_allModifiers, and ListModifiersEx().
Referenced by Player::Player().
 {
     print("Dumping all modifiers:");
     ListModifiersEx(g_allModifiers);
 }
ListModifiersEx()
void ListModifiersEx (Modifiers::ModifierList@ list, int indentSize = 1)
Definition at line 1476 of file Player.as.
Referenced by ListModifiersCFunc().
 {
     string indent = "";
     for (int i = 0; i < indentSize; i++)
         indent += "  ";
     for (uint i = 0; i < list.m_modifiers.length(); i++)
     {
         auto mod = list.m_modifiers[i];
         auto modList = cast<Modifiers::ModifierList>(mod);
         if (modList !is null)
         {
             print(indent + modList.m_name + ":");
             ListModifiersEx(modList, indentSize + 1);
         }
         else
             print(indent + Reflect::GetTypeName(mod));
     }
 }
NetDamage()
void SetNoClipCVar::NetDamage (DamageInfo dmg, vec2 pos, vec2 dir) override
Definition at line 672 of file Player.as.
References Actor::AddFloatingHurt(), DamageInfo::Attacker, DamageInfo::Crit, DamageInfo::Damage, EnemyHurtHusk, EnemyHurtLocal, g_team_player, GetLocalPlayer(), GetMaxHp(), Actor::IsDead(), m_gore, m_hp, m_hurtSound, m_movement, m_target, m_unit, PlaySound3D(), SetTarget(), and Actor::Team.
     {
NetDecimate()
void SetNoClipCVar::NetDecimate (int hp, int mana) override
Definition at line 471 of file Player.as.
References Actor::AddFloatingHurt(), EnemyHurtHusk, GetMaxHp(), and m_hp.
     {
         int maxHp = m_record.MaxHealth() + g_allModifiers.StatsAdd(this).x;
         m_record.hp -= float(hp) / float(maxHp);
         if (hp < 0)
             AddFloatingHurt(-hp, 0, FloatingTextType::PlayerHealed);
NetShareExperience()
void SetNoClipCVar::NetShareExperience (int experience)
Definition at line 311 of file Player.as.
     {
         float xpReward = float(experience - m_record.level * 3);
         xpReward *= m_buffs.ExperienceMul();
         xpReward *= Tweak::ExperienceScale;
         float expMul = g_allModifiers.ExpMul(this, null) * g_mpExpScale;
         int xpr = int(xpReward * expMul);
NextLevelCfunc()
void NextLevelCfunc ()
Definition at line 1355 of file Player.as.
Referenced by Player::Player().
 {
     if (!Network::IsServer())
         return;
     auto script = WorldScript::LevelExitNext();
     script.ServerExecute();
 }
OnComboBegin()
void SetNoClipCVar::OnComboBegin () override
Definition at line 935 of file Player.as.
     {
OnComboEnd()
void SetNoClipCVar::OnComboEnd () override
Definition at line 941 of file Player.as.
     {
OnDeath()
void SetNoClipCVar::OnDeath (DamageInfo di, vec2 dir) override
Definition at line 687 of file Player.as.
     {
         PlayerBase::OnDeath(di, dir);
         DisableModifiers();
         auto gm = cast<Campaign>(g_gameMode);
         Stats::Add("death-count", 1, m_record);
         if (cast<Town>(gm) is null)
             Stats::Add("floor-deaths-" + (gm.m_levelCount + 1), 1, m_record);
         int killerPeer = -1;
         auto plyKiller = cast<PlayerBase>(di.Attacker);
         if (plyKiller !is null)
             killerPeer = plyKiller.m_record.peer;
         m_record.deaths++;
         m_record.deathsTotal++;
         (Network::Message("PlayerDied") << killerPeer << int(di.DamageType) << int(di.Damage) << di.Melee << di.Weapon).SendToAll();
         PlayerRecord@ killerRecord;
         if (plyKiller !is null)
             @killerRecord = plyKiller.m_record;
         else if (di.Attacker !is null)
             cast<Campaign>(g_gameMode).m_townLocal.EnemyKilledPlayer(di.Attacker.m_unit.GetUnitProducer());
         gm.PlayerDied(m_record, killerRecord, di);
         auto hud = GetHUD();
OnLevelUp()
void SetNoClipCVar::OnLevelUp (int levels)
Definition at line 736 of file Player.as.
     {
         (Network::Message("PlayerLevelUp")).SendToAll();
         auto hud = GetHUD();
         hud.PlayPickup();
         PlaySound3D(Resources::GetSoundEvent("event:/player/levelup"), m_unit);
         PlayEffect("effects/players/levelup.effect", m_unit);
         AddFloatingText(FloatingTextType::Pickup, Resources::GetString(".hud.levelup"), m_unit.GetPosition());
         m_record.hp = 1.0;
         m_record.mana = 1.0;
         Stats::Add("levels-gained", levels, m_record);
OnNewTitle()
void SetNoClipCVar::OnNewTitle (Titles::Title@ title)
Definition at line 725 of file Player.as.
                            { return !m_unit.IsValid() || m_record.IsDead(); }
     void OnNewTitle(Titles::Title@ title)
     {
         auto gm = cast<Campaign>(g_gameMode);
         gm.SavePlayer(m_record);
         dictionary paramsTitle = { { "title", Resources::GetString(title.m_name) } };
         gm.m_notifications.Add(Resources::GetString(".hud.newtitle.character", paramsTitle), ParseColorRGBA("#" + Tweak::NotificationColors_NewTitle + "FF"));
Player()
SetNoClipCVar::Player (UnitPtr unit, SValue & params)
Definition at line 38 of file Player.as.
     {
         super(unit, params);
         //TODO: Replace check with something so that on splitscreen, only the first player can use cheats
         //if (Network::IsServer())
         {
             AddVar("noclip", false, SetNoClipCVar, cvar_flags::Cheat);
             AddVar("god", false, SetGodmodeCVar, cvar_flags::Cheat);
             AddVar("clientfollowshost", false, null, cvar_flags::Cheat);
             AddVar("show_all_accomplishments", false, null, cvar_flags::Cheat);
             {
                 array<cvar_type> cfuncParams = { cvar_type::String };
                 AddFunction("give_item", cfuncParams, GiveItemCFunc, cvar_flags::Cheat);
                 AddFunction("give_drink", cfuncParams, GiveDrinkCFunc, cvar_flags::Cheat);
                 AddFunction("give_blueprint", cfuncParams, GiveBlueprintCFunc, cvar_flags::Cheat);
             }
             {
                 array<cvar_type> cfuncParams = { cvar_type::Int, cvar_type::Int, cvar_type::Int, cvar_type::Int, cvar_type::Int };
                 AddFunction("give_items", cfuncParams, GiveItemsCFunc, cvar_flags::Cheat);
                 AddFunction("give_drinks", cfuncParams, GiveDrinksCFunc, cvar_flags::Cheat);
             }
             AddFunction("clear_items", ClearItemsCfunc, cvar_flags::Cheat);
             AddFunction("give_combo", GiveComboCfunc, cvar_flags::Cheat);
             AddFunction("next_level", NextLevelCfunc, cvar_flags::Cheat);
             {
                 array<cvar_type> cfuncParams = { cvar_type::Int };
                 AddFunction("give_experience", cfuncParams, GiveExperienceCFunc, cvar_flags::Cheat);
                 AddFunction("give_health", cfuncParams, GiveHealthCFunc, cvar_flags::Cheat);
                 AddFunction("give_mana", cfuncParams, GiveManaCFunc, cvar_flags::Cheat);
                 AddFunction("give_armor", cfuncParams, GiveArmorCFunc, cvar_flags::Cheat);
                 AddFunction("give_key", cfuncParams, GiveKeyCFunc, cvar_flags::Cheat);
                 AddFunction("levelup", cfuncParams, LevelupCFunc, cvar_flags::Cheat);
                 AddFunction("set_char_ngp", cfuncParams, SetCharNgpCFunc, cvar_flags::Cheat);
                 AddFunction("give_gold", cfuncParams, GiveGoldCFunc, cvar_flags::Cheat);
                 AddFunction("give_ore", cfuncParams, GiveOreCFunc, cvar_flags::Cheat);
             }
             {
                 array<cvar_type> cfuncParams = { cvar_type::String, cvar_type::Bool, cvar_type::Bool };
                 AddFunction("set_flag", cfuncParams, SetFlagCFunc, cvar_flags::Cheat);
             }
             AddFunction("killall", KillAllCFunc, cvar_flags::Cheat);
             AddFunction("revive", ReviveCFunc, cvar_flags::Cheat);
             AddFunction("listenemies", ListEnemiesCFunc, cvar_flags::Cheat);
             AddFunction("kill", KillCFunc);
             AddFunction("listmodifiers", ListModifiersCFunc);
         }
         @m_fxBlockProjectile = Resources::GetEffect("effects/players/block_projectile.effect");
         @m_sndBlockProjectile = Resources::GetSoundEvent("event:/player/projectile_block");
         @m_fxBlockPhysical = Resources::GetEffect("effects/players/block_physical.effect");
         @m_fxBlockMagical = Resources::GetEffect("effects/players/block_magical.effect");
         @m_fxLifesteal = Resources::GetEffect("effects/players/lifesteal.effect");
         @m_sndNoMana = Resources::GetSoundEvent("event:/player/no_mana");
         @m_sndCooldown = Resources::GetSoundEvent("event:/player/cooldown");
         @m_sndEvade = Resources::GetSoundEvent("event:/player/dodge");
         m_returningDamage = false;
PlayerKilled()
void SetNoClipCVar::PlayerKilled (PlayerRecord@ player)
Definition at line 324 of file Player.as.
     {
PreRender()
bool SetNoClipCVar::PreRender (int idt)
Definition at line 1219 of file Player.as.
Referenced by BaseGameMode::PreRenderFrame().
     {
         if (m_unit.IsDestroyed())
             return true;
RefreshModifiers()
void SetNoClipCVar::RefreshModifiers () override
Definition at line 177 of file Player.as.
     {
         PlayerBase::RefreshModifiers();
         // Modifiers for class title
         SValueBuilder builder;
RemoveUsable()
void SetNoClipCVar::RemoveUsable (IUsable@ usable)
Definition at line 153 of file Player.as.
     {
         int index = FindUsable(usable);
         if (index != -1)
         {
             if (--m_usables[index].m_refCount <= 0)
                 m_usables.removeAt(index);
             return;
ReviveCFunc()
void ReviveCFunc ()
Definition at line 1457 of file Player.as.
References GetLocalPlayerRecord().
Referenced by Player::Player().
 {
     auto record = GetLocalPlayerRecord();
     if (record is null)
         return;
     record.corpse.NetRevive(record);
 }
SendPlayerMove()
void SetNoClipCVar::SendPlayerMove (vec2 dir, bool force = false)
Definition at line 1198 of file Player.as.
     {
         auto pos = xy(m_unit.GetPosition());
         if (!force)
         {
             if (distsq(m_lastSentPos, pos) > 1 || distsq(m_lastSentDir, dir) > 0.01)
             {
                 m_lastSentPos = pos;
                 m_lastSentDir = dir;
                 (Network::Message("PlayerMove") << pos << dir).SendToAll();
             }
         }
         else
         {
             m_lastSentPos = pos;
             m_lastSentDir = dir;
SetCharNgpCFunc()
void SetCharNgpCFunc (cvar_t@ arg0)
Definition at line 1422 of file Player.as.
References g_gameMode, and GetLocalPlayer().
Referenced by Player::Player().
 {
     auto ply = GetLocalPlayer();
     if (ply is null)
         return;
     ply.m_record.newGamePlus = arg0.GetInt();
     auto gm = cast<Campaign>(g_gameMode);
     auto town = gm.m_townLocal;
     if (ply.m_record.newGamePlus > town.m_highestNgp)
         town.m_highestNgp = ply.m_record.newGamePlus;
 }
SetFlagCFunc()
void SetFlagCFunc (cvar_t@ arg0, cvar_t@ arg1, cvar_t@ arg2)
Definition at line 1514 of file Player.as.
References g_flags, Level, and Run.
Referenced by Player::Player().
 {
     string flag = arg0.GetString();
     bool value = arg1.GetBool();
     bool persistent = arg2.GetBool();
     if (!value)
         g_flags.Delete(flag);
     else
         g_flags.Set(flag, persistent ? FlagState::Run : FlagState::Level);
     (Network::Message("SyncFlag") << flag << value << persistent).SendToAll();
 }
SetGodmodeCVar()
void SetGodmodeCVar (bool val)
Definition at line 1241 of file Player.as.
References g_cvar_god.
Referenced by Player::Player().
 {
 %if NON_FINAL
     g_cvar_god = val;
 %endif
 }
SetNoClipCVar()
Player PlayerBase, IPreRenderable SetNoClipCVar (bool val)
Definition at line 1232 of file Player.as.
References GetLocalPlayer().
Referenced by Player::Player().
 {
     auto ply = GetLocalPlayer();
     if (ply is null)
         return;
     ply.m_unit.SetShouldCollide(!val);
 }
SoulLinkDamage()
void SetNoClipCVar::SoulLinkDamage (int dmg)
Definition at line 437 of file Player.as.
     {
     /*
         if (
 %if NON_FINAL
             g_cvar_god ||
 %endif
             m_record.IsDead() || dmg <= 0)
         {
             return;
         }
         int maxHp = m_record.MaxHealth();
         m_record.hp -= float(dmg) / float(maxHp);
         AddFloatingHurt(dmg, 0, FloatingTextType::PlayerHurt);
         m_dmgColor = vec4(1, 0, 0, 1);
         Stats::Add("damage-taken", dmg, m_record);
         Stats::Max("damage-taken-max", dmg, m_record);
         if (m_record.CurrentHealth() <= 0)
             OnDeath(DamageInfo(null, dmg, 0, false, true, 0), m_lastDirection);
         else
         {
             if (m_gore !is null)
                 m_gore.OnHit(float(dmg) / float(maxHp), xy(m_unit.GetPosition()), m_dirAngle);
             dictionary params = { { "damage", float(dmg) } };
             PlaySound3D(m_hurtSound, m_unit, params);
SoulLinkKill()
void SetNoClipCVar::SoulLinkKill (PlayerHusk@ killer)
Definition at line 431 of file Player.as.
     {
SpendCost()
bool SetNoClipCVar::SpendCost (int mana, int stamina, int health) override
Definition at line 765 of file Player.as.
     {
         ivec2 stats = g_allModifiers.StatsAdd(this);
         float manaCostMul = g_allModifiers.SpellCostMul(this);
         float manaCost = float(mana) / float(m_record.MaxMana() + stats.y) * manaCostMul;
         if (manaCost > 0 && !m_buffs.FreeMana())
         {
             if (m_record.mana < manaCost)
             {
                 int diff = int(ceil((manaCost - m_record.mana) * float(m_record.MaxMana())));
                 AddFloatingText(FloatingTextType::PlayerArmor, "(-" + diff + ")", m_unit.GetPosition());
                 PlaySound3D(m_sndNoMana, m_unit.GetPosition());
                 return false;
             }
             m_record.mana -= manaCost;
             //m_record.stamina -= stamina;
             Stats::Add("spent-mana", int(mana * manaCostMul), m_record);
         }
         /*
         if (stamina > 0)
         {
             if (m_record.stamina < stamina)
             {
                 AddFloatingText(FloatingTextType::EnemyImmortal, "Stamina!", m_unit.GetPosition());
                 return false;
             }
         }
         */
TakeMana()
void SetNoClipCVar::TakeMana (int mana)
Definition at line 410 of file Player.as.
     {
         ivec2 stats = g_allModifiers.StatsAdd(this);
         float manaf = float(mana) * g_allModifiers.ManaDamageTakenMul(this);
         AddFloatingGive(-int(manaf), FloatingTextType::PlayerAmmo);
         m_record.mana = clamp(m_record.mana - manaf / float(m_record.MaxMana() + stats.y), 0.0f, 1.0f);
Update()
void SetNoClipCVar::Update (int dt) override
Definition at line 947 of file Player.as.
     {
         PlayerBase::Update(dt);
         if (m_potionDelay > 0)
             m_potionDelay -= dt;
         auto input = GetInput();
         auto aimDir = input.AimDir;
         auto moveDir = input.MoveDir;
         if (m_buffs.Confuse() && !m_buffs.AntiConfuse())
         {
             aimDir *= -1;
             moveDir *= -1;
         }
         if (m_buffs.Drifting())
         {
             m_driftingOffset += 0.75f / dt;
             float ang = (sin(m_driftingOffset * 0.5f) - m_driftingOffset * 0.15f) * 0.4f;
             float a;
             a = atan(aimDir.y, aimDir.x) + ang;
             aimDir = vec2(cos(a), sin(a)) * length(aimDir);
             a = atan(moveDir.y, moveDir.x) + ang;
             moveDir = vec2(cos(a), sin(a)) * length(moveDir);
         }
         g_allModifiers.Update(this, dt);
         vec2 regen = (vec2(m_record.HealthRegen(), m_record.ManaRegen()) + g_allModifiers.RegenAdd(this)) * g_allModifiers.RegenMul(this);
         ivec2 stats = g_allModifiers.StatsAdd(this);
         m_effectParams.Set("hp_regen", (m_record.hp < 1.0f) ? regen.x : 0.f);
         m_effectParams.Set("mp_regen", (m_record.mana < 1.0f) ? regen.y : 0.f);
         float hpGainScale = g_allModifiers.AllHealthGainScale(this);
         float hpMax = m_record.MaxHealth() + stats.x;
         m_record.hp = clamp(m_record.hp + dt / 1000.0f * (regen.x * hpGainScale) / hpMax, 0.0f, 1.0f);
         m_record.mana = clamp(m_record.mana + dt / 1000.0f * regen.y / (m_record.MaxMana() + stats.y), 0.0f, 1.0f);
         if (m_queuedHealing > 0)
         {
             float healing = min(hpMax / 1000.0f * dt, m_queuedHealing);
             if (m_record.hp * hpMax + healing > hpMax)
             {
                 healing = float(hpMax - m_record.hp * hpMax);
                 m_queuedHealing = 0;
             }
             else
                 m_queuedHealing -= healing;
             m_record.hp = min(1.f, m_record.hp + healing / hpMax);
         }
         if (abs(m_lastSentHP - m_record.hp) > 0.001)
         {
             m_lastSentHP = m_record.hp;
             (Network::Message("PlayerSyncHealth") << m_lastSentHP).SendToAll();
         }
         auto baseGameMode = cast<BaseGameMode>(g_gameMode);
         HUD@ hud = GetHUD();
         bool freezeControls = IsDead() or baseGameMode.ShouldFreezeControls();
         int snapAngleCount = GetVarInt("g_movedir_snap");
         if (snapAngleCount > 0 && lengthsq(moveDir) > 0)
         {
             float snapAngle = TwoPI / float(snapAngleCount);
             float curAngle = atan(moveDir.y, moveDir.x);
             float snappedAngle = round(curAngle / snapAngle) * snapAngle;
             moveDir.x = cos(snappedAngle);
             moveDir.y = sin(snappedAngle);
         }
         int skillDt = int(g_allModifiers.SkillTimeMul(this) * dt);
         if (!freezeControls)
         {
             if (!m_buffs.Disarm())
             {
                 CheckUseSkill(skillDt, input.Attack4, m_skills[3], aimDir);
                 CheckUseSkill(skillDt, input.Attack3, m_skills[2], aimDir);
                 CheckUseSkill(skillDt, input.Attack2, m_skills[1], aimDir);
                 if (input.Attack1.Pressed)
                 {
                     auto skill = cast<Skills::ActiveSkill>(m_skills[0]);
                     if (skill !is null)
                     {
                         if (skill.m_cooldownC > 0 && g_allModifiers.CooldownClear(this, skill))
{
                             skill.m_cooldownC = 0;
                             skill.m_cooldownOverride = true;
                         }
                         else
                             skill.m_cooldownOverride = false;
                     }
                 }
                 if (input.Attack1.Down && !input.Ping.Down && !CheckSkillBlocked(m_skills[0]))
                 {
                     if (m_skills[0].Activate(aimDir))
                         g_allModifiers.TriggerEffects(this, null, Modifiers::EffectTrigger::Attack);
                 }
             }
             if ((input.Potion.Pressed && m_potionDelay <= 0) && (m_record.hp < 1.0 || m_record.mana < 1.0) && g_flags.IsSet("unlock_apothecary"))
             {
                 float healAmnt = 50 * g_allModifiers.PotionHealMul(this);
                 float manaAmnt = 50 * g_allModifiers.PotionManaMul(this);
                 int charges = 1 + g_allModifiers.PotionCharges();
                 if (charges > m_record.potionChargesUsed)
                 {
                     m_record.potionChargesUsed++;
                     int heal = int((healAmnt + 0.5f) * g_allModifiers.AllHealthGainScale(this));
                     NetHeal(heal);
                     (Network::Message("PlayerHealed") << int(healAmnt) << m_record.hp).SendToAll();
                     Stats::Add("amount-healed", heal, m_record);
                     AddFloatingText(FloatingTextType::PlayerHealed, "" + int(healAmnt + 0.5f), m_unit.GetPosition());
                     this.GiveMana(int(manaAmnt + 0.5f));
                     PlaySound3D(Resources::GetSoundEvent("event:/player/drink_potion"), m_unit.GetPosition());
                     Stats::Add("potion-charges-used", 1, m_record);
                     g_allModifiers.TriggerEffects(this, null, Modifiers::EffectTrigger::DrinkPotion);
                     m_potionDelay = GetVarInt("g_potion_delay");
                     Tutorial::RegisterAction("potion");
                 }
             }
             if (input.Use.Pressed && !m_buffs.Disarm())
             {
                 auto usable = GetTopUsable();
                 if (usable !is null && usable.CanUse(this))
                 {
                     Tutorial::RegisterAction("use");
                     UnitPtr unit = usable.GetUseUnit();
                     UnitProducer@ prod = unit.GetUnitProducer();
                     if (prod !is null && prod.GetNetSyncMode() == NetSyncMode::None)
                         usable.Use(this);
                     else if (Network::IsServer())
                     {
                         (Network::Message("UseUnit") << unit << m_unit).SendToAll();
                         usable.Use(this);
                     }
                     else
                         (Network::Message("UseUnitSecure") << unit).SendToHost();
                 }
             }
         }
         PhysicsBody@ bdy = m_unit.GetPhysicsBody();
         vec2 dir = vec2(cos(m_dirAngle), sin(m_dirAngle));
         // If we have no physics body, we can't do much (player died)
         if (bdy is null)
             return;
         float moveSpeed = Tweak::PlayerSpeed;
         float slowScale = g_allModifiers.SlowScale(this);
         moveSpeed += g_allModifiers.MoveSpeedAdd(this, slowScale);
         moveSpeed *= g_allModifiers.MoveSpeedMul(this, slowScale);
         moveSpeed *= m_buffs.MoveSpeedMul(slowScale);
         for (uint i = 0; i < m_skills.length(); i++)
         {
             float speedMod = m_skills[i].GetMoveSpeedMul();
             if (speedMod >= 1.0f || !m_comboActive)
                 moveSpeed *= speedMod;
             else
                 moveSpeed *= lerp(speedMod, 1.0, 0.5);
         }
         array<Tileset@>@ tilesets = g_scene.FetchTilesets(xy(m_unit.GetPosition()));
         for (int i = tilesets.length() - 1; i >= 0; i--)
         {
             auto tsd = tilesets[i].GetData();
             if (tsd is null)
                 continue;
             SValue@ tilesetSpeed = tsd.GetDictionaryEntry("walk-speed");
             if (tilesetSpeed !is null && tilesetSpeed.GetType() == SValueType::Float)
             {
                 moveSpeed *= tilesetSpeed.GetFloat();
                 break;
             }
         }
         moveSpeed = min(moveSpeed, Tweak::PlayerSpeedMax);
         float minSpeed = m_buffs.MinSpeed();
         auto moveDirLen = length(moveDir);
         if (moveDirLen < minSpeed)
             moveDir = normalize((moveDirLen > 0) ? moveDir : aimDir) * minSpeed;
         moveDir = freezeControls ? vec2() : (moveDir * moveSpeed);
         for (uint i = 0; i < m_skills.length(); i++)
         {
             vec2 skillMoveDir = m_skills[i].GetMoveDir();
             if (skillMoveDir.x != 0 || skillMoveDir.y != 0)
             {
                 moveDir = skillMoveDir;
                 break;
             }
         }
         int distance = int(length(moveDir));
         if (distance > 0)
             Stats::Add("units-traveled", distance, m_record);
         bdy.SetLinearVelocity(moveDir);
         float facing = atan(aimDir.y, aimDir.x);
         SetAngle(facing);
         bool walking = (lengthsq(bdy.GetLinearVelocity()) > 0.1);
         string scene = walking ? m_walkAnim.GetSceneName(facing) : m_idleAnim.GetSceneName(facing);
         SetBodyAnim(scene, false);
         if (m_playerBobbing)
             m_unit.SetPositionZ(walking ? ((m_unit.GetUnitSceneTime() / 125) % 2) : 0);
         UpdateFootsteps(dt, false);
         for (uint i = 0; i < m_skills.length(); i++)
             m_skills[i].Update(skillDt, walking);
         vec2 currDir = bdy.GetLinearVelocity();
         if (length(currDir) > 0.2)
             m_lastDirection = currDir;
WarnCooldown()
void SetNoClipCVar::WarnCooldown (Skills::Skill@ skill, int ms) override
Definition at line 756 of file Player.as.
     {
         if (skill.m_skillId == 0)
             return;
Variable Documentation
g_cvar_god
enum AttackRangeType g_cvar_god = false
Referenced by Player::Damage(), Player::Decimate(), and SetGodmodeCVar().
m_driftingOffset
float m_driftingOffset
Definition at line 18 of file Player.as.
m_fxBlockMagical
UnitScene m_fxBlockMagical
Definition at line 25 of file Player.as.
m_fxBlockPhysical
UnitScene m_fxBlockPhysical
Definition at line 24 of file Player.as.
m_fxBlockProjectile
UnitScene m_fxBlockProjectile
Definition at line 22 of file Player.as.
m_fxLifesteal
UnitScene m_fxLifesteal
Definition at line 26 of file Player.as.
m_insideJammable
bool m_insideJammable
Definition at line 32 of file Player.as.
m_lastCollideTime
uint m_lastCollideTime
Definition at line 804 of file Player.as.
m_lastCollideUnit
UnitPtr m_lastCollideUnit
Definition at line 805 of file Player.as.
m_lastDirection
vec2 m_lastDirection
Definition at line 13 of file Player.as.
m_lastSentDir
vec2 m_lastSentDir
Definition at line 15 of file Player.as.
m_lastSentHP
float m_lastSentHP
Definition at line 16 of file Player.as.
m_lastSentPos
vec2 m_lastSentPos
Definition at line 14 of file Player.as.
m_potionDelay
int m_potionDelay
Definition at line 34 of file Player.as.
m_queuedHealing
float m_queuedHealing = 0
Definition at line 19 of file Player.as.
m_returningDamage
bool m_returningDamage
Definition at line 31 of file Player.as.
m_sndBlockProjectile
SoundEvent m_sndBlockProjectile
Definition at line 23 of file Player.as.
m_sndCooldown
SoundEvent m_sndCooldown
Definition at line 28 of file Player.as.
m_sndEvade
SoundEvent m_sndEvade
Definition at line 29 of file Player.as.
m_sndNoMana
SoundEvent m_sndNoMana
Definition at line 27 of file Player.as.
m_usables
array<PlayerUsable@> m_usables
Definition at line 11 of file Player.as.
m_windScale
float m_windScale
Definition at line 36 of file Player.as.