HoHDocs: HUDSpectate Class Reference
HUDSpectate Class Reference
Private Member Functions
HUDSpectate (GUIBuilder@ b)
void Update (int dt) override
Private Attributes
TextWidget m_wWho
TextWidget m_wHelp
Detailed Description
Definition at line 1 of file HUDSpectate.as.
Constructor & Destructor Documentation
HUDSpectate()
HUDSpectate::HUDSpectate (GUIBuilder@ b) inline private
Definition at line 6 of file HUDSpectate.as.
References LoadWidget(), m_wHelp, m_widget, and m_wWho.
     {
         LoadWidget(b, "gui/spectate.gui");
         @m_wWho = cast<TextWidget>(m_widget.GetWidgetById("who"));
         @m_wHelp = cast<TextWidget>(m_widget.GetWidgetById("help"));
     }
Member Function Documentation
Update()
void HUDSpectate::Update (int dt) inline override private
Definition at line 14 of file HUDSpectate.as.
References g_gameMode, g_players, BaseGameMode::m_spectatingPlayer, m_wWho, TextWidget::SetText(), and Update().
Referenced by BaseGameMode::UpdateWidgets().
     {
         BaseGameMode@ gm = cast<BaseGameMode>(g_gameMode);
         if (gm is null)
             return;
         PlayerRecord@ player = g_players[gm.m_spectatingPlayer];
         if (m_wWho !is null)
         {
             string playerName;
             if (GetVarBool("ui_draw_plr_names_real"))
                 playerName = player.GetLobbyName();
             else
                 playerName = player.GetName();
             dictionary params = { { "name", playerName } };
             m_wWho.SetText(Resources::GetString(".hud.spectate.who", params));
         }
         IWidgetHoster::Update(dt);
     }
Member Data Documentation
m_wHelp
TextWidget HUDSpectate::m_wHelp private
Definition at line 4 of file HUDSpectate.as.
Referenced by HUDSpectate().
m_wWho
TextWidget HUDSpectate::m_wWho private
Definition at line 3 of file HUDSpectate.as.
Referenced by HUDSpectate(), and Update().
The documentation for this class was generated from the following file:
scripts/GUI/HUD/HUDSpectate.as