HoHDocs: ScalableSpriteButtonWidget Class Reference
ScalableSpriteButtonWidget Class Reference
Private Member Functions
ScalableSpriteButtonWidget ()
string GetValue ()
bool IsChecked ()
void SetCheckable ()
void SetChecked (bool b)
void SetGroupWidget (CheckBoxGroupWidget@ group)
Widget Clone () override
bool IsEnabled ()
void Load (WidgetLoadingContext &ctx) override
void SetText (string str)
void DoLayout (vec2 origin, vec2 parentSz) override
vec4 GetTextColor ()
array< Sprite@> GetSprites ()
void DoDraw (SpriteBatch &sb, vec2 pos) override
bool OnClick (vec2 mousePos) override
void OnMouseEnter (vec2 mousePos, bool forced) override
bool OnMouseDown (vec2 mousePos) override
bool OnMouseUp (vec2 mousePos) override
void OnMouseLeave (vec2 mousePos) override
void SetHovering (bool hovering, vec2 mousePos, bool force=false) override
void ShowTooltip () override
Private Attributes
CheckBoxGroupWidget m_checkBoxGroup
array< Sprite@> m_sprite
array< Sprite@> m_spriteHover
array< Sprite@> m_spriteDown
array< Sprite@> m_spriteDisabled
string m_func
string m_funcHover
string m_funcLeave
SoundEvent m_pressSound
SoundEvent m_selectSound
bool m_buttonDown
vec4 m_colorText
vec4 m_colorTextOriginal
vec4 m_colorDisableText
vec4 m_colorHoverText
vec4 m_colorDownText
bool m_enabled
bool m_disabledInGame
bool m_dynamicWidth
BitmapFont m_font
BitmapString m_text
string m_value
bool m_checkable
bool m_checked
vec2 m_textOffset
Detailed Description
Definition at line 1 of file ScalableSpriteButtonWidget.as.
Constructor & Destructor Documentation
ScalableSpriteButtonWidget()
ScalableSpriteButtonWidget::ScalableSpriteButtonWidget () inline private
Definition at line 38 of file ScalableSpriteButtonWidget.as.
Referenced by Clone().
     {
         super();
     }
Member Function Documentation
Clone()
Widget ScalableSpriteButtonWidget::Clone () inline override private
Definition at line 49 of file ScalableSpriteButtonWidget.as.
References Widget::CloneInto(), and ScalableSpriteButtonWidget().
Referenced by StatuesShopMenuContent::RefreshPlacementList(), and StatueSelectMenu::Show().
     {
         ScalableSpriteButtonWidget@ w = ScalableSpriteButtonWidget();
         CloneInto(w);
         return w;
     }
DoDraw()
void ScalableSpriteButtonWidget::DoDraw (SpriteBatch & sb, vec2 pos) inline override private
Definition at line 167 of file ScalableSpriteButtonWidget.as.
References g_menuTime, GetSprites(), Widget::m_height, m_text, and Widget::m_width.
Referenced by ScalableSpriteIconButtonWidget::DoDraw(), MenuServerListItem::DoDraw(), FavorButtonWidget::DoDraw(), and ShopButtonWidget::DoDraw().
     {
         array<Sprite@> sprites = GetSprites();
         if (sprites.length() == 0)
             return;
         Sprite@ left = sprites[0];
         Sprite@ mid = sprites[1];
         Sprite@ right = sprites[2];
         vec2 posLeft = pos;
         vec2 posRight = pos + vec2(m_width - right.GetWidth(), 0);
         vec4 rectMid = vec4(
             pos.x + left.GetWidth(),
             pos.y,
             m_width - left.GetWidth() - right.GetWidth(),
             m_height
         );
         sb.DrawSprite(posLeft, left, g_menuTime);
         sb.DrawSprite(mid.GetTexture2D(), rectMid, mid.GetFrame(g_menuTime));
         sb.DrawSprite(posRight, right, g_menuTime);
         if (m_text !is null)
         {
             m_text.SetColor(GetTextColor());
             vec2 textPos;
             if (m_textOffset.x == 0)
                 textPos.x = m_width / 2.0f - m_text.GetWidth() / 2.0f;
             else
                 textPos.x = m_textOffset.x;
             textPos.y = m_height / 2.0f - m_text.GetHeight() / 2.0f + m_textOffset.y;
             textPos.x = int(textPos.x);
             textPos.y = int(textPos.y);
             if (textPos.x < m_width)
                 sb.DrawString(pos + textPos, m_text);
         }
     }
DoLayout()
void ScalableSpriteButtonWidget::DoLayout (vec2 origin, vec2 parentSz) inline override private
Definition at line 133 of file ScalableSpriteButtonWidget.as.
References Widget::DoLayout(), m_dynamicWidth, Widget::m_padding, m_text, and Widget::m_width.
     {
         if (m_dynamicWidth && m_text !is null)
             m_width = m_text.GetWidth() + int(m_padding.x) * 2;
         Widget::DoLayout(origin, parentSz);
     }
GetSprites()
array<Sprite@> ScalableSpriteButtonWidget::GetSprites () inline private
Definition at line 152 of file ScalableSpriteButtonWidget.as.
References IsEnabled(), m_buttonDown, m_checkable, m_checked, Widget::m_hovering, m_sprite, m_spriteDisabled, m_spriteDown, and m_spriteHover.
Referenced by DoDraw().
     {
         if (!IsEnabled())
             return m_spriteDisabled;
         else
         {
             if (m_buttonDown || (m_checkable && m_checked))
                 return m_spriteDown;
             else if (m_hovering)
                 return m_spriteHover;
             else
                 return m_sprite;
         }
     }
GetTextColor()
vec4 ScalableSpriteButtonWidget::GetTextColor () inline private
Definition at line 141 of file ScalableSpriteButtonWidget.as.
References IsEnabled(), m_buttonDown, m_checked, m_colorDisableText, m_colorDownText, m_colorHoverText, m_colorText, and Widget::m_hovering.
Referenced by ShopButtonWidget::DoDraw(), and Load().
     {
         if (!IsEnabled())
             return m_colorDisableText;
         else if (m_buttonDown || (m_checked && m_checked))
             return m_colorDownText;
         else if (m_hovering)
             return m_colorHoverText;
         return m_colorText;
     }
GetValue()
string ScalableSpriteButtonWidget::GetValue () inline private
Definition at line 43 of file ScalableSpriteButtonWidget.as.
References m_value.
 { return m_value; }
IsChecked()
bool ScalableSpriteButtonWidget::IsChecked () inline private
Definition at line 44 of file ScalableSpriteButtonWidget.as.
References m_checked.
 { return m_checked; }
IsEnabled()
bool ScalableSpriteButtonWidget::IsEnabled () inline private
Definition at line 56 of file ScalableSpriteButtonWidget.as.
References g_gameMode, InGameMenu, m_disabledInGame, m_enabled, and m_state.
Referenced by GetSprites(), GetTextColor(), OnClick(), and OnMouseLeave().
     {
         if (m_disabledInGame && cast<MainMenu>(g_gameMode).m_state == MenuState::InGameMenu)
             return false;
         return m_enabled;
     }
Load()
void ScalableSpriteButtonWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 63 of file ScalableSpriteButtonWidget.as.
References Widget::Load().
Referenced by OnClick().
     {
         Widget::Load(ctx);
         GUIDef@ def = ctx.GetGUIDef();
         string spriteSet = ctx.GetString("spriteset");
         m_sprite.insertLast(def.GetSprite(spriteSet + "-left"));
         m_sprite.insertLast(def.GetSprite(spriteSet + "-mid"));
         m_sprite.insertLast(def.GetSprite(spriteSet + "-right"));
         m_spriteHover.insertLast(def.GetSprite(spriteSet + "-hover-left"));
         m_spriteHover.insertLast(def.GetSprite(spriteSet + "-hover-mid"));
         m_spriteHover.insertLast(def.GetSprite(spriteSet + "-hover-right"));
         m_spriteDown.insertLast(def.GetSprite(spriteSet + "-down-left"));
         m_spriteDown.insertLast(def.GetSprite(spriteSet + "-down-mid"));
         m_spriteDown.insertLast(def.GetSprite(spriteSet + "-down-right"));
         m_spriteDisabled.insertLast(def.GetSprite(spriteSet + "-disabled-left"));
         m_spriteDisabled.insertLast(def.GetSprite(spriteSet + "-disabled-mid"));
         m_spriteDisabled.insertLast(def.GetSprite(spriteSet + "-disabled-right"));
         m_func = ctx.GetString("func", false);
         m_funcHover = ctx.GetString("func-hover", false);
         m_funcLeave = ctx.GetString("func-leave", false);
         @m_pressSound = Resources::GetSoundEvent("event:/ui/button_click");
         @m_selectSound = Resources::GetSoundEvent("event:/ui/button_hover");
         @m_font = Resources::GetBitmapFont(ctx.GetString("font", false));
         bool caps = ctx.GetBoolean("text-caps", false);
         if (caps)
             SetText(utf8string(Resources::GetString(ctx.GetString("text", false))).toUpper().plain());
         else
             SetText(Resources::GetString(ctx.GetString("text", false)));
         m_textOffset = ctx.GetVector2("textoffset", false, m_textOffset);
         m_colorTextOriginal = m_colorText = ctx.GetColorRGBA("color", false, Tweak::ScaleButtonTextColor);
         m_colorDisableText = ctx.GetColorRGBA("disabletext", false, vec4(0.5, 0.5, 0.5, 1));
         m_colorHoverText = ctx.GetColorRGBA("hovertext", false, Tweak::ScaleButtonTextHoverColor);
         m_colorDownText = ctx.GetColorRGBA("downtext", false, Tweak::ScaleButtonTextDownColor);
         m_enabled = ctx.GetBoolean("enabled", false, true);
         m_disabledInGame = ctx.GetBoolean("not-in-game", false, false);
         m_value = ctx.GetString("value", false);
         m_checkable = ctx.GetBoolean("checkable", false);
         m_checked = ctx.GetBoolean("checked", false);
         m_width = ctx.GetInteger("width", false, -1);
         if (m_width == -1)
         {
             m_dynamicWidth = true;
             m_width = 20;
         }
         m_height = m_sprite[0].GetHeight();
         m_canFocus = true;
     }
OnClick()
bool ScalableSpriteButtonWidget::OnClick (vec2 mousePos) inline override private
Definition at line 209 of file ScalableSpriteButtonWidget.as.
References IsEnabled(), m_buttonDown, and m_checkable.
     {
         if (!IsEnabled())
             return false;
         if (!m_buttonDown)
             return true;
         if (m_checkable)
         {
             if (m_checkBoxGroup !is null)
                 m_checkBoxGroup.Toggled(this);
             else
                 m_checked = !m_checked;
         }
         m_host.OnFunc(this, m_func);
         PlaySound2D(m_pressSound);
         return true;
     }
OnMouseDown()
bool ScalableSpriteButtonWidget::OnMouseDown (vec2 mousePos) inline override private
Definition at line 243 of file ScalableSpriteButtonWidget.as.
References m_buttonDown.
 { m_buttonDown = true; return true; }
OnMouseEnter()
void ScalableSpriteButtonWidget::OnMouseEnter (vec2 mousePos, bool forced) inline override private
Definition at line 230 of file ScalableSpriteButtonWidget.as.
References Widget::OnMouseEnter().
     {
         Widget::OnMouseEnter(mousePos, forced);
         if (!IsEnabled())
             return;
         PlaySound2D(m_selectSound);
         if (m_funcHover != "")
             m_host.OnFunc(this, m_funcHover);
     }
OnMouseLeave()
void ScalableSpriteButtonWidget::OnMouseLeave (vec2 mousePos) inline override private
Definition at line 246 of file ScalableSpriteButtonWidget.as.
References IsEnabled(), m_buttonDown, m_funcLeave, Widget::m_host, and Widget::OnMouseLeave().
     {
         Widget::OnMouseLeave(mousePos);
         if (!IsEnabled())
             return;
         m_buttonDown = false;
         if (m_funcLeave != "")
             m_host.OnFunc(this, m_funcLeave);
     }
OnMouseUp()
bool ScalableSpriteButtonWidget::OnMouseUp (vec2 mousePos) inline override private
Definition at line 244 of file ScalableSpriteButtonWidget.as.
References m_buttonDown.
 { m_buttonDown = false; return true; }
SetCheckable()
void ScalableSpriteButtonWidget::SetCheckable () inline private
Definition at line 45 of file ScalableSpriteButtonWidget.as.
References m_checkable.
 { m_checkable = true; }
SetChecked()
void ScalableSpriteButtonWidget::SetChecked (bool b) inline private
Definition at line 46 of file ScalableSpriteButtonWidget.as.
References m_checked.
 { m_checked = b; }
SetGroupWidget()
void ScalableSpriteButtonWidget::SetGroupWidget (CheckBoxGroupWidget@ group) inline private
Definition at line 47 of file ScalableSpriteButtonWidget.as.
References m_checkBoxGroup.
 { @m_checkBoxGroup = group; }
SetHovering()
void ScalableSpriteButtonWidget::SetHovering (bool hovering, vec2 mousePos, bool force = false) inline override private
Definition at line 259 of file ScalableSpriteButtonWidget.as.
References force, g_gameMode, AGameMode::m_widgetInputFocus, and Widget::SetHovering().
     {
         //HACK: We need to force current input focus to null here in order to avoid bad UX in text input dialog
         if (hovering)
             @g_gameMode.m_widgetInputFocus = null;
         Widget::SetHovering(hovering, mousePos, force);
     }
SetText()
void ScalableSpriteButtonWidget::SetText (string str) inline private
Definition at line 125 of file ScalableSpriteButtonWidget.as.
References m_font, and m_text.
Referenced by AddButton(), Menu::CharacterSelectionMenu::Initialize(), UpgradeShopButtonWidget::Set(), Menu::SetCurrentDifficulty(), and LootBox::UpdateInterface().
     {
         if (str == "")
             @m_text = null;
         else if (m_font !is null)
             @m_text = m_font.BuildText(str);
     }
ShowTooltip()
void ScalableSpriteButtonWidget::ShowTooltip () inline override private
Definition at line 268 of file ScalableSpriteButtonWidget.as.
References m_enabled, Widget::m_tooltipEnabled, and Widget::ShowTooltip().
     {
         m_tooltipEnabled = m_enabled;
         Widget::ShowTooltip();
     }
Member Data Documentation
m_buttonDown
bool ScalableSpriteButtonWidget::m_buttonDown private
Definition at line 17 of file ScalableSpriteButtonWidget.as.
Referenced by GetSprites(), GetTextColor(), OnClick(), OnMouseDown(), OnMouseLeave(), and OnMouseUp().
m_checkable
bool ScalableSpriteButtonWidget::m_checkable private
Definition at line 33 of file ScalableSpriteButtonWidget.as.
Referenced by GetSprites(), OnClick(), and SetCheckable().
m_checkBoxGroup
CheckBoxGroupWidget ScalableSpriteButtonWidget::m_checkBoxGroup private
Definition at line 3 of file ScalableSpriteButtonWidget.as.
Referenced by SetGroupWidget().
m_checked
bool ScalableSpriteButtonWidget::m_checked private
Definition at line 34 of file ScalableSpriteButtonWidget.as.
Referenced by GetSprites(), GetTextColor(), IsChecked(), and SetChecked().
m_colorDisableText
vec4 ScalableSpriteButtonWidget::m_colorDisableText private
Definition at line 21 of file ScalableSpriteButtonWidget.as.
Referenced by GetTextColor().
m_colorDownText
vec4 ScalableSpriteButtonWidget::m_colorDownText private
Definition at line 23 of file ScalableSpriteButtonWidget.as.
Referenced by GetTextColor().
m_colorHoverText
vec4 ScalableSpriteButtonWidget::m_colorHoverText private
Definition at line 22 of file ScalableSpriteButtonWidget.as.
Referenced by GetTextColor().
m_colorText
vec4 ScalableSpriteButtonWidget::m_colorText private
Definition at line 19 of file ScalableSpriteButtonWidget.as.
Referenced by GetTextColor().
m_colorTextOriginal
vec4 ScalableSpriteButtonWidget::m_colorTextOriginal private
Definition at line 20 of file ScalableSpriteButtonWidget.as.
m_disabledInGame
bool ScalableSpriteButtonWidget::m_disabledInGame private
Definition at line 26 of file ScalableSpriteButtonWidget.as.
Referenced by IsEnabled().
m_dynamicWidth
bool ScalableSpriteButtonWidget::m_dynamicWidth private
Definition at line 27 of file ScalableSpriteButtonWidget.as.
Referenced by Clone(), and DoLayout().
m_enabled
bool ScalableSpriteButtonWidget::m_enabled private
Definition at line 25 of file ScalableSpriteButtonWidget.as.
Referenced by ShopButtonWidget::DoDraw(), IsEnabled(), Menu::HostMenu::OnFunc(), LootBox::Play(), Play(), ReloadList(), SkillsShopMenuContent::ReloadList(), StatueSelectMenu::Show(), ShowTooltip(), LootBox::Update(), Update(), ShopButtonWidget::UpdateEnabled(), and LootBox::UpdateInterface().
m_font
BitmapFont ScalableSpriteButtonWidget::m_font private
Definition at line 29 of file ScalableSpriteButtonWidget.as.
Referenced by ShopButtonWidget::Load(), Set(), and SetText().
m_func
string ScalableSpriteButtonWidget::m_func private
Definition at line 10 of file ScalableSpriteButtonWidget.as.
m_funcHover
string ScalableSpriteButtonWidget::m_funcHover private
Definition at line 11 of file ScalableSpriteButtonWidget.as.
m_funcLeave
string ScalableSpriteButtonWidget::m_funcLeave private
Definition at line 12 of file ScalableSpriteButtonWidget.as.
Referenced by OnMouseLeave().
m_pressSound
SoundEvent ScalableSpriteButtonWidget::m_pressSound private
Definition at line 14 of file ScalableSpriteButtonWidget.as.
Referenced by ShopButtonWidget::Load().
m_selectSound
SoundEvent ScalableSpriteButtonWidget::m_selectSound private
Definition at line 15 of file ScalableSpriteButtonWidget.as.
m_sprite
array<Sprite@> ScalableSpriteButtonWidget::m_sprite private
Definition at line 5 of file ScalableSpriteButtonWidget.as.
Referenced by GetSprites().
m_spriteDisabled
array<Sprite@> ScalableSpriteButtonWidget::m_spriteDisabled private
Definition at line 8 of file ScalableSpriteButtonWidget.as.
Referenced by GetSprites().
m_spriteDown
array<Sprite@> ScalableSpriteButtonWidget::m_spriteDown private
Definition at line 7 of file ScalableSpriteButtonWidget.as.
Referenced by GetSprites().
m_spriteHover
array<Sprite@> ScalableSpriteButtonWidget::m_spriteHover private
Definition at line 6 of file ScalableSpriteButtonWidget.as.
Referenced by GetSprites().
m_text
BitmapString ScalableSpriteButtonWidget::m_text private
Definition at line 30 of file ScalableSpriteButtonWidget.as.
Referenced by ScalableSpriteIconButtonWidget::DoDraw(), ShopButtonWidget::DoDraw(), DoDraw(), DoLayout(), and SetText().
m_textOffset
vec2 ScalableSpriteButtonWidget::m_textOffset private
Definition at line 36 of file ScalableSpriteButtonWidget.as.
Referenced by ScalableSpriteIconButtonWidget::DoDraw(), ShopButtonWidget::Load(), and FavorButtonWidget::Load().
m_value
string ScalableSpriteButtonWidget::m_value private
Definition at line 32 of file ScalableSpriteButtonWidget.as.
Referenced by GetValue(), and FavorButtonWidget::Set().
The documentation for this class was generated from the following file:
scripts/GUI/ScalableSpriteButtonWidget.as