HoHDocs: TextInputWidget Class Reference
TextInputWidget Class Reference
Private Member Functions
void Load (WidgetLoadingContext &ctx) override
void ClearText ()
bool UpdateInput (GameInput &input) override
void SetText (string str)
void UpdateText ()
vec2 GetTextOffset ()
void UpdateCursorPos ()
void DoDraw (SpriteBatch &sb, vec2 pos) override
Private Attributes
BitmapFont m_font
BitmapString m_bitmapText
utf8string m_text
int m_cursorPos = 0
float m_drawOffset = 0
vec2 m_textOffset
int m_textLimit
vec2 m_caretPos
int m_caretHeight
string m_func
string m_funcEdit
string m_funcCancel
TextAlignment m_alignment = TextAlignment::Left
vec4 m_color
Detailed Description
Definition at line 1 of file TextInputWidget.as.
Member Function Documentation
ClearText()
void TextInputWidget::ClearText () inline private
Definition at line 57 of file TextInputWidget.as.
References m_cursorPos, m_drawOffset, m_text, UpdateCursorPos(), and UpdateText().
     {
         m_text = "";
         m_cursorPos = 0;
         m_drawOffset = 0;
         UpdateText();
         UpdateCursorPos();
     }
DoDraw()
void TextInputWidget::DoDraw (SpriteBatch & sb, vec2 pos) inline override private
Definition at line 223 of file TextInputWidget.as.
References g_gameMode, GetTextOffset(), m_bitmapText, m_caretHeight, m_caretPos, m_drawOffset, Widget::m_height, Widget::m_origin, AGameMode::m_widgetInputFocus, and Widget::m_width.
     {
         if (m_bitmapText is null)
             return;
         sb.PushClipping(vec4(
             m_origin.x, m_origin.y,
             m_width, m_height
         ));
         vec2 textPos = pos + GetTextOffset();
         textPos.x -= m_drawOffset;
         sb.DrawString(textPos, m_bitmapText);
         sb.PopClipping();
         if (g_gameMode.m_widgetInputFocus is this)
         {
             vec4 rectCaret;
             rectCaret.x = textPos.x + m_caretPos.x;
             rectCaret.y = textPos.y + m_caretPos.y;
             rectCaret.z = 1;
             rectCaret.w = m_caretHeight;
             sb.DrawSprite(null, rectCaret, rectCaret, vec4(1, 1, 1, 1));
         }
     }
GetTextOffset()
vec2 TextInputWidget::GetTextOffset () inline private
Definition at line 186 of file TextInputWidget.as.
References Center, Left, m_alignment, m_bitmapText, m_textOffset, Widget::m_width, and Right.
Referenced by DoDraw().
     {
         if (m_bitmapText.GetWidth() > m_width)
             return m_textOffset;
         if (m_alignment == TextAlignment::Left)
             return m_textOffset;
         else if (m_alignment == TextAlignment::Center)
             return vec2(m_width / 2 - m_bitmapText.GetWidth() / 2, m_textOffset.y);
         else if (m_alignment == TextAlignment::Right)
             return vec2(m_width - m_bitmapText.GetWidth(), m_textOffset.y);
         return vec2();
     }
Load()
void TextInputWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 24 of file TextInputWidget.as.
References Center, Platform::CursorCaret, Widget::Load(), Widget::LoadWidthHeight(), m_alignment, Widget::m_canFocus, Widget::m_canFocusInput, m_caretHeight, m_color, Widget::m_cursor, m_font, m_func, m_funcCancel, m_funcEdit, m_text, m_textLimit, m_textOffset, Right, and UpdateText().
Referenced by LoadTextInputWidget().
     {
         LoadWidthHeight(ctx);
         string alignStr = ctx.GetString("align", false);
              if (alignStr == "right") m_alignment = TextAlignment::Right;
         else if (alignStr == "center") m_alignment = TextAlignment::Center;
         m_color = ctx.GetColorRGBA("color", false, vec4(1, 1, 1, 1));
         @m_font = Resources::GetBitmapFont(ctx.GetString("font"));
         m_text = ctx.GetString("text", false, "");
         m_textOffset = ctx.GetVector2("textoffset", false);
         m_textLimit = ctx.GetInteger("textlimit", false, -1);
         m_caretHeight = int(m_font.MeasureText("W").y);
         m_func = ctx.GetString("func", false, "");
         m_funcEdit = ctx.GetString("func-edit", false, "");
         m_funcCancel = ctx.GetString("func-cancel", false, "");
         @m_cursor = Platform::CursorCaret;
         UpdateText();
         Widget::Load(ctx);
         m_canFocus = true;
         m_canFocusInput = true;
         //m_overflow = WidgetOverflow::None;
     }
SetText()
void TextInputWidget::SetText (string str) inline private
Definition at line 165 of file TextInputWidget.as.
References m_cursorPos, m_text, UpdateCursorPos(), and UpdateText().
Referenced by Menu::HostMenu::Initialize(), CharacterCustomizationBase::Initialize(), and CharacterCustomizationBase::OnFunc().
     {
         m_text = str;
         UpdateText();
         m_cursorPos = m_text.length();
         UpdateCursorPos();
     }
UpdateCursorPos()
void TextInputWidget::UpdateCursorPos () inline private
Definition at line 201 of file TextInputWidget.as.
References m_bitmapText, m_caretPos, m_cursorPos, m_drawOffset, m_font, m_text, Widget::m_width, and max.
Referenced by ClearText(), SetText(), and UpdateInput().
     {
         if (m_font is null)
             return;
         string escText = EscapeString(m_text.substr(0, m_cursorPos).plain());
         auto textSize = m_font.MeasureText(escText);
         m_caretPos.x = textSize.x;
         m_caretPos.y = 0;
         if (m_bitmapText.GetWidth() > m_width)
         {
             float left = m_drawOffset;
             float right = left + m_width;
             if (m_caretPos.x > right)
                 m_drawOffset = m_caretPos.x - m_width;
             else if (m_caretPos.x < left)
                 m_drawOffset = max(0.0f, m_caretPos.x - 20.0f);
         }
     }
UpdateInput()
bool TextInputWidget::UpdateInput (GameInput & input) inline override private
Definition at line 66 of file TextInputWidget.as.
References Backspace, Cancel, Delete, End, evt, g_gameMode, Home, Left, LeftWord, m_cursorPos, m_func, m_funcCancel, m_funcEdit, Widget::m_host, m_text, m_textLimit, AGameMode::m_widgetInputFocus, None, Right, RightWord, Submit, UpdateCursorPos(), and UpdateText().
     {
         bool textUpdated = false;
         bool cursorUpdated = false;
         int n = input.GetTextInputCount();
         for (int i = 0; i < n; i++)
         {
             auto evt = input.GetTextInput(i);
             switch (evt.evt)
             {
                 case TextInputControlEventType::None:
                     if (m_textLimit != -1 && int(m_text.length()) >= m_textLimit)
                         break;
                     m_text.insert(m_cursorPos++, evt.text);
                     textUpdated = true;
                     cursorUpdated = true;
                     break;
                 case TextInputControlEventType::Submit:
                     if (m_func != "")
                         m_host.OnFunc(this, m_func);
                     break;
                 case TextInputControlEventType::Cancel:
                     @g_gameMode.m_widgetInputFocus = null;
                     if (m_funcCancel != "")
                         m_host.OnFunc(this, m_funcCancel);
                     break;
                 case TextInputControlEventType::Home: m_cursorPos = 0; cursorUpdated = true; break;
                 case TextInputControlEventType::End: m_cursorPos = m_text.length(); cursorUpdated = true; break;
                 case TextInputControlEventType::Left:
                     if (--m_cursorPos < 0)
                         m_cursorPos = 0;
                     cursorUpdated = true;
                     break;
                 case TextInputControlEventType::Right:
                     if (++m_cursorPos > int(m_text.length()))
                         m_cursorPos = m_text.length();
                     cursorUpdated = true;
                     break;
                 case TextInputControlEventType::LeftWord:
                     if (m_cursorPos > 0)
                     {
                         int j = m_text.findLast(" ", m_cursorPos - 1);
                         if (j == -1)
                             m_cursorPos = 0;
                         else
                             m_cursorPos = j;
                         cursorUpdated = true;
                     }
                     break;
                 case TextInputControlEventType::RightWord:
                     if (m_cursorPos < int(m_text.length()))
                     {
                         int j = m_text.findFirst(" ", m_cursorPos + 1);
                         if (j == -1)
                             m_cursorPos = m_text.length();
                         else
                             m_cursorPos = j + 1;
                         cursorUpdated = true;
                     }
                     break;
                 case TextInputControlEventType::Backspace:
                     if (m_cursorPos > 0)
                     {
                         m_text.erase(--m_cursorPos, 1);
                         textUpdated = true;
                         cursorUpdated = true;
                     }
                     break;
                 case TextInputControlEventType::Delete:
                     if (m_cursorPos < int(m_text.length()))
                     {
                         m_text.erase(m_cursorPos, 1);
                         textUpdated = true;
                     }
                     break;
             }
         }
         if (textUpdated)
         {
             UpdateText();
             if (m_funcEdit != "")
                 m_host.OnFunc(this, m_funcEdit);
         }
         if (cursorUpdated)
             UpdateCursorPos();
         return true;
     }
UpdateText()
void TextInputWidget::UpdateText () inline private
Definition at line 174 of file TextInputWidget.as.
References m_bitmapText, m_color, m_drawOffset, m_font, m_text, and Widget::m_width.
Referenced by ClearText(), Load(), SetText(), and UpdateInput().
     {
         if (m_font is null)
             return;
         @m_bitmapText = m_font.BuildText(EscapeString(m_text.plain()));
         m_bitmapText.SetColor(m_color);
         if (m_bitmapText.GetWidth() <= m_width)
             m_drawOffset = 0;
     }
Member Data Documentation
m_alignment
TextAlignment TextInputWidget::m_alignment = TextAlignment::Left private
Definition at line 20 of file TextInputWidget.as.
Referenced by GetTextOffset(), and Load().
m_bitmapText
BitmapString TextInputWidget::m_bitmapText private
Definition at line 4 of file TextInputWidget.as.
Referenced by DoDraw(), GetTextOffset(), UpdateCursorPos(), and UpdateText().
m_caretHeight
int TextInputWidget::m_caretHeight private
Definition at line 14 of file TextInputWidget.as.
Referenced by DoDraw(), and Load().
m_caretPos
vec2 TextInputWidget::m_caretPos private
Definition at line 13 of file TextInputWidget.as.
Referenced by DoDraw(), and UpdateCursorPos().
m_color
vec4 TextInputWidget::m_color private
Definition at line 22 of file TextInputWidget.as.
Referenced by Load(), and UpdateText().
m_cursorPos
int TextInputWidget::m_cursorPos = 0 private
Definition at line 7 of file TextInputWidget.as.
Referenced by ClearText(), SetText(), UpdateCursorPos(), and UpdateInput().
m_drawOffset
float TextInputWidget::m_drawOffset = 0 private
Definition at line 8 of file TextInputWidget.as.
Referenced by ClearText(), DoDraw(), UpdateCursorPos(), and UpdateText().
m_font
BitmapFont TextInputWidget::m_font private
Definition at line 3 of file TextInputWidget.as.
Referenced by Load(), UpdateCursorPos(), and UpdateText().
m_func
string TextInputWidget::m_func private
Definition at line 16 of file TextInputWidget.as.
Referenced by Load(), and UpdateInput().
m_funcCancel
string TextInputWidget::m_funcCancel private
Definition at line 18 of file TextInputWidget.as.
Referenced by Load(), and UpdateInput().
m_funcEdit
string TextInputWidget::m_funcEdit private
Definition at line 17 of file TextInputWidget.as.
Referenced by Load(), and UpdateInput().
m_text
utf8string TextInputWidget::m_text private
Definition at line 6 of file TextInputWidget.as.
Referenced by ClearText(), Load(), CharacterCustomizationNPC::OnFunc(), Menu::CharacterCustomizationMenu::OnFunc(), Menu::HostMenu::OnFunc(), SetText(), CharacterCustomizationBase::UpdateCost(), UpdateCursorPos(), UpdateInput(), and UpdateText().
m_textLimit
int TextInputWidget::m_textLimit private
Definition at line 11 of file TextInputWidget.as.
Referenced by Load(), and UpdateInput().
m_textOffset
vec2 TextInputWidget::m_textOffset private
Definition at line 10 of file TextInputWidget.as.
Referenced by GetTextOffset(), and Load().
The documentation for this class was generated from the following file:
scripts/GUI/TextInputWidget.as