HoHDocs: Skills::ActiveSkill Class Reference
Skills::ActiveSkill Class Reference
Private Member Functions
ActiveSkill (UnitPtr unit, SValue &params)
TargetingMode GetTargetingMode (int &out size) override
void StartHoldSound ()
void StopHoldSound ()
void Hold (int dt, vec2 target) override
void NetHold (int dt, vec2 target) override
bool Activate (vec2 target) override
void NetActivate (vec2 target) override
void Deactivate () override
void NetDeactivate () override
void Release (vec2 target) override
void NetRelease (vec2 target) override
void PlaySkillEffect (vec2 dir, dictionary ePs={ })
float GetMoveSpeedMul () override
bool IsActive () override
bool IsBlocking () override
void Update (int dt, bool walking) override
float GetCooldownProgess (int idt)
void DoActivate (SValueBuilder@ builder, vec2 target)
void DoDeactivate ()
void NetDoActivate (SValue@ param, vec2 target)
void NetDoDeactivate ()
void DoUpdate (int dt)
bool NeedNetParams ()
Private Attributes
AnimString m_animation
int m_animCountdown
string m_fx
SoundEvent m_sound
SoundEvent m_soundHold
SoundInstance m_soundHoldI
float m_speedMul
float m_idleCdMul
int m_cooldown
int m_cooldownC
bool m_cooldownOverride
int m_castpoint
int m_castingC
int m_costMana
int m_costStamina
int m_costHealth
float m_timeScale
bool m_blocking
bool m_netHold
vec2 m_queuedTarget
Detailed Description
Definition at line 3 of file ActiveSkill.as.
Constructor & Destructor Documentation
ActiveSkill()
Skills::ActiveSkill::ActiveSkill (UnitPtr unit, SValue & params) inline private
Definition at line 33 of file ActiveSkill.as.
References m_animation, m_animCountdown, m_blocking, m_castpoint, m_cooldown, m_costHealth, m_costMana, m_costStamina, m_fx, m_idleCdMul, m_sound, m_soundHold, m_speedMul, m_timeScale, max, and unit.
         {
             super(unit);
             @m_animation = AnimString(GetParamString(unit, params, "anim"));
             m_fx = GetParamString(unit, params, "fx", false);
             @m_sound = Resources::GetSoundEvent(GetParamString(unit, params, "snd", false));
             @m_soundHold = Resources::GetSoundEvent(GetParamString(unit, params, "snd-hold", false));
             m_castpoint = max(1, GetParamInt(unit, params, "castpoint", false, 0));
             m_cooldown = max(m_castpoint, GetParamInt(unit, params, "cooldown", true, 1000));
             m_costMana = GetParamInt(unit, params, "mana-cost", false, 0);
             m_costStamina = GetParamInt(unit, params, "stamina-cost", false, 0);
             m_costHealth = GetParamInt(unit, params, "health-cost", false, 0);
             m_speedMul = GetParamFloat(unit, params, "speed-mul", false, 1);
             m_idleCdMul = GetParamFloat(unit, params, "idle-cooldown-mul", false, 1);
             m_blocking = GetParamBool(unit, params, "blocking", false, false);
             m_animCountdown = 0;
             m_timeScale = 1.0f;
         }
Member Function Documentation
Activate()
bool Skills::ActiveSkill::Activate (vec2 target) inline override private
Definition at line 89 of file ActiveSkill.as.
References GetTargetingMode(), m_animation, m_animCountdown, m_castingC, m_castpoint, m_cooldown, m_cooldownC, m_costHealth, m_costMana, m_costStamina, Skills::m_owner, m_queuedTarget, Skills::m_skillId, Tutorial::RegisterAction(), and Skills::Toggle.
Referenced by Skills::DropUnit::Activate(), Skills::SpewProjectiles::Activate(), and Skills::ChargeUnit::Activate().
         {
             int targetSz = 0;
             TargetingMode targetMode = GetTargetingMode(targetSz);
             if (m_cooldownC > 0)
             {
                 m_owner.WarnCooldown(this, m_cooldownC);
                 return false;
             }
             if (!m_owner.SpendCost(m_costMana, m_costStamina, m_costHealth))
                 return false;
             if (m_skillId == 0)
                 Tutorial::RegisterAction("attack1");
             else if (m_skillId == 1)
                 Tutorial::RegisterAction("attack2");
             if (targetMode != TargetingMode::Toggle)
                 m_cooldownC = m_cooldown;
             m_castingC = m_castpoint;
             m_queuedTarget = target;
             m_animCountdown = m_owner.SetUnitScene(m_animation, true);
             (Network::Message("PlayerActiveSkillActivate") << int(m_skillId) << target).SendToAll();
             return true;
         }
Deactivate()
void Skills::ActiveSkill::Deactivate () inline override private
Definition at line 131 of file ActiveSkill.as.
References DoDeactivate(), GetTargetingMode(), m_cooldown, m_cooldownC, Skills::m_skillId, and Skills::Toggle.
         {
             int targetSz = 0;
             TargetingMode targetMode = GetTargetingMode(targetSz);
             if (targetMode == TargetingMode::Toggle)
                 m_cooldownC = m_cooldown;
             (Network::Message("PlayerActiveSkillDeactivate") << int(m_skillId)).SendToAll();
             DoDeactivate();
         }
DoActivate()
void Skills::ActiveSkill::DoActivate (SValueBuilder@ builder, vec2 target) inline private
Definition at line 231 of file ActiveSkill.as.
Referenced by Update().
 {}
DoDeactivate()
void Skills::ActiveSkill::DoDeactivate () inline private
Definition at line 232 of file ActiveSkill.as.
Referenced by Deactivate().
 {}
DoUpdate()
void Skills::ActiveSkill::DoUpdate (int dt) inline private
Definition at line 235 of file ActiveSkill.as.
Referenced by Update().
 {}
GetCooldownProgess()
float Skills::ActiveSkill::GetCooldownProgess (int idt) inline private
Definition at line 230 of file ActiveSkill.as.
References clamp(), m_cooldown, and m_cooldownC.
 { return clamp((m_cooldownC - idt) / float(m_cooldown), 0.0f, 1.0f); }
GetMoveSpeedMul()
float Skills::ActiveSkill::GetMoveSpeedMul () inline override private
Definition at line 177 of file ActiveSkill.as.
References m_animCountdown, and m_speedMul.
 { return m_animCountdown <= 0 ? 1.0 : m_speedMul; }
GetTargetingMode()
TargetingMode Skills::ActiveSkill::GetTargetingMode (int &out size) inline override private
Definition at line 58 of file ActiveSkill.as.
References Skills::Direction.
Referenced by Activate(), Deactivate(), NetActivate(), and NetDeactivate().
 { return TargetingMode::Direction; }
Hold()
void Skills::ActiveSkill::Hold (int dt, vec2 target) inline override private
Definition at line 77 of file ActiveSkill.as.
References m_soundHoldI, and StartHoldSound().
Referenced by Skills::Hold(), Skills::ChargeUnit::Hold(), and Skills::Explode::Hold().
         {
             if (m_soundHoldI is null)
                 StartHoldSound();
         }
IsActive()
bool Skills::ActiveSkill::IsActive () inline override private
Definition at line 178 of file ActiveSkill.as.
References m_animCountdown, and Skills::m_isActive.
 { return m_isActive || m_animCountdown > 0; }
IsBlocking()
bool Skills::ActiveSkill::IsBlocking () inline override private
Definition at line 179 of file ActiveSkill.as.
References m_blocking.
 { return m_blocking; }
NeedNetParams()
bool Skills::ActiveSkill::NeedNetParams () inline private
Definition at line 236 of file ActiveSkill.as.
Referenced by Update().
 { return false; }
NetActivate()
void Skills::ActiveSkill::NetActivate (vec2 target) inline override private
Definition at line 120 of file ActiveSkill.as.
References Skills::Channeling, GetTargetingMode(), m_animation, m_animCountdown, m_netHold, and Skills::m_owner.
Referenced by Skills::ChargeUnit::NetActivate().
         {
             m_animCountdown = m_owner.SetUnitScene(m_animation, true);
             int targetSz = 0;
             TargetingMode targetMode = GetTargetingMode(targetSz);
             if (targetMode == TargetingMode::Channeling)
                 m_netHold = true;
         }
NetDeactivate()
void Skills::ActiveSkill::NetDeactivate () inline override private
Definition at line 144 of file ActiveSkill.as.
References GetTargetingMode(), and NetDoDeactivate().
         {
             int targetSz = 0;
             TargetingMode targetMode = GetTargetingMode(targetSz);
             NetDoDeactivate();
         }
NetDoActivate()
void Skills::ActiveSkill::NetDoActivate (SValue@ param, vec2 target) inline private
Definition at line 233 of file ActiveSkill.as.
 {}
NetDoDeactivate()
void Skills::ActiveSkill::NetDoDeactivate () inline private
Definition at line 234 of file ActiveSkill.as.
Referenced by NetDeactivate().
 {}
NetHold()
void Skills::ActiveSkill::NetHold (int dt, vec2 target) inline override private
Definition at line 83 of file ActiveSkill.as.
References m_soundHoldI, and StartHoldSound().
Referenced by Skills::NetHold(), Skills::SpewProjectiles::NetHold(), Skills::ChargeUnit::NetHold(), Skills::Explode::NetHold(), and Update().
         {
             if (m_soundHoldI is null)
                 StartHoldSound();
         }
NetRelease()
void Skills::ActiveSkill::NetRelease (vec2 target) inline override private
Definition at line 159 of file ActiveSkill.as.
References m_netHold, and StopHoldSound().
Referenced by Skills::ChargeUnit::NetRelease(), Skills::Explode::NetRelease(), and Skills::NetRelease().
         {
             StopHoldSound();
             m_netHold = false;
         }
PlaySkillEffect()
void Skills::ActiveSkill::PlaySkillEffect (vec2 dir, dictionary ePs = { }) inline private
Definition at line 166 of file ActiveSkill.as.
Referenced by Skills::TempBuffAoe::DoActivate(), Skills::Charge::DoActivate(), Skills::ShootProjectile::DoActivate(), Skills::Explode::DoTrigger(), Skills::MeleeSwing::DoUpdate(), Skills::DropUnit::NetDoActivate(), Skills::TempBuffAoe::NetDoActivate(), Skills::Charge::NetDoActivate(), Skills::ShootProjectile::NetDoActivate(), Skills::Explode::NetTrigger(), Skills::DropEffect::SpawnDropEffect(), Skills::DropUnit::SpawnUnit(), Skills::StaggeredSpawnUnits::StartSpawning(), Skills::MeleeSwing::StartSwing(), Skills::Whirlwind::StartWhirl(), and Skills::Whirlnova::StartWhirl().
                                                         { })
         {
             PlaySound3D(m_sound, m_owner.m_unit.GetPosition());
             if (m_fx == "")
                 return;
             ePs["angle"] = atan(dir.y, dir.x);
             PlayEffect(m_fx, xy(m_owner.m_unit.GetPosition()), ePs);
         }
Release()
void Skills::ActiveSkill::Release (vec2 target) inline override private
Definition at line 152 of file ActiveSkill.as.
References Skills::m_skillId, and StopHoldSound().
Referenced by Skills::ChargeUnit::Release(), Skills::Explode::Release(), Skills::SpewProjectiles::Release(), and Skills::Release().
         {
             StopHoldSound();
             (Network::Message("PlayerActiveSkillRelease") << int(m_skillId) << target).SendToAll();
         }
StartHoldSound()
void Skills::ActiveSkill::StartHoldSound () inline private
Definition at line 60 of file ActiveSkill.as.
References Skills::m_owner, m_soundHold, and m_soundHoldI.
Referenced by Hold(), and NetHold().
         {
             if (m_soundHold is null)
                 return;
             if (m_soundHoldI !is null)
                 m_soundHoldI.Stop();
             @m_soundHoldI = m_soundHold.PlayTracked(m_owner.m_unit.GetPosition());
         }
StopHoldSound()
void Skills::ActiveSkill::StopHoldSound () inline private
Definition at line 69 of file ActiveSkill.as.
References m_soundHold, and m_soundHoldI.
Referenced by NetRelease(), and Release().
         {
             if (m_soundHold is null || m_soundHoldI is null)
                 return;
             m_soundHoldI.Stop();
             @m_soundHoldI = null;
         }
Update()
void Skills::ActiveSkill::Update (int dt, bool walking) inline override private
Definition at line 181 of file ActiveSkill.as.
References DoActivate(), DoUpdate(), m_animation, m_animCountdown, m_castingC, m_cooldownC, m_idleCdMul, m_netHold, Skills::m_owner, m_queuedTarget, Skills::m_skillId, m_soundHoldI, m_timeScale, NeedNetParams(), and NetHold().
         {
             dt = int(m_timeScale * dt);
             if (m_soundHoldI !is null)
                 m_soundHoldI.SetPosition(m_owner.m_unit.GetPosition());
             DoUpdate(dt);
             if (m_netHold)
             {
                 auto player = cast<PlayerHusk>(m_owner);
                 if (player !is null)
                     NetHold(dt, player.m_dir);
             }
             m_animCountdown -= dt;
             if (m_animCountdown > 0)
                 m_owner.SetUnitScene(m_animation, false);
             int mdt = int(dt * (walking ? 1.0f : m_idleCdMul));
             if (m_cooldownC > 0)
                 m_cooldownC -= mdt;
             if (m_castingC > 0)
             {
                 m_castingC -= mdt;
                 if (m_castingC <= 0)
                 {
                     //PlaySkillEffect(m_queuedTarget);
                     SValue@ svalNetParams = null;
                     if (NeedNetParams())
                     {
                         SValueBuilder builder;
                         DoActivate(builder, m_queuedTarget);
                         @svalNetParams = builder.Build();
                     }
                     else
                         DoActivate(null, m_queuedTarget);
                     (Network::Message("PlayerActiveSkillDoActivate") << int(m_skillId) << m_queuedTarget << svalNetParams).SendToAll();
                 }
             }
         }
Member Data Documentation
m_animation
AnimString Skills::ActiveSkill::m_animation private
Definition at line 5 of file ActiveSkill.as.
Referenced by Skills::Explode::Activate(), Activate(), ActiveSkill(), Skills::Charge::DoUpdate(), Skills::Explode::NetActivate(), NetActivate(), and Update().
m_animCountdown
int Skills::ActiveSkill::m_animCountdown private
Definition at line 6 of file ActiveSkill.as.
Referenced by Skills::Explode::Activate(), Activate(), ActiveSkill(), Skills::ChargeUnit::DoUpdate(), GetMoveSpeedMul(), Skills::Explode::Hold(), IsActive(), Skills::Explode::NetActivate(), NetActivate(), Skills::SpewProjectiles::NetHold(), Skills::Explode::NetHold(), Skills::StaggeredSpawnUnits::StartSpawning(), Skills::Whirlwind::StartWhirl(), Skills::Whirlnova::StartWhirl(), and Update().
m_blocking
bool Skills::ActiveSkill::m_blocking private
Definition at line 25 of file ActiveSkill.as.
Referenced by ActiveSkill(), and IsBlocking().
m_castingC
int Skills::ActiveSkill::m_castingC private
Definition at line 18 of file ActiveSkill.as.
Referenced by Skills::Explode::Activate(), Activate(), Skills::Explode::Hold(), and Update().
m_castpoint
int Skills::ActiveSkill::m_castpoint private
Definition at line 17 of file ActiveSkill.as.
Referenced by Skills::Explode::Activate(), Activate(), ActiveSkill(), Skills::Explode::Hold(), Skills::StaggeredSpawnUnits::StartSpawning(), Skills::Whirlwind::StartWhirl(), and Skills::Whirlnova::StartWhirl().
m_cooldown
int Skills::ActiveSkill::m_cooldown private
Definition at line 14 of file ActiveSkill.as.
Referenced by Skills::Explode::Activate(), Activate(), ActiveSkill(), Deactivate(), GetCooldownProgess(), Skills::ChargeUnit::Hold(), Skills::Explode::Hold(), and Skills::SpewProjectiles::NetHold().
m_cooldownC
int Skills::ActiveSkill::m_cooldownC private
Definition at line 15 of file ActiveSkill.as.
Referenced by Skills::Explode::Activate(), Activate(), Deactivate(), GetCooldownProgess(), Skills::ChargeUnit::Hold(), Skills::Explode::Hold(), Skills::SpewProjectiles::NetHold(), and Update().
m_cooldownOverride
bool Skills::ActiveSkill::m_cooldownOverride private
Definition at line 16 of file ActiveSkill.as.
m_costHealth
int Skills::ActiveSkill::m_costHealth private
Definition at line 22 of file ActiveSkill.as.
Referenced by Activate(), ActiveSkill(), Skills::SpewProjectiles::NetHold(), and Skills::Explode::Trigger().
m_costMana
int Skills::ActiveSkill::m_costMana private
Definition at line 20 of file ActiveSkill.as.
Referenced by Activate(), ActiveSkill(), Skills::SpewProjectiles::NetHold(), SkillWidget::SetSkill(), Skills::Explode::Trigger(), and PlayerMenuCharacterTab::UpdateFromRecord().
m_costStamina
int Skills::ActiveSkill::m_costStamina private
Definition at line 21 of file ActiveSkill.as.
Referenced by Activate(), ActiveSkill(), Skills::SpewProjectiles::NetHold(), and Skills::Explode::Trigger().
m_fx
string Skills::ActiveSkill::m_fx private
Definition at line 7 of file ActiveSkill.as.
Referenced by ActiveSkill(), and Skills::ChargeUnit::StartChargeEffect().
m_idleCdMul
float Skills::ActiveSkill::m_idleCdMul private
Definition at line 12 of file ActiveSkill.as.
Referenced by ActiveSkill(), and Update().
m_netHold
bool Skills::ActiveSkill::m_netHold private
Definition at line 27 of file ActiveSkill.as.
Referenced by Skills::Explode::NetActivate(), NetActivate(), NetRelease(), and Update().
m_queuedTarget
vec2 Skills::ActiveSkill::m_queuedTarget private
Definition at line 30 of file ActiveSkill.as.
Referenced by Skills::Explode::Activate(), Activate(), and Update().
m_sound
SoundEvent Skills::ActiveSkill::m_sound private
Definition at line 8 of file ActiveSkill.as.
Referenced by ActiveSkill().
m_soundHold
SoundEvent Skills::ActiveSkill::m_soundHold private
Definition at line 9 of file ActiveSkill.as.
Referenced by ActiveSkill(), StartHoldSound(), and StopHoldSound().
m_soundHoldI
SoundInstance Skills::ActiveSkill::m_soundHoldI private
Definition at line 10 of file ActiveSkill.as.
Referenced by Hold(), NetHold(), StartHoldSound(), StopHoldSound(), and Update().
m_speedMul
float Skills::ActiveSkill::m_speedMul private
Definition at line 11 of file ActiveSkill.as.
Referenced by ActiveSkill(), Skills::ChargeUnit::GetMoveSpeedMul(), Skills::StaggeredSpawnUnits::GetMoveSpeedMul(), Skills::Whirlwind::GetMoveSpeedMul(), Skills::Whirlnova::GetMoveSpeedMul(), and GetMoveSpeedMul().
m_timeScale
float Skills::ActiveSkill::m_timeScale private
Definition at line 24 of file ActiveSkill.as.
Referenced by ActiveSkill(), and Update().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Skills/ActiveSkill.as