HoHDocs: GiveMana Class Reference
GiveMana Class Reference
Private Member Functions
GiveMana (UnitPtr unit, SValue &params)
void SetWeaponInformation (uint weapon)
int GetAmount (float intensity, Player@ player)
bool Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
bool CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
Private Attributes
int m_mana
bool m_pickup
Detailed Description
Definition at line 1 of file GiveMana.as.
Constructor & Destructor Documentation
GiveMana()
GiveMana::GiveMana (UnitPtr unit, SValue & params) inline private
Definition at line 6 of file GiveMana.as.
References m_mana, m_pickup, and unit.
     {
         m_mana = GetParamInt(unit, params, "mana");
         m_pickup = GetParamBool(unit, params, "pickup", false, false);
     }
Member Function Documentation
Apply()
bool GiveMana::Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk) inline private
Definition at line 35 of file GiveMana.as.
References CanApply(), and GetAmount().
     {
         if (!CanApply(owner, target, pos, dir, intensity))
             return false;
         auto player = cast<Player>(target.GetScriptBehavior());
         if (player !is null)
             player.GiveMana(GetAmount(intensity, player));
         return true;
     }
CanApply()
bool GiveMana::CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) inline override private
Definition at line 47 of file GiveMana.as.
References GetAmount().
Referenced by Apply().
     {
         if (!target.IsValid())
             return false;
         auto player = cast<Player>(target.GetScriptBehavior());
         int amount = GetAmount(intensity, player);
         if (amount > 0 && player !is null)
             return player.m_record.mana < 1.0;
         return true;
     }
GetAmount()
int GiveMana::GetAmount (float intensity, Player@ player) inline private
Definition at line 14 of file GiveMana.as.
References Fountain::HasEffect(), m_mana, and m_pickup.
Referenced by Apply(), and CanApply().
     {
         float ret = float(m_mana);
         ret *= intensity;
         if (m_pickup)
         {
             if (player !is null)
                 ret *= player.m_record.GetModifiers().ManaGainScale(player);
             if (Fountain::HasEffect("amazing_pickups"))
                 ret *= 5;
             if (Fountain::HasEffect("bad_pickups"))
                 ret *= 0.5f;
         }
         return int(ret);
     }
SetWeaponInformation()
void GiveMana::SetWeaponInformation (uint weapon) inline private
Definition at line 12 of file GiveMana.as.
 {}
Member Data Documentation
m_mana
int GiveMana::m_mana private
Definition at line 3 of file GiveMana.as.
Referenced by GetAmount(), and GiveMana().
m_pickup
bool GiveMana::m_pickup private
Definition at line 4 of file GiveMana.as.
Referenced by GetAmount(), and GiveMana().
The documentation for this class was generated from the following file:
scripts/Behaviors/Effects/GiveMana.as