HoHDocs: LifestealDamage Class Reference
LifestealDamage Class Reference
Private Member Functions
LifestealDamage (UnitPtr unit, SValue &params)
int DoDamage (IDamageTaker@ target, DamageInfo di, vec2 pos, vec2 dir) override
Private Attributes
float m_lifesteal
float m_manasteal
uint m_fxAttackerHash
UnitScene m_fxAttacker
Detailed Description
Definition at line 1 of file LifestealDamage.as.
Constructor & Destructor Documentation
LifestealDamage()
LifestealDamage::LifestealDamage (UnitPtr unit, SValue & params) inline private
Definition at line 9 of file LifestealDamage.as.
References Fountain::GetEffect(), m_fxAttacker, m_fxAttackerHash, m_lifesteal, m_manasteal, and unit.
     {
         super(unit, params);
         m_lifesteal = GetParamFloat(unit, params, "lifesteal");
         m_manasteal = GetParamFloat(unit, params, "manasteal");
         m_fxAttackerHash = HashString(GetParamString(unit, params, "lifesteal-attacker-effect", false));
         @m_fxAttacker = Resources::GetEffect(m_fxAttackerHash);
     }
Member Function Documentation
DoDamage()
int LifestealDamage::DoDamage (IDamageTaker@ target, DamageInfo di, vec2 pos, vec2 dir) inline override private
Definition at line 20 of file LifestealDamage.as.
References DamageInfo::Attacker, Damage::DoDamage(), Actor::Heal(), m_fxAttacker, m_fxAttackerHash, m_lifesteal, m_manasteal, Actor::m_unit, PlayEffect(), and roll_round().
     {
         int dmg = Damage::DoDamage(target, di, pos, dir);
         if (di.Attacker !is null)
         {
             di.Attacker.Heal(roll_round(dmg * m_lifesteal));
             auto player = cast<Player>(di.Attacker);
             if (player !is null)
                 player.GiveMana(roll_round(dmg * m_manasteal));
             PlayEffect(m_fxAttacker, di.Attacker.m_unit);
             (Network::Message("AttachEffect") << m_fxAttackerHash << di.Attacker.m_unit).SendToAll();
         }
         return dmg;
     }
Member Data Documentation
m_fxAttacker
UnitScene LifestealDamage::m_fxAttacker private
Definition at line 7 of file LifestealDamage.as.
Referenced by DoDamage(), and LifestealDamage().
m_fxAttackerHash
uint LifestealDamage::m_fxAttackerHash private
Definition at line 6 of file LifestealDamage.as.
Referenced by DoDamage(), and LifestealDamage().
m_lifesteal
float LifestealDamage::m_lifesteal private
Definition at line 3 of file LifestealDamage.as.
Referenced by DoDamage(), and LifestealDamage().
m_manasteal
float LifestealDamage::m_manasteal private
Definition at line 4 of file LifestealDamage.as.
Referenced by DoDamage(), and LifestealDamage().
The documentation for this class was generated from the following file:
scripts/Behaviors/Effects/LifestealDamage.as