HoHDocs: WorldScript::LogText Class Reference
WorldScript::LogText Class Reference
Private Member Functions
bool IsVariable (UnitPtr unit)
SValue ServerExecute ()
void ClientExecute (SValue@ val)
Private Attributes
string Text
UnitFeed Variables
bool AsDialog
Detailed Description
Definition at line 4 of file LogText.as.
Member Function Documentation
ClientExecute()
void WorldScript::LogText::ClientExecute (SValue@ val) inline private
Definition at line 38 of file LogText.as.
References ServerExecute().
         {
             ServerExecute();
         }
IsVariable()
bool WorldScript::LogText::IsVariable (UnitPtr unit) inline private
Definition at line 15 of file LogText.as.
References unit.
         {
             return cast<Variable>(unit.GetScriptBehavior()) !is null;
         }
ServerExecute()
SValue WorldScript::LogText::ServerExecute () inline private
Definition at line 20 of file LogText.as.
References AsDialog, g_gameMode, WorldScript::Variable::GetValue(), AGameMode::ShowDialog(), Text, and Variables.
Referenced by ClientExecute().
         {
             string varDump = "";
             auto vars = Variables.FetchAll();
             for (uint i = 0; i < vars.length(); i++)
             {
                 Variable@ var = cast<Variable>(vars[i].GetScriptBehavior());
                 if (varDump != "")
                     varDump += " ";
                 varDump += vars[i].GetId() + ":" + var.GetValue();
             }
             string finalText = Text + " " + varDump;
             print("[LogText] " + finalText);
             if (AsDialog)
                 g_gameMode.ShowDialog("", finalText, Resources::GetString(".menu.ok"), null);
             return null;
         }
Member Data Documentation
AsDialog
bool WorldScript::LogText::AsDialog private
Definition at line 13 of file LogText.as.
Referenced by ServerExecute().
Text
string WorldScript::LogText::Text private
Definition at line 7 of file LogText.as.
Referenced by ServerExecute().
Variables
UnitFeed WorldScript::LogText::Variables private
Definition at line 10 of file LogText.as.
Referenced by ServerExecute().
The documentation for this class was generated from the following file:
scripts/WorldScript/LogText.as