HoHDocs: WorldScript::Door Class Reference
WorldScript::Door Class Reference
Private Member Functions
void Initialize ()
void Announce ()
void Update (int dt)
Player GetPlayer (UnitPtr unit)
void OnEnter (UnitPtr unit, vec2 pos, vec2 normal)
void OnExit (UnitPtr unit)
SValue ServerExecute ()
void ClientExecute (SValue@ val)
UnitPtr GetUseUnit ()
bool CanUse (PlayerBase@ player)
bool AnyClosedDoors ()
bool OpenDoor (UnitPtr user, bool force=false)
void Use (PlayerBase@ player)
void NetUse (PlayerHusk@ player)
UsableIcon GetIcon (Player@ player)
int UsePriority (IUsable@ other)
Private Attributes
array< CollisionArea@> UseAreas
string KeyFlag
UnitFeed DoorUnits
string OpenScene
SoundEvent SoundDenied
SoundEvent SoundGranted
SoundEvent SoundOpen
int AnnounceDelay
int AnnounceDelayC
string AnnounceFont
SoundEvent AnnounceSound
Detailed Description
Definition at line 4 of file Door.as.
Member Function Documentation
Announce()
void WorldScript::Door::Announce () inline private
Definition at line 58 of file Door.as.
References HUD::Announce(), AnnounceFont, AnnounceSound, GetHUD(), KeyFlag, AnnounceParams::m_anchor, AnnounceParams::m_font, AnnounceParams::m_text, and PlaySound2D().
Referenced by OpenDoor(), and Update().
         {
             HUD@ hud = GetHUD();
             if (hud is null)
                 return;
             AnnounceParams params;
             params.m_text = Resources::GetString(".meta.info.need." + KeyFlag);
             params.m_font = AnnounceFont;
             params.m_anchor.y = 0.2;
             hud.Announce(params);
             PlaySound2D(AnnounceSound);
         }
AnyClosedDoors()
bool WorldScript::Door::AnyClosedDoors () inline private
Definition at line 129 of file Door.as.
References DoorUnits, and OpenScene.
Referenced by OpenDoor().
         {
             array<UnitPtr>@ units = DoorUnits.FetchAll();
             for (uint i = 0; i < units.length(); i++)
             {
                 UnitScene@ currScene = units[i].GetCurrentUnitScene();
                 if (currScene.GetName() != OpenScene)
                     return true;
             }
             return false;
         }
CanUse()
bool WorldScript::Door::CanUse (PlayerBase@ player) inline private
Definition at line 124 of file Door.as.
         {
             return true;
         }
ClientExecute()
void WorldScript::Door::ClientExecute (SValue@ val) inline private
Definition at line 115 of file Door.as.
         {
         }
GetIcon()
UsableIcon WorldScript::Door::GetIcon (Player@ player) inline private
Definition at line 187 of file Door.as.
References Generic.
         {
             return UsableIcon::Generic;
         }
GetPlayer()
Player WorldScript::Door::GetPlayer (UnitPtr unit) inline private
Definition at line 83 of file Door.as.
References unit.
Referenced by OnEnter(), and OnExit().
         {
             if (!unit.IsValid())
                 return null;
             ref@ behavior = unit.GetScriptBehavior();
             if (behavior is null)
                 return null;
             return cast<Player>(behavior);
         }
GetUseUnit()
UnitPtr WorldScript::Door::GetUseUnit () inline private
Definition at line 119 of file Door.as.
References g_scene.
         {
             return WorldScript::GetWorldScript(g_scene, this).GetUnit();
         }
Initialize()
void WorldScript::Door::Initialize () inline private
Definition at line 37 of file Door.as.
References AnnounceSound, SoundDenied, SoundGranted, SoundOpen, and UseAreas.
         {
             if (SoundDenied is null)
                 @SoundDenied = Resources::GetSoundEvent("event:/misc/denied");
             if (SoundGranted is null)
                 @SoundGranted = Resources::GetSoundEvent("event:/misc/granted");
             if (SoundOpen is null)
                 @SoundOpen = Resources::GetSoundEvent("event:/misc/gate");
             if (AnnounceSound is null)
                 @AnnounceSound = Resources::GetSoundEvent("event:/misc/world-reminder");
             for (uint i = 0; i < UseAreas.length(); i++)
             {
                 UseAreas[i].AddOnEnter(this, "OnEnter");
                 UseAreas[i].AddOnExit(this, "OnExit");
             }
         }
NetUse()
void WorldScript::Door::NetUse (PlayerHusk@ player) inline private
Definition at line 182 of file Door.as.
References Use().
         {
             Use(player);
         }
OnEnter()
void WorldScript::Door::OnEnter (UnitPtr unit, vec2 pos, vec2 normal) inline private
Definition at line 96 of file Door.as.
References Player::AddUsable(), GetPlayer(), and unit.
         {
             Player@ plr = GetPlayer(unit);
             if (plr !is null)
                 plr.AddUsable(this);
         }
OnExit()
void WorldScript::Door::OnExit (UnitPtr unit) inline private
Definition at line 103 of file Door.as.
References GetPlayer(), Player::RemoveUsable(), and unit.
         {
             Player@ plr = GetPlayer(unit);
             if (plr !is null)
                 plr.RemoveUsable(this);
         }
OpenDoor()
bool WorldScript::Door::OpenDoor (UnitPtr user, bool force = false) inline private
Definition at line 141 of file Door.as.
References Announce(), AnnounceDelay, AnnounceDelayC, AnyClosedDoors(), DoorUnits, force, g_flags, KeyFlag, OpenScene, PlaySound3D(), SoundDenied, SoundGranted, and SoundOpen.
Referenced by Use().
         {
             if (!AnyClosedDoors())
                 return false;
             if (!force && KeyFlag != "" && !g_flags.IsSet(KeyFlag))
             {
                 PlaySound3D(SoundDenied, user.GetPosition());
                 if (AnnounceDelay > 0)
                 {
                     if (AnnounceDelayC <= 0)
                         AnnounceDelayC = AnnounceDelay;
                 }
                 else
                     Announce();
                 return false;
             }
             PlaySound3D(SoundGranted, user.GetPosition());
             array<UnitPtr>@ units = DoorUnits.FetchAll();
             for (uint i = 0; i < units.length(); i++)
             {
                 UnitPtr unitDoor = units[i];
                 unitDoor.SetUnitScene(OpenScene, true);
                 PlaySound3D(SoundOpen, unitDoor.GetPosition());
             }
             return true;
         }
ServerExecute()
SValue WorldScript::Door::ServerExecute () inline private
Definition at line 110 of file Door.as.
         {
             return null;
         }
Update()
void WorldScript::Door::Update (int dt) inline private
Definition at line 73 of file Door.as.
References Announce(), and AnnounceDelayC.
         {
             if (AnnounceDelayC > 0)
             {
                 AnnounceDelayC -= dt;
                 if (AnnounceDelayC <= 0)
                     Announce();
             }
         }
Use()
void WorldScript::Door::Use (PlayerBase@ player) inline private
Definition at line 173 of file Door.as.
References g_scene, and OpenDoor().
Referenced by NetUse().
         {
             if (!OpenDoor(player.m_unit))
                 return;
             if (Network::IsServer())
                 WorldScript::GetWorldScript(g_scene, this).Execute();
         }
UsePriority()
int WorldScript::Door::UsePriority (IUsable@ other) inline private
Definition at line 192 of file Door.as.
 { return 0; }
Member Data Documentation
AnnounceDelay
int WorldScript::Door::AnnounceDelay private
Definition at line 28 of file Door.as.
Referenced by OpenDoor().
AnnounceDelayC
int WorldScript::Door::AnnounceDelayC private
Definition at line 29 of file Door.as.
Referenced by OpenDoor(), and Update().
AnnounceFont
string WorldScript::Door::AnnounceFont private
Definition at line 32 of file Door.as.
Referenced by Announce().
AnnounceSound
SoundEvent WorldScript::Door::AnnounceSound private
Definition at line 35 of file Door.as.
Referenced by Announce(), and Initialize().
DoorUnits
UnitFeed WorldScript::Door::DoorUnits private
Definition at line 13 of file Door.as.
Referenced by AnyClosedDoors(), and OpenDoor().
KeyFlag
string WorldScript::Door::KeyFlag private
Definition at line 10 of file Door.as.
Referenced by Announce(), and OpenDoor().
OpenScene
string WorldScript::Door::OpenScene private
Definition at line 16 of file Door.as.
Referenced by AnyClosedDoors(), and OpenDoor().
SoundDenied
SoundEvent WorldScript::Door::SoundDenied private
Definition at line 19 of file Door.as.
Referenced by Initialize(), and OpenDoor().
SoundGranted
SoundEvent WorldScript::Door::SoundGranted private
Definition at line 22 of file Door.as.
Referenced by Initialize(), and OpenDoor().
SoundOpen
SoundEvent WorldScript::Door::SoundOpen private
Definition at line 25 of file Door.as.
Referenced by Initialize(), and OpenDoor().
UseAreas
array<CollisionArea@> WorldScript::Door::UseAreas private
Definition at line 7 of file Door.as.
Referenced by Initialize().
The documentation for this class was generated from the following file:
scripts/WorldScript/Door.as