HoHDocs: Menu::SplitscreenOptionsMenu Class Reference
Menu::SplitscreenOptionsMenu Class Reference
Private Member Functions
SplitscreenOptionsMenu (MenuProvider@ provider, SplitscreenSelectionMenu@ splitscreenMenu)
void Initialize (GUIDef@ def) override
void UpdateDifficultyTexts ()
void OnFunc (Widget@ sender, string name) override
Private Attributes
SplitscreenSelectionMenu m_splitscreenMenu
Detailed Description
Definition at line 3 of file SplitscreenOptionsMenu.as.
Constructor & Destructor Documentation
SplitscreenOptionsMenu()
Menu::SplitscreenOptionsMenu::SplitscreenOptionsMenu (MenuProvider@ provider, SplitscreenSelectionMenu@ splitscreenMenu) inline private
Definition at line 7 of file SplitscreenOptionsMenu.as.
References Menu::Menu::m_isPopup, and m_splitscreenMenu.
         {
             super(provider);
             m_isPopup = true;
             @m_splitscreenMenu = splitscreenMenu;
         }
Member Function Documentation
Initialize()
void Menu::SplitscreenOptionsMenu::Initialize (GUIDef@ def) inline override private
Definition at line 16 of file SplitscreenOptionsMenu.as.
References Menu::Menu::Initialize(), and UpdateDifficultyTexts().
         {
             Menu::Initialize(def);
             UpdateDifficultyTexts();
         }
OnFunc()
void Menu::SplitscreenOptionsMenu::OnFunc (Widget@ sender, string name) inline override private
Definition at line 48 of file SplitscreenOptionsMenu.as.
References m_splitscreenMenu, name, Menu::Menu::OnFunc(), and UpdateDifficultyTexts().
         {
             auto parse = name.split(" ");
             if (parse[0] == "host-set-difficulty")
             {
                 m_splitscreenMenu.OnFunc(sender, "change-difficulty");
                 UpdateDifficultyTexts();
             }
             else if (parse[0] == "setcustom" || parse[0] == "set-mod")
                 m_splitscreenMenu.OnFunc(sender, name);
             else
             {
                 if (name == "back")
                 {
                     //TODO..?
                     //m_splitscreenMenu.LobbyDataUpdate(true);
                 }
                 Menu::OnFunc(sender, name);
             }
         }
UpdateDifficultyTexts()
void Menu::SplitscreenOptionsMenu::UpdateDifficultyTexts () inline private
Definition at line 23 of file SplitscreenOptionsMenu.as.
References Easy, Hard, m_splitscreenMenu, m_widget, Normal, Serious, ButtonWidget::SetEnabled(), TextWidget::SetText(), and ButtonWidget::SetText().
Referenced by Initialize(), and OnFunc().
         {
             ButtonWidget@ wDiff = cast<ButtonWidget>(m_widget.GetWidgetById("host-set-difficulty"));
             if (wDiff !is null)
             {
                 string diffName = m_splitscreenMenu.GetDifficultyName(m_splitscreenMenu.m_startDifficulty);
                 wDiff.SetText(Resources::GetString(".menu.lobby.info.difficulty") + " " + utf8string(diffName).toUpper().plain());
                 wDiff.SetEnabled(true);
             }
             TextWidget@ wDesc = cast<TextWidget>(m_widget.GetWidgetById("option-diff-desc"));
             if (wDesc !is null)
             {
                 string diff;
                 switch (m_splitscreenMenu.m_startDifficulty)
                 {
                     case GameDifficulty::Easy: diff = Resources::GetString(".menu.splayer.difficulty.easy.desc"); break;
                     case GameDifficulty::Normal: diff = Resources::GetString(".menu.splayer.difficulty.normal.desc"); break;
                     case GameDifficulty::Hard: diff = Resources::GetString(".menu.splayer.difficulty.hard.desc"); break;
                     case GameDifficulty::Serious: diff = Resources::GetString(".menu.splayer.difficulty.serious.desc"); break;
                 }
                 wDesc.SetText(diff);
             }
         }
Member Data Documentation
m_splitscreenMenu
SplitscreenSelectionMenu Menu::SplitscreenOptionsMenu::m_splitscreenMenu private
Definition at line 5 of file SplitscreenOptionsMenu.as.
Referenced by OnFunc(), SplitscreenOptionsMenu(), and UpdateDifficultyTexts().
The documentation for this class was generated from the following file:
scripts/GUI/Menus/SplitscreenOptionsMenu.as