HoHDocs: Menu::HostMenu Class Reference
Menu::HostMenu Class Reference
Private Member Functions
HostMenu (MenuProvider@ provider)
void Initialize (GUIDef@ def) override
void UpdateNgp ()
void OnFunc (Widget@ sender, string name) override
Private Attributes
ScalableSpriteButtonWidget m_wButtonOK
TextInputWidget m_wName
SliderWidget m_wMaxPlayers
SliderWidget m_wMaxLevel
SliderWidget m_wMinLevel
TextWidget m_wNgp
SpriteButtonWidget m_wNgpLeft
SpriteButtonWidget m_wNgpRight
Detailed Description
Definition at line 3 of file HostMenu.as.
Constructor & Destructor Documentation
HostMenu()
Menu::HostMenu::HostMenu (MenuProvider@ provider) inline private
Definition at line 16 of file HostMenu.as.
         {
             super(provider);
         }
Member Function Documentation
Initialize()
void Menu::HostMenu::Initialize (GUIDef@ def) inline override private
Definition at line 21 of file HostMenu.as.
References g_gameMode, HwrSaves::GetCharacters(), GetPlayerName(), Menu::Menu::Initialize(), m_hostPrivate, m_wButtonOK, m_widget, m_wMaxLevel, m_wMaxPlayers, m_wMinLevel, m_wName, m_wNgp, m_wNgpLeft, m_wNgpRight, TextInputWidget::SetText(), and UpdateNgp().
         {
             Menu::Initialize(def);
             @m_wButtonOK = cast<ScalableSpriteButtonWidget>(m_widget.GetWidgetById("ok"));
             @m_wName = cast<TextInputWidget>(m_widget.GetWidgetById("name"));
             if (m_wName !is null)
                 m_wName.SetText(Resources::GetString(".mainmenu.host.name", { { "name", Lobby::GetPlayerName(0) } }));
             @m_wMaxPlayers = cast<SliderWidget>(m_widget.GetWidgetById("max-players"));
             if (m_wMaxPlayers !is null)
             {
                 int maxLimit = GetVarInt("g_multiplayer_limit");
                 if (maxLimit < 4)
                     maxLimit = 4;
                 m_wMaxPlayers.m_max = float(maxLimit);
                 m_wMaxPlayers.m_default = float(maxLimit);
                 m_wMaxPlayers.Reset();
             }
             @m_wMaxLevel = cast<SliderWidget>(m_widget.GetWidgetById("max-level"));
             @m_wMinLevel = cast<SliderWidget>(m_widget.GetWidgetById("min-level"));
             int highestLevel = int(m_wMaxLevel.m_max);
             auto arrCharacters = HwrSaves::GetCharacters();
             for (uint i = 0; i < arrCharacters.length(); i++)
             {
                 auto svChar = arrCharacters[i];
                 int level = GetParamInt(UnitPtr(), svChar, "level", false, 1);
                 if (level > highestLevel)
                     highestLevel = level;
             }
             m_wMaxLevel.m_max = (floor(float(highestLevel) / 10.0f) + 1) * 10.0f;
             m_wMaxLevel.UpdateText();
             @m_wNgp = cast<TextWidget>(m_widget.GetWidgetById("ngp"));
             @m_wNgpLeft = cast<SpriteButtonWidget>(m_widget.GetWidgetById("ngp-left"));
             @m_wNgpRight = cast<SpriteButtonWidget>(m_widget.GetWidgetById("ngp-right"));
             UpdateNgp();
             cast<MainMenu>(g_gameMode).m_hostPrivate = false;
         }
OnFunc()
void Menu::HostMenu::OnFunc (Widget@ sender, string name) inline override private
Definition at line 78 of file HostMenu.as.
References CreateLobby(), g_gameMode, ScalableSpriteButtonWidget::m_enabled, m_hostDownscaling, m_hostPrivate, TextInputWidget::m_text, m_wButtonOK, m_wMaxLevel, m_wMaxPlayers, m_wMinLevel, m_wName, name, Menu::Menu::OnFunc(), and UpdateNgp().
         {
             if (name == "privacy-changed")
             {
                 auto checkable = cast<ICheckableWidget>(sender);
                 cast<MainMenu>(g_gameMode).m_hostPrivate = (checkable.IsChecked());
             }
             else if (name == "host")
             {
                 auto gm = cast<MainMenu>(g_gameMode);
                 gm.m_hostName = m_wName.m_text.plain();
                 gm.m_hostMaxPlayers = m_wMaxPlayers.GetValueInt();
                 gm.m_hostMaxLevel = m_wMaxLevel.GetValueInt();
                 gm.m_hostMinLevel = m_wMinLevel.GetValueInt();
                 m_wButtonOK.m_enabled = false;
                 Lobby::CreateLobby();
             }
             else if (name == "levels-changed")
             {
                 float maxLevel = m_wMaxLevel.m_value;
                 float minLevel = m_wMinLevel.m_value;
                 if (minLevel > maxLevel)
                     m_wMinLevel.SetValue(maxLevel);
             }
             else if (name == "ngp-prev")
             {
                 auto gm = cast<MainMenu>(g_gameMode);
                 gm.m_hostNgp--;
                 if (gm.m_hostNgp < 0)
                     gm.m_hostNgp = 0;
                 UpdateNgp();
             }
             else if (name == "ngp-next")
             {
                 auto gm = cast<MainMenu>(g_gameMode);
                 gm.m_hostNgp++;
                 if (gm.m_hostNgp > gm.m_town.m_highestNgp)
                     gm.m_hostNgp = gm.m_town.m_highestNgp;
                 UpdateNgp();
             }
             else if (name == "downscaling-changed")
             {
                 auto checkable = cast<ICheckableWidget>(sender);
                 cast<MainMenu>(g_gameMode).m_hostDownscaling = (checkable.IsChecked());
             }
             else
                 Menu::OnFunc(sender, name);
         }
UpdateNgp()
void Menu::HostMenu::UpdateNgp () inline private
Definition at line 67 of file HostMenu.as.
References Menu::DoLayout(), g_gameMode, SpriteButtonWidget::m_enabled, m_wNgp, m_wNgpLeft, m_wNgpRight, and TextWidget::SetText().
Referenced by Initialize(), and OnFunc().
         {
             auto gm = cast<MainMenu>(g_gameMode);
             m_wNgp.SetText("+" + gm.m_hostNgp);
             m_wNgpLeft.m_enabled = (gm.m_hostNgp > 0);
             m_wNgpRight.m_enabled = (gm.m_hostNgp < gm.m_town.m_highestNgp);
             DoLayout();
         }
Member Data Documentation
m_wButtonOK
ScalableSpriteButtonWidget Menu::HostMenu::m_wButtonOK private
Definition at line 5 of file HostMenu.as.
Referenced by Initialize(), and OnFunc().
m_wMaxLevel
SliderWidget Menu::HostMenu::m_wMaxLevel private
Definition at line 9 of file HostMenu.as.
Referenced by Initialize(), and OnFunc().
m_wMaxPlayers
SliderWidget Menu::HostMenu::m_wMaxPlayers private
Definition at line 8 of file HostMenu.as.
Referenced by Initialize(), and OnFunc().
m_wMinLevel
SliderWidget Menu::HostMenu::m_wMinLevel private
Definition at line 10 of file HostMenu.as.
Referenced by Initialize(), and OnFunc().
m_wName
TextInputWidget Menu::HostMenu::m_wName private
Definition at line 6 of file HostMenu.as.
Referenced by Initialize(), and OnFunc().
m_wNgp
TextWidget Menu::HostMenu::m_wNgp private
Definition at line 12 of file HostMenu.as.
Referenced by Initialize(), and UpdateNgp().
m_wNgpLeft
SpriteButtonWidget Menu::HostMenu::m_wNgpLeft private
Definition at line 13 of file HostMenu.as.
Referenced by Initialize(), and UpdateNgp().
m_wNgpRight
SpriteButtonWidget Menu::HostMenu::m_wNgpRight private
Definition at line 14 of file HostMenu.as.
Referenced by Initialize(), and UpdateNgp().
The documentation for this class was generated from the following file:
scripts/GUI/Menus/HostMenu.as