HoHDocs: Skills::Juggernaut Class Reference
Skills::Juggernaut Class Reference
Private Member Functions
Juggernaut (UnitPtr unit, SValue &params)
void Initialize (Actor@ owner, ScriptSprite@ icon, uint id) override
void OnCollide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxOther) override
Private Attributes
array< IEffect@> m_effects
Modifiers::TriggerEffect m_bash
uint m_cooldown
uint m_lastHitTime
UnitPtr m_lastUnit
Detailed Description
Definition at line 3 of file Juggernaut.as.
Constructor & Destructor Documentation
Juggernaut()
Skills::Juggernaut::Juggernaut (UnitPtr unit, SValue & params) inline private
Definition at line 12 of file Juggernaut.as.
References LoadEffects(), m_bash, m_cooldown, m_effects, Skills::m_owner, m_skills, and unit.
         {
             super(unit);
             @m_effects = LoadEffects(unit, params);
             m_cooldown = GetParamInt(unit, params, "cooldown", false, 1);
             auto stunningBlows = cast<Skills::PassiveSkill>(cast<PlayerBase>(m_owner).m_skills[5]);
             if (stunningBlows !is null)
                 @m_bash = cast<Modifiers::TriggerEffect>(stunningBlows.m_modifiers[0]);
         }
Member Function Documentation
Initialize()
void Skills::Juggernaut::Initialize (Actor@ owner, ScriptSprite@ icon, uint id) inline override private
Definition at line 25 of file Juggernaut.as.
References icon, Initialize(), m_effects, and PropagateWeaponInformation().
         {
             Skill::Initialize(owner, icon, id);
             PropagateWeaponInformation(m_effects, id + 1);
         }
OnCollide()
void Skills::Juggernaut::OnCollide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxOther) inline override private
Definition at line 31 of file Juggernaut.as.
References ApplyEffects(), g_scene, Hit, m_bash, m_cooldown, m_effects, m_lastHitTime, m_lastUnit, Skills::m_owner, Modifiers::TriggerEffect::TriggerEffects(), and unit.
         {
             if (fxOther.IsSensor())
                 return;
             auto nowT = g_scene.GetTime();
             if (m_lastUnit == unit)
             {
                 if ((m_lastHitTime + m_cooldown) > nowT)
                     return;
             }
             m_lastUnit = unit;
             auto player = cast<PlayerHusk>(unit.GetScriptBehavior());
             if (player !is null)
                 return;
             ApplyEffects(m_effects, m_owner, unit, pos, vec2(-normal.x, -normal.y), 1.0f, false, 0.0f, 0.0f, 1.0);
             m_lastHitTime = nowT;
             auto a = cast<Actor>(unit.GetScriptBehavior());
             if (m_bash !is null && a !is null && a.Team != m_owner.Team)
                 m_bash.TriggerEffects(cast<Player>(m_owner), a, Modifiers::EffectTrigger::Hit);
         }
Member Data Documentation
m_bash
Modifiers::TriggerEffect Skills::Juggernaut::m_bash private
Definition at line 6 of file Juggernaut.as.
Referenced by Juggernaut(), and OnCollide().
m_cooldown
uint Skills::Juggernaut::m_cooldown private
Definition at line 8 of file Juggernaut.as.
Referenced by Juggernaut(), and OnCollide().
m_effects
array<IEffect@> Skills::Juggernaut::m_effects private
Definition at line 5 of file Juggernaut.as.
Referenced by Initialize(), Juggernaut(), and OnCollide().
m_lastHitTime
uint Skills::Juggernaut::m_lastHitTime private
Definition at line 9 of file Juggernaut.as.
Referenced by OnCollide().
m_lastUnit
UnitPtr Skills::Juggernaut::m_lastUnit private
Definition at line 10 of file Juggernaut.as.
Referenced by OnCollide().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Skills/Juggernaut.as