HoHDocs: GiveExperience Class Reference
GiveExperience Class Reference
Private Member Functions
GiveExperience (UnitPtr unit, SValue &params)
void SetWeaponInformation (uint weapon)
int GetExp (PlayerRecord@ record)
bool Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
bool CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
Private Attributes
int m_exp
float m_expScalar
Detailed Description
Definition at line 1 of file GiveExperience.as.
Constructor & Destructor Documentation
GiveExperience()
GiveExperience::GiveExperience (UnitPtr unit, SValue & params) inline private
Definition at line 6 of file GiveExperience.as.
References m_exp, m_expScalar, and unit.
     {
         m_exp = GetParamInt(unit, params, "exp", false);
         m_expScalar = GetParamFloat(unit, params, "exp-scalar", false);
     }
Member Function Documentation
Apply()
bool GiveExperience::Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk) inline private
Definition at line 23 of file GiveExperience.as.
References CanApply(), and GetExp().
     {
         if (!CanApply(owner, target, pos, dir, intensity))
             return false;
         Player@ plr = cast<Player>(target.GetScriptBehavior());
         int amount = int(GetExp(plr.m_record) * intensity);
         plr.m_record.GiveExperience(amount);
         return true;
     }
CanApply()
bool GiveExperience::CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) inline override private
Definition at line 34 of file GiveExperience.as.
References GetExp().
Referenced by Apply().
     {
         if (!target.IsValid())
             return false;
         Player@ plr = cast<Player>(target.GetScriptBehavior());
         if (plr is null)
             return false;
         int amount = int(GetExp(plr.m_record) * intensity);
         if (amount <= 0)
             return false;
         return true;
     }
GetExp()
int GiveExperience::GetExp (PlayerRecord@ record) inline private
Definition at line 14 of file GiveExperience.as.
References m_exp, and m_expScalar.
Referenced by Apply(), and CanApply().
     {
         if (m_exp > 0)
             return m_exp;
         int xpStart = record.LevelExperience(record.level - 1);
         int xpEnd = record.LevelExperience(record.level) - xpStart;
         return int(m_expScalar * xpEnd);
     }
SetWeaponInformation()
void GiveExperience::SetWeaponInformation (uint weapon) inline private
Definition at line 12 of file GiveExperience.as.
 {}
Member Data Documentation
m_exp
int GiveExperience::m_exp private
Definition at line 3 of file GiveExperience.as.
Referenced by GetExp(), and GiveExperience().
m_expScalar
float GiveExperience::m_expScalar private
Definition at line 4 of file GiveExperience.as.
Referenced by GetExp(), and GiveExperience().
The documentation for this class was generated from the following file:
scripts/Behaviors/Effects/GiveExperience.as