HoHDocs: MeleeHit Class Reference
MeleeHit Class Reference
Private Member Functions
MeleeHit (UnitPtr unit, SValue &params)
void SetWeaponInformation (uint weapon)
bool NeedNetParams ()
bool DoAction (SValueBuilder@ builder, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity)
bool DoHit (Actor@ owner, vec2 pos, vec2 dir, float intensity, bool husk)
bool NetDoAction (SValue@ param, Actor@ owner, vec2 pos, vec2 dir)
void Update (int dt, int cooldown)
Private Attributes
array< IEffect@> m_effects
array< IEffect@> m_missEffects
float m_teamDmg
uint m_radius
int m_dist
string m_hitFx
SoundEvent m_damageSound
Detailed Description
Definition at line 1 of file MeleeHit.as.
Constructor & Destructor Documentation
MeleeHit()
MeleeHit::MeleeHit (UnitPtr unit, SValue & params) inline private
Definition at line 14 of file MeleeHit.as.
References LoadEffects(), m_damageSound, m_dist, m_effects, m_hitFx, m_missEffects, m_radius, m_teamDmg, and unit.
     {
         @m_effects = LoadEffects(unit, params);
         @m_missEffects = LoadEffects(unit, params, "miss-");
         m_teamDmg = GetParamFloat(unit, params, "team-dmg", false, 0);
         m_radius = GetParamInt(unit, params, "radius", false, 24);
         m_dist = GetParamInt(unit, params, "dist", false, m_radius);
         m_hitFx = GetParamString(unit, params, "hit-fx", false);
         @m_damageSound = Resources::GetSoundEvent(GetParamString(unit, params, "damage-sound", false));
     }
Member Function Documentation
DoAction()
bool MeleeHit::DoAction (SValueBuilder@ builder, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity) inline private
Definition at line 36 of file MeleeHit.as.
References DoHit(), g_scene, m_dist, Actor::m_unit, and xy().
     {
         vec2 shootPos = pos + dir * m_dist;
         auto res = g_scene.RaycastClosest(xy(owner.m_unit.GetPosition()), shootPos, ~0, RaycastType::Shot);
         UnitPtr hitUnit = res.FetchUnit(g_scene);
         if (hitUnit.IsValid() && hitUnit != owner.m_unit)
             shootPos = res.point - dir * 2.0f;
         builder.PushArray();
         builder.PushFloat(intensity);
         builder.PushVector2(shootPos);
         builder.PopArray();
         return DoHit(owner, shootPos, dir, intensity, false);
     }
DoHit()
bool MeleeHit::DoHit (Actor@ owner, vec2 pos, vec2 dir, float intensity, bool husk) inline private
Definition at line 52 of file MeleeHit.as.
References ApplyEffects(), g_scene, m_damageSound, m_effects, m_hitFx, m_missEffects, m_radius, m_teamDmg, Actor::m_unit, PlayEffect(), and PlaySound3D().
Referenced by DoAction(), and NetDoAction().
     {
         array<UnitPtr> hitUnits;
         bool hitSomething = false;
         const uint numRays = 14;
         for (uint i = 0; i < numRays; i++)
         {
             vec2 upos = pos + vec2(cos(i * TwoPI / numRays), sin(i * TwoPI / numRays)) * m_radius;
             RaycastResult rayResults = g_scene.RaycastClosest(pos, upos, ~0, RaycastType::Shot);
             auto hitUnit = rayResults.FetchUnit(g_scene);
             upos = rayResults.point;
             if (!hitUnit.IsValid())
                 continue;
             if (hitUnit == owner.m_unit)
                 continue;
             bool alreadyHit = false;
             for (uint j = 0; j < hitUnits.length(); j++)
             {
                 if (hitUnits[j] == hitUnit)
                 {
                     alreadyHit = true;
                     break;
                 }
             }
             if (alreadyHit)
                 continue;
             hitUnits.insertLast(hitUnit);
             ApplyEffects(m_effects, owner, hitUnit, upos, dir, intensity, husk, 0, m_teamDmg);
             hitSomething = true;
         }
         if (!hitSomething)
             ApplyEffects(m_missEffects, owner, UnitPtr(), pos, dir, intensity, husk, 0, m_teamDmg);
         else
             PlaySound3D(m_damageSound, owner.m_unit.GetPosition());
         dictionary ePs = { { 'angle', atan(dir.y, dir.x) } };
         PlayEffect(m_hitFx, pos, ePs);
         return true;
     }
NeedNetParams()
bool MeleeHit::NeedNetParams () inline private
Definition at line 34 of file MeleeHit.as.
 { return true; }
NetDoAction()
bool MeleeHit::NetDoAction (SValue@ param, Actor@ owner, vec2 pos, vec2 dir) inline private
Definition at line 101 of file MeleeHit.as.
References DoHit().
     {
         auto d = param.GetArray();
         auto intensity = d[0].GetFloat();
         auto shootPos = d[1].GetVector2();
         return DoHit(owner, shootPos, dir, intensity, true);
     }
SetWeaponInformation()
void MeleeHit::SetWeaponInformation (uint weapon) inline private
Definition at line 28 of file MeleeHit.as.
References m_effects, m_missEffects, and PropagateWeaponInformation().
     {
         PropagateWeaponInformation(m_effects, weapon);
         PropagateWeaponInformation(m_missEffects, weapon);
     }
Update()
void MeleeHit::Update (int dt, int cooldown) inline private
Definition at line 110 of file MeleeHit.as.
     {
     }
Member Data Documentation
m_damageSound
SoundEvent MeleeHit::m_damageSound private
Definition at line 12 of file MeleeHit.as.
Referenced by DoHit(), and MeleeHit().
m_dist
int MeleeHit::m_dist private
Definition at line 8 of file MeleeHit.as.
Referenced by DoAction(), and MeleeHit().
m_effects
array<IEffect@> MeleeHit::m_effects private
Definition at line 3 of file MeleeHit.as.
Referenced by DoHit(), MeleeHit(), and SetWeaponInformation().
m_hitFx
string MeleeHit::m_hitFx private
Definition at line 10 of file MeleeHit.as.
Referenced by DoHit(), and MeleeHit().
m_missEffects
array<IEffect@> MeleeHit::m_missEffects private
Definition at line 4 of file MeleeHit.as.
Referenced by DoHit(), MeleeHit(), and SetWeaponInformation().
m_radius
uint MeleeHit::m_radius private
Definition at line 7 of file MeleeHit.as.
Referenced by DoHit(), and MeleeHit().
m_teamDmg
float MeleeHit::m_teamDmg private
Definition at line 6 of file MeleeHit.as.
Referenced by DoHit(), and MeleeHit().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actions/MeleeHit.as