HoHDocs: ButtonWidget Class Reference
ButtonWidget Class Reference
Private Member Functions
ButtonWidget ()
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void SetText (string str)
void SetText (string str, vec4 color)
void SetText (string str, vec4 color, TextAlignment align)
void SetEnabled (bool enabled)
void SetColor (vec4 color)
bool OnClick (vec2 mousePos) override
void OnMouseEnter (vec2 mousePos, bool forced) override
void OnMouseLeave (vec2 mousePos) override
void DoDraw (SpriteBatch &sb, vec2 pos) override
void ShowTooltip () override
Private Attributes
string m_func
string m_funcHover
BitmapFont m_font
vec4 m_textColor
vec4 m_textColorHover
vec4 m_textColorDisabled
bool m_textWrapping
string m_text
TextAlignment m_alignment = TextAlignment::Center
string m_textCurrent
bool m_enabled
vec2 m_textOffset
BitmapString m_renderText
Sprite m_sprite
SoundEvent m_pressSound
SoundEvent m_hoverSound
Detailed Description
Definition at line 1 of file ButtonWidget.as.
Constructor & Destructor Documentation
ButtonWidget()
ButtonWidget::ButtonWidget () inline private
Definition at line 25 of file ButtonWidget.as.
Referenced by Clone().
     {
         super();
     }
Member Function Documentation
Clone()
Widget ButtonWidget::Clone () inline override private
Definition at line 30 of file ButtonWidget.as.
References ButtonWidget(), and Widget::CloneInto().
     {
         ButtonWidget@ w = ButtonWidget();
         CloneInto(w);
         return w;
     }
DoDraw()
void ButtonWidget::DoDraw (SpriteBatch & sb, vec2 pos) inline override private
Definition at line 157 of file ButtonWidget.as.
References RectWidget::DoDraw().
     {
         RectWidget::DoDraw(sb, pos);
         if (m_renderText !is null)
         {
             int wText = int(m_renderText.GetWidth());
             int hText = int(m_renderText.GetHeight());
             if (m_alignment == TextAlignment::Left)
             {
                 sb.DrawString(vec2(
                     int(pos.x + m_textOffset.x),
                     int(pos.y + m_textOffset.y + m_height / 2 - hText / 2)
                 ), m_renderText);
             }
             else if (m_alignment == TextAlignment::Center)
             {
                 sb.DrawString(vec2(
                     int(pos.x + m_textOffset.x + m_width / 2 - wText / 2),
                     int(pos.y + m_textOffset.y + m_height / 2 - hText / 2)
                 ), m_renderText);
             }
             else if (m_alignment == TextAlignment::Right)
             {
                 sb.DrawString(vec2(
                     int(pos.x + m_textOffset.x + m_width - wText),
                     int(pos.y + m_textOffset.y + m_height / 2 - hText / 2)
                 ), m_renderText);
             }
         }
         if (m_sprite !is null)
         {
             float wSprite = m_sprite.GetWidth();
             float hSprite = m_sprite.GetHeight();
             sb.DrawSprite(vec2(
                 pos.x + m_width / 2 - wSprite / 2,
                 pos.y + m_height / 2 - hSprite / 2
             ), m_sprite, g_menuTime);
         }
     }
Load()
void ButtonWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 37 of file ButtonWidget.as.
References Center, Left, Widget::Load(), RectWidget::m_borderColor, RectWidget::m_borderWidth, Widget::m_canFocus, m_enabled, m_font, m_func, m_funcHover, m_hoverSound, m_pressSound, m_sprite, m_text, m_textColor, m_textColorDisabled, m_textColorHover, m_textOffset, m_textWrapping, Right, and SetText().
Referenced by LoadButtonWidget().
     {
         auto def = ctx.GetGUIDef();
         m_func = ctx.GetString("func", false);
         m_funcHover = ctx.GetString("func-hover", false);
         string fnmFont = ctx.GetString("font", false);
         if (fnmFont != "")
             @m_font = Resources::GetBitmapFont(fnmFont);
         m_textOffset = ctx.GetVector2("textoffset", false, m_textOffset);
         m_textColor = ctx.GetColorRGBA("textcolor", false, vec4(0, 0.82, 1, 1));
         m_textColorHover = ctx.GetColorRGBA("textcolor-hover", false, vec4(1, 1, 1, 1));
         m_textColorDisabled = ctx.GetColorRGBA("textcolor-disabled", false, vec4(0, 0.41, 0.5, 0.8));
         m_textWrapping = ctx.GetBoolean("textwrapping", false, true);
         m_text = Resources::GetString(ctx.GetString("text", false));
         TextAlignment align = TextAlignment::Center;
         string alignStr = ctx.GetString("align", false);
         if (alignStr == "left")
             align = TextAlignment::Left;
         else if (alignStr == "right")
             align = TextAlignment::Right;
         m_enabled = ctx.GetBoolean("enabled", false, true);
         auto sprite = ctx.GetString("sprite", false);
         if (sprite != "")
             @m_sprite = def.GetSprite(sprite);
         @m_pressSound = Resources::GetSoundEvent("event:/ui/button_click");
         @m_hoverSound = Resources::GetSoundEvent("event:/ui/button_hover");
         RectWidget::Load(ctx);
         m_borderColor = ctx.GetColorRGBA("border", false);
         m_borderWidth = ctx.GetInteger("borderwidth", false);
         SetText(m_text, m_enabled ? m_textColor : m_textColorDisabled, align);
         m_canFocus = true;
     }
OnClick()
bool ButtonWidget::OnClick (vec2 mousePos) inline override private
Definition at line 123 of file ButtonWidget.as.
References m_enabled, m_func, Widget::m_host, m_pressSound, and PlaySound2D().
     {
         if (!m_enabled)
             return false;
         m_host.OnFunc(this, m_func);
         PlaySound2D(m_pressSound);
         return true;
     }
OnMouseEnter()
void ButtonWidget::OnMouseEnter (vec2 mousePos, bool forced) inline override private
Definition at line 133 of file ButtonWidget.as.
References m_enabled, m_func, m_funcHover, Widget::m_host, m_hoverSound, m_textColorHover, Widget::OnMouseEnter(), PlaySound2D(), and SetColor().
     {
         if (m_enabled)
         {
             PlaySound2D(m_hoverSound);
             SetColor(m_textColorHover);
             if (m_funcHover != "")
                 m_host.OnFunc(this, m_func);
         }
         RectWidget::OnMouseEnter(mousePos, forced);
     }
OnMouseLeave()
void ButtonWidget::OnMouseLeave (vec2 mousePos) inline override private
Definition at line 147 of file ButtonWidget.as.
References m_enabled, m_textColor, m_textColorDisabled, Widget::OnMouseLeave(), and SetColor().
     {
         if (m_enabled)
             SetColor(m_textColor);
         else
             SetColor(m_textColorDisabled);
         RectWidget::OnMouseLeave(mousePos);
     }
SetColor()
void ButtonWidget::SetColor (vec4 color) inline private
Definition at line 117 of file ButtonWidget.as.
Referenced by ButtonWidget(), MenuControlInputWidget::Load(), OnMouseEnter(), and OnMouseLeave().
     {
         if (m_renderText !is null)
             m_renderText.SetColor(color);
     }
SetEnabled()
void ButtonWidget::SetEnabled (bool enabled) inline private
Definition at line 103 of file ButtonWidget.as.
Referenced by Menu::SplitscreenOptionsMenu::UpdateDifficultyTexts().
     {
         m_enabled = enabled;
         if (m_enabled)
         {
             if (m_hovering)
                 SetColor(m_textColorHover);
             else
                 SetColor(m_textColor);
         }
         else
             SetColor(m_textColorDisabled);
     }
SetText() [1/3]
void ButtonWidget::SetText (string str) inline private
Definition at line 78 of file ButtonWidget.as.
References m_alignment, and m_textColor.
Referenced by Load(), and Menu::SplitscreenOptionsMenu::UpdateDifficultyTexts().
     {
         SetText(str, m_textColor, m_alignment);
     }
SetText() [2/3]
void ButtonWidget::SetText (string str, vec4 color) inline private
Definition at line 83 of file ButtonWidget.as.
     {
         SetText(str, color, m_alignment);
     }
SetText() [3/3]
void ButtonWidget::SetText (string str, vec4 color, TextAlignment align) inline private
Definition at line 88 of file ButtonWidget.as.
     {
         m_textCurrent = str;
         m_alignment = align;
         if (m_font is null)
             return;
         int width = m_width;
         if (!m_textWrapping)
             width = -1;
         @m_renderText = m_font.BuildText(str, width, align);
         SetColor(color);
     }
ShowTooltip()
void ButtonWidget::ShowTooltip () inline override private
Definition at line 199 of file ButtonWidget.as.
     {
         m_tooltipEnabled = m_enabled;
         RectWidget::ShowTooltip();
     }
Member Data Documentation
m_alignment
TextAlignment ButtonWidget::m_alignment = TextAlignment::Center private
Definition at line 12 of file ButtonWidget.as.
Referenced by SetText().
m_enabled
bool ButtonWidget::m_enabled private
Definition at line 14 of file ButtonWidget.as.
Referenced by Load(), OnClick(), OnMouseEnter(), OnMouseLeave(), and SetColor().
m_font
BitmapFont ButtonWidget::m_font private
Definition at line 6 of file ButtonWidget.as.
Referenced by Load().
m_func
string ButtonWidget::m_func private
Definition at line 3 of file ButtonWidget.as.
Referenced by MenuControlInputWidget::ExpectedInput(), MenuControlInputWidget::GetBindings(), Load(), MenuControlInputWidget::OnClick(), OnClick(), and OnMouseEnter().
m_funcHover
string ButtonWidget::m_funcHover private
Definition at line 4 of file ButtonWidget.as.
Referenced by Load(), and OnMouseEnter().
m_hoverSound
SoundEvent ButtonWidget::m_hoverSound private
Definition at line 23 of file ButtonWidget.as.
Referenced by Load(), and OnMouseEnter().
m_pressSound
SoundEvent ButtonWidget::m_pressSound private
Definition at line 22 of file ButtonWidget.as.
Referenced by Load(), MenuControlInputWidget::OnClick(), and OnClick().
m_renderText
BitmapString ButtonWidget::m_renderText private
Definition at line 18 of file ButtonWidget.as.
Referenced by SetText().
m_sprite
Sprite ButtonWidget::m_sprite private
Definition at line 20 of file ButtonWidget.as.
Referenced by Load().
m_text
string ButtonWidget::m_text private
Definition at line 11 of file ButtonWidget.as.
Referenced by Load().
m_textColor
vec4 ButtonWidget::m_textColor private
Definition at line 7 of file ButtonWidget.as.
Referenced by ButtonWidget(), MenuControlInputWidget::Load(), Load(), OnMouseLeave(), and SetText().
m_textColorDisabled
vec4 ButtonWidget::m_textColorDisabled private
Definition at line 9 of file ButtonWidget.as.
Referenced by Load(), and OnMouseLeave().
m_textColorHover
vec4 ButtonWidget::m_textColorHover private
Definition at line 8 of file ButtonWidget.as.
Referenced by ButtonWidget(), MenuControlInputWidget::Load(), Load(), and OnMouseEnter().
m_textCurrent
string ButtonWidget::m_textCurrent private
Definition at line 13 of file ButtonWidget.as.
m_textOffset
vec2 ButtonWidget::m_textOffset private
Definition at line 16 of file ButtonWidget.as.
Referenced by Load(), and SetText().
m_textWrapping
bool ButtonWidget::m_textWrapping private
Definition at line 10 of file ButtonWidget.as.
Referenced by Load().
The documentation for this class was generated from the following file:
scripts/GUI/ButtonWidget.as