HoHDocs: ColorHSV Class Reference
ColorHSV Class Reference
Private Member Functions
ColorHSV ()
ColorHSV (float h, float s, float l)
ColorHSV (vec4 rgba)
ColorHSV (vec3 rgb)
void FromRGB (float r, float g, float b)
vec3 ToColorRGB ()
vec4 ToColorRGBA ()
Private Attributes
float m_hue
float m_saturation
float m_value
Detailed Description
Definition at line 2 of file ColorHSV.as.
Constructor & Destructor Documentation
ColorHSV() [1/4]
ColorHSV::ColorHSV () inline private
Definition at line 8 of file ColorHSV.as.
 {}
ColorHSV() [2/4]
ColorHSV::ColorHSV (float h, float s, float l) inline private
Definition at line 10 of file ColorHSV.as.
References m_hue, m_saturation, and m_value.
     {
         m_hue = h;
         m_saturation = s;
         m_value = l;
     }
ColorHSV() [3/4]
ColorHSV::ColorHSV (vec4 rgba) inline private
Definition at line 17 of file ColorHSV.as.
References FromRGB().
     {
         FromRGB(rgba.x, rgba.y, rgba.z);
     }
ColorHSV() [4/4]
ColorHSV::ColorHSV (vec3 rgb) inline private
Definition at line 22 of file ColorHSV.as.
References FromRGB().
     {
         FromRGB(rgb.x, rgb.y, rgb.z);
     }
Member Function Documentation
FromRGB()
void ColorHSV::FromRGB (float r, float g, float b) inline private
Definition at line 27 of file ColorHSV.as.
References m_hue, m_saturation, m_value, max, and min.
Referenced by ColorHSV().
     {
         float minn = min(min(r, g), b);
         float maxx = max(max(r, g), b);
         float delta = maxx - minn;
         if (maxx != 0 && delta != 0)
         {
             m_saturation = (delta / maxx) * 100.0f;
             if (r == maxx)
                 m_hue = (g - b) / delta;
             else
                 m_hue = (g == maxx) ? (2 + (b - r) / delta) : (4 + (r - g) / delta);
         }
         m_hue *= 60;
         if (m_hue < 0)
             m_hue += 360;
         m_value = maxx * 100.0f;
     }
ToColorRGB()
vec3 ColorHSV::ToColorRGB () inline private
Definition at line 46 of file ColorHSV.as.
References m_hue, m_saturation, and m_value.
Referenced by ToColorRGBA().
     {
         float r = 0, g = 0, b = 0;
         float h = m_hue % 360.0f;
         float s = m_saturation / 100.0f;
         float v = m_value / 100.0f;
         if (s == 0)
             r = g = b = v;
         else
         {
             float sPos = h / 60.0f;
             int sNum = int(floor(sPos));
             float fractional = sPos - float(sNum);
             float p = v * (1.0f - s);
             float q = v * (1.0f - s * fractional);
             float t = v * (1.0f - s * (1.0f - fractional));
             switch (sNum)
             {
                 case 0: r = v; g = t; b = p; break;
                 case 1: r = q; g = v; b = p; break;
                 case 2: r = p; g = v; b = t; break;
                 case 3: r = p; g = q; b = v; break;
                 case 4: r = t; g = p; b = v; break;
                 case 5: r = v; g = p; b = q; break;
             }
         }
         return vec3(r, g, b);
     }
ToColorRGBA()
vec4 ColorHSV::ToColorRGBA () inline private
Definition at line 75 of file ColorHSV.as.
References ToColorRGB().
Referenced by AddItem(), ReloadList(), and MultiplePlayersTab::UpdateNow().
     {
         vec3 ret = ToColorRGB();
         return vec4(ret.x, ret.y, ret.z, 1.0f);
     }
Member Data Documentation
m_hue
float ColorHSV::m_hue private
Definition at line 4 of file ColorHSV.as.
Referenced by ColorHSV(), FromRGB(), and ToColorRGB().
m_saturation
float ColorHSV::m_saturation private
Definition at line 5 of file ColorHSV.as.
Referenced by AddItem(), ColorHSV(), FromRGB(), ReloadList(), ToColorRGB(), and MultiplePlayersTab::UpdateNow().
m_value
float ColorHSV::m_value private
Definition at line 6 of file ColorHSV.as.
Referenced by AddItem(), ColorHSV(), FromRGB(), ReloadList(), ToColorRGB(), and MultiplePlayersTab::UpdateNow().
The documentation for this class was generated from the following file:
scripts/Utils/ColorHSV.as