HoHDocs: GuildHallAccomplishmentsTab Class Reference
GuildHallAccomplishmentsTab Class Reference
Private Member Functions
GuildHallAccomplishmentsTab ()
void OnShow () override
Widget AddHeader (string text)
void RefreshList ()
void AddBoss (int i)
Private Attributes
Widget m_wList
Widget m_wTemplateHeader
Widget m_wTemplateBar
Widget m_wTemplateVerticalSeparator
Widget m_wTemplateBoss
Widget m_wTemplateBossClass
int m_numBosses
Detailed Description
Definition at line 1 of file Accomplishments.as.
Constructor & Destructor Documentation
GuildHallAccomplishmentsTab()
GuildHallAccomplishmentsTab::GuildHallAccomplishmentsTab () inline private
Definition at line 13 of file Accomplishments.as.
References MenuTab::m_id.
     {
         m_id = "accomplishments";
     }
Member Function Documentation
AddBoss()
void GuildHallAccomplishmentsTab::AddBoss (int i) inline private
Definition at line 178 of file Accomplishments.as.
References Widget::AddChild(), AddHeader(), Widget::Clone(), g_gameMode, m_numBosses, m_wList, m_wTemplateBoss, m_wTemplateBossClass, and Widget::SetID().
Referenced by RefreshList().
     {
         auto wNewBoss = m_wTemplateBoss.Clone();
         wNewBoss.SetID("");
         wNewBoss.m_visible = true;
         auto gm = cast<Campaign>(g_gameMode);
         uint killedFlags = gm.m_townLocal.m_bossesKilled[i];
         auto wName = cast<TextWidget>(wNewBoss.GetWidgetById("name"));
         if (wName !is null)
             wName.SetText(Resources::GetString(".guildhall.accomplishments.boss-" + (i + 1)));
         bool anyHasKilled = false;
         bool showAllAccomplishmentsCheat = GetVarBool("show_all_accomplishments");
         if (showAllAccomplishmentsCheat)
             anyHasKilled = true;
         auto wClasses = wNewBoss.GetWidgetById("classes");
         if (wClasses !is null)
         {
             for (int j = 0; j < 7; j++)
             {
                 bool hasKilled = ((killedFlags & (1 << j)) != 0);
                 if (hasKilled)
                     anyHasKilled = true;
                 auto wNewBossClass = cast<SpriteWidget>(m_wTemplateBossClass.Clone());
                 wNewBossClass.SetID("");
                 wNewBossClass.m_visible = true;
                 string charClass = "";
                 switch (j)
                 {
                     case 0: charClass = "paladin"; break;
                     case 1: charClass = "ranger"; break;
                     case 2: charClass = "sorcerer"; break;
                     case 3: charClass = "warlock"; break;
                     case 4: charClass = "thief"; break;
                     case 5: charClass = "priest"; break;
                     case 6: charClass = "wizard"; break;
                 }
                 wNewBossClass.SetSprite("char-icon-" + charClass);
                 wNewBossClass.m_tooltipText = Resources::GetString(".class." + charClass);
                 wNewBossClass.m_tooltipEnabled = hasKilled;
                 if (hasKilled)
                 {
                     auto wNewBossClassCheck = wNewBossClass.GetWidgetById("check");
                     if (wNewBossClassCheck !is null)
                         wNewBossClassCheck.m_visible = true;
                 }
                 else
                     wNewBossClass.m_colorize = true;
                 wClasses.AddChild(wNewBossClass);
             }
         }
         if (anyHasKilled)
         {
             if (++m_numBosses == 1)
                 AddHeader(Resources::GetString(".guildhall.accomplishments.bosses"));
             m_wList.AddChild(wNewBoss);
         }
     }
AddHeader()
Widget GuildHallAccomplishmentsTab::AddHeader (string text) inline private
Definition at line 33 of file Accomplishments.as.
References Widget::AddChild(), Widget::Clone(), m_wList, m_wTemplateHeader, Widget::SetID(), and text.
Referenced by AddBoss(), and RefreshList().
     {
         auto wNewHeader = m_wTemplateHeader.Clone();
         wNewHeader.SetID("");
         wNewHeader.m_visible = true;
         auto wNewHeaderText = cast<TextWidget>(wNewHeader.GetWidgetById("text"));
         wNewHeaderText.SetText(text);
         m_wList.AddChild(wNewHeader);
         return wNewHeader;
     }
OnShow()
void GuildHallAccomplishmentsTab::OnShow () inline override private
Definition at line 18 of file Accomplishments.as.
References Widget::GetWidgetById(), MenuTab::m_widget, m_wList, m_wTemplateBar, m_wTemplateBoss, m_wTemplateBossClass, m_wTemplateHeader, m_wTemplateVerticalSeparator, MenuTab::OnShow(), and RefreshList().
     {
         GuildHallMenuTab::OnShow();
         @m_wList = m_widget.GetWidgetById("list");
         @m_wTemplateHeader = m_widget.GetWidgetById("template-header");
         @m_wTemplateBar = m_widget.GetWidgetById("template-bar");
         @m_wTemplateVerticalSeparator = m_widget.GetWidgetById("template-separator");
         @m_wTemplateBoss = m_widget.GetWidgetById("template-boss");
         @m_wTemplateBossClass = m_widget.GetWidgetById("template-boss-class");
         RefreshList();
     }
RefreshList()
void GuildHallAccomplishmentsTab::RefreshList () inline private
Definition at line 47 of file Accomplishments.as.
References AddBoss(), Widget::AddChild(), AddHeader(), Widget::ClearChildren(), Widget::Clone(), MenuTab::DoLayout(), formatThousands(), g_gameMode, Stats::Accomplishment::GetDescription(), Stats::Accomplishment::GetName(), ilerp(), MenuTab::m_def, Stats::Accomplishment::m_finished, Widget::m_height, m_numBosses, Widget::m_offset, Stats::Accomplishment::m_reputation, Stats::StatList::m_stats, Stats::Accomplishment::m_value, Widget::m_visible, m_wList, m_wTemplateBar, m_wTemplateVerticalSeparator, Widget::SetID(), and Stats::Stat().
Referenced by OnShow().
     {
         m_wList.ClearChildren();
         auto gm = cast<Campaign>(g_gameMode);
         if (gm is null)
             return;
         string lastCategory = "";
         Widget@ lastSeparatorLeft, lastSeparatorRight;
         int currentY = 0;
         bool showAllAccomplishmentsCheat = GetVarBool("show_all_accomplishments");
         Stats::StatList@ stats = gm.m_townLocal.m_statistics;
         for (uint i = 0; i < stats.m_stats.length(); i++)
         {
             Stats::Stat@ stat = stats.m_stats[i];
             if (stat.m_accomplishments.length() == 0)
                 continue;
             string categoryName = Resources::GetString(".stats.category." + stat.m_category);
             if (lastCategory != categoryName)
             {
                 auto wNewHeader = AddHeader(utf8string(categoryName).toUpper().plain());
                 currentY += wNewHeader.m_height;
                 lastCategory = categoryName;
                 @lastSeparatorLeft = m_wTemplateVerticalSeparator.Clone();
                 lastSeparatorLeft.SetID("");
                 lastSeparatorLeft.m_visible = true;
                 lastSeparatorLeft.m_offset = vec2(144, currentY);
                 m_wList.AddChild(lastSeparatorLeft);
                 @lastSeparatorRight = m_wTemplateVerticalSeparator.Clone();
                 lastSeparatorRight.SetID("");
                 lastSeparatorRight.m_visible = true;
                 lastSeparatorRight.m_offset = vec2(363, currentY);
                 m_wList.AddChild(lastSeparatorRight);
             }
             Stats::Accomplishment@ lastAccomplishment;
             int lastAccomplishmentIndex = -1;
             for (uint j = 0; j < stat.m_accomplishments.length(); j++)
             {
                 @lastAccomplishment = stat.m_accomplishments[j];
                 lastAccomplishmentIndex = j;
                 if (!stat.m_accomplishments[j].m_finished)
                     break;
             }
             string accomplishmentName = lastAccomplishment.GetName();
             auto wNewBar = m_wTemplateBar.Clone();
             wNewBar.SetID("");
             wNewBar.m_visible = true;
             currentY += wNewBar.m_height;
             bool hidden = (stat.ValueInt() == 0);
             if (showAllAccomplishmentsCheat)
                 hidden = false;
             auto wNewBarName = cast<TextWidget>(wNewBar.GetWidgetById("name"));
             if (hidden)
                 wNewBarName.SetText("?????");
             else
                 wNewBarName.SetText(accomplishmentName);
             auto wNewBarBar = cast<BarWidget>(wNewBar.GetWidgetById("bar"));
             if (!hidden)
             {
                 wNewBarBar.m_tooltipEnabled = true;
                 wNewBarBar.m_tooltipTitle = accomplishmentName;
                 wNewBarBar.m_tooltipText = lastAccomplishment.GetDescription();
                 wNewBarBar.AddTooltipSub(m_def.GetSprite("reputation-points"), formatThousands(lastAccomplishment.m_reputation));
             }
             auto wNewBarText = cast<TextWidget>(wNewBarBar.GetWidgetById("text"));
             if (hidden)
                 wNewBarText.SetText("? / ?");
             else
             {
                 if (lastAccomplishment.m_finished)
                 {
                     wNewBarBar.m_spriteRectVariation = 1;
                     wNewBarBar.SetScale(1.0f);
                     wNewBarText.SetText(formatThousands(stat.ValueInt()));
                 }
                 else
                 {
                     int goodStart = 0;
                     int goodEnd = lastAccomplishment.m_value;
                     if (lastAccomplishmentIndex > 0)
                         goodStart = stat.m_accomplishments[lastAccomplishmentIndex - 1].m_value;
                     float scale = ilerp(goodStart, goodEnd, stat.ValueInt());
                     wNewBarBar.SetScale(scale);
                     wNewBarText.SetText(stat.ToString(true) + " / " + stat.ToString(goodEnd, true));
                 }
             }
             m_wList.AddChild(wNewBar);
             lastSeparatorLeft.m_height += wNewBar.m_height;
             lastSeparatorRight.m_height += wNewBar.m_height;
         }
         m_numBosses = 0;
         for (int i = 0; i < 6; i++)
         {
             if (i == 4) // Thundersnow
                 continue;
             AddBoss(i);
         }
         AddBoss(4); // Thundersnow
         DoLayout();
     }
Member Data Documentation
m_numBosses
int GuildHallAccomplishmentsTab::m_numBosses private
Definition at line 11 of file Accomplishments.as.
Referenced by AddBoss(), and RefreshList().
m_wList
Widget GuildHallAccomplishmentsTab::m_wList private
Definition at line 3 of file Accomplishments.as.
Referenced by AddBoss(), AddHeader(), OnShow(), and RefreshList().
m_wTemplateBar
Widget GuildHallAccomplishmentsTab::m_wTemplateBar private
Definition at line 6 of file Accomplishments.as.
Referenced by OnShow(), and RefreshList().
m_wTemplateBoss
Widget GuildHallAccomplishmentsTab::m_wTemplateBoss private
Definition at line 8 of file Accomplishments.as.
Referenced by AddBoss(), and OnShow().
m_wTemplateBossClass
Widget GuildHallAccomplishmentsTab::m_wTemplateBossClass private
Definition at line 9 of file Accomplishments.as.
Referenced by AddBoss(), and OnShow().
m_wTemplateHeader
Widget GuildHallAccomplishmentsTab::m_wTemplateHeader private
Definition at line 5 of file Accomplishments.as.
Referenced by AddHeader(), and OnShow().
m_wTemplateVerticalSeparator
Widget GuildHallAccomplishmentsTab::m_wTemplateVerticalSeparator private
Definition at line 7 of file Accomplishments.as.
Referenced by OnShow(), and RefreshList().
The documentation for this class was generated from the following file:
scripts/GUI/GuildHall/Accomplishments.as