HoHDocs: SpawnEffect Class Reference
SpawnEffect Class Reference
Private Member Functions
SpawnEffect (UnitPtr unit, SValue &params)
bool NeedNetParams ()
void SetWeaponInformation (uint weapon)
bool DoAction (SValueBuilder@ builder, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity)
bool NetDoAction (SValue@ param, Actor@ owner, vec2 pos, vec2 dir)
bool Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
bool CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
void Do (vec2 pos)
void Update (int dt, int cooldown)
Private Attributes
UnitScene m_effect
Detailed Description
Definition at line 1 of file SpawnEffect.as.
Constructor & Destructor Documentation
SpawnEffect()
SpawnEffect::SpawnEffect (UnitPtr unit, SValue & params) inline private
Definition at line 5 of file SpawnEffect.as.
References Fountain::GetEffect(), m_effect, and unit.
     {
         @m_effect = Resources::GetEffect(GetParamString(unit, params, "effect"));
     }
Member Function Documentation
Apply()
bool SpawnEffect::Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk) inline private
Definition at line 25 of file SpawnEffect.as.
References Do().
     {
         Do(pos);
         return true;
     }
CanApply()
bool SpawnEffect::CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) inline override private
Definition at line 31 of file SpawnEffect.as.
     {
         return true;
     }
Do()
void SpawnEffect::Do (vec2 pos) inline private
Definition at line 36 of file SpawnEffect.as.
References m_effect, and PlayEffect().
Referenced by Apply(), DoAction(), and NetDoAction().
     {
         PlayEffect(m_effect, pos);
     }
DoAction()
bool SpawnEffect::DoAction (SValueBuilder@ builder, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity) inline private
Definition at line 13 of file SpawnEffect.as.
References Do().
     {
         Do(pos);
         return true;
     }
NeedNetParams()
bool SpawnEffect::NeedNetParams () inline private
Definition at line 10 of file SpawnEffect.as.
 { return false; }
NetDoAction()
bool SpawnEffect::NetDoAction (SValue@ param, Actor@ owner, vec2 pos, vec2 dir) inline private
Definition at line 19 of file SpawnEffect.as.
References Do().
     {
         Do(pos);
         return true;
     }
SetWeaponInformation()
void SpawnEffect::SetWeaponInformation (uint weapon) inline private
Definition at line 11 of file SpawnEffect.as.
 {}
Update()
void SpawnEffect::Update (int dt, int cooldown) inline private
Definition at line 43 of file SpawnEffect.as.
     {
     }
Member Data Documentation
m_effect
UnitScene SpawnEffect::m_effect private
Definition at line 3 of file SpawnEffect.as.
Referenced by Do(), and SpawnEffect().
The documentation for this class was generated from the following file:
scripts/Behaviors/Effects/SpawnEffect.as