HoHDocs: Titles::ClassTitles Class Reference
Titles::ClassTitles Class Reference
Private Member Functions
void AddClassTitles (string charClass)
TitleList GetList (string charClass)
Title GetTitle (string charClass, int index)
void RefreshModifiers (SValueBuilder &builder)
void NetRefreshModifiers (PlayerRecord@ record, SValue@ params)
Private Attributes
dictionary m_lists
Detailed Description
Definition at line 11 of file ClassTitles.as.
Member Function Documentation
AddClassTitles()
void Titles::ClassTitles::AddClassTitles (string charClass) inline private
Definition at line 15 of file ClassTitles.as.
References m_lists.
Referenced by Campaign::Campaign().
         {
             //print("Adding class titles for " + charClass);
             auto list = TitleList("tweak/titles/classes/" + charClass + ".sval");
             m_lists.set(charClass, @list);
         }
GetList()
TitleList Titles::ClassTitles::GetList (string charClass) inline private
Definition at line 23 of file ClassTitles.as.
References m_lists.
Referenced by GuildHallStatsTab::AddClassesClassToList(), GetTitle(), NetRefreshModifiers(), and RefreshModifiers().
         {
             TitleList@ list = null;
             m_lists.get(charClass, @list);
             return list;
         }
GetTitle()
Title Titles::ClassTitles::GetTitle (string charClass, int index) inline private
Definition at line 30 of file ClassTitles.as.
References GetList(), and Titles::TitleList::GetTitle().
Referenced by GuildHallStatsTab::AddClassesClassToList().
         {
             TitleList@ list = GetList(charClass);
             if (list is null)
             {
                 PrintError("Class titles list for \"" + charClass + "\" is not loaded!");
                 return null;
             }
             return list.GetTitle(index);
         }
NetRefreshModifiers()
void Titles::ClassTitles::NetRefreshModifiers (PlayerRecord@ record, SValue@ params) inline private
Definition at line 105 of file ClassTitles.as.
References GetList().
Referenced by PlayerHandler::PlayerTitleModifiers().
         {
             record.modifiersTitles.Clear();
             auto arrTitles = params.GetArray();
             for (uint i = 0; i < arrTitles.length(); i++)
             {
                 auto arrTitle = arrTitles[i].GetArray();
                 string charClass = arrTitle[0].GetString();
                 int titleIndex = arrTitle[1].GetInteger();
                 auto list = GetList(charClass);
                 if (list is null)
                 {
                     PrintError("Class titles list for \"" + charClass + "\" is not loaded!");
                     continue;
                 }
                 list.EnableTitleModifiers(record, titleIndex);
             }
         }
RefreshModifiers()
void Titles::ClassTitles::RefreshModifiers (SValueBuilder & builder) inline private
Definition at line 41 of file ClassTitles.as.
References HwrSaves::GetCharacters(), GetList(), GetLocalPlayerRecord(), Titles::GetMaxClassTitleIndex(), Fountain::HasEffect(), and max.
Referenced by Player::RefreshModifiers().
         {
             builder.PushArray();
             auto record = GetLocalPlayerRecord();
             record.modifiersTitles.Clear();
             if (Fountain::HasEffect("no_class_titles"))
             {
                 builder.PopArray();
                 return;
             }
             dictionary titles;
             auto characters = HwrSaves::GetCharacters();
             for (uint i = 0; i < characters.length(); i++)
             {
                 string charClass = GetParamString(UnitPtr(), characters[i], "class");
                 int titleIndex = GetParamInt(UnitPtr(), characters[i], "title", false, 0);
                 int64 best = titleIndex;
                 if (titles.get(charClass, best))
                     best = max(best, titleIndex);
                 titles.set(charClass, best);
             }
             int maxTitleIndex = GetMaxClassTitleIndex();
             auto keys = titles.getKeys();
             for (uint i = 0; i < keys.length(); i++)
             {
                 string charClass = keys[i];
                 int64 titleIndex;
                 titles.get(charClass, titleIndex);
                 auto list = GetList(charClass);
                 if (list is null)
                 {
                     PrintError("Class titles list for \"" + charClass + "\" is not loaded!");
                     continue;
                 }
                 if (titleIndex > maxTitleIndex)
                     titleIndex = maxTitleIndex;
                 auto title = list.GetTitle(int(titleIndex));
                 builder.PushArray();
                 builder.PushString(charClass);
                 builder.PushInteger(titleIndex);
                 builder.PopArray();
                 dictionary params = { { "title", Resources::GetString(title.m_name) } };
                 title.m_modifiers.m_name = Resources::GetString(".modifier.list.classtitle", params);
                 list.EnableTitleModifiers(record, titleIndex);
             }
             builder.PopArray();
         }
Member Data Documentation
m_lists
dictionary Titles::ClassTitles::m_lists private
Definition at line 13 of file ClassTitles.as.
Referenced by AddClassTitles(), and GetList().
The documentation for this class was generated from the following file:
scripts/Titles/ClassTitles.as