HoHDocs: ScoreDialog Class Reference
ScoreDialog Class Reference
Private Member Functions
ScoreDialog (GUIBuilder@ b, IWidgetHoster@ owner)
SValue BuildData ()
void Set (SValue@ sv, string header)
void OnFunc (Widget@ sender, string name) override
Private Attributes
IWidgetHoster m_owner
Detailed Description
Definition at line 1 of file ScoreDialog.as.
Constructor & Destructor Documentation
ScoreDialog()
ScoreDialog::ScoreDialog (GUIBuilder@ b, IWidgetHoster@ owner) inline private
Definition at line 5 of file ScoreDialog.as.
References m_owner.
     {
         super(b, "gui/scoredialog.gui");
         @m_owner = owner;
     }
Member Function Documentation
BuildData()
SValue ScoreDialog::BuildData () inline private
Definition at line 12 of file ScoreDialog.as.
References g_players.
     {
         SValueBuilder sval;
         sval.PushDictionary();
         sval.PushArray("players");
         for (uint i = 0; i < g_players.length(); i++)
         {
             PlayerRecord@ player = g_players[i];
             if (player.peer == 255)
                 continue;
             sval.PushDictionary();
             sval.PushInteger("peer", player.peer);
             sval.PushInteger("kills", player.kills);
             sval.PushInteger("deaths", player.deaths);
             sval.PopDictionary();
         }
         sval.PopArray();
         return sval.Build();
     }
OnFunc()
void ScoreDialog::OnFunc (Widget@ sender, string name) inline override private
Definition at line 121 of file ScoreDialog.as.
References UserWindow::Close(), m_owner, name, and UserWindow::OnFunc().
     {
         if (name == "close")
         {
             Close();
             if (m_owner !is null)
                 m_owner.OnFunc(sender, "scoreclose");
         }
         else
             UserWindow::OnFunc(sender, name);
     }
Set()
void ScoreDialog::Set (SValue@ sv, string header) inline private
Definition at line 37 of file ScoreDialog.as.
References Widget::AddChild(), Widget::ClearChildren(), Widget::Clone(), CurrPlaytimeLevel(), CurrPlaytimeTotal(), formatTime(), g_gameMode, GetPlayerColor(), GetPlayerRecordByPeer(), GetRestartCount(), Widget::GetWidgetById(), Widget::m_visible, m_widget, TextWidget::SetColor(), Widget::SetID(), and TextWidget::SetText().
     {
         auto wHeader = cast<TextWidget>(m_widget.GetWidgetById("header"));
         if (wHeader !is null)
             wHeader.SetText(header);
         Widget@ wList = m_widget.GetWidgetById("player-list");
         if (wList !is null)
             wList.ClearChildren();
         Widget@ wTemplate = m_widget.GetWidgetById("player-template");
         array<SValue@>@ dictPlayers = GetParamArray(UnitPtr(), sv, "players", false);
         if (wList !is null && wTemplate !is null && dictPlayers !is null)
         {
             for (uint i = 0; i < dictPlayers.length(); i++)
             {
                 SValue@ dictPlayer = dictPlayers[i];
                 uint8 peer = GetParamInt(UnitPtr(), dictPlayer, "peer");
                 PlayerRecord@ player = GetPlayerRecordByPeer(peer);
                 if (player is null)
                     continue;
                 Widget@ wNewItem = wTemplate.Clone();
                 wNewItem.m_visible = true;
                 wNewItem.SetID("");
                 TextWidget@ wName = cast<TextWidget>(wNewItem.GetWidgetById("name"));
                 if (wName !is null)
                 {
                     wName.SetText(player.GetName());
                     wName.SetColor(ParseColorRGBA("#" + GetPlayerColor(player.peer) + "ff"));
                 }
                 TextWidget@ wKills = cast<TextWidget>(wNewItem.GetWidgetById("kills"));
                 if (wKills !is null)
                     wKills.SetText("" + GetParamInt(UnitPtr(), dictPlayer, "kills"));
                 TextWidget@ wDeaths = cast<TextWidget>(wNewItem.GetWidgetById("deaths"));
                 if (wDeaths !is null)
                     wDeaths.SetText("" + GetParamInt(UnitPtr(), dictPlayer, "deaths"));
                 wList.AddChild(wNewItem);
             }
         }
         Widget@ wStatsLevel = m_widget.GetWidgetById("stats-level");
         if (wStatsLevel !is null)
         {
             Campaign@ campaign = cast<Campaign>(g_gameMode);
             TextWidget@ wStatsTime = cast<TextWidget>(wStatsLevel.GetWidgetById("time"));
             if (wStatsTime !is null)
                 wStatsTime.SetText(formatTime(CurrPlaytimeLevel() / 1000.0f, false, true, true));
             TextWidget@ wStatsSecrets = cast<TextWidget>(wStatsLevel.GetWidgetById("secrets"));
             if (wStatsSecrets !is null)
                 wStatsSecrets.SetText("-");
             TextWidget@ wStatsRestarts = cast<TextWidget>(wStatsLevel.GetWidgetById("restarts"));
             if (wStatsRestarts !is null)
                 wStatsRestarts.SetText("" + GetRestartCount());
         }
         Widget@ wStatsGame = m_widget.GetWidgetById("stats-game");
         if (wStatsGame !is null)
         {
             Campaign@ campaign = cast<Campaign>(g_gameMode);
             TextWidget@ wStatsTime = cast<TextWidget>(wStatsGame.GetWidgetById("time"));
             if (wStatsTime !is null)
                 wStatsTime.SetText(formatTime(CurrPlaytimeTotal() / 1000.0f, false, true, true));
             TextWidget@ wStatsSecrets = cast<TextWidget>(wStatsGame.GetWidgetById("secrets"));
             if (wStatsSecrets !is null)
                 wStatsSecrets.SetText("-");
             TextWidget@ wStatsRestarts = cast<TextWidget>(wStatsGame.GetWidgetById("restarts"));
             if (wStatsRestarts !is null)
                 wStatsRestarts.SetText("" + GetRestartCount());
         }
     }
Member Data Documentation
m_owner
IWidgetHoster ScoreDialog::m_owner private
Definition at line 3 of file ScoreDialog.as.
Referenced by OnFunc(), and ScoreDialog().
The documentation for this class was generated from the following file:
scripts/GUI/ScoreDialog.as