HoHDocs: BossEye Class Reference
BossEye Class Reference
Private Member Functions
BossEye (UnitPtr unit, SValue &params)
void AddWisps (int num)
void NetAddWisps (SValue@ params)
void ClearWisps ()
void Suspend ()
void Freeze (bool freeze)
bool IsTargetable () override
void Unsuspend ()
void NetWispSync (SValue@ params)
void Update (int dt) override
void FindWispTargets ()
SValue Save () override
void Load (SValue@ data) override
void PostLoad (SValue@ data) override
Private Attributes
UnitScene m_sceneDisappear
UnitScene m_sceneAppear
UnitProducer m_prod
int m_appearTimeC
int m_wispSyncTimeC
array< BossEyeWisp@> m_wisps
Detailed Description
Definition at line 1 of file BossEye.as.
Constructor & Destructor Documentation
BossEye()
BossEye::BossEye (UnitPtr unit, SValue & params) inline private
Definition at line 13 of file BossEye.as.
References m_prod, m_sceneAppear, m_sceneDisappear, m_unit, and unit.
     {
         super(unit, params);
         @m_sceneDisappear = m_unit.GetUnitScene(GetParamString(unit, params, "scene-disappear"));
         @m_sceneAppear = m_unit.GetUnitScene(GetParamString(unit, params, "scene-appear"));
         @m_prod = Resources::GetUnitProducer(GetParamString(unit, params, "wisp-unit"));
     }
Member Function Documentation
AddWisps()
void BossEye::AddWisps (int num) inline private
Definition at line 23 of file BossEye.as.
References g_scene, m_prod, m_unit, m_wisps, num, and unit.
     {
         SValueBuilder builder;
         builder.PushArray();
         for (int i = 0; i < num; i++)
         {
             UnitPtr unit = m_prod.Produce(g_scene, m_unit.GetPosition());
             auto wisp = cast<BossEyeWisp>(unit.GetScriptBehavior());
             if (wisp is null)
                 return;
             float angle = (i / float(num)) * PI * 2;
             wisp.Set(angle, this);
             builder.PushInteger(unit.GetId());
             m_wisps.insertLast(wisp);
         }
         builder.PopArray();
         (Network::Message("UnitEyeBossWispsAdded") << m_unit << builder.Build()).SendToAll();
     }
ClearWisps()
void BossEye::ClearWisps () inline private
Definition at line 72 of file BossEye.as.
References Disappear, and m_wisps.
     {
         for (uint i = 0; i < m_wisps.length(); i++)
             m_wisps[i].Disappear();
         m_wisps.removeRange(0, m_wisps.length());
     }
FindWispTargets()
void BossEye::FindWispTargets () inline private
Definition at line 166 of file BossEye.as.
References g_players, IsDead(), m_target, and m_wisps.
Referenced by Update().
     {
         array<PlayerRecord@> players;
         for (uint i = 0; i < g_players.length(); i++)
         {
             if (g_players[i].peer != 255 && !g_players[i].IsDead())
                 players.insertLast(g_players[i]);
         }
         players.sortAsc();
         if (players.length() > 0)
         {
             for (uint i = 0; i < m_wisps.length(); i++)
                 @m_wisps[i].m_target = players[i % players.length()].actor;
         }
     }
Freeze()
void BossEye::Freeze (bool freeze) inline private
Definition at line 88 of file BossEye.as.
References ActorMovement::m_enabled, m_frozen, m_movement, and m_unit.
Referenced by Suspend(), and Update().
     {
         m_frozen = freeze;
         m_movement.m_enabled = !freeze;
         auto body = m_unit.GetPhysicsBody();
         if (body !is null)
             body.SetStatic(freeze);
     }
IsTargetable()
bool BossEye::IsTargetable () inline override private
Definition at line 99 of file BossEye.as.
References IsTargetable(), and m_frozen.
     {
         if (m_frozen)
             return false;
         return CompositeActorBehavior::IsTargetable();
     }
Load()
void BossEye::Load (SValue@ data) inline override private
Definition at line 197 of file BossEye.as.
References Load(), m_appearTimeC, m_wispSyncTimeC, and Suspend().
     {
         SValue@ svComposite = data.GetDictionaryEntry("composite");
         if (svComposite !is null)
         {
             m_appearTimeC = GetParamInt(UnitPtr(), data, "appear-time", false);
             m_wispSyncTimeC = GetParamInt(UnitPtr(), data, "wisp-sync-time", false);
             bool frozen = GetParamBool(UnitPtr(), svComposite, "frozen", false);
             if (frozen)
                 Suspend();
             CompositeActorBehavior::Load(svComposite);
         }
         else
             CompositeActorBehavior::Load(data);
     }
NetAddWisps()
void BossEye::NetAddWisps (SValue@ params) inline private
Definition at line 48 of file BossEye.as.
References g_scene, id, m_prod, m_unit, m_wisps, num, and unit.
     {
         auto arr = params.GetArray();
         if (arr is null)
             return;
         uint num = arr.length();
         for (uint i = 0; i < num; i++)
         {
             int id = arr[i].GetInteger();
             UnitPtr unit = m_prod.Produce(g_scene, m_unit.GetPosition(), id);
             auto wisp = cast<BossEyeWisp>(unit.GetScriptBehavior());
             if (wisp is null)
                 return;
             float angle = (i / float(num)) * PI * 2;
             wisp.Set(angle, this);
             m_wisps.insertLast(wisp);
         }
     }
NetWispSync()
void BossEye::NetWispSync (SValue@ params) inline private
Definition at line 115 of file BossEye.as.
References m_wisps, and min.
     {
         auto arr = params.GetArray();
         if (arr is null)
             return;
         if (m_wisps.length() * 2 != arr.length())
             PrintError("Amount of local wisps does not match server wisps!");
         for (int i = 0; i < min(m_wisps.length(), arr.length() / 2); i++)
         {
             m_wisps[i].m_currAngle = arr[i * 2].GetFloat();
             m_wisps[i].m_currDistance = arr[i * 2 + 1].GetFloat();
         }
     }
PostLoad()
void BossEye::PostLoad (SValue@ data) inline override private
Definition at line 215 of file BossEye.as.
References PostLoad().
     {
         SValue@ svComposite = data.GetDictionaryEntry("composite");
         if (svComposite !is null)
             CompositeActorBehavior::PostLoad(svComposite);
         else
             CompositeActorBehavior::PostLoad(data);
     }
Save()
SValue BossEye::Save () inline override private
Definition at line 183 of file BossEye.as.
References m_appearTimeC, m_wispSyncTimeC, and Save().
     {
         SValueBuilder builder;
         builder.PushDictionary();
         builder.PushInteger("appear-time", m_appearTimeC);
         builder.PushInteger("wisp-sync-time", m_wispSyncTimeC);
         builder.PushSimple("composite", CompositeActorBehavior::Save());
         builder.PopDictionary();
         return builder.Build();
     }
Suspend()
void BossEye::Suspend () inline private
Definition at line 79 of file BossEye.as.
References Freeze(), m_frozen, m_sceneDisappear, and m_unit.
Referenced by Load().
     {
         if (m_frozen)
             return;
         Freeze(true);
         m_unit.SetUnitScene(m_sceneDisappear, true);
     }
Unsuspend()
void BossEye::Unsuspend () inline private
Definition at line 106 of file BossEye.as.
References m_appearTimeC, m_frozen, m_sceneAppear, and m_unit.
     {
         if (!m_frozen)
             return;
         m_unit.SetUnitScene(m_sceneAppear, true);
         m_appearTimeC = m_sceneAppear.Length();
     }
Update()
void BossEye::Update (int dt) inline override private
Definition at line 131 of file BossEye.as.
References FindWispTargets(), Freeze(), m_appearTimeC, m_unit, m_wisps, m_wispSyncTimeC, and Update().
     {
         if (m_appearTimeC > 0)
         {
             m_appearTimeC -= dt;
             if (m_appearTimeC <= 0)
             {
                 Freeze(false);
                 m_wispSyncTimeC = 2000;
             }
         }
         FindWispTargets();
         if (m_wispSyncTimeC > 0 && Network::IsServer())
         {
             m_wispSyncTimeC -= dt;
             if (m_wispSyncTimeC <= 0)
             {
                 m_wispSyncTimeC = 2000;
                 SValueBuilder builder;
                 builder.PushArray();
                 for (uint i = 0; i < m_wisps.length(); i++)
                 {
                     builder.PushFloat(m_wisps[i].m_currAngle);
                     builder.PushFloat(m_wisps[i].m_currDistance);
                 }
                 builder.PopArray();
                 (Network::Message("UnitEyeBossWispsSync") << m_unit << builder.Build()).SendToAll();
             }
         }
         CompositeActorBehavior::Update(dt);
     }
Member Data Documentation
m_appearTimeC
int BossEye::m_appearTimeC private
Definition at line 8 of file BossEye.as.
Referenced by Load(), Save(), Unsuspend(), and Update().
m_prod
UnitProducer BossEye::m_prod private
Definition at line 6 of file BossEye.as.
Referenced by AddWisps(), BossEye(), and NetAddWisps().
m_sceneAppear
UnitScene BossEye::m_sceneAppear private
Definition at line 4 of file BossEye.as.
Referenced by BossEye(), and Unsuspend().
m_sceneDisappear
UnitScene BossEye::m_sceneDisappear private
Definition at line 3 of file BossEye.as.
Referenced by BossEye(), and Suspend().
m_wisps
array<BossEyeWisp@> BossEye::m_wisps private
Definition at line 11 of file BossEye.as.
Referenced by AddWisps(), ClearWisps(), FindWispTargets(), NetAddWisps(), NetWispSync(), BossEyeWisp::PostLoad(), and Update().
m_wispSyncTimeC
int BossEye::m_wispSyncTimeC private
Definition at line 9 of file BossEye.as.
Referenced by Load(), Save(), and Update().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Enemies/BossEye.as