HoHDocs: TownBuilding Class Reference
TownBuilding Class Reference
Private Member Functions
TownBuilding (TownRecord@ town, string typeName, int level=0)
Modifiers::ModifierList GetModifiers ()
void RefreshModifiers ()
void LoadTweakData ()
Prefab GetPrefab ()
void Upgrade (int level)
void Save (SValueBuilder &builder)
void Load (SValue@ sv)
Private Attributes
TownRecord m_town
string m_typeName
int m_level
array< Modifiers::ModifierList@> m_levelModifiers
Detailed Description
Definition at line 1 of file TownBuilding.as.
Constructor & Destructor Documentation
TownBuilding()
TownBuilding::TownBuilding (TownRecord@ town, string typeName, int level = 0) inline private
Definition at line 10 of file TownBuilding.as.
References LoadTweakData(), m_level, m_town, and m_typeName.
     {
         @m_town = town;
         m_typeName = typeName;
         m_level = level;
         LoadTweakData();
     }
Member Function Documentation
GetModifiers()
Modifiers::ModifierList TownBuilding::GetModifiers () inline private
Definition at line 20 of file TownBuilding.as.
References m_level, and m_levelModifiers.
Referenced by RefreshModifiers().
     {
         if (m_level < int(m_levelModifiers.length()))
             return m_levelModifiers[m_level];
         return null;
     }
GetPrefab()
Prefab TownBuilding::GetPrefab () inline private
Definition at line 64 of file TownBuilding.as.
References GetPrefab(), m_level, and m_typeName.
Referenced by Town::SpawnBuildings().
     {
         return Resources::GetPrefab("prefabs/town/building_" + m_typeName + "_" + m_level + ".pfb");
     }
Load()
void TownBuilding::Load (SValue@ sv) inline private
Definition at line 81 of file TownBuilding.as.
References m_level, and RefreshModifiers().
Referenced by TownRecord::Load().
     {
         if (sv.GetType() == SValueType::Integer)
             m_level = sv.GetInteger();
         RefreshModifiers();
     }
LoadTweakData()
void TownBuilding::LoadTweakData () inline private
Definition at line 41 of file TownBuilding.as.
References Modifiers::LoadModifiersList(), m_levelModifiers, m_typeName, and RefreshModifiers().
Referenced by TownBuilding().
     {
         SValue@ sval = Resources::GetSValue("tweak/buildings/" + m_typeName + ".sval");
         if (sval is null)
             return;
         auto arrLevels = GetParamArray(UnitPtr(), sval, "levels");
         if (arrLevels is null)
             return;
         for (uint i = 0; i < arrLevels.length(); i++)
         {
             auto modList = Modifiers::LoadModifiersList(UnitPtr(), arrLevels[i]);
             dictionary params = { { "building", Resources::GetString(".town.building." + m_typeName) }, { "level", i + 1 } };
             modList.m_name = Resources::GetString(".modifier.list.building", params);
             m_levelModifiers.insertLast(modList);
         }
         RefreshModifiers();
     }
RefreshModifiers()
void TownBuilding::RefreshModifiers () inline private
Definition at line 27 of file TownBuilding.as.
References g_allModifiers, GetModifiers(), m_levelModifiers, TownRecord::m_local, and m_town.
Referenced by Load(), LoadTweakData(), and Upgrade().
     {
         // Only host town should apply building modifiers
         if (m_town.m_local)
             return;
         for (uint i = 0; i < m_levelModifiers.length(); i++)
             g_allModifiers.Remove(m_levelModifiers[i]);
         auto mods = GetModifiers();
         if (mods !is null)
             g_allModifiers.Add(mods);
     }
Save()
void TownBuilding::Save (SValueBuilder & builder) inline private
Definition at line 76 of file TownBuilding.as.
References m_level, and m_typeName.
     {
         builder.PushInteger(m_typeName, m_level);
     }
Upgrade()
void TownBuilding::Upgrade (int level) inline private
Definition at line 69 of file TownBuilding.as.
References m_level, and RefreshModifiers().
Referenced by Upgrades::BuildingUpgradeStep::UpgradeBulding().
     {
         m_level = level;
         RefreshModifiers();
     }
Member Data Documentation
m_level
int TownBuilding::m_level private
Definition at line 6 of file TownBuilding.as.
Referenced by Town::CheckForAchievements(), GetModifiers(), GetPrefab(), Upgrades::BuildingUpgradeStep::IsOwned(), Load(), Save(), TownBuilding(), Upgrade(), and Upgrades::BuildingUpgradeStep::UpgradeBulding().
m_levelModifiers
array<Modifiers::ModifierList@> TownBuilding::m_levelModifiers private
Definition at line 8 of file TownBuilding.as.
Referenced by GetModifiers(), LoadTweakData(), and RefreshModifiers().
m_town
TownRecord TownBuilding::m_town private
Definition at line 3 of file TownBuilding.as.
Referenced by TownhallMenuContent::AddButton(), RefreshModifiers(), and TownBuilding().
m_typeName
string TownBuilding::m_typeName private
Definition at line 5 of file TownBuilding.as.
Referenced by GetPrefab(), LoadTweakData(), Save(), and TownBuilding().
The documentation for this class was generated from the following file:
scripts/Town/TownBuilding.as