HoHDocs: CharacterCustomizationNPC Class Reference
CharacterCustomizationNPC Class Reference
Private Member Functions
CharacterCustomizationNPC (SValue &sval)
bool ShouldFreezeControls () override
bool ShouldDisplayCursor () override
bool ShouldSaveExistance () override
void Initialize (bool loaded) override
void OnFunc (Widget@ sender, string name) override
Private Attributes
CharacterCustomizationBase m_base
Detailed Description
Definition at line 1 of file CharacterCustomizationNPC.as.
Constructor & Destructor Documentation
CharacterCustomizationNPC()
CharacterCustomizationNPC::CharacterCustomizationNPC (SValue & sval) inline private
Definition at line 5 of file CharacterCustomizationNPC.as.
References GetLocalPlayerRecord(), and m_base.
     {
         super();
         auto record = GetLocalPlayerRecord();
         @m_base = CharacterCustomizationBase(record.charClass, this);
     }
Member Function Documentation
Initialize()
void CharacterCustomizationNPC::Initialize (bool loaded) inline override private
Definition at line 17 of file CharacterCustomizationNPC.as.
References GetLocalPlayerRecord(), CharacterCustomizationBase::Initialize(), m_base, and ScriptWidgetHost::m_def.
     {
         m_base.Initialize(m_def, GetLocalPlayerRecord());
     }
OnFunc()
void CharacterCustomizationNPC::OnFunc (Widget@ sender, string name) inline override private
Definition at line 22 of file CharacterCustomizationNPC.as.
References formatThousands(), g_gameMode, GetLocalPlayerRecord(), m_base, CharacterCustomizationBase::m_dyes, CharacterCustomizationBase::m_editCost, CharacterCustomizationBase::m_face, TextInputWidget::m_text, CharacterCustomizationBase::m_wName, name, CharacterCustomizationBase::OnFunc(), AGameMode::ShowDialog(), and ScriptWidgetHost::Stop().
     {
         if (!m_base.OnFunc(sender, name))
         {
             auto parse = name.split(" ");
             if (parse[0] == "finish")
             {
                 if (parse.length() == 1)
                 {
                     g_gameMode.ShowDialog(
                         "finish",
                         Resources::GetString(".mainmenu.character.customize.finish", { { "cost", formatThousands(m_base.m_editCost) } }),
                         Resources::GetString(".menu.yes"),
                         Resources::GetString(".menu.no"),
                         this);
                 }
                 else if (parse[1] == "yes")
                 {
                     auto gm = cast<Campaign>(g_gameMode);
                     if (gm.m_townLocal.m_gold < m_base.m_editCost)
                     {
                         PrintError("Not enough gold!");
                         return;
                     }
                     gm.m_townLocal.m_gold -= m_base.m_editCost;
                     auto record = GetLocalPlayerRecord();
                     record.name = m_base.m_wName.m_text.plain();
                     record.colors = m_base.m_dyes;
                     record.face = m_base.m_face;
                     if (!record.freeCustomizationUsed)
                         record.freeCustomizationUsed = true;
                     auto player = cast<PlayerBase>(record.actor);
                     player.UpdateColors();
                     SValueBuilder builder;
                     builder.PushDictionary();
                     builder.PushString("name", record.name);
                     builder.PushInteger("face", record.face);
                     builder.PushFloat("voice", record.voice);
                     builder.PushArray("colors");
                     for (uint i = 0; i < record.colors.length(); i++)
                     {
                         auto dye = record.colors[i];
                         builder.PushArray();
                         builder.PushInteger(int(dye.m_category));
                         builder.PushInteger(dye.m_idHash);
                         builder.PopArray();
                     }
                     builder.PopArray();
                     builder.PopDictionary();
                     (Network::Message("PlayerUpdateColors") << builder.Build()).SendToAll();
                     Stop();
                 }
             }
             else if (parse[0] == "back")
                 Stop();
         }
     }
ShouldDisplayCursor()
bool CharacterCustomizationNPC::ShouldDisplayCursor () inline override private
Definition at line 14 of file CharacterCustomizationNPC.as.
 { return true; }
ShouldFreezeControls()
bool CharacterCustomizationNPC::ShouldFreezeControls () inline override private
Definition at line 13 of file CharacterCustomizationNPC.as.
 { return true; }
ShouldSaveExistance()
bool CharacterCustomizationNPC::ShouldSaveExistance () inline override private
Definition at line 15 of file CharacterCustomizationNPC.as.
 { return false; }
Member Data Documentation
m_base
CharacterCustomizationBase CharacterCustomizationNPC::m_base private
Definition at line 3 of file CharacterCustomizationNPC.as.
Referenced by CharacterCustomizationNPC(), Initialize(), and OnFunc().
The documentation for this class was generated from the following file:
scripts/GUI/Town/CharacterCustomizationNPC.as