HoHDocs: DungeonSettingsMenu Class Reference
DungeonSettingsMenu Class Reference
Private Member Functions
DungeonSettingsMenu (SValue &sval)
void Initialize (bool loaded) override
void UpdateNgp ()
bool ShouldFreezeControls () override
bool ShouldDisplayCursor () override
bool ShouldSaveExistance () override
void Update (int dt) override
void OnNgpChanged ()
void OnFunc (Widget@ sender, string name) override
Private Attributes
TextWidget m_wNgp
SpriteButtonWidget m_wNgpLeft
SpriteButtonWidget m_wNgpRight
CheckBoxWidget m_wDownscaling
int m_lastNgp = -1
Detailed Description
Definition at line 1 of file DungeonSettingsMenu.as.
Constructor & Destructor Documentation
DungeonSettingsMenu()
DungeonSettingsMenu::DungeonSettingsMenu (SValue & sval) inline private
Definition at line 11 of file DungeonSettingsMenu.as.
     {
         super();
     }
Member Function Documentation
Initialize()
void DungeonSettingsMenu::Initialize (bool loaded) inline override private
Definition at line 16 of file DungeonSettingsMenu.as.
References m_wDownscaling, m_widget, m_wNgp, m_wNgpLeft, m_wNgpRight, and UpdateNgp().
     {
         @m_wNgp = cast<TextWidget>(m_widget.GetWidgetById("ngp"));
         @m_wNgpLeft = cast<SpriteButtonWidget>(m_widget.GetWidgetById("ngp-left"));
         @m_wNgpRight = cast<SpriteButtonWidget>(m_widget.GetWidgetById("ngp-right"));
         @m_wDownscaling = cast<CheckBoxWidget>(m_widget.GetWidgetById("downscaling"));
         UpdateNgp();
     }
OnFunc()
void DungeonSettingsMenu::OnFunc (Widget@ sender, string name) inline override private
Definition at line 71 of file DungeonSettingsMenu.as.
References g_downscaling, g_gameMode, g_ngp, IsInLobby(), name, Menu::OnFunc(), OnNgpChanged(), SendSystemMessage(), and ScriptWidgetHost::Stop().
     {
         if (name == "close")
             Stop();
         else if (name == "ngp-prev" && Network::IsServer())
         {
             g_ngp--;
             if (g_ngp < 0)
                 g_ngp = 0;
             OnNgpChanged();
         }
         else if (name == "ngp-next" && Network::IsServer())
         {
             g_ngp++;
             auto gm = cast<Campaign>(g_gameMode);
             auto town = gm.m_townLocal;
             if (g_ngp > town.m_highestNgp)
                 g_ngp = town.m_highestNgp;
             OnNgpChanged();
         }
         else if (name == "downscaling-changed" && Network::IsServer())
         {
             auto checkable = cast<ICheckableWidget>(sender);
             g_downscaling = checkable.IsChecked();
             (Network::Message("SetDownscaling") << g_downscaling).SendToAll();
             if (Lobby::IsInLobby())
             {
                 SValueBuilder builder;
                 builder.PushBoolean(g_downscaling);
                 SendSystemMessage("SetDownscaling", builder.Build());
             }
         }
         else
             ScriptWidgetHost::OnFunc(sender, name);
     }
OnNgpChanged()
void DungeonSettingsMenu::OnNgpChanged () inline private
Definition at line 59 of file DungeonSettingsMenu.as.
References g_ngp, IsInLobby(), and SendSystemMessage().
Referenced by OnFunc().
     {
         (Network::Message("SetNgp") << g_ngp).SendToAll();
         if (Network::IsServer() && Lobby::IsInLobby())
         {
             SValueBuilder builder;
             builder.PushInteger(g_ngp);
             SendSystemMessage("SetNGP", builder.Build());
         }
     }
ShouldDisplayCursor()
bool DungeonSettingsMenu::ShouldDisplayCursor () inline override private
Definition at line 42 of file DungeonSettingsMenu.as.
 { return true; }
ShouldFreezeControls()
bool DungeonSettingsMenu::ShouldFreezeControls () inline override private
Definition at line 41 of file DungeonSettingsMenu.as.
 { return true; }
ShouldSaveExistance()
bool DungeonSettingsMenu::ShouldSaveExistance () inline override private
Definition at line 43 of file DungeonSettingsMenu.as.
 { return false; }
Update()
void DungeonSettingsMenu::Update (int dt) inline override private
Definition at line 45 of file DungeonSettingsMenu.as.
References g_downscaling, g_ngp, CheckBoxWidget::m_enabled, m_lastNgp, m_wDownscaling, CheckBoxWidget::SetChecked(), Update(), and UpdateNgp().
     {
         if (m_lastNgp != g_ngp)
         {
             m_lastNgp = g_ngp;
             UpdateNgp();
         }
         m_wDownscaling.SetChecked(g_downscaling);
         m_wDownscaling.m_enabled = Network::IsServer();
         ScriptWidgetHost::Update(dt);
     }
UpdateNgp()
void DungeonSettingsMenu::UpdateNgp () inline private
Definition at line 27 of file DungeonSettingsMenu.as.
References DoLayout(), g_gameMode, g_ngp, SpriteButtonWidget::m_enabled, m_wNgp, m_wNgpLeft, m_wNgpRight, and TextWidget::SetText().
Referenced by Initialize(), and Update().
     {
         bool isHost = Network::IsServer();
         auto gm = cast<Campaign>(g_gameMode);
         auto town = gm.m_townLocal;
         m_wNgp.SetText("+" + g_ngp);
         m_wNgpLeft.m_enabled = (isHost && g_ngp > 0);
         m_wNgpRight.m_enabled = (isHost && g_ngp < town.m_highestNgp);
         DoLayout();
     }
Member Data Documentation
m_lastNgp
int DungeonSettingsMenu::m_lastNgp = -1 private
Definition at line 9 of file DungeonSettingsMenu.as.
Referenced by Update().
m_wDownscaling
CheckBoxWidget DungeonSettingsMenu::m_wDownscaling private
Definition at line 7 of file DungeonSettingsMenu.as.
Referenced by Initialize(), and Update().
m_wNgp
TextWidget DungeonSettingsMenu::m_wNgp private
Definition at line 3 of file DungeonSettingsMenu.as.
Referenced by Initialize(), and UpdateNgp().
m_wNgpLeft
SpriteButtonWidget DungeonSettingsMenu::m_wNgpLeft private
Definition at line 4 of file DungeonSettingsMenu.as.
Referenced by Initialize(), and UpdateNgp().
m_wNgpRight
SpriteButtonWidget DungeonSettingsMenu::m_wNgpRight private
Definition at line 5 of file DungeonSettingsMenu.as.
Referenced by Initialize(), and UpdateNgp().
The documentation for this class was generated from the following file:
scripts/GUI/Town/DungeonSettingsMenu.as