HoHDocs: DungeonStoreMenuContent Class Reference
DungeonStoreMenuContent Class Reference
Private Member Functions
DungeonStoreMenuContent (ShopMenu@ shopMenu)
string GetGuiFilename () override
void OnShow () override
bool BuyItem (Upgrades::Upgrade@ upgrade, Upgrades::UpgradeStep@ step) override
UpgradeShopButtonWidget AddItem (Widget@ template, Widget@ list, Upgrades::Upgrade@ upgrade) override
void ReloadList () override
Private Attributes
TextWidget m_wLimit
Upgrades::DungeonShop m_itemShop
Detailed Description
Definition at line 1 of file DungeonStoreMenu.as.
Constructor & Destructor Documentation
DungeonStoreMenuContent()
DungeonStoreMenuContent::DungeonStoreMenuContent (ShopMenu@ shopMenu) inline private
Definition at line 7 of file DungeonStoreMenu.as.
References UpgradeShopMenuContent::m_currentShop, and m_itemShop.
     {
         super(shopMenu, "dungeonstore");
         @m_itemShop = cast<Upgrades::DungeonShop>(m_currentShop);
         if (m_itemShop is null)
             PrintError("\"dungeonstore\" is not an item shop!");
     }
Member Function Documentation
AddItem()
UpgradeShopButtonWidget DungeonStoreMenuContent::AddItem (Widget@ template, Widget@ list, Upgrades::Upgrade@ upgrade) inline override private
Definition at line 39 of file DungeonStoreMenu.as.
References UpgradeShopMenuContent::AddItem(), GetLocalPlayerRecord(), m_itemShop, and Upgrades::DungeonShop::m_maxItems.
     {
         auto button = UpgradeShopMenuContent::AddItem(template, list, upgrade);
         if (button is null)
             return null;
         if (button.m_enabled)
         {
             auto record = GetLocalPlayerRecord();
             button.m_enabled = (record.generalStoreItemsBought < m_itemShop.m_maxItems);
         }
         return button;
     }
BuyItem()
bool DungeonStoreMenuContent::BuyItem (Upgrades::Upgrade@ upgrade, Upgrades::UpgradeStep@ step) inline override private
Definition at line 28 of file DungeonStoreMenu.as.
References ShopMenuContent::BuyItem(), and GetLocalPlayerRecord().
     {
         if (UpgradeShopMenuContent::BuyItem(upgrade, step))
         {
             auto record = GetLocalPlayerRecord();
             record.generalStoreItemsBought++;
             return true;
         }
         return false;
     }
GetGuiFilename()
string DungeonStoreMenuContent::GetGuiFilename () inline override private
Definition at line 16 of file DungeonStoreMenu.as.
     {
         return "gui/shop/dungeonstore.gui";
     }
OnShow()
void DungeonStoreMenuContent::OnShow () inline override private
Definition at line 21 of file DungeonStoreMenu.as.
References Widget::GetWidgetById(), ShopMenuContent::m_widget, m_wLimit, and UpgradeShopMenuContent::OnShow().
     {
         @m_wLimit = cast<TextWidget>(m_widget.GetWidgetById("limit"));
         UpgradeShopMenuContent::OnShow();
     }
ReloadList()
void DungeonStoreMenuContent::ReloadList () inline override private
Definition at line 54 of file DungeonStoreMenu.as.
References GetLocalPlayerRecord(), m_itemShop, Upgrades::DungeonShop::m_maxItems, Widget::m_visible, m_wLimit, UpgradeShopMenuContent::m_wSoldOut, UpgradeShopMenuContent::ReloadList(), TextWidget::SetColor(), and TextWidget::SetText().
     {
         UpgradeShopMenuContent::ReloadList();
         if (!m_wSoldOut.m_visible)
         {
             auto record = GetLocalPlayerRecord();
             m_wLimit.SetText(record.generalStoreItemsBought + " / " + m_itemShop.m_maxItems);
             if (record.generalStoreItemsBought >= m_itemShop.m_maxItems)
                 m_wLimit.SetColor(vec4(1, 0, 0, 1));
         }
         // Ughhhhh
         // m_shopMenu.DoLayout();
         // m_shopMenu.DoLayout();
     }
Member Data Documentation
m_itemShop
Upgrades::DungeonShop DungeonStoreMenuContent::m_itemShop private
Definition at line 5 of file DungeonStoreMenu.as.
Referenced by AddItem(), DungeonStoreMenuContent(), and ReloadList().
m_wLimit
TextWidget DungeonStoreMenuContent::m_wLimit private
Definition at line 3 of file DungeonStoreMenu.as.
Referenced by OnShow(), and ReloadList().
The documentation for this class was generated from the following file:
scripts/GUI/Shop/DungeonStoreMenu.as