HoHDocs: WorldScript::SpawnGore Class Reference
WorldScript::SpawnGore Class Reference
Private Member Functions
SValue ServerExecute ()
void ClientExecute (SValue@ val)
Private Attributes
vec3 Position
string Path
bool Death
float Damage
int Angle
float ForceXY
float ForceZ
GoreSpawner m_gore
Detailed Description
Definition at line 4 of file SpawnGore.as.
Member Function Documentation
ClientExecute()
void WorldScript::SpawnGore::ClientExecute (SValue@ val) inline private
Definition at line 48 of file SpawnGore.as.
References ServerExecute().
         {
             ServerExecute();
         }
ServerExecute()
SValue WorldScript::SpawnGore::ServerExecute () inline private
Definition at line 27 of file SpawnGore.as.
References Angle, Death, ForceXY, ForceZ, LoadGore(), m_gore, Path, Position, and xy().
Referenced by ClientExecute().
         {
             if (m_gore is null)
                 @m_gore = LoadGore(Path);
             if (m_gore is null)
                 return null;
             float mulBeforeXY = m_gore.m_forceMulXY;
             float mulBeforeZ = m_gore.m_forceMulZ;
             m_gore.m_forceMulXY = ForceXY;
             m_gore.m_forceMulZ = ForceZ;
             if (Death)
                 m_gore.OnDeath(Damage, xy(Position), Angle * PI / 180.0);
             else
                 m_gore.OnHit(Damage, xy(Position), Angle * PI / 180.0);
             m_gore.m_forceMulXY = mulBeforeXY;
             m_gore.m_forceMulZ = mulBeforeZ;
             return null;
         }
Member Data Documentation
Angle
int WorldScript::SpawnGore::Angle private
Definition at line 18 of file SpawnGore.as.
Referenced by ServerExecute().
Damage
float WorldScript::SpawnGore::Damage private
Definition at line 15 of file SpawnGore.as.
Death
bool WorldScript::SpawnGore::Death private
Definition at line 12 of file SpawnGore.as.
Referenced by ServerExecute().
ForceXY
float WorldScript::SpawnGore::ForceXY private
Definition at line 21 of file SpawnGore.as.
Referenced by ServerExecute().
ForceZ
float WorldScript::SpawnGore::ForceZ private
Definition at line 23 of file SpawnGore.as.
Referenced by ServerExecute().
m_gore
GoreSpawner WorldScript::SpawnGore::m_gore private
Definition at line 25 of file SpawnGore.as.
Referenced by ServerExecute().
Path
string WorldScript::SpawnGore::Path private
Definition at line 9 of file SpawnGore.as.
Referenced by ServerExecute().
Position
vec3 WorldScript::SpawnGore::Position private
Definition at line 6 of file SpawnGore.as.
Referenced by ServerExecute().
The documentation for this class was generated from the following file:
scripts/WorldScript/SpawnGore.as