HoHDocs: WorldScript::SpawnPrefab Class Reference
WorldScript::SpawnPrefab Class Reference
Private Member Functions
void Initialize ()
SValue ServerExecute ()
Private Attributes
vec3 Position
Detailed Description
Definition at line 4 of file SpawnPrefab.as.
Member Function Documentation
Initialize()
void WorldScript::SpawnPrefab::Initialize () inline private
Definition at line 8 of file SpawnPrefab.as.
         {
             Initialize(UnitPtr(), null);
         }
ServerExecute()
SValue WorldScript::SpawnPrefab::ServerExecute () inline private
Definition at line 13 of file SpawnPrefab.as.
References SpawnPrefabBase::CalcJitter(), Position, SpawnPrefabBase::SpawnPrefab(), and xy().
         {
             SpawnPrefab(xy(Position) + CalcJitter());
             return null;
         }
Member Data Documentation
Position
vec3 WorldScript::SpawnPrefab::Position private
Definition at line 6 of file SpawnPrefab.as.
Referenced by ServerExecute().
The documentation for this class was generated from the following file:
scripts/WorldScript/SpawnPrefab.as