HoHDocs: Menu::FrontMenu Class Reference
Menu::FrontMenu Class Reference
Private Member Functions
FrontMenu (MenuProvider@ provider)
void Initialize (GUIDef@ def) override
bool Close () override
void TogglePopupMenu (Widget@ w)
void Update (int dt) override
void OnFunc (Widget@ sender, string name) override
Private Attributes
Widget m_wPopupMultiplayer
Widget m_wPopupOptions
Widget m_wPopupConfirmRestart
Widget m_wPopupConfirmStop
array< Widget@> m_arrPopups
bool m_haveUnpackedMods
Detailed Description
Definition at line 3 of file FrontMenu.as.
Constructor & Destructor Documentation
FrontMenu()
Menu::FrontMenu::FrontMenu (MenuProvider@ provider) inline private
Definition at line 14 of file FrontMenu.as.
         {
             super(provider);
         }
Member Function Documentation
Close()
bool Menu::FrontMenu::Close () inline override private
Definition at line 58 of file FrontMenu.as.
         {
             return false;
         }
Initialize()
void Menu::FrontMenu::Initialize (GUIDef@ def) inline override private
Definition at line 19 of file FrontMenu.as.
References HwrSaves::GetEnabledMods(), Menu::Menu::Initialize(), IsInLobby(), m_arrPopups, m_haveUnpackedMods, Widget::m_parent, Widget::m_spacing, Widget::m_visible, m_widget, Widget::m_width, m_wPopupConfirmRestart, m_wPopupConfirmStop, m_wPopupMultiplayer, m_wPopupOptions, and Packaged().
         {
             HwrMenu::Initialize(def);
             auto wMultiTest = m_widget.GetWidgetById("multi-test");
             if (wMultiTest !is null)
                 wMultiTest.m_visible = GetVarBool("g_multi_test");
             m_arrPopups.insertLast(@m_wPopupMultiplayer = m_widget.GetWidgetById("popup-multiplayer"));
             m_arrPopups.insertLast(@m_wPopupOptions = m_widget.GetWidgetById("popup-options"));
             m_arrPopups.insertLast(@m_wPopupConfirmRestart = m_widget.GetWidgetById("popup-restart"));
             m_arrPopups.insertLast(@m_wPopupConfirmStop = m_widget.GetWidgetById("popup-stop"));
             Widget@ wLobbyPlayers = m_widget.GetWidgetById("players-list");
             if (wLobbyPlayers !is null && Lobby::IsInLobby())
             {
                 int addWidth = wLobbyPlayers.m_width + wLobbyPlayers.m_parent.m_spacing;
                 wLobbyPlayers.m_visible = true;
                 wLobbyPlayers.m_parent.m_width += addWidth;
                 for (uint i = 0; i < m_arrPopups.length(); i++)
                 {
                     if (m_arrPopups[i] !is null)
                         m_arrPopups[i].m_offset.x += addWidth / 2;
                 }
             }
             auto enabledMods = HwrSaves::GetEnabledMods();
             for (uint i = 0; i < enabledMods.length(); i++)
             {
                 if (!enabledMods[i].Packaged)
                 {
                     m_haveUnpackedMods = true;
                     break;
                 }
             }
         }
OnFunc()
void Menu::FrontMenu::OnFunc (Widget@ sender, string name) inline override private
Definition at line 105 of file FrontMenu.as.
References CreateLobby(), g_gameMode, Widget::m_children, Menu::Menu::m_provider, m_testLevel, m_wPopupConfirmRestart, m_wPopupConfirmStop, m_wPopupMultiplayer, m_wPopupOptions, name, Menu::Menu::OnFunc(), Menu::Menu::OpenMenu(), Platform::OpenUrl(), HwrSaves::PickCharacter(), QuitGame(), ResumeGame(), Modifiers::Set, Menu::HwrMenu::ShowCharacterSelection(), StopScenario(), and TogglePopupMenu().
         {
             if (name == "logo")
             {
                 auto logo = sender.m_children[0];
                 logo.m_visible = !logo.m_visible;
             }
             else if (name == "slots")
                 OpenMenu(SlotsMenu(m_provider), "gui/main_menu/slots.gui");
             else if (name == "single")
                 ShowCharacterSelection("");
             else if (name == "multi-test")
             {
                 cast<MainMenu>(g_gameMode).m_testLevel = true;
                 HwrSaves::PickCharacter(0);
                 Lobby::CreateLobby();
             }
             else if (name == "multi")
                 TogglePopupMenu(m_wPopupMultiplayer);
             else if (name == "multi-host")
                 ShowCharacterSelection("multi-host");
             else if (name == "multi-serverlist")
                 ShowCharacterSelection("multi-serverlist");
             else if (name == "options")
                 TogglePopupMenu(m_wPopupOptions);
             else if (name == "options-gameplay")
                 OpenMenu(GameOptionsMenu(m_provider), "gui/main_menu/options_game.gui");
             else if (name == "options-graphics")
                 OpenMenu(GraphicsMenu(m_provider), "gui/main_menu/options_graphics.gui");
             else if (name == "options-sound")
                 OpenMenu(SoundMenu(m_provider), "gui/main_menu/options_sound.gui");
             else if (name == "options-controls")
                 OpenMenu(ControlsMenu(m_provider), "gui/main_menu/options_controls.gui");
             else if (name == "options-credits")
                 OpenMenu(CreditsMenu(m_provider), "gui/main_menu/credits.gui");
             else if (name == "options-players")
                 OpenMenu(LobbyPlayersMenu(m_provider), "gui/ingame_menu/lobbyplayers.gui");
             else if (name == "resume")
                 ResumeGame();
             else if (name == "restart" || name == "restart-no")
                 TogglePopupMenu(m_wPopupConfirmRestart);
             else if (name == "restart-yes")
             {
                 ResumeGame();
                 GlobalCache::Set("main_restart", "1");
             }
             else if (name == "quit")
                 QuitGame();
             else if (name == "wiki")
                 Platform::OpenUrl("http://wiki.heroesofhammerwatch.com/Main_Page");
             else if (name == "discord")
                 Platform::OpenUrl("https://discord.gg/hammerwatch");
             else if (name == "stop" || name == "stop-no")
                 TogglePopupMenu(m_wPopupConfirmStop);
             else if (name == "stop-yes")
                 StopScenario();
             else
                 HwrMenu::OnFunc(sender, name);
         }
TogglePopupMenu()
void Menu::FrontMenu::TogglePopupMenu (Widget@ w) inline private
Definition at line 63 of file FrontMenu.as.
References m_arrPopups.
Referenced by OnFunc().
         {
             for (uint i = 0; i < m_arrPopups.length(); i++)
             {
                 if (m_arrPopups[i] is null)
                     continue;
                 if (m_arrPopups[i] is w)
                     m_arrPopups[i].m_visible = !m_arrPopups[i].m_visible;
                 else
                     m_arrPopups[i].m_visible = false;
             }
         }
Update()
void Menu::FrontMenu::Update (int dt) inline override private
Definition at line 77 of file FrontMenu.as.
References Widget::m_children, m_haveUnpackedMods, m_wPopupMultiplayer, and Update().
         {
             HwrMenu::Update(dt);
             if (m_wPopupMultiplayer !is null)
             {
                 bool onlineAvailable = Platform::Service.IsMultiplayerAvailable();
                 for (uint i = 0; i < m_wPopupMultiplayer.m_children.length(); i++)
                 {
                     auto wButton = cast<ScalableSpriteButtonWidget>(m_wPopupMultiplayer.m_children[i]);
                     if (wButton is null)
                         continue;
                     wButton.m_enabled = onlineAvailable;
                     if (!onlineAvailable)
                     {
                         if (m_haveUnpackedMods)
                             wButton.m_tooltipText = Resources::GetString(".mainmenu.multiplayer.disabled.mods");
                         else
                             wButton.m_tooltipText = Resources::GetString(".mainmenu.multiplayer.disabled");
                     }
                     else
                         wButton.m_tooltipText = "";
                 }
             }
         }
Member Data Documentation
m_arrPopups
array<Widget@> Menu::FrontMenu::m_arrPopups private
Definition at line 10 of file FrontMenu.as.
Referenced by Initialize(), and TogglePopupMenu().
m_haveUnpackedMods
bool Menu::FrontMenu::m_haveUnpackedMods private
Definition at line 12 of file FrontMenu.as.
Referenced by Initialize(), and Update().
m_wPopupConfirmRestart
Widget Menu::FrontMenu::m_wPopupConfirmRestart private
Definition at line 7 of file FrontMenu.as.
Referenced by Initialize(), and OnFunc().
m_wPopupConfirmStop
Widget Menu::FrontMenu::m_wPopupConfirmStop private
Definition at line 8 of file FrontMenu.as.
Referenced by Initialize(), and OnFunc().
m_wPopupMultiplayer
Widget Menu::FrontMenu::m_wPopupMultiplayer private
Definition at line 5 of file FrontMenu.as.
Referenced by Initialize(), OnFunc(), and Update().
m_wPopupOptions
Widget Menu::FrontMenu::m_wPopupOptions private
Definition at line 6 of file FrontMenu.as.
Referenced by Initialize(), and OnFunc().
The documentation for this class was generated from the following file:
scripts/GUI/Menus/FrontMenu.as