HoHDocs: ScrollableRectWidget Class Reference
ScrollableRectWidget Class Reference
Private Member Functions
ScrollableRectWidget ()
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void DoDraw (SpriteBatch &sb, vec2 pos) override
void AnimateSet (string key, vec4 v) override
Private Attributes
vec4 m_color
vec4 m_borderColor
int m_borderWidth
BorderType m_borderType
vec4 m_shadowColor
int m_shadowSize
SpriteRect m_spriteRect
Detailed Description
Definition at line 1 of file ScrollableRectWidget.as.
Constructor & Destructor Documentation
ScrollableRectWidget()
ScrollableRectWidget::ScrollableRectWidget () inline private
Definition at line 14 of file ScrollableRectWidget.as.
Referenced by Clone().
     {
         super();
     }
Member Function Documentation
AnimateSet()
void ScrollableRectWidget::AnimateSet (string key, vec4 v) inline override private
Definition at line 68 of file ScrollableRectWidget.as.
     {
         if (key == "color")
             m_color = v;
         else if (key == "border")
             m_borderColor = v;
         ScrollableWidget::AnimateSet(key, v);
     }
Clone()
Widget ScrollableRectWidget::Clone () inline override private
Definition at line 19 of file ScrollableRectWidget.as.
References Widget::CloneInto(), and ScrollableRectWidget().
     {
         ScrollableRectWidget@ w = ScrollableRectWidget();
         CloneInto(w);
         return w;
     }
DoDraw()
void ScrollableRectWidget::DoDraw (SpriteBatch & sb, vec2 pos) inline override private
Definition at line 48 of file ScrollableRectWidget.as.
References ScrollableWidget::DoDraw(), Widget::DrawBorder(), m_borderColor, m_borderType, m_borderWidth, m_color, Widget::m_height, m_shadowColor, m_shadowSize, m_spriteRect, and Widget::m_width.
     {
         ScrollableWidget::DoDraw(sb, pos);
         vec4 p = vec4(pos.x, pos.y, m_width, m_height);
         sb.DrawSprite(null, p, p, m_color);
         if (m_shadowSize > 0 && m_shadowColor.a > 0)
         {
             vec4 sp;
             sp = vec4(pos.x, pos.y, m_width, m_shadowSize); sb.DrawSprite(null, sp, sp, m_shadowColor);
             sp = vec4(pos.x, pos.y + m_shadowSize, m_shadowSize, m_height - m_shadowSize); sb.DrawSprite(null, sp, sp, m_shadowColor);
         }
         DrawBorder(sb, pos, vec2(m_width, m_height), m_borderWidth, m_borderColor, m_borderType);
         if (m_spriteRect !is null)
             m_spriteRect.Draw(sb, pos, m_width, m_height);
     }
Load()
void ScrollableRectWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 26 of file ScrollableRectWidget.as.
Referenced by LoadScrollableRectWidget().
     {
         LoadWidthHeight(ctx);
         m_color = ctx.GetColorRGBA("color", false, vec4(0, 0, 0, 0));
         m_borderColor = ctx.GetColorRGBA("border", false, vec4(0, 0, 0, 0));
         m_borderWidth = ctx.GetInteger("borderwidth", false, 1);
         string borderType = ctx.GetString("bordertype", false, "inner");
              if (borderType == "middle") m_borderType = BorderType::Middle;
         else if (borderType == "outer") m_borderType = BorderType::Outer;
         m_shadowColor = ctx.GetColorRGBA("shadow", false, vec4(0, 0, 0, 0.5f));
         m_shadowSize = ctx.GetInteger("shadowsize", false, 0);
         string spriteset = ctx.GetString("spriteset", false, "");
         if (spriteset != "")
             @m_spriteRect = SpriteRect(spriteset);
         ScrollableWidget::Load(ctx);
     }
Member Data Documentation
m_borderColor
vec4 ScrollableRectWidget::m_borderColor private
Definition at line 5 of file ScrollableRectWidget.as.
Referenced by DoDraw(), and DoDraw().
m_borderType
BorderType ScrollableRectWidget::m_borderType private
Definition at line 7 of file ScrollableRectWidget.as.
Referenced by DoDraw().
m_borderWidth
int ScrollableRectWidget::m_borderWidth private
Definition at line 6 of file ScrollableRectWidget.as.
Referenced by DoDraw().
m_color
vec4 ScrollableRectWidget::m_color private
Definition at line 3 of file ScrollableRectWidget.as.
Referenced by DoDraw(), and DoDraw().
m_shadowColor
vec4 ScrollableRectWidget::m_shadowColor private
Definition at line 9 of file ScrollableRectWidget.as.
Referenced by DoDraw().
m_shadowSize
int ScrollableRectWidget::m_shadowSize private
Definition at line 10 of file ScrollableRectWidget.as.
Referenced by DoDraw().
m_spriteRect
SpriteRect ScrollableRectWidget::m_spriteRect private
Definition at line 12 of file ScrollableRectWidget.as.
Referenced by DoDraw().
The documentation for this class was generated from the following file:
scripts/GUI/ScrollableRectWidget.as