HoHDocs: BossScatterBurstSkill Class Reference
BossScatterBurstSkill Class Reference
Private Member Functions
BossScatterBurstSkill (UnitPtr unit, SValue &params)
Actor GetTarget () override
void NetUseSkill (int stage, SValue@ param) override
void NewBurstShot () override
Private Attributes
Actor m_currTarget
Detailed Description
Definition at line 1 of file BossScatterBurstSkill.as.
Constructor & Destructor Documentation
BossScatterBurstSkill()
BossScatterBurstSkill::BossScatterBurstSkill (UnitPtr unit, SValue & params) inline private
Definition at line 5 of file BossScatterBurstSkill.as.
References unit.
     {
         super(unit, params);
     }
Member Function Documentation
GetTarget()
Actor BossScatterBurstSkill::GetTarget () inline override private
Definition at line 10 of file BossScatterBurstSkill.as.
References CompositeActorSkill::m_behavior, and m_currTarget.
     {
         if (m_currTarget is null)
             return m_behavior.m_target;
         return m_currTarget;
     }
NetUseSkill()
void BossScatterBurstSkill::NetUseSkill (int stage, SValue@ param) inline override private
Definition at line 19 of file BossScatterBurstSkill.as.
References g_scene, m_currTarget, and CompositeActorBurstSkill::NetUseSkill().
     {
         if (stage == 100)
         {
             if (param !is null && param.GetType() == SValueType::Integer)
             {
                 auto newTarget = g_scene.GetUnit(param.GetInteger());
                 if (newTarget.IsValid())
                     @m_currTarget = cast<Actor>(newTarget.GetScriptBehavior());
             }
             return;
         }
         CompositeActorBurstSkill::NetUseSkill(stage, param);
     }
NewBurstShot()
void BossScatterBurstSkill::NewBurstShot () inline override private
Definition at line 37 of file BossScatterBurstSkill.as.
References g_scene, Actor::IsDead(), Actor::IsTargetable(), CompositeActorSkill::m_behavior, m_currTarget, CompositeActorSkill::m_id, CompositeActorSkill::m_rangeSq, Actor::m_unit, CompositeActorSkill::m_unit, UnitHandler::NetSendUnitUseSkill(), and xy().
     {
         if (m_behavior.m_target is null)
         {
             @m_currTarget = null;
             return;
         }
         if (!Network::IsServer())
             return;
         auto possibleTargets = g_scene.FetchActorsWithOtherTeam(m_behavior.Team, xy(m_behavior.m_unit.GetPosition()), uint(sqrt(m_rangeSq)));
         array<Actor@> targets;
         for (uint i = 0; i < possibleTargets.length(); i++)
         {
             Actor@ a = cast<Actor>(possibleTargets[i].GetScriptBehavior());
             if (!a.IsDead() && a.IsTargetable())
                 targets.insertLast(a);
         }
         auto ts = randi(targets.length());
         for (uint i = 0; i < targets.length(); i++)
         {
             Actor@ a = targets[(ts + i) % targets.length()];
             if (!a.IsDead() && a.IsTargetable())
             {
                 @m_currTarget = a;
                 SValueBuilder@ builder = SValueBuilder();
                 builder.PushInteger(a.m_unit.GetId());
                 UnitHandler::NetSendUnitUseSkill(m_unit, m_id, 100, builder.Build());
                 return;
             }
         }
     }
Member Data Documentation
m_currTarget
Actor BossScatterBurstSkill::m_currTarget private
Definition at line 3 of file BossScatterBurstSkill.as.
Referenced by GetTarget(), NetUseSkill(), and NewBurstShot().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Enemies/Skills/BossScatterBurstSkill.as