HoHDocs: WorldScript::ExploreMinimap Class Reference
WorldScript::ExploreMinimap Class Reference
Private Member Functions
SValue ServerExecute ()
void ClientExecute (SValue@ val)
void DebugDraw (vec2 pos, SpriteBatch &sb)
Private Attributes
vec3 Position
int Radius
Detailed Description
Definition at line 4 of file ExploreMinimap.as.
Member Function Documentation
ClientExecute()
void WorldScript::ExploreMinimap::ClientExecute (SValue@ val) inline private
Definition at line 21 of file ExploreMinimap.as.
References ServerExecute().
         {
             ServerExecute();
         }
DebugDraw()
void WorldScript::ExploreMinimap::DebugDraw (vec2 pos, SpriteBatch & sb) inline private
Definition at line 26 of file ExploreMinimap.as.
References Radius.
         {
             sb.DrawCircle(pos, Radius, vec4(0, 1, 1, 1), 25);
         }
ServerExecute()
SValue WorldScript::ExploreMinimap::ServerExecute () inline private
Definition at line 12 of file ExploreMinimap.as.
References g_gameMode, g_scene, Position, Radius, and xy().
Referenced by ClientExecute().
         {
             auto campaign = cast<Campaign>(g_gameMode);
             if (campaign !is null)
                 campaign.m_minimap.Explore(g_scene, xy(Position), Radius);
             return null;
         }
Member Data Documentation
Position
vec3 WorldScript::ExploreMinimap::Position private
Definition at line 6 of file ExploreMinimap.as.
Referenced by ServerExecute().
Radius
int WorldScript::ExploreMinimap::Radius private
Definition at line 9 of file ExploreMinimap.as.
Referenced by DebugDraw(), and ServerExecute().
The documentation for this class was generated from the following file:
scripts/WorldScript/ExploreMinimap.as