HoHDocs: Skills::SpewProjectiles Class Reference
Skills::SpewProjectiles Class Reference
Private Member Functions
SpewProjectiles (UnitPtr unit, SValue &params)
void Initialize (Actor@ owner, ScriptSprite@ icon, uint id) override
TargetingMode GetTargetingMode (int &out size) override
bool Activate (vec2 target) override
vec2 GetShootDir (vec2 dir)
UnitPtr ProduceProjectile (vec2 shootPos, int id=0)
void Hold (int dt, vec2 target) override
void NetHold (int dt, vec2 target) override
void Release (vec2 target) override
Private Attributes
UnitProducer m_projectile
int m_projectiles
array< IEffect@> m_effects
int m_effectDist
float m_spread
int m_shootDist
int m_interval
int m_intervalC
int m_spewInterval
int m_spewIntervalC
int m_effectInterval
int m_effectIntervalC
bool m_active
Detailed Description
Definition at line 3 of file SpewProjectiles.as.
Constructor & Destructor Documentation
SpewProjectiles()
Skills::SpewProjectiles::SpewProjectiles (UnitPtr unit, SValue & params) inline private
Definition at line 24 of file SpewProjectiles.as.
References LoadEffects(), m_effectDist, m_effectInterval, m_effectIntervalC, m_effects, m_interval, m_projectile, m_projectiles, m_shootDist, m_spewInterval, m_spread, and unit.
         {
             super(unit, params);
             @m_projectile = Resources::GetUnitProducer(GetParamString(unit, params, "projectile"));
             m_projectiles = GetParamInt(unit, params, "projectiles", false, 1);
             m_spread = GetParamInt(unit, params, "spread", false) * PI / 180.0;
             m_shootDist = GetParamInt(unit, params, "dist", false, 0);
             m_interval = GetParamInt(unit, params, "interval", false, 100);
             m_spewInterval = GetParamInt(unit, params, "spew-interval", false, 30);
             m_effectInterval = GetParamInt(unit, params, "effect-interval", false, 1000);
             m_effectIntervalC = m_effectInterval / 2;
             m_effectDist = GetParamInt(unit, params, "effect-dist", false, 0);
             @m_effects = LoadEffects(unit, params);
         }
Member Function Documentation
Activate()
bool Skills::SpewProjectiles::Activate (vec2 target) inline override private
Definition at line 49 of file SpewProjectiles.as.
References Skills::ActiveSkill::Activate(), m_effectInterval, m_effectIntervalC, m_interval, m_intervalC, m_spewInterval, and m_spewIntervalC.
         {
             if (!ActiveSkill::Activate(target))
                 return false;
             m_intervalC = m_interval;
             m_spewIntervalC = m_spewInterval;
             m_effectIntervalC = m_effectInterval;
             return true;
         }
GetShootDir()
vec2 Skills::SpewProjectiles::GetShootDir (vec2 dir) inline private
Definition at line 60 of file SpewProjectiles.as.
References m_spread.
Referenced by NetHold().
         {
             if (m_spread > 0)
             {
                 float rnd = (randf() - 0.5) * m_spread;
                 float ang = atan(dir.y, dir.x) + rnd;
                 return vec2(cos(ang), sin(ang));
             }
             return dir;
         }
GetTargetingMode()
TargetingMode Skills::SpewProjectiles::GetTargetingMode (int &out size) inline override private
Definition at line 47 of file SpewProjectiles.as.
References Skills::Channeling.
 { return TargetingMode::Channeling; }
Hold()
void Skills::SpewProjectiles::Hold (int dt, vec2 target) inline override private
Definition at line 77 of file SpewProjectiles.as.
References ApplyEffects(), m_effectDist, m_effectInterval, m_effectIntervalC, m_effects, Skills::m_owner, NetHold(), and xy().
         {
             NetHold(dt, target);
             m_effectIntervalC -= dt;
             while(m_effectIntervalC <= 0)
             {
                 m_effectIntervalC += m_effectInterval;
                 vec2 upos = xy(m_owner.m_unit.GetPosition()) + target * m_effectDist;
                 ApplyEffects(m_effects, m_owner, m_owner.m_unit, upos, target, 1.0, false);
             }
         }
Initialize()
void Skills::SpewProjectiles::Initialize (Actor@ owner, ScriptSprite@ icon, uint id) inline override private
Definition at line 41 of file SpewProjectiles.as.
References icon, Initialize(), m_effects, and PropagateWeaponInformation().
         {
             ActiveSkill::Initialize(owner, icon, id);
             PropagateWeaponInformation(m_effects, id + 1);
         }
NetHold()
void Skills::SpewProjectiles::NetHold (int dt, vec2 target) inline override private
Definition at line 91 of file SpewProjectiles.as.
References g_scene, GetShootDir(), m_active, Skills::ActiveSkill::m_animCountdown, Skills::ActiveSkill::m_cooldown, Skills::ActiveSkill::m_cooldownC, Skills::ActiveSkill::m_costHealth, Skills::ActiveSkill::m_costMana, Skills::ActiveSkill::m_costStamina, m_interval, m_intervalC, Skills::m_owner, m_projectiles, m_shootDist, Skills::m_skillId, m_spewInterval, m_spewIntervalC, Skills::ActiveSkill::NetHold(), ProduceProjectile(), and xy().
Referenced by Hold().
         {
             m_intervalC -= dt;
             m_cooldownC = m_cooldown;
             //m_castingC = m_castpoint;
             while(m_intervalC <= 0)
             {
                 m_active = true;
                 m_intervalC += m_interval;
                 if (!m_owner.SpendCost(m_costMana, m_costStamina, m_costHealth))
                 {
                     m_active = false;
                     return;
                 }
             }
             if (!m_active)
                 return;
             m_animCountdown = 50;
             m_spewIntervalC -= dt;
             while(m_spewIntervalC <= 0)
             {
                 m_spewIntervalC += m_spewInterval;
                 for (int i = 0; i < m_projectiles; i++)
                 {
                     vec2 shootDir = GetShootDir(target);
                     vec2 shootPos = xy(m_owner.m_unit.GetPosition()) + shootDir * m_shootDist;
                     if (m_shootDist > 0)
                     {
                         auto results = g_scene.RaycastClosest(xy(m_owner.m_unit.GetPosition()), shootPos, ~0, RaycastType::Shot);
                         if (results.FetchUnit(g_scene).IsValid())
                             shootPos = results.point;
                     }
                     auto proj = ProduceProjectile(shootPos);
                     if (!proj.IsValid())
                         continue;
                     IProjectile@ p = cast<IProjectile>(proj.GetScriptBehavior());
                     if (p is null)
                         continue;
                     p.Initialize(m_owner, shootDir, 1.0f, false, null, m_skillId + 1);
                 }
             }
             ActiveSkill::NetHold(dt, target);
         }
ProduceProjectile()
UnitPtr Skills::SpewProjectiles::ProduceProjectile (vec2 shootPos, int id = 0) inline private
Definition at line 72 of file SpewProjectiles.as.
References g_scene, m_projectile, and xyz().
Referenced by NetHold().
         {
             return m_projectile.Produce(g_scene, xyz(shootPos), id);
         }
Release()
void Skills::SpewProjectiles::Release (vec2 target) inline override private
Definition at line 146 of file SpewProjectiles.as.
References Skills::ActiveSkill::Release().
         {
             ActiveSkill::Release(target);
         }
Member Data Documentation
m_active
bool Skills::SpewProjectiles::m_active private
Definition at line 21 of file SpewProjectiles.as.
Referenced by NetHold().
m_effectDist
int Skills::SpewProjectiles::m_effectDist private
Definition at line 9 of file SpewProjectiles.as.
Referenced by Hold(), and SpewProjectiles().
m_effectInterval
int Skills::SpewProjectiles::m_effectInterval private
Definition at line 18 of file SpewProjectiles.as.
Referenced by Activate(), Hold(), and SpewProjectiles().
m_effectIntervalC
int Skills::SpewProjectiles::m_effectIntervalC private
Definition at line 19 of file SpewProjectiles.as.
Referenced by Activate(), Hold(), and SpewProjectiles().
m_effects
array<IEffect@> Skills::SpewProjectiles::m_effects private
Definition at line 8 of file SpewProjectiles.as.
Referenced by Hold(), Initialize(), and SpewProjectiles().
m_interval
int Skills::SpewProjectiles::m_interval private
Definition at line 14 of file SpewProjectiles.as.
Referenced by Activate(), NetHold(), and SpewProjectiles().
m_intervalC
int Skills::SpewProjectiles::m_intervalC private
Definition at line 15 of file SpewProjectiles.as.
Referenced by Activate(), and NetHold().
m_projectile
UnitProducer Skills::SpewProjectiles::m_projectile private
Definition at line 5 of file SpewProjectiles.as.
Referenced by ProduceProjectile(), and SpewProjectiles().
m_projectiles
int Skills::SpewProjectiles::m_projectiles private
Definition at line 6 of file SpewProjectiles.as.
Referenced by NetHold(), and SpewProjectiles().
m_shootDist
int Skills::SpewProjectiles::m_shootDist private
Definition at line 12 of file SpewProjectiles.as.
Referenced by NetHold(), and SpewProjectiles().
m_spewInterval
int Skills::SpewProjectiles::m_spewInterval private
Definition at line 16 of file SpewProjectiles.as.
Referenced by Activate(), NetHold(), and SpewProjectiles().
m_spewIntervalC
int Skills::SpewProjectiles::m_spewIntervalC private
Definition at line 17 of file SpewProjectiles.as.
Referenced by Activate(), and NetHold().
m_spread
float Skills::SpewProjectiles::m_spread private
Definition at line 11 of file SpewProjectiles.as.
Referenced by GetShootDir(), and SpewProjectiles().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Skills/SpewProjectiles.as