HoHDocs: SpawnPrefab Class Reference
SpawnPrefab Class Reference
Private Member Functions
SpawnPrefab (UnitPtr unit, SValue &params)
bool NeedNetParams ()
void SetWeaponInformation (uint weapon)
bool DoAction (SValueBuilder@ builder, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity)
void DoSpawnPrefabs (Actor@ owner, vec2 pos, vec2 dir)
void DoSpawnPrefab (vec2 pos, vec2 dir)
bool NetDoAction (SValue@ param, Actor@ owner, vec2 pos, vec2 dir)
bool Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
bool CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
void Update (int dt, int cooldown)
Private Attributes
int m_spawnDist
bool m_safeSpawning
vec2 m_offset
bool m_rotateOffset
Detailed Description
Definition at line 1 of file SpawnPrefab.as.
Constructor & Destructor Documentation
SpawnPrefab()
SpawnPrefab::SpawnPrefab (UnitPtr unit, SValue & params) inline private
Definition at line 8 of file SpawnPrefab.as.
References SpawnPrefabBase::Initialize(), m_offset, m_rotateOffset, m_safeSpawning, m_spawnDist, and unit.
Referenced by DoSpawnPrefab().
     {
         m_safeSpawning = GetParamBool(unit, params, "safe-spawn", false);
         m_spawnDist = GetParamInt(unit, params, "spawn-dist", false);
         m_offset = GetParamVec2(unit, params, "offset", false);
         if (m_offset.x != 0 || m_offset.y != 0)
             m_rotateOffset = GetParamBool(unit, params, "rotate-offset", false);
         Initialize(unit, params);
     }
Member Function Documentation
Apply()
bool SpawnPrefab::Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk) inline private
Definition at line 92 of file SpawnPrefab.as.
References DoSpawnPrefabs().
     {
         if (!husk)
             DoSpawnPrefabs(owner, pos, dir);
         return true;
     }
CanApply()
bool SpawnPrefab::CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) inline override private
Definition at line 99 of file SpawnPrefab.as.
     {
         return true;
     }
DoAction()
bool SpawnPrefab::DoAction (SValueBuilder@ builder, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity) inline private
Definition at line 22 of file SpawnPrefab.as.
References DoSpawnPrefabs().
     {
         DoSpawnPrefabs(owner, pos, dir);
         return true;
     }
DoSpawnPrefab()
void SpawnPrefab::DoSpawnPrefab (vec2 pos, vec2 dir) inline private
Definition at line 77 of file SpawnPrefab.as.
References addrot(), m_offset, m_rotateOffset, and SpawnPrefab().
Referenced by DoSpawnPrefabs().
     {
         if (m_rotateOffset)
             pos += addrot(m_offset, atan(dir.y, dir.x)) * length(m_offset);
         else
             pos += m_offset;
         SpawnPrefab(pos);
     }
DoSpawnPrefabs()
void SpawnPrefab::DoSpawnPrefabs (Actor@ owner, vec2 pos, vec2 dir) inline private
Definition at line 28 of file SpawnPrefab.as.
References SpawnPrefabBase::CalcJitter(), distsq(), DoSpawnPrefab(), g_scene, m_safeSpawning, m_spawnDist, and Actor::m_unit.
Referenced by Apply(), and DoAction().
     {
         auto origPos = pos;
         pos += CalcJitter();
         dir *= m_spawnDist;
         if (!m_safeSpawning)
             DoSpawnPrefab(pos + dir, dir);
         else
         {
             if (m_spawnDist == 0)
             {
                 bool canSpawn = true;
                 if (distsq(origPos, pos) > 1.0f && g_scene.RaycastQuick(origPos, pos, ~0, RaycastType::Any))
                     canSpawn = false;
                 if (canSpawn)
                 {
                     auto res = g_scene.QueryRect(pos, 1, 1, ~0, RaycastType::Any);
                     for (uint i = 0; i < res.length; i++)
                     {
                         if (owner.m_unit != res[i])
{
                             canSpawn = false;
                             break;
                         }
                     }
                 }
                 if (canSpawn)
                     DoSpawnPrefab(pos, dir);
             }
             else
             {
                 if (!g_scene.RaycastQuick(origPos, pos + dir, ~0, RaycastType::Any))
                     DoSpawnPrefab(pos + dir, dir);
                 else if (!g_scene.RaycastQuick(origPos, vec2(pos.x, pos.y - m_spawnDist), ~0, RaycastType::Any))
                     DoSpawnPrefab(vec2(pos.x, pos.y - m_spawnDist), dir);
                 else if (!g_scene.RaycastQuick(origPos, vec2(pos.x, pos.y + m_spawnDist), ~0, RaycastType::Any))
                     DoSpawnPrefab(vec2(pos.x, pos.y + m_spawnDist), dir);
                 else if (!g_scene.RaycastQuick(origPos, vec2(pos.x - m_spawnDist, pos.y), ~0, RaycastType::Any))
                     DoSpawnPrefab(vec2(pos.x - m_spawnDist, pos.y), dir);
                 else if (!g_scene.RaycastQuick(origPos, vec2(pos.x + m_spawnDist, pos.y), ~0, RaycastType::Any))
                     DoSpawnPrefab(vec2(pos.x + m_spawnDist, pos.y), dir);
             }
         }
     }
NeedNetParams()
bool SpawnPrefab::NeedNetParams () inline private
Definition at line 19 of file SpawnPrefab.as.
 { return false; }
NetDoAction()
bool SpawnPrefab::NetDoAction (SValue@ param, Actor@ owner, vec2 pos, vec2 dir) inline private
Definition at line 87 of file SpawnPrefab.as.
     {
         return true;
     }
SetWeaponInformation()
void SpawnPrefab::SetWeaponInformation (uint weapon) inline private
Definition at line 20 of file SpawnPrefab.as.
 {}
Update()
void SpawnPrefab::Update (int dt, int cooldown) inline private
Definition at line 104 of file SpawnPrefab.as.
     {
     }
Member Data Documentation
m_offset
vec2 SpawnPrefab::m_offset private
Definition at line 5 of file SpawnPrefab.as.
Referenced by DoSpawnPrefab(), and SpawnPrefab().
m_rotateOffset
bool SpawnPrefab::m_rotateOffset private
Definition at line 6 of file SpawnPrefab.as.
Referenced by DoSpawnPrefab(), and SpawnPrefab().
m_safeSpawning
bool SpawnPrefab::m_safeSpawning private
Definition at line 4 of file SpawnPrefab.as.
Referenced by DoSpawnPrefabs(), and SpawnPrefab().
m_spawnDist
int SpawnPrefab::m_spawnDist private
Definition at line 3 of file SpawnPrefab.as.
Referenced by DoSpawnPrefabs(), and SpawnPrefab().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actions/SpawnPrefab.as