HoHDocs: EffectBehavior Class Reference
EffectBehavior Class Reference
Private Member Functions
EffectBehavior (UnitPtr unit, SValue &params)
void Initialize (UnitScene@ scene)
void Initialize (UnitScene@ scene, dictionary params)
void Initialize (UnitScene@ scene, EffectParams@ params)
void SetParam (string param, float value)
void Update (int dt)
Private Attributes
UnitPtr m_unit
int m_ttl
bool m_looping
EffectParams m_params
array< WorldScript@> m_finishTriggers
Detailed Description
Definition at line 1 of file EffectBehavior.as.
Constructor & Destructor Documentation
EffectBehavior()
EffectBehavior::EffectBehavior (UnitPtr unit, SValue & params) inline private
Definition at line 9 of file EffectBehavior.as.
References m_ttl, m_unit, and unit.
     {
         m_unit = unit;
         m_ttl = unit.GetCurrentUnitScene().Length();
     }
Member Function Documentation
Initialize() [1/3]
void EffectBehavior::Initialize (UnitScene@ scene) inline private
Definition at line 15 of file EffectBehavior.as.
References LoadGore(), m_params, m_ttl, m_unit, PlaySound3D(), and xy().
Referenced by Initialize().
     {
         m_unit.SetUnitScene(scene, true);
         m_ttl = scene.Length();
         @m_params = null;
         if (scene !is null)
         {
             auto d = scene.FetchData("data");
             if (d !is null)
             {
                 PlaySound3D(Resources::GetSoundEvent(GetParamString(m_unit, d, "sound", false)), m_unit.GetPosition());
                 auto gore = LoadGore(GetParamString(m_unit, d, "gore", false));
                 if (gore !is null)
                     gore.OnDeath(1.0, xy(m_unit.GetPosition()));
             }
         }
     }
Initialize() [2/3]
void EffectBehavior::Initialize (UnitScene@ scene, dictionary params) inline private
Definition at line 34 of file EffectBehavior.as.
References Initialize(), m_params, and m_unit.
     {
         Initialize(scene);
         @m_params = m_unit.CreateEffectParams();
         auto keys = params.getKeys();
         for (uint i = 0; i < keys.length(); i++)
         {
             float val;
             params.get(keys[i], val);
             m_params.Set(keys[i], val);
         }
     }
Initialize() [3/3]
void EffectBehavior::Initialize (UnitScene@ scene, EffectParams@ params) inline private
Definition at line 49 of file EffectBehavior.as.
References Initialize(), m_params, and m_unit.
     {
         Initialize(scene);
         @m_params = m_unit.CreateEffectParams(params);
     }
SetParam()
void EffectBehavior::SetParam (string param, float value) inline private
Definition at line 56 of file EffectBehavior.as.
References m_params.
Referenced by PingBehavior::Update(), and ActorBuff::Update().
     {
         if (m_params !is null)
             m_params.Set(param, value);
     }
Update()
void EffectBehavior::Update (int dt) inline private
Definition at line 62 of file EffectBehavior.as.
References m_finishTriggers, m_looping, m_ttl, and m_unit.
     {
         if (!m_looping)
         {
             m_ttl -= dt;
             if (m_ttl <= 0)
             {
                 m_unit.Destroy();
                 if (Network::IsServer())
                 {
                     for (uint i = 0; i < m_finishTriggers.length(); i++)
                         m_finishTriggers[i].Execute();
                 }
             }
         }
     }
Member Data Documentation
m_finishTriggers
array<WorldScript@> EffectBehavior::m_finishTriggers private
Definition at line 7 of file EffectBehavior.as.
Referenced by Update().
m_looping
bool EffectBehavior::m_looping private
Definition at line 5 of file EffectBehavior.as.
Referenced by Update().
m_params
EffectParams EffectBehavior::m_params private
Definition at line 6 of file EffectBehavior.as.
Referenced by Initialize(), and SetParam().
m_ttl
int EffectBehavior::m_ttl private
Definition at line 4 of file EffectBehavior.as.
Referenced by EffectBehavior(), Initialize(), ActorBuff::Refresh(), and Update().
m_unit
UnitPtr EffectBehavior::m_unit private
Definition at line 3 of file EffectBehavior.as.
Referenced by EffectBehavior(), Initialize(), PingBehavior::Update(), and Update().
The documentation for this class was generated from the following file:
scripts/Behaviors/EffectBehavior.as