HoHDocs: FilteredListWidget Class Reference
FilteredListWidget Class Reference
Private Member Functions
FilteredListWidget ()
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void ShowAll ()
int SetFilter (string filter)
Detailed Description
Definition at line 1 of file FilteredListWidget.as.
Constructor & Destructor Documentation
FilteredListWidget()
FilteredListWidget::FilteredListWidget () inline private
Definition at line 3 of file FilteredListWidget.as.
Referenced by Clone().
     {
         super();
     }
Member Function Documentation
Clone()
Widget FilteredListWidget::Clone () inline override private
Definition at line 8 of file FilteredListWidget.as.
References Widget::CloneInto(), and FilteredListWidget().
     {
         FilteredListWidget@ w = FilteredListWidget();
         CloneInto(w);
         return w;
     }
Load()
void FilteredListWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 15 of file FilteredListWidget.as.
References Widget::Load(), Widget::LoadWidthHeight(), ScrollableWidget::m_autoScroll, ClipWidget::m_clipping, Widget::m_flow, and Vbox.
Referenced by FilteredListWidget().
     {
         ScrollableWidget::Load(ctx);
         if (ctx.GetBoolean("scrolling", false, true))
             m_clipping = m_autoScroll = true;
         else
             m_clipping = m_autoScroll = false;
         m_flow = WidgetFlow::Vbox;
         LoadWidthHeight(ctx);
     }
SetFilter()
int FilteredListWidget::SetFilter (string filter) inline private
Definition at line 35 of file FilteredListWidget.as.
References ScrollableWidget::m_autoScrollHeight, Widget::m_children, and ShowAll().
Referenced by Menu::OnFunc().
     {
         if (filter == "")
         {
             ShowAll();
             return int(m_children.length());
         }
         filter = filter.toLower();
         int visible = 0;
         for (uint i = 0; i < m_children.length(); i++)
         {
             auto child = m_children[i];
             child.m_visible = child.PassesFilter(filter);
             if (child.m_visible)
                 visible++;
         }
         m_autoScrollHeight = 0;
         return visible;
     }
ShowAll()
void FilteredListWidget::ShowAll () inline private
Definition at line 29 of file FilteredListWidget.as.
References Widget::m_children, and Widget::m_visible.
Referenced by Menu::OnFunc(), and SetFilter().
     {
         for (uint i = 0; i < m_children.length(); i++)
             m_children[i].m_visible = true;
     }
The documentation for this class was generated from the following file:
scripts/GUI/FilteredListWidget.as