HoHDocs: WorldScript::SpawnEffect Class Reference
WorldScript::SpawnEffect Class Reference
Private Member Functions
bool IsExecutable (UnitPtr unit)
SValue ServerExecute ()
void ClientExecute (SValue@ val)
Private Attributes
vec3 Position
UnitScene Effect
UnitFeed FinishTrigger
int Layer
Detailed Description
Definition at line 4 of file SpawnEffect.as.
Member Function Documentation
ClientExecute()
void WorldScript::SpawnEffect::ClientExecute (SValue@ val) inline private
Definition at line 48 of file SpawnEffect.as.
References ServerExecute().
         {
             ServerExecute();
         }
IsExecutable()
bool WorldScript::SpawnEffect::IsExecutable (UnitPtr unit) inline private
Definition at line 17 of file SpawnEffect.as.
References unit.
         {
             WorldScript@ script = WorldScript::GetWorldScript(unit);
             if (script is null)
                 return false;
             return script.IsExecutable();
         }
ServerExecute()
SValue WorldScript::SpawnEffect::ServerExecute () inline private
Definition at line 26 of file SpawnEffect.as.
References Effect, FinishTrigger, g_scene, Layer, PlayEffect(), Position, and xy().
Referenced by ClientExecute().
         {
             UnitPtr effectUnit = PlayEffect(Effect, xy(Position));
             if (!effectUnit.IsValid())
                 return null;
             if (Layer != 0)
                 effectUnit.SetLayer(Layer);
             if (Network::IsServer())
             {
                 auto fx = cast<EffectBehavior>(effectUnit.GetScriptBehavior());
                 auto triggerArr = FinishTrigger.FetchAll();
                 for (uint i = 0; i < triggerArr.length(); i++)
                 {
                     auto callbackScript = WorldScript::GetWorldScript(g_scene, triggerArr[i].GetScriptBehavior());
                     fx.m_finishTriggers.insertLast(callbackScript);
                 }
             }
             return null;
         }
Member Data Documentation
Effect
UnitScene WorldScript::SpawnEffect::Effect private
Definition at line 9 of file SpawnEffect.as.
Referenced by ServerExecute().
FinishTrigger
UnitFeed WorldScript::SpawnEffect::FinishTrigger private
Definition at line 12 of file SpawnEffect.as.
Referenced by ServerExecute().
Layer
int WorldScript::SpawnEffect::Layer private
Definition at line 15 of file SpawnEffect.as.
Referenced by ServerExecute().
Position
vec3 WorldScript::SpawnEffect::Position private
Definition at line 6 of file SpawnEffect.as.
Referenced by ServerExecute().
The documentation for this class was generated from the following file:
scripts/WorldScript/SpawnEffect.as