HoHDocs: AreaTrigger Class Reference
AreaTrigger Class Reference
Private Member Functions
void Initialize ()
void OnEnabledChanged (bool enabled)
void OnEnter (UnitPtr unit, vec2 pos, vec2 normal)
void OnExit (UnitPtr unit)
SValue ServerExecute ()
Private Attributes
AreaEvent Event
array< CollisionArea@> Areas
AreaFilter Filter
UnitSource AllInside
UnitSource LastEntered
UnitSource LastExited
Detailed Description
Definition at line 61 of file AreaTrigger.as.
Member Function Documentation
Initialize()
void AreaTrigger::Initialize () inline private
Definition at line 77 of file AreaTrigger.as.
         {
             if (Network::IsServer())
             {
                 for (uint i = 0; i < Areas.length(); i++)
                 {
                     Areas[i].AddOnEnter(this, "OnEnter");
                     Areas[i].AddOnExit(this, "OnExit");
                 }
             }
         }
OnEnabledChanged()
void AreaTrigger::OnEnabledChanged (bool enabled) inline private
Definition at line 89 of file AreaTrigger.as.
References ApplyAreaFilter(), g_scene, OnEnter, and unit.
         {
             auto script = WorldScript::GetWorldScript(g_scene, this);
             if (enabled)
             {
                 UnitPtr unit;
                 for (uint i = 0; i < Areas.length(); i++)
                 {
                     auto units = Areas[i].FetchAllInside(g_scene);
                     for (uint j = 0; j < units.length; j++)
                     {
                         if (!ApplyAreaFilter(units[j], Filter))
                             continue;
                         unit = units[j];
                         AllInside.Add(units[j]);
                         if (Event == AreaEvent::OnEnter)
{
                             LastEntered.Replace(unit);
                             script.Execute();
                         }
                     }
                 }
                 if (unit.IsValid() && Event != AreaEvent::OnEnter)
                     LastEntered.Replace(unit);
             }
             else
             {
                 AllInside.Clear();
                 if (Event == AreaEvent::OnExit)
                 {
                     for (uint i = 0; i < Areas.length(); i++)
                     {
                         auto units = Areas[i].FetchAllInside(g_scene);
                         for (uint j = 0; j < units.length; j++)
{
                             if (!ApplyAreaFilter(units[j], Filter))
                                 continue;
                             LastExited.Replace(units[j]);
                             script.Execute();
                         }
                     }
                 }
                 else
                 {
                     for (uint i = 0; i < Areas.length(); i++)
                     {
                         auto units = Areas[i].FetchAllInside(g_scene);
                         for (uint j = 0; j < units.length; j++)
{
                             if (!ApplyAreaFilter(units[j], Filter))
                                 continue;
                             LastExited.Replace(units[j]);
                             return;
                         }
                     }
                 }
             }
         }
OnEnter()
void AreaTrigger::OnEnter (UnitPtr unit, vec2 pos, vec2 normal) inline private
Definition at line 153 of file AreaTrigger.as.
References ApplyAreaFilter(), g_scene, OnEnter, and unit.
         {
             if (ApplyAreaFilter(unit, Filter))
             {
                 LastEntered.Replace(unit);
                 AllInside.Add(unit);
                 if (Event == AreaEvent::OnEnter)
                     WorldScript::GetWorldScript(g_scene, this).Execute();
             }
         }
OnExit()
void AreaTrigger::OnExit (UnitPtr unit) inline private
Definition at line 165 of file AreaTrigger.as.
References ApplyAreaFilter(), g_scene, and unit.
         {
             if (ApplyAreaFilter(unit, Filter))
             {
                 LastExited.Replace(unit);
                 AllInside.Remove(unit);
                 if (Event == AreaEvent::OnExit)
                     WorldScript::GetWorldScript(g_scene, this).Execute();
             }
         }
ServerExecute()
SValue AreaTrigger::ServerExecute () inline private
Definition at line 177 of file AreaTrigger.as.
         {
             return null;
         }
Member Data Documentation
AllInside
UnitSource AreaTrigger::AllInside private
Definition at line 72 of file AreaTrigger.as.
Areas
array<CollisionArea@> AreaTrigger::Areas private
Definition at line 67 of file AreaTrigger.as.
Event
AreaEvent AreaTrigger::Event private
Definition at line 64 of file AreaTrigger.as.
Filter
AreaFilter AreaTrigger::Filter private
Definition at line 70 of file AreaTrigger.as.
LastEntered
UnitSource AreaTrigger::LastEntered private
Definition at line 73 of file AreaTrigger.as.
LastExited
UnitSource AreaTrigger::LastExited private
Definition at line 74 of file AreaTrigger.as.
The documentation for this class was generated from the following file:
scripts/WorldScript/AreaTrigger.as