HoHDocs: Menu::CharacterCustomizationMenu Class Reference
Menu::CharacterCustomizationMenu Class Reference
Private Member Functions
CharacterCustomizationMenu (MenuProvider@ provider, CharacterCreationMenu@ creationMenu, string context)
void Initialize (GUIDef@ def) override
void OnFunc (Widget@ sender, string name) override
Private Attributes
string m_context
CharacterCustomizationBase m_base
Detailed Description
Definition at line 3 of file CharacterCustomizationMenu.as.
Constructor & Destructor Documentation
CharacterCustomizationMenu()
Menu::CharacterCustomizationMenu::CharacterCustomizationMenu (MenuProvider@ provider, CharacterCreationMenu@ creationMenu, string context) inline private
Definition at line 9 of file CharacterCustomizationMenu.as.
References m_base, Menu::CharacterCreationMenu::m_charClass, and m_context.
         {
             super(provider);
             m_context = context;
             @m_base = CharacterCustomizationBase(creationMenu.m_charClass, this);
         }
Member Function Documentation
Initialize()
void Menu::CharacterCustomizationMenu::Initialize (GUIDef@ def) inline override private
Definition at line 18 of file CharacterCustomizationMenu.as.
References CharacterCustomizationBase::Initialize(), and m_base.
         {
             m_base.Initialize(def);
         }
OnFunc()
void Menu::CharacterCustomizationMenu::OnFunc (Widget@ sender, string name) inline override private
Definition at line 23 of file CharacterCustomizationMenu.as.
References HwrSaves::CreateCharacter(), Menu::HwrMenu::FinishContext(), m_base, CharacterCustomizationBase::m_charClass, m_context, CharacterCustomizationBase::m_dyes, CharacterCustomizationBase::m_face, TextInputWidget::m_text, CharacterCustomizationBase::m_voice, CharacterCustomizationBase::m_wName, name, Menu::Menu::OnFunc(), CharacterCustomizationBase::OnFunc(), and HwrSaves::PickCharacter().
         {
             if (!m_base.OnFunc(sender, name))
             {
                 auto parse = name.split(" ");
                 if (parse[0] == "finish")
                 {
                     SValueBuilder builder;
                     builder.PushDictionary();
                     builder.PushString("name", m_base.m_wName.m_text.plain());
                     builder.PushString("class", m_base.m_charClass);
                     builder.PushArray("colors");
                     for (uint i = 0; i < m_base.m_dyes.length(); i++)
                     {
                         auto dye = m_base.m_dyes[i];
                         builder.PushArray();
                         builder.PushInteger(int(dye.m_category));
                         builder.PushInteger(dye.m_idHash);
                         builder.PopArray();
                     }
                     builder.PopArray();
                     builder.PushInteger("face", m_base.m_face);
                     builder.PushFloat("voice", m_base.m_voice);
                     // Without this, the character list shows level 0
                     builder.PushInteger("level", 1);
                     HwrSaves::CreateCharacter(builder.Build());
                     HwrSaves::PickCharacter(0);
                     FinishContext(m_context);
                 }
                 else
                     HwrMenu::OnFunc(sender, name);
             }
         }
Member Data Documentation
m_base
CharacterCustomizationBase Menu::CharacterCustomizationMenu::m_base private
Definition at line 7 of file CharacterCustomizationMenu.as.
Referenced by CharacterCustomizationMenu(), Initialize(), and OnFunc().
m_context
string Menu::CharacterCustomizationMenu::m_context private
Definition at line 5 of file CharacterCustomizationMenu.as.
Referenced by CharacterCustomizationMenu(), and OnFunc().
The documentation for this class was generated from the following file:
scripts/GUI/Menus/CharacterCustomizationMenu.as