HoHDocs: MultiplePlayersTab Class Reference
MultiplePlayersTab Class Reference
Private Member Functions
void OnShow () override
void UpdateFromLocal ()
void UpdateNow ()
void UpdateNow (PlayerRecord@ record)
bool OnFunc (Widget@ sender, string name) override
Private Attributes
int m_currentPlayerIndex
Detailed Description
Definition at line 1 of file MultiplePlayersTab.as.
Member Function Documentation
OnFunc()
bool MultiplePlayersTab::OnFunc (Widget@ sender, string name) inline override private
Definition at line 103 of file MultiplePlayersTab.as.
References m_currentPlayerIndex, name, NumConnectedPlayers(), and UpdateNow().
     {
         if (name == "char-prev")
         {
             if (--m_currentPlayerIndex < 0)
                 m_currentPlayerIndex = NumConnectedPlayers() - 1;
             UpdateNow();
             return true;
         }
         else if (name == "char-next")
         {
             if (++m_currentPlayerIndex >= NumConnectedPlayers())
                 m_currentPlayerIndex = 0;
             UpdateNow();
             return true;
         }
         return false;
     }
OnShow()
void MultiplePlayersTab::OnShow () inline override private
Definition at line 5 of file MultiplePlayersTab.as.
References Widget::GetWidgetById(), MenuTab::m_widget, NumConnectedPlayers(), MenuTab::OnShow(), and UpdateFromLocal().
Referenced by PlayerMenuCharacterTab::OnShow().
     {
         PlayerMenuTab::OnShow();
         UpdateFromLocal();
         int connectedPlayers = NumConnectedPlayers();
         auto wPlayerButtonLeft = cast<SpriteButtonWidget>(m_widget.GetWidgetById("player-button-left"));
         if (wPlayerButtonLeft !is null)
             wPlayerButtonLeft.m_enabled = (connectedPlayers > 1);
         auto wPlayerButtonRight = cast<SpriteButtonWidget>(m_widget.GetWidgetById("player-button-right"));
         if (wPlayerButtonRight !is null)
             wPlayerButtonRight.m_enabled = (connectedPlayers > 1);
     }
UpdateFromLocal()
void MultiplePlayersTab::UpdateFromLocal () inline private
Definition at line 22 of file MultiplePlayersTab.as.
References g_players, m_currentPlayerIndex, and UpdateNow().
Referenced by OnShow(), and UpdateNow().
     {
         for (uint i = 0; i < g_players.length(); i++)
         {
             if (g_players[i].local)
             {
                 m_currentPlayerIndex = i;
                 break;
             }
         }
         UpdateNow(g_players[m_currentPlayerIndex]);
     }
UpdateNow() [1/2]
void MultiplePlayersTab::UpdateNow () inline private
Definition at line 35 of file MultiplePlayersTab.as.
References g_players, m_currentPlayerIndex, and UpdateFromLocal().
Referenced by OnFunc(), UpdateFromLocal(), PlayerMenuStatsTab::UpdateNow(), and PlayerMenuCharacterTab::UpdateNow().
     {
         int curIndex = 0;
         for (uint i = 0; i < g_players.length(); i++)
         {
             if (g_players[i].peer == 255)
                 continue;
             if (curIndex == m_currentPlayerIndex)
             {
                 UpdateNow(g_players[i]);
                 return;
             }
             curIndex++;
         }
         PrintError("Couldn't find player with active index " + m_currentPlayerIndex);
         UpdateFromLocal();
     }
UpdateNow() [2/2]
void MultiplePlayersTab::UpdateNow (PlayerRecord@ record) inline private
Definition at line 55 of file MultiplePlayersTab.as.
References GetFaceSprite(), GetPlayerColor(), GetPlayerName(), Widget::GetWidgetById(), ColorHSV::m_saturation, ColorHSV::m_value, MenuTab::m_widget, and ColorHSV::ToColorRGBA().
     {
         // Player face
         auto wFace = cast<SpriteWidget>(m_widget.GetWidgetById("playerface"));
         if (wFace !is null)
         {
             wFace.SetSprite(GetFaceSprite(record.charClass, record.face));
             wFace.m_multiColors = record.GetMulticolors();
         }
         // Player header
         vec4 playerColor = ParseColorRGBA("#" + GetPlayerColor(record.peer) + "ff");
         auto wPlayerName = cast<TextWidget>(m_widget.GetWidgetById("playername"));
         if (wPlayerName !is null)
         {
             wPlayerName.SetText(Lobby::GetPlayerName(record.peer));
             wPlayerName.SetColor(playerColor);
         }
         auto wPlayerTitle = cast<TextWidget>(m_widget.GetWidgetById("playertitle"));
         if (wPlayerTitle !is null)
         {
             auto title = record.GetTitle();
             dictionary titleParams = {
                 { "name", record.GetName() },
                 { "title", title is null ? Resources::GetString(".titles.guild-0") : Resources::GetString(title.m_name) },
                 { "lvl", "" + record.level },
                 { "class", Resources::GetString(".class." + record.charClass) }
             };
             wPlayerTitle.SetText(Resources::GetString(".hud.character.title", titleParams));
         }
         auto wPlayerHeader = cast<RectWidget>(m_widget.GetWidgetById("playerheader"));
         if (wPlayerHeader !is null)
         {
             if (record.local)
                 wPlayerHeader.m_color = ParseColorRGBA("#202A26FF");
             else
             {
                 ColorHSV hsv(playerColor);
                 hsv.m_saturation *= 0.5f;
                 hsv.m_value *= 0.35f;
                 wPlayerHeader.m_color = tocolor(hsv.ToColorRGBA());
             }
         }
     }
Member Data Documentation
m_currentPlayerIndex
int MultiplePlayersTab::m_currentPlayerIndex private
Definition at line 3 of file MultiplePlayersTab.as.
Referenced by OnFunc(), UpdateFromLocal(), and UpdateNow().
The documentation for this class was generated from the following file:
scripts/GUI/PlayerMenu/MultiplePlayersTab.as