HoHDocs: WorldScript::BossBarCheckpoint Class Reference
WorldScript::BossBarCheckpoint Class Reference
Private Member Functions
bool IsActor (UnitPtr unit)
SValue ServerExecute ()
void ClientExecute (SValue@ val)
Private Attributes
UnitFeed Actors
bool OverActor
float Factor
Detailed Description
Definition at line 4 of file BossBarCheckpoint.as.
Member Function Documentation
ClientExecute()
void WorldScript::BossBarCheckpoint::ClientExecute (SValue@ val) inline private
Definition at line 58 of file BossBarCheckpoint.as.
References ServerExecute().
         {
             ServerExecute();
         }
IsActor()
bool WorldScript::BossBarCheckpoint::IsActor (UnitPtr unit) inline private
Definition at line 15 of file BossBarCheckpoint.as.
References unit.
         {
             return cast<Actor>(unit.GetScriptBehavior()) !is null;
         }
ServerExecute()
SValue WorldScript::BossBarCheckpoint::ServerExecute () inline private
Definition at line 20 of file BossBarCheckpoint.as.
References Actors, Factor, g_gameMode, HUD::GetBossBar(), GetHUD(), BossBarWidget::m_checkpoint, OverheadBossBar::m_checkpoint, and OverActor.
Referenced by ClientExecute().
         {
             HUD@ hud = GetHUD();
             auto gm = cast<BaseGameMode>(g_gameMode);
             auto units = Actors.FetchAll();
             for (uint i = 0; i < units.length(); i++)
             {
                 Actor@ actor = cast<Actor>(units[i].GetScriptBehavior());
                 if (OverActor)
                 {
                     OverheadBossBar@ bar = null;
                     if (gm !is null)
                         @bar = gm.GetBossBarActor(actor);
                     if (bar is null)
                     {
                         PrintError("There is no overhead boss bar found for the actor at unit " + units[i].GetId());
                         continue;
                     }
                     bar.m_checkpoint = Factor;
                 }
                 else
                 {
                     BossBarWidget@ bar = hud.GetBossBar(actor);
                     if (bar is null)
                     {
                         PrintError("There is no boss bar widget found for the actor at unit " + units[i].GetId());
                         continue;
                     }
                     bar.m_checkpoint = Factor;
                 }
             }
             return null;
         }
Member Data Documentation
Actors
UnitFeed WorldScript::BossBarCheckpoint::Actors private
Definition at line 7 of file BossBarCheckpoint.as.
Referenced by ServerExecute().
Factor
float WorldScript::BossBarCheckpoint::Factor private
Definition at line 13 of file BossBarCheckpoint.as.
Referenced by ServerExecute().
OverActor
bool WorldScript::BossBarCheckpoint::OverActor private
Definition at line 10 of file BossBarCheckpoint.as.
Referenced by ServerExecute().
The documentation for this class was generated from the following file:
scripts/WorldScript/BossBarCheckpoint.as