HoHDocs: Menu::TestMenu Class Reference
Menu::TestMenu Class Reference
Private Member Functions
TestMenu (MenuProvider@ provider)
void Initialize (GUIDef@ def) override
void Update (int dt) override
bool Close () override
void OnFunc (Widget@ sender, string name) override
Private Attributes
Widget m_wList
Widget m_wTemplate
Detailed Description
Definition at line 3 of file TestMenu.as.
Constructor & Destructor Documentation
TestMenu()
Menu::TestMenu::TestMenu (MenuProvider@ provider) inline private
Definition at line 8 of file TestMenu.as.
         {
             super(provider);
         }
Member Function Documentation
Close()
bool Menu::TestMenu::Close () inline override private
Definition at line 26 of file TestMenu.as.
         {
             return false;
         }
Initialize()
void Menu::TestMenu::Initialize (GUIDef@ def) inline override private
Definition at line 13 of file TestMenu.as.
References Menu::Menu::Initialize(), m_widget, m_wList, and m_wTemplate.
         {
             Menu::Initialize(def);
             @m_wList = m_widget.GetWidgetById("testlist");
             @m_wTemplate = m_widget.GetWidgetById("template");
         }
OnFunc()
void Menu::TestMenu::OnFunc (Widget@ sender, string name) inline override private
Definition at line 31 of file TestMenu.as.
References Widget::AddChild(), Widget::Clone(), Widget::m_children, m_wList, m_wTemplate, name, Menu::Menu::OnFunc(), and Widget::SetID().
         {
             if (name == "add")
             {
                 auto wNewItem = m_wTemplate.Clone();
                 wNewItem.SetID("");
                 wNewItem.m_visible = true;
                 m_wList.AddChild(wNewItem);
             }
             else if (name == "delete")
             {
                 if (m_wList.m_children.length() > 0)
                     m_wList.m_children[m_wList.m_children.length() - 1].RemoveFromParent();
             }
             Menu::OnFunc(sender, name);
         }
Update()
void Menu::TestMenu::Update (int dt) inline override private
Definition at line 21 of file TestMenu.as.
References Menu::Update().
         {
             Menu::Update(dt);
         }
Member Data Documentation
m_wList
Widget Menu::TestMenu::m_wList private
Definition at line 5 of file TestMenu.as.
Referenced by Initialize(), and OnFunc().
m_wTemplate
Widget Menu::TestMenu::m_wTemplate private
Definition at line 6 of file TestMenu.as.
Referenced by Initialize(), and OnFunc().
The documentation for this class was generated from the following file:
scripts/GUI/Menus/TestMenu.as