HoHDocs: ShopButtonWidget Class Reference
ShopButtonWidget Class Reference
Private Member Functions
ShopButtonWidget ()
void Load (WidgetLoadingContext &ctx) override
Widget Clone () override
int OwnedGold ()
int OwnedOre ()
void SetPriceGold (int amount)
void SetPriceOre (int amount)
void SetPriceSkillPoints (int amount)
void SetPrice (int amount)
void DrawIcon (SpriteBatch &sb, vec2 pos, vec4 color)
void UpdateEnabled ()
void DoDraw (SpriteBatch &sb, vec2 pos) override
Private Attributes
Sprite m_spriteIconFrame
Sprite m_spriteIcon
Sprite m_itemDot
Sprite m_itemPlus
Sprite m_spriteGold
Sprite m_spriteOre
Sprite m_spriteSkillPoints
Sprite m_spriteCurrency
BitmapFont m_fontPrice
BitmapString m_textPrice
bool m_canAfford
bool m_shopRestricted
Detailed Description
Definition at line 1 of file ShopButtonWidget.as.
Constructor & Destructor Documentation
ShopButtonWidget()
ShopButtonWidget::ShopButtonWidget () inline private
Definition at line 20 of file ShopButtonWidget.as.
Referenced by Clone().
     {
         super();
     }
Member Function Documentation
Clone()
Widget ShopButtonWidget::Clone () inline override private
Definition at line 48 of file ShopButtonWidget.as.
References Widget::CloneInto(), and ShopButtonWidget().
Referenced by StatuesShopMenuContent::RefreshBuyList().
     {
         ShopButtonWidget@ w = ShopButtonWidget();
         CloneInto(w);
         return w;
     }
DoDraw()
void ShopButtonWidget::DoDraw (SpriteBatch & sb, vec2 pos) inline override private
Definition at line 116 of file ShopButtonWidget.as.
References ScalableSpriteButtonWidget::DoDraw(), DrawIcon(), g_menuTime, ScalableSpriteButtonWidget::GetTextColor(), m_canAfford, ScalableSpriteButtonWidget::m_enabled, Widget::m_height, m_spriteCurrency, m_spriteIconFrame, ScalableSpriteButtonWidget::m_text, m_textPrice, and Widget::m_width.
     {
         ScalableSpriteButtonWidget::DoDraw(sb, pos);
         if (!m_enabled)
             sb.EnableColorize(vec4(0, 0, 0, 1), vec4(0.125, 0.125, 0.125, 1), vec4(0.25, 0.25, 0.25, 1));
         DrawIcon(sb, pos + vec2(3, 3), vec4(1,1,1,1));
         if (!m_enabled)
             sb.DisableColorize();
         if (m_width > 64 && m_textPrice !is null)
         {
             if (m_canAfford)
                 m_textPrice.SetColor(GetTextColor());
             else
                 m_textPrice.SetColor(vec4(1, 0, 0, 1));
             vec2 spritePos;
             vec2 textPos;
             if (m_text is null)
             {
                 int contentOffset = m_spriteIconFrame.GetWidth();
                 int contentWidth = m_width - contentOffset;
                 int currencyWidth = m_textPrice.GetWidth() + 2;
                 if (m_spriteCurrency !is null)
                     currencyWidth += m_spriteCurrency.GetWidth();
                 textPos = vec2(
                     pos.x + contentOffset + contentWidth / 2 - currencyWidth / 2,
                     pos.y + m_height / 2 - m_textPrice.GetHeight() / 2 - 1
                 );
                 if (m_spriteCurrency !is null)
                 {
                     spritePos = vec2(
                         textPos.x + m_textPrice.GetWidth() + 2,
                         pos.y + m_height / 2 - m_spriteCurrency.GetHeight() / 2
                     );
                 }
             }
             else
             {
                 if (m_spriteCurrency !is null)
                 {
                     spritePos = vec2(
                         pos.x + m_width - m_spriteCurrency.GetWidth() - 8,
                         pos.y + m_height / 2 - m_spriteCurrency.GetHeight() / 2
                     );
                     textPos = vec2(
                         spritePos.x - m_textPrice.GetWidth() - 2,
                         pos.y + m_height / 2 - m_textPrice.GetHeight() / 2 - 1
                     );
                 }
                 else
                 {
                     textPos = vec2(
                         pos.x + m_width - m_textPrice.GetWidth() - 10,
                         pos.y + m_height / 2 - m_textPrice.GetHeight() / 2
                     );
                 }
             }
             if (m_spriteCurrency !is null)
                 sb.DrawSprite(spritePos, m_spriteCurrency, g_menuTime);
             sb.DrawString(textPos, m_textPrice);
         }
     }
DrawIcon()
void ShopButtonWidget::DrawIcon (SpriteBatch & sb, vec2 pos, vec4 color) inline private
Definition at line 104 of file ShopButtonWidget.as.
References g_menuTime, m_spriteIcon, and m_spriteIconFrame.
Referenced by DoDraw().
     {
         sb.DrawSprite(pos, m_spriteIconFrame, g_menuTime, color);
         if (m_spriteIcon !is null)
             sb.DrawSprite(pos + vec2(1, 1), m_spriteIcon, g_menuTime, color);
     }
Load()
void ShopButtonWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 25 of file ShopButtonWidget.as.
References Widget::Load(), ScalableSpriteButtonWidget::m_font, m_fontPrice, m_itemDot, m_itemPlus, ScalableSpriteButtonWidget::m_pressSound, m_spriteGold, m_spriteIcon, m_spriteIconFrame, m_spriteOre, m_spriteSkillPoints, and ScalableSpriteButtonWidget::m_textOffset.
Referenced by LoadShopButtonWidget().
     {
         m_textOffset = vec2(36, -1);
         ScalableSpriteButtonWidget::Load(ctx);
         @m_pressSound = null;
         @m_font = Resources::GetBitmapFont("gui/fonts/arial11.fnt");
         @m_fontPrice = Resources::GetBitmapFont("gui/fonts/arial11.fnt");
         auto def = ctx.GetGUIDef();
         @m_spriteIconFrame = def.GetSprite("frame-icon");
         @m_spriteIcon = def.GetSprite(ctx.GetString("icon", false));
         @m_itemDot = def.GetSprite("item-dot");
         @m_itemPlus = def.GetSprite("item-plus");
         @m_spriteGold = def.GetSprite("gold");
         @m_spriteOre = def.GetSprite("ore");
         @m_spriteSkillPoints = def.GetSprite("skill-points");
     }
OwnedGold()
int ShopButtonWidget::OwnedGold () inline private
Definition at line 55 of file ShopButtonWidget.as.
References g_gameMode, and GetLocalPlayerRecord().
Referenced by SetPriceGold().
     {
         auto gm = cast<Campaign>(g_gameMode);
         if (cast<Town>(gm) is null)
             return GetLocalPlayerRecord().runGold;
         return gm.m_townLocal.m_gold;
     }
OwnedOre()
int ShopButtonWidget::OwnedOre () inline private
Definition at line 65 of file ShopButtonWidget.as.
References g_gameMode, and GetLocalPlayerRecord().
Referenced by SetPriceOre().
     {
         auto gm = cast<Campaign>(g_gameMode);
         if (cast<Town>(gm) is null)
             return GetLocalPlayerRecord().runOre;
         return gm.m_townLocal.m_ore;
     }
SetPrice()
void ShopButtonWidget::SetPrice (int amount) inline private
Definition at line 96 of file ShopButtonWidget.as.
References formatThousands(), m_fontPrice, and m_textPrice.
Referenced by UpgradeShopButtonWidget::Set(), SetPriceGold(), SetPriceOre(), and SetPriceSkillPoints().
     {
         if (amount != 0)
             @m_textPrice = m_fontPrice.BuildText(formatThousands(amount));
         else
             @m_textPrice = null;
     }
SetPriceGold()
void ShopButtonWidget::SetPriceGold (int amount) inline private
Definition at line 75 of file ShopButtonWidget.as.
References m_canAfford, m_spriteCurrency, m_spriteGold, OwnedGold(), and SetPrice().
Referenced by UpgradeShopButtonWidget::Set().
     {
         @m_spriteCurrency = m_spriteGold;
         m_canAfford = (OwnedGold() >= amount);
         SetPrice(amount);
     }
SetPriceOre()
void ShopButtonWidget::SetPriceOre (int amount) inline private
Definition at line 82 of file ShopButtonWidget.as.
References m_canAfford, m_spriteCurrency, m_spriteOre, OwnedOre(), and SetPrice().
Referenced by UpgradeShopButtonWidget::Set().
     {
         @m_spriteCurrency = m_spriteOre;
         m_canAfford = (OwnedOre() >= amount);
         SetPrice(amount);
     }
SetPriceSkillPoints()
void ShopButtonWidget::SetPriceSkillPoints (int amount) inline private
Definition at line 89 of file ShopButtonWidget.as.
References GetLocalPlayerRecord(), m_canAfford, m_spriteCurrency, m_spriteSkillPoints, and SetPrice().
Referenced by UpgradeShopButtonWidget::Set().
     {
         @m_spriteCurrency = m_spriteSkillPoints;
         m_canAfford = (GetLocalPlayerRecord().GetAvailableSkillpoints() >= amount);
         SetPrice(amount);
     }
UpdateEnabled()
void ShopButtonWidget::UpdateEnabled () inline private
Definition at line 111 of file ShopButtonWidget.as.
References m_canAfford, ScalableSpriteButtonWidget::m_enabled, and m_shopRestricted.
Referenced by UpgradeShopButtonWidget::Set().
     {
         m_enabled = (m_canAfford && !m_shopRestricted);
     }
Member Data Documentation
m_canAfford
bool ShopButtonWidget::m_canAfford private
Definition at line 17 of file ShopButtonWidget.as.
Referenced by DoDraw(), SetPriceGold(), SetPriceOre(), SetPriceSkillPoints(), and UpdateEnabled().
m_fontPrice
BitmapFont ShopButtonWidget::m_fontPrice private
Definition at line 14 of file ShopButtonWidget.as.
Referenced by Load(), and SetPrice().
m_itemDot
Sprite ShopButtonWidget::m_itemDot private
Definition at line 5 of file ShopButtonWidget.as.
Referenced by Upgrades::ItemUpgradeStep::DrawShopIcon(), and Load().
m_itemPlus
Sprite ShopButtonWidget::m_itemPlus private
Definition at line 6 of file ShopButtonWidget.as.
Referenced by Upgrades::ItemUpgradeStep::DrawShopIcon(), and Load().
m_shopRestricted
bool ShopButtonWidget::m_shopRestricted private
Definition at line 18 of file ShopButtonWidget.as.
Referenced by UpgradeShopButtonWidget::Set(), and UpdateEnabled().
m_spriteCurrency
Sprite ShopButtonWidget::m_spriteCurrency private
Definition at line 12 of file ShopButtonWidget.as.
Referenced by DoDraw(), SetPriceGold(), SetPriceOre(), and SetPriceSkillPoints().
m_spriteGold
Sprite ShopButtonWidget::m_spriteGold private
Definition at line 8 of file ShopButtonWidget.as.
Referenced by Load(), and SetPriceGold().
m_spriteIcon
Sprite ShopButtonWidget::m_spriteIcon private
Definition at line 4 of file ShopButtonWidget.as.
Referenced by UpgradeShopButtonWidget::DrawIcon(), DrawIcon(), and Load().
m_spriteIconFrame
Sprite ShopButtonWidget::m_spriteIconFrame private
Definition at line 3 of file ShopButtonWidget.as.
Referenced by DoDraw(), UpgradeShopButtonWidget::DrawIcon(), DrawIcon(), and Load().
m_spriteOre
Sprite ShopButtonWidget::m_spriteOre private
Definition at line 9 of file ShopButtonWidget.as.
Referenced by Load(), and SetPriceOre().
m_spriteSkillPoints
Sprite ShopButtonWidget::m_spriteSkillPoints private
Definition at line 10 of file ShopButtonWidget.as.
Referenced by Load(), and SetPriceSkillPoints().
m_textPrice
BitmapString ShopButtonWidget::m_textPrice private
Definition at line 15 of file ShopButtonWidget.as.
Referenced by DoDraw(), and SetPrice().
The documentation for this class was generated from the following file:
scripts/GUI/Widgets/ShopButtonWidget.as