HoHDocs: Upgrades::DungeonShop Class Reference
Upgrades::DungeonShop Class Reference
Private Member Functions
DungeonShop (SValue &params)
int GetItemCategory () override
float GetCostScale () override
void NewItems (SValue@ sv, PlayerRecord@ record) override
void ReadItems (float costScale, PlayerRecord@ record) override
void OnOpenMenu (int shopLevel, PlayerRecord@ record) override
void AddPlumeItem (float costScale, PlayerRecord@ record)
Private Attributes
int m_maxItems
Detailed Description
Definition at line 3 of file DungeonShop.as.
Constructor & Destructor Documentation
DungeonShop()
Upgrades::DungeonShop::DungeonShop (SValue & params) inline private
Definition at line 7 of file DungeonShop.as.
         {
             super(params);
         }
Member Function Documentation
AddPlumeItem()
void Upgrades::DungeonShop::AddPlumeItem (float costScale, PlayerRecord@ record) inline private
Definition at line 64 of file DungeonShop.as.
References Upgrades::ItemShop::AddNewItem(), Common, Epic, GetItemCategory(), Legendary, Upgrades::UpgradeShop::m_upgrades, Rare, and Uncommon.
Referenced by NewItems(), and ReadItems().
         {
             if (record.generalStoreItemsPlume == GetItemCategory())
                 return;
             print("adding plume items");
             record.generalStoreItemsPlume = GetItemCategory();
             int numCommon = 0;
             int numUncommon = 0;
             int numRare = 0;
             int numEpic = 0;
             int numLegendary = 0;
             int numTotal = 0;
             for (uint i = 0; i < m_upgrades.length(); i++)
             {
                 auto upgrade = cast<ItemUpgrade>(m_upgrades[i]);
                 if (upgrade is null)
                     continue;
                 numTotal++;
                 if (upgrade.m_quality == ActorItemQuality::Common) numCommon++;
                 else if (upgrade.m_quality == ActorItemQuality::Uncommon) numUncommon++;
                 else if (upgrade.m_quality == ActorItemQuality::Rare) numRare++;
                 else if (upgrade.m_quality == ActorItemQuality::Epic) numEpic++;
                 else if (upgrade.m_quality == ActorItemQuality::Legendary) numLegendary++;
             }
             for (int c = 0; c < 2; c++)
             {
                 ActorItemQuality extraQuality = ActorItemQuality::Common;
                 int rnd = randi(numTotal);
                 if (rnd < numCommon) extraQuality = ActorItemQuality::Common;
                 else if ((rnd -= numCommon) < numUncommon) extraQuality = ActorItemQuality::Uncommon;
                 else if ((rnd -= numUncommon) < numRare) extraQuality = ActorItemQuality::Rare;
                 else if ((rnd -= numRare) < numEpic) extraQuality = ActorItemQuality::Epic;
                 else if ((rnd -= numEpic) < numLegendary) extraQuality = ActorItemQuality::Legendary;
                 AddNewItem(extraQuality, costScale, record);
             }
         }
GetCostScale()
float Upgrades::DungeonShop::GetCostScale () inline override private
Definition at line 18 of file DungeonShop.as.
References g_ngp.
         {
             return 1.0f + float(g_ngp) * 0.2f;
         }
GetItemCategory()
int Upgrades::DungeonShop::GetItemCategory () inline override private
Definition at line 12 of file DungeonShop.as.
References g_gameMode.
Referenced by AddPlumeItem().
         {
             auto gm = cast<Campaign>(g_gameMode);
             return gm.m_levelCount + 1;
         }
NewItems()
void Upgrades::DungeonShop::NewItems (SValue@ sv, PlayerRecord@ record) inline override private
Definition at line 23 of file DungeonShop.as.
References Upgrades::ItemShop::AddNewItem(), AddPlumeItem(), Fountain::HasEffect(), Upgrades::ItemShop::NewItems(), ParseActorItemQuality(), and quality.
         {
             ItemShop::NewItems(sv, record);
             float costScale = GetParamFloat(UnitPtr(), sv, "cost-scale", false, 1.0f);
             if (Fountain::HasEffect("more_shop_items"))
             {
                 auto arrQualities = GetParamArray(UnitPtr(), sv, "qualities");
                 for (int i = 0; i < 2; i++)
                 {
                     int index = randi(arrQualities.length());
                     ActorItemQuality quality = ParseActorItemQuality(arrQualities[index].GetString());
                     AddNewItem(quality, costScale, record);
                 }
             }
             if (record !is null && record.items.find("fancy-plume") != -1)
                 AddPlumeItem(costScale, record);
             record.generalStoreItemsBought = 0;
         }
OnOpenMenu()
void Upgrades::DungeonShop::OnOpenMenu (int shopLevel, PlayerRecord@ record) inline override private
Definition at line 54 of file DungeonShop.as.
References m_maxItems, Upgrades::ItemShop::m_sval, and Upgrades::ItemShop::OnOpenMenu().
         {
             ItemShop::OnOpenMenu(shopLevel, record);
             auto arr = GetParamArray(UnitPtr(), m_sval, "items");
             auto svalLevel = arr[shopLevel - 1];
             m_maxItems = GetParamInt(UnitPtr(), svalLevel, "max-items", false, 0);
         }
ReadItems()
void Upgrades::DungeonShop::ReadItems (float costScale, PlayerRecord@ record) inline override private
Definition at line 46 of file DungeonShop.as.
References AddPlumeItem(), and Upgrades::ItemShop::ReadItems().
         {
             ItemShop::ReadItems(costScale, record);
             if (record !is null && record.items.find("fancy-plume") != -1)
                 AddPlumeItem(costScale, record);
         }
Member Data Documentation
m_maxItems
int Upgrades::DungeonShop::m_maxItems private
Definition at line 5 of file DungeonShop.as.
Referenced by DungeonStoreMenuContent::AddItem(), OnOpenMenu(), and DungeonStoreMenuContent::ReloadList().
The documentation for this class was generated from the following file:
scripts/Upgrades/Shops/DungeonShop.as