HoHDocs: MenuTabSystem Class Reference
MenuTabSystem Class Reference
Private Member Functions
MenuTabSystem (IWidgetHoster@ host)
Widget GetTabWidget (string id)
void AddTab (MenuTab@ tab, GUIBuilder@ b=null)
void SetTab (string id)
void Close ()
void Update (int dt)
void AfterUpdate ()
void Draw (SpriteBatch &sb, int idt)
bool OnFunc (Widget@ sender, string name)
Private Attributes
IWidgetHoster m_host
array< MenuTab@> m_tabs
MenuTab m_currentTab
CheckBoxGroupWidget m_wTabsContainer
ClipWidget m_wTabsClip
int m_lastTabRight
float m_clipX
float m_clipXPrev
Detailed Description
Definition at line 1 of file MenuTabSystem.as.
Constructor & Destructor Documentation
MenuTabSystem()
MenuTabSystem::MenuTabSystem (IWidgetHoster@ host) inline private
Definition at line 14 of file MenuTabSystem.as.
References m_host, m_wTabsClip, and m_wTabsContainer.
     {
         @m_host = host;
         @m_wTabsContainer = cast<CheckBoxGroupWidget>(host.m_widget.GetWidgetById("tabs-container"));
         @m_wTabsClip = cast<ClipWidget>(host.m_widget.GetWidgetById("tabs-clip"));
     }
Member Function Documentation
AddTab()
void MenuTabSystem::AddTab (MenuTab@ tab, GUIBuilder@ b = null) inline private
Definition at line 33 of file MenuTabSystem.as.
References g_gameMode, MenuTab::GetGuiFilename(), GetTabWidget(), MenuTab::m_def, AGameMode::m_guiBuilder, MenuTab::m_id, m_tabs, Widget::m_visible, MenuTab::m_widget, and MenuTab::OnCreated().
Referenced by GuildHallMenu::GuildHallMenu(), and PlayerMenu::PlayerMenu().
     {
         if (b is null)
             @b = g_gameMode.m_guiBuilder;
         auto wTab = GetTabWidget(tab.m_id);
         if (wTab !is null)
         {
             @tab.m_def = wTab.AddResource(b, tab.GetGuiFilename());
             @tab.m_widget = wTab;
             wTab.m_visible = false;
             m_tabs.insertLast(tab);
             tab.OnCreated();
         }
     }
AfterUpdate()
void MenuTabSystem::AfterUpdate () inline private
Definition at line 106 of file MenuTabSystem.as.
References MenuTab::AfterUpdate(), and m_currentTab.
Referenced by PlayerMenu::AfterUpdate(), and GuildHallMenu::AfterUpdate().
     {
         if (m_currentTab !is null)
             m_currentTab.AfterUpdate();
     }
Close()
void MenuTabSystem::Close () inline private
Definition at line 68 of file MenuTabSystem.as.
References SetTab().
Referenced by PlayerMenu::Close(), and GuildHallMenu::Close().
     {
         SetTab("");
     }
Draw()
void MenuTabSystem::Draw (SpriteBatch & sb, int idt) inline private
Definition at line 112 of file MenuTabSystem.as.
References MenuTab::Draw(), lerp(), m_clipX, m_clipXPrev, m_currentTab, and m_wTabsClip.
Referenced by GuildHallMenu::Draw(), and PlayerMenu::Draw().
     {
         m_wTabsClip.m_padding.x = lerp(m_clipXPrev, m_clipX, idt / 33.0f);
         if (m_currentTab !is null)
             m_currentTab.Draw(sb, idt);
     }
GetTabWidget()
Widget MenuTabSystem::GetTabWidget (string id) inline private
Definition at line 22 of file MenuTabSystem.as.
References m_host.
Referenced by AddTab().
     {
         auto wTab = m_host.m_widget.GetWidgetById("tab-" + id);
         if (wTab is null)
         {
             PrintError("Tab widget not found: \"tab-" + id + "\"");
             return null;
         }
         return wTab;
     }
OnFunc()
bool MenuTabSystem::OnFunc (Widget@ sender, string name) inline private
Definition at line 120 of file MenuTabSystem.as.
References m_currentTab, name, MenuTab::OnFunc(), and SetTab().
Referenced by PlayerMenu::OnFunc(), and GuildHallMenu::OnFunc().
     {
         if (m_currentTab !is null && m_currentTab.OnFunc(sender, name))
             return true;
         auto parse = name.split(" ");
         if (parse[0] == "set-tab")
         {
             SetTab(parse[1]);
             return true;
         }
         return false;
     }
SetTab()
void MenuTabSystem::SetTab (string id) inline private
Definition at line 49 of file MenuTabSystem.as.
References id, m_currentTab, m_host, m_tabs, m_wTabsContainer, and CheckBoxGroupWidget::SetChecked().
Referenced by Close(), OnFunc(), PlayerMenu::SetTab(), and GuildHallMenu::SetTab().
     {
         for (uint i = 0; i < m_tabs.length(); i++)
         {
             auto tab = m_tabs[i];
             bool isTab = (tab.m_id == id);
             if (tab.IsVisible() != isTab)
                 tab.SetVisible(isTab);
             if (isTab)
                 @m_currentTab = tab;
         }
         m_wTabsContainer.SetChecked(id);
         m_host.DoLayout();
     }
Update()
void MenuTabSystem::Update (int dt) inline private
Definition at line 73 of file MenuTabSystem.as.
References clamp(), g_gameMode, ilerp(), lerp(), m_clipX, m_clipXPrev, m_currentTab, m_lastTabRight, m_wTabsClip, and MenuTab::Update().
Referenced by PlayerMenu::Update(), and GuildHallMenu::Update().
     {
         if (m_currentTab !is null)
             m_currentTab.Update(dt);
         if (m_wTabsClip !is null)
         {
             if (m_lastTabRight == 0)
             {
                 for (uint i = 0; i < m_wTabsClip.m_children.length(); i++)
                     m_lastTabRight += m_wTabsClip.m_children[i].m_width;
             }
             auto gm = cast<BaseGameMode>(g_gameMode);
             vec2 mousePos = gm.m_mice[0].GetPos(0);
             mousePos /= gm.m_wndScale;
             float offset = mousePos.x - m_wTabsClip.m_origin.x;
             float skew = 0.25f;
             float factor = clamp(offset / float(m_wTabsClip.m_width), skew, 1.0f - skew);
             factor = ilerp(skew, 1.0f - skew, factor);
             Widget@ lastWidget = m_wTabsClip.m_children[m_wTabsClip.m_children.length() - 1];
             int extraRight = m_lastTabRight - m_wTabsClip.m_width;
             if (extraRight > 0)
             {
                 m_clipXPrev = m_clipX;
                 m_clipX = lerp(0.0f, float(-extraRight), factor);
             }
         }
     }
Member Data Documentation
m_clipX
float MenuTabSystem::m_clipX private
Definition at line 11 of file MenuTabSystem.as.
Referenced by Draw(), and Update().
m_clipXPrev
float MenuTabSystem::m_clipXPrev private
Definition at line 12 of file MenuTabSystem.as.
Referenced by Draw(), and Update().
m_currentTab
MenuTab MenuTabSystem::m_currentTab private
Definition at line 6 of file MenuTabSystem.as.
Referenced by AfterUpdate(), Draw(), OnFunc(), SetTab(), and Update().
m_host
IWidgetHoster MenuTabSystem::m_host private
Definition at line 3 of file MenuTabSystem.as.
Referenced by GetTabWidget(), MenuTabSystem(), and SetTab().
m_lastTabRight
int MenuTabSystem::m_lastTabRight private
Definition at line 10 of file MenuTabSystem.as.
Referenced by Update().
m_tabs
array<MenuTab@> MenuTabSystem::m_tabs private
Definition at line 5 of file MenuTabSystem.as.
Referenced by AddTab(), and SetTab().
m_wTabsClip
ClipWidget MenuTabSystem::m_wTabsClip private
Definition at line 9 of file MenuTabSystem.as.
Referenced by Draw(), MenuTabSystem(), and Update().
m_wTabsContainer
CheckBoxGroupWidget MenuTabSystem::m_wTabsContainer private
Definition at line 8 of file MenuTabSystem.as.
Referenced by MenuTabSystem(), and SetTab().
The documentation for this class was generated from the following file:
scripts/GUI/MenuTabSystem.as