HoHDocs: MenuServerListItem Class Reference
MenuServerListItem Class Reference
Private Member Functions
MenuServerListItem ()
int opCmp (const Widget@ w) override
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void Set (Menu::ServerlistMenu@ owner, string name, int players, int playersMax, int lobbyPing)
bool PassesFilter (string str) override
void DoDraw (SpriteBatch &sb, vec2 pos) override
Private Attributes
Menu::ServerlistMenu m_owner
string m_serverName
int m_serverPlayers
int m_serverPlayersMax
BitmapString m_textPlayers
Detailed Description
Definition at line 1 of file MenuServerListItem.as.
Constructor & Destructor Documentation
MenuServerListItem()
MenuServerListItem::MenuServerListItem () inline private
Definition at line 12 of file MenuServerListItem.as.
Referenced by Clone().
     {
         super();
     }
Member Function Documentation
Clone()
Widget MenuServerListItem::Clone () inline override private
Definition at line 42 of file MenuServerListItem.as.
References Widget::CloneInto(), and MenuServerListItem().
Referenced by Menu::OnLobbyList().
     {
         MenuServerListItem@ w = MenuServerListItem();
         CloneInto(w);
         return w;
     }
DoDraw()
void MenuServerListItem::DoDraw (SpriteBatch & sb, vec2 pos) inline override private
Definition at line 89 of file MenuServerListItem.as.
References ScalableSpriteButtonWidget::DoDraw().
     {
         ScalableSpriteButtonWidget::DoDraw(sb, pos);
         if (m_textPlayers !is null)
         {
             m_textPlayers.SetColor(GetTextColor());
             sb.DrawString(pos + vec2(
                 m_width - m_textPlayers.GetWidth() - 10 /* - 24 */,
                 m_height / 2.0f - m_textPlayers.GetHeight() / 2.0f
             ), m_textPlayers);
         }
         /*
         if (m_textPing !is null)
         {
             sb.DrawString(pos + vec2(
                 m_width - m_textPing.GetWidth() - 10,
                 m_height / 2.0f - m_textPing.GetHeight() / 2.0f
             ), m_textPing);
         }
         */
     }
Load()
void MenuServerListItem::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 49 of file MenuServerListItem.as.
Referenced by LoadMenuServerListItemWidget().
     {
         ScalableSpriteButtonWidget::Load(ctx);
         m_textOffset.x = 10;
     }
opCmp()
int MenuServerListItem::opCmp (const Widget@ w) inline override private
Definition at line 17 of file MenuServerListItem.as.
References m_owner, m_serverName, m_serverPlayers, Name, None, and Menu::Players.
     {
         if (m_owner is null)
             return 0;
         const MenuServerListItem@ wServer = cast<MenuServerListItem>(w);
         if (wServer is null)
             return 0;
         if (m_owner.m_sortColumn == Menu::ServerlistSortColumn::None)
             return 0;
         else if (m_owner.m_sortColumn == Menu::ServerlistSortColumn::Name)
             return m_serverName.opCmp(wServer.m_serverName) * m_owner.m_sortDir;
         else if (m_owner.m_sortColumn == Menu::ServerlistSortColumn::Players)
         {
             if (m_serverPlayers < wServer.m_serverPlayers)
                 return 1 * m_owner.m_sortDir;
             else if (m_serverPlayers > wServer.m_serverPlayers)
                 return -1 * m_owner.m_sortDir;
             return 0;
         }
         return 0;
     }
PassesFilter()
bool MenuServerListItem::PassesFilter (string str) inline override private
Definition at line 82 of file MenuServerListItem.as.
References m_serverName.
     {
         if (m_serverName.toLower().findFirst(str) != -1)
             return true;
         return false;
     }
Set()
void MenuServerListItem::Set (Menu::ServerlistMenu@ owner, string name, int players, int playersMax, int lobbyPing) inline private
Definition at line 56 of file MenuServerListItem.as.
Referenced by Menu::OnLobbyList().
     {
         @m_owner = owner;
         m_serverName = name;
         m_serverPlayers = players;
         m_serverPlayersMax = playersMax;
         SetText(name);
         @m_textPlayers = m_font.BuildText(players + " / " + playersMax);
         /*
         string ping;
         if (lobbyPing < 0)
             ping = "?";
         else if (lobbyPing > 999)
             ping = "999";
         else
             ping = "" + lobbyPing;
         @m_textPing = m_font.BuildText(ping);
         */
     }
Member Data Documentation
m_owner
Menu::ServerlistMenu MenuServerListItem::m_owner private
Definition at line 3 of file MenuServerListItem.as.
Referenced by MenuServerListItem(), and opCmp().
m_serverName
string MenuServerListItem::m_serverName private
Definition at line 5 of file MenuServerListItem.as.
Referenced by MenuServerListItem(), opCmp(), and PassesFilter().
m_serverPlayers
int MenuServerListItem::m_serverPlayers private
Definition at line 6 of file MenuServerListItem.as.
Referenced by opCmp().
m_serverPlayersMax
int MenuServerListItem::m_serverPlayersMax private
Definition at line 7 of file MenuServerListItem.as.
m_textPlayers
BitmapString MenuServerListItem::m_textPlayers private
Definition at line 9 of file MenuServerListItem.as.
Referenced by Load().
The documentation for this class was generated from the following file:
scripts/GUI/Menus/Widgets/MenuServerListItem.as