HoHDocs: UserWindow Class Reference
UserWindow Class Reference
Private Member Functions
UserWindow (GUIBuilder@ b, string filename)
string GetScriptID ()
bool IsVisible ()
void Show ()
void Close ()
void CloseTooltip ()
void Update (int dt) override
void Draw (SpriteBatch &sb, int idt) override
void OnFunc (Widget@ sender, string name) override
Private Attributes
bool m_visible
Detailed Description
Definition at line 1 of file UserWindow.as.
Constructor & Destructor Documentation
UserWindow()
UserWindow::UserWindow (GUIBuilder@ b, string filename) inline private
Definition at line 5 of file UserWindow.as.
References LoadWidget().
     {
         LoadWidget(b, filename);
     }
Member Function Documentation
Close()
void UserWindow::Close () inline private
Definition at line 25 of file UserWindow.as.
References CloseTooltip(), g_gameMode, m_visible, and AGameMode::RemoveWidgetRoot().
Referenced by PlayerMenu::Close(), GuildHallMenu::Close(), StatueSelectMenu::Close(), ShopMenu::Close(), OnFunc(), and ScoreDialog::OnFunc().
     {
         if (!m_visible)
             return;
         m_visible = false;
         g_gameMode.RemoveWidgetRoot(this);
         CloseTooltip();
     }
CloseTooltip()
void UserWindow::CloseTooltip () inline private
Definition at line 36 of file UserWindow.as.
References g_gameMode.
Referenced by Close().
     {
         auto gm = cast<BaseGameMode>(g_gameMode);
         if (gm !is null)
             gm.m_tooltip.Hide();
     }
Draw()
void UserWindow::Draw (SpriteBatch & sb, int idt) inline override private
Definition at line 49 of file UserWindow.as.
References Draw(), and m_visible.
Referenced by GuildHallMenu::Draw(), PlayerMenu::Draw(), and GameOver::Draw().
     {
         if (m_visible)
             IWidgetHoster::Draw(sb, idt);
     }
GetScriptID()
string UserWindow::GetScriptID () inline private
Definition at line 10 of file UserWindow.as.
 { return ""; }
IsVisible()
bool UserWindow::IsVisible () inline private
Definition at line 12 of file UserWindow.as.
References m_visible.
 { return m_visible; }
OnFunc()
void UserWindow::OnFunc (Widget@ sender, string name) inline override private
Definition at line 55 of file UserWindow.as.
References Close(), and name.
Referenced by StatueSelectMenu::OnFunc(), GuildHallMenu::OnFunc(), ScoreDialog::OnFunc(), ShopMenu::OnFunc(), and GameOver::OnFunc().
     {
         if (name == "close")
             Close();
     }
Show()
void UserWindow::Show () inline private
Definition at line 14 of file UserWindow.as.
References AGameMode::AddWidgetRoot(), DoLayout(), g_gameMode, and m_visible.
Referenced by StatueSelectMenu::Show(), PlayerMenu::Show(), GuildHallMenu::Show(), ShopMenu::Show(), and Town::Start().
     {
         if (m_visible)
             return;
         m_visible = true;
         g_gameMode.AddWidgetRoot(this);
         DoLayout();
     }
Update()
void UserWindow::Update (int dt) inline override private
Definition at line 43 of file UserWindow.as.
References m_visible, and Update().
Referenced by PlayerMenu::Update(), GuildHallMenu::Update(), and ShopMenu::Update().
     {
         if (m_visible)
             IWidgetHoster::Update(dt);
     }
Member Data Documentation
m_visible
bool UserWindow::m_visible private
Definition at line 3 of file UserWindow.as.
Referenced by PlayerMenu::AfterUpdate(), GuildHallMenu::AfterUpdate(), Close(), PlayerMenu::Close(), GuildHallMenu::Close(), StatueSelectMenu::Close(), ShopMenu::Close(), GameOver::DoShow(), Draw(), GuildHallMenu::Draw(), PlayerMenu::Draw(), GameOver::Draw(), IsVisible(), Show(), StatueSelectMenu::Show(), PlayerMenu::Show(), GuildHallMenu::Show(), Update(), PlayerMenu::Update(), GuildHallMenu::Update(), ShopMenu::Update(), and GameOver::Update().
The documentation for this class was generated from the following file:
scripts/GUI/UserWindow.as