HoHDocs: Player Class Reference
Player Class Reference
Private Member Functions
Player (UnitPtr unit, SValue &params)
float GetWindScale () override
void Initialize (PlayerRecord@ record) override
void EnableModifiers ()
void DisableModifiers ()
int FindUsable (IUsable@ usable)
void AddUsable (IUsable@ usable)
void RemoveUsable (IUsable@ usable)
IUsable GetTopUsable ()
void RefreshModifiers () override
void AddItem (ActorItem@ item) override
void AttuneItem (ActorItem@ item) override
bool IsHusk () override
float GetDamageMul (AttackRangeType rangeType)
float GetDamageMulTarget (bool melee, UnitPtr target) override
void DamagedActor (Actor@ actor, DamageInfo di)
DamageInfo DamageActor (Actor@ actor, DamageInfo di)
void NetShareExperience (int experience)
void PlayerKilled (PlayerRecord@ player)
void KilledActor (Actor@ killed, DamageInfo di) override
bool CanGiveArmor (int amt, ArmorDef@ def, bool replace)
bool GiveArmor (int amt, ArmorDef@ def, bool replace)
void Kill (Actor@ killer, uint weapon) override
bool ApplyBuff (ActorBuff@ buff) override
void GiveMana (int mana)
void TakeMana (int mana)
int Heal (int amount) override
void SoulLinkKill (PlayerHusk@ killer,)
void SoulLinkDamage (int dmg)
void NetDecimate (int hp, int mana) override
int Decimate (DecimateInfo dec, vec2 pos, vec2 dir) override
int Damage (DamageInfo dmg, vec2 pos, vec2 dir) override
void NetDamage (DamageInfo dmg, vec2 pos, vec2 dir) override
void BroadcastNetDamage (DamageInfo di)
void OnDeath (DamageInfo di, vec2 dir) override
bool IsDead () override
void OnNewTitle (Titles::Title@ title)
void OnLevelUp (int levels)
void WarnCooldown (Skills::Skill@ skill, int ms) override
bool SpendCost (int mana, int stamina, int health) override
void Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther)
bool BlockProjectile (IProjectile@ proj) override
bool CheckSkillBlocked (Skills::Skill@ skill)
void CheckUseSkill (int dt, ButtonState &in btn, Skills::Skill@ skill, vec2 aimDir)
void OnComboBegin () override
void OnComboEnd () override
void Update (int dt) override
void SendPlayerMove (vec2 dir, bool force=false)
bool PreRender (int idt)
Private Attributes
array< PlayerUsable@> m_usables
vec2 m_lastDirection
vec2 m_lastSentPos
vec2 m_lastSentDir
float m_lastSentHP
float m_driftingOffset
float m_queuedHealing = 0
UnitScene m_fxBlockProjectile
SoundEvent m_sndBlockProjectile
UnitScene m_fxBlockPhysical
UnitScene m_fxBlockMagical
UnitScene m_fxLifesteal
SoundEvent m_sndNoMana
SoundEvent m_sndCooldown
SoundEvent m_sndEvade
bool m_returningDamage
bool m_insideJammable
int m_potionDelay
float m_windScale
uint m_lastCollideTime
UnitPtr m_lastCollideUnit
Detailed Description
Definition at line 12 of file Player.as.
Constructor & Destructor Documentation
Player()
Player::Player (UnitPtr unit, SValue & params) inline private
Definition at line 41 of file Player.as.
References ClearItemsCfunc(), Fountain::GetEffect(), GiveArmorCFunc(), GiveBlueprintCFunc(), GiveComboCfunc(), GiveDrinkCFunc(), GiveDrinksCFunc(), GiveExperienceCFunc(), GiveGoldCFunc(), GiveHealthCFunc(), GiveItemCFunc(), GiveItemsCFunc(), GiveKeyCFunc(), GiveManaCFunc(), GiveOreCFunc(), Int(), KillAllCFunc(), KillCFunc(), LevelupCFunc(), ListEnemiesCFunc(), ListModifiersCFunc(), m_fxBlockMagical, m_fxBlockPhysical, m_fxBlockProjectile, m_fxLifesteal, m_returningDamage, m_sndBlockProjectile, m_sndCooldown, m_sndEvade, m_sndNoMana, NextLevelCfunc(), ReviveCFunc(), SetCharNgpCFunc(), SetFlagCFunc(), SetGodmodeCVar(), SetNoClipCVar(), and unit.
     {
         super(unit, params);
         //TODO: Replace check with something so that on splitscreen, only the first player can use cheats
         //if (Network::IsServer())
         {
             AddVar("noclip", false, SetNoClipCVar, cvar_flags::Cheat);
             AddVar("god", false, SetGodmodeCVar, cvar_flags::Cheat);
             AddVar("clientfollowshost", false, null, cvar_flags::Cheat);
             AddVar("show_all_accomplishments", false, null, cvar_flags::Cheat);
             {
                 array<cvar_type> cfuncParams = { cvar_type::String };
                 AddFunction("give_item", cfuncParams, GiveItemCFunc, cvar_flags::Cheat);
                 AddFunction("give_drink", cfuncParams, GiveDrinkCFunc, cvar_flags::Cheat);
                 AddFunction("give_blueprint", cfuncParams, GiveBlueprintCFunc, cvar_flags::Cheat);
             }
             {
                 array<cvar_type> cfuncParams = { cvar_type::Int, cvar_type::Int, cvar_type::Int, cvar_type::Int, cvar_type::Int };
                 AddFunction("give_items", cfuncParams, GiveItemsCFunc, cvar_flags::Cheat);
                 AddFunction("give_drinks", cfuncParams, GiveDrinksCFunc, cvar_flags::Cheat);
             }
             AddFunction("clear_items", ClearItemsCfunc, cvar_flags::Cheat);
             AddFunction("give_combo", GiveComboCfunc, cvar_flags::Cheat);
             AddFunction("next_level", NextLevelCfunc, cvar_flags::Cheat);
             {
                 array<cvar_type> cfuncParams = { cvar_type::Int };
                 AddFunction("give_experience", cfuncParams, GiveExperienceCFunc, cvar_flags::Cheat);
                 AddFunction("give_health", cfuncParams, GiveHealthCFunc, cvar_flags::Cheat);
                 AddFunction("give_mana", cfuncParams, GiveManaCFunc, cvar_flags::Cheat);
                 AddFunction("give_armor", cfuncParams, GiveArmorCFunc, cvar_flags::Cheat);
                 AddFunction("give_key", cfuncParams, GiveKeyCFunc, cvar_flags::Cheat);
                 AddFunction("levelup", cfuncParams, LevelupCFunc, cvar_flags::Cheat);
                 AddFunction("set_char_ngp", cfuncParams, SetCharNgpCFunc, cvar_flags::Cheat);
                 AddFunction("give_gold", cfuncParams, GiveGoldCFunc, cvar_flags::Cheat);
                 AddFunction("give_ore", cfuncParams, GiveOreCFunc, cvar_flags::Cheat);
             }
             {
                 array<cvar_type> cfuncParams = { cvar_type::String, cvar_type::Bool, cvar_type::Bool };
                 AddFunction("set_flag", cfuncParams, SetFlagCFunc, cvar_flags::Cheat);
             }
             AddFunction("killall", KillAllCFunc, cvar_flags::Cheat);
             AddFunction("revive", ReviveCFunc, cvar_flags::Cheat);
             AddFunction("listenemies", ListEnemiesCFunc, cvar_flags::Cheat);
             AddFunction("kill", KillCFunc);
             AddFunction("listmodifiers", ListModifiersCFunc);
         }
         @m_fxBlockProjectile = Resources::GetEffect("effects/players/block_projectile.effect");
         @m_sndBlockProjectile = Resources::GetSoundEvent("event:/player/projectile_block");
         @m_fxBlockPhysical = Resources::GetEffect("effects/players/block_physical.effect");
         @m_fxBlockMagical = Resources::GetEffect("effects/players/block_magical.effect");
         @m_fxLifesteal = Resources::GetEffect("effects/players/lifesteal.effect");
         @m_sndNoMana = Resources::GetSoundEvent("event:/player/no_mana");
         @m_sndCooldown = Resources::GetSoundEvent("event:/player/cooldown");
         @m_sndEvade = Resources::GetSoundEvent("event:/player/dodge");
         m_returningDamage = false;
         m_windScale = GetParamFloat(unit, params, "wind-scale", false, 1.0f);
     }
Member Function Documentation
AddItem()
void Player::AddItem (ActorItem@ item) inline override private
Definition at line 190 of file Player.as.
References PlayerBase::AddItem(), and g_gameMode.
Referenced by GiveRandomItems().
     {
         PlayerBase::AddItem(item);
         (Network::Message("PlayerGiveItem") << item.id).SendToAll();
         cast<Campaign>(g_gameMode).m_townLocal.FoundItem(item);
         item.inUse = true;
     }
AddUsable()
void Player::AddUsable (IUsable@ usable) inline private
Definition at line 143 of file Player.as.
References FindUsable(), and m_usables.
Referenced by Chest::Collide(), ForgeBlueprint::Collide(), Item::Collide(), WorldScript::StoreOre::OnEnter(), WorldScript::RandomBuff::OnEnter(), WorldScript::UseTrigger::OnEnter(), WorldScript::Well::OnEnter(), and WorldScript::Door::OnEnter().
     {
         int index = FindUsable(usable);
         if (index != -1)
         {
             m_usables[index].m_refCount++;
             return;
         }
         m_usables.insertLast(PlayerUsable(usable));
         m_usables.sortAsc();
     }
ApplyBuff()
bool Player::ApplyBuff (ActorBuff@ buff) inline override private
Definition at line 391 of file Player.as.
References BlockBuff(), buff, and PlayerBase::m_record.
     {
         if (BlockBuff(buff, m_record.armorDef, m_record.armor))
             return false;
         return PlayerBase::ApplyBuff(buff);
     }
AttuneItem()
void Player::AttuneItem (ActorItem@ item) inline override private
Definition at line 200 of file Player.as.
References PlayerBase::AttuneItem().
     {
         PlayerBase::AttuneItem(item);
         (Network::Message("PlayerItemAttuned") << item.id).SendToAll();
     }
BlockProjectile()
bool Player::BlockProjectile (IProjectile@ proj) inline override private
Definition at line 841 of file Player.as.
References g_allModifiers, m_fxBlockProjectile, m_sndBlockProjectile, Actor::m_unit, PlayEffect(), PlaySound3D(), and xy().
     {
         auto block = g_allModifiers.ProjectileBlock(this, proj);
         if (block)
         {
             auto pb = cast<ProjectileBase>(proj);
             vec3 pos;
             if (pb !is null)
                 pos = pb.m_unit.GetPosition();
             else
                 pos = m_unit.GetPosition();
             PlayEffect(m_fxBlockProjectile, xy(pos));
             PlaySound3D(m_sndBlockProjectile, pos);
             return true;
         }
         return false;
     }
BroadcastNetDamage()
void Player::BroadcastNetDamage (DamageInfo di) inline private
Definition at line 680 of file Player.as.
References DamageInfo::Attacker, m_lastSentHP, PlayerBase::m_record, and Actor::m_unit.
Referenced by Damage().
     {
         int damager = 0;
         if (di.Attacker !is null && di.Attacker.m_unit.IsDestroyed())
             damager = di.Attacker.m_unit.GetId();
         m_lastSentHP = m_record.hp;
         (Network::Message("PlayerDamaged") << di.DamageType << damager << di.Damage << m_record.hp << di.Weapon).SendToAll();
     }
CanGiveArmor()
bool Player::CanGiveArmor (int amt, ArmorDef@ def, bool replace) inline private
Definition at line 375 of file Player.as.
Referenced by GiveArmor::CanApply().
     {
         return false;
     }
CheckSkillBlocked()
bool Player::CheckSkillBlocked (Skills::Skill@ skill) inline private
Definition at line 863 of file Player.as.
References Skills::IgnoreForBlock(), Skills::IsActive(), and PlayerBase::m_skills.
Referenced by CheckUseSkill(), and Update().
     {
         int firstSkill = (skill is m_skills[0]) ? 0 : 1;
         if (skill.IsBlocking())
         {
             for (uint i = firstSkill; i < m_skills.length(); i++)
             {
                 if (m_skills[i].IgnoreForBlock())
                     continue;
                 if (skill !is m_skills[i] && m_skills[i].IsActive())
                     return true;
             }
         }
         else
         {
             for (uint i = firstSkill; i < m_skills.length(); i++)
                 if (skill !is m_skills[i] && m_skills[i].IsActive() && m_skills[i].IsBlocking())
                     return true;
         }
         return false;
     }
CheckUseSkill()
void Player::CheckUseSkill (int dt, ButtonState &in btn, Skills::Skill@ skill, vec2 aimDir) inline private
Definition at line 887 of file Player.as.
References CastSpell, Skills::Channeling, CheckSkillBlocked(), g_allModifiers, PlayerBase::m_skills, and Skills::Toggle.
Referenced by Update().
     {
         int targetSz = 0;
         auto targetMode = skill.GetTargetingMode(targetSz);
         if (CheckSkillBlocked(skill))
         {
             if (targetMode == Skills::TargetingMode::Channeling && skill.IsActive())
             {
                 skill.Release(aimDir);
                 skill.m_isActive = false;
             }
             return;
         }
         if (btn.Pressed)
         {
             if (targetMode == Skills::TargetingMode::Toggle)
             {
                 if (!skill.m_isActive && skill.Activate(aimDir))
                 {
                     g_allModifiers.TriggerEffects(this, null, Modifiers::EffectTrigger::CastSpell);
                     skill.m_isActive = true;
                 }
                 else if (skill.m_isActive)
                 {
                     skill.Deactivate();
                     skill.m_isActive = false;
                 }
             }
             else if (skill.Activate(aimDir) && skill !is m_skills[0])
                 g_allModifiers.TriggerEffects(this, null, Modifiers::EffectTrigger::CastSpell);
         }
         if (targetMode == Skills::TargetingMode::Channeling)
         {
             if (btn.Down)
             {
                 skill.Hold(dt, aimDir);
                 skill.m_isActive = true;
             }
             if (btn.Released || (!btn.Down && skill.m_isActive))
             {
                 skill.Release(aimDir);
                 skill.m_isActive = false;
             }
         }
     }
Collide()
void Player::Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther) inline private
Definition at line 810 of file Player.as.
References Collide(), g_allModifiers, g_scene, m_lastCollideTime, m_lastCollideUnit, PlayerBase::m_skills, OnCollide, and unit.
     {
         for (uint i = 0; i < m_skills.length(); i++)
             m_skills[i].OnCollide(unit, pos, normal, fxOther);
         if (fxOther.IsSensor())
             return;
         auto nowT = g_scene.GetTime();
         if (m_lastCollideUnit == unit)
         {
             if ((m_lastCollideTime + 100) > nowT)
                 return;
         }
         m_lastCollideUnit = unit;
         auto actor = cast<Actor>(unit.GetScriptBehavior());
         if (actor is null)
             return;
         auto player = cast<PlayerBase>(actor);
         if (player !is null)
             return;
         g_allModifiers.TriggerEffects(this, actor, Modifiers::EffectTrigger::Collide);
         m_lastCollideTime = nowT;
     }
Damage()
int Player::Damage (DamageInfo dmg, vec2 pos, vec2 dir) inline override private
Definition at line 526 of file Player.as.
References Stats::Add(), Actor::AddFloatingHurt(), ApplyArmor(), DamageInfo::ArmorMul, ActorBuffList::ArmorMul(), DamageInfo::Attacker, BroadcastNetDamage(), DamageInfo::CanKill, DamageInfo::Crit, DamageInfo::Damage, ActorBuffList::DamageTakenMul(), DamageInfo::DamageType, Evade, g_allModifiers, g_cvar_god, g_ngp, GiveMana(), Fountain::HasEffect(), Heal(), Hurt, Actor::IsDead(), PlayerBase::m_buffs, PlayerBase::m_dmgColor, m_fxBlockMagical, m_fxBlockPhysical, PlayerBase::m_gore, PlayerBase::m_hurtSound, PlayerBase::m_record, m_returningDamage, m_sndEvade, Actor::m_unit, DamageInfo::MagicalDamage, max, Stats::Max(), DamageInfo::Melee, Tweak::NewGamePlusNegArmor(), OnDeath(), DamageInfo::PhysicalDamage, PlayEffect(), PlayerHurt, PlayerHurtMagical, PlaySound3D(), and DamageInfo::TrueStrike.
     {
         if (
 %if NON_FINAL
             g_cvar_god ||
 %endif
             m_record.IsDead())
         {
             return 0;
         }
         bool isTrapDamage = (dmg.Attacker is null);
         bool selfDmg = false;
         if (dmg.Attacker is this)
         {
             @dmg.Attacker = null;
             selfDmg = true;
         }
         int maxHp = m_record.MaxHealth();
         vec2 armor(m_record.Armor(), m_record.Resistance());
         ivec2 block;
         float dmgTakenMul = 1.0f;
         if (g_allModifiers.NonLethalDamage(this, dmg))
             dmg.CanKill = false;
         if (dmg.DamageType != 0)
         {
             if (!dmg.TrueStrike)
             {
                 if (g_allModifiers.Evasion(this, dmg.Attacker))
                 {
                     Stats::Add("evade-amount", 1, m_record);
                     g_allModifiers.TriggerEffects(this, dmg.Attacker, Modifiers::EffectTrigger::Evade);
                     m_dmgColor = vec4(0, 0, 0, 2.0);
                     PlaySound3D(m_sndEvade, m_unit);
                     return 0;
                 }
                 block += g_allModifiers.DamageBlock(this, dmg.Attacker);
                 if (block.x + block.y > 0)
                 {
                     Stats::Add("damage-blocked", block.x + block.y, m_record);
                     if (block.x > 0)
                         PlayEffect(m_fxBlockPhysical, pos);
                     else
                         PlayEffect(m_fxBlockMagical, pos);
                 }
                 if (dmg.PhysicalDamage > 0)
                     dmg.PhysicalDamage = max(0, dmg.PhysicalDamage - block.x);
                 if (dmg.MagicalDamage > 0)
                     dmg.MagicalDamage = max(0, dmg.MagicalDamage - block.y);
             }
             armor += g_allModifiers.ArmorAdd(this, dmg.Attacker);
             maxHp += g_allModifiers.StatsAdd(this).x;
             float trapMultiplier = 1.0f;
             if (isTrapDamage)
             {
                 if (Fountain::HasEffect("reduced_trap_damage"))
                     trapMultiplier *= 0.5f;
                 if (Fountain::HasEffect("more_trap_damage"))
                     trapMultiplier *= 2.0f;
             }
             float hc = 1.0f; //lerp(1.0f, 0.8f, m_record.GetHandicap());
             dmgTakenMul = hc * trapMultiplier * g_allModifiers.DamageTakenMul(this, dmg) * m_buffs.DamageTakenMul();
         }
         int dmgAmnt = ApplyArmor(dmg, m_buffs.ArmorMul() * armor * dmg.ArmorMul - Tweak::NewGamePlusNegArmor(g_ngp), dmgTakenMul);
         if (dmgAmnt > 0)
         {
             if (!dmg.CanKill && m_record.CurrentHealth() - dmgAmnt <= 0)
                 dmgAmnt = 0;
             bool evadable = dmg.Melee && dmg.Attacker !is null && !dmg.Attacker.IsDead();
             m_returningDamage = true;
             g_allModifiers.TriggerEffects(this, dmg.Attacker, Modifiers::EffectTrigger::Hurt);
             g_allModifiers.DamageTaken(this, dmg.Attacker, dmgAmnt);
             m_returningDamage = false;
             if (evadable && dmg.Attacker.IsDead())
             {
                 g_allModifiers.TriggerEffects(this, dmg.Attacker, Modifiers::EffectTrigger::Evade);
                 m_dmgColor = vec4(0, 0, 0, 2.0);
                 PlaySound3D(m_sndEvade, m_unit);
                 return 0;
             }
             float new = float(m_record.hp) - float(dmgAmnt) / float(maxHp);
             m_record.hp = new;
             assert(m_record.hp, new);
             AddFloatingHurt(dmgAmnt, dmg.Crit, dmg.MagicalDamage > dmg.PhysicalDamage ? FloatingTextType::PlayerHurtMagical : FloatingTextType::PlayerHurt);
             m_dmgColor = vec4(1, 0, 0, 1);
             int manaFromDamage = g_allModifiers.ManaFromDamage(this, dmgAmnt);
             if (manaFromDamage > 0)
                 this.GiveMana(manaFromDamage);
             Stats::Add("damage-taken", dmgAmnt, m_record);
             Stats::Max("damage-taken-max", dmgAmnt, m_record);
             //if (dmgAmnt > 5)
             //  MusicManager::AddTension(2.5);
             if (m_record.CurrentHealth() <= 0)
             {
                 //dmg.Damage = dmgAmnt;
                 //BroadcastNetDamage(dmg);
                 OnDeath(dmg, dir);
                 return dmgAmnt;
             }
             else
             {
                 if (m_gore !is null)
                     m_gore.OnHit(float(dmgAmnt) / float(maxHp), pos, atan(dir.y, dir.x));
                 dictionary params = { { "damage", float(dmgAmnt) } };
                 if (!selfDmg)
                     PlaySound3D(m_hurtSound, m_unit, params);
             }
         }
         else if (dmgAmnt < 0)
         {
             if (m_record.hp < 1.0)
                 return -Heal(-dmgAmnt);
             else
                 return 0;
         }
         else
         {
             AddFloatingHurt(0, dmg.Crit, dmg.MagicalDamage > dmg.PhysicalDamage ? FloatingTextType::PlayerHurtMagical : FloatingTextType::PlayerHurt);
         }
         dmg.Damage = dmgAmnt;
         BroadcastNetDamage(dmg);
         return dmgAmnt;
     }
DamageActor()
DamageInfo Player::DamageActor (Actor@ actor, DamageInfo di) inline private
Definition at line 260 of file Player.as.
References Stats::Add(), DamageInfo::ArmorMul, DamageInfo::Crit, CriticalHit, damage_round(), ActorBuffList::DamageMul(), g_allModifiers, Hit, PlayerBase::m_buffs, PlayerBase::m_record, DamageInfo::MagicalDamage, DamageInfo::PhysicalDamage, SpellHit, and DamageInfo::Weapon.
     {
         ivec2 dmgPowerV = g_allModifiers.DamagePower(this, actor);
         float dmgMul = m_buffs.DamageMul();
         int crit;
         int dmgPower;
         vec2 armorIg;
         ivec2 dmgAddV;
         if (di.Weapon == 1)
         {
             dmgPower = dmgPowerV.x;
             dmgMul *= g_allModifiers.DamageMul(this, actor).x;
             crit = g_allModifiers.Crit(this, actor, false);
             armorIg = g_allModifiers.ArmorIgnore(this, actor, false);
             dmgAddV = g_allModifiers.AttackDamageAdd(this, actor);
             g_allModifiers.TriggerEffects(this, actor, Modifiers::EffectTrigger::Hit);
         }
         else
         {
             dmgPower = dmgPowerV.y;
             dmgMul *= g_allModifiers.DamageMul(this, actor).y;
             crit = g_allModifiers.Crit(this, actor, true);
             armorIg = g_allModifiers.ArmorIgnore(this, actor, true);
             dmgAddV = g_allModifiers.SpellDamageAdd(this, actor);
             g_allModifiers.TriggerEffects(this, actor, Modifiers::EffectTrigger::SpellHit);
         }
         auto enemy = cast<CompositeActorBehavior>(actor);
         if (enemy !is null)
         {
             float receiveCritChance = enemy.m_buffs.ReceiveCritChance();
             if (receiveCritChance > 0.0f && randf() < receiveCritChance)
                 crit++;
         }
         if (crit > 0)
         {
             Stats::Add("crit-count", 1, m_record);
             dmgMul *= (2.0f + (g_allModifiers.CritMul(this, actor, di.Weapon != 1) - 1.0f)) * crit;
         }
         di.PhysicalDamage = damage_round(((di.PhysicalDamage + dmgAddV.x) * (50.0 + dmgPower) / 50.0) * dmgMul);
         di.MagicalDamage = damage_round(((di.MagicalDamage + dmgAddV.y) * (50.0 + dmgPower) / 50.0) * dmgMul);
         di.Crit = crit;
         di.ArmorMul *= armorIg;
         if (crit > 0)
             g_allModifiers.TriggerEffects(this, actor, Modifiers::EffectTrigger::CriticalHit);
         return di;
     }
DamagedActor()
void Player::DamagedActor (Actor@ actor, DamageInfo di) inline private
Definition at line 219 of file Player.as.
References Stats::Add(), DamageInfo::Crit, DamageInfo::Damage, DamageInfo::DamageDealt, g_allModifiers, DamageInfo::LifestealMul, m_fxLifesteal, m_queuedHealing, PlayerBase::m_record, m_returningDamage, Actor::m_unit, DamageInfo::MagicalDamage, max, Stats::Max(), DamageInfo::PhysicalDamage, PlayEffect(), roll_round(), DamageInfo::Weapon, and xy().
     {
         auto eb = cast<CompositeActorBehavior>(actor);
         if (!(eb !is null && eb.m_enemyType == "construct" && di.LifestealMul > 0))
         {
             float ls = di.LifestealMul * g_allModifiers.Lifesteal(this, actor, (di.Weapon != 1), di.Crit);
             ls *= g_allModifiers.AllHealthGainScale(this);
             if (ls > 0)
             {
                 ivec2 stats = g_allModifiers.StatsAdd(this);
                 float maxHealth = m_record.MaxHealth() + stats.x;
                 int stealHealth = max(0, roll_round(di.DamageDealt * ls));
                 if (m_record.hp * maxHealth + stealHealth > maxHealth)
                     stealHealth = int(maxHealth - m_record.hp * maxHealth);
                 if (stealHealth > 0)
                 {
                     m_queuedHealing += max(0, stealHealth);
                     Stats::Add("lifesteal-amount", stealHealth, m_record);
                 }
                 else if (stealHealth < 0)
                     PrintError("Lifesteal value " + stealHealth + " is invalid!");
                 PlayEffect(m_fxLifesteal, xy(m_unit.GetPosition()) + vec2(0, 1));
             }
         }
         if (di.Damage > 0)
         {
             Stats::Add("damage-dealt", di.Damage, m_record);
             Stats::Max("damage-dealt-max", di.Damage, m_record);
             if (m_returningDamage)
                 Stats::Add("damage-returned", di.Damage, m_record);
             Stats::Add("damage-dealt-physical", di.PhysicalDamage, m_record);
             Stats::Add("damage-dealt-magical", di.MagicalDamage, m_record);
         }
     }
Decimate()
int Player::Decimate (DecimateInfo dec, vec2 pos, vec2 dir) inline override private
Definition at line 485 of file Player.as.
References Stats::Add(), Actor::AddFloatingHurt(), clamp(), g_allModifiers, g_cvar_god, DecimateInfo::HealthCurr, DecimateInfo::HealthMax, PlayerBase::m_record, Actor::m_unit, DecimateInfo::ManaCurr, DecimateInfo::ManaMax, PlayerHealed, and PlayerHurt.
     {
         if (
 %if NON_FINAL
             g_cvar_god ||
 %endif
             m_record.IsDead())
         {
             return 0;
         }
         int maxHp = m_record.MaxHealth() + g_allModifiers.StatsAdd(this).x;
         int maxMp = m_record.MaxMana() + g_allModifiers.StatsAdd(this).y;
         int preHp = int(m_record.hp * maxHp);
         int preMp = int(m_record.mana * maxMp);
         float new = clamp((m_record.hp - dec.HealthMax) * (1.0f - dec.HealthCurr), 0.0f, 1.0f);
         m_record.hp = new;
         m_record.mana = clamp((m_record.mana - dec.ManaMax) * (1.0f - dec.ManaCurr), 0.0f, 1.0f);
         assert(m_record.hp, new);
         int dmgAmnt = preHp - int(m_record.hp * maxHp);
         int mpLoss = preMp - int(m_record.mana * maxMp);
         if (dmgAmnt < 0)
         {
             AddFloatingHurt(-dmgAmnt, 0, FloatingTextType::PlayerHealed);
             Stats::Add("amount-healed", -dmgAmnt, m_record);
         }
         else if (dmgAmnt > 0)
         {
             AddFloatingHurt(dmgAmnt, 0, FloatingTextType::PlayerHurt);
             //Stats::Add("damage-taken", dmgAmnt, m_record);
         }
         (Network::Message("UnitDecimated") << m_unit << dmgAmnt << mpLoss).SendToAll();
         return dmgAmnt;
     }
DisableModifiers()
void Player::DisableModifiers () inline private
Definition at line 128 of file Player.as.
Referenced by OnDeath().
     {
         g_allModifiers.Remove(m_record.modifiers);
     }
EnableModifiers()
void Player::EnableModifiers () inline private
Definition at line 123 of file Player.as.
     {
         g_allModifiers.Add(m_record.modifiers);
     }
FindUsable()
int Player::FindUsable (IUsable@ usable) inline private
Definition at line 133 of file Player.as.
References m_usables.
Referenced by AddUsable(), and RemoveUsable().
     {
         for (uint i = 0; i < m_usables.length(); i++)
         {
             if (m_usables[i].m_usable is usable)
                 return i;
         }
         return -1;
     }
GetDamageMul()
float Player::GetDamageMul (AttackRangeType rangeType) inline private
Definition at line 209 of file Player.as.
     {
         return 1;
     }
GetDamageMulTarget()
float Player::GetDamageMulTarget (bool melee, UnitPtr target) inline override private
Definition at line 214 of file Player.as.
     {
         return 1;
     }
GetTopUsable()
IUsable Player::GetTopUsable () inline private
Definition at line 168 of file Player.as.
References m_usables.
Referenced by Update().
     {
         for (uint i = 0; i < m_usables.length(); i++)
         {
             if (m_usables[i].m_usable.CanUse(this))
                 return m_usables[i].m_usable;
         }
         if (m_usables.length() > 0)
             return m_usables[0].m_usable;
         return null;
     }
GetWindScale()
float Player::GetWindScale () inline override private
Definition at line 112 of file Player.as.
References g_allModifiers, PlayerBase::m_buffs, m_windScale, and ActorBuffList::WindScaleMul().
 { return m_windScale * m_buffs.WindScaleMul() * g_allModifiers.WindScale(this); }
GiveArmor()
bool Player::GiveArmor (int amt, ArmorDef@ def, bool replace) inline private
Definition at line 380 of file Player.as.
Referenced by GiveArmor::Apply().
     {
         return false;
     }
GiveMana()
void Player::GiveMana (int mana) inline private
Definition at line 399 of file Player.as.
References Actor::AddFloatingGive(), clamp(), g_allModifiers, PlayerBase::m_record, and PlayerAmmo.
Referenced by Damage(), and Update().
     {
         ivec2 stats = g_allModifiers.StatsAdd(this);
         float manaf = mana;
         if (manaf < 0)
             manaf *= g_allModifiers.ManaDamageTakenMul(this);
         AddFloatingGive(int(manaf), FloatingTextType::PlayerAmmo);
         m_record.mana = clamp(m_record.mana + manaf / float(m_record.MaxMana() + stats.y), 0.0f, 1.0f);
         //TODO: Netsync
     }
Heal()
int Player::Heal (int amount) inline override private
Definition at line 424 of file Player.as.
References Stats::Add(), AddFloatingText(), g_allModifiers, m_queuedHealing, PlayerBase::m_record, Actor::m_unit, and PlayerHealed.
Referenced by Damage().
     {
         int healAmnt = int(amount * g_allModifiers.AllHealthGainScale(this));
         m_queuedHealing += healAmnt;
         AddFloatingText(FloatingTextType::PlayerHealed, "" + amount, m_unit.GetPosition());
         (Network::Message("PlayerHealed") << healAmnt << m_record.hp).SendToAll();
         Stats::Add("amount-healed", healAmnt, m_record);
         return healAmnt;
     }
Initialize()
void Player::Initialize (PlayerRecord@ record) inline override private
Definition at line 114 of file Player.as.
References PlayerBase::Initialize(), and m_preRenderables.
     {
         PlayerBase::Initialize(record);
         m_preRenderables.insertLast(this);
         EnableModifiers();
     }
IsDead()
bool Player::IsDead () inline override private
Definition at line 726 of file Player.as.
References PlayerBase::m_record, and Actor::m_unit.
Referenced by Pickup::Collide(), and Update().
 { return !m_unit.IsValid() || m_record.IsDead(); }
IsHusk()
bool Player::IsHusk () inline override private
Definition at line 207 of file Player.as.
 { return false; }
Kill()
void Player::Kill (Actor@ killer, uint weapon) inline override private
Definition at line 385 of file Player.as.
References DamageInfo(), m_lastDirection, and OnDeath().
     {
         OnDeath(DamageInfo(0, killer, 1, false, true, weapon), m_lastDirection);
         Actor::Kill(killer, weapon);
     }
KilledActor()
void Player::KilledActor (Actor@ killed, DamageInfo di) inline override private
Definition at line 331 of file Player.as.
References Stats::Add(), ActorBuffList::ExperienceMul(), Tweak::ExperienceScale, g_allModifiers, g_flags, g_gameMode, g_mpExpScale, g_ngp, PlayerBase::GetComboBars(), Kill(), Actor::KilledActor(), PlayerBase::m_buffs, PlayerBase::m_comboCount, PlayerBase::m_comboTime, PlayerBase::m_record, Actor::m_unit, and Stats::Max().
     {
         PlayerBase::KilledActor(killed, di);
         auto enemy = cast<CompositeActorBehavior>(killed);
         Stats::Add("enemies-killed", 1, m_record);
         if (enemy !is null && enemy.m_enemyType != "")
             Stats::Add(enemy.m_enemyType + "-killed", 1, m_record);
         cast<Campaign>(g_gameMode).m_townLocal.KilledEnemy(killed.m_unit.GetUnitProducer());
         g_allModifiers.TriggerEffects(this, killed, Modifiers::EffectTrigger::Kill);
         //TODO: Cache flag?
         if (g_flags.IsSet("unlock_combo"))
         {
             m_comboCount++;
             Stats::Max("best-combo", m_comboCount, m_record);
             vec2 combo = GetComboBars();
             if (combo.x >= 1.0f)
                 m_comboTime = 2000;
             else
                 m_comboTime = 1000;
         }
         if (enemy !is null && enemy.m_expReward > 0)
         {
             int xp = int(enemy.m_expReward * (1.0f + float(g_ngp) * 0.1f) + 30 * float(g_ngp));
             (Network::Message("PlayerShareExperience") << xp).SendToAll();
             float xpReward = float(xp - m_record.level * 3);
             xpReward *= m_buffs.ExperienceMul();
             xpReward *= Tweak::ExperienceScale;
             float expMul = g_allModifiers.ExpMul(this, killed) * g_mpExpScale;
             int xpr = int(xpReward * expMul);
             if (xpr > 0)
                 m_record.GiveExperience(xpr);
         }
     }
NetDamage()
void Player::NetDamage (DamageInfo dmg, vec2 pos, vec2 dir) inline override private
Definition at line 675 of file Player.as.
Referenced by PlayerHandler::PlayerDamage().
     {
         this.Damage(dmg, pos, dir);
     }
NetDecimate()
void Player::NetDecimate (int hp, int mana) inline override private
Definition at line 474 of file Player.as.
References Actor::AddFloatingHurt(), g_allModifiers, PlayerBase::m_record, and PlayerHealed.
     {
         int maxHp = m_record.MaxHealth() + g_allModifiers.StatsAdd(this).x;
         m_record.hp -= float(hp) / float(maxHp);
         if (hp < 0)
             AddFloatingHurt(-hp, 0, FloatingTextType::PlayerHealed);
         else if (hp > 0)
             AddFloatingHurt(hp, 0, FloatingTextType::PlayerHurt);
     }
NetShareExperience()
void Player::NetShareExperience (int experience) inline private
Definition at line 314 of file Player.as.
References ActorBuffList::ExperienceMul(), Tweak::ExperienceScale, g_allModifiers, g_mpExpScale, PlayerBase::m_buffs, and PlayerBase::m_record.
Referenced by PlayerHandler::PlayerShareExperience().
     {
         float xpReward = float(experience - m_record.level * 3);
         xpReward *= m_buffs.ExperienceMul();
         xpReward *= Tweak::ExperienceScale;
         float expMul = g_allModifiers.ExpMul(this, null) * g_mpExpScale;
         int xpr = int(xpReward * expMul);
         if (xpr > 0)
             m_record.GiveExperience(xpr);
     }
OnComboBegin()
void Player::OnComboBegin () inline override private
Definition at line 938 of file Player.as.
References PlayerBase::m_comboCount, and PlayerBase::m_comboTime.
     {
         (Network::Message("PlayerCombo") << true << m_comboTime << m_comboCount).SendToAll();
         PlayerBase::OnComboBegin();
     }
OnComboEnd()
void Player::OnComboEnd () inline override private
Definition at line 944 of file Player.as.
     {
         (Network::Message("PlayerCombo") << false << 0 << 0).SendToAll();
         PlayerBase::OnComboEnd();
     }
OnDeath()
void Player::OnDeath (DamageInfo di, vec2 dir) inline override private
Definition at line 690 of file Player.as.
References Stats::Add(), DamageInfo::Attacker, DamageInfo::Damage, DamageInfo::DamageType, DisableModifiers(), g_gameMode, GetHUD(), PlayerBase::m_record, Actor::m_unit, DamageInfo::Melee, PlayerBase::OnDeath(), and DamageInfo::Weapon.
Referenced by Damage(), Kill(), and SoulLinkKill().
     {
         PlayerBase::OnDeath(di, dir);
         DisableModifiers();
         auto gm = cast<Campaign>(g_gameMode);
         Stats::Add("death-count", 1, m_record);
         if (cast<Town>(gm) is null)
             Stats::Add("floor-deaths-" + (gm.m_levelCount + 1), 1, m_record);
         int killerPeer = -1;
         auto plyKiller = cast<PlayerBase>(di.Attacker);
         if (plyKiller !is null)
             killerPeer = plyKiller.m_record.peer;
         m_record.deaths++;
         m_record.deathsTotal++;
         (Network::Message("PlayerDied") << killerPeer << int(di.DamageType) << int(di.Damage) << di.Melee << di.Weapon).SendToAll();
         PlayerRecord@ killerRecord;
         if (plyKiller !is null)
             @killerRecord = plyKiller.m_record;
         else if (di.Attacker !is null)
             cast<Campaign>(g_gameMode).m_townLocal.EnemyKilledPlayer(di.Attacker.m_unit.GetUnitProducer());
         gm.PlayerDied(m_record, killerRecord, di);
         auto hud = GetHUD();
         if (hud !is null)
             hud.OnDeath();
     }
OnLevelUp()
void Player::OnLevelUp (int levels) inline private
Definition at line 739 of file Player.as.
References Stats::Add(), AddFloatingText(), GetHUD(), PlayerBase::m_record, Actor::m_unit, Pickup, PlayEffect(), and PlaySound3D().
     {
         (Network::Message("PlayerLevelUp")).SendToAll();
         auto hud = GetHUD();
         hud.PlayPickup();
         PlaySound3D(Resources::GetSoundEvent("event:/player/levelup"), m_unit);
         PlayEffect("effects/players/levelup.effect", m_unit);
         AddFloatingText(FloatingTextType::Pickup, Resources::GetString(".hud.levelup"), m_unit.GetPosition());
         m_record.hp = 1.0;
         m_record.mana = 1.0;
         Stats::Add("levels-gained", levels, m_record);
         Stats::Add("avg-levels-gained", levels, m_record);
         Stats::Max("max-level-" + m_record.charClass, m_record.level);
     }
OnNewTitle()
void Player::OnNewTitle (Titles::Title@ title) inline private
Definition at line 728 of file Player.as.
References g_gameMode, Titles::Title::m_name, PlayerBase::m_record, and Tweak::NotificationColors_NewTitle.
     {
         auto gm = cast<Campaign>(g_gameMode);
         gm.SavePlayer(m_record);
         dictionary paramsTitle = { { "title", Resources::GetString(title.m_name) } };
         gm.m_notifications.Add(Resources::GetString(".hud.newtitle.character", paramsTitle), ParseColorRGBA("#" + Tweak::NotificationColors_NewTitle + "FF"));
         RefreshModifiers();
     }
PlayerKilled()
void Player::PlayerKilled (PlayerRecord@ player) inline private
Definition at line 327 of file Player.as.
     {
     }
PreRender()
bool Player::PreRender (int idt) inline private
Definition at line 1222 of file Player.as.
References Actor::m_unit.
     {
         if (m_unit.IsDestroyed())
             return true;
         return false;
     }
RefreshModifiers()
void Player::RefreshModifiers () inline override private
Definition at line 180 of file Player.as.
References g_classTitles, Titles::ClassTitles::RefreshModifiers(), and PlayerBase::RefreshModifiers().
Referenced by ChapelShopMenuContent::OnFunc().
     {
         PlayerBase::RefreshModifiers();
         // Modifiers for class title
         SValueBuilder builder;
         g_classTitles.RefreshModifiers(builder);
         (Network::Message("PlayerTitleModifiers") << builder.Build()).SendToAll();
     }
RemoveUsable()
void Player::RemoveUsable (IUsable@ usable) inline private
Definition at line 156 of file Player.as.
References FindUsable(), and m_usables.
Referenced by Chest::EndCollision(), ForgeBlueprint::EndCollision(), Item::EndCollision(), TavernBarrel::EndCollision(), WorldScript::StoreOre::OnExit(), WorldScript::RandomBuff::OnExit(), WorldScript::UseTrigger::OnExit(), WorldScript::Well::OnExit(), and WorldScript::Door::OnExit().
     {
         int index = FindUsable(usable);
         if (index != -1)
         {
             if (--m_usables[index].m_refCount <= 0)
                 m_usables.removeAt(index);
             return;
         }
         PrintError("Tried removing unlisted usable");
     }
SendPlayerMove()
void Player::SendPlayerMove (vec2 dir, bool force = false) inline private
Definition at line 1201 of file Player.as.
References distsq(), force, m_lastSentDir, m_lastSentPos, Actor::m_unit, and xy().
     {
         auto pos = xy(m_unit.GetPosition());
         if (!force)
         {
             if (distsq(m_lastSentPos, pos) > 1 || distsq(m_lastSentDir, dir) > 0.01)
             {
                 m_lastSentPos = pos;
                 m_lastSentDir = dir;
                 (Network::Message("PlayerMove") << pos << dir).SendToAll();
             }
         }
         else
         {
             m_lastSentPos = pos;
             m_lastSentDir = dir;
             (Network::Message("PlayerMoveForce") << pos << dir).SendToAll();
         }
     }
SoulLinkDamage()
void Player::SoulLinkDamage (int dmg) inline private
Definition at line 440 of file Player.as.
     {
     /*
         if (
 %if NON_FINAL
             g_cvar_god ||
 %endif
             m_record.IsDead() || dmg <= 0)
         {
             return;
         }
         int maxHp = m_record.MaxHealth();
         m_record.hp -= float(dmg) / float(maxHp);
         AddFloatingHurt(dmg, 0, FloatingTextType::PlayerHurt);
         m_dmgColor = vec4(1, 0, 0, 1);
         Stats::Add("damage-taken", dmg, m_record);
         Stats::Max("damage-taken-max", dmg, m_record);
         if (m_record.CurrentHealth() <= 0)
             OnDeath(DamageInfo(null, dmg, 0, false, true, 0), m_lastDirection);
         else
         {
             if (m_gore !is null)
                 m_gore.OnHit(float(dmg) / float(maxHp), xy(m_unit.GetPosition()), m_dirAngle);
             dictionary params = { { "damage", float(dmg) } };
             PlaySound3D(m_hurtSound, m_unit, params);
         }
     */
     }
SoulLinkKill()
void Player::SoulLinkKill (PlayerHusk@ killer) inline private
Definition at line 434 of file Player.as.
References DamageInfo(), m_lastDirection, and OnDeath().
     {
         OnDeath(DamageInfo(killer, 1, 1, false, true, 0), m_lastDirection);
         Actor::Kill(killer, 0);
     }
SpendCost()
bool Player::SpendCost (int mana, int stamina, int health) inline override private
Definition at line 768 of file Player.as.
References Stats::Add(), AddFloatingText(), ActorBuffList::FreeMana(), g_allModifiers, PlayerBase::m_buffs, PlayerBase::m_record, m_sndNoMana, Actor::m_unit, PlayerArmor, and PlaySound3D().
     {
         ivec2 stats = g_allModifiers.StatsAdd(this);
         float manaCostMul = g_allModifiers.SpellCostMul(this);
         float manaCost = float(mana) / float(m_record.MaxMana() + stats.y) * manaCostMul;
         if (manaCost > 0 && !m_buffs.FreeMana())
         {
             if (m_record.mana < manaCost)
             {
                 int diff = int(ceil((manaCost - m_record.mana) * float(m_record.MaxMana())));
                 AddFloatingText(FloatingTextType::PlayerArmor, "(-" + diff + ")", m_unit.GetPosition());
                 PlaySound3D(m_sndNoMana, m_unit.GetPosition());
                 return false;
             }
             m_record.mana -= manaCost;
             //m_record.stamina -= stamina;
             Stats::Add("spent-mana", int(mana * manaCostMul), m_record);
         }
         /*
         if (stamina > 0)
         {
             if (m_record.stamina < stamina)
             {
                 AddFloatingText(FloatingTextType::EnemyImmortal, "Stamina!", m_unit.GetPosition());
                 return false;
             }
         }
         */
         return true;
     }
TakeMana()
void Player::TakeMana (int mana) inline private
Definition at line 413 of file Player.as.
References Actor::AddFloatingGive(), clamp(), g_allModifiers, PlayerBase::m_record, and PlayerAmmo.
     {
         ivec2 stats = g_allModifiers.StatsAdd(this);
         float manaf = float(mana) * g_allModifiers.ManaDamageTakenMul(this);
         AddFloatingGive(-int(manaf), FloatingTextType::PlayerAmmo);
         m_record.mana = clamp(m_record.mana - manaf / float(m_record.MaxMana() + stats.y), 0.0f, 1.0f);
         //TODO: Netsync
     }
Update()
void Player::Update (int dt) inline override private
Definition at line 950 of file Player.as.
References abs(), Skills::Activate(), Stats::Add(), AddFloatingText(), ActorBuffList::AntiConfuse(), Attack, CheckSkillBlocked(), CheckUseSkill(), clamp(), ActorBuffList::Confuse(), ActorBuffList::Disarm(), ActorBuffList::Drifting(), DrinkPotion, Float(), g_allModifiers, g_flags, g_gameMode, g_scene, GetHUD(), GetInput(), AnimString::GetSceneName(), GetTopUsable(), GiveMana(), IsDead(), lerp(), PlayerBase::m_buffs, PlayerBase::m_comboActive, PlayerBase::m_dirAngle, m_driftingOffset, PlayerBase::m_effectParams, PlayerBase::m_idleAnim, m_lastDirection, m_lastSentHP, PlayerBase::m_playerBobbing, m_potionDelay, m_queuedHealing, PlayerBase::m_record, PlayerBase::m_skills, Actor::m_unit, PlayerBase::m_walkAnim, min, ActorBuffList::MinSpeed(), ActorBuffList::MoveSpeedMul(), PlayerBase::NetHeal(), None, PlayerHealed, Tweak::PlayerSpeed, Tweak::PlayerSpeedMax, PlaySound3D(), Tutorial::RegisterAction(), PlayerBase::SetAngle(), PlayerBase::SetBodyAnim(), unit, PlayerBase::Update(), PlayerBase::UpdateFootsteps(), and xy().
     {
         PlayerBase::Update(dt);
         if (m_potionDelay > 0)
             m_potionDelay -= dt;
         auto input = GetInput();
         auto aimDir = input.AimDir;
         auto moveDir = input.MoveDir;
         if (m_buffs.Confuse() && !m_buffs.AntiConfuse())
         {
             aimDir *= -1;
             moveDir *= -1;
         }
         if (m_buffs.Drifting())
         {
             m_driftingOffset += 0.75f / dt;
             float ang = (sin(m_driftingOffset * 0.5f) - m_driftingOffset * 0.15f) * 0.4f;
             float a;
             a = atan(aimDir.y, aimDir.x) + ang;
             aimDir = vec2(cos(a), sin(a)) * length(aimDir);
             a = atan(moveDir.y, moveDir.x) + ang;
             moveDir = vec2(cos(a), sin(a)) * length(moveDir);
         }
         g_allModifiers.Update(this, dt);
         vec2 regen = (vec2(m_record.HealthRegen(), m_record.ManaRegen()) + g_allModifiers.RegenAdd(this)) * g_allModifiers.RegenMul(this);
         ivec2 stats = g_allModifiers.StatsAdd(this);
         m_effectParams.Set("hp_regen", (m_record.hp < 1.0f) ? regen.x : 0.f);
         m_effectParams.Set("mp_regen", (m_record.mana < 1.0f) ? regen.y : 0.f);
         float hpGainScale = g_allModifiers.AllHealthGainScale(this);
         float hpMax = m_record.MaxHealth() + stats.x;
         m_record.hp = clamp(m_record.hp + dt / 1000.0f * (regen.x * hpGainScale) / hpMax, 0.0f, 1.0f);
         m_record.mana = clamp(m_record.mana + dt / 1000.0f * regen.y / (m_record.MaxMana() + stats.y), 0.0f, 1.0f);
         if (m_queuedHealing > 0)
         {
             float healing = min(hpMax / 1000.0f * dt, m_queuedHealing);
             if (m_record.hp * hpMax + healing > hpMax)
             {
                 healing = float(hpMax - m_record.hp * hpMax);
                 m_queuedHealing = 0;
             }
             else
                 m_queuedHealing -= healing;
             m_record.hp = min(1.f, m_record.hp + healing / hpMax);
         }
         if (abs(m_lastSentHP - m_record.hp) > 0.001)
         {
             m_lastSentHP = m_record.hp;
             (Network::Message("PlayerSyncHealth") << m_lastSentHP).SendToAll();
         }
         auto baseGameMode = cast<BaseGameMode>(g_gameMode);
         HUD@ hud = GetHUD();
         bool freezeControls = IsDead() or baseGameMode.ShouldFreezeControls();
         int snapAngleCount = GetVarInt("g_movedir_snap");
         if (snapAngleCount > 0 && lengthsq(moveDir) > 0)
         {
             float snapAngle = TwoPI / float(snapAngleCount);
             float curAngle = atan(moveDir.y, moveDir.x);
             float snappedAngle = round(curAngle / snapAngle) * snapAngle;
             moveDir.x = cos(snappedAngle);
             moveDir.y = sin(snappedAngle);
         }
         int skillDt = int(g_allModifiers.SkillTimeMul(this) * dt);
         if (!freezeControls)
         {
             if (!m_buffs.Disarm())
             {
                 CheckUseSkill(skillDt, input.Attack4, m_skills[3], aimDir);
                 CheckUseSkill(skillDt, input.Attack3, m_skills[2], aimDir);
                 CheckUseSkill(skillDt, input.Attack2, m_skills[1], aimDir);
                 if (input.Attack1.Pressed)
                 {
                     auto skill = cast<Skills::ActiveSkill>(m_skills[0]);
                     if (skill !is null)
                     {
                         if (skill.m_cooldownC > 0 && g_allModifiers.CooldownClear(this, skill))
{
                             skill.m_cooldownC = 0;
                             skill.m_cooldownOverride = true;
                         }
                         else
                             skill.m_cooldownOverride = false;
                     }
                 }
                 if (input.Attack1.Down && !input.Ping.Down && !CheckSkillBlocked(m_skills[0]))
                 {
                     if (m_skills[0].Activate(aimDir))
                         g_allModifiers.TriggerEffects(this, null, Modifiers::EffectTrigger::Attack);
                 }
             }
             if ((input.Potion.Pressed && m_potionDelay <= 0) && (m_record.hp < 1.0 || m_record.mana < 1.0) && g_flags.IsSet("unlock_apothecary"))
             {
                 float healAmnt = 50 * g_allModifiers.PotionHealMul(this);
                 float manaAmnt = 50 * g_allModifiers.PotionManaMul(this);
                 int charges = 1 + g_allModifiers.PotionCharges();
                 if (charges > m_record.potionChargesUsed)
                 {
                     m_record.potionChargesUsed++;
                     int heal = int((healAmnt + 0.5f) * g_allModifiers.AllHealthGainScale(this));
                     NetHeal(heal);
                     (Network::Message("PlayerHealed") << int(healAmnt) << m_record.hp).SendToAll();
                     Stats::Add("amount-healed", heal, m_record);
                     AddFloatingText(FloatingTextType::PlayerHealed, "" + int(healAmnt + 0.5f), m_unit.GetPosition());
                     this.GiveMana(int(manaAmnt + 0.5f));
                     PlaySound3D(Resources::GetSoundEvent("event:/player/drink_potion"), m_unit.GetPosition());
                     Stats::Add("potion-charges-used", 1, m_record);
                     g_allModifiers.TriggerEffects(this, null, Modifiers::EffectTrigger::DrinkPotion);
                     m_potionDelay = GetVarInt("g_potion_delay");
                     Tutorial::RegisterAction("potion");
                 }
             }
             if (input.Use.Pressed && !m_buffs.Disarm())
             {
                 auto usable = GetTopUsable();
                 if (usable !is null && usable.CanUse(this))
                 {
                     Tutorial::RegisterAction("use");
                     UnitPtr unit = usable.GetUseUnit();
                     UnitProducer@ prod = unit.GetUnitProducer();
                     if (prod !is null && prod.GetNetSyncMode() == NetSyncMode::None)
                         usable.Use(this);
                     else if (Network::IsServer())
                     {
                         (Network::Message("UseUnit") << unit << m_unit).SendToAll();
                         usable.Use(this);
                     }
                     else
                         (Network::Message("UseUnitSecure") << unit).SendToHost();
                 }
             }
         }
         PhysicsBody@ bdy = m_unit.GetPhysicsBody();
         vec2 dir = vec2(cos(m_dirAngle), sin(m_dirAngle));
         // If we have no physics body, we can't do much (player died)
         if (bdy is null)
             return;
         float moveSpeed = Tweak::PlayerSpeed;
         float slowScale = g_allModifiers.SlowScale(this);
         moveSpeed += g_allModifiers.MoveSpeedAdd(this, slowScale);
         moveSpeed *= g_allModifiers.MoveSpeedMul(this, slowScale);
         moveSpeed *= m_buffs.MoveSpeedMul(slowScale);
         for (uint i = 0; i < m_skills.length(); i++)
         {
             float speedMod = m_skills[i].GetMoveSpeedMul();
             if (speedMod >= 1.0f || !m_comboActive)
                 moveSpeed *= speedMod;
             else
                 moveSpeed *= lerp(speedMod, 1.0, 0.5);
         }
         array<Tileset@>@ tilesets = g_scene.FetchTilesets(xy(m_unit.GetPosition()));
         for (int i = tilesets.length() - 1; i >= 0; i--)
         {
             auto tsd = tilesets[i].GetData();
             if (tsd is null)
                 continue;
             SValue@ tilesetSpeed = tsd.GetDictionaryEntry("walk-speed");
             if (tilesetSpeed !is null && tilesetSpeed.GetType() == SValueType::Float)
             {
                 moveSpeed *= tilesetSpeed.GetFloat();
                 break;
             }
         }
         moveSpeed = min(moveSpeed, Tweak::PlayerSpeedMax);
         float minSpeed = m_buffs.MinSpeed();
         auto moveDirLen = length(moveDir);
         if (moveDirLen < minSpeed)
             moveDir = normalize((moveDirLen > 0) ? moveDir : aimDir) * minSpeed;
         moveDir = freezeControls ? vec2() : (moveDir * moveSpeed);
         for (uint i = 0; i < m_skills.length(); i++)
         {
             vec2 skillMoveDir = m_skills[i].GetMoveDir();
             if (skillMoveDir.x != 0 || skillMoveDir.y != 0)
             {
                 moveDir = skillMoveDir;
                 break;
             }
         }
         int distance = int(length(moveDir));
         if (distance > 0)
             Stats::Add("units-traveled", distance, m_record);
         bdy.SetLinearVelocity(moveDir);
         float facing = atan(aimDir.y, aimDir.x);
         SetAngle(facing);
         bool walking = (lengthsq(bdy.GetLinearVelocity()) > 0.1);
         string scene = walking ? m_walkAnim.GetSceneName(facing) : m_idleAnim.GetSceneName(facing);
         SetBodyAnim(scene, false);
         if (m_playerBobbing)
             m_unit.SetPositionZ(walking ? ((m_unit.GetUnitSceneTime() / 125) % 2) : 0);
         UpdateFootsteps(dt, false);
         for (uint i = 0; i < m_skills.length(); i++)
             m_skills[i].Update(skillDt, walking);
         vec2 currDir = bdy.GetLinearVelocity();
         if (length(currDir) > 0.2)
             m_lastDirection = currDir;
         SendPlayerMove(dir);
     }
WarnCooldown()
void Player::WarnCooldown (Skills::Skill@ skill, int ms) inline override private
Definition at line 759 of file Player.as.
References AddFloatingText(), formatTime(), g_allModifiers, Actor::m_unit, and PlayerArmor.
     {
         if (skill.m_skillId == 0)
             return;
         AddFloatingText(FloatingTextType::PlayerArmor, "[" + formatTime(ms / 1000.0f / g_allModifiers.SkillTimeMul(this), true, false, false, false, true) + "]", m_unit.GetPosition());
         PlaySound3D(m_sndCooldown, m_unit.GetPosition());
     }
Member Data Documentation
m_driftingOffset
float Player::m_driftingOffset private
Definition at line 21 of file Player.as.
Referenced by Update().
m_fxBlockMagical
UnitScene Player::m_fxBlockMagical private
Definition at line 28 of file Player.as.
Referenced by Damage(), and Player().
m_fxBlockPhysical
UnitScene Player::m_fxBlockPhysical private
Definition at line 27 of file Player.as.
Referenced by Damage(), and Player().
m_fxBlockProjectile
UnitScene Player::m_fxBlockProjectile private
Definition at line 25 of file Player.as.
Referenced by BlockProjectile(), and Player().
m_fxLifesteal
UnitScene Player::m_fxLifesteal private
Definition at line 29 of file Player.as.
Referenced by DamagedActor(), and Player().
m_insideJammable
bool Player::m_insideJammable private
Definition at line 35 of file Player.as.
Referenced by JammableBehavior::Collide(), and JammableBehavior::EndCollision().
m_lastCollideTime
uint Player::m_lastCollideTime private
Definition at line 807 of file Player.as.
Referenced by Collide().
m_lastCollideUnit
UnitPtr Player::m_lastCollideUnit private
Definition at line 808 of file Player.as.
Referenced by Collide().
m_lastDirection
vec2 Player::m_lastDirection private
Definition at line 16 of file Player.as.
Referenced by Kill(), PlayerHandler::PlayerDamage(), SoulLinkKill(), and Update().
m_lastSentDir
vec2 Player::m_lastSentDir private
Definition at line 18 of file Player.as.
Referenced by SendPlayerMove().
m_lastSentHP
float Player::m_lastSentHP private
Definition at line 19 of file Player.as.
Referenced by BroadcastNetDamage(), and Update().
m_lastSentPos
vec2 Player::m_lastSentPos private
Definition at line 17 of file Player.as.
Referenced by SendPlayerMove().
m_potionDelay
int Player::m_potionDelay private
Definition at line 37 of file Player.as.
Referenced by Update().
m_queuedHealing
float Player::m_queuedHealing = 0 private
Definition at line 22 of file Player.as.
Referenced by DamagedActor(), Heal(), and Update().
m_returningDamage
bool Player::m_returningDamage private
Definition at line 34 of file Player.as.
Referenced by Damage(), DamagedActor(), and Player().
m_sndBlockProjectile
SoundEvent Player::m_sndBlockProjectile private
Definition at line 26 of file Player.as.
Referenced by BlockProjectile(), and Player().
m_sndCooldown
SoundEvent Player::m_sndCooldown private
Definition at line 31 of file Player.as.
Referenced by Player().
m_sndEvade
SoundEvent Player::m_sndEvade private
Definition at line 32 of file Player.as.
Referenced by Damage(), and Player().
m_sndNoMana
SoundEvent Player::m_sndNoMana private
Definition at line 30 of file Player.as.
Referenced by Player(), and SpendCost().
m_usables
array<PlayerUsable@> Player::m_usables private
Definition at line 14 of file Player.as.
Referenced by AddUsable(), FindUsable(), GetTopUsable(), and RemoveUsable().
m_windScale
float Player::m_windScale private
Definition at line 39 of file Player.as.
Referenced by GetWindScale().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Player/Player.as