HoHDocs: Skills::DropUnit Class Reference
Skills::DropUnit Class Reference
Private Member Functions
DropUnit (UnitPtr unit, SValue &params)
TargetingMode GetTargetingMode (int &out size) override
bool Activate (vec2 target) override
bool NeedNetParams () override
void DoActivate (SValueBuilder@ builder, vec2 target) override
void NetDoActivate (SValue@ param, vec2 target) override
void DoUpdate (int dt) override
UnitPtr SpawnUnit (vec3 pos, vec2 target)
Private Attributes
UnitProducer m_prod
bool m_needNetSync
uint m_maxCount
float m_distance
array< UnitPtr > m_units
Detailed Description
Definition at line 3 of file DropUnit.as.
Constructor & Destructor Documentation
DropUnit()
Skills::DropUnit::DropUnit (UnitPtr unit, SValue & params) inline private
Definition at line 14 of file DropUnit.as.
References IsNetsyncedExistance(), m_distance, m_maxCount, m_needNetSync, m_prod, and unit.
         {
             super(unit, params);
             @m_prod = Resources::GetUnitProducer(GetParamString(unit, params, "unit"));
             m_needNetSync = !IsNetsyncedExistance(m_prod.GetNetSyncMode());
             m_maxCount = GetParamInt(unit, params, "max-count");
             m_distance = GetParamFloat(unit, params, "offset", false, 0.0f);
         }
Member Function Documentation
Activate()
bool Skills::DropUnit::Activate (vec2 target) inline override private
Definition at line 28 of file DropUnit.as.
References Skills::ActiveSkill::Activate(), m_maxCount, and m_units.
         {
             if (m_units.length() >= m_maxCount)
                 return false;
             return ActiveSkill::Activate(target);
         }
DoActivate()
void Skills::DropUnit::DoActivate (SValueBuilder@ builder, vec2 target) inline override private
Definition at line 38 of file DropUnit.as.
References m_distance, m_needNetSync, Skills::m_owner, SpawnUnit(), and xyz().
         {
             vec3 unitPos = m_owner.m_unit.GetPosition() + xyz(target * m_distance);
             unitPos.z = 0;
             builder.PushVector3(unitPos);
             if (m_needNetSync || Network::IsServer())
                 SpawnUnit(unitPos, target);
         }
DoUpdate()
void Skills::DropUnit::DoUpdate (int dt) inline override private
Definition at line 60 of file DropUnit.as.
References m_units.
         {
             for (int i = m_units.length() - 1; i >= 0; i--)
             {
                 if (m_units[i].IsDestroyed())
                     m_units.removeAt(i);
             }
         }
GetTargetingMode()
TargetingMode Skills::DropUnit::GetTargetingMode (int &out size) inline override private
Definition at line 26 of file DropUnit.as.
References Skills::TargetAOE.
 { return TargetingMode::TargetAOE; }
NeedNetParams()
bool Skills::DropUnit::NeedNetParams () inline override private
Definition at line 36 of file DropUnit.as.
 { return true; }
NetDoActivate()
void Skills::DropUnit::NetDoActivate (SValue@ param, vec2 target) inline override private
Definition at line 48 of file DropUnit.as.
References m_needNetSync, Skills::ActiveSkill::PlaySkillEffect(), and SpawnUnit().
         {
             if (!m_needNetSync && !Network::IsServer())
             {
                 PlaySkillEffect(target);
                 return;
             }
             vec3 unitPos = param.GetVector3();
             SpawnUnit(unitPos, target);
         }
SpawnUnit()
UnitPtr Skills::DropUnit::SpawnUnit (vec3 pos, vec2 target) inline private
Definition at line 69 of file DropUnit.as.
References g_scene, m_needNetSync, Skills::m_owner, m_prod, m_units, Skills::ActiveSkill::PlaySkillEffect(), and unit.
Referenced by DoActivate(), NetDoActivate(), and Skills::DropUnitWarlock::SpawnUnit().
         {
             PlaySkillEffect(target);
             UnitPtr unit = m_prod.Produce(g_scene, pos);
             auto behavior = cast<IOwnedUnit>(unit.GetScriptBehavior());
             behavior.Initialize(m_owner, 1.0f, false);
             if (!m_needNetSync && Network::IsServer())
                 (Network::Message("SetOwnedUnit") << unit << m_owner.m_unit << 1.0f).SendToAll();
             m_units.insertLast(unit);
             return unit;
         }
Member Data Documentation
m_distance
float Skills::DropUnit::m_distance private
Definition at line 10 of file DropUnit.as.
Referenced by DoActivate(), and DropUnit().
m_maxCount
uint Skills::DropUnit::m_maxCount private
Definition at line 8 of file DropUnit.as.
Referenced by Activate(), and DropUnit().
m_needNetSync
bool Skills::DropUnit::m_needNetSync private
Definition at line 6 of file DropUnit.as.
Referenced by DoActivate(), DropUnit(), NetDoActivate(), and SpawnUnit().
m_prod
UnitProducer Skills::DropUnit::m_prod private
Definition at line 5 of file DropUnit.as.
Referenced by DropUnit(), and SpawnUnit().
m_units
array<UnitPtr> Skills::DropUnit::m_units private
Definition at line 12 of file DropUnit.as.
Referenced by Activate(), DoUpdate(), and SpawnUnit().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Skills/DropUnit.as