HoHDocs: MenuMouse Class Reference
MenuMouse Class Reference
Private Member Functions
MenuMouse (GameInput@ inputGame, MenuInput@ inputMenu, bool splitscreen)
Platform::CursorInfo GetCursor () override
void SetText (string str)
void Update (int dt) override
bool ShouldRenderName ()
void Draw (int idt, SpriteBatch &sb) override
Private Attributes
BitmapString m_text
bool m_splitscreen
ControlMap m_singularMap
vec2 m_lastPosMove
int m_tmSinceMove
Detailed Description
Definition at line 1 of file MenuMouse.as.
Constructor & Destructor Documentation
MenuMouse()
MenuMouse::MenuMouse (GameInput@ inputGame, MenuInput@ inputMenu, bool splitscreen) inline private
Definition at line 11 of file MenuMouse.as.
References ControlMap::ID, m_singularMap, m_splitscreen, and SetText().
     {
         super(inputGame, inputMenu);
         m_splitscreen = splitscreen;
         if (m_splitscreen)
         {
             array<ControlMap@>@ maps = inputGame.GetControlMaps();
             if (maps.length() == 1)
             {
                 @m_singularMap = maps[0];
                 SetText(Resources::GetString(".menu.controls.layout." + m_singularMap.ID));
             }
         }
     }
Member Function Documentation
Draw()
void MenuMouse::Draw (int idt, SpriteBatch & sb) inline override private
Definition at line 60 of file MenuMouse.as.
References MouseBase::Draw(), g_gameMode, GetCursor(), MouseBase::GetPos(), m_text, Platform::CursorInfo::m_texture, and AGameMode::m_wndScale.
     {
         MouseBase::Draw(idt, sb);
         if (m_text is null)
             return;
         Platform::CursorInfo@ cursor = GetCursor();
         if (cursor is null)
             return;
         vec2 pos = GetPos(idt) / g_gameMode.m_wndScale;
         pos.x += (cursor.m_texture.GetWidth() - 10) / 2 - m_text.GetWidth() / 2;
         pos.y += 28;
         sb.DrawString(pos, m_text);
     }
GetCursor()
Platform::CursorInfo MenuMouse::GetCursor () inline override private
Definition at line 27 of file MenuMouse.as.
References Platform::CursorColorable, g_gameMode, AGameMode::m_currCursor, and m_splitscreen.
Referenced by Draw().
     {
         if (m_splitscreen)
             return Platform::CursorColorable;
         else
             return g_gameMode.m_currCursor;
     }
SetText()
void MenuMouse::SetText (string str) inline private
Definition at line 35 of file MenuMouse.as.
References m_text.
Referenced by MenuMouse().
     {
         auto font = Resources::GetBitmapFont("gui/fonts/font_hw8.fnt");
         if (font !is null)
             @m_text = font.BuildText(str);
     }
ShouldRenderName()
bool MenuMouse::ShouldRenderName () inline private
Definition at line 54 of file MenuMouse.as.
References g_gameMode.
     {
         auto gm = cast<MainMenu>(g_gameMode);
         return (gm !is null && gm.m_mice.length() > 1);
     }
Update()
void MenuMouse::Update (int dt) inline override private
Definition at line 42 of file MenuMouse.as.
References distsq(), MouseBase::GetPos(), m_lastPosMove, m_tmSinceMove, and MouseBase::Update().
     {
         vec2 mousePos = GetPos(0);
         if (distsq(mousePos, m_lastPosMove) > 0)
             m_tmSinceMove = 0;
         else
             m_tmSinceMove += dt;
         m_lastPosMove = mousePos;
         MouseBase::Update(dt);
     }
Member Data Documentation
m_lastPosMove
vec2 MenuMouse::m_lastPosMove private
Definition at line 8 of file MenuMouse.as.
Referenced by Update().
m_singularMap
ControlMap MenuMouse::m_singularMap private
Definition at line 6 of file MenuMouse.as.
Referenced by MenuMouse().
m_splitscreen
bool MenuMouse::m_splitscreen private
Definition at line 5 of file MenuMouse.as.
Referenced by GetCursor(), and MenuMouse().
m_text
BitmapString MenuMouse::m_text private
Definition at line 3 of file MenuMouse.as.
Referenced by Draw(), and SetText().
m_tmSinceMove
int MenuMouse::m_tmSinceMove private
Definition at line 9 of file MenuMouse.as.
Referenced by Update().
The documentation for this class was generated from the following file:
scripts/GUI/Input/MenuMouse.as