HoHDocs: Skills::Whirlwind Class Reference
Skills::Whirlwind Class Reference
Private Member Functions
Whirlwind (UnitPtr unit, SValue &params)
void Initialize (Actor@ owner, ScriptSprite@ icon, uint id) override
TargetingMode GetTargetingMode (int &out size) override
void DoActivate (SValueBuilder@ builder, vec2 target) override
void NetDoActivate (SValue@ param, vec2 target) override
void StartWhirl (bool husk)
float GetMoveSpeedMul () override
void DoUpdate (int dt) override
Private Attributes
array< IEffect@> m_effects
int m_duration
int m_freq
int m_durationC
int m_freqC
Detailed Description
Definition at line 3 of file Whirlwind.as.
Constructor & Destructor Documentation
Whirlwind()
Skills::Whirlwind::Whirlwind (UnitPtr unit, SValue & params) inline private
Definition at line 12 of file Whirlwind.as.
References LoadEffects(), m_duration, m_effects, m_freq, and unit.
         {
             super(unit, params);
             @m_effects = LoadEffects(unit, params);
             m_duration = GetParamInt(unit, params, "duration");
             m_freq = GetParamInt(unit, params, "freq");
         }
Member Function Documentation
DoActivate()
void Skills::Whirlwind::DoActivate (SValueBuilder@ builder, vec2 target) inline override private
Definition at line 34 of file Whirlwind.as.
References StartWhirl().
         {
             StartWhirl(false);
         }
DoUpdate()
void Skills::Whirlwind::DoUpdate (int dt) inline override private
Definition at line 58 of file Whirlwind.as.
References ApplyEffects(), m_durationC, m_effects, m_freq, m_freqC, Skills::m_owner, and xy().
         {
             if (m_durationC <= 0)
                 return;
             m_durationC -= dt;
             m_freqC -= dt;
             if (m_freqC <= 0)
             {
                 m_freqC += m_freq;
                 vec2 pos = xy(m_owner.m_unit.GetPosition());
                 ApplyEffects(m_effects, m_owner, UnitPtr(), pos, vec2(1,0), 1.0, m_owner.IsHusk(), 1, 1);
             }
         }
GetMoveSpeedMul()
float Skills::Whirlwind::GetMoveSpeedMul () inline override private
Definition at line 56 of file Whirlwind.as.
References m_durationC, and Skills::ActiveSkill::m_speedMul.
 { return m_durationC <= 0 ? 1.0 : m_speedMul; }
GetTargetingMode()
TargetingMode Skills::Whirlwind::GetTargetingMode (int &out size) inline override private
Definition at line 28 of file Whirlwind.as.
References Skills::Direction.
         {
             size = 0;
             return TargetingMode::Direction;
         }
Initialize()
void Skills::Whirlwind::Initialize (Actor@ owner, ScriptSprite@ icon, uint id) inline override private
Definition at line 22 of file Whirlwind.as.
References icon, Initialize(), m_effects, and PropagateWeaponInformation().
         {
             ActiveSkill::Initialize(owner, icon, id);
             PropagateWeaponInformation(m_effects, id + 1);
         }
NetDoActivate()
void Skills::Whirlwind::NetDoActivate (SValue@ param, vec2 target) inline override private
Definition at line 39 of file Whirlwind.as.
References StartWhirl().
         {
             StartWhirl(true);
         }
StartWhirl()
void Skills::Whirlwind::StartWhirl (bool husk) inline private
Definition at line 44 of file Whirlwind.as.
References Skills::ActiveSkill::m_animCountdown, Skills::ActiveSkill::m_castpoint, m_duration, m_durationC, m_freq, m_freqC, and Skills::ActiveSkill::PlaySkillEffect().
Referenced by DoActivate(), and NetDoActivate().
         {
             if (m_durationC > 0)
                 return;
             m_durationC = m_duration;
             m_freqC = m_freq;
             m_animCountdown = m_duration - m_castpoint;
             PlaySkillEffect(vec2(1,0));
         }
Member Data Documentation
m_duration
int Skills::Whirlwind::m_duration private
Definition at line 7 of file Whirlwind.as.
Referenced by StartWhirl(), and Whirlwind().
m_durationC
int Skills::Whirlwind::m_durationC private
Definition at line 9 of file Whirlwind.as.
Referenced by DoUpdate(), GetMoveSpeedMul(), and StartWhirl().
m_effects
array<IEffect@> Skills::Whirlwind::m_effects private
Definition at line 5 of file Whirlwind.as.
Referenced by DoUpdate(), Initialize(), and Whirlwind().
m_freq
int Skills::Whirlwind::m_freq private
Definition at line 8 of file Whirlwind.as.
Referenced by DoUpdate(), StartWhirl(), and Whirlwind().
m_freqC
int Skills::Whirlwind::m_freqC private
Definition at line 10 of file Whirlwind.as.
Referenced by DoUpdate(), and StartWhirl().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Skills/Whirlwind.as