HoHDocs: BossVampireMovement Class Reference
BossVampireMovement Class Reference
Private Member Functions
BossVampireMovement (UnitPtr unit, SValue &params)
void Initialize (UnitPtr unit, CompositeActorBehavior &behavior) override
SValue Save () override
void Load (SValue@ sval) override
void PostLoad (SValue@ sval) override
WorldScript::BossLichNode FindNewNode ()
void SetTargetNode (WorldScript::BossLichNode@ node, int waitTime=-1)
void NetOnNodeArrived ()
void OnNodeArrived ()
void DoCasting (int dt)
void DoWalkPaths (int dt)
void Update (int dt, bool isCasting) override
Private Attributes
BossVampire m_vampire
AnimString m_idleAnim
AnimString m_walkAnim
float m_speed
float m_speedRoam
WorldScript::BossLichNode m_nodeTarget
WorldScript::BossLichNode m_nodeLastVisited
int m_nodeWaitTime
int m_nodeWaitTimeRandom
int m_nodeWaitTimeC
int m_centerCount
int m_centerCountC
bool m_isTransformed
UnitScene m_effectTransform
Detailed Description
Definition at line 3 of file BossVampireMovement.as.
Constructor & Destructor Documentation
BossVampireMovement()
BossVampireMovement::BossVampireMovement (UnitPtr unit, SValue & params) inline private
Definition at line 26 of file BossVampireMovement.as.
References Fountain::GetEffect(), m_centerCount, m_effectTransform, m_idleAnim, m_nodeWaitTime, m_nodeWaitTimeRandom, m_speed, m_speedRoam, m_walkAnim, and unit.
     {
         super(unit, params);
         @m_idleAnim = AnimString(GetParamString(unit, params, "anim-idle"));
         @m_walkAnim = AnimString(GetParamString(unit, params, "anim-walk"));
         m_speed = GetParamFloat(unit, params, "speed");
         m_speedRoam = GetParamFloat(unit, params, "speed-roam", false, m_speed);
         m_nodeWaitTime = GetParamInt(unit, params, "node-wait-time", false, 2000);
         m_nodeWaitTimeRandom = GetParamInt(unit, params, "node-wait-time-random", false, 2000);
         //m_nodeWaitTimeC = m_nodeWaitTime + randi(m_nodeWaitTimeRandom);
         m_centerCount = GetParamInt(unit, params, "center-count", false, 4);
         @m_effectTransform = Resources::GetEffect(GetParamString(unit, params, "transform-fx", false));
     }
Member Function Documentation
DoCasting()
void BossVampireMovement::DoCasting (int dt) inline private
Definition at line 180 of file BossVampireMovement.as.
References ActorMovement::m_behavior, m_effectTransform, m_isTransformed, ActorMovement::m_unit, and PlayEffect().
Referenced by Update().
     {
         if (m_behavior.m_target is null)
             return;
         // vec3 posTarget = m_behavior.m_target.m_unit.GetPosition();
         // vec3 posMe = m_unit.GetPosition();
         if (m_isTransformed)
         {
             PlayEffect(m_effectTransform, m_unit.GetPosition());
             m_isTransformed = false;
         }
         m_unit.GetPhysicsBody().SetStatic(true);
         m_behavior.m_frozen = false;
     }
DoWalkPaths()
void BossVampireMovement::DoWalkPaths (int dt) inline private
Definition at line 198 of file BossVampireMovement.as.
References FindNewNode(), AnimString::GetSceneName(), ActorMovement::m_behavior, m_effectTransform, m_idleAnim, m_isTransformed, m_nodeTarget, BossVampire::m_roamingC, m_speed, m_speedRoam, ActorMovement::m_unit, m_vampire, m_walkAnim, OnNodeArrived(), PlayEffect(), WorldScript::BossLichNode::Position, SetTargetNode(), and xy().
Referenced by Update().
     {
         auto body = m_unit.GetPhysicsBody();
         if (length(body.GetLinearVelocity()) > 0.5f)
             m_unit.SetUnitScene(m_walkAnim.GetSceneName(m_dir), false);
         else
             m_unit.SetUnitScene(m_idleAnim.GetSceneName(m_dir), false);
         if (!m_isTransformed)
         {
             PlayEffect(m_effectTransform, m_unit.GetPosition());
             m_isTransformed = true;
         }
         body.SetStatic(false);
         m_behavior.m_frozen = true;
         if (Network::IsServer())
         {
             if (m_nodeTarget is null)
                 SetTargetNode(FindNewNode());
             else
             {
                 float distance = dist(m_unit.GetPosition(), m_nodeTarget.Position);
                 float moveDot = dot(normalize(m_nodeTarget.Position - m_unit.GetPosition()), vec3(cos(m_dir), sin(m_dir), 0));
                 if (distance < 5.0f || (distance < 32.0f && moveDot < 0.0f))
                     OnNodeArrived();
             }
         }
         if (m_nodeTarget !is null)
         {
             vec2 dir = xy(normalize(m_nodeTarget.Position - m_unit.GetPosition()));
             if (m_vampire.m_roamingC > 0)
                 dir *= m_speedRoam;
             else
                 dir *= m_speed;
             body.SetLinearVelocity(dir);
             m_dir = atan(dir.y, dir.x);
         }
     }
FindNewNode()
WorldScript::BossLichNode BossVampireMovement::FindNewNode () inline private
Definition at line 96 of file BossVampireMovement.as.
References g_lichNodes, g_vampireCenterNode, m_centerCount, m_centerCountC, m_nodeLastVisited, m_nodeTarget, BossVampire::m_roamingC, m_vampire, and WorldScript::BossLichNode::PickNextNode().
Referenced by DoWalkPaths(), Initialize(), and OnNodeArrived().
     {
         if (!Network::IsServer())
         {
             PrintError("Clients can't find new BossLichNode!");
             return null;
         }
         if (m_vampire.m_roamingC <= 0 && ++m_centerCountC >= m_centerCount)
         {
             m_centerCountC = 0;
             return g_vampireCenterNode;
         }
         if (m_nodeTarget !is null)
         {
             WorldScript::BossLichNode@ newTarget;
             int picks = 0;
             do {
                 @newTarget = m_nodeTarget.PickNextNode();
             } while (newTarget is m_nodeLastVisited || ++picks > 3);
             return newTarget;
         }
         return g_lichNodes[randi(g_lichNodes.length())];
     }
Initialize()
void BossVampireMovement::Initialize (UnitPtr unit, CompositeActorBehavior & behavior) inline override private
Definition at line 45 of file BossVampireMovement.as.
References FindNewNode(), g_lichNodes, AnimString::GetSceneName(), Initialize(), m_idleAnim, ActorMovement::m_unit, m_vampire, SetTargetNode(), and unit.
     {
         ActorMovement::Initialize(unit, behavior);
         @m_vampire = cast<BossVampire>(behavior);
         m_unit.SetUnitScene(m_idleAnim.GetSceneName(m_dir), false);
         if (Network::IsServer() && g_lichNodes.length() > 0)
             SetTargetNode(FindNewNode(), 0);
     }
Load()
void BossVampireMovement::Load (SValue@ sval) inline override private
Definition at line 79 of file BossVampireMovement.as.
References m_centerCountC, m_isTransformed, and m_nodeWaitTimeC.
     {
         m_nodeWaitTimeC = GetParamInt(UnitPtr(), sval, "node-wait-time", false, m_nodeWaitTimeC);
         m_centerCountC = GetParamInt(UnitPtr(), sval, "center-count", false, m_centerCountC);
         m_isTransformed = GetParamBool(UnitPtr(), sval, "is-transformed", false, m_isTransformed);
     }
NetOnNodeArrived()
void BossVampireMovement::NetOnNodeArrived () inline private
Definition at line 143 of file BossVampireMovement.as.
References AnimString::GetSceneName(), ActorMovement::m_behavior, m_idleAnim, ActorMovement::m_unit, m_vampire, BossVampire::NetOnNodeArrived(), and xy().
Referenced by OnNodeArrived().
     {
         float dir = m_dir;
         if (m_behavior.m_target !is null)
         {
             vec2 vdir = normalize(xy(m_behavior.m_target.m_unit.GetPosition() - m_behavior.m_unit.GetPosition()));
             dir = atan(vdir.y, vdir.x);
         }
         m_unit.SetUnitScene(m_idleAnim.GetSceneName(dir), false);
         m_unit.GetPhysicsBody().SetLinearVelocity(vec2());
         m_vampire.NetOnNodeArrived();
     }
OnNodeArrived()
void BossVampireMovement::OnNodeArrived () inline private
Definition at line 157 of file BossVampireMovement.as.
References FindNewNode(), g_flags, g_scene, g_vampireCenterNode, Level, m_nodeTarget, BossVampire::m_roamingC, ActorMovement::m_unit, m_vampire, NetOnNodeArrived(), BossVampire::OnNodeArrived(), and SetTargetNode().
Referenced by DoWalkPaths().
     {
         (Network::Message("VampireNodeArrived") << m_unit).SendToAll();
         NetOnNodeArrived();
         m_vampire.OnNodeArrived();
         if (m_vampire.m_roamingC <= 0)
         {
             if (m_nodeTarget is g_vampireCenterNode)
                 g_flags.Set("vampire_middle", FlagState::Level);
             else
                 g_flags.Delete("vampire_middle");
         }
         auto ws = WorldScript::GetWorldScript(g_scene, m_nodeTarget);
         if (ws !is null)
             ws.Execute();
         SetTargetNode(FindNewNode());
     }
PostLoad()
void BossVampireMovement::PostLoad (SValue@ sval) inline override private
Definition at line 87 of file BossVampireMovement.as.
References g_scene, m_nodeLastVisited, and m_nodeTarget.
     {
         UnitPtr unitTarget = g_scene.GetUnit(GetParamInt(UnitPtr(), sval, "node-target", false));
         @m_nodeTarget = cast<WorldScript::BossLichNode>(unitTarget.GetScriptBehavior());
         UnitPtr unitLastVisited = g_scene.GetUnit(GetParamInt(UnitPtr(), sval, "node-target", false));
         @m_nodeLastVisited = cast<WorldScript::BossLichNode>(unitLastVisited.GetScriptBehavior());
     }
Save()
SValue BossVampireMovement::Save () inline override private
Definition at line 57 of file BossVampireMovement.as.
References g_scene, m_centerCountC, m_isTransformed, m_nodeLastVisited, m_nodeTarget, and m_nodeWaitTimeC.
     {
         SValueBuilder builder;
         builder.PushDictionary();
         auto wsTarget = WorldScript::GetWorldScript(g_scene, m_nodeTarget);
         if (wsTarget !is null)
             builder.PushInteger("node-target", wsTarget.GetUnit().GetId());
         auto wsLastVisited = WorldScript::GetWorldScript(g_scene, m_nodeLastVisited);
         if (wsLastVisited !is null)
             builder.PushInteger("node-last-visited", wsLastVisited.GetUnit().GetId());
         builder.PushInteger("node-wait-time", m_nodeWaitTimeC);
         builder.PushInteger("center-count", m_centerCountC);
         builder.PushBoolean("is-transformed", m_isTransformed);
         builder.PopDictionary();
         return builder.Build();
     }
SetTargetNode()
void BossVampireMovement::SetTargetNode (WorldScript::BossLichNode@ node, int waitTime = -1) inline private
Definition at line 123 of file BossVampireMovement.as.
References g_flags, g_scene, g_vampireCenterNode, m_nodeLastVisited, m_nodeTarget, m_nodeWaitTime, m_nodeWaitTimeC, m_nodeWaitTimeRandom, and ActorMovement::m_unit.
Referenced by DoWalkPaths(), Initialize(), and OnNodeArrived().
     {
         @m_nodeLastVisited = m_nodeTarget;
         @m_nodeTarget = node;
         if (node is g_vampireCenterNode)
             g_flags.Delete("thrall_res");
         if (waitTime == -1)
             m_nodeWaitTimeC = m_nodeWaitTime + randi(m_nodeWaitTimeRandom);
         else
             m_nodeWaitTimeC = waitTime;
         if (Network::IsServer())
         {
             auto script = WorldScript::GetWorldScript(g_scene, node);
             (Network::Message("UnitMovementBossVampireTarget") << m_unit << script.GetUnit() << m_nodeWaitTimeC).SendToAll();
         }
     }
Update()
void BossVampireMovement::Update (int dt, bool isCasting) inline override private
Definition at line 245 of file BossVampireMovement.as.
References DoCasting(), DoWalkPaths(), ActorMovement::m_enabled, m_nodeWaitTimeC, BossVampire::m_roamingC, m_vampire, and Update().
     {
         if (!m_enabled)
             return;
         ActorMovement::Update(dt, isCasting);
         if (m_nodeWaitTimeC > 0)
             m_nodeWaitTimeC -= dt;
         if ((isCasting || m_nodeWaitTimeC > 0) && m_vampire.m_roamingC <= 0)
             DoCasting(dt);
         else
             DoWalkPaths(dt);
     }
Member Data Documentation
m_centerCount
int BossVampireMovement::m_centerCount private
Definition at line 20 of file BossVampireMovement.as.
Referenced by BossVampireMovement(), and FindNewNode().
m_centerCountC
int BossVampireMovement::m_centerCountC private
Definition at line 21 of file BossVampireMovement.as.
Referenced by FindNewNode(), Load(), and Save().
m_effectTransform
UnitScene BossVampireMovement::m_effectTransform private
Definition at line 24 of file BossVampireMovement.as.
Referenced by BossVampireMovement(), DoCasting(), and DoWalkPaths().
m_idleAnim
AnimString BossVampireMovement::m_idleAnim private
Definition at line 7 of file BossVampireMovement.as.
Referenced by BossVampireMovement(), DoWalkPaths(), Initialize(), and NetOnNodeArrived().
m_isTransformed
bool BossVampireMovement::m_isTransformed private
Definition at line 23 of file BossVampireMovement.as.
Referenced by DoCasting(), DoWalkPaths(), Load(), and Save().
m_nodeLastVisited
WorldScript::BossLichNode BossVampireMovement::m_nodeLastVisited private
Definition at line 14 of file BossVampireMovement.as.
Referenced by FindNewNode(), PostLoad(), Save(), and SetTargetNode().
m_nodeTarget
WorldScript::BossLichNode BossVampireMovement::m_nodeTarget private
Definition at line 13 of file BossVampireMovement.as.
Referenced by DoWalkPaths(), FindNewNode(), OnNodeArrived(), PostLoad(), Save(), and SetTargetNode().
m_nodeWaitTime
int BossVampireMovement::m_nodeWaitTime private
Definition at line 16 of file BossVampireMovement.as.
Referenced by BossVampireMovement(), and SetTargetNode().
m_nodeWaitTimeC
int BossVampireMovement::m_nodeWaitTimeC private
Definition at line 18 of file BossVampireMovement.as.
Referenced by Load(), Save(), SetTargetNode(), and Update().
m_nodeWaitTimeRandom
int BossVampireMovement::m_nodeWaitTimeRandom private
Definition at line 17 of file BossVampireMovement.as.
Referenced by BossVampireMovement(), and SetTargetNode().
m_speed
float BossVampireMovement::m_speed private
Definition at line 10 of file BossVampireMovement.as.
Referenced by BossVampireMovement(), and DoWalkPaths().
m_speedRoam
float BossVampireMovement::m_speedRoam private
Definition at line 11 of file BossVampireMovement.as.
Referenced by BossVampireMovement(), and DoWalkPaths().
m_vampire
BossVampire BossVampireMovement::m_vampire private
Definition at line 5 of file BossVampireMovement.as.
Referenced by DoWalkPaths(), FindNewNode(), Initialize(), NetOnNodeArrived(), OnNodeArrived(), and Update().
m_walkAnim
AnimString BossVampireMovement::m_walkAnim private
Definition at line 8 of file BossVampireMovement.as.
Referenced by BossVampireMovement(), and DoWalkPaths().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Enemies/Movements/BossVampireMovement.as