HoHDocs: MenuControlInputWidget Class Reference
MenuControlInputWidget Class Reference
Private Member Functions
MenuControlInputWidget ()
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
bool OnClick (vec2 mousePos) override
void Clear ()
array< ControlMapBinding@> GetBindings ()
void ExpectedInput (ControllerType type, int key)
void UpdateText ()
Private Attributes
ControlMap m_map
bool m_waitingForInput
bool m_axisAction
ControlBindingSetAxis m_axisSet
Detailed Description
Definition at line 1 of file MenuControlInput.as.
Constructor & Destructor Documentation
MenuControlInputWidget()
MenuControlInputWidget::MenuControlInputWidget () inline private
Definition at line 9 of file MenuControlInput.as.
Referenced by Clone().
     {
         super();
     }
Member Function Documentation
Clear()
void MenuControlInputWidget::Clear () inline private
Definition at line 59 of file MenuControlInput.as.
References GetBindings(), m_map, and ControlMap::RemoveStaging().
Referenced by ExpectedInput().
     {
         array<ControlMapBinding@> existingBindings = GetBindings();
         for (uint i = 0; i < existingBindings.length(); i++)
             m_map.RemoveStaging(existingBindings[i]);
     }
Clone()
Widget MenuControlInputWidget::Clone () inline override private
Definition at line 14 of file MenuControlInput.as.
References Widget::CloneInto(), and MenuControlInputWidget().
     {
         MenuControlInputWidget@ w = MenuControlInputWidget();
         CloneInto(w);
         return w;
     }
ExpectedInput()
void MenuControlInputWidget::ExpectedInput (ControllerType type, int key) inline private
Definition at line 85 of file MenuControlInput.as.
References ControlMap::AddStaging(), ControlMap::AddStagingAxis(), Clear(), ControlMap::Gamepad, GetBindings(), ControlMap::Joystick, Keyboard, m_axisAction, m_axisSet, ButtonWidget::m_func, m_map, Mouse, MouseWheel, ControlMap::RemoveStaging(), type, and UpdateText().
     {
         if (type == ControllerType::Keyboard && (key == 42)) // Backspace
         {
             Clear();
             UpdateText();
             return;
         }
         bool isControllerMap = (m_map.Gamepad || m_map.Joystick);
         bool isControllerInput = (type != ControllerType::Keyboard && type != ControllerType::Mouse && type != ControllerType::MouseWheel);
         if (isControllerMap != isControllerInput)
         {
             // Oops, this controller type is restricted in this mapping
             UpdateText();
             return;
         }
         array<ControlMapBinding@> existingBindings = GetBindings();
         if (existingBindings.length() >= 2)
         {
             for (uint i = 0; i < existingBindings.length(); i++)
                 m_map.RemoveStaging(existingBindings[i]);
         }
         if (m_axisAction)
             m_map.AddStagingAxis(type, key, m_func, m_axisSet);
         else
             m_map.AddStaging(type, key, m_func);
         UpdateText();
     }
GetBindings()
array<ControlMapBinding@> MenuControlInputWidget::GetBindings () inline private
Definition at line 66 of file MenuControlInput.as.
References ControlMap::GetStaging(), m_axisAction, m_axisSet, ButtonWidget::m_func, and m_map.
Referenced by Clear(), and ExpectedInput().
     {
         array<ControlMapBinding@> ret;
         array<ControlMapBinding@>@ mapBindings = m_map.GetStaging();
         for (uint i = 0; i < mapBindings.length(); i++)
         {
             ControlMapBinding@ bind = mapBindings[i];
             if (bind.Action == m_func)
             {
                 if (m_axisAction && m_axisSet != bind.SetAxis)
                     continue;
                 ret.insertLast(bind);
             }
         }
         return ret;
     }
Load()
void MenuControlInputWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 21 of file MenuControlInput.as.
References Widget::Load(), RectWidget::m_borderColor, RectWidget::m_borderWidth, Widget::m_canFocus, ButtonWidget::m_textColor, ButtonWidget::m_textColorHover, and ButtonWidget::SetColor().
Referenced by LoadMenuControlInput().
     {
         ButtonWidget::Load(ctx);
         m_borderColor = ctx.GetColorRGBA("border", false, vec4(0, 0, 0, 0));
         m_borderWidth = ctx.GetInteger("borderwidth", false, 1);
         m_canFocus = true;
         m_textColor = vec4(1, 0.753, 0, 1);
         m_textColorHover = vec4(1, 1, 1, 1);
         SetColor(m_textColor);
     }
OnClick()
bool MenuControlInputWidget::OnClick (vec2 mousePos) inline override private
Definition at line 35 of file MenuControlInput.as.
References g_gameMode, GetControlBindings(), RectWidget::m_color, ButtonWidget::m_func, ButtonWidget::m_pressSound, Widget::OnClick(), and PlaySound2D().
     {
         if (m_func == "")
             return false;
         auto cb = GetControlBindings();
         if (cb !is null)
         {
             auto gm = cast<MainMenu>(g_gameMode);
             if (gm !is null)
             {
                 @gm.m_expectingInput = this;
                 cb.ExpectInput();
             }
         }
         m_color = vec4(1, 1, 0, 0.25);
         PlaySound2D(m_pressSound);
         RectWidget::OnClick(mousePos);
         return true;
     }
UpdateText()
void MenuControlInputWidget::UpdateText () inline private
Definition at line 118 of file MenuControlInput.as.
Referenced by Menu::ControlMapMenu::AddNewControl(), Menu::ControlMapMenu::AddNewControlAxis(), ExpectedInput(), and Menu::ControlMapMenu::OnFunc().
     {
         m_color = vec4(0, 0, 0, 0);
         string text = "";
         array<ControlMapBinding@> bindings = GetBindings();
         for (uint i = 0; i < bindings.length(); i++)
         {
             if (text != "")
                 text += ", ";
             string keyID = bindings[i].ID.toUpper();
             keyID = keyID.replace("_", " ");
             text += keyID;
         }
         if (text == "")
             text = Resources::GetString(".menu.none");
         SetText(text);
     }
Member Data Documentation
m_axisAction
bool MenuControlInputWidget::m_axisAction private
Definition at line 6 of file MenuControlInput.as.
Referenced by Menu::ControlMapMenu::AddNewControlAxis(), ExpectedInput(), and GetBindings().
m_axisSet
ControlBindingSetAxis MenuControlInputWidget::m_axisSet private
Definition at line 7 of file MenuControlInput.as.
Referenced by Menu::ControlMapMenu::AddNewControlAxis(), ExpectedInput(), and GetBindings().
m_map
ControlMap MenuControlInputWidget::m_map private
Definition at line 3 of file MenuControlInput.as.
Referenced by Menu::ControlMapMenu::AddNewControl(), Clear(), ExpectedInput(), and GetBindings().
m_waitingForInput
bool MenuControlInputWidget::m_waitingForInput private
Definition at line 4 of file MenuControlInput.as.
The documentation for this class was generated from the following file:
scripts/GUI/MenuControlInput.as