HoHDocs: OverheadBossBar Class Reference
OverheadBossBar Class Reference
Private Member Functions
void Set (Actor@ actor, int barCount, int barOffset, string name)
bool Draw (SpriteBatch &sb, int idt)
Private Attributes
Actor m_actor
float m_checkpoint = -1
int m_barCount
int m_barOffset
BitmapString m_text
Detailed Description
Definition at line 1 of file OverheadBossBar.as.
Member Function Documentation
Draw()
bool OverheadBossBar::Draw (SpriteBatch & sb, int idt) inline private
Definition at line 23 of file OverheadBossBar.as.
References g_gameMode, Actor::GetHealth(), Actor::IsDead(), lerp(), m_actor, m_barCount, m_barOffset, Actor::m_unit, AGameMode::m_wndScale, and ToScreenspace().
     {
         Actor@ a = m_actor;
         if (!a.m_unit.IsValid() || a.IsDead())
             return false;
         int barWidthPixels = m_barCount;
         int barHeight = 4;
         vec2 pos = ToScreenspace(a.m_unit.GetInterpolatedPosition(idt)) / g_gameMode.m_wndScale;
         pos += vec2(-(barWidthPixels) / 2, m_barOffset);
         float hp = a.GetHealth();
         vec4 fillRect = vec4(pos.x, pos.y, barWidthPixels, barHeight);
         sb.FillRectangle(fillRect, vec4(0, 0, 0, 1));
         vec4 barRect = fillRect;
         barRect.x += 1;
         barRect.y += 1;
         barRect.z -= 2;
         barRect.w -= 2;
         barRect.z *= hp;
         vec4 colorBar = lerp(vec4(1, 0, 0, 1), vec4(0, 1, 0, 1), hp);
         sb.FillRectangle(barRect, colorBar);
         return true;
     }
Set()
void OverheadBossBar::Set (Actor@ actor, int barCount, int barOffset, string name) inline private
Definition at line 12 of file OverheadBossBar.as.
References m_actor, m_barCount, m_barOffset, m_text, and name.
Referenced by BaseGameMode::AddBossBarActor().
     {
         BitmapFont@ font = Resources::GetBitmapFont("gui/fonts/font_hw8.fnt");
         @m_actor = actor;
         m_barCount = barCount;
         m_barOffset = barOffset;
         if (font !is null)
             @m_text = font.BuildText(Resources::GetString(name));
     }
Member Data Documentation
m_actor
Actor OverheadBossBar::m_actor private
Definition at line 3 of file OverheadBossBar.as.
Referenced by Draw(), BaseGameMode::GetBossBarActor(), and Set().
m_barCount
int OverheadBossBar::m_barCount private
Definition at line 7 of file OverheadBossBar.as.
Referenced by Draw(), and Set().
m_barOffset
int OverheadBossBar::m_barOffset private
Definition at line 8 of file OverheadBossBar.as.
Referenced by Draw(), and Set().
m_checkpoint
float OverheadBossBar::m_checkpoint = -1 private
Definition at line 5 of file OverheadBossBar.as.
Referenced by WorldScript::BossBarCheckpoint::ServerExecute().
m_text
BitmapString OverheadBossBar::m_text private
Definition at line 10 of file OverheadBossBar.as.
Referenced by Set().
The documentation for this class was generated from the following file:
scripts/GUI/HUD/OverheadBossBar.as