HoHDocs: WorldScript::UnitDestroyedTrigger Class Reference
WorldScript::UnitDestroyedTrigger Class Reference
Private Member Functions
bool IsValid (UnitPtr unit)
void OnChanged (array< UnitPtr >@ added, array< UnitPtr >@ removed)
void UnitDestroyed (UnitPtr unit, SValue &arg)
SValue ServerExecute ()
Private Attributes
UnitFeed Units
UnitSource Instigator
UnitCallbackList m_callbacks
Detailed Description
Definition at line 4 of file UnitDestroyedTrigger.as.
Member Function Documentation
IsValid()
bool WorldScript::UnitDestroyedTrigger::IsValid (UnitPtr unit) inline private
Definition at line 14 of file UnitDestroyedTrigger.as.
References unit.
         {
             return WorldScript::GetWorldScript(unit) is null;
         }
OnChanged()
void WorldScript::UnitDestroyedTrigger::OnChanged (array< UnitPtr >@ added, array< UnitPtr >@ removed) inline private
Definition at line 19 of file UnitDestroyedTrigger.as.
References Destroyed(), m_callbacks, WorldScript::UnitCallbackList::RegisterEventCallback(), and WorldScript::UnitCallbackList::UnregisterEventCallback().
         {
             if (!Network::IsServer())
                 return;
             if (added !is null)
                 for (uint i = 0; i < added.length(); i++)
                     m_callbacks.RegisterEventCallback(added[i], UnitEventType::Destroyed, this, "UnitDestroyed");
             if (removed !is null)
                 for (uint i = 0; i < removed.length(); i++)
                     m_callbacks.UnregisterEventCallback(removed[i]);
         }
ServerExecute()
SValue WorldScript::UnitDestroyedTrigger::ServerExecute () inline private
Definition at line 40 of file UnitDestroyedTrigger.as.
         {
             return null;
         }
UnitDestroyed()
void WorldScript::UnitDestroyedTrigger::UnitDestroyed (UnitPtr unit, SValue & arg) inline private
Definition at line 33 of file UnitDestroyedTrigger.as.
References g_scene, Instigator, and unit.
         {
             Instigator.Replace(unit);
             WorldScript::GetWorldScript(g_scene, this).Execute();
             Instigator.Clear();
         }
Member Data Documentation
Instigator
UnitSource WorldScript::UnitDestroyedTrigger::Instigator private
Definition at line 9 of file UnitDestroyedTrigger.as.
Referenced by UnitDestroyed().
m_callbacks
UnitCallbackList WorldScript::UnitDestroyedTrigger::m_callbacks private
Definition at line 11 of file UnitDestroyedTrigger.as.
Referenced by OnChanged().
Units
UnitFeed WorldScript::UnitDestroyedTrigger::Units private
Definition at line 7 of file UnitDestroyedTrigger.as.
The documentation for this class was generated from the following file:
scripts/WorldScript/UnitDestroyedTrigger.as