HoHDocs: BombBehavior Class Reference
BombBehavior Class Reference
Private Member Functions
BombBehavior (UnitPtr unit, SValue &params)
bool IsTargetable () override
void Initialize (Actor@ owner, float intensity, bool husk)
SValue Save ()
void PostLoad (SValue@ data)
Actor GetOwner ()
void OnSpawn ()
void NetDoExplode (SValue@ param)
void DoExplode ()
void Update (int dt)
Private Attributes
Actor m_owner
int m_delayC
int m_delay
int m_delayRandom
bool m_exploded
bool m_spawned
SoundEvent m_spawnSound
SoundEvent m_explodeSound
GoreSpawner m_gore
array< IAction@> m_actions
EffectParams m_effectParams
Detailed Description
Definition at line 1 of file BombBehavior.as.
Constructor & Destructor Documentation
BombBehavior()
BombBehavior::BombBehavior (UnitPtr unit, SValue & params) inline private
Definition at line 20 of file BombBehavior.as.
References IsNetsyncedExistance(), LoadActions(), LoadEffectParams(), LoadGore(), m_actions, m_delay, m_delayC, m_delayRandom, m_effectParams, m_exploded, m_explodeSound, m_gore, m_spawnSound, Actor::m_unit, Actor::Team, and unit.
     {
         super(unit);
         Team = HashString(GetParamString(unit, params, "team", false, "enemy"));
         m_delay = GetParamInt(unit, params, "delay");
         m_delayRandom = GetParamInt(unit, params, "delay-random", false);
         m_delayC = m_delay + randi(m_delayRandom);
         @m_spawnSound = Resources::GetSoundEvent(GetParamString(unit, params, "spawn-sound", false));
         @m_explodeSound = Resources::GetSoundEvent(GetParamString(unit, params, "explode-sound", false));
         @m_gore = LoadGore(GetParamString(unit, params, "gore", false));
         @m_actions = LoadActions(unit, params);
         m_exploded = false;
         @m_effectParams = LoadEffectParams(unit, params);
         if (!IsNetsyncedExistance(m_unit.GetUnitProducer().GetNetSyncMode()))
             PrintError("Non-netsynced BombBehavior is not supported!");
     }
Member Function Documentation
DoExplode()
void BombBehavior::DoExplode () inline private
Definition at line 106 of file BombBehavior.as.
References DoActions(), GetOwner(), m_actions, m_exploded, m_explodeSound, m_gore, Actor::m_unit, PlaySound3D(), and xy().
Referenced by Update().
     {
         if (m_exploded)
             return;
         m_exploded = true;
         if (m_explodeSound !is null)
             PlaySound3D(m_explodeSound, m_unit.GetPosition());
         if (m_gore !is null)
             m_gore.OnDeath(1.0f, xy(m_unit.GetPosition()), 0.0f);
         SValue@ param = DoActions(m_actions, GetOwner(), null, xy(m_unit.GetPosition()), vec2());
         if (Network::IsServer())
         {
             (Network::Message("UnitBombExploded") << m_unit << param).SendToAll();
             m_unit.Destroy();
         }
     }
GetOwner()
Actor BombBehavior::GetOwner () inline private
Definition at line 81 of file BombBehavior.as.
References m_owner.
Referenced by DoExplode(), and NetDoExplode().
     {
         if (m_owner !is null)
             return m_owner;
         return this;
     }
Initialize()
void BombBehavior::Initialize (Actor@ owner, float intensity, bool husk) inline private
Definition at line 45 of file BombBehavior.as.
References m_owner.
     {
         @m_owner = owner;
     }
IsTargetable()
bool BombBehavior::IsTargetable () inline override private
Definition at line 43 of file BombBehavior.as.
 { return false; }
NetDoExplode()
void BombBehavior::NetDoExplode (SValue@ param) inline private
Definition at line 95 of file BombBehavior.as.
References GetOwner(), m_actions, m_explodeSound, m_gore, Actor::m_unit, NetDoActions(), PlaySound3D(), and xy().
     {
         if (m_explodeSound !is null)
             PlaySound3D(m_explodeSound, m_unit.GetPosition());
         if (m_gore !is null)
             m_gore.OnDeath(1.0f, xy(m_unit.GetPosition()), 0.0f);
         NetDoActions(m_actions, param, GetOwner(), xy(m_unit.GetPosition()), vec2());
     }
OnSpawn()
void BombBehavior::OnSpawn () inline private
Definition at line 89 of file BombBehavior.as.
References m_spawnSound, Actor::m_unit, and PlaySound3D().
Referenced by Update().
     {
         if (m_spawnSound !is null)
             PlaySound3D(m_spawnSound, m_unit.GetPosition());
     }
PostLoad()
void BombBehavior::PostLoad (SValue@ data) inline private
Definition at line 63 of file BombBehavior.as.
References g_scene, m_delayC, m_owner, and m_spawned.
     {
         m_spawned = true;
         auto ttl = data.GetDictionaryEntry("ttl");
         if (ttl !is null && ttl.GetType() == SValueType::Integer)
             m_delayC = ttl.GetInteger();
         auto owner = data.GetDictionaryEntry("owner");
         if (owner !is null && owner.GetType() == SValueType::Integer)
         {
             auto ownerUnit = g_scene.GetUnit(owner.GetInteger());
             if (ownerUnit.IsValid())
                 @m_owner = cast<Actor>(ownerUnit.GetScriptBehavior());
         }
     }
Save()
SValue BombBehavior::Save () inline private
Definition at line 50 of file BombBehavior.as.
References m_delayC, m_owner, and Actor::m_unit.
     {
         SValueBuilder sval;
         sval.PushDictionary();
         sval.PushInteger("ttl", m_delayC);
         if (m_owner !is null && m_owner.m_unit.IsValid())
             sval.PushInteger("owner", m_owner.m_unit.GetId());
         return sval.Build();
     }
Update()
void BombBehavior::Update (int dt) inline private
Definition at line 128 of file BombBehavior.as.
References DoExplode(), m_delayC, m_spawned, and OnSpawn().
     {
         if (!m_spawned)
         {
             OnSpawn();
             m_spawned = true;
         }
         if (Network::IsServer())
         {
             m_delayC -= dt;
             if (m_delayC <= 0)
                 DoExplode();
         }
     }
Member Data Documentation
m_actions
array<IAction@> BombBehavior::m_actions private
Definition at line 16 of file BombBehavior.as.
Referenced by BombBehavior(), DoExplode(), and NetDoExplode().
m_delay
int BombBehavior::m_delay private
Definition at line 6 of file BombBehavior.as.
Referenced by BombBehavior().
m_delayC
int BombBehavior::m_delayC private
Definition at line 5 of file BombBehavior.as.
Referenced by BombBehavior(), PostLoad(), Save(), and Update().
m_delayRandom
int BombBehavior::m_delayRandom private
Definition at line 7 of file BombBehavior.as.
Referenced by BombBehavior().
m_effectParams
EffectParams BombBehavior::m_effectParams private
Definition at line 17 of file BombBehavior.as.
Referenced by BombBehavior().
m_exploded
bool BombBehavior::m_exploded private
Definition at line 9 of file BombBehavior.as.
Referenced by BombBehavior(), and DoExplode().
m_explodeSound
SoundEvent BombBehavior::m_explodeSound private
Definition at line 12 of file BombBehavior.as.
Referenced by BombBehavior(), DoExplode(), and NetDoExplode().
m_gore
GoreSpawner BombBehavior::m_gore private
Definition at line 14 of file BombBehavior.as.
Referenced by BombBehavior(), DoExplode(), and NetDoExplode().
m_owner
Actor BombBehavior::m_owner private
Definition at line 3 of file BombBehavior.as.
Referenced by GetOwner(), Initialize(), PostLoad(), and Save().
m_spawned
bool BombBehavior::m_spawned private
Definition at line 10 of file BombBehavior.as.
Referenced by PostLoad(), and Update().
m_spawnSound
SoundEvent BombBehavior::m_spawnSound private
Definition at line 11 of file BombBehavior.as.
Referenced by BombBehavior(), and OnSpawn().
The documentation for this class was generated from the following file:
scripts/Behaviors/BombBehavior.as