HoHDocs: Skills::Explode Class Reference
Skills::Explode Class Reference
Private Member Functions
Explode (UnitPtr unit, SValue &params)
void Initialize (Actor@ owner, ScriptSprite@ icon, uint id) override
TargetingMode GetTargetingMode (int &out size) override
bool Activate (vec2 target) override
void NetActivate (vec2 target) override
void DoTrigger (vec2 dir)
bool Trigger (vec2 dir)
bool NetTrigger (vec2 dir)
void Hold (int dt, vec2 target) override
void NetHold (int dt, vec2 target) override
void Release (vec2 target) override
void NetRelease (vec2 target) override
void DoUpdate (int dt) override
bool DoExplosion (Actor@ owner, vec2 pos, vec2 dir, float intensity, bool husk)
Private Attributes
array< IEffect@> m_effects
array< IEffect@> m_selfEffects
int m_radius
int m_minRadius
float m_distScaling
float m_selfDmg
float m_teamDmg
float m_enemyDmg
bool m_destroyProjectiles
int m_tickRate
int m_tickRateC
bool m_active
Detailed Description
Definition at line 3 of file Explode.as.
Constructor & Destructor Documentation
Explode()
Skills::Explode::Explode (UnitPtr unit, SValue & params) inline private
Definition at line 22 of file Explode.as.
References LoadEffects(), m_destroyProjectiles, m_distScaling, m_effects, m_enemyDmg, m_minRadius, m_radius, m_selfDmg, m_selfEffects, m_teamDmg, m_tickRate, and unit.
         {
             super(unit, params);
             @m_effects = LoadEffects(unit, params);
             @m_selfEffects = LoadEffects(unit, params, "self-");
             m_minRadius = GetParamInt(unit, params, "min-radius", false, 0);
             m_radius = GetParamInt(unit, params, "radius", false, m_minRadius);
             m_distScaling = GetParamFloat(unit, params, "dist-scaling", false, 3);
             m_selfDmg = GetParamFloat(unit, params, "self-dmg", false, 0);
             m_teamDmg = GetParamFloat(unit, params, "team-dmg", false, 0);
             m_enemyDmg = GetParamFloat(unit, params, "enemy-dmg", false, 1);
             m_destroyProjectiles = GetParamBool(unit, params, "destroy-projectiles", false, false);
             m_tickRate = GetParamInt(unit, params, "tick-rate", false, 0);
         }
Member Function Documentation
Activate()
bool Skills::Explode::Activate (vec2 target) inline override private
Definition at line 53 of file Explode.as.
References m_active, Skills::ActiveSkill::m_animation, Skills::ActiveSkill::m_animCountdown, Skills::ActiveSkill::m_castingC, Skills::ActiveSkill::m_castpoint, Skills::ActiveSkill::m_cooldown, Skills::ActiveSkill::m_cooldownC, Skills::m_owner, Skills::ActiveSkill::m_queuedTarget, Skills::m_skillId, m_tickRate, m_tickRateC, and Trigger().
         {
             if (m_cooldownC > 0)
             {
                 m_owner.WarnCooldown(this, m_cooldownC);
                 return false;
             }
             if (m_tickRate == 0)
             {
                 if (!Trigger(target))
                     return false;
             }
             else
                 m_tickRateC = m_tickRate;
             m_cooldownC = m_cooldown;
             m_castingC = m_castpoint;
             m_queuedTarget = target;
             m_animCountdown = m_owner.SetUnitScene(m_animation, true);
             m_active = true;
             //NOTE: We override ActiveSkill::Activate() here instead of DoActivate because we don't want to spend mana on first activation
             //      That's also why we explicitly send the network message here
             (Network::Message("PlayerActiveSkillActivate") << int(m_skillId) << target).SendToAll();
             return true;
         }
DoExplosion()
bool Skills::Explode::DoExplosion (Actor@ owner, vec2 pos, vec2 dir, float intensity, bool husk) inline private
Definition at line 161 of file Explode.as.
References ApplyEffects(), Destroy(), g_scene, m_destroyProjectiles, m_distScaling, m_effects, m_enemyDmg, m_minRadius, m_radius, m_selfDmg, m_selfEffects, m_teamDmg, Actor::m_unit, max, unit, and xy().
Referenced by DoTrigger(), and NetTrigger().
         {
             ApplyEffects(m_selfEffects, owner, owner.m_unit, pos, dir, intensity, husk);
             if (m_destroyProjectiles)
             {
                 array<UnitPtr>@ projs = g_scene.FetchUnitsWithBehavior("IProjectile", pos, m_radius, true);
                 for (uint i = 0; i < projs.length(); i++)
                 {
                     auto proj = cast<IProjectile>(projs[i].GetScriptBehavior());
                     if (proj is null)
                         continue;
                     if (proj.IsBlockable())
                         projs[i].Destroy();
                 }
             }
             array<UnitPtr>@ directHits;
             if (m_minRadius > 0)
                 @directHits = g_scene.QueryCircle(pos, m_minRadius, ~0, RaycastType::Shot, true);
             else
                 @directHits = array<UnitPtr>();
             auto results = g_scene.QueryCircle(pos, m_radius, ~0, RaycastType::Shot, true);
             for (uint i = 0; i < results.length(); i++)
             {
                 UnitPtr unit = results[i];
                 vec2 upos = xy(unit.GetPosition());
                 bool visible = true;
                 float hitDist = m_radius + 1;
                 for (uint j = 0; j < directHits.length(); j++)
                 {
                     if (results[i] == directHits[j])
                     {
                         hitDist = 0;
                         break;
                     }
                 }
                 if (hitDist > 0)
                 {
                     auto rayResults = g_scene.Raycast(pos, upos, ~0, RaycastType::Shot);
                     if (rayResults.length() <= 0)
                         hitDist = 0;
                     for (uint j = 0; j < rayResults.length(); j++)
                     {
                         UnitPtr res_unit = rayResults[j].FetchUnit(g_scene);
                         if (!res_unit.IsValid())
                             continue;
                         if (res_unit == unit)
{
                             hitDist = max(0.0, rayResults[j].fraction * length(upos - pos) - m_minRadius);
                             upos = rayResults[j].point;
                             break;
                         }
                         auto b = res_unit.GetScriptBehavior();
                         auto d = cast<IDamageTaker>(b);
                         if (d is null || d.Impenetrable())
{
                             visible = false;
                             break;
                         }
                     }
                 }
                 if (!visible)
                     continue;
                 float d = 1.0;
                 if (m_radius > m_minRadius)
                     d = max(0.0, 1.0 - pow(hitDist / (m_radius - m_minRadius), m_distScaling));
                 ApplyEffects(m_effects, owner, unit, upos, dir, intensity * d, husk, m_selfDmg, m_teamDmg, m_enemyDmg);
             }
             return true;
         }
DoTrigger()
void Skills::Explode::DoTrigger (vec2 dir) inline private
Definition at line 93 of file Explode.as.
References DoExplosion(), Skills::m_owner, m_tickRate, m_tickRateC, Skills::ActiveSkill::PlaySkillEffect(), and xy().
Referenced by Trigger().
         {
             m_tickRateC = m_tickRate;
             PlaySkillEffect(dir);
             DoExplosion(m_owner, xy(m_owner.m_unit.GetPosition()), dir, 1.0, false);
         }
DoUpdate()
void Skills::Explode::DoUpdate (int dt) inline override private
Definition at line 157 of file Explode.as.
         {
         }
GetTargetingMode()
TargetingMode Skills::Explode::GetTargetingMode (int &out size) inline override private
Definition at line 47 of file Explode.as.
References Skills::Channeling, Skills::Direction, and m_tickRate.
         {
             size = 0;
             return m_tickRate > 0 ? TargetingMode::Channeling : TargetingMode::Direction;
         }
Hold()
void Skills::Explode::Hold (int dt, vec2 target) inline override private
Definition at line 119 of file Explode.as.
References Skills::ActiveSkill::Hold(), m_active, Skills::ActiveSkill::m_animCountdown, Skills::ActiveSkill::m_castingC, Skills::ActiveSkill::m_castpoint, Skills::ActiveSkill::m_cooldown, Skills::ActiveSkill::m_cooldownC, m_tickRate, m_tickRateC, and Trigger().
         {
             if (!m_active)
                 return;
             m_animCountdown = m_tickRate;
             m_cooldownC = m_cooldown;
             m_castingC = m_castpoint;
             m_tickRateC -= dt;
             if (m_tickRateC <= 0)
                 Trigger(target);
             ActiveSkill::Hold(dt, target);
         }
Initialize()
void Skills::Explode::Initialize (Actor@ owner, ScriptSprite@ icon, uint id) inline override private
Definition at line 40 of file Explode.as.
References icon, Initialize(), m_effects, m_selfEffects, and PropagateWeaponInformation().
         {
             ActiveSkill::Initialize(owner, icon, id);
             PropagateWeaponInformation(m_effects, id + 1);
             PropagateWeaponInformation(m_selfEffects, id + 1);
         }
NetActivate()
void Skills::Explode::NetActivate (vec2 target) inline override private
Definition at line 82 of file Explode.as.
References m_active, Skills::ActiveSkill::m_animation, Skills::ActiveSkill::m_animCountdown, Skills::ActiveSkill::m_netHold, Skills::m_owner, m_tickRate, and NetTrigger().
         {
             m_animCountdown = m_owner.SetUnitScene(m_animation, true);
             m_active = true;
             if (m_tickRate == 0)
                 NetTrigger(target);
             else
                 m_netHold = true;
         }
NetHold()
void Skills::Explode::NetHold (int dt, vec2 target) inline override private
Definition at line 135 of file Explode.as.
References Skills::ActiveSkill::m_animCountdown, m_tickRate, m_tickRateC, Skills::ActiveSkill::NetHold(), and NetTrigger().
         {
             m_animCountdown = m_tickRate;
             m_tickRateC -= dt;
             if (m_tickRateC <= 0)
                 NetTrigger(target);
             ActiveSkill::NetHold(dt, target);
         }
NetRelease()
void Skills::Explode::NetRelease (vec2 target) inline override private
Definition at line 151 of file Explode.as.
References m_active, and Skills::ActiveSkill::NetRelease().
         {
             ActiveSkill::NetRelease(target);
             m_active = false;
         }
NetTrigger()
bool Skills::Explode::NetTrigger (vec2 dir) inline private
Definition at line 110 of file Explode.as.
References DoExplosion(), Skills::m_owner, m_tickRate, m_tickRateC, Skills::ActiveSkill::PlaySkillEffect(), and xy().
Referenced by NetActivate(), and NetHold().
         {
             m_tickRateC = m_tickRate;
             PlaySkillEffect(dir);
             DoExplosion(m_owner, xy(m_owner.m_unit.GetPosition()), dir, 1.0, true);
             return true;
         }
Release()
void Skills::Explode::Release (vec2 target) inline override private
Definition at line 145 of file Explode.as.
References m_active, and Skills::ActiveSkill::Release().
         {
             ActiveSkill::Release(target);
             m_active = false;
         }
Trigger()
bool Skills::Explode::Trigger (vec2 dir) inline private
Definition at line 101 of file Explode.as.
References DoTrigger(), Skills::ActiveSkill::m_costHealth, Skills::ActiveSkill::m_costMana, Skills::ActiveSkill::m_costStamina, and Skills::m_owner.
Referenced by Activate(), and Hold().
         {
             if (!m_owner.SpendCost(m_costMana, m_costStamina, m_costHealth))
                 return false;
             DoTrigger(dir);
             return true;
         }
Member Data Documentation
m_active
bool Skills::Explode::m_active private
Definition at line 19 of file Explode.as.
Referenced by Activate(), Hold(), NetActivate(), NetRelease(), and Release().
m_destroyProjectiles
bool Skills::Explode::m_destroyProjectiles private
Definition at line 14 of file Explode.as.
Referenced by DoExplosion(), and Explode().
m_distScaling
float Skills::Explode::m_distScaling private
Definition at line 10 of file Explode.as.
Referenced by DoExplosion(), and Explode().
m_effects
array<IEffect@> Skills::Explode::m_effects private
Definition at line 5 of file Explode.as.
Referenced by DoExplosion(), Explode(), and Initialize().
m_enemyDmg
float Skills::Explode::m_enemyDmg private
Definition at line 13 of file Explode.as.
Referenced by DoExplosion(), and Explode().
m_minRadius
int Skills::Explode::m_minRadius private
Definition at line 9 of file Explode.as.
Referenced by DoExplosion(), and Explode().
m_radius
int Skills::Explode::m_radius private
Definition at line 8 of file Explode.as.
Referenced by DoExplosion(), and Explode().
m_selfDmg
float Skills::Explode::m_selfDmg private
Definition at line 11 of file Explode.as.
Referenced by DoExplosion(), and Explode().
m_selfEffects
array<IEffect@> Skills::Explode::m_selfEffects private
Definition at line 6 of file Explode.as.
Referenced by DoExplosion(), Explode(), and Initialize().
m_teamDmg
float Skills::Explode::m_teamDmg private
Definition at line 12 of file Explode.as.
Referenced by DoExplosion(), and Explode().
m_tickRate
int Skills::Explode::m_tickRate private
Definition at line 16 of file Explode.as.
Referenced by Activate(), DoTrigger(), Explode(), GetTargetingMode(), Hold(), NetActivate(), NetHold(), and NetTrigger().
m_tickRateC
int Skills::Explode::m_tickRateC private
Definition at line 17 of file Explode.as.
Referenced by Activate(), DoTrigger(), Hold(), NetHold(), and NetTrigger().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Skills/Explode.as