HoHDocs: SpawnUnitBase Class Reference
SpawnUnitBase Class Reference
Private Member Functions
void Initialize (UnitPtr unit, SValue@ params)
vec2 CalcJitter ()
UnitPtr SpawnUnit (vec2 pos, Actor@ owner, float intensity=1.0)
Private Attributes
UnitProducer UnitType
string SceneName
int Layer
float JitterX
float JitterY
int Delay
bool AggroEnemy
bool NoLootEnemy
bool NoExperienceEnemy
Detailed Description
Definition at line 1 of file SpawnUnitBase.as.
Member Function Documentation
CalcJitter()
vec2 SpawnUnitBase::CalcJitter () inline private
Definition at line 47 of file SpawnUnitBase.as.
References JitterX, and JitterY.
Referenced by DoSpawnUnits(), WorldScript::SpawnUnit::ServerExecute(), and WorldScript::SpawnUnitAsLoot::ServerExecute().
     {
         return vec2((randf() * 2.0 - 1.0) * JitterX, (randf() * 2.0 - 1.0) * JitterY);
     }
Initialize()
void SpawnUnitBase::Initialize (UnitPtr unit, SValue@ params) inline private
Definition at line 30 of file SpawnUnitBase.as.
References AggroEnemy, Delay, JitterX, JitterY, Layer, NoExperienceEnemy, NoLootEnemy, SceneName, unit, and UnitType.
Referenced by SpawnUnit().
     {
         if (params !is null)
         {
             @UnitType = Resources::GetUnitProducer(GetParamString(unit, params, "unit"));
             SceneName = GetParamString(unit, params, "scene", false, "");
             Layer = GetParamInt(unit, params, "layer", false, 0);
             Delay = GetParamInt(unit, params, "delay", false, 0);
             AggroEnemy = GetParamBool(unit, params, "aggro", false, false);
             NoLootEnemy = GetParamBool(unit, params, "no-loot", false, false);
             NoExperienceEnemy = GetParamBool(unit, params, "no-experience", false, false);
             vec2 jitter = GetParamVec2(unit, params, "jitter", false);
             JitterX = jitter.x;
             JitterY = jitter.y;
         }
     }
SpawnUnit()
UnitPtr SpawnUnitBase::SpawnUnit (vec2 pos, Actor@ owner, float intensity = 1.0) inline private
Definition at line 52 of file SpawnUnitBase.as.
References AggroEnemy, Delay, IsNetsyncedExistance(), Layer, Actor::m_unit, NoExperienceEnemy, NoLootEnemy, SpawnUnitBaseHandler::PackEnemyCfg(), QueuedTasks::Queue(), SceneName, SpawnUnitBaseImpl(), and UnitType.
Referenced by DoSpawnUnit(), WorldScript::SpawnUnit::ServerExecute(), and WorldScript::SpawnUnitAsLoot::ServerExecute().
     {
         if (UnitType is null)
             return UnitPtr();
         int8 cfgEnemy = SpawnUnitBaseHandler::PackEnemyCfg(AggroEnemy, NoLootEnemy, NoExperienceEnemy);
         if (!Network::IsServer() && IsNetsyncedExistance(UnitType.GetNetSyncMode()))
         {
             (Network::Message("DoSpawnUnitBase") << Delay << UnitType.GetResourceHash() << pos << SceneName << Layer << cfgEnemy << (owner is null ? 0 : owner.m_unit.GetId()) << intensity).SendToHost();
             return UnitPtr();
         }
         if (Delay > 0)
         {
             QueuedTasks::Queue(Delay, SpawnUnitBaseTask(UnitType, pos, SceneName, Layer, cfgEnemy, owner is null ? UnitPtr() : owner.m_unit, intensity));
             return UnitPtr();
         }
         return SpawnUnitBaseImpl(UnitType, pos, SceneName, Layer, cfgEnemy, owner is null ? UnitPtr() : owner.m_unit, intensity);
     }
Member Data Documentation
AggroEnemy
bool SpawnUnitBase::AggroEnemy private
Definition at line 22 of file SpawnUnitBase.as.
Referenced by Initialize(), and SpawnUnit().
Delay
int SpawnUnitBase::Delay private
Definition at line 18 of file SpawnUnitBase.as.
Referenced by Initialize(), and SpawnUnit().
JitterX
float SpawnUnitBase::JitterX private
Definition at line 13 of file SpawnUnitBase.as.
Referenced by CalcJitter(), and Initialize().
JitterY
float SpawnUnitBase::JitterY private
Definition at line 15 of file SpawnUnitBase.as.
Referenced by CalcJitter(), and Initialize().
Layer
int SpawnUnitBase::Layer private
Definition at line 10 of file SpawnUnitBase.as.
Referenced by Initialize(), and SpawnUnit().
NoExperienceEnemy
bool SpawnUnitBase::NoExperienceEnemy private
Definition at line 26 of file SpawnUnitBase.as.
Referenced by Initialize(), and SpawnUnit().
NoLootEnemy
bool SpawnUnitBase::NoLootEnemy private
Definition at line 24 of file SpawnUnitBase.as.
Referenced by Initialize(), and SpawnUnit().
SceneName
string SpawnUnitBase::SceneName private
Definition at line 7 of file SpawnUnitBase.as.
Referenced by Initialize(), and SpawnUnit().
UnitType
UnitProducer SpawnUnitBase::UnitType private
Definition at line 4 of file SpawnUnitBase.as.
Referenced by DoSpawnUnit(), Initialize(), and SpawnUnit().
The documentation for this class was generated from the following file:
scripts/SpawnUnitBase.as