HoHDocs: StatueSelectMenu Class Reference
StatueSelectMenu Class Reference
Private Member Functions
StatueSelectMenu (GUIBuilder@ b, StatuesShopMenuContent@ owner, int slot)
bool BlocksLower () override
void Show () override
void Close () override
void OnFunc (Widget@ sender, string name) override
Private Attributes
StatuesShopMenuContent m_owner
int m_slot
Detailed Description
Definition at line 1 of file StatueSelectMenu.as.
Constructor & Destructor Documentation
StatueSelectMenu()
StatueSelectMenu::StatueSelectMenu (GUIBuilder@ b, StatuesShopMenuContent@ owner, int slot) inline private
Definition at line 7 of file StatueSelectMenu.as.
References m_owner, and m_slot.
     {
         super(b, "gui/shop/statues_select.gui");
         @m_owner = owner;
         m_slot = slot;
     }
Member Function Documentation
BlocksLower()
bool StatueSelectMenu::BlocksLower () inline override private
Definition at line 16 of file StatueSelectMenu.as.
     {
         return true;
     }
Close()
void StatueSelectMenu::Close () inline override private
Definition at line 61 of file StatueSelectMenu.as.
References UserWindow::Close(), g_gameMode, and UserWindow::m_visible.
Referenced by OnFunc().
     {
         if (!m_visible)
             return;
         auto gm = cast<Town>(g_gameMode);
         int index = gm.m_userWindows.findByRef(this);
         if (index != -1)
             gm.m_userWindows.removeAt(index);
         UserWindow::Close();
     }
OnFunc()
void StatueSelectMenu::OnFunc (Widget@ sender, string name) inline override private
Definition at line 75 of file StatueSelectMenu.as.
References Close(), g_gameMode, m_owner, m_slot, name, UserWindow::OnFunc(), and StatuesShopMenuContent::RefreshPlacementList().
     {
         auto parse = name.split(" ");
         if (parse[0] == "set")
         {
             auto gm = cast<Town>(g_gameMode);
             gm.m_town.m_statuePlacements[m_slot] = parse[1];
             gm.SetStatues();
             gm.RefreshTownModifiers();
             m_owner.RefreshPlacementList();
             Close();
         }
         else
             UserWindow::OnFunc(sender, name);
     }
Show()
void StatueSelectMenu::Show () inline override private
Definition at line 21 of file StatueSelectMenu.as.
References Widget::AddChild(), ScalableSpriteButtonWidget::Clone(), g_gameMode, ScalableSpriteButtonWidget::m_enabled, m_slot, UserWindow::m_visible, m_widget, and UserWindow::Show().
Referenced by StatuesShopMenuContent::OnFunc().
     {
         if (m_visible)
             return;
         auto gm = cast<Town>(g_gameMode);
         gm.m_userWindows.insertLast(this);
         Widget@ wList = m_widget.GetWidgetById("list");
         ScalableSpriteButtonWidget@ wTemplate = cast<ScalableSpriteButtonWidget>(m_widget.GetWidgetById("template"));
         auto resetButton = cast<ScalableSpriteButtonWidget>(wTemplate.Clone());
         resetButton.SetID("");
         resetButton.m_visible = true;
         resetButton.m_enabled = (gm.m_town.m_statuePlacements[m_slot] != "");
         resetButton.SetText("reset");
         resetButton.m_func = "set ";
         wList.AddChild(resetButton);
         for (uint i = 0; i < gm.m_town.m_statues.length(); i++)
         {
             auto statue = gm.m_town.m_statues[i];
             auto def = statue.GetDef();
             int placement = gm.m_town.GetStatuePlacement(statue.m_id);
             auto newButton = cast<ScalableSpriteButtonWidget>(wTemplate.Clone());
             newButton.SetID("");
             newButton.m_visible = true;
             newButton.m_enabled = (placement == -1 && statue.m_sculpted);
             newButton.SetText(Resources::GetString(def.m_name));
             newButton.m_tooltipTitle = Resources::GetString(def.m_name);
             newButton.m_tooltipText = Resources::GetString(def.m_desc);
             newButton.m_func = "set " + statue.m_id;
             wList.AddChild(newButton);
         }
         UserWindow::Show();
     }
Member Data Documentation
m_owner
StatuesShopMenuContent StatueSelectMenu::m_owner private
Definition at line 3 of file StatueSelectMenu.as.
Referenced by OnFunc(), and StatueSelectMenu().
m_slot
int StatueSelectMenu::m_slot private
Definition at line 5 of file StatueSelectMenu.as.
Referenced by OnFunc(), Show(), and StatueSelectMenu().
The documentation for this class was generated from the following file:
scripts/GUI/Shop/StatueSelectMenu.as