HoHDocs: RangedMovement Class Reference
RangedMovement Class Reference
Private Member Functions
RangedMovement (UnitPtr unit, SValue &params)
void Initialize (UnitPtr unit, CompositeActorBehavior &behavior) override
bool IsStandPosValid (vec2 pos, bool checkMinDist)
bool SeesTarget ()
void Update (int dt, bool isCasting) override
Private Attributes
vec2 m_targetPos
int m_targetPosVerifyCd
int m_stuckC
bool m_strafing
Detailed Description
Definition at line 1 of file RangedMovement.as.
Constructor & Destructor Documentation
RangedMovement()
RangedMovement::RangedMovement (UnitPtr unit, SValue & params) inline private
Definition at line 8 of file RangedMovement.as.
References m_strafing, and unit.
     {
         super(unit, params);
         m_strafing = GetParamBool(unit, params, "strafing", false, true);
     }
Member Function Documentation
Initialize()
void RangedMovement::Initialize (UnitPtr unit, CompositeActorBehavior & behavior) inline override private
Definition at line 14 of file RangedMovement.as.
References MeleeMovement::Initialize(), and unit.
     {
         MeleeMovement::Initialize(unit, behavior);
         unit.SetShouldCollideWithSame(false);
     }
IsStandPosValid()
bool RangedMovement::IsStandPosValid (vec2 pos, bool checkMinDist) inline private
Definition at line 20 of file RangedMovement.as.
References distsq(), g_scene, ActorMovement::m_behavior, MeleeMovement::m_minDist, MeleeMovement::m_standDist, and xy().
Referenced by Update().
     {
         float dsq = distsq(pos, xy(m_behavior.m_target.m_unit.GetPosition()));
         if (dsq > m_standDist * m_standDist)
             return false;
         if (checkMinDist && dsq < m_minDist * m_minDist)
             return false;
         RaycastResult res = g_scene.RaycastClosest(pos, xy(m_behavior.m_target.m_unit.GetPosition()), ~0, RaycastType::Aim);
         UnitPtr res_unit = res.FetchUnit(g_scene);
         if (!res_unit.IsValid())
             return true;
         return (res_unit == m_behavior.m_target.m_unit);
     }
SeesTarget()
bool RangedMovement::SeesTarget () inline private
Definition at line 38 of file RangedMovement.as.
References g_scene, ActorMovement::m_behavior, ActorMovement::m_unit, and xy().
Referenced by Update().
     {
         if (m_behavior.m_target is null)
             return false;
         RaycastResult res = g_scene.RaycastClosest(xy(m_unit.GetPosition()), xy(m_behavior.m_target.m_unit.GetPosition()), ~0, RaycastType::Aim);
         UnitPtr res_unit = res.FetchUnit(g_scene);
         if (res_unit.IsValid() && res_unit != m_behavior.m_target.m_unit)
             return false;
         return true;
     }
Update()
void RangedMovement::Update (int dt, bool isCasting) inline override private
Definition at line 52 of file RangedMovement.as.
References MeleeMovement::ClientUpdate(), distsq(), PathFollower::FollowPath(), g_scene, AnimString::GetSceneName(), MeleeMovement::IdleUpdate(), IsStandPosValid(), ActorMovement::m_behavior, ActorMovement::m_enabled, ActorFootsteps::m_facingDirection, MeleeMovement::m_footsteps, MeleeMovement::m_idleAnim, MeleeMovement::m_minDist, PathFollower::m_path, MeleeMovement::m_pathFollower, MeleeMovement::m_speed, MeleeMovement::m_stagger, MeleeMovement::m_standDist, m_strafing, m_stuckC, m_targetPos, m_targetPosVerifyCd, ActorMovement::m_unit, PathFollower::m_visualDir, max, SeesTarget(), MeleeMovement::SetWalkingAnimation(), ActorFootsteps::Update(), Update(), and xy().
     {
         if (!m_enabled || isCasting)
             return;
         ActorMovement::Update(dt, isCasting);
         if (!Network::IsServer())
         {
             if (SeesTarget() && m_strafing)
                 ClientUpdate(dt, isCasting, xy(m_behavior.m_target.m_unit.GetPosition() - m_unit.GetPosition()));
             else
                 ClientUpdate(dt, isCasting, m_unit.GetMoveDir());
             return;
         }
         float speed = m_speed * m_behavior.m_buffs.MoveSpeedMul();
         if (m_stagger > 0)
         {
             m_stagger -= dt;
             speed *= 0.5;
         }
         if (MeleeMovement::IdleUpdate(dt, speed))
             return;
         m_targetPosVerifyCd -= dt;
         bool validStandPos = !(m_targetPos.x == 0 && m_targetPos.y == 0);
         if (validStandPos && m_targetPosVerifyCd <= 0) // raycast cooldown
         {
             if (m_pathFollower.m_path is null)
                 validStandPos = false;
             else
                 validStandPos = IsStandPosValid(m_targetPos, true);
             m_targetPosVerifyCd = 750 + randi(500);
         }
         if (m_stuckC >= 200)
         {
             m_stuckC = 0;
             validStandPos = false;
         }
         if (!validStandPos)
         {
             //m_targetPos = vec2();
             for (uint i = 0; i < 4; i++)
             {
                 vec2 from = xy(m_behavior.m_target.m_unit.GetPosition());
                 vec2 dir = normalize(from - xy(m_unit.GetPosition()));
                 float ang = atan(dir.y, dir.x) + (randf() - 0.5) * PI + PI;
                 vec2 to = from + vec2(cos(ang), sin(ang)) * max(m_standDist * 0.8, (m_standDist + m_minDist) / 2.0);
                 RaycastResult res = g_scene.RaycastClosest(from, to, ~0, RaycastType::Aim);
                 UnitPtr res_unit = res.FetchUnit(g_scene);
                 if (res_unit.IsValid())
                     to = res.point - normalize(to - from) * 20;
                 if (IsStandPosValid(to, false))
                 {
                     m_targetPos = to;
                     break;
                 }
             }
         }
         auto body = m_unit.GetPhysicsBody();
         bool seesTarget = SeesTarget();
         if (distsq(xy(m_unit.GetPosition()), m_targetPos) <= 5 * 5)
         {
             if (seesTarget)
             {
                 vec2 dir = normalize(xy(m_behavior.m_target.m_unit.GetPosition() - m_unit.GetPosition()));
                 m_dir = atan(dir.y, dir.x);
             }
             body.SetLinearVelocity(0, 0);
             m_unit.SetUnitScene(m_idleAnim.GetSceneName(m_dir), false);
         }
         else
         {
             if (lengthsq(body.GetLinearVelocity()) < 0.1f)
                 m_stuckC += dt;
             else
                 m_stuckC = 0;
             vec2 dir = m_pathFollower.FollowPath(xy(m_unit.GetPosition()), m_targetPos) * speed;// * CalcDirSpeed();
             if (m_behavior.m_buffs.Confuse() && !m_behavior.m_buffs.AntiConfuse())
             {
                 dir = GetConfuseDir(dir, speed);
                 m_dir = atan(dir.y, dir.x);
             }
             else if (seesTarget && m_strafing)
             {
                 auto dr = normalize(xy(m_behavior.m_target.m_unit.GetPosition() - m_unit.GetPosition()));
                 m_dir = atan(dr.y, dr.x);
             }
             else
                 m_dir = m_pathFollower.m_visualDir;
             body.SetLinearVelocity(dir);
             SetWalkingAnimation();
             if (m_footsteps !is null)
             {
                 m_footsteps.m_facingDirection = m_dir;
                 m_footsteps.Update(dt);
             }
         }
     }
Member Data Documentation
m_strafing
bool RangedMovement::m_strafing private
Definition at line 6 of file RangedMovement.as.
Referenced by RangedMovement(), and Update().
m_stuckC
int RangedMovement::m_stuckC private
Definition at line 5 of file RangedMovement.as.
Referenced by Update().
m_targetPos
vec2 RangedMovement::m_targetPos private
Definition at line 3 of file RangedMovement.as.
Referenced by Update().
m_targetPosVerifyCd
int RangedMovement::m_targetPosVerifyCd private
Definition at line 4 of file RangedMovement.as.
Referenced by Update().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Enemies/Movements/RangedMovement.as