HoHDocs: WorldScript::StartDungeon Class Reference
WorldScript::StartDungeon Class Reference
Private Member Functions
SValue ServerExecute ()
Private Attributes
string Rotation
Detailed Description
Definition at line 4 of file StartDungeon.as.
Member Function Documentation
ServerExecute()
SValue WorldScript::StartDungeon::ServerExecute () inline private
Definition at line 9 of file StartDungeon.as.
References ChangeLevel(), DungeonRotation(), g_gameMode, Rotation, and SetJoinable().
         {
             auto gm = cast<Campaign>(g_gameMode);
             if (gm is null)
             {
                 PrintError("Gamemode is not of type Campaign!");
                 return null;
             }
             if (gm.m_rotation !is null)
                 PrintError("WARNING: Map rotation is not null! Overriding with new rotation.");
             @gm.m_rotation = DungeonRotation(Rotation);
             auto firstLevel = gm.m_rotation.GetLevel(gm.m_levelCount);
             Lobby::SetJoinable(false);
             ChangeLevel(firstLevel.m_filename);
             return null;
         }
Member Data Documentation
Rotation
string WorldScript::StartDungeon::Rotation private
Definition at line 7 of file StartDungeon.as.
Referenced by ServerExecute().
The documentation for this class was generated from the following file:
scripts/WorldScript/StartDungeon.as