HoHDocs: CheckBoxWidget Class Reference
CheckBoxWidget Class Reference
Private Member Functions
CheckBoxWidget ()
string GetValue ()
bool IsChecked ()
void SetCheckable ()
void SetChecked (bool b)
void SetGroupWidget (CheckBoxGroupWidget@ group)
bool IsEnabled ()
Widget Clone () override
void Reset ()
void Cancel ()
void Save ()
bool IsChanged ()
void Load (WidgetLoadingContext &ctx) override
void SetText (string str)
void SetColor (vec4 color)
bool OnClick (vec2 mousePos) override
bool OnDoubleClick (vec2 mousePos) override
void OnMouseEnter (vec2 mousePos, bool forced) override
void DoDraw (SpriteBatch &sb, vec2 pos) override
Private Attributes
CheckBoxGroupWidget m_checkBoxGroup
SpriteRect m_spriteRect
Sprite m_spriteUnchecked
Sprite m_spriteHover
Sprite m_spriteChecked
Sprite m_spriteDisabled
bool m_enabled
bool m_disabledTooltip
BitmapFont m_font
BitmapString m_text
string m_str = ""
vec4 m_color = vec4(1, 1, 1, 1)
string m_value
string m_func
string m_cvar
bool m_cvarOrig
bool m_checked
SoundEvent m_pressSound
SoundEvent m_selectSound
int m_contentWidth
int m_contentHeight
Detailed Description
Definition at line 1 of file CheckBox.as.
Constructor & Destructor Documentation
CheckBoxWidget()
CheckBoxWidget::CheckBoxWidget () inline private
Definition at line 33 of file CheckBox.as.
Referenced by Clone().
     {
         super();
     }
Member Function Documentation
Cancel()
void CheckBoxWidget::Cancel () inline private
Definition at line 62 of file CheckBox.as.
References m_cvar, m_cvarOrig, and SetChecked().
     {
         SetVar(m_cvar, m_cvarOrig);
         if (m_cvarOrig)
             SetChecked(true);
         else
             SetChecked(false);
     }
Clone()
Widget CheckBoxWidget::Clone () inline override private
Definition at line 45 of file CheckBox.as.
References CheckBoxWidget(), and Widget::CloneInto().
     {
         CheckBoxWidget@ w = CheckBoxWidget();
         CloneInto(w);
         return w;
     }
DoDraw()
void CheckBoxWidget::DoDraw (SpriteBatch & sb, vec2 pos) inline override private
Definition at line 208 of file CheckBox.as.
References g_menuTime, m_checked, m_color, m_enabled, Widget::m_height, Widget::m_hovering, m_spriteChecked, m_spriteDisabled, m_spriteHover, m_spriteRect, m_spriteUnchecked, m_text, and Widget::m_width.
Referenced by ColorCheckBoxWidget::DoDraw().
     {
         int textOffset = 0;
         if (m_spriteRect !is null)
         {
             int variation = 0;
             if (!m_enabled)
                 variation = 3;
             else if (m_checked)
                 variation = 2;
             else if (m_hovering)
                 variation = 1;
             m_spriteRect.Draw(sb, pos, m_width, m_height, variation);
         }
         else
         {
             Sprite@ sprite = m_spriteUnchecked;
             if (m_checked)
                 @sprite = m_spriteChecked;
             else if (m_hovering && m_spriteHover !is null)
                 @sprite = m_spriteHover;
             if (!m_enabled)
             {
                 if (m_spriteDisabled !is null)
                     @sprite = m_spriteDisabled;
                 else
                     sb.EnableColorize(vec4(0, 0, 0, 1), vec4(0.125, 0.125, 0.125, 1), vec4(0.25, 0.25, 0.25, 1));
             }
             sb.DrawSprite(pos + vec2(0, m_height / 2 - sprite.GetHeight() / 2), sprite, g_menuTime);
             if (!m_enabled && m_spriteDisabled is null)
                 sb.DisableColorize();
             textOffset = sprite.GetWidth() + 2;
         }
         if (m_text !is null)
         {
             vec4 textColor = m_color;
             if (!m_enabled)
                 textColor = vec4(0.25, 0.25, 0.25, 1);
             m_text.SetColor(textColor);
             sb.DrawString(pos + vec2(textOffset, -1), m_text);
         }
     }
GetValue()
string CheckBoxWidget::GetValue () inline private
Definition at line 38 of file CheckBox.as.
References m_value.
 { return m_value; }
IsChanged()
bool CheckBoxWidget::IsChanged () inline private
Definition at line 77 of file CheckBox.as.
References m_cvar, and m_cvarOrig.
     {
         return GetVarBool(m_cvar) != m_cvarOrig;
     }
IsChecked()
bool CheckBoxWidget::IsChecked () inline private
Definition at line 39 of file CheckBox.as.
References m_checked.
 { return m_checked; }
IsEnabled()
bool CheckBoxWidget::IsEnabled () inline private
Definition at line 43 of file CheckBox.as.
References m_enabled.
 { return m_enabled; }
Load()
void CheckBoxWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 82 of file CheckBox.as.
References Widget::Load(), Widget::m_canFocus, m_checked, m_color, m_cvar, m_cvarOrig, m_disabledTooltip, m_enabled, m_font, m_func, Widget::m_height, m_pressSound, m_selectSound, m_spriteChecked, m_spriteDisabled, m_spriteHover, m_spriteRect, m_spriteUnchecked, m_value, Widget::m_width, SetChecked(), SetText(), and SpriteRect().
Referenced by LoadCheckboxWidget().
     {
         GUIDef@ def = ctx.GetGUIDef();
         string spriteset = ctx.GetString("spriteset");
         if (spriteset.findLast(".sval") == int(spriteset.length()) - 5)
             @m_spriteRect = SpriteRect(spriteset);
         else
         {
             @m_spriteUnchecked = def.GetSprite(spriteset);
             @m_spriteHover = def.GetSprite(spriteset + "-hover");
             @m_spriteChecked = def.GetSprite(spriteset + "-checked");
             @m_spriteDisabled = def.GetSprite(spriteset + "-disabled");
         }
         m_enabled = ctx.GetBoolean("enabled", false, true);
         m_disabledTooltip = ctx.GetBoolean("disabled-tooltip", false);
         if (m_font is null)
         {
             string fontName = ctx.GetString("font", false);
             @m_font = Resources::GetBitmapFont(fontName);
         }
         m_color = ctx.GetColorRGBA("color", false, vec4(1, 1, 1, 1));
         m_value = ctx.GetString("value", false);
         m_func = ctx.GetString("func", false);
         m_checked = ctx.GetBoolean("checked", false);
         m_cvar = ctx.GetString("cvar", false);
         if (m_cvar != "")
         {
             SetChecked(GetVarBool(m_cvar));
             m_cvarOrig = GetVarBool(m_cvar);
         }
         SetText(Resources::GetString(ctx.GetString("text", false)));
         @m_pressSound = Resources::GetSoundEvent("event:/ui/button_click");
         @m_selectSound = Resources::GetSoundEvent("event:/ui/button_hover");
         if (m_font is null)
         {
             if (m_spriteRect !is null)
             {
                 m_width = ctx.GetInteger("content-width", false, m_spriteRect.m_width);
                 m_height = ctx.GetInteger("content-height", false, m_spriteRect.m_height);
             }
             else
             {
                 m_width = ctx.GetInteger("content-width", false, m_spriteUnchecked.GetWidth());
                 m_height = ctx.GetInteger("content-height", false, m_spriteUnchecked.GetHeight());
             }
         }
         Widget::Load(ctx);
         m_canFocus = true;
     }
OnClick()
bool CheckBoxWidget::OnClick (vec2 mousePos) inline override private
Definition at line 168 of file CheckBox.as.
References m_checkBoxGroup, m_checked, m_enabled, m_func, Widget::m_host, m_pressSound, PlaySound2D(), and CheckBoxGroupWidget::Toggled().
     {
         if (!m_enabled)
             return false;
         PlaySound2D(m_pressSound);
         if (m_checkBoxGroup !is null)
             m_checkBoxGroup.Toggled(this);
         else
             m_checked = !m_checked;
         if (m_func != "")
             m_host.OnFunc(this, m_func);
         return true;
     }
OnDoubleClick()
bool CheckBoxWidget::OnDoubleClick (vec2 mousePos) inline override private
Definition at line 186 of file CheckBox.as.
References m_checkBoxGroup, m_enabled, m_pressSound, CheckBoxGroupWidget::OnDoubleClick(), and PlaySound2D().
     {
         if (!m_enabled)
             return false;
         PlaySound2D(m_pressSound);
         if (m_checkBoxGroup !is null)
             return m_checkBoxGroup.OnDoubleClick(mousePos);
         return true;
     }
OnMouseEnter()
void CheckBoxWidget::OnMouseEnter (vec2 mousePos, bool forced) inline override private
Definition at line 199 of file CheckBox.as.
References m_disabledTooltip, m_enabled, m_selectSound, Widget::OnMouseEnter(), and PlaySound2D().
     {
         if (m_enabled || m_disabledTooltip)
             Widget::OnMouseEnter(mousePos, forced);
         if (m_enabled)
             PlaySound2D(m_selectSound);
     }
Reset()
void CheckBoxWidget::Reset () inline private
Definition at line 52 of file CheckBox.as.
References m_cvar, and SetChecked().
     {
         bool def = GetVarBoolDefault(m_cvar);
         SetVar(m_cvar, def);
         if (def)
             SetChecked(true);
         else
             SetChecked(false);
     }
Save()
void CheckBoxWidget::Save () inline private
Definition at line 71 of file CheckBox.as.
References m_cvar, and m_cvarOrig.
     {
         m_cvarOrig = GetVarBool(m_cvar);
         Config::SaveVar(m_cvar);
     }
SetCheckable()
void CheckBoxWidget::SetCheckable () inline private
Definition at line 40 of file CheckBox.as.
 { }
SetChecked()
void CheckBoxWidget::SetChecked (bool b) inline private
Definition at line 41 of file CheckBox.as.
References m_checked.
Referenced by Cancel(), Load(), Reset(), and DungeonSettingsMenu::Update().
 { m_checked = b; }
SetColor()
void CheckBoxWidget::SetColor (vec4 color) inline private
Definition at line 161 of file CheckBox.as.
References m_color, and m_text.
     {
         m_color = color;
         m_text.SetColor(color);
     }
SetGroupWidget()
void CheckBoxWidget::SetGroupWidget (CheckBoxGroupWidget@ group) inline private
Definition at line 42 of file CheckBox.as.
References m_checkBoxGroup.
 { @m_checkBoxGroup = group; }
SetText()
void CheckBoxWidget::SetText (string str) inline private
Definition at line 144 of file CheckBox.as.
References m_color, m_font, Widget::m_height, m_spriteUnchecked, m_str, m_text, and Widget::m_width.
Referenced by Load().
     {
         if (m_font is null)
             return;
         m_str = str;
         @m_text = m_font.BuildText(str);
         m_text.SetColor(m_color);
         if (m_spriteUnchecked !is null)
             m_width = m_text.GetWidth() + m_spriteUnchecked.GetWidth() + 1;
         else
             m_width = m_text.GetWidth();
         m_height = m_text.GetHeight();
     }
Member Data Documentation
m_checkBoxGroup
CheckBoxGroupWidget CheckBoxWidget::m_checkBoxGroup private
Definition at line 3 of file CheckBox.as.
Referenced by OnClick(), OnDoubleClick(), and SetGroupWidget().
m_checked
bool CheckBoxWidget::m_checked private
Definition at line 25 of file CheckBox.as.
Referenced by DoDraw(), IsChecked(), Load(), OnClick(), and SetChecked().
m_color
vec4 CheckBoxWidget::m_color = vec4(1, 1, 1, 1) private
Definition at line 18 of file CheckBox.as.
Referenced by DoDraw(), Load(), SetColor(), and SetText().
m_contentHeight
int CheckBoxWidget::m_contentHeight private
Definition at line 31 of file CheckBox.as.
m_contentWidth
int CheckBoxWidget::m_contentWidth private
Definition at line 30 of file CheckBox.as.
m_cvar
string CheckBoxWidget::m_cvar private
Definition at line 22 of file CheckBox.as.
Referenced by Cancel(), IsChanged(), Load(), Reset(), and Save().
m_cvarOrig
bool CheckBoxWidget::m_cvarOrig private
Definition at line 23 of file CheckBox.as.
Referenced by Cancel(), IsChanged(), Load(), and Save().
m_disabledTooltip
bool CheckBoxWidget::m_disabledTooltip private
Definition at line 12 of file CheckBox.as.
Referenced by Load(), and OnMouseEnter().
m_enabled
bool CheckBoxWidget::m_enabled private
Definition at line 11 of file CheckBox.as.
Referenced by DoDraw(), IsEnabled(), Load(), OnClick(), OnDoubleClick(), OnMouseEnter(), and DungeonSettingsMenu::Update().
m_font
BitmapFont CheckBoxWidget::m_font private
Definition at line 14 of file CheckBox.as.
Referenced by Load(), and SetText().
m_func
string CheckBoxWidget::m_func private
Definition at line 21 of file CheckBox.as.
Referenced by Load(), and OnClick().
m_pressSound
SoundEvent CheckBoxWidget::m_pressSound private
Definition at line 27 of file CheckBox.as.
Referenced by Load(), OnClick(), and OnDoubleClick().
m_selectSound
SoundEvent CheckBoxWidget::m_selectSound private
Definition at line 28 of file CheckBox.as.
Referenced by Load(), and OnMouseEnter().
m_spriteChecked
Sprite CheckBoxWidget::m_spriteChecked private
Definition at line 8 of file CheckBox.as.
Referenced by DoDraw(), and Load().
m_spriteDisabled
Sprite CheckBoxWidget::m_spriteDisabled private
Definition at line 9 of file CheckBox.as.
Referenced by DoDraw(), and Load().
m_spriteHover
Sprite CheckBoxWidget::m_spriteHover private
Definition at line 7 of file CheckBox.as.
Referenced by DoDraw(), and Load().
m_spriteRect
SpriteRect CheckBoxWidget::m_spriteRect private
Definition at line 5 of file CheckBox.as.
Referenced by DoDraw(), and Load().
m_spriteUnchecked
Sprite CheckBoxWidget::m_spriteUnchecked private
Definition at line 6 of file CheckBox.as.
Referenced by DoDraw(), Load(), and SetText().
m_str
string CheckBoxWidget::m_str = "" private
Definition at line 17 of file CheckBox.as.
Referenced by SetText().
m_text
BitmapString CheckBoxWidget::m_text private
Definition at line 15 of file CheckBox.as.
Referenced by DoDraw(), SetColor(), and SetText().
m_value
string CheckBoxWidget::m_value private
Definition at line 20 of file CheckBox.as.
Referenced by GetValue(), and Load().
The documentation for this class was generated from the following file:
scripts/GUI/CheckBox.as