HoHDocs: PlayerCorpse Class Reference
PlayerCorpse Class Reference
Private Member Functions
PlayerCorpse (UnitPtr unit, SValue &params)
void Initialize (PlayerRecord@ record)
void SetColor (int c, array< vec4 > color)
void NetUse (PlayerHusk@ player)
UnitPtr GetUseUnit ()
bool CanUse (PlayerBase@ player)
UsableIcon GetIcon (Player@ player)
int UsePriority (IUsable@ other)
void Use (PlayerBase@ player)
void NetRevive (PlayerRecord@ reviver, bool overridePosUsed=false, vec3 overridePos=vec3())
void Destroyed ()
void Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther)
void EndCollision (UnitPtr unit, Fixture@ fxSelf, Fixture@ fxOther)
Private Attributes
UnitPtr m_unit
PlayerRecord m_record
CustomUnitScene m_unitScene
EffectParams m_effectParams
Detailed Description
Definition at line 1 of file PlayerCorpse.as.
Constructor & Destructor Documentation
PlayerCorpse()
PlayerCorpse::PlayerCorpse (UnitPtr unit, SValue & params) inline private
Definition at line 8 of file PlayerCorpse.as.
References m_effectParams, m_unit, m_unitScene, and unit.
     {
         m_unit = unit;
         @m_unitScene = CustomUnitScene();
         @m_effectParams = m_unit.CreateEffectParams();
     }
Member Function Documentation
CanUse()
bool PlayerCorpse::CanUse (PlayerBase@ player) inline private
Definition at line 42 of file PlayerCorpse.as.
 { return true; }
Collide()
void PlayerCorpse::Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther) inline private
Definition at line 122 of file PlayerCorpse.as.
References unit.
     {
         auto player = cast<Player>(unit.GetScriptBehavior());
         if (player is null)
             return;
         player.AddUsable(this);
     }
Destroyed()
void PlayerCorpse::Destroyed () inline private
Definition at line 116 of file PlayerCorpse.as.
References m_record.
     {
         if (m_record.corpse is this)
             @m_record.corpse = null;
     }
EndCollision()
void PlayerCorpse::EndCollision (UnitPtr unit, Fixture@ fxSelf, Fixture@ fxOther) inline private
Definition at line 131 of file PlayerCorpse.as.
References unit.
     {
         auto player = cast<Player>(unit.GetScriptBehavior());
         if (player is null)
             return;
         player.RemoveUsable(this);
     }
GetIcon()
UsableIcon PlayerCorpse::GetIcon (Player@ player) inline private
Definition at line 43 of file PlayerCorpse.as.
References Revive.
 { return UsableIcon::Revive; }
GetUseUnit()
UnitPtr PlayerCorpse::GetUseUnit () inline private
Definition at line 41 of file PlayerCorpse.as.
References m_unit.
 { return m_unit; }
Initialize()
void PlayerCorpse::Initialize (PlayerRecord@ record) inline private
Definition at line 15 of file PlayerCorpse.as.
References GetPlayerColor(), m_effectParams, m_record, m_unit, m_unitScene, and SetColor().
     {
         @m_record = record;
         m_unitScene.Clear();
         m_unitScene.AddScene(m_unit.GetCurrentUnitScene(), 0, vec2(), 0, 0);
         auto body = Resources::GetUnitProducer("players/" + m_record.charClass + ".unit");
         m_unitScene.AddScene(body.GetUnitScene("death"), 0, vec2(), 0, 0);
         m_unit.SetUnitScene(m_unitScene, true);
         auto charColors = m_record.GetMulticolors();
         for (uint i = 0; i < charColors.length(); i++)
             SetColor(i, charColors[i]);
         auto color = ParseColorRGBA("#" + GetPlayerColor(m_record.peer) + "ff");
         m_effectParams.Set("color_r", color.r);
         m_effectParams.Set("color_g", color.g);
         m_effectParams.Set("color_b", color.b);
     }
NetRevive()
void PlayerCorpse::NetRevive (PlayerRecord@ reviver, bool overridePosUsed = false, vec3 overridePos = vec3()) inline private
Definition at line 52 of file PlayerCorpse.as.
References AddFloatingText(), g_gameMode, g_players, GetPlayerColor(), m_record, m_unit, Pickup, PlayEffect(), SendSystemMessage(), AGameMode::SpawnPlayer(), and xy().
Referenced by Use().
     {
         auto gm = cast<BaseGameMode>(g_gameMode);
         if (m_record.local)
             gm.StopSpectating();
         // Reviver is ourselves when using revive cheat
         if (reviver !is null && reviver !is m_record)
         {
             int soulLinkOrigin = reviver.soulLinkedBy;
             if (soulLinkOrigin == -1)
                 soulLinkOrigin = reviver.peer;
             m_record.soulLinks.insertLast(reviver.peer);
             m_record.soulLinkedBy = soulLinkOrigin;
             reviver.soulLinks.insertLast(m_record.peer);
             reviver.soulLinkedBy = soulLinkOrigin;
             reviver.hp *= 0.5;
         }
         SValueBuilder builder;
         if (reviver !is null)
         {
             builder.PushString(Resources::GetString(".menu.lobby.chat.revive", {
                 { "reviver", "\\c" + GetPlayerColor(reviver.peer) + gm.GetPlayerDisplayName(reviver) + "\\d" },
                 { "revivee", "\\c" + GetPlayerColor(m_record.peer) + gm.GetPlayerDisplayName(m_record) + "\\d" }
             }));
         }
         else
         {
             builder.PushString(Resources::GetString(".menu.lobby.chat.revive.free", {
                 { "revivee", "\\c" + GetPlayerColor(m_record.peer) + gm.GetPlayerDisplayName(m_record) + "\\d" }
             }));
         }
         SendSystemMessage("AddChat", builder.Build());
         vec3 pos = m_unit.GetPosition();
         if (overridePosUsed)
             pos = overridePos;
         if (reviver !is null)
             AddFloatingText(FloatingTextType::Pickup, Resources::GetString(".misc.soulslinked"), pos);
         PlayEffect("effects/players/revive.effect", xy(pos));
         m_record.hp = 0.5;
         m_record.mana = 0.5;
         if (Network::IsServer())
         {
             for (uint i = 0; i < g_players.length(); i++)
             {
                 if (m_record !is g_players[i])
                     continue;
                 g_gameMode.SpawnPlayer(i, xy(pos));
             }
         }
         m_unit.Destroy();
     }
NetUse()
void PlayerCorpse::NetUse (PlayerHusk@ player) inline private
Definition at line 40 of file PlayerCorpse.as.
 { }
SetColor()
void PlayerCorpse::SetColor (int c, array< vec4 > color) inline private
Definition at line 35 of file PlayerCorpse.as.
References m_unit.
Referenced by Initialize().
     {
         m_unit.SetMultiColor(c, color[0], color[1], color[2]);
     }
Use()
void PlayerCorpse::Use (PlayerBase@ player) inline private
Definition at line 46 of file PlayerCorpse.as.
References GetLocalPlayerRecord(), m_record, and NetRevive().
     {
         (Network::Message("ReviveCorpse") << m_record.peer).SendToAll();
         NetRevive(GetLocalPlayerRecord());
     }
UsePriority()
int PlayerCorpse::UsePriority (IUsable@ other) inline private
Definition at line 44 of file PlayerCorpse.as.
 { return -1; }
Member Data Documentation
m_effectParams
EffectParams PlayerCorpse::m_effectParams private
Definition at line 6 of file PlayerCorpse.as.
Referenced by Initialize(), and PlayerCorpse().
m_record
PlayerRecord PlayerCorpse::m_record private
Definition at line 4 of file PlayerCorpse.as.
Referenced by Destroyed(), Initialize(), NetRevive(), and Use().
m_unit
UnitPtr PlayerCorpse::m_unit private
Definition at line 3 of file PlayerCorpse.as.
Referenced by GetUseUnit(), Initialize(), NetRevive(), PlayerCorpse(), and SetColor().
m_unitScene
CustomUnitScene PlayerCorpse::m_unitScene private
Definition at line 5 of file PlayerCorpse.as.
Referenced by Initialize(), and PlayerCorpse().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Player/PlayerCorpse.as