HoHDocs: Stats::StatList Class Reference
Stats::StatList Class Reference
Private Member Functions
void AddStat (Stat@ stat)
void InitializeCounters (string id)
void SortStats ()
Stat GetStat (const string &in name)
string GetStatString (const string &in name)
int GetStatInt (const string &in name)
void Add (const string &in name, int value)
void AddAvg (const string &in name)
void Max (const string &in name, int value)
string ToString ()
int GetReputationPoints ()
void Load (SValue@ dictStatistics)
void Save (SValueBuilder &builder)
void Clear ()
Private Attributes
array< Stat@> m_stats
string m_id
bool m_checkRewards
Detailed Description
Definition at line 3 of file StatList.as.
Member Function Documentation
Add()
void Stats::StatList::Add (const string &in name, int value) inline private
Definition at line 65 of file StatList.as.
References GetStat(), m_checkRewards, and name.
         {
             auto stat = GetStat(name);
             if (stat is null)
             {
                 PrintError("Couldn't find statistic \"" + name + "\"");
                 return;
             }
             stat.Add(value, m_checkRewards);
         }
AddAvg()
void Stats::StatList::AddAvg (const string &in name) inline private
Definition at line 76 of file StatList.as.
References GetStat(), and name.
         {
             auto stat = GetStat(name);
             if (stat is null)
             {
                 PrintError("Couldn't find statistic \"" + name + "\"");
                 return;
             }
             stat.AddAvg();
         }
AddStat()
void Stats::StatList::AddStat (Stat@ stat) inline private
Definition at line 10 of file StatList.as.
References m_stats.
Referenced by Stats::LoadList().
         {
             m_stats.insertLast(stat);
         }
Clear()
void Stats::StatList::Clear () inline private
Definition at line 153 of file StatList.as.
References m_stats.
Referenced by Load().
         {
             for (uint i = 0; i < m_stats.length(); i++)
                 m_stats[i].Clear();
         }
GetReputationPoints()
int Stats::StatList::GetReputationPoints () inline private
Definition at line 112 of file StatList.as.
References m_stats.
Referenced by TownRecord::GetReputation().
         {
             int ret = 0;
             for (uint i = 0; i < m_stats.length(); i++)
             {
                 auto stat = m_stats[i];
                 for (uint j = 0; j < stat.m_accomplishments.length(); j++)
                 {
                     auto accomplishment = stat.m_accomplishments[j];
                     if (accomplishment.m_finished)
                         ret += accomplishment.m_reputation;
                 }
             }
             return ret;
         }
GetStat()
Stat Stats::StatList::GetStat (const string &in name) inline private
Definition at line 38 of file StatList.as.
References Stats::m_nameHash, m_stats, and name.
Referenced by Add(), AddAvg(), GetStatInt(), GetStatString(), Load(), and Max().
         {
             uint hash = HashString(name);
             for (uint i = 0; i < m_stats.length(); i++)
             {
                 if (m_stats[i].m_nameHash == hash)
                     return m_stats[i];
             }
             return null;
         }
GetStatInt()
int Stats::StatList::GetStatInt (const string &in name) inline private
Definition at line 57 of file StatList.as.
References GetStat(), and name.
         {
             auto stat = GetStat(name);
             if (stat is null)
                 return -1;
             return stat.m_valueInt;
         }
GetStatString()
string Stats::StatList::GetStatString (const string &in name) inline private
Definition at line 49 of file StatList.as.
References GetStat(), and name.
         {
             auto stat = GetStat(name);
             if (stat is null)
                 return "???";
             return stat.ToString();
         }
InitializeCounters()
void Stats::StatList::InitializeCounters (string id) inline private
Definition at line 15 of file StatList.as.
References id, and m_stats.
Referenced by Campaign::Start().
         {
             for (uint i = 0; i < m_stats.length(); i++)
             {
                 auto stat = m_stats[i];
                 if (stat.m_hasCounter)
                 {
                     stat.m_counterId = "stat_" + stat.m_name.replace("-", "_") + "_" + id;
                     stat.m_counterIdHash = HashString(stat.m_counterId);
                     if (!CounterExists(stat.m_counterId))
                         AddCounterInt(stat.m_counterId, CounterClear::Never);
                     stat.UpdateCounter();
                 }
             }
         }
Load()
void Stats::StatList::Load (SValue@ dictStatistics) inline private
Definition at line 128 of file StatList.as.
References Clear(), GetStat(), m_checkRewards, and Stats::Stat().
Referenced by GuildHallStatsTab::AddCharacterToList(), and TownRecord::Load().
         {
             Clear();
             auto keys = dictStatistics.GetDictionary().getKeys();
             for (uint i = 0; i < keys.length(); i++)
             {
                 Stats::Stat@ stat = GetStat(keys[i]);
                 if (stat is null)
                 {
                     PrintError("Tried loading non-existing statistic: \"" + keys[i] + "\"");
                     continue;
                 }
                 SValue@ svStat = dictStatistics.GetDictionaryEntry(keys[i]);
                 stat.Load(svStat, m_checkRewards);
             }
         }
Max()
void Stats::StatList::Max (const string &in name, int value) inline private
Definition at line 87 of file StatList.as.
References GetStat(), m_checkRewards, and name.
         {
             auto stat = GetStat(name);
             if (stat is null)
             {
                 PrintError("Couldn't find statistic \"" + name + "\"");
                 return;
             }
             stat.Max(value, m_checkRewards);
         }
Save()
void Stats::StatList::Save (SValueBuilder & builder) inline private
Definition at line 147 of file StatList.as.
References m_stats.
Referenced by TownRecord::Save().
         {
             for (uint i = 0; i < m_stats.length(); i++)
                 m_stats[i].Save(builder);
         }
SortStats()
void Stats::StatList::SortStats () inline private
Definition at line 33 of file StatList.as.
References m_stats.
Referenced by Stats::LoadList().
         {
             m_stats.sortAsc();
         }
ToString()
string Stats::StatList::ToString () inline private
Definition at line 98 of file StatList.as.
References m_checkRewards, and m_stats.
         {
             string ret = "";
             for (uint i = 0; i < m_stats.length(); i++)
             {
                 auto stat = m_stats[i];
                 ret += stat.m_name + ": " + stat.ToString();
                 if (m_checkRewards && stat.m_accomplishments.length() > 0)
                     ret += " (" + stat.GetNumRewarded() + " / " + stat.m_accomplishments.length() + " rewards)";
                 ret += "\n";
             }
             return ret;
         }
Member Data Documentation
m_checkRewards
bool Stats::StatList::m_checkRewards private
Definition at line 8 of file StatList.as.
Referenced by Add(), Load(), Max(), Campaign::Start(), and ToString().
m_id
string Stats::StatList::m_id private
Definition at line 7 of file StatList.as.
m_stats
array<Stat@> Stats::StatList::m_stats private
Definition at line 5 of file StatList.as.
Referenced by AddStat(), GuildHallStatsTab::AddStatisticsToList(), Clear(), GetReputationPoints(), GetStat(), InitializeCounters(), GuildHallAccomplishmentsTab::RefreshList(), Save(), SortStats(), and ToString().
The documentation for this class was generated from the following file:
scripts/Stats/StatList.as