HoHDocs: MenuLobbyPlayerWidget Class Reference
MenuLobbyPlayerWidget Class Reference
Private Member Functions
MenuLobbyPlayerWidget ()
Widget Clone () override
int opCmp (const Widget@ w) override
Private Attributes
uint8 m_peer
Detailed Description
Definition at line 1 of file MenuLobbyPlayerWidget.as.
Constructor & Destructor Documentation
MenuLobbyPlayerWidget()
MenuLobbyPlayerWidget::MenuLobbyPlayerWidget () inline private
Definition at line 5 of file MenuLobbyPlayerWidget.as.
Referenced by Clone().
     {
         super();
     }
Member Function Documentation
Clone()
Widget MenuLobbyPlayerWidget::Clone () inline override private
Definition at line 10 of file MenuLobbyPlayerWidget.as.
References Widget::CloneInto(), and MenuLobbyPlayerWidget().
     {
         MenuLobbyPlayerWidget@ w = MenuLobbyPlayerWidget();
         CloneInto(w);
         return w;
     }
opCmp()
int MenuLobbyPlayerWidget::opCmp (const Widget@ w) inline override private
Definition at line 17 of file MenuLobbyPlayerWidget.as.
References m_peer.
     {
         auto widget = cast<MenuLobbyPlayerWidget>(w);
         if (widget !is null)
         {
             if (m_peer < widget.m_peer)
                 return -1;
             else if (m_peer > widget.m_peer)
                 return 1;
         }
         return 0;
     }
Member Data Documentation
m_peer
uint8 MenuLobbyPlayerWidget::m_peer private
Definition at line 3 of file MenuLobbyPlayerWidget.as.
Referenced by opCmp().
The documentation for this class was generated from the following file:
scripts/GUI/Menus/Widgets/MenuLobbyPlayerWidget.as