HoHDocs: PlayerMenuMapTab Class Reference
PlayerMenuMapTab Class Reference
Private Member Functions
PlayerMenuMapTab ()
void OnCreated () override
int GetMapScale ()
int GetMapWidth ()
int GetMapHeight ()
void OnShow () override
void Update (int dt) override
void AfterUpdate () override
vec4 GetMapColor ()
bool ShouldShowFog ()
void Draw (SpriteBatch &sb, int idt) override
Private Attributes
vec2 m_mapDragLast
vec2 m_camPos
vec4 m_mapColor
Widget m_wMap
TextWidget m_wInfo
Widget m_wInfoNg
TextWidget m_wInfoNgText
bool m_showFog = true
Detailed Description
Definition at line 1 of file Map.as.
Constructor & Destructor Documentation
PlayerMenuMapTab()
PlayerMenuMapTab::PlayerMenuMapTab () inline private
Definition at line 15 of file Map.as.
References MenuTab::m_id, m_mapColor, and Tweak::PlayerMenuMapColor.
     {
         m_id = "map";
         m_mapColor = ParseColorRGBA("#" + Tweak::PlayerMenuMapColor + "FF");
     }
Member Function Documentation
AfterUpdate()
void PlayerMenuMapTab::AfterUpdate () inline override private
Definition at line 64 of file Map.as.
References g_gameMode, g_scene, GetMapHeight(), GetMapScale(), GetMapWidth(), and m_camPos.
     {
         auto gm = cast<Campaign>(g_gameMode);
         int scale = GetMapScale();
         int width = GetMapWidth() * scale;
         int height = GetMapHeight() * scale;
         gm.m_minimap.Prepare(g_scene, m_camPos, width, height, ~0);
     }
Draw()
void PlayerMenuMapTab::Draw (SpriteBatch & sb, int idt) inline override private
Definition at line 101 of file Map.as.
References g_gameMode, GetMapColor(), GetMapHeight(), GetMapWidth(), Widget::m_height, Widget::m_origin, Widget::m_width, and m_wMap.
     {
         auto gm = cast<Campaign>(g_gameMode);
         vec2 pos = m_wMap.m_origin;
         int width = GetMapWidth();
         int height = GetMapHeight();
         sb.PushClipping(vec4(
             pos.x, pos.y,
             m_wMap.m_width, m_wMap.m_height
         ));
         vec2 mapPos = pos - vec2(width - m_wMap.m_width, height - m_wMap.m_height) / 2.0f;
         sb.DrawMinimap(mapPos, gm.m_minimap, width, height, GetMapColor());
         //sb.DrawMinimap(pos - vec2(0, 32), gm.m_minimap, width, height, GetMapColor());
         sb.PopClipping();
     }
GetMapColor()
vec4 PlayerMenuMapTab::GetMapColor () inline private
Definition at line 75 of file Map.as.
References m_mapColor, and m_showFog.
Referenced by Draw(), and Campaign::RenderWidgets().
     {
         if (!m_showFog)
         {
             return vec4(
                 m_mapColor.x,
                 m_mapColor.y,
                 m_mapColor.z,
                 0.5f
             );
         }
         return m_mapColor;
     }
GetMapHeight()
int PlayerMenuMapTab::GetMapHeight () inline private
Definition at line 33 of file Map.as.
References Widget::m_height, and m_wMap.
Referenced by AfterUpdate(), and Draw().
 { return m_wMap.m_height + 64; }
GetMapScale()
int PlayerMenuMapTab::GetMapScale () inline private
Definition at line 31 of file Map.as.
Referenced by AfterUpdate(), and Update().
 { return 4; }
GetMapWidth()
int PlayerMenuMapTab::GetMapWidth () inline private
Definition at line 32 of file Map.as.
References Widget::m_width, and m_wMap.
Referenced by AfterUpdate(), and Draw().
 { return m_wMap.m_width + 64; }
OnCreated()
void PlayerMenuMapTab::OnCreated () inline override private
Definition at line 22 of file Map.as.
References Widget::GetWidgetById(), MenuTab::m_widget, m_wInfo, m_wInfoNg, m_wInfoNgText, and m_wMap.
     {
         @m_wMap = m_widget.GetWidgetById("map");
         @m_wInfo = cast<TextWidget>(m_widget.GetWidgetById("info"));
         @m_wInfoNg = m_widget.GetWidgetById("info-ng");
         @m_wInfoNgText = cast<TextWidget>(m_wInfoNg.GetWidgetById("text"));
     }
OnShow()
void PlayerMenuMapTab::OnShow () inline override private
Definition at line 35 of file Map.as.
References g_ngp, GetLevelName(), GetLocalPlayer(), m_camPos, Widget::m_visible, m_wInfo, m_wInfoNg, m_wInfoNgText, TextWidget::SetText(), and xy().
     {
         auto localPlayer = GetLocalPlayer();
         if (localPlayer is null)
             return;
         m_camPos = xy(localPlayer.m_unit.GetPosition());
         m_wInfo.SetText(GetLevelName());
         m_wInfoNg.m_visible = (g_ngp > 0);
         if (m_wInfoNg.m_visible)
             m_wInfoNgText.SetText(Resources::GetString(".misc.ngp2", { { "ngp", int(g_ngp) } }));
     }
ShouldShowFog()
bool PlayerMenuMapTab::ShouldShowFog () inline private
Definition at line 89 of file Map.as.
References GetLocalPlayerRecord().
Referenced by Campaign::UpdateWidgets().
     {
         if (GetVarBool("ui_hide_fog"))
             return false;
         auto plr = GetLocalPlayerRecord();
         if (plr !is null && plr.items.find("old-map") != -1)
             return false;
         return true;
     }
Update()
void PlayerMenuMapTab::Update (int dt) inline override private
Definition at line 50 of file Map.as.
References Rect::Contains(), ButtonState::Down, MenuInput::Forward, g_gameMode, GetMapScale(), GetMenuInput(), Widget::GetRectangle(), m_camPos, m_mapDragLast, m_wMap, and ButtonState::Pressed.
     {
         auto gm = cast<BaseGameMode>(g_gameMode);
         vec2 mousePos = (gm.m_mice[0].GetPos(0) / gm.m_wndScale);
         MenuInput@ mi = GetMenuInput();
         if (m_wMap.GetRectangle().Contains(mousePos))
         {
             if (!mi.Forward.Pressed && mi.Forward.Down)
                 m_camPos += (m_mapDragLast - mousePos) * GetMapScale();
             m_mapDragLast = mousePos;
         }
     }
Member Data Documentation
m_camPos
vec2 PlayerMenuMapTab::m_camPos private
Definition at line 4 of file Map.as.
Referenced by AfterUpdate(), OnShow(), and Update().
m_mapColor
vec4 PlayerMenuMapTab::m_mapColor private
Definition at line 5 of file Map.as.
Referenced by GetMapColor(), and PlayerMenuMapTab().
m_mapDragLast
vec2 PlayerMenuMapTab::m_mapDragLast private
Definition at line 3 of file Map.as.
Referenced by Update().
m_showFog
bool PlayerMenuMapTab::m_showFog = true private
Definition at line 13 of file Map.as.
Referenced by GetMapColor(), and Campaign::UpdateWidgets().
m_wInfo
TextWidget PlayerMenuMapTab::m_wInfo private
Definition at line 8 of file Map.as.
Referenced by OnCreated(), and OnShow().
m_wInfoNg
Widget PlayerMenuMapTab::m_wInfoNg private
Definition at line 10 of file Map.as.
Referenced by OnCreated(), and OnShow().
m_wInfoNgText
TextWidget PlayerMenuMapTab::m_wInfoNgText private
Definition at line 11 of file Map.as.
Referenced by OnCreated(), and OnShow().
m_wMap
Widget PlayerMenuMapTab::m_wMap private
Definition at line 7 of file Map.as.
Referenced by Draw(), GetMapHeight(), GetMapWidth(), OnCreated(), and Update().
The documentation for this class was generated from the following file:
scripts/GUI/PlayerMenu/Map.as