HoHDocs: DelayedBreakable Class Reference
DelayedBreakable Class Reference
Private Member Functions
DelayedBreakable (UnitPtr unit, SValue &params)
void DamageEffects ()
void SetDelayed ()
int Damage (DamageInfo dmg, vec2 pos, vec2 dir) override
void NetDamage (DamageInfo dmg, vec2 pos, vec2 dir) override
bool IsDead () override
void Update (int dt)
vec4 GetOverlayColor ()
bool Ricochets () override
Private Attributes
UnitPtr m_unit
SoundEvent m_breakSound
int m_delay
int m_delayC
string m_delayScene
CustomUnitScene m_delaySceneC
array< IEffect@> m_effects
GoreSpawner m_gore
UnitProducer m_corpse
float m_dmgColor = 0.0
bool m_showDmgColor
Detailed Description
Definition at line 1 of file DelayedBreakable.as.
Constructor & Destructor Documentation
DelayedBreakable()
DelayedBreakable::DelayedBreakable (UnitPtr unit, SValue & params) inline private
Definition at line 19 of file DelayedBreakable.as.
References LoadEffects(), LoadGore(), m_breakSound, m_corpse, m_delay, m_delayScene, m_delaySceneC, m_effects, m_gore, m_unit, and unit.
     {
         m_unit = unit;
         @m_breakSound = Resources::GetSoundEvent(GetParamString(unit, params, "break-sound", false));
         @m_gore = LoadGore(GetParamString(unit, params, "gore", false));
         m_delay = GetParamInt(unit, params, "delay");
         int delayRandomMax = GetParamInt(unit, params, "delay-random", false);
         if (delayRandomMax > 0)
             m_delay += randi(delayRandomMax);
         m_delayScene = GetParamString(unit, params, "delay-scene", false);
         @m_delaySceneC = CustomUnitScene();
         @m_corpse = Resources::GetUnitProducer(GetParamString(unit, params, "corpse", false));
         @m_effects = LoadEffects(unit, params);
         m_unit.SetUpdateDistanceLimit(300);
     }
Member Function Documentation
Damage()
int DelayedBreakable::Damage (DamageInfo dmg, vec2 pos, vec2 dir) inline override private
Definition at line 83 of file DelayedBreakable.as.
References DamageInfo::Attacker, DamageInfo::Damage, m_unit, UnitHandler::NetSendUnitDamaged(), and SetDelayed().
     {
         m_unit.SetUpdateDistanceLimit(0);
         SetDelayed();
         UnitHandler::NetSendUnitDamaged(m_unit, int(dmg.Damage), pos, dir, dmg.Attacker);
         return dmg.Damage;
     }
DamageEffects()
void DelayedBreakable::DamageEffects () inline private
Definition at line 40 of file DelayedBreakable.as.
References ApplyEffects(), g_scene, IsNetsyncedExistance(), m_breakSound, m_corpse, m_effects, m_gore, m_unit, PlaySound3D(), and xy().
Referenced by UnitHandler::UnitDelayedBreakable(), and Update().
     {
         if (!m_unit.IsValid() || m_unit.IsDestroyed() || m_unit.GetPhysicsBody() is null)
             return;
         PlaySound3D(m_breakSound, m_unit.GetPosition());
         if (m_gore !is null)
             m_gore.OnDeath(1, xy(m_unit.GetPosition()));
         bool netsynced = IsNetsyncedExistance(m_unit.GetUnitProducer().GetNetSyncMode());
         if (!netsynced || Network::IsServer())
             m_unit.Destroy();
         ApplyEffects(m_effects, null, m_unit, xy(m_unit.GetPosition()), vec2(), 1.0, !Network::IsServer());
         bool netsyncedCorpse = m_corpse !is null && IsNetsyncedExistance(m_corpse.GetNetSyncMode());
         if (Network::IsServer())
         {
             if (m_corpse !is null)
                 m_corpse.Produce(g_scene, m_unit.GetPosition());
         }
         else if (!netsyncedCorpse && m_corpse !is null)
             m_corpse.Produce(g_scene, m_unit.GetPosition());
         @m_corpse = null;
     }
GetOverlayColor()
vec4 DelayedBreakable::GetOverlayColor () inline private
Definition at line 129 of file DelayedBreakable.as.
References m_dmgColor.
     {
         return vec4(1, 1, 1, 0.5 * m_dmgColor);
     }
IsDead()
bool DelayedBreakable::IsDead () inline override private
Definition at line 102 of file DelayedBreakable.as.
References m_unit.
     {
         return !m_unit.IsValid();
     }
NetDamage()
void DelayedBreakable::NetDamage (DamageInfo dmg, vec2 pos, vec2 dir) inline override private
Definition at line 94 of file DelayedBreakable.as.
References m_dmgColor, m_showDmgColor, and SetDelayed().
     {
         if (m_showDmgColor)
             m_dmgColor = 1.0;
         SetDelayed();
     }
Ricochets()
bool DelayedBreakable::Ricochets () inline override private
Definition at line 134 of file DelayedBreakable.as.
 { return false; }
SetDelayed()
void DelayedBreakable::SetDelayed () inline private
Definition at line 68 of file DelayedBreakable.as.
References m_delay, m_delayC, m_delayScene, m_delaySceneC, m_dmgColor, m_showDmgColor, and m_unit.
Referenced by Damage(), and NetDamage().
     {
         if (m_showDmgColor)
             m_dmgColor = 1.0;
         if (m_delayC > 0)
             return;
         m_delayC = m_delay;
         m_delaySceneC.AddScene(m_unit.GetCurrentUnitScene(), 0, vec2(), 0, 0);
         m_delaySceneC.AddScene(m_unit.GetUnitScene(m_delayScene), 0, vec2(), 0, 0);
         m_unit.SetUnitScene(m_delaySceneC, true);
     }
Update()
void DelayedBreakable::Update (int dt) inline private
Definition at line 107 of file DelayedBreakable.as.
References DamageEffects(), m_delayC, m_dmgColor, and m_unit.
     {
         if (!m_unit.IsValid())
             return;
         if (m_delayC > 0 && Network::IsServer())
         {
             m_delayC -= dt;
             if (m_delayC <= 0)
             {
                 (Network::Message("UnitDelayedBreakable") << m_unit).SendToAll();
                 DamageEffects();
             }
         }
         if (m_unit.IsDestroyed())
             return;
         if (m_dmgColor > 0)
             m_dmgColor -= dt / 100.0;
     }
Member Data Documentation
m_breakSound
SoundEvent DelayedBreakable::m_breakSound private
Definition at line 5 of file DelayedBreakable.as.
Referenced by DamageEffects(), and DelayedBreakable().
m_corpse
UnitProducer DelayedBreakable::m_corpse private
Definition at line 14 of file DelayedBreakable.as.
Referenced by DamageEffects(), and DelayedBreakable().
m_delay
int DelayedBreakable::m_delay private
Definition at line 7 of file DelayedBreakable.as.
Referenced by DelayedBreakable(), and SetDelayed().
m_delayC
int DelayedBreakable::m_delayC private
Definition at line 8 of file DelayedBreakable.as.
Referenced by SetDelayed(), and Update().
m_delayScene
string DelayedBreakable::m_delayScene private
Definition at line 9 of file DelayedBreakable.as.
Referenced by DelayedBreakable(), and SetDelayed().
m_delaySceneC
CustomUnitScene DelayedBreakable::m_delaySceneC private
Definition at line 10 of file DelayedBreakable.as.
Referenced by DelayedBreakable(), and SetDelayed().
m_dmgColor
float DelayedBreakable::m_dmgColor = 0.0 private
Definition at line 16 of file DelayedBreakable.as.
Referenced by GetOverlayColor(), NetDamage(), SetDelayed(), and Update().
m_effects
array<IEffect@> DelayedBreakable::m_effects private
Definition at line 12 of file DelayedBreakable.as.
Referenced by DamageEffects(), and DelayedBreakable().
m_gore
GoreSpawner DelayedBreakable::m_gore private
Definition at line 13 of file DelayedBreakable.as.
Referenced by DamageEffects(), and DelayedBreakable().
m_showDmgColor
bool DelayedBreakable::m_showDmgColor private
Definition at line 17 of file DelayedBreakable.as.
Referenced by NetDamage(), and SetDelayed().
m_unit
UnitPtr DelayedBreakable::m_unit private
Definition at line 3 of file DelayedBreakable.as.
Referenced by Damage(), DamageEffects(), DelayedBreakable(), IsDead(), SetDelayed(), and Update().
The documentation for this class was generated from the following file:
scripts/Behaviors/Items/DelayedBreakable.as