HoHDocs: GuildHallMenu Class Reference
GuildHallMenu Class Reference
Private Member Functions
GuildHallMenu (GUIBuilder@ b)
bool BlocksLower () override
string GetScriptID () override
void SetTab (string id)
void Show () override
void Close () override
void Update (int dt) override
void Draw (SpriteBatch &sb, int idt) override
void AfterUpdate ()
void OnFunc (Widget@ sender, string name) override
Private Attributes
MenuTabSystem m_tabSystem
Detailed Description
Definition at line 1 of file GuildHallMenu.as.
Constructor & Destructor Documentation
GuildHallMenu()
GuildHallMenu::GuildHallMenu (GUIBuilder@ b) inline private
Definition at line 5 of file GuildHallMenu.as.
References MenuTabSystem::AddTab(), GuildHallItemiaryTab(), and m_tabSystem.
     {
         super(b, "gui/guildhallmenu.gui");
         @m_tabSystem = MenuTabSystem(this);
         m_tabSystem.AddTab(GuildHallStatsTab());
         m_tabSystem.AddTab(GuildHallAccomplishmentsTab());
         m_tabSystem.AddTab(GuildHallBeastiaryTab());
         m_tabSystem.AddTab(GuildHallItemiaryTab());
     }
Member Function Documentation
AfterUpdate()
void GuildHallMenu::AfterUpdate () inline private
Definition at line 77 of file GuildHallMenu.as.
References MenuTabSystem::AfterUpdate(), m_tabSystem, and UserWindow::m_visible.
     {
         if (m_visible)
             m_tabSystem.AfterUpdate();
     }
BlocksLower()
bool GuildHallMenu::BlocksLower () inline override private
Definition at line 17 of file GuildHallMenu.as.
     {
         return true;
     }
Close()
void GuildHallMenu::Close () inline override private
Definition at line 47 of file GuildHallMenu.as.
References UserWindow::Close(), MenuTabSystem::Close(), m_tabSystem, UserWindow::m_visible, and PauseGame().
Referenced by OnFunc().
     {
         if (!m_visible)
             return;
         m_tabSystem.Close();
         UserWindow::Close();
         PauseGame(false, true);
     }
Draw()
void GuildHallMenu::Draw (SpriteBatch & sb, int idt) inline override private
Definition at line 67 of file GuildHallMenu.as.
References UserWindow::Draw(), MenuTabSystem::Draw(), m_tabSystem, and UserWindow::m_visible.
     {
         if (!m_visible)
             return;
         UserWindow::Draw(sb, idt);
         m_tabSystem.Draw(sb, idt);
     }
GetScriptID()
string GuildHallMenu::GetScriptID () inline override private
Definition at line 22 of file GuildHallMenu.as.
 { return "guildhall"; }
OnFunc()
void GuildHallMenu::OnFunc (Widget@ sender, string name) inline override private
Definition at line 83 of file GuildHallMenu.as.
References Close(), m_tabSystem, name, UserWindow::OnFunc(), and MenuTabSystem::OnFunc().
     {
         if (name == "close")
             Close();
         else if (!m_tabSystem.OnFunc(sender, name))
             UserWindow::OnFunc(sender, name);
     }
SetTab()
void GuildHallMenu::SetTab (string id) inline private
Definition at line 24 of file GuildHallMenu.as.
References m_tabSystem, Modifiers::Set, and MenuTabSystem::SetTab().
Referenced by Show().
     {
         GlobalCache::Set("guildhallmenu-tab", id);
         m_tabSystem.SetTab(id);
     }
Show()
void GuildHallMenu::Show () inline override private
Definition at line 31 of file GuildHallMenu.as.
References Get(), UserWindow::m_visible, PauseGame(), SetTab(), and UserWindow::Show().
     {
         if (m_visible)
             return;
         UserWindow::Show();
         PauseGame(true, true);
         string startTab = GlobalCache::Get("guildhallmenu-tab");
         if (startTab == "")
             startTab = "stats";
         SetTab(startTab);
     }
Update()
void GuildHallMenu::Update (int dt) inline override private
Definition at line 59 of file GuildHallMenu.as.
References m_tabSystem, UserWindow::m_visible, UserWindow::Update(), and MenuTabSystem::Update().
     {
         if (m_visible)
             m_tabSystem.Update(dt);
         UserWindow::Update(dt);
     }
Member Data Documentation
m_tabSystem
MenuTabSystem GuildHallMenu::m_tabSystem private
Definition at line 3 of file GuildHallMenu.as.
Referenced by AfterUpdate(), Close(), Draw(), GuildHallMenu(), OnFunc(), SetTab(), and Update().
The documentation for this class was generated from the following file:
scripts/GUI/GuildHallMenu.as