HoHDocs: Upgrades::ItemUpgradeStep Class Reference
Upgrades::ItemUpgradeStep Class Reference
Private Member Functions
ItemUpgradeStep (ActorItem@ item, Upgrade@ upgrade, SValue@ params, int level)
string GetTooltipTitle () override
string GetTooltipDescription () override
void DrawShopIcon (ShopButtonWidget@ widget, SpriteBatch &sb, vec2 pos, vec2 size, vec4 color) override
float PayScale () override
void PayForUpgrade (PlayerRecord@ record) override
bool IsOwned (PlayerRecord@ record) override
bool IsRestricted () override
bool ApplyNow (PlayerRecord@ record) override
Private Attributes
ActorItem m_item
Detailed Description
Definition at line 3 of file ItemUpgradeStep.as.
Constructor & Destructor Documentation
ItemUpgradeStep()
Upgrades::ItemUpgradeStep::ItemUpgradeStep (ActorItem@ item, Upgrade@ upgrade, SValue@ params, int level) inline private
Definition at line 7 of file ItemUpgradeStep.as.
References Upgrades::UpgradeStep::m_costGold, and m_item.
         {
             super(upgrade, params, level);
             @m_item = item;
             m_costGold = m_item.cost;
         }
Member Function Documentation
ApplyNow()
bool Upgrades::ItemUpgradeStep::ApplyNow (PlayerRecord@ record) inline override private
Definition at line 103 of file ItemUpgradeStep.as.
References m_item, and Upgrades::UpgradeStep::m_upgrade.
         {
             auto player = cast<Player>(record.actor);
             if (player is null)
                 return false;
             cast<ItemUpgrade>(m_upgrade).SetApplied(record);
             player.AddItem(m_item);
             return true;
         }
DrawShopIcon()
void Upgrades::ItemUpgradeStep::DrawShopIcon (ShopButtonWidget@ widget, SpriteBatch & sb, vec2 pos, vec2 size, vec4 color) inline override private
Definition at line 34 of file ItemUpgradeStep.as.
References Common, g_menuTime, GetItemQualityColor(), GetLocalPlayerRecord(), m_item, ShopButtonWidget::m_itemDot, ShopButtonWidget::m_itemPlus, and SetItemColorString.
         {
             if (m_item.icon !is null)
             {
                 int iconWidth = m_item.icon.GetWidth();
                 int iconHeight = m_item.icon.GetHeight();
                 m_item.icon.Draw(sb, vec2(
                     pos.x + size.x / 2 - iconWidth / 2,
                     pos.y + size.y / 3 - iconHeight / 2
                 ), g_menuTime, color);
             }
             int dotX = int(size.x - widget.m_itemDot.GetWidth() - 2);
             int dotY = int(size.y - widget.m_itemDot.GetHeight() - 2);
             if (m_item.quality != ActorItemQuality::Common)
             {
                 vec4 colorDot = GetItemQualityColor(m_item.quality);
                 vec2 dotPos = pos + vec2(dotX, dotY);
                 sb.DrawSprite(dotPos, widget.m_itemDot, g_menuTime, colorDot);
                 dotX -= widget.m_itemDot.GetWidth();
             }
             if (m_item.set !is null)
             {
                 vec4 colorDot = ParseColorRGBA("#" + SetItemColorString + "FF");
                 vec2 dotPos = pos + vec2(dotX, dotY);
                 sb.DrawSprite(dotPos, widget.m_itemDot, g_menuTime, colorDot);
                 dotX -= widget.m_itemDot.GetWidth();
             }
             auto record = GetLocalPlayerRecord();
             if (record.itemForgeAttuned.find(m_item.idHash) != -1)
                 sb.DrawSprite(pos, widget.m_itemPlus, g_menuTime);
         }
GetTooltipDescription()
string Upgrades::ItemUpgradeStep::GetTooltipDescription () inline override private
Definition at line 21 of file ItemUpgradeStep.as.
References GetItemSetColorString(), GetLocalPlayerRecord(), Upgrades::UpgradeStep::GetTooltipDescription(), and m_item.
         {
             string ret = UpgradeStep::GetTooltipDescription();
             if (m_item.set !is null)
             {
                 ret += "\n\n";
                 ret += GetItemSetColorString(GetLocalPlayerRecord(), m_item);
             }
             return ret;
         }
GetTooltipTitle()
string Upgrades::ItemUpgradeStep::GetTooltipTitle () inline override private
Definition at line 16 of file ItemUpgradeStep.as.
References GetItemQualityColorString(), Upgrades::UpgradeStep::GetTooltipTitle(), and m_item.
         {
             return "\\c" + GetItemQualityColorString(m_item.quality) + UpgradeStep::GetTooltipTitle();
         }
IsOwned()
bool Upgrades::ItemUpgradeStep::IsOwned (PlayerRecord@ record) inline override private
Definition at line 90 of file ItemUpgradeStep.as.
         {
             return false;
         }
IsRestricted()
bool Upgrades::ItemUpgradeStep::IsRestricted () inline override private
Definition at line 95 of file ItemUpgradeStep.as.
References GetLocalPlayerRecord(), Upgrades::UpgradeStep::IsRestricted(), and m_item.
         {
             if (GetLocalPlayerRecord().items.find(m_item.id) != -1)
                 return true;
             return UpgradeStep::IsRestricted();
         }
PayForUpgrade()
void Upgrades::ItemUpgradeStep::PayForUpgrade (PlayerRecord@ record) inline override private
Definition at line 79 of file ItemUpgradeStep.as.
References Stats::Add(), Upgrades::UpgradeStep::CanAfford(), GetItemQualityName(), m_item, and Upgrades::UpgradeStep::PayForUpgrade().
         {
             if (CanAfford(record))
             {
                 Stats::Add("items-bought", 1, record);
                 Stats::Add("items-bought-" + GetItemQualityName(m_item.quality), 1, record);
             }
             UpgradeStep::PayForUpgrade(record);
         }
PayScale()
float Upgrades::ItemUpgradeStep::PayScale () inline override private
Definition at line 71 of file ItemUpgradeStep.as.
References GetLocalPlayerRecord().
         {
             float priceScale = 1.0f;
             if (GetLocalPlayerRecord().items.find("vendors-coin") != -1)
                 priceScale *= 0.75f;
             return priceScale;
         }
Member Data Documentation
m_item
ActorItem Upgrades::ItemUpgradeStep::m_item private
Definition at line 5 of file ItemUpgradeStep.as.
Referenced by ApplyNow(), DrawShopIcon(), GetTooltipDescription(), GetTooltipTitle(), IsRestricted(), ItemUpgradeStep(), and PayForUpgrade().
The documentation for this class was generated from the following file:
scripts/Upgrades/Steps/ItemUpgradeStep.as