HoHDocs: Menu::GraphicsMenu Class Reference
Menu::GraphicsMenu Class Reference
Private Member Functions
GraphicsMenu (MenuProvider@ provider)
void Update (int dt) override
void OnFunc (Widget@ sender, string name) override
Detailed Description
Definition at line 3 of file GraphicsMenu.as.
Constructor & Destructor Documentation
GraphicsMenu()
Menu::GraphicsMenu::GraphicsMenu (MenuProvider@ provider) inline private
Definition at line 5 of file GraphicsMenu.as.
         {
             super(provider);
             //TODO: Setting this menu as a popup messes up the preview panel
             //m_isPopup = true;
         }
Member Function Documentation
OnFunc()
void Menu::GraphicsMenu::OnFunc (Widget@ sender, string name) inline override private
Definition at line 43 of file GraphicsMenu.as.
References Menu::Menu::m_provider, name, Menu::SubOptionsMenu::OnFunc(), and Menu::Menu::OpenMenu().
         {
             array<string> parse = name.split(" ");
             if (parse[0] == "cfg-resolution")
                 OpenMenu(Menu::ResolutionsMenu(m_provider), "gui/main_menu/options_resolution.gui");
             else if (parse[0] == "accept")
             {
                 Config::SaveVar("v_resolution");
                 SubOptionsMenu::OnFunc(sender, "accept");
             }
             else
                 SubOptionsMenu::OnFunc(sender, name);
         }
Update()
void Menu::GraphicsMenu::Update (int dt) inline override private
Definition at line 13 of file GraphicsMenu.as.
References Menu::Backdrop(), g_gameMode, g_menuAnchors, Widget::GetRectangle(), MenuProvider::m_backdrop, Menu::Menu::m_closing, Menu::Menu::m_provider, m_widget, WorldScript::MenuAnchorPoint::Position, Update(), and xy().
         {
             SubOptionsMenu::Update(dt);
             Menu::Backdrop@ backdrop = m_provider.m_backdrop;
             if (backdrop !is null)
             {
                 Widget@ wPreview = m_widget.GetWidgetById("preview");
                 if (wPreview !is null)
                 {
                     backdrop.m_clipping = !m_closing;
                     backdrop.m_clippingRect = wPreview.GetRectangle();
                 }
             }
             WorldScript::MenuAnchorPoint@ map = null;
             for (uint i = 0; i < g_menuAnchors.length(); i++)
             {
                 if (g_menuAnchors[i].GraphicsOptions)
                     @map = g_menuAnchors[i];
             }
             if (map is null)
                 return;
             MainMenu@ gm = cast<MainMenu>(g_gameMode);
             gm.m_camPos = xy(map.Position);
         }
The documentation for this class was generated from the following file:
scripts/GUI/Menus/GraphicsMenu.as