HoHDocs: Item Class Reference
Item Class Reference
Private Member Functions
Item (UnitPtr unit, SValue &params)
void Initialize (ActorItem@ item)
SValue Save ()
void PostLoad (SValue@ data)
void Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther)
void EndCollision (UnitPtr unit, Fixture@ fxSelf, Fixture@ fxOther)
UnitPtr GetUseUnit ()
bool CanUse (PlayerBase@ player)
void Use (PlayerBase@ player)
void NetUse (PlayerHusk@ player)
UsableIcon GetIcon (Player@ player)
int UsePriority (IUsable@ other)
Private Attributes
UnitPtr m_unit
ActorItem m_item
Detailed Description
Definition at line 1 of file Item.as.
Constructor & Destructor Documentation
Item()
Item::Item (UnitPtr unit, SValue & params) inline private
Definition at line 6 of file Item.as.
References g_items, Initialize(), m_unit, ParseActorItemQuality(), quality, ActorItems::TakeRandomItem(), and unit.
     {
         m_unit = unit;
         auto quality = ParseActorItemQuality(GetParamString(unit, params, "quality", false, "common"));
         bool specific = GetParamBool(unit, params, "specific", false, false);
         if (!specific)
             Initialize(g_items.TakeRandomItem(quality));
     }
Member Function Documentation
CanUse()
bool Item::CanUse (PlayerBase@ player) inline private
Definition at line 102 of file Item.as.
     {
         return true;
     }
Collide()
void Item::Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther) inline private
Definition at line 77 of file Item.as.
References Player::AddUsable(), and unit.
     {
         Player@ player = cast<Player>(unit.GetScriptBehavior());
         if (player is null)
             return;
         if (fxSelf.IsSensor())
             player.AddUsable(this);
     }
EndCollision()
void Item::EndCollision (UnitPtr unit, Fixture@ fxSelf, Fixture@ fxOther) inline private
Definition at line 87 of file Item.as.
References Player::RemoveUsable(), and unit.
     {
         Player@ player = cast<Player>(unit.GetScriptBehavior());
         if (player is null)
             return;
         if (fxSelf.IsSensor())
             player.RemoveUsable(this);
     }
GetIcon()
UsableIcon Item::GetIcon (Player@ player) inline private
Definition at line 117 of file Item.as.
References Generic.
     {
         return UsableIcon::Generic;
     }
GetUseUnit()
UnitPtr Item::GetUseUnit () inline private
Definition at line 97 of file Item.as.
References m_unit.
     {
         return m_unit;
     }
Initialize()
void Item::Initialize (ActorItem@ item) inline private
Definition at line 17 of file Item.as.
References Common, Epic, Legendary, m_item, m_unit, Rare, ScriptSprite(), and Uncommon.
Referenced by Item(), and PostLoad().
     {
         if (item is null)
             return;
         @m_item = item;
         ScriptSprite@ sprite = m_item.icon;
         array<vec4> frames;
         array<int> frameTimes = { 100 };
         for (uint i = 0; i < sprite.m_frames.length(); i++)
             frames.insertLast(sprite.m_frames[i].frame);
         Material@ mat;
         if (m_item.quality == ActorItemQuality::Common)
             @mat = Resources::GetMaterial("items/items.mats:item-common");
         else if (m_item.quality == ActorItemQuality::Uncommon)
             @mat = Resources::GetMaterial("items/items.mats:item-uncommon");
         else if (m_item.quality == ActorItemQuality::Rare)
             @mat = Resources::GetMaterial("items/items.mats:item-rare");
         else if (m_item.quality == ActorItemQuality::Epic)
             @mat = Resources::GetMaterial("items/items.mats:item-epic");
         else if (m_item.quality == ActorItemQuality::Legendary)
             @mat = Resources::GetMaterial("items/items.mats:item-legendary");
         CustomUnitScene unitScene;
         unitScene.AddScene(m_unit.GetUnitScene("shared"), 0, vec2(), 0, 0);
         unitScene.AddSprite(CustomUnitSprite(vec2(6, 6), sprite.m_texture, mat, frames, frameTimes, true, 0), 0, vec2(), 0, 0);
         m_unit.SetUnitScene(unitScene, false);
     }
NetUse()
void Item::NetUse (PlayerHusk@ player) inline private
Definition at line 113 of file Item.as.
     {
     }
PostLoad()
void Item::PostLoad (SValue@ data) inline private
Definition at line 62 of file Item.as.
References g_items, Initialize(), m_item, m_unit, and ActorItems::TakeItem().
     {
         if (data.GetType() == SValueType::Array)
         {
             auto arr = data.GetArray();
             Initialize(g_items.TakeItem(arr[0].GetString()));
             m_unit.SetUnitScene(arr[1].GetString(), false);
         }
         else if (data.GetType() == SValueType::String)
             Initialize(g_items.TakeItem(data.GetString()));
         if (m_item is null)
             m_unit.Destroy();
     }
Save()
SValue Item::Save () inline private
Definition at line 52 of file Item.as.
References m_item, and m_unit.
     {
         SValueBuilder sval;
         sval.PushArray();
         sval.PushString(m_item.id);
         sval.PushString(m_unit.GetCurrentUnitScene().GetName());
         sval.PopArray();
         return sval.Build();
     }
Use()
void Item::Use (PlayerBase@ player) inline private
Definition at line 107 of file Item.as.
References GiveItemImpl(), m_item, and m_unit.
     {
         m_unit.Destroy();
         GiveItemImpl(m_item, player, true);
     }
UsePriority()
int Item::UsePriority (IUsable@ other) inline private
Definition at line 122 of file Item.as.
 { return 1; }
Member Data Documentation
m_item
ActorItem Item::m_item private
Definition at line 4 of file Item.as.
Referenced by Initialize(), PostLoad(), Save(), and Use().
m_unit
UnitPtr Item::m_unit private
Definition at line 3 of file Item.as.
Referenced by GetUseUnit(), Initialize(), Item(), PostLoad(), Save(), and Use().
The documentation for this class was generated from the following file:
scripts/Behaviors/Items/Item.as