HoHDocs: WorldScript::Teleport Class Reference
WorldScript::Teleport Class Reference
Private Member Functions
void Initialize ()
vec3 GetPosition ()
void OnEnter (UnitPtr unit, vec2 pos, vec2 normal)
void OnEnabledChanged (bool enabled)
SValue ServerExecute ()
Private Attributes
vec3 Position
array< CollisionArea@> Areas
string ScriptLinkTarget
AreaFilter Filter
UnitSource Teleported
Detailed Description
Definition at line 4 of file Teleport.as.
Member Function Documentation
GetPosition()
vec3 WorldScript::Teleport::GetPosition () inline private
Definition at line 29 of file Teleport.as.
References g_scene, Position, and ScriptLinkTarget.
Referenced by OnEnabledChanged(), and OnEnter().
         {
             if (ScriptLinkTarget != "")
             {
                 auto res = g_scene.FetchAllWorldScriptsWithComment("ScriptLink", ScriptLinkTarget);
                 if (res.length() > 0)
                 {
                     int startIdx = randi(res.length());
                     for (uint i = 0; i < res.length(); i++)
                     {
                         auto script = res[(startIdx + i) % res.length()];
                         if (!script.CanExecuteNow())
                             continue;
                         script.Execute();
                         return script.GetUnit().GetPosition();
                     }
                 }
             }
             return Position;
         }
Initialize()
void WorldScript::Teleport::Initialize () inline private
Definition at line 20 of file Teleport.as.
References Areas.
         {
             if (Network::IsServer())
             {
                 for (uint i = 0; i < Areas.length(); i++)
                     Areas[i].AddOnEnter(this, "OnEnter");
             }
         }
OnEnabledChanged()
void WorldScript::Teleport::OnEnabledChanged (bool enabled) inline private
Definition at line 72 of file Teleport.as.
References ApplyAreaFilter(), Areas, Filter, g_scene, GetPosition(), Teleported, unit, and xy().
         {
             if (!enabled)
                 return;
             if (!Network::IsServer())
                 return;
             auto script = WorldScript::GetWorldScript(g_scene, this);
             for (uint i = 0; i < Areas.length(); i++)
             {
                 auto units = Areas[i].FetchAllInside(g_scene);
                 for (uint j = 0; j < units.length; j++)
                 {
                     UnitPtr unit = units[j];
                     if (!ApplyAreaFilter(unit, Filter))
                         continue;
                     Teleported.Replace(unit);
                     auto telPos = GetPosition();
                     (Network::Message("UnitTeleported") << unit << xy(telPos)).SendToAll();
                     unit.SetPosition(telPos);
                     script.Execute();
                 }
             }
         }
OnEnter()
void WorldScript::Teleport::OnEnter (UnitPtr unit, vec2 pos, vec2 normal) inline private
Definition at line 52 of file Teleport.as.
References ApplyAreaFilter(), Filter, g_scene, GetPosition(), Teleported, unit, and xy().
         {
             if (!Network::IsServer())
                 return;
             auto ws = WorldScript::GetWorldScript(g_scene, this);
             if (!ws.IsEnabled() || ws.GetTriggerTimes() == 0)
                 return;
             if (!ApplyAreaFilter(unit, Filter))
                 return;
             Teleported.Replace(unit);
             auto telPos = GetPosition();
             (Network::Message("UnitTeleported") << unit << xy(telPos)).SendToAll();
             unit.SetPosition(telPos);
             ws.Execute();
         }
ServerExecute()
SValue WorldScript::Teleport::ServerExecute () inline private
Definition at line 101 of file Teleport.as.
         {
             return null;
         }
Member Data Documentation
Areas
array<CollisionArea@> WorldScript::Teleport::Areas private
Definition at line 9 of file Teleport.as.
Referenced by Initialize(), and OnEnabledChanged().
Filter
AreaFilter WorldScript::Teleport::Filter private
Definition at line 15 of file Teleport.as.
Referenced by OnEnabledChanged(), and OnEnter().
Position
vec3 WorldScript::Teleport::Position private
Definition at line 6 of file Teleport.as.
Referenced by GetPosition().
ScriptLinkTarget
string WorldScript::Teleport::ScriptLinkTarget private
Definition at line 12 of file Teleport.as.
Referenced by GetPosition().
Teleported
UnitSource WorldScript::Teleport::Teleported private
Definition at line 17 of file Teleport.as.
Referenced by OnEnabledChanged(), and OnEnter().
The documentation for this class was generated from the following file:
scripts/WorldScript/Teleport.as