HoHDocs: WorldScript::UseTrigger Class Reference
WorldScript::UseTrigger Class Reference
Private Member Functions
void Initialize ()
Player GetPlayer (UnitPtr unit)
void OnEnter (UnitPtr unit, vec2 pos, vec2 normal)
void OnExit (UnitPtr unit)
SValue ServerExecute ()
UnitPtr GetUseUnit ()
bool CanUse (PlayerBase@ player)
void Use (PlayerBase@ player)
void NetUse (PlayerHusk@ player)
UsableIcon GetIcon (Player@ player)
int UsePriority (IUsable@ other)
Private Attributes
bool Enabled
array< CollisionArea@> Areas
UsableIcon Icon
UsableIcon IconDisabled
bool OnlyHost
int Priority
UnitSource User
Detailed Description
Definition at line 4 of file UseTrigger.as.
Member Function Documentation
CanUse()
bool WorldScript::UseTrigger::CanUse (PlayerBase@ player) inline private
Definition at line 72 of file UseTrigger.as.
References g_scene, PlayerBase::m_record, and OnlyHost.
Referenced by GetIcon().
         {
             if (OnlyHost && player.m_record.peer != 0)
                 return false;
             auto ws = WorldScript::GetWorldScript(g_scene, this);
             if (!ws.IsEnabled())
                 return false;
             if (!ws.CanExecuteNow())
                 return false;
             return true;
         }
GetIcon()
UsableIcon WorldScript::UseTrigger::GetIcon (Player@ player) inline private
Definition at line 100 of file UseTrigger.as.
References CanUse(), Icon, and IconDisabled.
         {
             if (!CanUse(player))
                 return IconDisabled;
             return Icon;
         }
GetPlayer()
Player WorldScript::UseTrigger::GetPlayer (UnitPtr unit) inline private
Definition at line 35 of file UseTrigger.as.
References unit.
Referenced by OnEnter(), and OnExit().
         {
             if (!unit.IsValid())
                 return null;
             ref@ behavior = unit.GetScriptBehavior();
             if (behavior is null)
                 return null;
             return cast<Player>(behavior);
         }
GetUseUnit()
UnitPtr WorldScript::UseTrigger::GetUseUnit () inline private
Definition at line 67 of file UseTrigger.as.
References g_scene.
         {
             return WorldScript::GetWorldScript(g_scene, this).GetUnit();
         }
Initialize()
void WorldScript::UseTrigger::Initialize () inline private
Definition at line 26 of file UseTrigger.as.
References Areas.
         {
             for (uint i = 0; i < Areas.length(); i++)
             {
                 Areas[i].AddOnEnter(this, "OnEnter");
                 Areas[i].AddOnExit(this, "OnExit");
             }
         }
NetUse()
void WorldScript::UseTrigger::NetUse (PlayerHusk@ player) inline private
Definition at line 95 of file UseTrigger.as.
References Use().
         {
             Use(player);
         }
OnEnter()
void WorldScript::UseTrigger::OnEnter (UnitPtr unit, vec2 pos, vec2 normal) inline private
Definition at line 48 of file UseTrigger.as.
References Player::AddUsable(), GetPlayer(), and unit.
         {
             Player@ plr = GetPlayer(unit);
             if (plr !is null)
                 plr.AddUsable(this);
         }
OnExit()
void WorldScript::UseTrigger::OnExit (UnitPtr unit) inline private
Definition at line 55 of file UseTrigger.as.
References GetPlayer(), Player::RemoveUsable(), and unit.
         {
             Player@ plr = GetPlayer(unit);
             if (plr !is null)
                 plr.RemoveUsable(this);
         }
ServerExecute()
SValue WorldScript::UseTrigger::ServerExecute () inline private
Definition at line 62 of file UseTrigger.as.
         {
             return null;
         }
Use()
void WorldScript::UseTrigger::Use (PlayerBase@ player) inline private
Definition at line 87 of file UseTrigger.as.
References g_scene, and User.
Referenced by NetUse().
         {
             User.Replace(player.m_unit);
             if (Network::IsServer())
                 WorldScript::GetWorldScript(g_scene, this).Execute();
         }
UsePriority()
int WorldScript::UseTrigger::UsePriority (IUsable@ other) inline private
Definition at line 108 of file UseTrigger.as.
References Priority.
 { return Priority; }
Member Data Documentation
Areas
array<CollisionArea@> WorldScript::UseTrigger::Areas private
Definition at line 9 of file UseTrigger.as.
Referenced by Initialize().
Enabled
bool WorldScript::UseTrigger::Enabled private
Definition at line 6 of file UseTrigger.as.
Icon
UsableIcon WorldScript::UseTrigger::Icon private
Definition at line 12 of file UseTrigger.as.
Referenced by GetIcon().
IconDisabled
UsableIcon WorldScript::UseTrigger::IconDisabled private
Definition at line 15 of file UseTrigger.as.
Referenced by GetIcon().
OnlyHost
bool WorldScript::UseTrigger::OnlyHost private
Definition at line 18 of file UseTrigger.as.
Referenced by CanUse().
Priority
int WorldScript::UseTrigger::Priority private
Definition at line 21 of file UseTrigger.as.
Referenced by UsePriority().
User
UnitSource WorldScript::UseTrigger::User private
Definition at line 23 of file UseTrigger.as.
Referenced by Use().
The documentation for this class was generated from the following file:
scripts/WorldScript/UseTrigger.as