HoHDocs: WorldScript::CountdownText Class Reference
WorldScript::CountdownText Class Reference
Private Member Functions
bool IsExecutable (UnitPtr unit)
void Update (int dt)
void Done ()
SValue ServerExecute ()
void ClientExecute (SValue@ val)
Private Attributes
int BeginCount
int EndCount
bool ShowLastNumber
int StepCount
int StepInterval
string Font
float AnchorX
float AnchorY
vec4 Color
SoundEvent SoundTick
SoundEvent SoundFinish
UnitFeed FinishTrigger
bool m_counting
int m_count
int m_intervalC
TextWidget m_widget
Detailed Description
Definition at line 4 of file CountdownText.as.
Member Function Documentation
ClientExecute()
void WorldScript::CountdownText::ClientExecute (SValue@ val) inline private
Definition at line 121 of file CountdownText.as.
References ServerExecute().
         {
             ServerExecute();
         }
Done()
void WorldScript::CountdownText::Done () inline private
Definition at line 82 of file CountdownText.as.
References FinishTrigger, m_counting, m_widget, PlaySound2D(), ShowLastNumber, and SoundFinish.
Referenced by Update().
         {
             PlaySound2D(SoundFinish);
             m_counting = false;
             if (!ShowLastNumber)
                 m_widget.m_visible = false;
             auto scripts = FinishTrigger.FetchAll();
             for (uint i = 0; i < scripts.length(); i++)
             {
                 auto script = WorldScript::GetWorldScript(scripts[i]);
                 if (script !is null)
                     script.Execute();
             }
         }
IsExecutable()
bool WorldScript::CountdownText::IsExecutable (UnitPtr unit) inline private
Definition at line 44 of file CountdownText.as.
References unit.
         {
             WorldScript@ script = WorldScript::GetWorldScript(unit);
             if (script is null)
                 return false;
             return script.IsExecutable();
         }
ServerExecute()
SValue WorldScript::CountdownText::ServerExecute () inline private
Definition at line 99 of file CountdownText.as.
References AnchorX, AnchorY, BeginCount, Color, Font, HUD::GetCountDown(), GetHUD(), m_count, m_counting, m_intervalC, m_widget, PlaySound2D(), TextWidget::SetColor(), TextWidget::SetFont(), TextWidget::SetText(), SoundTick, and StepInterval.
Referenced by ClientExecute().
         {
             HUD@ hud = GetHUD();
             @m_widget = hud.GetCountDown();
             if (m_widget is null)
                 return null;
             m_counting = true;
             m_count = BeginCount;
             m_intervalC = StepInterval;
             PlaySound2D(SoundTick);
             m_widget.m_visible = true;
             m_widget.m_anchor = vec2(AnchorX, AnchorY);
             m_widget.SetColor(Color);
             m_widget.SetFont(Font);
             m_widget.SetText("" + m_count);
             return null;
         }
Update()
void WorldScript::CountdownText::Update (int dt) inline private
Definition at line 53 of file CountdownText.as.
References Done(), EndCount, m_count, m_counting, m_intervalC, m_widget, PlaySound2D(), TextWidget::SetText(), ShowLastNumber, SoundTick, StepCount, and StepInterval.
         {
             if ((ShowLastNumber && m_intervalC < 0) || (!ShowLastNumber && !m_counting) || m_widget is null)
                 return;
             m_intervalC -= dt;
             if (m_intervalC <= 0)
             {
                 m_count += StepCount;
                 if (m_counting)
                     m_intervalC += StepInterval;
                 else if (ShowLastNumber)
                 {
                     m_widget.m_visible = false;
                     return;
                 }
                 m_widget.SetText("" + m_count);
                 m_widget.m_host.DoLayout();
                 if (StepCount < 0 && m_count <= EndCount)
                     Done();
                 else if (StepCount > 0 && m_count >= EndCount)
                     Done();
                 else
                     PlaySound2D(SoundTick);
             }
         }
Member Data Documentation
AnchorX
float WorldScript::CountdownText::AnchorX private
Definition at line 23 of file CountdownText.as.
Referenced by ServerExecute().
AnchorY
float WorldScript::CountdownText::AnchorY private
Definition at line 25 of file CountdownText.as.
Referenced by ServerExecute().
BeginCount
int WorldScript::CountdownText::BeginCount private
Definition at line 7 of file CountdownText.as.
Referenced by ServerExecute().
Color
vec4 WorldScript::CountdownText::Color private
Definition at line 28 of file CountdownText.as.
Referenced by ServerExecute().
EndCount
int WorldScript::CountdownText::EndCount private
Definition at line 9 of file CountdownText.as.
Referenced by Update().
FinishTrigger
UnitFeed WorldScript::CountdownText::FinishTrigger private
Definition at line 36 of file CountdownText.as.
Referenced by Done().
Font
string WorldScript::CountdownText::Font private
Definition at line 20 of file CountdownText.as.
Referenced by ServerExecute().
m_count
int WorldScript::CountdownText::m_count private
Definition at line 39 of file CountdownText.as.
Referenced by ServerExecute(), and Update().
m_counting
bool WorldScript::CountdownText::m_counting private
Definition at line 38 of file CountdownText.as.
Referenced by Done(), ServerExecute(), and Update().
m_intervalC
int WorldScript::CountdownText::m_intervalC private
Definition at line 40 of file CountdownText.as.
Referenced by ServerExecute(), and Update().
m_widget
TextWidget WorldScript::CountdownText::m_widget private
Definition at line 42 of file CountdownText.as.
Referenced by Done(), ServerExecute(), and Update().
ShowLastNumber
bool WorldScript::CountdownText::ShowLastNumber private
Definition at line 12 of file CountdownText.as.
Referenced by Done(), and Update().
SoundFinish
SoundEvent WorldScript::CountdownText::SoundFinish private
Definition at line 33 of file CountdownText.as.
Referenced by Done().
SoundTick
SoundEvent WorldScript::CountdownText::SoundTick private
Definition at line 31 of file CountdownText.as.
Referenced by ServerExecute(), and Update().
StepCount
int WorldScript::CountdownText::StepCount private
Definition at line 15 of file CountdownText.as.
Referenced by Update().
StepInterval
int WorldScript::CountdownText::StepInterval private
Definition at line 17 of file CountdownText.as.
Referenced by ServerExecute(), and Update().
The documentation for this class was generated from the following file:
scripts/WorldScript/CountdownText.as