HoHDocs: FountainShopMenuContent Class Reference
FountainShopMenuContent Class Reference
Private Member Functions
FountainShopMenuContent (ShopMenu@ shopMenu)
string GetTitle () override
void OnShow () override
void ReloadList () override
string GetGuiFilename () override
int GetFavor ()
int GetCost ()
void Deposit (int amount)
void NetDeposit (int amount)
bool CanAfford ()
void Buy ()
void NetBuy ()
array< Fountain::Effect@> GetSelectedEffects ()
bool AnyEffectSelected ()
void UpdateInterface ()
void OnFunc (Widget@ sender, string name) override
Private Attributes
ScalableSpriteIconButtonWidget m_wButton
Widget m_wTemplateWish
Widget m_wListGood
Widget m_wListBad
SpriteWidget m_wScale
TextWidget m_wPoints
TextWidget m_wGoldGain
TextWidget m_wExpMul
TextWidget m_wDepositGold
Widget m_wDepositButtons
SoundEvent m_sndLockIn
array< FavorButtonWidget@> m_arrButtons
Detailed Description
Definition at line 1 of file FountainShopMenu.as.
Constructor & Destructor Documentation
FountainShopMenuContent()
FountainShopMenuContent::FountainShopMenuContent (ShopMenu@ shopMenu) inline private
Definition at line 22 of file FountainShopMenu.as.
     {
         super(shopMenu);
     }
Member Function Documentation
AnyEffectSelected()
bool FountainShopMenuContent::AnyEffectSelected () inline private
Definition at line 266 of file FountainShopMenu.as.
References IsChecked(), and m_arrButtons.
Referenced by UpdateInterface().
     {
         for (uint i = 0; i < m_arrButtons.length(); i++)
         {
             if (m_arrButtons[i].IsChecked())
                 return true;
         }
         return false;
     }
Buy()
void FountainShopMenuContent::Buy () inline private
Definition at line 158 of file FountainShopMenu.as.
References Stats::Add(), Fountain::ApplyEffect(), CanAfford(), cost, Fountain::CurrentEffects, effect, g_allModifiers, g_gameMode, GetCost(), GetFavor(), GetLocalPlayer(), GetSelectedEffects(), m_sndLockIn, PlaySound2D(), Fountain::RefreshModifiers(), ReloadList(), and UpdateInterface().
Referenced by OnFunc().
     {
         if (!Network::IsServer())
         {
             PrintError("Not server, can't buy effects");
             return;
         }
         if (!CanAfford())
         {
             PrintError("Can't afford effects");
             return;
         }
         if (Fountain::CurrentEffects.length() > 0)
         {
             PrintError("There already are affects active");
             return;
         }
         auto gm = cast<Town>(g_gameMode);
         if (gm is null)
             return;
         auto player = GetLocalPlayer();
         int favor = GetFavor();
         int cost = GetCost();
         PlaySound2D(m_sndLockIn);
         Stats::Add("fountain-used", 1, player.m_record);
         Stats::Add("fountain-paid", cost, player.m_record);
         if (favor > 0)
             Stats::Add("fountain-favor-good", favor, player.m_record);
         else if (favor < 0)
             Stats::Add("fountain-favor-bad", -favor, player.m_record);
         gm.m_town.m_fountainGold -= cost;
         gm.m_townLocal.m_fountainGold -= cost;
         SValueBuilder builder;
         builder.PushArray();
         auto arrSelected = GetSelectedEffects();
         for (uint i = 0; i < arrSelected.length(); i++)
         {
             auto effect = arrSelected[i];
             Fountain::ApplyEffect(effect.m_idHash);
             builder.PushInteger(effect.m_idHash);
         }
         builder.PopArray();
         (Network::Message("SetFountain") << builder.Build()).SendToAll();
         Fountain::RefreshModifiers(g_allModifiers);
         player.RefreshModifiers();
         ReloadList();
         UpdateInterface();
     }
CanAfford()
bool FountainShopMenuContent::CanAfford () inline private
Definition at line 149 of file FountainShopMenu.as.
References g_gameMode, and GetCost().
Referenced by Buy(), and UpdateInterface().
     {
         auto gm = cast<Town>(g_gameMode);
         if (gm is null)
             return false;
         return gm.m_town.m_fountainGold >= GetCost();
     }
Deposit()
void FountainShopMenuContent::Deposit (int amount) inline private
Definition at line 115 of file FountainShopMenu.as.
References Stats::Add(), g_gameMode, GetLocalPlayerRecord(), and UpdateInterface().
Referenced by OnFunc().
     {
         auto gm = cast<Town>(g_gameMode);
         if (gm is null)
             return;
         if (gm.m_townLocal.m_gold < amount)
         {
             PrintError("Can't afford to deposit " + amount + " gold into fountain!");
             return;
         }
         Stats::Add("fountain-deposited", amount, GetLocalPlayerRecord());
         gm.m_townLocal.m_gold -= amount;
         gm.m_town.m_fountainGold += amount;
         if (Network::IsServer())
             gm.m_townLocal.m_fountainGold += amount;
         (Network::Message("DepositFountain") << amount).SendToAll();
         UpdateInterface();
     }
GetCost()
int FountainShopMenuContent::GetCost () inline private
Definition at line 102 of file FountainShopMenu.as.
References GetFavor().
Referenced by Buy(), CanAfford(), and UpdateInterface().
     {
         int favor = GetFavor();
         if (favor <= 0)
             return 0;
         if (favor > 20)
             return 200000000; // 200m
         return int(150 * (pow(2, favor) - 1));
     }
GetFavor()
int FountainShopMenuContent::GetFavor () inline private
Definition at line 91 of file FountainShopMenu.as.
References GetSelectedEffects().
Referenced by Buy(), and GetCost().
     {
         auto effects = GetSelectedEffects();
         int favor = 0;
         for (uint i = 0; i < effects.length(); i++)
             favor += effects[i].m_favor;
         return favor;
     }
GetGuiFilename()
string FountainShopMenuContent::GetGuiFilename () inline override private
Definition at line 86 of file FountainShopMenu.as.
     {
         return "gui/shop/fountain.gui";
     }
GetSelectedEffects()
array<Fountain::Effect@> FountainShopMenuContent::GetSelectedEffects () inline private
Definition at line 228 of file FountainShopMenu.as.
References Fountain::CurrentEffects, effect, Fountain::GetEffect(), and m_arrButtons.
Referenced by Buy(), GetFavor(), and UpdateInterface().
     {
         array<Fountain::Effect@> ret;
         if (Fountain::CurrentEffects.length() > 0)
         {
             for (uint i = 0; i < Fountain::CurrentEffects.length(); i++)
             {
                 uint id = Fountain::CurrentEffects[i];
                 auto effect = Fountain::GetEffect(id);
                 if (effect is null)
                 {
                     PrintError("Couldn't find current effect with ID " + id);
                     continue;
                 }
                 ret.insertLast(effect);
             }
             return ret;
         }
         for (uint i = 0; i < m_arrButtons.length(); i++)
         {
             auto button = m_arrButtons[i];
             if (button.IsChecked())
             {
                 auto effect = Fountain::GetEffect(button.m_value);
                 if (effect is null)
                 {
                     PrintError("Couldn't find selected effect with ID \"" + button.m_value + "\"");
                     continue;
                 }
                 ret.insertLast(effect);
             }
         }
         return ret;
     }
GetTitle()
string FountainShopMenuContent::GetTitle () inline override private
Definition at line 27 of file FountainShopMenu.as.
     {
         return Resources::GetString(".shop.fountain");
     }
NetBuy()
void FountainShopMenuContent::NetBuy () inline private
Definition at line 222 of file FountainShopMenu.as.
References ReloadList(), and UpdateInterface().
     {
         ReloadList();
         UpdateInterface();
     }
NetDeposit()
void FountainShopMenuContent::NetDeposit (int amount) inline private
Definition at line 140 of file FountainShopMenu.as.
References formatThousands(), g_gameMode, m_wDepositGold, and TextWidget::SetText().
Referenced by GameModeHandler::DepositFountain().
     {
         auto gm = cast<Town>(g_gameMode);
         if (gm is null)
             return;
         m_wDepositGold.SetText(formatThousands(gm.m_town.m_fountainGold));
     }
OnFunc()
void FountainShopMenuContent::OnFunc (Widget@ sender, string name) inline override private
Definition at line 345 of file FountainShopMenu.as.
References Buy(), ShopMenu::Close(), Deposit(), ShopMenuContent::m_shopMenu, name, and UpdateInterface().
     {
         if (name == "close")
             m_shopMenu.Close();
         else if (name == "wishes-changed")
             UpdateInterface();
         else if (name == "buy")
             Buy();
         else if (name == "deposit")
         {
             auto wButton = cast<ScalableSpriteButtonWidget>(sender);
             int buttonValue = parseInt(wButton.m_value);
             Deposit(buttonValue);
         }
     }
OnShow()
void FountainShopMenuContent::OnShow () inline override private
Definition at line 32 of file FountainShopMenu.as.
References Widget::GetWidgetById(), m_sndLockIn, m_wButton, m_wDepositButtons, m_wDepositGold, m_wExpMul, m_wGoldGain, ShopMenuContent::m_widget, m_wListBad, m_wListGood, m_wPoints, m_wScale, m_wTemplateWish, ReloadList(), and UpdateInterface().
     {
         @m_wButton = cast<ScalableSpriteIconButtonWidget>(m_widget.GetWidgetById("button"));
         @m_wTemplateWish = m_widget.GetWidgetById("wish-template");
         @m_wListGood = m_widget.GetWidgetById("wishes-good");
         @m_wListBad = m_widget.GetWidgetById("wishes-bad");
         @m_wScale = cast<SpriteWidget>(m_widget.GetWidgetById("scale"));
         @m_wPoints = cast<TextWidget>(m_widget.GetWidgetById("favor-points"));
         @m_wGoldGain = cast<TextWidget>(m_widget.GetWidgetById("gold-gain"));
         @m_wExpMul = cast<TextWidget>(m_widget.GetWidgetById("exp-mul"));
         @m_wDepositGold = cast<TextWidget>(m_widget.GetWidgetById("deposited-gold"));
         @m_wDepositButtons = m_widget.GetWidgetById("deposit-buttons");
         @m_sndLockIn = Resources::GetSoundEvent("event:/ui/lockin");
         ReloadList();
         UpdateInterface();
     }
ReloadList()
void FountainShopMenuContent::ReloadList () inline override private
Definition at line 55 of file FountainShopMenu.as.
References Widget::AddChild(), Fountain::AvailableEffects, Widget::ClearChildren(), Widget::Clone(), Fountain::CurrentEffects, effect, Fountain::HasEffect(), m_arrButtons, Widget::m_children, ShopMenu::m_currentShopLevel, ShopMenuContent::m_shopMenu, m_wListBad, m_wListGood, m_wTemplateWish, and Widget::SetID().
Referenced by Buy(), NetBuy(), and OnShow().
     {
         m_wListBad.ClearChildren();
         m_wListGood.ClearChildren();
         for (uint i = 0; i < Fountain::AvailableEffects.length(); i++)
         {
             auto effect = Fountain::AvailableEffects[i];
             if (Fountain::CurrentEffects.length() > 0 && !Fountain::HasEffect(effect.m_idHash))
                 continue;
             Widget@ wList;
             if (effect.m_favor < 0)
                 @wList = m_wListBad;
             else if (effect.m_favor > 0)
                 @wList = m_wListGood;
             auto wNewButton = cast<FavorButtonWidget>(m_wTemplateWish.Clone());
             wNewButton.SetID("");
             wNewButton.m_visible = true;
             wNewButton.Set(effect, m_shopMenu.m_currentShopLevel);
             wList.AddChild(wNewButton);
             m_arrButtons.insertLast(wNewButton);
         }
         m_wListGood.m_children.sortAsc();
         m_wListBad.m_children.sortDesc();
     }
UpdateInterface()
void FountainShopMenuContent::UpdateInterface () inline private
Definition at line 276 of file FountainShopMenu.as.
References AnyEffectSelected(), CanAfford(), Fountain::CurrentEffects, ShopMenu::DoLayout(), formatThousands(), g_gameMode, GetCost(), GetSelectedEffects(), Widget::m_children, ScalableSpriteIconButtonWidget::m_iconVisible, ShopMenuContent::m_shopMenu, m_wButton, m_wDepositButtons, m_wDepositGold, m_wExpMul, m_wGoldGain, m_wPoints, m_wScale, TextWidget::SetColor(), SpriteWidget::SetSprite(), and TextWidget::SetText().
Referenced by Buy(), Deposit(), NetBuy(), OnFunc(), and OnShow().
     {
         auto gm = cast<Campaign>(g_gameMode);
         auto arrSelected = GetSelectedEffects();
         int favor = 0;
         for (uint i = 0; i < arrSelected.length(); i++)
             favor += arrSelected[i].m_favor;
         if (favor > 0)
         {
             m_wPoints.SetText(Resources::GetString(".fountain.favorcount", { { "favor", "+" + favor } }));
             m_wPoints.SetColor(vec4(0, 1, 0, 1));
             m_wScale.SetSprite("scale-left");
         }
         else if (favor < 0)
         {
             m_wPoints.SetText(Resources::GetString(".fountain.favorcount", { { "favor", "" + favor } }));
             m_wPoints.SetColor(vec4(1, 0, 0, 1));
             m_wScale.SetSprite("scale-right");
         }
         else if (favor == 0)
         {
             m_wPoints.SetText(Resources::GetString(".fountain.favorcount", { { "favor", "0" } }));
             m_wPoints.SetColor(vec4(1, 1, 1, 1));
             m_wScale.SetSprite("scale-balanced");
         }
         float goldGain = 0.0f;
         float expMul = 0.0f;
         if (favor < 0)
         {
             goldGain = 0.05f * -favor;
             expMul = 0.05f * -favor;
         }
         m_wGoldGain.SetText(round(goldGain * 100.0f) + "%");
         m_wExpMul.SetText(round(expMul * 100.0f) + "%");
         m_wDepositGold.SetText(formatThousands(gm.m_town.m_fountainGold));
         for (uint i = 0; i < m_wDepositButtons.m_children.length(); i++)
         {
             auto wButton = cast<ScalableSpriteButtonWidget>(m_wDepositButtons.m_children[i]);
             if (wButton is null)
                 continue;
             int buttonValue = parseInt(wButton.m_value);
             wButton.m_enabled = (gm.m_townLocal.m_gold >= buttonValue);
         }
         if (Fountain::CurrentEffects.length() > 0)
         {
             m_wButton.SetText(Resources::GetString(".fountain.lockedin"));
             m_wButton.m_enabled = false;
             m_wButton.m_iconVisible = false;
         }
         else
         {
             m_wButton.SetText(formatThousands(GetCost()));
             m_wButton.m_enabled = (Network::IsServer() && CanAfford() && AnyEffectSelected());
             m_wButton.m_iconVisible = true;
         }
         m_shopMenu.DoLayout();
     }
Member Data Documentation
m_arrButtons
array<FavorButtonWidget@> FountainShopMenuContent::m_arrButtons private
Definition at line 20 of file FountainShopMenu.as.
Referenced by AnyEffectSelected(), GetSelectedEffects(), and ReloadList().
m_sndLockIn
SoundEvent FountainShopMenuContent::m_sndLockIn private
Definition at line 18 of file FountainShopMenu.as.
Referenced by Buy(), and OnShow().
m_wButton
ScalableSpriteIconButtonWidget FountainShopMenuContent::m_wButton private
Definition at line 3 of file FountainShopMenu.as.
Referenced by OnShow(), and UpdateInterface().
m_wDepositButtons
Widget FountainShopMenuContent::m_wDepositButtons private
Definition at line 16 of file FountainShopMenu.as.
Referenced by OnShow(), and UpdateInterface().
m_wDepositGold
TextWidget FountainShopMenuContent::m_wDepositGold private
Definition at line 15 of file FountainShopMenu.as.
Referenced by NetDeposit(), OnShow(), and UpdateInterface().
m_wExpMul
TextWidget FountainShopMenuContent::m_wExpMul private
Definition at line 13 of file FountainShopMenu.as.
Referenced by OnShow(), and UpdateInterface().
m_wGoldGain
TextWidget FountainShopMenuContent::m_wGoldGain private
Definition at line 12 of file FountainShopMenu.as.
Referenced by OnShow(), and UpdateInterface().
m_wListBad
Widget FountainShopMenuContent::m_wListBad private
Definition at line 7 of file FountainShopMenu.as.
Referenced by OnShow(), and ReloadList().
m_wListGood
Widget FountainShopMenuContent::m_wListGood private
Definition at line 6 of file FountainShopMenu.as.
Referenced by OnShow(), and ReloadList().
m_wPoints
TextWidget FountainShopMenuContent::m_wPoints private
Definition at line 11 of file FountainShopMenu.as.
Referenced by OnShow(), and UpdateInterface().
m_wScale
SpriteWidget FountainShopMenuContent::m_wScale private
Definition at line 9 of file FountainShopMenu.as.
Referenced by OnShow(), and UpdateInterface().
m_wTemplateWish
Widget FountainShopMenuContent::m_wTemplateWish private
Definition at line 5 of file FountainShopMenu.as.
Referenced by OnShow(), and ReloadList().
The documentation for this class was generated from the following file:
scripts/GUI/Shop/FountainShopMenu.as