HoHDocs: RandomLevel Class Reference
RandomLevel Class Reference
Private Member Functions
RandomLevel (Scene@ scene)
void Generate (SValue@ save)
void Start (uint8 peer, SValue@ save, StartMode sMode) override
void PostStart () override
Private Attributes
EnemyPlacement m_enemyPlacer
Detailed Description
Definition at line 2 of file RandomLevel.as.
Constructor & Destructor Documentation
RandomLevel()
RandomLevel::RandomLevel (Scene@ scene) inline private
Definition at line 6 of file RandomLevel.as.
     {
         super(scene);
     }
Member Function Documentation
Generate()
void RandomLevel::Generate (SValue@ save) inline private
Definition at line 11 of file RandomLevel.as.
References Fountain::ApplyEffect(), g_downscaling, g_flags, g_ngp, GenerateDungeon(), Level, BaseGameMode::LoadDungeonRotation(), HwrSaves::LoadHostTown(), BaseGameMode::m_levelCount, and Town.
     {
         LoadDungeonRotation(save);
         int shortcut = 0;
         int numPlrs = 1;
         if (save !is null)
         {
             m_levelCount = GetParamInt(UnitPtr(), save, "level-count", false, GetVarInt("g_start_level"));
             shortcut = GetParamInt(UnitPtr(), save, "shortcut", false, 0);
             numPlrs = GetParamInt(UnitPtr(), save, "num-plrs", false, 1);
             if (GetParamBool(UnitPtr(), save, "soul-linked", false, false))
                 g_flags.Set("allow_graveyard", FlagState::Level);
             g_ngp = GetParamInt(UnitPtr(), save, "ngp", false, 0);
             g_downscaling = GetParamBool(UnitPtr(), save, "downscaling", false, false);
             auto arrFountain = GetParamArray(UnitPtr(), save, "fountain", false);
             if (arrFountain !is null)
             {
                 for (uint i = 0; i < arrFountain.length(); i++)
                     Fountain::ApplyEffect(arrFountain[i].GetInteger());
             }
         }
         else
             m_levelCount = GetVarInt("g_start_level");
         auto townSave = HwrSaves::LoadHostTown();
         auto arrFlags = GetParamArray(UnitPtr(), townSave, "flags", false);
         if (arrFlags !is null)
         {
             for (uint i = 0; i < arrFlags.length(); i++)
                 g_flags.Set(arrFlags[i].GetString(), FlagState::Town);
         }
         print("NewGame+ " +g_ngp);
         print("Downscaling: " + g_downscaling);
         GenerateDungeon(this, m_levelCount, shortcut, numPlrs);
     }
PostStart()
void RandomLevel::PostStart () inline override private
Definition at line 73 of file RandomLevel.as.
References GetLocalPlayerRecord(), Fountain::HasEffect(), LoadGame, BaseGameMode::m_levelCount, BaseGameMode::m_startMode, and Campaign::PostStart().
Referenced by Start().
     {
         Campaign::PostStart();
         auto record = GetLocalPlayerRecord();
         if (m_levelCount == 0 && m_startMode != StartMode::LoadGame && Network::IsServer())
         {
             if (Fountain::HasEffect("ace_key"))
                 record.keys[3]++;
             /*
             auto player = GetLocalPlayer();
             if (Fountain::HasEffect("rare_item") && player !is null)
                 player.AddItem(g_items.TakeRandomItem(ActorItemQuality::Rare));
             */
         }
     }
Start()
void RandomLevel::Start (uint8 peer, SValue@ save, StartMode sMode) inline override private
Definition at line 52 of file RandomLevel.as.
References Stats::Add(), DungeonLevelRichPresence(), g_prefabsToSpawn, g_scene, GetLocalPlayerRecord(), LoadGame, m_pfb, BaseGameMode::m_useSpawnLogic, PostStart(), and Campaign::Start().
     {
         if (sMode != StartMode::LoadGame)
             m_useSpawnLogic = false;
         Campaign::Start(peer, save, sMode);
         for (uint i = 0; i < g_prefabsToSpawn.length(); i++)
             g_prefabsToSpawn[i].m_pfb.Fabricate(g_scene, g_prefabsToSpawn[i].m_pos);
         g_prefabsToSpawn.removeRange(0, g_prefabsToSpawn.length());
         RandomLevel::PostStart();
         auto record = GetLocalPlayerRecord();
         Stats::Add("floors-visited", 1, record);
         DungeonLevelRichPresence(this);
     }
Member Data Documentation
m_enemyPlacer
EnemyPlacement RandomLevel::m_enemyPlacer private
Definition at line 4 of file RandomLevel.as.
Referenced by GenerateDungeon().
The documentation for this class was generated from the following file:
scripts/GameModes/RandomLevel.as