HoHDocs: WorldScript::LevelStart Class Reference
WorldScript::LevelStart Class Reference
Private Member Functions
void Initialize ()
SValue ServerExecute ()
vec2 GetFormationOffset (int index, int count)
void DebugDraw (vec2 pos, SpriteBatch &sb)
Private Attributes
vec3 Position
bool Enabled
string StartID
Detailed Description
Definition at line 4 of file LevelStart.as.
Member Function Documentation
DebugDraw()
void WorldScript::LevelStart::DebugDraw (vec2 pos, SpriteBatch & sb) inline private
Definition at line 29 of file LevelStart.as.
References GetFormationOffset(), and GetPlayerColor().
         {
             float playerBox = 32.0;
             for (int i = 0; i < 4; i++)
             {
                 vec4 color = ParseColorRGBA("#" + GetPlayerColor(i) + "7f");
                 vec2 spawnPos = pos + GetFormationOffset(i, 4);
                 sb.DrawRectangle(vec4(spawnPos.x, spawnPos.y, playerBox - 1, playerBox - 1), color);
             }
         }
GetFormationOffset()
vec2 WorldScript::LevelStart::GetFormationOffset (int index, int count) inline private
Definition at line 22 of file LevelStart.as.
Referenced by DebugDraw().
         {
             float dist = 32.0;
             float maxdist = count * dist;
             return vec2(-(maxdist / 2.0) + index * dist, -(dist / 2));
         }
Initialize()
void WorldScript::LevelStart::Initialize () inline private
Definition at line 12 of file LevelStart.as.
References m_levelStarts.
         {
             m_levelStarts.insertLast(this);
         }
ServerExecute()
SValue WorldScript::LevelStart::ServerExecute () inline private
Definition at line 17 of file LevelStart.as.
         {
             return null;
         }
Member Data Documentation
Enabled
bool WorldScript::LevelStart::Enabled private
Definition at line 7 of file LevelStart.as.
Position
vec3 WorldScript::LevelStart::Position private
Definition at line 6 of file LevelStart.as.
StartID
string WorldScript::LevelStart::StartID private
Definition at line 10 of file LevelStart.as.
The documentation for this class was generated from the following file:
scripts/WorldScript/LevelStart.as