HoHDocs: ProximityTrap Class Reference
ProximityTrap Class Reference
Private Member Functions
ProximityTrap (UnitPtr unit, SValue &params)
void Collide (UnitPtr unit, vec2 pos, vec2 normal) override
void EndCollision (UnitPtr unit) override
void OnEnter (Actor@ actor)
bool OnExit (Actor@ actor)
void Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther)
void EndCollision (UnitPtr unit, Fixture@ fxSelf, Fixture@ fxOther)
void Update (int dt) override
Private Attributes
array< Actor@> m_actorsNear
UnitScene m_sceneOff
UnitScene m_sceneOn
UnitScene m_sceneActivate
UnitScene m_sceneDeactivate
Detailed Description
Definition at line 1 of file ProximityTrap.as.
Constructor & Destructor Documentation
ProximityTrap()
ProximityTrap::ProximityTrap (UnitPtr unit, SValue & params) inline private
Definition at line 10 of file ProximityTrap.as.
References m_sceneActivate, m_sceneDeactivate, m_sceneOff, m_sceneOn, DangerAreaBehavior::m_unit, and unit.
     {
         super(unit, params);
         @m_sceneOff = m_unit.GetUnitScene("off");
         @m_sceneOn = m_unit.GetUnitScene("on");
         @m_sceneActivate = m_unit.GetUnitScene("activate");
         @m_sceneDeactivate = m_unit.GetUnitScene("deactivate");
     }
Member Function Documentation
Collide() [1/2]
void ProximityTrap::Collide (UnitPtr unit, vec2 pos, vec2 normal) inline override private
Definition at line 20 of file ProximityTrap.as.
 {}
Collide() [2/2]
void ProximityTrap::Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther) inline private
Definition at line 39 of file ProximityTrap.as.
References DangerAreaBehavior::Collide(), DangerAreaBehavior::m_unit, OnEnter(), and unit.
     {
         if (fxSelf.GetIndex() == 0)
         {
             DangerAreaBehavior::Collide(unit, pos, normal);
             return;
         }
         auto actor = cast<Actor>(unit.GetScriptBehavior());
         if (actor is null)
             return;
         OnEnter(actor);
         if (cast<Player>(actor) !is null)
             (Network::Message("ProximityTrapEnter") << m_unit).SendToAll();
     }
EndCollision() [1/2]
void ProximityTrap::EndCollision (UnitPtr unit) inline override private
Definition at line 21 of file ProximityTrap.as.
 {}
EndCollision() [2/2]
void ProximityTrap::EndCollision (UnitPtr unit, Fixture@ fxSelf, Fixture@ fxOther) inline private
Definition at line 57 of file ProximityTrap.as.
References DangerAreaBehavior::EndCollision(), DangerAreaBehavior::m_unit, OnExit(), and unit.
     {
         if (fxSelf.GetIndex() == 0)
         {
             DangerAreaBehavior::EndCollision(unit);
             return;
         }
         auto actor = cast<Actor>(unit.GetScriptBehavior());
         if (actor is null)
             return;
         if (OnExit(actor))
         {
             if (cast<Player>(actor) !is null)
                 (Network::Message("ProximityTrapExit") << m_unit).SendToAll();
         }
     }
OnEnter()
void ProximityTrap::OnEnter (Actor@ actor) inline private
Definition at line 23 of file ProximityTrap.as.
References m_actorsNear.
Referenced by Collide().
     {
         m_actorsNear.insertLast(actor);
     }
OnExit()
bool ProximityTrap::OnExit (Actor@ actor) inline private
Definition at line 28 of file ProximityTrap.as.
References m_actorsNear.
Referenced by EndCollision().
     {
         int index = m_actorsNear.findByRef(actor);
         if (index != -1)
         {
             m_actorsNear.removeAt(index);
             return true;
         }
         return false;
     }
Update()
void ProximityTrap::Update (int dt) inline override private
Definition at line 76 of file ProximityTrap.as.
References m_actorsNear, m_sceneActivate, m_sceneDeactivate, m_sceneOff, m_sceneOn, DangerAreaBehavior::m_unit, and DangerAreaBehavior::Update().
     {
         UnitScene@ currScene = m_unit.GetCurrentUnitScene();
         if (m_actorsNear.length() > 0 && currScene is m_sceneOff)
             m_unit.SetUnitScene(m_sceneActivate, true);
         else if (m_actorsNear.length() == 0 && currScene is m_sceneOn)
             m_unit.SetUnitScene(m_sceneDeactivate, true);
         else if (m_unit.GetUnitSceneTime() >= currScene.Length())
         {
             if (currScene is m_sceneActivate)
                 m_unit.SetUnitScene(m_sceneOn, true);
             else if (currScene is m_sceneDeactivate)
                 m_unit.SetUnitScene(m_sceneOff, true);
         }
         DangerAreaBehavior::Update(dt);
     }
Member Data Documentation
m_actorsNear
array<Actor@> ProximityTrap::m_actorsNear private
Definition at line 3 of file ProximityTrap.as.
Referenced by OnEnter(), OnExit(), and Update().
m_sceneActivate
UnitScene ProximityTrap::m_sceneActivate private
Definition at line 7 of file ProximityTrap.as.
Referenced by ProximityTrap(), and Update().
m_sceneDeactivate
UnitScene ProximityTrap::m_sceneDeactivate private
Definition at line 8 of file ProximityTrap.as.
Referenced by ProximityTrap(), and Update().
m_sceneOff
UnitScene ProximityTrap::m_sceneOff private
Definition at line 5 of file ProximityTrap.as.
Referenced by ProximityTrap(), and Update().
m_sceneOn
UnitScene ProximityTrap::m_sceneOn private
Definition at line 6 of file ProximityTrap.as.
Referenced by ProximityTrap(), and Update().
The documentation for this class was generated from the following file:
scripts/Behaviors/ProximityTrap.as