HoHDocs: WorldScript::RandomBuff Class Reference
WorldScript::RandomBuff Class Reference
Private Member Functions
void Initialize ()
Player GetPlayer (UnitPtr unit)
void OnEnter (UnitPtr unit, vec2 pos, vec2 normal)
void OnExit (UnitPtr unit)
UnitPtr GetUseUnit ()
bool CanUse (PlayerBase@ player)
void OnFunc (Widget@ sender, string name) override
void Use (PlayerBase@ player)
UsableIcon GetIcon (Player@ player)
int UsePriority (IUsable@ other)
SValue Save ()
void Load (SValue@ data)
void NetUse (PlayerHusk@ player)
void DoLayout () override
void Update (int dt) override
void Draw (SpriteBatch &sb, int idt) override
void UpdateInput (vec2 origin, vec2 parentSz, vec3 mousePos) override
Private Attributes
bool Enabled
array< CollisionArea@> Areas
UnitFeed Unit
string UseScene
RandomBuffNegative m_negativeEffect = RandomBuffNegative::None
bool m_used = false
Detailed Description
Definition at line 4 of file RandomBuff.as.
Member Function Documentation
CanUse()
bool WorldScript::RandomBuff::CanUse (PlayerBase@ player) inline private
Definition at line 62 of file RandomBuff.as.
References Enabled, PlayerBase::m_record, and m_used.
Referenced by GetIcon().
         {
             if (!Enabled)
                 return false;
             if (m_used && player.m_record.local)
                 return false;
             return true;
         }
DoLayout()
void WorldScript::RandomBuff::DoLayout () inline override private
Definition at line 242 of file RandomBuff.as.
 { }
Draw()
void WorldScript::RandomBuff::Draw (SpriteBatch & sb, int idt) inline override private
Definition at line 244 of file RandomBuff.as.
 { }
GetIcon()
UsableIcon WorldScript::RandomBuff::GetIcon (Player@ player) inline private
Definition at line 219 of file RandomBuff.as.
References CanUse(), Cross, and Speech.
         {
             if (!CanUse(player))
                 return Cross;
             return Speech;
         }
GetPlayer()
Player WorldScript::RandomBuff::GetPlayer (UnitPtr unit) inline private
Definition at line 30 of file RandomBuff.as.
References unit.
Referenced by OnEnter(), and OnExit().
         {
             if (!unit.IsValid())
                 return null;
             ref@ behavior = unit.GetScriptBehavior();
             if (behavior is null)
                 return null;
             return cast<Player>(behavior);
         }
GetUseUnit()
UnitPtr WorldScript::RandomBuff::GetUseUnit () inline private
Definition at line 57 of file RandomBuff.as.
References g_scene.
         {
             return WorldScript::GetWorldScript(g_scene, this).GetUnit();
         }
Initialize()
void WorldScript::RandomBuff::Initialize () inline private
Definition at line 21 of file RandomBuff.as.
References Areas.
         {
             for (uint i = 0; i < Areas.length(); i++)
             {
                 Areas[i].AddOnEnter(this, "OnEnter");
                 Areas[i].AddOnExit(this, "OnExit");
             }
         }
Load()
void WorldScript::RandomBuff::Load (SValue@ data) inline private
Definition at line 236 of file RandomBuff.as.
References m_used.
         {
             m_used = data.GetBoolean();
         }
NetUse()
void WorldScript::RandomBuff::NetUse (PlayerHusk@ player) inline private
Definition at line 241 of file RandomBuff.as.
 { }
OnEnter()
void WorldScript::RandomBuff::OnEnter (UnitPtr unit, vec2 pos, vec2 normal) inline private
Definition at line 43 of file RandomBuff.as.
References Player::AddUsable(), GetPlayer(), and unit.
         {
             Player@ plr = GetPlayer(unit);
             if (plr !is null)
                 plr.AddUsable(this);
         }
OnExit()
void WorldScript::RandomBuff::OnExit (UnitPtr unit) inline private
Definition at line 50 of file RandomBuff.as.
References GetPlayer(), Player::RemoveUsable(), and unit.
         {
             Player@ plr = GetPlayer(unit);
             if (plr !is null)
                 plr.RemoveUsable(this);
         }
OnFunc()
void WorldScript::RandomBuff::OnFunc (Widget@ sender, string name) inline override private
Definition at line 73 of file RandomBuff.as.
References DamageInfo(), g_gameMode, GetLocalPlayer(), GetRandomBuffAmount(), m_negativeEffect, m_used, MoreArmor, MoreExperience, MoreGold, MoreHp, MoreHPRegen, MoreMPRegen, MoreOre, name, SetUnitScene(), AGameMode::ShowDialog(), TakeDamage, Unit, UseScene, and xy().
         {
             if (name == "q yes")
             {
                 m_used = true;
                 if (UseScene != "")
                 {
                     auto units = Unit.FetchAll();
                     for (uint i = 0; i < units.length(); i++)
                         units[i].SetUnitScene(UseScene, true);
                 }
                 auto player = GetLocalPlayer();
                 if (m_negativeEffect != RandomBuffNegative::TakeDamage)
                     player.m_record.randomBuffNegative = player.m_record.randomBuffNegative | m_negativeEffect;
                 array<RandomBuffPositive> possible = { MoreHp, MoreArmor, MoreExperience, MoreGold, MoreOre, MoreHPRegen, MoreMPRegen, MoreDamage };
                 for (uint i = 0; i < possible.length(); i++)
                 {
                     if ((player.m_record.randomBuffPositive & possible[i]) != 0)
                     {
                         possible.removeAt(i);
                         i--;
                     }
                 }
                 auto positiveEffect = possible[randi(possible.length())];
                 if (possible.length() > 0)
                     player.m_record.randomBuffPositive = player.m_record.randomBuffPositive | positiveEffect;
                 player.RefreshModifiers();
                 if (m_negativeEffect == RandomBuffNegative::TakeDamage)
                 {
                     int dmg = GetRandomBuffAmount(m_negativeEffect);
                     player.Damage(DamageInfo(null, dmg / 2, dmg / 2, false, true, 0), xy(player.m_unit.GetPosition()), vec2(1,0));
                 }
                 string msg = "";
                 switch(positiveEffect)
                 {
                 case RandomBuffPositive::MoreHp:
                     msg = ".random_buff.more_hp";
                     break;
                 case RandomBuffPositive::MoreArmor:
                     msg = ".random_buff.more_armor";
                     break;
                 case RandomBuffPositive::MoreExperience:
                     msg = ".random_buff.more_experience";
                     break;
                 case RandomBuffPositive::MoreGold:
                     msg = ".random_buff.more_gold";
                     break;
                 case RandomBuffPositive::MoreOre:
                     msg = ".random_buff.more_ore";
                     break;
                 case RandomBuffPositive::MoreHPRegen:
                     msg = ".random_buff.more_hp_regen";
                     break;
                 case RandomBuffPositive::MoreMPRegen:
                     msg = ".random_buff.more_mp_regen";
                     break;
                 case RandomBuffPositive::MoreDamage:
                     msg = ".random_buff.more_damage";
                     break;
                 }
                 if (msg != "")
                     g_gameMode.ShowDialog("a",
                         Resources::GetString(msg, { { "amount", GetRandomBuffAmount(positiveEffect) } }),
                         Resources::GetString(".menu.ok"),
                         this);
             }
         }
Save()
SValue WorldScript::RandomBuff::Save () inline private
Definition at line 229 of file RandomBuff.as.
References m_used.
         {
             SValueBuilder sval;
             sval.PushBoolean(m_used);
             return sval.Build();
         }
Update()
void WorldScript::RandomBuff::Update (int dt) inline override private
Definition at line 243 of file RandomBuff.as.
 { }
UpdateInput()
void WorldScript::RandomBuff::UpdateInput (vec2 origin, vec2 parentSz, vec3 mousePos) inline override private
Definition at line 245 of file RandomBuff.as.
 { }
Use()
void WorldScript::RandomBuff::Use (PlayerBase@ player) inline private
Definition at line 153 of file RandomBuff.as.
References g_gameMode, GetRandomBuffAmount(), LowerArmor, LowerDamage, LowerHp, LowerHPRegen, LowerMPRegen, LowerResistance, m_negativeEffect, PlayerBase::m_record, NoExperience, NoGoldGain, None, AGameMode::ShowDialog(), and TakeDamage.
         {
             if (m_negativeEffect == RandomBuffNegative::None)
             {
                 array<RandomBuffNegative> possible = { LowerArmor, LowerResistance, NoExperience, NoGoldGain, LowerHPRegen, LowerMPRegen, /*TakeDamage,*/ LowerDamage };
                 if (player.m_record.MaxHealth() > GetRandomBuffAmount(LowerHp))
                     possible.insertLast(LowerHp);
                 for (uint i = 0; i < possible.length(); i++)
                 {
                     if ((player.m_record.randomBuffNegative & possible[i]) != 0)
                     {
                         possible.removeAt(i);
                         i--;
                     }
                 }
                 if (possible.length() <= 0)
                     return;
                 m_negativeEffect = possible[randi(possible.length())];
             }
             string question = "";
             switch(m_negativeEffect)
             {
             case RandomBuffNegative::LowerHp:
                 question = ".random_buff.lower_hp";
                 break;
             case RandomBuffNegative::LowerArmor:
                 question = ".random_buff.lower_armor";
                 break;
             case RandomBuffNegative::LowerResistance:
                 question = ".random_buff.lower_resistance";
                 break;
             case RandomBuffNegative::NoExperience:
                 question = ".random_buff.no_experience";
                 break;
             case RandomBuffNegative::NoGoldGain:
                 question = ".random_buff.no_gold";
                 break;
             case RandomBuffNegative::LowerHPRegen:
                 question = ".random_buff.lower_hp_regen";
                 break;
             case RandomBuffNegative::LowerMPRegen:
                 question = ".random_buff.lower_mp_regen";
                 break;
             case RandomBuffNegative::TakeDamage:
                 question = ".random_buff.take_damage";
                 break;
             case RandomBuffNegative::LowerDamage:
                 question = ".random_buff.lower_damage";
                 break;
             }
             if (question != "")
                 g_gameMode.ShowDialog("q",
                     Resources::GetString(question, { { "amount", GetRandomBuffAmount(m_negativeEffect) } }),
                     Resources::GetString(".misc.yes"),
                     Resources::GetString(".misc.no"),
                     this);
         }
UsePriority()
int WorldScript::RandomBuff::UsePriority (IUsable@ other) inline private
Definition at line 227 of file RandomBuff.as.
 { return 0; }
Member Data Documentation
Areas
array<CollisionArea@> WorldScript::RandomBuff::Areas private
Definition at line 9 of file RandomBuff.as.
Referenced by Initialize().
Enabled
bool WorldScript::RandomBuff::Enabled private
Definition at line 6 of file RandomBuff.as.
Referenced by CanUse().
m_negativeEffect
RandomBuffNegative WorldScript::RandomBuff::m_negativeEffect = RandomBuffNegative::None private
Definition at line 17 of file RandomBuff.as.
Referenced by OnFunc(), and Use().
m_used
bool WorldScript::RandomBuff::m_used = false private
Definition at line 18 of file RandomBuff.as.
Referenced by CanUse(), Load(), OnFunc(), and Save().
Unit
UnitFeed WorldScript::RandomBuff::Unit private
Definition at line 12 of file RandomBuff.as.
Referenced by OnFunc().
UseScene
string WorldScript::RandomBuff::UseScene private
Definition at line 14 of file RandomBuff.as.
Referenced by OnFunc().
The documentation for this class was generated from the following file:
scripts/WorldScript/RandomBuff.as