HoHDocs: WorldScript::Well Class Reference
WorldScript::Well Class Reference
Private Member Functions
void Initialize ()
Player GetPlayer (UnitPtr unit)
void OnEnter (UnitPtr unit, vec2 pos, vec2 normal)
void OnExit (UnitPtr unit)
UnitPtr GetUseUnit ()
bool HasInfiniteUses ()
bool CanUse (PlayerBase@ player)
void Use (PlayerBase@ player)
SValue Save ()
void Load (SValue@ data)
UsableIcon GetIcon (Player@ player)
int UsePriority (IUsable@ other)
void NetUse (PlayerHusk@ player)
Private Attributes
bool Enabled
vec3 Position
array< CollisionArea@> Areas
UnitFeed Unit
string UseScene
SoundEvent Sound
SoundInstance m_sndInstance
bool m_used = false
Detailed Description
Definition at line 4 of file Well.as.
Member Function Documentation
CanUse()
bool WorldScript::Well::CanUse (PlayerBase@ player) inline private
Definition at line 77 of file Well.as.
References Enabled, HasInfiniteUses(), PlayerBase::m_record, and m_used.
Referenced by GetIcon().
         {
             if (!Enabled)
                 return false;
             if (!HasInfiniteUses())
             {
                 if (m_used && player.m_record.local)
                     return false;
             }
             if (cast<PlayerHusk>(player) !is null)
                 return true;
             auto record = player.m_record;
             if (record.potionChargesUsed == 0 && record.hp >= 1.0f && record.mana >= 1.0f)
                 return false;
             return true;
         }
GetIcon()
UsableIcon WorldScript::Well::GetIcon (Player@ player) inline private
Definition at line 141 of file Well.as.
References CanUse(), Cross, and Generic.
         {
             if (!CanUse(player))
                 return Cross;
             return Generic;
         }
GetPlayer()
Player WorldScript::Well::GetPlayer (UnitPtr unit) inline private
Definition at line 40 of file Well.as.
References unit.
Referenced by OnEnter(), and OnExit().
         {
             if (!unit.IsValid())
                 return null;
             ref@ behavior = unit.GetScriptBehavior();
             if (behavior is null)
                 return null;
             return cast<Player>(behavior);
         }
GetUseUnit()
UnitPtr WorldScript::Well::GetUseUnit () inline private
Definition at line 67 of file Well.as.
References g_scene.
         {
             return WorldScript::GetWorldScript(g_scene, this).GetUnit();
         }
HasInfiniteUses()
bool WorldScript::Well::HasInfiniteUses () inline private
Definition at line 72 of file Well.as.
References Fountain::HasEffect().
Referenced by CanUse(), and Use().
         {
             return Fountain::HasEffect("infinite_wells");
         }
Initialize()
void WorldScript::Well::Initialize () inline private
Definition at line 24 of file Well.as.
References Areas, m_sndInstance, Position, and Sound.
         {
             for (uint i = 0; i < Areas.length(); i++)
             {
                 Areas[i].AddOnEnter(this, "OnEnter");
                 Areas[i].AddOnExit(this, "OnExit");
             }
             if (Sound !is null)
             {
                 @m_sndInstance = Sound.PlayTracked(Position);
                 m_sndInstance.SetLooped(true);
                 m_sndInstance.SetPaused(false);
             }
         }
Load()
void WorldScript::Well::Load (SValue@ data) inline private
Definition at line 136 of file Well.as.
References m_used.
         {
             m_used = data.GetBoolean();
         }
NetUse()
void WorldScript::Well::NetUse (PlayerHusk@ player) inline private
Definition at line 151 of file Well.as.
 { }
OnEnter()
void WorldScript::Well::OnEnter (UnitPtr unit, vec2 pos, vec2 normal) inline private
Definition at line 53 of file Well.as.
References Player::AddUsable(), GetPlayer(), and unit.
         {
             Player@ plr = GetPlayer(unit);
             if (plr !is null)
                 plr.AddUsable(this);
         }
OnExit()
void WorldScript::Well::OnExit (UnitPtr unit) inline private
Definition at line 60 of file Well.as.
References GetPlayer(), Player::RemoveUsable(), and unit.
         {
             Player@ plr = GetPlayer(unit);
             if (plr !is null)
                 plr.RemoveUsable(this);
         }
Save()
SValue WorldScript::Well::Save () inline private
Definition at line 129 of file Well.as.
References m_used.
         {
             SValueBuilder sval;
             sval.PushBoolean(m_used);
             return sval.Build();
         }
Use()
void WorldScript::Well::Use (PlayerBase@ player) inline private
Definition at line 98 of file Well.as.
References Stats::Add(), AddFloatingText(), HasInfiniteUses(), PlayerBase::m_record, m_sndInstance, m_used, Pickup, SetUnitScene(), Unit, and UseScene.
         {
             if (!HasInfiniteUses())
             {
                 if (UseScene != "")
                 {
                     auto units = Unit.FetchAll();
                     for (uint i = 0; i < units.length(); i++)
                         units[i].SetUnitScene(UseScene, true);
                 }
                 if (m_sndInstance !is null)
                 {
                     m_sndInstance.Stop();
                     @m_sndInstance = null;
                 }
             }
             auto record = player.m_record;
             record.potionChargesUsed = 0;
             record.hp = 1.0f;
             record.mana = 1.0f;
             AddFloatingText(FloatingTextType::Pickup, Resources::GetString(".hud.potionrefill"), player.m_unit.GetPosition());
             if (!m_used)
                 Stats::Add("well-used", 1, record);
             m_used = true;
         }
UsePriority()
int WorldScript::Well::UsePriority (IUsable@ other) inline private
Definition at line 149 of file Well.as.
 { return 0; }
Member Data Documentation
Areas
array<CollisionArea@> WorldScript::Well::Areas private
Definition at line 10 of file Well.as.
Referenced by Initialize().
Enabled
bool WorldScript::Well::Enabled private
Definition at line 6 of file Well.as.
Referenced by CanUse().
m_sndInstance
SoundInstance WorldScript::Well::m_sndInstance private
Definition at line 20 of file Well.as.
Referenced by Initialize(), and Use().
m_used
bool WorldScript::Well::m_used = false private
Definition at line 21 of file Well.as.
Referenced by CanUse(), Load(), Save(), and Use().
Position
vec3 WorldScript::Well::Position private
Definition at line 7 of file Well.as.
Referenced by Initialize().
Sound
SoundEvent WorldScript::Well::Sound private
Definition at line 18 of file Well.as.
Referenced by Initialize().
Unit
UnitFeed WorldScript::Well::Unit private
Definition at line 13 of file Well.as.
Referenced by Use().
UseScene
string WorldScript::Well::UseScene private
Definition at line 15 of file Well.as.
Referenced by Use().
The documentation for this class was generated from the following file:
scripts/WorldScript/Well.as