HoHDocs: DangerArea Class Reference
DangerArea Class Reference
Private Member Functions
void Initialize ()
bool ApplyDamage (UnitPtr unit, vec2 pos)
void TickDamage ()
void OnEnabledChanged (bool enabled)
void Update (int dt)
void OnEnter (UnitPtr unit, vec2 pos, vec2 normal)
void OnExit (UnitPtr unit)
Private Attributes
bool Enabled
DamageFilter Filter
array< CollisionArea@> Areas
int Frequency
int Damage
DamageType DamageType
string Buff
bool CanKill
int m_time
array< UnitPtr > m_units
DamageInfo m_dmg
ActorBuffDef m_buff
Detailed Description
Definition at line 43 of file DangerArea.as.
Member Function Documentation
ApplyDamage()
bool DangerArea::ApplyDamage (UnitPtr unit, vec2 pos) inline private
Definition at line 92 of file DangerArea.as.
References Actor::ApplyBuff(), FilterHuskDamage(), m_buff, m_dmg, and unit.
         {
             if (!FilterHuskDamage(null, unit, !Network::IsServer()))
                 return false;
             auto behavior = unit.GetScriptBehavior();
             if (m_buff !is null)
             {
                 Actor@ actor = cast<Actor>(behavior);
                 if (actor !is null)
                     actor.ApplyBuff(ActorBuff(null, m_buff, 1.0, false));
             }
             if (m_dmg.Damage > 0)
             {
                 unit.TriggerCallbacks(UnitEventType::Damaged);
                 IDamageTaker@ dt = cast<IDamageTaker>(behavior);
                 if (dt is null)
                     return true;
                 dt.Damage(m_dmg, pos, vec2(0, 0));
                 return dt.IsDead();
             }
             return false;
         }
Initialize()
void DangerArea::Initialize () inline private
Definition at line 75 of file DangerArea.as.
References CanKill, Damage, Frequency, LoadActorBuff(), m_buff, and m_dmg.
         {
             m_time = Frequency;
             for (uint i = 0; i < Areas.length(); i++)
             {
                 Areas[i].AddOnEnter(this, "OnEnter");
                 Areas[i].AddOnExit(this, "OnExit");
             }
             m_dmg.Damage = Damage;
             m_dmg.PhysicalDamage = Damage;
             m_dmg.DamageType = uint8(DamageType);
             m_dmg.CanKill = CanKill;
             @m_buff = LoadActorBuff(Buff);
         }
OnEnabledChanged()
void DangerArea::OnEnabledChanged (bool enabled) inline private
Definition at line 127 of file DangerArea.as.
         {
             if (enabled)
                 TickDamage();
         }
OnEnter()
void DangerArea::OnEnter (UnitPtr unit, vec2 pos, vec2 normal) inline private
Definition at line 146 of file DangerArea.as.
References ApplyDamageFilter(), and unit.
         {
             if (!ApplyDamageFilter(unit, Filter))
                 return;
             if (!Enabled || !ApplyDamage(unit, pos))
                 m_units.insertLast(unit);
         }
OnExit()
void DangerArea::OnExit (UnitPtr unit) inline private
Definition at line 155 of file DangerArea.as.
References ApplyDamageFilter(), and unit.
         {
             if (!ApplyDamageFilter(unit, Filter))
                 return;
             for (uint i = 0; i < m_units.length();)
             {
                 if (m_units[i] == unit)
                 {
                     m_units.removeAt(i);
                     return;
                 }
                 else
                     i++;
             }
         }
TickDamage()
void DangerArea::TickDamage () inline private
Definition at line 121 of file DangerArea.as.
References xy().
         {
             for (uint i = 0; i < m_units.length(); i++)
                 ApplyDamage(m_units[i], xy(m_units[i].GetPosition()));
         }
Update()
void DangerArea::Update (int dt) inline private
Definition at line 133 of file DangerArea.as.
References Frequency.
         {
             if (!Enabled)
                 return;
             m_time -= dt;
             while (m_time < 0)
             {
                 m_time += Frequency;
                 TickDamage();
             }
         }
Member Data Documentation
Areas
array<CollisionArea@> DangerArea::Areas private
Definition at line 51 of file DangerArea.as.
Buff
string DangerArea::Buff private
Definition at line 63 of file DangerArea.as.
CanKill
bool DangerArea::CanKill private
Definition at line 66 of file DangerArea.as.
Damage
int DangerArea::Damage private
Definition at line 57 of file DangerArea.as.
DamageType
DamageType DangerArea::DamageType private
Definition at line 60 of file DangerArea.as.
Enabled
bool DangerArea::Enabled private
Definition at line 45 of file DangerArea.as.
Filter
DamageFilter DangerArea::Filter private
Definition at line 48 of file DangerArea.as.
Frequency
int DangerArea::Frequency private
Definition at line 54 of file DangerArea.as.
m_buff
ActorBuffDef DangerArea::m_buff private
Definition at line 72 of file DangerArea.as.
m_dmg
DamageInfo DangerArea::m_dmg private
Definition at line 71 of file DangerArea.as.
m_time
int DangerArea::m_time private
Definition at line 69 of file DangerArea.as.
m_units
array<UnitPtr> DangerArea::m_units private
Definition at line 70 of file DangerArea.as.
The documentation for this class was generated from the following file:
scripts/WorldScript/DangerArea.as