HoHDocs: ScrollableWidget Class Reference
ScrollableWidget Class Reference
Private Member Functions
void Load (WidgetLoadingContext &ctx) override
void DoLayout (vec2 origin, vec2 parentSz) override
bool ShouldDrawChild (Widget@ child) override
void DebugDraw (SpriteBatch &sb) override
void DoDraw (SpriteBatch &sb, vec2 pos) override
bool UpdateInput (vec2 origin, vec2 parentSz, vec3 mousePos) override
bool FocusTowards (WidgetDirection dir) override
void PauseScrolling ()
void ResumeScrolling ()
void AddChild (ref widget, int insertAt=-1) override
void ClearChildren () override
void ScrollUp ()
void ScrollDown ()
bool TestAutoscrollLimit ()
bool SpaceToScroll ()
Private Attributes
bool m_autoScroll = true
int m_autoScrollHeight = -1
int m_autoScrollValue = 0
int m_autoScrollArrowDelta = 40
bool m_autoScrollLimits = true
bool m_scrollingPaused
Sprite m_scrollBackdropSprite
Detailed Description
Definition at line 1 of file ScrollableWidget.as.
Member Function Documentation
AddChild()
void ScrollableWidget::AddChild (ref widget, int insertAt = -1) inline override private
Definition at line 166 of file ScrollableWidget.as.
References Widget::AddChild(), m_autoScroll, m_autoScrollHeight, Widget::m_flow, Widget::m_height, m_scrollingPaused, Widget::m_visible, and Vbox.
Referenced by GameChatWidget::AddChat(), CheckBoxGroupWidget::AddChild(), InventoryWidget::AddItem(), and Menu::SlotsMenu::RefreshSlots().
     {
         ClipWidget::AddChild(widget, insertAt);
         Widget@ w = cast<Widget>(widget);
         if (!m_scrollingPaused && m_autoScroll && m_flow == WidgetFlow::Vbox && w.m_visible)
             m_autoScrollHeight += w.m_height;
     }
ClearChildren()
void ScrollableWidget::ClearChildren () inline override private
Definition at line 176 of file ScrollableWidget.as.
References Widget::ClearChildren(), m_autoScroll, m_autoScrollHeight, m_autoScrollValue, and m_scrollingPaused.
Referenced by CheckBoxGroupWidget::ClearChildren(), Menu::SlotsMenu::RefreshSlots(), and InventoryWidget::UpdateFromRecord().
     {
         ClipWidget::ClearChildren();
         if (!m_scrollingPaused && m_autoScroll)
         {
             m_autoScrollValue = 0;
             m_autoScrollHeight = 0;
         }
     }
DebugDraw()
void ScrollableWidget::DebugDraw (SpriteBatch & sb) inline override private
Definition at line 70 of file ScrollableWidget.as.
References Widget::DebugDraw(), m_autoScroll, m_autoScrollHeight, m_autoScrollValue, and Widget::m_origin.
     {
         ClipWidget::DebugDraw(sb);
         sb.PauseClipping();
         if (m_autoScroll)
         {
             vec2 asOrigin = m_origin + vec2(2, 2 - m_autoScrollValue);
             sb.DrawLine(asOrigin, asOrigin + vec2(0, m_autoScrollHeight), 2, vec4(0.4, 0.4, 1, 1));
         }
         sb.ResumeClipping();
     }
DoDraw()
void ScrollableWidget::DoDraw (SpriteBatch & sb, vec2 pos) inline override private
Definition at line 85 of file ScrollableWidget.as.
References g_menuTime, m_autoScrollValue, Widget::m_height, m_scrollBackdropSprite, and Widget::m_width.
Referenced by ScrollableRectWidget::DoDraw().
     {
         if (m_scrollBackdropSprite is null)
             return;
         int spriteWidth = m_scrollBackdropSprite.GetWidth();
         int spriteHeight = m_scrollBackdropSprite.GetHeight();
         for (int y = 0; y < m_height + spriteHeight; y += spriteHeight)
         {
             for (int x = 0; x < m_width; x += spriteWidth)
             {
                 vec2 offset = vec2(x, y);
                 offset.y -= m_autoScrollValue % spriteHeight;
                 sb.DrawSprite(pos + offset, m_scrollBackdropSprite, g_menuTime);
             }
         }
     }
DoLayout()
void ScrollableWidget::DoLayout (vec2 origin, vec2 parentSz) inline override private
Definition at line 32 of file ScrollableWidget.as.
References Widget::DoLayout(), m_autoScroll, m_autoScrollHeight, m_autoScrollValue, Widget::m_childOffset, Widget::m_children, Widget::m_height, Widget::m_origin, Widget::m_visible, and TestAutoscrollLimit().
     {
         m_childOffset = vec2(0, -m_autoScrollValue);
         ClipWidget::DoLayout(origin, parentSz);
         if (!m_autoScroll)
             return;
         for (uint i = 0; i < m_children.length(); i++)
         {
             Widget@ child = m_children[i];
             if (!child.m_visible)
                 continue;
             int bottom = int((child.m_origin.y - m_origin.y) + child.m_height) + m_autoScrollValue;
             //if (bottom > m_autoScrollHeight)
                 m_autoScrollHeight = bottom;
         }
         TestAutoscrollLimit();
     }
FocusTowards()
bool ScrollableWidget::FocusTowards (WidgetDirection dir) inline override private
Definition at line 121 of file ScrollableWidget.as.
References Down, Widget::FocusTowards(), m_autoScroll, m_autoScrollArrowDelta, m_autoScrollValue, Widget::m_children, SpaceToScroll(), TestAutoscrollLimit(), and Up.
Referenced by Widget::FocusTowards().
     {
         // special case: if we're trying to go up/down, and we are autoscrolling without any focusable widgets inside, it's probably scrollable visual content, so just scroll
         if ((dir == WidgetDirection::Up || dir == WidgetDirection::Down) && m_autoScroll)
         {
             bool hasFocusable = false;
             for (uint i = 0; i < m_children.length(); i++)
             {
                 auto w = m_children[i];
                 if (w.ContainsFocusable())
                 {
                     hasFocusable = true;
                     break;
                 }
             }
             if (!hasFocusable)
             {
                 if (SpaceToScroll())
                 {
                     if (dir == WidgetDirection::Up)
                         m_autoScrollValue -= m_autoScrollArrowDelta;
                     else if (dir == WidgetDirection::Down)
                         m_autoScrollValue += m_autoScrollArrowDelta;
                 }
                 if (!TestAutoscrollLimit())
                     return true;
             }
         }
         return ClipWidget::FocusTowards(dir);
     }
Load()
void ScrollableWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 18 of file ScrollableWidget.as.
References Widget::Load(), m_autoScroll, m_autoScrollArrowDelta, m_autoScrollHeight, m_autoScrollLimits, m_autoScrollValue, and m_scrollBackdropSprite.
     {
         ClipWidget::Load(ctx);
         m_autoScroll = ctx.GetBoolean("autoscroll", false, m_autoScroll);
         m_autoScrollHeight = ctx.GetInteger("autoscroll-height", false, m_autoScrollHeight);
         m_autoScrollValue = ctx.GetInteger("autoscroll-value", false, m_autoScrollValue);
         m_autoScrollArrowDelta = ctx.GetInteger("autoscroll-arrow-delta", false, m_autoScrollArrowDelta);
         m_autoScrollLimits = ctx.GetBoolean("autoscroll-limits", false, m_autoScrollLimits);
         auto def = ctx.GetGUIDef();
         @m_scrollBackdropSprite = def.GetSprite(ctx.GetString("scroll-backdrop-sprite", false));
     }
PauseScrolling()
void ScrollableWidget::PauseScrolling () inline private
Definition at line 155 of file ScrollableWidget.as.
References m_scrollingPaused.
Referenced by Menu::SlotsMenu::RefreshSlots().
     {
         m_scrollingPaused = true;
     }
ResumeScrolling()
void ScrollableWidget::ResumeScrolling () inline private
Definition at line 160 of file ScrollableWidget.as.
References m_scrollingPaused, and TestAutoscrollLimit().
Referenced by Menu::SlotsMenu::RefreshSlots().
     {
         m_scrollingPaused = false;
         TestAutoscrollLimit();
     }
ScrollDown()
void ScrollableWidget::ScrollDown () inline private
Definition at line 193 of file ScrollableWidget.as.
References m_autoScrollHeight, m_autoScrollValue, Widget::m_height, Widget::m_padding, and TestAutoscrollLimit().
Referenced by GameChatWidget::AddChat().
     {
         int scrollWidgetHeight = int(m_height - m_padding.y);
         m_autoScrollValue = m_autoScrollHeight - scrollWidgetHeight;
         TestAutoscrollLimit();
     }
ScrollUp()
void ScrollableWidget::ScrollUp () inline private
Definition at line 187 of file ScrollableWidget.as.
References m_autoScrollValue, and TestAutoscrollLimit().
     {
         m_autoScrollValue = 0;
         TestAutoscrollLimit();
     }
ShouldDrawChild()
bool ScrollableWidget::ShouldDrawChild (Widget@ child) inline override private
Definition at line 56 of file ScrollableWidget.as.
References Widget::GetOrigin(), m_autoScroll, and Widget::m_height.
     {
         if (!m_autoScroll)
             return true;
         vec2 childOrigin = child.GetOrigin();
         vec2 origin = GetOrigin();
         if (childOrigin.y + child.m_height > origin.y && childOrigin.y < origin.y + m_height)
             return true;
         return false;
     }
SpaceToScroll()
bool ScrollableWidget::SpaceToScroll () inline private
Definition at line 218 of file ScrollableWidget.as.
References m_autoScrollHeight, Widget::m_height, and Widget::m_padding.
Referenced by FocusTowards(), and UpdateInput().
     {
         // The widget height, minus the padding (so that we can scroll far enough to have our Y padding left)
         int scrollWidgetHeight = int(m_height - m_padding.y);
         return m_autoScrollHeight > scrollWidgetHeight;
     }
TestAutoscrollLimit()
bool ScrollableWidget::TestAutoscrollLimit () inline private
Definition at line 200 of file ScrollableWidget.as.
References m_autoScrollHeight, m_autoScrollLimits, m_autoScrollValue, Widget::m_height, and Widget::m_padding.
Referenced by DoLayout(), FocusTowards(), ResumeScrolling(), ScrollDown(), Widget::ScrollTo(), ScrollUp(), ScrollbarWidget::Update(), and UpdateInput().
     {
         if (!m_autoScrollLimits)
             return false;
         int scrollWidgetHeight = int(m_height - m_padding.y);
         if (m_autoScrollValue <= 0)
         {
             m_autoScrollValue = 0;
             return true;
         }
         else if (m_autoScrollHeight >= 0 && m_autoScrollValue >= m_autoScrollHeight - scrollWidgetHeight)
         {
             m_autoScrollValue = m_autoScrollHeight - scrollWidgetHeight;
             return true;
         }
         return false;
     }
UpdateInput()
bool ScrollableWidget::UpdateInput (vec2 origin, vec2 parentSz, vec3 mousePos) inline override private
Definition at line 103 of file ScrollableWidget.as.
References abs(), m_autoScroll, m_autoScrollValue, Widget::m_hovering, SpaceToScroll(), TestAutoscrollLimit(), and Widget::UpdateInput().
     {
         if (m_autoScroll && int(mousePos.z) != 0 && m_hovering && SpaceToScroll())
         {
             int scrollStep = 20 * int(abs(mousePos.z));
             if (mousePos.z < 0)
                 m_autoScrollValue += scrollStep;
             else if (mousePos.z > 0)
                 m_autoScrollValue -= scrollStep;
             // if this one can still scroll further, don't allow children to respond to mouse wheel events
             if (!TestAutoscrollLimit())
                 mousePos.z = 0;
         }
         return ClipWidget::UpdateInput(origin, parentSz, mousePos);
     }
Member Data Documentation
m_autoScroll
bool ScrollableWidget::m_autoScroll = true private
Definition at line 8 of file ScrollableWidget.as.
Referenced by AddChild(), ClearChildren(), DebugDraw(), DoLayout(), FocusTowards(), Widget::FocusTowards(), FilteredListWidget::Load(), Load(), CheckBoxGroupWidget::Load(), Widget::ScrollTo(), ShouldDrawChild(), and UpdateInput().
m_autoScrollArrowDelta
int ScrollableWidget::m_autoScrollArrowDelta = 40 private
Definition at line 11 of file ScrollableWidget.as.
Referenced by FocusTowards(), and Load().
m_autoScrollHeight
int ScrollableWidget::m_autoScrollHeight = -1 private
Definition at line 9 of file ScrollableWidget.as.
Referenced by AddChild(), ClearChildren(), DebugDraw(), DoLayout(), Widget::FocusTowards(), Load(), ScrollDown(), FilteredListWidget::SetFilter(), SpaceToScroll(), TestAutoscrollLimit(), and ScrollbarWidget::Update().
m_autoScrollLimits
bool ScrollableWidget::m_autoScrollLimits = true private
Definition at line 12 of file ScrollableWidget.as.
Referenced by Load(), and TestAutoscrollLimit().
m_autoScrollValue
int ScrollableWidget::m_autoScrollValue = 0 private
Definition at line 10 of file ScrollableWidget.as.
Referenced by ClearChildren(), DebugDraw(), DoDraw(), DoLayout(), FocusTowards(), Load(), ScrollDown(), Widget::ScrollTo(), ScrollUp(), TestAutoscrollLimit(), ScrollbarWidget::Update(), and UpdateInput().
m_scrollBackdropSprite
Sprite ScrollableWidget::m_scrollBackdropSprite private
Definition at line 16 of file ScrollableWidget.as.
Referenced by DoDraw(), and Load().
m_scrollingPaused
bool ScrollableWidget::m_scrollingPaused private
Definition at line 14 of file ScrollableWidget.as.
Referenced by AddChild(), ClearChildren(), PauseScrolling(), and ResumeScrolling().
The documentation for this class was generated from the following file:
scripts/GUI/ScrollableWidget.as