HoHDocs: ActorFootsteps Class Reference
ActorFootsteps Class Reference
Private Member Functions
ActorFootsteps (UnitPtr unit, SValue@ params)
vec3 GetFootPosition ()
void NextFoot ()
void StepSound ()
void StepEffect ()
void Update (int dt, bool force=false)
Private Attributes
UnitPtr m_unit
array< SoundEvent@> m_walkSounds
int m_currWalkSound
int m_delaySound
int m_delaySoundC
int m_delayEffect
int m_delayEffectC
bool m_tileEffects
bool m_paused
int m_feetCount
int m_currentFoot
int m_nextFootWait
int m_nextFootWaitC
int m_feetDistance
int m_feetDistanceFar
float m_facingDirection
Detailed Description
Definition at line 1 of file ActorFootsteps.as.
Constructor & Destructor Documentation
ActorFootsteps()
ActorFootsteps::ActorFootsteps (UnitPtr unit, SValue@ params) inline private
Definition at line 28 of file ActorFootsteps.as.
References m_delayEffect, m_delaySound, m_feetCount, m_feetDistance, m_feetDistanceFar, m_nextFootWait, m_nextFootWaitC, m_tileEffects, m_unit, m_walkSounds, and unit.
     {
         m_unit = unit;
         int i = 0;
         while (true)
         {
             string res = GetParamString(unit, params, "walk-snd-" + i++, false, "");
             if (res != "")
                 m_walkSounds.insertLast(Resources::GetSoundEvent(res));
             else
                 break;
         }
         if (m_walkSounds.get_length() == 0)
             m_walkSounds.insertLast(Resources::GetSoundEvent(GetParamString(unit, params, "walk-snd", false)));
         m_tileEffects = GetParamBool(unit, params, "tile-effects", false, true);
         int delay = GetParamInt(unit, params, "delay", false, -1);
         if (delay == -1)
         {
             m_delaySound = GetParamInt(unit, params, "snd-delay");
             m_delayEffect = GetParamInt(unit, params, "fx-delay");
         }
         else
             m_delaySound = m_delayEffect = delay;
         m_feetCount = GetParamInt(unit, params, "feet-count", false, 2);
         m_nextFootWaitC = m_nextFootWait = GetParamInt(unit, params, "feet-wait", false, 0);
         m_feetDistance = GetParamInt(unit, params, "feet-distance", false, 0);
         m_feetDistanceFar = GetParamInt(unit, params, "feet-distance-far", false, 0);
     }
Member Function Documentation
GetFootPosition()
vec3 ActorFootsteps::GetFootPosition () inline private
Definition at line 63 of file ActorFootsteps.as.
References m_currentFoot, m_facingDirection, m_feetCount, m_feetDistance, m_feetDistanceFar, m_unit, and xyz().
Referenced by StepEffect(), and StepSound().
     {
         vec3 pos = m_unit.GetPosition();
         if (m_feetCount > 0 && (m_feetCount % 2 == 0))
         {
             if (m_feetDistance > 0)
             {
                 float footOffset = m_feetDistance / 2.0;
                 if (m_currentFoot == 0)
                     footOffset *= -1;
                 float dir = m_facingDirection + PI / 2.0;
                 pos += vec3(cos(dir), sin(dir), 0) * footOffset;
             }
             if (m_feetDistanceFar > 0)
             {
                 float dir = m_facingDirection + PI;
                 pos += vec3(cos(dir), sin(dir), 0) * m_feetDistanceFar;
             }
         }
         else if (m_feetCount > 1)
             pos += xyz(m_unit.FetchLocator("foot-pos-" + m_currentFoot));
         else if (m_feetCount == 1)
             pos += xyz(m_unit.FetchLocator("foot-pos"));
         return pos;
     }
NextFoot()
void ActorFootsteps::NextFoot () inline private
Definition at line 89 of file ActorFootsteps.as.
References m_currentFoot, m_feetCount, m_nextFootWait, and m_nextFootWaitC.
Referenced by StepEffect().
     {
         if (m_nextFootWaitC > 0)
         {
             m_nextFootWaitC--;
             return;
         }
         m_nextFootWaitC = m_nextFootWait;
         m_currentFoot = (m_currentFoot + 1) % m_feetCount;
     }
StepEffect()
void ActorFootsteps::StepEffect () inline private
Definition at line 114 of file ActorFootsteps.as.
References g_scene, GetFootPosition(), m_paused, NextFoot(), PlayEffect(), and xy().
Referenced by Update().
     {
         if (m_paused)
             return;
         vec3 pos = GetFootPosition();
         NextFoot();
         array<Tileset@>@ tilesets = g_scene.FetchTilesets(xy(pos));
         for (int i = tilesets.length() - 1; i >= 0; i--)
         {
             auto tsd = tilesets[i].GetData();
             if (tsd is null)
                 continue;
             SValue@ svBlockStepEffect = tsd.GetDictionaryEntry("block-step-effect");
             if (svBlockStepEffect !is null && svBlockStepEffect.GetType() == SValueType::Boolean)
             {
                 if (svBlockStepEffect.GetBoolean())
                     break;
             }
             SValue@ svStepEffect = tsd.GetDictionaryEntry("step-effect");
             if (svStepEffect is null || svStepEffect.GetType() != SValueType::String)
                 continue;
             string stepFx = svStepEffect.GetString();
             PlayEffect(stepFx, xy(pos));
             SValue@ svPrioStepEffect = tsd.GetDictionaryEntry("prio-step-effect");
             if (svPrioStepEffect !is null && svPrioStepEffect.GetType() == SValueType::Boolean)
             {
                 if (svPrioStepEffect.GetBoolean())
                     break;
             }
         }
     }
StepSound()
void ActorFootsteps::StepSound () inline private
Definition at line 100 of file ActorFootsteps.as.
References GetFootPosition(), m_currWalkSound, m_paused, m_walkSounds, and PlaySound3D().
Referenced by Update().
     {
         if (m_paused)
             return;
         vec3 pos = GetFootPosition();
         if (m_walkSounds.length() > 0)
         {
             PlaySound3D(m_walkSounds[m_currWalkSound], pos);
             m_currWalkSound = (m_currWalkSound + 1) % m_walkSounds.length();
         }
     }
Update()
void ActorFootsteps::Update (int dt, bool force = false) inline private
Definition at line 152 of file ActorFootsteps.as.
References force, m_delayEffect, m_delayEffectC, m_delaySound, m_delaySoundC, m_tileEffects, m_unit, StepEffect(), StepSound(), and CVars::UseTileEffects.
Referenced by MeleeMovement::ClientUpdate(), ChargeMovement::ClientUpdate(), MeleeMovement::IdleUpdate(), CirclingMovement::Update(), TargetMovement::Update(), RangedMovement::Update(), ChargeMovement::Update(), MeleeMovement::Update(), and PlayerBase::UpdateFootsteps().
     {
         auto bdy = m_unit.GetPhysicsBody();
         if (bdy is null)
             return;
         bool walking = force || (lengthsq(m_unit.GetMoveDir()) > 0.1);
         if (!walking)
             return;
         m_delaySoundC -= dt;
         if (m_delaySoundC <= 0)
         {
             m_delaySoundC += m_delaySound;
             StepSound();
         }
         if (m_tileEffects && CVars::UseTileEffects)
         {
             m_delayEffectC -= dt;
             if (m_delayEffectC <= 0)
             {
                 m_delayEffectC += m_delayEffect;
                 StepEffect();
             }
         }
     }
Member Data Documentation
m_currentFoot
int ActorFootsteps::m_currentFoot private
Definition at line 19 of file ActorFootsteps.as.
Referenced by GetFootPosition(), and NextFoot().
m_currWalkSound
int ActorFootsteps::m_currWalkSound private
Definition at line 6 of file ActorFootsteps.as.
Referenced by StepSound().
m_delayEffect
int ActorFootsteps::m_delayEffect private
Definition at line 11 of file ActorFootsteps.as.
Referenced by ActorFootsteps(), and Update().
m_delayEffectC
int ActorFootsteps::m_delayEffectC private
Definition at line 12 of file ActorFootsteps.as.
Referenced by Update().
m_delaySound
int ActorFootsteps::m_delaySound private
Definition at line 8 of file ActorFootsteps.as.
Referenced by ActorFootsteps(), and Update().
m_delaySoundC
int ActorFootsteps::m_delaySoundC private
Definition at line 9 of file ActorFootsteps.as.
Referenced by Update().
m_facingDirection
float ActorFootsteps::m_facingDirection private
Definition at line 26 of file ActorFootsteps.as.
Referenced by MeleeMovement::ClientUpdate(), ChargeMovement::ClientUpdate(), GetFootPosition(), MeleeMovement::IdleUpdate(), PlayerBase::SetAngle(), CirclingMovement::Update(), TargetMovement::Update(), RangedMovement::Update(), ChargeMovement::Update(), and MeleeMovement::Update().
m_feetCount
int ActorFootsteps::m_feetCount private
Definition at line 18 of file ActorFootsteps.as.
Referenced by ActorFootsteps(), GetFootPosition(), and NextFoot().
m_feetDistance
int ActorFootsteps::m_feetDistance private
Definition at line 23 of file ActorFootsteps.as.
Referenced by ActorFootsteps(), and GetFootPosition().
m_feetDistanceFar
int ActorFootsteps::m_feetDistanceFar private
Definition at line 24 of file ActorFootsteps.as.
Referenced by ActorFootsteps(), and GetFootPosition().
m_nextFootWait
int ActorFootsteps::m_nextFootWait private
Definition at line 20 of file ActorFootsteps.as.
Referenced by ActorFootsteps(), and NextFoot().
m_nextFootWaitC
int ActorFootsteps::m_nextFootWaitC private
Definition at line 21 of file ActorFootsteps.as.
Referenced by ActorFootsteps(), and NextFoot().
m_paused
bool ActorFootsteps::m_paused private
Definition at line 16 of file ActorFootsteps.as.
Referenced by StepEffect(), and StepSound().
m_tileEffects
bool ActorFootsteps::m_tileEffects private
Definition at line 14 of file ActorFootsteps.as.
Referenced by ActorFootsteps(), and Update().
m_unit
UnitPtr ActorFootsteps::m_unit private
Definition at line 3 of file ActorFootsteps.as.
Referenced by ActorFootsteps(), GetFootPosition(), and Update().
m_walkSounds
array<SoundEvent@> ActorFootsteps::m_walkSounds private
Definition at line 5 of file ActorFootsteps.as.
Referenced by ActorFootsteps(), and StepSound().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/ActorFootsteps.as