HoHDocs: StaticLevel Class Reference
StaticLevel Class Reference
Private Member Functions
StaticLevel (Scene@ scene)
void Start (uint8 peer, SValue@ save, StartMode sMode) override
Private Attributes
EnemyPlacement m_enemyPlacer
Detailed Description
Definition at line 2 of file StaticLevel.as.
Constructor & Destructor Documentation
StaticLevel()
StaticLevel::StaticLevel (Scene@ scene) inline private
Definition at line 6 of file StaticLevel.as.
     {
         super(scene);
     }
Member Function Documentation
Start()
void StaticLevel::Start (uint8 peer, SValue@ save, StartMode sMode) inline override private
Definition at line 11 of file StaticLevel.as.
References Stats::Add(), DungeonLevelRichPresence(), GetLocalPlayerRecord(), m_enemyPlacer, BaseGameMode::m_levelCount, MakeDungeonGenerator(), Campaign::PostStart(), SetLevelFlags(), and Campaign::Start().
     {
         Campaign::Start(peer, save, sMode);
         SetLevelFlags(m_levelCount);
         Campaign::PostStart();
         int numPlrs = 1;
         if (save !is null)
             numPlrs = GetParamInt(UnitPtr(), save, "num-plrs", false, 1);
         DungeonGenerator@ dgn = MakeDungeonGenerator(m_levelCount, numPlrs);
         if (dgn !is null)
             @m_enemyPlacer = dgn.m_enemyPlacer;
         else
             print("Null dungeon");
         auto record = GetLocalPlayerRecord();
         Stats::Add("floors-visited", 1, record);
         DungeonLevelRichPresence(this);
     }
Member Data Documentation
m_enemyPlacer
EnemyPlacement StaticLevel::m_enemyPlacer private
Definition at line 4 of file StaticLevel.as.
Referenced by Start().
The documentation for this class was generated from the following file:
scripts/GameModes/StaticLevel.as