HoHDocs: GiveOre Class Reference
GiveOre Class Reference
Private Member Functions
GiveOre (UnitPtr unit, SValue &params)
void SetWeaponInformation (uint weapon)
bool Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
bool CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
Private Attributes
int m_amount
bool m_pickup
Detailed Description
Definition at line 1 of file GiveOre.as.
Constructor & Destructor Documentation
GiveOre()
GiveOre::GiveOre (UnitPtr unit, SValue & params) inline private
Definition at line 6 of file GiveOre.as.
References m_amount, m_pickup, and unit.
     {
         m_amount = GetParamInt(unit, params, "amount");
         m_pickup = GetParamBool(unit, params, "pickup", false, false);
     }
Member Function Documentation
Apply()
bool GiveOre::Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk) inline private
Definition at line 14 of file GiveOre.as.
References CanApply(), GetLocalPlayer(), GiveOreImpl(), m_amount, and m_pickup.
     {
         if (!CanApply(owner, target, pos, dir, intensity))
             return false;
         if (m_pickup)
         {
             auto localPlayer = GetLocalPlayer();
             GiveOreImpl(m_amount, localPlayer, localPlayer is cast<Player>(target.GetScriptBehavior()));
         }
         else
             GiveOreImpl(m_amount, cast<Player>(target.GetScriptBehavior()));
         return true;
     }
CanApply()
bool GiveOre::CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) inline override private
Definition at line 30 of file GiveOre.as.
Referenced by Apply().
     {
         return true;
     }
SetWeaponInformation()
void GiveOre::SetWeaponInformation (uint weapon) inline private
Definition at line 12 of file GiveOre.as.
 {}
Member Data Documentation
m_amount
int GiveOre::m_amount private
Definition at line 3 of file GiveOre.as.
Referenced by Apply(), and GiveOre().
m_pickup
bool GiveOre::m_pickup private
Definition at line 4 of file GiveOre.as.
Referenced by Apply(), and GiveOre().
The documentation for this class was generated from the following file:
scripts/Behaviors/Effects/GiveOre.as