HoHDocs: WorldScript::ProjectileShooter Class Reference
WorldScript::ProjectileShooter Class Reference
Private Member Functions
UnitPtr ProduceProjectile (int id)
SValue ServerExecute ()
void ClientExecute (SValue@ val)
Private Attributes
vec3 Position
UnitProducer Projectile
int Direction
int Spread
Detailed Description
Definition at line 4 of file ProjectileShooter.as.
Member Function Documentation
ClientExecute()
void WorldScript::ProjectileShooter::ClientExecute (SValue@ val) inline private
Definition at line 51 of file ProjectileShooter.as.
References ProduceProjectile().
         {
             if (val is null)
                 return;
             auto arr = val.GetArray();
             UnitPtr proj = ProduceProjectile(arr[0].GetInteger());
             if (!proj.IsValid())
                 return;
             IProjectile@ p = cast<IProjectile>(proj.GetScriptBehavior());
             if (p is null)
                 return;
             auto ang = arr[1].GetFloat();
             p.Initialize(null, vec2(cos(ang), sin(ang)), 1.0, true, null, 0);
         }
ProduceProjectile()
UnitPtr WorldScript::ProjectileShooter::ProduceProjectile (int id) inline private
Definition at line 18 of file ProjectileShooter.as.
References g_scene, and Position.
Referenced by ClientExecute(), and ServerExecute().
         {
             UnitPtr proj = Projectile.Produce(g_scene, Position, id);
             if (!proj.IsValid())
                 return UnitPtr();
             return proj;
         }
ServerExecute()
SValue WorldScript::ProjectileShooter::ServerExecute () inline private
Definition at line 27 of file ProjectileShooter.as.
References Direction, ProduceProjectile(), and Spread.
         {
             UnitPtr proj = ProduceProjectile(0);
             if (!proj.IsValid())
                 return null;
             IProjectile@ p = cast<IProjectile>(proj.GetScriptBehavior());
             if (p is null)
                 return null;
             float ang = Direction;
             ang += randf() * Spread - Spread / 2.f;
             ang = ang / 180.f * PI;
             p.Initialize(null, vec2(cos(ang), sin(ang)), 1.0, false, null, 0);
             SValueBuilder sval;
             sval.PushArray();
             sval.PushInteger(proj.GetId());
             sval.PushFloat(ang);
             return sval.Build();
         }
Member Data Documentation
Direction
int WorldScript::ProjectileShooter::Direction private
Definition at line 12 of file ProjectileShooter.as.
Referenced by ServerExecute().
Position
vec3 WorldScript::ProjectileShooter::Position private
Definition at line 6 of file ProjectileShooter.as.
Referenced by ProduceProjectile().
Projectile
UnitProducer WorldScript::ProjectileShooter::Projectile private
Definition at line 9 of file ProjectileShooter.as.
Spread
int WorldScript::ProjectileShooter::Spread private
Definition at line 15 of file ProjectileShooter.as.
Referenced by ServerExecute().
The documentation for this class was generated from the following file:
scripts/WorldScript/ProjectileShooter.as