HoHDocs: ShopMenuContent Class Reference
ShopMenuContent Class Reference
Private Member Functions
ShopMenuContent (ShopMenu@ shopMenu)
string GetTitle ()
void OnShow ()
void OnClose ()
string GetGuiFilename ()
void Update (int dt)
void ReloadList ()
bool BuyItem (Upgrades::Upgrade@ upgrade, Upgrades::UpgradeStep@ step)
void OnFunc (Widget@ sender, string name)
Private Attributes
ShopMenu m_shopMenu
GUIDef m_def
Widget m_widget
Detailed Description
Definition at line 1 of file ShopMenuContent.as.
Constructor & Destructor Documentation
ShopMenuContent()
ShopMenuContent::ShopMenuContent (ShopMenu@ shopMenu) inline private
Definition at line 8 of file ShopMenuContent.as.
References m_shopMenu.
     {
         @m_shopMenu = shopMenu;
     }
Member Function Documentation
BuyItem()
bool ShopMenuContent::BuyItem (Upgrades::Upgrade@ upgrade, Upgrades::UpgradeStep@ step) inline private
Definition at line 42 of file ShopMenuContent.as.
References Upgrades::UpgradeStep::BuyNow(), Upgrades::UpgradeStep::CanAfford(), GetLocalPlayer(), GetLocalPlayerRecord(), Upgrades::UpgradeStep::m_costOre, Upgrades::UpgradeStep::m_costSkillPoints, Upgrades::Upgrade::m_id, Upgrades::UpgradeStep::m_level, m_shopMenu, ShopMenu::m_sndBuyGold, ShopMenu::m_sndBuyOre, ShopMenu::m_sndBuySkill, ShopMenu::m_sndCantBuy, Upgrades::UpgradeStep::PayForUpgrade(), PlaySound2D(), and Upgrades::Upgrade::ShouldRemember().
Referenced by DungeonStoreMenuContent::BuyItem(), TownhallMenuContent::BuyItem(), ChapelShopMenuContent::BuyItem(), and OnFunc().
     {
         auto record = GetLocalPlayerRecord();
         auto player = GetLocalPlayer();
         if (player is null)
         {
             PrintError("Player is dead");
             PlaySound2D(m_shopMenu.m_sndCantBuy);
             return false;
         }
         if (!step.CanAfford(record))
         {
             PrintError("Too expensive");
             PlaySound2D(m_shopMenu.m_sndCantBuy);
             return false;
         }
         if (!step.BuyNow(record))
         {
             PlaySound2D(m_shopMenu.m_sndCantBuy);
             return false;
         }
         if (upgrade.ShouldRemember())
         {
             OwnedUpgrade@ ownedUpgrade = record.GetOwnedUpgrade(upgrade.m_id);
             if (ownedUpgrade !is null)
             {
                 ownedUpgrade.m_level = step.m_level;
                 @ownedUpgrade.m_step = step;
             }
             else
             {
                 @ownedUpgrade = OwnedUpgrade();
                 ownedUpgrade.m_id = upgrade.m_id;
                 ownedUpgrade.m_level = step.m_level;
                 @ownedUpgrade.m_step = step;
                 record.upgrades.insertLast(ownedUpgrade);
             }
         }
         step.PayForUpgrade(record);
         (Network::Message("PlayerGiveUpgrade") << upgrade.m_id << step.m_level).SendToAll();
         if (step.m_costSkillPoints > 0)
             PlaySound2D(m_shopMenu.m_sndBuySkill);
         else if (step.m_costOre > 0)
             PlaySound2D(m_shopMenu.m_sndBuyOre);
         else
             PlaySound2D(m_shopMenu.m_sndBuyGold);
         return true;
     }
GetGuiFilename()
string ShopMenuContent::GetGuiFilename () inline private
Definition at line 29 of file ShopMenuContent.as.
Referenced by ShopMenu::Show().
     {
         return "gui/shop/none.gui";
     }
GetTitle()
string ShopMenuContent::GetTitle () inline private
Definition at line 13 of file ShopMenuContent.as.
Referenced by ShopMenu::Show().
     {
         return "none";
     }
OnClose()
void ShopMenuContent::OnClose () inline private
Definition at line 22 of file ShopMenuContent.as.
References g_gameMode.
Referenced by ShopMenu::Close().
     {
         auto gm = cast<Campaign>(g_gameMode);
         if (gm !is null)
             gm.SaveLocalTown();
     }
OnFunc()
void ShopMenuContent::OnFunc (Widget@ sender, string name) inline private
Definition at line 99 of file ShopMenuContent.as.
References BuyItem(), name, and ReloadList().
Referenced by GeneralStoreMenuContent::OnFunc(), ShopMenu::OnFunc(), DrinksMenuContent::OnFunc(), OnFunc(), ChapelShopMenuContent::OnFunc(), and SkillsShopMenuContent::OnFunc().
     {
         auto parse = name.split(" ");
         if (parse[0] == "buy-item")
         {
             auto btn = cast<UpgradeShopButtonWidget>(sender);
             if (btn !is null)
             {
                 if (BuyItem(btn.m_upgrade, btn.m_upgradeStep))
                     ReloadList();
             }
         }
     }
OnShow()
void ShopMenuContent::OnShow () inline private
Definition at line 18 of file ShopMenuContent.as.
Referenced by ShopMenu::Show().
     {
     }
ReloadList()
void ShopMenuContent::ReloadList () inline private
Definition at line 38 of file ShopMenuContent.as.
Referenced by OnFunc(), OnFunc(), and OnShow().
     {
     }
Update()
void ShopMenuContent::Update (int dt) inline private
Definition at line 34 of file ShopMenuContent.as.
Referenced by ShopMenu::Update().
     {
     }
Member Data Documentation
m_def
GUIDef ShopMenuContent::m_def private
Definition at line 5 of file ShopMenuContent.as.
Referenced by ChapelShopMenuContent::OnShow(), SkillsShopMenuContent::OnShow(), TownhallMenuContent::OnShow(), DrinksMenuContent::ReloadList(), and ShopMenu::Show().
m_shopMenu
ShopMenu ShopMenuContent::m_shopMenu private
Definition at line 3 of file ShopMenuContent.as.
Referenced by TownhallMenuContent::AddButton(), BuyItem(), StatuesShopMenuContent::NumSlotsForLevel(), GeneralStoreMenuContent::OnFunc(), OnFunc(), ChapelShopMenuContent::OnFunc(), SkillsShopMenuContent::OnFunc(), FountainShopMenuContent::OnFunc(), StatuesShopMenuContent::RefreshBuyList(), StatuesShopMenuContent::RefreshPlacementList(), DrinksMenuContent::ReloadList(), GeneralStoreMenuContent::ReloadList(), FountainShopMenuContent::ReloadList(), UpgradeShopMenuContent::ReloadList(), ChapelShopMenuContent::ReloadList(), SkillsShopMenuContent::ReloadList(), TownhallMenuContent::ReloadList(), UpgradeShopButtonWidget::Set(), ShopMenuContent(), ChapelShopMenuContent::ShouldEnableButton(), and FountainShopMenuContent::UpdateInterface().
m_widget
Widget ShopMenuContent::m_widget private
Definition at line 6 of file ShopMenuContent.as.
Referenced by DrinksMenuContent::OnShow(), DungeonStoreMenuContent::OnShow(), StatuesShopMenuContent::OnShow(), GeneralStoreMenuContent::OnShow(), UpgradeShopMenuContent::OnShow(), ChapelShopMenuContent::OnShow(), FountainShopMenuContent::OnShow(), SkillsShopMenuContent::OnShow(), TownhallMenuContent::OnShow(), and ShopMenu::Show().
The documentation for this class was generated from the following file:
scripts/GUI/Shop/ShopMenuContent.as