HoHDocs: Modifiers::Thorns Class Reference
Modifiers::Thorns Class Reference
Private Member Functions
Thorns (UnitPtr unit, SValue &params)
bool HasDamageTaken () override
void DamageTaken (PlayerBase@ player, Actor@ enemy, int dmgAmnt) override
Private Attributes
float m_physical
float m_magical
Detailed Description
Definition at line 3 of file Thorns.as.
Constructor & Destructor Documentation
Thorns()
Modifiers::Thorns::Thorns (UnitPtr unit, SValue & params) inline private
Definition at line 8 of file Thorns.as.
References m_magical, m_physical, and unit.
         {
             m_physical = GetParamFloat(unit, params, "physical", false, 0);
             m_magical = GetParamFloat(unit, params, "magical", false, 0);
         }
Member Function Documentation
DamageTaken()
void Modifiers::Thorns::DamageTaken (PlayerBase@ player, Actor@ enemy, int dmgAmnt) inline override private
Definition at line 15 of file Thorns.as.
References Actor::Damage(), damage_round(), DamageInfo(), Actor::IsDead(), m_magical, m_physical, Actor::m_unit, and xy().
         {
             if (enemy is null || enemy.IsDead())
                 return;
             vec2 pos = xy(enemy.m_unit.GetPosition());
             vec2 dir = normalize(xy(enemy.m_unit.GetPosition() - player.m_unit.GetPosition()));
             uint weaponInfo = 0;
             auto dmg = DamageInfo(player, damage_round(dmgAmnt * m_physical), damage_round(dmgAmnt * m_magical), false, true, weaponInfo);
             dmg.LifestealMul = 0;
             enemy.Damage(dmg, pos, dir);
         }
HasDamageTaken()
bool Modifiers::Thorns::HasDamageTaken () inline override private
Definition at line 14 of file Thorns.as.
 { return true; }
Member Data Documentation
m_magical
float Modifiers::Thorns::m_magical private
Definition at line 6 of file Thorns.as.
Referenced by DamageTaken(), and Thorns().
m_physical
float Modifiers::Thorns::m_physical private
Definition at line 5 of file Thorns.as.
Referenced by DamageTaken(), and Thorns().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Modifiers/Thorns.as