HoHDocs: Menu::MultiplayerMenu Class Reference
Menu::MultiplayerMenu Class Reference
Private Member Functions
MultiplayerMenu (MenuProvider@ provider)
void Initialize (GUIDef@ def) override
void Update (int dt) override
void OnFunc (Widget@ sender, string name) override
Private Attributes
array< ButtonWidget@> m_onlineWidgets
Detailed Description
Definition at line 3 of file MultiplayerMenu.as.
Constructor & Destructor Documentation
MultiplayerMenu()
Menu::MultiplayerMenu::MultiplayerMenu (MenuProvider@ provider) inline private
Definition at line 7 of file MultiplayerMenu.as.
References Menu::Menu::m_isPopup.
         {
             super(provider);
             m_isPopup = true;
         }
Member Function Documentation
Initialize()
void Menu::MultiplayerMenu::Initialize (GUIDef@ def) inline override private
Definition at line 14 of file MultiplayerMenu.as.
References Menu::Menu::Initialize(), m_onlineWidgets, and m_widget.
         {
             Menu::Initialize(def);
             m_onlineWidgets.insertLast(cast<ButtonWidget>(m_widget.GetWidgetById("createlobby")));
             m_onlineWidgets.insertLast(cast<ButtonWidget>(m_widget.GetWidgetById("serverlist")));
             m_onlineWidgets.insertLast(cast<ButtonWidget>(m_widget.GetWidgetById("loadgame")));
         }
OnFunc()
void Menu::MultiplayerMenu::OnFunc (Widget@ sender, string name) inline override private
Definition at line 32 of file MultiplayerMenu.as.
References Menu::Menu::m_provider, name, Menu::Menu::OnFunc(), Menu::Menu::OpenMenu(), and Menu::ServerlistMenu().
         {
             /*if (name == "createlobby")
                 OpenMenu(Menu::LobbyMenu(m_provider, true), "gui/main_menu/lobby.gui");
             else*/ if (name == "serverlist")
                 OpenMenu(Menu::ServerlistMenu(m_provider), "gui/main_menu/serverlist.gui");
             /*else if (name == "loadgame")
                 OpenMenu(LoadGameMenu(m_provider, true), "gui/main_menu/loadgame.gui");
             else if (name == "splitscreen")
                 OpenMenu(SplitscreenMenu(m_provider), "gui/main_menu/splitscreen.gui");*/
             else
                 Menu::OnFunc(sender, name);
         }
Update()
void Menu::MultiplayerMenu::Update (int dt) inline override private
Definition at line 23 of file MultiplayerMenu.as.
References m_onlineWidgets, SetEnabled(), and Menu::Update().
         {
             bool onlineAvailable = Platform::Service.IsMultiplayerAvailable();
             for (uint i = 0; i < m_onlineWidgets.length(); i++)
                 m_onlineWidgets[i].SetEnabled(onlineAvailable);
             Menu::Update(dt);
         }
Member Data Documentation
m_onlineWidgets
array<ButtonWidget@> Menu::MultiplayerMenu::m_onlineWidgets private
Definition at line 5 of file MultiplayerMenu.as.
Referenced by Initialize(), and Update().
The documentation for this class was generated from the following file:
scripts/GUI/Menus/MultiplayerMenu.as