HoHDocs: MenuProvider Class Reference
MenuProvider Class Reference
Private Member Functions
MenuProvider ()
void Initialize (GUIBuilder@ b, Menu::Menu@ menu, string initFile, string backdrop)
Menu::Menu GetCurrentMenu ()
Menu::Menu GetTopmostMenu ()
bool GoBack ()
void Update (int ms, GameInput &gameInput, MenuInput &menuInput)
void Render (int idt, SpriteBatch &sb)
Private Attributes
array< Menu::Menu@> m_menus
bool m_visible
Menu::Backdrop m_backdrop
Detailed Description
Definition at line 1 of file MenuProvider.as.
Constructor & Destructor Documentation
MenuProvider()
MenuProvider::MenuProvider () inline private
Definition at line 8 of file MenuProvider.as.
     {
     }
Member Function Documentation
GetCurrentMenu()
Menu::Menu MenuProvider::GetCurrentMenu () inline private
Definition at line 24 of file MenuProvider.as.
References m_menus.
Referenced by GoBack(), Initialize(), MainMenu::RenderFrame(), MainMenu::SetMenuState(), Update(), and MainMenu::UpdateFrame().
     {
         return m_menus[m_menus.length() - 1];
     }
GetTopmostMenu()
Menu::Menu MenuProvider::GetTopmostMenu () inline private
Definition at line 30 of file MenuProvider.as.
References m_menus.
     {
         for (uint i = m_menus.length() - 1; i >= 0; i--)
         {
             if (!m_menus[i].m_isPopup)
                 return m_menus[i];
         }
         return null;
     }
GoBack()
bool MenuProvider::GoBack () inline private
Definition at line 40 of file MenuProvider.as.
References GetCurrentMenu(), and Menu::Menu::GoBack().
Referenced by MainMenu::MenuBack().
     {
         return GetCurrentMenu().GoBack();
     }
Initialize()
void MenuProvider::Initialize (GUIBuilder@ b, Menu::Menu@ menu, string initFile, string backdrop) inline private
Definition at line 12 of file MenuProvider.as.
References Menu::Backdrop(), GetCurrentMenu(), Menu::Menu::Initialize(), m_backdrop, m_menus, and Menu::Menu::SetActive().
Referenced by MainMenu::LoadMenu().
     {
         m_menus.insertLast(menu);
         menu.Initialize(menu.LoadWidget(b, initFile));
         if (backdrop != "")
             @m_backdrop = Menu::Backdrop(b, backdrop);
         GetCurrentMenu().SetActive();
     }
Render()
void MenuProvider::Render (int idt, SpriteBatch & sb) inline private
Definition at line 61 of file MenuProvider.as.
References DialogWindow::Draw(), g_gameMode, m_backdrop, AGameMode::m_dialogWindow, m_menus, AGameMode::m_wndHeight, and AGameMode::m_wndWidth.
Referenced by MainMenu::RenderFrame().
     {
         if (m_backdrop !is null)
             m_backdrop.Draw(sb, idt);
         uint startMenu = 0;
         uint popupMenu = 0;
         for (uint i = m_menus.length() - 1; i >= 0; i--)
         {
             if (!m_menus[i].m_isPopup)
             {
                 startMenu = i;
                 break;
             }
             else
                 popupMenu = i;
         }
         int w = g_gameMode.m_wndWidth;
         int h = g_gameMode.m_wndHeight;
         for (uint i = startMenu; i < m_menus.length(); i++)
         {
             sb.Begin(w, h, 0.5);
             if (popupMenu > 0 && popupMenu == i)
                 sb.FillRectangle(vec4(0, 0, w, h), vec4(0, 0, 0, 0.75));
             m_menus[i].Draw(sb, idt);
             sb.End();
         }
         if (g_gameMode.m_dialogWindow !is null)
             g_gameMode.m_dialogWindow.Draw(sb, idt);
     }
Update()
void MenuProvider::Update (int ms, GameInput & gameInput, MenuInput & menuInput) inline private
Definition at line 45 of file MenuProvider.as.
References GetCurrentMenu(), m_backdrop, Menu::Menu::m_closing, m_menus, and Menu::Menu::SetActive().
Referenced by MainMenu::UpdateFrame().
     {
         if (m_backdrop !is null)
             m_backdrop.Update(ms);
         for (uint i = 0; i < m_menus.length(); i++)
             m_menus[i].Update(ms);
         Menu::Menu@ curr = GetCurrentMenu();
         if (curr.m_closing)
         {
             m_menus.removeAt(m_menus.length() - 1);
             GetCurrentMenu().SetActive();
         }
     }
Member Data Documentation
m_backdrop
Menu::Backdrop MenuProvider::m_backdrop private
Definition at line 6 of file MenuProvider.as.
Referenced by Initialize(), Render(), Menu::GraphicsMenu::Update(), and Update().
m_menus
array<Menu::Menu@> MenuProvider::m_menus private
Definition at line 3 of file MenuProvider.as.
Referenced by Menu::Menu::Close(), GetCurrentMenu(), MainMenu::GetServerlistMenu(), GetTopmostMenu(), Initialize(), MainMenu::LobbyInviteAccepted(), Menu::Menu::OpenMenu(), Menu::Menu::RemoveFromProvider(), Render(), and Update().
m_visible
bool MenuProvider::m_visible private
Definition at line 4 of file MenuProvider.as.
The documentation for this class was generated from the following file:
scripts/GUI/Menus/MenuProvider.as