HoHDocs: Skills::ChargeUnit Class Reference
Skills::ChargeUnit Class Reference
Private Member Functions
ChargeUnit (UnitPtr unit, SValue &params)
float GetMoveSpeedMul () override
TargetingMode GetTargetingMode (int &out size) override
void StartChargeEffect ()
void StartFullChargeEffect ()
bool Activate (vec2 target) override
void NetActivate (vec2 target) override
void Hold (int dt, vec2 target) override
void NetHold (int dt, vec2 target) override
void Release (vec2 target) override
void NetRelease (vec2 target) override
UnitPtr DoShoot (float charge, vec2 target, int id=0)
void DoUpdate (int dt) override
Private Attributes
int m_tmCharge
int m_tmChargeMax
int m_holdFrame
UnitProducer m_prod
string m_fxCharged
float m_dist
bool m_pressOk = false
UnitPtr m_chargeFx
UnitPtr m_chargeFullFx
Detailed Description
Definition at line 3 of file ChargeUnit.as.
Constructor & Destructor Documentation
ChargeUnit()
Skills::ChargeUnit::ChargeUnit (UnitPtr unit, SValue & params) inline private
Definition at line 20 of file ChargeUnit.as.
References m_dist, m_fxCharged, m_holdFrame, m_prod, m_tmChargeMax, and unit.
         {
             super(unit, params);
             m_tmChargeMax = GetParamInt(unit, params, "charge-max", false, 2000);
             m_holdFrame = GetParamInt(unit, params, "hold-frame", false, -1);
             @m_prod = Resources::GetUnitProducer(GetParamString(unit, params, "unit"));
             m_fxCharged = GetParamString(unit, params, "fx-charged", false, "");
             m_dist = GetParamFloat(unit, params, "dist", false, 1.0f);
         }
Member Function Documentation
Activate()
bool Skills::ChargeUnit::Activate (vec2 target) inline override private
Definition at line 59 of file ChargeUnit.as.
References Skills::ActiveSkill::Activate(), Skills::m_isActive, m_pressOk, m_tmCharge, and StartChargeEffect().
         {
             if (m_isActive)
                 return false;
             if (ActiveSkill::Activate(target))
             {
                 m_tmCharge = 0;
                 m_pressOk = true;
                 StartChargeEffect();
                 return true;
             }
             m_pressOk = false;
             return false;
         }
DoShoot()
UnitPtr Skills::ChargeUnit::DoShoot (float charge, vec2 target, int id = 0) inline private
Definition at line 161 of file ChargeUnit.as.
References g_scene, m_dist, Skills::m_owner, m_prod, unit, xy(), and xyz().
Referenced by Release().
         {
             vec2 shootPos = xy(m_owner.m_unit.GetPosition());
             shootPos += target * m_dist;
             UnitPtr unit = m_prod.Produce(g_scene, xyz(shootPos), id);
             auto proj = cast<IProjectile>(unit.GetScriptBehavior());
             if (proj !is null)
                 proj.Initialize(m_owner, target, charge, false, null, 0);
             return unit;
         }
DoUpdate()
void Skills::ChargeUnit::DoUpdate (int dt) inline override private
Definition at line 175 of file ChargeUnit.as.
References Skills::ActiveSkill::m_animCountdown, and Skills::m_isActive.
         {
             if (m_isActive)
                 m_animCountdown += dt;
         }
GetMoveSpeedMul()
float Skills::ChargeUnit::GetMoveSpeedMul () inline override private
Definition at line 34 of file ChargeUnit.as.
References Skills::m_isActive, m_pressOk, and Skills::ActiveSkill::m_speedMul.
         {
             if (m_isActive && m_pressOk)
                 return m_speedMul;
             return 1.0f;
         }
GetTargetingMode()
TargetingMode Skills::ChargeUnit::GetTargetingMode (int &out size) inline override private
Definition at line 41 of file ChargeUnit.as.
References Skills::Channeling.
 { return TargetingMode::Channeling; }
Hold()
void Skills::ChargeUnit::Hold (int dt, vec2 target) inline override private
Definition at line 85 of file ChargeUnit.as.
References Skills::ActiveSkill::Hold(), Skills::ActiveSkill::m_cooldown, Skills::ActiveSkill::m_cooldownC, m_holdFrame, Skills::m_owner, m_pressOk, m_tmCharge, m_tmChargeMax, min, and StartFullChargeEffect().
         {
             if (!m_pressOk)
                 return;
             if (m_holdFrame != -1)
                 m_owner.m_unit.SetUnitSceneTime(m_holdFrame);
             m_cooldownC = m_cooldown;
             if (m_tmCharge < m_tmChargeMax && m_tmCharge + dt >= m_tmChargeMax)
                 StartFullChargeEffect();
             m_tmCharge = min(m_tmChargeMax, m_tmCharge + dt);
             ActiveSkill::Hold(dt, target);
         }
NetActivate()
void Skills::ChargeUnit::NetActivate (vec2 target) inline override private
Definition at line 77 of file ChargeUnit.as.
References m_tmCharge, Skills::ActiveSkill::NetActivate(), and StartChargeEffect().
         {
             m_tmCharge = 0;
             StartChargeEffect();
             ActiveSkill::NetActivate(target);
         }
NetHold()
void Skills::ChargeUnit::NetHold (int dt, vec2 target) inline override private
Definition at line 102 of file ChargeUnit.as.
References m_holdFrame, Skills::m_owner, m_tmCharge, m_tmChargeMax, min, Skills::ActiveSkill::NetHold(), and StartFullChargeEffect().
         {
             if (m_holdFrame != -1)
                 m_owner.m_unit.SetUnitSceneTime(m_holdFrame);
             if (m_tmCharge < m_tmChargeMax && m_tmCharge + dt >= m_tmChargeMax)
                 StartFullChargeEffect();
             m_tmCharge = min(m_tmChargeMax, m_tmCharge + dt);
             ActiveSkill::NetHold(dt, target);
         }
NetRelease()
void Skills::ChargeUnit::NetRelease (vec2 target) inline override private
Definition at line 142 of file ChargeUnit.as.
References m_chargeFullFx, m_chargeFx, m_tmCharge, and Skills::ActiveSkill::NetRelease().
         {
             ActiveSkill::NetRelease(target);
             if (m_chargeFx.IsValid())
             {
                 m_chargeFx.Destroy();
                 m_chargeFx = UnitPtr();
             }
             if (m_chargeFullFx.IsValid())
             {
                 m_chargeFullFx.Destroy();
                 m_chargeFullFx = UnitPtr();
             }
             m_tmCharge = 0;
         }
Release()
void Skills::ChargeUnit::Release (vec2 target) inline override private
Definition at line 114 of file ChargeUnit.as.
References DoShoot(), m_chargeFullFx, m_chargeFx, m_pressOk, Skills::m_skillId, m_tmCharge, m_tmChargeMax, Skills::ActiveSkill::Release(), and unit.
         {
             ActiveSkill::Release(target);
             if (!m_pressOk)
                 return;
             if (m_chargeFx.IsValid())
             {
                 m_chargeFx.Destroy();
                 m_chargeFx = UnitPtr();
             }
             if (m_chargeFullFx.IsValid())
             {
                 m_chargeFullFx.Destroy();
                 m_chargeFullFx = UnitPtr();
             }
             float charge = m_tmCharge / float(m_tmChargeMax);
             UnitPtr unit = DoShoot(charge, target);
             m_pressOk = false;
             m_tmCharge = 0;
             (Network::Message("PlayerChargeUnit") << m_skillId << charge << target << unit.GetId()).SendToAll();
         }
StartChargeEffect()
void Skills::ChargeUnit::StartChargeEffect () inline private
Definition at line 43 of file ChargeUnit.as.
References m_chargeFx, Skills::ActiveSkill::m_fx, Skills::m_owner, and PlayEffect().
Referenced by Activate(), and NetActivate().
         {
             m_chargeFx = PlayEffect(m_fx, m_owner.m_unit);
             auto behavior = cast<EffectBehavior>(m_chargeFx.GetScriptBehavior());
             behavior.m_looping = true;
         }
StartFullChargeEffect()
void Skills::ChargeUnit::StartFullChargeEffect () inline private
Definition at line 51 of file ChargeUnit.as.
References m_chargeFullFx, m_fxCharged, Skills::m_owner, and PlayEffect().
Referenced by Hold(), and NetHold().
         {
             m_chargeFullFx = PlayEffect(m_fxCharged, m_owner.m_unit);
             auto behavior = cast<EffectBehavior>(m_chargeFullFx.GetScriptBehavior());
             behavior.m_looping = true;
         }
Member Data Documentation
m_chargeFullFx
UnitPtr Skills::ChargeUnit::m_chargeFullFx private
Definition at line 18 of file ChargeUnit.as.
Referenced by NetRelease(), Release(), and StartFullChargeEffect().
m_chargeFx
UnitPtr Skills::ChargeUnit::m_chargeFx private
Definition at line 17 of file ChargeUnit.as.
Referenced by NetRelease(), Release(), and StartChargeEffect().
m_dist
float Skills::ChargeUnit::m_dist private
Definition at line 13 of file ChargeUnit.as.
Referenced by ChargeUnit(), and DoShoot().
m_fxCharged
string Skills::ChargeUnit::m_fxCharged private
Definition at line 11 of file ChargeUnit.as.
Referenced by ChargeUnit(), and StartFullChargeEffect().
m_holdFrame
int Skills::ChargeUnit::m_holdFrame private
Definition at line 8 of file ChargeUnit.as.
Referenced by ChargeUnit(), Hold(), and NetHold().
m_pressOk
bool Skills::ChargeUnit::m_pressOk = false private
Definition at line 15 of file ChargeUnit.as.
Referenced by Activate(), GetMoveSpeedMul(), Hold(), and Release().
m_prod
UnitProducer Skills::ChargeUnit::m_prod private
Definition at line 10 of file ChargeUnit.as.
Referenced by ChargeUnit(), and DoShoot().
m_tmCharge
int Skills::ChargeUnit::m_tmCharge private
Definition at line 5 of file ChargeUnit.as.
Referenced by Activate(), Hold(), NetActivate(), NetHold(), NetRelease(), and Release().
m_tmChargeMax
int Skills::ChargeUnit::m_tmChargeMax private
Definition at line 6 of file ChargeUnit.as.
Referenced by ChargeUnit(), Hold(), NetHold(), and Release().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Skills/ChargeUnit.as