HoHDocs: Skills::SpawnUnit Class Reference
Skills::SpawnUnit Class Reference
Private Member Functions
SpawnUnit (UnitPtr unit, SValue &params)
bool NeedNetParams () override
TargetingMode GetTargetingMode (int &out size) override
void DoActivate (SValueBuilder@ builder, vec2 target) override
void NetDoActivate (SValue@ param, vec2 target) override
UnitPtr DoSpawnUnits (SValueBuilder@ builder, Actor@ owner, vec2 pos, vec2 dir, float intensity, bool husk)
UnitPtr LocalSpawnUnit (vec2 pos, Actor@ owner, float intensity, bool husk, int id=0)
UnitPtr DoSpawnUnit (SValueBuilder@ builder, vec2 pos, Actor@ owner, float intensity, bool husk)
Private Attributes
UnitProducer m_unit
int m_spawnDist
bool m_safeSpawning
vec2 m_offset
bool m_needNetSync
Detailed Description
Definition at line 3 of file SpawnUnit.as.
Constructor & Destructor Documentation
SpawnUnit()
Skills::SpawnUnit::SpawnUnit (UnitPtr unit, SValue & params) inline private
Definition at line 13 of file SpawnUnit.as.
References IsNetsyncedExistance(), m_needNetSync, m_offset, m_safeSpawning, m_spawnDist, m_unit, and unit.
         {
             super(unit, params);
             @m_unit = Resources::GetUnitProducer(GetParamString(unit, params, "unit"));
             m_safeSpawning = GetParamBool(unit, params, "safe-spawn", false);
             m_spawnDist = GetParamInt(unit, params, "spawn-dist", false);
             m_offset = GetParamVec2(unit, params, "offset", false);
             m_needNetSync = !IsNetsyncedExistance(m_unit.GetNetSyncMode());
         }
Member Function Documentation
DoActivate()
void Skills::SpawnUnit::DoActivate (SValueBuilder@ builder, vec2 target) inline override private
Definition at line 33 of file SpawnUnit.as.
References DoSpawnUnits(), m_needNetSync, Skills::m_owner, and xy().
         {
             if (!m_needNetSync && !Network::IsServer())
             {
                 builder.PushFloat(1.0);
                 return;
             }
             DoSpawnUnits(builder, m_owner, xy(m_owner.m_unit.GetPosition()), target, 1.0, false);
         }
DoSpawnUnit()
UnitPtr Skills::SpawnUnit::DoSpawnUnit (SValueBuilder@ builder, vec2 pos, Actor@ owner, float intensity, bool husk) inline private
Definition at line 127 of file SpawnUnit.as.
References LocalSpawnUnit(), m_needNetSync, m_offset, and unit.
Referenced by DoSpawnUnits().
         {
             pos += m_offset;
             UnitPtr unit = LocalSpawnUnit(pos, owner, intensity, husk);
             if (builder !is null)
             {
                 if (m_needNetSync)
                 {
                     builder.PushArray();
                     builder.PushVector2(pos);
                     builder.PushInteger(unit.GetId());
                     builder.PushFloat(intensity);
                     builder.PopArray();
                 }
                 else
                     builder.PushNull();
             }
             return unit;
         }
DoSpawnUnits()
UnitPtr Skills::SpawnUnit::DoSpawnUnits (SValueBuilder@ builder, Actor@ owner, vec2 pos, vec2 dir, float intensity, bool husk) inline private
Definition at line 58 of file SpawnUnit.as.
References DoSpawnUnit(), g_scene, m_safeSpawning, m_spawnDist, and Actor::m_unit.
Referenced by DoActivate(), and NetDoActivate().
         {
             dir *= m_spawnDist;
             if (!m_safeSpawning)
                 return DoSpawnUnit(builder, pos + dir, owner, intensity, husk);
             else
             {
                 if (m_spawnDist == 0)
                 {
                     bool canSpawn = true;
                     auto res = g_scene.QueryRect(pos, 1, 1, ~0, RaycastType::Shot);
                     for (uint i = 0; i < res.length; i++)
                     {
                         if (owner.m_unit != res[i])
{
                             canSpawn = false;
                             break;
                         }
                     }
                     if (canSpawn)
                         return DoSpawnUnit(builder, pos, owner, intensity, husk);
                     else
                         builder.PushNull();
                 }
                 else
                 {
                     if (!g_scene.RaycastQuick(pos, pos + dir, ~0, RaycastType::Shot))
                         return DoSpawnUnit(builder, pos + dir, owner, intensity, husk);
                     else if (!g_scene.RaycastQuick(pos, vec2(pos.x, pos.y - m_spawnDist), ~0, RaycastType::Shot))
                         return DoSpawnUnit(builder, vec2(pos.x, pos.y - m_spawnDist), owner, intensity, husk);
                     else if (!g_scene.RaycastQuick(pos, vec2(pos.x, pos.y + m_spawnDist), ~0, RaycastType::Shot))
                         return DoSpawnUnit(builder, vec2(pos.x, pos.y + m_spawnDist), owner, intensity, husk);
                     else if (!g_scene.RaycastQuick(pos, vec2(pos.x - m_spawnDist, pos.y), ~0, RaycastType::Shot))
                         return DoSpawnUnit(builder, vec2(pos.x - m_spawnDist, pos.y), owner, intensity, husk);
                     else if (!g_scene.RaycastQuick(pos, vec2(pos.x + m_spawnDist, pos.y), ~0, RaycastType::Shot))
                         return DoSpawnUnit(builder, vec2(pos.x + m_spawnDist, pos.y), owner, intensity, husk);
                     else
                         builder.PushNull();
                 }
             }
             return UnitPtr();
         }
GetTargetingMode()
TargetingMode Skills::SpawnUnit::GetTargetingMode (int &out size) inline override private
Definition at line 27 of file SpawnUnit.as.
References Skills::Direction.
         {
             size = 0;
             return TargetingMode::Direction;
         }
LocalSpawnUnit()
UnitPtr Skills::SpawnUnit::LocalSpawnUnit (vec2 pos, Actor@ owner, float intensity, bool husk, int id = 0) inline private
Definition at line 104 of file SpawnUnit.as.
References g_scene, m_needNetSync, Skills::m_skillId, Actor::m_unit, m_unit, PropagateWeaponInformation(), unit, and xyz().
Referenced by DoSpawnUnit(), and NetDoActivate().
         {
             auto unit = m_unit.Produce(g_scene, xyz(pos), id);
             if (owner !is null)
             {
                 auto ownedUnit = cast<IOwnedUnit>(unit.GetScriptBehavior());
                 if (ownedUnit !is null)
                 {
                     ownedUnit.Initialize(owner, intensity, husk);
                     if (!m_needNetSync && Network::IsServer())
                         (Network::Message("SetOwnedUnit") << unit << owner.m_unit << intensity).SendToAll();
                     // TODO: Remove
                     auto bomb = cast<BombBehavior>(ownedUnit);
                     PropagateWeaponInformation(bomb.m_actions, m_skillId + 1);
                 }
             }
             return unit;
         }
NeedNetParams()
bool Skills::SpawnUnit::NeedNetParams () inline override private
Definition at line 26 of file SpawnUnit.as.
 { return true; }
NetDoActivate()
void Skills::SpawnUnit::NetDoActivate (SValue@ param, vec2 target) inline override private
Definition at line 44 of file SpawnUnit.as.
References DoSpawnUnits(), LocalSpawnUnit(), m_needNetSync, Skills::m_owner, and xy().
         {
             if (m_needNetSync)
             {
                 array<SValue@>@ p = param.GetArray();
                 LocalSpawnUnit(p[0].GetVector2(), m_owner, p[2].GetFloat(), true, p[1].GetInteger());
             }
             else if (Network::IsServer())
             {
                 float intensity = param.GetFloat();
                 DoSpawnUnits(null, m_owner, xy(m_owner.m_unit.GetPosition()), target, intensity, false);
             }
         }
Member Data Documentation
m_needNetSync
bool Skills::SpawnUnit::m_needNetSync private
Definition at line 10 of file SpawnUnit.as.
Referenced by DoActivate(), DoSpawnUnit(), LocalSpawnUnit(), NetDoActivate(), and SpawnUnit().
m_offset
vec2 Skills::SpawnUnit::m_offset private
Definition at line 9 of file SpawnUnit.as.
Referenced by DoSpawnUnit(), and SpawnUnit().
m_safeSpawning
bool Skills::SpawnUnit::m_safeSpawning private
Definition at line 8 of file SpawnUnit.as.
Referenced by DoSpawnUnits(), and SpawnUnit().
m_spawnDist
int Skills::SpawnUnit::m_spawnDist private
Definition at line 7 of file SpawnUnit.as.
Referenced by DoSpawnUnits(), and SpawnUnit().
m_unit
UnitProducer Skills::SpawnUnit::m_unit private
Definition at line 5 of file SpawnUnit.as.
Referenced by LocalSpawnUnit(), and SpawnUnit().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Skills/SpawnUnit.as