HoHDocs: LootBox Class Reference
LootBox Class Reference
Private Member Functions
LootBox (SValue &sval)
void Initialize (bool loaded) override
bool ShouldFreezeControls () override
bool ShouldDisplayCursor () override
bool ShouldSaveExistance () override
void UpdateInterface ()
void Play ()
void Update (int dt) override
void OnFunc (Widget@ sender, string name) override
Private Attributes
InventoryWidget m_wInventory
Widget m_wBox
ScalableSpriteButtonWidget m_wPlayButton
int m_waitTime
int m_waitTimeUp
array< LootBoxItemAnimator@> m_itemWidgets
Detailed Description
Definition at line 56 of file LootBox.as.
Constructor & Destructor Documentation
LootBox()
LootBox::LootBox (SValue & sval) inline private
Definition at line 68 of file LootBox.as.
     {
         super();
     }
Member Function Documentation
Initialize()
void LootBox::Initialize (bool loaded) inline override private
Definition at line 73 of file LootBox.as.
References GetLocalPlayerRecord(), InventoryWidget::m_itemTemplate, m_wBox, m_widget, m_wInventory, m_wPlayButton, InventoryWidget::UpdateFromRecord(), and UpdateInterface().
     {
         @m_wInventory = cast<InventoryWidget>(m_widget.GetWidgetById("inventory"));
         @m_wInventory.m_itemTemplate = cast<InventoryItemWidget>(m_widget.GetWidgetById("inventory-template"));
         @m_wBox = m_widget.GetWidgetById("box");
         @m_wPlayButton = cast<ScalableSpriteButtonWidget>(m_widget.GetWidgetById("play"));
         m_wInventory.UpdateFromRecord(GetLocalPlayerRecord());
         UpdateInterface();
     }
OnFunc()
void LootBox::OnFunc (Widget@ sender, string name) inline override private
Definition at line 193 of file LootBox.as.
References name, Menu::OnFunc(), and Play().
     {
         if (name == "play")
             Play();
         else
             ScriptWidgetHost::OnFunc(sender, name);
     }
Play()
void LootBox::Play () inline private
Definition at line 99 of file LootBox.as.
References g_gameMode, g_LootBoxCost, Widget::GetRelativeOffset(), ScalableSpriteButtonWidget::m_enabled, Widget::m_height, m_itemWidgets, m_waitTime, m_wBox, Widget::m_width, m_wInventory, m_wPlayButton, QuadOut, and WidgetVec2BezierAnimation().
Referenced by OnFunc().
     {
         auto gm = cast<Campaign>(g_gameMode);
         if (gm.m_townLocal.m_gold < g_LootBoxCost)
         {
             PrintError("Not enough gold!");
             return;
         }
         gm.m_townLocal.m_gold -= g_LootBoxCost;
         m_waitTime = 1000;
         m_wPlayButton.m_enabled = false;
         vec2 boxOffset = m_wBox.GetRelativeOffset();
         vec2 inventoryOffset = m_wInventory.GetRelativeOffset();
         for (int i = m_wInventory.m_children.length() - 1; i >= 0; i--)
         {
             auto wItem = cast<InventoryItemWidget>(m_wInventory.m_children[i]);
             wItem.MoveToParentInPlace(m_wInventory.m_parent, 3);
             vec2 posStart = wItem.m_offset;
             vec2 posEnd = boxOffset + vec2(m_wBox.m_width - wItem.m_width, m_wBox.m_height - wItem.m_height) * vec2(randf(), randf());
             vec2 posBezier = inventoryOffset + vec2(m_wInventory.m_width - wItem.m_width, m_wInventory.m_height - wItem.m_height) * vec2(randf(), randf());
             //TODO: Add animation delay
             wItem.Animate(WidgetVec2BezierAnimation("offset", posStart, posBezier, posEnd, m_waitTime).WithEasing(EasingFunction::QuadOut));
             m_itemWidgets.insertAt(0, LootBoxItemAnimator(this, wItem, posBezier.x - (m_wInventory.m_offset.x + m_wInventory.m_width / 2.0f)));
         }
     }
ShouldDisplayCursor()
bool LootBox::ShouldDisplayCursor () inline override private
Definition at line 88 of file LootBox.as.
 { return true; }
ShouldFreezeControls()
bool LootBox::ShouldFreezeControls () inline override private
Definition at line 87 of file LootBox.as.
 { return true; }
ShouldSaveExistance()
bool LootBox::ShouldSaveExistance () inline override private
Definition at line 89 of file LootBox.as.
 { return false; }
Update()
void LootBox::Update (int dt) inline override private
Definition at line 132 of file LootBox.as.
References g_items, g_LootBoxCost, ActorItems::GetItem(), GetLocalPlayerRecord(), ScalableSpriteButtonWidget::m_enabled, m_itemWidgets, m_waitTime, m_waitTimeUp, m_wPlayButton, ActorItems::TakeRandomItem(), Update(), and UpdateInterface().
     {
         for (int i = m_itemWidgets.length() - 1; i >= 0; i--)
         {
             m_itemWidgets[i].Update(dt);
             if (m_itemWidgets[i].m_done)
                 m_itemWidgets.removeAt(i);
         }
         if (m_waitTimeUp > 0)
         {
             m_waitTimeUp -= dt;
             if (m_waitTimeUp <= 0)
             {
                 m_wPlayButton.m_enabled = true;
                 g_LootBoxCost *= 2;
                 UpdateInterface();
             }
         }
         if (m_waitTime > 0)
         {
             m_waitTime -= dt;
             if (m_waitTime <= 0)
             {
                 m_waitTimeUp = 1000;
                 auto record = GetLocalPlayerRecord();
                 for (uint i = 0; i < record.items.length(); i++)
                 {
                     string id = record.items[i];
                     auto oldItem = g_items.GetItem(id);
                     ActorItem@ newItem;
                     int newItemAttempts = 0;
                     do
                     {
                         @newItem = g_items.TakeRandomItem(oldItem.quality, false);
                         newItemAttempts++;
                     } while (newItemAttempts <= 3 && newItem.id == oldItem.id);
                     print(oldItem.id + " -> " + newItem.id);
                     record.items[i] = newItem.id;
                     m_itemWidgets[i].m_wItem.Set(record, newItem);
                     m_itemWidgets[i].AnimateUp();
                 }
                 for (uint i = 0; i < m_itemWidgets.length(); i++)
                     m_itemWidgets[i].m_wItemNew.m_visible = false;
                 auto player = cast<Player>(record.actor);
                 player.RefreshModifiers();
             }
         }
         ScriptWidgetHost::Update(dt);
     }
UpdateInterface()
void LootBox::UpdateInterface () inline private
Definition at line 91 of file LootBox.as.
References g_gameMode, g_LootBoxCost, ScalableSpriteButtonWidget::m_enabled, m_wPlayButton, and ScalableSpriteButtonWidget::SetText().
Referenced by Initialize(), and Update().
     {
         auto gm = cast<Campaign>(g_gameMode);
         m_wPlayButton.SetText("play - " + g_LootBoxCost);
         m_wPlayButton.m_enabled = (gm.m_townLocal.m_gold >= g_LootBoxCost);
     }
Member Data Documentation
m_itemWidgets
array<LootBoxItemAnimator@> LootBox::m_itemWidgets private
Definition at line 66 of file LootBox.as.
Referenced by Play(), and Update().
m_waitTime
int LootBox::m_waitTime private
Definition at line 64 of file LootBox.as.
Referenced by Play(), and Update().
m_waitTimeUp
int LootBox::m_waitTimeUp private
Definition at line 65 of file LootBox.as.
Referenced by Update().
m_wBox
Widget LootBox::m_wBox private
Definition at line 60 of file LootBox.as.
Referenced by Initialize(), and Play().
m_wInventory
InventoryWidget LootBox::m_wInventory private
Definition at line 58 of file LootBox.as.
Referenced by LootBoxItemAnimator::AnimateUp(), Initialize(), and Play().
m_wPlayButton
ScalableSpriteButtonWidget LootBox::m_wPlayButton private
Definition at line 62 of file LootBox.as.
Referenced by Initialize(), Play(), Update(), and UpdateInterface().
The documentation for this class was generated from the following file:
scripts/GUI/Town/LootBox.as