HoHDocs: SpriteButtonWidget Class Reference
SpriteButtonWidget Class Reference
Private Member Functions
SpriteButtonWidget ()
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void SetSpriteset (string spriteSet)
Sprite GetCurrentSprite ()
void DoDraw (SpriteBatch &sb, vec2 pos) override
bool OnClick (vec2 mousePos) override
void ShowTooltip () override
void OnMouseEnter (vec2 mousePos, bool forced) override
bool OnMouseDown (vec2 mousePos) override
bool OnMouseUp (vec2 mousePos) override
void OnMouseLeave (vec2 mousePos) override
Private Attributes
GUIDef m_def
Sprite m_sprite
Sprite m_spriteHover
Sprite m_spriteDown
Sprite m_spriteDisabled
string m_func
string m_funcHover
string m_funcLeave
SoundEvent m_pressSound
SoundEvent m_selectSound
bool m_buttonDown
TextWidget m_wText
vec4 m_colorHoverText
bool m_enabled
Detailed Description
Definition at line 1 of file SpriteButtonWidget.as.
Constructor & Destructor Documentation
SpriteButtonWidget()
SpriteButtonWidget::SpriteButtonWidget () inline private
Definition at line 24 of file SpriteButtonWidget.as.
Referenced by Clone().
     {
         super();
     }
Member Function Documentation
Clone()
Widget SpriteButtonWidget::Clone () inline override private
Definition at line 29 of file SpriteButtonWidget.as.
References Widget::CloneInto(), and SpriteButtonWidget().
     {
         SpriteButtonWidget@ w = SpriteButtonWidget();
         CloneInto(w);
         return w;
     }
DoDraw()
void SpriteButtonWidget::DoDraw (SpriteBatch & sb, vec2 pos) inline override private
Definition at line 100 of file SpriteButtonWidget.as.
References g_menuTime, and GetCurrentSprite().
Referenced by ColorButtonWidget::DoDraw().
     {
         sb.DrawSprite(pos, GetCurrentSprite(), g_menuTime);
     }
GetCurrentSprite()
Sprite SpriteButtonWidget::GetCurrentSprite () inline private
Definition at line 84 of file SpriteButtonWidget.as.
References m_buttonDown, m_enabled, Widget::m_hovering, m_sprite, m_spriteDisabled, m_spriteDown, and m_spriteHover.
Referenced by DoDraw(), and ColorButtonWidget::GetCurrentSprite().
     {
         if (!m_enabled && m_spriteDisabled !is null)
             return m_spriteDisabled;
         if (!m_hovering || !m_enabled)
             return m_sprite;
         else
         {
             if (!m_buttonDown)
                 return m_spriteHover;
             else
                 return m_spriteDown;
         }
     }
Load()
void SpriteButtonWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 36 of file SpriteButtonWidget.as.
References Widget::Load().
Referenced by LoadSpriteButtonWidget().
     {
         Widget::Load(ctx);
         @m_def = ctx.GetGUIDef();
         string spriteSet = ctx.GetString("spriteset", false);
         if (spriteSet != "")
             SetSpriteset(spriteSet);
         else
         {
             string spriteDefault = ctx.GetString("sprite");
             @m_sprite = m_def.GetSprite(spriteDefault);
             string spriteHover = ctx.GetString("sprite-hover", false, spriteDefault);
             @m_spriteHover = m_def.GetSprite(spriteHover);
             @m_spriteDown = m_def.GetSprite(ctx.GetString("sprite-down", false, spriteHover));
         }
         m_func = ctx.GetString("func", false);
         m_funcHover = ctx.GetString("func-hover", false);
         m_funcLeave = ctx.GetString("func-leave", false);
         @m_pressSound = Resources::GetSoundEvent("event:/ui/button_click");
         @m_selectSound = Resources::GetSoundEvent("event:/ui/button_hover");
         m_colorHoverText = ctx.GetColorRGBA("hovertext", false, vec4());
         m_enabled = ctx.GetBoolean("enabled", false, true);
         if (m_sprite !is null)
         {
             m_width = m_sprite.GetWidth();
             m_height = m_sprite.GetHeight();
         }
         m_canFocus = true;
     }
OnClick()
bool SpriteButtonWidget::OnClick (vec2 mousePos) inline override private
Definition at line 105 of file SpriteButtonWidget.as.
References m_buttonDown, and m_enabled.
     {
         if (!m_enabled)
             return false;
         if (!m_buttonDown)
             return true;
         m_host.OnFunc(this, m_func);
         PlaySound2D(m_pressSound);
         return true;
     }
OnMouseDown()
bool SpriteButtonWidget::OnMouseDown (vec2 mousePos) inline override private
Definition at line 144 of file SpriteButtonWidget.as.
References m_buttonDown.
 { m_buttonDown = true; return true; }
OnMouseEnter()
void SpriteButtonWidget::OnMouseEnter (vec2 mousePos, bool forced) inline override private
Definition at line 124 of file SpriteButtonWidget.as.
References m_colorHoverText, m_enabled, m_selectSound, m_wText, Widget::OnMouseEnter(), and PlaySound2D().
     {
         Widget::OnMouseEnter(mousePos, forced);
         if (!m_enabled)
             return;
         PlaySound2D(m_selectSound);
         if (m_colorHoverText.w > 0)
         {
             if (m_wText is null)
                 @m_wText = cast<TextWidget>(m_children[0]);
             m_wText.SetColor(m_colorHoverText);
         }
         if (m_funcHover != "")
             m_host.OnFunc(this, m_funcHover);
     }
OnMouseLeave()
void SpriteButtonWidget::OnMouseLeave (vec2 mousePos) inline override private
Definition at line 147 of file SpriteButtonWidget.as.
References m_enabled, and Widget::OnMouseLeave().
     {
         Widget::OnMouseLeave(mousePos);
         if (!m_enabled)
             return;
         m_buttonDown = false;
         if (m_colorHoverText.w > 0 && m_wText !is null)
             m_wText.SetColor(m_wText.m_colorOriginal);
         if (m_funcLeave != "")
             m_host.OnFunc(this, m_funcLeave);
     }
OnMouseUp()
bool SpriteButtonWidget::OnMouseUp (vec2 mousePos) inline override private
Definition at line 145 of file SpriteButtonWidget.as.
References m_buttonDown.
 { m_buttonDown = false; return true; }
SetSpriteset()
void SpriteButtonWidget::SetSpriteset (string spriteSet) inline private
Definition at line 76 of file SpriteButtonWidget.as.
References m_def, m_sprite, m_spriteDisabled, m_spriteDown, and m_spriteHover.
     {
         @m_sprite = m_def.GetSprite(spriteSet);
         @m_spriteHover = m_def.GetSprite(spriteSet + "-hover");
         @m_spriteDown = m_def.GetSprite(spriteSet + "-down");
         @m_spriteDisabled = m_def.GetSprite(spriteSet + "-disabled");
     }
ShowTooltip()
void SpriteButtonWidget::ShowTooltip () inline override private
Definition at line 118 of file SpriteButtonWidget.as.
     {
         m_tooltipEnabled = m_enabled;
         Widget::ShowTooltip();
     }
Member Data Documentation
m_buttonDown
bool SpriteButtonWidget::m_buttonDown private
Definition at line 17 of file SpriteButtonWidget.as.
Referenced by GetCurrentSprite(), OnClick(), OnMouseDown(), and OnMouseUp().
m_colorHoverText
vec4 SpriteButtonWidget::m_colorHoverText private
Definition at line 20 of file SpriteButtonWidget.as.
Referenced by OnMouseEnter().
m_def
GUIDef SpriteButtonWidget::m_def private
Definition at line 3 of file SpriteButtonWidget.as.
Referenced by SetSpriteset().
m_enabled
bool SpriteButtonWidget::m_enabled private
Definition at line 22 of file SpriteButtonWidget.as.
Referenced by GetCurrentSprite(), OnClick(), OnMouseEnter(), OnMouseLeave(), DungeonSettingsMenu::UpdateNgp(), and Menu::HostMenu::UpdateNgp().
m_func
string SpriteButtonWidget::m_func private
Definition at line 10 of file SpriteButtonWidget.as.
m_funcHover
string SpriteButtonWidget::m_funcHover private
Definition at line 11 of file SpriteButtonWidget.as.
m_funcLeave
string SpriteButtonWidget::m_funcLeave private
Definition at line 12 of file SpriteButtonWidget.as.
m_pressSound
SoundEvent SpriteButtonWidget::m_pressSound private
Definition at line 14 of file SpriteButtonWidget.as.
m_selectSound
SoundEvent SpriteButtonWidget::m_selectSound private
Definition at line 15 of file SpriteButtonWidget.as.
Referenced by OnMouseEnter().
m_sprite
Sprite SpriteButtonWidget::m_sprite private
Definition at line 5 of file SpriteButtonWidget.as.
Referenced by Clone(), GetCurrentSprite(), and SetSpriteset().
m_spriteDisabled
Sprite SpriteButtonWidget::m_spriteDisabled private
Definition at line 8 of file SpriteButtonWidget.as.
Referenced by GetCurrentSprite(), and SetSpriteset().
m_spriteDown
Sprite SpriteButtonWidget::m_spriteDown private
Definition at line 7 of file SpriteButtonWidget.as.
Referenced by ColorButtonWidget::GetCurrentSprite(), GetCurrentSprite(), and SetSpriteset().
m_spriteHover
Sprite SpriteButtonWidget::m_spriteHover private
Definition at line 6 of file SpriteButtonWidget.as.
Referenced by GetCurrentSprite(), and SetSpriteset().
m_wText
TextWidget SpriteButtonWidget::m_wText private
Definition at line 19 of file SpriteButtonWidget.as.
Referenced by OnMouseEnter().
The documentation for this class was generated from the following file:
scripts/GUI/SpriteButtonWidget.as