HoHDocs: PlaySound Class Reference
PlaySound Class Reference
Private Member Functions
PlaySound (UnitPtr unit, SValue &params)
void SetWeaponInformation (uint weapon)
bool NeedNetParams ()
bool DoAction (SValueBuilder@ builder, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity)
bool NetDoAction (SValue@ param, Actor@ owner, vec2 pos, vec2 dir)
bool Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
bool CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
void Do (vec2 pos)
void Update (int dt, int cooldown)
Private Attributes
SoundEvent m_snd
bool m_2d
Detailed Description
Definition at line 1 of file PlaySound.as.
Constructor & Destructor Documentation
PlaySound()
PlaySound::PlaySound (UnitPtr unit, SValue & params) inline private
Definition at line 6 of file PlaySound.as.
References m_2d, m_snd, and unit.
     {
         string fnm = GetParamString(unit, params, "sound");
         @m_snd = Resources::GetSoundEvent(fnm);
         if (m_snd is null)
             print("WARNING: Sound resource not found: " + fnm);
         m_2d = GetParamBool(unit, params, "2d", false);
     }
Member Function Documentation
Apply()
bool PlaySound::Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk) inline private
Definition at line 30 of file PlaySound.as.
References CanApply(), and Do().
     {
         if (!CanApply(owner, target, pos, dir, intensity))
             return false;
         Do(pos);
         return true;
     }
CanApply()
bool PlaySound::CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) inline override private
Definition at line 39 of file PlaySound.as.
Referenced by Apply().
     {
         if (intensity <= 0)
             return false;
         return true;
     }
Do()
void PlaySound::Do (vec2 pos) inline private
Definition at line 47 of file PlaySound.as.
References m_2d, m_snd, and xyz().
Referenced by Apply(), DoAction(), and NetDoAction().
     {
         if (m_snd is null)
             return;
         if (m_2d)
             m_snd.Play();
         else
             m_snd.Play(xyz(pos));
     }
DoAction()
bool PlaySound::DoAction (SValueBuilder@ builder, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity) inline private
Definition at line 18 of file PlaySound.as.
References Do().
     {
         Do(pos);
         return true;
     }
NeedNetParams()
bool PlaySound::NeedNetParams () inline private
Definition at line 16 of file PlaySound.as.
 { return false; }
NetDoAction()
bool PlaySound::NetDoAction (SValue@ param, Actor@ owner, vec2 pos, vec2 dir) inline private
Definition at line 24 of file PlaySound.as.
References Do().
     {
         Do(pos);
         return true;
     }
SetWeaponInformation()
void PlaySound::SetWeaponInformation (uint weapon) inline private
Definition at line 15 of file PlaySound.as.
 {}
Update()
void PlaySound::Update (int dt, int cooldown) inline private
Definition at line 58 of file PlaySound.as.
     {
     }
Member Data Documentation
m_2d
bool PlaySound::m_2d private
Definition at line 4 of file PlaySound.as.
Referenced by Do(), and PlaySound().
m_snd
SoundEvent PlaySound::m_snd private
Definition at line 3 of file PlaySound.as.
Referenced by Do(), and PlaySound().
The documentation for this class was generated from the following file:
scripts/Behaviors/Effects/PlaySound.as