HoHDocs: GeneralStoreMenuContent Class Reference
GeneralStoreMenuContent Class Reference
Private Member Functions
GeneralStoreMenuContent (ShopMenu@ shopMenu)
int GetRerollCost ()
string GetGuiFilename () override
void OnShow () override
void ReloadList () override
void OnFunc (Widget@ sender, string name) override
Private Attributes
Widget m_wRerollTemplate
Widget m_wReroll
Upgrades::ItemShop m_itemShop
Detailed Description
Definition at line 1 of file GeneralStoreMenu.as.
Constructor & Destructor Documentation
GeneralStoreMenuContent()
GeneralStoreMenuContent::GeneralStoreMenuContent (ShopMenu@ shopMenu) inline private
Definition at line 8 of file GeneralStoreMenu.as.
References UpgradeShopMenuContent::m_currentShop, and m_itemShop.
     {
         super(shopMenu, "generalstore");
         @m_itemShop = cast<Upgrades::ItemShop>(m_currentShop);
         if (m_itemShop is null)
             PrintError("\"generalstore\" is not an item shop!");
     }
Member Function Documentation
GetGuiFilename()
string GeneralStoreMenuContent::GetGuiFilename () inline override private
Definition at line 22 of file GeneralStoreMenu.as.
     {
         return "gui/shop/generalstore.gui";
     }
GetRerollCost()
int GeneralStoreMenuContent::GetRerollCost () inline private
Definition at line 17 of file GeneralStoreMenu.as.
Referenced by OnFunc(), and ReloadList().
     {
         return 100;
     }
OnFunc()
void GeneralStoreMenuContent::OnFunc (Widget@ sender, string name) inline override private
Definition at line 73 of file GeneralStoreMenu.as.
References cost, g_gameMode, GetLocalPlayerRecord(), GetRerollCost(), UpgradeShopMenuContent::m_currentShop, ShopMenu::m_currentShopLevel, ShopMenuContent::m_shopMenu, name, ShopMenuContent::OnFunc(), and ReloadList().
     {
         if (name == "reroll")
         {
             int cost = GetRerollCost();
             auto gm = cast<Campaign>(g_gameMode);
             auto town = gm.m_townLocal;
             if (town.m_gold < cost)
             {
                 PrintError("Not enough gold to reroll general store!");
                 return;
             }
             town.m_gold -= cost;
             auto player = GetLocalPlayerRecord();
             auto itemShop = cast<Upgrades::ItemShop>(m_currentShop);
             itemShop.RerollItems(m_shopMenu.m_currentShopLevel, player);
             ReloadList();
         }
         else
             UpgradeShopMenuContent::OnFunc(sender, name);
     }
OnShow()
void GeneralStoreMenuContent::OnShow () inline override private
Definition at line 27 of file GeneralStoreMenu.as.
References Widget::GetWidgetById(), ShopMenuContent::m_widget, m_wRerollTemplate, and UpgradeShopMenuContent::OnShow().
     {
         @m_wRerollTemplate = m_widget.GetWidgetById("reroll");
         UpgradeShopMenuContent::OnShow();
     }
ReloadList()
void GeneralStoreMenuContent::ReloadList () inline override private
Definition at line 34 of file GeneralStoreMenu.as.
References Widget::AddChild(), Widget::Clone(), cost, ShopMenu::DoLayout(), g_gameMode, GetLocalPlayerRecord(), GetRerollCost(), Widget::GetWidgetById(), Upgrades::ItemShop::ItemsForLevel(), ShopMenu::m_currentShopLevel, m_itemShop, ShopMenuContent::m_shopMenu, Widget::m_visible, UpgradeShopMenuContent::m_wItemList, m_wReroll, m_wRerollTemplate, UpgradeShopMenuContent::m_wSoldOut, UpgradeShopMenuContent::ReloadList(), Widget::RemoveFromParent(), and Widget::SetID().
Referenced by OnFunc().
     {
         if (m_wReroll !is null)
             m_wReroll.RemoveFromParent();
         UpgradeShopMenuContent::ReloadList();
         if (!m_wSoldOut.m_visible)
         {
             @m_wReroll = m_wRerollTemplate.Clone();
             m_wReroll.SetID("");
             m_wReroll.m_visible = true;
             auto wRerollButton = cast<ScalableSpriteIconButtonWidget>(m_wReroll.GetWidgetById("button"));
             if (wRerollButton !is null)
             {
                 int cost = GetRerollCost();
                 auto gm = cast<Campaign>(g_gameMode);
                 auto town = gm.m_townLocal;
                 int numItemsNow = int(GetLocalPlayerRecord().generalStoreItems.length());
                 int numItemsOriginal = m_itemShop.ItemsForLevel(m_shopMenu.m_currentShopLevel);
                 wRerollButton.m_enabled = (town.m_gold >= cost && numItemsNow == numItemsOriginal);
                 if (wRerollButton.m_enabled)
                     wRerollButton.SetText(Resources::GetString(".shop.generalstore.reroll", { { "cost", cost } }));
                 else
                     wRerollButton.SetText(Resources::GetString(".shop.generalstore.rerolldisabled"));
             }
             m_wItemList.AddChild(m_wReroll);
         }
         // Ughhhhh
         m_shopMenu.DoLayout();
         m_shopMenu.DoLayout();
     }
Member Data Documentation
m_itemShop
Upgrades::ItemShop GeneralStoreMenuContent::m_itemShop private
Definition at line 6 of file GeneralStoreMenu.as.
Referenced by GeneralStoreMenuContent(), and ReloadList().
m_wReroll
Widget GeneralStoreMenuContent::m_wReroll private
Definition at line 4 of file GeneralStoreMenu.as.
Referenced by ReloadList().
m_wRerollTemplate
Widget GeneralStoreMenuContent::m_wRerollTemplate private
Definition at line 3 of file GeneralStoreMenu.as.
Referenced by OnShow(), and ReloadList().
The documentation for this class was generated from the following file:
scripts/GUI/Shop/GeneralStoreMenu.as