HoHDocs: MenuTab Class Reference
MenuTab Class Reference
Private Member Functions
string GetGuiFilename ()
void OnCreated ()
void DoLayout ()
bool IsVisible ()
void SetVisible (bool v)
void OnShow ()
void Update (int dt)
void AfterUpdate ()
void Draw (SpriteBatch &sb, int idt)
bool OnFunc (Widget@ sender, string name)
Private Attributes
string m_id
GUIDef m_def
Widget m_widget
Detailed Description
Definition at line 1 of file MenuTab.as.
Member Function Documentation
AfterUpdate()
void MenuTab::AfterUpdate () inline private
Definition at line 45 of file MenuTab.as.
Referenced by MenuTabSystem::AfterUpdate().
     {
     }
DoLayout()
void MenuTab::DoLayout () inline private
Definition at line 17 of file MenuTab.as.
References Widget::m_host, and m_widget.
Referenced by GuildHallStatsTab::OnFunc(), GuildHallBeastiaryTab::OnShow(), GuildHallAccomplishmentsTab::RefreshList(), ReloadList(), PlayerMenuStatsTab::UpdateNow(), and PlayerMenuCharacterTab::UpdateNow().
     {
         m_widget.m_host.DoLayout();
     }
Draw()
void MenuTab::Draw (SpriteBatch & sb, int idt) inline private
Definition at line 49 of file MenuTab.as.
Referenced by MenuTabSystem::Draw().
     {
     }
GetGuiFilename()
string MenuTab::GetGuiFilename () inline private
Definition at line 7 of file MenuTab.as.
Referenced by MenuTabSystem::AddTab().
     {
         PrintError("Implement MenuTab::GetGuiFilename!");
         return "";
     }
IsVisible()
bool MenuTab::IsVisible () inline private
Definition at line 22 of file MenuTab.as.
References Widget::m_visible, and m_widget.
     {
         return m_widget.m_visible;
     }
OnCreated()
void MenuTab::OnCreated () inline private
Definition at line 13 of file MenuTab.as.
Referenced by MenuTabSystem::AddTab(), and PlayerMenuCharacterTab::OnCreated().
     {
     }
OnFunc()
bool MenuTab::OnFunc (Widget@ sender, string name) inline private
Definition at line 53 of file MenuTab.as.
Referenced by MenuTabSystem::OnFunc().
     {
         return false;
     }
OnShow()
void MenuTab::OnShow () inline private
Definition at line 37 of file MenuTab.as.
Referenced by MultiplePlayersTab::OnShow(), GuildHallAccomplishmentsTab::OnShow(), GuildHallStatsTab::OnShow(), and SetVisible().
     {
     }
SetVisible()
void MenuTab::SetVisible (bool v) inline private
Definition at line 27 of file MenuTab.as.
References Widget::m_visible, m_widget, and OnShow().
     {
         if (m_widget.m_visible == v)
             return;
         m_widget.m_visible = v;
         if (v)
             OnShow();
     }
Update()
void MenuTab::Update (int dt) inline private
Definition at line 41 of file MenuTab.as.
Referenced by MenuTabSystem::Update().
     {
     }
Member Data Documentation
m_def
GUIDef MenuTab::m_def private
Definition at line 4 of file MenuTab.as.
Referenced by MenuTabSystem::AddTab(), GuildHallBeastiaryTab::OnCreated(), PlayerMenuCharacterTab::OnCreated(), and GuildHallAccomplishmentsTab::RefreshList().
m_id
string MenuTab::m_id private
Definition at line 3 of file MenuTab.as.
Referenced by MenuTabSystem::AddTab(), PlayerMenuTab::GetGuiFilename(), GuildHallMenuTab::GetGuiFilename(), GuildHallAccomplishmentsTab::GuildHallAccomplishmentsTab(), GuildHallBeastiaryTab::GuildHallBeastiaryTab(), GuildHallStatsTab::GuildHallStatsTab(), PlayerMenuCharacterTab::PlayerMenuCharacterTab(), PlayerMenuMapTab::PlayerMenuMapTab(), and PlayerMenuStatsTab::PlayerMenuStatsTab().
m_widget
Widget MenuTab::m_widget private
Definition at line 5 of file MenuTab.as.
Referenced by GuildHallBeastiaryTab::AddCategory(), MenuTabSystem::AddTab(), PlayerMenuCharacterTab::AddTextWidget(), DoLayout(), IsVisible(), PlayerMenuCharacterTab::OnCreated(), PlayerMenuMapTab::OnCreated(), MultiplePlayersTab::OnShow(), GuildHallAccomplishmentsTab::OnShow(), GuildHallStatsTab::OnShow(), GuildHallBeastiaryTab::OnShow(), PlayerMenuCharacterTab::SetTextWidget(), PlayerMenuCharacterTab::SetTooltipWidget(), SetVisible(), PlayerMenuCharacterTab::UpdateFromRecord(), PlayerMenuStatsTab::UpdateNow(), and MultiplePlayersTab::UpdateNow().
The documentation for this class was generated from the following file:
scripts/GUI/MenuTab.as