HoHDocs: CheckBoxGroupWidget Class Reference
CheckBoxGroupWidget Class Reference
Private Member Functions
CheckBoxGroupWidget ()
Widget Clone () override
void Reset ()
void Cancel ()
void Save ()
bool IsChanged ()
array< ICheckableWidget@> FindCheckables (Widget@ w)
void ClearChildren () override
void AddChild (ref widget, int insertAt=-1) override
void Toggled (ICheckableWidget@ check)
void SetCheckedRandom (int subtract=0)
void SetChecked (int index)
void SetChecked (string value)
ICheckableWidget GetChecked ()
void Update (int dt) override
void Load (WidgetLoadingContext &ctx) override
void DoLayout (vec2 origin, vec2 parentSz) override
bool OnDoubleClick (vec2 mousePos) override
Private Attributes
array< ICheckableWidget@> m_checkboxes
string m_func
string m_funcDouble
string m_cvar
bool m_cvarInit
cvar_type m_cvarType
string m_cvarOrigString
bool m_cvarOrigBool
int m_cvarOrigInt
float m_cvarOrigFloat
bool m_dynamicSize
Detailed Description
Definition at line 11 of file CheckBoxGroup.as.
Constructor & Destructor Documentation
CheckBoxGroupWidget()
CheckBoxGroupWidget::CheckBoxGroupWidget () inline private
Definition at line 28 of file CheckBoxGroup.as.
Referenced by Clone().
     {
         super();
     }
Member Function Documentation
AddChild()
void CheckBoxGroupWidget::AddChild (ref widget, int insertAt = -1) inline override private
Definition at line 152 of file CheckBoxGroup.as.
References ScrollableWidget::AddChild(), and FindCheckables().
Referenced by Menu::CharacterSelectionMenu::ReloadList().
     {
         ScrollableWidget::AddChild(widget, insertAt);
         array<ICheckableWidget@> checkables = FindCheckables(cast<Widget>(widget));
         for (uint i = 0; i < checkables.length(); i++)
         {
             auto checkable = checkables[i];
             checkable.SetCheckable();
             checkable.SetGroupWidget(this);
             m_checkboxes.insertLast(checkable);
         }
     }
Cancel()
void CheckBoxGroupWidget::Cancel () inline private
Definition at line 71 of file CheckBoxGroup.as.
References Float(), Int(), m_cvar, m_cvarOrigBool, m_cvarOrigFloat, m_cvarOrigInt, m_cvarOrigString, m_cvarType, and SetChecked().
     {
         if (m_cvarType == cvar_type::String)
         {
             SetVar(m_cvar, m_cvarOrigString);
             SetChecked(m_cvarOrigString);
         }
         else if (m_cvarType == cvar_type::Bool)
         {
             SetVar(m_cvar, m_cvarOrigBool);
             if (m_cvarOrigBool)
                 SetChecked("true");
             else
                 SetChecked("false");
         }
         else if (m_cvarType == cvar_type::Int)
         {
             SetVar(m_cvar, m_cvarOrigInt);
             SetChecked("" + m_cvarOrigInt);
         }
         else if (m_cvarType == cvar_type::Float)
         {
             SetVar(m_cvar, m_cvarOrigFloat);
             SetChecked("" + m_cvarOrigFloat);
         }
     }
ClearChildren()
void CheckBoxGroupWidget::ClearChildren () inline override private
Definition at line 145 of file CheckBoxGroup.as.
References ScrollableWidget::ClearChildren().
Referenced by Menu::CharacterSelectionMenu::ReloadList().
     {
         ScrollableWidget::ClearChildren();
         m_checkboxes.removeRange(0, m_checkboxes.length());
     }
Clone()
Widget CheckBoxGroupWidget::Clone () inline override private
Definition at line 33 of file CheckBoxGroup.as.
References CheckBoxGroupWidget().
     {
         CheckBoxGroupWidget@ w = CheckBoxGroupWidget();
         CloneInto(w);
         return w;
     }
DoLayout()
void CheckBoxGroupWidget::DoLayout (vec2 origin, vec2 parentSz) inline override private
Definition at line 288 of file CheckBoxGroup.as.
References m_dynamicSize, Widget::m_height, and Widget::m_width.
     {
         if (m_dynamicSize)
         {
             m_width = int(parentSz.x);
             m_height = int(parentSz.y);
         }
         ScrollableWidget::DoLayout(origin, parentSz);
     }
FindCheckables()
array<ICheckableWidget@> CheckBoxGroupWidget::FindCheckables (Widget@ w) inline private
Definition at line 124 of file CheckBoxGroup.as.
References Widget::m_children.
Referenced by AddChild().
     {
         array<ICheckableWidget@> ret;
         ICheckableWidget@ cb = cast<ICheckableWidget>(w);
         if (cb !is null)
             ret.insertLast(cb);
         for (uint i = 0; i < w.m_children.length(); i++)
         {
             array<ICheckableWidget@> arr = FindCheckables(w.m_children[i]);
             if (arr.length() > 0)
             {
                 for (uint j = 0; j < arr.length(); j++)
                     ret.insertLast(arr[j]);
             }
         }
         return ret;
     }
GetChecked()
ICheckableWidget CheckBoxGroupWidget::GetChecked () inline private
Definition at line 222 of file CheckBoxGroup.as.
References IsChecked(), and m_checkboxes.
Referenced by Menu::CharacterCreationMenu::ClassChanged(), and Menu::CharacterSelectionMenu::OnFunc().
     {
         for (uint i = 0; i < m_checkboxes.length(); i++)
         {
             if (m_checkboxes[i].IsChecked())
                 return m_checkboxes[i];
         }
         return null;
     }
IsChanged()
bool CheckBoxGroupWidget::IsChanged () inline private
Definition at line 111 of file CheckBoxGroup.as.
References Float(), Int(), m_cvar, m_cvarOrigBool, m_cvarOrigInt, m_cvarOrigString, and m_cvarType.
     {
         if (m_cvarType == cvar_type::String)
             return GetVarString(m_cvar) != m_cvarOrigString;
         else if (m_cvarType == cvar_type::Bool)
             return GetVarBool(m_cvar) != m_cvarOrigBool;
         else if (m_cvarType == cvar_type::Int)
             return GetVarInt(m_cvar) != m_cvarOrigInt;
         else if (m_cvarType == cvar_type::Float)
             return GetVarFloat(m_cvar) != m_cvarOrigFloat;
         return false;
     }
Load()
void CheckBoxGroupWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 271 of file CheckBoxGroup.as.
References Widget::Load(), ScrollableWidget::m_autoScroll, ClipWidget::m_clipping, m_cvar, m_dynamicSize, m_func, and m_funcDouble.
Referenced by LoadCheckBoxGroupWidget().
     {
         m_func = ctx.GetString("func", false);
         m_funcDouble = ctx.GetString("func-double", false);
         m_cvar = ctx.GetString("cvar", false);
         m_autoScroll = false;
         m_clipping = false;
         ScrollableWidget::Load(ctx);
         m_dynamicSize = ctx.GetBoolean("dynamic-size", false, true);
         if (!m_dynamicSize)
             LoadWidthHeight(ctx, true);
     }
OnDoubleClick()
bool CheckBoxGroupWidget::OnDoubleClick (vec2 mousePos) inline override private
Definition at line 299 of file CheckBoxGroup.as.
References m_funcDouble, and Widget::m_host.
Referenced by CheckBoxWidget::OnDoubleClick().
     {
         if (m_funcDouble != "")
             m_host.OnFunc(this, m_funcDouble);
         return true;
     }
Reset()
void CheckBoxGroupWidget::Reset () inline private
Definition at line 40 of file CheckBoxGroup.as.
References Float(), Int(), m_cvar, m_cvarType, and SetChecked().
     {
         if (m_cvarType == cvar_type::String)
         {
             string def = GetVarStringDefault(m_cvar);
             SetVar(m_cvar, def);
             SetChecked(def);
         }
         else if (m_cvarType == cvar_type::Bool)
         {
             bool def = GetVarBoolDefault(m_cvar);
             SetVar(m_cvar, def);
             if (def)
                 SetChecked("true");
             else
                 SetChecked("false");
         }
         else if (m_cvarType == cvar_type::Int)
         {
             int def = GetVarIntDefault(m_cvar);
             SetVar(m_cvar, def);
             SetChecked("" + def);
         }
         else if (m_cvarType == cvar_type::Float)
         {
             float def = GetVarFloatDefault(m_cvar);
             SetVar(m_cvar, def);
             SetChecked("" + def);
         }
     }
Save()
void CheckBoxGroupWidget::Save () inline private
Definition at line 98 of file CheckBoxGroup.as.
References Float(), Int(), m_cvar, m_cvarOrigBool, m_cvarOrigInt, m_cvarOrigString, and m_cvarType.
     {
         if (m_cvarType == cvar_type::String)
             m_cvarOrigString = GetVarString(m_cvar);
         else if (m_cvarType == cvar_type::Bool)
             m_cvarOrigBool = GetVarBool(m_cvar);
         else if (m_cvarType == cvar_type::Int)
             m_cvarOrigInt = GetVarInt(m_cvar);
         else if (m_cvarType == cvar_type::Float)
             m_cvarOrigFloat = GetVarFloat(m_cvar);
         Config::SaveVar(m_cvar);
     }
SetChecked() [1/2]
void CheckBoxGroupWidget::SetChecked (int index) inline private
Definition at line 210 of file CheckBoxGroup.as.
Referenced by Cancel(), Reset(), SetCheckedRandom(), SetLimitButtons(), MenuTabSystem::SetTab(), and Update().
     {
         for (uint i = 0; i < m_checkboxes.length(); i++)
             m_checkboxes[i].SetChecked(int(i) == index);
     }
SetChecked() [2/2]
void CheckBoxGroupWidget::SetChecked (string value) inline private
Definition at line 216 of file CheckBoxGroup.as.
     {
         for (uint i = 0; i < m_checkboxes.length(); i++)
             m_checkboxes[i].SetChecked(m_checkboxes[i].GetValue() == value);
     }
SetCheckedRandom()
void CheckBoxGroupWidget::SetCheckedRandom (int subtract = 0) inline private
Definition at line 183 of file CheckBoxGroup.as.
References IsEnabled(), m_checkboxes, and SetChecked().
Referenced by Menu::CharacterCreationMenu::Initialize().
     {
         int numEnabled = 0;
         for (int i = 0; i < int(m_checkboxes.length()) - subtract; i++)
         {
             if (m_checkboxes[i].IsEnabled())
                 numEnabled++;
         }
         int randomIndex = randi(numEnabled);
         int index = 0;
         for (uint i = 0; i < m_checkboxes.length(); i++)
         {
             if (!m_checkboxes[i].IsEnabled())
                 continue;
             if (index == randomIndex)
             {
                 SetChecked(i);
                 break;
             }
             index++;
         }
     }
Toggled()
void CheckBoxGroupWidget::Toggled (ICheckableWidget@ check) inline private
Definition at line 166 of file CheckBoxGroup.as.
References m_checkboxes.
Referenced by CheckBoxWidget::OnClick().
     {
         for (uint i = 0; i < m_checkboxes.length(); i++)
         {
             if (m_checkboxes[i] is check)
             {
                 check.SetChecked(true);
                 continue;
             }
             m_checkboxes[i].SetChecked(false);
         }
         if (m_func != "")
             m_host.OnFunc(this, m_func);
     }
Update()
void CheckBoxGroupWidget::Update (int dt) inline override private
Definition at line 232 of file CheckBoxGroup.as.
References Float(), Int(), m_cvar, m_cvarInit, m_cvarOrigBool, m_cvarOrigFloat, m_cvarOrigInt, m_cvarOrigString, m_cvarType, SetChecked(), Widget::SetID(), and Widget::Update().
     {
         ScrollableWidget::Update(dt);
         if (!m_cvarInit && m_cvar != "")
         {
             m_cvarInit = true;
             SetID(m_cvar);
             m_cvarType = GetVarType(m_cvar);
             if (m_cvarType == cvar_type::String)
             {
                 m_cvarOrigString = GetVarString(m_cvar);
                 SetChecked(m_cvarOrigString);
             }
             else if (m_cvarType == cvar_type::Bool)
             {
                 m_cvarOrigBool = GetVarBool(m_cvar);
                 if (m_cvarOrigBool)
                     SetChecked("true");
                 else
                     SetChecked("false");
             }
             else if (m_cvarType == cvar_type::Int)
             {
                 m_cvarOrigInt = GetVarInt(m_cvar);
                 SetChecked("" + m_cvarOrigInt);
             }
             else if (m_cvarType == cvar_type::Float)
             {
                 m_cvarOrigFloat = GetVarFloat(m_cvar);
                 SetChecked("" + m_cvarOrigFloat);
             }
             else
                 PrintError("Unhandled cvar type: " + int(m_cvarType));
         }
     }
Member Data Documentation
m_checkboxes
array<ICheckableWidget@> CheckBoxGroupWidget::m_checkboxes private
Definition at line 13 of file CheckBoxGroup.as.
Referenced by GetChecked(), SetCheckedRandom(), and Toggled().
m_cvar
string CheckBoxGroupWidget::m_cvar private
Definition at line 17 of file CheckBoxGroup.as.
Referenced by Cancel(), IsChanged(), Load(), Reset(), Save(), and Update().
m_cvarInit
bool CheckBoxGroupWidget::m_cvarInit private
Definition at line 18 of file CheckBoxGroup.as.
Referenced by Update().
m_cvarOrigBool
bool CheckBoxGroupWidget::m_cvarOrigBool private
Definition at line 22 of file CheckBoxGroup.as.
Referenced by Cancel(), IsChanged(), Save(), and Update().
m_cvarOrigFloat
float CheckBoxGroupWidget::m_cvarOrigFloat private
Definition at line 24 of file CheckBoxGroup.as.
Referenced by Cancel(), and Update().
m_cvarOrigInt
int CheckBoxGroupWidget::m_cvarOrigInt private
Definition at line 23 of file CheckBoxGroup.as.
Referenced by Cancel(), IsChanged(), Save(), and Update().
m_cvarOrigString
string CheckBoxGroupWidget::m_cvarOrigString private
Definition at line 21 of file CheckBoxGroup.as.
Referenced by Cancel(), IsChanged(), Save(), and Update().
m_cvarType
cvar_type CheckBoxGroupWidget::m_cvarType private
Definition at line 20 of file CheckBoxGroup.as.
Referenced by Cancel(), IsChanged(), Reset(), Save(), and Update().
m_dynamicSize
bool CheckBoxGroupWidget::m_dynamicSize private
Definition at line 26 of file CheckBoxGroup.as.
Referenced by DoLayout(), and Load().
m_func
string CheckBoxGroupWidget::m_func private
Definition at line 15 of file CheckBoxGroup.as.
Referenced by Load().
m_funcDouble
string CheckBoxGroupWidget::m_funcDouble private
Definition at line 16 of file CheckBoxGroup.as.
Referenced by Load(), and OnDoubleClick().
The documentation for this class was generated from the following file:
scripts/GUI/CheckBoxGroup.as