HoHDocs: HUDSurvival Class Reference
HUDSurvival Class Reference
Private Member Functions
HUDSurvival (GUIBuilder@ b)
void Update (int dt) override
Private Attributes
TextWidget m_wCrowd
Detailed Description
Definition at line 1 of file HUDSurvival.as.
Constructor & Destructor Documentation
HUDSurvival()
HUDSurvival::HUDSurvival (GUIBuilder@ b) inline private
Definition at line 5 of file HUDSurvival.as.
References LoadWidget(), m_wCrowd, and m_widget.
     {
         LoadWidget(b, "gui/hud/survival.gui");
         @m_wCrowd = cast<TextWidget>(m_widget.GetWidgetById("crowd"));
     }
Member Function Documentation
Update()
void HUDSurvival::Update (int dt) inline override private
Definition at line 12 of file HUDSurvival.as.
References g_gameMode, m_wCrowd, and TextWidget::SetText().
Referenced by Survival::UpdateFrame().
     {
         auto gm = cast<Survival>(g_gameMode);
         if (gm is null)
             return;
         m_wCrowd.SetText("" + round(gm.m_crowdValue));
     }
Member Data Documentation
m_wCrowd
TextWidget HUDSurvival::m_wCrowd private
Definition at line 3 of file HUDSurvival.as.
Referenced by HUDSurvival(), and Update().
The documentation for this class was generated from the following file:
scripts/GUI/HUD/HUDSurvival.as