HoHDocs: DetailsWidget Class Reference
DetailsWidget Class Reference
Private Member Functions
DetailsWidget ()
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void UpdateSize ()
void ToggleDetails ()
void AddedToParent () override
void DoDraw (SpriteBatch &sb, vec2 pos) override
bool OnMouseDown (vec2 mousePos) override
bool OnMouseUp (vec2 mousePos) override
bool OnClick (vec2 mousePos) override
Private Attributes
SpriteRect m_spriteRect
Sprite m_spriteArrowDown
Sprite m_spriteArrowUp
Widget m_wHeader
Widget m_wDetails
bool m_pressedDown
string m_func
Detailed Description
Definition at line 1 of file DetailsWidget.as.
Constructor & Destructor Documentation
DetailsWidget()
DetailsWidget::DetailsWidget () inline private
Definition at line 15 of file DetailsWidget.as.
Referenced by Clone().
     {
         super();
     }
Member Function Documentation
AddedToParent()
void DetailsWidget::AddedToParent () inline override private
Definition at line 95 of file DetailsWidget.as.
References Widget::AddedToParent(), Widget::GetWidgetById(), Widget::m_visible, m_wDetails, m_wHeader, and UpdateSize().
     {
         Widget::AddedToParent();
         @m_wHeader = GetWidgetById("header");
         @m_wDetails = GetWidgetById("details");
         if (m_wHeader is null)
         {
             PrintError("No header found in DetailsWidget!");
             return;
         }
         if (m_wDetails is null)
         {
             PrintError("No details found in DetailsWidget!");
             return;
         }
         m_wDetails.m_visible = false;
         UpdateSize();
     }
Clone()
Widget DetailsWidget::Clone () inline override private
Definition at line 20 of file DetailsWidget.as.
References Widget::CloneInto(), and DetailsWidget().
     {
         DetailsWidget@ w = DetailsWidget();
         CloneInto(w);
         return w;
     }
DoDraw()
void DetailsWidget::DoDraw (SpriteBatch & sb, vec2 pos) inline override private
Definition at line 119 of file DetailsWidget.as.
References g_menuTime, Widget::m_height, Widget::m_hovering, m_pressedDown, m_spriteArrowDown, m_spriteArrowUp, m_spriteRect, Widget::m_visible, m_wDetails, and Widget::m_width.
     {
         if (m_spriteRect !is null)
         {
             int variation = 0;
             if (m_hovering && m_pressedDown)
                 variation = 2;
             else if (m_hovering)
                 variation = 1;
             m_spriteRect.Draw(sb, pos, m_width, m_height, variation);
         }
         Sprite@ arrowSprite = m_spriteArrowDown;
         if (m_wDetails.m_visible)
             @arrowSprite = m_spriteArrowUp;
         if (m_spriteArrowDown !is null)
         {
             float bottomPadding = 8.0f;
             if (m_spriteRect !is null)
                 bottomPadding = m_spriteRect.GetBottom();
             vec2 arrowPos = pos + vec2(
                 float(int(m_width / 2.0f - arrowSprite.GetWidth() / 2.0f)),
                 m_height - arrowSprite.GetHeight() / 2.0f - bottomPadding / 2.0f - 1
             );
             sb.DrawSprite(arrowPos, arrowSprite, g_menuTime);
         }
     }
Load()
void DetailsWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 27 of file DetailsWidget.as.
References Widget::Load(), Widget::m_canFocus, Widget::m_flow, m_func, Widget::m_padding, m_spriteArrowDown, m_spriteArrowUp, m_spriteRect, SpriteRect(), and Vbox.
Referenced by LoadDetailsWidget().
     {
         auto def = ctx.GetGUIDef();
         string spriteset = ctx.GetString("spriteset", false, "");
         if (spriteset != "")
             @m_spriteRect = SpriteRect(spriteset);
         @m_spriteArrowDown = def.GetSprite(ctx.GetString("arrow-down", false));
         @m_spriteArrowUp = def.GetSprite(ctx.GetString("arrow-up", false));
         m_func = ctx.GetString("func", false);
         Widget::Load(ctx);
         m_canFocus = true;
         m_flow = WidgetFlow::Vbox;
         if (m_spriteRect !is null)
         {
             m_padding = vec2(
                 m_spriteRect.GetLeft(),
                 m_spriteRect.GetTop()
             );
         }
     }
OnClick()
bool DetailsWidget::OnClick (vec2 mousePos) inline override private
Definition at line 162 of file DetailsWidget.as.
References ToggleDetails().
     {
         ToggleDetails();
         return true;
     }
OnMouseDown()
bool DetailsWidget::OnMouseDown (vec2 mousePos) inline override private
Definition at line 150 of file DetailsWidget.as.
References m_pressedDown.
     {
         m_pressedDown = true;
         return true;
     }
OnMouseUp()
bool DetailsWidget::OnMouseUp (vec2 mousePos) inline override private
Definition at line 156 of file DetailsWidget.as.
References m_pressedDown.
     {
         m_pressedDown = false;
         return true;
     }
ToggleDetails()
void DetailsWidget::ToggleDetails () inline private
Definition at line 85 of file DetailsWidget.as.
References m_func, Widget::m_host, Widget::m_visible, m_wDetails, and UpdateSize().
Referenced by OnClick().
     {
         m_wDetails.m_visible = !m_wDetails.m_visible;
         m_host.DoLayout();
         UpdateSize();
         if (m_func != "")
             m_host.OnFunc(this, m_func);
     }
UpdateSize()
void DetailsWidget::UpdateSize () inline private
Definition at line 55 of file DetailsWidget.as.
References Widget::m_height, m_spriteRect, Widget::m_visible, m_wDetails, m_wHeader, Widget::m_width, and max.
Referenced by AddedToParent(), and ToggleDetails().
     {
         int padX = 0;
         int padY = 0;
         if (m_spriteRect !is null)
         {
             padX = m_spriteRect.GetLeft() + m_spriteRect.GetRight();
             padY = m_spriteRect.GetTop() + m_spriteRect.GetBottom();
         }
         m_width = 0;
         m_height = 0;
         if (m_wHeader.m_visible)
         {
             m_width = max(m_width, m_wHeader.m_width);
             m_height += m_wHeader.m_height;
         }
         if (m_wDetails.m_visible)
         {
             m_width = max(m_width, m_wDetails.m_width);
             m_height += m_wDetails.m_height;
         }
         m_width += padX;
         m_height += padY;
     }
Member Data Documentation
m_func
string DetailsWidget::m_func private
Definition at line 13 of file DetailsWidget.as.
Referenced by Load(), and ToggleDetails().
m_pressedDown
bool DetailsWidget::m_pressedDown private
Definition at line 11 of file DetailsWidget.as.
Referenced by DoDraw(), OnMouseDown(), and OnMouseUp().
m_spriteArrowDown
Sprite DetailsWidget::m_spriteArrowDown private
Definition at line 5 of file DetailsWidget.as.
Referenced by DoDraw(), and Load().
m_spriteArrowUp
Sprite DetailsWidget::m_spriteArrowUp private
Definition at line 6 of file DetailsWidget.as.
Referenced by DoDraw(), and Load().
m_spriteRect
SpriteRect DetailsWidget::m_spriteRect private
Definition at line 3 of file DetailsWidget.as.
Referenced by DoDraw(), Load(), and UpdateSize().
m_wDetails
Widget DetailsWidget::m_wDetails private
Definition at line 9 of file DetailsWidget.as.
Referenced by AddedToParent(), DoDraw(), ToggleDetails(), and UpdateSize().
m_wHeader
Widget DetailsWidget::m_wHeader private
Definition at line 8 of file DetailsWidget.as.
Referenced by AddedToParent(), and UpdateSize().
The documentation for this class was generated from the following file:
scripts/GUI/DetailsWidget.as