HoHDocs: PassiveMovement Class Reference
PassiveMovement Class Reference
Private Member Functions
PassiveMovement (UnitPtr unit, SValue &params)
void Initialize (UnitPtr unit, CompositeActorBehavior &behavior) override
void Update (int dt, bool isCasting) override
Private Attributes
AnimString m_idleAnim
Detailed Description
Definition at line 1 of file PassiveMovement.as.
Constructor & Destructor Documentation
PassiveMovement()
PassiveMovement::PassiveMovement (UnitPtr unit, SValue & params) inline private
Definition at line 5 of file PassiveMovement.as.
References m_idleAnim, and unit.
     {
         super(unit, params);
         @m_idleAnim = AnimString(GetParamString(unit, params, "anim-idle"));
     }
Member Function Documentation
Initialize()
void PassiveMovement::Initialize (UnitPtr unit, CompositeActorBehavior & behavior) inline override private
Definition at line 11 of file PassiveMovement.as.
References AnimString::GetSceneName(), Initialize(), m_idleAnim, ActorMovement::m_unit, and unit.
     {
         ActorMovement::Initialize(unit, behavior);
         m_unit.SetUnitScene(m_idleAnim.GetSceneName(m_dir), false);
     }
Update()
void PassiveMovement::Update (int dt, bool isCasting) inline override private
Definition at line 17 of file PassiveMovement.as.
References AnimString::GetSceneName(), ActorMovement::m_behavior, ActorMovement::m_enabled, m_idleAnim, ActorMovement::m_unit, and Update().
     {
         if (!m_enabled)
             return;
         ActorMovement::Update(dt, isCasting);
         if (!isCasting && m_behavior.m_target !is null)
         {
             vec3 dir = m_behavior.m_target.m_unit.GetPosition() - m_unit.GetPosition();
             m_dir = atan(dir.y, dir.x);
             string scene = m_idleAnim.GetSceneName(m_dir);
             m_unit.SetUnitScene(scene, false);
         }
     }
Member Data Documentation
m_idleAnim
AnimString PassiveMovement::m_idleAnim private
Definition at line 3 of file PassiveMovement.as.
Referenced by Initialize(), PassiveMovement(), and Update().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Enemies/Movements/PassiveMovement.as