HoHDocs: Skills::ShootProjectile Class Reference
Skills::ShootProjectile Class Reference
Private Member Functions
ShootProjectile (UnitPtr unit, SValue &params)
bool NeedNetParams () override
TargetingMode GetTargetingMode (int &out size) override
vec2 GetShootDir (vec2 dir, int i)
UnitPtr ProduceProjectile (vec2 shootPos, int id=0)
void DoShoot (SValueBuilder@ builder, vec2 pos, vec2 dir)
void DoActivate (SValueBuilder@ builder, vec2 target) override
void NetDoActivate (SValue@ param, vec2 target) override
void DoUpdate (int dt) override
Private Attributes
UnitProducer m_projectile
int m_projectiles
float m_spread
float m_spreadMin
float m_spreadMax
int m_spreadTime
int m_spreadTimeC
int m_spreadCooldown
int m_shootDist
float m_rangeMul
Detailed Description
Definition at line 3 of file ShootProjectile.as.
Constructor & Destructor Documentation
ShootProjectile()
Skills::ShootProjectile::ShootProjectile (UnitPtr unit, SValue & params) inline private
Definition at line 18 of file ShootProjectile.as.
References m_projectile, m_projectiles, m_rangeMul, m_shootDist, m_spread, m_spreadCooldown, m_spreadMax, m_spreadMin, m_spreadTime, and unit.
         {
             super(unit, params);
             @m_projectile = Resources::GetUnitProducer(GetParamString(unit, params, "projectile"));
             m_projectiles = GetParamInt(unit, params, "projectiles", false, 1);
             m_shootDist = GetParamInt(unit, params, "dist", false, 0);
             SValue@ spread = GetParamDictionary(unit, params, "spread", false);
             if (spread !is null)
             {
                 m_spreadMin = GetParamInt(unit, spread, "min") * PI / 180.0;
                 m_spreadMax = GetParamInt(unit, spread, "max") * PI / 180.0;
                 m_spreadTime = GetParamInt(unit, spread, "time");
                 m_spreadCooldown = GetParamInt(unit, params, "cooldown", false, 100);
             }
             else
             {
                 m_spreadMin = GetParamInt(unit, params, "spread-min", false) * PI / 180.0;
                 m_spread = GetParamInt(unit, params, "spread", false) * PI / 180.0;
             }
             m_rangeMul = GetParamFloat(unit, params, "range-mul", false, 1.0f);
         }
Member Function Documentation
DoActivate()
void Skills::ShootProjectile::DoActivate (SValueBuilder@ builder, vec2 target) inline override private
Definition at line 123 of file ShootProjectile.as.
References DoShoot(), lerp(), Skills::m_owner, m_spread, m_spreadCooldown, m_spreadMax, m_spreadMin, m_spreadTime, m_spreadTimeC, min, Skills::ActiveSkill::PlaySkillEffect(), and xy().
         {
             PlaySkillEffect(target);
             if (m_spreadTime > 0)
             {
                 m_spread = lerp(m_spreadMin, m_spreadMax, min(1.0, m_spreadTimeC / float(m_spreadTime)));
                 m_spreadTimeC = min(m_spreadTime, m_spreadTimeC + m_spreadCooldown);
             }
             auto pos = xy(m_owner.m_unit.GetPosition());
             DoShoot(builder, pos, target);
         }
DoShoot()
void Skills::ShootProjectile::DoShoot (SValueBuilder@ builder, vec2 pos, vec2 dir) inline private
Definition at line 72 of file ShootProjectile.as.
References g_scene, GetShootDir(), Skills::m_owner, m_projectiles, m_rangeMul, m_shootDist, Skills::m_skillId, Actor::m_unit, and ProduceProjectile().
Referenced by DoActivate().
         {
             Actor@ targetEnemy = null;
             if (builder !is null)
             {
                 builder.PushArray();
                 builder.PushVector2(pos);
                 if (targetEnemy is null)
                     builder.PushInteger(0);
                 else
                     builder.PushInteger(targetEnemy.m_unit.GetId());
             }
             for (int i = 0; i < m_projectiles; i++)
             {
                 vec2 shootDir = GetShootDir(dir, i);
                 vec2 shootPos = pos + shootDir * m_shootDist;
                 if (m_shootDist > 0)
                 {
                     auto results = g_scene.RaycastClosest(pos, shootPos, ~0, RaycastType::Shot);
                     if (results.FetchUnit(g_scene).IsValid())
                         shootPos = results.point;
                 }
                 auto proj = ProduceProjectile(shootPos);
                 if (!proj.IsValid())
                     continue;
                 auto p = cast<IProjectile>(proj.GetScriptBehavior());
                 if (p is null)
                     continue;
                 if (builder !is null)
                 {
                     builder.PushInteger(proj.GetId());
                     builder.PushVector2(shootDir);
                 }
                 p.Initialize(m_owner, shootDir, 1.0f, false, targetEnemy, m_skillId + 1);
                 auto pp = cast<Projectile>(p);
                 if (pp !is null)
                     pp.m_liveRangeSq *= m_rangeMul;
             }
             if (builder !is null)
                 builder.PopArray();
         }
DoUpdate()
void Skills::ShootProjectile::DoUpdate (int dt) inline override private
Definition at line 181 of file ShootProjectile.as.
         {
             //if (cooldown <= 0)
             //  m_spreadTimeC = 0;
         }
GetShootDir()
vec2 Skills::ShootProjectile::GetShootDir (vec2 dir, int i) inline private
Definition at line 52 of file ShootProjectile.as.
References m_spread, and m_spreadMin.
Referenced by DoShoot().
         {
             if (m_spread > 0 || m_spreadMin > 0)
             {
                 float rnd = (randf() - 0.5) * (m_spread - m_spreadMin);
                 if (m_spreadMin > 0)
                     rnd += (randi(2) == 0 ? m_spreadMin : -m_spreadMin);
                 float ang = atan(dir.y, dir.x) + rnd;
                 return vec2(cos(ang), sin(ang));
             }
             return dir;
         }
GetTargetingMode()
TargetingMode Skills::ShootProjectile::GetTargetingMode (int &out size) inline override private
Definition at line 46 of file ShootProjectile.as.
References Skills::Direction.
         {
             size = 0;
             return TargetingMode::Direction;
         }
NeedNetParams()
bool Skills::ShootProjectile::NeedNetParams () inline override private
Definition at line 45 of file ShootProjectile.as.
 { return true; }
NetDoActivate()
void Skills::ShootProjectile::NetDoActivate (SValue@ param, vec2 target) inline override private
Definition at line 137 of file ShootProjectile.as.
References g_scene, Skills::m_owner, m_rangeMul, m_shootDist, Skills::m_skillId, Skills::ActiveSkill::PlaySkillEffect(), ProduceProjectile(), and xy().
         {
             if (target.x != 0 && target.y != 0)
                 PlaySkillEffect(target);
             array<SValue@>@ pm = param.GetArray();
             auto pos = pm[0].GetVector2();
             int targetId = pm[1].GetInteger();
             Actor@ targetEnemy;
             if (targetId != 0)
             {
                 UnitPtr targetUnit = g_scene.GetUnit(targetId);
                 if (targetUnit.IsValid())
                     @targetEnemy = cast<Actor>(targetUnit.GetScriptBehavior());
             }
             for (uint i = 2; i < pm.length(); i += 2)
             {
                 vec2 shootDir = pm[i + 1].GetVector2();
                 vec2 shootPos = pos + shootDir * m_shootDist;
                 if (m_shootDist > 0)
                 {
                     auto results = g_scene.RaycastClosest(xy(m_owner.m_unit.GetPosition()), shootPos, ~0, RaycastType::Shot);
                     if (results.FetchUnit(g_scene).IsValid())
                         shootPos = results.point;
                 }
                 auto proj = ProduceProjectile(shootPos, pm[i + 0].GetInteger());
                 if (!proj.IsValid())
                     continue;
                 IProjectile@ p = cast<IProjectile>(proj.GetScriptBehavior());
                 if (p is null)
                     continue;
                 p.Initialize(m_owner, shootDir, 1.0f, true, targetEnemy, m_skillId + 1);
                 auto pp = cast<Projectile>(p);
                 if (pp !is null)
                     pp.m_liveRangeSq *= m_rangeMul;
             }
         }
ProduceProjectile()
UnitPtr Skills::ShootProjectile::ProduceProjectile (vec2 shootPos, int id = 0) inline private
Definition at line 67 of file ShootProjectile.as.
References g_scene, m_projectile, and xyz().
Referenced by DoShoot(), and NetDoActivate().
         {
             return m_projectile.Produce(g_scene, xyz(shootPos), id);
         }
Member Data Documentation
m_projectile
UnitProducer Skills::ShootProjectile::m_projectile private
Definition at line 5 of file ShootProjectile.as.
Referenced by ProduceProjectile(), and ShootProjectile().
m_projectiles
int Skills::ShootProjectile::m_projectiles private
Definition at line 6 of file ShootProjectile.as.
Referenced by DoShoot(), Skills::ShootProjectileFan::GetShootDir(), and ShootProjectile().
m_rangeMul
float Skills::ShootProjectile::m_rangeMul private
Definition at line 16 of file ShootProjectile.as.
Referenced by DoShoot(), NetDoActivate(), and ShootProjectile().
m_shootDist
int Skills::ShootProjectile::m_shootDist private
Definition at line 14 of file ShootProjectile.as.
Referenced by DoShoot(), NetDoActivate(), and ShootProjectile().
m_spread
float Skills::ShootProjectile::m_spread private
Definition at line 8 of file ShootProjectile.as.
Referenced by DoActivate(), Skills::ShootProjectileFan::GetShootDir(), GetShootDir(), and ShootProjectile().
m_spreadCooldown
int Skills::ShootProjectile::m_spreadCooldown private
Definition at line 13 of file ShootProjectile.as.
Referenced by DoActivate(), and ShootProjectile().
m_spreadMax
float Skills::ShootProjectile::m_spreadMax private
Definition at line 10 of file ShootProjectile.as.
Referenced by DoActivate(), and ShootProjectile().
m_spreadMin
float Skills::ShootProjectile::m_spreadMin private
Definition at line 9 of file ShootProjectile.as.
Referenced by DoActivate(), Skills::ShootProjectileFan::GetShootDir(), GetShootDir(), and ShootProjectile().
m_spreadTime
int Skills::ShootProjectile::m_spreadTime private
Definition at line 11 of file ShootProjectile.as.
Referenced by DoActivate(), and ShootProjectile().
m_spreadTimeC
int Skills::ShootProjectile::m_spreadTimeC private
Definition at line 12 of file ShootProjectile.as.
Referenced by DoActivate().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Skills/ShootProjectile.as