HoHDocs: BossBarWidget Class Reference
BossBarWidget Class Reference
Private Member Functions
BossBarWidget ()
Widget Clone () override
void Remove () override
void Load (WidgetLoadingContext &ctx) override
Sprite GetBarSprite (float factor) override
void Update (int dt) override
void SetText (string str)
void DoDraw (SpriteBatch &sb, vec2 pos) override
void UpdateAppearance ()
Private Attributes
Actor m_actor
float m_checkpoint = -1
BitmapFont m_font
BitmapString m_text
Sprite m_spriteBarInvuln
Sprite m_spriteBarCheckpoint
vec2 m_textOffset
Detailed Description
Definition at line 1 of file BossBar.as.
Constructor & Destructor Documentation
BossBarWidget()
BossBarWidget::BossBarWidget () inline private
Definition at line 15 of file BossBar.as.
Referenced by Clone().
     {
         super();
     }
Member Function Documentation
Clone()
Widget BossBarWidget::Clone () inline override private
Definition at line 20 of file BossBar.as.
References BossBarWidget().
     {
         BossBarWidget@ w = BossBarWidget();
         CloneInto(w);
         return w;
     }
DoDraw()
void BossBarWidget::DoDraw (SpriteBatch & sb, vec2 pos) inline override private
Definition at line 80 of file BossBar.as.
References DoDraw(), m_height, m_text, m_textOffset, and Skills::m_width.
     {
         BarWidget::DoDraw(sb, pos);
         if (m_text is null)
             return;
         sb.DrawString(pos + vec2(
             m_width / 2 - m_text.GetWidth() / 2,
             m_height / 2 - m_text.GetHeight() / 2
         ) + m_textOffset, m_text);
     }
GetBarSprite()
Sprite BossBarWidget::GetBarSprite (float factor) inline override private
Definition at line 54 of file BossBar.as.
References GetBarSprite(), Actor::IsImmortal(), m_actor, m_checkpoint, m_scale, m_spriteBarCheckpoint, and m_spriteBarInvuln.
     {
         if (factor < m_scale && m_actor.IsImmortal())
             return m_spriteBarInvuln;
         if (m_checkpoint >= 0 && factor > m_scale && factor > m_checkpoint)
             return m_spriteBarCheckpoint;
         return BarWidget::GetBarSprite(factor);
     }
Load()
void BossBarWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 42 of file BossBar.as.
References Load(), m_font, m_spriteBarCheckpoint, m_spriteBarInvuln, and m_textOffset.
Referenced by LoadBossBarWidget().
     {
         BarWidget::Load(ctx);
         @m_font = Resources::GetBitmapFont(ctx.GetString("text-font", false));
         m_textOffset = ctx.GetVector2("text-offset", false);
         GUIDef@ def = ctx.GetGUIDef();
         @m_spriteBarInvuln = def.GetSprite(ctx.GetString("bar-invuln", false));
         @m_spriteBarCheckpoint = def.GetSprite(ctx.GetString("bar-checkpoint", false));
     }
Remove()
void BossBarWidget::Remove () inline override private
Definition at line 27 of file BossBar.as.
References Remove().
Referenced by UpdateAppearance().
     {
         array<Widget@>@ arr = m_parent.m_children;
         BarWidget::Remove();
         for (uint i = 0; i < arr.length(); i++)
         {
             auto wBar = cast<BossBarWidget>(arr[i]);
             if (wBar is null)
                 continue;
             wBar.UpdateAppearance();
         }
     }
SetText()
void BossBarWidget::SetText (string str) inline private
Definition at line 69 of file BossBar.as.
References m_font, and m_text.
Referenced by UpdateAppearance().
     {
         if (str == "")
             @m_text = null;
         else
         {
             @m_text = m_font.BuildText(str);
             m_text.SetColor(vec4(1, 0, 0, 1));
         }
     }
Update()
void BossBarWidget::Update (int dt) inline override private
Definition at line 63 of file BossBar.as.
References Update(), and UpdateAppearance().
     {
         UpdateAppearance();
         BarWidget::Update(dt);
     }
UpdateAppearance()
void BossBarWidget::UpdateAppearance () inline private
Definition at line 93 of file BossBar.as.
References formatThousands(), Actor::GetHealth(), Actor::IsDead(), m_actor, m_colorValue, m_offset, m_scale, Actor::m_unit, Skills::m_width, Remove(), SetScale(), and SetText().
Referenced by Update().
     {
         if (m_actor is null)
             return;
         if (m_actor.IsDead() || m_actor.m_unit.IsDestroyed())
         {
             Remove();
             return;
         }
         int numBars = m_parent.m_children.length() - 2; // -2 because of the 2 sprite widgets inside of boss-bars in HoH
         float barWidth = m_parent.m_width / float(numBars);
         int index = m_parent.m_children.findByRef(this) - 2;
         if (index < 0)
             return;
         m_offset.x = index * int(barWidth);
         if (index == numBars - 1)
             m_width = int(ceil(barWidth));
         else
             m_width = int(barWidth);
         //print("num bars: " + numBars + ", index: " + index);
         SetScale(m_actor.GetHealth());
         m_colorValue = vec4(1 - m_scale, m_scale, 0, 1);
         auto enemy = cast<CompositeActorBehavior>(m_actor);
         if (enemy !is null)
             SetText(formatThousands(int(round(m_actor.GetHealth() * enemy.GetMaxHp()))));
     }
Member Data Documentation
m_actor
Actor BossBarWidget::m_actor private
Definition at line 3 of file BossBar.as.
Referenced by GetBarSprite(), HUD::GetBossBar(), and UpdateAppearance().
m_checkpoint
float BossBarWidget::m_checkpoint = -1 private
Definition at line 5 of file BossBar.as.
Referenced by GetBarSprite(), and WorldScript::BossBarCheckpoint::ServerExecute().
m_font
BitmapFont BossBarWidget::m_font private
Definition at line 7 of file BossBar.as.
Referenced by Load(), and SetText().
m_spriteBarCheckpoint
Sprite BossBarWidget::m_spriteBarCheckpoint private
Definition at line 11 of file BossBar.as.
Referenced by GetBarSprite(), and Load().
m_spriteBarInvuln
Sprite BossBarWidget::m_spriteBarInvuln private
Definition at line 10 of file BossBar.as.
Referenced by GetBarSprite(), and Load().
m_text
BitmapString BossBarWidget::m_text private
Definition at line 8 of file BossBar.as.
Referenced by DoDraw(), and SetText().
m_textOffset
vec2 BossBarWidget::m_textOffset private
Definition at line 13 of file BossBar.as.
Referenced by DoDraw(), and Load().
The documentation for this class was generated from the following file:
scripts/GUI/HUD/BossBar.as