HoHDocs: BuffWidget Class Reference
BuffWidget Class Reference
Private Member Functions
BuffWidget ()
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void AddedToParent () override
void Update (int dt) override
void DoDraw (SpriteBatch &sb, vec2 pos) override
Private Attributes
IBuffWidgetInfo m_buff
TextWidget m_wStackText
Detailed Description
Definition at line 9 of file BuffWidget.as.
Constructor & Destructor Documentation
BuffWidget()
BuffWidget::BuffWidget () inline private
Definition at line 15 of file BuffWidget.as.
Referenced by Clone().
     {
         super();
     }
Member Function Documentation
AddedToParent()
void BuffWidget::AddedToParent () inline override private
Definition at line 35 of file BuffWidget.as.
     {
         @m_wStackText = cast<TextWidget>(GetWidgetById("stack-count"));
     }
Clone()
Widget BuffWidget::Clone () inline override private
Definition at line 20 of file BuffWidget.as.
References BuffWidget().
     {
         BuffWidget@ w = BuffWidget();
         CloneInto(w);
         return w;
     }
DoDraw()
void BuffWidget::DoDraw (SpriteBatch & sb, vec2 pos) inline override private
Definition at line 68 of file BuffWidget.as.
References g_menuTime, icon, and m_buff.
     {
         if (m_buff is null)
             return;
         auto icon = m_buff.GetBuffIcon();
         if (icon is null)
             return;
         sb.EnableColorize(vec4(0, 0, 0, 1), vec4(0.125, 0.125, 0.125, 1), vec4(0.25, 0.25, 0.25, 1));
         icon.Draw(sb, pos, g_menuTime, vec4(0.5, 0.5, 0.5, 1));
         sb.DisableColorize();
         float radius = m_buff.GetBuffIconDuration() / float(m_buff.GetBuffIconMaxDuration());
         icon.DrawRadial(sb, pos, radius, g_menuTime);
     }
Load()
void BuffWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 27 of file BuffWidget.as.
References Widget::Load().
Referenced by LoadBuffWidget().
     {
         Widget::Load(ctx);
         m_width = 12;
         m_height = 12;
     }
Update()
void BuffWidget::Update (int dt) inline override private
Definition at line 40 of file BuffWidget.as.
References m_buff, m_wStackText, Widget::RemoveFromParent(), TextWidget::SetText(), and Widget::Update().
     {
         Widget::Update(dt);
         if (m_buff is null)
             return;
         if (m_buff.GetBuffIconDuration() <= 0)
         {
             RemoveFromParent();
             return;
         }
         int count = m_buff.GetBuffIconCount();
         if (count == 0)
         {
             RemoveFromParent();
             return;
         }
         else if (count != -1 && m_wStackText !is null)
         {
             m_wStackText.m_visible = true;
             m_wStackText.SetText("" + count);
         }
         else if (count == -1 && m_wStackText !is null)
             m_wStackText.m_visible = false;
     }
Member Data Documentation
m_buff
IBuffWidgetInfo BuffWidget::m_buff private
Definition at line 11 of file BuffWidget.as.
Referenced by DoDraw(), HUD::ShowBuffIcon(), and Update().
m_wStackText
TextWidget BuffWidget::m_wStackText private
Definition at line 13 of file BuffWidget.as.
Referenced by Update(), and Update().
The documentation for this class was generated from the following file:
scripts/GUI/HUD/BuffWidget.as