HoHDocs: EffectFilter Class Reference
EffectFilter Class Reference
Private Member Functions
EffectFilter (UnitPtr unit, SValue &params)
void SetWeaponInformation (uint weapon)
bool Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
bool CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity)
Private Attributes
array< IEffect@> m_effects
float m_selfDmg
float m_teamDmg
bool m_negate
Detailed Description
Definition at line 1 of file EffectFilter.as.
Constructor & Destructor Documentation
EffectFilter()
EffectFilter::EffectFilter (UnitPtr unit, SValue & params) inline private
Definition at line 10 of file EffectFilter.as.
References LoadEffects(), m_effects, m_negate, m_selfDmg, m_teamDmg, and unit.
     {
         @m_effects = LoadEffects(unit, params);
         m_selfDmg = GetParamFloat(unit, params, "self-dmg", false, 0);
         m_teamDmg = GetParamFloat(unit, params, "team-dmg", false, 0);
         m_negate = GetParamBool(unit, params, "negate", false);
     }
Member Function Documentation
Apply()
bool EffectFilter::Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk) inline private
Definition at line 25 of file EffectFilter.as.
References ApplyEffects(), CanApply(), m_effects, m_selfDmg, and m_teamDmg.
     {
         if (!CanApply(owner, target, pos, dir, intensity))
             return false;
         ApplyEffects(m_effects, owner, target, pos, dir, intensity, husk, m_selfDmg, m_teamDmg);
         return true;
     }
CanApply()
bool EffectFilter::CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) inline private
Definition at line 35 of file EffectFilter.as.
References m_negate.
Referenced by Apply().
     {
         bool ret = true;
         if (m_negate)
             return !ret;
         return ret;
     }
SetWeaponInformation()
void EffectFilter::SetWeaponInformation (uint weapon) inline private
Definition at line 20 of file EffectFilter.as.
References m_effects, and PropagateWeaponInformation().
     {
         PropagateWeaponInformation(m_effects, weapon);
     }
Member Data Documentation
m_effects
array<IEffect@> EffectFilter::m_effects private
Definition at line 3 of file EffectFilter.as.
Referenced by Apply(), EffectFilter(), and SetWeaponInformation().
m_negate
bool EffectFilter::m_negate private
Definition at line 8 of file EffectFilter.as.
Referenced by CanApply(), and EffectFilter().
m_selfDmg
float EffectFilter::m_selfDmg private
Definition at line 5 of file EffectFilter.as.
Referenced by Apply(), and EffectFilter().
m_teamDmg
float EffectFilter::m_teamDmg private
Definition at line 6 of file EffectFilter.as.
Referenced by Apply(), and EffectFilter().
The documentation for this class was generated from the following file:
scripts/Behaviors/Effects/EffectFilter.as