HoHDocs: ShortcutLevel Class Reference
ShortcutLevel Class Reference
Private Member Functions
ShortcutLevel (Scene@ scene)
void Generate (SValue@ save)
void Start (uint8 peer, SValue@ save, StartMode sMode) override
Detailed Description
Definition at line 2 of file ShortcutLevel.as.
Constructor & Destructor Documentation
ShortcutLevel()
ShortcutLevel::ShortcutLevel (Scene@ scene) inline private
Definition at line 4 of file ShortcutLevel.as.
     {
         super(scene);
     }
Member Function Documentation
Generate()
void ShortcutLevel::Generate (SValue@ save) inline private
Definition at line 10 of file ShortcutLevel.as.
 {}
Start()
void ShortcutLevel::Start (uint8 peer, SValue@ save, StartMode sMode) inline override private
Definition at line 12 of file ShortcutLevel.as.
References Stats::Add(), CalcLevel(), DiscordPresence::Clear(), ServicePresence::Clear(), g_ngp, GetLocalPlayerRecord(), BaseGameMode::m_levelCount, BaseGameMode::m_rotation, ServicePresence::Param(), BaseGameMode::PostStart(), RichPresenceGetActName(), ServicePresence::Set(), DiscordPresence::SetDetails(), DiscordPresence::SetLargeImageKey(), SetLevelFlags(), DiscordPresence::SetStartTimestamp(), DiscordPresence::SetState(), and Campaign::Start().
     {
         Campaign::Start(peer, save, sMode);
         SetLevelFlags(m_levelCount);
         BaseGameMode::PostStart(); // Don't call Campaign::PostStart to avoid applying m_levelCount == 0 stuff
         Stats::Add("floors-visited", 1, GetLocalPlayerRecord());
         auto record = GetLocalPlayerRecord();
         int nextLevelIndex = m_rotation.GetNextActIndex(m_levelCount);
         DiscordPresence::Clear();
         DiscordPresence::SetState("In portal level");
         DiscordPresence::SetDetails(RichPresenceGetActName(m_levelCount) + " to " + RichPresenceGetActName(nextLevelIndex));
         DiscordPresence::SetStartTimestamp(time() - record.statisticsSession.GetStatInt("time-played"));
         DiscordPresence::SetLargeImageKey("portal");
         auto levelInfo = CalcLevel(m_levelCount);
         ServicePresence::Clear();
         if (g_ngp == 0)
             ServicePresence::Set("#Status_InPortalLevel");
         else
         {
             ServicePresence::Set("#Status_InPortalLevel_NGP");
             ServicePresence::Param("ngp", "" + g_ngp);
         }
         ServicePresence::Param("level", "" + record.level);
         ServicePresence::Param("act", "" + (levelInfo.x + 1));
         ServicePresence::Param("nextact", "" + (levelInfo.x + 2));
     }
The documentation for this class was generated from the following file:
scripts/GameModes/ShortcutLevel.as