HoHDocs: BossLichMovement Class Reference
BossLichMovement Class Reference
Private Member Functions
BossLichMovement (UnitPtr unit, SValue &params)
void Initialize (UnitPtr unit, CompositeActorBehavior &behavior) override
WorldScript::BossLichNode FindNewNode ()
void SetTargetNode (WorldScript::BossLichNode@ node)
void DoCasting (int dt)
void DoWalkPaths (int dt)
void Update (int dt, bool isCasting) override
Private Attributes
AnimString m_idleAnim
AnimString m_walkAnim
float m_speed
WorldScript::BossLichNode m_nodeTarget
WorldScript::BossLichNode m_nodeLastVisited
Detailed Description
Definition at line 3 of file BossLichMovement.as.
Constructor & Destructor Documentation
BossLichMovement()
BossLichMovement::BossLichMovement (UnitPtr unit, SValue & params) inline private
Definition at line 13 of file BossLichMovement.as.
References m_idleAnim, m_speed, m_walkAnim, and unit.
     {
         super(unit, params);
         @m_idleAnim = AnimString(GetParamString(unit, params, "anim-idle"));
         @m_walkAnim = AnimString(GetParamString(unit, params, "anim-walk"));
         m_speed = GetParamFloat(unit, params, "speed");
     }
Member Function Documentation
DoCasting()
void BossLichMovement::DoCasting (int dt) inline private
Definition at line 54 of file BossLichMovement.as.
References ActorMovement::m_behavior, and ActorMovement::m_unit.
Referenced by Update().
     {
         if (m_behavior.m_target is null)
             return;
         vec3 posTarget = m_behavior.m_target.m_unit.GetPosition();
         vec3 posMe = m_unit.GetPosition();
         m_unit.GetPhysicsBody().SetStatic(true);
     }
DoWalkPaths()
void BossLichMovement::DoWalkPaths (int dt) inline private
Definition at line 65 of file BossLichMovement.as.
References FindNewNode(), g_scene, AnimString::GetSceneName(), m_nodeTarget, m_speed, ActorMovement::m_unit, m_walkAnim, WorldScript::BossLichNode::Position, SetTargetNode(), and xy().
Referenced by Update().
     {
         m_unit.SetUnitScene(m_walkAnim.GetSceneName(m_dir), false);
         auto body = m_unit.GetPhysicsBody();
         if (body is null)
             return;
         body.SetStatic(false);
         if (Network::IsServer())
         {
             if (m_nodeTarget is null)
                 SetTargetNode(FindNewNode());
             else
             {
                 float distance = dist(m_unit.GetPosition(), m_nodeTarget.Position);
                 if (distance < 5.0f)
                 {
                     auto ws = WorldScript::GetWorldScript(g_scene, m_nodeTarget);
                     if (ws !is null)
                         ws.Execute();
                     SetTargetNode(FindNewNode());
                 }
             }
         }
         if (m_nodeTarget !is null)
         {
             vec2 dir = xy(normalize(m_nodeTarget.Position - m_unit.GetPosition()));
             dir *= m_speed;
             body.SetLinearVelocity(dir);
             m_dir = atan(dir.y, dir.x);
         }
     }
FindNewNode()
WorldScript::BossLichNode BossLichMovement::FindNewNode () inline private
Definition at line 30 of file BossLichMovement.as.
References g_lichNodes, m_nodeTarget, and WorldScript::BossLichNode::PickNextNode().
Referenced by DoWalkPaths().
     {
         if (!Network::IsServer())
         {
             PrintError("Clients can't find new BossLichNode!");
             return null;
         }
         if (m_nodeTarget !is null)
             return m_nodeTarget.PickNextNode();
         return g_lichNodes[randi(g_lichNodes.length())];
     }
Initialize()
void BossLichMovement::Initialize (UnitPtr unit, CompositeActorBehavior & behavior) inline override private
Definition at line 23 of file BossLichMovement.as.
References AnimString::GetSceneName(), Initialize(), m_idleAnim, ActorMovement::m_unit, and unit.
     {
         ActorMovement::Initialize(unit, behavior);
         m_unit.SetUnitScene(m_idleAnim.GetSceneName(m_dir), false);
     }
SetTargetNode()
void BossLichMovement::SetTargetNode (WorldScript::BossLichNode@ node) inline private
Definition at line 43 of file BossLichMovement.as.
References g_scene, m_nodeTarget, and ActorMovement::m_unit.
Referenced by DoWalkPaths().
     {
         @m_nodeTarget = node;
         if (Network::IsServer())
         {
             auto script = WorldScript::GetWorldScript(g_scene, node);
             (Network::Message("UnitMovementBossLichTarget") << m_unit << script.GetUnit()).SendToAll();
         }
     }
Update()
void BossLichMovement::Update (int dt, bool isCasting) inline override private
Definition at line 103 of file BossLichMovement.as.
References DoCasting(), DoWalkPaths(), ActorMovement::m_enabled, and Update().
     {
         if (!m_enabled)
             return;
         ActorMovement::Update(dt, isCasting);
         if (isCasting)
             DoCasting(dt);
         else
             DoWalkPaths(dt);
     }
Member Data Documentation
m_idleAnim
AnimString BossLichMovement::m_idleAnim private
Definition at line 5 of file BossLichMovement.as.
Referenced by BossLichMovement(), and Initialize().
m_nodeLastVisited
WorldScript::BossLichNode BossLichMovement::m_nodeLastVisited private
Definition at line 11 of file BossLichMovement.as.
m_nodeTarget
WorldScript::BossLichNode BossLichMovement::m_nodeTarget private
Definition at line 10 of file BossLichMovement.as.
Referenced by DoWalkPaths(), FindNewNode(), and SetTargetNode().
m_speed
float BossLichMovement::m_speed private
Definition at line 8 of file BossLichMovement.as.
Referenced by BossLichMovement(), and DoWalkPaths().
m_walkAnim
AnimString BossLichMovement::m_walkAnim private
Definition at line 6 of file BossLichMovement.as.
Referenced by BossLichMovement(), and DoWalkPaths().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Enemies/Movements/BossLichMovement.as