HoHDocs: ApplyBuff Class Reference
ApplyBuff Class Reference
Private Member Functions
ApplyBuff (UnitPtr unit, SValue &params)
void SetWeaponInformation (uint weapon)
bool Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
bool CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
Private Attributes
ActorBuffDef m_buff
bool m_ignoreIntensity
uint m_weaponInfo
Detailed Description
Definition at line 1 of file ApplyBuff.as.
Constructor & Destructor Documentation
ApplyBuff()
ApplyBuff::ApplyBuff (UnitPtr unit, SValue & params) inline private
Definition at line 7 of file ApplyBuff.as.
References LoadActorBuff(), m_buff, m_ignoreIntensity, and unit.
     {
         @m_buff = LoadActorBuff(GetParamString(unit, params, "buff"));
         m_ignoreIntensity = GetParamBool(unit, params, "ignore-intensity", false, false);
     }
Member Function Documentation
Apply()
bool ApplyBuff::Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk) inline private
Definition at line 18 of file ApplyBuff.as.
References Actor::ApplyBuff(), CanApply(), FilterHuskDamage(), m_buff, m_ignoreIntensity, and m_weaponInfo.
     {
         if (!CanApply(owner, target, pos, dir, intensity))
             return false;
         if (!FilterHuskDamage(owner, target, husk))
             return false;
         Actor@ actor = cast<Actor>(target.GetScriptBehavior());
         return actor.ApplyBuff(ActorBuff(owner, m_buff, m_ignoreIntensity ? 1.0f : intensity, false, m_weaponInfo));
     }
CanApply()
bool ApplyBuff::CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) inline override private
Definition at line 30 of file ApplyBuff.as.
References m_buff.
Referenced by Apply().
     {
         if (!target.IsValid())
             return false;
         if (m_buff is null)
             return false;
         if (intensity <= 0)
             return false;
         Actor@ actor = cast<Actor>(target.GetScriptBehavior());
         if (actor is null)
             return false;
         return true;
     }
SetWeaponInformation()
void ApplyBuff::SetWeaponInformation (uint weapon) inline private
Definition at line 13 of file ApplyBuff.as.
References m_weaponInfo.
     {
         m_weaponInfo = weapon;
     }
Member Data Documentation
m_buff
ActorBuffDef ApplyBuff::m_buff private
Definition at line 3 of file ApplyBuff.as.
Referenced by Apply(), ApplyBuff(), and CanApply().
m_ignoreIntensity
bool ApplyBuff::m_ignoreIntensity private
Definition at line 4 of file ApplyBuff.as.
Referenced by Apply(), and ApplyBuff().
m_weaponInfo
uint ApplyBuff::m_weaponInfo private
Definition at line 5 of file ApplyBuff.as.
Referenced by Apply(), and SetWeaponInformation().
The documentation for this class was generated from the following file:
scripts/Behaviors/Effects/ApplyBuff.as