HoHDocs: Explode Class Reference
Explode Class Reference
Private Member Functions
Explode (UnitPtr unit, SValue &params)
void SetWeaponInformation (uint weapon)
bool NeedNetParams ()
bool DoAction (SValueBuilder@ builder, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity)
string GetFxName (vec2 pos)
bool DoExplosion (Actor@ owner, vec2 pos, vec2 dir, float intensity, bool husk)
bool NetDoAction (SValue@ param, Actor@ owner, vec2 pos, vec2 dir)
bool Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
bool CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
void Update (int dt, int cooldown)
Private Attributes
array< IEffect@> m_effects
string m_fx
string m_tileFx
int m_radius
int m_minRadius
float m_distScaling
float m_selfDmg
float m_teamDmg
float m_enemyDmg
Detailed Description
Definition at line 1 of file Explode.as.
Constructor & Destructor Documentation
Explode()
Explode::Explode (UnitPtr unit, SValue & params) inline private
Definition at line 13 of file Explode.as.
References LoadEffects(), m_distScaling, m_effects, m_enemyDmg, m_fx, m_minRadius, m_radius, m_selfDmg, m_teamDmg, m_tileFx, and unit.
     {
         m_fx = GetParamString(unit, params, "fx", false);
         m_tileFx = GetParamString(unit, params, "tile-fx", false);
         m_radius = GetParamInt(unit, params, "radius");
         m_minRadius = GetParamInt(unit, params, "min-radius", false, 0);
         m_distScaling = GetParamFloat(unit, params, "dist-scaling", false, 3);
         m_selfDmg = GetParamFloat(unit, params, "self-dmg", false, 0);
         m_teamDmg = GetParamFloat(unit, params, "team-dmg", false, 0);
         m_enemyDmg = GetParamFloat(unit, params, "enemy-dmg", false, 1);
         @m_effects = LoadEffects(unit, params);
     }
Member Function Documentation
Apply()
bool Explode::Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk) inline private
Definition at line 139 of file Explode.as.
References DoExplosion().
     {
         return DoExplosion(owner, pos, dir, intensity, husk);
     }
CanApply()
bool Explode::CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) inline override private
Definition at line 144 of file Explode.as.
     {
         return true;
     }
DoAction()
bool Explode::DoAction (SValueBuilder@ builder, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity) inline private
Definition at line 33 of file Explode.as.
References DoExplosion().
     {
         builder.PushFloat(intensity);
         return DoExplosion(owner, pos, dir, intensity, false);
     }
DoExplosion()
bool Explode::DoExplosion (Actor@ owner, vec2 pos, vec2 dir, float intensity, bool husk) inline private
Definition at line 62 of file Explode.as.
References ApplyEffects(), g_scene, GetFxName(), m_distScaling, m_effects, m_enemyDmg, m_minRadius, m_radius, m_selfDmg, m_teamDmg, max, PlayEffect(), unit, and xy().
Referenced by Apply(), DoAction(), ExplodeChainLimit::DoExplosion(), and NetDoAction().
     {
         dictionary ePs = { { 'radius', m_radius } };
         PlayEffect(GetFxName(pos), pos, ePs);
         array<UnitPtr>@ directHits;
         if (m_minRadius > 0)
             @directHits = g_scene.QueryCircle(pos, m_minRadius, ~0, RaycastType::Shot, true);
         else
             @directHits = array<UnitPtr>();
         auto results = g_scene.QueryCircle(pos, m_radius, ~0, RaycastType::Shot, true);
         for (uint i = 0; i < results.length(); i++)
         {
             UnitPtr unit = results[i];
             vec2 upos = xy(unit.GetPosition());
             bool visible = true;
             float hitDist = m_radius + 1;
             for (uint j = 0; j < directHits.length(); j++)
             {
                 if (results[i] == directHits[j])
                 {
                     hitDist = 0;
                     break;
                 }
             }
             if (hitDist > 0)
             {
                 auto rayResults = g_scene.Raycast(pos, upos, ~0, RaycastType::Shot);
                 if (rayResults.length() <= 0)
                     hitDist = 0;
                 for (uint j = 0; j < rayResults.length(); j++)
                 {
                     UnitPtr res_unit = rayResults[j].FetchUnit(g_scene);
                     if (!res_unit.IsValid())
                         continue;
                     if (res_unit == unit)
                     {
                         hitDist = max(0.0, rayResults[j].fraction * length(upos - pos) - m_minRadius);
                         upos = rayResults[j].point;
                         break;
                     }
                     auto b = res_unit.GetScriptBehavior();
                     auto d = cast<IDamageTaker>(b);
                     if (d is null or d.Impenetrable())
                     {
                         visible = false;
                         break;
                     }
                 }
             }
             if (!visible)
                 continue;
             float d = 1.0;
             if (m_radius >  m_minRadius)
                 d = max(0.0, 1.0 - pow(hitDist / (m_radius - m_minRadius), m_distScaling));
             ApplyEffects(m_effects, owner, unit, upos, dir, intensity * d, husk, m_selfDmg, m_teamDmg, m_enemyDmg);
         }
         return true;
     }
GetFxName()
string Explode::GetFxName (vec2 pos) inline private
Definition at line 39 of file Explode.as.
References g_scene, m_fx, and m_tileFx.
Referenced by DoExplosion().
     {
         string fx = m_fx;
         if (m_tileFx != "")
         {
             array<Tileset@>@ tilesets = g_scene.FetchTilesets(pos);
             for (int i = tilesets.length() - 1; i >= 0; i--)
             {
                 SValue@ tsd = tilesets[i].GetData();
                 if (tsd is null)
                     continue;
                 SValue@ svExplodeFx = tsd.GetDictionaryEntry(m_tileFx);
                 if (svExplodeFx is null || svExplodeFx.GetType() != SValueType::String)
                     continue;
                 fx = svExplodeFx.GetString();
                 break;
             }
         }
         return fx;
     }
NeedNetParams()
bool Explode::NeedNetParams () inline private
Definition at line 31 of file Explode.as.
 { return true; }
NetDoAction()
bool Explode::NetDoAction (SValue@ param, Actor@ owner, vec2 pos, vec2 dir) inline private
Definition at line 134 of file Explode.as.
References DoExplosion().
     {
         return DoExplosion(owner, pos, dir, param.GetFloat(), true);
     }
SetWeaponInformation()
void Explode::SetWeaponInformation (uint weapon) inline private
Definition at line 26 of file Explode.as.
References m_effects, and PropagateWeaponInformation().
     {
         PropagateWeaponInformation(m_effects, weapon);
     }
Update()
void Explode::Update (int dt, int cooldown) inline private
Definition at line 149 of file Explode.as.
     {
     }
Member Data Documentation
m_distScaling
float Explode::m_distScaling private
Definition at line 8 of file Explode.as.
Referenced by DoExplosion(), and Explode().
m_effects
array<IEffect@> Explode::m_effects private
Definition at line 3 of file Explode.as.
Referenced by DoExplosion(), Explode(), and SetWeaponInformation().
m_enemyDmg
float Explode::m_enemyDmg private
Definition at line 11 of file Explode.as.
Referenced by DoExplosion(), and Explode().
m_fx
string Explode::m_fx private
Definition at line 4 of file Explode.as.
Referenced by Explode(), and GetFxName().
m_minRadius
int Explode::m_minRadius private
Definition at line 7 of file Explode.as.
Referenced by DoExplosion(), and Explode().
m_radius
int Explode::m_radius private
Definition at line 6 of file Explode.as.
Referenced by DoExplosion(), and Explode().
m_selfDmg
float Explode::m_selfDmg private
Definition at line 9 of file Explode.as.
Referenced by DoExplosion(), and Explode().
m_teamDmg
float Explode::m_teamDmg private
Definition at line 10 of file Explode.as.
Referenced by DoExplosion(), and Explode().
m_tileFx
string Explode::m_tileFx private
Definition at line 5 of file Explode.as.
Referenced by Explode(), and GetFxName().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actions/Explode.as