HoHDocs: Chest Class Reference
Chest Class Reference
Private Member Functions
Chest (UnitPtr unit, SValue &params)
void Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther)
void EndCollision (UnitPtr unit, Fixture@ fxSelf, Fixture@ fxOther)
UnitPtr GetUseUnit ()
bool CanUse (PlayerBase@ player)
void Use (PlayerBase@ player)
void NetUse (PlayerHusk@ player)
UsableIcon GetIcon (Player@ player)
int UsePriority (IUsable@ other)
Private Attributes
UnitPtr m_unit
int m_lock
LootDef m_lootDef
SoundEvent m_openSnd
Detailed Description
Definition at line 1 of file Chest.as.
Constructor & Destructor Documentation
Chest()
Chest::Chest (UnitPtr unit, SValue & params) inline private
Definition at line 8 of file Chest.as.
References LoadLootDef(), m_lock, m_lootDef, m_openSnd, m_unit, and unit.
     {
         m_unit = unit;
         m_lock = GetParamInt(unit, params, "lock");
         @m_lootDef = LoadLootDef(GetParamString(unit, params, "loot", false));
         @m_openSnd = Resources::GetSoundEvent(GetParamString(unit, params, "open-snd", false));
     }
Member Function Documentation
CanUse()
bool Chest::CanUse (PlayerBase@ player) inline private
Definition at line 41 of file Chest.as.
References m_lock, PlayerBase::m_record, and m_unit.
Referenced by GetIcon().
     {
         if (!m_unit.IsValid() || m_unit.IsDestroyed())
             return false;
         if (m_lock < 0)
             return true;
         if (cast<PlayerHusk>(player) !is null)
             return true;
         return player.m_record.keys[m_lock] > 0;
     }
Collide()
void Chest::Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther) inline private
Definition at line 16 of file Chest.as.
References Player::AddUsable(), and unit.
     {
         Player@ player = cast<Player>(unit.GetScriptBehavior());
         if (player is null)
             return;
         if (fxSelf.IsSensor())
             player.AddUsable(this);
     }
EndCollision()
void Chest::EndCollision (UnitPtr unit, Fixture@ fxSelf, Fixture@ fxOther) inline private
Definition at line 26 of file Chest.as.
References Player::RemoveUsable(), and unit.
     {
         Player@ player = cast<Player>(unit.GetScriptBehavior());
         if (player is null)
             return;
         if (fxSelf.IsSensor())
             player.RemoveUsable(this);
     }
GetIcon()
UsableIcon Chest::GetIcon (Player@ player) inline private
Definition at line 92 of file Chest.as.
References CanUse(), Cross, Generic, Key, and m_lock.
     {
         if (!CanUse(player))
             return UsableIcon::Cross;
         if (m_lock < 0)
             return UsableIcon::Generic;
         else
             return UsableIcon::Key;
     }
GetUseUnit()
UnitPtr Chest::GetUseUnit () inline private
Definition at line 36 of file Chest.as.
References m_unit.
     {
         return m_unit;
     }
NetUse()
void Chest::NetUse (PlayerHusk@ player) inline private
Definition at line 87 of file Chest.as.
References Use().
Referenced by Door::NetUse().
     {
         Use(player);
     }
Use()
void Chest::Use (PlayerBase@ player) inline private
Definition at line 55 of file Chest.as.
References Stats::Add(), AddFloatingText(), m_lock, m_lootDef, m_openSnd, PlayerBase::m_record, m_unit, Pickup, PlaySound3D(), and xy().
Referenced by NetUse().
     {
         if (m_unit.IsDestroyed() || !m_unit.IsValid())
             return;
         if (m_lock >= 0)
         {
             if (player.m_record.keys[m_lock] <= 0 && cast<PlayerHusk>(player) is null)
             {
                 AddFloatingText(FloatingTextType::Pickup, Resources::GetString(".hud.nokey"), player.m_unit.GetPosition());
                 print("No key!");
                 return;
             }
             player.m_record.keys[m_lock]--;
             Stats::Add("chest-used-" + m_lock, 1, player.m_record);
         }
         else
             Stats::Add("chest-used-wood", 1, player.m_record);
         if (Network::IsServer())
         {
             m_unit.Destroy();
             if (m_lootDef !is null)
                 m_lootDef.Spawn(xy(m_unit.GetPosition()));
         }
         Stats::Add("chests-opened", 1, player.m_record);
         PlaySound3D(m_openSnd, m_unit.GetPosition());
     }
UsePriority()
int Chest::UsePriority (IUsable@ other) inline private
Definition at line 103 of file Chest.as.
 { return 0; }
Member Data Documentation
m_lock
int Chest::m_lock private
Definition at line 4 of file Chest.as.
Referenced by CanUse(), Chest(), GetIcon(), Door::Use(), and Use().
m_lootDef
LootDef Chest::m_lootDef private
Definition at line 5 of file Chest.as.
Referenced by Chest(), and Use().
m_openSnd
SoundEvent Chest::m_openSnd private
Definition at line 6 of file Chest.as.
Referenced by Chest(), Door::Use(), and Use().
m_unit
UnitPtr Chest::m_unit private
Definition at line 3 of file Chest.as.
Referenced by CanUse(), Chest(), GetUseUnit(), Door::Use(), and Use().
The documentation for this class was generated from the following file:
scripts/Behaviors/Items/Chest.as