HoHDocs: WorldScript::SoundEnvironmentArea Class Reference
WorldScript::SoundEnvironmentArea Class Reference
Private Member Functions
void Initialize ()
void OnEnter (UnitPtr unit, vec2 pos, vec2 normal)
void OnExit (UnitPtr unit)
Private Attributes
array< CollisionArea@> Areas
float ReverbTime
Detailed Description
Definition at line 4 of file SoundEnvironmentArea.as.
Member Function Documentation
Initialize()
void WorldScript::SoundEnvironmentArea::Initialize () inline private
Definition at line 13 of file SoundEnvironmentArea.as.
References Areas.
         {
             for (uint i = 0; i < Areas.length(); i++)
             {
                 Areas[i].AddOnEnter(this, "OnEnter");
                 Areas[i].AddOnExit(this, "OnExit");
             }
         }
OnEnter()
void WorldScript::SoundEnvironmentArea::OnEnter (UnitPtr unit, vec2 pos, vec2 normal) inline private
Definition at line 22 of file SoundEnvironmentArea.as.
References GetLocalPlayer(), ReverbTime, EnvironmentSoundSystem::SetEnvironment(), and unit.
         {
             auto plr = GetLocalPlayer();
             if (plr !is null && plr.m_unit == unit)
                 EnvironmentSoundSystem::SetEnvironment(ReverbTime);
         }
OnExit()
void WorldScript::SoundEnvironmentArea::OnExit (UnitPtr unit) inline private
Definition at line 29 of file SoundEnvironmentArea.as.
References EnvironmentSoundSystem::ClearEnvironment(), GetLocalPlayer(), and unit.
         {
             auto plr = GetLocalPlayer();
             if (plr !is null && plr.m_unit == unit)
                 EnvironmentSoundSystem::ClearEnvironment();
         }
Member Data Documentation
Areas
array<CollisionArea@> WorldScript::SoundEnvironmentArea::Areas private
Definition at line 7 of file SoundEnvironmentArea.as.
Referenced by Initialize().
ReverbTime
float WorldScript::SoundEnvironmentArea::ReverbTime private
Definition at line 10 of file SoundEnvironmentArea.as.
Referenced by OnEnter().
The documentation for this class was generated from the following file:
scripts/WorldScript/SoundEnvironmentArea.as