HoHDocs: WorldScript::HideAllSpeechBubbles Class Reference
WorldScript::HideAllSpeechBubbles Class Reference
Private Member Functions
SValue ServerExecute ()
void ClientExecute (SValue@ val)
Private Attributes
UnitFeed ForPlayer
Detailed Description
Definition at line 4 of file HideAllSpeechBubbles.as.
Member Function Documentation
ClientExecute()
void WorldScript::HideAllSpeechBubbles::ClientExecute (SValue@ val) inline private
Definition at line 15 of file HideAllSpeechBubbles.as.
References ForPlayer, GetHUD(), SpeechBubbleManager::HideAll(), HUD::m_speechBubbles, and unit.
Referenced by ServerExecute().
         {
             UnitPtr unit = ForPlayer.FetchFirst();
             if (unit.IsValid() && cast<Player>(unit.GetScriptBehavior()) is null)
                 return;
             GetHUD().m_speechBubbles.HideAll();
         }
ServerExecute()
SValue WorldScript::HideAllSpeechBubbles::ServerExecute () inline private
Definition at line 9 of file HideAllSpeechBubbles.as.
References ClientExecute().
         {
             ClientExecute(null);
             return null;
         }
Member Data Documentation
ForPlayer
UnitFeed WorldScript::HideAllSpeechBubbles::ForPlayer private
Definition at line 7 of file HideAllSpeechBubbles.as.
Referenced by ClientExecute().
The documentation for this class was generated from the following file:
scripts/WorldScript/HideAllSpeechBubbles.as