HoHDocs: Upgrades::Shop Class Reference
Upgrades::Shop Class Reference
Private Member Functions
Shop (SValue &params)
void OnOpenMenu (int shopLevel, PlayerRecord@ record)
Upgrade FindUpgrade (string id, PlayerRecord@ record)
ShopIterator Iterate (int shopLevel, PlayerRecord@ record)
Private Attributes
string m_id
string m_name
bool m_starsVisible
Detailed Description
Definition at line 3 of file Shop.as.
Constructor & Destructor Documentation
Shop()
Upgrades::Shop::Shop (SValue & params) inline private
Definition at line 9 of file Shop.as.
References m_id, m_name, and m_starsVisible.
         {
             m_id = GetParamString(UnitPtr(), params, "id");
             m_name = GetParamString(UnitPtr(), params, "name", false);
             m_starsVisible = GetParamBool(UnitPtr(), params, "stars-visible", false, true);
         }
Member Function Documentation
FindUpgrade()
Upgrade Upgrades::Shop::FindUpgrade (string id, PlayerRecord@ record) inline private
Definition at line 20 of file Shop.as.
References Iterate().
         {
             for (auto iter = Iterate(5, record); !iter.AtEnd(); iter.Next())
             {
                 auto upgrade = iter.Current();
                 if (upgrade.m_id == id)
                     return upgrade;
             }
             return null;
         }
Iterate()
ShopIterator Upgrades::Shop::Iterate (int shopLevel, PlayerRecord@ record) inline private
Definition at line 31 of file Shop.as.
References Upgrades::ShopIterator().
Referenced by FindUpgrade(), and UpgradeShopMenuContent::ReloadList().
         {
             return ShopIterator(this, shopLevel, record);
         }
OnOpenMenu()
void Upgrades::Shop::OnOpenMenu (int shopLevel, PlayerRecord@ record) inline private
Definition at line 16 of file Shop.as.
Referenced by UpgradeShopMenuContent::ReloadList().
         {
         }
Member Data Documentation
m_id
string Upgrades::Shop::m_id private
Definition at line 5 of file Shop.as.
Referenced by Shop().
m_name
string Upgrades::Shop::m_name private
Definition at line 6 of file Shop.as.
Referenced by UpgradeShopMenuContent::GetTitle(), and Shop().
m_starsVisible
bool Upgrades::Shop::m_starsVisible private
Definition at line 7 of file Shop.as.
Referenced by Shop().
The documentation for this class was generated from the following file:
scripts/Upgrades/Shop.as