HoHDocs: Skills::DropEffect Class Reference
Skills::DropEffect Class Reference
Private Member Functions
DropEffect (UnitPtr unit, SValue &params)
void Initialize (Actor@ owner, ScriptSprite@ icon, uint id) override
TargetingMode GetTargetingMode (int &out size) override
void DoActivate (SValueBuilder@ builder, vec2 target) override
void NetDoActivate (SValue@ param, vec2 target) override
void SpawnDropEffect (vec2 dir)
void OnDropped (UnitPtr unit)
bool DoExplosion (Actor@ owner, vec2 pos, bool husk)
Private Attributes
UnitScene m_dropFx
UnitScene m_droppedFx
array< IEffect@> m_effects
int m_radius
float m_selfDmg
float m_teamDmg
float m_enemyDmg
int m_dropDist
vec2 m_offset
Detailed Description
Definition at line 3 of file DropEffect.as.
Constructor & Destructor Documentation
DropEffect()
Skills::DropEffect::DropEffect (UnitPtr unit, SValue & params) inline private
Definition at line 19 of file DropEffect.as.
References Fountain::GetEffect(), LoadEffects(), m_dropDist, m_dropFx, m_droppedFx, m_effects, m_enemyDmg, m_offset, m_radius, m_selfDmg, m_teamDmg, and unit.
         {
             super(unit, params);
             @m_effects = LoadEffects(unit, params);
             m_radius = GetParamInt(unit, params, "radius", true);
             m_selfDmg = GetParamFloat(unit, params, "self-dmg", false, 0);
             m_teamDmg = GetParamFloat(unit, params, "team-dmg", false, 0);
             m_enemyDmg = GetParamFloat(unit, params, "enemy-dmg", false, 1);
             @m_dropFx = Resources::GetEffect(GetParamString(unit, params, "drop-fx", false));
             @m_droppedFx = Resources::GetEffect(GetParamString(unit, params, "dropped-fx", false));
             m_dropDist = GetParamInt(unit, params, "drop-dist", false);
             m_offset = GetParamVec2(unit, params, "offset", false);
         }
Member Function Documentation
DoActivate()
void Skills::DropEffect::DoActivate (SValueBuilder@ builder, vec2 target) inline override private
Definition at line 48 of file DropEffect.as.
References SpawnDropEffect().
         {
             SpawnDropEffect(target);
         }
DoExplosion()
bool Skills::DropEffect::DoExplosion (Actor@ owner, vec2 pos, bool husk) inline private
Definition at line 84 of file DropEffect.as.
References ApplyEffects(), FilterAction(), g_scene, m_droppedFx, m_effects, m_enemyDmg, Skills::m_owner, m_radius, m_selfDmg, m_teamDmg, num, PlayEffect(), unit, and xy().
Referenced by OnDropped().
         {
             PlayEffect(m_droppedFx, pos);
             auto results = g_scene.QueryCircle(pos, m_radius, ~0, RaycastType::Shot, true);
             int num = 0;
             for (uint i = 0; i < results.length(); i++)
             {
                 auto a = cast<Actor>(results[i].GetScriptBehavior());
                 if (a is null)
                     continue;
                 if (FilterAction(a, m_owner, m_selfDmg, m_teamDmg, m_enemyDmg) > 0)
                     num++;
             }
             float intensity = (num > 0) ? (1.0f / num) : 1.0f;
             for (uint i = 0; i < results.length(); i++)
             {
                 UnitPtr unit = results[i];
                 vec2 upos = xy(unit.GetPosition());
                 ApplyEffects(m_effects, m_owner, unit, upos, vec2(), intensity, husk, m_selfDmg, m_teamDmg, m_enemyDmg);
             }
             return true;
         }
GetTargetingMode()
TargetingMode Skills::DropEffect::GetTargetingMode (int &out size) inline override private
Definition at line 42 of file DropEffect.as.
References Skills::Direction.
         {
             size = 0;
             return TargetingMode::Direction;
         }
Initialize()
void Skills::DropEffect::Initialize (Actor@ owner, ScriptSprite@ icon, uint id) inline override private
Definition at line 36 of file DropEffect.as.
References icon, Initialize(), m_effects, and PropagateWeaponInformation().
         {
             ActiveSkill::Initialize(owner, icon, id);
             PropagateWeaponInformation(m_effects, id + 1);
         }
NetDoActivate()
void Skills::DropEffect::NetDoActivate (SValue@ param, vec2 target) inline override private
Definition at line 53 of file DropEffect.as.
References SpawnDropEffect().
         {
             SpawnDropEffect(target);
         }
OnDropped()
void Skills::DropEffect::OnDropped (UnitPtr unit) inline private
Definition at line 79 of file DropEffect.as.
References DoExplosion(), Skills::m_owner, unit, and xy().
         {
             DoExplosion(m_owner, xy(unit.GetPosition()), m_owner.IsHusk());
         }
SpawnDropEffect()
void Skills::DropEffect::SpawnDropEffect (vec2 dir) inline private
Definition at line 58 of file DropEffect.as.
References g_scene, Height, m_dropDist, m_dropFx, Skills::m_owner, Skills::ActiveSkill::PlaySkillEffect(), xy(), and xyz().
Referenced by DoActivate(), and NetDoActivate().
         {
             PlaySkillEffect(dir);
             vec2 pos = xy(m_owner.m_unit.GetPosition()) + dir * m_dropDist;
             if (m_dropFx is null)
                 return;
             float Height = 100.0;
             float InitialFallSpeed = 0.2;
             float MaxFallSpeed = 0.6;
             float FallSpeedMultiplier = 1.15;
             auto prod = Resources::GetUnitProducer("system/drop_spawn.unit");
             UnitPtr u = prod.Produce(g_scene, xyz(pos));
             u.SetUnitScene(m_dropFx, true);
             auto dropper = cast<DropSpawnBehavior>(u.GetScriptBehavior());
             dropper.Initialize(this, null, InitialFallSpeed, MaxFallSpeed, FallSpeedMultiplier, Height);
         }
Member Data Documentation
m_dropDist
int Skills::DropEffect::m_dropDist private
Definition at line 15 of file DropEffect.as.
Referenced by DropEffect(), and SpawnDropEffect().
m_dropFx
UnitScene Skills::DropEffect::m_dropFx private
Definition at line 5 of file DropEffect.as.
Referenced by DropEffect(), and SpawnDropEffect().
m_droppedFx
UnitScene Skills::DropEffect::m_droppedFx private
Definition at line 6 of file DropEffect.as.
Referenced by DoExplosion(), and DropEffect().
m_effects
array<IEffect@> Skills::DropEffect::m_effects private
Definition at line 8 of file DropEffect.as.
Referenced by DoExplosion(), DropEffect(), and Initialize().
m_enemyDmg
float Skills::DropEffect::m_enemyDmg private
Definition at line 13 of file DropEffect.as.
Referenced by DoExplosion(), and DropEffect().
m_offset
vec2 Skills::DropEffect::m_offset private
Definition at line 16 of file DropEffect.as.
Referenced by DropEffect().
m_radius
int Skills::DropEffect::m_radius private
Definition at line 10 of file DropEffect.as.
Referenced by DoExplosion(), and DropEffect().
m_selfDmg
float Skills::DropEffect::m_selfDmg private
Definition at line 11 of file DropEffect.as.
Referenced by DoExplosion(), and DropEffect().
m_teamDmg
float Skills::DropEffect::m_teamDmg private
Definition at line 12 of file DropEffect.as.
Referenced by DoExplosion(), and DropEffect().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Skills/DropEffect.as