HoHDocs: CompositeActorBurstSkill Class Reference
CompositeActorBurstSkill Class Reference
Private Member Functions
CompositeActorBurstSkill (UnitPtr unit, SValue &params)
void NetUseSkill (int stage, SValue@ param) override
Actor GetTarget ()
void NewBurstShot ()
void Update (int dt, bool isCasting) override
bool IsCasting () override
Private Attributes
int m_numBursts
int m_burstC
Detailed Description
Definition at line 1 of file CompositeActorBurstSkill.as.
Constructor & Destructor Documentation
CompositeActorBurstSkill()
CompositeActorBurstSkill::CompositeActorBurstSkill (UnitPtr unit, SValue & params) inline private
Definition at line 6 of file CompositeActorBurstSkill.as.
References m_burstC, m_numBursts, and unit.
     {
         super(unit, params);
         m_numBursts = GetParamInt(unit, params, "burst", true, 1);
         m_burstC = 0;
     }
Member Function Documentation
GetTarget()
Actor CompositeActorBurstSkill::GetTarget () inline private
Definition at line 29 of file CompositeActorBurstSkill.as.
References CompositeActorSkill::m_behavior.
Referenced by Update().
     {
         return m_behavior.m_target;
     }
IsCasting()
bool CompositeActorBurstSkill::IsCasting () inline override private
Definition at line 154 of file CompositeActorBurstSkill.as.
References m_burstC, and CompositeActorSkill::m_castC.
Referenced by Update().
     {
         return m_castC > 0 || m_burstC > 0;
     }
NetUseSkill()
void CompositeActorBurstSkill::NetUseSkill (int stage, SValue@ param) inline override private
Definition at line 15 of file CompositeActorBurstSkill.as.
References m_burstC, m_numBursts, and CompositeActorSkill::NetUseSkill().
Referenced by BossScatterBurstSkill::NetUseSkill().
     {
         if (stage == 2)
         {
             stage = 0;
             m_burstC = m_numBursts;
         }
         if (stage == 0)
             m_burstC--;
         CompositeActorSkill::NetUseSkill(stage, param);
     }
NewBurstShot()
void CompositeActorBurstSkill::NewBurstShot () inline private
Definition at line 34 of file CompositeActorBurstSkill.as.
Referenced by Update().
 {}
Update()
void CompositeActorBurstSkill::Update (int dt, bool isCasting) inline override private
Definition at line 36 of file CompositeActorBurstSkill.as.
References CompositeActorSkill::CalcAimDir(), CompositeActorSkill::CanSee(), DoActions(), FetchOffsetPos(), GetTarget(), CompositeActorSkill::IsAvailable(), IsCasting(), CompositeActorSkill::m_actions, CompositeActorSkill::m_anims, CompositeActorSkill::m_behavior, m_burstC, CompositeActorSkill::m_castC, CompositeActorSkill::m_castPoint, CompositeActorSkill::m_castPointC, CompositeActorSkill::m_charges, CompositeActorSkill::m_cooldown, CompositeActorSkill::m_cooldownC, CompositeActorSkill::m_currAnim, CompositeActorSkill::m_goodAim, CompositeActorSkill::m_id, CompositeActorSkill::m_mustSee, m_numBursts, CompositeActorSkill::m_offset, CompositeActorSkill::m_skillAimDir, CompositeActorSkill::m_sound, CompositeActorSkill::m_startActions, CompositeActorSkill::m_startSound, CompositeActorSkill::m_unit, UnitHandler::NetSendUnitUseSkill(), NewBurstShot(), PlaySound3D(), and xy().
     {
         if (isCasting && IsCasting())
             isCasting = false;
         if (m_castC > 0)
         {
             vec2 dir = normalize(xy(GetTarget().m_unit.GetPosition() - m_unit.GetPosition()));
             m_behavior.m_movement.m_dir = atan(dir.y, dir.x);
             auto body = m_unit.GetPhysicsBody();
             if (body !is null)
                 body.SetLinearVelocity(0, 0);
             m_castC -= dt;
             if (Network::IsServer() && m_castC <= 0 && m_burstC > 0)
             {
                 m_burstC--;
                 if (m_burstC <= 0)
                 {
                     if (m_charges > 0)
                         m_charges--;
                     m_cooldownC = m_cooldown;
                 }
                 else
                     m_cooldownC = 0;
             }
         }
         if (m_cooldownC > 0)
         {
             m_cooldownC -= dt;
             return;
         }
         if (Network::IsServer())
         {
             if (m_cooldownC <= 0 && !isCasting && m_castC <= 0)
             {
                 bool initial = false;
                 if (m_burstC <= 0)
                 {
                     if (IsAvailable() && (!m_mustSee || CanSee(GetTarget().m_unit)))
                     {
                         m_burstC = m_numBursts;
                         initial = true;
                     }
                     else
                     {
                         m_cooldownC = m_cooldown;
                         return;
                     }
                 }
                 if (!initial && !IsAvailable())
                 {
                     m_burstC = 0;
                     return;
                 }
                 NewBurstShot();
                 vec2 dir = xy(GetTarget().m_unit.GetPosition() - m_unit.GetPosition());
                 if (dir.x != 0 || dir.y != 0)
                     m_behavior.m_movement.m_dir = atan(dir.y, dir.x);
                 m_cooldownC = 0;
                 m_castPointC = m_castPoint;
                 PlaySound3D(m_startSound, m_unit.GetPosition());
                 m_castC = m_behavior.SetUnitScene(m_anims[m_currAnim].GetSceneName(m_behavior.m_movement.m_dir), true);
                 m_currAnim = (m_currAnim + 1) % m_anims.get_length();
                 if (m_startActions.length() > 0)
                 {
                     CalcAimDir();
                     vec2 pos = FetchOffsetPos(m_unit, m_offset);
                     SValue@ param = DoActions(m_startActions, m_behavior, GetTarget(), pos, m_skillAimDir);
                     UnitHandler::NetSendUnitUseSkill(m_unit, m_id, initial ? 2 : 0, param);
                 }
                 else
                 {
                     UnitHandler::NetSendUnitUseSkill(m_unit, m_id, initial ? 2 : 0);
                     if (!m_goodAim)
                         CalcAimDir();
                 }
             }
             if (m_castPointC > 0)
             {
                 m_castPointC -= dt;
                 if (m_castPointC <= 0)
                 {
                     //if (IsAvailable())
                     {
                         PlaySound3D(m_sound, m_unit.GetPosition());
                         if (m_goodAim)
                             CalcAimDir();
                         vec2 pos = FetchOffsetPos(m_unit, m_offset);
                         SValue@ param = DoActions(m_actions, m_behavior, GetTarget(), pos, m_skillAimDir);
                         UnitHandler::NetSendUnitUseSkill(m_unit, m_id, 1, param);
                     }
                 }
             }
         }
         for (uint i = 0; i < m_actions.length(); i++)
             m_actions[i].Update(dt, m_cooldownC);
     }
Member Data Documentation
m_burstC
int CompositeActorBurstSkill::m_burstC private
Definition at line 4 of file CompositeActorBurstSkill.as.
Referenced by CompositeActorBurstSkill(), IsCasting(), NetUseSkill(), and Update().
m_numBursts
int CompositeActorBurstSkill::m_numBursts private
Definition at line 3 of file CompositeActorBurstSkill.as.
Referenced by CompositeActorBurstSkill(), NetUseSkill(), and Update().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Enemies/Skills/CompositeActorBurstSkill.as