HoHDocs: WorldScript::SpawnUnitAsLoot Class Reference
WorldScript::SpawnUnitAsLoot Class Reference
Private Member Functions
void Initialize ()
SValue ServerExecute ()
Private Attributes
UnitFeed SpawnOn
UnitSource LastSpawned
UnitSource AllSpawned
Detailed Description
Definition at line 4 of file SpawnUnitAsLoot.as.
Member Function Documentation
Initialize()
void WorldScript::SpawnUnitAsLoot::Initialize () inline private
Definition at line 13 of file SpawnUnitAsLoot.as.
         {
             Initialize(UnitPtr(), null);
         }
ServerExecute()
SValue WorldScript::SpawnUnitAsLoot::ServerExecute () inline private
Definition at line 18 of file SpawnUnitAsLoot.as.
References AllSpawned, SpawnUnitBase::CalcJitter(), LastSpawned, SpawnOn, SpawnUnitBase::SpawnUnit(), and xy().
         {
             LastSpawned.Clear();
             auto units = SpawnOn.FetchAll();
             for (uint i = 0; i < units.length(); i++)
             {
                 vec2 pos = xy(units[i].GetPosition());
                 UnitPtr u = SpawnUnit(pos + CalcJitter(), null, 1.0);
                 if (u.IsValid())
                 {
                     LastSpawned.Replace(u);
                     AllSpawned.Add(u);
                 }
             }
             return null;
         }
Member Data Documentation
AllSpawned
UnitSource WorldScript::SpawnUnitAsLoot::AllSpawned private
Definition at line 10 of file SpawnUnitAsLoot.as.
Referenced by ServerExecute().
LastSpawned
UnitSource WorldScript::SpawnUnitAsLoot::LastSpawned private
Definition at line 9 of file SpawnUnitAsLoot.as.
Referenced by ServerExecute().
SpawnOn
UnitFeed WorldScript::SpawnUnitAsLoot::SpawnOn private
Definition at line 7 of file SpawnUnitAsLoot.as.
Referenced by ServerExecute().
The documentation for this class was generated from the following file:
scripts/WorldScript/SpawnUnitAsLoot.as