HoHDocs: SpriteBarWidget Class Reference
SpriteBarWidget Class Reference
Private Member Functions
SpriteBarWidget ()
void SetValue (float v)
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void Update (int dt) override
void DoDraw (SpriteBatch &sb, vec2 pos) override
Private Attributes
Sprite m_sprite
Sprite m_spriteHi
Sprite m_spriteExtra
vec4 m_color
float m_value
float m_valueExtra
float m_valuePrev
int m_timePrev
Detailed Description
Definition at line 1 of file SpriteBarWidget.as.
Constructor & Destructor Documentation
SpriteBarWidget()
SpriteBarWidget::SpriteBarWidget () inline private
Definition at line 14 of file SpriteBarWidget.as.
References Widget::m_height, m_sprite, and Widget::m_width.
Referenced by Clone().
     {
         super();
         @m_sprite = null;
         m_width = 0;
         m_height = 0;
     }
Member Function Documentation
Clone()
Widget SpriteBarWidget::Clone () inline override private
Definition at line 37 of file SpriteBarWidget.as.
References Widget::CloneInto(), and SpriteBarWidget().
     {
         auto w = SpriteBarWidget();
         CloneInto(w);
         return w;
     }
DoDraw()
void SpriteBarWidget::DoDraw (SpriteBatch & sb, vec2 pos) inline override private
Definition at line 74 of file SpriteBarWidget.as.
     {
         if (m_valueExtra > 0 && m_spriteExtra !is null)
         {
             auto tex = m_spriteExtra.GetTexture2D();
             auto frame = m_spriteExtra.GetFrame(g_menuTime);
             int vOffset = m_height - int(round(m_height * m_value));
             vec4 p(pos.x, pos.y + vOffset, m_width, m_height - vOffset);
             frame.y += vOffset;
             frame.w -= vOffset;
             sb.DrawSprite(tex, p, frame, m_color);
         }
         if (m_timePrev > 0 && m_spriteHi !is null)
         {
             auto tex = m_spriteHi.GetTexture2D();
             auto frame = m_spriteHi.GetFrame(g_menuTime);
             int vOffset = m_height - int(round(m_height * m_value));
             vec4 p(pos.x, pos.y + vOffset, m_width, m_height - vOffset);
             frame.y += vOffset;
             frame.w -= vOffset;
             sb.DrawSprite(tex, p, frame, m_color);
         }
         if (m_sprite !is null)
         {
             auto tex = m_sprite.GetTexture2D();
             auto frame = m_sprite.GetFrame(g_menuTime);
             float showValue = m_value;
             if (m_timePrev > 0)
                 showValue = m_valuePrev;
             if (m_valueExtra > 0 && showValue > m_valueExtra)
                 showValue = m_valueExtra;
             int vOffset = m_height - int(round(m_height * showValue));
             vec4 p(pos.x, pos.y + vOffset, m_width, m_height - vOffset);
             frame.y += vOffset;
             frame.w -= vOffset;
             sb.DrawSprite(tex, p, frame, m_color);
         }
     }
Load()
void SpriteBarWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 44 of file SpriteBarWidget.as.
References Widget::Load(), m_color, Widget::m_height, m_sprite, m_spriteExtra, m_spriteHi, and Widget::m_width.
     {
         string spriteName = ctx.GetString("src", false);
         if (spriteName != "")
         {
             @m_sprite = ctx.GetGUIDef().GetSprite(spriteName);
             m_width = m_sprite.GetWidth();
             m_height = m_sprite.GetHeight();
         }
         string spriteHiName = ctx.GetString("src-hi", false);
         if (spriteHiName != "")
             @m_spriteHi = ctx.GetGUIDef().GetSprite(spriteHiName);
         string spriteExtraName = ctx.GetString("src-extra", false);
         if (spriteExtraName != "")
             @m_spriteExtra = ctx.GetGUIDef().GetSprite(spriteExtraName);
         m_color = ctx.GetColorRGBA("color", false, vec4(1, 1, 1, 1));
         Widget::Load(ctx);
     }
SetValue()
void SpriteBarWidget::SetValue (float v) inline private
Definition at line 23 of file SpriteBarWidget.as.
References clamp(), m_spriteHi, m_timePrev, m_value, and m_valuePrev.
Referenced by HUD::Update().
     {
         v = clamp(v, 0.0f, 1.0f);
         if (v > m_value && (v - m_value) > 0.1f && m_spriteHi !is null)
         {
             if (m_timePrev <= 0)
                 m_valuePrev = m_value;
             m_timePrev = 1000;
         }
         m_value = v;
     }
Update()
void SpriteBarWidget::Update (int dt) inline override private
Definition at line 66 of file SpriteBarWidget.as.
References m_timePrev, and Widget::Update().
     {
         if (m_timePrev > 0)
             m_timePrev -= dt;
         Widget::Update(dt);
     }
Member Data Documentation
m_color
vec4 SpriteBarWidget::m_color private
Definition at line 7 of file SpriteBarWidget.as.
Referenced by Load().
m_sprite
Sprite SpriteBarWidget::m_sprite private
Definition at line 3 of file SpriteBarWidget.as.
Referenced by Load(), and SpriteBarWidget().
m_spriteExtra
Sprite SpriteBarWidget::m_spriteExtra private
Definition at line 5 of file SpriteBarWidget.as.
Referenced by Load().
m_spriteHi
Sprite SpriteBarWidget::m_spriteHi private
Definition at line 4 of file SpriteBarWidget.as.
Referenced by Load(), and SetValue().
m_timePrev
int SpriteBarWidget::m_timePrev private
Definition at line 12 of file SpriteBarWidget.as.
Referenced by SetValue(), and Update().
m_value
float SpriteBarWidget::m_value private
Definition at line 8 of file SpriteBarWidget.as.
Referenced by SetValue().
m_valueExtra
float SpriteBarWidget::m_valueExtra private
Definition at line 9 of file SpriteBarWidget.as.
Referenced by HUD::Update().
m_valuePrev
float SpriteBarWidget::m_valuePrev private
Definition at line 11 of file SpriteBarWidget.as.
Referenced by SetValue().
The documentation for this class was generated from the following file:
scripts/GUI/HUD/SpriteBarWidget.as