HoHDocs: TownhallMenuContent Class Reference
TownhallMenuContent Class Reference
Private Member Functions
TownhallMenuContent (ShopMenu@ shopMenu)
void OnShow () override
string GetTitle () override
void AddButton (Widget@ wList, Upgrades::BuildingUpgrade@ upgrade, Upgrades::BuildingUpgradeStep@ step, Upgrades::BuildingUpgradeStep@ stepAbove, bool addSpacing)
void ReloadList () override
bool BuyItem (Upgrades::Upgrade@ upgrade, Upgrades::UpgradeStep@ step) override
string GetGuiFilename () override
Private Attributes
Widget m_wSpecialSeparator
Widget m_wRowList
Widget m_wTemplateRow
Widget m_wTemplateRowUnavailable
Widget m_wTemplateBuilding
Widget m_wTemplateBuildingOwned
Widget m_wTemplateBuildingUnavailable
Widget m_wTemplateBuildingEmpty
Widget m_wTemplateBuildingUnknown
Sprite m_spriteOre
Upgrades::UpgradeShop m_shop
array< Upgrades::BuildingUpgradeStep@> m_tiersTownhall
array< array< Upgrades::BuildingUpgradeStep@> > m_tiers
int m_numTiers = 5
int m_numUpgrades = 10
Detailed Description
Definition at line 1 of file TownhallShopMenu.as.
Constructor & Destructor Documentation
TownhallMenuContent()
TownhallMenuContent::TownhallMenuContent (ShopMenu@ shopMenu) inline private
Definition at line 24 of file TownhallShopMenu.as.
References Upgrades::GetShop(), m_numTiers, m_shop, m_tiers, m_tiersTownhall, and Upgrades::UpgradeShop::m_upgrades.
     {
         super(shopMenu);
         @m_shop = cast<Upgrades::UpgradeShop>(Upgrades::GetShop("townhall"));
         for (int i = 0; i < m_numTiers; i++)
             m_tiers.insertLast(array<Upgrades::BuildingUpgradeStep@>());
         for (uint i = 0; i < m_shop.m_upgrades.length(); i++)
         {
             auto upgrade = m_shop.m_upgrades[i];
             int stepLevel = 1;
             for (int j = 0; j < m_numTiers; j++)
             {
                 auto step = cast<Upgrades::BuildingUpgradeStep>(upgrade.GetStep(stepLevel));
                 if (upgrade.m_id == "townhall")
                 {
                     m_tiersTownhall.insertLast(step);
                     stepLevel++;
                 }
                 else
                 {
                     if (step !is null && j + 1 >= step.m_restrictShopLevelMin)
                     {
                         m_tiers[j].insertLast(step);
                         stepLevel++;
                     }
                     else
                         m_tiers[j].insertLast(null);
                 }
             }
         }
         /*
         print("Building upgrades: " + m_tiers.length());
         for (uint i = 0; i < m_tiers.length(); i++)
         {
             print("  " + m_tiers[i].length() + " steps");
             for (uint j = 0; j < m_tiers[i].length(); j++)
                 print("    " + j + ": " + (m_tiers[i][j] is null ? "null" : "OK"));
         }
         */
     }
Member Function Documentation
AddButton()
void TownhallMenuContent::AddButton (Widget@ wList, Upgrades::BuildingUpgrade@ upgrade, Upgrades::BuildingUpgradeStep@ step, Upgrades::BuildingUpgradeStep@ stepAbove, bool addSpacing) inline private
Definition at line 95 of file TownhallShopMenu.as.
References Widget::AddChild(), Widget::Clone(), g_flags, g_gameMode, TownRecord::GetBuilding(), GetLocalPlayerRecord(), Upgrades::BuildingUpgradeStep::IsOwned(), ShopMenu::m_currentShopLevel, ShopMenuContent::m_shopMenu, m_spriteOre, TownBuilding::m_town, m_wTemplateBuilding, m_wTemplateBuildingEmpty, m_wTemplateBuildingOwned, m_wTemplateBuildingUnavailable, m_wTemplateBuildingUnknown, and Widget::SetID().
Referenced by ReloadList().
     {
         auto record = GetLocalPlayerRecord();
         auto gm = cast<Town>(g_gameMode);
         string tooltipTitle;
         string tooltipSub;
         string tooltipText;
         TownBuilding@ building = null;
         if (step !is null && upgrade !is null)
         {
             @building = gm.m_town.GetBuilding(upgrade.m_id);
             tooltipTitle = step.GetTooltipTitle();
             tooltipSub = ("" + step.m_costOre);
             tooltipText = step.GetTooltipDescription();
         }
         vec2 offset;
         if (addSpacing)
             offset.x = 6;
         if (step is null || upgrade is null)
         {
             // There's no step
             auto wNewButton = m_wTemplateBuildingEmpty.Clone();
             wNewButton.SetID("");
             wNewButton.m_visible = true;
             wNewButton.m_offset = offset;
             wList.AddChild(wNewButton);
         }
         else if (step.m_restrictFlag != "" && !g_flags.IsSet(step.m_restrictFlag))
         {
             // Step is not unlocked yet
             auto wNewButton = m_wTemplateBuildingUnknown.Clone();
             wNewButton.SetID("");
             wNewButton.m_visible = true;
             wNewButton.m_offset = offset;
             wList.AddChild(wNewButton);
         }
         else if (step.IsOwned(record))
         {
             // Step is owned
             auto wNewButton = m_wTemplateBuildingOwned.Clone();
             wNewButton.SetID("");
             wNewButton.m_visible = true;
             wNewButton.m_offset = offset;
             wNewButton.m_tooltipTitle = tooltipTitle;
             wNewButton.m_tooltipText = tooltipText;
             auto wIcon = cast<SpriteWidget>(wNewButton.GetWidgetById("icon"));
             if (wIcon !is null)
                 wIcon.SetSprite(step.GetSprite());
             wList.AddChild(wNewButton);
         }
         else if (m_shopMenu.m_currentShopLevel < step.m_restrictShopLevelMin || (stepAbove !is null && !stepAbove.IsOwned(record)))
         {
             // Shop level is not high enough for this step or the step above is not owned
             auto wNewButton = m_wTemplateBuildingUnavailable.Clone();
             wNewButton.SetID("");
             wNewButton.m_visible = true;
             wNewButton.m_offset = offset;
             wNewButton.m_tooltipTitle = tooltipTitle;
             wNewButton.AddTooltipSub(m_spriteOre, tooltipSub);
             wNewButton.m_tooltipText = tooltipText;
             auto wIcon = cast<SpriteWidget>(wNewButton.GetWidgetById("icon"));
             if (wIcon !is null)
             {
                 wIcon.m_colorize = true;
                 wIcon.SetSprite(step.GetSprite());
             }
             wList.AddChild(wNewButton);
         }
         else if (m_shopMenu.m_currentShopLevel >= step.m_restrictShopLevelMin)
         {
             // Shop level is high enough to buy it
             auto wNewButton = m_wTemplateBuilding.Clone();
             wNewButton.SetID("");
             wNewButton.m_visible = true;
             wNewButton.m_offset = offset;
             auto wButton = cast<UpgradeShopButtonWidget>(wNewButton.GetWidgetById("button"));
             wButton.Set(this, upgrade, step);
             wButton.m_tooltipTitle = tooltipTitle;
             wButton.AddTooltipSub(m_spriteOre, tooltipSub);
             wButton.m_tooltipText = tooltipText;
             if (!Network::IsServer())
                 wButton.m_enabled = false;
             wList.AddChild(wNewButton);
         }
     }
BuyItem()
bool TownhallMenuContent::BuyItem (Upgrades::Upgrade@ upgrade, Upgrades::UpgradeStep@ step) inline override private
Definition at line 273 of file TownhallShopMenu.as.
References Stats::Add(), ShopMenuContent::BuyItem(), and GetLocalPlayerRecord().
     {
         if (!ShopMenuContent::BuyItem(upgrade, step))
             return false;
         Stats::Add("buildings-purchased", 1, GetLocalPlayerRecord());
         return true;
     }
GetGuiFilename()
string TownhallMenuContent::GetGuiFilename () inline override private
Definition at line 282 of file TownhallShopMenu.as.
     {
         return "gui/shop/townhall.gui";
     }
GetTitle()
string TownhallMenuContent::GetTitle () inline override private
Definition at line 90 of file TownhallShopMenu.as.
     {
         return Resources::GetString(".shop.townhall");
     }
OnShow()
void TownhallMenuContent::OnShow () inline override private
Definition at line 71 of file TownhallShopMenu.as.
References Widget::GetWidgetById(), ShopMenuContent::m_def, m_spriteOre, ShopMenuContent::m_widget, m_wRowList, m_wSpecialSeparator, m_wTemplateBuilding, m_wTemplateBuildingEmpty, m_wTemplateBuildingOwned, m_wTemplateBuildingUnavailable, m_wTemplateBuildingUnknown, m_wTemplateRow, m_wTemplateRowUnavailable, and ReloadList().
     {
         @m_wSpecialSeparator = m_widget.GetWidgetById("special-separator");
         @m_wRowList = m_widget.GetWidgetById("row-list");
         @m_wTemplateRow = m_widget.GetWidgetById("row-template");
         @m_wTemplateRowUnavailable = m_widget.GetWidgetById("row-template-unavailable");
         @m_wTemplateBuilding = m_widget.GetWidgetById("building-template");
         @m_wTemplateBuildingOwned = m_widget.GetWidgetById("building-owned-template");
         @m_wTemplateBuildingUnavailable = m_widget.GetWidgetById("building-unavailable-template");
         @m_wTemplateBuildingEmpty = m_widget.GetWidgetById("building-empty-template");
         @m_wTemplateBuildingUnknown = m_widget.GetWidgetById("building-unknown-template");
         @m_spriteOre = m_def.GetSprite("ore");
         ReloadList();
     }
ReloadList()
void TownhallMenuContent::ReloadList () inline override private
Definition at line 194 of file TownhallShopMenu.as.
References AddButton(), Widget::AddChild(), Widget::ClearChildren(), Widget::Clone(), ShopMenu::DoLayout(), GetLocalPlayer(), Widget::GetWidgetById(), ShopMenu::m_currentShopLevel, Widget::m_height, m_numTiers, m_numUpgrades, m_shop, ShopMenuContent::m_shopMenu, m_tiers, m_tiersTownhall, Upgrades::UpgradeShop::m_upgrades, Widget::m_visible, m_wRowList, m_wSpecialSeparator, m_wTemplateRow, m_wTemplateRowUnavailable, and Widget::SetID().
Referenced by OnShow().
     {
         m_wRowList.ClearChildren();
         auto player = GetLocalPlayer();
         if (player is null)
             return;
         for (int i = 0; i < m_numTiers; i++)
         {
             Upgrades::BuildingUpgrade@ townhallUpgrade = cast<Upgrades::BuildingUpgrade>(m_shop.m_upgrades[0]);
             Upgrades::BuildingUpgradeStep@ townhallStep = m_tiersTownhall[i];
             Widget@ wNewRow = null;
             if (i >= m_shopMenu.m_currentShopLevel)
             {
                 @wNewRow = m_wTemplateRowUnavailable.Clone();
                 auto wButton = cast<UpgradeShopButtonWidget>(wNewRow.GetWidgetById("button"));
                 if (wButton !is null)
                 {
                     wButton.Set(this, townhallUpgrade, townhallStep);
                     if (!Network::IsServer())
                         wButton.m_enabled = false;
                 }
             }
             else
             {
                 @wNewRow = m_wTemplateRow.Clone();
                 auto wIcon = cast<SpriteWidget>(wNewRow.GetWidgetById("icon"));
                 if (wIcon !is null)
                     wIcon.SetSprite(townhallStep.GetSprite());
             }
             wNewRow.SetID("");
             wNewRow.m_visible = true;
             auto wLevelIcon = cast<SpriteWidget>(wNewRow.GetWidgetById("icon-level"));
             if (wLevelIcon !is null)
                 wLevelIcon.SetSprite("shop-level-" + (i + 1));
             m_wRowList.AddChild(wNewRow);
             auto wBuildingList = wNewRow.GetWidgetById("building-list");
             if (wBuildingList is null)
                 break;
             for (uint j = 0; j < uint(m_numUpgrades); j++)
             {
                 Upgrades::BuildingUpgrade@ listedUpgrade;
                 Upgrades::BuildingUpgradeStep@ listedStep;
                 Upgrades::BuildingUpgradeStep@ listedStepAbove;
                 if (j + 1 < m_shop.m_upgrades.length())
                     @listedUpgrade = cast<Upgrades::BuildingUpgrade>(m_shop.m_upgrades[j + 1]);
                 if (j < m_tiers[i].length())
                 {
                     @listedStep = m_tiers[i][j];
                     if (i > 0)
                     {
                         for (int k = 0; k < i; k++)
{
                             @listedStepAbove = m_tiers[i - k - 1][j];
                             if (listedStepAbove !is null)
                                 break;
                         }
                     }
                 }
                 AddButton(wBuildingList, listedUpgrade, listedStep, listedStepAbove, j == 7);
             }
         }
         m_shopMenu.DoLayout();
         m_wSpecialSeparator.m_height = m_wRowList.m_height;
     }
Member Data Documentation
m_numTiers
int TownhallMenuContent::m_numTiers = 5 private
Definition at line 21 of file TownhallShopMenu.as.
Referenced by ReloadList(), and TownhallMenuContent().
m_numUpgrades
int TownhallMenuContent::m_numUpgrades = 10 private
Definition at line 22 of file TownhallShopMenu.as.
Referenced by ReloadList().
m_shop
Upgrades::UpgradeShop TownhallMenuContent::m_shop private
Definition at line 17 of file TownhallShopMenu.as.
Referenced by ReloadList(), and TownhallMenuContent().
m_spriteOre
Sprite TownhallMenuContent::m_spriteOre private
Definition at line 15 of file TownhallShopMenu.as.
Referenced by AddButton(), and OnShow().
m_tiers
array<array<Upgrades::BuildingUpgradeStep@> > TownhallMenuContent::m_tiers private
Definition at line 19 of file TownhallShopMenu.as.
Referenced by ReloadList(), and TownhallMenuContent().
m_tiersTownhall
array<Upgrades::BuildingUpgradeStep@> TownhallMenuContent::m_tiersTownhall private
Definition at line 18 of file TownhallShopMenu.as.
Referenced by ReloadList(), and TownhallMenuContent().
m_wRowList
Widget TownhallMenuContent::m_wRowList private
Definition at line 5 of file TownhallShopMenu.as.
Referenced by OnShow(), and ReloadList().
m_wSpecialSeparator
Widget TownhallMenuContent::m_wSpecialSeparator private
Definition at line 3 of file TownhallShopMenu.as.
Referenced by OnShow(), and ReloadList().
m_wTemplateBuilding
Widget TownhallMenuContent::m_wTemplateBuilding private
Definition at line 9 of file TownhallShopMenu.as.
Referenced by AddButton(), and OnShow().
m_wTemplateBuildingEmpty
Widget TownhallMenuContent::m_wTemplateBuildingEmpty private
Definition at line 12 of file TownhallShopMenu.as.
Referenced by AddButton(), and OnShow().
m_wTemplateBuildingOwned
Widget TownhallMenuContent::m_wTemplateBuildingOwned private
Definition at line 10 of file TownhallShopMenu.as.
Referenced by AddButton(), and OnShow().
m_wTemplateBuildingUnavailable
Widget TownhallMenuContent::m_wTemplateBuildingUnavailable private
Definition at line 11 of file TownhallShopMenu.as.
Referenced by AddButton(), and OnShow().
m_wTemplateBuildingUnknown
Widget TownhallMenuContent::m_wTemplateBuildingUnknown private
Definition at line 13 of file TownhallShopMenu.as.
Referenced by AddButton(), and OnShow().
m_wTemplateRow
Widget TownhallMenuContent::m_wTemplateRow private
Definition at line 6 of file TownhallShopMenu.as.
Referenced by OnShow(), and ReloadList().
m_wTemplateRowUnavailable
Widget TownhallMenuContent::m_wTemplateRowUnavailable private
Definition at line 7 of file TownhallShopMenu.as.
Referenced by OnShow(), and ReloadList().
The documentation for this class was generated from the following file:
scripts/GUI/Shop/TownhallShopMenu.as