HoHDocs: ShopMenu Class Reference
ShopMenu Class Reference
Private Member Functions
ShopMenu (GUIBuilder@ b)
void Show (ShopMenuContent@ menuContent, int shopLevel)
void Show () override
void Close () override
void Update (int dt) override
void DoLayout () override
void OnFunc (Widget@ sender, string name) override
Private Attributes
GUIBuilder m_guiBuilder
SoundEvent m_sndBuyGold
SoundEvent m_sndBuyOre
SoundEvent m_sndBuySkill
SoundEvent m_sndCantBuy
Widget m_wLevelList
SpriteWidget m_wLevelTemplate
TextWidget m_wName
Widget m_wInnerFrame
Widget m_wTitle
Widget m_wTitleSeparator
Widget m_wContent
ShopMenuContent m_menuContent
int m_currentShopLevel
bool m_upgradedBuilding
Detailed Description
Definition at line 1 of file ShopMenu.as.
Constructor & Destructor Documentation
ShopMenu()
ShopMenu::ShopMenu (GUIBuilder@ b) inline private
Definition at line 25 of file ShopMenu.as.
References m_guiBuilder, m_sndBuyGold, m_sndBuyOre, m_sndBuySkill, m_sndCantBuy, m_wContent, m_widget, m_wInnerFrame, m_wLevelList, m_wLevelTemplate, m_wName, m_wTitle, and m_wTitleSeparator.
     {
         super(b, "gui/shop.gui");
         @m_guiBuilder = b;
         @m_sndBuyGold = Resources::GetSoundEvent("event:/ui/buy_gold");
         @m_sndBuyOre = Resources::GetSoundEvent("event:/ui/buy_ore");
         @m_sndBuySkill = Resources::GetSoundEvent("event:/ui/buy_skill");
         @m_sndCantBuy = Resources::GetSoundEvent("event:/ui/cant_buy");
         @m_wLevelList = m_widget.GetWidgetById("level-list");
         @m_wLevelTemplate = cast<SpriteWidget>(m_widget.GetWidgetById("level-template"));
         @m_wName = cast<TextWidget>(m_widget.GetWidgetById("name"));
         @m_wInnerFrame = m_widget.GetWidgetById("inner-frame");
         @m_wTitle = m_widget.GetWidgetById("title");
         @m_wTitleSeparator = m_widget.GetWidgetById("title-separator");
         @m_wContent = m_widget.GetWidgetById("content");
     }
Member Function Documentation
Close()
void ShopMenu::Close () inline override private
Definition at line 90 of file ShopMenu.as.
References ChangeLevel(), UserWindow::Close(), GetCurrentLevelFilename(), m_menuContent, m_upgradedBuilding, UserWindow::m_visible, ShopMenuContent::OnClose(), and PauseGame().
Referenced by FountainShopMenuContent::OnFunc(), and Update().
     {
         if (!m_visible)
             return;
         UserWindow::Close();
         PauseGame(false, true);
         if (m_menuContent !is null)
             m_menuContent.OnClose();
         if (m_upgradedBuilding)
             ChangeLevel(GetCurrentLevelFilename());
     }
DoLayout()
void ShopMenu::DoLayout () inline override private
Definition at line 121 of file ShopMenu.as.
References DoLayout(), Widget::m_height, m_wContent, and m_wInnerFrame.
Referenced by StatuesShopMenuContent::RefreshBuyList(), StatuesShopMenuContent::RefreshPlacementList(), DrinksMenuContent::ReloadList(), GeneralStoreMenuContent::ReloadList(), UpgradeShopMenuContent::ReloadList(), ChapelShopMenuContent::ReloadList(), SkillsShopMenuContent::ReloadList(), TownhallMenuContent::ReloadList(), Show(), and FountainShopMenuContent::UpdateInterface().
     {
         m_wInnerFrame.m_height = m_wContent.m_height + 25; // 2 top border + 21 header + 2 bottom border
         UserWindow::DoLayout();
     }
OnFunc()
void ShopMenu::OnFunc (Widget@ sender, string name) inline override private
Definition at line 128 of file ShopMenu.as.
References m_menuContent, name, UserWindow::OnFunc(), and ShopMenuContent::OnFunc().
     {
         if (m_menuContent !is null)
             m_menuContent.OnFunc(sender, name);
         UserWindow::OnFunc(sender, name);
     }
Show() [1/2]
void ShopMenu::Show (ShopMenuContent@ menuContent, int shopLevel) inline private
Definition at line 47 of file ShopMenu.as.
References Widget::AddResource(), Widget::ClearChildren(), DoLayout(), g_gameMode, ShopMenuContent::GetGuiFilename(), m_currentShopLevel, ShopMenuContent::m_def, m_guiBuilder, m_menuContent, m_wContent, ShopMenuContent::m_widget, Widget::m_width, m_wInnerFrame, m_wTitle, m_wTitleSeparator, and ShopMenuContent::OnShow().
     {
         if (m_menuContent !is null)
         {
             m_wContent.ClearChildren();
             @m_menuContent.m_widget = null;
         }
         m_currentShopLevel = shopLevel;
         @m_menuContent = menuContent;
         @m_menuContent.m_def = m_wContent.AddResource(m_guiBuilder, m_menuContent.GetGuiFilename());
         @m_menuContent.m_widget = m_wContent;
         m_menuContent.OnShow();
         cast<BaseGameMode>(g_gameMode).ShowUserWindow(this);
         m_wInnerFrame.m_width = m_wContent.m_width + 4; // 2 left border + 2 right border
         m_wTitle.m_width = m_wContent.m_width - 21; // 21 close button
         m_wTitleSeparator.m_width = m_wContent.m_width;
         DoLayout();
     }
Show() [2/2]
void ShopMenu::Show () inline override private
Definition at line 71 of file ShopMenu.as.
References Widget::AddChild(), Widget::ClearChildren(), SpriteWidget::Clone(), ShopMenuContent::GetTitle(), m_currentShopLevel, m_menuContent, m_wLevelList, m_wLevelTemplate, m_wName, PauseGame(), TextWidget::SetText(), and UserWindow::Show().
     {
         m_wName.SetText(m_menuContent.GetTitle());
         m_wLevelList.ClearChildren();
         for (int i = 0; i < m_currentShopLevel; i++)
         {
             auto wNewIcon = cast<SpriteWidget>(m_wLevelTemplate.Clone());
             wNewIcon.m_visible = true;
             wNewIcon.SetID("");
             wNewIcon.SetSprite("shop-level-" + (i + 1));
             m_wLevelList.AddChild(wNewIcon);
         }
         UserWindow::Show();
         PauseGame(true, true);
     }
Update()
void ShopMenu::Update (int dt) inline override private
Definition at line 106 of file ShopMenu.as.
References Close(), GetInput(), m_menuContent, UserWindow::m_visible, ShopMenuContent::Update(), and UserWindow::Update().
     {
         if (m_visible)
         {
             auto input = GetInput();
             if (input.PlayerMenu.Pressed)
                 Close();
         }
         if (m_menuContent !is null)
             m_menuContent.Update(dt);
         UserWindow::Update(dt);
     }
Member Data Documentation
m_currentShopLevel
int ShopMenu::m_currentShopLevel private
Definition at line 21 of file ShopMenu.as.
Referenced by TownhallMenuContent::AddButton(), StatuesShopMenuContent::NumSlotsForLevel(), GeneralStoreMenuContent::OnFunc(), DrinksMenuContent::ReloadList(), GeneralStoreMenuContent::ReloadList(), FountainShopMenuContent::ReloadList(), UpgradeShopMenuContent::ReloadList(), SkillsShopMenuContent::ReloadList(), TownhallMenuContent::ReloadList(), UpgradeShopButtonWidget::Set(), ChapelShopMenuContent::ShouldEnableButton(), and Show().
m_guiBuilder
GUIBuilder ShopMenu::m_guiBuilder private
Definition at line 3 of file ShopMenu.as.
Referenced by ShopMenu(), and Show().
m_menuContent
ShopMenuContent ShopMenu::m_menuContent private
Definition at line 19 of file ShopMenu.as.
Referenced by Close(), OnFunc(), Show(), and Update().
m_sndBuyGold
SoundEvent ShopMenu::m_sndBuyGold private
Definition at line 5 of file ShopMenu.as.
Referenced by ShopMenuContent::BuyItem(), and ShopMenu().
m_sndBuyOre
SoundEvent ShopMenu::m_sndBuyOre private
Definition at line 6 of file ShopMenu.as.
Referenced by ShopMenuContent::BuyItem(), and ShopMenu().
m_sndBuySkill
SoundEvent ShopMenu::m_sndBuySkill private
Definition at line 7 of file ShopMenu.as.
Referenced by ShopMenuContent::BuyItem(), and ShopMenu().
m_sndCantBuy
SoundEvent ShopMenu::m_sndCantBuy private
Definition at line 8 of file ShopMenu.as.
Referenced by ShopMenuContent::BuyItem(), and ShopMenu().
m_upgradedBuilding
bool ShopMenu::m_upgradedBuilding private
Definition at line 23 of file ShopMenu.as.
Referenced by Close().
m_wContent
Widget ShopMenu::m_wContent private
Definition at line 18 of file ShopMenu.as.
Referenced by DoLayout(), ShopMenu(), and Show().
m_wInnerFrame
Widget ShopMenu::m_wInnerFrame private
Definition at line 15 of file ShopMenu.as.
Referenced by DoLayout(), ShopMenu(), and Show().
m_wLevelList
Widget ShopMenu::m_wLevelList private
Definition at line 10 of file ShopMenu.as.
Referenced by ShopMenu(), and Show().
m_wLevelTemplate
SpriteWidget ShopMenu::m_wLevelTemplate private
Definition at line 11 of file ShopMenu.as.
Referenced by ShopMenu(), and Show().
m_wName
TextWidget ShopMenu::m_wName private
Definition at line 13 of file ShopMenu.as.
Referenced by ShopMenu(), and Show().
m_wTitle
Widget ShopMenu::m_wTitle private
Definition at line 16 of file ShopMenu.as.
Referenced by ShopMenu(), and Show().
m_wTitleSeparator
Widget ShopMenu::m_wTitleSeparator private
Definition at line 17 of file ShopMenu.as.
Referenced by ShopMenu(), and Show().
The documentation for this class was generated from the following file:
scripts/GUI/ShopMenu.as