HoHDocs: ControlMap Class Reference
ControlMap Class Reference
Private Member Functions
bool get_SteamController ()
uint64 get_Handle ()
array< ControlMapBinding@> GetBindings ()
array< ControlMapBinding@> GetStaging ()
void Clear ()
void Remove (ControlMapBinding@ bind)
void Add (ControllerType type, int key, const string &in action)
void ClearStaging ()
void RemoveStaging (ControlMapBinding@ bind)
void AddStaging (ControllerType type, int key, const string &in action)
void AddStagingAxis (ControllerType type, int key, const string &in action, ControlBindingSetAxis setAxis)
void BeginStaging ()
void CommitStaging ()
void Defaults ()
Private Attributes
string ID
int Index
bool UseMouseLook
bool Gamepad
bool Joystick
bool SteamController
Detailed Description
Definition at line 245 of file engine.as.
Member Function Documentation
Add()
void ControlMap::Add (ControllerType type, int key, const string &in action) inline private
Definition at line 262 of file engine.as.
 { }
AddStaging()
void ControlMap::AddStaging (ControllerType type, int key, const string &in action) inline private
Definition at line 266 of file engine.as.
Referenced by MenuControlInputWidget::ExpectedInput().
 { }
AddStagingAxis()
void ControlMap::AddStagingAxis (ControllerType type, int key, const string &in action, ControlBindingSetAxis setAxis) inline private
Definition at line 267 of file engine.as.
Referenced by MenuControlInputWidget::ExpectedInput().
 { }
BeginStaging()
void ControlMap::BeginStaging () inline private
Definition at line 269 of file engine.as.
Referenced by Menu::ControlMapMenu::Initialize(), and Menu::ControlMapMenu::OnFunc().
 { }
Clear()
void ControlMap::Clear () inline private
Definition at line 260 of file engine.as.
 { }
ClearStaging()
void ControlMap::ClearStaging () inline private
Definition at line 264 of file engine.as.
 { }
CommitStaging()
void ControlMap::CommitStaging () inline private
Definition at line 270 of file engine.as.
Referenced by Menu::ControlMapMenu::OnFunc().
 { }
Defaults()
void ControlMap::Defaults () inline private
Definition at line 272 of file engine.as.
Referenced by Menu::ControlMapMenu::OnFunc().
 { }
get_Handle()
uint64 ControlMap::get_Handle () inline private
Definition at line 255 of file engine.as.
 { return 0; }
get_SteamController()
bool ControlMap::get_SteamController () inline private
Definition at line 254 of file engine.as.
 { return false; }
GetBindings()
array<ControlMapBinding@> ControlMap::GetBindings () inline private
Definition at line 257 of file engine.as.
 { return null; }
GetStaging()
array<ControlMapBinding@> ControlMap::GetStaging () inline private
Definition at line 258 of file engine.as.
Referenced by MenuControlInputWidget::GetBindings().
 { return null; }
Remove()
void ControlMap::Remove (ControlMapBinding@ bind) inline private
Definition at line 261 of file engine.as.
 { }
RemoveStaging()
void ControlMap::RemoveStaging (ControlMapBinding@ bind) inline private
Definition at line 265 of file engine.as.
Referenced by MenuControlInputWidget::Clear(), and MenuControlInputWidget::ExpectedInput().
 { }
Member Data Documentation
Gamepad
bool ControlMap::Gamepad private
Definition at line 250 of file engine.as.
Referenced by MenuControlInputWidget::ExpectedInput().
ID
string ControlMap::ID private
Definition at line 247 of file engine.as.
Referenced by Menu::ControlsMenu::Initialize(), and MenuMouse::MenuMouse().
Index
int ControlMap::Index private
Definition at line 248 of file engine.as.
Joystick
bool ControlMap::Joystick private
Definition at line 251 of file engine.as.
Referenced by MenuControlInputWidget::ExpectedInput().
SteamController
bool ControlMap::SteamController private
Definition at line 252 of file engine.as.
Referenced by Menu::ControlsMenu::Initialize().
UseMouseLook
bool ControlMap::UseMouseLook private
Definition at line 249 of file engine.as.
Referenced by Menu::SplitscreenPlayer::DisplayName(), Menu::GetKbmPlayer(), and Menu::JoinInput().
The documentation for this class was generated from the following file:
system/engine.as