HoHDocs: HUDCoop Class Reference
HUDCoop Class Reference
Private Member Functions
HUDCoop (GUIBuilder@ b)
CoopPlayerWidget GetPlayer (uint8 peer)
bool ShouldShow ()
void Update (int dt) override
void Draw (SpriteBatch &sb, int idt) override
Private Attributes
Widget m_wPlayerList
Widget m_wPlayerTemplate
Widget m_wSeparatorTemplate
array< CoopPlayerWidget@> m_players
bool m_localPlayerAdded
Detailed Description
Definition at line 101 of file HUDCoop.as.
Constructor & Destructor Documentation
HUDCoop()
HUDCoop::HUDCoop (GUIBuilder@ b) inline private
Definition at line 111 of file HUDCoop.as.
References LoadCoopPlayerWidget(), LoadWidget(), m_widget, m_wPlayerList, m_wPlayerTemplate, and m_wSeparatorTemplate.
     {
         b.AddWidgetProducer("coop-player", LoadCoopPlayerWidget);
         LoadWidget(b, "gui/hud/coop.gui");
         @m_wPlayerList = m_widget.GetWidgetById("playerlist");
         @m_wPlayerTemplate = m_widget.GetWidgetById("playerlist-template");
         @m_wSeparatorTemplate = m_widget.GetWidgetById("separator-template");
     }
Member Function Documentation
Draw()
void HUDCoop::Draw (SpriteBatch & sb, int idt) inline override private
Definition at line 207 of file HUDCoop.as.
References Draw(), and ShouldShow().
Referenced by Campaign::RenderWidgets().
     {
         if (!ShouldShow())
             return;
         IWidgetHoster::Draw(sb, idt);
     }
GetPlayer()
CoopPlayerWidget HUDCoop::GetPlayer (uint8 peer) inline private
Definition at line 122 of file HUDCoop.as.
References Widget::m_children, and m_wPlayerList.
     {
         for (uint i = 0; i < m_wPlayerList.m_children.length(); i++)
         {
             auto wPlayer = cast<CoopPlayerWidget>(m_wPlayerList.m_children[i]);
             if (wPlayer is null)
                 continue;
             if (wPlayer.m_record.peer == peer)
                 return wPlayer;
         }
         return null;
     }
ShouldShow()
bool HUDCoop::ShouldShow () inline private
Definition at line 136 of file HUDCoop.as.
References g_players, and IsInLobby().
Referenced by Draw(), and Update().
     {
         if (!GetVarBool("ui_hud_coop"))
             return false;
         if (!Lobby::IsInLobby())
             return false;
         if (g_players.length() > 4)
             return false;
         return true;
     }
Update()
void HUDCoop::Update (int dt) inline override private
Definition at line 150 of file HUDCoop.as.
References Widget::AddChild(), Widget::Clone(), DoLayout(), g_players, GetLocalPlayerRecord(), CoopPlayerWidget::m_hudCoop, m_localPlayerAdded, m_players, m_record, m_wPlayerList, m_wPlayerTemplate, m_wSeparatorTemplate, Widget::SetID(), CoopPlayerWidget::SetPeer(), ShouldShow(), and Update().
Referenced by Campaign::UpdateWidgets().
     {
         if (!ShouldShow())
             return;
         IWidgetHoster::Update(dt);
         if (!m_localPlayerAdded)
         {
             auto localPlayer = GetLocalPlayerRecord();
             if (localPlayer !is null)
             {
                 m_localPlayerAdded = true;
                 // Add local player
                 CoopPlayerWidget@ wNewLocalPlayer = cast<CoopPlayerWidget>(m_wPlayerTemplate.Clone());
                 wNewLocalPlayer.SetID("");
                 wNewLocalPlayer.m_visible = true;
                 @wNewLocalPlayer.m_hudCoop = this;
                 wNewLocalPlayer.SetPeer(GetLocalPlayerRecord());
                 m_wPlayerList.AddChild(wNewLocalPlayer);
                 // Add separator
                 auto wNewSeparator = m_wSeparatorTemplate.Clone();
                 wNewSeparator.SetID("");
                 wNewSeparator.m_visible = true;
                 m_wPlayerList.AddChild(wNewSeparator);
                 DoLayout();
                 DoLayout(); // avoid flickering.. (I hate layout issues)
             }
             else
                 return;
         }
         // Check for new players
         for (uint i = 0; i < g_players.length(); i++)
         {
             if (i >= m_players.length())
             {
                 CoopPlayerWidget@ wNewPlayer = cast<CoopPlayerWidget>(m_wPlayerTemplate.Clone());
                 wNewPlayer.SetID("");
                 wNewPlayer.m_visible = true;
                 @wNewPlayer.m_hudCoop = this;
                 wNewPlayer.SetPeer(g_players[i]);
                 if (!g_players[i].local)
                 {
                     m_wPlayerList.AddChild(wNewPlayer);
                     DoLayout();
                 }
                 m_players.insertLast(wNewPlayer);
             }
             else if (m_players[i].m_record !is g_players[i])
                 m_players[i].SetPeer(g_players[i]);
         }
     }
Member Data Documentation
m_localPlayerAdded
bool HUDCoop::m_localPlayerAdded private
Definition at line 109 of file HUDCoop.as.
Referenced by Update().
m_players
array<CoopPlayerWidget@> HUDCoop::m_players private
Definition at line 107 of file HUDCoop.as.
Referenced by Update().
m_wPlayerList
Widget HUDCoop::m_wPlayerList private
Definition at line 103 of file HUDCoop.as.
Referenced by GetPlayer(), HUDCoop(), and Update().
m_wPlayerTemplate
Widget HUDCoop::m_wPlayerTemplate private
Definition at line 104 of file HUDCoop.as.
Referenced by HUDCoop(), and Update().
m_wSeparatorTemplate
Widget HUDCoop::m_wSeparatorTemplate private
Definition at line 105 of file HUDCoop.as.
Referenced by HUDCoop(), and Update().
The documentation for this class was generated from the following file:
scripts/GUI/HUD/HUDCoop.as