HoHDocs: BaseGameMode Class Reference
BaseGameMode Class Reference
Private Member Functions
BaseGameMode (Scene@ scene)
OverheadBossBar AddBossBarActor (Actor@ actor, int barCount, int barOffset, string name)
OverheadBossBar GetBossBarActor (Actor@ actor)
void DrawOverheadBossBars (SpriteBatch &sb, int idt)
int GetPlayersAlive ()
void ShowDialog (string id, string question, string buttonYes, string buttonNo, IWidgetHoster@ returnHost) override
void ShowDialog (string id, string message, string button, IWidgetHoster@ returnHost) override
void ShowInputDialog (string id, string message, IWidgetHoster@ returnHost, string defaultInput="") override
bool ShowOffscreenPlayer (PlayerBase@ player)
bool IsUserWindowVisible ()
void ShowUserWindow (string id)
void ShowUserWindow (UserWindow@ window)
void CloseUserWindow ()
void ToggleUserWindow (UserWindow@ window)
bool ShouldFreezeControls ()
bool ShouldDisplayCursor ()
void ResizeWindow (int w, int h, float scale)
HUD GetHUD () override
ScreenShake ShakeScreen (int tm, float amount, vec3 pos=vec3(), float range=-1.0f)
vec2 GetMousePos ()
void UpdateMouse (int ms, GameInput &gameInput, MenuInput &menuInput)
void DrawMouse (int idt, SpriteBatch &sb)
void UpdatePausedFrame (int ms, GameInput &gameInput, MenuInput &menuInput)
void UpdateFrame (int ms, GameInput &gameInput, MenuInput &menuInput)
void SpectateUpdateHUD ()
void StopSpectating ()
void BeginSpectating ()
void ToggleSpectating ()
void SpectateNextPlayer ()
void FocusTopRoot ()
void AddWidgetRoot (IWidgetHoster@ host) override
void RemoveWidgetRoot (IWidgetHoster@ host) override
void ReplaceWidgetRoot (IWidgetHoster@ find, IWidgetHoster@ replace) override
void ReplaceTopWidgetRoot (IWidgetHoster@ host) override
void SetExclusiveWidgetRoot (IWidgetHoster@ host) override
void ClearWidgetRoot () override
bool MenuBack ()
void SetCursorGame ()
void SetCursorUI ()
void UpdateCurrentCursor ()
void UpdateWidgets (int ms, GameInput &gameInput, MenuInput &menuInput)
Widget FirstFocusable (Widget@ w)
void DrawFloatingTexts (int idt, SpriteBatch &sb)
vec2 GetCameraPos (int idt)
vec4 GetVignette (int idt)
bool ShouldDisplayPlayerNames ()
void PreRenderFrame (int idt)
string GetPlayerDisplayName (PlayerRecord@ record)
void DisplayPlayerName (SpriteBatch &sb, PlayerRecord@ record, PlayerHusk@ plr, vec2 pos)
void DisplayPlayerHealth (SpriteBatch &sb, PlayerRecord@ record, PlayerHusk@ plr, vec2 pos)
void RenderFrame (int idt, SpriteBatch &sb)
vec4 ColorForPlayer (PlayerRecord@ record)
void RenderWidgets (PlayerRecord@ player, int idt, SpriteBatch &sb)
SValue Save ()
void Save (SValueBuilder &builder)
void SavePlayer (PlayerRecord &player, bool saveLevel=false, SValueBuilder@ town=null)
void SavePlayer (SValueBuilder &builder, PlayerRecord &player)
void LoadPlayer (SValue &data, PlayerRecord &player)
PlayerRecord CreatePlayerRecord ()
void LoadDungeonRotation (SValue@ save)
void Start (uint8 peer, SValue@ save, StartMode sMode)
void PostStart ()
void ActivatePlayerRecord (uint8 peer)
void InitializePlayer (PlayerRecord &player)
void GetPlayerSave (uint8 peer)
void AddPlayer (uint8 peer)
void RemovePlayer (uint8 peer, bool kicked)
void RefreshMultiplayerScaling ()
void RestartGame ()
void PlayerDied (PlayerRecord@ player, PlayerRecord@ killer, DamageInfo di)
void SpawnPlayers ()
vec2 GetPlayerSpawnPosition (PlayerRecord &record)
void SpawnPlayer (int i, vec2 pos=vec2(-1, -1), int unitId=0, uint team=0) override
void SpawnPlayerCorpse (int i, vec2 pos=vec2(-1, -1)) override
void AttemptRespawn (uint8 peer) override
float FilterAction (Actor@ a, Actor@ owner, float selfDmg, float teamDmg, float enemyDmg, uint teamOverride=1) override
void RefreshPlayerScene (PlayerBase@ player, CustomUnitScene@ scene)
void _Deprecation9030 ()
bool get_m_mouseReal ()
void set_m_mouseReal (bool real)
vec2 get_m_mouseScreenPosPrev ()
void set_m_mousePosPrev (vec2 p)
vec2 get_m_mouseScreenPos ()
void set_m_mousePos (vec2 p)
bool get_m_usingRealCursor ()
void set_m_usingRealCursor (bool b)
bool get_m_showCursor ()
void set_m_showCursor (bool b)
int get_m_currCursorColorC ()
void set_m_currCursorColorC (int c)
vec3 get_m_currCursorColor ()
void set_m_currCursorColor (vec3 color)
Private Attributes
vec2 m_camPos
vec2 m_camPosLastLocal
bool m_camPosLastLocalSet
StartMode m_startMode
bool m_started
bool m_spawnedInitial
bool m_useSpawnLogic = true
array< IWidgetHoster@> m_widgetRoots
array< ScriptWidgetHost@> m_widgetScriptHosts
array< UserWindow@> m_userWindows
WidgetInspector m_widgetInspector
HUDSpectate m_hudSpectate
GameOver m_gameOver
bool m_showOverheadBossBars
array< OverheadBossBar@> m_arrBosses
bool m_switchingWidgetHoster
bool m_spectating
int m_spectatingPlayer
BitmapFont m_fntPlayerName
array< ScreenShake@> m_screenShake
int m_extraLives
int m_levelCount
DungeonRotation m_rotation
Tooltip m_tooltip
array< MouseBase@> m_mice
bool m_usingUICursor
bool _Deprecation9030Printed
bool _m_showCursor = true
Detailed Description
Definition at line 170 of file BaseGameMode.as.
Constructor & Destructor Documentation
BaseGameMode()
BaseGameMode::BaseGameMode (Scene@ scene) inline private
Definition at line 212 of file BaseGameMode.as.
References Platform::CursorNormal, CvarDebugHandicap(), CvarDebugWidgets(), CvarExtraPlayers(), CvarHardwareCursor(), CvarInspectWidget(), CvarPlayerNamesChanged(), CvarSmoothUI(), g_doubleClickTime, g_effectUnit, g_floatTextFont, g_floatTextFontBig, g_gameMode, g_scene, GiveAllDyesCFunc(), Platform::HideCursor(), MusicManager::Initialize(), Tutorial::Initialize(), EnvironmentSoundSystem::Initialize(), QueuedTasks::Initialize(), Platform::Initialize(), InitializeFloatingText(), ListFlagsCFunc(), LoadBarWidget(), LoadBlinkWidget(), LoadBuffWidget(), LoadButtonWidget(), LoadCheckBoxGroupWidget(), LoadCheckboxWidget(), LoadClipWidget(), LoadColorButtonWidget(), LoadColorCheckboxWidget(), CharacterColors::LoadColors(), LoadDetailsWidget(), LoadDotbarWidget(), Materials::LoadDyes(), LoadFilteredListWidget(), LoadFlagWidget(), LoadGore(), LoadGroupRectWidget(), LoadGroupWidget(), LoadRectWidget(), LoadScalableSpriteButtonWidget(), LoadScalableSpriteIconButtonWidget(), LoadScrollableRectWidget(), LoadScrollbarWidget(), LoadSliderWidget(), LoadSpriteBarWidget(), LoadSpriteButtonWidget(), LoadSpriteWidget(), LoadSysTextWidget(), LoadTextInputWidget(), LoadTextWidget(), LoadTopNumberIconWidget(), LoadTransformWidget(), LoadUnitWidget(), AGameMode::m_currCursor, m_fntPlayerName, AGameMode::m_guiBuilder, m_hudSpectate, m_safeGore, m_tooltip, m_widgetInspector, SetTileEffectsCvar(), SetUIScaleCVar(), and Tooltip().
     {
         @g_scene = scene;
         @g_gameMode = this;
         Platform::Initialize();
         @m_currCursor = Platform::CursorNormal;
         g_doubleClickTime = Platform::GetDoubleClickTime();
         CharacterColors::LoadColors();
         Materials::LoadDyes();
     //  m_guiBuilder.AddWidgetProducer("gui", PrintWidget);
         m_guiBuilder.AddWidgetProducer("group", LoadGroupWidget);
         m_guiBuilder.AddWidgetProducer("grouprect", LoadGroupRectWidget);
         m_guiBuilder.AddWidgetProducer("text", LoadTextWidget);
         m_guiBuilder.AddWidgetProducer("systext", LoadSysTextWidget);
         m_guiBuilder.AddWidgetProducer("sprite", LoadSpriteWidget);
         m_guiBuilder.AddWidgetProducer("rect", LoadRectWidget);
         m_guiBuilder.AddWidgetProducer("clip", LoadClipWidget);
         m_guiBuilder.AddWidgetProducer("scrollrect", LoadScrollableRectWidget);
         m_guiBuilder.AddWidgetProducer("flag", LoadFlagWidget);
         m_guiBuilder.AddWidgetProducer("transform", LoadTransformWidget);
         m_guiBuilder.AddWidgetProducer("button", LoadButtonWidget);
         m_guiBuilder.AddWidgetProducer("spritebutton", LoadSpriteButtonWidget);
         m_guiBuilder.AddWidgetProducer("colorbutton", LoadColorButtonWidget);
         m_guiBuilder.AddWidgetProducer("scalebutton", LoadScalableSpriteButtonWidget);
         m_guiBuilder.AddWidgetProducer("scaleiconbutton", LoadScalableSpriteIconButtonWidget);
         m_guiBuilder.AddWidgetProducer("slider", LoadSliderWidget);
         m_guiBuilder.AddWidgetProducer("unit", LoadUnitWidget);
         m_guiBuilder.AddWidgetProducer("textinput", LoadTextInputWidget);
         m_guiBuilder.AddWidgetProducer("bar", LoadBarWidget);
         m_guiBuilder.AddWidgetProducer("scrollbar", LoadScrollbarWidget);
         m_guiBuilder.AddWidgetProducer("checkbox", LoadCheckboxWidget);
         m_guiBuilder.AddWidgetProducer("colorcheckbox", LoadColorCheckboxWidget);
         m_guiBuilder.AddWidgetProducer("checkboxgroup", LoadCheckBoxGroupWidget);
         m_guiBuilder.AddWidgetProducer("blink", LoadBlinkWidget);
         m_guiBuilder.AddWidgetProducer("filteredlist", LoadFilteredListWidget);
         m_guiBuilder.AddWidgetProducer("dotbar", LoadDotbarWidget);
         m_guiBuilder.AddWidgetProducer("spritebar", LoadSpriteBarWidget);
         m_guiBuilder.AddWidgetProducer("details", LoadDetailsWidget);
         m_guiBuilder.AddWidgetProducer("buff", LoadBuffWidget);
         m_guiBuilder.AddWidgetProducer("topnumber", LoadTopNumberIconWidget);
         @g_effectUnit = Resources::GetUnitProducer("system/effect.unit");
         @g_floatTextFont = Resources::GetBitmapFont("gui/fonts/font_hw8.fnt");
         @g_floatTextFontBig = Resources::GetBitmapFont("gui/fonts/arial11.fnt");
         InitializeFloatingText();
         AddVar("ui_smooth", false, CvarSmoothUI);
         AddVar("ui_hide_fog", false, null, cvar_flags::Cheat);
         AddVar("ui_debug_handicap", false, CvarDebugHandicap);
         AddVar("g_screenshake", 1.0f);
         AddVar("g_gore", true);
         AddVar("g_extra_players", 0, CvarExtraPlayers);
         AddVar("debug_widgets", false, CvarDebugWidgets);
         AddVar("inspect_widget", false, CvarInspectWidget);
         AddVar("g_start_level", 0, null, cvar_flags::Cheat);
         AddVar("g_autoswitch_pickup", false);
         AddVar("g_autoswitch_empty", true);
         AddVar("g_local_player_marker", false);
         AddVar("g_player_markers", true);
         AddVar("g_laser_sight", -1);
         AddVar("g_movedir_snap", 16);
         AddVar("g_mousemove_speed", 40.0f);
         AddVar("g_potion_delay", 0);
         AddVar("ui_hud_stats", true);
         AddVar("ui_hud_skills", true);
         AddVar("ui_hud_bossbar", true);
         AddVar("ui_hud_bossbar_actors", true);
         AddVar("ui_hud_topbar", true);
         AddVar("ui_hud_coop", true);
         AddVar("ui_draw_widgets", true);
         AddVar("ui_draw_plr_names", 1);
         AddVar("ui_draw_plr_names_real", false, CvarPlayerNamesChanged);
         AddVar("ui_draw_plr_stats", true);
         AddVar("ui_draw_vignette", true);
         AddVar("ui_player_measure", false);
         AddVar("ui_cursor_unit", false);
         AddVar("ui_cursor_alpha", 1.0);
         AddVar("ui_chat_fade_time", 7000);
         AddVar("ui_chat_dialog", true);
         AddVar("ui_chat_scale", 1.0);
         AddVar("ui_chat_width", 0.35);
         AddVar("ui_chat_pos", vec2(0.05, 0.8));
         AddVar("ui_hardware_cursor", false, CvarHardwareCursor);
         Tutorial::Initialize();
         AddVar("ui_show_intro", true);
         AddVar("ui_waypoint_player", 1.0f);
         AddVar("ui_waypoint_world", 1.0f);
         AddVar("g_wheel_always", false);
         AddVar("g_wheel_nextprev", true);
         AddVar("g_wheel_number", true);
         AddVar("g_wheel_showammo", true);
         AddVar("g_wheel_accurate", -1);
         AddVar("g_tile_effects", true, SetTileEffectsCvar);
         AddVar("ui_bars_visibility", 0);
         AddVar("ui_key_count", false);
         AddVar("ui_speechbubble_alpha", 1.0f);
         AddVar("ui_cursor_health", false);
         AddVar("ui_cursor_health_alpha", 0.5f);
         AddVar("ui_minimap_alpha", 0.75);
         AddVar("ui_minimap_size", -1);
         AddVar("ui_scale", 1.0, SetUIScaleCVar);
         AddVar("ui_tooltip_pretty", true);
         @m_widgetInspector = WidgetInspector();
         if (!GetVarBool("ui_hardware_cursor"))
             Platform::HideCursor();
         MusicManager::Initialize();
         QueuedTasks::Initialize();
         EnvironmentSoundSystem::Initialize();
         @m_hudSpectate = HUDSpectate(m_guiBuilder);
         @m_fntPlayerName = Resources::GetBitmapFont("gui/fonts/arial11.fnt");
         @m_tooltip = Tooltip(Resources::GetSValue("gui/tooltip.sval"));
         @m_safeGore = LoadGore("effects/gibs/no_gore.sval");
         AddFunction("list_flags", ListFlagsCFunc, cvar_flags::Cheat);
         AddFunction("give_all_dyes", GiveAllDyesCFunc, cvar_flags::Cheat);
     }
Member Function Documentation
_Deprecation9030()
void BaseGameMode::_Deprecation9030 () inline private
Compatibility layer due to revision 9030
Definition at line 1941 of file BaseGameMode.as.
Referenced by set_m_currCursorColor(), set_m_currCursorColorC(), set_m_mousePos(), set_m_mousePosPrev(), set_m_mouseReal(), set_m_showCursor(), and set_m_usingRealCursor().
 { if (_Deprecation9030Printed) return; _Deprecation9030Printed = true; PrintError("Warning: BaseGameMode's mouse values are deprecated, use m_mice array instead."); } bool _Deprecation9030Printed;
ActivatePlayerRecord()
void BaseGameMode::ActivatePlayerRecord (uint8 peer) inline private
Definition at line 1643 of file BaseGameMode.as.
References CreatePlayerRecord(), g_players, GetUniquePeerId(), id, InitializePlayer(), IsPlayerLocal(), HwrSaves::LoadCharacter(), LoadPlayer(), and RefreshMultiplayerScaling().
Referenced by AddPlayer(), GetPlayerSave(), and Start().
     {
         uint64 id = GetUniquePeerId(peer);
         bool local = Lobby::IsPlayerLocal(peer);
         for (uint i = 0; i < g_players.length(); i++)
         {
             if (g_players[i].id == id)
             {
                 g_players[i].id = id;
                 g_players[i].peer = peer;
                 g_players[i].local = local;
                 auto plrSave = HwrSaves::LoadCharacter(peer);
                 if (plrSave !is null)
                     LoadPlayer(plrSave, g_players[i]);
                 RefreshMultiplayerScaling();
                 return;
             }
         }
         PlayerRecord@ plr = CreatePlayerRecord();
         plr.peer = peer;
         plr.local = local;
         plr.id = id;
         @plr.actor = null;
         InitializePlayer(plr);
         g_players.insertLast(plr);
         auto plrSave = HwrSaves::LoadCharacter(peer);
         if (plrSave !is null)
             LoadPlayer(plrSave, plr);
         RefreshMultiplayerScaling();
     }
AddBossBarActor()
OverheadBossBar BaseGameMode::AddBossBarActor (Actor@ actor, int barCount, int barOffset, string name) inline private
Definition at line 358 of file BaseGameMode.as.
References m_arrBosses, m_showOverheadBossBars, name, and OverheadBossBar::Set().
     {
         if (!m_showOverheadBossBars)
             return null;
         OverheadBossBar@ b = OverheadBossBar();
         b.Set(actor, barCount, barOffset, name);
         m_arrBosses.insertLast(b);
         return b;
     }
AddPlayer()
void BaseGameMode::AddPlayer (uint8 peer) inline private
Definition at line 1697 of file BaseGameMode.as.
References ActivatePlayerRecord(), g_players, IsPlayerLocal(), RefreshMultiplayerScaling(), unit, and xy().
     {
         if (Lobby::IsPlayerLocal(peer))
             return;
         ActivatePlayerRecord(peer);
         RefreshMultiplayerScaling();
         if (Network::IsServer())
         {
             for (uint i = 0; i < g_players.length(); i++)
             {
                 if (g_players[i].peer == 255)
                     continue;
                 /*
                 if (m_started && g_players[i].peer == peer)
                 {
                     // Immediately spawn drop-in players
                     SpawnPlayer(i);
                     continue;
                 }
                 */
                 if (g_players[i].actor is null)
                     continue;
                 auto unit = g_players[i].actor.m_unit;
                 (Network::Message("SpawnPlayer") << g_players[i].peer << xy(unit.GetPosition()) << unit.GetId() << g_players[i].team).SendToPeer(peer);
             }
         }
     }
AddWidgetRoot()
void BaseGameMode::AddWidgetRoot (IWidgetHoster@ host) inline override private
Definition at line 794 of file BaseGameMode.as.
References FocusTopRoot(), and m_widgetRoots.
Referenced by ShowDialog(), and ShowInputDialog().
     {
         m_widgetRoots.insertLast(host);
         FocusTopRoot();
     }
AttemptRespawn()
void BaseGameMode::AttemptRespawn (uint8 peer) inline override private
Definition at line 1888 of file BaseGameMode.as.
References g_players, IsDead(), and SpawnPlayer().
Referenced by Campaign::UpdateWidgets().
     {
         if (!Network::IsServer())
             return;
         for (uint i = 0; i < g_players.length(); i++)
         {
             if (g_players[i].peer == peer)
             {
                 if (!g_players[i].IsDead())
                     return;
                 (Network::Message("ResetPlayerHealthArmor") << g_players[i].peer).SendToAll();
                 g_players[i].hp = 1.0;
                 g_players[i].armor = 0;
                 SpawnPlayer(i, vec2(), 0, g_players[i].team);
                 return;
             }
         }
     }
BeginSpectating()
void BaseGameMode::BeginSpectating () inline private
Definition at line 748 of file BaseGameMode.as.
References m_spectating, and SpectateUpdateHUD().
Referenced by ToggleSpectating().
     {
         m_spectating = true;
         SpectateUpdateHUD();
     }
ClearWidgetRoot()
void BaseGameMode::ClearWidgetRoot () inline override private
Definition at line 834 of file BaseGameMode.as.
References AGameMode::m_widgetInputFocus, and m_widgetRoots.
     {
         m_widgetRoots.removeRange(0, m_widgetRoots.length());
         @m_widgetInputFocus = null;
     }
CloseUserWindow()
void BaseGameMode::CloseUserWindow () inline private
Definition at line 483 of file BaseGameMode.as.
References m_userWindows.
     {
         for (uint i = 0; i < m_userWindows.length(); i++)
         {
             if (m_userWindows[i].m_visible)
                 m_userWindows[i].Close();
         }
     }
ColorForPlayer()
vec4 BaseGameMode::ColorForPlayer (PlayerRecord@ record) inline private
Definition at line 1356 of file BaseGameMode.as.
References GetPlayerColor().
Referenced by DisplayPlayerName().
     {
         return ParseColorRGBA("#" + GetPlayerColor(record.peer) + "ff");
     }
CreatePlayerRecord()
PlayerRecord BaseGameMode::CreatePlayerRecord () inline private
Definition at line 1528 of file BaseGameMode.as.
Referenced by ActivatePlayerRecord().
     {
         return PlayerRecord();
     }
DisplayPlayerHealth()
void BaseGameMode::DisplayPlayerHealth (SpriteBatch & sb, PlayerRecord@ record, PlayerHusk@ plr, vec2 pos) inline private
Definition at line 1207 of file BaseGameMode.as.
References clamp().
Referenced by RenderFrame().
     {
         vec4 colorBackground = vec4(0, 0, 0, 1);
         vec4 colorEmpty = vec4(0.16, 0.06, 0.06, 1);
         vec4 colorFilled = vec4(1, 0, 0, 1);
         int barWidth = 16;
         int barHeight = 3;
         int x = int(pos.x - barWidth / 2);
         int y = int(pos.y - 14);
         sb.FillRectangle(vec4(x, y, barWidth, 3), colorBackground);
         int w = int((barWidth - 2) * clamp(record.hp, 0.0f, 1.0f));
         int h = barHeight - 2;
         sb.FillRectangle(vec4(x + 1, y + 1, w, h), colorFilled);
         x += w;
         w = (barWidth - 2) - w;
         sb.FillRectangle(vec4(x + 1, y + 1, w, h), colorEmpty);
     }
DisplayPlayerName()
void BaseGameMode::DisplayPlayerName (SpriteBatch & sb, PlayerRecord@ record, PlayerHusk@ plr, vec2 pos) inline private
Definition at line 1196 of file BaseGameMode.as.
References Center, ColorForPlayer(), GetPlayerDisplayName(), m_fntPlayerName, and PlayerHusk::m_textName.
Referenced by RenderFrame().
     {
         if (plr.m_textName is null)
         {
             string playerName = GetPlayerDisplayName(record);
             @plr.m_textName = m_fntPlayerName.BuildText(playerName, -1, TextAlignment::Center);
             plr.m_textName.SetColor(ColorForPlayer(record));
         }
         sb.DrawString(pos - vec2(plr.m_textName.GetWidth() / 2, 16 + plr.m_textName.GetHeight()), plr.m_textName);
     }
DrawFloatingTexts()
void BaseGameMode::DrawFloatingTexts (int idt, SpriteBatch & sb) inline private
Definition at line 1082 of file BaseGameMode.as.
References Draw(), g_floatingTexts, and IsPaused().
Referenced by Campaign::RenderWidgets().
     {
         for (uint i = 0; i < g_floatingTexts.length(); i++)
             g_floatingTexts[i].Draw(IsPaused() ? 0 : idt, sb);
     }
DrawMouse()
void BaseGameMode::DrawMouse (int idt, SpriteBatch & sb) inline private
Definition at line 604 of file BaseGameMode.as.
References g_gameMode, m_mice, m_tooltip, m_usingUICursor, m_widgetRoots, AGameMode::m_wndHeight, AGameMode::m_wndScale, and AGameMode::m_wndWidth.
Referenced by MainMenu::RenderFrame(), and RenderFrame().
     {
         sb.Begin(g_gameMode.m_wndWidth, g_gameMode.m_wndHeight, m_wndScale);
         if (m_widgetRoots.length() > 0)
         {
             if (m_mice.length() != 0)
                 m_mice[0].DrawTooltip(idt, sb, m_tooltip);
         }
         for (uint i = 0; i < m_mice.length(); i++)
         {
             if (m_mice[i].m_real && m_usingUICursor && GetVarBool("ui_hardware_cursor"))
                 continue;
             m_mice[i].Draw(idt, sb);
         }
         sb.End();
     }
DrawOverheadBossBars()
void BaseGameMode::DrawOverheadBossBars (SpriteBatch & sb, int idt) inline private
Definition at line 380 of file BaseGameMode.as.
References Draw(), m_arrBosses, and m_showOverheadBossBars.
Referenced by Campaign::RenderWidgets().
     {
         if (!m_showOverheadBossBars)
             return;
         for (int i = 0; i < int(m_arrBosses.length()); i++)
         {
             if (!m_arrBosses[i].Draw(sb, idt))
                 m_arrBosses.removeAt(i--);
         }
     }
FilterAction()
float BaseGameMode::FilterAction (Actor@ a, Actor@ owner, float selfDmg, float teamDmg, float enemyDmg, uint teamOverride = 1) inline override private
Definition at line 1911 of file BaseGameMode.as.
References Actor::Team.
     {
         if (teamOverride == 1)
         {
             if (owner is null)
                 return 1;
             teamOverride = owner.Team;
         }
         if (a.Team != teamOverride)
             return enemyDmg;
         /*
         //TODO: Reconsider.. this used to be 0, but that would also block healing teammates!
         //      So now we just rely on teamDmg directly.
         if (teamOverride == g_team_player)
             return teamDmg * GetFriendlyFireScale();
         */
         return teamDmg;
     }
FirstFocusable()
Widget BaseGameMode::FirstFocusable (Widget@ w) inline private
Definition at line 1062 of file BaseGameMode.as.
References Widget::m_canFocus, and Widget::m_children.
Referenced by UpdateWidgets().
     {
         if (w.m_canFocus)
             return w;
         for (uint i = 0; i < w.m_children.length(); i++)
         {
             auto ww = w.m_children[i];
             if (ww.m_canFocus)
                 return ww;
             auto wwf = FirstFocusable(ww);
             if (wwf !is null)
                 return wwf;
         }
         return null;
     }
FocusTopRoot()
void BaseGameMode::FocusTopRoot () inline private
Definition at line 776 of file BaseGameMode.as.
References Widget::GetCenter(), m_switchingWidgetHoster, AGameMode::m_widgetInputFocus, m_widgetRoots, AGameMode::m_widgetUnderCursor, and Widget::SetHovering().
Referenced by AddWidgetRoot(), RemoveWidgetRoot(), ReplaceTopWidgetRoot(), ReplaceWidgetRoot(), and SetExclusiveWidgetRoot().
     {
         if (m_widgetRoots.length() == 0)
             return;
         m_widgetRoots[m_widgetRoots.length() - 1].m_forceFocus = true;
         if (m_widgetUnderCursor !is null)
         {
             m_widgetUnderCursor.SetHovering(false, m_widgetUnderCursor.GetCenter());
             @m_widgetUnderCursor = null;
         }
         if (m_widgetInputFocus !is null)
             @m_widgetInputFocus = null;
         m_switchingWidgetHoster = true;
     }
get_m_currCursorColor()
vec3 BaseGameMode::get_m_currCursorColor () inline private
Definition at line 1948 of file BaseGameMode.as.
 { _Deprecation9030(); return m_mice[0].m_color; } void set_m_currCursorColor(vec3 color) { _Deprecation9030(); m_mice[0].m_color = color; }
get_m_currCursorColorC()
int BaseGameMode::get_m_currCursorColorC () inline private
Definition at line 1947 of file BaseGameMode.as.
 { _Deprecation9030(); return m_mice[0].m_colorC; } void set_m_currCursorColorC(int c) { _Deprecation9030(); m_mice[0].m_colorC = c; }
get_m_mouseReal()
bool BaseGameMode::get_m_mouseReal () inline private
Definition at line 1942 of file BaseGameMode.as.
Referenced by set_m_usingRealCursor().
 { _Deprecation9030(); return m_mice[0].m_real; } void set_m_mouseReal(bool real) { _Deprecation9030(); m_mice[0].m_real = real; }
get_m_mouseScreenPos()
vec2 BaseGameMode::get_m_mouseScreenPos () inline private
Definition at line 1944 of file BaseGameMode.as.
 { _Deprecation9030(); return m_mice[0].m_pos; } void set_m_mousePos(vec2 p) { _Deprecation9030(); m_mice[0].m_pos = p; }
get_m_mouseScreenPosPrev()
vec2 BaseGameMode::get_m_mouseScreenPosPrev () inline private
Definition at line 1943 of file BaseGameMode.as.
 { _Deprecation9030(); return m_mice[0].m_posPrev; } void set_m_mousePosPrev(vec2 p) { _Deprecation9030(); m_mice[0].m_posPrev = p; }
get_m_showCursor()
bool BaseGameMode::get_m_showCursor () inline private
Definition at line 1946 of file BaseGameMode.as.
 { _Deprecation9030(); return _m_showCursor; } void set_m_showCursor(bool b) { _Deprecation9030(); _m_showCursor = b; } bool _m_showCursor = true;
get_m_usingRealCursor()
bool BaseGameMode::get_m_usingRealCursor () inline private
Definition at line 1945 of file BaseGameMode.as.
 { _Deprecation9030(); return get_m_mouseReal(); } void set_m_usingRealCursor(bool b) { _Deprecation9030(); set_m_mouseReal(b); }
GetBossBarActor()
OverheadBossBar BaseGameMode::GetBossBarActor (Actor@ actor) inline private
Definition at line 369 of file BaseGameMode.as.
References OverheadBossBar::m_actor, and m_arrBosses.
     {
         for (uint i = 0; i < m_arrBosses.length(); i++)
         {
             OverheadBossBar@ bar = m_arrBosses[i];
             if (bar.m_actor is actor)
                 return bar;
         }
         return null;
     }
GetCameraPos()
vec2 BaseGameMode::GetCameraPos (int idt) inline private
Definition at line 1088 of file BaseGameMode.as.
References g_players, g_prepareCameraIndex, g_prepareCameras, GetLocalPlayerRecord(), m_camPos, m_camPosLastLocal, m_camPosLastLocalSet, m_levelStarts, m_screenShake, m_spectating, m_spectatingPlayer, Tweak::PlayerCameraHeight, xy(), and xyz().
Referenced by PreRenderFrame().
     {
         PlayerRecord@ player = null;
         if (m_spectating)
             @player = g_players[m_spectatingPlayer];
         else
             @player = GetLocalPlayerRecord();
         if (player !is null && player.actor !is null)
         {
             m_camPos = xy(player.actor.m_unit.GetInterpolatedPosition(idt));
             m_camPos.y -= Tweak::PlayerCameraHeight;
             if (player.local)
             {
                 m_camPosLastLocal = m_camPos;
                 m_camPosLastLocalSet = true;
             }
         }
         else if (player !is null && player.actor is null && player.local && m_camPosLastLocalSet)
             m_camPos = m_camPosLastLocal;
         else if (g_prepareCameras.length() > 0)
         {
             if (g_prepareCameraIndex == -1)
                 g_prepareCameraIndex = randi(g_prepareCameras.length());
             m_camPos = xy(g_prepareCameras[g_prepareCameraIndex].Position);
         }
         else if (m_levelStarts.length() > 0)
             m_camPos = xy(m_levelStarts[0].Position);
         vec2 shake;
         for (uint i = 0; i < m_screenShake.length(); i++)
             shake += m_screenShake[i].GetCameraOffset(xyz(m_camPos), idt);
         return m_camPos + shake;
     }
GetHUD()
HUD BaseGameMode::GetHUD () inline override private
Definition at line 573 of file BaseGameMode.as.
Referenced by ResizeWindow().
 { return null; }
GetMousePos()
vec2 BaseGameMode::GetMousePos () inline private
Definition at line 591 of file BaseGameMode.as.
References m_mice.
Referenced by GetGameModeMousePosition(), and UpdateWidgets().
     {
         if (m_mice.length() == 0)
             return vec2();
         return m_mice[0].m_pos;
     }
GetPlayerDisplayName()
string BaseGameMode::GetPlayerDisplayName (PlayerRecord@ record) inline private
Definition at line 1182 of file BaseGameMode.as.
Referenced by DisplayPlayerName(), and Town::GetPlayerDisplayName().
     {
         string ret;
         if (GetVarBool("ui_draw_plr_names_real"))
             ret = record.GetLobbyName();
         else
             ret = record.GetName();
         if (ret.length() > 12)
             ret = ret.substr(0, 12) + "..";
         return EscapeString(ret);
     }
GetPlayersAlive()
int BaseGameMode::GetPlayersAlive () inline private
Definition at line 392 of file BaseGameMode.as.
References g_players, and IsDead().
Referenced by Campaign::CheckGameOver().
     {
         int ret = 0;
         for (uint i = 0; i < g_players.length(); i++)
         {
             if (g_players[i].peer != 255 && !g_players[i].IsDead())
                 ret++;
         }
         return ret;
     }
GetPlayerSave()
void BaseGameMode::GetPlayerSave (uint8 peer) inline private
Definition at line 1689 of file BaseGameMode.as.
References ActivatePlayerRecord(), and IsPlayerLocal().
     {
         if (Lobby::IsPlayerLocal(peer))
             return;
         ActivatePlayerRecord(peer);
     }
GetPlayerSpawnPosition()
vec2 BaseGameMode::GetPlayerSpawnPosition (PlayerRecord & record) inline private
Definition at line 1814 of file BaseGameMode.as.
References g_spawnPos, LoadGame, and m_startMode.
Referenced by SpawnPlayer(), SpawnPlayerCorpse(), and SpawnPlayers().
     {
         /*
         if (m_spawnedInitial)
             return g_spawnPos;
         int index = record.peer;
         int count = g_players.length();
         float dist = (count > 4 ? 16.0f : 32.0f);
         float maxdist = (min(count, 8) - 1) * dist;
         return g_spawnPos + vec2(-(maxdist / 2.0f) + (index % 8) * dist, 0);
         */
         if (record.spawnPosSaved && m_startMode == StartMode::LoadGame)
             return record.spawnPos;
         return g_spawnPos;
     }
GetVignette()
vec4 BaseGameMode::GetVignette (int idt) inline private
Definition at line 1127 of file BaseGameMode.as.
References g_players, g_scene, GetLocalPlayerRecord(), lerp(), m_spectating, and m_spectatingPlayer.
     {
         if (!GetVarBool("ui_draw_vignette"))
             return vec4(0,0,0,0);
         PlayerRecord@ player = null;
         if (m_spectating)
             @player = g_players[m_spectatingPlayer];
         else
             @player = GetLocalPlayerRecord();
         float hp = (player !is null) ? player.CurrentHealthScalar() : 0;
         float timePulse = sin((g_scene.GetTime() + idt) * lerp(0.006, 0.003, hp / 3.0));
         vec4 vignette(0.7 + timePulse * 0.075, 0, 0, 0);
         if (hp <= 0.3)
             vignette.a = 1.0;
         return vignette;
     }
InitializePlayer()
void BaseGameMode::InitializePlayer (PlayerRecord & player) inline private
Definition at line 1681 of file BaseGameMode.as.
Referenced by ActivatePlayerRecord(), and Campaign::InitializePlayer().
     {
         player.hp = 1.0;
         player.armor = 0;
         if (player.level == 0)
             player.level = 1;
     }
IsUserWindowVisible()
bool BaseGameMode::IsUserWindowVisible () inline private
Definition at line 451 of file BaseGameMode.as.
References m_userWindows.
     {
         for (uint i = 0; i < m_userWindows.length(); i++)
         {
             if (m_userWindows[i].m_visible)
                 return true;
         }
         return false;
     }
LoadDungeonRotation()
void BaseGameMode::LoadDungeonRotation (SValue@ save) inline private
Definition at line 1533 of file BaseGameMode.as.
References DungeonRotation(), and m_rotation.
Referenced by RandomLevel::Generate(), Campaign::Start(), and Start().
     {
         if (m_rotation !is null)
             return;
         if (save !is null)
         {
             string rotationFilename = GetParamString(UnitPtr(), save, "rotation-file", false);
             if (rotationFilename != "")
                 @m_rotation = DungeonRotation(rotationFilename);
         }
         if (m_rotation is null)
         {
             PrintError("WARNING: Falling back to default dungeon rotation file!");
             @m_rotation = DungeonRotation("tweak/levels.sval");
         }
     }
LoadPlayer()
void BaseGameMode::LoadPlayer (SValue & data, PlayerRecord & player) inline private
Definition at line 1492 of file BaseGameMode.as.
References LoadArmorDef().
Referenced by ActivatePlayerRecord(), and Campaign::LoadPlayer().
     {
         player.hp = GetParamFloat(UnitPtr(), data, "hp", false, 1.0);
         player.mana = GetParamFloat(UnitPtr(), data, "mana", false, 1.0);
         player.armor = GetParamInt(UnitPtr(), data, "armor", false, 0);
         @player.armorDef = LoadArmorDef(GetParamInt(UnitPtr(), data, "armor-def", false));
         player.experience = GetParamInt(UnitPtr(), data, "experience", false, 0);
         player.level = GetParamInt(UnitPtr(), data, "level", false, 1);
         player.freeLivesTaken = GetParamInt(UnitPtr(), data, "free-lives-taken", false, 0);
         player.killsTotal = GetParamInt(UnitPtr(), data, "kills-total", false, 0);
         player.deathsTotal = GetParamInt(UnitPtr(), data, "deaths-total", false, 0);
         player.pickupsTotal = GetParamInt(UnitPtr(), data, "pickups-total", false, 0);
         if (player.hp <= 0.0f)
             player.deadTime = 1;
         //if (sMode != StartMode::Continue)
         {
             player.kills = GetParamInt(UnitPtr(), data, "kills", false, 0);
             player.deaths = GetParamInt(UnitPtr(), data, "deaths", false, 0);
             player.pickups = GetParamInt(UnitPtr(), data, "pickups", false, 0);
         }
         //print("Loaded plr hp: " + player.hp);
         //builder.PushVector2("pos", xy(player.actor.m_unit.GetPosition()));
         auto spawnPosData = data.GetDictionaryEntry("pos");
         if (spawnPosData is null)
             player.spawnPosSaved = false;
         else
         {
             player.spawnPosSaved = true;
             player.spawnPos = spawnPosData.GetVector2();
         }
     }
MenuBack()
bool BaseGameMode::MenuBack () inline private
Definition at line 840 of file BaseGameMode.as.
References DialogWindow::Close(), AGameMode::m_dialogWindow, m_userWindows, DialogWindow::m_visible, AGameMode::m_widgetInputFocus, and m_widgetScriptHosts.
Referenced by MainMenu::MenuBack().
     {
         if (m_widgetInputFocus !is null)
         {
             @m_widgetInputFocus = null;
             return true;
         }
         if (m_widgetScriptHosts.length() > 0)
         {
             m_widgetScriptHosts[0].Stop();
             return true;
         }
         for (int i = m_userWindows.length() - 1; i >= 0; i--)
         {
             if (m_userWindows[i].IsVisible())
             {
                 m_userWindows[i].Close();
                 return true;
             }
         }
         if (m_dialogWindow !is null && m_dialogWindow.m_visible)
         {
             m_dialogWindow.Close();
             return true;
         }
         return false;
     }
PlayerDied()
void BaseGameMode::PlayerDied (PlayerRecord@ player, PlayerRecord@ killer, DamageInfo di) inline private
Definition at line 1772 of file BaseGameMode.as.
     {
     }
PostStart()
void BaseGameMode::PostStart () inline private
Definition at line 1628 of file BaseGameMode.as.
References RefreshMultiplayerScaling(), and SpawnPlayers().
Referenced by Campaign::PostStart(), and ShortcutLevel::Start().
     {
         SpawnPlayers();
         /*
         if (loadedLevelStart !is null)
         {
             auto script = WorldScript::GetWorldScript(g_scene, loadedLevelStart);
             if (script !is null)
                 script.Execute();
         }
         */
         RefreshMultiplayerScaling();
     }
PreRenderFrame()
void BaseGameMode::PreRenderFrame (int idt) inline private
Definition at line 1157 of file BaseGameMode.as.
References GetCameraPos(), m_attachedEffects, m_camPos, m_preRenderables, PreRender(), unit, and xyz().
Referenced by Campaign::PreRenderFrame().
     {
         for (uint i = 0; i < m_preRenderables.length();)
         {
             if (m_preRenderables[i].PreRender(idt))
                 m_preRenderables.removeAt(i);
             else
                 i++;
         }
         for (uint i = 0; i < m_attachedEffects.length();)
         {
             if (m_attachedEffects[i].unit.IsDestroyed() || m_attachedEffects[i].effect.m_unit.IsDestroyed())
                 m_attachedEffects.removeAt(i);
             else
             {
                 m_attachedEffects[i].effect.m_unit.SetPosition(m_attachedEffects[i].unit.GetInterpolatedPosition(idt));
                 i++;
             }
         }
         GetCameraPos(idt);
         Sound::SetListener(xyz(m_camPos), vec3(0, 0, -1), vec3(0, -1, 0));
     }
RefreshMultiplayerScaling()
void BaseGameMode::RefreshMultiplayerScaling () inline private
Definition at line 1746 of file BaseGameMode.as.
References g_mpEnemyHealthScale, g_mpExpScale, g_players, GetLocalPlayerRecord(), max, and num.
Referenced by ActivatePlayerRecord(), AddPlayer(), PostStart(), and RemovePlayer().
     {
         int num = max(0, GetVarInt("g_extra_players"));
         int highLvl = 0;
         for (uint i = 0; i < g_players.length(); i++)
         {
             if (g_players[i].peer == 255)
                 continue;
             num++;
             highLvl = max(highLvl, g_players[i].level);
         }
         auto plr = GetLocalPlayerRecord();
         int lDiff = max(0, (plr is null ? highLvl : plr.level) - highLvl);
         g_mpEnemyHealthScale = (num - 1) * pow(num, -0.35) + max(0.0f, (num - 2) * 0.3f);
         g_mpExpScale = pow(0.9f,  num - 1) * pow(0.935, lDiff);
         print("MP enemy health scale: " + g_mpEnemyHealthScale + ", exp scale: " + g_mpExpScale);
     }
RefreshPlayerScene()
void BaseGameMode::RefreshPlayerScene (PlayerBase@ player, CustomUnitScene@ scene) inline private
Definition at line 1934 of file BaseGameMode.as.
Referenced by PlayerBase::RefreshScene().
     {
     }
RemovePlayer()
void BaseGameMode::RemovePlayer (uint8 peer, bool kicked) inline private
Definition at line 1730 of file BaseGameMode.as.
References PlayerHandler::GetPlayerRecord(), and RefreshMultiplayerScaling().
Referenced by Campaign::RemovePlayer().
     {
         auto plr = PlayerHandler::GetPlayerRecord(peer);
         if (plr is null)
             return;
         plr.peer = 255;
         if (plr.actor !is null)
         {
             plr.actor.m_unit.Destroy();
             @plr.actor = null;
         }
         RefreshMultiplayerScaling();
     }
RemoveWidgetRoot()
void BaseGameMode::RemoveWidgetRoot (IWidgetHoster@ host) inline override private
Definition at line 800 of file BaseGameMode.as.
References FocusTopRoot(), and m_widgetRoots.
     {
         int i = m_widgetRoots.findByRef(host);
         if (i != -1)
             m_widgetRoots.removeAt(i);
         FocusTopRoot();
     }
RenderFrame()
void BaseGameMode::RenderFrame (int idt, SpriteBatch & sb) inline private
Definition at line 1229 of file BaseGameMode.as.
References Center, DisplayPlayerHealth(), DisplayPlayerName(), DrawMouse(), g_players, g_scene, GetLocalPlayer(), GetLocalPlayerRecord(), Platform::GetSessionCount(), GetUIScale(), m_mice, m_spectating, m_spectatingPlayer, AGameMode::m_wndHeight, AGameMode::m_wndScale, AGameMode::m_wndWidth, RenderWidgets(), ShouldDisplayCursor(), ShouldDisplayPlayerNames(), text, ToScreenspace(), ToWorldspace(), and xy().
Referenced by Campaign::RenderFrame().
     {
         sb.PushTransformation(mat::scale(mat4(), GetUIScale()));
         for (uint i = 0; i < g_players.length(); i++)
         {
             PlayerRecord@ record = g_players[i];
             PlayerHusk@ plr = cast<PlayerHusk>(record.actor);
             if (plr is null)
                 continue;
             int showNames = GetVarInt("ui_draw_plr_names");
             bool willShowNames = false;
             if (showNames == 1)
                 willShowNames = true;
             else if (showNames == 0)
                 willShowNames = (cast<Town>(this) !is null);
             vec2 playerHuskPos = ToScreenspace(plr.m_unit.GetInterpolatedPosition(idt)) / m_wndScale;
             if (ShouldDisplayPlayerNames() && willShowNames)
                 DisplayPlayerName(sb, record, plr, playerHuskPos);
         }
         if (GetVarBool("ui_draw_plr_stats"))
         {
             for (uint i = 0; i < g_players.length(); i++)
             {
                 PlayerRecord@ record = g_players[i];
                 PlayerHusk@ plr = cast<PlayerHusk>(record.actor);
                 if (plr is null)
                     continue;
                 vec2 playerHuskPos = ToScreenspace(plr.m_unit.GetInterpolatedPosition(idt)) / m_wndScale;
                 DisplayPlayerHealth(sb, record, plr, playerHuskPos);
             }
         }
         if (GetVarBool("ui_draw_widgets"))
         {
 %PROFILE_START DrawWidgets
             PlayerRecord@ player = null;
             if (m_spectating)
                 @player = g_players[m_spectatingPlayer];
             else
                 @player = GetLocalPlayerRecord();
             sb.Begin(m_wndWidth, m_wndHeight, m_wndScale);
             RenderWidgets(player, idt, sb);
             sb.End();
 %PROFILE_STOP
         }
         if (GetVarBool("ui_player_measure") && m_mice.length() > 0)
         {
             auto player = GetLocalPlayer();
             if (player !is null)
             {
                 vec2 posMouse = m_mice[0].GetPos(idt);
                 vec3 posPlayer = player.m_unit.GetPosition();
                 vec3 posMouseWorld = ToWorldspace(posMouse);
                 auto font = Resources::GetBitmapFont("gui/fonts/font_hw8.fnt");
                 auto text = font.BuildText(round(dist(posPlayer, posMouseWorld)) + "px");
                 sb.DrawString((posMouse / m_wndScale) + vec2(-text.GetWidth() / 2, 12), text);
             }
         }
         if (GetVarBool("ui_cursor_unit") && m_mice.length() > 0)
         {
             vec2 posMouse = m_mice[0].GetPos(idt);
             vec3 posMouseWorld = ToWorldspace(posMouse);
             array<UnitPtr>@ units = g_scene.QueryCircle(xy(posMouseWorld), 8, ~0, RaycastType::Any, true);
             string strUnits = "";
             for (uint i = 0; i < units.length(); i++)
                 strUnits += units[i].GetDebugName() + "\n";
             auto font = Resources::GetBitmapFont("gui/fonts/font_hw8.fnt");
             auto text = font.BuildText(strUnits, -1, TextAlignment::Center);
             sb.DrawString((posMouse / m_wndScale) + vec2(-text.GetWidth() / 2, 20), text);
         }
         if (ShouldDisplayCursor())
             DrawMouse(idt, sb);
         int numSessions = Platform::GetSessionCount();
         int numPeer = GetLocalPlayerRecord().peer;
         vec4 borderColor = vec4(0, 0, 0, 1);
         if (numSessions > 1)
         {
             sb.Begin(m_wndWidth, m_wndHeight, m_wndScale);
             vec4 rect;
             if (numSessions == 2)
             {
                 if (numPeer == 0)
                     rect = vec4(m_wndWidth - 1, 0, 1, m_wndHeight);
                 else if (numPeer == 1)
                     rect = vec4(0, 0, 1, m_wndHeight);
                 sb.DrawSprite(null, rect, rect, borderColor);
             }
             else if (numSessions == 3 || numSessions == 4)
             {
                 if ((numPeer % 2) == 0)
                     rect = vec4(m_wndWidth - 1, 0, 1, m_wndHeight);
                 else if ((numPeer % 2) == 1)
                     rect = vec4(0, 0, 1, m_wndHeight);
                 sb.DrawSprite(null, rect, rect, borderColor);
                 if (numPeer < 2)
                     rect = vec4(0, m_wndHeight - 1, m_wndWidth, 1);
                 else
                     rect = vec4(0, 0, m_wndWidth, 1);
                 sb.DrawSprite(null, rect, rect, borderColor);
             }
             sb.End();
         }
         sb.PopTransformation();
     }
RenderWidgets()
void BaseGameMode::RenderWidgets (PlayerRecord@ player, int idt, SpriteBatch & sb) inline private
Definition at line 1361 of file BaseGameMode.as.
References WidgetInspector::Draw(), Draw(), DialogWindow::Draw(), g_debugWidgets, AGameMode::m_dialogWindow, m_filenameDef, m_hudSpectate, m_spectating, m_userWindows, m_widgetInspector, m_widgetRoots, m_widgetScriptHosts, and text.
Referenced by MainMenu::RenderFrame(), RenderFrame(), and Campaign::RenderWidgets().
     {
         for (uint i = 0; i < m_widgetScriptHosts.length(); i++)
             m_widgetScriptHosts[i].Draw(sb, idt);
         if (m_hudSpectate !is null && m_spectating)
             m_hudSpectate.Draw(sb, idt);
         for (uint i = 0; i < m_userWindows.length(); i++)
             m_userWindows[i].Draw(sb, idt);
         if (m_dialogWindow !is null)
             m_dialogWindow.Draw(sb, idt);
         if (g_debugWidgets)
         {
             string hosterDebug = "";
             hosterDebug += "\\cff0000Widget Roots\n";
             for (uint i = 0; i < m_widgetRoots.length(); i++)
                 hosterDebug += "\\caaaaaa" + i + " \\cffffff" + m_widgetRoots[i].m_filenameDef + "\n";
             BitmapFont@ fontDebug = Resources::GetBitmapFont("system/system_small.fnt");
             BitmapString@ text = fontDebug.BuildText(hosterDebug);
             sb.FillRectangle(vec4(10, 10, text.GetWidth(), text.GetHeight()), vec4(0, 0, 0, 0.7f));
             sb.DrawString(vec2(10, 10), text);
         }
         if (GetVarBool("inspect_widget"))
             m_widgetInspector.Draw(sb, idt);
     }
ReplaceTopWidgetRoot()
void BaseGameMode::ReplaceTopWidgetRoot (IWidgetHoster@ host) inline override private
Definition at line 818 of file BaseGameMode.as.
References FocusTopRoot(), and m_widgetRoots.
     {
         if (m_widgetRoots.length() == 0)
             m_widgetRoots.insertLast(host);
         else
             @m_widgetRoots[m_widgetRoots.length() - 1] = host;
         FocusTopRoot();
     }
ReplaceWidgetRoot()
void BaseGameMode::ReplaceWidgetRoot (IWidgetHoster@ find, IWidgetHoster@ replace) inline override private
Definition at line 808 of file BaseGameMode.as.
References FocusTopRoot(), and m_widgetRoots.
     {
         int i = m_widgetRoots.findByRef(find);
         if (i != -1)
             @m_widgetRoots[i] = replace;
         else
             m_widgetRoots.insertLast(replace);
         FocusTopRoot();
     }
ResizeWindow()
void BaseGameMode::ResizeWindow (int w, int h, float scale) inline private
Definition at line 552 of file BaseGameMode.as.
References DoLayout(), GetHUD(), GetUIScale(), m_widgetRoots, AGameMode::m_wndAspect, AGameMode::m_wndHeight, AGameMode::m_wndInvScaleTransform, AGameMode::m_wndScale, and AGameMode::m_wndWidth.
     {
         if(scale == 0 || w == 0 || h == 0)
             return;
         scale *= GetUIScale();
         m_wndWidth = int(w / scale);
         m_wndHeight = int(h / scale);
         m_wndAspect = m_wndWidth / float(m_wndHeight);
         m_wndScale = scale;
         m_wndInvScaleTransform = mat::scale(mat4(), 1.0 / scale);
         for (uint i = 0; i < m_widgetRoots.length(); i++)
             m_widgetRoots[i].DoLayout();
         auto hud = GetHUD();
         if (hud !is null)
             hud.DoLayout();
     }
RestartGame()
void BaseGameMode::RestartGame () inline private
Definition at line 1768 of file BaseGameMode.as.
     {
     }
Save() [1/2]
SValue BaseGameMode::Save () inline private
Definition at line 1394 of file BaseGameMode.as.
References m_levelCount.
Referenced by Town::Save(), and Campaign::Save().
     {
         SValueBuilder builder;
         builder.PushDictionary();
         builder.PushInteger("level-count", m_levelCount);
         Save(builder);
         return builder.Build();
     }
Save() [2/2]
void BaseGameMode::Save (SValueBuilder & builder) inline private
Definition at line 1403 of file BaseGameMode.as.
References g_flags, g_ngp, g_players, g_spawnPos, g_startId, GetLocalPlayerRecord(), Level, m_rotation, max, Run, MusicManager::Save(), QueuedTasks::Save(), and SavePlayer().
     {
         if (m_rotation !is null)
             builder.PushString("rotation-file", m_rotation.m_filename);
         builder.PushString("start-id", g_startId);
         builder.PushVector2("spawn-pos", g_spawnPos);
         int shortcut = 0;
         int numPlrs = 0;
         bool soulLinked = false;
         for (uint i = 0; i < g_players.length(); i++)
         {
             if (g_players[i].peer == 255)
                 continue;
             numPlrs++;
             shortcut = max(shortcut, g_players[i].shortcut);
             if (g_players[i].newGamePlus > g_ngp)
                 shortcut = 1000;
             if (g_players[i].soulLinks.length() > 0)
                 soulLinked = true;
         }
         builder.PushInteger("num-plrs", numPlrs);
         builder.PushInteger("shortcut", shortcut);
         if (soulLinked)
             builder.PushBoolean("soul-linked", true);
         MusicManager::Save(builder);
         QueuedTasks::Save(builder);
         auto flagKeys = g_flags.m_flags.getKeys();
         if (flagKeys.length() > 0)
         {
             builder.PushDictionary("flags");
             for (uint i = 0; i < flagKeys.length(); i++)
             {
                 int64 state;
                 g_flags.m_flags.get(flagKeys[i], state);
                 FlagState flag = FlagState(state);
                 if (flag == FlagState::Level)
                     builder.PushBoolean(flagKeys[i], false);
                 else if (flag == FlagState::Run)
                     builder.PushBoolean(flagKeys[i], true);
             }
             builder.PopDictionary();
         }
         SavePlayer(GetLocalPlayerRecord());
     }
SavePlayer() [1/2]
void BaseGameMode::SavePlayer (PlayerRecord & player, bool saveLevel = false, SValueBuilder@ town = null) inline private
Definition at line 1461 of file BaseGameMode.as.
Referenced by Save(), and Campaign::SavePlayer().
 { PrintError("Error: BaseGameMode::SavePlayer not implemented!!"); }
SavePlayer() [2/2]
void BaseGameMode::SavePlayer (SValueBuilder & builder, PlayerRecord & player) inline private
Definition at line 1463 of file BaseGameMode.as.
References xy().
     {
         if (player.IsDead() || player.hp <= 0)
             builder.PushFloat("hp", -1);
         else
             builder.PushFloat("hp", player.hp);
         builder.PushFloat("mana", player.mana);
         builder.PushInteger("armor", player.armor);
         builder.PushInteger("experience", player.experience);
         builder.PushInteger("level", player.level);
         builder.PushInteger("free-lives-taken", player.freeLivesTaken);
         builder.PushInteger("kills", player.kills);
         builder.PushInteger("kills-total", player.killsTotal);
         builder.PushInteger("deaths", player.deaths);
         builder.PushInteger("deaths-total", player.deathsTotal);
         builder.PushInteger("pickups", player.pickups);
         builder.PushInteger("pickups-total", player.pickupsTotal);
         if (player.armorDef !is null)
             builder.PushInteger("armor-def", player.armorDef.m_pathHash);
         if (player.actor !is null)
             builder.PushVector2("pos", xy(player.actor.m_unit.GetPosition()));
         if (player.runEnded)
             builder.PushBoolean("in-town", true);
     }
set_m_currCursorColor()
void BaseGameMode::set_m_currCursorColor (vec3 color) inline private
Definition at line 1948 of file BaseGameMode.as.
References _Deprecation9030(), and m_mice.
 { _Deprecation9030(); return m_mice[0].m_color; } void set_m_currCursorColor(vec3 color) { _Deprecation9030(); m_mice[0].m_color = color; }
set_m_currCursorColorC()
void BaseGameMode::set_m_currCursorColorC (int c) inline private
Definition at line 1947 of file BaseGameMode.as.
References _Deprecation9030(), and m_mice.
 { _Deprecation9030(); return m_mice[0].m_colorC; } void set_m_currCursorColorC(int c) { _Deprecation9030(); m_mice[0].m_colorC = c; }
set_m_mousePos()
void BaseGameMode::set_m_mousePos (vec2 p) inline private
Definition at line 1944 of file BaseGameMode.as.
References _Deprecation9030(), and m_mice.
 { _Deprecation9030(); return m_mice[0].m_pos; } void set_m_mousePos(vec2 p) { _Deprecation9030(); m_mice[0].m_pos = p; }
set_m_mousePosPrev()
void BaseGameMode::set_m_mousePosPrev (vec2 p) inline private
Definition at line 1943 of file BaseGameMode.as.
References _Deprecation9030(), and m_mice.
 { _Deprecation9030(); return m_mice[0].m_posPrev; } void set_m_mousePosPrev(vec2 p) { _Deprecation9030(); m_mice[0].m_posPrev = p; }
set_m_mouseReal()
void BaseGameMode::set_m_mouseReal (bool real) inline private
Definition at line 1942 of file BaseGameMode.as.
References _Deprecation9030(), and m_mice.
 { _Deprecation9030(); return m_mice[0].m_real; } void set_m_mouseReal(bool real) { _Deprecation9030(); m_mice[0].m_real = real; }
set_m_showCursor()
void BaseGameMode::set_m_showCursor (bool b) inline private
Definition at line 1946 of file BaseGameMode.as.
References _Deprecation9030(), and _m_showCursor.
 { _Deprecation9030(); return _m_showCursor; } void set_m_showCursor(bool b) { _Deprecation9030(); _m_showCursor = b; } bool _m_showCursor = true;
set_m_usingRealCursor()
void BaseGameMode::set_m_usingRealCursor (bool b) inline private
Definition at line 1945 of file BaseGameMode.as.
References _Deprecation9030(), and get_m_mouseReal().
 { _Deprecation9030(); return get_m_mouseReal(); } void set_m_usingRealCursor(bool b) { _Deprecation9030(); set_m_mouseReal(b); }
SetCursorGame()
void BaseGameMode::SetCursorGame () inline private
Definition at line 872 of file BaseGameMode.as.
References Platform::CursorAimNormal, Platform::HideCursor(), AGameMode::m_currCursor, and m_usingUICursor.
Referenced by UpdateCurrentCursor().
     {
         if (m_currCursor is Platform::CursorAimNormal)
             return;
         m_usingUICursor = false;
         @m_currCursor = Platform::CursorAimNormal;
         Platform::HideCursor();
     }
SetCursorUI()
void BaseGameMode::SetCursorUI () inline private
Definition at line 883 of file BaseGameMode.as.
References Platform::CursorNormal, Platform::HideCursor(), AGameMode::m_currCursor, Widget::m_cursor, Widget::m_hovering, m_usingUICursor, AGameMode::m_widgetUnderCursor, and Platform::ShowCursor().
Referenced by UpdateCurrentCursor().
     {
         Platform::CursorInfo@ cursor = m_currCursor;
         if (m_widgetUnderCursor !is null && m_widgetUnderCursor.m_hovering && m_widgetUnderCursor.m_cursor !is null)
             @cursor = m_widgetUnderCursor.m_cursor;
         else
             @cursor = Platform::CursorNormal;
         if (m_currCursor is cursor)
             return;
         m_usingUICursor = true;
         @m_currCursor = cursor;
         if (GetVarBool("ui_hardware_cursor"))
             Platform::ShowCursor();
         else
             Platform::HideCursor();
     }
SetExclusiveWidgetRoot()
void BaseGameMode::SetExclusiveWidgetRoot (IWidgetHoster@ host) inline override private
Definition at line 827 of file BaseGameMode.as.
References FocusTopRoot(), and m_widgetRoots.
     {
         m_widgetRoots.removeRange(0, m_widgetRoots.length());
         m_widgetRoots.insertLast(host);
         FocusTopRoot();
     }
ShakeScreen()
ScreenShake BaseGameMode::ShakeScreen (int tm, float amount, vec3 pos = vec3(), float range = -1.0f) inline private
Definition at line 575 of file BaseGameMode.as.
References ScreenShake::m_amount, ScreenShake::m_position, ScreenShake::m_range, m_screenShake, ScreenShake::m_time, and ScreenShake::m_timeC.
     {
         float scale = GetVarFloat("g_screenshake");
         if (scale <= 0.0f)
             return null;
         ScreenShake@ newShake = ScreenShake();
         newShake.m_time = newShake.m_timeC = tm;
         newShake.m_amount = amount * scale;
         newShake.m_position = pos;
         newShake.m_range = range;
         m_screenShake.insertLast(newShake);
         return newShake;
     }
ShouldDisplayCursor()
bool BaseGameMode::ShouldDisplayCursor () inline private
Definition at line 529 of file BaseGameMode.as.
References IsPaused(), AGameMode::m_currInput, AGameMode::m_dialogWindow, m_userWindows, DialogWindow::m_visible, and m_widgetScriptHosts.
Referenced by RenderFrame(), Campaign::UpdateFrame(), and Campaign::UpdatePausedFrame().
     {
         for (uint i = 0; i < m_widgetScriptHosts.length(); i++)
         {
             if (m_widgetScriptHosts[i].ShouldDisplayCursor())
                 return true;
         }
         for (uint i = 0; i < m_userWindows.length(); i++)
         {
             if (m_userWindows[i].IsVisible())
                 return true;
         }
         if (m_dialogWindow !is null && m_dialogWindow.m_visible)
             return true;
         if (!IsPaused() && m_currInput !is null && !m_currInput.UsingGamepad)
             return true;
         return false;
     }
ShouldDisplayPlayerNames()
bool BaseGameMode::ShouldDisplayPlayerNames () inline private
Definition at line 1148 of file BaseGameMode.as.
Referenced by RenderFrame().
     {
 %if CFG_SPLITSCREEN
         return false;
 %else
         return true;
 %endif
     }
ShouldFreezeControls()
bool BaseGameMode::ShouldFreezeControls () inline private
Definition at line 512 of file BaseGameMode.as.
References AGameMode::m_dialogWindow, m_userWindows, DialogWindow::m_visible, and m_widgetScriptHosts.
Referenced by Campaign::UpdateWidgets().
     {
         for (uint i = 0; i < m_widgetScriptHosts.length(); i++)
         {
             if (m_widgetScriptHosts[i].ShouldFreezeControls())
                 return true;
         }
         for (uint i = 0; i < m_userWindows.length(); i++)
         {
             if (m_userWindows[i].IsVisible())
                 return true;
         }
         return (m_dialogWindow !is null && m_dialogWindow.m_visible);
     }
ShowDialog() [1/2]
void BaseGameMode::ShowDialog (string id, string question, string buttonYes, string buttonNo, IWidgetHoster@ returnHost) inline override private
Definition at line 403 of file BaseGameMode.as.
References AddWidgetRoot(), AGameMode::m_dialogWindow, AGameMode::m_guiBuilder, DialogWindow::m_visible, DialogWindow::SetButtonNo(), DialogWindow::SetButtonYes(), DialogWindow::SetID(), DialogWindow::SetQuestion(), and DialogWindow::SetReturnHost().
Referenced by MainMenu::LobbyInviteAccepted(), and MainMenu::UpdateFrame().
     {
         if (m_dialogWindow is null)
             @m_dialogWindow = DialogWindow(m_guiBuilder);
         m_dialogWindow.SetID(id);
         m_dialogWindow.SetButtonYes(buttonYes);
         m_dialogWindow.SetButtonNo(buttonNo);
         m_dialogWindow.SetReturnHost(returnHost);
         m_dialogWindow.SetQuestion(question);
         m_dialogWindow.m_visible = true;
         AddWidgetRoot(m_dialogWindow);
     }
ShowDialog() [2/2]
void BaseGameMode::ShowDialog (string id, string message, string button, IWidgetHoster@ returnHost) inline override private
Definition at line 417 of file BaseGameMode.as.
References AddWidgetRoot(), AGameMode::m_dialogWindow, AGameMode::m_guiBuilder, DialogWindow::m_visible, DialogWindow::SetButtonNo(), DialogWindow::SetButtonYes(), DialogWindow::SetID(), DialogWindow::SetQuestion(), and DialogWindow::SetReturnHost().
     {
         if (m_dialogWindow is null)
             @m_dialogWindow = DialogWindow(m_guiBuilder);
         m_dialogWindow.SetID(id);
         m_dialogWindow.SetButtonYes("");
         m_dialogWindow.SetButtonNo(button);
         m_dialogWindow.SetReturnHost(returnHost);
         m_dialogWindow.SetQuestion(message);
         m_dialogWindow.m_visible = true;
         AddWidgetRoot(m_dialogWindow);
     }
ShowInputDialog()
void BaseGameMode::ShowInputDialog (string id, string message, IWidgetHoster@ returnHost, string defaultInput = "") inline override private
Definition at line 431 of file BaseGameMode.as.
References AddWidgetRoot(), DialogWindow::FocusInput(), AGameMode::m_dialogWindow, AGameMode::m_guiBuilder, DialogWindow::m_visible, DialogWindow::SetID(), DialogWindow::SetInput(), DialogWindow::SetQuestion(), and DialogWindow::SetReturnHost().
     {
         if (m_dialogWindow is null)
             @m_dialogWindow = DialogWindow(m_guiBuilder);
         m_dialogWindow.SetID(id);
         m_dialogWindow.SetInput(defaultInput);
         m_dialogWindow.SetReturnHost(returnHost);
         m_dialogWindow.SetQuestion(message);
         m_dialogWindow.m_visible = true;
         AddWidgetRoot(m_dialogWindow);
         m_dialogWindow.FocusInput();
     }
ShowOffscreenPlayer()
bool BaseGameMode::ShowOffscreenPlayer (PlayerBase@ player) inline private
Definition at line 446 of file BaseGameMode.as.
     {
         return true;
     }
ShowUserWindow() [1/2]
void BaseGameMode::ShowUserWindow (string id) inline private
Definition at line 461 of file BaseGameMode.as.
References m_userWindows, and Show.
     {
         for (uint i = 0; i < m_userWindows.length(); i++)
         {
             if (m_userWindows[i].GetScriptID() == id && !m_userWindows[i].m_visible)
                 m_userWindows[i].Show();
             else if (m_userWindows[i].m_visible)
                 m_userWindows[i].Close();
         }
     }
ShowUserWindow() [2/2]
void BaseGameMode::ShowUserWindow (UserWindow@ window) inline private
Definition at line 472 of file BaseGameMode.as.
References m_userWindows.
     {
         for (uint i = 0; i < m_userWindows.length(); i++)
         {
             if (m_userWindows[i] is window && !m_userWindows[i].m_visible)
                 m_userWindows[i].Show();
             else if (m_userWindows[i].m_visible)
                 m_userWindows[i].Close();
         }
     }
SpawnPlayer()
void BaseGameMode::SpawnPlayer (int i, vec2 pos = vec2(-1, -1), int unitId = 0, uint team = 0) inline override private
Definition at line 1833 of file BaseGameMode.as.
References g_players, g_scene, GetPlayerSpawnPosition(), Initialize(), unit, xy(), and xyz().
Referenced by AttemptRespawn(), and SpawnPlayers().
     {
         if (g_players[i].peer == 255)
             return;
         if (g_players[i].actor !is null)
             return;
         if (team > 0)
             g_players[i].team = team;
         UnitPtr unit;
         vec3 spawnPos = xyz(pos);
         if (Network::IsServer() && pos.x == -1 && pos.y == -1)
             spawnPos = xyz(GetPlayerSpawnPosition(g_players[i]));
         if (g_players[i].local)
             unit = Resources::GetUnitProducer("players/player.unit").Produce(g_scene, spawnPos, unitId);
         else
             unit = Resources::GetUnitProducer("players/player_husk.unit").Produce(g_scene, spawnPos, unitId);
         g_players[i].AssignUnit(unit);
         if (team > 0)
             g_players[i].actor.SetTeam(team, false);
         if (Network::IsServer())
             (Network::Message("SpawnPlayer") << g_players[i].peer << xy(unit.GetPosition()) << unit.GetId() << team).SendToAll();
         cast<PlayerBase>(unit.GetScriptBehavior()).Initialize(g_players[i]);
         Hooks::Call("GameModeSpawnPlayer", @this, @g_players[i]);
     }
SpawnPlayerCorpse()
void BaseGameMode::SpawnPlayerCorpse (int i, vec2 pos = vec2(-1, -1)) inline override private
Definition at line 1867 of file BaseGameMode.as.
References g_players, g_scene, GetPlayerSpawnPosition(), unit, xy(), and xyz().
Referenced by SpawnPlayers().
     {
         if (g_players[i].peer == 255)
             return;
         if (g_players[i].actor !is null)
             return;
         UnitPtr unit;
         vec3 spawnPos = xyz(pos);
         if (Network::IsServer() && pos.x == -1 && pos.y == -1)
             spawnPos = xyz(GetPlayerSpawnPosition(g_players[i]));
         auto corpse = Resources::GetUnitProducer("players/player_corpse.unit").Produce(g_scene, spawnPos);
         @g_players[i].corpse = cast<PlayerCorpse>(corpse.GetScriptBehavior());
         g_players[i].corpse.Initialize(g_players[i]);
         if (Network::IsServer())
             (Network::Message("SpawnPlayerCorpse") << g_players[i].peer << xy(spawnPos)).SendToAll();
     }
SpawnPlayers()
void BaseGameMode::SpawnPlayers () inline private
Definition at line 1776 of file BaseGameMode.as.
References g_players, g_spawnPos, GetPlayerSpawnPosition(), m_spawnedInitial, SpawnPlayer(), and SpawnPlayerCorpse().
Referenced by PostStart().
     {
     /*
         if (!Network::IsServer())
             return;
     */
         bool isTown = cast<Town>(this) !is null;
         for (uint i = 0; i < g_players.length(); i++)
         {
             auto record = g_players[i];
             if (!record.local)
                 continue;
             vec2 spawnPos(-1, -1);
             if (g_spawnPos.x != 0 || g_spawnPos.y != 0)
                 spawnPos = GetPlayerSpawnPosition(record);
             if (g_players[i].hp <= 0 && !isTown)
             {
                 if (Network::IsServer())
                     SpawnPlayerCorpse(i);
                 else
                     (Network::Message("SpawnPlayerCorpse") << g_players[i].peer << spawnPos).SendToHost();
             }
             else
             {
                 if (Network::IsServer())
                     SpawnPlayer(i);
                 else
                     (Network::Message("SpawnPlayer") << g_players[i].peer << spawnPos << 0 << 0).SendToHost();
             }
         }
         m_spawnedInitial = true;
     }
SpectateNextPlayer()
void BaseGameMode::SpectateNextPlayer () inline private
Definition at line 762 of file BaseGameMode.as.
References g_players, IsDead(), m_spectatingPlayer, and SpectateUpdateHUD().
Referenced by UpdateFrame().
     {
         int startIndex = m_spectatingPlayer;
         do
         {
             m_spectatingPlayer++;
             if (uint(m_spectatingPlayer) >= g_players.length())
                 m_spectatingPlayer = 0;
         }
         while (m_spectatingPlayer != startIndex && g_players[m_spectatingPlayer].IsDead());
         SpectateUpdateHUD();
     }
SpectateUpdateHUD()
void BaseGameMode::SpectateUpdateHUD () inline private
Definition at line 734 of file BaseGameMode.as.
References g_players, m_spectating, and m_spectatingPlayer.
Referenced by BeginSpectating(), and SpectateNextPlayer().
     {
         if (!m_spectating)
             return;
         auto spectatingRecord = g_players[m_spectatingPlayer];
         auto spectatingPlayer = cast<PlayerHusk>(spectatingRecord.actor);
     }
Start()
void BaseGameMode::Start (uint8 peer, SValue@ save, StartMode sMode) inline private
Definition at line 1552 of file BaseGameMode.as.
References ActivatePlayerRecord(), Continue, g_flags, g_spawnPos, g_useSpawnPos, Level, MusicManager::Load(), QueuedTasks::Load(), LoadDungeonRotation(), m_levelStarts, m_started, m_startMode, m_useSpawnLogic, Run, StartGame, and xy().
Referenced by Campaign::Start().
     {
         m_startMode = sMode;
         LoadDungeonRotation(save);
         ActivatePlayerRecord(peer);
         bool loadedStartPos = false;
         WorldScript::LevelStart@ loadedLevelStart = null;
         if (m_useSpawnLogic)
         {
             if ((sMode == StartMode::Continue || sMode == StartMode::StartGame) && !g_useSpawnPos)
             {
                 string startId = "";
                 auto startIdV = (save !is null) ? save.GetDictionaryEntry("start-id") : null;
                 if (startIdV !is null && startIdV.GetType() == SValueType::String)
                     startId = startIdV.GetString();
                 for (uint i = 0; i < m_levelStarts.length(); i++)
                 {
                     if (m_levelStarts[i].StartID == startId)
                     {
                         g_spawnPos = xy(m_levelStarts[i].Position);
                         loadedStartPos = true;
                         @loadedLevelStart = m_levelStarts[i];
                         break;
                     }
                 }
             }
             if (!loadedStartPos && save !is null)
             {
                 auto spawnPosV = save.GetDictionaryEntry("spawn-pos");
                 if (spawnPosV !is null && spawnPosV.GetType() == SValueType::Vector2)
                     g_spawnPos = spawnPosV.GetVector2();
             }
         }
         if (save !is null)
         {
             if (sMode != StartMode::Continue)
             {
                 MusicManager::Load(save);
                 QueuedTasks::Load(save);
             }
             auto flagsData = save.GetDictionaryEntry("flags");
             if (flagsData !is null && flagsData.GetType() == SValueType::Dictionary)
             {
                 auto flagsDict = flagsData.GetDictionary();
                 auto flagsKeys = flagsDict.getKeys();
                 for (uint i = 0; i < flagsKeys.length(); i++)
                 {
                     SValue@ flagData = null;
                     if (!flagsDict.get(flagsKeys[i], @flagData))
                         continue;
                     if (flagData is null || flagData.GetType() != SValueType::Boolean)
                         continue;
                     bool persistent = flagData.GetBoolean();
                     if (!persistent && sMode == StartMode::Continue)
                         continue;
                     g_flags.Set(flagsKeys[i], persistent ? FlagState::Run : FlagState::Level);
                 }
             }
         }
         m_started = true;
     }
StopSpectating()
void BaseGameMode::StopSpectating () inline private
Definition at line 743 of file BaseGameMode.as.
References m_spectating.
Referenced by ToggleSpectating().
     {
         m_spectating = false;
     }
ToggleSpectating()
void BaseGameMode::ToggleSpectating () inline private
Definition at line 754 of file BaseGameMode.as.
References BeginSpectating(), m_spectating, and StopSpectating().
Referenced by Campaign::UpdateWidgets().
     {
         if (m_spectating)
             StopSpectating();
         else
             BeginSpectating();
     }
ToggleUserWindow()
void BaseGameMode::ToggleUserWindow (UserWindow@ window) inline private
Definition at line 492 of file BaseGameMode.as.
References m_userWindows.
Referenced by Campaign::UpdateWidgets().
     {
         for (uint i = 0; i < m_userWindows.length(); i++)
         {
             if (m_userWindows[i] !is window && m_userWindows[i].m_visible)
                 m_userWindows[i].Close();
         }
         for (uint i = 0; i < m_userWindows.length(); i++)
         {
             if (m_userWindows[i] is window)
             {
                 if (window.m_visible)
                     window.Close();
                 else
                     window.Show();
             }
         }
     }
UpdateCurrentCursor()
void BaseGameMode::UpdateCurrentCursor () inline private
Definition at line 903 of file BaseGameMode.as.
References m_widgetRoots, SetCursorGame(), and SetCursorUI().
Referenced by UpdateWidgets().
     {
         if (m_widgetRoots.length() == 0)
             SetCursorGame();
         else
             SetCursorUI();
     }
UpdateFrame()
void BaseGameMode::UpdateFrame (int ms, GameInput & gameInput, MenuInput & menuInput) inline private
Definition at line 633 of file BaseGameMode.as.
References g_floatingTexts, g_players, g_scene, m_alive, m_attachedSounds, m_camPos, AGameMode::m_currInput, AGameMode::m_currInputMenu, AGameMode::m_gameTime, m_screenShake, m_showOverheadBossBars, m_spectating, SpectateNextPlayer(), unit, MusicManager::Update(), QueuedTasks::Update(), UpdateGibs(), UpdateMouse(), UpdateWidgets(), and xy().
Referenced by MainMenu::UpdateFrame(), and Campaign::UpdateFrame().
     {
         m_gameTime += ms;
         MusicManager::Update(ms);
         QueuedTasks::Update(ms);
         m_showOverheadBossBars = GetVarBool("ui_hud_bossbar_actors");
         for (uint i = 0; i < m_screenShake.length(); i++)
         {
             m_screenShake[i].Update(ms);
             if (m_screenShake[i].m_timeC <= 0)
                 m_screenShake.removeAt(i--);
         }
         @m_currInput = gameInput;
         @m_currInputMenu = menuInput;
         array<vec2> pingPos;
         for (uint i = 0; i < g_players.length(); i++)
         {
             auto a = g_players[i].actor;
             if (a !is null)
             {
                 pingPos.insertLast(xy(a.m_unit.GetPosition()));
                 continue;
             }
             auto c = g_players[i].corpse;
             if (c !is null)
             {
                 pingPos.insertLast(xy(c.m_unit.GetPosition()));
                 continue;
             }
         }
         if (pingPos.length() == 0)
             pingPos.insertLast(m_camPos);
         g_scene.Ping(pingPos);
         if (m_spectating)
         {
             if (gameInput.Attack1.Pressed && !gameInput.Ping.Down)
                 SpectateNextPlayer();
         }
         UpdateWidgets(ms, gameInput, menuInput);
         UpdateGibs(ms);
 %PROFILE_START AttachedSounds
         for (uint i = 0; i < m_attachedSounds.length();)
         {
             if (m_attachedSounds[i].unit.IsDestroyed() || !m_attachedSounds[i].sound.IsPlaying())
                 m_attachedSounds.removeAt(i);
             else
             {
                 m_attachedSounds[i].sound.SetPosition(m_attachedSounds[i].unit.GetPosition());
                 i++;
             }
         }
 %PROFILE_STOP
 %PROFILE_START FloatingTexts
         for (uint i = 0; i < g_floatingTexts.length();)
         {
             g_floatingTexts[i].Update(ms);
             if (!g_floatingTexts[i].m_alive)
                 g_floatingTexts.removeAt(i);
             else
                 i++;
         }
 %PROFILE_STOP
         UpdateMouse(ms, gameInput, menuInput);
         if (randi(1000) == 0)
         {
             pfloat a = 0.0f;
             assert(a, 0.0f);
             a = 0.5f;
             assert(a, 0.5f);
             a = 0.95f;
             assert(a, 0.95f);
             float x = a;
             a -= 0.5f; x -= 0.5f;
             assert(a, x);
             pint b = 199;
             assert(b, 199);
             b = 57;
             assert(b, 57);
             b = 0;
             assert(b, 0);
         }
     }
UpdateMouse()
void BaseGameMode::UpdateMouse (int ms, GameInput & gameInput, MenuInput & menuInput) inline private
Definition at line 598 of file BaseGameMode.as.
References m_mice, and Update().
Referenced by UpdateFrame(), and UpdatePausedFrame().
     {
         for (uint i = 0; i < m_mice.length(); i++)
             m_mice[i].Update(ms);
     }
UpdatePausedFrame()
void BaseGameMode::UpdatePausedFrame (int ms, GameInput & gameInput, MenuInput & menuInput) inline private
Definition at line 624 of file BaseGameMode.as.
References AGameMode::m_currInput, AGameMode::m_currInputMenu, UpdateMouse(), and UpdateWidgets().
Referenced by Campaign::UpdatePausedFrame().
     {
         @m_currInput = gameInput;
         @m_currInputMenu = menuInput;
         UpdateWidgets(ms, gameInput, menuInput);
         UpdateMouse(ms, gameInput, menuInput);
     }
UpdateWidgets()
void BaseGameMode::UpdateWidgets (int ms, GameInput & gameInput, MenuInput & menuInput) inline private
Definition at line 911 of file BaseGameMode.as.
References BlocksLower(), Down, ButtonState::Down, MenuInput::Down, FirstFocusable(), Widget::FocusTowards(), MenuInput::Forward, g_doubleClickTime, g_menuTime, GetMousePos(), Left, MenuInput::Left, Widget::m_canDoubleClick, Widget::m_canFocus, Widget::m_canFocusInput, AGameMode::m_dialogWindow, Widget::m_doubleClickPos, Widget::m_doubleClickTime, Widget::m_host, Widget::m_hovering, m_hudSpectate, m_mice, Widget::m_origin, Widget::m_parent, Widget::m_priorityFocus, m_spectating, m_switchingWidgetHoster, m_userWindows, Widget::m_visible, m_widget, AGameMode::m_widgetInputFocus, m_widgetInspector, m_widgetRoots, m_widgetScriptHosts, AGameMode::m_widgetUnderCursor, AGameMode::m_wndHeight, AGameMode::m_wndScale, AGameMode::m_wndWidth, Widget::OnClick(), Widget::OnDoubleClick(), Widget::OnMouseDown(), Widget::OnMouseUp(), ButtonState::Pressed, ButtonState::Released, Right, MenuInput::Right, Up, MenuInput::Up, WidgetInspector::Update(), HUDSpectate::Update(), DialogWindow::Update(), Update(), UpdateCurrentCursor(), and Widget::UpdateInput().
Referenced by UpdateFrame(), UpdatePausedFrame(), and Campaign::UpdateWidgets().
     {
         g_menuTime += ms;
         if (m_mice.length() == 0)
             m_mice.insertLast(IngameMouse(gameInput, menuInput));
         else
         {
             @m_mice[0].m_inputGame = gameInput;
             @m_mice[0].m_inputMenu = menuInput;
         }
         UpdateCurrentCursor();
         int width = m_wndWidth;
         int height = m_wndHeight;
         float scale = m_wndScale;
         for (uint i = 0; i < m_widgetScriptHosts.length(); i++)
             m_widgetScriptHosts[i].Update(ms);
         for (uint i = 0; i < m_userWindows.length(); i++)
             m_userWindows[i].Update(ms);
         if (m_hudSpectate !is null && m_spectating)
             m_hudSpectate.Update(ms);
         bool ignoreInput = false;
         if (m_widgetInputFocus !is null)
             ignoreInput = m_widgetInputFocus.UpdateInput(gameInput);
         bool underCursorValid = m_widgetUnderCursor !is null;
         if (underCursorValid)
         {
             bool inRoots = false;
             for (uint i = 0; i < m_widgetRoots.length(); i++)
             {
                 if (m_widgetUnderCursor.m_host is m_widgetRoots[i])
                 {
                     inRoots = true;
                     break;
                 }
             }
             if (!inRoots)
                 underCursorValid = false;
         }
         if (!underCursorValid)
             @m_widgetUnderCursor = null;
         for (int i = int(m_widgetRoots.length()) - 1; i >= 0; i--)
         {
             vec2 mousePos = GetMousePos();
             m_widgetRoots[i].UpdateInput(vec2(), vec2(width, height), vec3(mousePos.x / scale, mousePos.y / scale, gameInput.MouseWheelDelta));
             if (m_widgetRoots[i].BlocksLower())
                 break;
         }
         if (menuInput.Forward.Released)
         {
             if (m_widgetInputFocus !is null && !m_widgetInputFocus.m_hovering && !m_widgetInputFocus.m_priorityFocus)
             {
                 @m_widgetInputFocus = null;
                 if (ignoreInput)
                     ignoreInput = false;
             }
             else if (m_widgetUnderCursor !is null && m_widgetUnderCursor.m_canFocusInput)
                 @m_widgetInputFocus = m_widgetUnderCursor;
         }
         if (ignoreInput)
             return;
         if (m_switchingWidgetHoster)
         {
             if (!menuInput.Forward.Pressed && !menuInput.Forward.Down && !menuInput.Forward.Released)
                 m_switchingWidgetHoster = false;
         }
         // Widgets that can be interacted with must be visible and must have a parent accompanying their child at all times.
         if (m_widgetUnderCursor !is null && (!m_widgetUnderCursor.m_visible || m_widgetUnderCursor.m_parent is null))
             @m_widgetUnderCursor = null;
         if (m_widgetUnderCursor !is null && m_widgetUnderCursor.m_canFocus)
         {
             auto w = m_widgetUnderCursor;
             if (w.m_hovering && !m_switchingWidgetHoster)
             {
                 Widget@ wb = w;
                 while (wb !is null) {
                     bool propogate = true;
                     vec2 mousePosRel = (GetMousePos() / m_wndScale) - wb.m_origin;
                     if (menuInput.Forward.Pressed)
                         propogate = !wb.OnMouseDown(mousePosRel);
                     else if (menuInput.Forward.Released)
                     {
                         if (wb.m_canDoubleClick && wb.m_doubleClickTime > 0 && (int(wb.m_doubleClickPos.x) == int(mousePosRel.x) && int(wb.m_doubleClickPos.y) == int(mousePosRel.y)))
{
                             wb.m_doubleClickTime = 0;
                             propogate = !wb.OnDoubleClick(mousePosRel);
                         }
                         else
{
                             wb.m_doubleClickTime = g_doubleClickTime;
                             wb.m_doubleClickPos = mousePosRel;
                             propogate = !wb.OnClick(mousePosRel);
                         }
                         if (wb.OnMouseUp(mousePosRel))
                             propogate = false;
                     }
                     if (!propogate)
                         break;
                     @wb = wb.m_parent;
                 }
             }
             bool changedFocus = false;
             if (menuInput.Up.Pressed)
                 changedFocus = w.FocusTowards(WidgetDirection::Up);
             else if (menuInput.Down.Pressed)
                 changedFocus = w.FocusTowards(WidgetDirection::Down);
             if (menuInput.Left.Pressed)
                 changedFocus = w.FocusTowards(WidgetDirection::Left);
             else if (menuInput.Right.Pressed)
                 changedFocus = w.FocusTowards(WidgetDirection::Right);
             if (changedFocus)
                 w.SetHovering(false, w.GetCenter(), true);
         }
         else if (menuInput.Up.Pressed || menuInput.Down.Pressed || menuInput.Left.Pressed || menuInput.Right.Pressed)
         {
             // give focus to the first focusable widget we can find
             for (uint i = 0; i < m_widgetRoots.length(); i++)
             {
                 auto w = FirstFocusable(m_widgetRoots[i].m_widget);
                 if (w !is null)
                 {
                     w.SetHovering(true, w.GetCenter(), true);
                     break;
                 }
             }
         }
         if (m_dialogWindow !is null)
             m_dialogWindow.Update(ms);
         if (GetVarBool("inspect_widget"))
             m_widgetInspector.Update(ms);
     }
Member Data Documentation
_Deprecation9030Printed
bool BaseGameMode::_Deprecation9030Printed private
Definition at line 1941 of file BaseGameMode.as.
_m_showCursor
bool BaseGameMode::_m_showCursor = true private
Definition at line 1946 of file BaseGameMode.as.
Referenced by set_m_showCursor().
m_arrBosses
array<OverheadBossBar@> BaseGameMode::m_arrBosses private
Definition at line 192 of file BaseGameMode.as.
Referenced by AddBossBarActor(), DrawOverheadBossBars(), and GetBossBarActor().
m_camPos
vec2 BaseGameMode::m_camPos private
Definition at line 172 of file BaseGameMode.as.
Referenced by GetCameraPos(), Campaign::PreRenderFrame(), PreRenderFrame(), ResolveGibs(), and UpdateFrame().
m_camPosLastLocal
vec2 BaseGameMode::m_camPosLastLocal private
Definition at line 173 of file BaseGameMode.as.
Referenced by GetCameraPos().
m_camPosLastLocalSet
bool BaseGameMode::m_camPosLastLocalSet private
Definition at line 174 of file BaseGameMode.as.
Referenced by GetCameraPos().
m_extraLives
int BaseGameMode::m_extraLives private
Definition at line 203 of file BaseGameMode.as.
Referenced by Campaign::UpdateWidgets().
m_fntPlayerName
BitmapFont BaseGameMode::m_fntPlayerName private
Definition at line 199 of file BaseGameMode.as.
Referenced by BaseGameMode(), and DisplayPlayerName().
m_gameOver
GameOver BaseGameMode::m_gameOver private
Definition at line 189 of file BaseGameMode.as.
Referenced by Campaign::Campaign(), GameModeHandler::GameOver(), Campaign::PlayerDied(), Campaign::RenderWidgets(), and Campaign::UpdateWidgets().
m_hudSpectate
HUDSpectate BaseGameMode::m_hudSpectate private
Definition at line 188 of file BaseGameMode.as.
Referenced by BaseGameMode(), RenderWidgets(), and UpdateWidgets().
m_levelCount
int BaseGameMode::m_levelCount private
Definition at line 204 of file BaseGameMode.as.
Referenced by RandomLevel::Generate(), Campaign::HandicapCalculate(), RandomLevel::PostStart(), Campaign::PostStart(), Save(), StaticLevel::Start(), ShortcutLevel::Start(), BossLevel::Start(), TestLevel::Start(), Town::Start(), and Campaign::Start().
m_mice
array<MouseBase@> BaseGameMode::m_mice private
Definition at line 208 of file BaseGameMode.as.
Referenced by DrawMouse(), GetMousePos(), MainMenu::InstantiateMice(), RenderFrame(), set_m_currCursorColor(), set_m_currCursorColorC(), set_m_mousePos(), set_m_mousePosPrev(), set_m_mouseReal(), Campaign::UpdateFrame(), UpdateMouse(), and UpdateWidgets().
m_rotation
DungeonRotation BaseGameMode::m_rotation private
Definition at line 205 of file BaseGameMode.as.
Referenced by LoadDungeonRotation(), Save(), and ShortcutLevel::Start().
m_screenShake
array<ScreenShake@> BaseGameMode::m_screenShake private
Definition at line 201 of file BaseGameMode.as.
Referenced by GetCameraPos(), ShakeScreen(), and UpdateFrame().
m_showOverheadBossBars
bool BaseGameMode::m_showOverheadBossBars private
Definition at line 191 of file BaseGameMode.as.
Referenced by AddBossBarActor(), DrawOverheadBossBars(), and UpdateFrame().
m_spawnedInitial
bool BaseGameMode::m_spawnedInitial private
Definition at line 179 of file BaseGameMode.as.
Referenced by SpawnPlayers().
m_spectating
bool BaseGameMode::m_spectating private
Definition at line 196 of file BaseGameMode.as.
Referenced by BeginSpectating(), GetCameraPos(), GetVignette(), RenderFrame(), RenderWidgets(), SpectateUpdateHUD(), StopSpectating(), ToggleSpectating(), HUD::Update(), UpdateFrame(), Campaign::UpdateWidgets(), and UpdateWidgets().
m_spectatingPlayer
int BaseGameMode::m_spectatingPlayer private
Definition at line 197 of file BaseGameMode.as.
Referenced by GetCameraPos(), GetVignette(), RenderFrame(), SpectateNextPlayer(), SpectateUpdateHUD(), HUDSpectate::Update(), HUD::Update(), and Campaign::UpdateWidgets().
m_started
bool BaseGameMode::m_started private
Definition at line 177 of file BaseGameMode.as.
Referenced by Campaign::Start(), and Start().
m_startMode
StartMode BaseGameMode::m_startMode private
Definition at line 176 of file BaseGameMode.as.
Referenced by GetPlayerSpawnPosition(), RandomLevel::PostStart(), Campaign::PostStart(), and Start().
m_switchingWidgetHoster
bool BaseGameMode::m_switchingWidgetHoster private
Definition at line 194 of file BaseGameMode.as.
Referenced by FocusTopRoot(), and UpdateWidgets().
m_tooltip
Tooltip BaseGameMode::m_tooltip private
Definition at line 207 of file BaseGameMode.as.
Referenced by BaseGameMode(), Menu::Menu::Close(), DrawMouse(), Widget::OnMouseLeave(), and Widget::ShowTooltip().
m_userWindows
array<UserWindow@> BaseGameMode::m_userWindows private
Definition at line 184 of file BaseGameMode.as.
Referenced by Campaign::Campaign(), CloseUserWindow(), IsUserWindowVisible(), MenuBack(), Campaign::RenderWidgets(), RenderWidgets(), ShouldDisplayCursor(), ShouldFreezeControls(), ShowUserWindow(), ToggleUserWindow(), Town::Town(), and UpdateWidgets().
m_useSpawnLogic
bool BaseGameMode::m_useSpawnLogic = true private
Definition at line 180 of file BaseGameMode.as.
Referenced by RandomLevel::Start(), and Start().
m_usingUICursor
bool BaseGameMode::m_usingUICursor private
Definition at line 210 of file BaseGameMode.as.
Referenced by DrawMouse(), SetCursorGame(), and SetCursorUI().
m_widgetInspector
WidgetInspector BaseGameMode::m_widgetInspector private
Definition at line 186 of file BaseGameMode.as.
Referenced by BaseGameMode(), RenderWidgets(), and UpdateWidgets().
m_widgetRoots
array<IWidgetHoster@> BaseGameMode::m_widgetRoots private
Definition at line 182 of file BaseGameMode.as.
Referenced by AddWidgetRoot(), ClearWidgetRoot(), DrawMouse(), FocusTopRoot(), RemoveWidgetRoot(), RenderWidgets(), ReplaceTopWidgetRoot(), ReplaceWidgetRoot(), ResizeWindow(), SetExclusiveWidgetRoot(), UpdateCurrentCursor(), and UpdateWidgets().
m_widgetScriptHosts
array<ScriptWidgetHost@> BaseGameMode::m_widgetScriptHosts private
Definition at line 183 of file BaseGameMode.as.
Referenced by MenuBack(), RenderWidgets(), ShouldDisplayCursor(), ShouldFreezeControls(), and UpdateWidgets().
The documentation for this class was generated from the following file:
scripts/GameModes/BaseGameMode.as