HoHDocs: TextWidget Class Reference
TextWidget Class Reference
Private Member Functions
TextWidget ()
Widget Clone () override
void Load (WidgetLoadingContext &ctx) override
void SetFont (string fnm)
void SetText (string str, int width, TextAlignment align=TextAlignment::Left, vec4 color=vec4(1, 1, 1, 1), bool force=false)
void SetText (string str, bool setColor=true, bool force=false)
void SetColor (vec4 color)
void DoDraw (SpriteBatch &sb, vec2 pos) override
void AnimateSet (string key, vec4 v) override
Private Attributes
BitmapFont m_font
string m_fontName
BitmapString m_text
string m_str = ""
bool m_upper = false
int m_textWidth = -1
TextAlignment m_alignment = TextAlignment::Left
vec4 m_color = vec4(1, 1, 1, 1)
vec4 m_colorOriginal
Detailed Description
Definition at line 1 of file TextWidget.as.
Constructor & Destructor Documentation
TextWidget()
TextWidget::TextWidget () inline private
Definition at line 14 of file TextWidget.as.
References Widget::m_height, and Widget::m_width.
Referenced by Clone().
     {
         super();
         m_width = 0;
         m_height = 0;
     }
Member Function Documentation
AnimateSet()
void TextWidget::AnimateSet (string key, vec4 v) inline override private
Definition at line 135 of file TextWidget.as.
References Widget::AnimateSet(), and SetColor().
     {
         if (key == "color")
             SetColor(v);
         Widget::AnimateSet(key, v);
     }
Clone()
Widget TextWidget::Clone () inline override private
Definition at line 22 of file TextWidget.as.
References Widget::CloneInto(), and TextWidget().
     {
         TextWidget@ w = TextWidget();
         CloneInto(w);
         return w;
     }
DoDraw()
void TextWidget::DoDraw (SpriteBatch & sb, vec2 pos) inline override private
Definition at line 127 of file TextWidget.as.
References m_text.
     {
         if (m_text is null)
             return;
         sb.DrawString(vec2(int(pos.x), int(pos.y)), m_text);
     }
Load()
void TextWidget::Load (WidgetLoadingContext & ctx) inline override private
Definition at line 29 of file TextWidget.as.
References Center, Left, Widget::Load(), Widget::LoadWidthHeight(), m_color, m_colorOriginal, m_font, m_fontName, m_upper, Widget::m_width, Right, SetText(), and text.
Referenced by LoadSysTextWidget(), and LoadTextWidget().
     {
         TextAlignment align = TextAlignment::Left;
         string alignStr = ctx.GetString("align", false);
         if (alignStr == "right")
             align = TextAlignment::Right;
         else if (alignStr == "center")
             align = TextAlignment::Center;
         m_width = ctx.GetInteger("width", false, 0);
         m_upper = ctx.GetBoolean("upper", false, false);
         if (m_font is null)
         {
             m_fontName = ctx.GetString("font", false);
             @m_font = Resources::GetBitmapFont(m_fontName);
             if (m_font is null)
                 PrintError("Couldn't load font: '" + m_fontName + "'");
         }
         m_colorOriginal = ctx.GetColorRGBA("color", false, m_color);
         string text = Resources::GetString(ctx.GetString("text", false));
         LoadWidthHeight(ctx, false);
         SetText(text, m_width, align, m_colorOriginal);
         Widget::Load(ctx);
     }
SetColor()
void TextWidget::SetColor (vec4 color) inline private
Definition at line 120 of file TextWidget.as.
References m_color, and m_text.
Referenced by GameChatWidget::AddChat(), AnimateSet(), Play(), DungeonStoreMenuContent::ReloadList(), WorldScript::CountdownText::ServerExecute(), ScoreDialog::Set(), and FountainShopMenuContent::UpdateInterface().
     {
         m_color = color;
         m_text.SetColor(color);
     }
SetFont()
void TextWidget::SetFont (string fnm) inline private
Definition at line 59 of file TextWidget.as.
References m_alignment, m_color, m_font, m_str, m_text, m_textWidth, and SetText().
Referenced by WorldScript::CountdownText::ServerExecute().
     {
         @m_font = Resources::GetBitmapFont(fnm);
         if (m_font is null)
         {
             PrintError("Font not found: \"" + fnm + "\"");
             @m_text = null;
         }
         else
             SetText(m_str, m_textWidth, m_alignment, m_color, true);
     }
SetText() [1/2]
void TextWidget::SetText (string str, int width, TextAlignment align = TextAlignment::Left, vec4 color = vec4(1, 1, 1, 1), bool force = false) inline private
Definition at line 71 of file TextWidget.as.
References force, m_alignment, m_color, Widget::m_filter, m_font, Widget::m_height, m_str, m_text, m_textWidth, m_upper, Widget::m_width, and min.
Referenced by GameChatWidget::AddChat(), Menu::ControlMapMenu::AddNewControl(), Menu::ControlMapMenu::AddNewControlAxis(), Menu::SplitscreenPlayer::DisplayName(), Draw(), StatisticsInterface::Initialize(), Load(), FountainShopMenuContent::NetDeposit(), PlayerMenuMapTab::OnShow(), PlayerMenuCharacterTab::OnShow(), Play(), DrinksMenuContent::ReloadList(), DungeonStoreMenuContent::ReloadList(), ReloadList(), SkillsShopMenuContent::ReloadList(), WorldScript::CountdownText::ServerExecute(), ScoreDialog::Set(), SetBattleStatus(), SetFont(), SetGoldStatus(), Menu::SetStartLevel(), Menu::SetStartScenario(), ShopMenu::Show(), HUDSurvival::Update(), HUDSpectate::Update(), Tutorial::Update(), BuffWidget::Update(), PlayerMenuCharacterTab::Update(), WorldScript::CountdownText::Update(), HUD::Update(), Menu::SplitscreenOptionsMenu::UpdateDifficultyTexts(), FountainShopMenuContent::UpdateInterface(), DungeonSettingsMenu::UpdateNgp(), Menu::HostMenu::UpdateNgp(), Menu::LobbyPlayersMenu::UpdatePlayerList(), UpdateText(), Campaign::UpdateWidgets(), and WinCash().
     {
         if (!force && m_str == str && m_textWidth == width && m_alignment == align)// && m_color == color)
             return;
         if (m_upper)
             str = utf8string(str).toUpper().plain();
         m_str = str;
         m_textWidth = width;
         m_alignment = align;
         m_color = color;
         m_filter = str.toLower();
         @m_text = m_font.BuildText(str, width, align);
         m_text.SetColor(color);
         if (m_textWidth > 0)
             m_width = min(m_text.GetWidth(), m_textWidth);
         else
             m_width = m_text.GetWidth();
         m_height = m_text.GetHeight();
     }
SetText() [2/2]
void TextWidget::SetText (string str, bool setColor = true, bool force = false) inline private
Definition at line 95 of file TextWidget.as.
References force, m_alignment, m_color, Widget::m_filter, m_font, Widget::m_height, Widget::m_parent, m_str, m_text, m_textWidth, m_upper, Widget::m_width, Widget::m_widthScalar, and min.
     {
         if (!force && m_str == str)
             return;
         if (m_upper)
             str = utf8string(str).toUpper().plain();
         m_str = str;
         m_filter = str.toLower();
         if (m_widthScalar >= 0 && m_parent !is null)
             m_textWidth = int(m_widthScalar * m_parent.m_width);
         @m_text = m_font.BuildText(str, m_textWidth, m_alignment);
         if (setColor)
             m_text.SetColor(m_color);
         if (m_textWidth > 0)
             m_width = min(m_text.GetWidth(), m_textWidth);
         else
             m_width = m_text.GetWidth();
         m_height = m_text.GetHeight();
     }
Member Data Documentation
m_alignment
TextAlignment TextWidget::m_alignment = TextAlignment::Left private
Definition at line 10 of file TextWidget.as.
Referenced by SetFont(), and SetText().
m_color
vec4 TextWidget::m_color = vec4(1, 1, 1, 1) private
Definition at line 11 of file TextWidget.as.
Referenced by Load(), SetColor(), SetFont(), and SetText().
m_colorOriginal
vec4 TextWidget::m_colorOriginal private
Definition at line 12 of file TextWidget.as.
Referenced by Load().
m_font
BitmapFont TextWidget::m_font private
Definition at line 3 of file TextWidget.as.
Referenced by Load(), LoadSysTextWidget(), SetFont(), and SetText().
m_fontName
string TextWidget::m_fontName private
Definition at line 4 of file TextWidget.as.
Referenced by Load().
m_str
string TextWidget::m_str = "" private
Definition at line 7 of file TextWidget.as.
Referenced by SetFont(), and SetText().
m_text
BitmapString TextWidget::m_text private
Definition at line 5 of file TextWidget.as.
Referenced by DoDraw(), SetColor(), SetFont(), and SetText().
m_textWidth
int TextWidget::m_textWidth = -1 private
Definition at line 9 of file TextWidget.as.
Referenced by SetFont(), and SetText().
m_upper
bool TextWidget::m_upper = false private
Definition at line 8 of file TextWidget.as.
Referenced by Load(), and SetText().
The documentation for this class was generated from the following file:
scripts/GUI/TextWidget.as