HoHDocs: DyeBucket Class Reference
DyeBucket Class Reference
Private Member Functions
DyeBucket (UnitPtr unit, SValue &params)
SValue Save ()
void PostLoad (SValue@ data)
void Initialize (Materials::Dye@ dye)
void Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther)
void EndCollision (UnitPtr unit, Fixture@ fxSelf, Fixture@ fxOther)
UnitPtr GetUseUnit ()
bool CanUse (PlayerBase@ player)
void Use (PlayerBase@ player)
void NetUse (PlayerHusk@ player)
UsableIcon GetIcon (Player@ player)
int UsePriority (IUsable@ other)
Private Attributes
UnitPtr m_unit
Materials::Dye m_dye
Detailed Description
Definition at line 1 of file DyeBucket.as.
Constructor & Destructor Documentation
DyeBucket()
DyeBucket::DyeBucket (UnitPtr unit, SValue & params) inline private
Definition at line 7 of file DyeBucket.as.
References m_unit, and unit.
     {
         m_unit = unit;
     }
Member Function Documentation
CanUse()
bool DyeBucket::CanUse (PlayerBase@ player) inline private
Definition at line 76 of file DyeBucket.as.
     {
         return true;
     }
Collide()
void DyeBucket::Collide (UnitPtr unit, vec2 pos, vec2 normal, Fixture@ fxSelf, Fixture@ fxOther) inline private
Definition at line 51 of file DyeBucket.as.
     {
         Player@ player = cast<Player>(unit.GetScriptBehavior());
         if (player is null)
             return;
         if (fxSelf.IsSensor())
             player.AddUsable(this);
     }
EndCollision()
void DyeBucket::EndCollision (UnitPtr unit, Fixture@ fxSelf, Fixture@ fxOther) inline private
Definition at line 61 of file DyeBucket.as.
References unit.
     {
         Player@ player = cast<Player>(unit.GetScriptBehavior());
         if (player is null)
             return;
         if (fxSelf.IsSensor())
             player.RemoveUsable(this);
     }
GetIcon()
UsableIcon DyeBucket::GetIcon (Player@ player) inline private
Definition at line 91 of file DyeBucket.as.
     {
         return UsableIcon::Generic;
     }
GetUseUnit()
UnitPtr DyeBucket::GetUseUnit () inline private
Definition at line 71 of file DyeBucket.as.
References m_unit.
     {
         return m_unit;
     }
Initialize()
void DyeBucket::Initialize (Materials::Dye@ dye) inline private
Definition at line 36 of file DyeBucket.as.
Referenced by PostLoad().
     {
         @m_dye = dye;
         if (m_dye.m_quality == ActorItemQuality::Common)
             m_unit.SetUnitScene("common", false);
         else if (m_dye.m_quality == ActorItemQuality::Uncommon)
             m_unit.SetUnitScene("uncommon", false);
         else if (m_dye.m_quality == ActorItemQuality::Rare)
             m_unit.SetUnitScene("rare", false);
         array<vec4> color = m_dye.m_shades;
         m_unit.SetMultiColor(0, color[0], color[1], color[2]);
     }
NetUse()
void DyeBucket::NetUse (PlayerHusk@ player) inline private
Definition at line 87 of file DyeBucket.as.
     {
     }
PostLoad()
void DyeBucket::PostLoad (SValue@ data) inline private
Definition at line 22 of file DyeBucket.as.
References Materials::GetDye(), Initialize(), and m_unit.
     {
         auto arr = data.GetArray();
         auto cat = Materials::Category(arr[0].GetInteger());
         uint id = uint(arr[1].GetInteger());
         auto dye = Materials::GetDye(cat, id);
         if (dye !is null)
             Initialize(dye);
         else
             m_unit.Destroy();
     }
Save()
SValue DyeBucket::Save () inline private
Definition at line 12 of file DyeBucket.as.
References m_dye.
     {
         SValueBuilder sval;
         sval.PushArray();
         sval.PushInteger(int(m_dye.m_category));
         sval.PushInteger(m_dye.m_idHash);
         sval.PopArray();
         return sval.Build();
     }
Use()
void DyeBucket::Use (PlayerBase@ player) inline private
Definition at line 81 of file DyeBucket.as.
     {
         m_unit.Destroy();
         GiveDyeImpl(m_dye, player, true);
     }
UsePriority()
int DyeBucket::UsePriority (IUsable@ other) inline private
Definition at line 96 of file DyeBucket.as.
 { return 0; }
Member Data Documentation
m_dye
Materials::Dye DyeBucket::m_dye private
Definition at line 5 of file DyeBucket.as.
Referenced by Collide(), and Save().
m_unit
UnitPtr DyeBucket::m_unit private
Definition at line 3 of file DyeBucket.as.
Referenced by Collide(), DyeBucket(), GetUseUnit(), and PostLoad().
The documentation for this class was generated from the following file:
scripts/Behaviors/Items/DyeBucket.as