HoHDocs: GiveArmor Class Reference
GiveArmor Class Reference
Private Member Functions
GiveArmor (UnitPtr unit, SValue &params)
void SetWeaponInformation (uint weapon)
int GetAmount (float intensity)
bool Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
bool CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
Private Attributes
int m_amount
ArmorDef m_def
bool m_replace
bool m_pickup
Detailed Description
Definition at line 1 of file GiveArmor.as.
Constructor & Destructor Documentation
GiveArmor()
GiveArmor::GiveArmor (UnitPtr unit, SValue & params) inline private
Definition at line 9 of file GiveArmor.as.
References LoadArmorDef(), m_amount, m_def, m_pickup, m_replace, and unit.
     {
         m_amount = GetParamInt(unit, params, "amount");
         @m_def = LoadArmorDef(GetParamString(unit, params, "definition"));
         m_replace = GetParamBool(unit, params, "replace");
         m_pickup = GetParamBool(unit, params, "pickup", false, false);
     }
Member Function Documentation
Apply()
bool GiveArmor::Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk) inline private
Definition at line 24 of file GiveArmor.as.
References CanApply(), GetAmount(), Player::GiveArmor(), m_def, and m_replace.
     {
         if (!CanApply(owner, target, pos, dir, intensity))
             return false;
         Player@ plr = cast<Player>(target.GetScriptBehavior());
         return plr.GiveArmor(GetAmount(intensity), m_def, m_replace);
     }
CanApply()
bool GiveArmor::CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) inline override private
Definition at line 33 of file GiveArmor.as.
References Player::CanGiveArmor(), GetAmount(), m_def, and m_replace.
Referenced by Apply().
     {
         if (!target.IsValid())
             return false;
         Player@ plr = cast<Player>(target.GetScriptBehavior());
         if (plr is null)
             return false;
         int amt = GetAmount(intensity);
         if (amt <= 0)
             return false;
         if (!plr.CanGiveArmor(amt, m_def, m_replace))
             return false;
         return true;
     }
GetAmount()
int GiveArmor::GetAmount (float intensity) inline private
Definition at line 19 of file GiveArmor.as.
References m_amount.
Referenced by Apply(), and CanApply().
     {
         return int(float(m_amount) * intensity);
     }
SetWeaponInformation()
void GiveArmor::SetWeaponInformation (uint weapon) inline private
Definition at line 17 of file GiveArmor.as.
 {}
Member Data Documentation
m_amount
int GiveArmor::m_amount private
Definition at line 3 of file GiveArmor.as.
Referenced by GetAmount(), and GiveArmor().
m_def
ArmorDef GiveArmor::m_def private
Definition at line 4 of file GiveArmor.as.
Referenced by Apply(), CanApply(), and GiveArmor().
m_pickup
bool GiveArmor::m_pickup private
Definition at line 6 of file GiveArmor.as.
Referenced by GiveArmor().
m_replace
bool GiveArmor::m_replace private
Definition at line 5 of file GiveArmor.as.
Referenced by Apply(), CanApply(), and GiveArmor().
The documentation for this class was generated from the following file:
scripts/Behaviors/Effects/GiveArmor.as