HoHDocs: Miniboss Class Reference
Miniboss Class Reference
Private Member Functions
Miniboss (UnitPtr unit, SValue &params)
void NetDamage (DamageInfo dmg, vec2 pos, vec2 dir) override
void Update (int dt) override
Private Attributes
int m_bossBarWidth
OverheadBossBar m_bossBar
int m_bossBarTimeC
Detailed Description
Definition at line 1 of file Miniboss.as.
Constructor & Destructor Documentation
Miniboss()
Miniboss::Miniboss (UnitPtr unit, SValue & params) inline private
Definition at line 7 of file Miniboss.as.
References m_bossBarWidth, and unit.
     {
         super(unit, params);
         m_bossBarWidth = GetParamInt(unit, params, "overhead-bossbar-width", false, -1);
     }
Member Function Documentation
NetDamage()
void Miniboss::NetDamage (DamageInfo dmg, vec2 pos, vec2 dir) inline override private
Definition at line 14 of file Miniboss.as.
References DamageInfo::Damage, g_gameMode, m_bossBar, m_bossBarTimeC, m_bossBarWidth, m_unitHeight, and NetDamage().
     {
         CompositeActorBehavior::NetDamage(dmg, pos, dir);
         if (dmg.Damage != 0 && m_bossBarWidth != -1)
         {
             m_bossBarTimeC = 3000;
             if (m_bossBar is null)
             {
                 auto gm = cast<Campaign>(g_gameMode);
                 if (gm !is null)
                     @m_bossBar = gm.AddBossBarActor(this, m_bossBarWidth, -m_unitHeight, "");
             }
         }
     }
Update()
void Miniboss::Update (int dt) inline override private
Definition at line 30 of file Miniboss.as.
References g_gameMode, IsDead(), m_bossBar, m_bossBarTimeC, and Update().
     {
         if (!IsDead() && m_bossBar !is null)
         {
             m_bossBarTimeC -= dt;
             if (m_bossBarTimeC <= 0)
             {
                 auto gm = cast<Campaign>(g_gameMode);
                 if (gm !is null)
                 {
                     int index = gm.m_arrBosses.findByRef(m_bossBar);
                     if (index != -1)
                         gm.m_arrBosses.removeAt(index);
                 }
                 @m_bossBar = null;
             }
         }
         CompositeActorBehavior::Update(dt);
     }
Member Data Documentation
m_bossBar
OverheadBossBar Miniboss::m_bossBar private
Definition at line 4 of file Miniboss.as.
Referenced by NetDamage(), and Update().
m_bossBarTimeC
int Miniboss::m_bossBarTimeC private
Definition at line 5 of file Miniboss.as.
Referenced by NetDamage(), and Update().
m_bossBarWidth
int Miniboss::m_bossBarWidth private
Definition at line 3 of file Miniboss.as.
Referenced by Miniboss(), and NetDamage().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Enemies/Miniboss.as