HoHDocs: HUD Class Reference
HUD Class Reference
Private Member Functions
HUD (GUIBuilder@ b)
void Start ()
void OnDeath ()
void InitializeKeys (PlayerRecord@ record)
void Update (int dt) override
void Update (int dt, PlayerRecord@ record)
void Draw (SpriteBatch &sb, int idt) override
bool DrawPlayerBars (SpriteBatch &sb)
void DrawPlayerBar (SpriteBatch &sb, int width, int ypos, float fill, vec4 colorFilled, vec4 colorEmpty)
void DrawHoverItem (SpriteBatch &sb)
void DrawUseIcon (SpriteBatch &sb, int y)
bool Announce (const AnnounceParams &in params)
TextWidget GetCountDown ()
void SetExtraLife ()
TopNumberIconWidget GetTopNumberIcon (string id)
void SetTopNumberIcon (string id, int number)
void HideTopNumberIcon (string id)
void ClearTopNumberIcons ()
void AddBossBar (Actor@ actor, string name)
BossBarWidget GetBossBar (Actor@ actor)
void PlayPickup ()
Widget ShowBuffIcon (PlayerBase@ player, IBuffWidgetInfo@ buff)
Private Attributes
GUIDef m_guiDef
WorldScript::AnnounceText m_currAnnounce
WaypointMarkersWidget m_waypoints
SpeechBubbleManager m_speechBubbles
UsableIcon m_currentUseIcon
Sprite m_useIcon
Sprite m_useIconCross
Sprite m_useIconKey
Sprite m_useIconShop
Sprite m_useIconSpeech
Sprite m_useIconExit
Sprite m_useIconQuestion
Sprite m_useIconRevive
Widget m_wTopbar
Widget m_wHealthGui
Widget m_wSkillGui
Widget m_wBossBars
uint m_tutorialData
TextWidget m_wTutorial
TextWidget m_wDeadMessage
TextWidget m_wDeadMessage2
int m_barStatsTimeC
SpriteBarWidget m_wBarHealth
TextWidget m_wHealth
SpriteBarWidget m_wBarMana
TextWidget m_wMana
TextWidget m_wCombo
SpriteBarWidget m_wBarCombo
SpriteBarWidget m_wBarComboTimer
SpriteBarWidget m_wBarExperience
TextWidget m_wCurrencyGold
SpriteWidget m_wCurrencyGoldIcon
TextWidget m_wCurrencyOre
SpriteWidget m_wCurrencyOreIcon
Widget m_wCurrencySkillPointsContainer
TextWidget m_wCurrencySkillPoints
RectWidget m_wKeyTemplate
Widget m_wKeyList
SpriteWidget m_wPotion
DotbarWidget m_wPotionBar
array< SkillWidget@> m_arrSkillWidgets
PlayerRecord m_lastRecord
Tooltip m_tooltipItems
TextWidget m_wDebugHandicap
Widget m_wBuffList
Widget m_wBuffTemplate
array< TopNumberIconWidget@> m_topNumberIcons
Widget m_wTopNumberTemplate
Widget m_wTopNumberList
Detailed Description
Definition at line 1 of file HUD.as.
Constructor & Destructor Documentation
HUD()
HUD::HUD (GUIBuilder@ b) inline private
Definition at line 74 of file HUD.as.
References Tutorial::AssignHUD(), LoadBossBarWidget(), LoadSkillWidget(), LoadWaypointMarkersWidget(), LoadWidget(), m_arrSkillWidgets, m_guiDef, m_speechBubbles, m_tooltipItems, m_useIcon, m_useIconCross, m_useIconExit, m_useIconKey, m_useIconQuestion, m_useIconRevive, m_useIconShop, m_useIconSpeech, m_waypoints, m_wBarCombo, m_wBarComboTimer, m_wBarExperience, m_wBarHealth, m_wBarMana, m_wBossBars, m_wBuffList, m_wBuffTemplate, m_wCombo, m_wCurrencyGold, m_wCurrencyGoldIcon, m_wCurrencyOre, m_wCurrencyOreIcon, m_wCurrencySkillPoints, m_wCurrencySkillPointsContainer, m_wDeadMessage, m_wDeadMessage2, m_wDebugHandicap, m_wHealth, m_wHealthGui, m_widget, m_wKeyList, m_wKeyTemplate, m_wMana, m_wPotion, m_wPotionBar, m_wSkillGui, m_wTopbar, m_wTopNumberList, m_wTopNumberTemplate, and Tooltip().
     {
         b.AddWidgetProducer("skill", LoadSkillWidget);
         b.AddWidgetProducer("bossbar", LoadBossBarWidget);
         b.AddWidgetProducer("waypoints", LoadWaypointMarkersWidget);
         @m_speechBubbles = SpeechBubbleManager();
         GUIDef@ def = LoadWidget(b, "gui/hud.gui");
         @m_guiDef = def;
         @m_useIcon = def.GetSprite("use-icon");
         @m_useIconCross = def.GetSprite("use-icon-cross");
         @m_useIconKey = def.GetSprite("use-icon-key");
         @m_useIconShop = def.GetSprite("use-icon-shop");
         @m_useIconSpeech = def.GetSprite("use-icon-speech");
         @m_useIconExit = def.GetSprite("use-icon-exit");
         @m_useIconQuestion = def.GetSprite("use-icon-question");
         @m_useIconRevive = def.GetSprite("use-icon-revive");
         @m_wTopbar = m_widget.GetWidgetById("topbar");
         @m_wHealthGui = m_widget.GetWidgetById("health-gui");
         @m_wSkillGui = m_widget.GetWidgetById("skill-gui");
         @m_wBossBars = m_widget.GetWidgetById("boss-bars");
         @m_waypoints = cast<WaypointMarkersWidget>(m_widget.GetWidgetById("waypoints"));
         Tutorial::AssignHUD(cast<TextWidget>(m_widget.GetWidgetById("tutorial")));
         @m_wDeadMessage = cast<TextWidget>(m_widget.GetWidgetById("deadmessage"));
         @m_wDeadMessage2 = cast<TextWidget>(m_widget.GetWidgetById("deadmessage2"));
         @m_wBarHealth = cast<SpriteBarWidget>(m_widget.GetWidgetById("health-bar"));
         @m_wHealth = cast<TextWidget>(m_widget.GetWidgetById("health"));
         @m_wBarMana = cast<SpriteBarWidget>(m_widget.GetWidgetById("mana-bar"));
         @m_wMana = cast<TextWidget>(m_widget.GetWidgetById("mana"));
         @m_wCombo = cast<TextWidget>(m_widget.GetWidgetById("combo"));
         @m_wBarCombo = cast<SpriteBarWidget>(m_widget.GetWidgetById("combo-bar"));
         @m_wBarComboTimer = cast<SpriteBarWidget>(m_widget.GetWidgetById("combo-bar-timer"));
         @m_wBarExperience = cast<SpriteBarWidget>(m_widget.GetWidgetById("exp-bar"));
         @m_wCurrencyGold = cast<TextWidget>(m_widget.GetWidgetById("gold"));
         @m_wCurrencyGoldIcon = cast<SpriteWidget>(m_widget.GetWidgetById("gold-icon"));
         @m_wCurrencyOre = cast<TextWidget>(m_widget.GetWidgetById("ore"));
         @m_wCurrencyOreIcon = cast<SpriteWidget>(m_widget.GetWidgetById("ore-icon"));
         @m_wCurrencySkillPointsContainer = m_widget.GetWidgetById("skill-points-container");
         @m_wCurrencySkillPoints = cast<TextWidget>(m_widget.GetWidgetById("skill-points"));
         @m_wKeyTemplate = cast<RectWidget>(m_widget.GetWidgetById("topbar-key-template"));
         @m_wKeyList = m_widget.GetWidgetById("topbar-key-list");
         @m_wPotion = cast<SpriteWidget>(m_widget.GetWidgetById("potion"));
         @m_wPotionBar = cast<DotbarWidget>(m_widget.GetWidgetById("potion-bar"));
         for (uint i = 0; ; i++)
         {
             auto wSkill = cast<SkillWidget>(m_widget.GetWidgetById("skill-" + (i + 1)));
             if (wSkill is null)
                 break;
             m_arrSkillWidgets.insertLast(wSkill);
         }
         @m_tooltipItems = Tooltip(Resources::GetSValue("gui/tooltip.sval"));
         @m_wDebugHandicap = cast<TextWidget>(m_widget.GetWidgetById("debug-handicap"));
         @m_wBuffList = m_widget.GetWidgetById("buff-list");
         @m_wBuffTemplate = m_widget.GetWidgetById("buff-template");
         @m_wTopNumberTemplate = m_widget.GetWidgetById("topnumber-template");
         @m_wTopNumberList = m_widget.GetWidgetById("topnumber-list");
     }
Member Function Documentation
AddBossBar()
void HUD::AddBossBar (Actor@ actor, string name) inline private
Definition at line 640 of file HUD.as.
References Widget::AddChild(), Widget::m_children, m_wBossBars, m_widget, and name.
Referenced by WorldScript::CreateBossBar::ServerExecute().
     {
         auto wTemplate = cast<BossBarWidget>(m_widget.GetWidgetById("boss-template"));
         if (wTemplate is null)
             return;
         if (m_wBossBars is null)
             return;
         auto wBossBar = cast<BossBarWidget>(wTemplate.Clone());
         wBossBar.m_visible = true;
         wBossBar.SetID("");
         @wBossBar.m_actor = actor;
         wBossBar.SetText(Resources::GetString(name));
         m_wBossBars.AddChild(wBossBar);
         for (uint i = 0; i < m_wBossBars.m_children.length(); i++)
         {
             auto wBar = cast<BossBarWidget>(m_wBossBars.m_children[i]);
             if (wBar is null)
                 continue;
             wBar.UpdateAppearance();
         }
     }
Announce()
bool HUD::Announce (const AnnounceParams &in params) inline private
Definition at line 549 of file HUD.as.
References Center, Left, m_widget, Right, and WidgetVec4Animation().
Referenced by WorldScript::Door::Announce().
     {
         auto w = cast<TextWidget>(m_widget.GetWidgetById("announce"));
         if (w is null)
         {
             PrintError("TextWidget \"announce\" not found!");
             return false;
         }
         if (w.m_visible && !params.m_override)
             return false;
         if (params.m_align == -1) w.m_alignment = TextAlignment::Left;
         else if (params.m_align == 0) w.m_alignment = TextAlignment::Center;
         else if (params.m_align == 1) w.m_alignment = TextAlignment::Right;
         w.SetFont(params.m_font);
         w.SetText(params.m_text);
         w.m_anchor = params.m_anchor;
         w.m_visible = true;
         auto col = tocolor(params.m_color);
         auto colTransparent = vec4(col.r, col.g, col.b, 0);
         w.CancelAnimations();
         w.Animate(WidgetVec4Animation("color", colTransparent, col, params.m_fadeTime));
         if (params.m_time != -1)
         {
             w.Animate(WidgetVec4Animation("color", col, colTransparent, params.m_fadeTime, params.m_fadeTime + params.m_time));
             w.Animate(WidgetBoolAnimation("visible", false, params.m_fadeTime + params.m_time + params.m_fadeTime));
         }
         return true;
     }
ClearTopNumberIcons()
void HUD::ClearTopNumberIcons () inline private
Definition at line 634 of file HUD.as.
References Widget::ClearChildren(), m_topNumberIcons, and m_wTopNumberList.
Referenced by Campaign::OnRunEnd().
     {
         m_wTopNumberList.ClearChildren();
         m_topNumberIcons.removeRange(0, m_topNumberIcons.length());
     }
Draw()
void HUD::Draw (SpriteBatch & sb, int idt) inline override private
Definition at line 377 of file HUD.as.
References SpeechBubbleManager::Draw(), Draw(), DrawHoverItem(), DrawPlayerBars(), DrawUseIcon(), and m_speechBubbles.
Referenced by Campaign::RenderWidgets().
     {
         bool drawnPlayerBars = DrawPlayerBars(sb);
         DrawUseIcon(sb, drawnPlayerBars ? 22 : 14);
         m_speechBubbles.Draw(sb, idt);
         IWidgetHoster::Draw(sb, idt);
         DrawHoverItem(sb);
     }
DrawHoverItem()
void HUD::DrawHoverItem (SpriteBatch & sb) inline private
Definition at line 454 of file HUD.as.
References g_gameMode, Materials::GetCategoryName(), GetItemQualityColorString(), GetItemQualityNameFull(), GetLocalPlayer(), m_tooltipItems, and SetItemColorString.
Referenced by Draw().
     {
         auto localPlayer = GetLocalPlayer();
         if (localPlayer is null)
             return;
         auto usable = localPlayer.GetTopUsable();
         if (usable is null || !usable.CanUse(localPlayer))
             return;
         auto gm = cast<BaseGameMode>(g_gameMode);
         if (gm is null)
             return;
         bool hasTooltip = false;
         auto hoverItem = cast<Item>(usable);
         if (hoverItem !is null)
         {
             m_tooltipItems.SetTitle("\\c" + GetItemQualityColorString(hoverItem.m_item.quality) + utf8string(Resources::GetString(hoverItem.m_item.name)).toUpper().plain());
             m_tooltipItems.SetText(Resources::GetString(hoverItem.m_item.desc) + (hoverItem.m_item.set !is null ? ("\n\\c" + SetItemColorString + Resources::GetString(hoverItem.m_item.set.name) + "\\d") : ""));
             hasTooltip = true;
         }
         auto hoverBarrel = cast<TavernBarrel>(usable);
         if (hoverBarrel !is null)
         {
             m_tooltipItems.SetTitle("\\c" + GetItemQualityColorString(hoverBarrel.m_drink.quality) + utf8string(Resources::GetString(hoverBarrel.m_drink.name)).toUpper().plain());
             m_tooltipItems.SetText(Resources::GetString(hoverBarrel.m_drink.desc));
             hasTooltip = true;
         }
         auto hoverBlueprint = cast<ForgeBlueprint>(usable);
         if (hoverBlueprint !is null)
         {
             m_tooltipItems.SetTitle("\\c" + GetItemQualityColorString(hoverBlueprint.m_item.quality) + utf8string(Resources::GetString(hoverBlueprint.m_item.name)).toUpper().plain());
             m_tooltipItems.SetText(Resources::GetString(hoverBlueprint.m_item.desc) + (hoverBlueprint.m_item.set !is null ? ("\n\\c" + SetItemColorString + Resources::GetString(hoverBlueprint.m_item.set.name) + "\\d") : ""));
             hasTooltip = true;
         }
         auto hoverDyeBucket = cast<DyeBucket>(usable);
         if (hoverDyeBucket !is null)
         {
             m_tooltipItems.SetTitle(Materials::GetCategoryName(hoverDyeBucket.m_dye.m_category) + ": " + Resources::GetString(hoverDyeBucket.m_dye.m_name));
             m_tooltipItems.SetText("\\c" + GetItemQualityColorString(hoverDyeBucket.m_dye.m_quality) + GetItemQualityNameFull(hoverDyeBucket.m_dye.m_quality));
             hasTooltip = true;
         }
         if (hasTooltip)
         {
             vec2 tooltipSize = m_tooltipItems.GetSize();
             m_tooltipItems.Draw(sb, vec2(
                 gm.m_wndWidth / 2 - tooltipSize.x / 2,
                 gm.m_wndHeight / 2 - tooltipSize.y - 30
             ));
         }
     }
DrawPlayerBar()
void HUD::DrawPlayerBar (SpriteBatch & sb, int width, int ypos, float fill, vec4 colorFilled, vec4 colorEmpty) inline private
Definition at line 442 of file HUD.as.
References clamp(), g_gameMode, and AGameMode::m_wndWidth.
Referenced by DrawPlayerBars().
     {
         int w = int(width * clamp(fill, 0.0, 1.0));
         vec4 p = vec4((g_gameMode.m_wndWidth - width) / 2, ypos, w, 1);
         sb.DrawSprite(null, p, p, colorFilled);
         p.x += w;
         p.z = width - w;
         sb.DrawSprite(null, p, p, colorEmpty);
     }
DrawPlayerBars()
bool HUD::DrawPlayerBars (SpriteBatch & sb) inline private
Definition at line 389 of file HUD.as.
References DrawPlayerBar(), g_gameMode, GetLocalPlayerRecord(), m_barStatsTimeC, AGameMode::m_wndHeight, and AGameMode::m_wndWidth.
Referenced by Draw().
     {
         if (cast<Town>(g_gameMode) !is null)
             return false;
         auto plr = GetLocalPlayerRecord();
         auto localPlayer = cast<Player>(plr.actor);
         if (localPlayer is null)
             return false;
         int yPos = g_gameMode.m_wndHeight / 2 - 10 - 10 - 1;
         int width = 16;
         vec2 comboBars = localPlayer.GetComboBars();
         int barsVisibility = GetVarInt("ui_bars_visibility");
         if (barsVisibility == -1)
             return false;
         bool alwaysShowBars = (barsVisibility == 1);
         bool showBarStats = (alwaysShowBars || m_barStatsTimeC > 0);
         bool showBarCombo = (alwaysShowBars || comboBars.x > 0.0f);
         int height = 1;
         if (showBarStats) height += 4;
         if (showBarCombo) height += 2;
         if (height == 1)
             return false;
         vec4 p = vec4((g_gameMode.m_wndWidth - width) / 2, yPos, width, height);
         sb.DrawSprite(null, p, p, vec4(0, 0, 0, 1));
         yPos--;
         if (showBarStats)
         {
             DrawPlayerBar(sb, width -2, yPos += 2, plr.hp, vec4(1,0,0,1), vec4(0.16,0.06,0.06,1));
             DrawPlayerBar(sb, width -2, yPos += 2, plr.mana, vec4(0,0.71,1,1), vec4(0.06,0.08,0.12,1));
         }
         if (showBarCombo)
         {
             yPos += 2;
             DrawPlayerBar(sb, width -2, yPos, comboBars.x, vec4(.3,0,.3,1), vec4(0.03,0,0.03,1));
             DrawPlayerBar(sb, width -2, yPos, comboBars.x * comboBars.y, vec4(1,0,1,1), vec4(0,0,0,0));
         }
         return true;
     }
DrawUseIcon()
void HUD::DrawUseIcon (SpriteBatch & sb, int y) inline private
Definition at line 512 of file HUD.as.
References Cross, Exit, g_gameMode, g_menuTime, GetLocalPlayer(), icon, Key, m_useIcon, m_useIconCross, m_useIconExit, m_useIconKey, m_useIconQuestion, m_useIconRevive, m_useIconShop, m_useIconSpeech, AGameMode::m_wndHeight, AGameMode::m_wndWidth, None, Question, Revive, Shop, and Speech.
Referenced by Draw().
     {
         auto localPlayer = GetLocalPlayer();
         if (localPlayer is null)
             return;
         IUsable@ usable = localPlayer.GetTopUsable();
         if (usable is null)
             return;
         vec2 pos = vec2(g_gameMode.m_wndWidth / 2, g_gameMode.m_wndHeight / 2);
         auto icon = usable.GetIcon(localPlayer);
         if (icon == UsableIcon::None)
             return;
         if (icon == UsableIcon::Cross)
             sb.DrawSprite(pos - vec2(m_useIconCross.GetWidth() / 2, y + m_useIconCross.GetHeight()), m_useIconCross, g_menuTime);
         else if (icon == UsableIcon::Shop)
             sb.DrawSprite(pos - vec2(m_useIconShop.GetWidth() / 2, y + m_useIconShop.GetHeight()), m_useIconShop, g_menuTime);
         else if (icon == UsableIcon::Speech)
             sb.DrawSprite(pos - vec2(m_useIconSpeech.GetWidth() / 2, y + m_useIconSpeech.GetHeight()), m_useIconSpeech, g_menuTime);
         else if (icon == UsableIcon::Exit)
             sb.DrawSprite(pos - vec2(m_useIconExit.GetWidth() / 2, y + m_useIconExit.GetHeight()), m_useIconExit, g_menuTime);
         else if (icon == UsableIcon::Question)
             sb.DrawSprite(pos - vec2(m_useIconQuestion.GetWidth() / 2, y + m_useIconQuestion.GetHeight()), m_useIconQuestion, g_menuTime);
         else if (icon == UsableIcon::Revive)
             sb.DrawSprite(pos - vec2(m_useIconRevive.GetWidth() / 2, y + m_useIconRevive.GetHeight()), m_useIconRevive, g_menuTime);
         else
         {
             sb.DrawSprite(pos - vec2(m_useIcon.GetWidth() / 2, y + m_useIcon.GetHeight()), m_useIcon, g_menuTime);
             if (icon == UsableIcon::Key)
                 sb.DrawSprite(pos - vec2(m_useIconKey.GetWidth() / 2, y + m_useIcon.GetHeight() + 2 + m_useIconKey.GetHeight()), m_useIconKey, g_menuTime);
         }
     }
GetBossBar()
BossBarWidget HUD::GetBossBar (Actor@ actor) inline private
Definition at line 665 of file HUD.as.
References BossBarWidget::m_actor, Widget::m_children, and m_wBossBars.
Referenced by WorldScript::BossBarCheckpoint::ServerExecute().
     {
         if (m_wBossBars is null)
             return null;
         for (uint i = 0; i < m_wBossBars.m_children.length(); i++)
         {
             BossBarWidget@ bar = cast<BossBarWidget>(m_wBossBars.m_children[i]);
             if (bar is null)
                 continue;
             if (bar.m_actor is actor)
                 return bar;
         }
         return null;
     }
GetCountDown()
TextWidget HUD::GetCountDown () inline private
Definition at line 584 of file HUD.as.
References m_widget.
Referenced by WorldScript::CountdownText::ServerExecute().
     {
         return cast<TextWidget>(m_widget.GetWidgetById("countdown"));
     }
GetTopNumberIcon()
TopNumberIconWidget HUD::GetTopNumberIcon (string id) inline private
Definition at line 594 of file HUD.as.
References m_topNumberIcons.
Referenced by SetTopNumberIcon().
     {
         for (uint i = 0; i < m_topNumberIcons.length(); i++)
         {
             auto wIcon = m_topNumberIcons[i];
             if (wIcon.m_topID == id)
                 return wIcon;
         }
         return null;
     }
HideTopNumberIcon()
void HUD::HideTopNumberIcon (string id) inline private
Definition at line 621 of file HUD.as.
References m_topNumberIcons.
     {
         for (uint i = 0; i < m_topNumberIcons.length(); i++)
         {
             auto wIcon = m_topNumberIcons[i];
             if (wIcon.m_topID != id)
                 continue;
             wIcon.RemoveFromParent();
             m_topNumberIcons.removeAt(i);
         }
     }
InitializeKeys()
void HUD::InitializeKeys (PlayerRecord@ record) inline private
Definition at line 167 of file HUD.as.
References Widget::AddChild(), Widget::ClearChildren(), RectWidget::Clone(), m_wKeyList, m_wKeyTemplate, and num.
Referenced by Update().
     {
         m_wKeyList.ClearChildren();
         for (uint i = 0; i < record.keys.length(); i++)
         {
             int num = record.keys[i];
             auto wNewKey = cast<RectWidget>(m_wKeyTemplate.Clone());
             wNewKey.m_visible = true;
             wNewKey.SetID("");
             wNewKey.m_visible = (num > 0);
             auto wSprite = cast<SpriteWidget>(wNewKey.GetWidgetById("icon"));
             wSprite.SetSprite("topbar-icon-key-" + i);
             auto wText = cast<TextWidget>(wNewKey.GetWidgetById("value"));
             wText.m_visible = GetVarBool("ui_key_count");
             wText.SetText("" + num);
             m_wKeyList.AddChild(wNewKey);
         }
     }
OnDeath()
void HUD::OnDeath () inline private
Definition at line 162 of file HUD.as.
     {
         // ?
     }
PlayPickup()
void HUD::PlayPickup () inline private
Definition at line 683 of file HUD.as.
     {
         // ?
     }
SetExtraLife()
void HUD::SetExtraLife () inline private
Definition at line 589 of file HUD.as.
Referenced by GiveLives::Apply(), and GameModeHandler::ExtraLives().
     {
         // ?
     }
SetTopNumberIcon()
void HUD::SetTopNumberIcon (string id, int number) inline private
Definition at line 605 of file HUD.as.
References Widget::AddChild(), Widget::Clone(), GetTopNumberIcon(), id, m_topNumberIcons, m_wTopNumberList, and m_wTopNumberTemplate.
Referenced by Campaign::Start().
     {
         auto wIcon = GetTopNumberIcon(id);
         if (wIcon is null)
         {
             @wIcon = cast<TopNumberIconWidget>(m_wTopNumberTemplate.Clone());
             wIcon.m_visible = true;
             wIcon.SetID("");
             wIcon.m_topID = id;
             wIcon.SetSprite("topnumber-" + id);
             m_wTopNumberList.AddChild(wIcon);
             m_topNumberIcons.insertLast(wIcon);
         }
         wIcon.SetNumber(number);
     }
ShowBuffIcon()
Widget HUD::ShowBuffIcon (PlayerBase@ player, IBuffWidgetInfo@ buff) inline private
Definition at line 688 of file HUD.as.
References Widget::AddChild(), buff, Widget::Clone(), g_gameMode, g_players, BuffWidget::m_buff, Widget::m_children, PlayerBase::m_record, m_wBuffList, and m_wBuffTemplate.
     {
         if (player is null)
             return null;
         auto gm = cast<Campaign>(g_gameMode);
         if (gm is null)
             return null;
         if (gm.m_spectating)
         {
             if (player.m_record !is g_players[gm.m_spectatingPlayer])
                 return null;
         }
         else if (!player.m_record.local)
             return null;
         if (buff.GetBuffIcon() is null)
             return null;
         BuffWidget@ wExisting = null;
         for (uint i = 0; i < m_wBuffList.m_children.length(); i++)
         {
             auto wBuff = cast<BuffWidget>(m_wBuffList.m_children[i]);
             if (wBuff.m_buff is buff)
             {
                 @wExisting = wBuff;
                 break;
             }
         }
         if (wExisting !is null)
             return wExisting;
         auto wNewBuff = cast<BuffWidget>(m_wBuffTemplate.Clone());
         wNewBuff.SetID("");
         wNewBuff.m_visible = true;
         @wNewBuff.m_buff = buff;
         m_wBuffList.AddChild(wNewBuff);
         return wNewBuff;
     }
Start()
void HUD::Start () inline private
Definition at line 151 of file HUD.as.
References g_gameMode, m_wCurrencyGoldIcon, m_wCurrencyOreIcon, m_wDebugHandicap, and SpriteWidget::SetSprite().
Referenced by Campaign::Start().
     {
         if (cast<Town>(g_gameMode) !is null)
         {
             m_wCurrencyGoldIcon.SetSprite("topbar-icon-gold-town");
             m_wCurrencyOreIcon.SetSprite("topbar-icon-ore-town");
         }
         m_wDebugHandicap.m_visible = GetVarBool("ui_debug_handicap");
     }
Update() [1/2]
void HUD::Update (int dt) inline override private
Definition at line 191 of file HUD.as.
References g_gameMode, g_players, GetLocalPlayerRecord(), BaseGameMode::m_spectating, and BaseGameMode::m_spectatingPlayer.
Referenced by Campaign::UpdateWidgets().
     {
         BaseGameMode@ gm = cast<BaseGameMode>(g_gameMode);
         if (gm is null)
             return;
         PlayerRecord@ record = null;
         if (gm.m_spectating)
             @record = g_players[gm.m_spectatingPlayer];
         else
             @record = GetLocalPlayerRecord();
         Update(dt, record);
     }
Update() [2/2]
void HUD::Update (int dt, PlayerRecord@ record) inline private
Definition at line 206 of file HUD.as.
References clamp(), formatThousands(), g_allModifiers, g_flags, g_gameMode, InitializeKeys(), m_arrSkillWidgets, m_barStatsTimeC, Widget::m_children, m_lastRecord, DotbarWidget::m_max, Widget::m_offset, m_speechBubbles, DotbarWidget::m_value, SpriteBarWidget::m_valueExtra, Widget::m_visible, m_wBarCombo, m_wBarComboTimer, m_wBarExperience, m_wBarHealth, m_wBarMana, m_wBossBars, m_wBuffList, m_wCombo, m_wCurrencyGold, m_wCurrencyOre, m_wCurrencySkillPoints, m_wCurrencySkillPointsContainer, m_wDebugHandicap, m_wHealth, m_wHealthGui, Widget::m_width, m_wKeyList, m_wMana, AGameMode::m_wndWidth, m_wPotion, m_wPotionBar, m_wSkillGui, m_wTopbar, m_wTopNumberList, min, num, SetSkill(), SpriteWidget::SetSprite(), TextWidget::SetText(), SpriteBarWidget::SetValue(), SpeechBubbleManager::Update(), Tutorial::Update(), and Update().
     {
         if (record is null)
             return;
         m_speechBubbles.Update(dt);
         m_wHealthGui.m_visible = GetVarBool("ui_hud_stats");
         m_wSkillGui.m_visible = GetVarBool("ui_hud_skills");
         m_wBuffList.m_visible = m_wSkillGui.m_visible;
         m_wBossBars.m_visible = (m_wBossBars.m_children.length() > 2 && GetVarBool("ui_hud_bossbar"));
         m_wTopbar.m_visible = GetVarBool("ui_hud_topbar");
         m_wTopNumberList.m_visible = m_wTopbar.m_visible;
         m_wBossBars.m_width = g_gameMode.m_wndWidth;
         m_wBossBars.m_offset.x = 15;
         if (m_wHealthGui.m_visible)
         {
             int statsWidth = m_wHealthGui.m_width - 7;
             m_wBossBars.m_offset.x = statsWidth;
             m_wBossBars.m_width -= statsWidth;
         }
         else
             m_wBossBars.m_width -= 15;
         if (m_wSkillGui.m_visible)
             m_wBossBars.m_width -= m_wSkillGui.m_width - 7;
         else
             m_wBossBars.m_width -= 15;
         Tutorial::Update(dt);
         if (m_lastRecord !is record)
         {
             if (m_lastRecord is null)
                 InitializeKeys(record);
             @m_lastRecord = record;
         }
         if (record.hp < 1.0f || record.mana < 1.0f)
             m_barStatsTimeC = 1500;
         else if (m_barStatsTimeC > 0)
             m_barStatsTimeC -= dt;
         auto player = cast<PlayerBase>(record.actor);
         if (player !is null)
         {
             for (int i = 0; i < min(m_arrSkillWidgets.length(), player.m_skills.length()); i++)
                 m_arrSkillWidgets[i].SetSkill(player.m_skills[i]);
             auto localPlayer = cast<Player>(player);
             if (localPlayer !is null)
             {
                 vec2 comboBars = localPlayer.GetComboBars();
                 comboBars.x = clamp(comboBars.x, 0.0f, 1.0f);
                 m_wBarCombo.SetValue(comboBars.x);
                 m_wBarComboTimer.SetValue(comboBars.x * comboBars.y);
                 m_wCombo.m_visible = comboBars.x >= 1.0f;
                 m_wCombo.SetText("" + localPlayer.m_comboCount);
             }
             else
             {
                 m_wBarCombo.SetValue(0);
                 m_wBarComboTimer.SetValue(0);
                 m_wCombo.m_visible = false;
             }
             int charges = 1 + g_allModifiers.PotionCharges();
             float potionSpriteStep = (4.0f / float(charges));
             int potionSprite = (4 - int(round(potionSpriteStep * record.potionChargesUsed)));
             if (potionSprite < 0 || record.potionChargesUsed == charges) potionSprite = 0;
             else if (potionSprite > 4) potionSprite = 4;
             //NOTE: This has to be in Update() since this unlocks when you find a well in dungeon
             m_wPotion.m_visible = g_flags.IsSet("unlock_apothecary");
             if (m_wPotion.m_visible)
             {
                 m_wPotion.SetSprite("potion-" + potionSprite);
                 m_wPotionBar.m_value = (charges - record.potionChargesUsed);
                 m_wPotionBar.m_max = charges;
             }
             //TODO: use Player instead of localPlayer so we can spectate player's proper stats
             ivec2 extraStats;
             ivec2 extraStatsFromItems;
             if (localPlayer !is null)
             {
                 extraStats = g_allModifiers.StatsAdd(localPlayer);
                 extraStatsFromItems = localPlayer.m_record.modifiersItems.StatsAdd(localPlayer);
             }
             float maxHealth = record.MaxHealth() + extraStats.x;
             float maxMana = record.MaxMana() + extraStats.y;
             m_wBarHealth.SetValue(record.hp);
             m_wBarHealth.m_valueExtra = 1.0f - (extraStatsFromItems.x / maxHealth);
             m_wHealth.SetText("" + int(ceil(record.hp * maxHealth)));
             m_wBarMana.SetValue(record.mana);
             m_wBarMana.m_valueExtra = 1.0f - (extraStatsFromItems.y / maxMana);
             m_wMana.SetText("" + int(floor(record.mana * maxMana)));
         }
         else
         {
             for (uint i = 0; i < m_arrSkillWidgets.length(); i++)
                 m_arrSkillWidgets[i].SetSkill(null);
             m_wBarHealth.SetValue(0);
             m_wHealth.SetText("0");
             m_wBarMana.SetValue(0);
             m_wMana.SetText("0");
             m_wBarCombo.SetValue(0);
             m_wBarComboTimer.SetValue(0);
             m_wPotion.SetSprite("potion-0");
         }
         int xpStart = record.LevelExperience(record.level - 1);
         int xpEnd = record.LevelExperience(record.level) - xpStart;
         int xpNow = record.experience - xpStart;
         m_wBarExperience.SetValue(xpNow / float(xpEnd));
         auto gm = cast<Campaign>(g_gameMode);
         if (gm !is null && gm.m_townLocal !is null)
         {
             auto town = gm.m_townLocal;
             int currGold = town.m_gold;
             int currOre = town.m_ore;
             auto gmTown = cast<Town>(g_gameMode);
             if (gmTown is null)
             {
                 currGold = record.runGold;
                 currOre = record.runOre;
             }
             else
             {
                 m_wCurrencySkillPointsContainer.m_visible = GetVarBool("ui_hud_topbar");
                 m_wCurrencySkillPoints.SetText(formatThousands(record.GetAvailableSkillpoints()));
             }
             m_wCurrencyGold.SetText(formatThousands(currGold));
             m_wCurrencyOre.SetText(formatThousands(currOre));
         }
         bool showKeyCount = GetVarBool("ui_key_count");
         for (uint i = 0; i < record.keys.length(); i++)
         {
             int num = record.keys[i];
             m_wKeyList.m_children[i].m_visible = (num > 0);
             auto wTextValue = cast<TextWidget>(m_wKeyList.m_children[i].GetWidgetById("value"));
             wTextValue.m_visible = showKeyCount;
             if (wTextValue.m_visible)
                 wTextValue.SetText("" + num);
         }
         if (m_wDebugHandicap.m_visible)
             m_wDebugHandicap.SetText("Handicap: " + record.handicap);
 %PROFILE_START HUD UpdateWidgets
         IWidgetHoster::Update(dt);
 %PROFILE_STOP
     }
Member Data Documentation
m_arrSkillWidgets
array<SkillWidget@> HUD::m_arrSkillWidgets private
Definition at line 59 of file HUD.as.
Referenced by HUD(), and Update().
m_barStatsTimeC
int HUD::m_barStatsTimeC private
Definition at line 31 of file HUD.as.
Referenced by DrawPlayerBars(), and Update().
m_currAnnounce
WorldScript::AnnounceText HUD::m_currAnnounce private
Definition at line 5 of file HUD.as.
m_currentUseIcon
UsableIcon HUD::m_currentUseIcon private
Definition at line 11 of file HUD.as.
m_guiDef
GUIDef HUD::m_guiDef private
Definition at line 3 of file HUD.as.
Referenced by HUD(), PlayerWaypoint::PlayerWaypoint(), and ScriptWaypoint::ScriptWaypoint().
m_lastRecord
PlayerRecord HUD::m_lastRecord private
Definition at line 61 of file HUD.as.
Referenced by Update().
m_speechBubbles
SpeechBubbleManager HUD::m_speechBubbles private
Definition at line 9 of file HUD.as.
Referenced by WorldScript::HideAllSpeechBubbles::ClientExecute(), Draw(), HUD(), and Update().
m_tooltipItems
Tooltip HUD::m_tooltipItems private
Definition at line 63 of file HUD.as.
Referenced by DrawHoverItem(), and HUD().
m_topNumberIcons
array<TopNumberIconWidget@> HUD::m_topNumberIcons private
Definition at line 70 of file HUD.as.
Referenced by ClearTopNumberIcons(), GetTopNumberIcon(), HideTopNumberIcon(), Campaign::Save(), and SetTopNumberIcon().
m_tutorialData
uint HUD::m_tutorialData private
Definition at line 26 of file HUD.as.
m_useIcon
Sprite HUD::m_useIcon private
Definition at line 12 of file HUD.as.
Referenced by DrawUseIcon(), and HUD().
m_useIconCross
Sprite HUD::m_useIconCross private
Definition at line 13 of file HUD.as.
Referenced by DrawUseIcon(), and HUD().
m_useIconExit
Sprite HUD::m_useIconExit private
Definition at line 17 of file HUD.as.
Referenced by DrawUseIcon(), and HUD().
m_useIconKey
Sprite HUD::m_useIconKey private
Definition at line 14 of file HUD.as.
Referenced by DrawUseIcon(), and HUD().
m_useIconQuestion
Sprite HUD::m_useIconQuestion private
Definition at line 18 of file HUD.as.
Referenced by DrawUseIcon(), and HUD().
m_useIconRevive
Sprite HUD::m_useIconRevive private
Definition at line 19 of file HUD.as.
Referenced by DrawUseIcon(), and HUD().
m_useIconShop
Sprite HUD::m_useIconShop private
Definition at line 15 of file HUD.as.
Referenced by DrawUseIcon(), and HUD().
m_useIconSpeech
Sprite HUD::m_useIconSpeech private
Definition at line 16 of file HUD.as.
Referenced by DrawUseIcon(), and HUD().
m_waypoints
WaypointMarkersWidget HUD::m_waypoints private
Definition at line 7 of file HUD.as.
Referenced by HUD().
m_wBarCombo
SpriteBarWidget HUD::m_wBarCombo private
Definition at line 40 of file HUD.as.
Referenced by HUD(), and Update().
m_wBarComboTimer
SpriteBarWidget HUD::m_wBarComboTimer private
Definition at line 41 of file HUD.as.
Referenced by HUD(), and Update().
m_wBarExperience
SpriteBarWidget HUD::m_wBarExperience private
Definition at line 42 of file HUD.as.
Referenced by HUD(), and Update().
m_wBarHealth
SpriteBarWidget HUD::m_wBarHealth private
Definition at line 33 of file HUD.as.
Referenced by HUD(), and Update().
m_wBarMana
SpriteBarWidget HUD::m_wBarMana private
Definition at line 36 of file HUD.as.
Referenced by HUD(), and Update().
m_wBossBars
Widget HUD::m_wBossBars private
Definition at line 24 of file HUD.as.
Referenced by AddBossBar(), GetBossBar(), HUD(), and Update().
m_wBuffList
Widget HUD::m_wBuffList private
Definition at line 67 of file HUD.as.
Referenced by HUD(), ShowBuffIcon(), and Update().
m_wBuffTemplate
Widget HUD::m_wBuffTemplate private
Definition at line 68 of file HUD.as.
Referenced by HUD(), and ShowBuffIcon().
m_wCombo
TextWidget HUD::m_wCombo private
Definition at line 39 of file HUD.as.
Referenced by HUD(), and Update().
m_wCurrencyGold
TextWidget HUD::m_wCurrencyGold private
Definition at line 44 of file HUD.as.
Referenced by HUD(), and Update().
m_wCurrencyGoldIcon
SpriteWidget HUD::m_wCurrencyGoldIcon private
Definition at line 45 of file HUD.as.
Referenced by HUD(), and Start().
m_wCurrencyOre
TextWidget HUD::m_wCurrencyOre private
Definition at line 47 of file HUD.as.
Referenced by HUD(), and Update().
m_wCurrencyOreIcon
SpriteWidget HUD::m_wCurrencyOreIcon private
Definition at line 48 of file HUD.as.
Referenced by HUD(), and Start().
m_wCurrencySkillPoints
TextWidget HUD::m_wCurrencySkillPoints private
Definition at line 51 of file HUD.as.
Referenced by HUD(), and Update().
m_wCurrencySkillPointsContainer
Widget HUD::m_wCurrencySkillPointsContainer private
Definition at line 50 of file HUD.as.
Referenced by HUD(), and Update().
m_wDeadMessage
TextWidget HUD::m_wDeadMessage private
Definition at line 28 of file HUD.as.
Referenced by HUD(), and Campaign::UpdateWidgets().
m_wDeadMessage2
TextWidget HUD::m_wDeadMessage2 private
Definition at line 29 of file HUD.as.
Referenced by HUD(), and Campaign::UpdateWidgets().
m_wDebugHandicap
TextWidget HUD::m_wDebugHandicap private
Definition at line 65 of file HUD.as.
Referenced by HUD(), Start(), and Update().
m_wHealth
TextWidget HUD::m_wHealth private
Definition at line 34 of file HUD.as.
Referenced by HUD(), and Update().
m_wHealthGui
Widget HUD::m_wHealthGui private
Definition at line 22 of file HUD.as.
Referenced by HUD(), and Update().
m_wKeyList
Widget HUD::m_wKeyList private
Definition at line 54 of file HUD.as.
Referenced by HUD(), InitializeKeys(), and Update().
m_wKeyTemplate
RectWidget HUD::m_wKeyTemplate private
Definition at line 53 of file HUD.as.
Referenced by HUD(), and InitializeKeys().
m_wMana
TextWidget HUD::m_wMana private
Definition at line 37 of file HUD.as.
Referenced by HUD(), and Update().
m_wPotion
SpriteWidget HUD::m_wPotion private
Definition at line 56 of file HUD.as.
Referenced by HUD(), and Update().
m_wPotionBar
DotbarWidget HUD::m_wPotionBar private
Definition at line 57 of file HUD.as.
Referenced by HUD(), and Update().
m_wSkillGui
Widget HUD::m_wSkillGui private
Definition at line 23 of file HUD.as.
Referenced by HUD(), and Update().
m_wTopbar
Widget HUD::m_wTopbar private
Definition at line 21 of file HUD.as.
Referenced by HUD(), and Update().
m_wTopNumberList
Widget HUD::m_wTopNumberList private
Definition at line 72 of file HUD.as.
Referenced by ClearTopNumberIcons(), HUD(), SetTopNumberIcon(), and Update().
m_wTopNumberTemplate
Widget HUD::m_wTopNumberTemplate private
Definition at line 71 of file HUD.as.
Referenced by HUD(), and SetTopNumberIcon().
m_wTutorial
TextWidget HUD::m_wTutorial private
Definition at line 27 of file HUD.as.
The documentation for this class was generated from the following file:
scripts/GUI/HUD/HUD.as