HoHDocs: ShootBolt Class Reference
ShootBolt Class Reference
Private Member Functions
ShootBolt (UnitPtr unit, SValue &params)
void SetWeaponInformation (uint weapon)
bool Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
bool CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
Private Attributes
UnitScene m_fx
int m_height
int m_spread
array< IEffect@> m_effects
Detailed Description
Definition at line 1 of file ShootBolt.as.
Constructor & Destructor Documentation
ShootBolt()
ShootBolt::ShootBolt (UnitPtr unit, SValue & params) inline private
Definition at line 8 of file ShootBolt.as.
References Fountain::GetEffect(), LoadEffects(), m_effects, m_fx, m_height, m_spread, and unit.
     {
         @m_fx = Resources::GetEffect(GetParamString(unit, params, "fx", false));
         m_height = GetParamInt(unit, params, "height", false, 0);
         m_spread = GetParamInt(unit, params, "spread", false, 0);
         @m_effects = LoadEffects(unit, params);
     }
Member Function Documentation
Apply()
bool ShootBolt::Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk) inline private
Definition at line 21 of file ShootBolt.as.
References ApplyEffects(), DrawLightningBolt(), m_effects, m_fx, m_height, m_spread, Actor::m_unit, and xy().
     {
         if (!target.IsValid())
             return false;
         vec2 shooterPos = xy(owner.m_unit.GetPosition());
         auto diff = pos - shooterPos;
         ApplyEffects(m_effects, owner, target, pos, normalize(diff), intensity, husk);
         DrawLightningBolt(m_fx, shooterPos + vec2(randi(m_spread) - m_spread / 2, randi(m_spread) - m_spread / 2 - m_height), pos + vec2(randi(8) - 4, randi(8) - 4));
         return true;
     }
CanApply()
bool ShootBolt::CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) inline override private
Definition at line 35 of file ShootBolt.as.
     {
         return true;
     }
SetWeaponInformation()
void ShootBolt::SetWeaponInformation (uint weapon) inline private
Definition at line 16 of file ShootBolt.as.
References m_effects, and PropagateWeaponInformation().
     {
         PropagateWeaponInformation(m_effects, weapon);
     }
Member Data Documentation
m_effects
array<IEffect@> ShootBolt::m_effects private
Definition at line 6 of file ShootBolt.as.
Referenced by Apply(), SetWeaponInformation(), and ShootBolt().
m_fx
UnitScene ShootBolt::m_fx private
Definition at line 3 of file ShootBolt.as.
Referenced by Apply(), and ShootBolt().
m_height
int ShootBolt::m_height private
Definition at line 4 of file ShootBolt.as.
Referenced by Apply(), and ShootBolt().
m_spread
int ShootBolt::m_spread private
Definition at line 5 of file ShootBolt.as.
Referenced by Apply(), and ShootBolt().
The documentation for this class was generated from the following file:
scripts/Behaviors/Effects/ShootBolt.as