HoHDocs: Menu::ControlMapMenu Class Reference
Menu::ControlMapMenu Class Reference
Private Member Functions
ControlMapMenu (MenuProvider@ provider, string mapID)
void Initialize (GUIDef@ def) override
void AddNewControlAxis (bool uneven, string action, ControlBindingSetAxis setAxis)
Widget AddNewControl (bool uneven, string action)
void OnFunc (Widget@ sender, string name) override
Private Attributes
ControlMap m_map
string m_mapID
RectWidget m_wTemplate
Widget m_wControls
Detailed Description
Definition at line 3 of file ControlMapMenu.as.
Constructor & Destructor Documentation
ControlMapMenu()
Menu::ControlMapMenu::ControlMapMenu (MenuProvider@ provider, string mapID) inline private
Definition at line 11 of file ControlMapMenu.as.
References Menu::Menu::m_isPopup, and m_mapID.
         {
             m_mapID = mapID;
             super(provider);
             m_isPopup = true;
         }
Member Function Documentation
AddNewControl()
Widget Menu::ControlMapMenu::AddNewControl (bool uneven, string action) inline private
Definition at line 66 of file ControlMapMenu.as.
References Widget::AddChild(), RectWidget::Clone(), RectWidget::m_color, MenuControlInputWidget::m_map, m_map, m_wControls, m_wTemplate, TextWidget::SetText(), and MenuControlInputWidget::UpdateText().
Referenced by AddNewControlAxis(), and Initialize().
         {
             RectWidget@ wNewControl = cast<RectWidget>(m_wTemplate.Clone());
             wNewControl.m_visible = true;
             wNewControl.SetID("");
             if (uneven)
                 wNewControl.m_color = tocolor(vec4(0.9, 0.9, 1, 0.05));
             TextWidget@ wName = cast<TextWidget>(wNewControl.GetWidgetById("name"));
             if (wName !is null)
             {
                 wName.SetText(Resources::GetString(".menu.controls." + action.toLower()));
                 if (action.substr(0, 6) == "Weapon")
                     wName.m_tooltipText = Resources::GetString(".menu.controls." + action.toLower() + ".help");
             }
             MenuControlInputWidget@ wInput = cast<MenuControlInputWidget>(wNewControl.GetWidgetById("button"));
             if (wInput !is null)
             {
                 @wInput.m_map = m_map;
                 wInput.m_func = action;
                 wInput.UpdateText();
             }
             m_wControls.AddChild(wNewControl);
             return wNewControl;
         }
AddNewControlAxis()
void Menu::ControlMapMenu::AddNewControlAxis (bool uneven, string action, ControlBindingSetAxis setAxis) inline private
Definition at line 52 of file ControlMapMenu.as.
References AddNewControl(), Widget::GetWidgetById(), MenuControlInputWidget::m_axisAction, MenuControlInputWidget::m_axisSet, TextWidget::SetText(), and MenuControlInputWidget::UpdateText().
Referenced by Initialize().
         {
             Widget@ w = AddNewControl(uneven, action);
             MenuControlInputWidget@ wInput = cast<MenuControlInputWidget>(w.GetWidgetById("button"));
             wInput.m_axisAction = true;
             wInput.m_axisSet = setAxis;
             wInput.UpdateText();
             TextWidget@ wName = cast<TextWidget>(w.GetWidgetById("name"));
             if (wName !is null)
                 wName.SetText(Resources::GetString(".menu.controls." + action.toLower() + ".axis" + setAxis));
         }
Initialize()
void Menu::ControlMapMenu::Initialize (GUIDef@ def) inline override private
Definition at line 20 of file ControlMapMenu.as.
References AddNewControl(), AddNewControlAxis(), ControlMap::BeginStaging(), GetControlBindings(), Low, m_map, m_mapID, m_wControls, m_widget, and m_wTemplate.
         {
             auto cb = GetControlBindings();
             @m_map = cb.GetMap(m_mapID);
             if (m_map is null)
             {
                 PrintError("Control map \"" + m_mapID + "\" was not found!");
                 return;
             }
             m_map.BeginStaging();
             @m_wTemplate = cast<RectWidget>(m_widget.GetWidgetById("template"));
             @m_wControls = m_widget.GetWidgetById("controls");
             if (m_wTemplate is null)
                 return;
             if (m_mapID == "kbm")
             {
                 AddNewControlAxis(false, "move_y", ControlBindingSetAxis::Low);
                 AddNewControlAxis(true, "move_y", ControlBindingSetAxis::High);
                 AddNewControlAxis(false, "move_x", ControlBindingSetAxis::Low);
                 AddNewControlAxis(true, "move_x", ControlBindingSetAxis::High);
             }
             array<string>@ actions = cb.GetAvailableActions();
             for (uint i = 0; i < actions.length(); i++)
                 AddNewControl(i % 2 == 1, actions[i]);
         }
OnFunc()
void Menu::ControlMapMenu::OnFunc (Widget@ sender, string name) inline override private
Definition at line 96 of file ControlMapMenu.as.
References ControlMap::BeginStaging(), Menu::Menu::Close(), ControlMap::CommitStaging(), ControlMap::Defaults(), g_gameMode, GetControlBindings(), Widget::GetWidgetById(), Widget::m_children, m_map, m_wControls, name, Menu::Menu::OnFunc(), AGameMode::ShowDialog(), and MenuControlInputWidget::UpdateText().
         {
             if (name == "reset-controls")
             {
                 g_gameMode.ShowDialog(
                     "reset-controls",
                     Resources::GetString(".menu.controls.defaults_dialog"),
                     Resources::GetString(".menu.yes"),
                     Resources::GetString(".menu.no"),
                     this
                 );
             }
             else if (name == "reset-controls yes")
             {
                 m_map.Defaults();
                 m_map.BeginStaging();
                 for (uint i = 0; i < m_wControls.m_children.length(); i++)
                 {
                     Widget@ wBox = m_wControls.m_children[i];
                     MenuControlInputWidget@ wInput = cast<MenuControlInputWidget>(wBox.GetWidgetById("button"));
                     if (wInput !is null)
                         wInput.UpdateText();
                 }
             }
             else if (name == "apply-controls")
             {
                 m_map.CommitStaging();
                 auto cb = GetControlBindings();
                 if (cb !is null)
                     cb.Save();
                 Close();
             }
             else
                 Menu::OnFunc(sender, name);
         }
Member Data Documentation
m_map
ControlMap Menu::ControlMapMenu::m_map private
Definition at line 5 of file ControlMapMenu.as.
Referenced by AddNewControl(), Initialize(), and OnFunc().
m_mapID
string Menu::ControlMapMenu::m_mapID private
Definition at line 6 of file ControlMapMenu.as.
Referenced by ControlMapMenu(), and Initialize().
m_wControls
Widget Menu::ControlMapMenu::m_wControls private
Definition at line 9 of file ControlMapMenu.as.
Referenced by AddNewControl(), Initialize(), and OnFunc().
m_wTemplate
RectWidget Menu::ControlMapMenu::m_wTemplate private
Definition at line 8 of file ControlMapMenu.as.
Referenced by AddNewControl(), and Initialize().
The documentation for this class was generated from the following file:
scripts/GUI/Menus/ControlMapMenu.as