HoHDocs: WorldScript::PlayAttachedEffect Class Reference
WorldScript::PlayAttachedEffect Class Reference
Private Member Functions
SValue ServerExecute ()
void ClientExecute (SValue@ val)
Private Attributes
UnitScene Effect
int Layer
UnitFeed Objects
int OffsetY
Detailed Description
Definition at line 4 of file PlayAttachedEffect.as.
Member Function Documentation
ClientExecute()
void WorldScript::PlayAttachedEffect::ClientExecute (SValue@ val) inline private
Definition at line 30 of file PlayAttachedEffect.as.
References ServerExecute().
         {
             ServerExecute();
         }
ServerExecute()
SValue WorldScript::PlayAttachedEffect::ServerExecute () inline private
Definition at line 18 of file PlayAttachedEffect.as.
References Effect, Objects, and PlayEffect().
Referenced by ClientExecute().
         {
             auto units = Objects.FetchAll();
             for (uint i = 0; i < units.length(); i++)
             {
                 //TODO: Layer
                 //TODO: OffsetY
                 PlayEffect(Effect, units[i]);
             }
             return null;
         }
Member Data Documentation
Effect
UnitScene WorldScript::PlayAttachedEffect::Effect private
Definition at line 7 of file PlayAttachedEffect.as.
Referenced by ServerExecute().
Layer
int WorldScript::PlayAttachedEffect::Layer private
Definition at line 10 of file PlayAttachedEffect.as.
Objects
UnitFeed WorldScript::PlayAttachedEffect::Objects private
Definition at line 13 of file PlayAttachedEffect.as.
Referenced by ServerExecute().
OffsetY
int WorldScript::PlayAttachedEffect::OffsetY private
Definition at line 16 of file PlayAttachedEffect.as.
The documentation for this class was generated from the following file:
scripts/WorldScript/PlayAttachedEffect.as