HoHDocs: Nova Class Reference
Nova Class Reference
Private Member Functions
Nova (UnitPtr unit, SValue &params)
void SetWeaponInformation (uint weapon)
bool NeedNetParams ()
bool Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk)
bool CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) override
bool DoAction (SValueBuilder@ builder, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity)
bool NetDoAction (SValue@ param, Actor@ owner, vec2 pos, vec2 dir)
void Update (int dt, int cooldown)
void DoNova (Actor@ owner, Actor@ target, vec2 pos, float intensity, bool husk)
Private Attributes
UnitProducer m_projectile
int m_projectiles
float m_projDist
uint m_weaponInfo
Detailed Description
Definition at line 1 of file Nova.as.
Constructor & Destructor Documentation
Nova()
Nova::Nova (UnitPtr unit, SValue & params) inline private
Definition at line 8 of file Nova.as.
References m_projDist, m_projectile, m_projectiles, and unit.
     {
         @m_projectile = Resources::GetUnitProducer(GetParamString(unit, params, "projectile"));
         m_projectiles = GetParamInt(unit, params, "projectiles", false, 1);
         m_projDist = GetParamFloat(unit, params, "proj-dist", false);
     }
Member Function Documentation
Apply()
bool Nova::Apply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity, bool husk) inline private
Definition at line 22 of file Nova.as.
References DoNova().
     {
         Actor@ targetActor;
         if (target.IsValid())
             @targetActor = cast<Actor>(target.GetScriptBehavior());
         DoNova(owner, targetActor, pos, intensity, husk);
         return true;
     }
CanApply()
bool Nova::CanApply (Actor@ owner, UnitPtr target, vec2 pos, vec2 dir, float intensity) inline override private
Definition at line 32 of file Nova.as.
     {
         return true;
     }
DoAction()
bool Nova::DoAction (SValueBuilder@ builder, Actor@ owner, Actor@ target, vec2 pos, vec2 dir, float intensity) inline private
Definition at line 37 of file Nova.as.
References DoNova(), and Actor::m_unit.
     {
         builder.PushArray();
         builder.PushFloat(intensity);
         if (target is null)
             builder.PushInteger(0);
         else
             builder.PushInteger(target.m_unit.GetId());
         DoNova(owner, target, pos, intensity, false);
         builder.PopArray();
         return true;
     }
DoNova()
void Nova::DoNova (Actor@ owner, Actor@ target, vec2 pos, float intensity, bool husk) inline private
Definition at line 71 of file Nova.as.
References g_scene, m_projDist, m_projectile, m_projectiles, m_weaponInfo, and xyz().
Referenced by Apply(), DoAction(), and NetDoAction().
     {
         for (int i = 0; i < m_projectiles; i++)
         {
             float ang = i * TwoPI / m_projectiles;
             vec2 shootDir = vec2(cos(ang), sin(ang));
             UnitPtr proj = m_projectile.Produce(g_scene, xyz(pos + shootDir * m_projDist));
             if (!proj.IsValid())
                 continue;
             IProjectile@ p = cast<IProjectile>(proj.GetScriptBehavior());
             if (p is null)
                 continue;
             p.Initialize(owner, shootDir, intensity, husk, target, m_weaponInfo);
         }
     }
NeedNetParams()
bool Nova::NeedNetParams () inline private
Definition at line 20 of file Nova.as.
 { return true; }
NetDoAction()
bool Nova::NetDoAction (SValue@ param, Actor@ owner, vec2 pos, vec2 dir) inline private
Definition at line 53 of file Nova.as.
References DoNova(), and g_scene.
     {
         array<SValue@>@ arr = param.GetArray();
         float intensity = arr[0].GetFloat();
         UnitPtr targetUnit = g_scene.GetUnit(arr[1].GetInteger());
         Actor@ target;
         if (targetUnit.IsValid())
             @target = cast<Actor>(targetUnit.GetScriptBehavior());
         DoNova(owner, target, pos, intensity, true);
         return true;
     }
SetWeaponInformation()
void Nova::SetWeaponInformation (uint weapon) inline private
Definition at line 15 of file Nova.as.
References m_weaponInfo.
     {
         m_weaponInfo = weapon;
     }
Update()
void Nova::Update (int dt, int cooldown) inline private
Definition at line 67 of file Nova.as.
     {
     }
Member Data Documentation
m_projDist
float Nova::m_projDist private
Definition at line 5 of file Nova.as.
Referenced by DoNova(), and Nova().
m_projectile
UnitProducer Nova::m_projectile private
Definition at line 3 of file Nova.as.
Referenced by DoNova(), and Nova().
m_projectiles
int Nova::m_projectiles private
Definition at line 4 of file Nova.as.
Referenced by DoNova(), and Nova().
m_weaponInfo
uint Nova::m_weaponInfo private
Definition at line 6 of file Nova.as.
Referenced by DoNova(), and SetWeaponInformation().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actions/Nova.as