HoHDocs: WerebullChargeHitSkill Class Reference
WerebullChargeHitSkill Class Reference
Private Member Functions
WerebullChargeHitSkill (UnitPtr unit, SValue &params)
void Initialize (UnitPtr unit, CompositeActorBehavior &behavior, int id)
void Save (SValueBuilder &builder)
void Load (SValue@ sval)
bool IsAvailable ()
void OnCollide (UnitPtr unit, vec2 normal)
bool IsCasting ()
void Update (int dt, bool isCasting)
void OnDamaged ()
void OnDeath ()
void Destroyed ()
void NetUseSkill (int stage, SValue@ param)
Private Attributes
UnitPtr m_unit
CompositeActorBehavior m_behavior
int m_id
array< IEffect@> m_effects
array< ISkillConditional@> m_conditionals
Detailed Description
Definition at line 1 of file WerebullChargeHitSkill.as.
Constructor & Destructor Documentation
WerebullChargeHitSkill()
WerebullChargeHitSkill::WerebullChargeHitSkill (UnitPtr unit, SValue & params) inline private
Definition at line 11 of file WerebullChargeHitSkill.as.
References LoadEffects(), LoadSkillConditionals(), m_conditionals, m_effects, and unit.
     {
         @m_effects = LoadEffects(unit, params);
         @m_conditionals = LoadSkillConditionals(unit, params);
     }
Member Function Documentation
Destroyed()
void WerebullChargeHitSkill::Destroyed () inline private
Definition at line 74 of file WerebullChargeHitSkill.as.
 {}
Initialize()
void WerebullChargeHitSkill::Initialize (UnitPtr unit, CompositeActorBehavior & behavior, int id) inline private
Definition at line 17 of file WerebullChargeHitSkill.as.
References id, m_behavior, m_id, m_unit, and unit.
     {
         m_unit = unit;
         @m_behavior = behavior;
         m_id = id;
     }
IsAvailable()
bool WerebullChargeHitSkill::IsAvailable () inline private
Definition at line 32 of file WerebullChargeHitSkill.as.
References CheckConditionals(), m_behavior, and m_conditionals.
Referenced by OnCollide().
     {
         return CheckConditionals(m_conditionals, m_behavior);
     }
IsCasting()
bool WerebullChargeHitSkill::IsCasting () inline private
Definition at line 66 of file WerebullChargeHitSkill.as.
     {
         return false;
     }
Load()
void WerebullChargeHitSkill::Load (SValue@ sval) inline private
Definition at line 28 of file WerebullChargeHitSkill.as.
     {
     }
NetUseSkill()
void WerebullChargeHitSkill::NetUseSkill (int stage, SValue@ param) inline private
Definition at line 75 of file WerebullChargeHitSkill.as.
 {}
OnCollide()
void WerebullChargeHitSkill::OnCollide (UnitPtr unit, vec2 normal) inline private
Definition at line 37 of file WerebullChargeHitSkill.as.
References ApplyEffects(), FilterAction(), IsAvailable(), m_behavior, m_effects, m_unit, unit, and xy().
     {
         if (!IsAvailable())
             return;
         if (!unit.IsValid())
             return;
         vec2 dir = m_unit.GetMoveDir();
         if (lengthsq(m_unit.GetMoveDir()) <= 0.01)
             return;
         if (dot(dir, normal) <= 0.0)
             return;
         auto b = cast<Actor>(unit.GetScriptBehavior());
         if (b !is null)
         {
             if (!b.IsTargetable())
                 return;
             if (FilterAction(b, m_behavior, 0.0, 0.0, 1.0, 1.0) <= 0.0)
                 return;
         }
         vec2 pos = xy(m_unit.GetPosition());
         ApplyEffects(m_effects, m_behavior, unit, pos, normal, m_behavior.m_buffs.DamageMul(), !Network::IsServer());
     }
OnDamaged()
void WerebullChargeHitSkill::OnDamaged () inline private
Definition at line 72 of file WerebullChargeHitSkill.as.
 {}
OnDeath()
void WerebullChargeHitSkill::OnDeath () inline private
Definition at line 73 of file WerebullChargeHitSkill.as.
 {}
Save()
void WerebullChargeHitSkill::Save (SValueBuilder & builder) inline private
Definition at line 24 of file WerebullChargeHitSkill.as.
     {
     }
Update()
void WerebullChargeHitSkill::Update (int dt, bool isCasting) inline private
Definition at line 71 of file WerebullChargeHitSkill.as.
 {}
Member Data Documentation
m_behavior
CompositeActorBehavior WerebullChargeHitSkill::m_behavior private
Definition at line 4 of file WerebullChargeHitSkill.as.
Referenced by Initialize(), IsAvailable(), and OnCollide().
m_conditionals
array<ISkillConditional@> WerebullChargeHitSkill::m_conditionals private
Definition at line 8 of file WerebullChargeHitSkill.as.
Referenced by IsAvailable(), and WerebullChargeHitSkill().
m_effects
array<IEffect@> WerebullChargeHitSkill::m_effects private
Definition at line 7 of file WerebullChargeHitSkill.as.
Referenced by OnCollide(), and WerebullChargeHitSkill().
m_id
int WerebullChargeHitSkill::m_id private
Definition at line 5 of file WerebullChargeHitSkill.as.
Referenced by Initialize().
m_unit
UnitPtr WerebullChargeHitSkill::m_unit private
Definition at line 3 of file WerebullChargeHitSkill.as.
Referenced by Initialize(), and OnCollide().
The documentation for this class was generated from the following file:
scripts/Behaviors/Actors/Enemies/Skills/WerebullChargeHitSkill.as