var dir_9f64808310dec86d138fd97176d1a823 =
[
    [ "eye.unit", "actors_2bosses_2eye_2eye_8unit.html", null ],
    [ "eye_ball_hit.effect", "eye__ball__hit_8effect.html", null ],
    [ "eye_bounce_fall.effect", "eye__bounce__fall_8effect.html", null ],
    [ "eye_bounce_jump.effect", "eye__bounce__jump_8effect.html", null ],
    [ "eye_death.effect", "eye__death_8effect.html", null ],
    [ "eye_death.unit", "eye__death_8unit.html", null ],
    [ "eye_death_blood.effect", "eye__death__blood_8effect.html", null ],
    [ "eye_death_explosion.effect", "eye__death__explosion_8effect.html", null ],
    [ "eye_explosion.effect", "eye__explosion_8effect.html", null ],
    [ "eye_fall.effect", "eye__fall_8effect.html", null ],
    [ "eye_jump.effect", "eye__jump_8effect.html", null ],
    [ "eye_magic.effect", "eye__magic_8effect.html", null ],
    [ "eye_magic_intro.effect", "eye__magic__intro_8effect.html", null ],
    [ "eye_magic_outro.effect", "eye__magic__outro_8effect.html", null ],
    [ "eye_ritual_decay.effect", "eye__ritual__decay_8effect.html", null ],
    [ "impact_blood.effect", "impact__blood_8effect.html", null ],
    [ "intro_eye.unit", "intro__eye_8unit.html", null ],
    [ "poison_area.unit", "poison__area_8unit.html", null ],
    [ "poison_area_active.unit", "poison__area__active_8unit.html", null ],
    [ "poison_area_end.effect", "poison__area__end_8effect.html", null ],
    [ "poison_area_indicator_32.effect", "poison__area__indicator__32_8effect.html", null ],
    [ "smoke_impact_eye.effect", "smoke__impact__eye_8effect.html", null ],
    [ "tooth.effect", "tooth_8effect.html", null ],
    [ "tooth.unit", "tooth_8unit.html", null ],
    [ "tooth_shard.unit", "tooth__shard_8unit.html", null ],
    [ "tooth_spew.unit", "tooth__spew_8unit.html", null ],
    [ "wisp.unit", "wisp_8unit.html", null ],
    [ "wisp_ritual.unit", "wisp__ritual_8unit.html", null ]
];