var dir_c5b025199ce6aae39c75d83238a7addd =
[
    [ "biting_chill.sval", "biting__chill_8sval.html", null ],
    [ "char.sval", "sorcerer_2char_8sval.html", null ],
    [ "comet.sval", "comet_8sval.html", null ],
    [ "frost_nova.sval", "frost__nova_8sval.html", null ],
    [ "frost_shard.sval", "frost__shard_8sval.html", null ],
    [ "ice_barrier.effect", "ice__barrier_8effect.html", null ],
    [ "ice_barrier.sval", "ice__barrier_8sval.html", null ],
    [ "ice_barrier_charge.effect", "ice__barrier__charge_8effect.html", null ],
    [ "nova.effect", "nova_8effect.html", null ],
    [ "nova_1.unit", "nova__1_8unit.html", null ],
    [ "nova_2.unit", "nova__2_8unit.html", null ],
    [ "nova_3.unit", "nova__3_8unit.html", null ],
    [ "nova_4.unit", "nova__4_8unit.html", null ],
    [ "orb_1.unit", "orb__1_8unit.html", null ],
    [ "orb_2.unit", "orb__2_8unit.html", null ],
    [ "orb_3.unit", "orb__3_8unit.html", null ],
    [ "orb_break.effect", "orb__break_8effect.html", null ],
    [ "orb_dust.effect", "orb__dust_8effect.html", null ],
    [ "orb_of_winter.sval", "orb__of__winter_8sval.html", null ],
    [ "orb_shard.effect", "orb__shard_8effect.html", null ],
    [ "orb_shard_1.unit", "orb__shard__1_8unit.html", null ],
    [ "orb_shard_2.unit", "orb__shard__2_8unit.html", null ],
    [ "orb_shard_3.unit", "orb__shard__3_8unit.html", null ],
    [ "shard.effect", "players_2sorcerer_2shard_8effect.html", null ],
    [ "shard_1.unit", "shard__1_8unit.html", null ],
    [ "shard_2.unit", "shard__2_8unit.html", null ],
    [ "shard_3.unit", "shard__3_8unit.html", null ],
    [ "shard_4.unit", "shard__4_8unit.html", null ],
    [ "shard_5.unit", "shard__5_8unit.html", null ],
    [ "shard_6.effect", "shard__6_8effect.html", null ],
    [ "shard_6.unit", "shard__6_8unit.html", null ],
    [ "shatter.effect", "shatter_8effect.html", null ],
    [ "shatter.sval", "shatter_8sval.html", null ],
    [ "shatter_small.effect", "shatter__small_8effect.html", null ]
];