var dir_4727f766ece07279544a015520e2aafa =
[
    [ "bomb.unit", "items_2projectiles_2bomb_8unit.html", null ],
    [ "delta_dukes_signet_ring.effect", "delta__dukes__signet__ring_8effect.html", null ],
    [ "dukes_signet_ring.effect", "dukes__signet__ring_8effect.html", null ],
    [ "dukes_signet_ring.unit", "dukes__signet__ring_8unit.html", null ],
    [ "dukes_signet_ring_particles.effect", "dukes__signet__ring__particles_8effect.html", null ],
    [ "earthsplitter.unit", "earthsplitter_8unit.html", null ],
    [ "fire_area.effect", "items_2projectiles_2fire__area_8effect.html", null ],
    [ "fire_area.unit", "items_2projectiles_2fire__area_8unit.html", null ],
    [ "magic_missile.effect", "magic__missile_8effect.html", null ],
    [ "magic_missile.unit", "magic__missile_8unit.html", null ],
    [ "magic_missile_big.unit", "magic__missile__big_8unit.html", null ],
    [ "magic_missile_hit.effect", "magic__missile__hit_8effect.html", null ],
    [ "meteor.effect", "meteor_8effect.html", null ],
    [ "meteor.unit", "meteor_8unit.html", null ],
    [ "meteor_hit.effect", "items_2projectiles_2meteor__hit_8effect.html", null ],
    [ "poison_dart.unit", "poison__dart_8unit.html", null ],
    [ "projectile_magic_missile_big.effect", "projectile__magic__missile__big_8effect.html", null ],
    [ "projectile_magic_missile_fade.effect", "projectile__magic__missile__fade_8effect.html", null ],
    [ "sphere_of_heroes.unit", "sphere__of__heroes_8unit.html", null ],
    [ "sphere_of_heroes_attack.effect", "sphere__of__heroes__attack_8effect.html", null ],
    [ "sphere_of_heroes_trail.effect", "sphere__of__heroes__trail_8effect.html", null ],
    [ "stormcaller.unit", "stormcaller_8unit.html", null ]
];