HoHDocs: CharacterColors Namespace Reference
CharacterColors Namespace Reference
Classes
class ClassColors
Functions
array< vec4 > ParseColorList (SValue@ arr)
void LoadColors ()
ClassColors GetClass (string id)
Variables
class CharacterColors::ClassColors g_classes
Function Documentation
GetClass()
ClassColors CharacterColors::GetClass (string id)
Definition at line 77 of file CharacterColors.as.
References g_classes, and m_id.
     {
         for (uint i = 0; i < g_classes.length(); i++)
         {
             if (g_classes[i].m_id == id)
                 return g_classes[i];
         }
         return null;
     }
LoadColors()
void CharacterColors::LoadColors ()
Definition at line 51 of file CharacterColors.as.
References g_classes, and ParseColorList().
Referenced by BaseGameMode::BaseGameMode().
     {
         if (g_classes.length() > 0)
             return;
         auto sval = Resources::GetSValue("tweak/classcolors.sval");
         auto arrSkinColor = sval.GetDictionaryEntry("colors-skin").GetArray();
         dictionary dic = sval.GetDictionary();
         array<string> keys = dic.getKeys();
         string classPrefix = "class-";
         for (uint i = 0; i < keys.length(); i++)
         {
             if (keys[i].substr(0, classPrefix.length()) != classPrefix)
                 continue;
             SValue@ svClass = sval.GetDictionaryEntry(keys[i]);
             string classId = keys[i].substr(classPrefix.length());
             auto colorsClass = ClassColors(classId, svClass);
             for (uint j = 0; j < arrSkinColor.length(); j++)
                 colorsClass.m_skin.insertLast(ParseColorList(arrSkinColor[j]));
             g_classes.insertLast(colorsClass);
         }
     }
ParseColorList()
array<vec4> CharacterColors::ParseColorList (SValue@ arr)
Definition at line 3 of file CharacterColors.as.
Referenced by CharacterColors::ClassColors::ClassColors(), and LoadColors().
     {
         array<SValue@>@ colors = arr.GetArray();
         array<vec4> ret;
         for (uint i = 0; i < 3; i++)
             ret.insertLast(ParseColorRGBA(colors[i].GetString()));
         return ret;
     }
Variable Documentation
g_classes
class CharacterColors::ClassColors CharacterColors::g_classes
Referenced by GetClass(), and LoadColors().