HoHDocs: Fountain Namespace Reference
Fountain Namespace Reference
Classes
class Effect
Functions
void ClearEffects ()
void RefreshModifiers (Modifiers::ModifierList@ list)
bool HasEffect (const string &in effect)
bool HasEffect (uint effect)
void ApplyEffect (const string &in effect)
void ApplyEffect (uint effect)
Effect GetEffect (const string &in effect)
Effect GetEffect (uint effect)
void Clear ()
void AddWishFile (const string &in filename)
void AddWishFiles ()
Variables
class Fountain::Effect CurrentEffects
array< Effect@> AvailableEffects
Modifiers::ModifierList Modifiers
Function Documentation
AddWishFile()
void Fountain::AddWishFile (const string &in filename)
Definition at line 106 of file FountainEffect.as.
References AvailableEffects, Effect, Modifiers::LoadModifiers(), Fountain::Effect::m_favor, Fountain::Effect::m_flag, Fountain::Effect::m_id, Fountain::Effect::m_idHash, Fountain::Effect::m_level, Fountain::Effect::m_modifiers, and Modifiers::Wish.
Referenced by AddWishFiles().
     {
         auto sval = Resources::GetSValue(filename);
         auto arr = sval.GetArray();
         for (uint i = 0; i < arr.length(); i++)
         {
             auto svEffect = arr[i];
             Effect@ newEffect = Effect();
             newEffect.m_id = GetParamString(UnitPtr(), svEffect, "id");
             newEffect.m_idHash = HashString(newEffect.m_id);
             newEffect.m_level = GetParamInt(UnitPtr(), svEffect, "level");
             newEffect.m_favor = GetParamInt(UnitPtr(), svEffect, "favor");
             newEffect.m_flag = GetParamString(UnitPtr(), svEffect, "flag", false);
             newEffect.m_modifiers = Modifiers::LoadModifiers(UnitPtr(), svEffect, "", Modifiers::SyncVerb::Wish, newEffect.m_idHash);
             AvailableEffects.insertLast(newEffect);
         }
     }
AddWishFiles()
void Fountain::AddWishFiles ()
Definition at line 125 of file FountainEffect.as.
References AddWishFile(), and Clear().
Referenced by Campaign::Campaign().
     {
         @Modifiers = Modifiers::ModifierList();
         Modifiers.m_name = Resources::GetString(".modifier.list.fountain");
         Clear();
         AddWishFile("tweak/wishes/good.sval");
         AddWishFile("tweak/wishes/bad.sval");
     }
ApplyEffect() [1/2]
void Fountain::ApplyEffect (const string &in effect)
Definition at line 75 of file FountainEffect.as.
References effect.
Referenced by FountainShopMenuContent::Buy(), RandomLevel::Generate(), GameModeHandler::SetFountain(), and Campaign::Start().
     {
         ApplyEffect(HashString(effect));
     }
ApplyEffect() [2/2]
void Fountain::ApplyEffect (uint effect)
Definition at line 80 of file FountainEffect.as.
References CurrentEffects, effect, and HasEffect().
     {
         if (!HasEffect(effect))
             CurrentEffects.insertLast(effect);
     }
Clear()
void Fountain::Clear ()
Definition at line 101 of file FountainEffect.as.
References AvailableEffects.
Referenced by AddWishFiles().
     {
         AvailableEffects.removeRange(0, AvailableEffects.length());
     }
ClearEffects()
void Fountain::ClearEffects ()
Definition at line 18 of file FountainEffect.as.
References CurrentEffects.
Referenced by Campaign::OnRunEnd(), and GameModeHandler::SetFountain().
     {
         CurrentEffects.removeRange(0, CurrentEffects.length());
     }
GetEffect() [1/2]
Effect Fountain::GetEffect (const string &in effect)
Definition at line 86 of file FountainEffect.as.
References effect.
Referenced by ActorBuffDef(), UnitHandler::AttachEffect(), BlinkSkill::BlinkSkill(), BoltShooter::BoltShooter(), UnitHandler::BoltShooter(), BossVampireMovement::BossVampireMovement(), Breakable::Breakable(), Skills::BuffAoe::BuffAoe(), Skills::CelestialOrbs(), Skills::CooldownStackMeleeSwing(), SpawnTilesetEffect::Do(), Skills::DropEffect::DropEffect(), EffectSpawner::EffectSpawner(), Modifiers::FlameShield::FlameShield(), FountainShopMenuContent::GetSelectedEffects(), Skills::GrappleHook(), PlayerBase::InitSkin(), KillSameType::KillSameType(), LifestealDamage::LifestealDamage(), LoadEffectSets(), Skills::ManaShield(), Skills::MeleeSwing::MeleeSwing(), PlayerHandler::ModifierTriggerEffect(), PingBehavior::PingBehavior(), PlayEffect(), UnitHandler::PlayEffect(), Player::Player(), PlayerBase::PlayerBase(), RefreshModifiers(), SetLevelFlags(), ShootBolt::ShootBolt(), SimpleBreakable::SimpleBreakable(), SpawnEffect::SpawnEffect(), SpawnTilesetEffect::SpawnTilesetEffect(), Skills::StackSkill::StackSkill(), and Skills::TempBuffAoe::TempBuffAoe().
     {
         return GetEffect(HashString(effect));
     }
GetEffect() [2/2]
Effect Fountain::GetEffect (uint effect)
Definition at line 91 of file FountainEffect.as.
References AvailableEffects, effect, and Materials::m_idHash.
     {
         for (uint i = 0; i < AvailableEffects.length(); i++)
         {
             if (AvailableEffects[i].m_idHash == effect)
                 return AvailableEffects[i];
         }
         return null;
     }
HasEffect() [1/2]
bool Fountain::HasEffect (const string &in effect)
Definition at line 65 of file FountainEffect.as.
References effect.
Referenced by ApplyEffect(), ApplyTaxRate(), Player::Damage(), EnemyPlacement::EnemyPlacement(), EnemySetting(), GiveMana::GetAmount(), Heal::GetAmount(), WorldScript::Well::HasInfiniteUses(), MeleeMovement::Initialize(), MakeDungeonGenerator(), Upgrades::DungeonShop::NewItems(), Pickup::Pickup(), RandomLevel::PostStart(), Titles::ClassTitles::RefreshModifiers(), FountainShopMenuContent::ReloadList(), EnemyPlacement::SpawnGroup(), and TriggerOnDeath().
     {
         return HasEffect(HashString(effect));
     }
HasEffect() [2/2]
bool Fountain::HasEffect (uint effect)
Definition at line 70 of file FountainEffect.as.
References CurrentEffects, and effect.
     {
         return CurrentEffects.find(effect) != -1;
     }
RefreshModifiers()
void Fountain::RefreshModifiers (Modifiers::ModifierList@ list)
Definition at line 23 of file FountainEffect.as.
References CurrentEffects, effect, and GetEffect().
Referenced by FountainShopMenuContent::Buy(), and Campaign::Start().
     {
         if (Modifiers is null)
             return;
         list.Remove(Modifiers);
         list.Add(Modifiers);
         Modifiers.Clear();
         int favor = 0;
         for (uint i = 0; i < CurrentEffects.length(); i++)
         {
             auto effect = GetEffect(CurrentEffects[i]);
             if (effect is null)
             {
                 PrintError("Couldn't find effect with ID " + CurrentEffects[i] + " for modifiers");
                 continue;
             }
             favor += effect.m_favor;
             for (uint j = 0; j < effect.m_modifiers.length(); j++)
                 Modifiers.Add(effect.m_modifiers[j]);
         }
         if (favor < 0)
         {
             SValueBuilder builderGold;
             builderGold.PushDictionary();
             builderGold.PushFloat("scale", 1.0f + 0.05f * -favor);
             builderGold.PopDictionary();
             Modifiers.Add(Modifiers::GoldGain(UnitPtr(), builderGold.Build()));
             SValueBuilder builderExp;
             builderExp.PushDictionary();
             builderExp.PushFloat("mul", 1.0f + 0.05f * -favor);
             builderExp.PopDictionary();
             Modifiers.Add(Modifiers::Experience(UnitPtr(), builderExp.Build()));
         }
     }
Variable Documentation
AvailableEffects
array<Effect@> Fountain::AvailableEffects
Definition at line 14 of file FountainEffect.as.
Referenced by AddWishFile(), Clear(), GetEffect(), and FountainShopMenuContent::ReloadList().
CurrentEffects
class Fountain::Effect Fountain::CurrentEffects
Referenced by ApplyEffect(), FountainShopMenuContent::Buy(), ClearEffects(), FountainShopMenuContent::GetSelectedEffects(), HasEffect(), RefreshModifiers(), FountainShopMenuContent::ReloadList(), Campaign::Save(), TownRecord::Save(), SetLevelFlags(), and FountainShopMenuContent::UpdateInterface().
Modifiers
Modifiers::ModifierList Fountain::Modifiers
Definition at line 16 of file FountainEffect.as.