var namespaces_dup =
[
    [ "CharacterColors", "namespace_character_colors.html", null ],
    [ "Crowd", "namespace_crowd.html", null ],
    [ "CVars", "namespace_c_vars.html", null ],
    [ "DebugHandler", "namespace_debug_handler.html", null ],
    [ "Discord", "namespace_discord.html", null ],
    [ "DiscordPresence", "namespace_discord_presence.html", null ],
    [ "EnvironmentSoundSystem", "namespace_environment_sound_system.html", null ],
    [ "Fountain", "namespace_fountain.html", null ],
    [ "GameModeHandler", "namespace_game_mode_handler.html", null ],
    [ "HwrSaves", "namespace_hwr_saves.html", null ],
    [ "LootDef", "namespace_loot_def.html", null ],
    [ "Materials", "namespace_materials.html", null ],
    [ "Menu", "namespace_menu.html", null ],
    [ "Modifiers", "namespace_modifiers.html", null ],
    [ "MusicManager", "namespace_music_manager.html", null ],
    [ "Platform", "namespace_platform.html", null ],
    [ "PlayerHandler", "namespace_player_handler.html", null ],
    [ "QueuedTasks", "namespace_queued_tasks.html", null ],
    [ "RandomLootManager", "namespace_random_loot_manager.html", null ],
    [ "Saves", "namespace_saves.html", null ],
    [ "ServicePresence", "namespace_service_presence.html", null ],
    [ "Skills", "namespace_skills.html", null ],
    [ "SpawnUnitBaseHandler", "namespace_spawn_unit_base_handler.html", null ],
    [ "Stats", "namespace_stats.html", null ],
    [ "Statues", "namespace_statues.html", null ],
    [ "Titles", "namespace_titles.html", null ],
    [ "Tutorial", "namespace_tutorial.html", null ],
    [ "Tweak", "namespace_tweak.html", null ],
    [ "UnitHandler", "namespace_unit_handler.html", null ],
    [ "Upgrades", "namespace_upgrades.html", null ],
    [ "WorldScript", "namespace_world_script.html", null ]
];