HoHDocs: SpawnUnitBaseHandler Namespace Reference
SpawnUnitBaseHandler Namespace Reference
Functions
int PackEnemyCfg (bool AggroEnemy, bool NoLootEnemy, bool NoExperienceEnemy)
void ConfigureEnemy (CompositeActorBehavior@ enemy, int cfgEnemy)
void NetSpawnUnitBaseImpl (uint prodHash, int unitId, vec2 pos, string scene, int layer, int cfgEnemy, UnitPtr owner, float intensity)
void DoSpawnUnitBase (int delay, uint prodHash, vec2 pos, string scene, int layer, int cfgEnemy, int ownerId, float intensity)
void SpawnedOwnedUnitEnemy (uint prodHash, int unitId, vec2 pos, string scene, int layer, int cfgEnemy, UnitPtr owner, float intensity)
void SpawnedOwnedUnit (uint prodHash, int unitId, vec2 pos, string scene, int layer, UnitPtr owner, float intensity)
void SpawnedUnitEnemy (uint prodHash, int unitId, vec2 pos, string scene, int layer, int cfgEnemy)
void SpawnedUnit (uint prodHash, int unitId, vec2 pos, string scene, int layer)
void SpawnedUnitSimple (uint prodHash, int unitId, vec2 pos)
Function Documentation
ConfigureEnemy()
void SpawnUnitBaseHandler::ConfigureEnemy (CompositeActorBehavior@ enemy, int cfgEnemy)
Definition at line 122 of file SpawnUnitBase.as.
Referenced by SpawnUnitBaseImpl().
     {
         enemy.Configure((cfgEnemy & 1) != 0, (cfgEnemy & 2) != 0, (cfgEnemy & 4) != 0);
     }
DoSpawnUnitBase()
void SpawnUnitBaseHandler::DoSpawnUnitBase (int delay, uint prodHash, vec2 pos, string scene, int layer, int cfgEnemy, int ownerId, float intensity)
Definition at line 153 of file SpawnUnitBase.as.
References g_scene, QueuedTasks::Queue(), and SpawnUnitBaseImpl().
     {
         UnitProducer@ prod = Resources::GetUnitProducer(prodHash);
         if (prod is null)
             return;
         if (delay > 0)
             QueuedTasks::Queue(delay, SpawnUnitBaseTask(prod, pos, scene, layer, cfgEnemy, g_scene.GetUnit(ownerId), intensity));
         else
             SpawnUnitBaseImpl(prod, pos, scene, layer, cfgEnemy, g_scene.GetUnit(ownerId), intensity);
     }
NetSpawnUnitBaseImpl()
void SpawnUnitBaseHandler::NetSpawnUnitBaseImpl (uint prodHash, int unitId, vec2 pos, string scene, int layer, int cfgEnemy, UnitPtr owner, float intensity)
Definition at line 127 of file SpawnUnitBase.as.
Referenced by SpawnedOwnedUnit(), SpawnedOwnedUnitEnemy(), SpawnedUnit(), SpawnedUnitEnemy(), and SpawnedUnitSimple().
     {
         UnitProducer@ UnitType = Resources::GetUnitProducer(prodHash);
         if (UnitType is null)
             return;
         UnitPtr u;
         if (IsNetsyncedExistance(UnitType.GetNetSyncMode()))
             u = g_scene.GetUnit(unitId);
         else
             u = UnitType.Produce(g_scene, xyz(pos));
         auto enemyBehavior = cast<CompositeActorBehavior>(u.GetScriptBehavior());
         if (enemyBehavior !is null)
             ConfigureEnemy(enemyBehavior, cfgEnemy);
         if (scene != "")
             u.SetUnitScene(scene, true);
         if (layer != 0)
             u.SetLayer(layer);
         auto ownedUnit = cast<IOwnedUnit>(u.GetScriptBehavior());
         if (owner.IsValid() && ownedUnit !is null)
             ownedUnit.Initialize(cast<Actor>(owner.GetScriptBehavior()), intensity, true);
     }
PackEnemyCfg()
int SpawnUnitBaseHandler::PackEnemyCfg (bool AggroEnemy, bool NoLootEnemy, bool NoExperienceEnemy)
Definition at line 117 of file SpawnUnitBase.as.
References AggroEnemy, NoExperienceEnemy, and NoLootEnemy.
Referenced by SpawnUnitBase::SpawnUnit().
     {
         return (AggroEnemy ? 1 : 0) | (NoLootEnemy ? 2 : 0) | (NoExperienceEnemy ? 4 : 0);
     }
SpawnedOwnedUnit()
void SpawnUnitBaseHandler::SpawnedOwnedUnit (uint prodHash, int unitId, vec2 pos, string scene, int layer, UnitPtr owner, float intensity)
Definition at line 170 of file SpawnUnitBase.as.
References NetSpawnUnitBaseImpl().
     {
         NetSpawnUnitBaseImpl(prodHash, unitId, pos, scene, layer, 0, owner, intensity);
     }
SpawnedOwnedUnitEnemy()
void SpawnUnitBaseHandler::SpawnedOwnedUnitEnemy (uint prodHash, int unitId, vec2 pos, string scene, int layer, int cfgEnemy, UnitPtr owner, float intensity)
Definition at line 165 of file SpawnUnitBase.as.
References NetSpawnUnitBaseImpl().
     {
         NetSpawnUnitBaseImpl(prodHash, unitId, pos, scene, layer, cfgEnemy, owner, intensity);
     }
SpawnedUnit()
void SpawnUnitBaseHandler::SpawnedUnit (uint prodHash, int unitId, vec2 pos, string scene, int layer)
Definition at line 180 of file SpawnUnitBase.as.
References NetSpawnUnitBaseImpl().
     {
         NetSpawnUnitBaseImpl(prodHash, unitId, pos, scene, layer, 0, UnitPtr(), 1.0f);
     }
SpawnedUnitEnemy()
void SpawnUnitBaseHandler::SpawnedUnitEnemy (uint prodHash, int unitId, vec2 pos, string scene, int layer, int cfgEnemy)
Definition at line 175 of file SpawnUnitBase.as.
References NetSpawnUnitBaseImpl().
     {
         NetSpawnUnitBaseImpl(prodHash, unitId, pos, scene, layer, cfgEnemy, UnitPtr(), 1.0f);
     }
SpawnedUnitSimple()
void SpawnUnitBaseHandler::SpawnedUnitSimple (uint prodHash, int unitId, vec2 pos)
Definition at line 185 of file SpawnUnitBase.as.
References NetSpawnUnitBaseImpl().
     {
         NetSpawnUnitBaseImpl(prodHash, unitId, pos, "", 0, 0, UnitPtr(), 1.0f);
     }