HoHDocs: UnitHandler Namespace Reference
UnitHandler Namespace Reference
Functions
void NetSendUnitDamaged (UnitPtr unit, int dmg, vec2 pos, vec2 dir, Actor@ attacker)
void NetSendUnitUseSkill (UnitPtr unit, int skillId, int stage=0, SValue@ param=null)
Actor GetActor (int unitId)
Actor GetActor (UnitPtr unit)
IDamageTaker GetDamageTaker (UnitPtr unit)
Pickup GetPickup (UnitPtr unit)
void UnitTeleported (UnitPtr unit, vec2 pos)
void UnitDestroyed (UnitPtr unit)
void UnitHealed (UnitPtr unit, int amount)
void UnitKilled (UnitPtr unit, UnitPtr attacker, int dmg, vec2 dir, uint weapon)
void UnitTarget (UnitPtr unit, UnitPtr target)
void UnitUseSSkillParam (UnitPtr unit, int skillId, int stage, vec2 pos, SValue@ param)
void UnitUseSSkill (UnitPtr unit, int skillId, int stage, vec2 pos)
void UnitUseSkillParam (UnitPtr unit, int skillId, vec2 pos, SValue@ param)
void UnitUseSkill (UnitPtr unit, int skillId, vec2 pos)
void SpawnUnit (int unitId, uint producerHash, vec2 pos)
void UnitDamaged (UnitPtr unit, int damage, vec2 pos, vec2 dir)
void UnitDecimated (UnitPtr unit, int health, int mana)
void UnitDamagedBySelf (uint8 peer, UnitPtr unit, int damage, vec2 pos, vec2 dir)
void UnitDelayedBreakable (UnitPtr unit)
void UnitBuffed (UnitPtr unit, UnitPtr ownerUnit, uint buffHash, float intensity, uint weapon, int duration)
void UnitPicked (UnitPtr unit, UnitPtr picker)
void UnitPickSecure (UnitPtr unit, UnitPtr picker)
void UnitPickCallback (UnitPtr unit, UnitPtr picker)
void UnitMovementChargeBegin (UnitPtr unit, vec2 pos, float dir)
void UnitMovementChargeLook (UnitPtr unit, vec2 pos)
void UnitMovementBossLichTarget (UnitPtr unit, UnitPtr targetUnit)
void UnitMovementBossVampireTarget (UnitPtr unit, UnitPtr targetUnit, int nodeWaitTime)
void UnitEyeBossWispsAdded (UnitPtr unit, SValue@ params)
void UnitEyeBossWispsSync (UnitPtr unit, SValue@ params)
void VampireBossRoaming (UnitPtr unit)
void VampireNodeArrived (UnitPtr unit)
void UnitBombExploded (UnitPtr unit, SValue@ param)
void SpawnLoot (SValue@ param)
void SetOwnedUnit (UnitPtr ownedUnit, UnitPtr ownerUnit, float intensity)
void PlayEffect (uint eHash, vec2 pos)
void AttachEffect (uint eHash, UnitPtr unit)
void BoltShooter (SValue@ params)
Function Documentation
AttachEffect()
void UnitHandler::AttachEffect (uint eHash, UnitPtr unit)
Definition at line 520 of file UnitHandler.as.
References Fountain::GetEffect(), PlayEffect(), and unit.
     {
         ::PlayEffect(Resources::GetEffect(eHash), unit);
     }
BoltShooter()
void UnitHandler::BoltShooter (SValue@ params)
Definition at line 525 of file UnitHandler.as.
References DrawLightningBolt(), and Fountain::GetEffect().
     {
         auto fx = Resources::GetEffect("effects/players/lightning_bolt.effect");
         if (fx is null)
         {
             PrintError("Lightning bolt effect does not exist!");
             return;
         }
         auto arr = params.GetArray();
         for (uint i = 0; i < arr.length(); i++)
         {
             auto arr2 = arr[i].GetArray();
             vec2 startPos = arr2[0].GetVector2();
             vec2 endPos = arr2[1].GetVector2();
             DrawLightningBolt(fx, startPos, endPos);
         }
     }
GetActor() [1/2]
Actor UnitHandler::GetActor (int unitId)
Definition at line 33 of file UnitHandler.as.
References g_scene, and unit.
Referenced by PlayerHandler::PlayerDamaged(), SetOwnedUnit(), UnitBuffed(), UnitHealed(), UnitKilled(), UnitMovementChargeBegin(), UnitMovementChargeLook(), UnitTarget(), and UnitUseSSkillParam().
     {
         if (unitId <= 0)
             return null;
         UnitPtr unit = g_scene.GetUnit(unitId);
         if (!unit.IsValid())
         {
             PrintError("Couldn't find unit " + unitId);
             return null;
         }
         if (unit.IsDestroyed())
             return null;
         ref@ behavior = unit.GetScriptBehavior();
         if (behavior is null)
         {
             PrintError("Unit " + unitId + " (" + unit.GetDebugName() + ") has no behavior");
             return null;
         }
         Actor@ actor = cast<Actor>(behavior);
         if (actor is null)
         {
             PrintError("Unit " + unitId + " (" + unit.GetDebugName() + ") is not an actor");
             return null;
         }
         return actor;
     }
GetActor() [2/2]
Actor UnitHandler::GetActor (UnitPtr unit)
Definition at line 66 of file UnitHandler.as.
References unit.
     {
         if (unit.IsDestroyed())
             return null;
         ref@ behavior = unit.GetScriptBehavior();
         if (behavior is null)
         {
             PrintError("Unit " + unit.GetId() + " (" + unit.GetDebugName() + ") has no behavior");
             return null;
         }
         Actor@ actor = cast<Actor>(behavior);
         if (actor is null)
         {
             PrintError("Unit " + unit.GetId() + " (" + unit.GetDebugName() + ") is not an actor");
             return null;
         }
         return actor;
     }
GetDamageTaker()
IDamageTaker UnitHandler::GetDamageTaker (UnitPtr unit)
Definition at line 88 of file UnitHandler.as.
References unit.
Referenced by UnitDamaged(), UnitDamagedBySelf(), and UnitDecimated().
     {
         if (unit.IsDestroyed())
             return null;
         ref@ behavior = unit.GetScriptBehavior();
         if (behavior is null)
         {
             PrintError("Unit " + unit.GetId() + " (" + unit.GetDebugName() + ") has no behavior");
             return null;
         }
         auto dmgTaker = cast<IDamageTaker>(behavior);
         if (dmgTaker is null)
         {
             PrintError("Unit " + unit.GetId() + " (" + unit.GetDebugName() + ") is not an IDamageTaker");
             return null;
         }
         return dmgTaker;
     }
GetPickup()
Pickup UnitHandler::GetPickup (UnitPtr unit)
Definition at line 111 of file UnitHandler.as.
References unit.
Referenced by UnitPickCallback(), UnitPicked(), and UnitPickSecure().
     {
         if (unit.IsDestroyed())
             return null;
         ref@ behavior = unit.GetScriptBehavior();
         if (behavior is null)
         {
             PrintError("Unit " + unit.GetId() + " (" + unit.GetDebugName() + ") has no behavior");
             return null;
         }
         Pickup@ pickup = cast<Pickup>(behavior);
         if (pickup is null)
         {
             PrintError("Unit " + unit.GetId() + " (" + unit.GetDebugName() + ") is not a pickup");
             return null;
         }
         return pickup;
     }
NetSendUnitDamaged()
void UnitHandler::NetSendUnitDamaged (UnitPtr unit, int dmg, vec2 pos, vec2 dir, Actor@ attacker)
Definition at line 3 of file UnitHandler.as.
References unit.
Referenced by Breakable::Collide(), DelayedBreakable::Damage(), Damage(), Breakable::Damage(), and Breakable::Update().
     {
         if (!unit.IsValid())
             return;
         auto localPlayer = cast<Player>(attacker);
         if (localPlayer is null)
             (Network::Message("UnitDamaged") << unit << dmg << pos << dir).SendToAll();
         else
             (Network::Message("UnitDamagedBySelf") << unit << dmg << pos << dir).SendToAll();
     }
NetSendUnitUseSkill()
void UnitHandler::NetSendUnitUseSkill (UnitPtr unit, int skillId, int stage = 0, SValue@ param = null)
Definition at line 15 of file UnitHandler.as.
References unit, and xy().
Referenced by CastTrigger(), CompositeActorSkill::HandleCastpoint(), BossScatterBurstSkill::NewBurstShot(), Trigger(), CompositeActorBurstSkill::Update(), NovaSkill::Update(), WhirlNovaSkill::Update(), EnemyMeleeStrike::Update(), WhirlwindSkill::Update(), SpewSkill::Update(), and CompositeActorSkill::Update().
     {
         if (stage == 0)
         {
             if (param !is null)
                 (Network::Message("UnitUseSkillParam") << unit << skillId << xy(unit.GetPosition()) << param).SendToAll();
             else
                 (Network::Message("UnitUseSkill") << unit << skillId << xy(unit.GetPosition())).SendToAll();
         }
         else
         {
             if (param !is null)
                 (Network::Message("UnitUseSSkillParam") << unit << skillId << stage << xy(unit.GetPosition()) << param).SendToAll();
             else
                 (Network::Message("UnitUseSSkill") << unit << skillId << stage << xy(unit.GetPosition())).SendToAll();
         }
     }
PlayEffect()
void UnitHandler::PlayEffect (uint eHash, vec2 pos)
Definition at line 515 of file UnitHandler.as.
References Fountain::GetEffect().
Referenced by AttachEffect().
     {
         ::PlayEffect(Resources::GetEffect(eHash), pos);
     }
SetOwnedUnit()
void UnitHandler::SetOwnedUnit (UnitPtr ownedUnit, UnitPtr ownerUnit, float intensity)
Definition at line 499 of file UnitHandler.as.
References GetActor().
     {
         Actor@ owner = GetActor(ownerUnit);
         if (owner is null)
             return;
         auto owned = cast<IOwnedUnit>(ownedUnit.GetScriptBehavior());
         if (owned is null)
         {
             PrintError("Unit " + ownedUnit.GetId() + " (" + ownedUnit.GetDebugName() + ") is not of type IOwnedUnit");
             return;
         }
         owned.Initialize(owner, intensity, true);
     }
SpawnLoot()
void UnitHandler::SpawnLoot (SValue@ param)
Definition at line 494 of file UnitHandler.as.
References LootDef::NetSpawnLoot().
     {
         LootDef::NetSpawnLoot(param);
     }
SpawnUnit()
void UnitHandler::SpawnUnit (int unitId, uint producerHash, vec2 pos)
Definition at line 217 of file UnitHandler.as.
References g_scene, and xyz().
     {
         UnitProducer@ prod = Resources::GetUnitProducer(producerHash);
         if (prod is null)
         {
             PrintError("Unknown unit producer '" + producerHash + "'");
             return;
         }
         prod.Produce(g_scene, xyz(pos), unitId);
     }
UnitBombExploded()
void UnitHandler::UnitBombExploded (UnitPtr unit, SValue@ param)
Definition at line 482 of file UnitHandler.as.
References unit.
     {
         auto bomb = cast<BombBehavior>(unit.GetScriptBehavior());
         if (bomb is null)
         {
             PrintError("Unit " + unit.GetId() + " (" + unit.GetDebugName() + ") is not of type BombBehavior");
             return;
         }
         bomb.NetDoExplode(param);
     }
UnitBuffed()
void UnitHandler::UnitBuffed (UnitPtr unit, UnitPtr ownerUnit, uint buffHash, float intensity, uint weapon, int duration)
Definition at line 281 of file UnitHandler.as.
References Actor::ApplyBuff(), GetActor(), LoadActorBuff(), and unit.
     {
         Actor@ actor = GetActor(unit);
         if (actor is null)
             return;
         Actor@ owner = null;
         if (ownerUnit.IsValid())
             @owner = GetActor(ownerUnit);
         auto aBuffDef = LoadActorBuff(buffHash);
         if (aBuffDef is null)
             return;
         auto newBuff = ActorBuff(owner, aBuffDef, intensity, true, weapon);
         newBuff.m_duration = duration;
         actor.ApplyBuff(newBuff);
     }
UnitDamaged()
void UnitHandler::UnitDamaged (UnitPtr unit, int damage, vec2 pos, vec2 dir)
Definition at line 230 of file UnitHandler.as.
References DamageInfo::Damage, GetDamageTaker(), and unit.
     {
         auto b = GetDamageTaker(unit);
         if (b is null)
             return;
         if (damage == 0)
             PrintError("Damage to unit " + unit.GetId() + " is 0 damage?");
         DamageInfo di;
         di.Damage = damage;
         b.NetDamage(di, pos, dir);
     }
UnitDamagedBySelf()
void UnitHandler::UnitDamagedBySelf (uint8 peer, UnitPtr unit, int damage, vec2 pos, vec2 dir)
Definition at line 253 of file UnitHandler.as.
References DamageInfo::Attacker, GetDamageTaker(), PlayerHandler::GetPlayer(), and unit.
     {
         auto b = GetDamageTaker(unit);
         if (b is null)
             return;
         if (damage == 0)
             PrintError("Damage to unit " + unit.GetId() + " is 0 damage?");
         DamageInfo di;
         @di.Attacker = PlayerHandler::GetPlayer(peer);
         di.Damage = damage;
         b.NetDamage(di, pos, dir);
     }
UnitDecimated()
void UnitHandler::UnitDecimated (UnitPtr unit, int health, int mana)
Definition at line 244 of file UnitHandler.as.
References GetDamageTaker(), and unit.
     {
         auto b = GetDamageTaker(unit);
         if (b is null)
             return;
         b.NetDecimate(health, mana);
     }
UnitDelayedBreakable()
void UnitHandler::UnitDelayedBreakable (UnitPtr unit)
Definition at line 268 of file UnitHandler.as.
References DelayedBreakable::DamageEffects(), and unit.
     {
         DelayedBreakable@ breakable = cast<DelayedBreakable>(unit.GetScriptBehavior());
         if (breakable is null)
         {
             PrintError("Unit " + unit.GetId() + " (" + unit.GetDebugName() + ") is not of type DelayedBreakable");
             return;
         }
         breakable.DamageEffects();
     }
UnitDestroyed()
void UnitHandler::UnitDestroyed (UnitPtr unit)
Definition at line 138 of file UnitHandler.as.
References unit.
     {
         unit.Destroy();
     }
UnitEyeBossWispsAdded()
void UnitHandler::UnitEyeBossWispsAdded (UnitPtr unit, SValue@ params)
Definition at line 432 of file UnitHandler.as.
References unit.
     {
         auto boss = cast<BossEye>(unit.GetScriptBehavior());
         if (boss is null)
         {
             PrintError("Unit " + unit.GetId() + " (" + unit.GetDebugName() + ") is not of type BossEye");
             return;
         }
         boss.NetAddWisps(params);
     }
UnitEyeBossWispsSync()
void UnitHandler::UnitEyeBossWispsSync (UnitPtr unit, SValue@ params)
Definition at line 444 of file UnitHandler.as.
References unit.
     {
         auto boss = cast<BossEye>(unit.GetScriptBehavior());
         if (boss is null)
         {
             PrintError("Unit " + unit.GetId() + " (" + unit.GetDebugName() + ") is not of type BossEye");
             return;
         }
         boss.NetWispSync(params);
     }
UnitHealed()
void UnitHandler::UnitHealed (UnitPtr unit, int amount)
Definition at line 143 of file UnitHandler.as.
References GetActor(), Actor::NetHeal(), and unit.
     {
         Actor@ actor = GetActor(unit);
         if (actor is null)
             return;
         actor.NetHeal(amount);
     }
UnitKilled()
void UnitHandler::UnitKilled (UnitPtr unit, UnitPtr attacker, int dmg, vec2 dir, uint weapon)
Definition at line 152 of file UnitHandler.as.
References GetActor(), Actor::NetKill(), and unit.
     {
         Actor@ actor = GetActor(unit);
         if (actor is null)
             return;
         if (attacker.IsValid())
         {
             Actor@ actorAttacker = GetActor(attacker);
             actor.NetKill(actorAttacker, dmg, dir, weapon);
             PlayerHusk@ playerAttacker = cast<PlayerHusk>(actorAttacker);
             if (playerAttacker !is null)
             {
                 playerAttacker.m_record.kills++;
                 playerAttacker.m_record.killsTotal++;
             }
         }
         else
             actor.NetKill(null, dmg, dir, weapon);
     }
UnitMovementBossLichTarget()
void UnitHandler::UnitMovementBossLichTarget (UnitPtr unit, UnitPtr targetUnit)
Definition at line 380 of file UnitHandler.as.
References unit.
     {
         auto lich = cast<BossLich>(unit.GetScriptBehavior());
         if (lich is null)
         {
             PrintError("Unit " + unit.GetId() + " (" + unit.GetDebugName() + ") is not of type BossLich");
             return;
         }
         auto target = cast<WorldScript::BossLichNode>(targetUnit.GetScriptBehavior());
         if (target is null)
         {
             PrintError("Unit " + targetUnit.GetId() + " (" + targetUnit.GetDebugName() + ") is not of type BossLichNode");
             return;
         }
         auto movement = cast<BossLichMovement>(lich.m_movement);
         if (movement is null)
         {
             PrintError("Unit " + unit.GetId() + " (" + unit.GetDebugName() + ") does not have a movement of type BossLichMovement");
             return;
         }
         movement.SetTargetNode(target);
     }
UnitMovementBossVampireTarget()
void UnitHandler::UnitMovementBossVampireTarget (UnitPtr unit, UnitPtr targetUnit, int nodeWaitTime)
Definition at line 406 of file UnitHandler.as.
References unit.
     {
         auto vampire = cast<BossVampire>(unit.GetScriptBehavior());
         if (vampire is null)
         {
             PrintError("Unit " + unit.GetId() + " (" + unit.GetDebugName() + ") is not of type BossVampire");
             return;
         }
         auto target = cast<WorldScript::BossLichNode>(targetUnit.GetScriptBehavior());
         if (target is null)
         {
             PrintError("Unit " + targetUnit.GetId() + " (" + targetUnit.GetDebugName() + ") is not of type BossLichNode");
             return;
         }
         auto movement = cast<BossVampireMovement>(vampire.m_movement);
         if (movement is null)
         {
             PrintError("Unit " + unit.GetId() + " (" + unit.GetDebugName() + ") does not have a movement of type BossVampireMovement");
             return;
         }
         movement.SetTargetNode(target, nodeWaitTime);
     }
UnitMovementChargeBegin()
void UnitHandler::UnitMovementChargeBegin (UnitPtr unit, vec2 pos, float dir)
Definition at line 331 of file UnitHandler.as.
References GetActor(), Actor::m_unit, unit, and xyz().
     {
         Actor@ actor = GetActor(unit);
         if (actor is null)
             return;
         auto b = cast<CompositeActorBehavior>(actor);
         if (b is null)
         {
             PrintError("Unit " + unit.GetId() + " (" + unit.GetDebugName() + ") is not of type CompositeActorBehavior");
             return;
         }
         auto charge = cast<ChargeMovement>(b.m_movement);
         if (charge is null)
         {
             PrintError("Unit " + unit.GetId() + " (" + unit.GetDebugName() + ") does not have a movement of type ChargeMovement");
             return;
         }
         charge.m_dir = dir;
         charge.BeginCharging();
         actor.m_unit.SetPosition(xyz(pos), true);
     }
UnitMovementChargeLook()
void UnitHandler::UnitMovementChargeLook (UnitPtr unit, vec2 pos)
Definition at line 356 of file UnitHandler.as.
References GetActor(), Actor::m_unit, unit, and xyz().
     {
         Actor@ actor = GetActor(unit);
         if (actor is null)
             return;
         auto b = cast<CompositeActorBehavior>(actor);
         if (b is null)
         {
             PrintError("Unit " + unit.GetId() + " (" + unit.GetDebugName() + ") is not of type CompositeActorBehavior");
             return;
         }
         auto charge = cast<ChargeMovement>(b.m_movement);
         if (charge is null)
         {
             PrintError("Unit " + unit.GetId() + " (" + unit.GetDebugName() + ") does not have a movement of type ChargeMovement");
             return;
         }
         actor.m_unit.SetPosition(xyz(pos), true);
         charge.BeginLooking();
     }
UnitPickCallback()
void UnitHandler::UnitPickCallback (UnitPtr unit, UnitPtr picker)
Definition at line 322 of file UnitHandler.as.
References GetPickup(), and unit.
     {
         auto pickup = GetPickup(unit);
         if (pickup is null)
             return;
         pickup.CallbackPicked(picker);
     }
UnitPicked()
void UnitHandler::UnitPicked (UnitPtr unit, UnitPtr picker)
Definition at line 300 of file UnitHandler.as.
References GetPickup(), and unit.
Referenced by Pickup::CallbackPicked().
     {
         auto pickup = GetPickup(unit);
         if (pickup is null)
             return;
         pickup.NetPicked(picker);
     }
UnitPickSecure()
void UnitHandler::UnitPickSecure (UnitPtr unit, UnitPtr picker)
Definition at line 309 of file UnitHandler.as.
References GetPickup(), and unit.
     {
         if (!Network::IsServer())
             return;
         auto pickup = GetPickup(unit);
         if (pickup is null)
             return;
         if (pickup.NetPicked(picker))
             (Network::Message("UnitPicked") << unit << picker).SendToAll();
     }
UnitTarget()
void UnitHandler::UnitTarget (UnitPtr unit, UnitPtr target)
Definition at line 174 of file UnitHandler.as.
References GetActor(), Actor::NetSetTarget(), and unit.
     {
         Actor@ actor = GetActor(unit);
         if (actor is null)
             return;
         if (target.IsValid())
         {
             Actor@ t = GetActor(target);
             //print("Target set to: " + t.m_unit.GetDebugName() + " (" + unit.GetId() + " -> " + target.GetId() + ")");
             actor.NetSetTarget(t);
         }
         else
         {
             actor.NetSetTarget(null);
             //print("Target set to: null (" + unit.GetId() + " -> 0)");
         }
     }
UnitTeleported()
void UnitHandler::UnitTeleported (UnitPtr unit, vec2 pos)
Definition at line 133 of file UnitHandler.as.
References unit, and xyz().
     {
         unit.SetPosition(xyz(pos));
     }
UnitUseSkill()
void UnitHandler::UnitUseSkill (UnitPtr unit, int skillId, vec2 pos)
Definition at line 212 of file UnitHandler.as.
References unit, and UnitUseSSkillParam().
     {
         UnitUseSSkillParam(unit, skillId, 0, pos, null);
     }
UnitUseSkillParam()
void UnitHandler::UnitUseSkillParam (UnitPtr unit, int skillId, vec2 pos, SValue@ param)
Definition at line 207 of file UnitHandler.as.
References unit, and UnitUseSSkillParam().
     {
         UnitUseSSkillParam(unit, skillId, 0, pos, param);
     }
UnitUseSSkill()
void UnitHandler::UnitUseSSkill (UnitPtr unit, int skillId, int stage, vec2 pos)
Definition at line 202 of file UnitHandler.as.
References unit, and UnitUseSSkillParam().
     {
         UnitUseSSkillParam(unit, skillId, stage, pos, null);
     }
UnitUseSSkillParam()
void UnitHandler::UnitUseSSkillParam (UnitPtr unit, int skillId, int stage, vec2 pos, SValue@ param)
Definition at line 193 of file UnitHandler.as.
References GetActor(), Actor::NetUseSkill(), and unit.
Referenced by UnitUseSkill(), UnitUseSkillParam(), and UnitUseSSkill().
     {
         Actor@ actor = GetActor(unit);
         if (actor is null)
             return;
         actor.NetUseSkill(skillId, stage, pos, param);
     }
VampireBossRoaming()
void UnitHandler::VampireBossRoaming (UnitPtr unit)
Definition at line 456 of file UnitHandler.as.
References unit.
     {
         auto boss = cast<BossVampire>(unit.GetScriptBehavior());
         if (boss is null)
         {
             PrintError("Unit " + unit.GetId() + " (" + unit.GetDebugName() + ") is not of type BossVampire");
             return;
         }
         boss.m_roamingC = boss.m_roaming;
     }
VampireNodeArrived()
void UnitHandler::VampireNodeArrived (UnitPtr unit)
Definition at line 468 of file UnitHandler.as.
References unit.
     {
         auto boss = cast<BossVampire>(unit.GetScriptBehavior());
         if (boss is null)
         {
             PrintError("Unit " + unit.GetId() + " (" + unit.GetDebugName() + ") is not of type BossVampire");
             return;
         }
         auto movement = cast<BossVampireMovement>(boss.m_movement);
         if (movement !is null)
             movement.NetOnNodeArrived();
     }