HoHDocs: GameModeHandler Namespace Reference
GameModeHandler Namespace Reference
Functions
FountainShopMenuContent GetFountainMenu ()
void SetFountain (SValue@ data)
void DepositFountain (uint8 peer, int amount)
void SetNgp (int ngp)
void SetDownscaling (bool downscaling)
void GameOver ()
void ExtraLives (int lives)
void SyncFlag (string flag, bool value, bool persistent)
void SpawnDrinkBarrel (vec2 pos, int quality)
void SpawnItemBlueprint (vec2 pos, int quality)
void SpawnDyeBucket (vec2 pos, int quality)
Function Documentation
DepositFountain()
void GameModeHandler::DepositFountain (uint8 peer, int amount)
Definition at line 32 of file GameModeHandler.as.
References g_gameMode, GetFountainMenu(), and FountainShopMenuContent::NetDeposit().
     {
         auto gm = cast<Campaign>(g_gameMode);
         if (gm is null)
             return;
         gm.m_town.m_fountainGold += amount;
         if (Network::IsServer())
             gm.m_townLocal.m_fountainGold += amount;
         auto fountainMenu = GetFountainMenu();
         if (fountainMenu !is null)
             fountainMenu.NetDeposit(amount);
     }
ExtraLives()
void GameModeHandler::ExtraLives (int lives)
Definition at line 74 of file GameModeHandler.as.
References g_gameMode, GetHUD(), and HUD::SetExtraLife().
     {
         auto gm = cast<BaseGameMode>(g_gameMode);
         if (gm is null)
             return;
         if (lives > gm.m_extraLives)
             GetHUD().SetExtraLife();
         gm.m_extraLives = lives;
     }
GameOver()
void GameModeHandler::GameOver ()
Definition at line 64 of file GameModeHandler.as.
References GameOver::DoShow(), g_gameMode, and BaseGameMode::m_gameOver.
     {
         BaseGameMode@ gm = cast<BaseGameMode>(g_gameMode);
         if (gm is null)
             return;
         if (gm.m_gameOver !is null)
             gm.m_gameOver.DoShow();
     }
GetFountainMenu()
FountainShopMenuContent GameModeHandler::GetFountainMenu ()
Definition at line 3 of file GameModeHandler.as.
References g_gameMode.
Referenced by DepositFountain(), and SetFountain().
     {
         auto gm = cast<BaseGameMode>(g_gameMode);
         for (uint i = 0; i < gm.m_userWindows.length(); i++)
         {
             auto shopMenu = cast<ShopMenu>(gm.m_userWindows[i]);
             if (shopMenu is null)
                 continue;
             auto ret = cast<FountainShopMenuContent>(shopMenu.m_menuContent);
             if (ret !is null)
                 return ret;
         }
         return null;
     }
SetDownscaling()
void GameModeHandler::SetDownscaling (bool downscaling)
Definition at line 56 of file GameModeHandler.as.
References g_downscaling.
     {
         if (Network::IsServer())
             return;
         g_downscaling = downscaling;
     }
SetFountain()
void GameModeHandler::SetFountain (SValue@ data)
Definition at line 19 of file GameModeHandler.as.
References Fountain::ApplyEffect(), Fountain::ClearEffects(), and GetFountainMenu().
     {
         Fountain::ClearEffects();
         auto arr = data.GetArray();
         for (uint i = 0; i < arr.length(); i++)
             Fountain::ApplyEffect(uint(arr[i].GetInteger()));
         auto fountainMenu = GetFountainMenu();
         if (fountainMenu !is null)
             fountainMenu.NetBuy();
     }
SetNgp()
void GameModeHandler::SetNgp (int ngp)
Definition at line 48 of file GameModeHandler.as.
References g_ngp.
     {
         if (Network::IsServer())
             return;
         g_ngp = ngp;
     }
SpawnDrinkBarrel()
void GameModeHandler::SpawnDrinkBarrel (vec2 pos, int quality)
Definition at line 93 of file GameModeHandler.as.
References RandomLootManager::NetSpawnDrinkBarrel(), and quality.
     {
         RandomLootManager::NetSpawnDrinkBarrel(pos, ActorItemQuality(quality));
     }
SpawnDyeBucket()
void GameModeHandler::SpawnDyeBucket (vec2 pos, int quality)
Definition at line 103 of file GameModeHandler.as.
References RandomLootManager::NetSpawnDyeBucket(), and quality.
     {
         RandomLootManager::NetSpawnDyeBucket(pos, ActorItemQuality(quality));
     }
SpawnItemBlueprint()
void GameModeHandler::SpawnItemBlueprint (vec2 pos, int quality)
Definition at line 98 of file GameModeHandler.as.
References RandomLootManager::NetSpawnItemBlueprint(), and quality.
     {
         RandomLootManager::NetSpawnItemBlueprint(pos, ActorItemQuality(quality));
     }
SyncFlag()
void GameModeHandler::SyncFlag (string flag, bool value, bool persistent)
Definition at line 85 of file GameModeHandler.as.
References g_flags, Level, and Run.
     {
         if (!value)
             g_flags.Delete(flag);
         else
             g_flags.Set(flag, persistent ? FlagState::Run : FlagState::Level);
     }