var namespace_menu =
[
    [ "BackdropLayer", "class_menu_1_1_backdrop_layer.html", "class_menu_1_1_backdrop_layer" ],
    [ "CharacterCreationMenu", "class_menu_1_1_character_creation_menu.html", "class_menu_1_1_character_creation_menu" ],
    [ "CharacterCustomizationMenu", "class_menu_1_1_character_customization_menu.html", "class_menu_1_1_character_customization_menu" ],
    [ "CharacterSelectionMenu", "class_menu_1_1_character_selection_menu.html", "class_menu_1_1_character_selection_menu" ],
    [ "ControlMapMenu", "class_menu_1_1_control_map_menu.html", "class_menu_1_1_control_map_menu" ],
    [ "ControlsMenu", "class_menu_1_1_controls_menu.html", "class_menu_1_1_controls_menu" ],
    [ "CreditsMenu", "class_menu_1_1_credits_menu.html", "class_menu_1_1_credits_menu" ],
    [ "EditSlotMenu", "class_menu_1_1_edit_slot_menu.html", "class_menu_1_1_edit_slot_menu" ],
    [ "FrontMenu", "class_menu_1_1_front_menu.html", "class_menu_1_1_front_menu" ],
    [ "GameLanguagesMenu", "class_menu_1_1_game_languages_menu.html", "class_menu_1_1_game_languages_menu" ],
    [ "GameOptionsMenu", "class_menu_1_1_game_options_menu.html", "class_menu_1_1_game_options_menu" ],
    [ "GraphicsMenu", "class_menu_1_1_graphics_menu.html", "class_menu_1_1_graphics_menu" ],
    [ "HostMenu", "class_menu_1_1_host_menu.html", "class_menu_1_1_host_menu" ],
    [ "HwrMenu", "class_menu_1_1_hwr_menu.html", "class_menu_1_1_hwr_menu" ],
    [ "InGameChat", "class_menu_1_1_in_game_chat.html", "class_menu_1_1_in_game_chat" ],
    [ "InGameNotifier", "class_menu_1_1_in_game_notifier.html", "class_menu_1_1_in_game_notifier" ],
    [ "IntroMenu", "class_menu_1_1_intro_menu.html", "class_menu_1_1_intro_menu" ],
    [ "JoiningLobbyMenu", "class_menu_1_1_joining_lobby_menu.html", "class_menu_1_1_joining_lobby_menu" ],
    [ "LobbyPlayersMenu", "class_menu_1_1_lobby_players_menu.html", "class_menu_1_1_lobby_players_menu" ],
    [ "Menu", "class_menu_1_1_menu.html", "class_menu_1_1_menu" ],
    [ "MultiplayerMenu", "class_menu_1_1_multiplayer_menu.html", "class_menu_1_1_multiplayer_menu" ],
    [ "OptionsMenu", "class_menu_1_1_options_menu.html", "class_menu_1_1_options_menu" ],
    [ "ResolutionsMenu", "class_menu_1_1_resolutions_menu.html", "class_menu_1_1_resolutions_menu" ],
    [ "SimpleMenu", "class_menu_1_1_simple_menu.html", "class_menu_1_1_simple_menu" ],
    [ "SingleplayerMenu", "class_menu_1_1_singleplayer_menu.html", "class_menu_1_1_singleplayer_menu" ],
    [ "SlotsMenu", "class_menu_1_1_slots_menu.html", "class_menu_1_1_slots_menu" ],
    [ "SoundMenu", "class_menu_1_1_sound_menu.html", "class_menu_1_1_sound_menu" ],
    [ "SplitscreenMenu", "class_menu_1_1_splitscreen_menu.html", "class_menu_1_1_splitscreen_menu" ],
    [ "SplitscreenOptionsMenu", "class_menu_1_1_splitscreen_options_menu.html", "class_menu_1_1_splitscreen_options_menu" ],
    [ "SplitscreenPlayer", "class_menu_1_1_splitscreen_player.html", "class_menu_1_1_splitscreen_player" ],
    [ "SubOptionsMenu", "class_menu_1_1_sub_options_menu.html", "class_menu_1_1_sub_options_menu" ],
    [ "TestMenu", "class_menu_1_1_test_menu.html", "class_menu_1_1_test_menu" ]
];