HoHDocs: Platform Namespace Reference
Platform Namespace Reference
Classes
class CursorInfo
Functions
void Initialize ()
void HideCursor ()
void ShowCursor ()
vec2 GetMousePosition ()
int GetInputCount ()
GameInput GetGameInput (int index)
MenuInput GetMenuInput (int index)
int GetSessionCount ()
array< ivec2 > GetResolutions ()
array< LanguageInfo > GetLanguages ()
void OpenUrl (const string &in url)
ButtonState GetKeyState (int button)
array< ScenarioInfo@> GetAllScenarios ()
ScenarioInfo GetScenario (const string &in id)
ScenarioInfo GetScenario (uint32 id)
array< ResourceMod@> GetAllResourceMods ()
ResourceMod GetResourceMod (const string &in id)
ResourceMod GetResourceMod (uint32 id)
Variables
class Platform::CursorInfo CursorNormal
CursorInfo CursorColorable
CursorInfo CursorHover
CursorInfo CursorCaret
CursorInfo CursorAimNormal
array< CursorInfo@> CursorStack
Function Documentation
GetAllResourceMods()
array<ResourceMod@> Platform::GetAllResourceMods ()
Definition at line 327 of file engine.as.
Referenced by Menu::EditSlotMenu::Initialize().
 { return null; }
GetAllScenarios()
array<ScenarioInfo@> Platform::GetAllScenarios ()
Definition at line 323 of file engine.as.
 { return null; }
GetGameInput()
GameInput Platform::GetGameInput (int index)
Definition at line 310 of file engine.as.
Referenced by MainMenu::InstantiateMice(), and Menu::SplitscreenPlayer::SplitscreenPlayer().
 { return null; }
GetInputCount()
int Platform::GetInputCount ()
Definition at line 309 of file engine.as.
Referenced by MainMenu::InstantiateMice().
 { return 0; }
GetKeyState()
ButtonState Platform::GetKeyState (int button)
Definition at line 321 of file engine.as.
 { return ButtonState(); }
GetLanguages()
array<LanguageInfo> Platform::GetLanguages ()
Definition at line 317 of file engine.as.
Referenced by Menu::GameLanguagesMenu::Initialize().
 { return null; }
GetMenuInput()
MenuInput Platform::GetMenuInput (int index)
Definition at line 311 of file engine.as.
Referenced by MainMenu::InstantiateMice(), and Menu::SplitscreenPlayer::SplitscreenPlayer().
 { return null; }
GetMousePosition()
vec2 Platform::GetMousePosition ()
Definition at line 307 of file engine.as.
Referenced by MouseBase::GetPos().
 { return vec2(); }
GetResolutions()
array<ivec2> Platform::GetResolutions ()
Definition at line 315 of file engine.as.
Referenced by Menu::ResolutionsMenu::Initialize().
 { return null; }
GetResourceMod() [1/2]
ResourceMod Platform::GetResourceMod (const string &in id)
Definition at line 328 of file engine.as.
Referenced by Menu::SlotsMenu::RefreshSlots().
 { return null; }
GetResourceMod() [2/2]
ResourceMod Platform::GetResourceMod (uint32 id)
Definition at line 329 of file engine.as.
 { return null; }
GetScenario() [1/2]
ScenarioInfo Platform::GetScenario (const string &in id)
Definition at line 324 of file engine.as.
 { return null; }
GetScenario() [2/2]
ScenarioInfo Platform::GetScenario (uint32 id)
Definition at line 325 of file engine.as.
 { return null; }
GetSessionCount()
int Platform::GetSessionCount ()
Definition at line 313 of file engine.as.
Referenced by MainMenu::MainMenu(), and BaseGameMode::RenderFrame().
 { return 1; }
HideCursor()
void Platform::HideCursor ()
Definition at line 305 of file engine.as.
Referenced by BaseGameMode::BaseGameMode(), CvarHardwareCursor(), BaseGameMode::SetCursorGame(), and BaseGameMode::SetCursorUI().
 { }
Initialize()
void Platform::Initialize ()
Definition at line 32 of file Platform.as.
References CursorAimNormal, CursorCaret, CursorColorable, CursorHover, and CursorNormal.
Referenced by BaseGameMode::BaseGameMode().
     {
         @CursorNormal = CursorInfo(Resources::GetTexture2D("system/cursors/normal.tga"));
         @CursorColorable = CursorInfo(Resources::GetTexture2D("system/cursors/colorable.tga"));
         @CursorHover = CursorInfo(Resources::GetTexture2D("system/cursors/hover.tga"));
         @CursorCaret = CursorInfo(Resources::GetTexture2D("system/cursors/text.tga"), 3, 6);
         @CursorAimNormal = CursorInfo(Resources::GetTexture2D("system/cursors/aim_normal.tga"), 15, 15);
     }
OpenUrl()
void Platform::OpenUrl (const string &in url)
Definition at line 319 of file engine.as.
Referenced by Menu::FrontMenu::OnFunc().
 { }
ShowCursor()
void Platform::ShowCursor ()
Definition at line 306 of file engine.as.
Referenced by CvarHardwareCursor(), and BaseGameMode::SetCursorUI().
 { }
Variable Documentation
CursorAimNormal
CursorInfo Platform::CursorAimNormal
Definition at line 28 of file Platform.as.
Referenced by Initialize(), and BaseGameMode::SetCursorGame().
CursorCaret
CursorInfo Platform::CursorCaret
Definition at line 27 of file Platform.as.
Referenced by Initialize(), and TextInputWidget::Load().
CursorColorable
CursorInfo Platform::CursorColorable
Definition at line 25 of file Platform.as.
Referenced by MenuMouse::GetCursor(), and Initialize().
CursorHover
CursorInfo Platform::CursorHover
Definition at line 26 of file Platform.as.
Referenced by Initialize().
CursorNormal
class Platform::CursorInfo Platform::CursorNormal
Referenced by BaseGameMode::BaseGameMode(), Initialize(), and BaseGameMode::SetCursorUI().
CursorStack
array<CursorInfo@> Platform::CursorStack
Definition at line 30 of file Platform.as.