HoHDocs: Modifiers Namespace Reference
Modifiers Namespace Reference
Classes
class Armor
class ArmorPierce
class Aura
class AuraCone
class Block
class BlockProjectile
class Buff
class BuffImmune
class BuffScaling
class CleaveRange
class Combo
class CriticalHit
class CriticalHitTrigger
class CriticalMul
class Damage
class EnemyTypeFilter
class Evade
class Experience
class FlameShield
class GoldGain
class HealthFilter
class HealthGain
class KeyGain
class Lifestealing
class ManaFromDamageTaken
class ManaGain
class Markham
class MoveFilter
class OreGain
class PlayerBarrier
class Potion
class RandomBuff
class Regen
class SealOfMana
class SealOfMartyr
class Speed
class SpellCost
class Stats
class StatsBase
class Tax
class Thorns
class TriggerEffect
class UnlethalDamage
class WarlockCleaverModifier
class Windscale
Enumerations
enum EffectTrigger {
Hit, SpellHit, Hurt, Kill,
Attack, CastSpell, DrinkPotion, CriticalHit,
Evade, Collide
}
Functions
enum Modifiers::EffectTrigger LoadModifiers (UnitPtr owner, SValue &params, string prefix="", Modifiers::SyncVerb verb=Modifiers::SyncVerb::None, uint verbId=0)
ModifierList LoadModifiersList (UnitPtr owner, SValue &params, string prefix="")
EffectTrigger ParseEffectTrigger (string trigger)
Variables
enum Modifiers::EffectTrigger None
enum Modifiers::EffectTrigger Item
enum Modifiers::EffectTrigger Set
enum Modifiers::EffectTrigger Drink
enum Modifiers::EffectTrigger Passive
enum Modifiers::EffectTrigger Wish
Enumeration Type Documentation
EffectTrigger
enum Modifiers::EffectTrigger
Enumerator
Hit
SpellHit
Hurt
Kill
Attack
CastSpell
DrinkPotion
CriticalHit
Evade
Collide
Definition at line 3 of file Modifiers.as.
     {
         None,
         Hit,
         SpellHit,
         Hurt,
         Kill,
         Attack,
         CastSpell,
         DrinkPotion,
         CriticalHit,
         Evade,
         Collide
     }
Function Documentation
LoadModifiers()
enum Modifiers::EffectTrigger Modifiers::LoadModifiers (UnitPtr owner, SValue & params, string prefix = "", Modifiers::SyncVerb verb = Modifiers::SyncVerb::None, uint verbId = 0)
Definition at line 29 of file Modifiers.as.
References modifiers.
Referenced by ActorBuffDef(), ActorItems::AddItemFile(), ActorItems::AddSetFile(), Fountain::AddWishFile(), Skills::BuffAoe::BuffAoe(), Skills::ExtendedDomain::ExtendedDomain(), Skills::PassiveSkill::Initialize(), LoadModifiersList(), Upgrades::ModifierUpgradeStep::ModifierUpgradeStep(), opCmp(), Statues::StatueLevelDef(), Skills::TempBuffAoe::TempBuffAoe(), and Titles::TitleList::TitleList().
     {
         array<Modifier@> modifiers;
         array<SValue@>@ datArr = GetParamArray(owner, params, prefix + "modifiers", false);
         if (datArr !is null)
         {
             for (uint i = 0; i < datArr.length(); i++)
             {
                 string c = GetParamString(owner, datArr[i], "class");
                 auto mod = cast<Modifier>(InstantiateClass(c, owner, datArr[i]));
                 if (mod !is null)
                 {
                     mod.Initialize(verb, verbId, i);
                     modifiers.insertLast(mod);
                 }
             }
         }
         else
         {
             SValue@ dat = GetParamDictionary(owner, params, prefix + "modifier", false);
             if (dat !is null)
             {
                 string c = GetParamString(owner, dat, "class");
                 auto mod = cast<Modifier>(InstantiateClass(c, owner, dat));
                 if (mod !is null)
                 {
                     mod.Initialize(verb, verbId, 0);
                     modifiers.insertLast(mod);
                 }
             }
         }
         return modifiers;
     }
LoadModifiersList()
ModifierList Modifiers::LoadModifiersList (UnitPtr owner, SValue & params, string prefix = "")
Definition at line 65 of file Modifiers.as.
References LoadModifiers().
Referenced by TownBuilding::LoadTweakData(), and Titles::Title::Title().
     {
         return ModifierList(LoadModifiers(owner, params, prefix));
     }
ParseEffectTrigger()
EffectTrigger Modifiers::ParseEffectTrigger (string trigger)
Definition at line 70 of file Modifiers.as.
References Attack, CastSpell, Collide, CriticalHit, DrinkPotion, Evade, Hit, Hurt, Kill, None, and SpellHit.
Referenced by Skills::Shatter::Shatter(), and Modifiers::TriggerEffect::TriggerEffect().
     {
         if (trigger == "hit")
             return EffectTrigger::Hit;
         else if (trigger == "spellhit")
             return EffectTrigger::SpellHit;
         else if (trigger == "hurt")
             return EffectTrigger::Hurt;
         else if (trigger == "kill")
             return EffectTrigger::Kill;
         else if (trigger == "attack")
             return EffectTrigger::Attack;
         else if (trigger == "castspell")
             return EffectTrigger::CastSpell;
         else if (trigger == "drinkpotion" || trigger == "potion")
             return EffectTrigger::DrinkPotion;
         else if (trigger == "criticalhit" || trigger == "crit")
             return EffectTrigger::CriticalHit;
         else if (trigger == "evade" || trigger == "dodge")
             return EffectTrigger::Evade;
         else if (trigger == "collide")
             return EffectTrigger::Collide;
         return EffectTrigger::None;
     }
Variable Documentation
Drink
enum Modifiers::EffectTrigger Modifiers::Drink
Referenced by PlayerHandler::ModifierTriggerEffect(), and opCmp().
Item
enum Modifiers::EffectTrigger Modifiers::Item
None
Modifiers::None
Definition at line 5 of file Modifiers.as.
Passive
enum Modifiers::EffectTrigger Modifiers::Passive
Referenced by Skills::PassiveSkill::Initialize(), and PlayerHandler::ModifierTriggerEffect().
Set
enum Modifiers::EffectTrigger Modifiers::Set
Referenced by ActorItems::AddSetFile(), MainMenu::LobbyCreated(), PlayerHandler::ModifierTriggerEffect(), Menu::FrontMenu::OnFunc(), PlayerMenu::SetTab(), GuildHallMenu::SetTab(), Menu::SkinInput(), Campaign::Start(), and Campaign::UpdateFrame().
Wish
enum Modifiers::EffectTrigger Modifiers::Wish
Referenced by Fountain::AddWishFile(), and PlayerHandler::ModifierTriggerEffect().