HoHDocs: Statues Namespace Reference
Statues Namespace Reference
Classes
class StatueDef
Functions
StatueLevelDef (SValue@ sval)
void EnableModifiers ()
void DisableModifiers ()
int GetPlacedLevel (string id)
StatueDef GetStatue (string id)
StatueLevelDef GetStatue (string id, int level)
void LoadStatues ()
Variables
class Statues::StatueDef m_name
string m_desc
int m_sculptCost
UnitScene m_scene
array< vec4 > m_colors
Modifiers::ModifierList m_modifiers
Function Documentation
DisableModifiers()
void Statues::DisableModifiers ()
Definition at line 70 of file StatueDef.as.
References g_allModifiers, and m_modifiers.
Referenced by Campaign::RefreshTownModifiers().
         {
             if (m_modifiers !is null)
                 g_allModifiers.Remove(m_modifiers);
         }
EnableModifiers()
void Statues::EnableModifiers ()
Definition at line 64 of file StatueDef.as.
References g_allModifiers, and m_modifiers.
         {
             if (m_modifiers !is null)
                 g_allModifiers.Add(m_modifiers);
         }
GetPlacedLevel()
int Statues::GetPlacedLevel (string id)
Definition at line 86 of file StatueDef.as.
References g_gameMode.
     {
         auto gm = cast<Campaign>(g_gameMode);
         int placement = gm.m_town.GetStatuePlacement(id);
         if (placement == -1)
             return 0;
         auto statue = gm.m_town.GetStatue(id);
         if (statue is null)
         {
             PrintError("Coulnd't find statue with ID \"" + id + "\"");
             return 0;
         }
         return statue.m_level;
     }
GetStatue() [1/2]
StatueDef Statues::GetStatue (string id)
Definition at line 104 of file StatueDef.as.
References g_statues, and m_id.
Referenced by TownStatue::GetDef(), and GetStatue().
     {
         for (uint i = 0; i < g_statues.length(); i++)
         {
             if (g_statues[i].m_id == id)
                 return g_statues[i];
         }
         return null;
     }
GetStatue() [2/2]
StatueLevelDef Statues::GetStatue (string id, int level)
Definition at line 114 of file StatueDef.as.
References GetStatue().
     {
         auto def = GetStatue(id);
         if (def is null)
         {
             PrintError("Couldn't find statue with ID \"" + id + "\"");
             return null;
         }
         return def.GetLevel(level);
     }
LoadStatues()
void Statues::LoadStatues ()
Definition at line 125 of file StatueDef.as.
References g_statues.
Referenced by Campaign::Campaign().
     {
         auto sv = Resources::GetSValue("tweak/statues.sval");
         auto keys = sv.GetDictionary().getKeys();
         for (uint i = 0; i < keys.length(); i++)
             g_statues.insertLast(StatueDef(keys[i], sv.GetDictionaryEntry(keys[i])));
     }
StatueLevelDef()
Statues::StatueLevelDef (SValue@ sval)
Definition at line 40 of file StatueDef.as.
References Modifiers::LoadModifiers(), m_colors, m_desc, m_modifiers, m_name, m_scene, and m_sculptCost.
Referenced by StatuesShopMenuContent::RefreshPlacementList(), and Statues::StatueDef::StatueDef().
         {
             m_name = GetParamString(UnitPtr(), sval, "name");
             m_desc = GetParamString(UnitPtr(), sval, "desc");
             m_sculptCost = GetParamInt(UnitPtr(), sval, "sculpt-cost");
             auto prod = Resources::GetUnitProducer(GetParamString(UnitPtr(), sval, "unit"));
             @m_scene = prod.GetUnitScene(GetParamString(UnitPtr(), sval, "scene"));
             auto colors = GetParamArray(UnitPtr(), sval, "colors");
             for (uint i = 0; i < colors.length(); i++)
                 m_colors.insertLast(colors[i].GetVector4());
             auto arrModifiers = Modifiers::LoadModifiers(UnitPtr(), sval);
             if (arrModifiers.length() > 0)
             {
                 @m_modifiers = Modifiers::ModifierList(arrModifiers);
                 dictionary params = { { "statue", Resources::GetString(m_name) } };
                 m_modifiers.m_name = Resources::GetString(".modifier.list.statue", params);
             }
         }
Variable Documentation
m_colors
array<vec4> Statues::m_colors
Definition at line 36 of file StatueDef.as.
Referenced by StatueLevelDef().
m_desc
string Statues::m_desc
Definition at line 31 of file StatueDef.as.
Referenced by StatueLevelDef().
m_modifiers
Modifiers::ModifierList Statues::m_modifiers
Definition at line 38 of file StatueDef.as.
Referenced by DisableModifiers(), EnableModifiers(), and StatueLevelDef().
m_name
class Statues::StatueDef Statues::m_name
Referenced by StatueLevelDef().
m_scene
UnitScene Statues::m_scene
Definition at line 35 of file StatueDef.as.
Referenced by StatueLevelDef().
m_sculptCost
int Statues::m_sculptCost
Definition at line 33 of file StatueDef.as.
Referenced by StatueLevelDef().